### ISSUE TITLE
SMP - Delete submission

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#10]
Does not work because, according to the winning submission:
> - there's no endpoint for deleting a specific submission (`/challenges/{id}/resources` in v3 doesn't work either)

**Comment by birdofpreyru** [comment]
@ajefts Any chance to get this working soon? Probably, it is already supported, just not well documented?

**Comment by ajefts** [comment]
@birdofpreyru It's actually not in v3 yet.  Here is the task for that one:  https://github.com/appirio-tech/ap-submission-microservice/issues/28

**Comment by skyhit** [comment]
@ajefts @birdofpreyru I am going to get this implemented.

**Comment by birdofpreyru** [comment]
UPDATE: For now, until we get backend API ready, the delete submission icon has been hidden in SMP (https://github.com/topcoder-platform/community-app/commit/960680269eb4de2f173954d5b48755dd872ec21b)

**Comment by birdofpreyru** [comment]
Delete submission functionality is added in https://github.com/topcoder-platform/community-app/commit/0dc601b9791fb11b75fdce068908a3349e5648b5
