### ISSUE TITLE
Chrome –Payment Preference  –Application just navigating to Account section without any confirmation message , If user click “Wester Union” Radio button ->save butt

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1000]
Summary:
Chrome –Payment Preference  –Application just navigating to Account section without any confirmation message , If user click “Wester Union” Radio button ->save button
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click “Payment Preference”
3.	Click Western Union radio button
4.	Click Save button
### Expected Result ###
Chrome –Payment Preference  –Application should not navigating to Account section without any confirmation message , 
Should show some confirmation message as setting saved
### Actual  Result ##
Chrome –Payment Preference  –Application just navigating to Account section without any confirmation message , If user click “Wester Union” Radio button ->save button
.
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41188065-97f0a66e-6bd5-11e8-9890-928c7086bc0f.png)
![image](https://user-images.githubusercontent.com/31862600/41188068-a4ed0024-6bd5-11e8-95b1-0a57b4639625.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
