### ISSUE TITLE
user should stay on the same page or PREFERENCES page after saving payment preferences

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1001]
### Reported URL ###

https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. enter the payment accrual amount as 234, click Save

### Expected Result ###
user should stay on the same page or go to PREFERENCES tab.

### Actual Result ###

See screenshot, it will go to ACCOUNT tab

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Safari Version 11.1 (13605.1.33.1.4)*

**Comment by winterflame** [comment]
<img width="822" alt="234" src="https://user-images.githubusercontent.com/4590317/41188079-ba057c24-6bea-11e8-9a12-91ebb88d9fbd.png">

<img width="1198" alt="account" src="https://user-images.githubusercontent.com/4590317/41188080-c100c0c4-6bea-11e8-9d94-126bfdd1fefa.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
That's part of the legacy page and not the community app
