### ISSUE TITLE
error message should be in different color (e.g. red)

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1002]
### Reported URL ###

https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. enter an invalid email as PayPal account, click Save

### Expected Result ###

error message should be in different color (e.g. red)

### Actual Result ###

See screenshot, it will go to ACCOUNT tab

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Safari Version 11.1 (13605.1.33.1.4)*

**Comment by winterflame** [comment]
<img width="732" alt="va" src="https://user-images.githubusercontent.com/4590317/41188117-86a62e04-6beb-11e8-96e7-3bac9ec2047a.png">

**Comment by winterflame** [comment]
Also, if the payment method is not PayPal, we don't need to validate this field.

**Comment by winterflame** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
This is part of the legacy page not the community app.
