### ISSUE TITLE
[$15] Chrome –members  –Idea Generation “0 wins” is not getting displayed in summary view

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1003]
Summary:
Chrome –members  –Idea Generation “0 wins” is not getting displayed in summary view
### Reported URL ###
https://www.topcoder-dev.c

### Reported URL ###
https://www.topcoder-dev.com/om/members/iamtong/details/?track=DESIGN&subTrack=IDEA_GENERATION
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/members/iamtong/details/?track=DESIGN&subTrack=IDEA_GENERATION
2.	Click Small menu
3.	View the idea generation win count
### Expected Result ###
Chrome –members  –Idea Generation “0 wins” should get displayed in summary view
### Actual  Result ##
Chrome –members  –Idea Generation “0 wins” is not getting displayed in summary view
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41188566-054b1da0-6bdd-11e8-8abe-9a3028e5f267.png)
![image](https://user-images.githubusercontent.com/31862600/41188571-14a29710-6bdd-11e8-9c93-069e430fa48b.png)

**Comment by youdare** [comment]
Note:- If challenges o wins , we are seeing above issue ,
This issue is there in all challenge if the win rate is zero

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069497 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069497 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
done in https://github.com/topcoder-platform/community-app/pull/1188, pls check, thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069497 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069497
