### ISSUE TITLE
debug info in the console should be removed

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1004]
### Reported URL ###

https://www.topcoder-dev.com/settings/preferences/
https://apps.topcoder-dev.com/forums/?module=Settings
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. randomly browse https://www.topcoder-dev.com/settings/preferences/ , https://apps.topcoder-dev.com/forums/?module=Settings and other pages

3. check the console log

### Expected Result ###

debug info in the console should be removed

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Google Chrome - Version 67.0.3396.62 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
<img width="1434" alt="log" src="https://user-images.githubusercontent.com/4590317/41189782-c7628676-6c05-11e8-837b-bceb5f4d5379.png">

<img width="1370" alt="log2" src="https://user-images.githubusercontent.com/4590317/41189786-de97f18c-6c05-11e8-8f9d-05401864403a.png">

Also there are some errors should be handled properly.

**Comment by winterflame** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
