### ISSUE TITLE
hovering on the track type should not show a hand cursor

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1007]
### Reported URL ###

https://www.topcoder-dev.com/members/pshah_manager/

### Reproduction Steps ###

1. login as pshah_manager

2. go to https://www.topcoder-dev.com/members/pshah_manager/

3. move the cursor to the track type (DESIGNER in this case)

4. it changes to a hand cursor, click on it

### Expected Result ###

Should not show a hand cursor if it is not clickable.

### Actual Result ###

See screenshot

### Screenshots ###
<img width="1368" alt="hover" src="https://user-images.githubusercontent.com/4590317/41199603-503027bc-6cc7-11e8-8048-c3b74a210d65.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by ThomasKranitsas** [comment]
Not valid issue
