### ISSUE TITLE
web links should be synchronized between user profile management page and user profile page

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1008]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
https://www.topcoder-dev.com/members/pshah_manager/

### Reproduction Steps ###

1. login as pshah_manager

2. go to https://www.topcoder-dev.com/settings/profile/, add some non existing weblinks

3. go to https://www.topcoder-dev.com/members/pshah_manager/ to check web links section

4. observe

### Expected Result ###

Should remove all invalid web links to keep them consistent.

### Actual Result ###

See screenshots, they're inconsistent.

### Screenshots ###
Profile management page:
<img width="1292" alt="backend" src="https://user-images.githubusercontent.com/4590317/41199652-2bf70518-6cc8-11e8-8eda-8f1378b60590.png">

Profile page:
<img width="1324" alt="frontend" src="https://user-images.githubusercontent.com/4590317/41199654-32d10906-6cc8-11e8-8093-106b5d4b3486.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by ThomasKranitsas** [comment]
Can't reproduce. Must have been fixed
