### ISSUE TITLE
track names are inconsistent between profile setting page and profile display page

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1009]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
https://www.topcoder-dev.com/members/pshah_manager/

### Reproduction Steps ###

1. login as pshah_manager

2. go to https://www.topcoder-dev.com/settings/profile/, select all tracks (DESIGN, DEVELOPMENT and DATA SCIENCE) and save

3. go to https://www.topcoder-dev.com/members/pshah_manager

4. observe the track names on the left side

### Expected Result ###
1. Track names should be consistent
2. If possible, the order should be consistent too.

### Actual Result ###
See screenshots, 
it's DESIGN, DEVELOP, DATA SCIENCE on the setting page, it's DATA SCIENTIST, DESIGNER, DEVELOPER on the profile display page, however the icons are totally the same.

### Screenshots ###
<img width="851" alt="t1" src="https://user-images.githubusercontent.com/4590317/41199755-2566e4dc-6cca-11e8-8ab4-f56358443850.png">

<img width="392" alt="t2" src="https://user-images.githubusercontent.com/4590317/41199756-2596c256-6cca-11e8-9765-d14e0aa6fc30.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by sjbr** [comment]
https://github.com/topcoder-platform/community-app/issues/980

**Comment by winterflame** [comment]
Agree, closed.
