### ISSUE TITLE
[$20] broken profile image is shown for some member

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1010]
### Reported URL ###
https://www.topcoder-dev.com/members/ghostar/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/ghostar/

3. observe

### Expected Result ###
Should not show a broken image.

### Actual Result ###

See screenshots

### Screenshots ###
In Firefox:
<img width="1406" alt="ff" src="https://user-images.githubusercontent.com/4590317/41199830-a9a970b0-6ccb-11e8-8b02-cad6323ce03c.png">

In Chrome:
<img width="1435" alt="chrome" src="https://user-images.githubusercontent.com/4590317/41199831-b1539eda-6ccb-11e8-966d-64025c60c230.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)* and *Google Chrome - Version 67.0.3396.62 (Official Build) (64-bit)*

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069481 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069481 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas : Can you assign me this ticket, I'm going to work on it.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069481 has been updated - it has been assigned to diazz.

**Comment by suppermancool** [comment]
i don't know why but look like the image doesn't exist in this case it is:
https://topcoder-dev-media.s3.amazonaws.com/member/profile/Ghostar-12345.jpg

@ThomasKranitsas in this case can i display default image if the image is broken?

**Comment by ThomasKranitsas** [comment]
yes, default image sounds good

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069481
