### ISSUE TITLE
active challenges count is shown twice

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1012]
### Reported URL ###
https://www.topcoder-dev.com/members/ghostar/details/?track=COPILOT&subTrack=COPILOT

### Reproduction Steps ###

1. login as pshah_manager

2. go to https://www.topcoder-dev.com/members/ghostar/details/?track=COPILOT&subTrack=COPILOT , observe the ACTIVE CHALLENGES count

### Expected Result ###
No need to show ACTIVE CHALLENGES twice, if they are the same thing.

### Actual Result ###

See screenshot, one is 39, the other is 43.

### Screenshots ###
<img width="1335" alt="3" src="https://user-images.githubusercontent.com/4590317/41199904-f7e7fa0c-6ccc-11e8-8063-27bc316e25ca.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
This has been removed
