### ISSUE TITLE
UE is inconsistent for the PayPal email validation

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1013]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. go to https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. clear the input of two text boxes, select PayPal as Payment method

4. click Save button, observe

5. close the modal, fill in a valid email address in the field, click Save again, observe

### Expected Result ###
Validation error should be presented on the page, not the popup modal.

### Actual Result ###

See screenshots, for other fields, validation error message is not on the popup modal.

### Screenshots ###
<img width="1060" alt="u1" src="https://user-images.githubusercontent.com/4590317/41202319-0be106f2-6cfa-11e8-82ca-58de603d4b77.png">

<img width="764" alt="u2" src="https://user-images.githubusercontent.com/4590317/41202320-0c19c898-6cfa-11e8-9f31-68d9abd956fe.png">

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Google Chrome - Version 67.0.3396.62 (Official Build) (64-bit)*

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
That's part of the legacy site not the community app. Closing the ticket
