### ISSUE TITLE
'How to request  visa letter?' not working.

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1014]
@ThomasKranitsas  'How to request  visa letter?' link-button 
![screenshot from 2018-06-10 20-38-47](https://user-images.githubusercontent.com/18382400/41203601-19689e6e-6cf7-11e8-8aaa-af939496f838.png)
in 'Request a Visa Letter' not working.

**Comment by ThomasKranitsas** [comment]
That's part of the legacy page not the community app. Closing the ticket
