### ISSUE TITLE
'User Avatar' image is showing in Preferences - PD - Member - Migration- BLOCKER

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1015]
@ThomasKranitsas 
'User Avatar' in any of the modules of 'PREFERENCES' tag is broken. 
![screenshot from 2018-06-10 20-50-33](https://user-images.githubusercontent.com/18382400/41203687-40efde1a-6cf8-11e8-8786-9255b4243fe2.png)

**Comment by ThomasKranitsas** [comment]
This is not a blocker issue

**Comment by ThomasKranitsas** [comment]
Not a valid issue
