### ISSUE TITLE
Tabs on 'Forums' Module of PREFERENCES are not correct - PD - Member - Migration - MINOR

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1016]
Tabs on 'Forums' Module of PREFERENCES are not correct, only edges are shown. @ThomasKranitsas 
![screenshot from 2018-06-10 20-32-36](https://user-images.githubusercontent.com/18382400/41203730-c7bc67c4-6cf8-11e8-8a7d-ceb8ccbf5bdf.png)

**Comment by ThomasKranitsas** [comment]
that's part of the legacy page and not the community app
