### ISSUE TITLE
 CHALLENGE DETAILS FAILS TO SHOW - PD - Member - Migration - MAJOR

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1024]
@ThomasKranitsas 
Many a times CHALLENGE DETAILs of a member profiles doesn't show any result
![screenshot from 2018-06-11 00-24-20](https://user-images.githubusercontent.com/18382400/41205264-f697196c-6d0d-11e8-8755-3baae3a24168.png)

**Comment by sjbr** [comment]
https://github.com/topcoder-platform/community-app/issues/980

**Comment by psharneja** [comment]
Those aren't same

**Comment by ThomasKranitsas** [comment]
Duplicate of #973
