### ISSUE TITLE
NO VALIDATION for Paypal email in payments option - PD - Member - Migration - MAJOR

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1025]
@ThomasKranitsas 
NO VALIDATION for Paypal email in payments option, even spaces and special characters are allowed and GETS SAVED,  also when actually i have not even selected paypal as a method of payment
![screenshot from 2018-06-11 00-32-32](https://user-images.githubusercontent.com/18382400/41205332-22e82fe6-6d0f-11e8-9050-c8f217438673.png)

**Comment by ThomasKranitsas** [comment]
That is part of the legacy page and not the community app. Closing this ticket.
