### ISSUE TITLE
Profile -> Can't scroll to the bottom of page for some users

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#1026]
# Reported URL
https://www.topcoder-dev.com/members/testmember1/

# Reproduction Steps
1. Go to https://www.topcoder-dev.com/members/testmember1/
2. Scroll to the bottom of screen using mouse scroll or use the scroll bar
3. The page flickers and doesn't stay at the bottom when browser window is maximized

# Expected Result
Page scrolling should work and the user should be able to see the page footer

# Actual Result
Page flickers and doesn't stay at the bottom

# Video
Video zip:
[2018-06-10 15-07-38.zip](https://github.com/topcoder-platform/community-app/files/2088236/2018-06-10.15-07-38.zip)

Youtube link:
https://youtu.be/PTQBwsX76vo

Issue Information
Device: Desktop
OS: Windows 10
Browser: Chrome  67.0.3396.79 (Official Build) (64-bit)
Resolution: 1920 x 1980
Frequency: Always

**Comment by sjbr** [comment]
Also works with keyboard button Page Down

**Comment by sjbr** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
I can't reproduce that
