### ISSUE TITLE
Chrome-Application is throwing error message as “There was an error uploading Profile Image. Please Try again” while uploading invalid image type 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1027]
1. Summary:
Chrome-Application is throwing error message as “There was an error uploading Profile Image. Please Try again” while uploading invalid image type 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Click Change Image 
3.Try to upload PDF or Excel File

### Actual  Result ###
Chrome-Application is throwing error message as “There was an error uploading Profile Image. Please Try again” while uploading invalid image type 
## Expected Result ###
Chrome-Application should throw error message as “Please upload only JPEG, GIF or PNG File ” while uploading invalid image type 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214636-f54358c6-6d69-11e8-972a-09ce85cc8a44.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Enhancement

**Comment by ThomasKranitsas** [comment]
duplicate
