### ISSUE TITLE
Chrome-Need to show uploading symbol or Uploading message, While uploading profile picture

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1028]
2. Summary:
Chrome-Need to show uploading symbol or Uploading message, While uploading profile picture
Note:- My net speed gone down and uploading a big file, Need to wait 20 second, No Message to user saying InProgress 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Click Change Image 
3.Try to upload Big Image File

### Actual  Result ###
Chrome-Application is not show uploading symbol or Uploading message, While uploading profile picture
## Expected Result ###
Chrome-Need to show uploading symbol or Uploading message, While uploading profile picture
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214662-1ad17bc2-6d6a-11e8-9235-45fb6a3c3259.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Enhancement

**Comment by ThomasKranitsas** [comment]
This has been fixed in the latest version
