### ISSUE TITLE
[$20] Chrome-Able to add same website in the “Linked Account”, By one with Lower case and Another one in upper case

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1029]
3. Summary:
Chrome-Able to add same website in the “Linked Account”, By one with Lower case and Another one in upper case
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Go to ADD A Web Link Section
3.Enter www.google.com and Click “ADD” button
4.Again Go to ADD A Web Link Section
5.Enter WWW.GOOGLE.COM and Click “ADD button
6. Go to Linked Account section and Observe
### Actual  Result ###
Chrome-Should not allow to add same website in the “Linked Account”, By one with Lower case and Another one in upper case
## Expected Result ###
Chrome-Able to add same website in the “Linked Account”, By one with Lower case and Another one in upper case
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214677-30950820-6d6a-11e8-80f3-0d344d814475.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
It shouldn't allow duplicate entries

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069502 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069502 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas can you assign to me

**Comment by suppermancool** [comment]
fixed in https://github.com/topcoder-platform/community-app/pull/1186, pls check , thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069502 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069502
