### ISSUE TITLE
Chrome-Forum Preference - Clicking on save button will move the tabs to general setting.  

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1030]
4. Summary:
Chrome-Forum Preference - Clicking on save button will move the tabs to general setting.  
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/preferences/
2. Click Forum Preference.
3.GO to Rating preference and Click “No” option in the show rating
4.Click Save button
### Actual  Result ###
Chrome-Forum Preference - Clicking on save button should not move the tabs to general setting. 
Should be same section where we save 
## Expected Result ###
Chrome-Forum Preference - Clicking on save button will move the tabs to general setting.  
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214706-5fa8a39c-6d6a-11e8-92fc-7655f05f675e.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
