### ISSUE TITLE
Chrome-Forum Preference – When Collapse read message check box is unchecked, Application should disable the dropdown selection of Collapse read message

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1031]
5. Summary:
Chrome-Forum Preference – When Collapse read message check box is unchecked, Application should disable the dropdown selection of Collapse read message
Note;- Do not collapse posts with new replies check box is getting disabled, only issue is with drop down box
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/preferences/
2. Click Forum Preference.
3.GO to “General Setting”
4.Go to Collapse read message section
5. Uncheck the Collapse read message check box
### Actual  Result ###
Chrome-Forum Preference – When Collapse read message check box is unchecked, Application should disable the dropdown selection of Collapse read message
## Expected Result ###
Chrome-Forum Preference – When Collapse read message check box is unchecked, Application is not disabling the dropdown selection of Collapse read message
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214754-94a5b60c-6d6a-11e8-9303-2f9b7fa5d229.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
