### ISSUE TITLE
Chrome-Forum Preference – In My Watches, Category Forum names should be hyperlinked and Last Post Header should be center aligned

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1032]
6. Summary:
Chrome-Forum Preference – In My Watches, Category Forum names should be hyperlinked and Last Post Header should be center aligned
Note;- Now Header is closely packed with messages.
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/preferences/
2. Click Forum Preference.
3.GO to “My Watches”
4.Obsevre the UI
### Actual  Result ###
Chrome-Forum Preference – In My Watches, Category Forum names should be hyperlinked and Last Post Header should be center aligned
## Expected Result ###
Chrome-Forum Preference – In My Watches, Category Forum names is not hyperlinked and Last Post Header is not center aligned
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214778-b0e2f5f0-6d6a-11e8-9dc8-b8c72398c3e5.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Enhancement

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
