### ISSUE TITLE
Chrome-Forum Preference – Update button should be center aligned below the Watched Software Forums.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1033]
7. Summary:
Chrome-Forum Preference – Update button should be center aligned below the Watched Software Forums.
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/preferences/
2. Click Forum Preference.
3.Observe the Update button
### Actual  Result ###
Chrome-Forum Preference – Update button is not center aligned below the Watched Software Forums.
## Expected Result ###
Chrome-Forum Preference – Update button should be center aligned below the Watched Software Forums.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214805-c99b2c66-6d6a-11e8-8cbe-8c25f188ff07.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
