### ISSUE TITLE
Chrome-Forum Preference – My Post History rating is always in +0/-0, Ratting is not getting reflected.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1034]
8. Summary:
Chrome-Forum Preference – My Post History rating is always in +0/-0, Ratting is not getting reflected.
### Reproduction Steps ###
Precondition- Create some Forum, Start Editing , Reply to the Forums ects…
1. Go to  https://www.topcoder-dev.com/settings/preferences/
2. Click Forum Preference.
3.Go to My Post History tab
4.View the ratting column 
### Actual  Result ###
Chrome-Forum Preference – My Post History rating is always in +0/-0, Ratting is not getting reflected.
## Expected Result ###
Chrome-Forum Preference – My Post History rating should not be +0/-0, Ratting should be reflected.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214813-dd7cee04-6d6a-11e8-8386-c5a04a098c9b.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
