### ISSUE TITLE
Chrome-Members – Page is moving up and down automatically while clicking “Developer” , Data scientist” and Copilot” icons from member page.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1035]
9. Summary:
Chrome-Members – Page is moving up and down automatically while clicking “Developer” , Data scientist” and Copilot” icons from member page.
### Reproduction Steps ###
Precondition- Create some Forum, Start Editing , Reply to the Forums ects…
1. Go to  https://www.topcoder-dev.com/members/wendell/
2. Click “Developer” , Data scientist” and Copilot” icons from member page.(Repeat This Step 2 or 3 Time)
### Actual  Result ###
Chrome-Members – Page is moving up and down automatically while clicking “Developer” , Data scientist” and Copilot” icons from member page.
## Expected Result ###
Chrome-Members – Page should not move up and down automatically while clicking “Developer” , Data scientist” and Copilot” icons from member page.
While clicking application should navigate to correct page or Remove the click event
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214832-f62fa7f2-6d6a-11e8-8466-0f85ccd34836.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
It was built this way. Not a valid issue
