### ISSUE TITLE
10. Summary: Chrome-Members – Not able to view “Forum Post” from the member page.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1036]
10. Summary:
Chrome-Members – Not able to view “Forum Post” from the member page.
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/
2. Click “FORUM POST” from the member page.
Note:- In Wendel project I have joined and Replied, Even common forum is now shown here
### Actual  Result ###
Chrome-Members – Not able to view “Forum Post” from the member page.
## Expected Result ###
Chrome-Members – Should allow to view “Forum Post” from the member page.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214855-13f3defc-6d6b-11e8-996d-1de779c0465c.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
