### ISSUE TITLE
Chrome-Members – In Member page, short bio text is not fitting inside the content.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1037]
11. Summary:
Chrome-Members – In Member page, short bio text is not fitting inside the content.
### Reproduction Steps ###
1.Log in as pshah_manager/topcoder123
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Go to Short Bio section 
3.Enter
 “iam a Coderrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
in JAVA”
4.Click Save button
5.Go to https://www.topcoder-dev.com/members/pshah_manager/
6.View the content
### Actual  Result ###
Chrome-Members – In Member page, short bio text is not fitting inside the content.
## Expected Result ###
Chrome-Members – In Member page, short bio text should fitting inside the content.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214885-304692de-6d6b-11e8-8527-dc46858fa863.png)
![image](https://user-images.githubusercontent.com/31862600/41214892-3b66602c-6d6b-11e8-9600-5f2976c6eb8c.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Fixed
