### ISSUE TITLE
Chrome-Members – existing added skills icon or images are broken.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1038]
12. Summary:
Chrome-Members – existing added skills icon or images are broken.
### Reproduction Steps ###
1.Log in as pshah_manager/topcoder123
2.Go to https://www.topcoder-dev.com/members/pshah_manager/ ( If you didn’t get expected UI, Please move the mouse towards pshah_manage on the right hand top corner ->Click Setting -> Again Click Profile) 
6.View the Skill Section.
### Actual  Result ###
Chrome-Members – existing added skills icon or images are broken.
## Expected Result ###
Chrome-Members – existing added skills icon or images should display properly.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214920-5a2098ac-6d6b-11e8-92e3-628b5942897f.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
duplicate
