### ISSUE TITLE
[$15] Chrome-Members – getting error message as “Error establishing a database connection” while clicking “Lode More” link in the My Challenge section.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1040]
14. Summary:
Chrome-Members – getting error message as “Error establishing a database connection” while clicking “Lode More” link in the My Challenge section.
### Reproduction Steps ###
1.Log in as pshah_manager/topcoder123
2.Go to https://www.topcoder-dev.com/members/pshah_manager/( If you didn’t get expected UI, please move the mouse towards pshah_manage on the right hand top corner ->Click Setting -> Again Click Profile) 
3.Click “Lode More” link in the My Challenge section.
4.Observe the UI
### Actual  Result ###
Chrome-Members – getting error message as “Error establishing a database connection” while clicking “Lode More” link in the My Challenge section.
## Expected Result ###
Chrome-Members – Should not get message as “Error establishing a database connection” while clicking “Lode More” link in the My Challenge section.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41214967-9703e7f6-6d6b-11e8-9ee6-f7d2e2b6ef12.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
Remove the `Learn more` link.

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069479 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069479 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas can you assign to me

**Comment by suppermancool** [comment]
[screencast 2018-08-15 14-51-35.mp4.zip](https://github.com/topcoder-platform/community-app/files/2289559/screencast.2018-08-15.14-51-35.mp4.zip)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069479 has been updated - it has been assigned to diazz.
