### ISSUE TITLE
Chrome-Members – Summary Grid view not displayed for second time.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1041]
15. Summary:
Chrome-Members – Summary Grid view not displayed for second time.
### Reproduction Steps ###
1.Go to https://www.topcoder-dev.com/members/wendell/
2. Click Design 
3. Click “Grid” View in the design
4.Application display the summary view
5.Close the Summary View by clicking “X” button
6.Again Click “Grid” View in the design

### Actual  Result ###
Chrome-Members – Summary Grid view not displayed for second time.
## Expected Result ###
Chrome-Members – Summary Grid view should be displayed for second time.
### Screenshots ###
https://youtu.be/hTz2FbM-ICo 
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
duplicate

**Comment by youdare** [comment]
Agree
