### ISSUE TITLE
view other members link is broken

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#1042]
### Reproduction Steps ###

1.  go to https://www.topcoder-dev.com/members/pshah_customer/

2. click VIEW OTHER MEMBERS link

3. observe

### Expected Result ###
Should navigate to another page.

### Actual Result ###
It links to https://www.topcoder-dev.com/community/members/undefined/ , which is a dead link.

### Screenshots ###
![b](https://user-images.githubusercontent.com/4590317/41233941-6a27f8ec-6dbd-11e8-8aa8-a495626b2177.png)

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.2*

**Comment by sjbr** [comment]
https://github.com/topcoder-platform/community-app/issues/959
