### ISSUE TITLE
[$0] Skill section is missing in the members profile page

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1043]
1. Summary:
Chrome-Skill section is missing in the members view page
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/
2. Observe the UI

### Actual  Result ###
Skill section is missing in the members view page 
## Expected Result ###
Skill section should present in the members view page 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
Actual:
 
![image](https://user-images.githubusercontent.com/31862600/41250212-e25869da-6dd3-11e8-9bf7-2d721f48beca.png)


Expected:
 
![image](https://user-images.githubusercontent.com/31862600/41250230-ececf550-6dd3-11e8-8b16-c71ec06c4932.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket available for pickup

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069287 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069287 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas i can't assign myself to this ticket or change the label, pls give me permission, thanks

**Comment by suppermancool** [comment]
Right now the server api return empty skill, nothing to do with the client app right now, pls check

https://api.topcoder-dev.com/v3/members/wendell/skills

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069287 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
@suppermancool let me check that.. I may have to do some fixes on the backend first. I'll keep you updated

**Comment by ThomasKranitsas** [comment]
This ticket requires more fixes. I'll open a new ticket

**Comment by Tim15** [comment]
Is this open to work on?

**Comment by ThomasKranitsas** [comment]
I'll probably be after https://github.com/topcoder-platform/community-app/issues/1167 is closed

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069287 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069287 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment]
This works just fine. It's a backend issue in the dev environment. Running it against production works fine.

See screenshot:
<img width="1493" alt="screen shot 2018-08-13 at 20 37 51" src="https://user-images.githubusercontent.com/4612921/44048011-dd3778e2-9f38-11e8-9ded-2cfd6ae53a56.png">

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069287
