### ISSUE TITLE
Chrome- Designer icon or Logo is missing in the profile.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1044]
. Summary:
Chrome- Designer icon or Logo is missing in the profile.
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/
2. Observe the UI

### Actual  Result ###
Chrome- Designer icon or Logo is missing in the profile.
## Expected Result ###
Chrome- Designer icon or Logo should be there in the profile.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
Actual:
 
![image](https://user-images.githubusercontent.com/31862600/41250273-0bc44852-6dd4-11e8-9b5b-39fa72649aa2.png)


Expected:
![image](https://user-images.githubusercontent.com/31862600/41250294-16daa204-6dd4-11e8-8e59-6c2af02e358e.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Not a valid issue
