### ISSUE TITLE
Chrome- Developer,Data Scientist and Copilot icons are getting disappeared if we visit Copilot stats->Overall summary and return back to member page.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1045]
Summary:
Chrome- Developer,Data Scientist and Copilot icons are getting disappeared if we visit Copilot stats->Overall summary and return back to member page.
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/
2. Click Copilot
3.Clik the the Grid and View the summary
4.Now close the summary Grid
5.Click back button , So we can move to member page.

### Actual  Result ###
Chrome- Developer,Data Scientist and Copilot icons are getting disappeared if we visit Copilot stats->Overall summary and return back to member page.
## Expected Result ###
Chrome- Developer,Data Scientist and Copilot icons should not get disappeared if we visit Copilot stats->Overall summary and return back to member page.
### Screenshots ###

https://youtu.be/ELjEW-vsuBo

### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Cannot reproduce. Must have been fixed
