### ISSUE TITLE
Chrome- Design Activity is not getting listed in the Grid Summary View.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1046]
Summary:
Chrome- Design Activity is not getting listed in the Grid Summary View.
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/
2. Click Copilot
3.Clik the Grid and View the summary
4.Obsereve the UI

### Actual  Result ###
Chrome- Design Activity is not getting listed in the Grid Summary View.
## Expected Result ###
Chrome- Design Activity should be listed in the Grid Summary View.
### Screenshots ###
See Comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
Actual:
  
![image](https://user-images.githubusercontent.com/31862600/41250372-54efdf8c-6dd4-11e8-946b-0d9f9d0e1c6a.png)


Expected:
![image](https://user-images.githubusercontent.com/31862600/41250380-5e0a8f36-6dd4-11e8-8abb-7e918c99c996.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Invalid issue
