### ISSUE TITLE
[$40] Chrome- Tool tip prompt is getting displayed in member page , IF we follow the below steps.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1047]
Summary:
Chrome- Tool tip prompt is getting displayed in member page , IF we follow the below steps.
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/members/wendell/details/?track=DATA_SCIENCE&subTrack=SRM
2. Go to Rating History Graph 
3.Click any Graph point (When you get Hand Symbol click)
4.Click Back button in the browser
5.Observe the UI

### Actual  Result ###
Chrome- Tool tip prompt is getting displayed in member page , IF we follow the below steps.
## Expected Result ###
Chrome- Tool tip prompt should not get displayed in member page , IF we follow the below steps.
### Screenshots ###
See Comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41250409-79a1f900-6dd4-11e8-9fc6-9d79981d0eb6.png)

![image](https://user-images.githubusercontent.com/31862600/41250419-80bb946c-6dd4-11e8-843c-29625e04c76e.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket available for pickup

**Comment by suppermancool** [comment]
@ThomasKranitsas can you assign me to this ticket?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069298 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
Sure, it's yours

**Comment by suppermancool** [comment]
@ThomasKranitsas  fixed in https://github.com/topcoder-platform/community-app/pull/1166 pls check

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069298
