### ISSUE TITLE
[$40] Chrome- getting error as “An error occurred.” While clicking graph tool prompt.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1048]
Summary:
Chrome- getting error as “An error occurred.” While clicking graph tool prompt.
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/members/sdgun/details/?track=DEVELOP&subTrack=CONTENT_CREATION
2. Go to Rating History Graph 
3.Click any Graph point (When you get Hand Symbol click)
4.Scroll near the label and click

### Actual  Result ###
Chrome- getting error as “An error occurred.” While clicking graph tool prompt.
## Expected Result ###
Chrome- Should navigate to corresponding challenge.
### Screenshots ###
See Comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41250433-94f17ce4-6dd4-11e8-87e2-fdb725d01f22.png)

![image](https://user-images.githubusercontent.com/31862600/41250456-9f4312ca-6dd4-11e8-9e51-260efc8611de.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069300 has been updated - it has been assigned to gets0ul.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069300
