### ISSUE TITLE
[$20] Chrome- SRM/MARATHON LOGO is missing.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1049]
Summary:
Chrome- SRM/MARATHON LOGO is missing.
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM
2. Observe we have SRM LOGO

### Actual  Result ###
Chrome- SRM/MARATHON LOGO is missing.
## Expected Result ###
Chrome- SRM/MARATHON LOGO should be placed.
### Screenshots ###
See Comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
I believe you can grab the icon from https://github.com/appirio-tech/topcoder-app/ if it's not already in this repo

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069503 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069503 has been updated - the new changes has been updated for this ticket.

**Comment by sandipanghos** [comment]
@ThomasKranitsas please assign me this ticket

**Comment by ThomasKranitsas** [comment]
Should I remove you from the other ticket?

**Comment by sandipanghos** [comment]
yes

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069503 has been updated - it has been assigned to sandipanghosh64.

**Comment by sandipanghos** [comment]
@ThomasKranitsas In the asset folder i cannot find the srm logo

**Comment by sandipanghos** [comment]
@ThomasKranitsas i found the logo

**Comment by sandipanghos** [comment]
@ThomasKranitsas  please review it

**Comment by sandipanghos** [comment]
@ThomasKranitsas please tell why the build failed.issue is fixed
![screenshot from 2018-08-15 05-08-33](https://user-images.githubusercontent.com/16544084/44124749-5f269978-a04c-11e8-8254-2e915d42d446.png)

**Comment by sandipanghos** [comment]
@ThomasKranitsas the build got passed now and merged into new-develop.
Please mark it as ready for review.
And assign me another ticket

**Comment by ThomasKranitsas** [comment]
@sandipanghos the fix is not completely correct. Please see my comment on the pull request and update your pull request.

**Comment by ThomasKranitsas** [comment]
@sandipanghos please see my comment on your pull request. If you don't fix it ASAP, I'll open the ticket for pickup

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please assign me if he fails? thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069503 has been updated - it has been assigned to gauravseta.

**Comment by ThomasKranitsas** [comment]
@Gauravseta please do start working on it

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069503
