### ISSUE TITLE
Chrome- On the Web Links are not getting displayed.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1050]
. Summary:
Chrome- On the Web Links are not getting displayed.
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/members/petr/
2. Observe we have On the Web Links

### Actual  Result ###
Chrome- On the Web Links are not getting displayed.
## Expected Result ###
Chrome- On the Web Links should be displayed.
### Screenshots ###
See Comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment]
Actual:
 
![image](https://user-images.githubusercontent.com/31862600/41250542-df316fbc-6dd4-11e8-9343-b3b191de45c6.png)


Expected:
![image](https://user-images.githubusercontent.com/31862600/41250553-e628a45c-6dd4-11e8-90d5-8b0e05bfb880.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Not a valid issue
