### ISSUE TITLE
Chrome-Mobile-Profile,While clicking tabs like Profile, Account, Email and Preference are not highlighted properly 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1051]
1. Summary:
Chrome-Mobile-Profile,While clicking tabs like Profile, Account, Email and Preference are not highlighted properly 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Click tabs like Profile,Account,Email and Preference.

### Actual  Result ###
Chrome-Mobile-Profile,While clicking tabs like Profile, Account, Email and Preference are not highlighted properly 
## Expected Result ###
Chrome-Mobile-Profile,While clicking tabs like Profile, Account, Email and Preference are not highlighted properly 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Mobile
OS: Android 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41251395-6b5691d2-6dd7-11e8-886a-80f93e1f9ff9.png)

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
