### ISSUE TITLE
Chrome-Mobile-Profile,Short Bio text Field is accepting more than 256 words.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1052]
1. Summary:
Chrome-Mobile-Profile,Short Bio text Field is accepting more than 256 words.
Note; This issue is only in mobile 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Go to Shore Bio text Fields
3.Trype more than 300 words
4.Click Save button

### Actual  Result ###
Chrome-Mobile-Profile,Short Bio text Field is accepting more than 256 words.
## Expected Result ###
Chrome-Mobile-Profile,Short Bio text Field should limit text to 256 words.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Mobile
OS: Android 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41251514-c84d7748-6dd7-11e8-80fa-7f884b8bccb0.png)

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
