### ISSUE TITLE
Chrome-Mobile-Profile,Add A New Skill Text Box size should be increased. 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1054]
1. Summary:
Chrome-Mobile-Profile,Add A New Skill Text Box size should be increased. 
Note; This issue is only in mobile 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/profile/
2. Add A New Skill section and Observe.
### Actual  Result ###
Chrome-Mobile-Profile,Add A New Skill Text Box size is very small. 
## Expected Result ###
Chrome-Mobile-Profile,Add A New Skill Text Box size should be increased. 
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Mobile
OS: Android 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41251724-6f577c00-6dd8-11e8-95b5-3fc931774dd5.png)

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
