### ISSUE TITLE
[$20] Chrome-Mobile-Member, Graph is not completely displayed  

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1055]
1. Summary:
Chrome-Mobile-Member, Graph is not completely displayed  
Note; This issue is only in mobile 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/details/?track=DEVELOP&subTrack=DESIGN
2. View the graph
### Actual  Result ###
Chrome-Mobile-Member, Graph is not completely displayed  
## Expected Result ###
Chrome-Mobile-Member, Graph should be completely displayed  
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Mobile
OS: Android 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41251823-bd95ff36-6dd8-11e8-832e-4f0a119c421d.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069477 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069477 has been updated - the new changes has been updated for this ticket.

**Comment by sandipanghos** [comment]
@ThomasKranitsas on chrome mobile view i can see the complete graph if i drag it.Is this require a fix?

**Comment by ThomasKranitsas** [comment]
Yes, it needs to be fixed so it fits in the screen

**Comment by suppermancool** [comment]
@ThomasKranitsas can you assign to me

**Comment by suppermancool** [comment]
@ThomasKranitsas fixed in https://github.com/topcoder-platform/community-app/pull/1184, pls check, thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069477 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069477
