### ISSUE TITLE
[$15] Chrome-Mobile-Member, View Ratting History and View Rating Distribution button are missing.  

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1056]
1. Summary:
Chrome-Mobile-Member, View Ratting History and View Rating Distribution button are missing.  
Note; This issue is only in mobile 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/members/wendell/details/?track=DEVELOP&subTrack=DESIGN
2. Click View Ratting History and View Rating Distribution button
### Actual  Result ###
Chrome-Mobile-Member, View Ratting History and View Rating Distribution button are missing.  
## Expected Result ###
Chrome-Mobile-Member, View Ratting History and View Rating Distribution button should be there and While clicking application should display the graph.  
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Mobile
OS: Android 
Browser: Chrome

**Comment by youdare** [comment]
Actual:
![image](https://user-images.githubusercontent.com/31862600/41251933-2d38ba4a-6dd9-11e8-96a7-08b34d6cca3e.png)

Expected:
![image](https://user-images.githubusercontent.com/31862600/41251951-3e380382-6dd9-11e8-97ae-84e069ad5c22.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069472 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069472 has been updated - the new changes has been updated for this ticket.

**Comment by sandipanghos** [comment]
@ThomasKranitsas  please assign me the ticket

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069472 has been updated - it has been assigned to sandipanghosh64.

**Comment by sandipanghos** [comment]
@ThomasKranitsas  I have checked in Google chrome mobile view .The button View  Ratting History and View Rating Distribution are there.

Chrome-Mobile-Member is a button?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069472 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Seems like this was an issue in the old code and it's been fixed now

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069472
