### ISSUE TITLE
Chrome-Mobile-Alignment issue in setting->Email  

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1057]
1. Summary:
Chrome-Mobile-Alignment issue in setting->Email  
Note; This issue is only in mobile 
### Reproduction Steps ###
1. Go to  https://www.topcoder-dev.com/settings/email/
2. View the text
### Actual  Result ###
Chrome-Mobile-Alignment issue in setting->Email  
## Expected Result ###
Chrome-Mobile-Alignment issue should not be there in setting->Email  
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Mobile
OS: Android 
Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41252046-9e6f5ce6-6dd9-11e8-96eb-80c710966451.png)
![image](https://user-images.githubusercontent.com/31862600/41252059-acae08de-6dd9-11e8-80c7-7916e5ee404e.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
This is a minor issue

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
