### ISSUE TITLE
Challenge not visible on topcoder.com 

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1058]
When a challenge technology is set to Data Science, the challenge details are not visible on topcoder.com.
Getting this issue with below challenges:
https://www.topcoder.com/challenges/30062822
https://www.topcoder.com/challenges/30057606
https://www.topcoder.com/challenges/30063682

![image](https://user-images.githubusercontent.com/34749364/41275475-9f93667a-6e3e-11e8-9d39-ab93dce26541.png)
![image 1](https://user-images.githubusercontent.com/34749364/41275623-1b54ed74-6e3f-11e8-8f8b-dc41cff9b06d.png)

Please check and fix the issue.
@birdofpreyru

**Comment by birdofpreyru** [comment]
fixed
