### ISSUE TITLE
Unlink account from Topcoder profile page

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1059]
User handle: ronesim 

Above user wants to remove the linked account other than Github from here: https://www.topcoder.com/settings/profile/

@birdofpreyru

**Comment by nithyaasworld** [comment]
There is no way to unlink the linked accounts in the Settings -> Accounts -> Linked Accounts Page. So keeping this ticket in open.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
