### ISSUE TITLE
Updates for CS and  Contentful 

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1060]
1. Add a page named Catalog. It should be a blank viewport that we can add content to.

2. Add a content type that allows us to add content in this format:

![image](https://user-images.githubusercontent.com/3812270/41317745-257e5fb8-6e64-11e8-8466-567db9870eb7.png)

**Comment by ajefts** [comment]
@birdofpreyru Any chance we could do this tomorrow?

**Comment by birdofpreyru** [comment]
sure

**Comment by birdofpreyru** [comment]
Read in dev

**Comment by birdofpreyru** [comment]
released to prod
