### ISSUE TITLE
Contentful - Content Block Updates

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1061]
1. The sites break when you add images to the text area.

![image](https://user-images.githubusercontent.com/3812270/41317959-bb81eaa2-6e64-11e8-86d7-fb26614b9657.png)

2. Lists don't seem to work.  It displays the first item with no bullet and seems to drop the remaining items.

3. Tables don't see to display.  If I create a table I'm seeing he top left cell, but nothing else.

**Comment by birdofpreyru** [comment]
All fixed and released to prod
