### ISSUE TITLE
Content Block For Embed Links

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1068]
Please create a way to allow to embed items such as Google Calendar and Youtube Videos.  Thanks!

**Comment by birdofpreyru** [comment]
Actually, for YouTube videos just copy-pasting of their embed code into Markdown works fine:

<iframe width="560" height="315" src="https://www.youtube.com/embed/BEX-FTB-xq8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

I guess, same for other embed codes.
