### ISSUE TITLE
Enable leaderboard for blockchain

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1069]
API:  http://api.topcoder.com/v4/looks/1037/run/json

**Comment by ajefts** [comment]
@birdofpreyru would you mind hooking the blockchain leaderboard to the API above?  Let's not enable the nav yet though.  Thanks.

**Comment by birdofpreyru** [comment]
@ajefts ok, it will up shortly, ~5 mins from now, at https://community-app.topcoder-dev.com/__community__/blockchain/leaderboard

There are these mismatches in the field names between current API response and what is expected by the leaderboard:
`challenge_stats.registrant_handle` should be `challenge_stats.winner_handle`
`challenge_stats.tco_points` should be just `points`

Also, the actual placements look quite different from what I see at http://tco18.topcoder.com/win-a-trip/blockchain-community/ Seeing myself at the second place, I guess, you probably do not filter out payments.

**Comment by ajefts** [comment]
Thanks.  I added the points field so that shows now.

Can you fix the sorting so it's sorted by points desc?  I think right now it's sorting by count of challenges.

You're right on the placements not matching.  We're still working on that...

**Comment by ajefts** [comment]
@birdofpreyru because of the way looker works, I had to name the column "handle" for winner_handle.  Can you adjust for that?  I can change the other API's for leaderboards to match if we need to.

**Comment by birdofpreyru** [comment]
@ajefts updated

**Comment by nithyaasworld** [comment]
@ajefts From the conversation above, it looks like the issue is resolved. Please feel free to re-open if not.
