### ISSUE TITLE
topgear group not showing in sub community filter on challenges for some users

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1072]
Some users are reporting that the groups they are in are not showing up in the group dropdown on the challenge listings page and also the header on topgear.topcoder.com.

![image](https://user-images.githubusercontent.com/3812270/41592541-e76e6af2-738a-11e8-99aa-fdb3f4aee6f0.png)

**Comment by ajefts** [comment]
@birdofpreyru Can you check this one please? I'm able to see the group, but the issue seems to be happening for SSO users.

**Comment by birdofpreyru** [comment]
@ajefts I also see the groups. It should be API problem, I guess it does not properly message user groups for SSO users?

**Comment by birdofpreyru** [comment]
Seems to still be an issue.

**Comment by ajefts** [comment]
@aah-74 Can you please confirm that you can see the topgear community in the dropdowns now?  Thanks.

**Comment by aah-74** [comment]
Tony,

Yes Now I can see the TopGear community in the drop down list. PFB screenshot.

[cid:image005.jpg@01D419CC.42531170]

Thanks for closing this.

@Smitha M V (Global Delivery Enablement)<mailto:smitha.kumaran@wipro.com> @Umesha H S (Global Delivery Enablement)<mailto:umesha.hassan@wipro.com>  Please check.

Regards,
[http://marketing.wiprodigital.com/apps/wipro-esig/assets/images/logo-01.png]<http://www.wipro.com/>

Achyut Hirve

Manager

Global Delivery Enablement | TopGear

M: +91 70660 37923<tel:+91%2070660%2037923>

Wipro Limited

Rajiv Gandhi Infotech Park, Phase-2 Hinjewadi, Pune, Maharashtra, India 411057






Sensitivity: Internal & Restricted
