### ISSUE TITLE
Update CDN / Webpack build handling

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#1077]
Currently, when the app is re-deployed, for a short time AWS will have both old and new instances of the app running side-by-side, which creates problems when requests for newly compiled assets land to the old instances and this is cached by ClouldFront CDN.

Probably, we should use something like https://github.com/matrus2/webpack-s3-uploader to upload all assets generated by Webpack to S3 bucket, and use that as CDN data source.

**Comment by birdofpreyru** [comment]
To add more context: 
![image](https://user-images.githubusercontent.com/20144632/41789188-c3fef336-764e-11e8-8fcb-f038e2eca73e.png)

**Comment by birdofpreyru** [comment]
FYI @ajefts @mtwomey 

What we briefly discussed in Slack, it happens cause now ClouldFront CDN directly hits **community-app** to get any CSS/JS assets.

There is a proper fix: to update our deployment flow so that all assets generated during the build are uploaded to S3 bucket, and then reconfigure CDN so that it gets all CSS/JS assets from S3 bucket. It will solve the problem as the assets from new version of the app will be uploaded to S3 before he new app goes into rotation behind the load balancer.

There are cons: it will complicate entire setup, both for the interactions between CircleCI build / S3 bucket and CDN; and also because local deployment should work without CDN/S3.

As an alternative quick fix I reconfigured CDN to not cache 404 error responses for more than 1 second (it was 5 mins by default). This way, after redeployment, as soon as all instances of a previous version of **community-app** are killed by AWS, every visitor should be fine.

What do you think, should we say that's it and close the issue, or should we further look into the proper fix?

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
