### ISSUE TITLE
Community App Performance : General Report

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1078]
Community app challenge listing page is very slow compared to the number of actions that it can perform. It should be one of the fast pages in the app as community members are most likely to come to listing looking for new exciting challenges.

Community app (https://www.topcoder.com/challenges) on production with moderate internet speed performs very badly. I have done and audit and profiling of community app with these profile attributes

1. Network: Fast 3G
2. CPU: 4x slowdown

This is how lighthouse **audit** performance report looks like

<img width="1303" alt="screen shot 2018-06-25 at 4 22 48 pm" src="https://user-images.githubusercontent.com/683231/41846433-489f7fc4-7894-11e8-93fe-69f42c041ebf.png">

**And** this is how **profiling** looks like, there is huge scripting time and call chaining involved in the rendering of the app. That creates the bad user experience and add server payload cost.

<img width="1680" alt="screen shot 2018-06-23 at 7 19 42 pm" src="https://user-images.githubusercontent.com/683231/41810380-00583802-771b-11e8-8e06-37040579fadd.png">

There a is a huge opportunity for improvement in every area, I will divide this report into three main categories in the order of low hanging fruits.

#### 1. Build artifacts contain unused code 
Some of these files are huge, the amount of code that is being downloaded isn't used by the application. And it blocks main thread and a network connections.

<img width="1675" alt="screen shot 2018-06-23 at 7 28 56 pm" src="https://user-images.githubusercontent.com/683231/41810431-c92f7344-771b-11e8-8f06-db153c775955.png">

In some of the files more than **50%** of the code is not used indicated by red zone

And it can be reduced with **[treeshaking](https://webpack.js.org/guides/tree-shaking/)**, which will reduce the size of the build artifacts.

#### 2. Files that are non-essential to display of listing components

<img width="1668" alt="screen shot 2018-06-23 at 7 26 37 pm" src="https://user-images.githubusercontent.com/683231/41810409-6c691c46-771b-11e8-9303-2f40099b4188.png">

Some of these files are huge and loaded synchronously in a [parser blocking manner](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript#parser_blocking_versus_asynchronous_javascript), they are also blocking the main thread and network connections. 

These are the list of files

1. google analytics
2. zendesk
3. messo
4. google tag manager
5. hotjar
6. connect.facebook
7. even raven.js

These files can be downloaded with async/defer as these aren't neccessary for first paint.

`<script src="some-analytics.js" async></script>`

### B. API calls improvements
On the listing page, essential components that need to be rendered in order to make a user interface ready for interaction are 

1. Challenge Summary 
2. My Challenges
3. Open of Registration

To render these components, we only need 
    

>     41      // 20 open for registration, 20 Past and 1 challenge summary
>     + X     // My challenges
>     = 41 + X // Total records 

If we decide to show past challenges lazily, in that case, total records are necessary to show first painted view is only 21 + X

Instead, app is fetching 

>     50      // Past
>     + 50    // Completed
>     + 50    // Active
>     + 50    // Active 50 to 100
>     + X     // My challenges 
>     = 200 + X // Total records

Lots of unnecessary data calls

<img width="1680" alt="screen shot 2018-06-23 at 7 21 01 pm" src="https://user-images.githubusercontent.com/683231/41815926-d6f6c69c-7795-11e8-89ff-9ad0d694d2f0.png">

[Here is the detailed report on calls ](https://github.com/topcoder-platform/community-app/issues/1138)

### C. Misc

These calls are not compressed and consuming the network time 

1. https://lc1-user-settings-service.herokuapp.com/saved-searches
2. https://d2nl5eqipnb33q.cloudfront.net/static-assets/loading-indicator-animation-1529020371826.js
3. Cloudfont will not compress font file with woff extension, https://d2nl5eqipnb33q.cloudfront.net/static-assets/fonts/bae8500e15c460acae92cfc8da3b4f3d.woff

_PS : I'm still investigating bottlenecks, I will continue to add to the list_

**Comment by dmessing** [comment]
Let's remove past challenges all together and show only if someone wants to view pasts challenges.

**Comment by ajefts** [comment]
Past challenges are removed from the main UI, but maybe the app is still fetching them for some reason...

**Comment by vic-topcoder** [comment]
Also an interesting read about react-specific optimizations with potential to further optimize the pages and our approach towards performant front-end: https://medium.com/airbnb-engineering/recent-web-performance-fixes-on-airbnb-listing-pages-6cd8d93df6f4.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
