### ISSUE TITLE
Dashboard Text

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1086]
Can we have a WYSIWYG for the text in the Dashboard?  Jessie was trying to create a new paragraph in her announcement but it wouldn't let her.

**Comment by birdofpreyru** [comment]
@hokienick do you mean for the text inside announcements in the dash? WYSIWYG is tricky at the moment; updating it to Markdown editor, with support of any html tags, the same as it works for `ContentBlock`s, sure, can be done fast.

**Comment by birdofpreyru** [comment]
@hokienick not sure, why you closed this one? I believe, making dashboard announcement text working the same way as text in ContentBlocks is still a thing todo.
