### ISSUE TITLE
Direct Linking to Filtered Challenge Listing Page - broken

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1087]
Attempting to link to all open DS challenges does not work.  Ex:

https://www.topcoder.com/challenges/?filter[tracks][data_science]=true

**Comment by birdofpreyru** [comment]
Figured out that it actually worked, but not when you prepended `?` by `/` after `challenges`.
I've pushed a patch to make it work either way, with `/` or without it in front of `?`. Should be in prod in ~10 mins.

f95a15a914fa62f9f24ffe7874e1d031aabb34d7
