### ISSUE TITLE
Unable to view formulas and code correctly in Content Blocks

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1095]
Attempting to create blocks of code with < pre > and/or < code > do not format correctly.  All tabs and spaces are stripped so everything appears in one column. 

Should look like this:

<img width="519" alt="screen shot 2018-07-05 at 11 50 29 am" src="https://user-images.githubusercontent.com/1373998/42342062-e5f05df4-8049-11e8-9323-12ce9103d31b.png">

But it looks like this:

<img width="727" alt="screen shot 2018-07-05 at 1 08 43 pm" src="https://user-images.githubusercontent.com/1373998/42345571-952f9afa-8054-11e8-9411-fea3d63b8851.png">

**Comment by hokienick** [comment]
Also of note, if there are empty lines in between code it breaks the block and formatting stops.

**Comment by birdofpreyru** [comment]
@hokienick this is partially fixed: if you input codeblocks as
> &grave;&grave;&grave;
> some code
> &grave;&grave;&grave;

it will be rendered fine.

To fix HTML `<code>` blocks with empty lines inside them will demand a bit of extra efforts.

**Comment by hokienick** [comment]
I'll try those ticks!  Thank you.

**Comment by hokienick** [comment]
Is it possible to control padding?  Specifically on the top and bottom:

<img width="746" alt="screen shot 2018-07-09 at 11 29 53 am" src="https://user-images.githubusercontent.com/1373998/42469060-789a1522-836b-11e8-9178-7b7e41bfe8b1.png">

<img width="1019" alt="screen shot 2018-07-09 at 11 29 38 am" src="https://user-images.githubusercontent.com/1373998/42469061-78b267a8-836b-11e8-84fe-274c8303da99.png">

**Comment by hokienick** [comment]
Any update on this ticket?

**Comment by birdofpreyru** [comment]
F2F did not work out. I could clear this myself, but probably it is not that high priority, as code blocks entered with Markdown's ``` do work well.
