### ISSUE TITLE
Stock art bulk upload in comma-separated format does not work at design challenge submission

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1097]
**Actual result**
I placed my comma separated links in the respective stock art text box, but nothing has happened

**Expected result**
The URLs should have been automatically spread out into different text boxes. 

Safari 11.1 on OS X El Capitan

**Comment by birdofpreyru** [comment]
@PereViki it should be space (or white-space / tab / new-line) separated list of links, cause comma, in principle, is allowed inside URLs, thus we can't use it as separator :)
