### ISSUE TITLE
Somebody added back to community-app the old stylesheets that have been moved to topcoder-react-ui-kit before!!! Should be carefully eliminated!

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#1099]

**Comment by birdofpreyru** [comment]
@ThomasKranitsas, I guess this comes from one of your challenges that moved stuff from *topcoder-app* to *community-app*? Instead of properly upgrading the code on the way, somebody just returned old styles to https://github.com/topcoder-platform/community-app/tree/new-develop/src/styles instead of upgrading the code that depends on them to use topcoder-react-ui-kit properly?

**Comment by ThomasKranitsas** [comment]
@birdofpreyru perhaps. Can you point the exact commit that introduced that?

**Comment by birdofpreyru** [comment]
@ThomasKranitsas oh, actually, my bad. After double-checking, it looks like I thought that I moved more styling to _topcoder-react-ui-kit_, than I actually did.
