### ISSUE TITLE
mm-feature-experiment branch : TESTING : UI not updated for registration and unregister 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1102]
Can we add an intentional delay after registration and registration before next call to fetch registrants details?

@birdofpreyru @a-lowe

**Comment by birdofpreyru** [comment]
Although, not the best practice, we can. How large should it be? 1 / 3 / 5 seconds?

**Comment by sushilshinde** [comment]
Let's try with 3 secs
