### ISSUE TITLE
mm-feature-experiment : TESTING : submission UI not displaying

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1103]
It was working when @birdofpreyru worked on it

<img width="1635" alt="screen shot 2018-07-09 at 12 32 53 pm" src="https://user-images.githubusercontent.com/683231/42435463-4d0c301c-8374-11e8-98ed-1dc2ad8feb4f.png">

**Comment by sushilshinde** [comment]
@a-lowe yes

**Comment by birdofpreyru** [comment]
@sushilshinde I am lost in the part, how the regular MMs will work then? Are we redirectling to the legacy MM engine page for them? Is it taken into account @a-lowe ?

**Comment by a-lowe** [comment]
@birdofpreyru @sushilshinde 
I would need some clarification on this as well.  The mm-feature-experiment branch removed the call to the legacy MM endpoint.  This means that the legacy marathon matches would also need to be returned by the v4 challenges endpoint ( and include any legacy specific fields, such as the 'rd' id ).

**Comment by birdofpreyru** [comment]
Isn't it doing it at the moment?

**Comment by sushilshinde** [comment]
@a-lowe you are right all the challenges and mms will be returned by v4/challenges endpoint

**Comment by sushilshinde** [comment]
Working now
