### ISSUE TITLE
Please add option  in community app to upload checkpoint submission

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1104]
A UI PRototype challenge run in multiple rounds. Online Review allows uploading to checkpoint submissions but there is no option to upload Checkpoint submission in the Community App.

@birdofpreyru Please check and do the needful.

Challenge link: https://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30066941 

https://www.topcoder.com/challenges/30066941/?type=develop

**Comment by birdofpreyru** [comment]
@skyhit @ajefts can we double-check whether API v3 handles checkpoint submissions correctly? Cause the code at **community-app** side looks like it should be already working: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/components/SubmissionPage/Design/index.jsx#L92-L144 : it takes the list of active challenge phases, reported by API for challenge details, and if there is a phase with `Checkpoint Submission` type, it passes its ID as `phaseId` to the submit endpoint.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
