### ISSUE TITLE
[$30] Profile - Bio

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1106]
Make sure Bio info gets migrated.  i.e. All user bio info is in informix now.  If we're staving the same bio info as "traits" (address, etc), then existing info needs to be migrated or a double read/write needs to happen...?

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
@ajefts We changed the implementation so we read/write the bio from/to the `description` property of the `MemberProfiles` table.

Anything else pending on this ticket?

**Comment by ajefts** [comment]
@ThomasKranitsas @urwithat On my profile in prod, country is not showing although it is set to USA in the DB...

![image](https://user-images.githubusercontent.com/3812270/44363570-8c403a00-a492-11e8-829c-afd926587f2d.png)

**Comment by ThomasKranitsas** [comment]
Good catch! 


I know why. It’s because in the new UI it’s “United States of America”.

We’ll have to think of how to catch such cases.

**Comment by ThomasKranitsas** [comment]
@ajefts @cwdcwd do we have a list of the old values we were using so we can compare and fix this issue?

Or `USA => United States of America` is the only issue?

**Comment by ajefts** [comment]
We should be pulling this list from an API and not hardcoding it in the UI.  

This is the data we have for countries:  http://api.topcoder.com/v2/data/countries

@cwdcwd should we create a quick endpoint for this that is NOT v2...?

**Comment by ajefts** [comment]
fyi @ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
@ajefts @cwdcwd what's the service that has that endpoint?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070224 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070224 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070224 has been updated - the new changes has been updated for this ticket.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas can i get this?

**Comment by ThomasKranitsas** [comment]
No, I've already fixed this.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas ok anything else i can work on? thanks

**Comment by ThomasKranitsas** [comment]
We don't have anything right now
