### ISSUE TITLE
[$20] Profile - clean up dropdown list data

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1107]
Let's make sure we have appropriate info in all dropdowns.

Gender: I'd like to make this more inclusive.  Can we do Male, Female, Prefer not to answer, Custom...where custom would provide a freeform text field to let the user specify?

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
I'm not really sure if it's a good idea to allow a user to set anything as a gender.
I believe just `Male`, `Female`, `Prefer not to answer` is enough.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069278 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069278 has been updated - the new changes has been updated for this ticket.

**Comment by PrakashDurlabhji** [comment]
i am not able to assing it. @ThomasKranitsas can you please assing? working on it. to whomsoever wana take please note i have already taken it

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji are you registered on this https://www.topcoder.com/challenges/30069264?tab=details challenge?
If not please register and follow the link from the challenge forum otherwise I can't add you to any ticket

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas its done. can you please check?

**Comment by ThomasKranitsas** [comment]
Did you get any invitation on your email? I still can't find you

**Comment by ThomasKranitsas** [comment]
Did you use this https://x.topcoder.com/api/v1/github/teams/registration/887210ad-9ed5-4641-b0ff-12b1d8191d63-1533938364810 link?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas its finally done i guess. can you please try once more thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069278 has been updated - it has been assigned to PkDurlabhji.

**Comment by ThomasKranitsas** [comment]
Done

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas why no label change possible? its ready and PR raised.

#1161

**Comment by ThomasKranitsas** [comment]
I believe only copilots/admins can modify the tickets on this repo. Don't worry about that. Just comment on the ticket and I'll update it

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069278
