### ISSUE TITLE
[$40] Profile - required fields

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1108]
Let's review the required fields.

Basic Info Required Fields:

- First Name
- Last Name
- Country

What is "Current Location" supposed to refer? I'm thinking we should remove it.

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ajefts** [comment]
@urwithat @ThomasKranitsas Please make only the above 3 fields required on the basic info page.  Everything else should be optional.

**Comment by ThomasKranitsas** [comment]
How about the following?
- birthdate 
- gender
- address info

**Comment by Gauravseta** [comment]
@thomaskranitsas if it becomes open for pickup then will i get this? as it was implemented by me.thanks

**Comment by dmessing** [comment]
@Gauravseta I say fix it, I think @ThomasKranitsas is out right now

**Comment by dmessing** [comment]
@ThomasKranitsas those should be optional

**Comment by ThomasKranitsas** [comment]
This will require backend fixes as well.

**Comment by ThomasKranitsas** [comment]
Please do the frontend changes and I’ll do the backend work

**Comment by Gauravseta** [comment]
@thomaskranitsas to be done on backend too? or only front end?

**Comment by ThomasKranitsas** [comment]
You only have to work on the frontend

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069810 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069810 has been updated - it has been assigned to gauravseta.

**Comment by ThomasKranitsas** [comment]
@Gauravseta what's the status here?

**Comment by Gauravseta** [comment]
@thomaskranitsas i will complete it soon as i did it and know well where to change it. it will be surely done.just few hrs

**Comment by ThomasKranitsas** [comment]
Thanks for the update!

**Comment by Gauravseta** [comment]
@ThomasKranitsas need to work on "develop" branch or "new-develop" branch?

**Comment by ThomasKranitsas** [comment]
Please use the “develop” branch

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please check the PR? thanks

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069810
