### ISSUE TITLE
Profile - context help on fields

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1109]
We need help text on a lot of the fields that aren't self explanatory.

**Comment by ThomasKranitsas** [comment]
Can we get a design for that and more info on which fields aren't self-explanatory?

**Comment by ajefts** [comment]
I believe we have something in the UI kit for that, but will double check with @vic-topcoder

**Comment by nithyaasworld** [comment]
Hi @ajefts Do we have any updates for this enhancement?

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
