### ISSUE TITLE
Profile - move consent option

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1114]
![image](https://user-images.githubusercontent.com/3812270/42484459-18d09a2a-83c1-11e8-8a75-50e19ced1f07.png)

Move the consent toggle so it's an option at the bottom of the basic profile page.

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
@ajefts do we still need this? In this challenge https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069040 every time a user updates his/her profile data we show this https://marvelapp.com/8gc9e84/screen/44675024 modal and we set the user consent property based on the answer from this modal.

I think we can close this ticket

**Comment by ThomasKranitsas** [comment]
@ajefts this has been moved here https://community-app.topcoder-dev.com/settings/account based on the new design.
Can we close this ticket or do we need to move the user consent option to the basic info section?
