### ISSUE TITLE
Usability Suggestion : Challenge Details Page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1120]
I think it will be nice to have back button on details page just like submission screen

![abc missing details portal architecture](https://user-images.githubusercontent.com/683231/42568940-7232135c-852c-11e8-9311-1accc10c4a55.png)

Similar to the submission page

![screen shot 2018-07-11 at 4 59 40 pm](https://user-images.githubusercontent.com/683231/42568947-7c4676a8-852c-11e8-90be-086b8969b99a.png)

@vic-topcoder is that ok?

**Comment by birdofpreyru** [comment]
@Dara-K what do you think?

**Comment by Dara-K** [comment]
Hey, I missed this as the email got into my spam.

I discussed with Vic the idea of adding a back icon, when we started designing this page, but it would unbalance the page / have the items not to be left aligned anymore. Besides, most of the TC users know to use the Back from Browser to get to previous page.

**Comment by birdofpreyru** [comment]
But in the dev team Slack, both Tony and Victor told to go for it, thus I added it.

**Comment by Dara-K** [comment]
I guess Vic changed his mind then... so even if it won't look aligned, it's fine.

**Comment by sushilshinde** [comment]
@Dara-K if you have an idea about how back button/link should look like. I wanted to only suggest the navigation but it should also fit in app UX wise.

**Comment by Dara-K** [comment]
It's good how you used it now. Just make the space between the arrow and title little smaller.
