### ISSUE TITLE
mm-feature-experiment branch : Navigation is wrong

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1125]
All legacy MM matches from the listing are hitting old legacy app for details, it should follow the navigation as other challenges 

`https://test-community-app.topcoder-dev.com/challenges/{id}`

![mm-legacy](https://user-images.githubusercontent.com/683231/42750494-0e83a69a-8905-11e8-8768-de758e71b916.png)

**Details (unexpected)** 

![deta](https://user-images.githubusercontent.com/683231/42750557-44f314b8-8905-11e8-93fa-504946c92aba.png)
'

**Sometimes it navigates to** 

`https://test-community-app.topcoder-dev.com/https://community.topcoder-dev.com/tc?module=MatchDetails&rd=14478`

**Comment by birdofpreyru** [comment]
@a-lowe, please check & fix

**Comment by birdofpreyru** [comment]
@a-lowe and this one? It looks to me, the details of legacy MMs are supported now by `/v4/challenges/{ID}`, e.g. https://api.topcoder-dev.com/v4/challenges/13798 so challenge details for legacy MMs should be shown in the same page as for other challenges.

**Comment by a-lowe** [comment]
@birdofpreyru Sounds good, I'm just finishing the normalization for those right now.

**Comment by birdofpreyru** [comment]
Ok, so, in my current understanding, the details, registrants, submittions tabs should work for them, the link to challenge forum should work, the registration / unregistration should, presumably, also work via v4 api. And only for submission I am not sure. @sushilshinde should submission button for the legacy MMs still redirect to legacy submission page, that allows to enter code and send it for testing?

**Comment by a-lowe** [comment]
@sushilshinde 
Some potential issues:
1. No prizes field for legacy MMs.  This means that the 'winners' tab will show '$N/A' for each winner.
2. The 'winners' field for challenges does not implement the photoURL field that the v3 API did.  This means that the winner avatars on the Challenge Listing will be the standard placeholder portrait.  Currently no winners are shown on the Challenge Listing, but this will be fixed next commit.  This is affecting all challenge types.

**Comment by skyhit** [comment]
1. yes. there is no prizes.
2. can we dynmically form the url using handle ?

**Comment by birdofpreyru** [comment]
@skyhit I believe not, e.g. my avatar has this address:
https://topcoder-prod-media.s3.amazonaws.com/member/profile/birdofpreyru-1474623113239.jpeg

**Comment by sushilshinde** [comment]
@birdofpreyru for past legacy matches all the buttons should be disabled

**Comment by sushilshinde** [comment]
@skyhit is there a way to pull winners?

@a-lowe what else you find missing in order to display legacy matches?

**Comment by birdofpreyru** [comment]
@sushilshinde and for new MMs that follow legacy format, with code submission to scoring engine?

**Comment by sushilshinde** [comment]
New will MM will not have any connection with the legacy format

any example?

**Comment by birdofpreyru** [comment]
https://community.topcoder.com/tc?module=MatchDetails&rd=17203 - the ongoing 2018 TCO MM 3 challenge. How will we support such challenges if we do what you ask here, until you get correct support of them in API and frontend?

**Comment by sushilshinde** [comment]
Working on a transition plan with Mess and Chris, will keep you updated.

**Comment by a-lowe** [comment]
Hi @sushilshinde, just wanted to follow up on the previous commits and see if there is anything else that needs to be changed or fixed for legacy MMs in Community App.  Thanks.
