### ISSUE TITLE
mm-feature-experiment branch : Listing breaking on TEST Env

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1127]
This page is breaking with user logged in

`https://test-community-app.topcoder-dev.com/challenges`

@a-lowe I can't test further because of this

**Comment by a-lowe** [comment]
@sushilshinde I'm unable to replicate this issue.  Can you tell me what browser and account this is happening with?  Also, are there any error messages in the developer console?  Thanks.

**Comment by sushilshinde** [comment]
This is resolved
