### ISSUE TITLE
mm-feature-experiment branch : MM not displayed in the listing

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1128]
This challenge do exist **This is test MM - do not register - only for MM-V4 testers** in

`https://api.topcoder.com/v4/challenges/`

but not displayed in neither **My Challenges** bucket nor Open for registration bucket

**Comment by a-lowe** [comment]
@sushilshinde Is this issue happening at https://test-community-app.topcoder-dev.com/challenges or a different deploy? Thanks.

**Comment by sushilshinde** [comment]
No longer a problem, I can see it now
