### ISSUE TITLE
mm-feature-experiment branch : Can't unregister for the challenge

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1131]
https://test-community-app.topcoder-dev.com/challenges/30052113

https://beta-community-app.topcoder.com/challenges/30067759

**Comment by birdofpreyru** [comment]
@sushilshinde it works for me at https://beta-community-app.topcoder.com/challenges/30067759

**Comment by sushilshinde** [comment]
UI is disabled

![this is test mm do not register only for mm v4 testers](https://user-images.githubusercontent.com/683231/42821951-6a08ff68-89f7-11e8-9744-1249ff37207c.png)

**Comment by birdofpreyru** [comment]
Ah, ok, but you have submitted to this MM already. The current logic is: you cannot unregister if you have submitted to the challenge.
