### ISSUE TITLE
Add catalog page for Topgear

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1132]
Add a blank page/viewport on topgear.  It will be used to build a catalog just like we did for the cs site.  Don't add it to the top nav yet.

**Comment by ajefts** [comment]
@birdofpreyru think you could do this one in the next couple of days please?

**Comment by ajefts** [comment]
fyi @aah-74

**Comment by birdofpreyru** [comment]
@ajefts it is ready in dev.

The page: https://community-app.topcoder-dev.com/__community__/wipro/catalog (right at the moment it is not possible to access TopGear community in dev, it stucks in infinit authentication loop, I guess there is some problem with member service, preventing the app to pull user groups).

The viewport in Contentful: https://app.contentful.com/spaces/b5f1djy59z3a/entries/2HqNKZnutGWQYsCkmSIs2q

I actually wired TopGear to contentful routes, so here is how catalog page is mounted:
https://app.contentful.com/spaces/b5f1djy59z3a/entries/1CrrJBEB6Uu4Y4uE44swEq

And here is the root route, where you can add more pages, as long as they are not shadowed by existing pages, served directly from **community app** code: https://app.contentful.com/spaces/b5f1djy59z3a/entries/1VXRAIxJdi6eCeeyKCmicK

**Comment by ajefts** [comment]
Thanks @birdofpreyru 

btw...the dev login is ok now...

**Comment by ajefts** [comment]
@birdofpreyru What would it take to get this content put into it's own space?

**Comment by birdofpreyru** [comment]
@ajefts As I told before, it should not be too difficult to do.

**Comment by ajefts** [comment]
mind spinning up a challenge for it? I'd like to set us up so we can specify the space per site.  It's becoming pretty cluttered and I want to be able to leverage the user provisioning per space...

**Comment by kkartunov** [comment]
@birdofpreyru please if you do so also consider add [environment](https://www.contentful.com/developers/docs/references/content-management-api/#/reference/environments) support too. This will enable dev/prod setups per space which will be very useful for development needs.

**Comment by birdofpreyru** [comment]
Ok, here we go: https://www.topcoder.com/challenges/30068306

**Comment by birdofpreyru** [comment]
@ajefts @kkartunov 

**Update here**

I run the challenge with $800/$400 prizes, got 1 submission, which passed with a minimal score 80.33, which resulted from a split decision: one reviewer (**MonicaMurani**) failed it with 73.17 as incorrect implementation, which also breaks existing functionality; while the second reviewer (**reynard2007**) approved the submission with 87.5 score. I tested submission myself, and I side with Monica in her decision that the winning solution does not work, and has a little value.

I sent a message to TC support, warning about the situation, and asking their opinion how to handle the situation. As for the implementation of the feature, I am tempted just to implement it myself, though I sure can re-launch the challenge from scratch.

**Comment by kkartunov** [comment]
I faced the same situation with navi/menu functionality challenge. It is so unpleasant hence the idea to take things in own hands is logical.
We are allowed as copilots to reset the score of an inappropriate review. Probably it was late to do so...?

**Comment by ajefts** [comment]
@birdofpreyru I cases like this I like to add a 3rd reviewer.  Since you already took the time to do the review, do you want formally fill out the scorecard and let the submission naturally fail.  

Raising the issue to support is also appropriate so we can address review performance issues.

I'd prefer to repost a challenge instead of doing it as a task...

**Comment by birdofpreyru** [comment]
@ajefts sure, I am happy to follow the way you say. Just need somebody's help then to re-open the challenge, add the scorecard, and fix the payments that have been done already.

**Comment by ajefts** [comment]
@riteshtc is up to speed and can help

**Comment by birdofpreyru** [comment]
@ajefts works in prod, if you access as https://community-app.topcoder.com/__community__/wipro/catalog
Indeed, it is shadowed by Home page if you go to http://topgear.topcoder.com/catalog I'll correct it later today

**Comment by birdofpreyru** [comment]
@ajefts 
As of now, catalogs looks fine at: https://community-app.topcoder-dev.com/__community__/wipro/catalog
I believe, once last updates are in prod, it will also work there.

**Comment by ajefts** [comment]
ok, thanks.  I was trying to load it at www.topcoder.com/catalog

**Comment by birdofpreyru** [comment]
@ajefts TopGear community in dev updated to rely on the dedicated Contentful space, and it seems to work. Production version still relies on the main CMS space, thus TopGear content in the mail space should be kept until app update makes it to prod.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
