### ISSUE TITLE
Blank page after selecting details for payments

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#1134]
Steps to reproduce:

1. Visit payment.topcoder.com
2. Made payment for a member on a project
3. If select the details, the blank(white) page will appear 

@birdofpreyru 
@ajefts

**Comment by cwdcwd** [comment]
@NehaSharma02 this is the wrong repo. Please move this issue to [here](https://github.com/topcoder-platform/topcoder-payment-tool)
