### ISSUE TITLE
To remove decimal place and put comma in member count

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#1137]
Take out the decimal place and round to nearest dollar and put in a comma into the community member count from Topgear Homepage.

![image 1](https://user-images.githubusercontent.com/37835397/43271278-bc248e06-9114-11e8-98ff-0a5586ebd6d8.png)

@ajefts @birdofpreyru

**Comment by ajefts** [comment]
@birdofpreyru can you do this change this week?
