### ISSUE TITLE
Issue in timezone calculations

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1139]
Website:  https://www.topcoder.com/challenges/30068438/?type=develop&tab=submissions 

Online Review: https://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30068438 

For the above challenge, the user with this handle shubhamranjan is the first to submit for the challenge on 29th July 2018 at 13:00hrs but the submission time reflecting in OR and website is incorrect as per EDT and IST both. Due to an error in time calculation, shubhamranjan is at second place in the below screenshot.

![image 1](https://user-images.githubusercontent.com/34749364/43389170-a7d347ca-9408-11e8-864e-7ae45e05742c.png)
![image 2](https://user-images.githubusercontent.com/34749364/43389181-ab1c6f7e-9408-11e8-96ea-cb6565971046.png)

Please correct the timezone calculations for the challenges.

**Comment by birdofpreyru** [comment]
@JayaDhaka it is not *community-app* problem, I believe, but a long time known API bug, which I am not sure why is not solved still. The api tells *2018-07-28T09:33:51Z* is the time of *shubhamranjan*'s submission i.e. it wrongly claims that the date/time are given in UTC+0 timezone.

**Comment by JayaDhaka** [comment]
@birdofpreyru Can I please tell me the correct Github repo for this issue?

**Comment by ThomasKranitsas** [comment]
@JayaDhaka is that issue the same with this one https://github.com/appirio-tech/ap-submission-microservice/issues/36 ?

**Comment by JayaDhaka** [comment]
@ThomasKranitsas No, In the issue that I have raised the date of submission is correct only the time of submission is reflecting wrong.

**Comment by ajefts** [comment]
This appears to be an  issue with the challenge api.  I'm going to move this issue to there...

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
