### ISSUE TITLE
Formatting of <p> and header tags

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1141]
The content blocks in the "FAQ" and "Extras" are not the same as the content displayed in the section above.  For example:

For Header Tags

**padding-top: 10px;** will be needed

For paragraph tags, I've noticed that even though I double space in the WYSIWYG there is no spacing whatsoever for new paragraphs.  Could we get:

**padding: 10px 0;**

This will make content look much better!  Thank you :)

**Comment by hokienick** [comment]
That being said, it seems italics aren't working in the How-To content section either.

**Comment by birdofpreyru** [comment]
@hokienick should be fine now, please open a new issues if you still see irregularities (please, with a link to the page, where they happen)
