### ISSUE TITLE
Getting error when trying to access a challenge

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1142]
When trying to access this challenge https://www.topcoder.com/challenges/30068678/?type=develop an error message popped up saying "cannot read property 'forEach' of undefined"

Please check and resolve.

![image 5](https://user-images.githubusercontent.com/34749364/43574457-d9cb6900-9661-11e8-90e1-5f9689cd4e3d.png)

@birdofpreyru

**Comment by birdofpreyru** [comment]
@JayaDhaka fixed, though it looks like there is some problem with that challenge at the backend side: (1) API response for that challenge missed some data that all challenges have; (2) it looks like a private payment, though it is visible to me after fixes, and I don't know what is the *Styx* project, thus probably should not be able to see it.
