### ISSUE TITLE
Broken mobile layout at challenge details page

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#1144]
https://www.topcoder.com/challenges/30068755/?type=develop&nocache=true
https://www.topcoder.com/challenges/30068553/?type=develop&nocache=true

**Comment by nithyaasworld** [comment]
@birdofpreyru Closing this as I see no layout issue in mobile view now. Attached is the screenshots of https://www.topcoder.com/challenges/30068755/?type=develop&nocache=true in mobile view

Please re-open if I have missed anything. Thanks.

[screencapture-topcoder-challenges-30068755-2019-06-20-23_51_32.pdf](https://github.com/topcoder-platform/community-app/files/3311659/screencapture-topcoder-challenges-30068755-2019-06-20-23_51_32.pdf)
