### ISSUE TITLE
tco19 Leaderboards

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1147]
Please hook up the following leaderboards:

Copilot:  http://api.topcoder.com/v4/looks/1067/run/json
Algo:  TDB
MM:  TBD
Dev:  http://api.topcoder.com/v4/looks/1059/run/json
F2F: http://api.topcoder.com/v4/looks/1061/run/json
Design:  http://api.topcoder.com/v4/looks/1068/run/json
QA:  http://api.topcoder.com/v4/looks/1058/run/json

**Comment by ajefts** [comment]
Hi @kkartunov 

Here are the leaderboard APIs that we have so far.  Can you get them hooked up to the site?

**Comment by kkartunov** [comment]
Sure. Here they are:

Copilot: https://community-app.topcoder-dev.com/examples/contentful/tabs/3mBvbq4fbq6GIyqsiUWQY0
Algo: TDB
MM: TBD
Dev: https://community-app.topcoder-dev.com/examples/contentful/tabs/3o2PEqH4MgcmWa4co462KM
F2F: https://community-app.topcoder-dev.com/examples/contentful/tabs/3QATlOyqPmgqOMcyEKIkMY
Design: https://community-app.topcoder-dev.com/examples/contentful/tabs/3PlNpppbO0qwWYEiW82eIk
QA: https://community-app.topcoder-dev.com/examples/contentful/tabs/7FD4sPXGDuoMmAkQ26wUA

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by kkartunov** [comment]
Is this card on private board? I get "Card not found." error. What is it about and how it is related to tco19 leaderboards?
