### ISSUE TITLE
UI Suggestions : Dashboard : Remove extra space, add animations

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1148]
_This is not a bug, don't fix it_

The current dashboard UI has a lot of whitespaces. And elements doesn't interact with the user visually (there is no feedback)

### Current UI

![loose 1](https://user-images.githubusercontent.com/683231/43889301-6e453b68-9be1-11e8-807a-e2a0d0300ff8.png)
![loose2](https://user-images.githubusercontent.com/683231/43889568-30a28e9a-9be2-11e8-998d-34d87b72d1af.png)

### Tighter UI

![screen shot 2018-08-09 at 3 26 43 pm](https://user-images.githubusercontent.com/683231/43892445-92332c44-9be9-11e8-8abf-e3a935e275e4.png)

### Add Style and Animations
1. Add box shadow to the cards similar to listing page UI components
2. hover lift [animation](http://ianlunn.github.io/Hover/)

**Comment by birdofpreyru** [comment]
:point_up: @Dara-K

**Comment by ThomasKranitsas** [comment]
Another improvement would be to hide (maybe in a separate tab) the challenges where you have the `observer` role.

**Comment by ajefts** [comment]
@vic-topcoder ^^^

**Comment by vic-topcoder** [comment]
There is a general need to update the TC UI to the latest from TC. The need to update the navigation is more pressing than the small changes in general UI. Let's talk about visual updates to community app before we start modifying small things.
