### ISSUE TITLE
Profile Setting UI Cleanup

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1151]
Clean up the UI for the settings pages.  We just need to focus on cleaning up the form layout.

Here is the design update.

https://marvelapp.com/1816996g/screen/45448641

Don't worry about the header/footer for now.  Just focus on the form layout and any font/sizing/spacing.

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
holding this one until https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069040 is merged

**Comment by gurmeetb** [comment]
Is this ready for pickup? if yes, could you assign me?

**Comment by Gauravseta** [comment]
@ThomasKranitsas i am near to start working on it. can you please assign it to me. thanks

**Comment by ThomasKranitsas** [comment]
@gurmeetb @Gauravseta please see my comment above. This will be open for pickup once the challenge is completed and the code is merged ;)

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors we'll handle this ticket as a separate code challenge.

You can find the challenge here https://www.topcoder.com/challenges/30069539/?type=develop

The registration phase will open in a few minutes.
