### ISSUE TITLE
[$15] Profile Settings - Move Skills above Education

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1152]
Reorder the left nav so Skills is 2nd.

![image](https://user-images.githubusercontent.com/3812270/43914326-9c447d0a-9bd5-11e8-9bb0-f694566d130c.png)

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069273 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069273 has been updated - the new changes has been updated for this ticket.

**Comment by Gauravseta** [comment]
@ThomasKranitsas please assign me to this issue. i have started working and near to complete it.

**Comment by ThomasKranitsas** [comment]
@Gauravseta are you registered on this https://www.topcoder.com/challenges/30069264?tab=details challenge?
If not please register and follow the link from the challenge forum otherwise I can't add you to any ticket

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069273 has been updated - it has been assigned to gauravseta.

**Comment by ThomasKranitsas** [comment]
Ok, I've assigned this to you

**Comment by Gauravseta** [comment]
@ThomasKranitsas yes i registered already

**Comment by Gauravseta** [comment]
@ThomasKranitsas i am not able to change the label. can you pleas help thanks.
can you please mark it ready for review as PR has been raised. #1160

**Comment by Gauravseta** [comment]
@ThomasKranitsas wont i be able to change the labels?

**Comment by ThomasKranitsas** [comment]
I'm not sure what's wrong with this repo... I guess only copilots/admins can modify the tickets.

Not something to worry though. Just a comment is enough ;)

**Comment by Gauravseta** [comment]
@ThomasKranitsas ok np thanks. any more open for pickup issues in this contest? thanks

**Comment by ThomasKranitsas** [comment]
Yeah, there will be more tickets soon

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069273
