### ISSUE TITLE
[$20] Profile Settings:  Device Types

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1153]
Add the following to the list:

- Wearable
- Other

**Comment by ajefts** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
I'll fix that by myself as it also requires backend changes

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069258 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069258 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069258 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069258
