### ISSUE TITLE
[$50] Profile Settings - email change verification issue

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1155]
When I get the email after I change my email and select the option to "Disagree" with the change, I'm getting this:

![image](https://user-images.githubusercontent.com/3812270/43914732-ad872ec2-9bd6-11e8-8a8a-3cf0f12c293b.png)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069267 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069267 has been updated - the new changes has been updated for this ticket.

**Comment by narekcat** [comment]
@ThomasKranitsas please assign this issue to me. I follow the link provided in challenge forum and I didn't get any error.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069267 has been updated - it has been assigned to Narekvar90.

**Comment by ThomasKranitsas** [comment]
@narekcat it's yours ;) Follow the same process on other tickets. Just comment on the ticket and I'll add you.

**Comment by narekcat** [comment]
@ThomasKranitsas Ok, thank you very much.

**Comment by ThomasKranitsas** [comment]
@narekcat  just checking on this. It's been 23 hours since you started working on it. Note that you can only keep a ticket for 24h then you have to open it for pickup again.

**Comment by narekcat** [comment]
@ThomasKranitsas I were busy last 24 hours, just can't complete another challenge, so won't be able to complete this. Please open it for others to pick it up. Sorry for inconveniences.

**Comment by ThomasKranitsas** [comment]
No worries!

@topcoder-platform/topcodercompetitors this is now available for pickup

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069267 has been updated - it has been assigned to gurmeetb.

**Comment by gurmeetb** [comment]
please assign me this

**Comment by gurmeetb** [comment]
@ThomasKranitsas I would like to open this for others, as I have tried few options but in vain.

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors this is now available

**Comment by gets0ul** [comment]
Please assign me.  
Thanks.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069267 has been updated - it has been assigned to gets0ul.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069267
