### ISSUE TITLE
[$20] Profile Settings - button text wrapping

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1156]
Buttons with longer labels seem to be wrapping.  Here is an example:

![image](https://user-images.githubusercontent.com/3812270/43914899-2709ed02-9bd7-11e8-9c50-75e0975720b6.png)

**Comment by cwdcwd** [comment]
Contest https://www.topcoder.com/challenges/30069249 has been created for this ticket.

**Comment by cwdcwd** [comment]
Contest https://www.topcoder.com/challenges/30069249 has been updated - the new changes has been updated for this ticket.

**Comment by cwdcwd** [comment]
Contest https://www.topcoder.com/challenges/30069249 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069249 has been updated - it has been assigned to lazybaer.

**Comment by gurmeetb** [comment]
@Thomas please assign me this

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069249 has been updated - it has been assigned to gurmeetb.

**Comment by gurmeetb** [comment]
@ThomasKranitsas Sorry I cannot change status to "Ready for review" - Kindly validate, it fixed and pushed in.

**Comment by ThomasKranitsas** [comment]
Will check.. Thanks!

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069249
