### ISSUE TITLE
[$100] Profile - Basic info validation

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1162]
Currently, the `Save Changes` button is enabled only when the form is valid but there's no indication about the required fields which is bad UX.

You need to:
- Add a `* Required` text with a small red (use `$tc-red-110`) font (use `11px`) next to the field label.
- Always keep the `Save Changes` button enabled.
- Mimic the validation error of the rest of the traits and show a similar message when there's a validation error in the basic info.

See here:
<img width="1445" alt="screen shot 2018-08-12 at 00 40 30" src="https://user-images.githubusercontent.com/4612921/43996292-6eb75872-9dc8-11e8-877c-707930219b06.png">

Those are the required fields:
- First name
- Last name
- Gender
- T-Shirt size
- Address information (all fields except `Address line 2`)
- Birthdate
- Current location

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors  new ticket available for pickup

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069282 has been created for this ticket.

**Comment by PrakashDurlabhji** [comment]
can you please assign it to me thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069282 has been updated - it has been assigned to PkDurlabhji.

**Comment by ThomasKranitsas** [comment]
Done

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069282 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji any update? Please remember that you can only keep a ticket for 24h.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas yes MR will be raised within few hrs.

**Comment by ThomasKranitsas** [comment]
Ok

**Comment by ThomasKranitsas** [comment]
Can I get an update, please?

**Comment by Gauravseta** [comment]
@ThomasKranitsas can i take this if prakashdurlabhji fails to? i can start working on it nowitself. thanks

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji any updates?

@Gauravseta sure, if @PrakashDurlabhji won't complete this, it's yours

**Comment by ThomasKranitsas** [comment]
@Gauravseta I'll wait 20 more minutes. Then the ticket is yours

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069282 has been updated - it has been assigned to gauravseta.

**Comment by ThomasKranitsas** [comment]
Since it's been a long time and I didn't get any response after many warnings, I'm removing @PrakashDurlabhji and I'm assigning @Gauravseta to this.

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
calling dibs in case you decide to move on :)

**Comment by urwithat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by suppermancool** [comment]
@ThomasKranitsas can i take this ticket if @Gauravseta fail? thanks

**Comment by Gauravseta** [comment]
@ThomasKranitsas i will complete this.

**Comment by Gauravseta** [comment]
@ThomasKranitsas . will soon raise PR.

**Comment by ThomasKranitsas** [comment]
Awesome! Thanks @Gauravseta

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please take a look into it?
how is it looking ? ok ? as it meets your requirement ? also it updates you on my progress
<img width="858" alt="untitled1" src="https://user-images.githubusercontent.com/16337895/44118206-fb5f6028-a032-11e8-86fa-3575a4e38017.png">

**Comment by ThomasKranitsas** [comment]
@cwdcwd what do you think on the above?

I believe the `* Required` text should be slightly smaller.

**Comment by Gauravseta** [comment]
@ThomasKranitsas Required text is 11px and label is 12px , thats why hardly any difference visible.
shall i make it 10 or 9px ? and paste screenshot?

**Comment by ThomasKranitsas** [comment]
yes, please

**Comment by Gauravseta** [comment]
@ThomasKranitsas screenshot with 10px.
<img width="858" alt="untitled2" src="https://user-images.githubusercontent.com/16337895/44118393-925a77d8-a033-11e8-9189-d2818fe44789.png">

**Comment by ThomasKranitsas** [comment]
Looks good to me

**Comment by Gauravseta** [comment]
@ThomasKranitsas screenshot with 9px.
<img width="859" alt="untitled3" src="https://user-images.githubusercontent.com/16337895/44118444-c086c62a-a033-11e8-82c0-d0dcfcfe93b3.png">

**Comment by ThomasKranitsas** [comment]
Let's go with 10px

**Comment by Gauravseta** [comment]
@ThomasKranitsas Also to my assumption on your requirements ,
this shud be error text in basic info.

"first name, last name , Gender , T shirt size , address information, Current location cannot be empty. Birth date is incomplete or have an invalid date".

kindly correct me if wrong so i can complete it as everything looks clear now.

**Comment by ThomasKranitsas** [comment]
Sounds correct to me

**Comment by Gauravseta** [comment]
@ThomasKranitsas will soon raise PR.

**Comment by ThomasKranitsas** [comment]
@Gauravseta any update?

**Comment by nauhil** [comment]
If @Gauravseta did not finish it on time, please assign me

**Comment by ThomasKranitsas** [comment]
Yes, of course. If @Gauravseta won't complete it, it's yours

**Comment by Gauravseta** [comment]
@ThomasKranitsas its done raising Pr within 20mins.

**Comment by ThomasKranitsas** [comment]
Sounds good, thank you

**Comment by Gauravseta** [comment]
@ThomasKranitsas shall i paste some screenshots here of validation?

**Comment by ThomasKranitsas** [comment]
Yeah, feel free to do that

**Comment by Gauravseta** [comment]
<img width="664" alt="untitled4" src="https://user-images.githubusercontent.com/16337895/44158956-bcbf5700-a0d3-11e8-9da7-4ed1cb34d831.png">

**Comment by Gauravseta** [comment]
@ThomasKranitsas i hope its at correct position and similar to education behaviour. m raising PR now.

**Comment by ThomasKranitsas** [comment]
Looks good

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069282

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please check this.

**Comment by Gauravseta** [comment]
@ThomasKranitsas thanks

**Comment by Gauravseta** [comment]
@ThomasKranitsas any more issues open for pickup soon? waiting .thanks

**Comment by ThomasKranitsas** [comment]
Maybe.. Not sure yet. I'll inform everyone if I open any new ticket
