### ISSUE TITLE
[$80] Profile - Fix flickering issue on the basic info page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1163]
Currently, when you open the `Basic Info` page in the `Profile` settings page, the page is re-rendering few times and until the page stops re-rendering and becomes stable, if the user changes anything, it will reset to the original value.

That creates a terrible UX.

This needs to be fixed so the page works smoothly and doesn't "flicker" anymore.

Video:
- http://take.ms/VKlHd

**Please note that I've never pressed the BACKSPACE key on the video.**
The field was just resetting as the component was probable re-rendering by it's parent component.

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket available for pickup

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069284 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069284 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
@Colinh84, please sign-up with Topcoder X tool

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069284 has been updated - it has been assigned to Colinh84.

**Comment by ekundayo-ab** [comment]
Hi @ThomasKranitsas can I get access to work on this issue?

**Comment by suppermancool** [comment]
hi @ThomasKranitsas can you assign me to this ticket?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069284 has been updated - it has been assigned to ekundayo.

**Comment by ThomasKranitsas** [comment]
@ekundayo-ab it's yours

**Comment by ThomasKranitsas** [comment]
@ekundayo-ab any progress on this? Please note that you can only keep a ticket for 24h. Then you have to open it for others to pick it up

**Comment by ekundayo-ab** [comment]
Hi @ThomasKranitsas how do I open it up back? also is there a way I can get access to work on tickets by assigning myself to issues any time so that I'm not blocked especially when I"m ready to work, since our time zones are different?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, please could you assign ticket to me ?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069284 has been updated - it has been assigned to kevin.crain.

**Comment by ThomasKranitsas** [comment]
@ekundayo-ab no, I don't think so. You'll have to comment on the ticket.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas I am not getting the same issue as shown in the video from this issues description, please see verification video here -> https://youtu.be/82Ajnep4Jm0

**Comment by ThomasKranitsas** [comment]
@KevinLeigh to reproduce the issue, you need to start typing immediately when the page loads. If you leave it for few seconds, it'll load completely so it won't flicker

**Comment by KevinLeigh** [comment]
Thank you for the update Thomas, I will re-test, maybe we should disable short bio field until the page is fully loaded? That should fix the issue.

**Comment by KevinLeigh** [comment]
I will also try remove those multiple renders as that cannot be good :)

**Comment by KevinLeigh** [comment]
The issue looks like `componentWillReceiveProps` is being called multiple times and calls setState every time which afterwards render gets called each time. I will see if I can reduce `componentWillReceiveProps` calls or try only get page to render on the last call to `componentWillReceiveProps`, cause it looks like we still need `componentWillReceiveProps` for the page to fully function.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey there, I have managed to significantly reduce multiple rendering issue on screen `settings > profile > basic info`, please see PR here -> https://github.com/topcoder-platform/community-app/pull/1172

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069284 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069284
