### ISSUE TITLE
[$30] Profile - Fix member statistics layout

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1164]
As you can see in the image below, each statistics group is centered and has a fixed width which doesn't look good.

<img width="1445" alt="screen shot 2018-08-12 at 01 19 49" src="https://user-images.githubusercontent.com/4612921/43996558-e7c5ef30-9dcd-11e8-8afd-64e54e5e74f1.png">

You need to fix that so it matches the current implementation of the live site (https://www.topcoder.com/members/thomaskranitsas/)

Example:
<img width="1445" alt="screen shot 2018-08-12 at 01 21 59" src="https://user-images.githubusercontent.com/4612921/43996575-3ef94310-9dce-11e8-9d46-edb0c0094311.png">

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069286 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069286 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas i can't assign myself to this ticket or change the label, pls give me permission, thanks

**Comment by meggamind** [comment]
working on this, please assign it to me

**Comment by ThomasKranitsas** [comment]
@meggamind are you registered on this https://www.topcoder.com/challenges/30069264?tab=details challenge?
If not please register and follow the link from the challenge forum otherwise I can't add you to any ticket

**Comment by gurmeetb** [comment]
is this still open for pickup? if yes, kindly assign me as i am already registered on challenge. Thanks.

**Comment by Gauravseta** [comment]
@ThomasKranitsas even m registered on this challenge u can assign it to me too.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069286 has been updated - it has been assigned to gurmeetb.

**Comment by ThomasKranitsas** [comment]
@gurmeetb I'm assigning this to you as I haven't heard back from @meggamind and you asked first

**Comment by gurmeetb** [comment]
Thanks - working on it now

**Comment by gurmeetb** [comment]
@ThomasKranitsas It is coming up fine for me - https://cl.ly/2I3u2a162i3r 

Kindly suggest if I am not looking at right place ?

**Comment by ThomasKranitsas** [comment]
@gurmeetb example: https://community-app.topcoder-dev.com/members/TonyJ

**Comment by ThomasKranitsas** [comment]
I get the same when I run the app locally.
Note that the production site shows the legacy page which doesn't have that issue.

**Comment by meggamind** [comment]
@ThomasKranitsas it was night here when you messaged. Was sleeping that’s why I didn’t reply? Also I was registered for the challenge already that’s I came here to the bugs. anyways isn’t there a 24 hour wait period ? You waited 8 hours. Lol

**Comment by ThomasKranitsas** [comment]
Sorry @meggamind but your account doesn't show up in the assignees list until you use the link I posted on the challenge forum to register to our Topcoder-X platform which means I can't really give you any ticket until you register there.
As you can see in the other ticket's I'm waiting for 24h before I remove anyone from a ticket.

The 24h wait period starts when you pick up a ticket (when I assign you a ticket).

If @gurmeetb hasn't started yet, I'm ok assigning this ticket to you.

**Comment by gurmeetb** [comment]
@thomas - it’s fine, kindly fee free to reassign to @meggarmind, i will pick up something else.

**Comment by ThomasKranitsas** [comment]
@meggamind are you still interested on this?

**Comment by ekundayo-ab** [comment]
@ThomasKranitsas can you assign me to this ticket?

**Comment by suppermancool** [comment]
@ThomasKranitsas can you assign me to this ticket?

**Comment by ThomasKranitsas** [comment]
You're both assigned to another ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas i finished https://github.com/topcoder-platform/community-app/issues/1047, pls assigned me to this ticket

**Comment by suppermancool** [comment]
@ThomasKranitsas pls add me to the ticket https://github.com/topcoder-platform/community-app/issues/1167 first

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069286 has been updated - it has been assigned to daga_sumit.
