### ISSUE TITLE
[$140] Profile - Change skills implementation in settings page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1167]
<img width="1402" alt="screen shot 2018-08-13 at 12 59 28" src="https://user-images.githubusercontent.com/4612921/44025412-c07a42e2-9ef8-11e8-9e93-cc98a8388fa6.png">

Currently, the app saves the skills as `traits`.

You need to update the logic of that page to save the skills in the same way as the legacy app (https://github.com/appirio-tech/topcoder-app/).

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket available for pickup

**Comment by suppermancool** [comment]
@ThomasKranitsas pls add me to this ticket

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
if you could add me to one of the tickets you are not adding @suppermancool to :)

**Comment by ThomasKranitsas** [comment]
@suppermancool it's yours

@sumitdaga which one do you want?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069326 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069326 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069326 has been updated - it has been assigned to diazz.

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
only two tickets have open-for-pickup label ...not sure if they are actually available!

**Comment by ThomasKranitsas** [comment]
Does it work if you run the app against the production API?

My guess is that the dev db is not populated properly so the skills are missing there.

**Comment by suppermancool** [comment]
i check in the project https://github.com/appirio-tech/topcoder-app/, it use the same api for getting list but different parameter and it return empty
https://api.topcoder-dev.com/v3/tags/?filter=domain%3DSKILLS%26status%3DAPPROVED

**Comment by ThomasKranitsas** [comment]
This one https://api.topcoder-dev.com/v3/tags/ returns all skills

**Comment by suppermancool** [comment]
@ThomasKranitsas the production work. Can i do base on production api?

**Comment by ThomasKranitsas** [comment]
yes

**Comment by suppermancool** [comment]
@ThomasKranitsas fixed in https://github.com/topcoder-platform/community-app/pull/1169, pls check with production api

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069326 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Thanks @suppermancool!
I've also increased the payment a bit.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069326
