### ISSUE TITLE
Veterans - Learn Page [Launch Contentful]

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1174]
I have recreated the Learn page from: https://veterans.topcoder.com/learn in Contentful

I'm pretty sure everything is formatted correctly although it looks messed up in Preview mode (as does the Veterans home so I feel like it is ok).

The only thing that may need to be reviewed is that the join button on the Learn page needs to be blue, but I feel as thought it will be rendered grey.

**Comment by birdofpreyru** [comment]
It made it to prod, thus closing the ticket.
