### ISSUE TITLE
[$20] Profile - user challenges style issue

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1175]
## Steps to reproduce

- Go to https://community-app.topcoder.com/members/thomaskranitsas/details/?track=DEVELOP&subTrack=CODE&tab=challenges
- Click on the menu icon to toggle the tracks.
- Observe. The `Winner` tags are shown on top.

<img width="1378" alt="screen shot 2018-08-14 at 23 01 40" src="https://user-images.githubusercontent.com/4612921/44115304-38935a70-a016-11e8-957f-413184a02406.png">
<img width="1378" alt="screen shot 2018-08-14 at 23 01 44" src="https://user-images.githubusercontent.com/4612921/44115312-3bf75edc-a016-11e8-8f07-e42724fa02f9.png">

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069473 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069473 has been updated - the new changes has been updated for this ticket.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, am I allowed to pick up more than one ticket ?

**Comment by KevinLeigh** [comment]
I can fix this one quite quickly :)

**Comment by ThomasKranitsas** [comment]
No, you have to finish your ticket to pick up the next one

**Comment by ThomasKranitsas** [comment]
Or, you can leave your ticket to pickup another one

**Comment by KevinLeigh** [comment]
All good will finish the one I am working on now, it is performance related with a lot of testing and profiling so I do not think I will be done in time to pick up this issue.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you Thomas, I will do my best to finish performance issue as quick as possible.

Please see PR for this issue here -> https://github.com/topcoder-platform/community-app/pull/1176

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069473
