### ISSUE TITLE
[$15] Profile - Style issue when deleting a long link

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1177]
See screenshot:

<img width="1326" alt="screen shot 2018-08-14 at 23 41 31" src="https://user-images.githubusercontent.com/4612921/44117320-a664807e-a01b-11e8-8454-c1d3b2aaeb3b.png">

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069495 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069495 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas pls assigned to me

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069495 has been updated - it has been assigned to diazz.

**Comment by suppermancool** [comment]
@ThomasKranitsas pls check https://github.com/topcoder-platform/community-app/pull/1178, thanks

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069495
