### ISSUE TITLE
[$80] Profile - Issue when visiting another member's profile

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1192]
Video: http://take.ms/nxlLM9

As you can see in the video above, when you visit a profile then go back (without refreshing the page or doing a fresh load of the page) and then visiting another profile, the app shows the data from the previous profile and it changes the data as it's loading the new one which looks odd.

This needs to be fixed.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069535 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069535 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas : Can you assign me this ticket,

**Comment by suppermancool** [comment]
@ThomasKranitsas : Can you assign me this ticket,

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069535 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
@suppermancool it's your but please fix your open PRs before you work on this.

Thanks

**Comment by Gauravseta** [comment]
@ThomasKranitsas can i take this? as supermancool wud be busy in solving open PR.

**Comment by sumitdaga** [comment]
or me :)
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
@suppermancool sure, the ticket has your name ;)

**Comment by suppermancool** [comment]
hi @ThomasKranitsas i updated the topcoder-react-lib for supporting action for clearing profile, pls check this PR first
https://github.com/topcoder-platform/topcoder-react-lib/pull/21

**Comment by suppermancool** [comment]
PR for this issue is done at
https://github.com/topcoder-platform/community-app/pull/1201
pls check

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069535
