### ISSUE TITLE
[$30] Profile - Hobby - Textarea resize issue

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1197]
- When you focus on the textarea, it changes size.
<img width="1455" alt="screen shot 2018-08-15 at 16 56 58" src="https://user-images.githubusercontent.com/4612921/44151801-48c4016a-a0ac-11e8-87bf-b07201909b06.png">

- When you resize the textarea, you can easily break the layout.
<img width="1455" alt="screen shot 2018-08-15 at 16 57 07" src="https://user-images.githubusercontent.com/4612921/44151808-4b0f33cc-a0ac-11e8-83e0-2de26ced7c85.png">

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069537 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069537 has been updated - the new changes has been updated for this ticket.

**Comment by gets0ul** [comment]
Please assign me.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069537 has been updated - it has been assigned to gets0ul.

**Comment by gets0ul** [comment]
"When you focus on the textarea, it changes size."
Cannot reproduce this one. The textarea is just fine whenever I focus on it.
Can you check it again? Thanks

**Comment by ThomasKranitsas** [comment]
I'm using the grammarly chrome extension so maybe that's causing the issue.

If you force the textarea to be 100% it'll solve the issue

**Comment by gets0ul** [comment]
Can you share the screencast when focusing the textarea?
Because I'm unable to reproduce it. The textarea size is just fine, it is not shrinking or enlarging when focused.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069537
