### ISSUE TITLE
Challenge API to My Challenges Bucket

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1203]
Currently, this endpoint is servicing member challenges but challenge data model is different from the standard listing data model

`https://api.topcoder.com/v4/members/{id}/challenges/`

I want to unify this with the standard listing data model, one difference I do find here is `userDetails` object @birdofpreyru what are restrictions posed on roles

@skyhit do you find any creative to solve this problem? 

I was thinking to add userDetails to standard data model

**Comment by birdofpreyru** [comment]
@sushilshinde as I remember, UI relies on roles to decide, which buttons and links to show at challenge details page, and in dashboard (like forum, register / submit / OR / Direct / etc).

**Comment by sushilshinde** [comment]
ok thanks @birdofpreyru
