### ISSUE TITLE
Problem with Review Opportunity page

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/community-app#1205]
Recently in multiple instances, there is always problem with review opportunities page.

Though the challenge shows up in the review opportunity listing page, If I click on the individual challenge apply option, It loads an empty page with lot of console errors.

All of sudden after some hours, If I check the page it would have started working properly. Not sure what is happening and the behaviour is seen in all recently launched challenges.

E.g. It's blank now - https://www.topcoder.com/challenges/30067403/review-opportunities

When this challenge (https://www.topcoder.com/challenges/30069379/review-opportunities) was launched, it was having issue for hours and now it loads fine.

**Comment by sharathkumaranbu** [comment]
It started working now. Couldn't understand why there is a lag.

**Comment by ajefts** [comment]
@ThomasKranitsas is this likely due to health issues with the backend services?

**Comment by ThomasKranitsas** [comment]
Fixed
