### ISSUE TITLE
[$60] Profile - Deleting an entry in the user traits should show the user consent popup

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1208]
## Current behavior
Currently, if you edit anything in the profile settings page, the app will show the user consent popup.

If you delete any entry (eg a hobby) it won't show the user consent popup.

## Expected behavior
The app should show the user consent popup when deleting an entry.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, I would like to pick up issue :)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069648 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069648 has been updated - it has been assigned to kevin.crain.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you, much appreciated

**Comment by ThomasKranitsas** [comment]
The other ticket is under review.

If @KevinLeigh won't complete this ticket, it's yours.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas @Gauravseta Hey Guys, I have started working on issue now, I have been super busy, I should be complete in 30 - 45 mins :)

**Comment by KevinLeigh** [comment]
Done, here is the PR -> https://github.com/topcoder-platform/community-app/pull/1210

**Comment by Gauravseta** [comment]
@thomaskranitsas any issues open for pickup?

**Comment by ThomasKranitsas** [comment]
@Gauravseta we don't have any other tickets right now. Feel free to open a new ticket if you find any issue with the member profile page or the settings page.

**Comment by Gauravseta** [comment]
sure

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069648 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069648
