### ISSUE TITLE
Details page broke on Beta-v4 : mm-features-experiments branch

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1212]
For these results

`https://beta-community-app.topcoder.com/challenges?filter[tracks][data_science]=true&bucket=past`

Details page doesn't work, here is an example

`https://beta-community-app.topcoder.com/challenges/17230`

<img width="685" alt="screen shot 2018-08-17 at 9 38 16 am" src="https://user-images.githubusercontent.com/683231/44247331-4b7dc200-a201-11e8-938f-bb6aa097d5ba.png">

Probably latest merge might have caused this issue @birdofpreyru

**Comment by birdofpreyru** [comment]
Fixed
