### ISSUE TITLE
[$60] Profile - Issue with change email functionality 

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1213]
Once you type in a new email and hit `send verification email`  ...a green box pops up which says `your account information has been updated` and the button changes to `send verification email` again.
Clicking on which again shows the same message and so on.

## Expected behavior

- The `Send verification email` button should be hidden once you click it.
- The notification should say `Verification email sent. Please check your inbox.`.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069729 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069729 has been updated - the new changes has been updated for this ticket.

**Comment by sumitdaga** [comment]
can you assign it to me?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069729 has been updated - it has been assigned to daga_sumit.

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
please check the PR and let me know if i have missed something

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069729 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069729
