### ISSUE TITLE
[$30] Profile - Fixes on the skills page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1223]
## Screenshot:
<img width="1361" alt="screen shot 2018-08-18 at 22 19 57" src="https://user-images.githubusercontent.com/4612921/44302605-12df0500-a335-11e8-8d6e-31d53f34da25.png">

## Current behavior

The skills are shown twice which makes the page too long.

## Expected behavior

- We should only show the skills under the `Your skills` section
- Reduce the bottom margin of each skill to `55px`

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Please assign to me :)

**Comment by Gauravseta** [comment]
@thomaskranitsas can you please assign to me

**Comment by ThomasKranitsas** [comment]
It was assigned to @KevinLeigh

**Comment by Gauravseta** [comment]
@thomaskranitsas i guess kevin already working on another issue.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069753 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069753 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069753 has been updated - it has been assigned to kevin.crain.

**Comment by ThomasKranitsas** [comment]
The other tickets are ready to be merged. I'm just holding them because I need confirmation from the PM on those.

**Comment by Gauravseta** [comment]
@thomaskranitsas any more to come from ur side  ? or i need to search on my own?

**Comment by ThomasKranitsas** [comment]
None at the moment but we will probably run a second round of bug bash soon.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Basically done, however I cannot test my changes because I am getting an error while adding a skill, is there maybe a test account with skills added to that I can use to login to locally and test changes ?

- Current error while adding a skill:

<img width="1190" alt="screen shot 2018-08-18 at 21 49 56" src="https://user-images.githubusercontent.com/32452072/44302825-ed4ffc80-a330-11e8-9a07-3625418b3122.png">

**Comment by ThomasKranitsas** [comment]
You can run `sudo NODE_CONFIG_ENV=production PORT=80 npm run dev` to run the app locally against the production API which works perfectly fine and test with your account.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas After command unfortunately I get unauthorised screen now, which I have fixed for a local develop build already.

**Comment by KevinLeigh** [comment]
<img width="1166" alt="screen shot 2018-08-18 at 22 01 31" src="https://user-images.githubusercontent.com/32452072/44302896-83385700-a332-11e8-8772-2b2b0ace5e57.png">

**Comment by ThomasKranitsas** [comment]
Oh, that's because you need to add `127.0.0.1	local.topcoder.com` to your hosts file (`/etc/hosts`) and then visit local.topcoder.com (without the `-dev` suffix)

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you for the update, I am getting the same issue with url `http://local.topcoder.com/settings/profile`, maybe it could be because I need to use alternative Contentful values for CONTENTFUL_CDN_API_KEY, CONTENTFUL_PREVIEW_API_KEY & CONTENTFUL_SPACE_ID ?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you so much for the help, and I understand :). Please see PR here -> https://github.com/topcoder-platform/community-app/pull/1226

**Comment by ThomasKranitsas** [comment]
Thanks @KevinLeigh for the quick fix!

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069753

**Comment by KevinLeigh** [comment]
Anytime @ThomasKranitsas :)
