### ISSUE TITLE
Blockchain and cognitive sites not recognizing membership

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1227]
I'm a member of the groups, but when I visit the sites it's not showing me as registered for the community.

**Comment by ajefts** [comment]
@birdofpreyru can you check this one?

fyi @cwdcwd

**Comment by cwdcwd** [comment]
this in the current UI or the new profile stuff @ajefts ?

**Comment by ajefts** [comment]
@cwdcwd  It's in the current UI and blockchain.topcoder.com and cognitive.topcoder.com.  

Currently, I'm in the blockchain group and when I visit blockchain.topcoder.com it should not be showing me the "Join Now" option:

![image](https://user-images.githubusercontent.com/3812270/44398221-1dee8c80-a511-11e8-8e06-d5676e525b63.png)

If I try to join (again), it does this because I'm already in the group:

![image](https://user-images.githubusercontent.com/3812270/44398240-3199f300-a511-11e8-9055-e7281523d4f4.png)
