### ISSUE TITLE
[$20] Profile - hide some tabs for now

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1228]
Edited:  Please hide education/work/organization/language from the UI for now.

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket

**Comment by PrakashDurlabhji** [comment]
@thomaskranitsas can u please assign it to me

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069818 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069818 has been updated - it has been assigned to PkDurlabhji.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069818 has been updated - the new changes has been updated for this ticket.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas can you please provide tonyj id password to login? thanks

**Comment by ThomasKranitsas** [comment]
TonyJ/appirio123

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas its ready for review.Mr raised

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069818
