### ISSUE TITLE
[$50] Profile - Communities not working

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1229]
When I load the communities page, it should be showing me as a member of the communities I'm in.  However, it's not.  For example, I'm in blockchain and cognitive, but this is what I see:

![image](https://user-images.githubusercontent.com/3812270/44363718-fb1d9300-a492-11e8-8342-b559c05e548a.png)

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket!

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069815 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069815 has been updated - the new changes has been updated for this ticket.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, please could you assign me this ticket?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069815 has been updated - it has been assigned to kevin.crain.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you, which branch should I work off for the new bugs ?

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors please use the “develop” branch

**Comment by KevinLeigh** [comment]
Perfect will do 👍

**Comment by KevinLeigh** [comment]
@ThomasKranitsas 

Without any changes the competitions load properly and also toggling community works properly and persists if I reload. 

I am testing in development environment, which leads me to suspect that maybe in production something is going wrong with the database / persistence layer.

<img width="1191" alt="screen shot 2018-08-20 at 23 10 29" src="https://user-images.githubusercontent.com/32452072/44366840-4bfead00-a4ce-11e8-8e0c-29cc25e58bf9.png">

**Comment by ThomasKranitsas** [comment]
Do we get the data from the Groups API or from the user traits?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas We get it from Groups API

**Comment by ThomasKranitsas** [comment]
Interesting... @ajefts can you provide more info on how to reproduce the issue?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, any update on the above issue ?

**Comment by ThomasKranitsas** [comment]
@ajefts is there any issue with the Groups API?

Even https://blockchain.topcoder.com/ doesn't work for me.
I always get `failed to join` with 400 Bad Request

cc @cwdcwd

**Comment by ajefts** [comment]
This seems to be working now @ThomasKranitsas .  I think it was an issue with the groups api...

**Comment by ThomasKranitsas** [comment]
Ok, closing this one as there's no issue

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069815

**Comment by ThomasKranitsas** [comment]
[400]: Failed to update challenge. Detail: javax.ejb.EJBTransactionRolledbackException

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069815 has been updated - the new changes has been updated for this ticket.
