### ISSUE TITLE
[$20] Profile - remove some communities

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1230]
Remove IOS and Predix communities from the options list on the communities tab.

![image](https://user-images.githubusercontent.com/3812270/44363741-0ec8f980-a493-11e8-9a1a-c35aa2d73e4b.png)

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket!

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069813 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069813 has been updated - the new changes has been updated for this ticket.

**Comment by nqviet** [comment]
@ThomasKranitsas:
can you assign this ticket to me?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069813 has been updated - it has been assigned to nqv2018.

**Comment by nqviet** [comment]
@ThomasKranitsas : 
PR is ready

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069813
