### ISSUE TITLE
[$30] profile - uploading profile pic

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/community-app#1231]
It works but doesn't refresh the picture so it doesn't look like it works.

Definitly low priority

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket

**Comment by rashmi73** [comment]
@thomaskranitsas i work on this..pleae assign thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069821 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069821 has been updated - it has been assigned to rashmi73.

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
please assign it to me when you decide to move on!

**Comment by rashmi73** [comment]
@thomaskranitsas i will surely solve it this time.please give some time..i am working on it

**Comment by ThomasKranitsas** [comment]
Sure, thanks for the update

**Comment by rashmi73** [comment]
@ThomasKranitsas PR done.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069821
