### ISSUE TITLE
[$40] profile -- languages

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/community-app#1232]
Fine to leave for now but should this be some sort of type ahead?

**Comment by ThomasKranitsas** [comment]
Hmm, I thought about that but there are actually too many languages.. do we really need that? I think it will be easier for a member to just type the language that we may have missed in our list

**Comment by ThomasKranitsas** [comment]
@ajefts @urwithat @dmessing thoughts?

**Comment by urwithat** [comment]
Languages as drop down would be too many to handle. Lets keep it as a Text box @dmessing

**Comment by ajefts** [comment]
I don't think the list is that long...?    https://datahub.io/core/language-codes

If we don't restrict the selection (I'd use a type ahead like we do for country) then it will make reporting and filtering very difficult.  We'll have dirty data...

**Comment by ThomasKranitsas** [comment]
@ajefts Ok, I'll make that change on the backend and I'll then open this for pickup

**Comment by Gauravseta** [comment]
@thomaskranitsas after that can u please assign it to me? thanks

**Comment by ThomasKranitsas** [comment]
Sure

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070024 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070024 has been updated - it has been assigned to gauravseta.

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please clarify if my understanding is correct?

1. I need to add language field same as country field? exactly below the country field?
2. or i need to add just simple textbox of language field?

screenshot for reference: i need to add language field below country? correct?
<img width="676" alt="issue_1232" src="https://user-images.githubusercontent.com/16337895/44628071-0bcc7e00-a957-11e8-9616-4f7e089abb61.png">

**Comment by Gauravseta** [comment]
@ThomasKranitsas thanks..i saw it ..everything clear till  now, mostly PR within few hrs unless any question.

**Comment by Gauravseta** [comment]
@ThomasKranitsas i forgot to submit issues list..will i be eligible for prize of 1000$ or it was just indicative?

**Comment by ThomasKranitsas** [comment]
The price on the challenge was indicative based on the total $ from all tickets. It was mentioned in the challenge spec that there will be no winner on the challenge but we'll pay everyone per accepted ticket.

**Comment by ThomasKranitsas** [comment]
@Gauravseta any update on this?

**Comment by Gauravseta** [comment]
@thomaskranitsas its near to done..raising PR within few hrs

**Comment by ThomasKranitsas** [comment]
ok, thanks

**Comment by PrakashDurlabhji** [comment]
@thomaskranitsas can i get this if gauravseta fails?

**Comment by Gauravseta** [comment]
@PrakashDurlabhji  it will be completed , i wont fail

**Comment by ThomasKranitsas** [comment]
@Gauravseta any update?

**Comment by Gauravseta** [comment]
@ThomasKranitsas raising PR its done

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30070024
