### ISSUE TITLE
[$10] profile -- personalization spelled differently in on paragraph

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/community-app#1233]
You can opt out from personalisation any time in the future in at Preferences > Personalization.

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket!

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069824 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069824 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069824 has been updated - the new changes has been updated for this ticket.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas can u please assign it to me thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069824 has been updated - it has been assigned to PkDurlabhji.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas MR ready

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas any more open for pickup? within 15 minutes if u are planning to?

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069824
