### ISSUE TITLE
[$20] Profile - Skill dropdown sort

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1235]
Sort the list alphabetically.

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069826 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069826 has been updated - the new changes has been updated for this ticket.

**Comment by gets0ul** [comment]
Please assign me.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069826 has been updated - it has been assigned to gets0ul.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069826
