### ISSUE TITLE
Add link on homepage to All challenges 

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#124]
On the topgear homepage, add a link to the topgear challenges page with the All community filter on.

**Comment by ajefts** [comment]
@birdofpreyru can you do this one today?  ANy ideas on a good place to incorporate a link that says something like "View All Public Challenges"?

**Comment by birdofpreyru** [comment]
@ajefts Yeap, I can do it shorly.
Probaby right below the statistics block, in the center of the page?

**Comment by birdofpreyru** [comment]
Or, might be better under the block with the pictures.
