### ISSUE TITLE
Unregistered challenges are reflecting under this URL https://topgear.topcoder.com/challenges?bucket=my

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1244]
User handle: SU394347

A user registered for 4 challenges previously but unregistered from 2, but still its showing as 4 against my challenges. Please assist in correcting the same.

URL: https://topgear.topcoder.com/challenges?bucket=my 

<img width="956" alt="topcoder" src="https://user-images.githubusercontent.com/34749364/44476184-9ad64f00-a654-11e8-88fd-4d7e98662e9b.PNG">

**Comment by birdofpreyru** [comment]
This should be a caching problem in API.
