### ISSUE TITLE
Submission - Change confirmation page text

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1250]
Please change the text on the confirmation page that presents after you submit to:

Current Text:

![image](https://user-images.githubusercontent.com/3812270/44587563-55fc0680-a781-11e8-9fbc-5422f3e7d177.png)

New Text:

"Thanks for participating! We’ve received your submission. Once the review process starts you'll receive an email with some more information. In the meantime, stay tuned into the forum for any real time updates."

Also, let's see how it looks if we remove the coderbot image.  Feedback is that it looks too much like an error page...

**Comment by ajefts** [comment]
@cwdcwd I'd actually prefer to have a confirmation email sent upon successful upload/processing as the original page states, but that can be done later.  I think the email helps build confidence that we actually did receive the submission.  With all the issues we've had historically, people don't quite trust the process and this is our chance to change that.

**Comment by nithyaasworld** [comment]
@ajefts The confirmation message remains the same. That is, it says "Thanks for participating! We’ve received your submission and will send you an email shortly to confirm and explain what happens next."

Member also receives Submission confirmation email as below:

![image](https://user-images.githubusercontent.com/5114190/59760987-39513200-92b1-11e9-8d6c-63f24e677ca6.png)

>Also, let's see how it looks if we remove the coderbot image. Feedback is that it looks too much like an error page...
Very much agree on this! We will remove the coderbot image as part of this ticket.

Please let us know if we should make any changes to the submission confirmation phrase.

Thanks.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
