### ISSUE TITLE
Submission - Remove preview from My Submissions

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1251]
Until we have a way to show it, please remove the preview image column in the table below.

![image](https://user-images.githubusercontent.com/3812270/44588125-e38c2600-a782-11e8-8131-290b6bdac173.png)

**Comment by Gauravseta** [comment]
@thomaskranitsas can this assigned to me once it is open for pickup? thanks

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
