### ISSUE TITLE
Submission - Submission dates not showing on challenge page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1254]
With the new submission page in dev, I'm not seeing the submission dates when I upload a submission.

For example, on this challenge I have submitted to round 1:

![image](https://user-images.githubusercontent.com/3812270/44604299-675e0680-a7b3-11e8-9eec-241081fe01a9.png)

**Comment by PrakashDurlabhji** [comment]
@thomaskranitsas please assign me in future. i wish to work on it.
