### ISSUE TITLE
[$30] Profile - Basic info fixes

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1256]
- `Optional` tags should be removed as they make the design inconsistent.
- If the `birthDate` is not defined we should not try to convert it to `ISOString`

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070029 has been created for this ticket.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas can i get thhis?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30070029 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment]
I've already fixed that :) I'll push the code in a bit

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas ok np. can i get something else? waiting for it

**Comment by ThomasKranitsas** [comment]
Currently, we don't have any other tickets but we'll open new tickets as we find any bugs. Feel free to search the new Settings page for bugs and create new tickets if you want.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30070029
