### ISSUE TITLE
[$20] Profile - Issue with empty gender/tShirtSize

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1258]
If the `gender` or the `tShirtSize` is `''` the backend is returning `400 Bad Request`.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas can i get this?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas even i will raise PR immediately

**Comment by ThomasKranitsas** [comment]
I thought the PR would come immediately

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas raising it 2 min done

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas PR raised

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30070032
