### ISSUE TITLE
Profile - default value for t-shirt size

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1272]
**Describe the bug**
Please make sure the t-shirt size is not defaulted to a value.  When I loaded my profile, it was defaulted to "S".  

**Expected behavior**
We should default to "Not Selected" so the user doesn't unknowingly save the wrong value.

**Screenshots**

![image](https://user-images.githubusercontent.com/3812270/45057006-7457e100-b062-11e8-8f15-c6dd535feede.png)

**Comment by Gauravseta** [comment]
@ThomasKranitsas can i get this if ever made open for pickup?

**Comment by ThomasKranitsas** [comment]
I've already fixed it. I'll push the code in a few minutes.

**Comment by ThomasKranitsas** [comment]
@ajefts should be fixed in https://github.com/topcoder-platform/community-app/commit/ca12b024727756f5eb8c5eb3e69ea288d2ab8ab3
