### ISSUE TITLE
Profile - Can't set country

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1273]
**Describe the bug**
When I try to set my country to "United States" or any other country, it's not allowing me to set it.  The result is that I can't save my basic info.

**To Reproduce**
1. Go to https://community-app.topcoder.com/settings/profile
2. Pick United States for address country.
3. Save

**Expected behavior**
Country should be set and profile updated.

**Screenshots**

![image](https://user-images.githubusercontent.com/3812270/45057199-02cc6280-b063-11e8-9598-5c448c06a92a.png)

**Comment by ThomasKranitsas** [comment]
@ajefts dev or prod? My backend changes weren't pushed to prod yet

**Comment by ThomasKranitsas** [comment]
Oh, I see it now.. It's a frontend issue. I'll fix it shortly

**Comment by Gauravseta** [comment]
@ThomasKranitsas can i get this or something elsE?

**Comment by ThomasKranitsas** [comment]
I've already fixed this. I'll push the code shortly

**Comment by ThomasKranitsas** [comment]
@ajefts should be fixed in https://github.com/topcoder-platform/community-app/commit/ca12b024727756f5eb8c5eb3e69ea288d2ab8ab3
