### ISSUE TITLE
Profile - Email change validation

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1274]
**Describe the bug**
When changing my email, it's preventing me due to a validation error but the email is valid.

**To Reproduce**
1. Go to https://community-app.topcoder.com/settings/account
2. Click on 'Change Email'
3. Enter an email address with '+' in it, foo+bar@example.com
4. See validation error

**Expected behavior**
valid emails should be accepted.  Please use the same validation that we use in Accounts App.

**Screenshots**
![image](https://user-images.githubusercontent.com/3812270/45057557-e8df4f80-b063-11e8-8775-d023cf9cb510.png)

**Comment by ThomasKranitsas** [comment]
@ajefts should be fixed in https://github.com/topcoder-platform/community-app/commit/ca12b024727756f5eb8c5eb3e69ea288d2ab8ab3
