### ISSUE TITLE
Profile - can't link accounts

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1276]
**Describe the bug**
When attempting to link an account (github, stackoverflow, etc.), it fails.  See screenshot.

**To Reproduce**
1. Go to https://community-app.topcoder.com/settings/account
2. Click on Linked Accounts
3. Try to link any account

**Expected behavior**
Account should get linked to profile.

**Screenshots**

![image](https://user-images.githubusercontent.com/3812270/45059797-40cd8480-b06b-11e8-90a5-bc16b22dfa86.png)

**Comment by ThomasKranitsas** [comment]
@ajefts which link did you use? I just added `http://github.com` with no issues

**Comment by cwdcwd** [comment]
@ajefts did you see anything on the console when that happened?

**Comment by ajefts** [comment]
no, there was nothing...

**Comment by ajefts** [comment]
maybe there is bad data in the db for my account...?

**Comment by ThomasKranitsas** [comment]
I tried with `TonyJ/appirio123` on dev and worked fine.

**Comment by ajefts** [comment]
Can you try prod?

**Comment by ThomasKranitsas** [comment]
It worked when I tried with `https://github.com` but not with `https://github.com/ThomasKranitsas` 🤔 But that looks like a validation issue not like the one you're having.

**Comment by nithyaasworld** [comment]
@ajefts Can you please confirm if this is still an issue for your account? 

I just tried linking  stackoverflow and bitbucket accounts and it went smooth. My github is already linked, so couldn't verify if a new github linking works good.

Thanks.
