### ISSUE TITLE
Contentful error 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1280]
On branch - https://github.com/topcoder-platform/community-app/tree/mm-feature-experiment

I get this error and it kills the page 

<img width="1497" alt="screen shot 2018-09-06 at 3 42 20 pm" src="https://user-images.githubusercontent.com/683231/45151334-a0eb3480-b1eb-11e8-8fc5-95625e917afd.png">

**Comment by birdofpreyru** [comment]
CMS access tokens should be explicitly set to give a locally running app access to most of the segments. Tokens can be found in CMS (_Space settings_ > _API Keys_ > _Temporary - Community App Dev_), and **MUST NOT** be commited to the repo. **README.md** should be updated to mention this info.
