### ISSUE TITLE
Contentful Dashboard Announcements Preview - BROKEN

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1282]
**Describe the bug**
Cannot Preview Dashboard Announcements

**To Reproduce**
1. Go to any Dashboard Announcement (this for example: https://app.contentful.com/spaces/b5f1djy59z3a/entries/40DbhtCuf6YMGEuoGMGwwq)
2. Click "Preview"

**Expected behavior**
A preview of the banner

**Screenshots**
<img width="1305" alt="screen shot 2018-09-06 at 11 28 53 am" src="https://user-images.githubusercontent.com/1373998/45177529-1513e100-b1c8-11e8-95e3-bda958c7c4ce.png">

**Desktop (please complete the following information):**
 - OS:  OSX
 - Browser:  Chrome
 - Version:  Latest

**Comment by hokienick** [comment]
@sushilshinde @cwdcwd - @birdofpreyru may know more about this though

**Comment by birdofpreyru** [comment]
I believe, it was resolved by the recent fix related to broken links to some of images coming from CMS.
