### ISSUE TITLE
Update the error message on the review opportunity details page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1284]
Design: https://marvelapp.com/3d4dd93/screen/47541771/handoff

**Comment by Gauravseta** [comment]
@ThomasKranitsas can  i get  a chance?

**Comment by ThomasKranitsas** [comment]
Hi @Gauravseta ! This is not open for pickup. It's a fix I have to do on my code from some recent changes I made.

Thanks for offering though!

**Comment by Gauravseta** [comment]
@ThomasKranitsas ok np. waiting for if any in future
