### ISSUE TITLE
Slider's Not Accepting images unless at specific size

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1285]
**Describe the bug**
When using images in Slider's, the slider does not display the image I believe because of the size it was uploaded in.  For example, the image for blockchain that worked when it was just one banner is 1280 x 470 as other banners are.  The second slide DOES show the image, which is 2048 x 822.

**To Reproduce**
1. Go to https://blockchain.topcoder.com/
2. Notice the first slide does not have a background and the 2nd slide does

**Expected behavior**
The slide should have a background or Contentful should not allow me to publish with a particular size.

**Screenshots**
<img width="1611" alt="screen shot 2018-09-06 at 1 30 03 pm" src="https://user-images.githubusercontent.com/1373998/45183464-fec25100-b1d8-11e8-98a9-fdd81da198f9.png">

**Desktop (please complete the following information):**
 - OS: OSX High Sierra
 - Browser Chrome
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iphone X
 - OS: latest
 - Browser chrome
 - Version Latest

**Additional context**

**Comment by hokienick** [comment]
@sushilshinde @cwdcwd  - has been down since the last big update (~2 weeks ago)

**Comment by birdofpreyru** [comment]
Fixed by e42463336adaf9f54a599d7d11680a5256c29a6e, but not yet in prod
