### ISSUE TITLE
Show assigned reviewers in Review opportunity page

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/community-app#1287]
**Is your feature request related to a problem? Please describe.**
Currently in the review opportunities page, once the reviewer is assigned for a challenge, we don't know who is assigned as reviewer from the review opportunity page, which makes the process not transparent and may raise doubts and concerns in the reviewer minds.

**Describe the solution you'd like**
When a challenge is launched, Copilot will select whether the Review type is internal or community.

If the Review type is internal, We can simply display the message "The challenge will be reviewed internally. Thank you for your interest"

If the Review type is Community, Challenge will be opened for application from Reviewers, Once the reviewers are assigned, we can fetch that information from Challenge API [Resources of the Project will give Reviewers detail (Require a M2M token in the backend to fetch that information)] and display it in the review opportunity page for being more transparent

Even if the reviewers are pre-assigned by Copilot, We can fetch that information from Challenge API and display it in the review opportunity page.

This way reviewer assignment process will be more transparent.

@ThomasKranitsas FYI

**Comment by ThomasKranitsas** [comment]
@ajefts thoughts?
