### ISSUE TITLE
Getting an error "Failed to add user trait" on profile page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1295]
While updating first name, last name and country on this URL https://www.topcoder.com/settings/profile, the user is getting an error "Failed to add user trait".
Please check and fix the issue.

![45407557-59e7be00-b687-11e8-83be-bb6bf64fa6f8](https://user-images.githubusercontent.com/4612921/45418587-90c0d280-b68d-11e8-965c-02735c33b3ab.png)

Reported by @JayaDhaka

**Comment by Gauravseta** [comment]
@thomaskranitsas any front end issue open for pickup? thanks

**Comment by ThomasKranitsas** [comment]
No, none at the moment. Stay tuned ;)

**Comment by ThomasKranitsas** [comment]
@JayaDhaka can you please send me the API response (from the network tab)? It's working fine on my end.

**Comment by RiteshTC** [comment]
@ThomasKranitsas We don't have the network response, as it has been reported by members.
We are not able to consistently reproduce the issue, but it does seem to occur at times. 
Most likely it related to authorization or gateway timeouts.

**Comment by RiteshTC** [comment]
cc: @cwdcwd

**Comment by nithyaasworld** [comment]
I am able to reproduce this by following the below steps:

1. Sign up with topcoder
2. Click on the activation link sent to the email
3. Then login and then go to profile settings
4. Enter the country and save. ( This gets success)
5. Now change the first and last name and save.

This showed the "Failed to add user trait" error. I did not have my network tab open. Below is my console log.

![image](https://user-images.githubusercontent.com/5114190/59796521-57438480-92fb-11e9-98ee-cb0c94079210.png)

Response of the failed API:
![image](https://user-images.githubusercontent.com/5114190/59796621-8954e680-92fb-11e9-832d-f9988777b7ee.png)
