### ISSUE TITLE
Can enter future date as a DOB

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1299]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Basic Info
3. Enter Birth Date > 09/13/2023
4. Click Save Changes

## Actual Result(s)

- Can enter future date as a DOB

## Expected Result(s)

- Must validate the DOB

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![2018-09-13_21-31-00](https://user-images.githubusercontent.com/4592712/45526360-67429c80-b79c-11e8-9632-4ba885ecbb89.png)

**Comment by ThomasKranitsas** [comment]
@ajefts do we have a min age to register at Topcoder? I guess yesterday's date should also not be valid.

**Comment by ajefts** [comment]
Let's just make sure it's in the future...

**Comment by ThomasKranitsas** [comment]
I'm not sure what you mean. The date of birth shouldn't be a future date :)

**Comment by ThomasKranitsas** [comment]
this is fixed
