### ISSUE TITLE
Error message displayed while saving data on the profile page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1304]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Basic Info
3. Fill some details and don't fill the country
4. Click Save Changes

## Actual Result(s)

- Error message displayed while saving data on the profile page

## Expected Result(s)

- Must not display an error

## Ref:

@ThomasKranitsas 

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
```
traits:1 PUT https://api.topcoder-dev.com/v3/members/pshah_manager/traits 400
main-1536762026959.js:83 Uncaught (in promise) Error
    at main-1536762026959.js:83
    at g (main-1536762026959.js:96)
    at Generator._invoke (main-1536762026959.js:96)
    at Generator.e.(anonymous function) [as next] (https://d1aahxkjiobka8.cloudfront.net/static-assets/main-1536762026959.js:96:15969)
    at o (main-1536762026959.js:9)
    at main-1536762026959.js:9
    at new Promise (<anonymous>)
    at new t (main-1536762026959.js:9)
    at main-1536762026959.js:9
    at main-1536762026959.js:83
```

**Comment by ThomasKranitsas** [comment]
Cannot reproduce. Maybe it's because of dirty existing data in the db that's causing this error on the backend.
