### ISSUE TITLE
Both error and success message gets displayed when saving a new subscription.

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1309]
**Describe the bug**
Both error and success message gets displayed when saving a new subscription.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Subscriptions'
3. Fill in the 'Name'
4. Click 'Add subscription to your list'

**Expected behavior**
Should display the correct message.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-13 22 39 22" src="https://user-images.githubusercontent.com/35376779/45514681-539c3380-b7a6-11e8-8839-f3335839460c.png">

**Desktop:**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

**Comment by PereViki** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
cannot reproduce
