### ISSUE TITLE
[$20] - Challenge Listings: Minor styling bugs at the XXS (<320px) sreen size

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#132]
![screenshot](https://user-images.githubusercontent.com/20144632/28779986-70106fd8-7605-11e7-96c2-7a8339ecea9b.png)

![screenshot](https://user-images.githubusercontent.com/20144632/28780019-94eb974c-7605-11e7-9952-f8c2ec6e9e39.png)

**Comment by elfman** [comment]
can you assign me this?

**Comment by birdofpreyru** [comment]
@elfman Consider yourself assigned. I have just noticed that I don't have enough rights in the repo to add contributors, and without it, I cannot technically assign people who are not contributors. Once my rights corrected, I'll fix it.

**Comment by elfman** [comment]
@birdofpreyru what is the min screen size this page should compatible with?

**Comment by birdofpreyru** [comment]
@elfman 0px :-D
Well, we are fine if staff just does not fit into the screen cause there is not enough space. But, in the screenshots above, my problem is that `Tracks` and `Filters` loose background and hover over other elements, rather than just occupy additional row. And in the filters panel, everythings just is not aligned properly to occupy available width.

**Comment by elfman** [comment]
I have raised a pr, but I can't change the issue's label

**Comment by birdofpreyru** [comment]
@elfman I've send you invitation to the repo. I guess, you should check your email, accept it, and then you'll be able to update the labels. I'll check your PR later :)
