### ISSUE TITLE
'Other' icons is too small compared to others

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1321]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Tools > Service Providers
3. Select the Type > Other
4. Enter provider name
5. Tap 'Add Provider'
6. Check the icon in the list

## Actual Result(s)

- 'Other' icons is too small compared to others

## Expected Result(s)

- Must display in same size

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![issue](https://user-images.githubusercontent.com/4592712/45560626-4b2a1400-b80b-11e8-9f2d-e69db7b19af9.png)

**Comment by ThomasKranitsas** [comment]
Seems like this has been resolved
