### ISSUE TITLE
[iphone4s][Basic Info] Layout of the switch buttons doesn't display properly.

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1325]
**Step To Reproduce**
1. Go to Basic Info of the Profile tab of the Setting page.
2. Scroll down to the Tracks section.
3. See the switch buttons, the circles are all in left side regardless of ON/OFF.

**Expected behavior**
The circle of the switch button should be in left side for OFF, and in right side for ON. 

**Screenshots**
![20180914_040249](https://user-images.githubusercontent.com/36178659/45516192-8d842e80-b7d4-11e8-8d7c-022a02767cb7.jpg)

**Smartphone (please complete the following information):**
 - Device: iphone4s
 - OS: IOS 9.3.5
 - Browser: Safari 
 - Version: 9

**Comment by ThomasKranitsas** [comment]
can't reproduce anymore
