### ISSUE TITLE
Able to overflow the Short Bio input? 

### ISSUE THREAD

**Issue by SecureMovieStreaming** [topcoder-platform/community-app#1327]
**To Reproduce**
1. Open Website and Login as User,
2. Go to Settings > Profile
3. Paste ""':;/?.,><[]{}\|-=`~!@#$%^&*()_+" 8 times
4. Click save changes
5. Refresh page

**Expected behavior**
Stops pasting at 240 characters and saves.

**Actual behavior**
Cuts off display of text as 240 characters but Says "256/240"

**Screenshots**
![image](https://user-images.githubusercontent.com/6743318/45516696-f25e6b00-b779-11e8-8ca9-cc87506c2231.png)

**Reference**
@ThomasKranitsas

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 69.0.3497.92

**Additional context**
Having trouble reproducing on same account due to "failed to add user trait" problem

**Comment by ThomasKranitsas** [comment]
cannot reproduce
