### ISSUE TITLE
Profile picture could not be added from gallery on iPhone 6s

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1329]
**Describe the bug**
Profile picture could not be added from gallery on iPhone 6s, even though I get a success message. After refreshing the page, the image is still empty.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Add an image from the gallery.
3. See error.

**Expected behavior**
The added image should show up.

**Screenshots**
![img_3877](https://user-images.githubusercontent.com/35376779/45517062-4fbfdf80-b7ad-11e8-98ef-f0c304b7bfac.PNG)
![img_3878](https://user-images.githubusercontent.com/35376779/45517093-61a18280-b7ad-11e8-903d-c5fe4dec7773.PNG)
![img_3879](https://user-images.githubusercontent.com/35376779/45517123-7120cb80-b7ad-11e8-983d-2400b8748886.PNG)

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

**Comment by PereViki** [comment]
@ThomasKranitsas

**Comment by nithyaasworld** [comment]
It is actually getting uploaded. But the page is not immediately refreshed. This issue exists in desktop too.
