### ISSUE TITLE
[Basic Info] Unnecessary `*require` label above the Country control.

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1332]
**Step To Reproduce**
1. Go to Basic Info of Profile tab of Setting page
2. Click on Country control.
3. See that the control always have value, and can't set to an empty value.

**Expected behavior**
The control should have an empty value as default, OR the label shouldn't be there.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/36178659/45517590-d342f600-b7d8-11e8-9428-2886efdddf60.jpg)

Environment: All

**Comment by ThomasKranitsas** [comment]
This field gets populated from the country you selected when registering for Topcoder. It can't be empty so this is not a valid issue
