### ISSUE TITLE
[Profile - Skill] The placeholder text overlaps the dropdown icon

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1337]
**Step To Reproduce**
1. Go to Skill of Profile tab of Setting page
4. See the placeholder text of the skill control.

**Expected behavior**
The dropdown icon shouldn't overlap the placeholder text.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/36178659/45518099-a42d8400-b7da-11e8-9744-355eff21cc0b.png)

**Environtment**: all

**Comment by ThomasKranitsas** [comment]
can't reproduce
