### ISSUE TITLE
Turning on a community setting does not get saved and gets error message

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1338]
**Describe the bug**
Turning on a community setting does not get saved and gets error message

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Community' on the side
3. Switch any community on.

**Expected behavior**
The community setting should be saved.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-13 23 59 17" src="https://user-images.githubusercontent.com/35376779/45518213-0c677000-b7b1-11e8-8789-469c272f7f08.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

**Comment by PereViki** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
this was possibly due to a backend issue at that time. It seems to be working now so it's not a frontend issue
