### ISSUE TITLE
Profile/Skill is narrower than the screen resource on iPhone 6s

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1339]
**Describe the bug**
Profile/Skill content is narrower than the screen resource on iPhone 6s.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Skill'
3. See error

**Expected behavior**
The content holder should be wider.

**Screenshots**
![img_3884](https://user-images.githubusercontent.com/35376779/45518437-d080da80-b7b1-11e8-8af2-98eb2281cc9b.PNG)

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

**Comment by PereViki** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
fixed
