### ISSUE TITLE
Profile/Hobby is narrower than the screen resource on iPhone 6s

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1340]
**Describe the bug**
Profile/Hobby content is narrower than the screen resource on iPhone 6s.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Hobby'
3. See error

**Expected behavior**
The content holder should be wider.

**Screenshots**
![img_3882](https://user-images.githubusercontent.com/35376779/45518468-e9898b80-b7b1-11e8-8230-b78fe877ea89.PNG)

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

**Comment by PereViki** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
fixed
