### ISSUE TITLE
Sometimes adding devices will display an error message

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1341]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Tools > Device
3. Fill all the details and add a device

## Actual Result(s)

- Sometimes adding devices will display an error message

## Expected Result(s)

- Must not display an error, user should able to add devices without an issue

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![2018-09-14_11-04-23](https://user-images.githubusercontent.com/4592712/45561859-57fc3700-b80e-11e8-9ae0-12dd10830b5d.png)

**Comment by ThomasKranitsas** [comment]
cannot reproduce. I tried with all device types
