### ISSUE TITLE
Full error message is not displayed in the Linked account page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1346]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Account > Linked Account
3. Enter www.google.com and click Add Link
4. Check the green validation popup

## Actual Result(s)

- Full error message is not displayed in the Linked account page

## Expected Result(s)

- Must display the error/validation text clearly

## Ref:

@ThomasKranitsas 

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

OR

- **Device(s):** iPhone 6s
- **Operating System:** iOS 11.4.1
- **Size:** 4.7 inches (~65.6% screen-to-body ratio)
- **Resolution:** 750 x 1334 pixels (~326 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![issue1](https://user-images.githubusercontent.com/4592712/45560007-9511fa80-b809-11e8-8911-472507fa8f23.png)

**Comment by ThomasKranitsas** [comment]
duplicate
