### ISSUE TITLE
[Deleting Links]; full error message is not displayed in the Linked account page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1347]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Account > Linked Account
3. Click Delete icon of a Linked Account
4. Check the green validation popup

## Actual Result(s)

- Full error message (Success! Your web link "Www.google.com" was removed.) is not displayed in the Linked account page

## Expected Result(s)

- Must display the error/validation text clearly

## Ref:

@ThomasKranitsas 

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

OR

- **Device(s):** iPhone 6s
- **Operating System:** iOS 11.4.1
- **Size:** 4.7 inches (~65.6% screen-to-body ratio)
- **Resolution:** 750 x 1334 pixels (~326 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
Desktop also

![2018-09-13_20-48-50](https://user-images.githubusercontent.com/4592712/45524987-b554a180-b796-11e8-8f9c-c217d765594c.png)

**Comment by ThomasKranitsas** [comment]
cannot reproduce
