### ISSUE TITLE
[Edge][Settings- Profile - Hobby, Skill] TextArea is always too small.

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1348]
**To Reproduce**
1. Go to Skill, or Hobby of Profile tab of Setting page.
2. See any textarea input, it size is having issue, it's too small.

**Expected behavior**
The textarea control should fill the remain space.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/36178659/45519375-fec8df00-b7de-11e8-9b90-724872fa81d0.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Edge
 - Version: 42

**Comment by nqviet** [comment]
add more picture:
![untitled](https://user-images.githubusercontent.com/36178659/45519567-d1306580-b7df-11e8-8007-887e8cf2586f.png)

**Comment by ThomasKranitsas** [comment]
duplicate
