### ISSUE TITLE
[Mobile, Tablet][Settings - Profile] The error validation message always disappear when scroll up.

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1356]
**Describe the bug**
After clicking to add a hobby, or skill unsuccessfully. He/she touches to scroll up to see the error message.

**To Reproduce**
1. Go to Hobby, or Skill of Profile tab of Setting page.
2. Click on Add button.
3. Drag up to the top.
4. See that the error validation message disappears immediately.

**Expected behavior**
The error validation message shouldn't disappear.

**Video attachment**
https://monosnap.com/file/pne03Tsa5cQfVtuEmuTpjzgdyDDBcm

**Smartphone:** All

**Comment by ThomasKranitsas** [comment]
cannot reproduce
