### ISSUE TITLE
Error message at password change seems like being covered partly by a white container

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1368]
**Describe the bug**
The error message I get when I try to change my password, but I enter incorrect password, the error message I get seems like being covered partly by a white container.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/account'
2. Click on 'My Account'
3. Try to change your password but with a wrong original password, so you get an error message.
4. Scroll up to the top.
4. See error (3 out of 5 times)

**Expected behavior**
There should be no white cover on the error message.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-14 01 49 39" src="https://user-images.githubusercontent.com/35376779/45522288-64f33900-b7c2-11e8-879d-ad31edad9e8d.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
cannot reproduce
