### ISSUE TITLE
'TRACKS' changes are saved without clicking on Save changes button

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1372]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Basic info
3. Go to 'TRACKS' 
4. Disable/Enable the DESIGN/DEVELOPMENTDATA SCIENCE
5. Now go to another tab
6. Again Go to Settings > Profile > Basic info
7. Check the settings

## Actual Result(s)

- 'TRACKS' changes are saved without clicking on Save changes buttonype, Name, cannot be empty

## Expected Result(s)

- Must not save the changes without if user didn't click on Save changes button
- This is compared to the mobile and tablet versions if this is the correct behaviour; must have to change the functionality on mobile devices

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
I cannot reproduce that
