### ISSUE TITLE
Entering the date manually to the field, and click on save will display time on the date field

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1377]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Basic info
3. Enter > 2018/05/05 as DOB
4. Click Save Changes
5. check the DOB field again

## Actual Result(s)

- Entering the date manually to the field, and click on save will display time on the date field
- 2018-05-05T05:00:00.000Z

## Expected Result(s)

- mm/dd/yyyy

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
