### ISSUE TITLE
[Settings - Account - My Account] Can't click on outside to hide the validation message

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1380]
**To Reproduce**
1. Go to My Account of Account tab of Settings page.
2. Click on 'Send Verification Email' button.
3. The message 'Your email address is not valid' appears.
4. Click on outside
5. See that the message doesn't disappear, user have to click on the input control and click on outside again so that it works.

**Expected behavior**
The validation message should disappear when clicking on the outside.

**Video attachment**
https://monosnap.com/file/RTbB8HRl8XI4HwFQmfKxhlRgZXybW8
or [video.zip](https://github.com/topcoder-platform/community-app/files/2381505/video.zip)

**Environment:** all

**Comment by ThomasKranitsas** [comment]
this works fine on my end
