### ISSUE TITLE
Layout issue in the Delete web address popup, if we have a long web address

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1383]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Portraot]
2. Go to Settings > Account > Linked Account
3. Enter URL as HTTP://WWW.THESITEWIZARDACUSTOMDOMAINNAME.COM and Add the external link to the list
4. Click Delete and check the popup

## Actual Result(s)

- Layout issue in the Delete web address popup, if we have a long web address

## Expected Result(s)

- Must display the popup correctly

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

and 

- **Device(s):** iPhone 6s
- **Operating System:** iOS 11.4.1
- **Size:** 4.7 inches (~65.6% screen-to-body ratio)
- **Resolution:** 750 x 1334 pixels (~326 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
Same can be seen on desktop as well

**Comment by ThomasKranitsas** [comment]
cannot reproduce
