### ISSUE TITLE
Always displays "Loading data. This will take a few minutes.", nothing changes after waiting few mins

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1389]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > linked Account
3. Add a Link > www.google.com
4. Wait5-10min and check the added weblink

## Actual Result(s)

- Always displays "Loading data. This will take a few minutes.", nothing changes after waiting few mins

## Expected Result(s)

- Must remove the info message if it is not applicable to here

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
Not sure if this can be fixed though.
