### ISSUE TITLE
I could change my e-mail to one that is already used by another user

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1391]
**Describe the bug**
I could change my e-mail to one that is already used by another user (my other test profile)

**To Reproduce**
You must have 2 accounts to be able to reproduce this bug
1. Go to 'https://www.topcoder-dev.com/settings/account' with one of your accounts
2. Click on 'My Account'
3. Change your e-mail to the same what is registered for your other account, and verify it.
4. See error (you'll have to refresh the page you get, due to another bug, which will not update the field)

**Expected behavior**
The user should get an error message if he attempts to change his e-mail to an already used one.

**Screenshots**
In the links it can be seen, that both users got the same e-mail.
<img width="1280" alt="screenshot 2018-09-14 04 24 45" src="https://user-images.githubusercontent.com/35376779/45526395-303dac80-b7d7-11e8-8194-54642cdd5a06.png">
<img width="1280" alt="screenshot 2018-09-14 04 25 04" src="https://user-images.githubusercontent.com/35376779/45526396-30d64300-b7d7-11e8-806c-3078782472ca.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by dedywahyudi** [comment]
@ThomasKranitsas 
Function to check new email already in use should be new feature i think. 
Not remember we have that on previous build.

**Comment by ThomasKranitsas** [comment]
Should I close this ticket?

**Comment by ThomasKranitsas** [comment]
This has been fixed
