### ISSUE TITLE
UX issue - The 3 required fields are too far from each other on Basic Info

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1392]
**Describe the bug**
The 3 required fields should be closer to each other, so the user would not miss Country easily, as it is below the fold. 

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. See error

**Expected behavior**
Better information architecture.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-14 04 54 45" src="https://user-images.githubusercontent.com/35376779/45527135-6e889b00-b7da-11e8-9579-39940c2b6bec.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
@vic-topcoder thoughts?

**Comment by ThomasKranitsas** [comment]
@vic-topcoder ?

**Comment by vic-topcoder** [comment]
In general yes - required fields are on top, but in this case I wonder what dictates the structure of the page. I would love to have a second pass on the whole form, as for example we have:

- Labels are left-aligned; they should be right-aligned to make it easy for the user to identify the field, right now there is a gap between element and field;
- certain fields are dependent on the country - zip code validation, address formatting
- Not all fields take into consideration the value - zip code should be very short, next to the state (US format), in other countries ZIP is associated with town, etc., etc.
- Support link covers form elements
- Save is hard to reach at the bottom of the page
- Updating password and email use different interaction; they shouldn't.
- Form placeholder might benefit from language improvements

**Comment by ThomasKranitsas** [comment]
I'm not quite sure what needs to be done :)

Do we need to rethink about the overall layout of our forms?
