### ISSUE TITLE
[Common] When the Success message is displaying; drop down values are resetting

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1394]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Tool > Service providers (Also in the Devices/Software/Subscription)
3. Add a new item
4. Now select item from the drop down (Type) and type a text in the Provider Name
5. When the validation messages activated check the drop down value

## Actual Result(s)

- When the Success message is displaying; drop down values are resetting

## Expected Result(s)

- Must not reset the form data when the success message is displaying/hiding

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** Chrome 64.0.3282.137

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
https://cl.ly/026fa64d16e0

**Comment by ThomasKranitsas** [comment]
This should be fixed in `0.6.1` of topcoder-react-lib
