### ISSUE TITLE
Can enter invalid URL to the 'Add a new external link'

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1396]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > Linked Account
3. Go to 'Add a new external link' section
4. Enter www.facebook.comwww.facebook.com
5. Check the Link

## Actual Result(s)

- Can enter invalid URL to the 'Add a new external link'

## Expected Result(s)

- Must validate the correct URL format

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![2018-09-13_22-26-40](https://user-images.githubusercontent.com/4592712/45528042-1df64b00-b7a4-11e8-9d6e-f717e2dd1125.png)

**Comment by ThomasKranitsas** [comment]
that's not really an invalid URL... It's being recognized as a chain of subdomains.
