### ISSUE TITLE
setup qa community

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#140]
Add another community:

name = QA
visibility = public, with the Join option for people to self join.
challenge filtering = filter on technology.  We'll add another tag for QA.
content = copy the tc-prod-dev for now.

**Comment by ajefts** [comment]
fyi @birdofpreyru ...when you get a chance...

**Comment by birdofpreyru** [comment]
@ajefts I have added it. For the moment it uses the same `groupId` as `tc-prod-dev` - it should be updated at some point. Also, filtering by `qa` tag, at the moment, also matches challenges with `qa` literals in title. It is easy to change to match only technology tags, but as we don't have `qa` tag yet, I have left it as it is for now, as the listing looks nicer with some challenges in it, and they anyway mostly related to qa.
