### ISSUE TITLE
Some HTTPS sites can't added as Web Links

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1402]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > Linked Account
3. Enter > https://www.google.com as the External Link
4. Press ENTER
5. Enter > https://www.topcoder.com as the External Link
6. Press ENTER

## Actual Result(s)

- Some HTTPS sites can't added as Web Links

## Expected Result(s)

- Must able to add any HTTPS site

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
Browser(s): Google Chrome 69.0.3497.92 (Official Build) (64-bit)

```
POST https://api.topcoder-dev.com/v3/members/pshah_manager/externalLinks 400
main-1536762026959.js:83 Uncaught (in promise) Error
    at main-1536762026959.js:83
    at g (main-1536762026959.js:96)
    at Generator._invoke (main-1536762026959.js:96)
    at Generator.e.(anonymous function) [as next] (https://d1aahxkjiobka8.cloudfront.net/static-assets/main-1536762026959.js:96:15969)
    at o (main-1536762026959.js:9)
    at main-1536762026959.js:9
    at new Promise (<anonymous>)
    at new t (main-1536762026959.js:9)
    at main-1536762026959.js:9
    at main-1536762026959.js:83
(anonymous) @ main-1536762026959.js:83
g @ main-1536762026959.js:96
(anonymous) @ main-1536762026959.js:96
e.(anonymous function) @ main-1536762026959.js:96
o @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:9
t @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:83
(anonymous) @ main-1536762026959.js:83
g @ main-1536762026959.js:96
(anonymous) @ main-1536762026959.js:96
e.(anonymous function) @ main-1536762026959.js:96
o @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:9
```

![2018-09-13_22-44-13](https://user-images.githubusercontent.com/4592712/45528618-b7bef780-b7a6-11e8-83a2-a7f48aa897c2.png)
![2018-09-13_22-44-55](https://user-images.githubusercontent.com/4592712/45528619-b8578e00-b7a6-11e8-8d2d-9a92ed1e9380.png)

**Comment by ThomasKranitsas** [comment]
cannot reproduce
