### ISSUE TITLE
External Link default text is wrong

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1407]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > Linked Account
3. Check the default text of External Link field

## Actual Result(s)

- HTTP.//WWW.YOURLINK.COM

## Expected Result(s)

- HTTP://WWW.YOURLINK.COM

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![2018-09-13_23-10-48](https://user-images.githubusercontent.com/4592712/45529355-5567f600-b7aa-11e8-8d4c-314aa75cf27b.png)

**Comment by ThomasKranitsas** [comment]
It's actually a font issue as the letter `P` overlaps with the `:`

cc @vic-topcoder

**Comment by ThomasKranitsas** [comment]
Closing this one as it's not a valid issue
