### ISSUE TITLE
Add a Link option is not displayed in Landscape mode

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1409]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Portrait]
2. Go to Settings > Account > Linked Account
3. Scroll down to the bottom
4. Go to Landscape mode and check the Add a Link option

## Actual Result(s)

- Add a Link option is not displayed in Landscape mode

## Expected Result(s)

- Must display the Add a Link option at the bottom of the page

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPad Air 2
- **Operating System:** iOS 11.4.1
- **Size:** 9.7 inches (~71.6% screen-to-body ratio)
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
https://cl.ly/2a3d62ea8987

**Comment by ThomasKranitsas** [comment]
invalid issue. The input is visible at the top.
