### ISSUE TITLE
Footer text is not aligned properly in mobile

### ISSUE THREAD

**Issue by Neha-2208** [topcoder-platform/community-app#1418]
**Describe the bug**
Footer text is not aligned properly in mobile

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Scroll down to Footer Section
4. Observe text is not aligned prpoerly

**Expected behavior**
Text should be properly aligned

**Screenshots**
![image](https://user-images.githubusercontent.com/20572731/45534780-df9b7300-b819-11e8-88a4-691e3bd0bd03.png)

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS:  iOS
 - Browser: Chrome
 - Version: 68.0.3440.106

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
this is a common issue in the app thus can't be counted as valid issue for this bug hunt targetting the settings page.
