### ISSUE TITLE
Delete Avatar button not working

### ISSUE THREAD

**Issue by Neha-2208** [topcoder-platform/community-app#1419]
**Describe the bug**
After uploading avatar, when I am clicking on 'Delete Avatar' nothing is happening. The avatar is not getting removed. 

**To Reproduce**
1. Go to https://www.topcoder-dev.com/settings/profile
2. Click on Upload Avatar button. An avatar will be uploaded
3. Now, click on 'Delete Avatar' button
4. See error, the avatar is not getting deleted/removed.

**Expected behavior**
After clicking on delete button the avatar button should get removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/20572731/45535321-b5e34b80-b81b-11e8-8cfb-dc2648f71edd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 69.0.3497.91

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
