### ISSUE TITLE
Date format stored in IE is completely different

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1423]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Profile > Basic Profile
3. Enter 02/25/1980 to DOB
4. Click Save changes and observe

## Actual Result(s)

- Date format stored in IE is completely different and stored as yyyy/mm/dd

## Expected Result(s)

- Must display as mm/dd/yyyy

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

https://www.screencast.com/t/HFxbFCGKM

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![2018-09-14_9-23-33](https://user-images.githubusercontent.com/4592712/45556264-70655500-b800-11e8-84b8-18e12c19d1fb.png)

**Comment by ThomasKranitsas** [comment]
duplicate
