### ISSUE TITLE
Extra characters displayed on the Date when user is saving the changes

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1425]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Profile > Basic Profile
3. Enter 02/25/1980 to DOB
4. Click Save changes 
5. While saving check the date field

## Actual Result(s)

- Extra characters displayed on the Date when user is saving the changes

## Expected Result(s)

- Must display only the date

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
https://www.screencast.com/t/GOG29FUFmb

**Comment by ThomasKranitsas** [comment]
duplicate
