### ISSUE TITLE
Upon saving Basic Info, the UI freezes for an unreasonable time

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1431]
**Describe the bug**
When I try to save Basic Info, with an invalid date of birth (not sure that tis is the reason) the UI freezes for a long time, so the user might think that he needs to refresh. Even the cursor remains in a hover state.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. Fill in 'Birth Date' with an invalid value e.g. 2111111111
4. Save form... there will be an error message.
5. Try to close the message.
6. See error

**Expected behavior**
The error message should be closed immediately.

**Screenshots**
https://www.screencast.com/t/e7wDQeL1eo

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
This will be fixed once we replace the birthdate input implementation
