### ISSUE TITLE
Changed email is not displayed on the page when user navigates to the page from email link

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1432]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > My Account
3. Click Change Email
4. Enter sdgun@qa.com
5. Wait for the email and click on the Link
6. In the success page click on the button 'Back to the Account'
7. Check the 'Primary Email' (Displayed the old one)

## Actual Result(s)

- Changed email is not displayed on the page when user navigates to the page from email link

## Expected Result(s)

- Must display the new email not the old one

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![2018-09-14_14-29-59](https://user-images.githubusercontent.com/4592712/45571127-d8c92c00-b82a-11e8-879f-23ef59395039.png)

**Comment by ThomasKranitsas** [comment]
duplicate
