### ISSUE TITLE
Verification of the external link of Linked Account fails on iPad

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1435]
**Describe the bug**
If I type Www.hu to the textbox the system let me save the invalid link.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/account'
2. Click on 'Linked Account'
3. Start to type 'Www.hu'

**Expected behavior**
Invalid urls should not be saved.

**Screenshots**
![img_0526](https://user-images.githubusercontent.com/35376779/45571732-81957c80-b867-11e8-9285-c13ec0eb1634.PNG)
![img_0527](https://user-images.githubusercontent.com/35376779/45571735-82c6a980-b867-11e8-8cdb-dbcccca6e4d2.PNG)

**Tablet:**
 - Device: iPad Mini 2
 - OS: iOS 11
 - Browser: Chrome
 - Version: 69.0.3497.91

@ThomasKranitsas

**Comment by nithyaasworld** [comment]
Same issue is observed in Desktop as well.

It seems some kind of validation is already done, but it does not include the above scenario.
