### ISSUE TITLE
[Common in All locations] Tapping on the drop down won't focus that field in the visible screen area like textboxes

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1440]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Profile > Basic Info
3. Scroll down and tap on T Shirt size or Country drop down
4. Observe > User needs to scroll down to find the drop down
5. Tap on a text box and observe

## Actual Result(s)

- Tapping on the drop down won't focus that field in the visible screen area like textboxes

## Expected Result(s)

- Must focus the input field in the visible screen area like text boxes

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPad Air 2
- **Operating System:** iOS 11.4.1
- **Size:** 9.7 inches (~71.6% screen-to-body ratio)
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **Browser(s):**  Google Chrome 69.0.3497.92

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
https://cl.ly/7cbabe6b8f86

**Comment by ThomasKranitsas** [comment]
This is not really needed. The user may don't want to type but just scroll in the list
