### ISSUE TITLE
Hobby form fields (Hobby, Description) are too short; compared to other locations

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1441]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Profile > Hobby
3. Check the form fields (Hobby, Description)

## Actual Result(s)

- Hobby form fields (Hobby, Description) are too short; compared to other locations

## Expected Result(s)

- Must spread the text fields across the view so that user can have more space to work with, like in the Profile page

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPad Air 2
- **Operating System:** iOS 11.4.1
- **Size:** 9.7 inches (~71.6% screen-to-body ratio)
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **Browser(s):**  Google Chrome 69.0.3497.92

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![img_0416](https://user-images.githubusercontent.com/4592712/45592187-46a94c80-b92c-11e8-986c-225252187e0d.PNG)

**Comment by ThomasKranitsas** [comment]
duplicate
