### ISSUE TITLE
Overall the feedback system is not following a uniform approach

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1442]
**Describe the bug**
There are 3 types of error messages and an additional success message.

**To Reproduce**

**Expected behavior**
Feedback system should follow a uniform approach. Error/success messages should be shown in the same manner. For inline form validation there should be an additional type of error message on the field itself.

**Screenshots**
![img_ae9ffbb0e1d3-1](https://user-images.githubusercontent.com/35376779/45572979-4dbc5600-b86b-11e8-9d66-087e9aa91fb8.jpeg)
![img_06473e8f5f0e-1](https://user-images.githubusercontent.com/35376779/45573161-efdc3e00-b86b-11e8-9bac-a1ba076cbe1c.jpeg)
![img_89c89e7da267-1](https://user-images.githubusercontent.com/35376779/45573177-f8cd0f80-b86b-11e8-9f22-1913e690c94e.jpeg)
![img_ca20070189c4-1](https://user-images.githubusercontent.com/35376779/45573218-1ef2af80-b86c-11e8-8a49-a7530a4b0562.jpeg)

**Tablet:**
 - Device: iPad Mini 2
 - OS: iOS 11
 - Browser: Chrome
 - Version: 69.0.3497.91

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
cc @vic-topcoder
