### ISSUE TITLE
Tools [Devices/Software/Service Providers/Subscriptions] form fields are too short

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1443]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Tools > Devices/Software/Service Providers/Subscriptions
3. Check the form fields

## Actual Result(s)

- Tools [Devices/Software/Service Providers/Subscriptions] form fields are too short compared to Desktop
- Because there is more space in the landscape view, better to have larger input fields

## Expected Result(s)

- Must spread the text fields across the view so that user can have more space to work with, like in the Profile page

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPad Air 2
- **Operating System:** iOS 11.4.1
- **Size:** 9.7 inches (~71.6% screen-to-body ratio)
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **Browser(s):**  Google Chrome 69.0.3497.92

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![img_0418](https://user-images.githubusercontent.com/4592712/45592203-aef82e00-b92c-11e8-9c90-33f3e174b0b5.PNG)
![img_0419](https://user-images.githubusercontent.com/4592712/45592204-aef82e00-b92c-11e8-859f-a286490842ee.PNG)
![img_0420](https://user-images.githubusercontent.com/4592712/45592205-af90c480-b92c-11e8-9549-c94e27b0d74c.PNG)
![img_0417](https://user-images.githubusercontent.com/4592712/45592206-af90c480-b92c-11e8-82d1-6bfc9faa6d1c.PNG)

**Comment by ThomasKranitsas** [comment]
duplicate
