### ISSUE TITLE
Tapping on the 'Show' checkbox must not display the validation info popup

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1445]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Account > My Account
3. Scroll down and click on the 'New password'; Show checkbox

## Actual Result(s)

- Tapping on the 'Show' checkbox is displaying the validation info popup

## Expected Result(s)

- Tapping on the 'Show' checkbox must not display the validation info popup

## Frequency

- 5/5

## Environment Details

- All Devices

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
not a valid issue
