### ISSUE TITLE
First Name and Last name fields are automatically filled out when user tap on the Save Changes button after deleting it

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1447]
## Steps to Reproduce

1. Open the Application and Login as a valid user [Landscape]
2. Go to Settings > Profile > Basic Info
3. Remove the First Name and Last name fields data
4. Tap Save Changes
5. You can see Success message; scroll up and check the fields

## Actual Result(s)

- First Name and Last name fields are automatically filled out when user tap on the Save Changes button after deleting it

## Expected Result(s)

- Should not auto fill the data after removing them; Must display the validation message instead

## Frequency

- 5/5

## Environment Details

- All Devices

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
cannot reproduce
