### ISSUE TITLE
Visual fixes

### ISSUE THREAD

**Issue by vic-topcoder** [topcoder-platform/community-app#145]
*NOTE: If an issue marked as resolved below, it does not mean the fix is already in the repo, it just means it has been taken care of*

We need some small CSS tweaks on the challenge details page:

- [x] - page background should be #EBEBEB;
- [x] - page container doesn't have rounded corners;
- [x] - right column should be static width (245px), the same for the buttons;
- [x] - right column should never change background - #F4F9FF $tc-dark-blue-10;
- [x] - space between tab bottom border and the header bottom - should be flushed;
- [x] - link inside notes paragraph is larger than the rest of the text;
- [x] - responsive isn't implemented to specification:
  - [x] - header buttons don't fold under prize;
  - [x] - tab navigation should slide, now it stacks;
- [ ] - ~~buttons should always use the static button colors/classes defined in TC UI;~~
  *We got a technically more appealing solution in Community App, which allows to handled button styles and functionality*

Expected:
![screen shot 4](https://user-images.githubusercontent.com/8484061/29049503-356704f6-7b8b-11e7-9034-2f5f4c3aa41b.png)
![header](https://user-images.githubusercontent.com/8484061/29049536-6c76fe92-7b8b-11e7-8f41-a3485533c9cc.png)
![01 m-challenge details](https://user-images.githubusercontent.com/8484061/29049538-6f63405c-7b8b-11e7-8044-b5349d62fd70.png)
![01 t-challenge details](https://user-images.githubusercontent.com/8484061/29049539-6f782fda-7b8b-11e7-9b9f-db2c26f9ed87.png)
![02b status registered with all deadlines visible](https://user-images.githubusercontent.com/8484061/29049540-6f78447a-7b8b-11e7-8817-d375ec494414.png)

**Comment by vic-topcoder** [comment]
@TonyJ - can you reference to the google drive if needed?

**Comment by birdofpreyru** [comment]
@vic-topcoder I have my copy of specs here: https://drive.google.com/open?id=0B3y3SEA9cIEkRWt2TVpXMDhQbTA
