### ISSUE TITLE
There is a 403 error on load of pages

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1458]
**Describe the bug**
Loading any page triggers a 403 error.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Open the inspector and see the network messages upon refresh.
3. See error

**Expected behavior**
There should be no error.

**Screenshots**
https://www.screencast.com/t/OfxBjyqmdu

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Firefox
 - Version: 62.0

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
cannot reproduce
