### ISSUE TITLE
Error displayed when user click on 'Preferences'

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1459]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Preferences

## Actual Result(s)

- 404 HTTP Error

## Expected Result(s)

- Must not display an error

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
```
GET https://api.topcoder-dev.com/v3/users/40152238/preferences/email 404
main-1536762026959.js:83 Uncaught (in promise) Error
    at main-1536762026959.js:83
    at g (main-1536762026959.js:96)
    at Generator._invoke (main-1536762026959.js:96)
    at Generator.e.(anonymous function) [as next] (https://d1aahxkjiobka8.cloudfront.net/static-assets/main-1536762026959.js:96:15969)
    at o (main-1536762026959.js:9)
    at main-1536762026959.js:9
    at new Promise (<anonymous>)
    at new t (main-1536762026959.js:9)
    at main-1536762026959.js:9
    at main-1536762026959.js:83
```

https://www.screencast.com/t/TAKjnJudo

**Comment by ThomasKranitsas** [comment]
cannot reproduce. I created a new account and I was able to access the preference page without issues
