### ISSUE TITLE
'Preferences' tab is inaccessible when user changes the email to a non-existing one

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1460]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > My Account
3. Change the email to a non-existing one like sdgun@sdgun.com
4. Go to Primary email and approve the change
5. Go to 'Preferences' tab

## Actual Result(s)

- 'Preferences' tab is inaccessible when user changes the email to a non-existing one

## Expected Result(s)

- Must validate the new email address existence also

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
https://www.screencast.com/t/pGicRc1jc

**Comment by urwithat** [comment]
@dedywahyudi Lets add the 2-step verification.

cc @ThomasKranitsas, @cwdcwd

**Comment by dedywahyudi** [comment]
@ThomasKranitsas @urwithat 
I need some clarifications here for 2-steps verification: 

- Verify the action in the old email
> What action needed in the old email? Did we need different email message? 

- Verify the new email address
> So, we need send verification to the old email address about change for the new address? I think this is exists, not sure why i'm not receive anymore email notifications. 

'Preferences' tab is inaccessible when user changes the email to a non-existing one
- @sdgun What error you see when access the Preference tab?

**Comment by sdgun** [comment]
@dedywahyudi 404 Error > https://www.screencast.com/t/pGicRc1jc

**Comment by dedywahyudi** [comment]
@sdgun Thanks!
Did you receive email message after click the verification button?

**Comment by dedywahyudi** [comment]
Not following? email you listed are same sdgun@sdgun.com. That email active? 
New email should different right?

**Comment by sdgun** [comment]
No fake email > sdgun@sdgun.com

**Comment by ThomasKranitsas** [comment]
Closing this one as it's no longer needed
