### ISSUE TITLE
Must validate the new email address as well when changing the email

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1462]
## Steps to Reproduce

1. Open the Application and Login as a valid user 
2. Go to Settings > Account > My Account > Change Email
3. Change the email to non-existing one
4. Click 'Send Verification Email' button
5. Go to your working (Primary email) and click on the link to approve the process
6. After that go to Settings > Account > My Account
7. Your newly added non-existing email is there
8. Click Change Email
9. Enter your previous working email
10. Click 'Send Verification Email' button
11. Now the verification email never comes

## Actual Result(s)

- Currently the new email address is not validated, because of it after approving it, we can't change it again because now the verification email is sending to a non-existing email
 so user can't never change his/her email without contacting admins

## Expected Result(s)

- Must validate the new email address as well when changing the email

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment]
![2018-09-14_18-05-36](https://user-images.githubusercontent.com/4592712/45578721-dc6bab80-b848-11e8-8948-86af41080007.png)

**Comment by ThomasKranitsas** [comment]
Closing this one as it's no longer needed
