### ISSUE TITLE
[UI] An icon is hidden under Checkbox and SHOW text in Password and New Password fields

### ISSUE THREAD

**Issue by karinakohl** [topcoder-platform/community-app#1466]
**Describe the bug**
An icon is hidden in a password field

**To Reproduce**
1. Go to Settings/Account
2. Scroll down to Password and New Password Fields

**Actual Behavior:**
An icon is hidden under Checkbox and SHOW text in Password and New Password fields

**Expected behavior**
I cannot see what is the icon and what it is supposed to be

**Screenshots**
![settingsaccounticonundershow](https://user-images.githubusercontent.com/10549808/45590984-0f32a400-b91c-11e8-9a38-4a1b56c7270f.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: chrome
 - Version: 69.0.3497.92

**Comment by karinakohl** [comment]
@thomaskranitsas

**Comment by ThomasKranitsas** [comment]
@karinakohl are you using some 3rd party extension on your browser? Anything that manages passwords or generates passwords? I'm not seeing that icon on my chrome. I'm also using MacOS High Sierra
