### ISSUE TITLE
[FUNCTIONAL] It is not possible to delete the user profile avatar

### ISSUE THREAD

**Issue by karinakohl** [topcoder-platform/community-app#1467]
**Describe the bug**
It is not possible to delete the user profile avatar

**To Reproduce**
1. Go to Settings/Profile/Basic Info
2. Upload your avatar
3. After uploading a new button will appear: "Delete Avatar"
4. Click on "Delete Avatar"

**Actual behavior**
Avatar is not deleted and no message is presented to user

**Expected behavior**
Avatar should be deleted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - Browser chrome
 - Version 69.0.3497.92

**Comment by karinakohl** [comment]
@thomaskranitsas

**Comment by ThomasKranitsas** [comment]
duplicate. This was already reported
