### ISSUE TITLE
[UX] User is redirected to the forum page when click Forum in Settings/Preference. No warning. User lost reference.

### ISSUE THREAD

**Issue by karinakohl** [topcoder-platform/community-app#1469]
**Describe the bug**
User is redirected to the forum page when click Forum in Settings/Preference. No warning. User lost reference.

**To Reproduce**
1. Go to Settings/Preference
2. Click on Forum

**Expected behavior**
To open the forum in the same screen or in a new tab/window. 

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser chrome
 - Version 69.0.3497.92

**Comment by karinakohl** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
this is expected behavior as those pages haven't been moved to the new site yet
