### ISSUE TITLE
Code-splitting should be set up

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#147]
It turns out that along with the growth of our codebase, even with all optimizations our compiled .css bundle approaches 3mb :( Also HMR is slower than it could be, as it has to de-dube css code (otherwise .css bundle is about 6mb, due to dublicated code, which blows up browser's dev tools :( This should be resolved.

**Comment by vic-topcoder** [comment]
Oh wow! That's way too much CSS!
