### ISSUE TITLE
Skill section separator is not visible

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1475]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills
3. Scroll down and check above Hobby Title

## Actual Result(s)

- Skill section separator is not visible

## Expected Result(s)

- Must display a line at the end of the skill page

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPhone 6s
- **Operating System:** iOS 11.4.1
- **Size:** 4.7 inches (~65.6% screen-to-body ratio)
- **Resolution:** 750 x 1334 pixels (~326 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
This applies to Hobby section as well, if there are no data on it

**Comment by ThomasKranitsas** [comment]
duplicate
