### ISSUE TITLE
Empty messages are automatically removed when user tap on the screen/ or scroll

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1479]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills/Hobby
3. Tap 'Add skill to your list' or 'Add hobby to your list'
4. Now scroll the page up/down

NOTE" Tools > Devices pages won't have this issue

## Actual Result(s)

- Empty messages are automatically removed when user tap on the screen/ or scroll

## Expected Result(s)

- Must not hide the error message (Compared to Desktop and Tab)

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPhone 6s
- **Operating System:** iOS 11.4.1
- **Size:** 4.7 inches (~65.6% screen-to-body ratio)
- **Resolution:** 750 x 1334 pixels (~326 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
https://cl.ly/775a00de72bc

**Comment by ThomasKranitsas** [comment]
duplicate
