### ISSUE TITLE
Skill list is not up to date

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1481]
**Describe the bug**
I tried to add Adobe XD (and XD) to my skills as it is an actively allowed in design chalenges, but it is not on the list

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile'
2. Click on 'Skill'
3. Try to add XD

**Expected behavior**
All the skills that might be needed for Topcoder challenges should be able to be added.

**Screenshots**
![img_0c07c3878598-1](https://user-images.githubusercontent.com/35376779/45591819-568d5480-b95d-11e8-8034-cb10bbc6a7db.jpeg)

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
we need to add more skills to the list

cc @ajefts

**Comment by ThomasKranitsas** [comment]
Logged on Trello. Closing for now
