### ISSUE TITLE
Dummy Data displayed on the Skill list (Adding some of them will display errors)

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1488]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills
3. Add tony_test, test1 as skills

## Actual Result(s)

- tony_test, test1

## Expected Result(s)

- Must not display the dummy data

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

And All other devices

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![2018-09-15_20-31-32](https://user-images.githubusercontent.com/4592712/45591945-5f166880-b926-11e8-82c3-c8e8a11fab63.png)

**Comment by ThomasKranitsas** [comment]
Not a valid issue... It's an issue on the development backend/db

**Comment by sdgun** [comment]
@ThomasKranitsas This can be seen on the production as well

**Comment by ThomasKranitsas** [comment]
@cwdcwd @urwithat @ajefts skills `Test 1` and `Tony_Test` do exist in prod

**Comment by urwithat** [comment]
@ThomasKranitsas 
This similar to https://github.com/topcoder-platform/community-app/issues/1490#issuecomment-423272873.
I believe the data for skills are hard coded on the front end, so we are facing data difference on front end and backend! 

cc @cwdcwd @ajefts

**Comment by ThomasKranitsas** [comment]
Logged on Trello. Closing for now

**Comment by urwithat** [comment]
This has been resolved..
