### ISSUE TITLE
Error while adding Marvel-Design

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1490]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills
3. Add Marvel - Design

## Actual Result(s)

- Error while adding Marvel-Design

## Expected Result(s)

- Must not display an error

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![2018-09-15_20-40-22](https://user-images.githubusercontent.com/4592712/45592010-9a656700-b927-11e8-9f96-4d4af0e2b0bf.png)

**Comment by ThomasKranitsas** [comment]
@urwithat @cwdcwd should you add this to the db?

**Comment by urwithat** [comment]
@ThomasKranitsas This is the error.
{"id":"-2491f2d3:165f91f07b8:-3ada","result":{"success":true,"status":400,"metadata":null,"content":"[\"Tag id 2 is not valid\"]"},"version":"v3"}

Where is the list of Skills displayed in drop down populated from? hope its not hardcoded and are there any other skills missed out?

cc @cwdcwd

**Comment by ThomasKranitsas** [comment]
@urwithat we get the skills from https://api.topcoder-dev.com/v3/tags/?domain=SKILLS&status=APPROVED

**Comment by ThomasKranitsas** [comment]
Logged on Trello. Closing for now
