### ISSUE TITLE
Some long skill names gets cut off not wrapped on desktop

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1492]
**Describe the bug**
Some of my skills gets cut off instead of being wrapped, e.g. 'Interaction Design (IxD)' became 'Interaction...', however 'design (IxD)' could have gone into the second row.

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile'
2. Click on 'Skill'
3. Add 'Interaction design (IxD)'

**Expected behavior**
Long skill napes should wrap into at least 2 lines.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-16 03 44 47" src="https://user-images.githubusercontent.com/35376779/45592061-97886780-b963-11e8-9b0b-ddd248ce90db.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
I think that's expected behavior... I can't think of another way to render the full text without looking weird.
