### ISSUE TITLE
Some skills are overlaps with each other

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1493]
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills
3. Add IBM Websphere Application Server, IBM WebSphere MQ, IDOL OnDemand to the list
4. Observe

## Actual Result(s)

- Some skill names are overlapping each other

## Expected Result(s)

- Must not overlap the names with each other

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment]
![2018-09-15_20-56-43](https://user-images.githubusercontent.com/4592712/45592093-e0232f00-b929-11e8-8c79-23f2d0b13e0c.png)

**Comment by ThomasKranitsas** [comment]
duplicate
