### ISSUE TITLE
[Settings - Account - Linked Account] Error message appears when cancelling.

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1494]
**Steps To Reproduce**

1. Go to Settings -> Account -> Linked Account
2. Click on 'Your linked Accounts'
3. Wait for the login popup appearing, then click 'Close' button.
4. See that the error message: 'ERROR: Failed to link external account!' displays.

**Expected behavior**
It shouldn't show the error message when cancelling adding link accounts

**Video attachment:**
https://monosnap.com/file/aquS2cJ7B1aBkU0RkkXYbFs7eiCCRd
or [video.zip](https://github.com/topcoder-platform/community-app/files/2386240/video.zip)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 69

**Comment by ThomasKranitsas** [comment]
duplicate
