### ISSUE TITLE
[Settings - Account - Linked Account] Invalid URL message is shown even that the url is valid

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1495]
**Step To Reproduce**
1. Go to Settings -> Account -> Lined Account.
2. Click on 'External Link' and enter a valid URL.
3. Add more space at the end of the URL.
4. Error message 'Please enter a valid URL' appears.

**Expected behavior**
A URL with blank characters at head or tail should be considered as valid.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/36178659/45592291-35475b00-b993-11e8-8cc4-3e1a235e3dbf.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 69

**Comment by ThomasKranitsas** [comment]
what's under the blue box? `www.wikipedia.com` works fine when I try it
