### ISSUE TITLE
Uploading pdf document for avatar throws invalid error message

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1496]
Uploading pdf document for avatar throws invalid error message

1. Launch the application: https://www.topcoder.com/settings/profile
2. Login as valid user
3. In profile page,  upload a pdf document for avatar

**Expected behavior**
Error message should indicate the actual failure.  It should indicate the upload failed since the application doesn't support pdf images for avatar.

Actual Behavior:
Error message displayed is irrevalant.

**Desktop (please complete the following information):**
 - Browser - Chrome
 - Version v68
![uploading_pdf_document_throws_invalid_error_message](https://user-images.githubusercontent.com/33897533/45592297-cd8b1300-b986-11e8-9309-bd34d24467a0.png)

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
