### ISSUE TITLE
Upload Avatar:  While uploading avatar the application should list the supported document types

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1497]
**Describe the bug**
While uploading avatar the application should list the supported document types

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, verify the avatar upload section

**Expected behavior**
Supported document types for avatar image should be displayed.

**Desktop (please complete the following information):**
 - OS:  Win8
 - Browser - Chrome
 - Version  - v68

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
