### ISSUE TITLE
Profile Page: Birth date should not accept future date

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1500]
**Describe the bug**
Birth date should not accept future date

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, set birth date as future date
4.  Save changes

**Expected behavior**
Birth date field should not accept future date
![birth_date_should_not_accept_future_date](https://user-images.githubusercontent.com/33897533/45592568-1777f700-b98f-11e8-89bd-6d986ec3419f.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: - Win8
 - Browser - Chrome
 - Version - v68

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
