### ISSUE TITLE
Upload avatar: Error Displayed on uploading new avatar and saving changes

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1504]
**Describe the bug**
Error Displayed on uploading new avatar and saving changes

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, upload an image for avatar
4.  Click on save changes
5.  Verify the error message displayed

**Expected behavior**
No error message should be displayed on uploading images and saving the changes.
![error_displayed_on_uploading_new_avatar_and_saving_changes](https://user-images.githubusercontent.com/33897533/45592757-b868b100-b993-11e8-8758-fc279dee6882.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: - Win8
 - Browser - Chrome
 - Version - v68

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
cannot reproduce
