### ISSUE TITLE
[Settings] Not returning to the same page when coming back

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1506]
**To Reproduce**
1. Go to Settings -> Preference
2. Click on 'payment' icon on the left side bar
3. On the payment page, click on 'Cancel' button
4. See that it isn't back to the previous page

**Expected behavior**
It should be back to the previous page.

**Video attachment:**
http://take.ms/aP3WK or [video.zip](https://github.com/topcoder-platform/community-app/files/2386301/video.zip)

**Environment:** Desktop

**Comment by ThomasKranitsas** [comment]
The payments page hasn't been moved to the new site yet. This is not a valid issue
