### ISSUE TITLE
Profile:  Skill Remove:  When removed multiple skills at same time,  the success message comes as the same skill has been removed

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1508]
**Describe the bug**
When removed multiple skills at same time,  the success message comes as the same skill(first skill which was removed) has been removed

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, navigate to skill tab
4.  Add multiple skills
5.  Remove 2-3 skills
6.  Verify the success message displayed

**Expected behavior**
Removed skill name should be displayed.  

Actual Behavior:
Currently the name of the skill which was removed first was displayed.  
![multiple_skill_remove](https://user-images.githubusercontent.com/33897533/45593210-958fca00-b99e-11e8-8831-53a6caba2b4e.png)
![multiple_skill_remove1](https://user-images.githubusercontent.com/33897533/45593211-96286080-b99e-11e8-9eca-cdfc49c78f11.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win8
 - Browser - Chrome
 - Version - v68

**Comment by ThomasKranitsas** [comment]
duplicate
