### ISSUE TITLE
Profile Skill update: When added the same skill again,  in success message the skill name is not displayed.

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1509]
**Describe the bug**
When added the same skill again,  in success message the skill name is not displayed.

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, navigate to skill tab
4.  Add a skill
5.  Add the same skill again
6.  Verify the success message

**Expected behavior**
Skill name should be displayed in success message.
![adding_same_skill_success_message_skill_name_not_displayed](https://user-images.githubusercontent.com/33897533/45593228-3088a400-b99f-11e8-8a53-169786484064.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win8
 - Browser - Chrome
 - Version - v68

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
