### ISSUE TITLE
We are missing SVG icon for the lock on challenge details page

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#151]
.png icon is used as a temporary replacement at the moment.

**Comment by birdofpreyru** [comment]
@vic-topcoder Can you drop me this icon as SVG (I believe, the smaller gray one, and the larger blue on on submissions tab, are the same icon)?

**Comment by vic-topcoder** [comment]
[lock.svg.zip](https://github.com/topcoder-platform/community-app/files/1212496/lock.svg.zip)

**Comment by birdofpreyru** [comment]
@vic-topcoder The one you attached here is different from what we have in the design:

![screenshot](https://user-images.githubusercontent.com/20144632/29466433-2d583ea0-843d-11e7-97e0-7f25bf96b822.png)

![screenshot-1](https://user-images.githubusercontent.com/20144632/29466439-2f895c36-843d-11e7-89ac-ebdb4e06420f.png)

**Comment by vic-topcoder** [comment]
Push to DaraK for resources.

**Comment by Dara-K** [comment]
@birdofpreyru Check these
[icons lock.zip](https://github.com/topcoder-platform/community-app/files/1282603/icons.lock.zip)
