### ISSUE TITLE
Profile - Hobby:  Confirmation message to be displayed on deleting hobby

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1510]
**Describe the bug**
Confirmation message to be displayed on deleting hobby

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, navigate to hobby tab
4.  Click on delete icon in hobby list

**Expected behavior**
Confirmation message to delete the hobby to be displayed
![deleting_hobby_confirmation_message_to_be_displayed](https://user-images.githubusercontent.com/33897533/45593264-13a0a080-b9a0-11e8-8370-72a00044244c.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win8
 - Browser - Chrome
 - Version - v68

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by aravindm1** [comment]
This is issue is seen across application.  Before deleting any record confirmation needs to be displayed

**Comment by ThomasKranitsas** [comment]
@ajefts @vic-topcoder thoughts?

**Comment by ThomasKranitsas** [comment]
This has been fixed
