### ISSUE TITLE
Profile - Community:  The selected option not retatined and comes to default value

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1512]
**Describe the bug**
The select option not retatined and comes to default value

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In profile page, navigate to community tab
4.  Turn on / off both the radio button one after the another before success message comes up
5.  Verify the result

**Expected behavior**
The selected value for second option button should be retained

Actual Output:
The selected value for second option button is not retained and it comes to default one.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win8
 - Browser - Chrome
 - Version - v68

**Comment by aravindm1** [comment]
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
duplicate
