### ISSUE TITLE
[Settings] ComboBoxes collapse their dropdown list only if they were focused and mouse clicks on outside

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1513]
**To Reproduce**
1. Go to Settings -> Profile / or Tools
2. Click on the arrow of any comboxBox
3. Click on to outside
4. See that the combo box doesn't collapse its dropdown list

**Expected behavior**
The combo boxes should hide their dropdown lists when mouse clicks on outside

**Video attachment:**
http://take.ms/U5OJb or [video.zip](https://github.com/topcoder-platform/community-app/files/2386347/video.zip)

**Environment:** Desktop

**Comment by ThomasKranitsas** [comment]
This has been fixed
