### ISSUE TITLE
[IE 11][Settings - Tools] 'delete' icons are stretched horizontally

### ISSUE THREAD

**Issue by nqviet** [topcoder-platform/community-app#1514]
**Steps To Reproduce**
1. Go to Settings -> Tools -> Software / or Service Providers, Subscriptions
2. See that the 'delete' icons are being stretched.

**Expected behavior**
The icons should be proportional.

**Screenshots**
![untitled](https://user-images.githubusercontent.com/36178659/45593613-3a68d200-b9b4-11e8-809c-cbfd53082b4c.png)

**Desktop:**
 - OS: Win10
 - Browser: IE
 - Version: 11

**Comment by ThomasKranitsas** [comment]
duplicate
