### ISSUE TITLE
Account_linkedAccount:  Error message displayed when closed the linked account application window

### ISSUE THREAD

**Issue by aravindm1** [topcoder-platform/community-app#1515]
**Describe the bug**
Error message displayed when closed the linked account application window

**To Reproduce**
1.  Launch the application: https://www.topcoder.com/settings/profile
2.  Login as valid user
3.  In Accounts page, navigate to linked account tab
4.  Click on any linked account application
5.  Close the new window that opens
6.  See error

**Expected behavior**
On closing the new window the error popup should not appear
![open_linked_accounts_and_close_the_window](https://user-images.githubusercontent.com/33897533/45594417-fb3c8000-b9b7-11e8-8c99-60c662d3694c.png)
![open_linked_accounts_and_close_the_window_error](https://user-images.githubusercontent.com/33897533/45594418-fb3c8000-b9b7-11e8-8501-41f4c9dc57ab.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win8
 - Browser - Chrome
 - Version - v68

**Comment by ThomasKranitsas** [comment]
duplicate
