### ISSUE TITLE
UX Issue - Dropdown list is used for only 3 options

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1518]
**Describe the bug**
According to Jacob Nielsen, UIs should rather use radio buttons vs. dropdowns, as they have lower cognitive load. It is a common UX practice, that for a few options radio buttons are a better choice.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. Scroll down to 'Gender' and see the options

**Expected behavior**
For just a few options radio buttons should be used.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-16 18 01 18" src="https://user-images.githubusercontent.com/35376779/45598402-ccd09c00-b9db-11e8-85a3-1226a01963aa.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Firefox
 - Version: 62.0

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
@vic-topcoder thoughts?
