### ISSUE TITLE
UX Issue - Increased cognitive load due to the labels on the side on desktop

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1525]
**Describe the bug**
When the user browses the site on a desktop, the field labels are on the right of the field, not on the top, as on the mobile version. This increases the cognitive load as users cannot scan the form at the same fixation. Placing the label on the top would also allow using longer labels (e.g. same naming of the 'Primary Interest of Topcoder' on every device type)

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. Check Primary Interest label

**Expected behavior**
The labels should be placed on the top of the fields. The full label should be written out as well.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-16 18 01 18" src="https://user-images.githubusercontent.com/35376779/45600650-745fc580-ba00-11e8-9d60-1d83c1bc2f3a.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Firefox
 - Version: 62.0

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
that was based on the design so it's not a valid issue
