### ISSUE TITLE
UX Issue - Hint text disappears upon clicking into the field.

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1526]
**Describe the bug**
When I try to fill in a field, the hint text disappears immediately when I click into the field, which increases the load on my short term memory. It is a good UX practice to keep the hint text until the user actually starts to type in the textbox, aka overwriting the hint. 

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. Click on a textbox

**Expected behavior**
The hint text should stay intact until the user actually typed the first letter into the textbox.

**Screenshots**
https://www.screencast.com/t/dPD9idcv8jNS

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
This has been fixed
