### ISSUE TITLE
Broken Link : "ERROR 401 | Error: deleted_client | The OAuth client was deleted."

### ISSUE THREAD

**Issue by AkkiAkash22** [topcoder-platform/community-app#1527]
**Description :** 
Upon clicking on the "Google" icon in the "https://accounts.topcoder-dev.com/member" link, present under "OR LOG IN WITH" is leading to ERROR 401.

**Repro Steps :**
1. Launch Microsoft Edge/IE and navigate to the following link "https://accounts.topcoder-dev.com/member".
2. Click on 'Google' icon present under "OR LOG IN WITH"

**Expected behavior :**
A pop-up window must be launched from which user can login into his/her Google account.

**Screenshots :** 

**Image 1 :**

![image1](https://user-images.githubusercontent.com/43329295/45606247-2d55ec80-ba61-11e8-86f6-ecd7070f3c29.PNG)

**Image 2:**

![image](https://user-images.githubusercontent.com/43329295/45605707-ac94f180-ba5c-11e8-8c78-94e84c5c4c6b.png)

**Desktop :**
 - OS: [Windows]
 - Browser [Microsoft Edge, Internet Explorer]
 - Version [Microsoft Edge 41.16299.696.0, IE Version: 11.696.16299.0]

**Additional context :** 
The above issue has been observed on the registration page : "https://accounts.topcoder-dev.com/member/registration"

**Comment by nithyaasworld** [comment]
Issue seems to have resolved. Error is not displayed anymore. Verified in both the urls: https://accounts.topcoder.com/member and https://accounts.topcoder-dev.com/member/registration
