### ISSUE TITLE
Unable to Save the Basic Info Details

### ISSUE THREAD

**Issue by Arunkumar8992** [topcoder-platform/community-app#1528]
Description :
After entering the Input details in Basic Info page , unable to save it. Getting error message

Repro Steps :

Launch Chrome / Microsoft Edge/IE and navigate to the following link "https://www.topcoder-dev.com/settings/profile"

Under BASIC INFO tab, Enter the details.

Once Entered , while clicking "Save Changes" button getting Error window.

Expected behavior :
The inputs should be save for future reference.

Screenshot:

![image](https://user-images.githubusercontent.com/43334676/45612478-a6b10780-ba80-11e8-9d6d-5269d2c4a5a8.png)

Desktop :

OS: [Windows]
Browser [Google Chrome]
Version [69.0.3497.92]

**Comment by ThomasKranitsas** [comment]
there's not enough information on the issue description on how to reproduce the issue. I tried with multiple users, both existing and new and everything worked
