### ISSUE TITLE
The image link is broken on Development homepage

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#1531]
There is a broken image in the tutorials section at the bottom of the Development Homepage.
(https://www.topcoder.com/community/development/)

![image](https://user-images.githubusercontent.com/37835397/45639742-6a0bfd00-bace-11e8-8be8-ba32819211ab.png)

@birdofpreyru 
cc @ajefts

**Comment by NehaSharma02** [comment]
The image links are also broken here:

https://www.topcoder.com/community/development
https://www.topcoder.com/community/design
https://www.topcoder.com/community/data-science
https://www.topcoder.com/community/competitive-programming

**Comment by birdofpreyru** [comment]
Fixed by e42463336adaf9f54a599d7d11680a5256c29a6e, but not yet in prod
