### ISSUE TITLE
Agree to terms from terms page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1533]
We currently have a page to display a given set of terms.  Let's add the ability for a logged in user to agree to the terms by adding a checkbox at the bottom and an "Accept" button.

Checkbox label:  "I understand and agree."

Here is an example of the page we need to add the button to:
https://www.topcoder.com/challenges/terms/detail/21303

**Comment by ajefts** [comment]
@birdofpreyru is this one you'd want to take?

**Comment by birdofpreyru** [comment]
OK, the challenge is scheduled: https://www.topcoder.com/challenges/30071290

**Comment by ajefts** [comment]
Thanks!

**Comment by birdofpreyru** [comment]
@ajefts ready in dev

**Comment by ajefts** [comment]
Thanks @birdofpreyru !
