### ISSUE TITLE
P1:   Error '  404 HTTP Error ' 

### ISSUE THREAD

**Issue by PA384814** [topcoder-platform/community-app#1535]
**Describe the bug**
Getting error after opening the preferences tab in below link.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Preferences Tab'
3. See error

**Expected behavior**
It should ask a list of preferences that users want to give.

**Screenshots**
See the attached screenshot. 
![screenshot 482](https://user-images.githubusercontent.com/31277524/45748830-6fc92600-bc27-11e8-9757-7aaf9f743be4.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [ Version 68.0.3440.106 (Official Build) (64-bit)]

**Comment by sushilshinde** [comment]
fixed
