### ISSUE TITLE
Add vets community

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#154]
Add another community:

name = veterans
group = 20000006
visibility = public, with the Join option for people to self join.
challenge filtering = group 20000006
content = copy the qa community for now.
pages = home, learn, challenges, leaderboard

**Comment by ajefts** [comment]
fyi @dmessing

**Comment by birdofpreyru** [comment]
@ajefts Group `20000006` is already used for `srmx` community. Is it fine?

**Comment by ajefts** [comment]
Sorry, make it 20000007
