### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/community-app#156]
Adding FAQ section / menu on Home page of Topgear.topcoder.com
2.       In FAQ section, you can add existing links for
a.       How to participate in challenge ( Text may need customization for Topgear community)
b.       Code submissions for a challenge
c.       Roles, responsibilities for reviewer and copilot

Please have a place holder for documents specific to TopGear.
We will provide those documents, including customized content regarding participation etc.

**Comment by ajefts** [comment]
Maybe we can just add this section back and tweak the content:

[image: Inline image 1]

**Comment by birdofpreyru** [comment]
@ajefts Cannot see the image

**Comment by birdofpreyru** [comment]
@ajefts I guess, you mean `Learn The Basics` section at this page: http://local.topcoder-dev.com:3000/community/veterans/learn ?

**Comment by birdofpreyru** [comment]
@dmessing A draft version is pushed to dev
