### ISSUE TITLE
New Profile Settings - Data not moved

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#1566]
As I've checked my new Profile Settings page, I noticed that the data I had on Basic Info already completed on previous profile, is not there anymore.
![profile settings](https://user-images.githubusercontent.com/25185079/45927687-6e596f80-bf3f-11e8-8dd9-e6098f99b4ce.png)

**Comment by ThomasKranitsas** [comment]
This should be fixed now. Can you please check again?

**Comment by Dara-K** [comment]
Yes, it's fixed. Thanks!
