### ISSUE TITLE
[$10] The DOB field is subtracting 1 day after submitting the changes on profile page

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1571]
Please check and resolve, the Birth Date field is subtracting 1 day after submitting the page

1. Go to URL https://www.topcoder.com/settings/profile 
2. Edit the DOB field, adding one day from 07/12/1988 to 07/13/1988. 
3. Click on submit then the date is back to 12.

![inkededge-before_li](https://user-images.githubusercontent.com/34749364/45994303-a0d6aa00-c0b0-11e8-90bc-37e1f0f0b015.jpg)
![inkedchrome-after_li](https://user-images.githubusercontent.com/34749364/45994305-a3d19a80-c0b0-11e8-8246-53d2fadb8538.jpg)
![inkedchrome-before_li](https://user-images.githubusercontent.com/34749364/45994307-a6cc8b00-c0b0-11e8-9d88-e56713409bd5.jpg)
![inkededge-after_li](https://user-images.githubusercontent.com/34749364/45994311-a9c77b80-c0b0-11e8-9047-bc1d598ed34e.jpg)

**Comment by ajefts** [comment]
@ThomasKranitsas can we add this to the bug bash please?

**Comment by PrakashDurlabhji** [comment]
@ajefts can i take it? @ThomasKranitsas is it allowed to take it as of now?

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji yes, you can work on it

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas thanks. will complete immediatly

**Comment by PrakashDurlabhji** [comment]
@thomaskranitsas PR within hr near to complete it

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas after investigating from every side. also checking topcder-react-lib,it is working well. can you please check once again.if working well?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas no problem thanks

**Comment by ThomasKranitsas** [comment]
@tuliocasagrande that's interesting... 🤔 

Which OS/browser are you using?

**Comment by tuliocasagrande** [comment]
I've tested on Windows 10 with chrome and edge, and on Linux Mint 19 with chrome.

**Comment by ThomasKranitsas** [comment]
@tuliocasagrande can you please make watch your network tab (in chrome), get the request payload from the `PUT https://api.topcoder-dev.com/v3/members/{USERNAME}/traits` and check if the `birthDate` from the request payload matches with what you've entered?

<img width="1452" alt="screenshot 2018-09-27 at 18 40 24" src="https://user-images.githubusercontent.com/4612921/46157698-fbc0fa80-c284-11e8-9e13-8bbf671e6383.png">

I want to see if this is a frontend or backend issue.

**Comment by tuliocasagrande** [comment]
@ThomasKranitsas, the payload matches with what I have entered, however, the order is different than in your screenshot.

When entering 08/12/1988 as you did, I get:
![image](https://user-images.githubusercontent.com/1420513/46168329-89452000-c26e-11e8-9ff9-75ac33192f1f.png)

**Comment by ThomasKranitsas** [comment]
Thanks @tuliocasagrande! I've resolved the issue and should be deployed in dev shortly.
