### ISSUE TITLE
SVG for check-mark icon is missing

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#161]
![screenshot](https://user-images.githubusercontent.com/20144632/29464354-ea73e064-8435-11e7-972f-dbf60645d842.png)

@vic-topcoder drop it to me please!

**Comment by vic-topcoder** [comment]
Ask DaraK for resources

**Comment by Dara-K** [comment]
@birdofpreyru  Check attached 
[icon check mark.zip](https://github.com/topcoder-platform/community-app/files/1282594/icon.check.mark.zip)
