### ISSUE TITLE
Update CSS so that link color is #006DEA

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1648]
**Describe the bug**
The Design Team has informed us that the color of our links are wrong.  Please make the global change of links to use #006DEA in our CSS.

@kkartunov

**Comment by kkartunov** [comment]
This requires an update in https://github.com/topcoder-platform/topcoder-react-ui-kit
I do not have push access currently to this repo. Will need to ask @birdofpreyru to provide.

**Comment by hokienick** [comment]
@birdofpreyru can you please help @kkartunov out with this?

**Comment by kkartunov** [comment]
or @ajefts ?

**Comment by birdofpreyru** [comment]
@kkartunov @hokienick access given
