### ISSUE TITLE
Change border-top of cards to a new color #26ade9

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1650]
**Describe the bug**
Currently the border at the top of the component "Card" is a shade of blue that does not adhere to our brand guidelines.  Please change this color in the CSS to: #26ade9

@kkartunov

**Comment by kkartunov** [comment]
@hokienick could you point me to see which card is in question? There are multiple possibilities. Could you provide a screenshot?

**Comment by kkartunov** [comment]
Should be fixed by db0fcc2cb53050747fa3392e6890db1d256b994b
