### ISSUE TITLE
[$40] - Update TopcoderHeader and Challenge Listing to properly support links within the app

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#166]
At the moment, all links in the standard TopcoderHeader component lead to the main Topcoder website, thus they use `<a>`, which, if a link address is changed to an endpoint within Community App, reloads the app when clicked. These links should be updated to use `<Link>` from `utils/router` to seamlessly support both remote or local URLs.

The same applies to the links to the Challenge Detail pages from Challenge Listings.

**Comment by Colinh84** [comment]
Can you assign me to this issue please?
