### ISSUE TITLE
Unable to update profile

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1667]
user handle: Alex_Z_

For the above handle, we have updated the profile information (first name, last name, DOB and country) in our database but the changes are not reflecting here https://www.topcoder.com/settings/profile 

Please check and fix the issue.

**Comment by ThomasKranitsas** [comment]
@JayaDhaka where did you modify the data? I mean, which table?

Can you provide more info as this is not enough to understand what the issue could be.

**Comment by RiteshTC** [comment]
Both informix and Dynamo Db tables MemberTrait, MemberProfile

**Comment by ThomasKranitsas** [comment]
That's interesting...

So, when you modify the data from the Settings page it reflects the changes in dynamo DB but when you modify the data directly in dynamo DB you don't see the changes in the settings page?

I'm not exactly sure how to reproduce the issue.

**Comment by ThomasKranitsas** [comment]
@RiteshTC can you please check now that we have the processors in place? I tried with a new profile and it worked fine.

**Comment by nithyaasworld** [comment]
This is no more an issue. @JayaDhaka @RiteshTC If its not resolved for you, please feel free to re-open.
