### ISSUE TITLE
CMS error on mm-feature-experiment branch

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1668]
<img width="520" alt="screen shot 2018-10-08 at 6 18 00 pm" src="https://user-images.githubusercontent.com/683231/46610053-3baa9c00-cb27-11e8-9255-f1796226f5ae.png">

**Comment by kkartunov** [comment]
Can not reproduce: https://drive.google.com/file/d/1qBEqXq1j6gbA0wwvO6BotnrcJaPlzQXy/view
