### ISSUE TITLE
Add financial institution to settings

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1681]
Add "Financial Institution" to the dropdown for service providers.  This will allow users to enter financial institutions that they have accounts with.  Some financial customers require this for participation in certain challenges.

![image](https://user-images.githubusercontent.com/3812270/46759880-76831000-cc9e-11e8-843f-961c2dbd31ee.png)

Use the icon that we currently use for "Payments".

**Comment by ajefts** [comment]
@urwithat think we could do this as a quick add?

**Comment by ThomasKranitsas** [comment]
@urwithat I've made the required changes on the backend and I'll push the frontend changes in a bit.

Though, you'll either have to run the script to init the lookups again or add the new value into the DB manually since we don't have POST/PUT support on the lookup endpoints.

**Comment by ThomasKranitsas** [comment]
Fixed
