### ISSUE TITLE
Header for Accordion Component should be H2 instead of H1

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1684]
We have changed the headers globally, but for some reason the Accordion headers were not affected.  Please make sure those headers take from the global css and change it to H2.

@kkartunov

**Comment by kkartunov** [comment]
@hokienick please, point to an example. I do not understand which headers are in question?

**Comment by hokienick** [comment]
Sorry about that!  Check out https://blockchain.topcoder.com/learn

You can see that first accordion section (clickable text to the left changes text to the right), the header is not correct.  [The viewport](https://app.contentful.com/spaces/b5f1djy59z3a/entries/2FrZBDUlFK4WgQSgws6Yeg?previousEntries=ZDESwJrkSAOsikiueUiKI) accepts just the text for this title. The title should use an h2 tag that matches the other h2 titles that you see on this page.

**Comment by kkartunov** [comment]
@hokienick we should better update the styling to match the one for H2 instead of switching to H2 elements. There is special click handlers assigned so those should be better divs. You OK with this?

**Comment by hokienick** [comment]
Yes that sounds good to me!
