### ISSUE TITLE
Topgear Leaderboard Update

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1687]
Add the following columns to the topgear leaderboard:

- Wins
- Total Earnings

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1325289

**Comment by kkartunov** [comment]
@ajefts https://api.topcoder.com/v4/looks/458/run/json/ this is the related API look. We need `wins` and `totalEarnings` is the response. We do have currently `challengecount` and `points` available but I am not sure if those match expected?

**Comment by ajefts** [comment]
@kkartunov Please check the latest api:  https://api.topcoder.com/v4/looks/458/run/json/

Thanks.

**Comment by kkartunov** [comment]
@ajefts update available for review here: https://community-app.topcoder-dev.com/__community__/wipro/leaderboard
I was not able to find differences but only duplicates. Looks that `wins` = `points` and `Total Earnings` = `# of Challenges`. Again is this desired behavior?
