### ISSUE TITLE
The "Learn" dropdown from the menu is currently not clickable but needs to be.

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1690]
Please make the "Learn" menu item on the top header bar link to https://www.topcoder.com/community/learn

Also assure that this works on legacy pages such as the forums as well.

**Comment by kkartunov** [comment]
@hokienick I pushed a commit that fixes this but only for the community-app. I do not know how to update legacy pages nor have access to do so. Probably we need @ajefts or @birdofpreyru to explain then we could eventually handle fixes in legacy pages.

**Comment by hokienick** [comment]
@kkartunov figured that may be the issue.  I'll contact @ajefts and see what he says.  Thanks for pushing to community-app!

**Comment by hokienick** [comment]
Creating another ticket for Tony.  This can be considered closed now.
