### ISSUE TITLE
Data Science How To page - Image is deformed

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1691]
On the [Data Science How To page](https://www.topcoder.com/community/data-science/how-to-compete) ([Viewport](https://app.contentful.com/spaces/b5f1djy59z3a/entries/4JY0bIXRo4yguOggiGYmCg))the icon next to "beginning a match" on the left side bar seems to be squished.

This image is the same size as all the other icon images so it seems weird that it would look so different.

**Comment by kkartunov** [comment]
@hokienick This is the original image. It is 192x192px on left it is resized equally to 60x60px thus apspect ratio is same as original and not transformed. If it looks squished we need new icon image made. See original: 
![](https://images.ctfassets.net/b5f1djy59z3a/6wa5wi5p3qCUii0Y2y6kcM/3bfae9317c7f8c11371fcd6000da5ebf/ds-match-begin.png)

**Comment by hokienick** [comment]
It's strange.  Sometimes it seems squished, but when i resize the window it looks fine.  Let's close this ticket.
