### ISSUE TITLE
When creating Cards in Contentful the bottom gets clipped.

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1692]
This can be solved by increase the padding at the bottom of the container, but we do not want this to be a global change.  Is there a way to increase the padding of the container if a card is recognized?

Please use this viewport as an example: https://app.contentful.com/spaces/b5f1djy59z3a/entries/vTN2qPNsXuiws2G2UyyE2

**Comment by kkartunov** [comment]
@hokienick We do not need touching the container. We could increase the bottom-margin of a card. This will fix it. I suggest `bottom-margin: 1em` OK?
