### ISSUE TITLE
Google Calendar IFrame is not responsive

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1693]
The[ Events Calendar](https://www.topcoder.com/community/events) ([Viewport](https://app.contentful.com/spaces/b5f1djy59z3a/entries/5ylEiWAjPqSUycO6ssAkgo?previousEntries=6pTNNoF9wQuCy2c6qIk4yI)) on our site is not mobile friendly.  It is currently in an iFrame and doesn't scale correctly.

After a quick google search I came across this article, which may help! https://answers.squarespace.com/questions/54774/how-to-embed-a-google-calendar-in-a-responsive-way.html

**Comment by kkartunov** [comment]
Fixed in Contentful https://app.contentful.com/spaces/b5f1djy59z3a/entries/5ylEiWAjPqSUycO6ssAkgo?previousEntries=6pTNNoF9wQuCy2c6qIk4yI
