### ISSUE TITLE
Links to Studio Site To Be Updated

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#1694]
**Describe the bug**
We have a couple of links on our site who still point to our old Topcoder Studio site which is no longer available.

**To Reproduce**
When going to Manage submission page,  on pressing the download icon to receive and check our submission, it takes us to the old Studio.

![image](https://user-images.githubusercontent.com/25185079/46919386-6c874700-cfe7-11e8-9c89-c0fe3dfab3cf.png)

Same thing happens in the email, when receiving notes to check the screening score and even to go to challenge details page.
![image](https://user-images.githubusercontent.com/25185079/46919409-993b5e80-cfe7-11e8-9995-39667929778d.png)

Hope all links can be updated to work as they should.

Thanks.

**Comment by ajefts** [comment]
@cwdcwd can we get this on someone's plate now that we have the design download URLs fixed?  I think we can use the OR links for everything....

**Comment by cwdcwd** [comment]
@ThomasKranitsas can you push on this one a little?

**Comment by ajefts** [comment]
Duplicate tracked at https://github.com/topcoder-platform/community-app/issues/1252
