### ISSUE TITLE
CSS loading issue in Dev

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#17]
As of the moment CSS loading in development environment has some problems, as it loads pre-build css file, and then loads updates from HMR as a part of JS bundle. This is not a correct setup, and should be updated.

**Comment by birdofpreyru** [comment]
Resolved in 6884aad9308d928446c740946060d7091a2b30d3

**Comment by SathyaJayabal** [comment]
@bug-hunt-helper help
