### ISSUE TITLE
[$120] - Challenge Details - Checkpoints - Refactor the code

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#170]
The code in `/src/shared/components/challenge-detail/Checkpoints/index.jsx` does work, but is hacky, thus should be refactored. The fix should address the following:

- Right now the component uses local state, window resize event, and some hacky code to "trim" the content when page size goes under 768 px. The same should be achieved by pure SCSS (using media mixins defined in `/src/styles/mixins/_media.scss`.

- Also collapse / expansion of the checkpoint sections is handled using the local state. It should be refactored to properly use Redux store / actions / reducers.

**Comment by daft300punk** [comment]
Please assign me this.

**Comment by birdofpreyru** [comment]
@daft300punk Consider yourself assigned. I have just noticed that I don't have enough rights in the repo to add contributors, and without it, I cannot technically assign people who are not contributors. Once my rights corrected, I'll fix it.

**Comment by daft300punk** [comment]
Check out the PR - https://github.com/topcoder-platform/community-app/pull/229

**Comment by daft300punk** [comment]
Is it a bug? The original site doesn't do anything when clicked on those side ids. Anyways, it is easy to fix. I will submit PR as soon as you confirm.

**Comment by daft300punk** [comment]
Updated the PR, take a look. https://github.com/topcoder-platform/community-app/pull/229

**Comment by daft300punk** [comment]
Updated the PR, take a look https://github.com/topcoder-platform/community-app/pull/229

1. Removed jquery dependency
2. To check scroll to feedback, click on the first 4 feedback ids in the side bar. This will increase page size. Now, go to top, and then click on the 5th feedback id. Should scroll down to it.
