### ISSUE TITLE
The "Learn" dropdown from the menu is currently not clickable in Legacy Apps but needs to be.

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1701]
Please make the "Learn" menu item on the top header bar link to https://www.topcoder.com/community/learn

This has been completed on the community app but needs to be updated in legacy apps.

@ajefts @skyhit

**Comment by ajefts** [comment]
@skyhit more generally on this one, would you be able to get the header nav and footer updated in the legacy apps to match what we have in community-app?

**Comment by hokienick** [comment]
This seems to be working.  Closing.
