### ISSUE TITLE
Cards should be the same width when in a row or grid

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1706]
Cards are positioned well on the page when in a row or grid, but if one card's title is shorter than the others, the entire card's width doesn't match the others and throws off the balance of the page.

This can be seen on the [Anemoi Landing Page ](https://www.topcoder.com/lp/anemoi)as well as the [Statistics](https://www.topcoder.com/community/statistics) page.

**Comment by hokienick** [comment]
Figured out the issue with the grid.

**Comment by kkartunov** [comment]
@hokienick I delayed this as wanted to confirm if we want all cards to take 100% width of the parent container. This will work well for grids but will expand stand-alone cards. OK with that?
