### ISSUE TITLE
Dictate the number of rows the leaderboards show

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1720]
We would like to use the TCO leaderboards on the track homepages, but most of them are very long and take up a majority of the page.  Can we introduce a parameter that allows us to choose the number of rows the leaderboard shows?

In addition, I noticed that randomly some competitor's avatars do not show (is there an issue with the api calls?) but it is random, which members they are each time the page is reloaded.

**Comment by kkartunov** [comment]
@hokienick Implemented as `memberLimit` property. Add it to the JSON controlling the component(App Component).

Avatars are hosted by our cdn that sometimes have issues. It works in prod but fails in dev. We are not in control of this thus I suggest we leave it there as it is.
