### ISSUE TITLE
Send more info to segment

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1721]
We make a call at https://github.com/topcoder-platform/community-app/blob/f26ee94553fff5776fc7352f2d4b62449a7ce497/src/client/index.jsx#L27 that sends info to Segment, which we can then leverage downstream in other tools.  I'd like to add the following if possible:

1.  list of groups that the user belongs to
2. the tracks that the user belongs to (http://api.topcoder.com/v3/members/TonyJ/)

**Comment by ajefts** [comment]
@sushilshinde could we do this as a quick add?  Maybe @ThomasKranitsas can help...

**Comment by ThomasKranitsas** [comment]
1. Do you only need the group IDs?

**Comment by ajefts** [comment]
ideally both id/name, but what options do we have?

**Comment by ThomasKranitsas** [comment]
The `/groups` endpoint returns data like this:

```
{
  "id": "********",
  "modifiedBy": null,
  "modifiedAt": null,
  "createdBy": "********",
  "createdAt": "2017-10-19T10:54:47.000Z",
  "name": "Veterans",
  "description": "Veterans",
  "privateGroup": true,
  "selfRegister": true,
  "subGroups": null,
  "parentGroup": null
}
```

**Comment by ThomasKranitsas** [comment]
@ajefts I've fixed this. Let me know if it works as expected. Should be deployed in dev shortly.
