### ISSUE TITLE
Ability to add other content to Countdown Component

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1723]
I am receiving a request for our Countdown banner to add extra buttons and/or text such as "Add to Calendar" or to view the date/time in their timezone.  Is this possible?

**Comment by kkartunov** [comment]
@hokienick can we just use a `contentBlock` below it and add there what is needed? You are asking me here to "embed" the whole functionality of it inside the counter...is this really worth the effort?

**Comment by hokienick** [comment]
I guess we can do this is if eliminate bottom padding from Countdown Block and top padding from Content Block

**Comment by kkartunov** [comment]
@hokienick yeah they both have `extraStyles` support now thus it is totally doable.
