### ISSUE TITLE
User Handles are not displayed in rated colors

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#173]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user

- Go to /challenges/30058973

- Click 'REGISTRANTS (22)' tab

- Check the user handles

Actual Result(s)
-----------------------------------------------------------------
- User Handles are not displayed in rated colors

Expected Result(s)
-----------------------------------------------------------------
- User Handles must displayed in rated colors

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2](https://user-images.githubusercontent.com/4592712/29668030-530822aa-88fc-11e7-82d4-796dcecbb6af.jpg)

**Comment by birdofpreyru** [comment]
Does not look like a bug for me, as the raiting colors are not used in the current version of this page either.
Though, for this I rely on the final decision of @vic-topcoder: if he says, we should use rating colors for handles here, I'll accept this and open it for fix.

**Comment by vic-topcoder** [comment]
Not a bug, and we're going to redesign that particular tab soon to use the full avatar that displays more  relevant user data (like on the user search page).
