### ISSUE TITLE
Learn more buttons reloads same page

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#1730]
On the link "https://www.topcoder.com/solutions/" all Learn More buttons only reloads same page.
Please check and fix.

@RiteshTC 
@ajefts 
@birdofpreyru 

![image 3](https://user-images.githubusercontent.com/37835397/47679697-e1af6a80-dbea-11e8-9c66-30a1145854ca.png)

**Comment by NehaSharma02** [comment]
@birdofpreyru Please look into it.

**Comment by kkartunov** [comment]
This is on the WP instance and belongs there not here...

**Comment by nithyaasworld** [comment]
Issue resolved.
