### ISSUE TITLE
annoying flickering of challenge details

### ISSUE THREAD

**Issue by BetterCallSky** [topcoder-platform/community-app#1731]
Steps:
- open challenge details
- challenge details are visible (from SSR)
- after 2-4s there is a loader
- challenge details are visible again

It's very easy to notice it if you open any link from `#dev-challenges` from Slack.

I reported it multiple times on Slack, but it seems nobody cares :wink:

**Comment by sushilshinde** [comment]
We are addressing this

https://github.com/topcoder-platform/community-app/issues/1957

So closing
