### ISSUE TITLE
Challenge listing automatic reload inconsistent results to initial load

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#1734]
**Describe the bug**
The challenge listing component will automatically reload all challenges once per configured amount of time(currently 300s). When this occurs results are different than those loaded initially but should no be.

**To Reproduce**
1. Go to https://www.topcoder.com/challenges?bucket=openForRegistration
2. Wait for page to and note the count of `Open for registration` in the right sidebar.
3. After ~5min the page will auto reload. Then check the count again it should match but it does not.

**Expected behavior**
Challenges count and the listing should match between reloads.

**Screenshots**
![screenshot from 2018-11-01 10-30-52](https://user-images.githubusercontent.com/5585002/47842826-71f5d700-ddc6-11e8-8b2c-463402be87bb.png)
![screenshot from 2018-11-01 10-45-09](https://user-images.githubusercontent.com/5585002/47842825-71f5d700-ddc6-11e8-92cb-4eeda53b87b3.png)

**Comment by kkartunov** [comment]
@ThomasKranitsas could this go via tcX?

**Comment by sushilshinde** [comment]
@kkartunov we will fix this in performance exercise. Currently on hold

**Comment by kkartunov** [comment]
@sushilshinde OK

**Comment by sushilshinde** [comment]
I think we covered this in performance effort
