### ISSUE TITLE
[$20] - Submit and Register disable button color is not correct

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#175]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user

- Go to /challenges/30058529

- Check the Submit and Register disable buttons

Actual Result(s)
-----------------------------------------------------------------
- Button color is BLUE

Expected Result(s)
-----------------------------------------------------------------
- Button color must Gray

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![3](https://user-images.githubusercontent.com/4592712/29668023-4f752d36-88fc-11e7-8513-d870aea38c66.jpg)

**Comment by sdgun** [comment]
![3 0](https://user-images.githubusercontent.com/4592712/29668289-40857bfe-88fd-11e7-8c87-d7328cd03f7a.jpg)

**Comment by birdofpreyru** [comment]
I accept it (1 point), as it is indeed different from design specs.
Though, @vic-topcoder wanna double check with you, should we make it gray or leave pale blue? Originally, it was done pale blue, because we took track-dependent color accents too seriously, so design / dev / datasci pages had these buttons blue / green / orange when active, and pale versions of these colors when disabled.

**Comment by vic-topcoder** [comment]
Correct: From original design point the cases are:

- Not registered - all buttons but Register are disabled (gray style by default).
- Registered - can unregister (danger button), and primary Submit
- Submitted - can unregister (danger), Submit and Manage submissions (primary)

The latest styles in https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_buttons.scss take care of all those states - reuse the styling please.

**Comment by birdofpreyru** [comment]
### Expected Fix
Ok, should be fixed according to Vic's comment above. Though, rather than adding those styles he mentioned directly to button elements, be sure just to modify themes of standard buttons in `/src/shared/components/buttons` so that the result matches the specs

**Comment by birdofpreyru** [comment]
@vic-topcoder Wanna double-check once more. In the challenge details style specs these two pages actually contradict each other:
![styleguide-ui-kit-buttons](https://user-images.githubusercontent.com/20144632/29828054-00a4d402-8cdc-11e7-8ef1-29172d9faac2.png)
![styleguide-header](https://user-images.githubusercontent.com/20144632/29828060-047dd682-8cdc-11e7-83f4-176c2ec03dad.png)
from the first one it looks like disabled state of primary (blue) button should have pale-blue packground. In the artboard for buttons however, disabled buttons are gray, i.e. just of different type (I call it secondary button within community app). So, we can do either way, just wanna double-check.

**Comment by vic-topcoder** [comment]
Yes, that's a bit old. The code that I pointed earlier manages the disabled state for all buttons:

``` SCSS
button[disabled],
a.tc-btn[disabled],
button[disabled]:hover,
a.tc-btn[disabled]:hover,
button[disabled]:active,
a.tc-btn[disabled]:active {
  opacity: 0.3;
  filter: grayscale(90%);
  pointer-events: none;
}
```
