### ISSUE TITLE
Topgear leaderboard is not loading

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1751]
In the below link not able to see the topgear leaderboard 
https://topgear.topcoder.com/leaderboard 

![image 28](https://user-images.githubusercontent.com/34749364/48466471-05d69280-e80c-11e8-9590-eaead8467cf0.png)

Please check and fix the issue.

@ajefts

**Comment by JohnPranay** [comment]
Development team could you please solve this issue on high priority based.  Thank you.

**Comment by kkartunov** [comment]
@JohnPranay this issue is known and solved by 2e75d27becd227384c4a538d776ba995779ec325. It will land in production with next release.
