### ISSUE TITLE
CHALLENGE LISTING page stucks when user selects any item from the filter

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#177]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Click Filters

- Expand the keyword drop down and select any item

- Observe the page and try to clear the filter, try to click on any item on the page

Actual Result(s)
-----------------------------------------------------------------
- CHALLENGE LISTING page stucks when user selects any item from the filter

Expected Result(s)
-----------------------------------------------------------------
- Must not stuck the app

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![4](https://user-images.githubusercontent.com/4592712/29668708-c60d35b8-88fe-11e7-8929-e6312a4db617.jpg)

**Comment by birdofpreyru** [comment]
@sdgun Does not stack for me. I mean, with many combinations of filters, it keeps on showing placeholders instead of past challenges, just because it keeps on looking for such challenges (and due to backend restrictions we cannot do it in a better way), but if I press on any other element of the page, it is responsive: it immediately stop looking for past challenges, and does whatever I ask for. Thus, does not look like a bug for me, however, probably, you can supply more details for the cases when it really stucks?

**Comment by sdgun** [comment]
@birdofpreyru Please check the video attached below;

https://www.screencast.com/t/UBec1iYzKP

**Comment by birdofpreyru** [comment]
@sdgun No, it is not really stuck. You just set different filtering options that have no matching challenges. Under the hood it keeps on searching such challenges in past, but can't find them, so you see the placeholders.

The reason for that is the backend, at the moment, does not provide the same fancy filtering options, as we have in the frontend. So, while for active challenges, we can just load them all intially (not that many of them), and do any search at the frontend side in no time, for past challenges there are ~30 000 of them, and the best search we can do for filters not supported by backend is to fetch 50 challenges, filter them on the frontend side, show those that match, if there is not enough challenges found to fill the screen, we fetch the next 50, and so on...

**Comment by sdgun** [comment]
Thanks for the clarification @birdofpreyru :+1:
