### ISSUE TITLE
[$10] - [Bug Hunt - NEW BUG]Search contest with keyword "          ", no item show

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#179]
I think "       " should be works like ""
<img width="1651" alt="2017-08-24 9 38 03" src="https://user-images.githubusercontent.com/3046795/29668983-90ec5d1c-8914-11e7-8d06-f800f0ad71d4.png">

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

### Expected Fix
When we do the free-text search we should trim the search string of whitespace-like characters, before doing the actual search (it works fine with a single whitespace now, as any challenge title usually has some single spaces).

**Comment by elfman** [comment]
@birdofpreyru can you assign me to this bug?

**Comment by elfman** [comment]
ready for review, I can't change label
