### ISSUE TITLE
Unable to get member active challenges

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/community-app#1791]
**Describe the bug**
Getting the error message while accessing the profile page.

**To Reproduce**
1. Go to 'https://www.topcoder.com/members/weiszago/'
2. Click on 'Activity option'

**Screenshots**
![image](https://user-images.githubusercontent.com/44159743/49713674-c1ee7600-fc6f-11e8-834a-4ac878166870.png)

**Comment by RiteshTC** [comment]
@cwdcwd @sushilshinde

**Comment by sushilshinde** [comment]
@skyhit please comment

**Comment by sushilshinde** [comment]
Trying to fix it today

**Comment by kkartunov** [comment]
@sushilshinde why assigned to me?

**Comment by kkartunov** [comment]
Fixed.
