### ISSUE TITLE
Incorrect redirection on topgear

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/community-app#1792]
**Describe the bug**
Incorrect redirection on topgear.
when user is logging out from the topgear.topcopder.com,
and again login to topgear, redirection is happening to topcoder.com.

**Expected behavior**
Redirection should be to topgear.topcoder.com.

**Comment by nithyaasworld** [comment]
Not able to verify this in Topgear-dev environment as the login process is done by logging into www.topcoder-dev.com and then accessing the topgear-dev.topcoder.com
