### ISSUE TITLE
Handle color changed

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/community-app#1796]
**Describe the bug**
Color of the handle for the member has been changed.

Handle color is now black instead of dark blue.

**Comment by sushilshinde** [comment]
Please screenshots and steps @ajaysaini9782

**Comment by ajaysaini9782** [comment]
@sushilshinde 
https://www.topcoder.com/challenges/30076476/?tab=registrants

![screenshot handles](https://user-images.githubusercontent.com/44159743/49789963-220a1880-fd53-11e8-8445-9373471e4a8d.png)

**Comment by sushilshinde** [comment]
it should be 

should be dark blue 110: #006DEA

**Comment by sushilshinde** [comment]
@ThomasKranitsas please go ahead with this. Blue color here only represents href html link, not the ranking. This change applied to non-MM challenge pages. 

FYI... @Dara-K

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/community-app/commit/f8d53e6e01bd9074d2cb5776f176227ed545d6f7
