### ISSUE TITLE
Issue related to submission tab

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/community-app#1797]
**Describe the bug**

If the user tries to click on Submission tab on a challenge, the system takes him to a page with no return back.

**Comment by sushilshinde** [comment]
@ajaysaini9782 please steps and screenshot

**Comment by RiteshTC** [comment]
@Dara-K

**Comment by sushilshinde** [comment]
@Dara-K can you share the challenge URL

**Comment by Dara-K** [comment]
It's the same for all the challenges - I don't remember that one exactly but  you can check these - designa nd development:

https://www.topcoder.com/challenges/30076591?tab=registrants
https://www.topcoder.com/challenges/30076504?tab=registrants

**Comment by sushilshinde** [comment]
@Dara-K please ping me on slack

**Comment by sushilshinde** [comment]
Hoping to solve this here https://github.com/topcoder-platform/community-app/issues/1817

**Comment by ThomasKranitsas** [comment]
I'm not sure I understand what the issue here is but I did some fixes. Can someone verify if the issue has been fixed?

**Comment by sushilshinde** [comment]
fixed

**Comment by Dara-K** [comment]
Looks good, thank you!

**Comment by Dara-K** [comment]
Seems like this issue is happening again: https://www.topcoder.com/challenges/30078212?tab=registrants. Can you fix it again? @ThomasKranitsas  @sushilshinde

**Comment by Dara-K** [comment]
The issue was that the handles of the members are showing as black again instead of blue.

**Comment by ThomasKranitsas** [comment]
this was requested by @vic-topcoder @dmessing @ajefts 

Here's the exact comment from @vic-topcoder:
> black if there’s no rating, not blue for sure

**Comment by Dara-K** [comment]
Okay - I will talk to Vic.
