### ISSUE TITLE
Dashboard Announcement Responsiveness

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1799]
This ticket is to make #1771 - Dashboard Announcement Layout responsive as per your suggestion.

**Comment by kkartunov** [comment]
@hokienick we need to define what is expected here. As far I can see the layout is responsive.

**Comment by hokienick** [comment]
That seems to be formatted correctly on mobile.  Closing this ticket, but let's keep an eye on it in different formats (i.e. with a video)
