### ISSUE TITLE
[$20] - 'My challenges' section won't hide from the page when user deactivated from the filter section if user have only Dev Challenges

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#180]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Register for few Dev challenges

- Switch OFF the 'Development' and 'Data Science'

- Observe the section

Actual Result(s)
-----------------------------------------------------------------
- 'My challenges' section won't hide from the page when user deactivated from the filter section if user have only Dev Challenges

Expected Result(s)
-----------------------------------------------------------------
- Must hide the 'My challenges' section 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):**  IE11

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![5](https://user-images.githubusercontent.com/4592712/29669106-037fde7c-8900-11e7-932f-56b134e95152.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by birdofpreyru** [comment]
Seems to be not an issue anymore
