### ISSUE TITLE
[$20] - Round 1 submission date entries in round 2 column

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#181]
Steps to Reproduce
1. Login to go for http://community-app.topcoder.com/challenges?
2. Go to http://community-app.topcoder.com/challenges/30058719/?type=design
3. Select option Registrants
4. Observe column for Round1 and Round2 submissions

Screenshots 
![image](https://user-images.githubusercontent.com/20595047/29669109-051b23c2-8900-11e7-907b-1da920a1f87d.png)

Expected Result:
Entries should be in Round 1 submission

Current Result:
Round 1 submission dates reflecting in round 2 column

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

**Comment by shubhendusaurabh** [comment]
assigning myself

**Comment by shubhendusaurabh** [comment]
@birdofpreyru This looks like service bug. The checkpoint array is empty even though checkpoint deadline has passed.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Ok. I'll double-check it myself later. Feel free to work on other staff in the meantime.

**Comment by birdofpreyru** [comment]
Seems to be not an issue anymore.
