### ISSUE TITLE
Remove Copyright notice from Marathon Match Challenge Statement

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#1815]
**Describe the bug**
Remove the copyright text from the marathon match problem statements. 
https://www.topcoder.com/challenges/17323

**Screenshots**
<img width="703" alt="remove copyright" src="https://user-images.githubusercontent.com/5771673/49867886-cb274080-fe31-11e8-8913-b467cbd000ab.png">

**Comment by RiteshTC** [comment]
cc @alamora

**Comment by alamora** [comment]
Actually, I dont see it: odd.  Anyway, please update the copyright.

**Comment by RiteshTC** [comment]
@sushilshinde 
Please help here.

**Comment by ThomasKranitsas** [comment]
This doesn't seem to be an issue in the community app. The API returns it's as text which means it was probably entered in the spec (maybe in Direct?).

See: http://api.topcoder.com/v4/challenges/17323

It's part of the `detailedRequirements`.

I would say, the copilot copy-pasted that paragraph in the spec. We can close this ticket.

**Comment by alamora** [comment]
Please do NOT close this ticket.  The purpose of this ticket is to fix the problem.  It's not fixed.

Note the Marathons are managed through MPSQAS - are you taking that into account?  Eg I dont personally know if the community API has anything to do with it.  These pages are legacy.

If its a copilot copy/paste issue, lets experiment and make sure that's the case before we close this.  I'll ask t-mac and report back here, but, please dont close this until its fixed.

Andy

**Comment by ajefts** [comment]
@sushilshinde can you please triage this one?  I'm assuming the text was loaded from informix into elastic search when we did the data migration from old to new.

Let's strip the copyright content out of the requirements field and make it part of the challenge page template similar to what we do for the payments paragraph at the bottom of the challenges.  It should only show on marathon match pages.

**Comment by sushilshinde** [comment]
I think we found the problem after long debugging exercise with @skyhit 

This is one jar where this text is hardcoded, @skyhit will update the challenge API with this new JAR.

So it will be always a current year henceforth.

fyi @ajefts @alamora

**Comment by sushilshinde** [comment]
Fixed from the API side.

fyi @alamora @ajefts

**Comment by alamora** [comment]
Thank you so much.  These details are important, particularly in data science, where we want customers to trust us with sensitive information.  I appreciate the time and attention you paid to this!!
