### ISSUE TITLE
[$10] - 'Wireframe' challenges won't have heading in the tool tip

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#182]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Switch OFF the 'Development' and 'Data Science'

- Hover over tge 'Wf' icon in a Wireframe

Actual Result(s)
-----------------------------------------------------------------
- 'Wireframe' challenges won't have heading in the tool tip

Expected Result(s)
-----------------------------------------------------------------
- Must display the Header Title as Wireframe (Wf)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![6](https://user-images.githubusercontent.com/4592712/29669221-588253fa-8900-11e7-85ce-2e57e80c8c56.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by chqy24** [comment]
assign to myself

**Comment by chqy24** [comment]
ready for review, PR #262

**Comment by iversonLv** [comment]
Soory
Unassign myself..
Thx.
