### ISSUE TITLE
Clicking on the Check Point ID #241486 won't expand the section

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#183]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058648/?type=design

- Click 'CHECKPOINTS (7)'

- Click on the #241486

Actual Result(s)
-----------------------------------------------------------------
- Clicking on the Check Point ID #241486 won't expand the section

Expected Result(s)
-----------------------------------------------------------------
- Clicking on the Check Point ID #241486 must expand the section because the text is hyperlinked
- Or If it is not hyperlinked must remove it

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![7](https://user-images.githubusercontent.com/4592712/29669427-04f18264-8901-11e7-991e-0d729b4efa2c.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points

**Comment by birdofpreyru** [comment]
I believe, it might be fixed as a part of #170 fix, thus not opening it for Bug Bash so far.
