### ISSUE TITLE
Unable to search members from Search option

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#1837]
Unable to search a member using username or skill from search option of topcoder.com community section.

1.  Go to www.topcoder.com
2.  Select Community.
3.  Click on Search icon to bring up search page.
4.  Enter username to search for.  In this case 'sharma.neha'.
5.  Get error page.
![image 2](https://user-images.githubusercontent.com/37835397/50245365-44a5cc80-03f8-11e9-8447-ee9615f9e2ad.png)

@ajefts

**Comment by ThomasKranitsas** [comment]
This seems to be a backend issue.

`GET https://api.topcoder.com/v3/members/_search/?query=MEMBER_SEARCH&handle=thomas&offset=0&limit=10` returns:
```
{
  "id": "-33f4e1fc:167c72c5189:4043",
  "result": {
    "success": true,
    "status": 500,
    "metadata": null,
    "content": "{\"root_cause\":[{\"type\":\"query_parsing_exception\",\"reason\":\"[nested] failed to find nested object under path [skills]\",\"index\":\"members-2018-12\",\"line\":40,\"col\":16}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"members-2018-12\",\"node\":\"V24O3O7pTDWKEAK-7RMe8Q\",\"reason\":{\"type\":\"query_parsing_exception\",\"reason\":\"[nested] failed to find nested object under path [skills]\",\"index\":\"members-2018-12\",\"line\":40,\"col\":16}}]}"
  },
  "version": "v3"
}
```
cc @sushilshinde

**Comment by sushilshinde** [comment]
May be @urwithat

**Comment by sushilshinde** [comment]
We are killing this feature in near future.

**Comment by Oanh-and-only-Oanh** [comment]
Challenge link https://www.topcoder.com/challenges/30104420

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh we are still fixing backend for this, we will do front-end once we have backend in good shape for use by front-end. Hence, moving this back to `TO DO`

**Comment by urwithat** [comment]
The Member micro service layer has been fixed and deployed on dev, kindly test. No need to make any front end modifications.

**Comment by lakshmiathreya** [comment]
Search is working for some users and not for others. Pls see screenshots. The nandle "neha.sharma" is present yet Search fails.
<img width="1598" alt="Screenshot 2019-11-27 at 7 28 34 AM" src="https://user-images.githubusercontent.com/51733042/69687502-29a00a00-10e9-11ea-93f4-f12ff1b3de2e.png">
<img width="1640" alt="Screenshot 2019-11-27 at 7 29 16 AM" src="https://user-images.githubusercontent.com/51733042/69687507-2f95eb00-10e9-11ea-9365-021d7e9a8893.png">
<img width="1614" alt="Screenshot 2019-11-27 at 7 41 03 AM" src="https://user-images.githubusercontent.com/51733042/69687543-4dfbe680-10e9-11ea-91b0-f84c5c46c378.png">

**Comment by urwithat** [comment]
For member who don't have much details in profile, will not be displayed.

**Comment by urwithat** [comment]
Gave a thought about it, thinks it's very valid. We have fixed this in dev. https://www.topcoder-dev.com/search/members/?q=neha.sharma

**Comment by lakshmiathreya** [comment]
Verified Member info now available for Members without details. 
<img width="1467" alt="Screenshot 2019-11-27 at 2 27 12 PM" src="https://user-images.githubusercontent.com/51733042/69708666-0776ae00-1122-11ea-8ca3-77c228be675a.png">

**Comment by ajefts** [comment]
Hi all.  Nice job getting the basic search available again on the site.  Can we close this ticket out now @urwithat ?  Is there anything else we're working on related to it?  Thanks.

**Comment by codeMinter** [comment]
@ajefts @urwithat looks like memberSince data is wrong on PROD - can you help check if this is DB issue or data is not sync to ES right? all are coming with member since 1969 on PROD
