### ISSUE TITLE
Logout should go back to zurich.topcoder.com

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1838]
When a user uses the logout feature in the top nav from zurich.topcoder.com, it should return the user to zurich.topcoder.com and not www.topcoder.com

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1571668

**Comment by ajefts** [comment]
@kkartunov Are you able to look at this one?

**Comment by kkartunov** [comment]
@ajefts I am afraid this is not possible. There is no redirect support for topcoder.com/logout
I looked when Mo raised the question...

**Comment by ajefts** [comment]
@kkartunov Can you try it like this?

http://accounts.topcoder.com/logout?retUrl=https%3A%2F%2Fzurich.topcoder.com
