### ISSUE TITLE
[$10] - No need of vertical parting line for last element as per design guideline

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#184]
Steps to Reproduce
1. Login to open for http://community-app.topcoder.com/challenges/30058719/?type=design
2. Click to 'View All Deadline'
3. Observe the last vertical line given after 'Winner' time details.

Screenshots : 
![image](https://user-images.githubusercontent.com/20595047/29669412-01670c7c-8901-11e7-8cf9-a9746c5cef14.png)

Expected Result:
No need of vertical parting line at last as per design spec.It may give a feeling of continuation of list.

Current Result:Vertical parting line at last is present.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by iversonLv** [comment]
can not assign myself like git lab ?

**Comment by iversonLv** [comment]
I can't not git push, says permission to topcoder-platform/community-app.git denied to iversonLv
....
Could you give me permission? Need assign myself in the future and git push permission.

Thanks.

**Comment by iversonLv** [comment]
![image](https://user-images.githubusercontent.com/4952611/29697288-c6a41b4a-8980-11e7-9fea-9eba8bc760f5.png)
