### ISSUE TITLE
Winners not reflecting for Topgear challenges

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#1843]
For the below challenge, winners are announced in DIRECT and the challenge is finished, but winners are not visible on the contest page.
Please check and resolve.

Challenge id: https://topgear.topcoder.com/challenges/30073963 

![image](https://user-images.githubusercontent.com/34749364/50298304-d539e680-04a4-11e9-9cfa-50cdd4f51af3.png)

**Comment by ThomasKranitsas** [comment]
This is a backend issue. The API does not return the `winners` array.

cc @sushilshinde @cwdcwd

**Comment by sushilshinde** [comment]
Created issue on api repo

**Comment by sushilshinde** [comment]
fixed
