### ISSUE TITLE
Click on Submit button to submit another solution display "You are not authorized to access this page." 

### ISSUE THREAD

**Issue by tmalbonph** [topcoder-platform/community-app#1846]
**Describe the bug**
I already registered and submitted into a challenge. Upon submission of another solution the page display "You are not authorized to access this page." after I click on the Submit button.

I noticed also, the tab display number of registered member like REGISTRANTS(18), but is just listed 3 registrant and my handle is not one of them.

It only happen to this challenge here: https://www.topcoder.com/challenges/30077594
But on the other challenge, I am able to click the Submit button without any problem like this one: https://www.topcoder.com/challenges/30077498

This issue happen both on Firefox and Chrome.
![300777594_not_authorized_error](https://user-images.githubusercontent.com/3745678/50381623-62a85100-06c6-11e9-9085-41539ad982bb.png)
![error-in-registrants-tab-and-submit-btn](https://user-images.githubusercontent.com/3745678/50381624-6d62e600-06c6-11e9-9436-6094f8010316.png)

**Comment by tmalbonph** [comment]
> @sushilshinde @cwdcwd This one needs quick attention. @ThomasKranitsas, @birdofpreyru or @kkartunov Are you able to help with this one at all?

As reported before, I can submit to https://www.topcoder.com/challenges/30077498
Now (Tue Dec 25 04:29:42 PST 2018) I can't. please check the attached screenshot
![30077498_not_authorized_error](https://user-images.githubusercontent.com/3745678/50406297-bd909400-07fd-11e9-8ae1-8b173613066e.png)

**Comment by sushilshinde** [comment]
@tmalbonph seems like you were able to submit, is this problem still relevant?

**Comment by tmalbonph** [comment]
> @tmalbonph seems like you were able to submit, is this problem still relevant?

It is working now. Thanks
