### ISSUE TITLE
No records (names) are shown on the registrants tab of challenges 

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1847]
**Describe the bug**
On challenge pages the number of rows on the registrants tab does not reflect to the number given on the tab. It is either zero or less then it should be.

**To Reproduce**
1. Go to 'https://www.topcoder.com/challenges/30077698?tab=registrants' and 'https://www.topcoder.com/challenges/30077297?tab=registrants'
2. Click on the 'Registrants' tab
3. See error

**Expected behavior**
The specified number of members should be shown in the list.

**Screenshots**

<img width="1440" alt="screenshot 2018-12-23 at 21 20 54" src="https://user-images.githubusercontent.com/35376779/50387296-e67b3100-06f8-11e9-8eaa-f9f3eec0556c.png">

<img width="1440" alt="screenshot 2018-12-23 at 21 22 04" src="https://user-images.githubusercontent.com/35376779/50387297-e67b3100-06f8-11e9-9d68-41ded3ece6b5.png">

**Desktop:**
 - OS: MacOS Mojave Version 10.14.2
 - Browser: Chrome
 - Version: 71.0.3578.98

**Additional context**
For a member it is important to see the competition in a challenge.

**Comment by ThomasKranitsas** [comment]
This is a backend issue.
The API returns the `numberOfRegistrants` but doesn't return the `registrants` array.

The only thing we can do on the frontend is to show a proper error message to indicate that there was an error loading the challenge registrants.

cc @ajefts @cwdcwd

**Comment by ThomasKranitsas** [comment]
This also happens in https://www.topcoder.com/challenges/30077766

**Comment by tmalbonph** [comment]
Similar to issue mention here https://github.com/topcoder-platform/community-app/issues/1846

**Comment by sushilshinde** [comment]
Seems like it is resolved

![vulcan - nerve center app refinement design challenge 2019-01-07 15-34-04](https://user-images.githubusercontent.com/683231/50761975-b6ec2d00-1291-11e9-9068-4c8e41fc3a53.png)
