### ISSUE TITLE
[$20] - [Bug Hunt - NEW BUG]No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#185]
Seach some items and see the console
<img width="1652" alt="2017-08-24 9 43 18" src="https://user-images.githubusercontent.com/3046795/29669208-45c43188-8915-11e7-985c-dbe23e166a23.png">

**Comment by birdofpreyru** [comment]
In principle, this are from some 3-rd party scripts, not related to Community App. I'll rely on @ajefts judgement on what are these, and whether we should do something about these.

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
If somebody has an idea how to avoid this problem with 3-rd party plugin - feel free to pick-up the ticket and attempt to fix.

**Comment by birdofpreyru** [comment]
The error does not show up in the console anymore. Thus, closing the issue.
