### ISSUE TITLE
Create Dropdown Bar Feature

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1856]
Currently on our track "How To" pages we have dropdowns with information like our FAQ section.

<img width="1335" alt="screen shot 2019-01-04 at 1 43 41 pm" src="https://user-images.githubusercontent.com/1373998/50712627-0975e100-1027-11e9-845d-df8cf4a3ee7d.png">
<img width="1334" alt="screen shot 2019-01-04 at 1 43 49 pm" src="https://user-images.githubusercontent.com/1373998/50712628-0975e100-1027-11e9-92c1-26fb775ee7e4.png">

The ask is pretty simple.  We just would like that but the ability to put it on other created pages.

**Comment by kkartunov** [comment]
https://community-app.topcoder-dev.com/examples/contentful/viewport/1ekIMzLLz2CrkRxPgA4FZ1

**Comment by hokienick** [comment]
Before we close this issue, can we make the default have no background instead of the grey?

**Comment by kkartunov** [comment]
@hokienick there is no default gray applied by the dropdown. In the example, it comes from the viewport as extra style property. I think we can safely close this one.

**Comment by hokienick** [comment]
There we go!
