### ISSUE TITLE
Contentful - Preview does not match look of Published page

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1857]
Currently the published page looks like a zoomed in version of preview according to these pages as examples:

Preview: https://community-app.topcoder.com/examples/contentful/viewport/4UqUCeKnKEQEiim4we68gI

Published: https://www.topcoder.com/lp/test-for-success

<img width="1473" alt="screen shot 2019-01-04 at 1 50 06 pm" src="https://user-images.githubusercontent.com/1373998/50712814-bd776c00-1027-11e9-9720-b333bf1d2f07.png">
<img width="1474" alt="screen shot 2019-01-04 at 1 50 23 pm" src="https://user-images.githubusercontent.com/1373998/50712815-be100280-1027-11e9-8507-4a33a4c93019.png">

This is important as we are trying to be more cognizant of what we include above the fold.

**Comment by kkartunov** [comment]
@hokienick I think this is related to browser zoom applied to your view. Please, check if you have the zoom icon in address bar(Chrome) or check your browser settings. Zooms can be applied on domain base...hence you have different settings currently. Please, check.

**Comment by hokienick** [comment]
Wow, I had no idea my browser was doing that!  Thank you.
