### ISSUE TITLE
Unable to Unregister from Design Challenge

### ISSUE THREAD

**Issue by philipstb** [topcoder-platform/community-app#1859]
Hi everyone,

I just noticed that it seems the unregister feature in the UX/UI design challenge is not work properly, the issue is once a user registered on a challenge he will not be able to unregister, when I force many times to unreg the handlename will missing from the registrants tab and can't access the submission form as well but the button still stay red with "unregister" caption. As usual this feature is work.

Thank You

**Comment by sushilshinde** [comment]
@philipstb can you help with steps to reproduce this problem

**Comment by philipstb** [comment]
@sushilshinde Yes sure. 
1. I registered on a design challenge
2. I clicked the unregister button from the challenge. The reason could be accidentally clicking the register button twice or more.
3. I checked in the participants tab, my handlename is not there, but the button stay indicated if I was registered. I coudn't access the submission form.
4. The conclusion of this bug is a user unable to unregister correctly, you might be to try it if you have chance. Try to register a challenge and then ureg

Thank you

**Comment by sushilshinde** [comment]
@philipstb looking into it

**Comment by skyhit** [comment]
@sushilshinde @philipstb I tested with this design F2F, and both are working - https://community-app.topcoder.com/challenges/30078867

is there any special for your tested design challenge?

**Comment by sushilshinde** [comment]
@skyhit there is a problem with forum creation

When I try to register for a `design` challenge

![Insurance Renewals Monitoring Dashboard Design Concepts Challenge 2019-05-06 16-24-52](https://user-images.githubusercontent.com/683231/57221220-f5b1aa00-701b-11e9-93bb-8de2993862d6.png)

when I reload I don't see the orange button and if I try to register again, I get this

![Insurance Renewals Monitoring Dashboard Design Concepts Challenge 2019-05-06 16-26-08](https://user-images.githubusercontent.com/683231/57221228-fba78b00-701b-11e9-8218-d059308ec39b.png)


Non of this is happening for `develop` type

**Comment by sushilshinde** [comment]
Resolved
