### ISSUE TITLE
Non price winning items are also marked in green arrow icon in REGISTRANTS tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#186]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058662/?type=design

- Click REGISTRANTS tab

- Check the winning items

Actual Result(s)
-----------------------------------------------------------------
- Non price winning items are also marked in green arrow icon in REGISTRANTS tab

Expected Result(s)
-----------------------------------------------------------------
- Non winning items must not marked in green color icon

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![8](https://user-images.githubusercontent.com/4592712/29669574-8f1e8ce8-8901-11e7-8621-65a3ba096562.jpg)

**Comment by birdofpreyru** [comment]
I believe, it is not a bug: checkmarks show that submission has passed the checkpoint, and it is not directly related with winning money in the end. Though, I'll rely on the final say of @vic-topcoder about what is the meaning of checkmarks here.

**Comment by vic-topcoder** [comment]
It is showing checkpoint win in the Round 1 column - we have X number checkpoint prize money in design challenges (usually five). Final win can only be one that passed checkpoint, but not necessarily the winning checkpoint. Not a bug
