### ISSUE TITLE
"Round Information" displayed in wrong place!

### ISSUE THREAD

**Issue by systic** [topcoder-platform/community-app#1860]
In design challenges (all challenges that are running as 2 rounds) - I see "Round information" is displaying in the wrong place. It should be originally be seen as a separate section at the top in the challenge page but we are seeing it in the bottom along with the final fixes information (please see attached screenshot).

https://www.topcoder.com/challenges/30078212
https://www.topcoder.com/challenges/30076738
<img width="1265" alt="screenshot 2019-01-07 at 6 10 32 pm" src="https://user-images.githubusercontent.com/15885764/50773407-cfbb0980-12b6-11e9-8512-b1d58158620e.png">

One more issue is that text styling is not working (color, bold, etc)

**Comment by ThomasKranitsas** [comment]
@sushilshinde fyi ☝️

**Comment by sushilshinde** [comment]
Forwarded to @skyhit

**Comment by sushilshinde** [comment]
@systic can you verify the change?

**Comment by sushilshinde** [comment]
Deployed on production
