### ISSUE TITLE
[$40] - [Bug Hunt - NEW BUG]n.subtracks.join is not a function Challenge-list.js:11

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#187]
1) Try to open page: 
http://community-app.topcoder.com/challenges?filter[tags][0]=Java&filter[subtracks][0]=Architecture&filter[subtracks][1]=Banners/Icons&filter[subtracks][2]=Conceptualization&filter[subtracks][3]=Design&filter[subtracks][4]=First2Finish&filter[subtracks][5]=Logo%20Design&filter[subtracks][6]=RIA%20Build%20Competition&filter[subtracks][7]=Test%20Suites&filter[subtracks][8]=Wireframes&filter[subtracks][9]=Widget%20or%20Mobile%20Screen%20Design&filter[subtracks][10]=Test%20Scenarios&filter[subtracks][11]=Studio%20Other&filter[subtracks][12]=Print/Presentation&filter[subtracks][13]=Marathon%20Match&filter[subtracks][14]=Front-End%20Flash&filter[subtracks][15]=Development&filter[subtracks][16]=Design%20First2Finish&filter[subtracks][17]=Copilot%20Posting&filter[subtracks][18]=Bug%20Hunt&filter[subtracks][19]=Code&filter[subtracks][20]=Application%20Front-End%20Design&filter[subtracks][21]=Assembly%20Competition&filter[subtracks][22]=Content%20Creation&filter[subtracks][23]=Idea%20Generation&filter[subtracks][24]=Web%20Design&filter[subtracks][25]=Specification&filter[subtracks][26]=UI%20Prototype%20Competition&filter[tracks][design]=true&filter[tracks][develop]=true&filter[startDate]=2017-08-01T04:00:00.000Z&filter[endDate]=2017-08-05T04:00:00.000Z

2) Page can't show items and there is console error:
<img width="1657" alt="2017-08-24 9 49 43" src="https://user-images.githubusercontent.com/3046795/29669618-a493187c-8916-11e7-96a4-d4b901d09a3f.png">

**Comment by birdofpreyru** [comment]
Accepted, 5 points.
I am not sure, whether this is a valid URL or not, from point of view of proper filters logic, but we surely should not allow a user to break the app by supplying incorrect query params in URL. So, it is necessary to check, what is the issue, and fix it properly.

**Comment by birdofpreyru** [comment]
Pay attention to #195 - should be also fixed as a part of this

**Comment by elfman** [comment]
assign to myself
