### ISSUE TITLE
Profile Image changes are not reflecting change on forum/forum posts. 

### ISSUE THREAD

**Issue by codeMinter** [topcoder-platform/community-app#1872]
**Describe the bug**
Profile Image should be consistent and changes should be carried forward all over topcoder. If I update my profile picture on Profile Page, I still see old profile picture on Forums. If not wrong I had changed it almost more than a month back. 

**To Reproduce**
1. Login to Topcoder.com, go to settings, change profile picture. 
2. Go to any challenge forum, I still see old image (this is not updated after months too). 

**Expected behavior**
Profile Picture should be consistent, once updated it should be used everywhere immediately. 

**Screenshots**
Profile Page:

![profile_image](https://user-images.githubusercontent.com/14284629/51111027-90456d80-1820-11e9-9983-5691a3cd0429.jpg)

Forums Page and Forum Posts (yes same images is shown when I post queries on forums):
![forum_has_old_image](https://user-images.githubusercontent.com/14284629/51111091-c7b41a00-1820-11e9-9789-bbb2fb5b0527.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14 
 - Browser SAFARI
 - Version 12.0 (14606.1.36.1.9)

**Comment by ThomasKranitsas** [comment]
We have created a processor that listens for profile update events and updates the data in the legacy db (informix).

Once this processor is set up and running, this will be fixed.

cc @urwithat

**Comment by nithyaasworld** [comment]
This is still an issue.

This issue is duplicated here: https://github.com/topcoder-platform/community-app/issues/3414 and here: https://github.com/topcoder-platform/community-app/issues/3432
