### ISSUE TITLE
Make challenges banner contentful for kubik

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1875]
Update the challenges page for the kubit site so we can manage the banner area via contentful.  We have a few other sites that already do this.

**Comment by kkartunov** [comment]
https://community-app.topcoder-dev.com/__community__/zurich/challenges?communityId=zurich

**Comment by kkartunov** [comment]
Contentful: https://app.contentful.com/spaces/f4rv5dt395nf/entries/5ghmniPmVqe0KKYQs8gEg0

**Comment by ajefts** [comment]
Edit content at https://app.contentful.com/spaces/f4rv5dt395nf/entries/5ghmniPmVqe0KKYQs8gEg0
