### ISSUE TITLE
Green arrow icon displayed in front of the winning items are not aligned properly in REGISTRANTS tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#188]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058662/?type=design

- Click REGISTRANTS tab

- Check the green arrow icon

Actual Result(s)
-----------------------------------------------------------------
- Green arrow icon displayed infront of the winning items are not aligned properly in REGISTRANTS tab

Expected Result(s)
-----------------------------------------------------------------
- Icon must align with the text

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![8](https://user-images.githubusercontent.com/4592712/29669871-7baf619a-8902-11e7-82b4-8e4ef1c4a80f.jpg)

**Comment by birdofpreyru** [comment]
Well, this one was already noted before the bug hunt, sorry (#169)
