### ISSUE TITLE
Text is not formatted when displayed in Challenge Detail page.

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/community-app#1883]
**Describe the bug**
Text is not formatted when displayed in Challenge Detail page.

**To Reproduce**
1. Go to 'https://www.topcoder.com/direct/contest/detail.action?projectId=30079467'
2. Scroll down
3. check the important note heading.

**Expected behavior**
Text color preview should be same on direct page as well as challenge page.

**Screenshots**

Text color on the direct page:
![image](https://user-images.githubusercontent.com/44159743/51371392-0cd99400-1b20-11e9-9da8-b383cf4025c6.png)

Text color on the challenge page:
![image](https://user-images.githubusercontent.com/44159743/51371458-372b5180-1b20-11e9-8ef1-4ab3acdbdbf1.png)

**Comment by RiteshTC** [comment]
cc @adroc-tc,  @billsedison

**Comment by nithyaasworld** [comment]
@ajaysaini9782 Recently the changes done on Direct, are properly reflecting in the Challenge Details page with the expected Font. 

Please re-open if you find the issue happening again. Thanks.
