### ISSUE TITLE
[$10] - 'BUG HUNT' challenge tag has blank info on hovering a mouse over it.

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#189]
Steps to Reproduce
1. Login to open http://community-app.topcoder.com/challenges?
2. Hover a mouse over a 'BH' tag for any bug hunt challenge.

Screenshots : 
![image](https://user-images.githubusercontent.com/20595047/29669820-4dbe15ec-8902-11e7-8b05-e8042f4041ac.png)

Expected Result: The black comment window on mouse hovering should show details likewise in other challenge types.

Current Result: No info on hovering a mouse pointer over BH tag.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by shubhendusaurabh** [comment]
Assigning myself

**Comment by shubhendusaurabh** [comment]
PR #268
