### ISSUE TITLE
Change API Call for Email Newsletter Signups

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1917]
This update is a follow up to closed issue #1271 

Originally the plan was that at a click of a button, the Topcoder member would register for a newsletter by being assigned to a group within a list in our Mailchimp instance.

This has been working out fine, but we have discovered that it has limitations.  Instead of assigning these members to groups, we are instead going to assign that member a "tag".

[Here is some documentation](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/#%20) on how that can be accomplished.

Here is an example of how we currently call this function in Contentful:

`<NewsletterSignupForMembers listId="28bfd3c062" interests="0281f15d3f" label="Register for Updates"/>`

I'm sure this will need to be changed as well.  Please let me know as soon as this functionality has been implemented as I will need to update all the pages that currently utilize this button.

If you have any questions on how it is currently implemented, you may contact @birdofpreyru as he had completed the original task.

**Comment by kkartunov** [comment]
@hokienick 
Example use: https://app.contentful.com/spaces/b5f1djy59z3a/entries/1wdOJLysXa8G6IqSAseEeQ

**Comment by hokienick** [comment]
Here is an example of how to use this 
```<NewsletterSignupForMembers listId="28bfd3c062" tags="Dev Newsletter" label="Subscribe to the Development Newsletter"/>```
