### ISSUE TITLE
[Bug Hunt - NEW BUG]504 Gateway Time-out

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#192]
1) Try to open URL: http://community-app.topcoder.com/challenges/10000090909090909090909090909
2) Long time no response
<img width="1066" alt="2017-08-24 10 02 41" src="https://user-images.githubusercontent.com/3046795/29670032-fb440914-8917-11e7-86f8-29e7464b5a96.png">

**Comment by birdofpreyru** [comment]
I'll accept it with 1 point, though it is kind of dublicate of #190

**Comment by elfman** [comment]
This bug is different with #190. It's cause by the server, server does not return anything response when challengeId is wrong, which make the link time out.
Except: Server returns 'null' or other error msg when challenge id is not exist. At least, don't make the link time out.
