### ISSUE TITLE
Subscription to Newsletter Button Does not Work 

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#1927]
**Describe the bug**
Clicking on Subscribe to Newsletter generates an error.

**To Reproduce**
1. Go to https://www.topcoder.com/community/competitive-programming
2. Click on "Subscribe to the Competitive Programming Newsletter"
3. See error "The resource submitted could not be validated. For field-specific details, see the 'errors' array."

1. Reproducible on https://www.topcoder.com/lp/digitalannealer
"Register for updates"

**Expected behavior**
User should be able subscribe to the newsletter

**Screenshots**
<img width="1187" alt="errorscreenshot" src="https://user-images.githubusercontent.com/5771673/52193413-13347380-2875-11e9-909b-5c4925387708.png">
<img width="883" alt="mailchimperror" src="https://user-images.githubusercontent.com/5771673/52193415-16c7fa80-2875-11e9-998a-2223718dd85d.png">

**Desktop (please complete the following information):**
N/A

**Additional context**
Possibly related to issue
https://github.com/topcoder-platform/community-app/issues/1917

**Comment by nithyaasworld** [comment]
I am able to successfully signup for the newsletter/updates using the above 2 links. 

@RiteshTC Please re-open if you find this is to be not resolved. Thanks.
