### ISSUE TITLE
Email change functionality is broken

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1928]
**Describe the bug**
The API returns an `Unable to process JSON` error when the user tries to change the email address from the Settings page

**To Reproduce**
1. Go to https://www.topcoder.com/settings/account
2. Click on `Change email`
3. Enter the new email and click `Send verification email`

**Expected behavior**
Only the required properties for changing the email should be passed in the request body to prevent such errors from unused properties.

**Comment by ajefts** [comment]
@ThomasKranitsas where did you move it?

**Comment by ajefts** [comment]
ok, thanks
