### ISSUE TITLE
[$40] - 'Next Deadline: Submission' must change to 'Next Deadline: Checkpoint Submission' in Design Challenges

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#193]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058900/?type=design

- Register for the Challenge

- Click 'View All Deadlines'

- Check the 'Next Deadline'

Actual Result(s)
-----------------------------------------------------------------
- Next Deadline: Submission is displayed for Checkpoint Submission

Expected Result(s)
-----------------------------------------------------------------
- 'Next Deadline: Submission' must change to 'Next Deadline: Checkpoint Submission' in Design Challenges

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![10](https://user-images.githubusercontent.com/4592712/29670141-68488b94-8903-11e7-9bac-27ead7aa8e94.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
The logic behind text in the `Next Deadline` section should be double-checked and fixed for design challenges.

**Comment by birdofpreyru** [comment]
Pay attention to #214 as well

**Comment by yillapens** [comment]
Assign

**Comment by yillapens** [comment]
@birdofpreyru 

Sorry, I am confused about the meaning of next deadline. If the contest is opening for registration, checkpoint submission and submission, which one will be the right next deadline?  

If the match still can register, is the registration deadline  current deadline?

**Comment by birdofpreyru** [comment]
@yillapens I imagine it the following way:
1. If user is not registered to a challenge, and registration is still open, then next deadline for him is the registration;
2. If user is registered, and challenge is going on, then the next deadline is either checkpoint or final submission;
3. If challenge is finished, we just write there that the challenge is finished (which I believe, already done in another ticket).
Does it make sence?

**Comment by yillapens** [comment]
@birdofpreyru That's clear. Thanks a lot.  :)
