### ISSUE TITLE
[$30] - Search overlap with the filter section

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#194]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Hover over the search icon

Actual Result(s)
-----------------------------------------------------------------
- Search overlap with the filter section and opens below the filter controllers

Expected Result(s)
-----------------------------------------------------------------
- Search overlay must open in front of the filter section

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![11](https://user-images.githubusercontent.com/4592712/29670249-b7131140-8903-11e7-96f1-6027e0b3722c.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
The search component should expand on the top level, over any other element of the page.

**Comment by iversonLv** [comment]
I have finish issue #184 but I can't not git push.
Can I keep on this ticket?
Thanks.

**Comment by iversonLv** [comment]
I have finish this ticket, please assign and give me permission to git push.

thanks.

**Comment by iversonLv** [comment]
![image](https://user-images.githubusercontent.com/4952611/29697247-a094fc3a-8980-11e7-8f0d-2ef2629be409.png)
