### ISSUE TITLE
[Bug Hunt - NEW BUG]TypeError: n.tags.join is not a function

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#195]
1) Try to open http://community-app.topcoder.com/challenges?filter[tags][-1]=HelloWorldXXXXXXX
2) see error in console and web page will not show contest items
![2017-08-24 10 07 26](https://user-images.githubusercontent.com/3046795/29670227-a46d0248-8918-11e7-8873-ace39b16a54d.png)

**Comment by birdofpreyru** [comment]
Looks like kind of dublicate of #187, but as it is a bit different, I'll accept with 1 point
