### ISSUE TITLE
Regionals Leaderboard

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1951]
We have the TCO19 Leaderboards but those come with the expectation that we have "Rank, Handle, # of challenges, Points, and Total Score".

In our Slack channel with Harshit he asks that we have the columns for "Handle, # of Challenges, TCO Points, and Final Score".  Let me know what you would need to test this.

Thanks!

**Comment by kkartunov** [comment]
@hokienick this is now clear, right?
