### ISSUE TITLE
My Projects menu on community portal

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1963]
Add a "My Projects" link in the top nav as described in the attached screenshot.  

- Only show "My Projects" if the user is logged in.
- It should link to https://connect.topcoder.com

![image](https://user-images.githubusercontent.com/3812270/52576095-767e5280-2ded-11e9-8137-3952aadf6398.png)

**Comment by ajefts** [comment]
@kkartunov Is this one you can do?

**Comment by ajefts** [comment]
Failed to create challenge
Response body:
```
{
    "message": "Unauthorized",
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by ajefts** [comment]
Failed to create challenge
Response body:
```
{
    "message": "Unauthorized",
    "challengeURL": "https://www.topcoder.com/challenge-details/undefined/?type=develop&noncache=true"
}
```

**Comment by kkartunov** [comment]
@ajefts how is ^^^ related to this issue? Where do we fail to create a challenge?

**Comment by nithyaasworld** [comment]
Issue resolved.
