### ISSUE TITLE
Page won't load in IE11 sometimes

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#197]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

Actual Result(s)
-----------------------------------------------------------------
- Page won't load in IE11 sometimes

Expected Result(s)
-----------------------------------------------------------------
- Must load the challenge page in IE11

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![12](https://user-images.githubusercontent.com/4592712/29670661-f6a2b62a-8904-11e7-970a-88c91bd0e537.jpg)

**Comment by birdofpreyru** [comment]
Should try it myself on IE11 and think a bit about the possible reason.

**Comment by sdgun** [comment]
@birdofpreyru I can still reproduce this issue, Won't load the site in IE11

**Comment by birdofpreyru** [comment]
@sdgun Ok, accepted, 5 points.

**Comment by birdofpreyru** [comment]
For information of those who pick this up:

What happens there, I believe: now we use code-splitting in our app. On `/challenges` route, the header/foorter, and the actual content of the page are in different code chunks. So, it stucks when the code chunk for the challenge listing is being loaded. It looks to me, that there is some IE-specific bug with it.

**Comment by birdofpreyru** [comment]
In the last few months we have added to the code various polyfills, that, hopefully, solve IE-specific issues of our code. If anybody still have problems let's open new tickets for them.
