### ISSUE TITLE
[$30] - [Bug Hunt - NEW BUG]Filter list hide page footer

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#198]
1) When user create many filters, the filer list will be too long to display

<img width="969" alt="2017-08-24 10 11 35" src="https://user-images.githubusercontent.com/3046795/29670683-fe6e9b02-8919-11e7-81d8-91a40de7ab56.png">

**Comment by birdofpreyru** [comment]
Accepted, 3 point.
Yeah, ideally, the height of the main part of the page, should be always expanded large enough to fit the filters.

**Comment by birdofpreyru** [comment]
Pay attention to #209 as well

**Comment by shubhendusaurabh** [comment]
assigning muself
