### ISSUE TITLE
Contest specification page is hanging while waiting for facebook

### ISSUE THREAD

**Issue by ajaysaini9782** [topcoder-platform/community-app#1983]
**Describe the bug**
Contest specification page is hanging while waiting for facebook.

**Screenshots**
![Uploading Specification issue.png…]()

**Comment by ajaysaini9782** [comment]
@alamora

**Comment by alamora** [comment]
Thanks - let me know if you need me to re-attach the image

**Comment by SathyaJayabal** [comment]
@ajaysaini9782 , is this still na issues. If so  can you please attach a screenshot/video ?
