### ISSUE TITLE
Ability to choose size of slider 

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1986]
Currently we are able to create a slider, but we are only able to create a large banner version.

We would like an option to have the same functionality, just at a smaller scale physically.  If we could have the choice to create a slider centered with the dimensions of 1100x500, that would be great!

Here is an example of what the slider should look like on a page:

<img width="1300" alt="screen shot 2019-02-22 at 12 34 58 pm" src="https://user-images.githubusercontent.com/1373998/53269653-4c0a8000-369e-11e9-8e42-706d3fac4729.png">

**Comment by kkartunov** [comment]
@hokienick check this one:
https://app.contentful.com/spaces/b5f1djy59z3a/entries/7iU0F379Q5vhw1cpUM1hMb

note how width is controlled by the slider but height is controlled by the slider item itself! We will be more flexible with such an approach as it allows different sizes for slider and slider items.

demo here:
http://community-app.topcoder-dev.com/examples/contentful/slider/7iU0F379Q5vhw1cpUM1hMb

**Comment by kkartunov** [comment]
@hokienick this is now in prod. See: https://community-app.topcoder.com/examples/contentful/slider/7iU0F379Q5vhw1cpUM1hMb
