### ISSUE TITLE
Ability to Create An Item Slider

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1987]
Our track homepages used to contain [a slider to display the different competition types for a track](https://app.contentful.com/spaces/b5f1djy59z3a/entries/3JV1ynpUY0oS0UUwiwW0uu). We need a similar functionality that we can use on any community page.

**Requirements:**
- Ability to enter 2 or more _items_ (unlimited, but if needed Max:20)
- Each _item_ will contain the options to choose an image (option to make the image a clickable link) and/or enter text into a WYSIWYG
- An _item_ may contain just text, just an image, or image and text, but requires at least one of those listed.
- Items should be equally spaced apart

**Example of Image and Text:**
<img width="1299" alt="screen shot 2019-02-22 at 12 39 28 pm" src="https://user-images.githubusercontent.com/1373998/53271981-e077e100-36a4-11e9-8260-12764c36a7b6.png">

**Example of Image Only**
<img width="1252" alt="screen shot 2019-02-22 at 1 24 33 pm" src="https://user-images.githubusercontent.com/1373998/53272136-46646880-36a5-11e9-8b0f-c0a743591b17.png">

**Comment by kkartunov** [comment]
Tests:
https://app.contentful.com/spaces/b5f1djy59z3a/entries/7GVSVjV0EtQpOftve8u6AM
and
https://community-app.topcoder.com/examples/contentful/slider/7GVSVjV0EtQpOftve8u6AM
