### ISSUE TITLE
Ability To Change Button Color

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1988]
Checked with Thomas and he says it is not possible to change the colors of a button.  We will need this for our past TCO pages that we are recreating in Contentful.

I used [this doc](https://github.com/topcoder-platform/topcoder-react-utils/blob/master/docs/button.md) to see if it was possible, but alas it is not!

**Comment by kkartunov** [comment]
@hokienick for this one we will need to patch our react-utils library...
https://github.com/topcoder-platform/topcoder-react-utils/blob/master/src/shared/components/Button/index.jsx

**Comment by hokienick** [comment]
@kkartunov That would be perfectly fine for our needs.  In order to keep in line with the other parameters however like 

`<Button to="">` or `<Button opennewtab="true">`

Should we do something like
`Button color="red">` or something like that?

Also, the ability to put in a hex value should be possible as well

**Comment by ajefts** [comment]
@hokienick Do none of the existing button styles/themes work for this?  I mean, do we have to match the old style exactly?  We should aim for consistency...

**Comment by hokienick** [comment]
@ajefts I agree with the consistency, but this is specifically in reference to the old tco pages (think tco03).  Jessie is trying to keep the same look and feel that they had back in the day.  If this is too complicated then I will let her and the design team know.

**Comment by kkartunov** [comment]
https://app.contentful.com/spaces/b5f1djy59z3a/entries/FNmL56lEahdv0irLASC5a

**Comment by hokienick** [comment]
Seems to be completed based on DaraKs specification.
