### ISSUE TITLE
Challenge description is shown with bold font when using paragraphs

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/community-app#1998]
**Describe the bug**
If we use tag `<p>` inside challenge description it is shown as bold.

**To Reproduce**
1. Create some text in Google Docs and copy it to the challenge description in Direct. If you check the source code of such text it doesn't have any styles for bold. It only uses paragraphs - tag `<p>`.
2. Open the challenge in the community app.
3. You would see that all the text becomes bold.

**Expected behavior**
Tag `<p>` inside challenge description should not have bold style for text.

**Screenshots**
![topcoder connect - wizard - skip empty steps 2019-03-06 15-47-36](https://user-images.githubusercontent.com/146016/53864689-195e7100-4028-11e9-86ae-f8f42e9a6df1.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Google Chrome 
 - Version 72.0.3626.119 (Official Build) (64-bit)

**Additional context**
This issues appeared a few days ago. Before old challenges created in such a way were shown with normal font.
Old projects which before looked good, now also are shown as bold.

**Comment by sushilshinde** [comment]
Fixed
