### ISSUE TITLE
[$60] - Underscore displayed in the 'First 2_finish' and 'Ui Prototype_competition' tags

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#200]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058991/?type=develop

- Check the tag > First 2_finish

- Go to http://community-app.topcoder.com/challenges/30058932/?type=develop

- Check the tag > Ui Prototype_competition

Actual Result(s)
-----------------------------------------------------------------
- First 2_finish
- Ui Prototype_competition

Expected Result(s)
-----------------------------------------------------------------
- First 2 finish
- UI Prototype

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![13](https://user-images.githubusercontent.com/4592712/29670844-95c03b1a-8905-11e7-8e79-a3d2e99a1518.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
### Expected Fix
I believe, since the original implementation of the page, the backend has been updated to return consistent names of subtracks, it should be double-checked, and updated in the frontend accordingly.

**Comment by chqy24** [comment]
Assign to myself
and please grant me permission to change the label, thanks

**Comment by chqy24** [comment]
Ready to review, PR #247

**Comment by chqy24** [comment]
@birdofpreyru 
PR #247 has been updated
