### ISSUE TITLE
[Bug Hunt - NEW BUG]Filter page and Search page overlapped

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#201]
Steps:
1) Open URL: http://community-app.topcoder.com/challenges/?filter[tags][0]=HTML5
2) Open Filter
3) Move mouse to search option on upper right corner
<img width="1642" alt="2017-08-24 10 20 30" src="https://user-images.githubusercontent.com/3046795/29670916-bb8bf856-891a-11e7-81e9-95f95125d4af.png">

**Comment by birdofpreyru** [comment]
Dublicate of #194
