### ISSUE TITLE
Improve the experience on existing no access page for community

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#2018]
There isn't anything on the no access page that informs the user, especially if they are a valid member but happen to be logged in with a different account that doesn't have access.
![image (1)](https://user-images.githubusercontent.com/5585002/54182093-32907300-44a9-11e9-9de4-bf224472cf12.png)

Please, update the page to look as shown below:
![image__3_](https://user-images.githubusercontent.com/5585002/54182401-18a36000-44aa-11e9-8aa0-5ddc397c97d8.png)

The component to update is here: https://github.com/topcoder-platform/community-app/tree/develop/src/shared/components/tc-communities/AccessDenied

cc @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
@ThomasKranitsas can you either close this ticket if it's a duplicate or update it since it's being worked on?
