### ISSUE TITLE
[$40] - [Bug Hunt - NEW BUG]TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#202]
1) Open contest page: http://community-app.topcoder.com/challenges/
2) Open Filter
3) Click on "Start Date" of "Date range" 
4) Click other place but not the pop up date picker
5) The web console shows error:
challenge-listing.js:11 Uncaught TypeError: Cannot read property 'contains' of null
<img width="1256" alt="2017-08-24 10 27 13" src="https://user-images.githubusercontent.com/3046795/29671182-6c400cb4-891b-11e7-9502-c59a96f5ba30.png">

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
### Note
It looks to me, like this does not cause any visible problems for our app, and probably it is caused by an error in 3-rd party code, though, it would be great, if we can fix it to avoid any errors in such case.

**Comment by daft300punk** [comment]
I checked, the related code is only inside code built by webpack. Any ideas how to trace it back to which file it is coming from? Unassigning myself for time being.

**Comment by twicoder** [comment]
It's a bug of react-dates, and it seems that react-dates will fix this bug later.
Details: https://github.com/airbnb/react-dates/issues/437
