### ISSUE TITLE
[$40] - [Common] All the pages and tabs in the challenge details pages are not optimized for mobile view

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#203]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058880/?type=design

- Check the page layout

Actual Result(s)
-----------------------------------------------------------------
- All the pages and tabs in the challenge details pages are not optimized for mobile view

Expected Result(s)
-----------------------------------------------------------------
- All the pages and tabs in the challenge details pages must optimized for mobile view
- As per the provided design guide

Environment
-----------------------------------------------------------------
- **Device(s):** iPhone
- **Operating System:** iOS 10.3.3
- **Browser(s):** Safari

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
Expected:

![14 2](https://user-images.githubusercontent.com/4592712/29671456-396c9a50-8907-11e7-9b69-cffd9eb8e336.jpg)

**Comment by birdofpreyru** [comment]
@sdgun Can you be more specific? For me it looks, like they behave quite correct in mobile view, and are matching the design.

**Comment by sdgun** [comment]
@birdofpreyru Below are the actual screens. All  the elements in the contest detail page is scrambled
- Register, Submit, View buttons are too close to the right border
- Content is not readable and half of them re hidden
- etc ..

![img_3683](https://user-images.githubusercontent.com/4592712/29693024-e24c2372-8950-11e7-98a0-78d9c60cfe38.PNG)
![img_3680](https://user-images.githubusercontent.com/4592712/29693025-e24ec8b6-8950-11e7-8ece-d5ca84598ec7.PNG)
![img_3681](https://user-images.githubusercontent.com/4592712/29693026-e24eee5e-8950-11e7-8972-522bb9176f4c.PNG)
![img_3682](https://user-images.githubusercontent.com/4592712/29693027-e2562066-8950-11e7-8c2a-a6aaac041ebd.PNG)

**Comment by birdofpreyru** [comment]
@sdgun Are you testing it on a real device? When I check mobile view in mobile emulation mode of Chrome on Ubuntu, these screens are rendered properly.

**Comment by sdgun** [comment]
@birdofpreyru Yes I am testing on real devices (iPhone 5 and iPhone 6s)

Device(s): iPhone 5 (Portrait Mode)
Operating System: iOS 10.3.3
Browser(s): Safari

Please check video from here: https://www.screencast.com/t/dojkrvVgkV4


Device(s): iPhone 6s (Portrait Mode)
Operating System: iOS 10.3.3
Browser(s): Safari

Please check the below screenshots

![img_1369](https://user-images.githubusercontent.com/4592712/29713444-3033eb54-89bc-11e7-8812-e26c77e13985.jpg)
![img_1370](https://user-images.githubusercontent.com/4592712/29713445-3035a46c-89bc-11e7-8bd9-27d6b9f0afe7.jpg)
![img_1371](https://user-images.githubusercontent.com/4592712/29713446-303bfc86-89bc-11e7-9169-6dafc2471ba5.jpg)
![img_1372](https://user-images.githubusercontent.com/4592712/29713447-3040660e-89bc-11e7-8096-f02288984768.jpg)

**Comment by birdofpreyru** [comment]
@sdgun Ok, I accept with 5 points. Actually, mobile layouts are implemented in the app, I guess, the problem is that your apple-devices has so much resolution / pixels, that our media rules in css consider them to be desktop-kind of screens. So, we should add some code into app's setup to count for pixel's dencity in a better way.
