### ISSUE TITLE
'Challenge forum' option is absent for past challenges.

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#204]
Steps to Reproduce
1. Login to open http://community-app.topcoder.com/challenges/30058702/?type=design
2. Try to find 'Challenge Forum' option.
 
Screenshots : 

Expected Result: Challenge Forum access and option should be there as per design spec.

Current Result:Challenge forum option absent.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by Kvm87** [comment]
![image](https://user-images.githubusercontent.com/20595047/29671498-58790c94-8907-11e7-8da0-a199ece860fa.png)

**Comment by birdofpreyru** [comment]
Does not look like a bug to me. We only show forum links for users who had participated in a challenge. I've checked, and I see the link for past challenges I have participated in. It might be not visible for past design challenges, but that would be a dublicate of #191
