### ISSUE TITLE
Profile Page: Error while updating Profile picture

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2049]
**Describe the bug**
"Failed to update user trait" error while updating user profile

**To Reproduce**
1. Go to 'http://www.topcoder-dev.com/settings/profile'
2. Click on 'Profile' tab
3. Click on  'Upload a new avatar'
4. Choose any image from your system
5. Fill the required details if not there in profile page
6. Click "Save Changes" at the bottom of the page

**Expected behavior**
Profile should be saved, and image should be reflected as profile avatar

**Screenshots**
https://i.imgur.com/OHtDK23.png
![image](https://user-images.githubusercontent.com/6736067/54462233-fdc83880-4794-11e9-94bc-609c5b90aa6e.png)

**Desktop (please complete the following information):**
 - Windows 10 PRO
 - Google Chrome
 -  73.0.3683.75 (Official Build) (64-bit)

**Comment by ThomasKranitsas** [comment]
This has been fixed but it's not yet deployed. Will close the issue but it'll count for the bug hunt scoring.
