### ISSUE TITLE
[$20] - [Bug Hunt - NEW BUG]Blank filters are shown in edit page but can't see in normal page

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#205]
1) Create several filters and then edit them, rename their names to blank, and click "done"
2) You will not see the blank name filters but if you edit them, they will back
3) Maybe should forbid blank filter name
<img width="639" alt="2017-08-24 10 31 13" src="https://user-images.githubusercontent.com/3046795/29671519-58e5511e-891c-11e7-8abd-3affe79e5e82.png">

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
Indeed, we should not allow to save blank filter names.

**Comment by twicoder** [comment]
PR #283
