### ISSUE TITLE
Settings > Profile > Skill: Error while adding skills

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2050]
![image](https://user-images.githubusercontent.com/42398485/54462281-2de3ed00-473d-11e9-8cd9-a15605191c96.png)

```
PATCH https://api.topcoder-dev.com/v3/members/TonyJ/skills 400
16:13:07.149 main-1552640067013.js:65 Uncaught (in promise) Error
    at main-1552640067013.js:65
    at m (main-1552640067013.js:57)
    at Generator._invoke (main-1552640067013.js:57)
    at Generator.e.(/settings/anonymous function) [as next] (https://d1aahxkjiobka8.cloudfront.net/static-assets/main-1552640067013.js:57:35948)
    at o (main-1552640067013.js:9)
    at main-1552640067013.js:9
    at new Promise (<anonymous>)
    at new t (main-1552640067013.js:9)
    at main-1552640067013.js:9
    at main-1552640067013.js:65
```

1. Open the application and login as Tonyj
2. Hover over the profile avatar > Click Settings
3. Click Profile Tab > Skills
4. Add a skill

**Actual:** Error while adding skills

**Expected:** Should not display such an error while adding skills

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
@ajefts @cwdcwd @urwithat it would be great to get this fixed on the dev db as it prevents us from testing on dev

**Comment by nithyaasworld** [comment]
This is no more an issue.
