### ISSUE TITLE
Profile Settings: TRACKS are not saving after saving profile

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2055]
**To Reproduce**
1. Go to 'http://www.topcoder-dev.com/settings/profile'
2. Click on 'Profile' tab
3. Fill out if any mandatory fields are not filled yet
3. Scroll down to 'TRACKS'
4. Enable any track(eg. : DESIGN)
5. Click on "Save changes"
6. Reload the profile settings page('http://www.topcoder-dev.com/settings/profile') and verify TRACKS are saved or not

**Screenshots**
![image](https://user-images.githubusercontent.com/6736067/54463052-c7d88380-4797-11e9-8102-f780a75be3b7.png)

 
**Actual**: TRACKS are not saving after clicking on "Save Changes" button in profile settings page

**Expected**: TRACKS should be saved with user's selection mentioned in step4

**Reproducible Rate**: 3/3

**Environment**: Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Comment by kiranmaroju** [comment]
Video URL: https://dl.dropboxusercontent.com/s/gvlicexyiv8o2k6/3qttOwt2Pn.mp4

**Comment by ThomasKranitsas** [comment]
seems to be working fine now
