### ISSUE TITLE
Settings > Profile > Hobbies: Error while adding a hobby 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2057]
![image](https://user-images.githubusercontent.com/42398485/54463418-07c04c00-4741-11e9-936c-b2857d0fe401.png)

1. Open the application and login as Manager (pshah_manager)
2. Hover over the profile avatar > Click Settings
3. Click Profile Tab > Hobbies
4. Enter data (Hobby: A; Description:A)
5. Click 'Add hobby to your list'

**Actual:** Error while adding a hobby

**Expected:** User should be able to create a hobby without an issue

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
Can you provide more details? Is this a new account, did you do anything else before saving the hobby? I cannot reproduce this.
