### ISSUE TITLE
Settings > Account > My Account: Changing the E-Mail address shows an error

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2059]
1. Open the application and login as Manager (pshah_manager)
2. Hover over the profile avatar > Click Settings
3. Click Account Tab > My Account
4. Click Change Email button
5. Enter the new email and click Send verification email

**Actual:** Changing the E-Mail address shows an error

**Expected:** Should be able to change the email and new email address entered should receive an email

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
The flow has been modified. Pending frontend updates.

I'll close this but it's valid for the bug hunt.
