### ISSUE TITLE
Public Profile: "DESIGN FIRST2FINISH" challenges are not showing

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2064]
**Describe the bug**
"DESIGN FIRST2FINISH" challenge related details are not showing even though there are few(1) associated with user profile. Showing below message
"Sorry, no successful challenges found."

**To Reproduce**
1. Go to any user's public profile 'https://www.topcoder.com/members/thomaskranitsas/'
2. Click on "DESIGN FIRST2FINISH" section to see challenges
3. Check the count of Wins and Challenges user participated
4. Click on "Challenges" tab , and verify the challenge details

**Expected behavior**
Should show "DESIGN FIRST2FINISH" related challenges that user has participated.

**Screenshots**
https://dl.dropboxusercontent.com/s/0eef7erpvsub5cc/FT4omCds9m.mp4

**Desktop (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Comment by ThomasKranitsas** [comment]
Invalid issue. I only have 1 design F2F challenge in my profile which is a private task thus it's not visible to you.

You can check the profile from a designer (eg https://www.topcoder.com/members/iamtong/details/?track=DESIGN&subTrack=DESIGN_FIRST_2_FINISH&tab=challenges)

**Comment by kiranmaroju** [comment]
@ThomasKranitsas , HI

iamtong's Design F2F challenges also not displaying. 


![image](https://user-images.githubusercontent.com/6736067/54480074-4c83da00-484a-11e9-8df0-2a821bd7265f.png)
