### ISSUE TITLE
Settings -> Account ->Change email: Exception Error pop-up appeared "...contact our support support@topcoder.com"

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2065]
Steps:
Settings -> Account 
Click on Change email
Enter New email address same as Primary Email
Click on "Send Verification Email"
Exception Error pop-up appeared "...contact our support support@topcoder.com"

Actual: Exception Error pop-up appeared "...contact our support support@topcoder.com" when click on "Send Verification Email"

Expected: Exception should not be coming. instead proper error message should be displayed.

Reproducible  Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)

![Issue_2](https://user-images.githubusercontent.com/48600675/54465790-f7d95400-47a2-11e9-97fe-8a76bc019d70.PNG)

**Comment by ThomasKranitsas** [comment]
Duplicate https://github.com/topcoder-platform/community-app/issues/2059
