### ISSUE TITLE
Settings -> Account ->Change email: "Send Verification Email" button got enabled even though New email address same as primary email

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2066]
Steps:
Settings -> Account 
Click on Change email
Enter New email address same as Primary Email
"Send Verification Email" button got enabled even though New email address same as primary email

Actual: "Send Verification Email" button got enabled even though New email address same as primary email

Expected: "Send Verification Email" button should not get enabled if New email address same as primary email

Reproducible  Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
![Issue_4](https://user-images.githubusercontent.com/48600675/54465925-8c43b680-47a3-11e9-8613-de865ba1a28f.PNG)

**Comment by ThomasKranitsas** [comment]
fixed
