### ISSUE TITLE
Public Profile: Past SRMs are not shown

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2068]
![image](https://user-images.githubusercontent.com/42398485/54466223-df3e4f00-474c-11e9-93db-1c2e9cbb8e53.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder-dev.com/members/Egor/details/?track=DATA_SCIENCE&subTrack=SRM&tab=statistics
3. Click Past SRM

**Actual:** Past SRMs are not shown

**Expected:** Should show the Past SRMs

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
https://www.topcoder.com/members/roma/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

**Comment by ThomasKranitsas** [comment]
@sushilshinde  @skyhit does this look like an API issue?

**Comment by nithyaasworld** [comment]
This issue seems to have resolved

![image](https://user-images.githubusercontent.com/5114190/59377933-d3c0eb00-8d70-11e9-897d-561f6eb2a07e.png)
