### ISSUE TITLE
[$40] - register button  enabled for winner annonced challenge 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#207]
Steps to Reproduce

   
  Goto http://community-app.topcoder.com/challenges/30058908/?type=develop
  Click  winner link 
  Observe  Next Deadline:  and register button 
   

Actual Result(s)
Next Deadline:  staus is register and register button  enabled 

Expected Result(s)
Should show the status properly 

  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
![screenshot-community-app topcoder com 2017-08-24 20-03-53](https://user-images.githubusercontent.com/3225433/29671983-a75db2aa-8908-11e7-9dc4-c034b342b370.png)

**Comment by chqy24** [comment]
ready for review, PR #266

**Comment by chqy24** [comment]
@birdofpreyru 
PR #266 has been updated
