### ISSUE TITLE
Public Profile: (Common) Challenges count is not matched with the list count

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2073]
![image](https://user-images.githubusercontent.com/42398485/54466901-106c4e80-4750-11e9-8102-c5d4384fd6ab.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/iamtong/details/?track=DESIGN&subTrack=BANNERS_OR_ICONS&tab=challenges
3. Challenge count-24 but the list have only 19

**Actual:** Challenges count is not matched with the list count

**Expected:** Count should match with the list count

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
This is not a bug but it's a valid UX issue.

We should probably add a message to indicate that private challenges are not shown.

**Comment by Oanh-and-only-Oanh** [comment]
@oanh-and-only-oanh

**Comment by ThomasKranitsas** [comment]
@Oanh-and-only-Oanh can you please create some designs for the message I described above (if you agree with my suggestion)?

**Comment by Oanh-and-only-Oanh** [comment]
@ThomasKranitsas I see 19 which doesn't match with total count of 24. I also see some listed challenges wins are for private challenges. What are some other private challenges that wouldn't show up here?

**Comment by ThomasKranitsas** [comment]
@Oanh-and-only-Oanh by private, I mean challenges that belong to groups (or communities) where you may not have access. For example, a TopGear member can have a history of multiple TopGear challenges in his history which you can't see unless you are also a TopGear member.

The counter shows them but you can't see the actual challenges.

Another good example is the F2F track.
We use F2F challenges for private task payments and those are counted in but now displayed. Only the member and the copilot can see them.

The private challenges you see in the link from the issue description are not actually private. They just have a flag that prevents the winning submission from being viewable.

Let me know if something is not clear.

**Comment by Oanh-and-only-Oanh** [comment]
what about adding another count "Total Challenges" and "Private Challenges" only when applicable?

@ThomasKranitsas  to check how we store the `wins`

**Comment by ajefts** [comment]
@Oanh-and-only-Oanh I think we may need to step back and evaluate the fields we show on these to determine if we should be showing public, private both, etc. along the same lines as the conversation we were having about private profiles in general.
