### ISSUE TITLE
View public profile returns 404 HTTP Error

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2076]
Steps:
https://www.topcoder-dev.com/members/ashok.das1
Click on public profile.
Received "404 HTTP Error"

Actual: Unable to view public profile

Expected: "404 HTTP error" should not be coming

Reproducible  Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
![Issue_8](https://user-images.githubusercontent.com/48600675/54467569-ffe9c180-47ab-11e9-8e33-6c44345c3696.PNG)

**Comment by ThomasKranitsas** [comment]
Fixed
