### ISSUE TITLE
Settings > Account > Linked Accounts: Long time taken to load the data but sometimes it never loads

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2077]
![image](https://user-images.githubusercontent.com/42398485/54468263-cf2c6c80-4758-11e9-9c77-22b75303ae63.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder-dev.com/settings/account
3. Click Linked Accounts
4. Enter http://www.gitlab.com as a link
5. Check the link card, refresh the page and check the link card again

**Actual:** Long time taken to load the data but sometimes it never loads

**Expected:** Should display the short description

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by nithyaasworld** [comment]
This works good now.
