### ISSUE TITLE
Settings > Tools: Can't edit existing items

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2078]
![image](https://user-images.githubusercontent.com/42398485/54468439-8ecdee00-475a-11e9-9409-96706197dbc5.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder-dev.com/settings/tools
3. Click Devices/Software/Service Providers/Subscriptions
4. Edit an existing item

**Actual:** Can't edit existing items

**Expected:** User should be able to the edit existing items especially devices, because when the user updates the OS user needs to delete the existing and needs to create a new device now

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by SathyaJayabal** [comment]
This issue is fixed.
<img width="1386" alt="Screenshot 2020-02-04 at 10 18 05 AM" src="https://user-images.githubusercontent.com/58783823/73714697-b5f92980-4737-11ea-9dfe-ca787f661339.png">
