### ISSUE TITLE
Settings>>Profile>>Edit any field and save always throws the same error

### ISSUE THREAD

**Issue by DharaniD88** [topcoder-platform/community-app#2079]
**Describe the bug**
Every time same failure message is shown even if the given details are correct in Basic info of Profile settings page

**To Reproduce**
Open the application and login as Member
Hover over the profile avatar > Click Settings
Click Profile Tab > Basic Info
Enter data (Required fields)
Click Save changes
Actual: Error while saving the basic details

**Expected behavior**
No error should be thrown if given details are valid

**Screenshots**
![image](https://user-images.githubusercontent.com/47949458/54469336-cff6ea00-47bc-11e9-91c6-7f0494e11290.png)

**Desktop (please complete the following information):**
 - OS: [HP Pavilion; Windows 10 |]
 - Browser Chrome Version 73.0.3683.75 (Official Build) (64-bit)]

**Comment by ThomasKranitsas** [comment]
The provided information is not enough to understand the error. You should also provide screenshots or paste the console log output.
