### ISSUE TITLE
[$50] - SUBMISSIONS link   not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#208]
Steps to Reproduce

   
  Goto http://community-app.topcoder.com/challenges/30058908/?type=develop
 click SUBMISSIONS link 

   

Actual Result(s)
nothing happen 

Expected Result(s)
Should show submissions page 
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
![screenshot-community-app topcoder com 2017-08-24 20-01-19](https://user-images.githubusercontent.com/3225433/29671884-49068844-8908-11e7-9682-7c9754d8e574.png)

**Comment by birdofpreyru** [comment]
Accepted, 5 points

**Comment by birdofpreyru** [comment]
Please pay attention to #218, it looks related, and should be fixed as a part of this one as well

**Comment by birdofpreyru** [comment]
Also check #228. Should address that one as well.

**Comment by chqy24** [comment]
Assign to my self.

**Comment by chqy24** [comment]
ready for review, PR #255
