### ISSUE TITLE
Proper validation is not In settings>>Tools>>Devices>>Fields of add devices accepting special characters

### ISSUE THREAD

**Issue by DharaniD88** [topcoder-platform/community-app#2081]
**Describe the bug**
In settings>>Tools>>Devices>>Fields of add devices accepting special characters
and also Settings>>Tools>>Software
**To Reproduce**
1. Open the application and login as Member
2. Hover over the profile avatar > Click Settings
3.Click Tools Tab > Devices
4. Enter data (Manufacturer: :::::::::::::::::::::: os version: }}}}}}}}}}}}}})
5.Click 'Add Device to your list' the device with invalid details are getting added
6.Click Tools Tab >software
4. Enter data (Name %%%%%%%%%%%%%%%%%%)
5.Click 'Add Software to your list' the device with invalid details are getting added

Same issue for Adding service provider
Actual behavior:
Fields are accepting even the special characters as a field value which is not valid for the specific field

**Expected behavior**
Invalid characters should not be accepted for the fields. Proper validation should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/47949458/54469464-49dba300-47be-11e9-8b13-1e9cbcadca57.png)

![image](https://user-images.githubusercontent.com/47949458/54469533-2bc27280-47bf-11e9-9101-473e1c5a0907.png)

![image](https://user-images.githubusercontent.com/47949458/54469568-98d60800-47bf-11e9-8a39-5ca02c9a3b5f.png)

![image](https://user-images.githubusercontent.com/47949458/54469596-f9fddb80-47bf-11e9-8ad9-e43c8f056bb1.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [Chrome]
 - Version [73]

**Comment by ThomasKranitsas** [comment]
Closing as we can't really prevent this but I'll count it for the bug hunt
