### ISSUE TITLE
Setting>Tool>Subscription: No validation message for empty field on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2086]
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Tool Tab > Subscription
4. Click Add Subscription

**Actual:**
No validation message for an empty field
**Expected**
Should show a validation ("Name cannot be empty") 
**Screenshots**
No screenshot
**Smartphone :**
 - Device: [Oppo F7], android 8.1
 - Browser [Google Chrome]

**Comment by ThomasKranitsas** [comment]
Duplicate https://github.com/topcoder-platform/community-app/issues/2083
