### ISSUE TITLE
Setting>Tool>Service Provider: broken input text if the text is too long on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2088]
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Tool Tab > Service Provider
4. At field [Provider Name]: input text [testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest]
5. Click Add Service Provider

**Actual:**
Broken input text if the text is too long on mobile

**Expected**
The text should fit inside screen

**Screenshots**
![viber image 2019-03-16 , 09 59 26](https://user-images.githubusercontent.com/26895101/54469949-481bda80-47d2-11e9-8f09-039440a88518.jpg)

**Smartphone :**
 - Device: [Oppo F7], android 8.1
 - Browser [Google Chrome]

**Comment by nithyaasworld** [comment]
This is tested with invalid data. In real time, this is not likely to happen.

Closing this for now! 

CC: @Oanh-and-only-Oanh
