### ISSUE TITLE
Settings > Profile > Basic Info: Delete button layout changes when user uploads a camera photo

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2089]
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Profile Tab > Basic Info
4. Click the Browse button near the profile image
5. Select Camera and take a photo and click OK
6. Look at the delete button while uploading

**Actual:** Delete button layout changes when the user uploads a camera photo

**Expected:** Delete button layout should not be changed

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![Screenshot_20190315-220404](https://user-images.githubusercontent.com/42398485/54470106-808acc80-4770-11e9-95af-50f817ecf675.png)

**Comment by ThomasKranitsas** [comment]
Closing this as the delete button will be removed. It counts for the bug hunt though
