### ISSUE TITLE
Footer overlap with the About • Contact • Help • Privacy links

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#209]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Scroll down the page to the bottom and check the About • Contact • Help • Privacy links

Actual Result(s)
-----------------------------------------------------------------
- Footer overlap with the About • Contact • Help • Privacy links

Expected Result(s)
-----------------------------------------------------------------
- Must not overlap the links

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![17](https://user-images.githubusercontent.com/4592712/29672259-55e45130-8909-11e7-87c1-8785e925c6f5.jpg)

**Comment by birdofpreyru** [comment]
Under the hoold it dublicates the issue #198
