### ISSUE TITLE
Settings > Profile > Basic Info: Uploaded profile image (Camera/Gallery) is not shown immediately

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2090]
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Profile Tab > Basic Info
4. Click the Browse button near the profile image
5. Select Camera and take a photo and click OK (same for the gallery photos)

**Actual:** Uploaded profile image (Camera/Gallery) is not shown immediately

**Expected:** Should update the image immediately

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![Screenshot_20190315-220350](https://user-images.githubusercontent.com/42398485/54470104-7b2d8200-4770-11e9-88c9-5a583106943a.png)

**Comment by ThomasKranitsas** [comment]
I don't think this is a valid issue. It takes some time to upload the picture to our backend.
