### ISSUE TITLE
Setting>Tool>Add Device: broken input text if the text is too long on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2091]
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Tool Tab > Add Device
4. At field [Manufacturer]/[Model]/[Operation System]/[OS version]/[OS language]: input text [testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest]
5. Click Add Device

**Actual:**
Broken input text if the text is too long on mobile

**Expected**
The text should fit inside screen

**Screenshots**
![viber image 2019-03-16 , 10 10 57](https://user-images.githubusercontent.com/26895101/54470038-f6744f80-47d3-11e9-87d8-033ec1075e29.jpg)

**Smartphone :**
 - Device: [Oppo F7], android 8.1
 - Browser [Google Chrome]

**Comment by ThomasKranitsas** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2088
