### ISSUE TITLE
Settings > Tools: Sometimes long time taken to enable the add button after adding an item

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2092]
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Tools Tab > Devices/Software/Service Providers/Subscriptions (Any Tab)
4. Add an item
5. Enter data to the empty form again as soon as you created the item
6. Look at the add button and the data in the form

**Actual:** Sometimes long time taken to enable the add button after adding an item. You can see the item is added to the list as soon as the user clicks on the add button but the add button is in the disabled state for sometime

**Expected:** Should able to add another item as soon as user added an item. 

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![Screenshot_20190315-221513](https://user-images.githubusercontent.com/42398485/54470100-736ddd80-4770-11e9-89a5-539354da608c.png)

**Comment by ThomasKranitsas** [comment]
can't reproduce
