### ISSUE TITLE
Setting>Tool>Software: broken input text if the text is too long on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2093]
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Tool Tab > Software
4. At field [Name]: input text [testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest]
5. Click Add Software

**Actual:**
Broken input text if the text is too long on mobile

**Expected**
The text should fit inside screen

**Screenshots**
![viber image 2019-03-16 , 10 17 26](https://user-images.githubusercontent.com/26895101/54470083-c24d5e80-47d4-11e9-88cd-e72b5c1dc5ec.jpg)

**Smartphone :**
 - Device: [Oppo F7], android 8.1
 - Browser [Google Chrome]

**Comment by ThomasKranitsas** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2088
