### ISSUE TITLE
[$20] - [Common] Page won't focus on top once the user clicked the 'view more challenges' link in each sections

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#210]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click 'view more challenges' link in 'Open for registration'

- Click 'Ongoing challenges' link in 'Open for registration'

- Click 'Open for review' link in 'Open for registration'

- Observe the page position

Actual Result(s)
-----------------------------------------------------------------
- [Common] Page won't focus on top once the user clicked the 'view more challenges' link in each sections

Expected Result(s)
-----------------------------------------------------------------
- Must focus the page on top when user click on the 'view more challenges' link

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![17](https://user-images.githubusercontent.com/4592712/29672488-02a5230e-890a-11e7-87a0-9ce5aa9ebe58.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
Indeed, when the buckets are switched in the sidebar, we should scroll to the top of the page.

**Comment by daft300punk** [comment]
Check PR https://github.com/topcoder-platform/community-app/pull/273

**Comment by daft300punk** [comment]
Updated PR - https://github.com/topcoder-platform/community-app/pull/273
