### ISSUE TITLE
Setting>Preferences>E-Mail:The Switch button doesn't changed after click  

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2100]
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Preferences Tab > E-Mail
4. Click button Switch

**Actual:**
Show successfully message but the button doesn't changed (have to refresh the page to see the button change)

**Expected**
The Switch button should change after click

**Screenshots**

** Environments:**
 - Device: MacBook Pro (15-inch, 2016)
 - Browser [The latest Safari]

**Comment by ThomasKranitsas** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2058
