### ISSUE TITLE
Settings> Tools> Subscription> Special characters are accepted in the "Name" field under "Subscriptions".

### ISSUE THREAD

**Issue by Zunu123** [topcoder-platform/community-app#2102]
**Describe the bug**
When entered only special characters in the name text field, it is being accepted.

**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar and Click Settings
3. Click on 'Tools' tab.
4. Click on 'Subscriptions'.
5. Input special characters in the name field.
6. Click on 'Save Changes'.
7. Observe the result.

**Expected behavior**
Special characters should not be accepted in the name text field. Error message should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/48575864/54470457-3afdec00-47d0-11e9-8d8e-b2e347f67f40.png)
![image](https://user-images.githubusercontent.com/48575864/54470491-94feb180-47d0-11e9-9400-4ef0c615e469.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (64-bit)
 - Browser: Firefox Quantum
 - Version: 65.0.2

**Comment by Zunu123** [comment]
Reproducibility Rate: 3/3

**Comment by ThomasKranitsas** [comment]
Closing as we can't really fix this but it'll count for the bug hunt
