### ISSUE TITLE
Settings >Account>Linked Account Adding External link Loading data message appears for long time

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2103]
**Describe the bug**
"Loading data. This will take a few minutes message" appears under newly added link for long time.

**To Reproduce**
1. Go to Settings
2. Click on Accounts. Click on Linked Accounts.
3. Scroll down to 'Adding external links'
4. Add a link and save.
5. Newly added links shows the message "Loading data..." for long time.

**Expected behavior**
Newly added links shows the message "Loading data.." for long time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [Chrome]
 - Version [73.0.3683.75 (Official Build) (32-bit)]

**Additional context**

**Comment by Jacob15** [comment]
![LoadingData](https://user-images.githubusercontent.com/13567734/54470850-633c1980-47d5-11e9-8bd4-50565e2700e6.jpg)

**Comment by ThomasKranitsas** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2077
