### ISSUE TITLE
Settings -> Tools -> Service Providers: "Other" Category icon is not proper.It was assign with no internet or no wifi icon.

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2107]
Steps:
Settings -> Tools -> Service Providers
Add "Internet Service Provider"
Add "Mobile Carrier"
Add "Television"
Add "Financial Institution"
Add "Other"

"Other" Category icon is not proper. It looks like it was assign with no internet or no wifi icon.

Actual: "Other" Category icon is not proper.It was assign with no internet or no wifi icon.

Expected: "Other" Category icon should have its own

Reproducible Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
![Issue_10](https://user-images.githubusercontent.com/48600675/54471758-67236800-47e4-11e9-9d0e-afedc1d22970.PNG)

**Comment by ThomasKranitsas** [comment]
Duplicate https://github.com/topcoder-platform/community-app/issues/2106
