### ISSUE TITLE
[$10] - [Common] Must display the $ sign in front of the 'RELIABILITY BONUS' price

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#211]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058888/?type=develop

- Check the > RELIABILITY BONUS: 220

Actual Result(s)
-----------------------------------------------------------------
- No $ sign displayed in front of the 'RELIABILITY BONUS' price

Expected Result(s)
-----------------------------------------------------------------
- Must display the $ sign in front of the 'RELIABILITY BONUS' price

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![18](https://user-images.githubusercontent.com/4592712/29672748-be47b82e-890a-11e7-89db-60a089fde1cc.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by shubhendusaurabh** [comment]
Assinginy myself

**Comment by shubhendusaurabh** [comment]
PR #267

**Comment by twicoder** [comment]
Sorry, I didn't found it was already picked up.
