### ISSUE TITLE
Settings -> Preference -> Payment:  Not able to differentiate error message with normal line in Edit Payment page.

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2111]
Steps:
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

Settings -> Preference -> Payment
In edit text box "Payment accrual amount (minimum $25):" set value 10
Click on save.

One new line after "Payment accrual amount (minimum $25):" appeared

It is not clear to user that this is the error message. 
Error message should be in read or clearly mentioned that this with "Error:...."

  
Actual: Not able to differentiate error message with normal line in Edit Payment page.

Expected: Error message should be in read or clearly mentioned that this with "Error:...."

Reproducible Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
![Issue_13](https://user-images.githubusercontent.com/48600675/54472211-ee73da00-47ea-11e9-95c2-e00fb9342a39.PNG)

**Comment by ThomasKranitsas** [comment]
As clarified in the forum, those legacy pages are out of the scope of this bug hunt.
