### ISSUE TITLE
Settings -> Tools -> Device: Device details layout issue in mobile browser with max character in all field.

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2112]
Steps:

Settings -> Tools -> Device
Created two console device with max character limit.
Opened same page from Mobile Chrome browser

Device string crossing significant outside from layout

 
Actual: Device details layout issue in mobile browser with max character in all field.

Expected: String should be within boundary limit

Reproducible Rate: 3/3

Environment: Mobile Android| Browser: Chrome 
![Issue_14_Mobile](https://user-images.githubusercontent.com/48600675/54472404-06992880-47ee-11e9-8fe4-2b06c58b3058.png)

**Comment by ThomasKranitsas** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2088
