### ISSUE TITLE
Settings -> Preferences -> Email -> E-Mail Preferences: switch change not getting reflected when user change status

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2115]
Steps:
https://www.topcoder-dev.com/settings/preferences

Settings -> Preferences -> Email -> E-Mail Preferences
Change "Design Newsletter" switch status from off to on
Success message appeared on top.
But Switch did not get enabled.

Refresh page. Now "Design Newsletter" showing enabled.

Similar behaviour for on to off 

"E-Mail Preferences" switch change not getting reflected when user change status

 
Actual: "E-Mail Preferences" switch change not getting reflected when user change status

Expected: Switch should show current change status

Reproducible Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by ThomasKranitsas** [comment]
duplicate
