### ISSUE TITLE
Settings>Account>Linked Accounts: The delete button of link cell have wrong position in mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2116]
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Account Tab > Linked Accounts
4. Look into External link section

**Actual:**
The delete button of link cell have wrong position in mobile (all delete button move to top right of the page)

**Expected**
The delete button should be inside the link cell

**Screenshots**

![viber image 2019-03-16 , 15 20 55](https://user-images.githubusercontent.com/26895101/54472703-6ea43a80-47ff-11e9-98c1-e5748b144370.jpg)

![viber image 2019-03-16 , 15 20 39](https://user-images.githubusercontent.com/26895101/54472702-6e0ba400-47ff-11e9-8b54-bc0a26dca170.jpg)

** Environments:**
 - Device: Oppo F7, android 8.1
 - Browser [The latest Chrome]

**Comment by ThomasKranitsas** [comment]
this has been fixed
