### ISSUE TITLE
Settings -> Profile -> Basic Info -> Personal details: "Birth Date" accepts text in place of calendar date. 

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2117]
Steps:

Settings -> Profile -> Basic Info -> Personal details
Copy text string and paste in "Birth Date" field.
"Birth Date" accepts text in place of calendar date. 

Actual: "Birth Date" accepts text in place of calendar date. 

Expected: "Birth Date" validation should be such that user no way can paste text in calendar date field.

Reproducible Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)
![Issue_15](https://user-images.githubusercontent.com/48600675/54472746-c9379980-47f3-11e9-893c-fb90ec5b6d11.PNG)

**Comment by ThomasKranitsas** [comment]
It resets to the previous date on `blur`
