### ISSUE TITLE
Settings -> Profile -> Community: Community switches on-off are not smooth.

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2118]
Steps:

Settings -> Profile -> Community

Community switch on-off are not smooth.
There is flicker when change status from off to on and on to off.
 

Actual: Community switches on-off are not smooth.

Expected: Community switch on-off should be smooth.

Reproducible Rate: 3/3

Environment: Windows 10 | Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by ThomasKranitsas** [comment]
duplicate
