### ISSUE TITLE
[$30] - [Bug Hunt - NEW BUG]Can't handle invalid date properly

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#212]
1) Open URL
http://community-app.topcoder.com/challenges/?filter[text]=&filter[endDate]=99999999999-09-01T04:00:00.000Z
2) The date is invalid, but it should be handled properly

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
Indeed, we should validate that dates suggested in URL query are proper, otherwise, ignore them and remove corresponding element of the query.

**Comment by twicoder** [comment]
ready for review, PR #272
