### ISSUE TITLE
Settings -> Account -> Linked Accounts: Wrongly placed delete icon in linked account page from mobile device 

### ISSUE THREAD

**Issue by ashokdas1** [topcoder-platform/community-app#2120]
Steps:
https://www.topcoder-dev.com/settings/account
Settings -> Account -> Linked Accounts
Add "www.google.com" through "External Link" edit box.
WEBLINK GOOGLE appeared in Link Accounts

Now, go to Mobile browser and fresh account settings.
Very carefully observed that one delete icon at top right corner of layout.

This delete icon has no meaning with this layout. This is not clear for which item this delete icon.

Actual: Wrongly placed delete icon in linked account page from mobile device 

Expected: Community switch on-off should be smooth.

Reproducible Rate: 3/3

Environment: Mobile Android | Browser: Chrome latest version

![Issue_16_mobile_1](https://user-images.githubusercontent.com/48600675/54472923-cdb18180-47f6-11e9-9510-1368d281750b.png)

![Issue_16_mobile_2](https://user-images.githubusercontent.com/48600675/54472924-d30ecc00-47f6-11e9-8813-6a007af866b5.png)

**Comment by ThomasKranitsas** [comment]
duplicate
