### ISSUE TITLE
Settings>Account>Linked Accounts Add Link Button change into big size while adding already added link

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2123]
**Describe the bug**

Already added link makes add link button bigger.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Account'
3. Scroll down to 'Linked Accounts'
4. Enter the already added link in the External link text box.
5. Observe that the "Add link" button becoming bigger size.

**Expected behavior**
Add link button should not become bigger size while typing already added links.

**Screenshots**
![Add_Link](https://user-images.githubusercontent.com/13567734/54473651-95af3c00-4800-11e9-983c-8f49fa43aa3d.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [safari]
 - Version [65.0.2 (32-bit)]

**Additional context**
User should have already added links.

**Comment by ThomasKranitsas** [comment]
duplicate
