### ISSUE TITLE
Profile Settings: Tools-->Software: Same icon is being displayed for all Software Types 

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2124]
**Steps to Reproduce**

1. Go to  Profile settings and Tools page('https://www.topcoder-dev.com/settings/tools')
2. Click on 'Software' tab
3. Add "Browser" type software entry
4. Add "Utilities" type software entry
5. Check items are saved or not and check icons & data of the above items added

**Actual Behaviour**
Same icon is being displayed for all Software Types 

**Expected behavior**
Different icons should be displayed for different Software Types to easily distinguish software types

**Screen shots/video**
https://dl.dropboxusercontent.com/s/zvqxhb58a3sgwcc/ECDpfc9RwB.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
This is expected behaviour
