### ISSUE TITLE
Settings>Account>Linked Accounts User able to add already defaulted links again.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2125]
**Describe the bug**
User able to add already defaulted link as external link again(for ex:github)

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Account'
3. Scroll down to 'Linked Accounts'. Click it.
4. Add "www.github.com" as external link agin.
5. Click Add link button.

**Expected behavior**
User should not able to add external link as defaulted link again.

**Screenshots**
![Defaultedlink](https://user-images.githubusercontent.com/13567734/54473715-972d3400-4801-11e9-902d-199232b07122.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [ safari]
 - Version [65.0.2 (32-bit)]

**Additional context**
User needs to have account registered with topcoder-dev.

**Comment by ThomasKranitsas** [comment]
Not really an issue. Someone may want to add the link to his/her github org instead of just linking the personal profile.
