### ISSUE TITLE
Profile Settings: Tools-->Service Providers: Same icon for "Financial Institution" and "Internet Service Provider"

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2126]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Service Providers"' tab on left side
3. Add a "Financial Institution" and "Internet Service Provider" entry
4. Check above entries are saved and check the data & icons pf the entries

**Actual Behavior**
Entries are saved with same icon for "Financial Institution" and "Internet Service Provider"

**Expected behavior**
Should have different icon to easily distinguish Service Provider types

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54473813-e031b800-4802-11e9-969c-0dcde71f1e4b.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
Duplicate
