### ISSUE TITLE
Settings>Account>Linked Accounts Disable feature is not present similar to that of defaulted account.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2127]
**Describe the bug**
User unable to disable the external links similar to defaulted links.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Preferences'
3. Scroll down to 'Linked Accounts'. Click on it.
4. User unable to disable the external links added right now.

**Expected behavior**
User should be able to disable the external links added.

**Screenshots**
![Linkedaccounts](https://user-images.githubusercontent.com/13567734/54473816-ee7fd400-4802-11e9-9bf8-473620256ea1.jpg)

**Desktop (please complete the following information):**
 - OS: [windows 7 32 bit]
 - Browser [Safari]
 - Version [65.0.2 (32-bit)]

**Additional context**
User need to have both external and defaulted links

**Comment by ThomasKranitsas** [comment]
Not a valid issue. The user should not be able to disable external links.
