### ISSUE TITLE
Profile Settings: Tools-->Service Providers: Incorrect icon for  "Other" type

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2128]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Service Providers"' tab on left side
3. Add  "Other" type entry
4. Check above entrys is saved and check the data & icons of the enty

**Actual Behaviour**
Incorrect icon for  "Other" type

**Expected behavior**
Icon should be meaningful and easily convey the service provide type 

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54473850-5afad300-4803-11e9-84a0-c28141052d49.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
