### ISSUE TITLE
Settings>Account>Linked Accounts Icons were not highlighted similar to that of defaulted links.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2129]
**Describe the bug**
External link icons were not highlighted in blue color similar to defaulted link when user hover mouse over it.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Account'
3. Scroll down to 'Linked Accounts'. Click on Linked Accounts again.
4. Hover the mouse over the defaulted links and external links added.
5. User able to view blue color highlighted icon for defaulted links but not for external links.

**Expected behavior**
User should be able to view blue color highlighted icon for external links.

**Screenshots**
![Externallinks](https://user-images.githubusercontent.com/13567734/54473891-eaa08180-4803-11e9-9023-6f6ad429f3e7.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [safari]
 - Version [63]

**Additional context**
User needs to have both external and defaulted links mapped to his account.

**Comment by ThomasKranitsas** [comment]
Not a valid issue.
