### ISSUE TITLE
[Common] 'RELIABILITY BONUS' price displayed for Design challenges also

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#213]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?

- Hover over the 'Purse' in a design challenge

Actual Result(s)
-----------------------------------------------------------------
- 'RELIABILITY BONUS' price displayed for Design challenges also

Expected Result(s)
-----------------------------------------------------------------
- Must not display 'RELIABILITY BONUS' price for Design challenges
- Instead system can display Checkpoint price details

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![19](https://user-images.githubusercontent.com/4592712/29672873-17037fe8-890b-11e7-88d0-2afc15df3cc8.jpg)

**Comment by birdofpreyru** [comment]
It is dublicate of #93, it is backend problem: frontend just shows bonus when a challenge data object contains it. The other question is, why backend includes bonuses into challenges that are not supposed to have them. @ajefts, @skyhit  any news on this?
