### ISSUE TITLE
Profile Settings: Tools-->Subscriptions: Only "Name" field displayed, "Type" field is not there

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2130]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Subscriptions"' tab on left side
3. Check fields available to enter data

**Actual Behaviour**
Only "Name" field displayed. "Type" field is not there

**Expected behavior**
For user to enter data in proper & easy way Both Type and Name fields should be there.
Type: Can be anything which topcoder thinks more appropriate, im listing few i thought below 
1. Online Media(Netflix/Amazon Prime etc)
2. Storage(Google Drive/iCloud etc)
3. ...

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54473974-08221b00-4805-11e9-9146-467d6a82c0a8.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
This is a very broad category. I'll close this one as it'll most probably won't get fixed.
