### ISSUE TITLE
Profile Settings: Tools-->Devices: "Add" button is enabled even though all required fields are blank

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2134]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Devices"' tab on left side
3. Check fields available to enter data

**Actual Behavior**
"Add subscription to your list" button is enabled even though all required fields(Type, Manufacturer etc) are blank

**Expected behavior**
"Add subscription to your list" button should be disabled when any of the required fields(Type, Manufacturer etc) are blank

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54474104-a4005680-4806-11e9-814e-eb1e1623a800.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
