### ISSUE TITLE
Profile Settings: Tools-->Software: "Add" button is enabled even though all required fields are blank

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2135]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Software"' tab on left side
3. Check fields available to enter data

**Actual Behaviour**
"Add subscription to your list" button is enabled even though all required fields(Type, Name etc) are blank

**Expected behavior**
"Add subscription to your list" button should be disabled when any of the required fields(Type,Name etc) are blank

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54474144-3ef93080-4807-11e9-9c87-2d32e9fb8e29.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
