### ISSUE TITLE
Settings>Profile>Skills Skill dropdown box to be highlighted similar to that of text box.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2138]
**Describe the bug**
Skill dropdown box to be highlighted similar to that of text boxes.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Profile'
3. Scroll down to 'Skills'.
4. Observe Skill Type dropdown.
5. Its to be higlighted similar to that of text boxes.

**Expected behavior**
Skill Type dropdown were not highligted similar to that of text boxes.

**Screenshots**
![DropdownHighlighted](https://user-images.githubusercontent.com/13567734/54474307-59cca480-4809-11e9-8a15-9bf191e63a50.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [Safari]
 - Version [63]

**Additional context**
User need to have topcoder-dev user account

**Comment by ThomasKranitsas** [comment]
I'm not sure I understand what the issue is here. It seems very trivial to me
