### ISSUE TITLE
Profile Settings: Account-->Linked Accounts: "Add Link" button is enabled even though 'External Link' field is blank

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2139]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/account'
2. Click on 'Linked Accounts' tab on left side
3. Check fields available to enter data

**Actual Behaviour**
"Add Link" button is enabled even though 'External Link' is blank

**Expected behavior**
"Add Link" button should be disabled when any of the required fields('External Link') are blank

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54474370-e11a1800-4809-11e9-97ae-ba8c2d6d9721.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
