### ISSUE TITLE
'Checkpoint Submission' Should be reflected as next deadline wherever applicable

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#214]
Steps to Reproduce
1. Login to open http://community-app.topcoder.com/challenges/30058925/?type=design
2. Click to view all deadline and observe the date of 'Checkpoint Submission' and what is written before 'Next Deadline'
3. Now click on 'Register' to register into challenge.
4. Observe 'Next Deadline'.
Screenshots : 
![image](https://user-images.githubusercontent.com/20595047/29672756-c39eaa8a-890a-11e7-902c-2c3d01a6d3db.png)

Expected Result: Next deadline should be something which is about to close next in given timeline.Therefore, in this case it should be 'Checkpoint Submission' (At least for 'Registered Member').This expected result for given example is valid only if reviewed before Aug 28,2017.Otherwise, try to relate with current date on review of this issue.

Current Result: Next deadline is shown as 'Registration' instead of 'Checkpoint Submission', even for registered member.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by birdofpreyru** [comment]
Dublicate of #193
