### ISSUE TITLE
Profile Settings: Account-->Linked Accounts:  "*Required field" mark is not there on 'External Link' field

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2140]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/account'
2. Click on 'Linked Accounts' tab on left side
3. Check fields available to enter data

**Actual Behavior**
"*Required field" mark is not there on 'External Link' field

**Expected behavior**
"*Required field" mark should be there on 'External Link' field

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54474415-6b627c00-480a-11e9-9ab0-3b5150a334f7.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
I don't think we need a `Required` note here. It's just one field. It can't be optional
