### ISSUE TITLE
Login via Twitter

### ISSUE THREAD

**Issue by JudithElizabeth** [topcoder-platform/community-app#2141]
**Cannot Login via Twitter**
When selecting twitter as as option to log in, Firefox opens another tab, which automatically closes without allowing you to log in.

**To Reproduce**
1. Go to login page
2. Click on Twitter as an option to log in
3. See error

**Expected behavior**
Should open page that asks for Twitter account details

**Video**
https://drive.google.com/open?id=16DDqWbxb5PtlCbtk8hNJoF8A8VFI4rvJ

**Desktop :**
 - OS: Windows 64bit
 - Browser: Firefox
 - Version: 10

**Comment by JudithElizabeth** [comment]
Major

**Comment by ThomasKranitsas** [comment]
This was out of scope
