### ISSUE TITLE
Profile Settings: Account-->Linked Accounts: "Loading data. This will take a few minutes." message displayed even after 15mins

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2142]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/account'
2. Click on 'Linked Accounts' tab on left side
3. Add any account(Stackoverflow, Github )
4. Wait for 15mins
5, Check whether the account data is loaded properly

**Actual Behaviour**
 "Loading data. This will take a few minutes." message displayed even after 15mins

**Expected behavior**
Account data should be loaded properly after some time

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54474478-4e7a7880-480b-11e9-936d-afd39e1f1028.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
