### ISSUE TITLE
Settings>Profile>Hobbies Description User unable to enter new line if the user performed <160+new line operation twice.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2143]
**Describe the bug**
User unable to enter new line after user performed new line operation twice in 160th charecter twice.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Hobbies'
3. Scroll down to 'Description ' text box.
4. Add 160 charecters in Description text box.
5. Delete 160th charecter and add new line.
7. Now move to 160th charecter and add a charecter now charecter count becomes 160.
8. Delete 160th charecter again and add new line.
9. Now move to 160th charecter and add a charecter now charecter count becomes 160.
10. Now try deleting a charecter. User unable to delete 160th charecter.

**Expected behavior**
User should be able to enter new lines at all times without any restrictions.

**Screenshots**
http://www.screencast.com/t/FVEn4gtR

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [safari]
 - Version [63]

**Additional context**
User need to have topcoder.com-dev account.

**Comment by ThomasKranitsas** [comment]
Expected behavior. Newline is counted as a character.
