### ISSUE TITLE
Settings>Profile>Community Alert messages were not appearing again when Community switches on/off

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2145]
**Describe the bug**
Success validation message is not appearing twice when community switches between on/off state without any time interval.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Community'.
3. Change the Community name to on/off state immediately without any interval between two operations.
4. Observe the validation messages were not appearing twice.

**Expected behavior**
Validation messages to be cleared immediately show that the user can feel real experience of toggling between states.

**Screenshots**
http://www.screencast.com/t/4gGk8TuMF

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [Safari]
 - Version [63]

**Additional context**
User need to be a member with topcoder community to have community shown.

**Comment by ThomasKranitsas** [comment]
This will count for the bug hunt but we'll fix it as part of another ticket
