### ISSUE TITLE
Cannot Change Email Prefernces

### ISSUE THREAD

**Issue by JudithElizabeth** [topcoder-platform/community-app#2146]
**Options to change email preferences cannot be clicked**

**To Reproduce**
1. Login in
2. Click on Preferences
3. Try to select or deselect an email preference option

**Expected behavior**
Should be able to select button to make changes

**Video**
https://drive.google.com/open?id=1nK0VudOVcNYOi02Gu2xhscdTqQx6tL66.

**Laptop:**
 - OS: Windows 64 bit
 - Browser Firefox
 - Version 10

**Comment by JudithElizabeth** [comment]
Blocker/Critical

**Comment by ThomasKranitsas** [comment]
duplicate
