### ISSUE TITLE
All the winning challenges are not shown

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2147]
![image](https://user-images.githubusercontent.com/42398485/54475644-a42a3300-47c1-11e9-9b46-436d65babfca.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/Wendell/details/?track=DEVELOP&subTrack=DESIGN&tab=challenges

**Actual:** There are 32 wins but only a few shown

**Expected:** Should show all the 32 challenges

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
Same here as well: https://www.topcoder.com/members/Wendell/details/?track=DEVELOP&subTrack=DEVELOPMENT&tab=challenges

**Comment by ThomasKranitsas** [comment]
The rest are private challenges that you don't have access to.

Invalid issue
