### ISSUE TITLE
[Common] Can't search the full challenge name in search (eg: Cloud Banking UI Prototype Challenge)

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#215]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Enter 'Cloud Banking UI Prototype Challenge' in search

- Press Enter

Actual Result(s)
-----------------------------------------------------------------
- [Common] Can't search the full challenge name in search (eg: Cloud Banking UI Prototype Challenge)
- Check the URL http://community-app.topcoder.com/challenges?filter[text]=%20Cloud%20Banking%20UI%20Prototype%20Challenge

Expected Result(s)
-----------------------------------------------------------------
- Must display the challenge in the search result page

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![20](https://user-images.githubusercontent.com/4592712/29672984-752a01be-890b-11e7-9b5f-6d3b273fdc00.jpg)

**Comment by birdofpreyru** [comment]
I'll accept it with 1 point, cause functionally it looks like dublicate of #179: you have prepended the title with whitespace. If I remove that whitespace, I can find the challenge by its full name.
