### ISSUE TITLE
Public Profile: COPILOT challenges data not showing

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2151]
**Steps to Reproduce**

1. Go to any copilots public profile ex: 'https://www.topcoder.com/members/thomaskranitsas/details/?track=COPILOT&subTrack=COPILOT'
2. Check copilots challenges data

**Actual Behaviour**
COPILOT challenges data not showing

**Expected behavior**
Should show COPILOT challenges

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54476251-167e3000-4821-11e9-8c62-8f8cc2e29b83.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
Expected behavior.
