### ISSUE TITLE
Tapping on a point won't open the tool tip sometimes

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2154]
1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/winterflame/details/?track=DEVELOP&subTrack=TEST_SCENARIOS
3. Click 'View Rating History'
4. Tap on 2010 point

**Actual:** Tapping on a point won't open the tool tip sometimes

**Expected:** Should display the tool tip

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/54476361-5ebe3380-47ca-11e9-8199-7f21434e5e46.png)

**Comment by ThomasKranitsas** [comment]
I guess this is sort of expected as there are quite many points.
