### ISSUE TITLE
[View Rating Distribution] Tool tip goes out of the screen area when user tap on it

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2156]
![image](https://user-images.githubusercontent.com/42398485/54476425-3e42a900-47cb-11e9-8048-487ec666e8ce.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/winterflame/details/?track=DEVELOP&subTrack=TEST_SCENARIOS
3. Click 'View Rating Distribution'
4. Tap on a bar

**Actual:** Tool tip goes out of the screen area when user tap on it

**Expected:** Should display with in the page

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
duplicate
