### ISSUE TITLE
[View Rating Distribution] Very difficult to tap on if the member count is less than 3

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2157]
[View Rating Distribution] Very difficult to tap on if the member count is less than 3

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/winterflame/details/?track=DEVELOP&subTrack=TEST_SCENARIOS
3. Click 'View Rating Distribution' 
4. Tap on a bar that have 2-3 members

**Actual:** Very difficult to tap on if the member count is less than 3

**Expected:** Should increase the bar height ratio with the count

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/54476477-db9ddd00-47cb-11e9-940c-ad1b827740e3.png)

**Comment by ThomasKranitsas** [comment]
Sort of expected.
