### ISSUE TITLE
SRM: the labels of x-axis are overlap when user tap on the 'View Rating Distribution'

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2159]
**To Reproduce**
1. Go to:
https://www.topcoder.com/members/thomaskranitsas/details/?track=DATA_SCIENCE&subTrack=SRM

2. Click 'View Rating Distribution'

**Actual:**
The labels of x-axis are overlap when user tap on the 'View Rating Distribution' 

**Expected**
The labels of x-axis should not overlap when user tap on the 'View Rating Distribution'

**Screenshots**
![Screenshot_2019-03-16-21-48-24-73](https://user-images.githubusercontent.com/26895101/54476972-c6f62f00-4835-11e9-9b85-a6c53aff4796.png)

**Environments:** 
 - Device: Oppo F7, android 8.1
 - Browser [The latest Chrome]

**Comment by ThomasKranitsas** [comment]
duplicate
