### ISSUE TITLE
[$30] - [Common] Empty filter can be saved

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#216]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click Filter

- Click Save Filter

- Observe the 'MY FILTERS' section

Actual Result(s)
-----------------------------------------------------------------
- Empty filter can be saved

Expected Result(s)
-----------------------------------------------------------------
- Must validate before saveing empty filter

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![21](https://user-images.githubusercontent.com/4592712/29673087-c3c08f46-890b-11e7-805f-926f95c0a223.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points

**Comment by shubhendusaurabh** [comment]
assigning myself
