### ISSUE TITLE
[View Rating Distribution/View Rating History] Page width increases after viewing the tool tip

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2160]
![image](https://user-images.githubusercontent.com/42398485/54477165-266f2300-47d3-11e9-8500-d827d5f37c5b.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/winterflame/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH
3. Click 'View Rating Distribution'
4.  Click 'View Rating History'
5. Tap on a bar that has 2-3 members ('View Rating Distribution')
6. Tap on a point ('View Rating History')

**Actual:** Page width increases after viewing the tool tip

**Expected:** Page width should not increase

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Edge 44

**Comment by nithyaasworld** [comment]
Issue cannot be reproduced.
