### ISSUE TITLE
ASSEMBLY COMPETITION: chart line is not showing the correct color

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2162]
**To Reproduce**
1. Go to:
 https://www.topcoder.com/members/thomaskranitsas/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION

2. Click 'View Rating History'

**Actual:**
chart line is not showing the correct color. The rating is in the green area and Y axis color label is red

**Expected**
Should display the Green

**Screenshots**
<img width="1208" alt="Screen Shot 2019-03-16 at 10 59 49 PM" src="https://user-images.githubusercontent.com/26895101/54478004-248f7900-4840-11e9-8059-6e61aa0ec7d0.png">

**Environments:** 
 - Device: Macbook pro (15 inch, 2016)
 - Browser [The latest Safari]

**Comment by ThomasKranitsas** [comment]
Invalid issue
