### ISSUE TITLE
Profile Settings: Tools-->Devices: No Success message after deleting devices

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2164]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/tools'
2. Click on 'Devices"' tab on left side
3. Delete any already existing device
4. Check confirmation/success message after device deletion

**Actual Behavior**
No Success message after deleting devices

**Expected behavior**
Success message should be displayed after deletion of the device

**Screen shots/video**
https://dl.dropboxusercontent.com/s/kcwkkmtj35na9q7/mqUyb4YgAY.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
