### ISSUE TITLE
Profile Settings: profile: Form data entered is not saving temporarily

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2166]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Profile"' tab
3. Enter some data(Country , City, State etc)
4. Reload the page

**Actual Behavior**
Data entered is not showing up again after reloading

**Expected behavior**
Entered data should be shown after reloading, data should be saved temporarily for some time, 
Because there are several fields, user would be entering so much data.
If the page is reloaded due to some reason(network etc) and data is not stored temporarily user have to type data again.

**Screen shots/video**
https://dl.dropboxusercontent.com/s/8o7o9lvb1kcqw63/b7MwGDBHSy.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
Not required
