### ISSUE TITLE
Profile Settings: Profile-->Hobbies: "Add hobby to your list" button is enabled even though all required fields are blank

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2167]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Hobbies"' tab on left side
3. Check "Add hobby to your list" is disabled if no data is entered in required fields("Hobby" & "Description")

**Actual Behaviour**
"Add hobby to your list" button is enabled even though all required fields(("Hobby" & "Description") are blank

**Expected behavior**
"Add hobby to your list" Button should be disabled when any of the required fields("Hobby" & "Description") are blank

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54478724-679b1d80-483b-11e9-9b87-e4b4123fc368.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
