### ISSUE TITLE
Profile Settings: Profile-->Skills: "Add skill to your list" button is enabled even though all required fields are blank

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2169]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Skills"' tab on left side
3. Check "Add skill to your list" is disabled if no data is entered in required fields("Skill")'

**Actual Behavior**
"Add skill to your list" button is enabled even though all required fields(("Skill") are blank

**Expected behavior**
"Add skill to your list" Button should be disabled when any of the required fields("skill") are blank

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54478753-bba60200-483b-11e9-8065-b1f27dfbe8e0.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
