### ISSUE TITLE
[$10] - [Common] Types first letter in to the 'Keywords' and 'Subtrack' are partially visible

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#217]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click Filter

- Enter w in 'Keywords'

- Enter a in 'Subtrack'

Actual Result(s)
-----------------------------------------------------------------
- Types first letter in to the 'Keywords' and 'Subtrack' are partially visible

Expected Result(s)
-----------------------------------------------------------------
- First letter must displayed fully

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![22 1](https://user-images.githubusercontent.com/4592712/29673237-3c908fde-890c-11e7-9715-c1a6a5a5ed65.jpg)
![22](https://user-images.githubusercontent.com/4592712/29673238-3cbebc06-890c-11e7-924e-0ceddb088f51.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by shubhendusaurabh** [comment]
assigning myself

**Comment by elfman** [comment]
This bug is cause by third-party lib `react-Select`, it compute the wrong input size when user input character. set prop `autosize={false}` in `Select` can fix this, but will raise another problem, the Select input will wrap to next line while there is still a lot of space.
The best way to fix it is autosizing the input box by myself, but it will take a lot time, so I give up.

**Comment by birdofpreyru** [comment]
Well, I believe, there should be a way to apply some extra styling on our side to the markup produced by `react-select`, to compensate for this issue. Something like making a padding, or whatever is there, smaller to not hide the letters.

**Comment by elfman** [comment]
the width of `input` is the primary problem.
when `autosize` is true, it will set input's width with inline style. so css styling rule can not override it. 
When input text is more than 3 character, the input string can not be shown completely.

**Comment by elfman** [comment]
er, I find another solution, if the input's `font-size` is `10px`, `react-Select` can work well, input text can shown completely. But the character seems small, is this OK? currently the `font-size` is 15px

**Comment by birdofpreyru** [comment]
Nah, I believe, we need to maintain the size of text according to the design, it is higher priority.
