### ISSUE TITLE
Profile Settings: Profile-->Basic Info: "Save Changes" button is enabled even though all required fields are blank

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2170]
**Steps to Reproduce**

1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info"' tab on left side
3. Check "Save Changes" button is disabled if no data is entered in required fields("Last Name")'

**Actual behavior**
"Save Changes" button is enabled even though all required fields(("Last Name") are blank

**Expected behavior**
"Save Changes" Button should be disabled when any of the required fields("Last Name") are blank

**Screen shots/video**
https://dl.dropboxusercontent.com/s/t1leucnqlnncbs0/pD57Fyu39F.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
