### ISSUE TITLE
Search function is not working correctly on Skills page 

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/community-app#2171]
**To Reproduce**
1. Open the application and login as TonyJ
2. Go to 'https://www.topcoder-dev.com/settings/profile'
3. Click on 'Skills' menu.
4. Type 'kafka' in  skill's dropdown's search box.

**Expected behavior**
  All items with 'kafka' should be display. From skill dropdown, user can slect 'Apache Kafka'  by typing 'kafka' in textbox.

**Screenshots**
![SearchBefore](https://user-images.githubusercontent.com/25297859/54478924-b77be380-483f-11e9-9bb2-ade4356f844a.png)
![SearchAfter](https://user-images.githubusercontent.com/25297859/54478926-b9de3d80-483f-11e9-9579-c0386e5ff2f2.png)

 
**Desktop (please complete the following information):**
 - OS:  macOS Mojave 10.14.3
 - Browser  Chrome
 - Version  72.0.3626.121 (Official Build) (64-bit)

**Comment by ThomasKranitsas** [comment]
duplicate
