### ISSUE TITLE
Profile Settings: Profile-->Basic Info: After changing Country, is not reflecting in public profile page

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2172]
**Steps to Reproduce**
1. Login as "christina_uw" in https://www.topcoder-dev.com
2. Go to user's profile settings page( 'https://www.topcoder-dev.com/settings/profile')
3. Click on 'Basic Info"' tab on left side
4. Change "Country" and save changes
5. Verify new country is reflected in user's public profile page("https://www.topcoder-dev.com/members/christina_uw")

**Actual behavior**
New Country is not reflected in public profile page

**Expected behavior**
New Country should be reflected in public profile page

**Screen shots/video**
https://dl.dropboxusercontent.com/s/a9o9onryih3mtl1/o03SIfxUia.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
This has been fixed
