### ISSUE TITLE
Public  Profile-->Badges: 100,500,1000 Forum post dates are incorrect

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2174]
**Steps to Reproduce**
1. Navigate to any user's public profile(who has posts more than 1000 ex: https://www.topcoder.com/members/nithyaasworld)
2. Click on Badges
3. Check 100, 500, 1000 forum post dates and verify the dates

**Actual behavior**
100, 500,1000 Forum post dates are incorrect, same date(as 1st post) is displayed.

**Expected behavior**
Should show actual date on which that post(1/100/500/1000th) is posted.

**Screen shots/video**
https://dl.dropboxusercontent.com/s/xhcd0y6eupcdxa8/NcKG45thEt.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
The app displays what the API returns. It's an API issue though so I'll close it
