### ISSUE TITLE
Public Profile-->Badges: 50th & 100th Passing Submission dates are incorrect

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2175]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has Passing Submission more than 100 ex: https://www.topcoder.com/members/nithyaasworld)
2. Click on Badges
3. Check 50, 100, Passing Submission dates and verify the dates

**Actual behavior**
100th Passing Submission date is before the 50th Passing Submission.
1st Jul 27th 2013
50th Aug 04th 2013
100th Jul 27th 2013, 

**Expected behavior**
Respective Passing Submission dates should be correct

**Screen shots/video**
https://dl.dropboxusercontent.com/s/987lob9xr44qtlw/gayrX0vaGt.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
