### ISSUE TITLE
Public Profile-->Badges:  Placement dates(25,50,100th) are incorrect

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2176]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has Placements more than 100 ex: https://www.topcoder.com/members/nithyaasworld)
2. Click on Badges
3. Check 25, 50, 100th Placements dates and verify the dates

**Actual behavior**
25, 50, 100th Placements dates shown as 1st Placement Date.

**Expected behavior**
Placements dates should be the dates on which respective(25, 50, 100th) placement is achieved. 

**Screen shots/video**
https://dl.dropboxusercontent.com/s/zfydo2dtdms969b/Y1UMrrKot5.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
