### ISSUE TITLE
Public Profile-->Badges: First Placement dates(25,50th) are incorrect 

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2177]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has First Placements more than 50 ex: https://www.topcoder.com/members/nithyaasworld)
2. Click on Badges
3. Check 25, 50th First Placements dates and verify the dates''

**Actual behavior**
First Placement dates(25,50th) are incorrect , showing 1st First placement date for 25th & 50th also.

**Expected behavior**
First Placements dates should be the dates on which respective(25, 50, 100th) First placement is achieved.

**Screen shots/video**
https://dl.dropboxusercontent.com/s/igq4nzx5wjvvdff/pJ489SJ9X0.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
