### ISSUE TITLE
Public Profile-->Failed to load Marathon challenges

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2178]
**Steps to Reproduce**

1. Navigate to any user's(who has participated in marathons) public profile
ex: https://www.topcoder.com/members/cannab
2. Click on "MARATHON_MATCH"(https://www.topcoder.com/members/cannab/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH)
3. Click on Challenges tab(https://www.topcoder.com/members/cannab/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH&tab=challenges)

**Actual behavior**
Error with "Failed to get member marathons" message displayed

**Expected behavior**
Should load marathon challenges related data(only public challenges)

**Screen shots/video**
https://dl.dropboxusercontent.com/s/s9tvlnbd3l77z2q/OAOCAL4en0.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2069
