### ISSUE TITLE
REGISTRANTS   link not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#218]
Steps to Reproduce

   
  Goto http://community-app.topcoder.com/challenges/30058472/?type=develop
 click REGISTRANTS (75) link 

   

Actual Result(s)
nothing happen 

Expected Result(s)
Should show REGISTRANTS  page 
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 

![screenshot-community-app topcoder com 2017-08-24 20-39-33](https://user-images.githubusercontent.com/3225433/29673314-774e2d20-890c-11e7-9f1c-3b6f1d24f4d6.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 poitns, under the hood is related to #208, I believe
