### ISSUE TITLE
Public Profile-->Invalid Rank(0) displayed in Statistics page

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2180]
**Steps to Reproduce**

1. Navigate to any user's(who has participated in marathons) public profile
2. ex: https://www.topcoder.com/members/cannab
3. Click on "MARATHON_MATCH"(https://www.topcoder.com/members/cannab/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH)
4. Check Rank in Statistics page.

**Actual behavior**
Rank(0) displayed in Statistics page

**Expected behavior**
Valid Rank should be displayed in Statistics page

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54480470-a71f3500-484e-11e9-97ce-29c7f06aaf39.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
1/3

**Comment by ThomasKranitsas** [comment]
duplicate
