### ISSUE TITLE
HomePage>Profile>Profile icon Bootstrap icon still displayed after user get login with topcoder-dev.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2183]
**Describe the bug**
Bootstrap icon having login and Join Topcoder still shows near profile icon in Home page after user complete signing process

**To Reproduce**
1. Go to 'topcoder-dev.com'
2. Enter login credentials with TonyJ.'
3. Observe the Home page displayed.
4. Verify the bootstrap icon is present near to the profile logo.

**Expected behavior**
Bootstrap icon is present near to the profile logo.

**Screenshots**
![Login](https://user-images.githubusercontent.com/13567734/54483629-8ff73c00-487c-11e9-97fd-e77bcef19ef9.jpg)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [Android 8.1.0]
 - Browser [Chrome]
 - Version [72]

**Additional context**
User need to login with topcoder-dev in an android device.

**Comment by ThomasKranitsas** [comment]
out of scope
