### ISSUE TITLE
Settings>Profile>Basic Info Profile picture uploading is very slow.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2184]
**Describe the bug**
profile picture uploading performance is very slow when ompared to other operations.

**To Reproduce**
1. Go to 'Settings''
2. Click on 'Basic Info'
3. Scroll down to 'Profile Picture'. Upload picture
4. It takes 1-2 min to upload the picture

**Expected behavior**
Uploading the profile picture is taking time to load.

**Screenshots**
![Profile_Picture](https://user-images.githubusercontent.com/13567734/54483710-fd579c80-487d-11e9-8cde-c7eac5f429ec.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 7 32 bit]
 - Browser [safari]
 - Version [63]

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [Android 8.0.1]
 - Browser[chrome]
 - Version [73]

**Additional context**
User needs to upload a profile picture in both android and operating systems..

**Comment by ThomasKranitsas** [comment]
This depends on your network and the picture size. Not an issue with the platform itself
