### ISSUE TITLE
Public Profile > Profile Page contents were not displayed in new page without hitting refresh.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2189]
**Describe the bug**
Public profile contents were not displayed while opening in new tab.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Settings'
3. Scroll down to 'Basic Info'. Now click profile icon link again and select "My Profile"
4. My profile page is opening new tab but its contents were not displayed.

**Expected behavior**
Profile page contents to be displayed without hitting any refresh with new tab.

**Screenshots**
http://www.screencast.com/t/wgeRqkOdqSq

**Desktop (please complete the following information):**
 - OS: [windows 7 32 bit]
 - Browser [IE]
 - Version [11]

**Smartphone (please complete the following information):**

**Additional context**
User need to login with topcoder-dev

**Comment by ThomasKranitsas** [comment]
duplicate
