### ISSUE TITLE
View All Deadlines button  not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#219]
Steps to Reproduce

   
  Goto http://community-app.topcoder.com/challenges/30058472/?type=develop
 click REGISTRANTS (75) link 
 Now click View All Deadlines button 

   

Actual Result(s)
nothing happen 

Expected Result(s)
Should show View All Deadlines box
 
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
![screenshot-community-app topcoder com 2017-08-24 20-41-51](https://user-images.githubusercontent.com/3225433/29673425-c681fcbe-890c-11e7-809f-32d8ca8ed994.png)

**Comment by birdofpreyru** [comment]
Hmm... works for me. Can you double check / submit further details?

**Comment by karthikbecse** [comment]
@birdofpreyru  steps updated kindly recheck

**Comment by birdofpreyru** [comment]
Hmm... still works for me on Chrome / Ubuntu. I guess, I should really try it on FF / Windows.

**Comment by birdofpreyru** [comment]
Ok, I believe, it is not a separate bug, but the consequence of #218: there were some corner case that broke our JS code for some challenges, and after that none of JS scripts did not work anymore, including those responsible for opening/closing this panel.
