### ISSUE TITLE
DEVELOPMENT challenges count is incorrect

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2193]
![3](https://user-images.githubusercontent.com/42398485/54485598-a506a780-4849-11e9-8751-78e718a67477.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/winterflame/details/?track=DEVELOP&subTrack=DEVELOPMENT&tab=challenges

**Actual:** DEVELOPMENT challenges count is incorrect

**Expected:** Should show 25 available challenges in the list

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
This is due to private challenges
