### ISSUE TITLE
UI issue in the 'Skill' drop down

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2195]
![5](https://user-images.githubusercontent.com/42398485/54485607-c7002a00-4849-11e9-93c4-0657b3b82276.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder-dev.com/settings/profile
3. Click on Skills

**Actual:** UI issue in the 'Skill' drop down

**Expected:** Should span through the entire section (Comapre with Google Chrome)

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Microsoft Edge 44.17763.1.0

**Comment by ThomasKranitsas** [comment]
duplicate
