### ISSUE TITLE
UI issue in the 'Hobby' text fields

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2196]
![6](https://user-images.githubusercontent.com/42398485/54485610-d7b0a000-4849-11e9-9ea5-a78b2bb1897b.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder-dev.com/settings/profile
3. Click on Hobbies

**Actual:** UI issue in the 'Hobby' text fields

**Expected:** Should span through the entire section (Comapre with Google Chrome)

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Microsoft Edge 44.17763.1.0

**Comment by ThomasKranitsas** [comment]
duplicate
