### ISSUE TITLE
UI issue in the 'Service Providers' and 'Subscriptions' textboxes

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2198]
![8 2](https://user-images.githubusercontent.com/42398485/54485629-0464b780-484a-11e9-83c2-643cb4a152d4.png)
![8 1](https://user-images.githubusercontent.com/42398485/54485630-04fd4e00-484a-11e9-9c03-b2988176a816.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder-dev.com/settings/tools
3. Click on Service Providers
4. Click on Subscriptions

**Actual:** UI issue in the 'Service Providers' and 'Subscriptions' textboxes

**Expected:** Should span through the entire section (Comapre with Google Chrome)

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Microsoft Edge 44.17763.1.0

**Comment by ThomasKranitsas** [comment]
duplicate
