### ISSUE TITLE
Public Profile > No "Developer" icon below profile pic, even though user has participated in Development activities

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2199]
**Steps to Reproduce**

1. Navigate to any user's(who has participated in Development activities) public profile (ex: https://www.topcoder.com/members/PereViki)
2. Below profile pic, check whether "Developer" icon is present or not

**Actual behavior**
No "Developer" icon 

**Expected behavior**
"Developer" icon should be there, and clicking on it should focus development activities on right side.

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54487242-b7202e80-48b9-11e9-9a0b-2e8fb604f315.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
1/3

**Comment by kiranmaroju** [comment]
Developer icon like this:

![image](https://user-images.githubusercontent.com/6736067/54487478-6e1da980-48bc-11e9-8977-6a3e3d0164b9.png)

**Comment by ThomasKranitsas** [comment]
This is based on the selected tracks and not the history.
