### ISSUE TITLE
CSS dublication in dev.

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#22]
> - in many scss file of components we import main style like @import '~styles/tc-styles' This import is being processed by scss which include imported files every time we import it and not only once like webpack.

Most probably, this is not a problem in prod, as styles are optimized by CSS optimization/uglification plugin, which is not used in dev, though. Should be double-checked and enhanced.

**Comment by maxceem** [comment]
There is one more possible side effect of this. DevTools in Chrome, Safari and probably other browsers work very slow. I suspect it's because css bundle file may became too big or just too many duplicate rules are being applied to the same elements, but I've not checked it.

**Comment by birdofpreyru** [comment]
Fixed by 9f86874cbb1fcad70ef336aaa6eae1db24f54d30. The fix makes HMR of (S)CSS somewhat slower, but delivers a reasonable compromise between .css bundle size, performance of browser's developer tools, and HMR speed.
