### ISSUE TITLE
[$20] - Challenge details page hyperlink (Hover, normal, visited) colors are wrong

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#220]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058990/?type=develop

- Check the hyperlinks

Actual Result(s)
-----------------------------------------------------------------
- Challenge details page hyperlink (Hover, normal, visited) colors are wrong

Expected Result(s)
-----------------------------------------------------------------
- Must match with the style guide, attached

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![23](https://user-images.githubusercontent.com/4592712/29673616-6873273c-890d-11e7-8aee-307ae0eb10fa.jpg)

![23 1](https://user-images.githubusercontent.com/4592712/29673634-756e2e14-890d-11e7-8028-5bb7eb893e70.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by iversonLv** [comment]
For this page, spec content is written from Editor which has inline css, seems can't not fix via css file?

**Comment by birdofpreyru** [comment]
Well, we don't touch those styles that have been explicitely set as inline styles by the editor. However, on this page it is not always the case. E.g. the first blue link becomes dark gray on hover, however I don't see any inline styling for this in the page source.

**Comment by twicoder** [comment]
PR #301
