### ISSUE TITLE
Settings> Tools>Devices Name of the device goes out of the modal if the user enter long charecters

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2200]
**Describe the bug**
Device information added is going out of the text box if the length of the device information is much.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Tools'
3. Scroll down to 'Devices'. Add devices with long charecters.
4. User added device information is going out of the text box.

**Expected behavior**
Added device information should not go out of the modal 

**Screenshots**
![layout1](https://user-images.githubusercontent.com/13567734/54487296-a2906600-48ba-11e9-924a-37ac3b4a32dd.jpg)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5 Pro]
 - OS: [Android 8.0.1]
 - Browser [safari]
 - Version [63]

**Additional context**
User need to sign in with topcoder using mobile device.

**Comment by Jacob15** [comment]
This is happening for all softwares, Service Provider &Subscriptions under tools section

**Comment by ThomasKranitsas** [comment]
duplicate
