### ISSUE TITLE
Public Profile-->Badges: Milestones dates are incorrect

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2202]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has milestones more than 50 ex: https://www.topcoder-dev.com/members/iamtong)
2. Click on Badges
3. Check 50,100,150,200th Milestones dates

**Actual behavior**
Dates are incorrect. 50th Milestone date(Jun20 2012) is before the 1st Milestone(1st Mar19.2013)

**Expected behavior**
Milestones dates should be the dates on which respective Milestone is achieved

**Screen shots/video**
https://dl.dropboxusercontent.com/s/8ktu0397z8yxn7b/kN6JPxKUJ6.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
