### ISSUE TITLE
Public Profile-->Badges details are not showing for few members

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2204]
**Steps to Reproduce**

1. Navigate to any user's public profile( ex: https://www.topcoder-dev.com/members/ACRush)
2. Click on Badges
3. Check Badges details showing correctly or not

**Actual behavior**
Empty page displayed

**Expected behavior**
Should show member's badges details

**Screen shots/video**
https://dl.dropboxusercontent.com/s/lkrh61ihcc1pqhe/Txi77RnF0n.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | 
Browser1: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
Browser2: Firefox Quantum 65.0.2 (64-bit)

**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
