### ISSUE TITLE
'WIDGET OR MOBILE SCREEN DESIGN' challenges are not shown

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2207]
![image](https://user-images.githubusercontent.com/42398485/54493455-44558a00-489e-11e9-873a-2dea1ce3bc6f.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/iamtong/details/?track=DEVELOP&subTrack=WIDGET_OR_MOBILE_SCREEN_DESIGN
3. Click on Challenges
4. Look at the count = 9

**Actual:** 'WIDGET OR MOBILE SCREEN DESIGN' challenges are not shown

**Expected:** Should show the challenge cards

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
duplicate
