### ISSUE TITLE
'APPLICATION FRONT END DESIGN' challenges are not shown

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2208]
![image](https://user-images.githubusercontent.com/42398485/54493469-6ea74780-489e-11e9-8ec1-9e0f7ced9398.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/iamtong/details/?track=DEVELOP&subTrack=APPLICATION_FRONT_END_DESIGN
3. Click on Challenges
4. Look at the count = 7

**Actual:** 'APPLICATION FRONT END DESIGN' challenges are not shown

**Expected:** Should show the challenge cards

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
duplicate
