### ISSUE TITLE
[$80] - 'TCO18' Tag in subheading of challenge details not consistent with design spec.

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#221]
Steps to Reproduce
1. Login to open http://community-app.topcoder.com/challenges/30058868/?type=design#winner
2. Observe 'TCO18' tag under heading title of the challenge
3. Also open http://community-app.topcoder.com/challenges/30058970/?type=develop
4. Observe 'TCO18' Tag at same location for this development challenge.
5. Also check 'Header' styleguide in design spec.

Screenshots : 
![image](https://user-images.githubusercontent.com/20595047/29673569-47145958-890d-11e7-8607-6245077f65a2.png)
![image](https://user-images.githubusercontent.com/20595047/29673580-4d45c596-890d-11e7-87e1-410ff4edf926.png)

Expected Result: As per design spec, the mentioned 'TCO' tag should be stylised in such a way that its background to be in light shade of color specific to the challenge type and letters to be written in true color.Hence, here 'TCO18' tag for design challenge should show light blue background with wording written in blue.

Current Result: In current system, for design challenges 'TCO18' tag is present in incorrect format.However, for development challenge it is coorect and consistent with design spec.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by birdofpreyru** [comment]
Accepted, 1 point

### Expected Fix
I would like to make the fix in a fancy way: check the new implementation for buttons, themed using `react-css-themr` in `/src/shared/components/buttons`. These tags are, basically, button-like links with different styling, so we should just add additional themes to style that standard button component as tags, and ensure that proper theme is taken from `ThemeProvider`.

Feel free to ask for more details, if the brief note above does not look creal to you.

**Comment by Colinh84** [comment]
@shubhendusaurabh Did you tag the wrong issue here, or did you really submit a fix for the issue I am assigned?

**Comment by shubhendusaurabh** [comment]
@Colinh84 sorry my bad. I meant #211
