### ISSUE TITLE
'DESIGN FIRST2FINISH' listed on two locations

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2210]
![image](https://user-images.githubusercontent.com/42398485/54493517-0311aa00-489f-11e9-92b9-207e019a3f51.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/iamtong/details/?track=DEVELOP&subTrack=FIRST_2_FINISH
3. Click on menu icon (3x3 icon)

**Actual:** 'DESIGN FIRST2FINISH' listed on two locations

**Expected:** Should display on the design section

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
Those are different. They exist in both Design and Develop track
