### ISSUE TITLE
Some members SRM points/Division and Room info are not showing

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2211]
![image](https://user-images.githubusercontent.com/42398485/54493578-b7133500-489f-11e9-9331-0165392705b5.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm
3. Click Past SRM

**Actual:** Some members SRM points/Division and Room info are not showing

**Expected:** Should display the SRM points/Division and Room info

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment]
duplicate
