### ISSUE TITLE
Some members clicking on division will show a white page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2212]
1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm
3. Click Past SRM
4. Click Division0 in TCO19 Single Round Match 743

**Actual:** Some members clicking on division will show a white page

**Expected:** Should load the division page

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/54493616-0ce7dd00-48a0-11e9-9f1f-342fb5afbb9a.png)

**Comment by ThomasKranitsas** [comment]
@ajefts @cwdcwd fyi, those are legacy pages that are broken
