### ISSUE TITLE
A badge is shown on the page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2214]
1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm
3. Go to https://www.topcoder.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH
4. Click Past SRM

**Actual:** A badge is shown on the page

**Expected:** Should not show that particular badge on the page because on the desktop there is no such a badge shown the page

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by codejamtc** [comment]
![Screenshot_20190317-115729](https://user-images.githubusercontent.com/42398485/54494783-fe9fbe00-48ab-11e9-9f65-1bffcf617e2a.png)

**Comment by ThomasKranitsas** [comment]
Expected behavior
