### ISSUE TITLE
Public Profile-->Badges: Same dates displayed for "Rated Algorithm Competition"

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2215]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has "Rated Algorithm Competition"more than 25 ex: https://www.topcoder.com/members/Cosmin.ro)
2. Click on Badges
3. Check 1st,5th, 25th Rated Algorithm Competition" dates

**Actual behavior**
Same dates displayed as 1st "Rated Algorithm Competition" for the 5th & 25th also
1st - Sep 28th 2012
5th - Sep 28th 2012
25th - Sep 28th 2012

**Expected behavior**
"Rated Algorithm Competition" dates should be the dates on which respective "Rated Algorithm Competition" is achieved

**Screen shots/video**
https://dl.dropboxusercontent.com/s/vna1622fyiayapk/cHWxlGdijI.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
