### ISSUE TITLE
Public Profile-->Badges: Same dates displayed for "SRM Room Win"

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2216]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has "SRM Room Win"more than 5 ex: https://www.topcoder.com/members/Cosmin.ro)
2. Click on Badges
3. Check 1st,5th "SRM Room Win" dates

**Actual behavior**
Same dates displayed as 1st "SRM Room Win" for the 5th  also
1st - Sep 28th 2012
5th - Sep 28th 2012

**Expected behavior**
"SRM Room Win" dates should be the dates on which respective "SRM Room Win" is achieved

**Screen shots/video**
https://dl.dropboxusercontent.com/s/ojqdspngwynqlzk/uamkyU2LWl.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
