### ISSUE TITLE
Public Profile-->Badges: Same dates displayed for "Solved Algorithm Problem" badges

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2217]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has "Solved Algorithm Problem "more than 50 ex: https://www.topcoder.com/members/Cosmin.ro)
2. Click on Badges
3. Check 1st,10th, 50th "Solved Algorithm Problem" dates

**Actual behavior**
Same dates displayed as 1st "Solved Algorithm Problem" for the 10th & 50th also
1st - Sep 28th 2012
10th - Sep 28th 2012
50th - Sep 28th 2012

**Expected behavior**
"Solved Algorithm Problem" dates should be the dates on which respective "Solved Algorithm Problem" is achieved

**Screen shots/video**
https://dl.dropboxusercontent.com/s/ppgvucewswe1gsy/IKGIUl5LXw.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
