### ISSUE TITLE
Public Profile-->Forum posts are loading very slow(more than 22sec) for members who has many posts

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2219]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has forum posts more than 5000 ex: https://www.topcoder.com/members/Wendell)
2. Click on "Forum posts"

**Actual behavior**
Forum posts are loading very slow(taking more than 22secs)

**Expected behavior**
Forum posts should be loaded within 22sec(most accepted time)

**Screen shots/video**
https://dl.dropboxusercontent.com/s/0e5uc2cj1mge6w7/P0RoW76tg8.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
out of scope
