### ISSUE TITLE
[$20] - Clicking on tags will go to All challenges page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#222]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058990/?type=develop

- Click C++

Actual Result(s)
-----------------------------------------------------------------
- Clicking on tags will go to All challenges page

Expected Result(s)
-----------------------------------------------------------------
- Tags must not clickable or
- Must filter the challenges that have the clicked tags associated with (eg: If we click the tag Node.Js, must filter the challenges that have node.js associted with)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![24](https://user-images.githubusercontent.com/4592712/29673984-79a7b90e-890e-11e7-8a5c-54bca586f198.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
### Note
Actually, it works fine now: the tags redirect to challenge listing with proper tag filters activated. Though, we need to ensure that URL is properly updated on such transition (i.e. the filter is added there)

**Comment by shubhendusaurabh** [comment]
assigning myself
