### ISSUE TITLE
Public Profile-->Linked Github profile showing with incorrect details

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2221]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has Github linked ex: https://www.topcoder.com/members/lunarkid)
2. Check the Github details(Followers, Repositories) and verify details

**Actual behavior**
Followers, Repositories details are not matching with actual github details

**Expected behavior**
Guthub details should match with details in github profile

**Screen shots/video**
https://dl.dropboxusercontent.com/s/9hqlojt8x66q8ge/tFjFkWxXqD.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
This is provided by a 3rd party app. Invalid issue
