### ISSUE TITLE
Public Profile-->Can see Private challenges details 

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2224]
**Steps to Reproduce**

1. Navigate to any user's public profile(who has some private challenges ex: https://www.topcoder.com/members/lunarkid)
2. Check above user's(lunarkid) Webdesign challenges
https://www.topcoder.com/members/lunarkid/details/?track=DESIGN&subTrack=WEB_DESIGNS&tab=challenges
3. Check if private challenges details are visible

**Actual behavior**
Can see Private challenges details on public profile

**Expected behavior**
Private challenges details should not be visible on public profile

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/54494497-e7d78680-4900-11e9-8071-ada9167336f4.png)

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
1/3

**Comment by ThomasKranitsas** [comment]
Not a valid issue. This means the submissions are not viewable. Private challenges are not returned by the API. The filtering is happening on the backend
