### ISSUE TITLE
Profile Settings: After saving Tracks, details are not reflecting in profile page

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2226]
**Steps to Reproduce**

1. Navigate to profile settings page(for ex: christina_uw)
2. In the Basic info, Enable Design, Development, Data Science tracks
3. Check details(icons) are reflected in above user public profile page.

**Actual behavior**
Respective icons(Designer, Developer, Data Scientist) are reflecting in public  profile page

**Expected behavior**
Respective icons(Designer, Developer, Data Scientist) should be reflected public  profile page

**Screen shots/video**
https://dl.dropboxusercontent.com/s/jqpef82zihxklf0/31PS84AQN0.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
