### ISSUE TITLE
Profile Settings: Reloading the "Subscriptions" page redirects to "Devices" page

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2227]
**Steps to Reproduce**

1. Go to user's profile settings page-->Basic info (https://www.topcoder-dev.com/settings/tools)
2. Click on Software' tab on left side
3. Add any software item
4. Reload the page to check whether Software page is still there.

**Actual Behaviour**
Reloading the "Software" page redirects to "Devices" page. Should have separate page or marker in url to avoid this issue(ex: https://www.topcoder-dev.com/settings/tools#Software)

**Expected behavior**
Reloading Should launch same page, Should have separate page or marker in URL to navigate to same page that user is working on currently(ex: https://www.topcoder-dev.com/settings/tools#Software)

**Screen shots/video**
https://dl.dropboxusercontent.com/s/xypj0mebyrsbbfr/ZOd2htlp7l.mp4

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
duplicate
