### ISSUE TITLE
Image slider is not working

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2228]
![image](https://user-images.githubusercontent.com/42398485/54495624-365e3400-48b3-11e9-9680-e385e5a180a4.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/abedavera/details/?track=DESIGN&subTrack=STUDIO_OTHER&tab=challenges
3. Click on 2010 TOPCODER OPEN T-SHIRT DESIGN CONTEST
4. Click >

**Actual:** Image slider is not working

**Expected:** Click on < and > buttons should move the images

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Microsoft Edge 44.17763.1.0

**Comment by ThomasKranitsas** [comment]
This is actually working. Check the selected thumbnail at the bottom of the carousel.
