### ISSUE TITLE
Profile Settings: Switching between pages in Tools, deletes entered data

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2229]
**Steps to Reproduce**

1. Go to user's profile settings page-->Basic info (https://www.topcoder-dev.com/settings/tools)
2. Click on 'Device' tab on left side, enter some device details (do not add it)
3. Click on 'Software' tab on left side, enter some software details (do not add it)
4. Switch back to "Devices" page adn check whether the entered data is still there or not

**Actual Behaviour**
Switching between pages, deletes entered data

**Expected behavior**
Switching between the page should not delete data entered by user.

**Screen shots/video**
https://dl.dropboxusercontent.com/s/pfodxnql5c96z64/UAmdW0Q2hx.mp4

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
Expected behavior
