### ISSUE TITLE
[$60] - Menu stays forever when user move the mouse down over COMPETE/LEARN/COMMUNITY

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#223]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058991/?type=develop

- Click Filter and apply any filter

- While filtering move the mouse down over COMPETE/LEARN/COMMUNITY and quickly scroll the page down

- Now scroll up you can see menu is activated and click on any empty location

Actual Result(s)
-----------------------------------------------------------------
- Menu stays forever when user move the mouse down over COMPETE/LEARN/COMMUNITY

Expected Result(s)
-----------------------------------------------------------------
- Must close the menu when user tap on a empty space

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2017-08-25_5-05-05](https://user-images.githubusercontent.com/4592712/29693412-0d619dba-8953-11e7-97f3-194d6fbab677.jpg)

**Comment by birdofpreyru** [comment]
@sdgun Not sure about this one. When I click on empty space, then move mouse out of the menu, it still collapses. Do you mean, that we should close the menu immediately if we click on its empty part (dark gray zone)? It does not look that obvious to me. @vic-topcoder ?

**Comment by vic-topcoder** [comment]
That's a mobile interaction you're describing: on mobile to invoke the menu one has to tap to simulate hover state. On desktop it should not happen. I cannot reproduce this on my side. If your mouse is outside the menu, it should collapse. Always-persistent menu is a bug

**Comment by sdgun** [comment]
@vic-topcoder @birdofpreyru Please give me sometime I will comment the exact steps. I can reproduce this 8/10 times

**Comment by sdgun** [comment]
@birdofpreyru Please check the attached video;

https://www.screencast.com/t/lzsEbOULW

**Comment by birdofpreyru** [comment]
@sdgun Ahhh... I see. It looks the actual reason is that you scroll at the same time when the menu is being opened, so this interfere with JS code taking care about the menu. Accepted, 5 points.

### Expected Fix
The logic behind sub-menu expansion / collapsing should be revised to ensure that scrolling does not break it.
