### ISSUE TITLE
Profile Settings: Switching between pages in Account tab, deletes entered data

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2230]
**Steps to Reproduce**

1. Go to user's profile settings page-->Basic info (https://www.topcoder-dev.com/settings/account)
2. Click on 'Linked Accounts' tab on left side, enter some URL details (do not add it)
3. Click on 'My Account' tab on left side
4. Switch back to 'Linked Accounts'  page and check whether the entered data is still there or not

**Actual Behaviour**
Switching between pages, deletes entered data

**Expected behavior**
Switching between the page should not delete data entered by user.

**Screen shots/video**
https://dl.dropboxusercontent.com/s/iezzbza3zooa139/dPy7YuPVjn.mp4

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
Expected behavior
