### ISSUE TITLE
Profile Settings: Switching between pages in Profile tab, deletes entered data

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2232]
**Steps to Reproduce**

1. Go to user's profile settings page-->Basic info (https://www.topcoder-dev.com/settings/profile)
2. Click on 'Basic Info' tab on left side, enter some details (do not Save it)
3. Likewise add some details in Skills, Hobbies page(do not click on add/save)
4. Switch back to 'Basic Info'  page and check whether the entered data is still there or not

**Actual Behavior**
Switching between pages, deletes entered data

**Expected behavior**
Switching between the page should not delete data entered by user.

**Screen shots/video**
https://dl.dropboxusercontent.com/s/2tv9zbg6f2e6r19/IF9dCyqAWh.mp4

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)

**Reproducible rate**
3/3

**Comment by ThomasKranitsas** [comment]
Expected behavior
