### ISSUE TITLE
Submission button not working in Chrome

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#2234]
A topgear user is reporting seeing this case many times. The same challenge opened in Firefox and Chrome behaves differently. Screenshots are below.

<p></p>

In Firefox Submit button is enabled, but in chrome Submit button is disabled.

<p></p>

Handle = aswathi.nair

Last Reported = March 9, 2019

<p></p>

FireFox

![](https://productboard-files.s3.amazonaws.com/production/attachments/2fb4150e8df6143fff8a9427562bc21ae4b147c05afbc2e6279edd621fdffe14/image.png)

<p></p>

Chrome

![](https://productboard-files.s3.amazonaws.com/production/attachments/30f1a20a7cd6d31b8b512dd297fd2ab9f13355e29d3ba769729a1a4bb6696b0f/image.png)

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1898794

**Comment by ThomasKranitsas** [comment]
@ajefts I just started a bug bash. Should I include this one to get it fixed?

**Comment by nithyaasworld** [comment]
I am not able to reproduce this in https://topgear.topcoder-dev.com/ environment

In the chrome-screenshot provided in the ticket, Next Deadline info is missing. It could be the reason for Submit button being disabled in Chrome.
In Firefox-screenshot, Next Deadline info is present and thus Submit button is enabled

May be, the page in Chrome is not loaded properly for the user.
