### ISSUE TITLE
Bug hunt tool tip not loading 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#224]
Steps to Reproduce

   
  Goto http://community-app.topcoder.com/challenges?
  Move the cursor on bug hunt icon 
  observe 

   

Actual Result(s)
blank tool tip shown  

Expected Result(s)
Should show tool tip  properly
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
![dfgdf](https://user-images.githubusercontent.com/3225433/29674484-f2cffaac-890f-11e7-9a22-d250c886278b.png)

**Comment by birdofpreyru** [comment]
Dublicates #189
