### ISSUE TITLE
Wrong input to the search field stuck at the middle of searching

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#225]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Enter 'Hercules C#' as search term

- Press Enter

- No items displayed

Actual Result(s)
-----------------------------------------------------------------
- Wrong input to the search field stuck at the middle of searching
- http://community-app.topcoder.com/challenges?filter[text]=Hercules%20C#

Expected Result(s)
-----------------------------------------------------------------
- Must display "no items found' if there are no match
- Must not take long time to search

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/dCGbpsJZRGD

**Comment by birdofpreyru** [comment]
Not a bug. It does not stuck, it just keeps on searching in past challenges, but cannot find any. Due to backend restrictions , we can't do it more efficient, we just have to keep on fetching challenges in 50 challenge portions, and check whether they match the search on the frontend side.
