### ISSUE TITLE
Unregistered challenge stays in 'My challenges' category

### ISSUE THREAD

**Issue by Kvm87** [topcoder-platform/community-app#226]
Steps to Reproduce
1. Login to open http://community-app.topcoder.com/challenges?
2. Go for challenge details of any challenge which is not registered by you yet.In this example, go to  http://community-app.topcoder.com/challenges/30058925/?type=design
3. Register into the challenge
4. Go back to 'My Challenges' list to see it included.
5. Again click on challenge to go to details.
6. Now, unregister the challenge.
7. Go back to 'My challenges' list.

Screenshots : Please check video in comment section.

Expected Result: The challenge should not be listed in 'my challenges' list after un-registration.

Current Result:The unregistered challenge continue to stay in 'my challenges' list.

Browser : Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OS : Windows 8.1

**Comment by sdgun** [comment]
https://www.screencast.com/t/4AzjVTkWw

**Comment by birdofpreyru** [comment]
I believe, it does not belong to Community App, and it is a backend problem, that when we register / unregister, the results are not immediately syncronized with ElasticSearch which returns data for rendering the challenge listing. @ajefts can you check / confirm it?

**Comment by birdofpreyru** [comment]
Anyway, I'll accept it with 5 points. However, not opening for the bug bash, as I am still pretty sure it is a backend-related one.

**Comment by birdofpreyru** [comment]
@Kvm87  Btw, have you seen my last post in the challenge forum? I don't know what is your TC nickname to be able to pay for the Bug Hunt part of the challenge.

**Comment by Kvm87** [comment]
Yes, I posted the details just now in challenge forum.Thanks!!!
