### ISSUE TITLE
Registered Design challenges won't display in My Challenges section

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#227]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058925/?type=design

- Register for it

- Go to http://community-app.topcoder.com/challenges?

- Check the My Challenges section

Actual Result(s)
-----------------------------------------------------------------
- Registered Design challenges won't display in My Challenges section
- Even though user enable only design challenges from the filter won't display any My Challenges section and the registered Challenge

Expected Result(s)
-----------------------------------------------------------------
- Must display the design challenges in My Challenges section

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![27](https://user-images.githubusercontent.com/4592712/29675100-c2129e4a-8911-11e7-8558-299a370ee224.jpg)

**Comment by birdofpreyru** [comment]
Similar to #227
