### ISSUE TITLE
URL for Competitive Programming is incorrect on Forum Page

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#2270]
**Describe the bug**
On the Webpage  "https://apps.topcoder.com/forums/", the link ( navbar -> learn -> competitive programming) to Competitive Programming is not correct. The URL contains space between the words

**To Reproduce**
1. Go to 'https://apps.topcoder.com/forums/'
2. Hover Over Learn followed by on competitive programming
3. Look for the URL it is being redirected to on the bottom left corner of the screen before clicking on the icon
4. You will see the URL as https://www.topcoder.com/community/competitive programming/
and it will redirect you to a 404 error.

**Expected behavior**
The URL should be pointed to https://www.topcoder.com/community/competitive-programming/ instead of https://www.topcoder.com/community/competitive programming/ and the user will land on the desired web-page.There is a difference of a space and hyphen only.

**Screenshots**
![image](https://user-images.githubusercontent.com/45197181/54910874-38f40580-4f13-11e9-9e8d-c32e56b55b38.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [71]

**Smartphone (please complete the following information):**
NA
**Additional context**
NA

**Comment by sushilshinde** [comment]
Fixed

![Screen Shot 2019-05-31 at 5 06 26 PM](https://user-images.githubusercontent.com/683231/58703556-a8c8b580-83c6-11e9-819f-46caea240a38.png)
