### ISSUE TITLE
If user is in the 'Checkpoints' tab can't open the 'Winners' tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#228]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058214/?type=design

- Click 'Checkpoints' tab

- Click 'Winners' tab

Actual Result(s)
-----------------------------------------------------------------
- If user is in the 'Checkpoints' tab can't open the 'Winners' tab

Expected Result(s)
-----------------------------------------------------------------
- User must able to opent he winners tab

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![28](https://user-images.githubusercontent.com/4592712/29675377-9c5d875e-8912-11e7-92fc-acb6659f24b8.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points. Probably, related to #208
