### ISSUE TITLE
Spelling correction for skill named 'Symfony'

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#2281]
On the profiles page the one of the skill spelling is incorrect. It should be 'Symfony' instead of 'Sympfony'

Steps to reproduce:
1. Go to the link: https://www.topcoder.com/settings/profile 
2. Add the skill named as 'Sympfony' from the drop down list.

Please refer the attached screenshot
![image](https://user-images.githubusercontent.com/37835397/55262694-99c56a00-5294-11e9-841d-bfeec18ce0f2.png)

@ajefts

**Comment by sushilshinde** [comment]
@urwithat db entry?

**Comment by urwithat** [comment]
@NehaSharma02 & @sushilshinde - This has been fixed, kindly verify and close.
