### ISSUE TITLE
Round Information (Design Challenges) need to be in the top

### ISSUE THREAD

**Issue by systic** [topcoder-platform/community-app#2284]
Hi there,

In Design challenges, we have "Round information" displayed in the bottom which is wrong. It should be originally be seen as a separate section at the top in the challenge page (please see attached screenshot).

https://www.topcoder.com/challenges/30087721/?type=design
<img width="795" alt="Screenshot 2019-03-31 at 4 24 21 PM" src="https://user-images.githubusercontent.com/15885764/55288191-84098f00-53d1-11e9-9f53-03b9e79096c0.png">

This round information should be shown below the "Challenge Summary" (below the yellow info text - please see screenshot) and it should have a title as "Round Information"
<img width="718" alt="Screenshot 2019-03-31 at 4 25 49 PM" src="https://user-images.githubusercontent.com/15885764/55288219-cc28b180-53d1-11e9-89ba-18d718e12401.png">

Let me know if there are any questions.
Thank you!
Shyam [systic]

**Comment by skyhit** [comment]
@systic @sushilshinde can you give me access to https://www.topcoder.com/direct/contest/detail?projectId=30087721? My Handle is `FireIce`, I need to understand the situation in more detail

**Comment by JayaDhaka** [comment]
@adroc-tc

**Comment by systic** [comment]
@skyhit You are added to the project
https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30087721

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde @ThomasKranitsas, where are we on this?

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde how's this going?

**Comment by sushilshinde** [comment]
Deployed on production!

**Comment by adroc-tc** [comment]
@sushilshinde I found an issue (thanks for putting it on production!) the issue is when we have a single- round challenge this should be hidden
<img width="1278" alt="Screen Shot 2019-05-31 at 3 19 38 AM" src="https://user-images.githubusercontent.com/15901238/58688610-f1df2200-8352-11e9-93ff-0b474be6b5a6.png">

**Comment by sushilshinde** [comment]
@adroc-tc yes, on it, will patch it.
