### ISSUE TITLE
Challenge page and listing does not show correct submission counts

### ISSUE THREAD

**Issue by tmalbonph** [topcoder-platform/community-app#2290]
**Describe the bug**

Submission tab is missing in Challenge page while the page for listing challenges does not show the correct number of submissions for the listed projects.

**To Reproduce**

1. Go to Challenge listing page at `https://www.topcoder.com/challenges?`
2. Register to a project you want to participate with like: `https://www.topcoder.com/challenges/30087734`
3. Click the [Register] button to register
4. After successful registration, Click the [Submit] button to submit your solution. Follow on screen instruction for this.
5. Visit Online Review page to check status of the submission, the submission should be there.
6. Go back to Challenge listing page at `https://www.topcoder.com/challenges?` to check if the project submission count is updated.
7. Go back to Challenge page (E.g. `https://www.topcoder.com/challenges/30087734` ) a new Submission tab should be there
8. After step 7, Click on the "Registrants" tab and scroll to find your `handle` (in here were looking for `TMALBONPH` ), it should have a submission date on the `"Submitted Date"` column

**Expected behavior**

a. After step 4 and successfully submit a solution; Following step 5; I have visited the Online review page here `"https://software.topcoder.com/review/actions/ViewProjectDetails?pid=PROJECT_ID"`

**NOTE:**
<Replace the `PROJECT_ID` with the project ID of the challenge you have registered with>

I expected my submission to be listing in Online Review as shown on screen shot `"OR_Screenshot_2019-04-04 09-07-52.png"`

b. Following step 6. I expected my submission should be counted but it is not as shown on screen shot `"Challenges_Screenshot_2019-04-04 09-09-20.png"`

c. Following step 7. I expected my submission should be on the `"Submission tab" but the submission tab is missing as shown on screen shot "Challenge_detail_Screenshot_2019-04-04 09-10-52.png"`

d. Following step 8. I expected my submission date on the `"Submission date" column` should reflect the date and time I have submitted my solution and it was updated as shown on screen shot `"Registrants_Screenshot_2019-04-04 09-11-57.png"`

**Screenshots**

- "Challenge_detail_Screenshot_2019-04-04 09-10-52.png"

![Challenge_detail_Screenshot_2019-04-04 09-10-52](https://user-images.githubusercontent.com/3745678/55525494-cc6fc800-56c3-11e9-83c1-e97e7ef73440.png)

- "Registrants_Screenshot_2019-04-04 09-11-57.png"

![Registrants_Screenshot_2019-04-04 09-11-57](https://user-images.githubusercontent.com/3745678/55525498-cd085e80-56c3-11e9-9fc1-e3fcdd06e95c.png)

- "Challenges_Screenshot_2019-04-04 09-09-20.png"

![Challenges_Screenshot_2019-04-04 09-09-20](https://user-images.githubusercontent.com/3745678/55525496-cc6fc800-56c3-11e9-9551-8903870f421a.png)

- "OR_Screenshot_2019-04-04 09-07-52.png"

![OR_Screenshot_2019-04-04 09-07-52](https://user-images.githubusercontent.com/3745678/55525497-cd085e80-56c3-11e9-87b5-4cb79c74d8f9.png)

**Comment by tmalbonph** [comment]
@sushilshinde @Oanh-and-only-Oanh any updates on this issue?

**Comment by SathyaJayabal** [comment]
@tmalbonph , I see the submission count getting updated on the listings page correctly. Are you still facing this issue?

**Comment by tmalbonph** [comment]
@SathyaJayabal This was an April 2019 issue. Did anyone fix it and this issue was left behind? Anyway, closing it now!

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal This was an April 2019 issue. Did anyone fix it and this issue was left behind? Anyway, closing it now!

It was fixed as part of the V5 challenge api release. Before there was a small delay with the updating the submission count. But now its immediate.
