### ISSUE TITLE
Formatting Of Content In A Card

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2307]
We may need to re-model the way a card is created.

Let's take this [Contentful Card Row](https://app.contentful.com/spaces/b5f1djy59z3a/entries/4fr7QZfF2qh9PWEhtBmOZ3?previousEntries=38TqynTX01qD0k0AyrzrSv,7s3Ly1IkNlOcxaS1787GRg,5Dr60B2YW7U7VYwfeUiIeA) as an example and it's [preview](https://community-app.topcoder.com/examples/contentful/viewport/4fr7QZfF2qh9PWEhtBmOZ3).

Notice in the preview how everything is misaligned.  The buttons do not lineup at the bottom.

Also, DaraK has informed me that in order to keep everything consistent, we should have the same treatment as those spotlight cards when the rounded edges:

<img width="1071" alt="Screen Shot 2019-04-12 at 9 33 01 AM" src="https://user-images.githubusercontent.com/1373998/56052343-05ccb700-5d06-11e9-8329-b8b5841cd629.png">

**Comment by kkartunov** [comment]
@hokienick we can have this with some CSS sugar. No code update required. Check the https://app.contentful.com/spaces/b5f1djy59z3a/entries/5BPWTXQVlFrfH6w5FHZncr?previousEntries=38TqynTX01qD0k0AyrzrSv,7s3Ly1IkNlOcxaS1787GRg,5Dr60B2YW7U7VYwfeUiIeA,4fr7QZfF2qh9PWEhtBmOZ3 and its preview.
What do you think?
