### ISSUE TITLE
Invalid file downloaded when user download the submission

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#232]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058817/?type=develop (Must be a F2F and user needs to participate and uploaded a submission)

- Click Winners tab

- Click 'Download'

Actual Result(s)
-----------------------------------------------------------------
- Invalid file downloaded when user download the submission

Expected Result(s)
-----------------------------------------------------------------
- Must display the correct file uploaded to the challenge > text File

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![31](https://user-images.githubusercontent.com/4592712/29693785-2c88a72c-8955-11e7-8d4c-34f587d557f0.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

@ajefts @skyhit It looks like backend problem to me. For regular F2F challenges it works fine. Though when F2F is task (just payment made, no actual submissions), calling the endpoint to download submission still downloads an empty text file, rather than responding with appropriate HTTP error. Should be corrected.

**Comment by birdofpreyru** [comment]
Fixed, now we don't show winners tab for tasks at all.
