### ISSUE TITLE
[$100] False submission count on challenge page

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#2329]
**Describe the bug**
User reported that when he just launched a challenge (https://www.topcoder.com/challenges/30088979) and right after it went live and had no registrants obviously yet, the page  still shows 1 submission. Ideally the submission count should be coming out to be zero as.

Kindly refer the screenshot below. You can take in account any design challenge. As of now this can be seen in below challenges : 
https://www.topcoder.com/challenges/30088979?tab=details
https://www.topcoder.com/challenges/30088932/?type=design

**Expected behavior**
The submission count on the challenge page should reflect only the member submission and specification submission should not be considered in the count

**Screenshots**
The challenge page shows one submission 
![image](https://user-images.githubusercontent.com/45197181/56634352-4e2d9280-667f-11e9-8a26-0d2c16b0cf0c.png)

There are no submission from the participants. We only have one submission from the copilot which is specification submission.
![image](https://user-images.githubusercontent.com/45197181/56634380-6dc4bb00-667f-11e9-9a43-7bddcf8e8361.png)

![image](https://user-images.githubusercontent.com/45197181/56634396-8503a880-667f-11e9-8827-6de9ef7ff33c.png)

**Comment by nithyaasworld** [comment]
This issue seems to have resolved. 

I have added "On Watch" label and I will be watching the application for few days to see if this gets reproduced. If not, this will be closed.

**Comment by nithyaasworld** [comment]
This issue is not reproduced anymore.

**Comment by nithyaasworld** [comment]
This is occurring again.

![image](https://user-images.githubusercontent.com/5114190/60867967-98b7b780-a249-11e9-8c10-2944fe7a67bb.png)

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this is fixed with release of v5 challenge api.
