### ISSUE TITLE
[$20] - If the submission phase is over must disable the 'Update Submission' button

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#233]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058817/?type=develop (Must be a F2F and user needs to participate and uploaded a submission)

- Click 'View Submissions'

- Click 'Update Submission'

Actual Result(s)
-----------------------------------------------------------------
- Even though the submission phase is over 'Update Submission' button is still enabled

Expected Result(s)
-----------------------------------------------------------------
- If the submission phase is over must disable the 'Update Submission' button

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![32](https://user-images.githubusercontent.com/4592712/29693893-da872e98-8955-11e7-9975-341f4b1346d4.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
The button, indeed, should be disabled or hidden in such case.

**Comment by birdofpreyru** [comment]
Pay attention to #356, hopefully your fix does the same about that button, otherwise should be updated (I have not tested, nor looked in the code, I guess most probably, it is the same button, technically, just the text is different, so fixing one, fixes another?).
