### ISSUE TITLE
Avatar change doesn't propagates change to Forums

### ISSUE THREAD

**Issue by gurmeetb** [topcoder-platform/community-app#2333]
**Describe the bug**
Changing Avatar on Topcoder.com, changes it on Profile and homepage right icon but doesn't propagates the change to forums. 

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile'
2. Change Avatar
3. Goto any registered challenge, try posting in forums or scroll through previous posts in forums
4. You still see previous Avatar, the change is not propagated here. 

**Expected behavior**
We should propagate the change to forums from profile once users change their Avatar. 

**Additional context**
I have tried and testing this option but even after weeks of change it doesn't propagates so maybe we are never pushing the change to forums platform 🤔 ?

**Comment by nithyaasworld** [comment]
This is also reported here: https://github.com/topcoder-platform/community-app/issues/1872

So closing this.
