### ISSUE TITLE
Executing Mailchimp Javascript

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2336]
There is a script that we are trying to run in Mailchimp that should return a list of links to old Mailchimp Newsletters.

As you mentioned in our chat, it turns out that when react triggers it is parsed at raw text and messes things up.  Below please find the code snippet we are trying to accomplish.

```
<style type="text/css">
<!--
.display_archive {font-family: arial,verdana; font-size: 12px;}
.campaign {line-height: 125%; margin: 5px;}
//-->
</style>
<script language="javascript" src="//topcoder.us13.list-manage.com/generate-js/?u=65bd5a1857b73643aad556093&fid=13801&show=10" type="text/javascript"></script>
```

**Comment by kkartunov** [comment]
waits for prod
