### ISSUE TITLE
[$30] - 'Download' button is not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#234]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058817/?type=develop (Must be a F2F and user needs to participate and uploaded a submission)

- Click 'View Submissions'

- Click 'Download'

Actual Result(s)
-----------------------------------------------------------------
- 'Download' button is not working it will redirect the page to 404 page
- https://studio.topcoder.com/?module=DownloadSubmission&sbmid=241585&sbt=original

Expected Result(s)
-----------------------------------------------------------------
- Must download the submission

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![33](https://user-images.githubusercontent.com/4592712/29693927-0e371c4e-8956-11e7-909d-38ae4b4c164f.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by birdofpreyru** [comment]
Current implementation was done some time ago and works for design challenges only. The fix should ensure that it also works properly for development challenges (and, if possible, the same code is used both for design and dev challenges to download submissions).

**Comment by tilumi** [comment]
Hi, I want to work on this issue, can I get the permission to assign this issue to me?

**Comment by tilumi** [comment]
I start with `NODE_ENV=production npm start` on my local machine & navigate to http://local.topcoder-dev.com:3000/challenges/30059030/my-submissions but show nothing
![screenshot 2017-08-29 13 52 56](https://user-images.githubusercontent.com/734766/29806340-630051aa-8cc1-11e7-9e7d-881a4787bb53.png)
and I see a error occurs on the console
```
Failed to get challenge details! TypeError: Cannot read property 'track' of undefined
    at /Users/lucasmf/git/community-app/src/shared/actions/challenge.js:38:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
While the http://community-app.topcoder.com/challenges/30059030/my-submissions shows my submissions:
![screenshot 2017-08-29 13 55 20](https://user-images.githubusercontent.com/734766/29806423-bac14bba-8cc1-11e7-8328-5834137374d0.png)
Is there any configuration I missed?

**Comment by birdofpreyru** [comment]
@tilumi Yes, for production backend you should:
1. Permit node to listen on port 80
2. `NODE_ENV=production PORT=80 npm run dev ` (`npm run dev` is better cause it start in development mode, with hot module reloading).
3. And then you should access as `local.topcoder.com`

**Comment by tilumi** [comment]
Ok, it works, thanks!

**Comment by tilumi** [comment]
Hi, @birdofpreyru 
Is there any backend API documentation?

**Comment by birdofpreyru** [comment]
@tilumi well, it is fragmented (different places for different pieces of the backend).
for this, just check in the existing code, how submissions are downloaded at challenge results tab of challenge details page. Basically, for dev challenges, the download url is just stored in the redux for each submission. For design ones, we have to compose an URL to a legacy studio backend, using challenge ID.

**Comment by tilumi** [comment]
OK, thanks a lot

**Comment by tilumi** [comment]
The PR: #414
