### ISSUE TITLE
Active Page of Navigation Bar (White)

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2346]
Currently it is not known which page of the navigation bar someone is on.  To fix this, we should create it so that the current tab is highlighted in White Text.

**Comment by hokienick** [comment]
Example:  If you are on the Design Statistics page it looks like this:

<img width="1547" alt="Screen Shot 2019-05-06 at 12 15 14 PM" src="https://user-images.githubusercontent.com/1373998/57249008-b160e280-6ff8-11e9-85aa-bb019ac8e858.png">

Notice how all the tabs are the same color, you wouldn't know which page you were on otherwise.  My recommendation is to bold/whiten when on the specific page, something like this:

<img width="1550" alt="Screen Shot 2019-05-06 at 12 15 24 PM" src="https://user-images.githubusercontent.com/1373998/57249126-fedd4f80-6ff8-11e9-891e-437aa728a428.png">

This way we know what the current active page is.

**Comment by kkartunov** [comment]
https://www.topcoder.com/community/statistics/development
Done.
