### ISSUE TITLE
TCO19 Headings Update

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#2348]
For reference:  https://marvelapp.com/17dai3f6/screen/45383283/handoff

To update the texts on the following pages based on the headings mentioned below:

**1.Homepage:**
**1.1 Main Banner: d**escription of the track like for Copilot Tournament the text below it: “We are happy to announce a special opportunity for Topcoder copilots….”  
=> text should be: Body Size – MD (15px / 25px)

**1.2 TCO19 & What’s New + Regional Events sections** descriptions: “Check out what's new for TCO19.”, “We can't wait to get our TCO19 Regional Events kicked off!”
=> text should be: Body Size – LG  (20px / 25px)

**1.3 “Competition Tracks” text** 
=> text should be: Heading 2 (36px / 45px)

**1.4 “Competition Tracks” track name** 
=> text should be: Heading 4 (20px / 35px)

**1.5 “Weekly updates about the Topcoder Open (TCO) straight to your inbox.”**
=> text should be: Heading 3 (28px / 35px)

“•  All the latest news about TCO
•  Leaderboard updates
•  Newly launched TCO-eligible challenges.
•  Blog posts, event updates, contests, and more!”
=> text should be: Body - Size MD (15px / 25px)

**2. Competition Overview**
**2.1 “How it Works”** => should be Heading 2 (36 px / 45 px)
**2.2 “Register and submit for any TCO eligible challenge…. ”**=>  should be Heading 4 (20 px / 35 px)
**2.3 “Each competition for a certain time frame…”** =>  text should be: Body - Size MD (15px / 25px)
Same structure as above would have to be applied for all the other sections on this page in terms of Title, Overview description and Detailed description. Sections to apply this: TCO Regional Events, TCO Onsite Finals in the USA, TCO Competitions, How to Compete, Prizes, Trips  

**3. Competition Rules**
3.1 “Entering the Tournament” and similar titles on the same page: => should be Heading 2
3.2 Table text: => should be: Body MD (15px / 25px)

**4. Regional Events:** https://tco19.topcoder.com/regional-events

**4.1. “Regional Events”**
 => should be Heading 1 (42px / 50px)

_4.2. “Join us at one of our four TCO19 Regional Events! These events include live challenges for attendees…”_
=> text should be: Body Size – MD (15px / 25px)

**4.3 “New And Improved Regional Events”** and similar title should be Heading 2 (36 / 45px)

**4.4 China Regional Event:** https://tco19.topcoder.com/regional-events/tco19-regional-event-china
“About the TCO19 Beijing Event” and all the other titles should be Heading 2 (36 / 45px)

**4.5 Table Header** => should be Label Large size (15 / 20 px bold)

Please apply the above things to all the regionals pages.

**5. Sponsors** 
“Want to see your logo here as a sponsor of the 2019 Topcoder Open?” => text should be: Body Size – MD (15px / 25px)
 

**6. Win a Trip:** https://tco19.topcoder.com/home/win-a-trip
“Win a TCO Trip” => should be Heading 1 (42/50px)

**6.1. “Not participating in one of the TCO Tracks? You still have a chance…”** => text should be: Body Size – MD (15px / 25px)

This applies to all the other sections below as Title + Description.

**7. Copilot Tournament**
“We are happy to announce a special opportunity for Topcoder…” => text should be: Body Size – MD (15px / 25px)

**7.1 Titles like “Overview”, “Leaderboard”, etc**. =>  should be Heading 2 (36 / 45px)

**8. Development, Design, Data Science, Sponsored MM Tournament, Problem Writer, Veterans Community tabs:**
For all of them on the top banners
=>  the title should be H1 size (42/ 50px) and the description below them should be Body Size – MD (15px / 25px)
On content area / white space: => the titles should be H2 (36/ 45px)

**Comment by kkartunov** [comment]
@Dara-K updates available for preview here: https://beta-community-app.topcoder.com/__community__/tco19

**Comment by Dara-K** [comment]
Hi @kkartunov 

Nice updates - the site is looking better now, but I still notice some items that are not improved.

1.5, 2., 3.1 Table text is not updated, 4.2, 4.5, 6.1 , 8 

Can you fix these too?

**Comment by kkartunov** [comment]
Remaining after the last merge:
4.5
