### ISSUE TITLE
[$30] - 'Submit' button is not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#235]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058925/?type=design

- Register for the challenge

- Click 'Submit'

Actual Result(s)
-----------------------------------------------------------------
- Error displayed : You are either not registered for this challenge, or it is not a valid challenge. Please use your browser's back button to return.

Expected Result(s)
-----------------------------------------------------------------
- Must able to submit for the challenge

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![35](https://user-images.githubusercontent.com/4592712/29694057-ec2e611a-8956-11e7-881c-6ead751311b4.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by tilumi** [comment]
Hi, I would like to work on this issue. Could anyone give the permission to me?

**Comment by birdofpreyru** [comment]
@tilumi Ready, added you to collaborators.

**Comment by tilumi** [comment]
Thanks a lot

**Comment by tilumi** [comment]
@birdofpreyru 
Since the projects in development backend are all over the registration deadline, how can I create a new Design project for registration?

**Comment by tilumi** [comment]
@birdofpreyru @sdgun 
I found I can successfully read the submission page if I go back and go to again.
I'll keep trying

**Comment by birdofpreyru** [comment]
@tilumi We saw this problem in prod. Once you have registered for a design challenge, submit button should get you to the same design submission page, as in the current version of the site. As to test it it is enough just to register / unregister, you can do it with production backend.

**Comment by tilumi** [comment]
OK

**Comment by birdofpreyru** [comment]
@ajefts So, it looks to me like the other consequence of slow sync between API v2 and v3 (Elasticsearch). When you register and go directly to submission page, you see the message that you have not registered. The same happens with legacy site in prod.

**Comment by birdofpreyru** [comment]
Does not happen anymore
