### ISSUE TITLE
[$20] - Blank page displayed when user press browser back button to go back from 'Submit' error page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#236]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058925/?type=design

- Register for the challenge

- Click 'Submit'

- Click Browser back button and observe

Actual Result(s)
-----------------------------------------------------------------
- Blank page displayed when user press browser back button to go back from 'Submit' error page
- After the Error displayed : "You are either not registered for this challenge, or it is not a valid challenge. Please use your browser's back button to return." clicking browser back button will display a blank page

Expected Result(s)
-----------------------------------------------------------------
- Must load the challenge details page

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![36](https://user-images.githubusercontent.com/4592712/29694105-4b319376-8957-11e7-9931-c6597b80ebc4.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points

**Comment by birdofpreyru** [comment]
Does not look a problem anymore.
