### ISSUE TITLE
Log in /Join Topcoder button not working on mobile(iPhone) for Topcoder.com

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#2363]
On mobile, the 'Login' and 'Join Topcoder' button on Topcoder.com site is not working on Chrome/Safari browser.

Steps to reproduce
1. Go to https://www.topcoder.com/
2. Click on login button / Join Topcoder button (does not work)

Browser Details:
Chrome (iPhone)  - Not Working
Safari (iPhone) - Not Working

But, on Topcoder.com click on Dropdown and go to Community (top left) is giving normal login screen which allows to login.

Please check and fix the issue.

@RiteshTC

**Comment by Oanh-and-only-Oanh** [comment]
@RiteshTC i thought this was resolved? can we close it?
