### ISSUE TITLE
Challenges Component in Contentful

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2367]
Currently we have a Challenges Block but does not contain any parameters of what it should display.  Currently this is the way the Challenges Block displays on our Veterans page:

<img width="1080" alt="Screen Shot 2019-05-21 at 2 13 14 PM" src="https://user-images.githubusercontent.com/1373998/58131137-b87c1900-7bd2-11e9-8881-2df2a474070f.png">

I think those boxes are ok, but would like to extend its capabilities by making this row scrollable to the left and right, similar to our Content Slider.

If there are no challenges that are returned, there should be a message displayed instead that says "No Active Challenges Available".  If there are only 1 or 2 challenges, those challenges will appear in their current alignment and the other areas will stay blank.

### Challenge Parameters
The following should be available to the webpage creator when creating this section:

**Challenge Slider Title (Mandatory)** - In the example above "Active Challenges" appears upon loading. We should have a textbox that allows us to replace the title.

**Challenge Title Contains (optional)** - For example, if we want to pull all the active fun challenges, we could type in "fun" here to filter out those types of challenges

**Challenge Types Checkboxes (optional)** - This page may want to pull challenges that are Code and UI Design types and should be able to choose them here

**Technologies (Tags) Textbox (optional)** - If we want to display challenges of a certain technology, we should be able to list them here, comma-separated.

**Completed Challenges Radio Button (Mandatory - default on "No")** - Yes/No radio button.  If "yes" is selected, the list should not filter out completed challenges.

**Comment by cwdcwd** [comment]
this should all be doable except for maybe the title filter. That could probably be done client side in whatever component we build that fetches the data. 
technology filter example https://api.topcoder.com/v4/challenges?filter=technologies%3Dnode.js

**Comment by Oanh-and-only-Oanh** [comment]
@hokienick, can you tag this ticket with the corresponding priority level? thanks.

**Comment by kkartunov** [comment]
https://community-app.topcoder-dev.com/examples/contentful/viewport/3p6F0Wei94uEVOzaBPgtdX
https://app.contentful.com/spaces/b5f1djy59z3a/entries/3p6F0Wei94uEVOzaBPgtdX
