### ISSUE TITLE
Submissions won't display in the Challeneg listing page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#237]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[tracks][design]=true

- Check the submissions in "Synergy - Campus Recruitment Web Application Design Challenge." = 0

- Click on the Challenge > http://community-app.topcoder.com/challenges/30058925/?type=design

- Click 'REGISTRANTS' tab

- You can see 1 submission from anshubhatt1910 - Aug 23, 2017 16:37 EDT

Actual Result(s)
-----------------------------------------------------------------
- Submissions won't display in the Challeneg listing page

Expected Result(s)
-----------------------------------------------------------------
- Must display the submissions as 1

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![37 2](https://user-images.githubusercontent.com/4592712/29694347-1d229212-8959-11e7-9c0b-7a95619c5e1b.jpg)
![37 1](https://user-images.githubusercontent.com/4592712/29694348-1d493110-8959-11e7-93c8-d82a6799b139.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points

**Comment by birdofpreyru** [comment]
@ajefts This is API problem, related to #411. The number in challenge listing comes from api v3, submission and checkpoint submission dates come from api v2. And while for some challenges api v2 returns fine results, for the challenge pointed above we have:
![screenshot](https://user-images.githubusercontent.com/20144632/30169191-f683f3ec-93eb-11e7-9f05-7e2680c73b3d.png)
`submissions` array is empty. The dates in the last column of the page are coming from registrants data, where submission dates are present somehow (and they are used as a fallback in our frontend code).
