### ISSUE TITLE
[$10] - Empty Tool tip displayed for Logo Design Challenge 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#238]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[tracks][design]=true&filter[subtracks][0]=Logo%20Design&bucket=past

- Hover over the Lg icon

Actual Result(s)
-----------------------------------------------------------------
- Empty Tool tip displayed for Logo Design Challenge 

Expected Result(s)
-----------------------------------------------------------------
- Must display a tool tip text

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![38](https://user-images.githubusercontent.com/4592712/29694662-8da43200-895b-11e7-81e9-b6616f75b00a.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by twicoder** [comment]
PR #306
