### ISSUE TITLE
Challenge Listing Page: Challenges are not displayed in Past Challenges for some Subtrack and Keyword Filters

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2383]
**Describe the bug**
Challenges are not displayed in Past Challenges for some Subtrack filters (Example: Bug Hunt, Design)
Similary When Keyword filter is applied in Past Challenges, it displays only half the results and the remaining are displayed like boxes

**To Reproduce**
1. Go to https://www.topcoder.com/challenges?
2. Click on Past Challenges 
3. Then apply the filter Subtrack = Bughunt or Design
4. Check the results
5. Similary check the results of the filter: Keyword = QA or Python

**Expected behavior**
All matching challenges should be displayed

**Actual behavior**
1. For some of the Subtrack values, it shows nothing on screen. Just the grey boxes are displayed
2. For Keyword values, it loads only the first few challenges and rest are all displayed as boxes.

**Screenshots**

![image](https://user-images.githubusercontent.com/5114190/58611746-cfef8c00-82cd-11e9-825d-8d5881d613a8.png)

![image](https://user-images.githubusercontent.com/5114190/58611789-f01f4b00-82cd-11e9-8ef1-99659486845b.png)

**Comment by nithyaasworld** [comment]
@sushilshinde Tagging you as I am not able to assign this to you! Please check. Thanks.

**Comment by nithyaasworld** [comment]
As part of this ticket, we should also fix and verify this: https://github.com/topcoder-platform/community-app/issues/1992

**Comment by nithyaasworld** [comment]
@sushilshinde We have increased the Priority for this from P3 to P2. CC: @ThomasKranitsas

**Comment by sushilshinde** [comment]
We will cover this in server-side filtering @nithyaasworld can you log this issue with `Performance` label on beta if that still exists.

FYI... @ThomasKranitsas

**Comment by nithyaasworld** [comment]
This exact issue is not present in SSF , but we have a similar one https://github.com/topcoder-platform/community-app/issues/2391

Priority of this issue has been set to P2 (Resolve in 3 days). Can we get all SSF fixes in 3 days and deploy to production? 

Your thoughts please? @sushilshinde

**Comment by huangqun** [comment]
Is there going to be a fix for this soon?

**Comment by SathyaJayabal** [comment]
This has been fixed in #3610 and #3609
