### ISSUE TITLE
Challenge listing filtering is not working

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/community-app#2384]
**Describe the bug**
https://www.topcoder.com/challenges?filter[tracks][data_science]=true&filter[tracks][develop]=true seems to only load develop

**To Reproduce**
1. Go to https://www.topcoder.com/challenges?filter[tracks][data_science]=true&filter[tracks][develop]=true
2. Scroll down to should see data science and dev projects
3. Only see dev projects
I do see a bunch of  Uncaught (in promise) DOMException sw.js:1 errors

**Expected behavior**
Should see both

**Screenshots**
 This shows the link as incognito not logged in
![Screen Shot 2019-05-30 at 9 45 46 AM](https://user-images.githubusercontent.com/664840/58637117-cb23db80-82bf-11e9-8fa3-cccb9ef5e85f.png)

this is still incognito but removed dev so you can see there are data science projects
![Screen Shot 2019-05-30 at 9 45 52 AM](https://user-images.githubusercontent.com/664840/58637107-c65f2780-82bf-11e9-951a-55ca177546dd.png)

**Comment by dmessing** [comment]
@sushilshinde

**Comment by sushilshinde** [comment]
Thanks @dmessing, looking at it

**Comment by sushilshinde** [comment]
@dmessing 

please look at this video, I was able to see both types of challenges with the filter link

@nithyaasworld can you verify

https://monosnap.com/file/sXNQQLnetuQxZ1rZ27lrlcuhCG1mjT

**Comment by nithyaasworld** [comment]
Yes @sushilshinde 

Hi @dmessing It seems the MM matches were not displayed as the filter "Most Recent" was applied by default and there was no MM matches posted recently. So Old MM matches are not displayed. It can be seen if Challenge list is expanded by clicking "View More".

It can also be seen if the filter is set to Prize High to Low.

![image](https://user-images.githubusercontent.com/5114190/58705635-6e164b80-83cd-11e9-9836-c774e63da0da.png)

**Comment by veshu** [comment]
@sushilshinde @nithyaasworld This can be closed?

**Comment by SathyaJayabal** [comment]
@lakshmiathreya @nithyaasworld @sushilshinde , I am closing this as the filters work fine.
