### ISSUE TITLE
Challenge Listing Page: Date range filter looks misaligned in "Open for review" challenges

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2385]
**Describe the bug**
Date range filter looks misaligned in "Open for review" challenges

**To Reproduce**
1. Go to https://www.topcoder.com/challenges
2. Click on "Open for review" 
3. Expand the filter and Check the Date range

**Expected behavior**
It should be same like in other pages 

**Screenshots**

![image](https://user-images.githubusercontent.com/5114190/58693939-84adaa00-83af-11e9-8a5d-c89d92219ebd.png)

**Comment by sandhiyakavi** [comment]
Size of Review type dropdown box under Filters is smaller sometimes.

![image](https://user-images.githubusercontent.com/55895538/78249142-7b2f2a00-750b-11ea-8f7a-374ab251e996.png)
