### ISSUE TITLE
Challenge listing page: Keywords(Tech Stacks) are not displayed for "Open for review" challenges

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2386]
**Describe the bug**
Keywords(Tech Stacks) are not displayed for "Open for review" challenges

**To Reproduce**
1. Go to https://www.topcoder.com/challenges
2. Click on "Open for review" filter from the right panel
3. Check the challenges listed

**Expected behavior**
It should have Tech Stack displayed just like the other screens.

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/58694766-6ea0e900-83b1-11e9-9a56-862f337153fa.png)

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde can we assign to someone or pick this up for pickup?

**Comment by ThomasKranitsas** [comment]
This may be a backend issue. I need to check before opening this for pickup

**Comment by nithyaasworld** [comment]
Just a note: when I apply "Keywords" filter in the above page, it works. Just the Tech Stack is not displayed on UI.

**Comment by sandhiyakavi** [comment]
Closing the issue as the Tech stacks are getting displayed now.

![image](https://user-images.githubusercontent.com/55895538/106853671-6c9e3a00-66fd-11eb-87ac-2a3e2cd28042.png)
