### ISSUE TITLE
[Common for All] Clicking on registrants icon won't go to the correct URL

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#239]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[tracks][design]=true&filter[subtracks][0]=Logo%20Design&bucket=past

- Click on Registrants icon

Actual Result(s)
-----------------------------------------------------------------
- URL is https://www.topcoder.com/challenge-details/30052440/?type=design#viewRegistrant

Expected Result(s)
-----------------------------------------------------------------
- URL must http://community-app.topcoder.com/challenges/30052440/?type=design#viewRegistrant
- Also when user goes to the page 'Registrants' tab must be selected

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/SJ4HcxPW

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

Not openning for pickup as we are pending another fix, which will allow to deeplink / select tabs on challenge details page in the correct way.
