### ISSUE TITLE
Beta community app: Grey boxes displayed before loading the results

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2390]
**To Reproduce**
1. Go to https://beta-community-app.topcoder.com/challenges
2. Apply any filter or navigate to any options present in the right pane
3. Check the results

**Actual behavior**
It displays Grey box before displaying the results.

**Expected behavior**
No Grey boxes 

**Screenshots**

![image](https://user-images.githubusercontent.com/5114190/58730471-e438a380-8409-11e9-9497-b5fb6b774e99.png)

**Comment by nithyaasworld** [comment]
@sushilshinde I am not able to set the Performance label for this, as I do not have permission.

**Comment by ThomasKranitsas** [comment]
That was as per the designs. This is called "content placeholder". Should we get rid of that and show a loading indicator instead?

cc @sushilshinde @Oanh-and-only-Oanh

**Comment by sushilshinde** [comment]
@ThomasKranitsas is right

**Comment by Oanh-and-only-Oanh** [comment]
@ThomasKranitsas @sushilshinde, going to discuss with Vic.

**Comment by vic-topcoder** [comment]
The place holder was designed to be animated so that we just populate content into a predetermined space instead of jumping the page. This design was inspired by the way Facebook loads the feed with grayed out content placeholders. The whole loading of the page should be pre-rendered to reduce the need of loading indicator.

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld, are the placeholders animated?

**Comment by nithyaasworld** [comment]
No @Oanh-and-only-Oanh , Placeholders are not animated. 

Other thing is that, If we have only few results, say just 2 in the page, then what happens is, it shows lots of such placeholder till it covers the whole view-port. Once the results are available, its shows the 2 results and the extra placeholders are gone. It just doesn't look good to see!!

Video here:  

[placeholder issues.zip](https://github.com/topcoder-platform/community-app/files/3249087/placeholder.issues.zip)

**Comment by Oanh-and-only-Oanh** [comment]
thanks @nithyaasworld. I understand what you're saying. I think this UX is not ideal. Let's work on getting the challenge listings page to load faster (I saw some threads about this) so we can limit the amount of time users see these grey boxes. Then we can revisit this issue if we need to. How does that sound?

**Comment by nithyaasworld** [comment]
Yes, that sounds good! 👍

**Comment by ThomasKranitsas** [comment]
Closing this as it's being corrected here https://github.com/topcoder-platform/community-app/issues/2410
