### ISSUE TITLE
Challenge Listing Page: After returning from challenge details page, UI of Filter values looks broken

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2393]
**To Reproduce**
1. Go to https://www.topcoder.com/challenges and expand the filter
2. Click on any challenge and go into challenge details page
3. Click back and check the filter values

**Actual behavior**
UI of filter values are broken. Please see screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/58733213-8b6d0900-8411-11e9-8953-a9024b1bd950.png)

**Comment by nithyaasworld** [comment]
Tagging @sushilshinde

**Comment by nithyaasworld** [comment]
Also the Sub community filter values are changed, when returning from challenge Details page to Challenge listing page.

![image](https://user-images.githubusercontent.com/5114190/59187167-66effa00-8b92-11e9-8fcf-535b2d457b68.png)

![image](https://user-images.githubusercontent.com/5114190/59187416-07461e80-8b93-11e9-8846-49952f59da73.png)

**Comment by nithyaasworld** [comment]
@sushilshinde Changed the priority to P3 from P4 because of the above issue.

**Comment by sandhiyakavi** [comment]
Closing this issue as it is not applicable now.
