### ISSUE TITLE
$50 | New Nav - "Challenges" navigation not working from Dashboard

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#2395]
**Describe the bug**

"Challenges" navigation not working from the dashboard

**To Reproduce**
1. Go to `https://test-community-app.topcoder-dev.com/my-dashboard`
2. Click on WORK > Compete > All Challenges
3. Challenge page doesn't load, this is an issue is consistent for most of the navigation links present on the page

**Expected behavior**

The respective target page should be loaded.

**Screenshots**
<img width="1923" alt="challenge-link" src="https://user-images.githubusercontent.com/683231/58784528-44456a80-8601-11e9-9eb7-9f39d98a7b63.png">

![Topcoder 2019-06-03 13-30-59](https://user-images.githubusercontent.com/683231/58786036-6096d680-8604-11e9-816e-18c724f76de7.png)

**Desktop:**
 - OS: Mac
 - Chrome

**Comment by luizrrodrigues** [comment]
@Gauravseta Any status on this?

**Comment by sushilshinde** [comment]
@luizrrodrigues please re-open it for pickup. It's P1

**Comment by nahidshahin** [comment]
@luizrrodrigues can I pick it?

**Comment by luizrrodrigues** [comment]
@nahidshahin Sure.

**Comment by nahidshahin** [comment]
@luizrrodrigues where to go when clicking on `All projects` ?

**Comment by luizrrodrigues** [comment]
@nahidshahin Keep dead link for now.

**Comment by nahidshahin** [comment]
@luizrrodrigues PR https://github.com/topcoder-platform/community-app/pull/2620. I keep `All projects` as it was.

**Comment by luizrrodrigues** [comment]
@nahidshahin Please check feedback here: https://github.com/topcoder-platform/community-app/pull/2620#pullrequestreview-249617702
