### ISSUE TITLE
[Common for All] Clicking on Submission icon won't go to the correct URL

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#240]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[tracks][design]=true&filter[subtracks][0]=Logo%20Design&bucket=past

- From the list click on Submissions icon

Actual Result(s)
-----------------------------------------------------------------
- page redirects to https://www.topcoder.com/challenge-details/30052440/?type=design#viewRegistrant

Expected Result(s)
-----------------------------------------------------------------
- URL must http://community-app.topcoder.com/challenges/30052440/?type=design#submissions
- Also when user goes to the page 'ubmissions' tab must be selected

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
https://www.screencast.com/t/jLl3rh60a

**Comment by birdofpreyru** [comment]
Accepted, 1 point. Basically the same as #239 just for another icon
