### ISSUE TITLE
New Nav- move Contentful content over to new navigation UI

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#2400]
**Describe the bug**
Not all content pages have the new nav UI but still Contentful navigation components

**To Reproduce**
1. Go to https://beta-community-app.topcoder.com/members/TonyJ 

2. Click on any pages under Tracks and Community topbar navigation
![image](https://user-images.githubusercontent.com/47536078/58823429-83b68b80-85ee-11e9-88d2-05894bd0ed3d.png)
![image](https://user-images.githubusercontent.com/47536078/58823779-5cac8980-85ef-11e9-859e-f15fac5e9f37.png)

4. It takes you to pages that do not have the new navigation but are using the previous Contentful navigation components
![image](https://user-images.githubusercontent.com/47536078/58823833-7bab1b80-85ef-11e9-8e0d-01a3cf39b472.png)

**Expected behavior**
These content pages should also have the new nav UI.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Oanh-and-only-Oanh** [comment]
@kkartunov, do you have bandwidth for this?

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh yes. As we spoke on Slack this will be delayed until new navi reactJS development completes.

**Comment by kkartunov** [comment]
@luizrrodrigues please notify when new navi components ready so we can begin this one...thanks!

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @kkartunov This looks like issue reported here: https://github.com/topcoder-platform/community-app/issues/2453

This was problem with links redirect to other domain.

Fix already merged and can see here:
https://test-community-app.topcoder-dev.com/challenges

https://gyazo.com/f13a61070dda6b01ff5d961afbf79048

**Comment by kkartunov** [comment]
@nithyaasworld this is not closed. Please, leave it to us. Thanks
