### ISSUE TITLE
Beta-community-app: Challenge-listing-page loading speed has to be improved

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2404]
**To Reproduce**
1. Go to https://beta-community-app.topcoder.com/challenges?
2. Check the page load speed

**Actual behavior**
It takes 5 to 6 seconds to load the Challenge-listing-page in beta-community-app, which is same as the load-time of the same page in Production.

**Expected behavior**
Load time has to be improved.

**Comment by sushilshinde** [comment]
@ThomasKranitsas please ignore for now, I will chat with @nithyaasworld

**Comment by nithyaasworld** [comment]
Closing this
