### ISSUE TITLE
$20 | New Nav: User Menu popup is overlapping with the Sub Community

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2405]
**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. Login
3. Click on the user name present at the right side of the new nav
4. Check the User popup 

**Actual behavior**
Sub  Community is overlapping with the User Popup

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/58901903-b6ac6c80-871f-11e9-9fbd-be58bac21b17.png)

**Comment by iversonLv** [comment]
Can I take this?

**Comment by PrakashDurlabhji** [comment]
even I wanted to take it, confused whether it is actually open?
@luizrrodrigues

**Comment by luizrrodrigues** [comment]
@iversonLv sure.

@PrakashDurlabhji issues with nav_OpenForPickup

**Comment by iversonLv** [comment]
@luizrrodrigues I don't have permission set assignee and change label.
Please help with changing

Thanks.

**Comment by luizrrodrigues** [comment]
Assigned to @iversonLv

**Comment by luizrrodrigues** [comment]
I'll do this manually, maybe I can't assigned in right way too, but I'll
add a comment "Assigned to... "

**Comment by luizrrodrigues** [comment]
@iversonLv Any status on this?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues can i give it a try if iverson is busy.

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji If @iversonLv no reply in 2h from, yes.

**Comment by iversonLv** [comment]
@luizrrodrigues I have raise the PR? 
https://github.com/topcoder-platform/community-app/pull/2589

**Comment by iversonLv** [comment]
4 Days ago.
Maybe I need comment here the PR number here, sorry for inconvenient.

**Comment by luizrrodrigues** [comment]
@iversonLv Ah sorry, I don't see this. Thanks :)
