### ISSUE TITLE
$50 | New Nav: Business is not displayed. Only Work is displayed

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2406]
**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. **Do not login**
3. Check the new nav

**Actual behavior**
Only Work is present. Business is not present

**Expected behavior**
Business should be present and expanded by default.

**Screenshots**

![image](https://user-images.githubusercontent.com/5114190/58905637-d6e02980-8727-11e9-84bf-1984e9f44961.png)

**Comment by PrakashDurlabhji** [comment]
@luizrrodigues i am taking this

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues is it ok to work on it nowitself? or it was supposed to be taken later? though i have already started working

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues on which branch?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji feature-new-nav

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues @ThomasKranitsas 
1.in bussiness menu, all sections have same submenu as of now.
2.So currently in business menu, for just 1 section i have added submenus and for other section there are no submenu as it is irrelevant for me to add because it is going to change anyway.
3. I can add all submenus properly, kindly provide the data for href and title each.

PR at https://github.com/topcoder-platform/community-app/pull/2590

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please check feedback in PR #2590

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji What status on this one?

I'll give you more **12h** to fix issue related in feedback.

Thanks.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues on this actively.

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Status?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues sometime

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please let me know what is your progress on this one or if we can open for pickup.

Thanks.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues please dont open it, update in mins

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues it is working well now. PR updated
https://github.com/topcoder-platform/community-app/pull/2590

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji I'll still seeing the issue: 
[video.zip](https://github.com/topcoder-platform/community-app/files/3303006/video.zip)

Please let me know if you can fix this in next hours, or need need open to pickup this one.

We need close issue today ASAP.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues i am online and update you in sometime, it is working well i will also paste video for verification

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues
1. are you using Mac?

2. this issue should exist even before merging my PR.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues verification video
[Screencast 2019-06-19 01:27:51.mp4.zip](https://github.com/topcoder-platform/community-app/files/3303203/Screencast.2019-06-19.01.27.51.mp4.zip)

**Comment by luizrrodrigues** [comment]
1. Yes, I'm on Mac

2. This, I don't see this error before, check: 
[video.zip](https://github.com/topcoder-platform/community-app/files/3303227/video.zip)

Looks working well in your video, which browser and OS?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues 
1.actually nothing is done specific as such that it distorts ui, u can observe PR is raised only for community-app and not navigation component.

2.i am on ubuntu 16.04 and Chrome

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues tests are passed too.

now stuck at mac issue? what to do? I do not wish to lose efforts on this.

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Thanks for fix tests issues.

So I found what happing, is just in Safari.

Check secondary menu:
![image](https://user-images.githubusercontent.com/7029641/59719459-c6818180-91f2-11e9-8ea2-5965e8cb0947.png)

When this is collapsed, using `display: flex` and `width: 0`, this not working in Safari, browser will overwrite `width: 0` with `display: flex`.

So I think the solution is remove `display: flex` when collapsed and add when expanded.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues yes working on it

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Any luck?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please let me know if you'll able to fix Safari issue.

Thanks.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues trying it as i do not wish to lose my efforts.

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Thanks

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Can open for pickup?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Please give me a status about this one ASAP.

**Comment by r0hit-gupta** [comment]
@luizrrodrigues May I pick this up?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues i have a solution, let me give a try else i will directly assign to rohit

**Comment by r0hit-gupta** [comment]
@PrakashDurlabhji @luizrrodrigues this is not fair. What is the point of rules if they are not going to be enforced? It's been more than 24 hours since last update. You should give others a chance.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues Is mac issue included in this scope? Can i get something for my efforts? as issue stated business to be added which was already met long back.Additional requirements later make it really difficult to complete this issue.Request you to think on this aspect as scope was met to my knowledge.Thank you.

**Comment by luizrrodrigues** [comment]
Sorry delay guys.

@r0hit-gupta request to pick this before when this is Open, so yes @r0hit-gupta you can work on this.

@PrakashDurlabhji Safari was a bug related 4 days ago, give you a possible solution and try to get status always, but no reply, so just open for pickup. I see your progress on this, but work in Safari is required (this not about add additional requirements later, you fix need work in all browsers). 

I'm trying to be fair here.

@r0hit-gupta You available to work on this? If yes, you'll work from zero or will reuse what @PrakashDurlabhji  is done so far?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues the solution which i gave to show "business" is the only possible solution, anyone who creates a PR has to use my logic, just to solve MAc issue some code needs to be added

**Comment by r0hit-gupta** [comment]
@luizrrodrigues yes I am available to work on this. There is currently only one structured way of adding new links and anyone who wants to add new links have to do it in the same way just like Prakash did.

**Comment by r0hit-gupta** [comment]
@luizrrodrigues PRs at https://github.com/topcoder-platform/community-app/pull/2658 and https://github.com/topcoder-platform/navigation-component/pull/34 . Please review, thanks.

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues request you to split the amount if possible, to display bussiness option, and another to make it work on Mac.
so i get paid for my efforts atleast, for adding business option and making testcases work.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Looks like break somethings of latest pushes/PR.

Missing secondary menu of **Community** and looks back **Community** changed to **Work**
![image](https://user-images.githubusercontent.com/7029641/60035483-52782b00-9683-11e9-912f-d68ca59cd548.png)

Existing:
![image](https://user-images.githubusercontent.com/7029641/60035655-bf8bc080-9683-11e9-819d-0d63ce42ee3e.png)

Please make sure to work with latest commits in branch `feature-new-nav` and if needed make some merge, make sure to no break anything from existing fixes.

Let me know if you have any question.

Thanks.

**Comment by r0hit-gupta** [comment]
@luizrrodrigues fixing it up.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Any status on this one?

**Comment by luizrrodrigues** [comment]
@r0hit-gupta I just applied my approach share here: https://github.com/topcoder-platform/community-app/issues/2406#issuecomment-503313550 and working fine.

**Comment by r0hit-gupta** [comment]
@luizrrodrigues I had already fixed that issue https://github.com/topcoder-platform/navigation-component/pull/34. Fixing the menu items.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta This not working in Safari, still showing horizontal scroll when reduce window size.

**Comment by r0hit-gupta** [comment]
@luizrrodrigues so looks like you solved everything 😄. If there is anything more to be done, please let me know. Thanks.

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Yeah, working fine :)
Thanks for check this one.
More issue is coming soon :)

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues is prize splitted for this one?

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Nope, just use your approach + my fix to Safari.
