### ISSUE TITLE
[All the links] Click on navigation links loads a new page in the same tab

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2419]
1. Open the application and login using valid credentials
2. Click Menu > Work > Track > QA

**Actual:** Click on navigation links loads a new page in the same tab

**Expected:** The navigation is designed to load a page on a click. Each click on navigation links should load a new page.

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Chrome 75.0.3770.80 (Official Build) (64-bit)

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/59123042-e925b780-8921-11e9-977c-7e134b8428e6.png)

**Comment by vic-tian** [comment]
I'm confused what is the bug reported here. Each pages should be loaded on clicking on the new navigation menu. What is the wrong behavior, can you please elaborate? Thanks

**Comment by codejamtc** [comment]
@vic-tian 

![image](https://user-images.githubusercontent.com/42398485/59133533-f9e42680-893d-11e9-89a4-4af757fd5926.png)

https://docs.google.com/document/d/1-ExQxNCncwH8YNcuFl-bq0PwteBoaoefPeo-BBGw_XQ/edit

**Comment by vic-tian** [comment]
no, it means that unlike our current navigation, everything should happen on click, not on hover. The pages should be loading in the same window, not in a new. Thanks for clarifying this.
