### ISSUE TITLE
[$20] - N/A is not displayed for empty checkpoint responses

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#242]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30052058/?type=design

- Expand a checkpoint

- Go to https://www.topcoder.com/challenge-details/30052058/?type=design#checkpoints

- Expand a checkpoint

Actual Result(s)
-----------------------------------------------------------------
- N/A is not displayed for empty checkpoint responses

Expected Result(s)
-----------------------------------------------------------------
- N/A must display for empty checkpoint responses

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![39](https://user-images.githubusercontent.com/4592712/29695103-610b381c-895e-11e7-9168-d0bf8c3ad830.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point. Let's show something like `Empty feedback` in a gray color in such case.
