### ISSUE TITLE
There is no Notifications button on left side of User Name

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2420]
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Check the Notifications button on left side of User Name

**Actual behavior**
There is no Notifications button on left side of User Name

**Expected behavior**
Notifications button should be on left side of User Name

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/59123196-56653700-897a-11e9-8c36-c663a48888e6.png)

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment]
Notification part is not yet implemented. So anything related to that is not part of this Bug Hunt.
