### ISSUE TITLE
$ symbol shown on the Community Statistics page

### ISSUE THREAD

**Issue by DonPablito** [topcoder-platform/community-app#2429]
**Describe the bug**
$ symbol shown in front of text on Community Statistics page

**To Reproduce**
1. Go to Work from navigation bar
2. Click on Community> Statistics
3. Scroll down to General Statistics

**Actual Behaviour**
$ symbol shown before the text.

**Expected behavior**
**$** symbol should not be shown in front of text.

**Screenshots**
<img width="1280" alt="Screenshot 2019-06-07 at 11 19 27 PM" src="https://user-images.githubusercontent.com/29794211/59123758-a7295f80-897b-11e9-8480-b6fb4c3ca4b7.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Out of scope

**Comment by nithyaasworld** [comment]
Please read the challenge details and documents provided in the "Code documents" forum to understand the scope of this Bug Hunt.
