### ISSUE TITLE
[$30] - 4 places displayed in the new challenge details page but 3 in old page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#243]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30052058/?type=design

- Check the Prices > 4th $50

- Go to https://www.topcoder.com/challenge-details/30052058/?type=design#checkpoints

- Check the Prices > 4th None

Actual Result(s)
-----------------------------------------------------------------
- 4 palces displayed in the new challenge details page but 3 in old page

Expected Result(s)
-----------------------------------------------------------------
- Must display 3 places

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![40 2](https://user-images.githubusercontent.com/4592712/29695192-f88617de-895e-11e7-8ade-7a2c94c964e1.jpg)
![40 1](https://user-images.githubusercontent.com/4592712/29695193-f8883be0-895e-11e7-94fa-6e2d7f9a9837.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points. It looks to me, that new challenge details page mixes the checkpoint prize into the main place prizes as well. We should ensure that it is handled correctly.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru service bug. check prize in v2 and prizes in v3 api.
https://api.topcoder.com/v3/challenges/?filter=id%3D30052058
https://api.topcoder.com/v2/design/challenges/30052058
