### ISSUE TITLE
Already opened navigation tab should not be clickable.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2431]
**Describe the bug**
Already opened navigation tab is clickable.

**To Reproduce**
1. Open  https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on any Navigation tab ex- "Compete"
4. Navigation Suboption opened.
5. Again Move the mouse to same tab.
6. Mouse pointer changed to hand sign .

**Expected behavior**
Already opened navigation tab should not be clickable.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Computer
 - OS: Windows 10
 - Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
covered as part of https://github.com/topcoder-platform/community-app/issues/2403
