### ISSUE TITLE
"All challenges" page can't open 

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2433]
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
2. Try to open Settings page with url: https://test-community-app.topcoder-dev.com/settings/profile
3. Then Click Work menu
4. Click on "Compete" item 
5. Click on "All challenges" item and observe page

### Expected Result: ###
"All challenges" page open correctly.

### Actual Result: ###
URL is changed to "challenges" but Content still stay "Settings" page.

### Screenshots or screencast: ###

See comment

### Browser Information: ###

Google Chrome 74.0 on desktop window 10

**Comment by HongHT** [comment]
![3](https://user-images.githubusercontent.com/26895101/59126308-f9c04700-898e-11e9-9a6d-0ab1a1528b03.png)

**Comment by nithyaasworld** [comment]
@luizrrodrigues Please confirm if we are covering this as part of any other bug. As far as I searched, there is no bug logged for navigating from https://test-community-app.topcoder-dev.com/settings/profile screen.

**Comment by luizrrodrigues** [comment]
@nithyaasworld this one is duplication of #2395

**Comment by luizrrodrigues** [comment]
Duplicate of #2395
