### ISSUE TITLE
Collapse icon is not displayed when User-Menu is in Open state

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2436]
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click on User Name handle

**Actual behavior**
Collapse icon is not displayed when User-Menu is in Open state

**Expected behavior**
Collapse icon should be displayed when User-Menu is in Open state

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/59124276-e86e3f00-897c-11e9-877d-58d01185b226.png)

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment]
![image](https://user-images.githubusercontent.com/5114190/59163580-7d5d6d80-8b20-11e9-8424-dee0815543a2.png)

**Comment by luizrrodrigues** [comment]
@rashmi73 Any status in this one?

**Comment by LieutenantRoger** [comment]
Not able to reproduce, please double check

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Thanks for check. Looks like already fixed in another issue.
