### ISSUE TITLE
Notification page displays a 'Log Out' option

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2437]
![image](https://user-images.githubusercontent.com/42398485/59124244-d19bfe00-8924-11e9-8b95-9eab8839679b.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon
4. Tap Notifications

**Actual:** Notification page displays a 'Log Out' option

**Expected:** Should remove the logout option

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by codejamtc** [comment]
Expected: Should remove the logout option, to do that we have to display the notification on the entire screen

**Comment by nithyaasworld** [comment]
I think we should hide the Notification in mobile view until the Notification-part is implemented.

**Comment by nithyaasworld** [comment]
Notification will be removed and Switch to Business option will be displayed as part of https://github.com/topcoder-platform/community-app/issues/2450
