### ISSUE TITLE
Should have space between title and arrow icon on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2438]
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
2. Then click 'Work' menu
3. Click on "Compete" item and observe

### Expected Result: ###
Should have space between title and arrow icon

### Actual Result: ###
Haven't space between title and arrow icon

### Screenshots or screencast: ###

See comment

### Browser Information: ###
Oppo F7, android 8.1
Google Chrome on mobile

**Comment by HongHT** [comment]
![6](https://user-images.githubusercontent.com/26895101/59126787-1741e080-8990-11e9-8e63-d5c6b0611fd8.png)

**Comment by nithyaasworld** [comment]
This is similar to https://github.com/topcoder-platform/community-app/issues/2432 

![image](https://user-images.githubusercontent.com/5114190/59163618-f8bf1f00-8b20-11e9-9ec7-45ffaf903ef5.png)

**Comment by luizrrodrigues** [comment]
Duplicate of #2432
