### ISSUE TITLE
Back button is not displayed on the Notification page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2439]
![image](https://user-images.githubusercontent.com/42398485/59124386-1c1d7a80-8925-11e9-92e0-075dd8f50b54.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon
4. Tap Notifications
5. Tap Top left corner of the notification

**Actual:** Back button is not displayed on the Notification page

**Expected:** Should show the back button

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by nithyaasworld** [comment]
Notification is not part of this bug hunt.
