### ISSUE TITLE
Can't select the winner tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#244]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30052058/?type=design

- Click 'Winner' tab

Actual Result(s)
-----------------------------------------------------------------
- Can't select the winner tab

Expected Result(s)
-----------------------------------------------------------------
- Must able to select the winner tab

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![41](https://user-images.githubusercontent.com/4592712/29695226-2c7346ac-895f-11e7-8aea-43afad0cc0ad.jpg)

**Comment by birdofpreyru** [comment]
Looks like a dublicate of #228 for me
