### ISSUE TITLE
The title on submenu can't show immediately on mobile in the first time

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2440]
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
2. Try to click on menu icon on the top left
3. Click on items on submenu and observe 

### Expected Result: ###
The title on submenu should show immediately on mobile.

### Actual Result: ###
The title on submenu can't show immediately on mobile in the first time.

### Screenshots or screencast: ###

See comment

### Browser Information: ###
Oppo F7, android 8.1
Google Chrome version latest on mobile

**Comment by HongHT** [comment]
![7](https://user-images.githubusercontent.com/26895101/59126801-23c63900-8990-11e9-8050-d373599479ee.png)

**Comment by LieutenantRoger** [comment]
@luizrrodrigues  

Could you reproduce this ? 
I tried on an `Honor 6x Phone` with Android `8.0.0`,  with Chrome version: `76.0.3809.111` but can't reproduce this.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger I'll re check and let you know

**Comment by LieutenantRoger** [comment]
up

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Thanks for check.
Looks like this was fixed.

**Comment by nithyaasworld** [comment]
Cannot reproduce in production too.

**Comment by luizrrodrigues** [comment]
@nithyaasworld Please add QA Pass here

**Comment by SathyaJayabal** [comment]
Closing this as it seems not reproducible
