### ISSUE TITLE
'Notification Settings' button is not working on the Notification page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2441]
![image](https://user-images.githubusercontent.com/42398485/59124462-4838fb80-8925-11e9-902f-ac34cc9d46f2.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon
4. Tap Notifications
5. Tap 'Notification Settings' button

**Actual:** 'Notification Settings' button is not working on the Notification page

**Expected:** Should go to the Notification settings page

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by nithyaasworld** [comment]
Notification is not part of this bug hunt.
