### ISSUE TITLE
"Competitive programming" sub menu available in both the tab "Compete" and "Tracks"

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2442]
**Describe the bug**

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on Navigation tab "Compete" and check sub menu
4. Click on Navigation tab "Tracks" and check sub menu
5. Look for sub menu in both tab
6. "Competitive programming" sub menu available in both the tab.

**Expected behavior**
"Competitive programming" should be present in only one navigation tab

**Screenshots**

**Desktop (please complete the following information):**
Device: Computer
OS: Windows 10
Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by nithyaasworld** [comment]
This is not part of navigation component. This is how it is present now in Production.
