### ISSUE TITLE
Hovering on MM icon isn't showing the full name of Marathon match

### ISSUE THREAD

**Issue by DonPablito** [topcoder-platform/community-app#2443]
**Describe the bug**
When the user hovers over the Cd icon beside the Challenges name the information box is opened showing the user further information about the type of challenge it is. This isn't happening with hovering over MM challenges

**To Reproduce**
1. Open the app and Login.
2. Click on Work> Compete> All Challenges
3. Hover over any MM marked challenge.
4. No information is shown about the Marathon match

**Expected behavior**
Dialog box with all the information should be shown to the user.

**Screenshots**
<img width="1278" alt="Screenshot 2019-06-07 at 11 34 01 PM" src="https://user-images.githubusercontent.com/29794211/59124463-4b5fd600-897d-11e9-9a23-4852b18a788e.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Out of Scope
