### ISSUE TITLE
Topcoder icon and Work menu doesn't align center horizotal on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2444]
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
3. Try to click on menu icon on the top left
4. Then observe Topcoder icon and Work menu

### Expected Result: ###
Topcoder icon and Work menu should align center horizotal on mobile. 

### Actual Result: ###
Topcoder icon and Work menu doesn't align center horizotal on mobile. 

### Screenshots or screencast: ###

See comment

### Browser Information: ###

Oppo F7, android 8.1
Google Chrome version latest on mobile

**Comment by HongHT** [comment]
![5](https://user-images.githubusercontent.com/26895101/59126742-0002f300-8990-11e9-932b-0857db320c72.png)

**Comment by nithyaasworld** [comment]
Duplicate
