### ISSUE TITLE
Profile drop down close button is not visible

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2445]
![image](https://user-images.githubusercontent.com/42398485/59124698-03619480-8926-11e9-8685-78e9eb8596ec.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon

**Actual:** Profile drop down close button is not visible

**Expected:** Should display the close button

**Reproducibility Rate:** 3/3

**Environment:** iPhone 5S, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment]
![image](https://user-images.githubusercontent.com/5114190/59163678-ceba2c80-8b21-11e9-8ce9-4ed0d511b0b2.png)

**Comment by nithyaasworld** [comment]
Duplicate of https://github.com/topcoder-platform/community-app/issues/2398
