### ISSUE TITLE
Bio goes out of the screen area

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2446]
![image](https://user-images.githubusercontent.com/42398485/59124743-1bd1af00-8926-11e9-9f06-b11d1e6dad6c.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon

**Actual:** Bio goes out of the screen area

**Expected:** Should display the bio within the page area

**Reproducibility Rate:** 3/3

**Environment:** iPhone 5S, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment]
similar to https://github.com/topcoder-platform/community-app/issues/2435
