### ISSUE TITLE
Only Notification page title is visible when opening

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2449]
![image](https://user-images.githubusercontent.com/42398485/59124831-56d3e280-8926-11e9-85a5-811be6887b4a.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Profile icon
4. Tap Notifications

**Actual:** Only Notification page title is visible when opening

**Expected:** Should display the title and the description. There is room to display the title and the description. Scroll the section up and you can see the title and description clearly

**Reproducibility Rate:** 3/3

**Environment:** iPhone 5S, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment]
Notification is not in scope for this Bug hunt.
