### ISSUE TITLE
[$30] - green mark missing 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#245]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058577/?type=design

- check CHALLENGE TERMS section

Actual Result(s)
-----------------------------------------------------------------
  green mark not visiable 

Expected Result(s)
-----------------------------------------------------------------
  should show green mark 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-community-app topcoder com 2017-08-25 06-50-15](https://user-images.githubusercontent.com/3225433/29695680-e254fb62-8961-11e7-825f-fdf3ff11c4c1.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

When this element was done, competitors noted that for past challenges API does not return the status of challenge terms agreements when request is done with user's credentials. So, if user has not been registered for past challenge, the check is just ignored. I guess, there might be a way to still handle it correctly, using v2 api - let's fix it, if possible.

**Comment by daft300punk** [comment]
Is something wrong with challenge details page? I get Unhandled promise rejection -> Cannot read property 'track' of undefined in the terminal console. The browser page just keeps loading. Is some api not returning as expected? I'm in develop branch.

**Comment by birdofpreyru** [comment]
@daft300punk Hm... I've just briefly checked remotely deployed versions, seems to be working both in prod and dev.

**Comment by birdofpreyru** [comment]
@ajefts We use v2 api to handle terms. If called without auth tokens, it tells what terms cover the challenge; if tokens are provided, for active challenges, it also tells whether user has agreed to each terms or not. However, for past challenges calling it with tokens results in an error response, and thus we don't have a way to check whether user has agreed or not for terms.

**Comment by birdofpreyru** [comment]
In the end, it was decided just to remove these checkmarks from the sidebar altogether, thus not an issue anymore.
