### ISSUE TITLE
No way to identify already visited menus 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2451]
**Describe the bug**

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on any Navigation tab ex- "Tracks" then click on QA
4. QA page opens.
5. CLick on Browser back button.
6. Click on Navigation tab "Tracks"
7. There is no indication that "QA" was already visited

**Expected behavior**
Already visited menus should be identifiable with other menus 

**Screenshots**

**Desktop (please complete the following information):**
Device: Computer
OS: Windows 10
Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Not in design
