### ISSUE TITLE
Filtering challenges by Date Range isn't working

### ISSUE THREAD

**Issue by DonPablito** [topcoder-platform/community-app#2452]
**Describe the bug**
The user applies a  specific Date Range filter from the filter menu but the challenges aren't filtered accordingly

**To Reproduce**
1. Open the app and Login
2. Click on 'Work> Compete> All challenges
3. Click on Filter and select some Date Range as the filter
4. The Challenges are reloaded but still, some challenges are shown which fall out of the date range

**Expected behavior**
Only challenges falling in Date Range should be shown.

**Screen recording**
https://www.screencast.com/t/LdBH46Zw3yW

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Out of Scope
