### ISSUE TITLE
$50 | Common > Navigation menu go to other domain when we access the pages via the menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2453]
![image](https://user-images.githubusercontent.com/42398485/59125186-39ebdf00-8927-11e9-96d7-16e57e82a010.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Tap Menu > Work > Tracks > QA

**Actual:** Navigation menu changes to a different one when we access the pages via the menu

**Expected:** All the pages should have the same navigation

https://docs.google.com/document/d/1-ExQxNCncwH8YNcuFl-bq0PwteBoaoefPeo-BBGw_XQ/edit - Bullet 5 and 6

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Chrome 75.0.3770.80 (Official Build) (64-bit)

**Comment by luizrrodrigues** [comment]
@codejamtc @nithyaasworld What is changed here is the domain:

https://test-community-app.topcoder-dev.com 
to
https://www.topcoder-dev.com/challenges

<img width="959" alt="Screen Shot 2019-06-09 at 17 59 03" src="https://user-images.githubusercontent.com/7029641/59164218-8cbcc680-8ae0-11e9-89a9-c88f0202fe17.png">

So need make sure links have right path/domain.

**Comment by gets0ul** [comment]
Is this open? Can I work on this?

**Comment by luizrrodrigues** [comment]
> Is this open? Can I work on this?

Yep, this is open.

**Comment by luizrrodrigues** [comment]
Assigned to @gets0ul

**Comment by gets0ul** [comment]
@luizrrodrigues 
So for example, from https://test-community-app.topcoder-dev.com/challenges  
the QA track should be  
https://test-community-app.topcoder-dev.com/community/qa  
instead of  
https://www.topcoder-dev.com/community/qa  
  
Is that correct?

**Comment by luizrrodrigues** [comment]
@gets0ul Yes, that is right.

**Comment by gets0ul** [comment]
MR is submitted. I can't change the label to Assigned.  
Thanks

**Comment by luizrrodrigues** [comment]
@gets0ul Changed, thanks.
