### ISSUE TITLE
Collapse icon is not displayed when Sub-items menu is open

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2454]
**Pre-Requisite**

**Steps to Reproduce**

1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click on Hamburger Menu(Left side)-->Work-->Tracks
4. When Sub-items menu is open, check the icon on right side of the "Tracks" header 

**Actual behavior**
Collapse icon is not displayed when Sub-items menu is open

**Expected behavior**
Collapse icon should be displayed when Sub-items menu is open

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/59125258-66cbe080-897f-11e9-9e41-7e080bce6d67.png)

**Environment :**
Samsung S7 Edge || Android 8.0.0 || Chrome Browser
 
**Rep

**Comment by nithyaasworld** [comment]
Thanks @kiranmaroju this will be fixed as part of https://github.com/topcoder-platform/community-app/issues/2432
