### ISSUE TITLE
Underscore line below the sub menu did not appear when hovering mouse to sun menu

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2455]
**Describe the bug**

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on any Navigation tab ex- "Tracks"
4. Hover mouse "Data Science"
5. Underscore line below the "Data Science" did not appear when hovering mouse to sun menu

**Expected behavior**
Underscore line should appear as per design when hover mouse on sub menu

**Screenshots**

**Desktop (please complete the following information):**
Device: Computer
OS: Windows 10
Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by agnelvishal** [comment]
Same as https://github.com/topcoder-platform/community-app/issues/2430 which tells hover state is not displayed
