### ISSUE TITLE
$10 | 'Work' is not highlighted even though subsection selected

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2457]
**Reproduction steps:**

1. Open the test URL and log in
2. Click on the hamburger menu at the top left corner
3. Click on Work
4. Click on Community
5. Click on the hamburger menu at the top left corner
6. Observe which items are highlighted 

**Expected result:** 
'Work' navigation item stays highlighted if it's subsection is selected

**Actual result:** 
'Work' navigation item is not highlighted even though subsection selected

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s: Chrome

**Screenshot:**

![screenshot3](https://user-images.githubusercontent.com/45698232/59125575-8fb88b00-8917-11e9-92e2-37b2ca86706f.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
@alexandreeva What highlight are you expecting? I see an upward arrow under the "Work" which indicates the user is currently in Work.

**Comment by alexandreeva** [comment]
@nithyaasworld I assumed 'Work' would be green as shown on this marvel app screen

![Capture](https://user-images.githubusercontent.com/45698232/59207200-71db6800-8b5b-11e9-9f4b-86108b805f60.JPG)

**Comment by LieutenantRoger** [comment]
MR: https://github.com/topcoder-platform/navigation-component/pull/115

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Not working:

![image](https://user-images.githubusercontent.com/7029641/72655642-96f74b00-3974-11ea-8023-5dfc9da4bf13.png)

**Comment by LieutenantRoger** [comment]
New fix is pushed here: https://github.com/topcoder-platform/navigation-component/pull/115

**Comment by nithyaasworld** [comment]
Verified in test env.

![image](https://user-images.githubusercontent.com/5114190/72891700-d342f680-3d3a-11ea-98b6-c6332f795d40.png)

**Comment by LieutenantRoger** [comment]
Hi, Is this ticket deployed but not release payment ?

**Comment by macs054** [comment]
Verified in Beta
![87604555_178537603570852_7163556634235502592_n](https://user-images.githubusercontent.com/1199534/75417906-20833b00-596d-11ea-8a57-bc853df0a6f6.png)

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="506" alt="Screenshot 2020-02-28 at 9 27 45 AM" src="https://user-images.githubusercontent.com/58783823/75509182-a1454400-5a0c-11ea-8f48-419106166f7a.png">
