### ISSUE TITLE
Work Submenu Missing

### ISSUE THREAD

**Issue by VanitaW** [topcoder-platform/community-app#2458]
***Reproduction Steps:***
1.  In a browser, go to  https://test-community-app.topcoder-dev.com/challenges
2.  Click on Work
3. Observe that a submenu does not appear.

***Expected Results:***
A submenu with the following options:  Topcoder Community, Development, Analytics &AI, QA, 
Competitive Programming, Topcoder Open per design specs.

***Actual Results:***
No submenu appears.

***Screenshots or screencast:***

![Nosubmenus](https://user-images.githubusercontent.com/12702517/59125490-1ecd9f00-8928-11e9-8255-d00905742f05.png)

***Device/OS Information:***
 - OS: macOS
 - Browser Safari
 - Version 12.1.1

**Comment by nithyaasworld** [comment]
Function of Work is covered here: https://github.com/topcoder-platform/community-app/issues/2396#issuecomment-498343703
