### ISSUE TITLE
Menu has occupied full page view in Mobile

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2459]
**Pre-Requisite**

**Steps to Reproduce**

1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click on User Name icon on Right side

**Actual behavior**
Menu has occupied full page view in Mobile

**Expected behavior**
Menu should not occupy full page, user should be able to view content existing behind the menu

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/59125613-7566c780-8980-11e9-832e-951ae664c56c.png)

**Environment :**
Samsung S7 Edge || Android 8.0.0 || Chrome Browser

**Comment by nithyaasworld** [comment]
That's the short bio of the user and there are already 2 bugs logged around this part.
