### ISSUE TITLE
User menu is not displayed as expected

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2461]
**Reproduction steps:**

1. Open the test URL and log in
2. Open the user menu at the top right corner
3. Observe

**Expected result:** 
The user menu is displayed as shown in the marvel app screen

**Actual result:** 
The user menu is displayed as if not designed yet

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome

**Screenshot:**

![screenshot2](https://user-images.githubusercontent.com/45698232/59125980-be833100-8918-11e9-9fed-ef000f5c01b3.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
Related bugs: https://github.com/topcoder-platform/community-app/issues/2450 and https://github.com/topcoder-platform/community-app/issues/2398
