### ISSUE TITLE
Drop down arrow is too close to the title

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2464]
**Reproduction steps:**

1. Open the test URL and log in
2. Open the hamburger menu at the top left corner
3. Click on Work > Compete
4. Observe the placement of the drop down arrow

**Expected result:** 
There is a space between the title of a section and the drop down arrow as shown in the marvel app screens

**Actual result:** 
There is no space between the title of a section and the drop down arrow

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome 7

**Screenshot:**

![screenshot4](https://user-images.githubusercontent.com/45698232/59126233-6862bd80-8919-11e9-83d4-1fee67572706.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
duplicate
