### ISSUE TITLE
Edge Browser: Current Sub-Item is not underlined 

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2465]
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Clikc on Work -->Tracks

**Actual behavior**
Current Sub-Item is not underlined 

**Expected behavior**
Current selected sub-item should be underlined as specified in spec document(https://marvelapp.com/89423f8/screen/54465717)

**Screen shots/video**
![ApplicationFrameHost_4mxwcG0gU0](https://user-images.githubusercontent.com/6736067/59126135-ef4b8080-8981-11e9-92f2-88e7c025d6ba.png)

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: MS Edge v42

 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment]
duplicate
