### ISSUE TITLE
Profile icon is missing on the profile drop down

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2466]
![image](https://user-images.githubusercontent.com/42398485/59126327-70772900-892a-11e9-8778-08134528ceb3.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click Menu > Profile avatar

**Actual:** Profile icon is missing on the profile drop down

**Expected:** Should display the profile icon

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** IE11

**Comment by nithyaasworld** [comment]
similar to https://github.com/topcoder-platform/community-app/issues/2426
