### ISSUE TITLE
UI Issue on the sub-menu section

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2467]
![image](https://user-images.githubusercontent.com/42398485/59126426-b207d400-892a-11e9-92fb-7eb6080aba91.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click Menu > Work > Compete

**Actual:** UI Issue on the sub-menu section

**Expected:** Should remove the extra line

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Microsoft Edge 44.17763.1.0

**Comment by nithyaasworld** [comment]
duplicate
