### ISSUE TITLE
Active state Underscore line movement happens when switching navigation tab

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2468]
**Describe the bug**
Active state Underscore line movement happens when switching navigation tabs 

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on WORK
4. Click on "Track" or switch to other tab ex- "Compete"
5. Active state Underscore line movement happens. 
6. This movement is not desirable 

**Expected behavior**
Active state Underscore line movement should not happen when switching tabs

**Screenshots**

**Desktop (please complete the following information):**
Device: Computer
OS: Windows 10
Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
As designed.
