### ISSUE TITLE
Close button in the user menu is not displayed in portrait mode

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2469]
**Reproduction steps:**

1. Open the test URL and log in 
2. Open the user menu at the top right corner
3. Switch to landscape mode and observe the close button
4. Switch back to portrait mode and observe if there is a close button

**Expected result:** 
The close button in user menu is displayed in both portrait and landscape mode

**Actual result:** 
The close button in the user menu only appears in landscape mode; the user is unable to close the menu in portrait mode

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome 

**Screenshot:**

![screenshot2](https://user-images.githubusercontent.com/45698232/59126646-6cdba600-891a-11e9-8b9f-9ccc60e1cef1.jpg)

![screenshot2 2](https://user-images.githubusercontent.com/45698232/59126651-706f2d00-891a-11e9-8ed3-2a4b68a09dff.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
covered as part of https://github.com/topcoder-platform/community-app/issues/2398
