### ISSUE TITLE
Main page menu is not as expected

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2470]
**Describe the bug**
In main page menu is not displayed as expected.

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Login with valid user name and password

**Expected behavior**
Main page menu should be as expected

**Screenshots**
![chrome_9NnKnfZaIZ](https://user-images.githubusercontent.com/5110867/59126571-ffb02b00-8982-11e9-98b3-7899b78594a0.png)

**Desktop (please complete the following information):**
 - OS: -Window7
 - Browser - Chrome
 - Version -7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
If you mean "Business" is not displayed, it is already reported here: https://github.com/topcoder-platform/community-app/issues/2406
