### ISSUE TITLE
No minimum characters set for first name and last name in Edit profile

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2471]
**Describe the bug**

*
![Screenshot_20190608-000853](https://user-images.githubusercontent.com/41059603/59126756-751bfb80-8983-11e9-96f1-2299b05aa389.png)
*To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click on menus - Settings - Profile
4. Edit profile by entering first name as single character and last name as single character.

**Expected behavior**
Application should display minimum characters to be entered for first name and last name.

**Screenshots**
Attached the screenshot.

**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
 - Device: Nokia 8.1
 - OS: Android 9
 - Browser : Chrome
 - Version : 75.0.3770.67

**Additional context**

**Comment by nithyaasworld** [comment]
If you are reporting this bug as part of Bug Hunt, Please re-check the instructions. We are looking for only issues around New Navigation.

**Comment by sraarum** [comment]
Okay. This can be removed.
