### ISSUE TITLE
No results display when the filter on data science is set to off

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2472]
**Describe the bug**

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Data Science filter as OFF

**Expected behavior**
Resulted to be displayed as per filters

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59126639-daf98a80-8965-11e9-8e4d-57b35409ad01.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
@satkanhub Please read the challenge instructions carefully. We are looking for issues only around the New Navigation.
