### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by agnelvishal** [topcoder-platform/community-app#2473]
**Icons Missing**
When accessing the user section in mobile, 404 error is returned for the following two files.
1. https://test-community-app.topcoder-dev.com/images/right-arrow.svg 
2. https://test-community-app.topcoder-dev.com/images/icon-bell-red.svg 

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges from a smartphone.
2. Click on the user icon at the top right corner.
3. 404 error is logged in the browser console for two icon files mentioned above

**Expected behavior**
The icons should be displayed and no error should arise in the browser console. 

**Screenshots**
![Screenshot from 2019-06-08 00-22-46](https://user-images.githubusercontent.com/10105332/59127000-1905a700-8984-11e9-88ee-8dbb52c303f5.png)

**Smartphone :**
 - Device: iPhone X, Pixel 2, Moto G
 - Browser Chrome, Firefox and probably others too.

**Comment by nithyaasworld** [comment]
console errors not in scope
