### ISSUE TITLE
Topcoder logo is not centered in mobile web

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2474]
**Reproduction steps:**

1. Open the test URL and log in
2. Observe the placement of the topcoder logo

**Expected result:** 
The topcoder logo is centered as shown in the marvel app screens

**Actual result:** 
The topcoder logo in not centered

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome 

**Screenshot:**

![screenshot5](https://user-images.githubusercontent.com/45698232/59126936-29356c00-891b-11e9-9fdb-34d7f3c73abe.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2398
