### ISSUE TITLE
Work arrow position is misplaced when user switches the orientation

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2475]
![image](https://user-images.githubusercontent.com/42398485/59126966-02cbfc80-892c-11e9-81dc-9c8f098738da.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Tracks
4. Go to Landscape view
5. Click Menu

**Actual:** Work arrow position is misplaced when user switches the orientation

**Expected:** Should always point the arrow to the menu

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by nithyaasworld** [comment]
root cause of the screen being resized: https://github.com/topcoder-platform/community-app/issues/2407
