### ISSUE TITLE
Notification page title or description is not displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2476]
![image](https://user-images.githubusercontent.com/42398485/59126922-e16b1080-892b-11e9-875b-bf72135c957e.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Tracks
4. Go to Landscape view
5. Click Menu > Profile > Notifications

**Actual:** Notification page title or description is not displayed

**Expected:** Should display the title and description. Now user needs to scroll to see them

**Reproducibility Rate:** 3/3

**Environment:** Pixel XL, Android 9

**Browser:** Chrome 75.0.3770.80

**Comment by nithyaasworld** [comment]
Notification is not in scope for this Bug hunt.
