### ISSUE TITLE
Setting tab is not working

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2477]
**Describe the bug**
setting tab is not working

**To Reproduce**
1. Go to 'user name on menu toolbar'
2. Click on 'down arrow'
3. Click on setting

**Expected behavior**
setting page should open

**Screenshots**
![chrome_AqI4VnqIoE](https://user-images.githubusercontent.com/5110867/59126992-14d98980-8984-11e9-934a-84c4be280f5b.png)

**Desktop (please complete the following information):**
 - OS: windows 7
 - Browser chrome
 - Version 7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
duplicate
