### ISSUE TITLE
result text printed instead of user profile picture 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#248]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[tags][0]=Other

- check past challenge (TCO India Regionals 2017 Development Challenge) winner column 

Actual Result(s)
-----------------------------------------------------------------
results text shown 

Expected Result(s)
-----------------------------------------------------------------
  should show winner icon 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-community-app topcoder com 2017-08-25 07-10-46](https://user-images.githubusercontent.com/3225433/29696204-fa667584-8964-11e7-9dd4-93801e313e1c.png)

**Comment by birdofpreyru** [comment]
Not a bug. It looks like for this challenge there is indeed no winners, so printing Results linking to results look appropriate.
