### ISSUE TITLE
Lag in displaying the challenge

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2480]
**Describe the bug**
On clicking the challenge details, it is taking time to open the challenge. The browser is processing for long to open the details of challenge

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on challenge "TC3 Code 01"

**Expected behavior**
Challenge details to be available as soon on clicking on the challenge link.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59127122-0a5cc700-8967-11e9-8cae-fe99bc11233d.png)

**Desktop
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
Out of Scope
