### ISSUE TITLE
UI: Topcoder logo has no colours

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2482]
**Describe the bug**
Topcoder logo has no colours, displayed in black and white theme. 
**To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Verify the logo on top

*Expected behavior**
Logo to be displayed in colours.

**Screenshots**
Attached screenshot.
![Screenshot_20190608-002443](https://user-images.githubusercontent.com/41059603/59127316-f6c05900-8984-11e9-9737-a70ac056b23c.png)

**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
 - Device: Nokia 8.1
 - OS: Android 9
 - Browser : Chrome
 - Version : 75.0.3770.67

**Additional context**

**Comment by nithyaasworld** [comment]
As designed.
