### ISSUE TITLE
Item Header's font is changing when Window is resized

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2483]
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click Work-->Tracks, 
4, Try Resizing the window size, and check font displayed for the "Tracks" Header

**Actual behavior**
Item Header's font is changing when Window is resized

**Expected behavior**
Item Header's font should not when Window is resized

**Screen shots/video**
https://drive.google.com/uc?id=1a48PPyl3n-xdCB2Sio4aAtf1D_lL-wRt

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)

 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment]
Thats as per the design: https://marvelapp.com/89423f8/screen/54595272/handoff
