### ISSUE TITLE
[Windows][Chrome] After clicking near right bar, Community tab is getting highlighted

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2484]
**Describe the bug**
After clicking near right bar, Community tab is getting highlighted
**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on WORK
4. Click on right bar where WORK was present before
6. clicking on right most empty space, Community tab getting highlighted
Please refer attached video present in zip 

**Expected behavior**
Clicking on empty space Community tab should not get highlighted

**Screenshots**
[Video_1.zip](https://github.com/topcoder-platform/community-app/files/3267258/Video_1.zip)

**Desktop (please complete the following information):**
 Device: Computer
OS: Windows 10
Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
I am not able to reproduce. Moreover this issue is too trivial.
