### ISSUE TITLE
Broken layout of the notification page

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2485]
**Reproduction steps:**

1.  Open the test URL and log in 
2. Open the user menu at the top right corner
3. Click on Notifications
4. Scroll the top part of the screen displaying "Good job! You're all caught up" up and down
5. Observe the bottom of the screen

**Expected result:** 
Only the notification screen is displayed; no other menu items are displayed below it, or they are displayed but not cut off. The text under "Good job! You're all caught up" doesn't get hidden behind Notification Settings when scrolling up and down.

**Actual result:** 
Menu items are displayed below  the notifications page, some are cut off . The text under "Good job! You're all caught up" gets hidden behind Notification Settings when scrolling up and down.

**Frequency:** 
5/5 

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome 

**Screenshot:**

![screenshot6](https://user-images.githubusercontent.com/45698232/59127599-effdfb80-891c-11e9-811f-617139b61468.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
