### ISSUE TITLE
Fonts are missing in mobile view when side bar section is accessed.

### ISSUE THREAD

**Issue by agnelvishal** [topcoder-platform/community-app#2486]
**Fonts are missing**
The following font files give a 404 error when "Compete", "Tracks" and "Community" section is accessed from a mobile from the top navbar. 
1. https://test-community-app.topcoder-dev.com/fonts/barlow-condensed-v3-latin-600.woff2 
2. https://test-community-app.topcoder-dev.com/fonts/barlow-condensed-v3-latin-600.woff
3. https://test-community-app.topcoder-dev.com/fonts/barlow-condensed-v3-latin-600.ttf

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges from a mobile.
2. Click on the sidebar at top felt
3. Click on the heading "Work"
4. Click on any one of the headings "Compete", "Tracks" or "Community" 
5. See the 404 error for the font files in the browser console. 

**Screenshots**

**Smartphone (please complete the following information):**
- Device: iPhone X, Pixel 2, Moto G
- Browser Chrome, Firefox and probably others too.

**Comment by nithyaasworld** [comment]
Console errors are not in scope for the Bug hunt.
