### ISSUE TITLE
[Mobile][Chrome]After click on profile full page is filled up and no back option in mobile

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2487]
**Describe the bug**
After click on profile full page is filled up and no back option in mobile

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges in Mobile Chrome
2. Login with dan_developer
3. click on profile
4. Full page filled up and no back option to navigate back to previous page

**Expected behavior**
In Mobile either full page should not be filled or back option should be present

**Screenshots**
![3](https://user-images.githubusercontent.com/51490878/59127824-291e8600-8986-11e9-831d-552228caa297.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4
 - OS: Android 7.0
 - Browser : Chrome

**Comment by nithyaasworld** [comment]
Will be fixed as part of https://github.com/topcoder-platform/community-app/issues/2398
