### ISSUE TITLE
Notification bell icon is not available at header bar

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2488]
**Describe the bug**
Notification bell icon is not available at header bar

**To Reproduce**
1. Go to ' https://test-community-app.topcoder-dev.com/challenges'
2. login with valid username and password
3. Go to header bar

**Expected behavior**
Notification bell icon shod available

**Screenshots**
![chrome_F9y8F13WnW](https://user-images.githubusercontent.com/5110867/59127883-523f1680-8986-11e9-8730-ae67f1f2bb58.png)

**Desktop (please complete the following information):**
 - OS: window 7
 - Browser -chrome
 - Version 7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by agnelvishal** [comment]
Same as https://github.com/topcoder-platform/community-app/issues/2420
