### ISSUE TITLE
Notification text in landscape mode is not displayed by default

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2489]
**Reproduction steps:**

1. Open the test URL and log in
2. Open the user menu at the top right corner
3. Click on Notifications
4. Enter the landscape mode
5. Observe
6. Scroll down in the section between the green tab "Notifications" and the blue button "Notification Settings"

**Expected result:** 
The text about notifications is displayed by default when entering landscape mode. The text is fixed; user can't scroll the text to an empty space

**Actual result:** 
Empty space is displayed when entering landscape mode in notifications; the user has to scroll down in the section between the green tab "Notifications" and the blue button "Notification Settings" to see the text

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome 

**Screenshot:**

![screenshot7](https://user-images.githubusercontent.com/45698232/59128062-ec1ea900-891d-11e9-9d18-ab6d74a9d1ec.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
