### ISSUE TITLE
Past challenge count missing  

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#249]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges

- Scroll down to past challenge 

- check Past CHALLENGE count

Actual Result(s)
-----------------------------------------------------------------
Past challenge count missing  

Expected Result(s)
-----------------------------------------------------------------
  should show past challenge count  

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![Uploading screenshot-community-app.topcoder.com 2017-08-25 07-20-14.png…]()

**Comment by birdofpreyru** [comment]
Not a bug, it is intentional: at the moment backend does not allows us to efficiently count past challenges matching frontend filters, thus the count omitted for past challenges.
