### ISSUE TITLE
Contact Us Form is not cleared after submission of query

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2491]
**Describe the bug**

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Support at the bottom of the page.
4. Enter the details of the issue and click Send
5. A Thank you message appears and then click OK
6. Click on Support again
7. Form is still having the old details ( Name & Email etc ) submitted previously.

**Expected behavior**
A blank form should appear

**Screenshots**

![image](https://user-images.githubusercontent.com/51492004/59127972-37aa7480-8969-11e9-92f5-7d2a2f83797d.png)

![image](https://user-images.githubusercontent.com/51492004/59127987-42fda000-8969-11e9-8419-2ef5af9269c6.png)

![image](https://user-images.githubusercontent.com/51492004/59127997-4db83500-8969-11e9-9e0d-9cbb2cb2ac6a.png)

![image](https://user-images.githubusercontent.com/51492004/59128034-5872ca00-8969-11e9-876b-da6ac86f7b6b.png)

**Desktop
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
Out of Scope
