### ISSUE TITLE
[Mobile]: Sub-items navigation is not smooth in Mobile

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2492]
**Pre-Requisite**

**Steps to Reproduce**

1. In Mobile browser, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder(if not already logged in)
3. Click Work-->Compete

**Actual behavior**
Sub-items navigation is not smooth in Mobile, Item's header is displayed after 3-4 secs

**Expected behavior**
Item's header should be displayed in real-time(i.e. immedietly after clicking on Item).

**Screen shots/video**
https://drive.google.com/uc?id=1S_PmDyYzm0JDzjyEttKeMiynQCkDfzwe

**Environment :**

Samsung S7 Edge || Android 8.0.0 || Chrome Browser

 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment]
duplicate of https://github.com/topcoder-platform/community-app/issues/2440
