### ISSUE TITLE
Functional: Tapping on "Competitive Programming" doesn't load anything

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2494]
**Describe the bug**
Functional: Tapping on "Competitive Programming" doesn't load anything. The webpage shows "Completing login, one moment place".

*To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Go to settings - Edit Profile.
4. Tap on Menu - Work - Compete - competitive Programming

Expected behavior*

Should display the web page related to competitive Programming.

Repro : 3/3

**Screenshots**
Attached 
![Screenshot_20190608-004125](https://user-images.githubusercontent.com/41059603/59128400-8f57d880-8987-11e9-8e99-3ba0774b9d4d.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
Device: Nokia 8.1
OS: Android 9
Browser : Chrome
Version : 75.0.3770.67

*Additional context**

**Comment by nithyaasworld** [comment]
duplicate
