### ISSUE TITLE
Functional: Tapping on Topcoder logo doesn't navigate to any page

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2496]
**Describe the bug**
Tapping on Topcoder logo doesn't navigate to any page.

**To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. settings - Edit Profile 
4. Now tap on Topcoder logo to navigate to home page
5. It doesn't do anything

**Expected behavior**
Tapping the logo should navigate to home page

**Screenshots**
Attached.

![Screenshot_20190608-002443](https://user-images.githubusercontent.com/41059603/59128780-a2b77380-8988-11e9-942e-f059cd24db85.png)

**Desktop (please complete the following information):**
NA
**Smartphone (please complete the following information):**
Device: Nokia 8.1
OS: Android 9
Browser : Chrome
Version : 75.0.3770.67

**Additional context**

**Comment by nithyaasworld** [comment]
@luizrrodrigues are we covering this as part of any other bug? Thanks.

**Comment by luizrrodrigues** [comment]
@nithyaasworld Yes.
