### ISSUE TITLE
Sub menu does not started from selected main menu option

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2497]
**Describe the bug**
Sub menu starts from selected main menu option

**To Reproduce**
1. Go to ' https://test-community-app.topcoder-dev.com/challenges'
2. login with valid user name and password
3. Click on WORK tab
4. Click on design
5. Check allignment of sub menu

**Expected behavior**
Sub menu starts from selected main menu option

**Screenshots**
![chrome_dBrndfqFBf](https://user-images.githubusercontent.com/5110867/59128869-df836a80-8988-11e9-9a95-59af5f8c2048.png)

**Desktop (please complete the following information):**
 - OS: -windows 7
 - Browser -chrome
 - Version 7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
It is as designed.
