### ISSUE TITLE
The user is taken to topcoder home page after logging out

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2499]
**Reproduction steps:**

1. Open the test URL and log in
2. Click on the user drop down menu
3. Click on log out
4. Observe
5. Click on the back button of the browser

**Expected result:** 
The user stays on challenges page after logging out

**Actual result:** 
The user is taken to topcoder home page after logging out; clicking on the back button of the browser takes them back to challenges page

**Frequency:** 
5/5 

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Comment by nithyaasworld** [comment]
Challenge listing page is public. so its accessible even after logging out.
