### ISSUE TITLE
Functional: Tapping on All projects doesn't redirect to any page.

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2500]
**Describe the bug**
Functional: Tapping on All projects doesn't redirect to any page.

**To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Tap on drop-down next to Profile photo
4. Tap on All projects

**Expected behavior**
Tapping on All Projects should navigate to a page or show the projects list.

**Screenshots**
Attached.
![Screenshot_20190608-010435](https://user-images.githubusercontent.com/41059603/59129329-29208500-898a-11e9-86bf-bb4abdc9abd0.png)

**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
Device: Nokia 8.1
OS: Android 9
Browser : Chrome
Version : 75.0.3770.67

**Additional context**

**Comment by nithyaasworld** [comment]
duplicate
