### ISSUE TITLE
Selected section is not highlighted in IE11

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2501]
**Reproduction steps:**

1. Open the test URL and sign in
2. Click on Work > Compete
3. Observe the All challenges menu item

**Expected result:** 
Selected menu items have a green line under them to show they are selected

**Actual result:** 
Selected menu items are not highlighted with a green line under them

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
IE 11.503.17763.0

![screenshot8](https://user-images.githubusercontent.com/45698232/59129572-0eb2c100-8922-11e9-8e7b-47c534e9199f.jpg)

**Comment by nithyaasworld** [comment]
duplicate
