### ISSUE TITLE
Active state underscore not shown below the submenu when user not logged in

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2502]
**Describe the bug**
Active state underscore not shown below the submenu when user not logged in to portal.

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Do not login
3. Click on WORK then Compete
4. Look for active state.
5. Active state underscore not below sub-menu.
6. Underscore shown in extreme left of layout

**Expected behavior**
Active state underscore should be below sub-menu.

**Screenshots**
![7](https://user-images.githubusercontent.com/51490878/59129652-0cd11800-898b-11e9-8426-7a7ec892bb6c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 42.17134.1.0

**Comment by nithyaasworld** [comment]
duplicate
