### ISSUE TITLE
Drop down arrow is not displayed correctly in logged out state

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2503]
**Reproduction steps:**
prereq.: the user is logged out

1. Open the test URL
2. Click on the hamburger menu at the top left corner
3. Click on Compete
4. Observe

**Expected result:** 
Drop down arrow appears next to 'Compete' text

**Actual result:** 
A weird icon appears instead of the drop down arrow next to 'Compete' text in logged out state

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser/s:
Chrome 

**Screenshot:**

![screenshot9](https://user-images.githubusercontent.com/45698232/59130108-6140ad00-8923-11e9-80f3-48b13fcba9c7.jpg)

**Comment by alexandreeva** [comment]
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment]
duplicate
