### ISSUE TITLE
Notification option is too close to the short Bio

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2507]
1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Profile

**Actual:** Notification option is too close to the short Bio

**Expected:** Should have some spacing 

**Reproducibility Rate:** 3/3

**Environment:** iPhone 5S, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
