### ISSUE TITLE
Compete is having a hipen " - " next to it in the display

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2508]
**Describe the bug**

**To Reproduce**
1. Open the test URL and click on the menu bar on the top left
2. Click on Work
3. Click on Compete

**Expected behavior**
On the screen, it should display only Compete

**Screenshots**
![Screenshot_20190607-212605_Chrome](https://user-images.githubusercontent.com/51492004/59130299-5d3a7c80-896f-11e9-84c1-a20ca41c3ffa.jpg)

**Smartphone:**
 - Device: Samsung J7 Pro
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157
.

**Comment by nithyaasworld** [comment]
duplicate

**Comment by satkanhub** [comment]
> duplicate

Can you give reference number please.

Thanks

**Comment by nithyaasworld** [comment]
Please check the already accepted bug list (bugs with the label: nav_bugaccepted)

**Comment by satkanhub** [comment]
Thanks.... Found #2432
