### ISSUE TITLE
The secondary menu appears connected to the topcoder logo instead of the section they belong to

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2509]
**Reproduction steps:**

1. Open the test URL and log in 
2. Click on Work in the header
3. Click on Compete
4. Observe the position of the triangle-like shape showing the connection of the opened secondary menu to the main menu

**Expected result:** 
The secondary menu is displayed as being connected to the corresponding main menu item

**Actual result:** 
The secondary menu is displayed as being connected to the topcoder logo

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
IE 11.503.17763.0

![screenshot10](https://user-images.githubusercontent.com/45698232/59130655-e8daeb80-8924-11e9-86ce-dc52b68e0f70.jpg)

**Comment by nithyaasworld** [comment]
duplicate
