### ISSUE TITLE
[$10] - tool tip  profile image layout broken 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#251]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[tags][0]=Other

- Scroll down to  past challenge 

- move mouse over TeckedIn - Simpler Content Management Platform Nodejs Backend Implementation Challenge  2nd place winner

- Observe  

Actual Result(s)
-----------------------------------------------------------------
tool tip  profile image layout broken 

Expected Result(s)
-----------------------------------------------------------------
  should show  profile image  properly 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

![qweeee](https://user-images.githubusercontent.com/3225433/29696591-89a37740-8967-11e7-8de7-d898f708657d.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points (cause it is not an easy one to notice - in many tooltips the style looks fine).
