### ISSUE TITLE
Filters in Track are not producing the results promptly

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2510]
**Describe the bug**
Filters in Track are not producing the results promptly

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Tracks and uncheck Development and Data Science.

**Expected behavior**
Results to be displayed as per track

**Screenshots**
![Screenshot_20190607-214311_Chrome](https://user-images.githubusercontent.com/51492004/59130684-69730980-8970-11e9-95ac-050c39106bc2.jpg)

**Smartphone:**
 - Device: Samsung J7 Pro
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment]
out of scope
