### ISSUE TITLE
Functional: Accepting the topgear user consent throws an error.

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2511]
**Describe the bug**
Functional: Accepting the topgear user consent throws an error.

**To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Tap on drop-down next to user profile photo
4. Settings - Account
5. Tap on User consent button to accept
6. Throws an error

**Expected behavior**
Either the option should get enabled as acceptance by user. Or navigate to terms and conditions page.
**Screenshots**
Attached.
![Screenshot_20190608-013157](https://user-images.githubusercontent.com/41059603/59130791-0c864c00-898e-11e9-918c-bf3e526b3428.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Device: Nokia 8.1
OS: Android 9
Browser : Chrome
Version : 75.0.3770.67

**Additional context**

**Comment by nithyaasworld** [comment]
Out of Scope
