### ISSUE TITLE
UI is not responding to the On / Off against the Tracks

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2512]
**Describe the bug**
UI is not responding to the On / Off against the Tracks

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Track
4. Randomly keep trying On / Off for the tracks.

**Expected behavior**
UI should respond to the input promptly. However, there is no response and it is not allowing to change the On / Off and page seems to be unresponsive to user for long time.

**Screenshots**
![Screenshot_20190607-214535_Chrome](https://user-images.githubusercontent.com/51492004/59130940-249ba280-8971-11e9-8665-a514a6244078.jpg)

**Smartphone:**
 - Device: Samsung J7 Pro
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment]
out of scope
