### ISSUE TITLE
More button and Arrow spacing issue

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2514]
![image](https://user-images.githubusercontent.com/42398485/59131134-14ff6800-8937-11e9-9a30-05cecc59bafe.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work > More

**Actual:** No spacing in between the arrow icon and the more text

**Expected:** Should have some spacing https://marvelapp.com/89423f8/screen/54465717

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@nithyaasworld  This one will be fixed in #2515

**Comment by SathyaJayabal** [comment]
Closing this as this issue is being tracked here.
https://github.com/topcoder-platform/navigation-component/issues/99
