### ISSUE TITLE
Unable to save filters with keywords

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2516]
**Describe the bug**

**To Reproduce**
1. Open the test URL and log in
2. Click on Filters
3. Select keywords "ActionScript" and Save Filter

**Expected behavior**
Filters to apply with the keywords selected. Currently, it is unable to save filters.

**Screenshots**
![Screenshot_20190607-214749_Chrome](https://user-images.githubusercontent.com/51492004/59131107-b1def700-8971-11e9-9953-045a47293029.jpg)
![Screenshot_20190607-214805_Chrome](https://user-images.githubusercontent.com/51492004/59131113-b60b1480-8971-11e9-9792-399ba1962d6c.jpg)

**Smartphone:**
 - Device: Samsung Galaxy Tab A
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Additional context**

**Comment by nithyaasworld** [comment]
out of scope
