### ISSUE TITLE
The user profile is only displayed after reloading the page

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2517]
**Reproduction steps:**

1. Open the test URL and log in
2. Open the user drop down menu at the top right corner
3. Click on the green box to open the member profile
4. Observe the change in URL
5. Reload the page
6. Observe

**Expected result:** 
The user is taken to their member profile when they open it through the user menu

**Actual result:** 
The user remains on the same page after opening their member profile through the user menu, even though the URL indicates that they are on their member profile; the user has to reload the page for the member profile to display

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

![screenshot12](https://user-images.githubusercontent.com/45698232/59131631-b8488100-8927-11e9-9490-71773a6da8f0.jpg)

**Comment by nithyaasworld** [comment]
Thanks @alexandreeva but this is covered in https://github.com/topcoder-platform/community-app/issues/2395
