### ISSUE TITLE
'RELIABILITY BONUS' displayed in a design challenge price section

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#252]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Check the Price section

Actual Result(s)
-----------------------------------------------------------------
- 'RELIABILITY BONUS' displayed in a design challenge price section

Expected Result(s)
-----------------------------------------------------------------
- Must not display 'RELIABILITY BONUS' values

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![42](https://user-images.githubusercontent.com/4592712/29696951-c55a732c-8969-11e7-955e-46e03ec7ee50.jpg)

**Comment by birdofpreyru** [comment]
Dublicates #213, I believe
