### ISSUE TITLE
All Devices> Page won't navigate to the default selected sub menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2522]
1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work > Complete > Default Sub-menu is All Challenges (Page is in that page)
4. Tap Menu > Work > Tracks > Default Sub-menu is Competitive programming (Still in the challenges page)
5. Tap Menu > More > Community > Default Sub-menu is TCO (Still in the challenges page)

**Actual:** Page won't navigate to the default selected submenu

**Expected:** When the user selects a main menu from the navigation bar, the page should be redirected to the default selected sub-menu (First item on the submenu) page automatically. Because of the 2nd bullet point in the below document,> **Currently selected item should not reload the page (inactive link)**

Because of the above, user can't click on the default selected menu to go to that page

https://docs.google.com/document/d/1-ExQxNCncwH8YNcuFl-bq0PwteBoaoefPeo-BBGw_XQ/edit

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch, iPhone 5S, Pixel XL

**Browser:** Chrome 75.0.3770.80

**Comment by luizrrodrigues** [comment]
@nithyaasworld This one is duplication of #2395

**Comment by luizrrodrigues** [comment]
Duplicate of #2395
