### ISSUE TITLE
Menu path is not as per Marvelapp under WORK

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2524]
**Describe the bug**
Menu path is not as per Marvelapp under WORK

**To Reproduce**
1. Open the test URL and log in
2. Click on Work

**Expected behavior**
Menu path is not as per Marvelapp

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59133955-f078af80-8979-11e9-85ef-01bb88a581d0.png)

**Desktop (please complete the following information):**

**Smartphone:**
 - Device: Samsung Galaxy Tab A
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment]
@satkanhub Can you please detail about what Menu Path are you referring here?

**Comment by satkanhub** [comment]
@nithyaasworld  Sub Menu under WORK shows as Compete / Track / Community. But it is not the same as per Marvel app.

**Comment by nithyaasworld** [comment]
Ok! Thats the design prototype for the nav component! Not the actual values we should expect in our app.
