### ISSUE TITLE
First item in secondary menu is selected by default

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2525]
**Reproduction steps:**

1. Open the test URL and log in
2. Click on Work
3. Click on Complete
4. Observe the opened secondary menu
5. Click on Tracks and repeat step 4
6. Click on Community and repeat step 4

**Expected result:** 
No menu items are selected in the secondary menu unless the user selects it

**Actual result:** 
The first menu item is selected in the secondary menu even though the user didn't select any yet

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80
Firefox 67.0.1
Microsoft Edge 44.17763.1.0
IE 11.503.17763.0

![screenshot15](https://user-images.githubusercontent.com/45698232/59134049-cb128400-892e-11e9-9731-c4cbea05e6e4.jpg)

**Comment by nithyaasworld** [comment]
It is as designed
