### ISSUE TITLE
Unable to login when navigated through WORK->Competitive Programming

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2526]
**Describe the bug**
Unable to login when navigated through WORK->Competitive Programming. Screen was stuck in below as shown in screenshot.

**To Reproduce**
1. Open the test URL
2. Click on Work
3. Click on Competitive Programming
4. Enter the user credentials and Signin

**Expected behavior**
User should be able to login to see the details under Competitive Programming.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59134201-a80dc180-897a-11e9-85e5-b659e26fedf4.png)

**Smartphone:**
 - Device: Samsung Galaxy Tab A
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment]
Out of Scope
