### ISSUE TITLE
[$10] - After the text 'RELIABILITY BONUS' Below spacing is not enough

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#253]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Check the spacing below the 'RELIABILITY BONUS' text

Actual Result(s)
-----------------------------------------------------------------
- After the text 'RELIABILITY BONUS' Below spacing is not enough

Expected Result(s)
-----------------------------------------------------------------
- Must have some space in between the text and to bottom section

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![43](https://user-images.githubusercontent.com/4592712/29697004-1f2da43c-896a-11e7-8a64-0537f0f2192c.jpg)
![43 2](https://user-images.githubusercontent.com/4592712/29697005-1f2daaae-896a-11e7-96d5-9cfbf651ecc0.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point. We should ensure that if there are many prizes on a challenge, and they occupy multiple rows; and there is the checkpoints string, then we still have enough spacing there.
