### ISSUE TITLE
Menu items displayed incorrectly when entering portrait/landscape view

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2530]
**Reproduction steps:**

1. In portrait mode, open the test URL and log in
2. Click on the hamburger menu and select Compete
3. Switch to landscape view
4. Observe
5. Click on Tracks
6. Switch back to portrait mode
7. Click on the hamburger menu
8. Observe

**Expected result:** 
When the user switches from portrait to landscape view and reverse, the menu items are displayed correctly and as they usually would in the corresponding view

**Actual result:** 
After opening the secondary menu in the portrait view and switching to landscape, the secondary menu is not displayed. After opening a secondary menu and switching back to portrait view the menu appears as in landscape view, but main menu items are not displayed, and the green line highlighting the selected secondary menu item is out of place.

**Frequency:** 

**Device/Browser/OS:** 

Device: iPad (5th generation)

OS: iOS 12.2

Browser: Safari

![IMG_3062](https://user-images.githubusercontent.com/45698232/59137419-9e656900-893c-11e9-817a-b6bbaefa803f.PNG)
![IMG_3063](https://user-images.githubusercontent.com/45698232/59137421-9e656900-893c-11e9-9f40-18a5cec630da.PNG)

**Comment by alexandreeva** [comment]
Frequency: 5/5

**Comment by alexandreeva** [comment]
same issue occurs on desktop when switching between 250% zoom and lesser zoom (Chrome 75.0.3770.80)

**Comment by luizrrodrigues** [comment]
@nithyaasworld This will be fixed in following issues: #2403 #2407 #2498

**Comment by nithyaasworld** [comment]
Verified. This is no more an isue.
