### ISSUE TITLE
No option to exit notifications on iPad

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2531]
**Reproduction steps:**
prereq.: the user is in portrait mode

1. Open the test URL and log in
2. Click on the user menu in the top right corner
3. Click on Notifications
4. Observe
5. Try going back

**Expected result:** 
There is a back or close button to exit notifications

**Actual result:** 
The user is unable to exit notifications; there is no exit or back button. The browser back button closes the page.

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: iPad (5th generation)

OS: iOS 12.2

Browser: Safari

![IMG_3064](https://user-images.githubusercontent.com/45698232/59137771-39127780-893e-11e9-8570-531fcf1b7557.PNG)

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
