### ISSUE TITLE
Opened user menu is not displayed after switching orientation

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2534]
**Reproduction steps:**

1. In the portrait view, open the URL and log in
2. Open the user menu at the top right corner
3. Switch to landscape view and observe
4. Switch back to portrait view and close the menu
5. Switch to landscape view and open the drop down user menu
6. Switch back to portrait view and observe

**Expected result:** 
If the user menu is opened in portrait view, it should be opened in landscape view, and reverse

**Actual result:** 
After opening the user menu in portrait view and switching to landscape view it is not displayed as opened in landscape view, and reverse

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: iPad (5th generation)

OS: iOS 12.2

Browser: Safari

**Comment by nithyaasworld** [comment]
Should be fixed as part of https://github.com/topcoder-platform/community-app/issues/2493
