### ISSUE TITLE
Sub menu arrow is not pointing to the correct menu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2536]
![image](https://user-images.githubusercontent.com/42398485/59138230-9d8b0200-8951-11e9-894b-29f489aa51d2.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Community
4. Go to Landscape view

**Actual:** Sub menu arrow is not pointing to the correct menu

**Expected:** Should point to the correct item

**Reproducibility Rate:** 3/3

**Environment:** iPad Air 2, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2407
