### ISSUE TITLE
Opened notification screen in not displayed when switching to landscape view

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2537]
**Reproduction steps:**

1. In the portrait view, open the test URL and log in
2. Open on the user menu in the top right corner 
3. Open Notifications
4. Switch to landscape view and observe

**Expected result:** 
The user stays on the notifications screen after switching to landscape view

**Actual result:** 
After switching to landscape view, the notification screen is not displayed even though it was opened in portrait view

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: iPad (5th generation)

OS; iOS 12.2

Browser: Safari

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
