### ISSUE TITLE
Main menu arrow is not pointing to the correct location

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2538]
![image](https://user-images.githubusercontent.com/42398485/59138395-708b1f00-8952-11e9-99b0-44436bb9095f.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work
4. Go to Portrait view
5. Tap hamburger menu

**Actual:** Main menu arrow is not pointing to the correct location

**Expected:** Should point to the correct item

**Reproducibility Rate:** 3/3

**Environment:** iPad Air 2, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment]
duplicate https://github.com/topcoder-platform/community-app/issues/2407
