### ISSUE TITLE
[$20] - Winners 5-8 are missing in the 'Winners' tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#254]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Click on the 'Winners' tab

- Check the winner handles

Actual Result(s)
-----------------------------------------------------------------
- Winners 5-8 are missing in the 'Winners' tab

Expected Result(s)
-----------------------------------------------------------------
- Must display all the Winners from 1-9 in the 'Winners' tab

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![44](https://user-images.githubusercontent.com/4592712/29697049-632d119a-896a-11e7-9698-bbd5b15758d9.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points
