### ISSUE TITLE
$75 | Common > Accessing the page directly won't highlight the submenu

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2542]
![image](https://user-images.githubusercontent.com/42398485/59140200-23ae4500-8960-11e9-89b3-9ffcaf82fcf3.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click Menu > Work > Tracks > 

- Competitive programming: https://test-community-app.topcoder-dev.com/community/competitive-programming
- Data Science: https://test-community-app.topcoder-dev.com/community/data-science/
- Design: https://test-community-app.topcoder-dev.com/community/design/
- Development: https://test-community-app.topcoder-dev.com/community/development/
- QA: https://test-community-app.topcoder-dev.com/community/qa/

**Other pages as well**

**Actual:** Accessing the page directly won't highlight the submenu

**Expected:** Should highlight the submenu

- Competitive programming: Menu > Work > Tracks > Competitive programming should have an underline, Bold formatting and should be a deadlink
- Data Science: Menu > Work > Tracks > Data Science should have an underline, Bold formatting and should be a deadlink
- Design: Menu > Work > Tracks > Design should have an underline, Bold formatting and should be a deadlink
- Development: Menu > Work > Tracks > Development should have an underline, Bold formatting and should be a deadlink
- QA: Menu > Work > Tracks > QA should have an underline, Bold formatting and should be a deadlink

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Chrome 75.0.3770.80 (Official Build) (64-bit) | Microsoft Edge 44.17763.1.0

**Comment by luizrrodrigues** [comment]
@nithyaasworld just added P1 back, this is right?

**Comment by luizrrodrigues** [comment]
@rashmi73 Status on this one?

**Comment by rashmi73** [comment]
@luizrrodrigues in progress, but confused with "dead link", what will happen if someone direclty clicks on it?

**Comment by rashmi73** [comment]
@luizrrodrigues PR in few minutes

**Comment by luizrrodrigues** [comment]
@rashmi73 When PR is ready, post here.

**Comment by luizrrodrigues** [comment]
> @luizrrodrigues in progress, but confused with "dead link", what will happen if someone direclty clicks on it?

To deadline, nothing. Not need highlight.

**Comment by luizrrodrigues** [comment]
@rashmi73 Any status on this one?

**Comment by rashmi73** [comment]
@luizrrodrigues PR in half hour

**Comment by rashmi73** [comment]
@luizrrodrigues both PR ready

https://github.com/topcoder-platform/community-app/pull/2621

https://github.com/topcoder-platform/navigation-component/pull/14

**Comment by luizrrodrigues** [comment]
@rashmi73 Please check feedback in PR's. 
If you have this working in you local, please share a video showing that.

Thanks.

**Comment by rashmi73** [comment]
@luizrrodrigues yes it is working for development link,
I hope it is correctly implemented by me,

1. whenever we visit the any of links directly,
2.then we click on WORK
3. then we click on Tracks
4. and we see menu selected is respective to link.

is this what being tested?

**Comment by luizrrodrigues** [comment]
@rashmi73 Here if access a page directly or refresh the page, I'm getting this error:
` window is not defined `

**Comment by rashmi73** [comment]
@luizrrodrigues PR update and it wont window not defined anymore on refresh

**Comment by luizrrodrigues** [comment]
@rashmi73 Looks like working in Desktop, but not working in mobile.

Also, when you go to Challenges then click in Work -> Tracks the first track will be highlighted. 
Same if you go to track section and go to Work -> Compete the first tab will be highlighted.

![Screen Shot 2019-06-14 at 18 25 42](https://user-images.githubusercontent.com/7029641/59539023-18b06300-8ed2-11e9-9a8a-33e60e131255.png)

We just highlighted currently page in sub menu.

Make sense?

**Comment by rashmi73** [comment]
@luizrrodrigues actually current previous logic and also current logic is that first tab willl be highlighted if path does match url.

as challenges is not present in any of tab, so first will be highlighted.

Need to see on this logic handling of removing highlight if nothing matches with url.

**Comment by luizrrodrigues** [comment]
@rashmi73 I see, are you able to fix/implement that?

**Comment by rashmi73** [comment]
@luizrrodrigues trying it

**Comment by rashmi73** [comment]
@luizrrodrigues PR updated as per latest requirements.

@luizrrodrigues both PR ready

#2621

topcoder-platform/navigation-component#14

is it possible to increase the prize by few?

**Comment by luizrrodrigues** [comment]
I need about increase prize.

**Comment by luizrrodrigues** [comment]
Tests here:

http://local.topcoder.com/challenges
Work -> All Challenges : Works
Work -> Tracks : Works
Work -> Community : Fail - Active state showing in TCO

http://local.topcoder.com/community/qa
Work -> All Challenges : Fail - Active state showing in All Challenges
Work -> Tracks : Works
Work -> Community : Fail - Active state showing in TCO

http://local.topcoder.com/settings/profile
Work -> All Challenges : Fail - Active state showing in All Challenges
Work -> Tracks : Works
Work -> Community : Fail - Active state showing in TCO

Mobile looks like working now, but have same problem related above.

**Comment by rashmi73** [comment]
@luizrrodrigues updated and PR are
#2621

topcoder-platform/navigation-component#14

**Comment by luizrrodrigues** [comment]
@rashmi73 Issues related above looks fixed.

But now I'm seeing another issue, please check the video:
[2542.zip](https://github.com/topcoder-platform/community-app/files/3293251/2542.zip)

**Comment by luizrrodrigues** [comment]
@rashmi73 Status on this one?

**Comment by rashmi73** [comment]
@luizrrodrigues PR updated 
https://github.com/topcoder-platform/navigation-component/pull/14

**Comment by luizrrodrigues** [comment]
@rashmi73 Prize increased to $75

**Comment by luizrrodrigues** [comment]
@rashmi73 Looks like not fixed, can you recheck please and if possible share a video showing this working in your side.

**Comment by rashmi73** [comment]
@luizrrodrigues unable to shoot video, but latest changes are pushed PR updated.
and working perfectly fine, tested well this time.

both PR are #2621

topcoder-platform/navigation-component#14

I am sure this will be closed now successufuly. kindly verify

**Comment by luizrrodrigues** [comment]
@rashmi73 Please fix CircleCI tests.

**Comment by rashmi73** [comment]
@luizrrodrigues all is fixed
