### ISSUE TITLE
Drop down More menu is not highlighted even though an item in it selected

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2544]
**Reproduction steps:**

1. Open the test URL and log in
2. Click on 'Work' in the header
3. Zoom in 175%
4. Click on the More drop down menu
5. Click on Community
6. Observe

**Expected result:** 
The More drop down menu is highlighted when an item in it is selected. Or the selected item (in this case Community) is displayed instead of the drop down More menu

**Actual result:** 
The More drop down menu is not highlighted even though an item in it is selected. 

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Resolution:** 1600 x 900
![screenshot1](https://user-images.githubusercontent.com/45698232/59140641-569f0b80-8955-11e9-84e3-dc2ccafdcc78.png)

**Comment by nithyaasworld** [comment]
Expected behavior is: 

>Selecting an option from the “More” tab should become visible and swap position with the first element to the left of the tab.

We have another bug to address the above
