### ISSUE TITLE
a bar to scroll down the main page appears in the user menu at 250% 

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2545]
**Reproduction steps:**

1. Open the test URL and log in
2. Zoom in 250%
3. Open the user menu at the top right corner
4. Observe the scrolling bars in the right
5. Scroll down the most right bar
6. Close the user menu
7. Observe

**Expected result:** 
The user is not able to scroll down the main page when the user menu is open and the user does not see the main page

**Actual result:** 
When the user menu is opened at 250%, the user can scroll down the main page even though they don't see it

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Resolution:** 1600 x 900

![screenshot7](https://user-images.githubusercontent.com/45698232/59140653-7cc4ab80-8955-11e9-955b-5270a5d81f03.png)

**Comment by nithyaasworld** [comment]
same as https://github.com/topcoder-platform/community-app/issues/2481
