### ISSUE TITLE
The green line highlighting the selected menu item misplaced when zooming in

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2546]
**Reproduction steps:**

1. Open the test URL and log in 
2. Click on 'Work' in the header
3. Click on 'Community'
4. Zoom in
5. Observe the placement of the green line that highlights the selected menu item

**Expected result:** 
The green line highlighting the selected menu item is displayed under the selected item

**Actual result:** 
The green line highlighting the selected menu item gets misplaced when zooming in

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Resolution:* 1600 x 900

![screenshot3](https://user-images.githubusercontent.com/45698232/59140664-98c84d00-8955-11e9-800a-710f5d797a8c.png)

**Comment by nithyaasworld** [comment]
Duplicate
