### ISSUE TITLE
The green line highlighting the selected menu item misplaced when zooming out

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2547]
1. Open the test URL and log in 
2. Click on 'Work' in the header
3. Click on 'Community'
4. Zoom out
5. Observe the placement of the green line that highlights the selected menu item

**Expected result:** 
The green line highlighting the selected menu item is displayed under the selected item

**Actual result:** 
The green line highlighting the selected menu item gets misplaced when zooming out

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Resolution:* 1600 x 900

![screenshot4](https://user-images.githubusercontent.com/45698232/59140675-b85f7580-8955-11e9-8a27-535de124a55f.png)

**Comment by nithyaasworld** [comment]
similar to https://github.com/topcoder-platform/community-app/issues/2546
