### ISSUE TITLE
undesigned user menu appears when zooming in 250%

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2548]
**Reproduction steps:**

1. Open the test URL and log in
2. Zoom in 250%
3. Open the user menu at the top right corner
4. Observe

**Expected result:** 
The designed user menu is displayed 

**Actual result:** 
The undesigned user menu is displayed at 250%

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Resolution:** 1600 x 900

![screenshot6](https://user-images.githubusercontent.com/45698232/59140689-d62cda80-8955-11e9-8982-41fc3320a080.png)

**Comment by nithyaasworld** [comment]
duplicate
