### ISSUE TITLE
user menu flickers when scrolling down at 250% in IE11

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2549]
**Reproduction steps:**

1. Open the test URL and log in
2. Zoom in 250%
3. Open the user menu at the top right corner
4. Scroll down
5. Observe

**Expected result:** 
The page doesn't flicker when the user scrolls down in the user menu

**Actual result:** 
The page flickers when the user scrolls down in the user menu at 250% zoom

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
IE 11.503.17763.0

**Resolution:** 1600 x 900

![screenshot5](https://user-images.githubusercontent.com/45698232/59140700-f2c91280-8955-11e9-96ce-4996fdb32dbc.png)

**Comment by nithyaasworld** [comment]
User menu should not be scrollable in mobile view. This is covered as part of another bug.
