### ISSUE TITLE
Click on another item won't hide the user drop down (Compared to Chrome and Firefox)

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2550]
https://www.screencast.com/t/b2VHMggPGfY

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click Menu > Work > Tracks 
4. Click on User avatar
5. Click Menu > Work > Tracks > Competitive programming or any other

**Expected:** Should hide the user drop down

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** IE11 | Microsoft Edge 44.17763.1.0

**Reproducibility Rate:** 3/3

**Comment by nithyaasworld** [comment]
similar to https://github.com/topcoder-platform/community-app/issues/2513
