### ISSUE TITLE
'More' drop down menu remains opened after selecting other menu items

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2551]
**Reproduction steps:**

1. Open the test URL and log in 
2. Click on 'Work' in the header
3. Zoom in 175%
4. Click on the 'More' drop down menu in the header
5. Click on other menu items (for example, 'Compete')

**Expected result:** 
The 'More' drop down menu hides after the user selects a different menu item in the header

**Actual result:** 
The 'More' drop down menu remains open even after selecting other menu items in the header

**Frequency:** 5/5

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80

**Resolution:** 1600 x 900

![screenshot8](https://user-images.githubusercontent.com/45698232/59140939-7cc6aa80-8959-11e9-95b0-588e80e01b9a.png)

**Comment by nithyaasworld** [comment]
similar to https://github.com/topcoder-platform/community-app/issues/2518
