### ISSUE TITLE
Sub menu and main menu both displayed at the same time

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2552]
https://www.screencast.com/t/rbbjjLTSp

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait )
3. Tap Menu > Work
4. Go to Landscape view
5. Tap Compete > Main menu and Sub menu both displayed at the same time
6. Tap Tracks > Main menu and Sub menu both displayed at the same time
7. Tap Community > Main menu and Sub menu both displayed at the same time

**Actual:** Sub menu and main menu both displayed at the same time

**Expected:** Should hide the main menu

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch

**Browser:** Chrome 75.0.3770.80

**Comment by nithyaasworld** [comment]
same as https://github.com/topcoder-platform/community-app/issues/2498
