### ISSUE TITLE
At help page,it ask you to login again

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2553]
**Describe the bug**
When you go to help from the dropdown, it goes to help page but it ask you to login again.

**To Reproduce**
1. Go to 'right side dropdown'
2. Click on 'help'
3. It redirect to help page but you can see at right side it ask you to login again.
4. click on sign in
5.Login page opens

**Expected behavior**
It should not ask you to login again

**Screenshots**
![chrome_bdIDaYIDYK](https://user-images.githubusercontent.com/5110867/59141821-44fb4980-89d1-11e9-8159-03f050622acf.png)

**Desktop (please complete the following information):**
 - OS: Window7
 - Browser :-chrome
 - Version 7

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
Out of scope
