### ISSUE TITLE
When you click on profile dropdown,unable to go back to home screen

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2555]
**Describe the bug**
When you click on profile dropdown,unable to go back to home screen at Ios.No back button enabled.

**To Reproduce**
1. Go to 'right profile dropdown'
2. Try to go Back to home screen
3. Back button disabled.

**Expected behavior**
Back button should be enabled or have option to go back to home page

**Screenshots**
![Copy of IMG_7960](https://user-images.githubusercontent.com/5110867/59142860-0e79fa80-89e2-11e9-8cbc-a506ef10324a.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [ iOS12.0.1]
 - Browser [Mobile Ios chrome browser]
 - Version [12.0.1]

**Additional context**

**Comment by nithyaasworld** [comment]
duplicate
