### ISSUE TITLE
Notification Screen doesnot have setting icon and back button on Ios device

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2556]
**Describe the bug**
Notification screen does not have back arrow icon and setting icon on Ios device

**To Reproduce**
1. Go to 'right profile dropdown'
2. Click on 'Notification'
3. Dont have back button and setting icon on Ios device

**Expected behavior**
Notification screen should have setting icon and back arrow option

**Screenshots**
<img width="375" alt="File_001" src="https://user-images.githubusercontent.com/5110867/59142964-809f0f00-89e3-11e9-92c3-6cd9563d526b.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [ iOS12.0.1]
 - Browser [Mobile ios chrome browser]
 - Version [12.0.1]

**Additional context**

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
