### ISSUE TITLE
Sub community dropdown is hiding the Switch to business option

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2557]
**Describe the bug**
Sub community dropdown is hiding the Switch to business option from user profile menu

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges?
2. Click on filters button
3. Click on drop down near user name
4. Notice the Sub community dropdown is hiding the Switch to business option from user profile menu

**Expected behavior**
Option should be visible

**Screenshots**
![Sub community error](https://user-images.githubusercontent.com/29533254/59143505-b47d3300-89e9-11e9-86ef-c1f1334db3f6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75.0.3770.80 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
Duplicate of https://github.com/topcoder-platform/community-app/issues/2405
