### ISSUE TITLE
Notification page has logout option on Ios device

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2558]
**Describe the bug**
Notification pagehas logout option on IOS Device

**To Reproduce**
1. Go to 'right profile dropdown'
2. Click on 'notification'
3. Notification page has logout option

**Expected behavior**
Logout option should not be available in notification page

**Screenshots**
![IMG_7962](https://user-images.githubusercontent.com/5110867/59143703-299d3800-89eb-11e9-86e8-a6f8d6279477.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [iOS12.0.1]
 - Browser [mobile ios chrome browser]
 - Version [12.0.1]

**Additional context**

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
