### ISSUE TITLE
"Notification settings" button is not working at notification screen on ios device

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2560]
**Describe the bug**
"Notification settings" button is not working at notification screen on ios device

**To Reproduce**
1. Go to 'right profile dropdown menu'
2. Click on 'notification'
3. Click on 'Notification settings'

**Expected behavior**
Notification setting button should work

**Screenshots**
![IMG_7962](https://user-images.githubusercontent.com/5110867/59143790-31111100-89ec-11e9-9017-bfb4e92a347f.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iPhone6]
 - OS: [e.g. iOS12.0.1]
 - Browser [Mobile chrome browser]
 - Version [12.0.1]

**Additional context**

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
