### ISSUE TITLE
[General] User is not navigating back to previous link visited

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2561]
**Describe the bug**
The user is not navigating back to the previous link visited.

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Click on 'Work'
3. Click on 'Community'
4. Click on 'TCO'
5. Page is navigating to 'https://www.topcoder.com/community/member-programs/topcoder-open/'
6. Click Back button in the browser.
7. User is not shown the old state of the page i.e which is selected manner.

**Expected behavior**

Old state of the page with menus and submenus to be rendered after navigation.

**Screenshots**
![Navigation_Compete_TCO](https://user-images.githubusercontent.com/13567734/59143812-a7157800-89ec-11e9-9a80-805b3a09d648.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [74]

**Additional context**
This is for all navigation generally using Work menu.

**Comment by luizrrodrigues** [comment]
@nithyaasworld For now add **Backlog** to this one.

2 existing issue will fix that: #2395 and #2453

**Comment by luizrrodrigues** [comment]
This one already fixed with #2395 and #2453
