### ISSUE TITLE
Text for Logout is showing in InitCaps

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2562]
**Describe the bug**
Text for Logout is showing in InitCaps and it is not the same in Marvel App

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Profile

**Expected behavior**
**Log out** is expected, instead of **Log Out**.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59143871-da95d980-89cf-11e9-88b2-06a405f83011.png)

**Desktop:**
**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
As designed. Please check https://marvelapp.com/89423f8/screen/54465717
