### ISSUE TITLE
My Dashboard not found

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2563]
**Describe the bug**
**My Dashboard** not found

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Profile

**Expected behavior**
Menu should have **My Dashboard** option.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59143899-5728b800-89d0-11e9-970d-6f0c26d48c8e.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
You are comparing with the mobile design. Please check: https://marvelapp.com/89423f8/screen/54465717
