### ISSUE TITLE
Unwanted Text is displayed below for a second when you scroll on Notification page 

### ISSUE THREAD

**Issue by coderHacker** [topcoder-platform/community-app#2564]
**Describe the bug**
Unwanted Text is displayed when you scroll on Notification page 

**To Reproduce**
1. Go to ' Profile dropdown'
2. Click on 'Notification'
3. Scroll up and down

**Expected behavior**
unwanted text should not displayed on notification page

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [e.g. iOS12.0.1]
 - Browser [mobile ios chrome browser]
 - Version [12.0.1]

**Additional context**

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
