### ISSUE TITLE
Menu to have Help center

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2565]
**Describe the bug**
Menu to have Help center

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Profile

**Expected behavior**
Menu to have **Help center**. It is now showing as **Help** only.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59143976-2a28d500-89d1-11e9-9649-13358d7c6154.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
This is as per design. Please check: https://marvelapp.com/89423f8/screen/54465717
