### ISSUE TITLE
Account & Security to be displayed in user menu

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2566]
**Describe the bug**
Account & Security to be displayed in user profile menu

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Profile

**Expected behavior**
Account & Security option to be available under user profile menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59144055-1cc01a80-89d2-11e9-8b85-af9e3ba85659.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
Duplicate of https://github.com/topcoder-platform/community-app/issues/2523
