### ISSUE TITLE
Hover on Close has inappropriate text

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2568]
**Describe the bug**
Hover on Close has inappropriate text

**To Reproduce**
1. Open the test URL
2. Reduce the window size of browser until you see Menu bar at the top left.
3. Click on Menu Bar.
4. Hover on Close " X " symbol and observe

**Expected behavior**
Hovering on  Close " X " symbol should not display any inappropriate text.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59144154-a6bcb300-89d3-11e9-8414-9819390beec8.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
similar to https://github.com/topcoder-platform/community-app/issues/2559

**Comment by satkanhub** [comment]
@nithyaasworld Even though the UI issue is similar, the issue is highlighted for different object. Is this still a duplicate ?

**Comment by nithyaasworld** [comment]
Yes.

Please see the challenge details where it states:
If the same issue is found on some other elements/levels/screens, club it into one single bug with all the details of the issue occurrence and log as one single bug.
