### ISSUE TITLE
Resizing the chrome browser has different screens of User profile menu

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2569]
**Describe the bug**
Resizing the chrome browser has different screens of User profile menu. Maximum screen is showing colored user profile menu. On reducing the window size, it displays a plain user profile menu.

**To Reproduce**
1. Open the test URL and login
2. Click Work
3. Click on the User Profile
4. Keep reducing the window size of browser and observe

**Expected behavior**
Resizing the browser should not change the view for user profile menu.

**Screenshots**
Full sized window
![image](https://user-images.githubusercontent.com/51492004/59144320-8fcb9000-89d6-11e9-9221-882d23822124.png)

Reduced Sized window
![image](https://user-images.githubusercontent.com/51492004/59144330-af62b880-89d6-11e9-8ecc-a99f390df25a.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
As designed
