### ISSUE TITLE
[$40] - Can't download the submissions from 'Winners' tab instead code displayed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#257]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Click on the 'Winners' tab

- Click Download from 'johan_92'

Actual Result(s)
-----------------------------------------------------------------
- Can't download the submissions from 'Winners' tab instead code displayed

Expected Result(s)
-----------------------------------------------------------------
- Must able to download the submissions; if not must display a validation message

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
{
  "error": {
    "name": "Unauthorized",
    "value": 401,
    "description": "Authentication credentials were missing or incorrect.",
    "details": "Authentication details missing or incorrect."
  },
  "serverInformation": {
    "serverName": "TopCoder API",
    "apiVersion": "0.0.1",
    "requestDuration": 4,
    "currentTime": 1503627989177
  },
  "requesterInformation": {
    "id": "5602cfacfa335587c7c709df698a47c5c3cd62e6-UAoaXpOHTwfCnR1e",
    "remoteIP": "123.231.111.23",
    "receivedParams": {
      "submissionType": "original",
      "apiVersion": "v2",
      "submissionId": "238671",
      "action": "downloadDesignSubmission"
    }
  }
}

**Comment by sdgun** [comment]
![46](https://user-images.githubusercontent.com/4592712/29697181-2d172982-896b-11e7-8fde-9e7e511b2a22.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points
