### ISSUE TITLE
[Community][Blog] The url is not navigating to topcoder-dev.com/blog

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2570]
**Describe the bug**
The blog url is navigating to topcoder.com/blog instead of topcoder-dev.com/blog

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges?'
2. Click on 'Work'
3. Click on  ''community"
4. Click on "Blog".
5. The Page is navigating to topcoder.com/blog

**Expected behavior**
The Page should be navigating to topcoder-dev.com/blog like other links.

**Screenshots**
![Navigation_Community_Blog](https://user-images.githubusercontent.com/13567734/59144352-5f92ea00-89f4-11e9-8427-bd014b1193b9.jpg)
![Navigation_Community_Blog1](https://user-images.githubusercontent.com/13567734/59144355-66216180-89f4-11e9-8a8e-131b7a93af89.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [74]

**Additional context**
This is about the URL navigation

**Comment by nithyaasworld** [comment]
@luizrrodrigues Hope we are covering this as part of another bug! Please confirm. Thanks.

**Comment by luizrrodrigues** [comment]
@nithyaasworld looks like no blog setup to test-community-app server:
https://test-community-app.topcoder-dev.com/blog/

But issue #2395 will fix that.

**Comment by nithyaasworld** [comment]
Thanks @luizrrodrigues for all the help!

I will mark this one as Accepted to credit the reporter.

**Comment by luizrrodrigues** [comment]
This one was fixed in #2395
