### ISSUE TITLE
blank screen when clicked on Competitive programming

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2572]
**Describe the bug**
Redirected to a blank screen when clicked on Competitive programming menu
**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Click on 'compete menu after clicking on work menu'
3. Click on Competitive programming submenu

**Expected behavior**
it should redirect successfully.

**Screenshots**
![redirect](https://user-images.githubusercontent.com/29533254/59144654-3411fe80-89f8-11e9-8a0b-d0c44227fa49.png)

**Desktop (please complete the following information):**
 - OS:windows10
 - Browser Chrome
 - Version:75.0.3770.80

**Smartphone (please complete the following information):**

Logs:
[crash logs.txt](https://github.com/topcoder-platform/community-app/files/3268465/crash.logs.txt)

**Comment by nithyaasworld** [comment]
It says to wait. I dont see any error in your screenshot.

Moreover, its Out of Scope.
