### ISSUE TITLE
UI: All the tabs are in Capital Letters in "Switch to Business" Window.

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2573]
**Describe the bug**
All the tabs under Switch to Business Window "MY PROJECTS", "GETTING STARTED", "HELP" in Capital letters .

**To Reproduce**
1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer 
3. Click on dropdown next to User profile pic
4. Click on "Switch to Business Window"
5. Displays the tabs in capital letters

**Expected behavior**
Should be displayed as "My Projects", "Getting Started", "Help".

**Screenshots**
Attached

<img width="1084" alt="Screenshot 2019-06-08 at 1 41 22 PM" src="https://user-images.githubusercontent.com/41059603/59144883-d2529400-89f9-11e9-949d-9eb7750cd488.png">

<img width="1440" alt="Screenshot 2019-06-08 at 1 41 46 PM" src="https://user-images.githubusercontent.com/41059603/59144950-bb607180-89fa-11e9-8c92-07ba9cf68bdd.png">

**Desktop (please complete the following information):**
 - OS: MacOS (10.14.5)
 - Browser : Safari
 - Version : 12.1.1 (14607.2.6.1.1)

**Smartphone (please complete the following information):**
 NA

**Comment by nithyaasworld** [comment]
Out of Scope
