### ISSUE TITLE
Search Challenges Text box and Search button goes missing when chrome window is resized

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2574]
**Describe the bug**
Search Challenges Text box and Search button goes missing when chrome window is resized

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges' in normal browser window size
2. Reduce the browser window size
3. Notice that Search Challenges Text box and Search button goes missing

**Expected behavior**
Search option should be available

**Screenshots**
![Search](https://user-images.githubusercontent.com/29533254/59144888-eb5b4500-89f9-11e9-8705-6e0320dc88e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.80

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
Out of Scope
