### ISSUE TITLE
search button is highlighted on mouse hover though the button is disabled

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2575]
**Describe the bug**
Search button is highlighted on mouse hover though the button is disabled, as there is no text entered in search challenge text box.
This confuses user , as it looks like button is enabled.

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges?
2. Hover mouse on Search icon 
3. Notice that the search button is highlighted, giving impression that it is enabled.

**Expected behavior**
Since the text box is empty search icon should not be highlighted 

**Screenshots**
![search highlight](https://user-images.githubusercontent.com/29533254/59144989-493c5c80-89fb-11e9-9cea-2b884173a25b.png)

**Desktop (please complete the following information):**
 OS: Windows 10
Browser Chrome
Version 75.0.3770.80

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nithyaasworld** [comment]
Out of scope
