### ISSUE TITLE
UI : WORK is in Capital letters, unless it is an abbreviation of something.

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2576]
**Describe the bug**
UI : WORK tab is in Capital letters, unless it is an abbreviation of something.

**To Reproduce**
1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Main window displays "WORK" in capital letters.

**Expected behavior**
Should be represented as Work unless "WORK" is an abbreviation of something.

**Screenshots**
Attached

<img width="1440" alt="Screenshot 2019-06-08 at 2 40 37 PM" src="https://user-images.githubusercontent.com/41059603/59145060-8ead5980-89fc-11e9-8894-b8b0d177c118.png">

Desktop (please complete the following information):

OS: MacOS (10.14.5)
Browser : Safari
Version : 12.1.1 (14607.2.6.1.1)
Smartphone (please complete the following information):
NA

**Comment by nithyaasworld** [comment]
Sorry, it is as designed :)
