### ISSUE TITLE
seeing few options twice - About/Contact/Help/Privacy/Terms

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2579]
**Describe the bug**
seeing few options twice - About/Contact/Help/Privacy/Terms

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. Scroll down to the end
3. Seeing the options twice at the botton and also on the right(see screenshot)

**Expected behavior**
Menu/link can be at one place only

**Screenshots**
![image](https://user-images.githubusercontent.com/29533254/59145364-717a8a00-8a00-11e9-9784-ce08ee7e51a4.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 75.0.3770.80

**Comment by nithyaasworld** [comment]
Out of scope
