### ISSUE TITLE
[$10] - Profile URL have extra part '/design' in 'Submission' tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#258]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Click on the 'Submission' tab

- Click 'chamdi' from the submissions

Actual Result(s)
-----------------------------------------------------------------
- Profile URL have extra part '/design' in 'Submission' tab
- https://www.topcoder.com/member-profile/chamdi/design

Expected Result(s)
-----------------------------------------------------------------
- Must remove the '/design' part from the URL or must navigate to the design portfolio of the users instead profile page
- https://www.topcoder.com/member-profile/chamdi

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![47](https://user-images.githubusercontent.com/4592712/29697280-cc21ae94-896b-11e7-8969-8477949fee76.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
