### ISSUE TITLE
Naming convention is inconsistent for mouse hover text for social media icons

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2580]
**Describe the bug**
Naming convention is inconsistent for mouse hover text for social media icons

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. Select any project and navigate to challenge page (eg.https://test-community-app.topcoder-dev.com/challenges/30055052)
3. Observe the mouse hover text for social media icons

**Expected behavior**
Naming convention should be same throughout the application.

**Screenshots**
![image](https://user-images.githubusercontent.com/29533254/59145506-82c49600-8a02-11e9-9c32-0a78ecafebfe.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 75.0.3770.80

**Comment by nithyaasworld** [comment]
Out of Scope
