### ISSUE TITLE
[Mobile] Navigation dropdown has UI issue when user is not logged in

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2581]
**Describe the bug**
when user not signed in, the work submenus has UI issue.

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges?'
2. Click on 'Hamburger menu.
3. Click on Work.
4. Tap on Compete.
5. Observe the dropdown issue near Compete submenu.

**Expected behavior**
The dropdown should not has UI issue near to submenu for example (Compete)

**Screenshots**
![Navigation_Community_Compete_dropdown_mobile](https://user-images.githubusercontent.com/13567734/59146430-8f012100-8a0b-11e9-8ada-2dcc06ee32c0.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [8.0.2]
 - Browser [Chrome]
 - Version [74]

**Additional context**
This is happening for all the submenus

**Comment by nithyaasworld** [comment]
Duplicate
