### ISSUE TITLE
[General] Logo is not navigating to Home Page

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2582]
**Describe the bug**
Logo near the Hamburger menu is not navigating to home page.

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges?
2. Click on Topcoder logo
3. Observe whether its navigable.

**Expected behavior**
Selecting logo should be navigable.

**Screenshots**
![Navigation_logo](https://user-images.githubusercontent.com/13567734/59146482-79d8c200-8a0c-11e9-94e3-548382540756.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [74]

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [8.0.2]
 - Browser [Chrome]
 - Version [74]

**Additional context**
Logo is not navigable.

**Comment by nithyaasworld** [comment]
Duplicate
