### ISSUE TITLE
504 Gateway Time-out when clicked on Forums

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2584]
**Describe the bug**
504 Gateway Time-out when clicked on Forums

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. Navigate to community->Forums
3. Observe the error.

**Expected behavior**
User should be navigated to respective page successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/29533254/59146898-81e73080-8a11-11e9-87f1-4e143ee66db5.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 75.0.3770.80

Console logs:
17:16:39.036 api.segment.io/v1/m:1 POST https://api.segment.io/v1/m net::ERR_TUNNEL_CONNECTION_FAILED
17:17:20.599 apps.topcoder-dev.com/forums/:1 GET https://apps.topcoder-dev.com/forums/ 504
17:17:20.665 Navigated to https://apps.topcoder-dev.com/forums/

**Comment by nithyaasworld** [comment]
Out of Scope
