### ISSUE TITLE
Secondary menu arrow is off when zooming out

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2585]
**Reproduction steps:**

1. Open the test URL and log in
2. Zoom in 200%
3. Click on 'Work' > 'Tracks'
4. Zoom out while observing the arrow connecting the secondary menu to the 'Tracks' section in the header

**Expected result:** 
The arrow connecting the secondary menu to the header points to the center of the selected section in the header

**Actual result:** 
The arrow connecting the secondary menu to the selected section in the header gets misaligned when zooming out

**Frequency:** 5/5 

**Device/Browser/OS:** 

Device: Laptop

OS: Windows 10 pro 64-bit

Browser/s:
Chrome 75.0.3770.80
Firefox 67.0.1

**Resolution:** 1600 x 900

![screenshot9](https://user-images.githubusercontent.com/45698232/59148677-cbf3f600-89c0-11e9-8818-9e08d4398bd0.png)

**Comment by nithyaasworld** [comment]
duplicate
