### ISSUE TITLE
Incorrect Active State Position

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2587]
**Describe the bug**
Incorrect Active State Position

**To Reproduce**
1. Open the test URL in 250% zoom in chrome browser and log in
2. Click on Menu bar at the left
3. Observe the Menu Active state position on the screen

**Expected behavior**
Active positionting should be appropriate.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59150146-363b8380-8a1f-11e9-84a8-909b9f6af6d8.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
duplicate
