### ISSUE TITLE
Appearance of MORE tab is not happening correctly

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2588]
**Describe the bug**
Appearance of MORE tab is not happening correctly

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Keep zooming the browser and you will observe **More** tab in some zoom level. In my case it appeared at 175%.
4. Keep zooming the browser and you will observe **More** tab disappearing in next zoom level. In my case it disappeared at 200%.

**Expected behavior**
**More** tab appearance should be constant

**Screenshots**
100% Zoom
![image](https://user-images.githubusercontent.com/51492004/59150380-ccbd7400-8a22-11e9-8b70-c0a01a34f515.png)

175% Zoom
![image](https://user-images.githubusercontent.com/51492004/59150362-9122aa00-8a22-11e9-956e-e6ecef88dc99.png)

200% Zoom
![image](https://user-images.githubusercontent.com/51492004/59150369-a5ff3d80-8a22-11e9-926e-53883e1e0650.png)

**Desktop:** 
 - OS: Windows 10 Home
 - Browser : Chrome 
 - Version :  75.0.3770.80

**Comment by nithyaasworld** [comment]
Same as https://github.com/topcoder-platform/community-app/issues/2543
