### ISSUE TITLE
submissions  link is  not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#259]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?

- Scroll down to  past challenge 

- In past challenge section click submissions   link 

- Observe  

Actual Result(s)
-----------------------------------------------------------------
it redirects to viewRegistrant page 

Expected Result(s)
-----------------------------------------------------------------
  should show  submissions   tab properly  

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

![screenshot-community-app topcoder com 2017-08-25 08-02-59](https://user-images.githubusercontent.com/3225433/29697316-f04301a6-896b-11e7-851f-a965bea98b9f.png)

**Comment by birdofpreyru** [comment]
Dublicates #240
