### ISSUE TITLE
Dark Mode not found for menu under WORK

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2593]
**Describe the bug**
Dark Mode not found for menu under WORK, whereas it is available in other menu paths like WORK->Community

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Observe the menu path to see if it is in Dark Mode / Light Mode
4. Click on Community
5.  Observe the menu path to see if it is in Dark Mode / Light Mode

**Expected behavior**
Dark Mode should be consistent across all the menu paths.

**Screenshots**

![20190609_083416](https://user-images.githubusercontent.com/51492004/59155854-c9150600-8a91-11e9-8103-47f48ccec760.jpg)

![20190609_083553](https://user-images.githubusercontent.com/51492004/59155857-d16d4100-8a91-11e9-96f5-d796bea34aa3.jpg)

**Smartphone:**
 - Device: Samsung 
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment]
same as https://github.com/topcoder-platform/community-app/issues/2592

Application currently has light mode
