### ISSUE TITLE
User profile menu is having different view while switching the orientation

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2595]
**Describe the bug**
User profile menu is having different view while switching the orientation

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Profile
4. Observe the Menu
5. Switch your mobile to Landscape view and observe the user profile menu.
6. You will observe Switch to BUSINESS is available in Landscape view.

**Expected behavior**
User profile menu should be consistent irrespective of the orientation for mobile users.

**Screenshots**
Portrait
![20190609_085408](https://user-images.githubusercontent.com/51492004/59156095-ec41b480-8a95-11e9-982c-e2112b9ceda5.jpg)

Landscape
![20190609_085426](https://user-images.githubusercontent.com/51492004/59156098-f82d7680-8a95-11e9-81c8-e1bb65699543.jpg)

**Smartphone:**
 - Device: Samsung 
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment]
duplicate

**Comment by satkanhub** [comment]
@nithyaasworld Can you help me with the reference number please. I tried to check, could not succeed.

**Comment by nithyaasworld** [comment]
https://github.com/topcoder-platform/community-app/issues/2450

**Comment by satkanhub** [comment]
@nithyaasworld The issue observed in this ticket is that user view keeps changing while user switches the orientation. In the referenced ticket, it talks about SWITCH to BUSINESS unavailable in user profile menu. There is no ticket raised apart from mine, about the user menu changing while user switches the orientation. Let me know, if I missed any.

Thanks

**Comment by nithyaasworld** [comment]
Hey @satkanhub You are missing a big thing here! Mobile has different view and web has different view. Please carefully go through the Marvel  app link provided in the Test Phase documents forum.
