### ISSUE TITLE
[$10] - Large empty space displayed right side of the page in 'Submission' tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#260]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30057469/?type=design

- Click on the 'Submission' tab

- Check the submission arrangement

Actual Result(s)
-----------------------------------------------------------------
- Large empty space displayed right side of the page in 'Submission' tab

Expected Result(s)
-----------------------------------------------------------------
- Page can have 4 column submission item layout

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![48](https://user-images.githubusercontent.com/4592712/29697356-3a6652ec-896c-11e7-8892-df837b53b3ca.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
