### ISSUE TITLE
[General] Default focus is not in the first option of the menu.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2600]
**Describe the bug**
After selecting work default focus is not in the first option of the menu.

**To Reproduce**
1. Go to  https://test-community-app.topcoder-dev.com/challenges
2. Click on 'Work'
3. Observe whether the "Compete' menu is selected by default.

**Expected behavior**
'Compete' menu should be selected by default.

**Screenshots**
![Navigation_default](https://user-images.githubusercontent.com/13567734/59159347-f4c1db80-8ae5-11e9-9320-b6f16c0a56d7.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [8.0.2]
 - Browser [Chrome]
 - Version [74]

**Additional context**
This is about the default focus of submenus.

**Comment by nithyaasworld** [comment]
Not in design. Only if you have already selected  the compete section, it will show the selection-indicator.
