### ISSUE TITLE
[Notifications] Notifications close button is not aligned Properly.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2601]
**Describe the bug**
Notification close button appearance and alignment is not good.

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Click on 'Login'
3. Enter Username and Password credentials''
4. Click on drop down near the profile logo.
5. Click on the Notifications(0).
6. Observe the Close

**Expected behavior**
Notification close button should be good in appearance and alignment for closing.

**Screenshots**

![Notification_Closebutton_new](https://user-images.githubusercontent.com/13567734/59159407-dd372280-8ae6-11e9-9fc5-e367b320075b.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [8.0.2]
 - Browser [Chrome]
 - Version [e.g. 74]

**Additional context**
Notification menu icons should be good in appearance.

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
