### ISSUE TITLE
[Notifications] No Notification close/ back button present.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2602]
**Describe the bug**
Notification page doesn't have close or back buttons.

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Click on 'Login'
3. Enter Username and Password credentials.
4. Click Login.
5. Click on Profile logo dropdown.
6. Click on Notifications(0).
7, Observe whether close or back button is present or not.

**Expected behavior**
Close or back button should be present in the Notifications page.

**Screenshots**
![Notification_Closebutton](https://user-images.githubusercontent.com/13567734/59159488-e379ce80-8ae7-11e9-92be-f8c8f0d267e0.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [8.0.2]
 - Browser [Chrome]
 - Version [74]

**Additional context**
This is to improve overall UI feature for Notification Page in mobile.

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
