### ISSUE TITLE
Sub menus are not expanded when user switches the orientation

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2603]
![image](https://user-images.githubusercontent.com/42398485/59159566-34aaa380-8a91-11e9-945c-878aeb361285.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Tracks/Compete or Community > Expand the submenu
5. Go to Landscape view

**Actual:** Submenus are not expanded when user switches the orientation

**Expected:** Should enable the submenu because the 'Track' is already selected

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch

**Browser:** Chrome 75.0.3770.80

**Comment by LieutenantRoger** [comment]
Hi @luizrrodrigues 

Are you able to reproduce ? I seemed not able to

**Comment by LieutenantRoger** [comment]
Up

**Comment by luizrrodrigues** [comment]
Checking

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Thanks for checking this one, again looks like already fixed with other ticket.

**Comment by nithyaasworld** [comment]
Cannot reproduce in production env too

**Comment by luizrrodrigues** [comment]
@nithyaasworld Please add QA Pass here

**Comment by luizrrodrigues** [comment]
@nithyaasworld I think we good to close this one.
