### ISSUE TITLE
[Notification] Notification settings button is not navigable in Notifications Page

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#2604]
**Describe the bug**
Notifications settings Page is not navigable.

**To Reproduce**
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Click on 'Login'
3. Enter Username and Password credentials. Click Login.
4. Click on Profile logo.
5. Tap Notifications(0).
6. In the Notifications Page tap Notification settings.
7. Notification settings Page is not navigating to any page.

**Expected behavior**
Notifications settings button should be responsive to the user.

**Screenshots**
![Notifications_Notificationsettings](https://user-images.githubusercontent.com/13567734/59159544-b7ab1880-8ae8-11e9-8500-8636d22f54b4.jpg)

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [8.0.2]
 - Browser [Chrome]
 - Version [74]

**Additional context**
This is about the responsiveness of Notification settings button.

**Comment by nithyaasworld** [comment]
Notification is not part of this Bug Hunt.
