### ISSUE TITLE
"General" theme support for Contentful components

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#2607]
Extract a new theme(inheriting current TCO19) called "General" for `contentBlock` and `Banner` components.

**Comment by kkartunov** [comment]
Playground: https://community-app.topcoder.com/examples/contentful/viewport/5X7Hh6yfySd1rO3ktxWXfI
Source: https://app.contentful.com/spaces/b5f1djy59z3a/entries/5X7Hh6yfySd1rO3ktxWXfI

**Comment by sushilshinde** [comment]
Deployed on prod
