### ISSUE TITLE
winners link is not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#261]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?

- Scroll down to  past challenge 

- In past challenge (TCO RUX - 72H Banking User Interface Design Challenge) winner section click +2 circle 

- Observe  

Actual Result(s)
-----------------------------------------------------------------
it redirects to challenge page 

Expected Result(s)
-----------------------------------------------------------------
  should show  winners tab properly  

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by karthikbecse** [comment]
![screenshot-community-app topcoder com 2017-08-25 08-06-14](https://user-images.githubusercontent.com/3225433/29697374-64196d72-896c-11e7-92a4-c532d268fe1f.png)

**Comment by birdofpreyru** [comment]
Dublicates #206
