### ISSUE TITLE
Regarding Verified Badge Tooltip

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2612]
**To Reproduce**
1. Go to https://www.topcoder.com/members/luizrrodrigues or to any member profile page
2. Hover over the Verified Skill Badge (Blue Tick present under some of the skills)
3. Check the Tooltip

**Actual behavior**
It shows some unknown value

**Expected behavior**
It could say something useful like "This Skill is Verified" on hover.

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/59248586-7a599e80-8c40-11e9-9adf-3d6841d6905a.png)

**Comment by Oanh-and-only-Oanh** [comment]
@gurmeetb, we want to use this tooltip to explain to members how to get their skills verified.

"Skills are verified when members win challenges with different Skills tags."

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh @nithyaasworld we have the PR ready for this, will work with @sushilshinde to get it deployed tomb.

**Comment by gurmeetb** [comment]
@nithyaasworld we have this deployed here - https://beta-community-app.topcoder.com/members/gurmeetb

Please verify and confirm and will work with @sushilshinde tomm to move to PROD.

**Comment by nithyaasworld** [comment]
@gurmeetb This looks good. 

@Oanh-and-only-Oanh is looking to re-phrase the sentence to convey the message in a more clear way.

**Comment by Oanh-and-only-Oanh** [comment]
@gurmeetb, feedback is that the phrasing could be clearer. 
Can we change to "This member has won a challenge using this skill"

**Comment by gurmeetb** [comment]
> This member has won a challenge using this skill

Sure, will change the message.

**Comment by gurmeetb** [comment]
@nithyaasworld as discussed with @Oanh-and-only-Oanh we changed the tooltip to read `This skill was used to win a challenge`. 

This has been pushed to DEV, as confirmed by @sushilshinde around 3 hrs back. I am not able to load profile, maybe due to other profile issue we had on DEV, @nithyaasworld can you give it a try once on dev and see if profile loads fine with SKILLS on your side on DEV ?

**Comment by nithyaasworld** [comment]
@gurmeetb I checked for the profiles TonyJ, mess, gurmeetb, nithyaasworld. None of the profiles have skills section displayed.

This is the URL I used to verify:  http://www.topcoder-dev.com/members/gurmeetb

Can you please confirm that I am testing at the right environment?

![image](https://user-images.githubusercontent.com/5114190/59843847-04a7ae00-9377-11e9-8d10-e1e989d1b642.png)

**Comment by gurmeetb** [comment]
@nithyaasworld yup looks like some issue with dev, working with @sushilshinde to get it deployed to beta for testing.

**Comment by gurmeetb** [comment]
@nithyaasworld this is deployed to https://beta-community-app.topcoder.com/members/gurmeetb

**Comment by nithyaasworld** [comment]
It looks good @gurmeetb 

We can close this ticket once this has been moved to production.

Thanks.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh @nithyaasworld This was deployed to PROD. Please help verify and close this. Thanks

**Comment by nithyaasworld** [comment]
Thanks @gurmeetb for following this up!

Verified in Production.

![image](https://user-images.githubusercontent.com/5114190/60250495-61a9e380-98e4-11e9-8abc-86a54c517c4b.png)
