### ISSUE TITLE
General Theme - Table - Formatting Update

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2614]
Please see the table in [Rodeo 2](https://community-app.topcoder.com/examples/contentful/viewport/4GDArUQpRx3jOmrjYAJgo0) as an example.

<img width="603" alt="Screen Shot 2019-06-11 at 12 42 19 PM" src="https://user-images.githubusercontent.com/1373998/59302448-d7595280-8c48-11e9-9d7a-0a136f4b5e7d.png">

In the CSS for <td> for the first-child we have it set to `padding-left:10px`
Please set the first-child for <th> to the same property.

We would also like to see more space between columns, so please edit the "padding" property from `20px 10px 20px 0` to `20px 50px 20px 0`

**Comment by kkartunov** [comment]
waits for prod
https://community-app.topcoder-dev.com/examples/contentful/viewport/4GDArUQpRx3jOmrjYAJgo0
waits for prod
