### ISSUE TITLE
Newsletter Archive - Formatting Fixes

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2615]
Just a few minor fixes to what you have on our [dev Newsletter Archive](https://community-app.topcoder-dev.com/examples/contentful/viewport/1IbkLrXJLA75fbzVl27PVz) page.

**Padding**
Please create a spacing of 10px between each of the entries.

**Link Color**
The link color IS the correct color (#006dea) however there is some kind of overlay somewhere that makes the color lighter than it should be.  Please find and remove the overlay so that it shows it's true color.

**Comment by kkartunov** [comment]
waits for prod
