### ISSUE TITLE
[$60]"Find member by Username or Skills" Search box not working

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2616]
**To Reproduce**
1. Go to www.topcoder.com/challenges
2. Click on the search icon present at the top right corner
3. Search by any user or skill

**Actual behavior**
It shows the error "Oops! There was an error."

**Expected behavior**
It should show the matching result.

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/59344691-393eb880-8d2c-11e9-9d57-154cab22b9a9.png)

**Comment by sandhiyakavi** [comment]
Search box is working fine in Prod now.Fetching both related username and skills.

![image](https://user-images.githubusercontent.com/55895538/78347079-8a6eb000-75bd-11ea-80ea-4ab3bf098bcd.png)

![image](https://user-images.githubusercontent.com/55895538/78347092-90649100-75bd-11ea-8c78-b2c7b7b30540.png)

cc: @SathyaJayabal
