### ISSUE TITLE
TaaS Group - Need a way to add private communities as filter on the community app

### ISSUE THREAD

**Issue by iScreamByte** [topcoder-platform/community-app#2619]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iScreamByte** [comment]
![image](https://user-images.githubusercontent.com/4011121/59426716-7a030400-8df6-11e9-91d4-1ba9f30959b7.png)

We need a way to communicate with the TaaS team about private challenges launched just for the TaaS group.

**Comment by iScreamByte** [comment]
Details 
name = TaaS Group - GnG
security = private, require login
challenge filtering = filter on the group
group_id = 20000313 

cc: @ajefts , @luizrrodrigues

**Comment by nithyaasworld** [comment]
@ajefts @iScreamByte This is set with P4 label ( Resolve within 2 weeks). Please change the label accordingly, if this has to be of some higher Priority.
