### ISSUE TITLE
Unable to login with the correct password, when the user changes his/her email address in TopCoder.

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#2630]
**Describe the bug**
Unable to login with the correct password, when the user changes his/her email address in TopCoder.
The bug is that while TopCoder allows email ID in the place of username during login, after a change in the email ID, this process isn't working as expected.

**To Reproduce**
1. Create a topcoder account with an email address. Get it verified. 
2. Now change the email address.
3. You will be sent emails to both the new and old email accounts. Confirm the process from both the email IDs.
4. Now you have a new email address to your topcoder account. Login with your new email ID as the username and your TopCoder password. You will get an error saying that this password is incorrect.
5. Now try logging in with your TopCoder Username (not email ID) and password. You can log in successfully.

**Expected behavior**
The user should be able to log in via latest email and password irrespective of the handle/username

**Additional context**
Some people may not remember the username but just remember the email ID that they use for login purposes. It is a little discomfort to use the Forgot Password option even when they are using the right password.

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh I am getting below error when clicking on the "Verify Email Change" link received in both the email accounts. I tried about 6 times with 2 different set of email ids.

![image](https://user-images.githubusercontent.com/5114190/59634210-dace6b80-916b-11e9-91d5-d2e7c4c26a3b.png)

**Comment by nithyaasworld** [comment]
For me, I am getting error when clicking "Send Verification email". 

![image](https://user-images.githubusercontent.com/5114190/59706365-f7c37700-921d-11e9-91d9-fae9582eff1e.png)

**Comment by nithyaasworld** [comment]
@m-yadav Can you please provide a Video of the issue, as the issue seems to be not reproducible for @Oanh-and-only-Oanh 

When recording, please keep browser console open, so we can see which API fails.

**Comment by RiteshTC** [comment]
@nithyaasworld 
This was reported by a member. We don't have any more information that we can provide.

**Comment by sandhiyakavi** [comment]
This issue is not applicable now as Change Email feature hided.
