### ISSUE TITLE
$15 | New Nav-  Tweak the challenge listing page to better fit the navigation

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#2632]
1. Go to 'https://test-community-app.topcoder-dev.com/challenges'
2. Click WORK
3. See below
![image](https://user-images.githubusercontent.com/47536078/59632407-036c4c00-90ff-11e9-8d99-fb73b4107de9.png)

**Expected behavior**
Remove the the Challenges/SRMs. See below
![image](https://user-images.githubusercontent.com/47536078/59632465-1e3ec080-90ff-11e9-9af5-99cae5ac6f98.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yoution** [comment]
@luizrrodrigues  please assign to me

**Comment by LieutenantRoger** [comment]
MR here: https://github.com/topcoder-platform/community-app/pull/3570

**Comment by nithyaasworld** [comment]
Verified in test env.

**Comment by macs054** [comment]
Verified in Beta
![image](https://user-images.githubusercontent.com/1199534/75419639-414d8f80-5971-11ea-81d2-4c650c614dca.png)

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1439" alt="Screenshot 2020-02-28 at 9 29 23 AM" src="https://user-images.githubusercontent.com/58783823/75509226-d782c380-5a0c-11ea-99cd-f46d0e50bbcb.png">
