### ISSUE TITLE
$40 | New Nav: Business related options should be enabled only for copilots and topcoder employees

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2639]
"Switch to Business" option in drop down User menu  - This should be visible only to copilots and topcoder employees. Disable for all other users.
![image](https://user-images.githubusercontent.com/47536078/59707810-43dbd080-91b8-11e9-9e32-58c03cfd6161.png)

**Comment by gets0ul** [comment]
Can I work on this?

**Comment by luizrrodrigues** [comment]
@gets0ul Yes, we need close this ASAP. 
Let me know if you have any questions.

**Comment by gets0ul** [comment]
@luizrrodrigues 
Where to look for data to check if a user is an employee?  
Is there any backend API providing this?  
What employee account to use for test? Do you have any?

**Comment by luizrrodrigues** [comment]
@gets0ul Sorry delay here. 

If API end point don't return Employee or Copilot status, just hide for now.

**Comment by gets0ul** [comment]
PR: #2643 
navigation-component: https://github.com/topcoder-platform/navigation-component/pull/24

**Comment by luizrrodrigues** [comment]
@gets0ul Need fix circleci errors

**Comment by luizrrodrigues** [comment]
@gets0ul Fixed accepted, good job.

Please fix CircleCI errors.

Thanks.

**Comment by gets0ul** [comment]
@luizrrodrigues Done, fixed.  
Thanks.
