### ISSUE TITLE
$20 | New Navigation- Change WORK top level navi to "COMMUNITY" 

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#2640]
1. Go to https://test-community-app.topcoder-dev.com/
2. See WORK as top level navigation
![image](https://user-images.githubusercontent.com/47536078/59715268-58c06000-91c8-11e9-9171-d6e9c1408a38.png)

Expected:
1. Change WORK top level navi to "COMMUNITY" 
2. Change "Community" tab to "Explore"

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld FYI

**Comment by marioskranitsas** [comment]
will this be open for pickup? @luizrrodrigues

**Comment by luizrrodrigues** [comment]
@marioskranitsas Status on this one?

**Comment by marioskranitsas** [comment]
it's completed. l'll create  a PR shortly. @luizrrodrigues

**Comment by luizrrodrigues** [comment]
@marioskranitsas I don't see PT, can you post here, please?

**Comment by marioskranitsas** [comment]
I'm sure I created a PR yesterday. Github was a bit unstable yesterday so that may be it. As you can see, my code was pushed yesterday. @luizrrodrigues

**Comment by marioskranitsas** [comment]
https://github.com/topcoder-platform/community-app/pull/2646

**Comment by nithyaasworld** [comment]
@luizrrodrigues Can we close this?

**Comment by luizrrodrigues** [comment]
@nithyaasworld Yes.
