### ISSUE TITLE
Show verification badge in the /settings/profile#skills page too

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2642]
Actual:
Currently Verified Skills badge is displayed only here: https://www.topcoder.com/members/nithyaasworld

Expected:
Verified Skills badge should also appear in this page too:  https://www.topcoder.com/settings/profile#skills

**Comment by gurmeetb** [comment]
@nithyaasworld this was deployed here - https://beta-community-app.topcoder.com/settings/profile#skills - can you help validate?

**Comment by nithyaasworld** [comment]
@gurmeetb It seems like the fix is no longer available in beta environment. Can you please re-deploy and let me know in slack?

Sorry that I missed to notice your above message.

**Comment by gurmeetb** [comment]
@nithyaasworld will work to get it back on env where you can test this, thanks for flagging.

**Comment by gurmeetb** [comment]
@nithyaasworld this is deployed to https://beta-community-app.topcoder.com/settings/profile#skills

Since beta would get busy from tonight for other planned stuff, can you please help test and provide feedback on this ASAP? Thanks

**Comment by nithyaasworld** [comment]
Thanks @gurmeetb But hovering on the tooltip, shows remove option.  Can we show only tooltip when hovering on the badge and not the remove option?

![image](https://user-images.githubusercontent.com/5114190/60256756-c454ac80-98ef-11e9-8cdc-032d0a2ca8dc.png)

**Comment by gurmeetb** [comment]
@nithyaasworld done, kindly validate.

**Comment by nithyaasworld** [comment]
Thanks @gurmeetb Verified.

**Comment by gurmeetb** [comment]
@Oanh-and-only-Oanh @nithyaasworld This is on PROD now, https://www.topcoder.com/settings/profile/#skills - kindly help verify and close the ticket.
