### ISSUE TITLE
$20 | The Navbar is always in logged in state

### ISSUE THREAD

**Issue by ya3ya6** [topcoder-platform/community-app#2647]
**Describe the bug**
Even when User is not logged in, `loggedIn` will set to true and account dropdown will set to `logged in` state.

**To Reproduce**
See The website (https://test-community-app.topcoder-dev.com/members/TonyJ) in a private window (or just log out.). you'll see the aaccount menu still is in logged in state.

**Probable Cause**
In this commit, rules is added to profile, without checking if its null or not. it will cause `is loggedIn` (which is  !profile ) to true:
https://github.com/topcoder-platform/community-app/commit/a157b323085b96929816c93f2b51418923b5688a

**Comment by luizrrodrigues** [comment]
@ya3ya6 @nithyaasworld 
This was fixed and deployed.
