### ISSUE TITLE
Remove Top Padding from Accordion Details

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#2659]
Please use [this page](https://community-app.topcoder.com/examples/contentful/viewport/1IbkLrXJLA75fbzVl27PVz) as an example.  Notice the 25px padding in the details section of the accordion (right side).  The top should match the starting point of the text on the left.  Please remove this padding.

**Comment by kkartunov** [comment]
https://community-app.topcoder-dev.com/examples/contentful/viewport/1IbkLrXJLA75fbzVl27PVz
