### ISSUE TITLE
New nav - Business links needs work

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#2662]
`Business` links are not working

URL - https://test-community-app.topcoder-dev.com/challenges

![image](https://user-images.githubusercontent.com/683231/60104206-9dc33400-977e-11e9-9dd3-1edf23a8a6fd.png)

**Comment by luizrrodrigues** [comment]
@sushilshinde I see links in design not match with existing site, all links need like existing site?

Design
![image](https://user-images.githubusercontent.com/7029641/60104843-a3962680-9738-11e9-8909-27a90ee98382.png)

Existing Site
![image](https://user-images.githubusercontent.com/7029641/60104874-b4469c80-9738-11e9-8e49-5cba30781a72.png)

**Comment by nithyaasworld** [comment]
CC: @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, let's go with this solution for the Business links.

Remain this BUSINESS level navigation (see below)
![image](https://user-images.githubusercontent.com/47536078/60124020-962f6b00-973d-11e9-8211-bb49134ea7fe.png)

to what is currently in production (See below)
![image](https://user-images.githubusercontent.com/47536078/60124056-ae06ef00-973d-11e9-961b-65b5c1c0365c.png)

Then have the top level BUSINESS links navigation to the the pages in production now.
![image](https://user-images.githubusercontent.com/47536078/60124160-e0b0e780-973d-11e9-95f6-9612fc6e0833.png)

The BUSINESS secondary menu will have the same treatment as what we do with data science page on community app.

Let me know if you have any questions.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh All clear.

**Comment by luizrrodrigues** [comment]
New requirements was send in Slack
- when they visit community side, then they will see the new navigation
- BUSSINESS/COMMUNITY toggle will always show. but COMMUNITY will be default.
- When BUSINESS is clicked, route to www.topcoder.com
- no sub menu. no top level menu for Business even. take out
- clicking BUSINESS links to www.topcoder.com

**Comment by nithyaasworld** [comment]
> New requirements was send in Slack
> 
> when they visit community side, then they will see the new navigation
> BUSSINESS/COMMUNITY toggle will always show. but COMMUNITY will be default.
> When BUSINESS is clicked, route to www.topcoder.com
> no sub menu. no top level menu for Business even. take out
> clicking BUSINESS links to www.topcoder.com

This has been verified.

**Comment by nithyaasworld** [comment]
Verified again
