### ISSUE TITLE
Regarding Payments and Forums link testing

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2668]
In our Test Environment, Clicking on Community --> Payments and Clicking on Explore --> Forums are re-directing to dev environments and they are not working.

So I am not sure how to **make sure** that Payments and Forums would work after deploying our Navigation V1 into Production.

**Comment by nithyaasworld** [comment]
This is No: 5 and No: 7 in https://github.com/topcoder-platform/community-app/issues/2663

**Comment by luizrrodrigues** [comment]
@nithyaasworld 
This working well with **Production** deploy:
[Screen Recording 2019-06-25 at 21.19.37.mov.zip](https://github.com/topcoder-platform/community-app/files/3327670/Screen.Recording.2019-06-25.at.21.19.37.mov.zip)

**Comment by nithyaasworld** [comment]
Thanks @luizrrodrigues for the video!
