### ISSUE TITLE
Some pages are not having the New Navigation

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2670]
1. Explore --> TCO is not having New nav
2. Explore --> Blog is not having the new nav 
3. User menu --> Help doesn't have new nav
4. User menu --> About Topcoder doesn't have new nav
5. In the NOT logged in state: Community second level menu pages are not having the new-nav as they are redirecting to prod/dev environment.

**Comment by nithyaasworld** [comment]
This is No: 6, 8, 11, 12, 14 in https://github.com/topcoder-platform/community-app/issues/2663

**Comment by nithyaasworld** [comment]
Some more pages that doesn't have new nav:
6: Tracks ->  Data science -> Datasets
7: Tracks -> Competitive Programming -> All menus present in that page

**Comment by luizrrodrigues** [comment]
1. Already fixed.
2. Already fixed.
3. Is a different app, navigation is different here.
4. This menu was removed
5. Already fixed.
6. Already fixed.
7. Valid.

@nithyaasworld @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @nithyaasworld, 

3. open this in a new and separate tab
7. leave these as they are. They are on a different app so it's fine that they open on a different tab.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues 
here is one more page that does not have the new nav
https://www.topcoder.com/my-challenges/?status=completed

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Thanks

**Comment by luizrrodrigues** [comment]
Note: Bellow is header used by some TC app:
https://github.com/appirio-tech/topcoder-app/blob/dev/app/layout/header/header.jade

**Comment by sandhiyakavi** [comment]
Closing as the issues are resolved now
