### ISSUE TITLE
SSF - Sub community has only "All" value

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2675]
Sub community has only "All" value in the dropdown

![image](https://user-images.githubusercontent.com/5114190/60173741-12ed4280-982d-11e9-96ba-a8682a5d3cdd.png)

Expected: It should have values like in the production

**Comment by nithyaasworld** [comment]
This has occurred earlier and reported here: https://github.com/topcoder-platform/community-app/issues/2381

**Comment by sushilshinde** [comment]
That's a different problem, should be resolved after merge with regular branch.
