### ISSUE TITLE
Minor problems with the leaderboard component

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#27]
> loading-indicator component is not used correctly, it should be used in the LeaderboardPageContainer when loading the data. 
it should not be used in Podium component. 

> Besides, if there is only 1 or 2 users on leaderboard, the Podium component won't render it properly as it accesses comps[1] and comps[2] directly.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/11/2017 and back
