### ISSUE TITLE
winner section 2nd prize winner not shown 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#270]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges/30052058/?type=design

- Click Winners tab

- check 2nd prize 

Actual Result(s)
-----------------------------------------------------------------
2nd prize winner  missing  

Expected Result(s)
-----------------------------------------------------------------
  should show 2nd prize winner  missing  

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

![screenshot-community-app topcoder com 2017-08-25 10-02-12](https://user-images.githubusercontent.com/3225433/29699921-384040ce-897e-11e7-967d-74430e9f263a.png)

**Comment by birdofpreyru** [comment]
Dublicates #254
