### ISSUE TITLE
New Nav: My Profile is not getting loaded at times

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2704]
Steps:

**Please follow the steps exactly as below to reproduce:**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer
3. Click on User menu --> Settings
4. Observe that Profile screen is loaded 
5. Now click on Dashboard and then click on My Profile
6. Observe that it is stuck with loading symbol without loading the "My Profile"

![image](https://user-images.githubusercontent.com/5114190/60509295-3b23e800-9cea-11e9-9f66-7a00d27bdfd0.png)

**Comment by nithyaasworld** [comment]
[My Profile not loading.zip](https://github.com/topcoder-platform/community-app/files/3349908/My.Profile.not.loading.zip)

**Comment by nithyaasworld** [comment]
@luizrrodrigues Just checked in beta. This issue is still there. Kindly check.

cc: @sushilshinde @Oanh-and-only-Oanh

**Comment by luizrrodrigues** [comment]
@nithyaasworld Working fine here, what account you used to test?

**Comment by nithyaasworld** [comment]
It is dan_developer. Please try once following the exact steps as provided in the ticket. I was able to reproduce it when I tried a while before.

**Comment by luizrrodrigues** [comment]
Note: This only happen when access the Settings in dropdown menu

**Comment by nithyaasworld** [comment]
**Earlier reproduction video**, adding just for reference:

[my video.zip](https://github.com/topcoder-platform/community-app/files/3955911/my.video.zip)

**Comment by SathyaJayabal** [comment]
test

**Comment by SathyaJayabal** [comment]
Profile page is working fine now.
[2704_verification.mov.zip](https://github.com/topcoder-platform/community-app/files/3956694/2704_verification.mov.zip)

**Comment by SathyaJayabal** [comment]
Verified

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh This one already deployed in Prod
