### ISSUE TITLE
Tracks --> Competitive Programming --> Your SRMs throws 404

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2706]
1. Go to www.topcoder.com and login with valid user credentials
2. Go to www.topcoder.com/challenges and then go to Tracks --> Competitive Programming --> Your SRMs

Actual:
It shows 404 error

![image](https://user-images.githubusercontent.com/5114190/60513285-7aefcd00-9cf4-11e9-9c17-f2e49f7c5c1c.png)

**Comment by sandhiyakavi** [comment]
@SathyaJayabal  Not able to replicate the issue since the feature has been changed.

![image](https://user-images.githubusercontent.com/55895538/78329118-7c5d6700-759e-11ea-885c-b104c8a43c33.png)

**Comment by SathyaJayabal** [comment]
closing this as its obsolete now.
