### ISSUE TITLE
[$10] - MM challenges links are not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#271]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click 'Filter'

- Select 'MM' as Subtrack (http://community-app.topcoder.com/challenges?filter[subtracks][0]=Marathon%20Match)

- Click on a contest

Actual Result(s)
-----------------------------------------------------------------
- MM challenges links are not working

Expected Result(s)
-----------------------------------------------------------------
- Must open MM challenge details page

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![49](https://user-images.githubusercontent.com/4592712/29700180-06d1747a-8980-11e7-8174-1893b1da1690.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points. We should correct URLs for MM.

**Comment by rrandom** [comment]
Can I take this, Thanks

**Comment by rrandom** [comment]
Seems the url is correct in `community.topcoder.com`  but fails in `community.topcoder-dev.com`

**Comment by birdofpreyru** [comment]
@rrandom Why? I believe, prod and dev URLs differ only by base, and it is correctly configured for dev and prod environments in the config? The endpoints are supposed to be the same in any case?

**Comment by mohhasbias** [comment]
Looks like the endpoint returns different MM challenge from the current live site.

**Comment by birdofpreyru** [comment]
@mohhasbias What exactly is the difference?

**Comment by mohhasbias** [comment]
I can't tell the difference yet. It just return different json data.
