### ISSUE TITLE
$75 | Implement only one `secondaryMenu` and add flag `logged`

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#2719]
@luizrrodrigues as discussed in Slack https://topcoder.slack.com/archives/GL67E1K8W/p1562249685014200 let's please implement only one `secondaryMenu` and add flag `logged`

> it looks that navi menu component wrongly searches for secondaryMenuForLoggedInUser and secondaryMenuForGuest on each level. This need to change as it is a bad design. You can see if those:
https://github.com/topcoder-platform/community-app/blob/e3209b3ee460a0d2f08d58ee99e13472e46ac913/config/default.js#L225
https://github.com/topcoder-platform/community-app/blob/e3209b3ee460a0d2f08d58ee99e13472e46ac913/config/default.js#L240
missing deeper levels of navis do not render the secondary menu. For example the 2dn one from the tests page! (edited) 
> Please, extract/rafactor secondaryMenuForLoggedInUser and secondaryMenuForGuest as one time menu properties
> Make just one secondaryMenu and add flag logged

**Comment by bappapatra** [comment]
I would like to pick it up

**Comment by bappapatra** [comment]
I am unassigning my self. Its open for pickup. I am assigning myself to different issue, since cant access slack. Thanks.

**Comment by LieutenantRoger** [comment]
Hi @luizrrodrigues  the slack archive conversion is not accessible, please advise how to see the detail.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Update issue description above. Please check and let me know if have any question.

**Comment by LieutenantRoger** [comment]
Could you clarify where's the 2nd test page ?  Per my testing, the SecondaryMenu is always rendered no matter I login or not.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Please check this:

https://github.com/topcoder-platform/community-app/blob/107840d8ed0ecd598e5ef2aec37be71621eba3c4/config/default.js#L237,L263

**Comment by LieutenantRoger** [comment]
Ok, so we just need to merge them and add logged flag , correct ?

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Yep, so each menu item will have 3 ways to show:

- Logged
- Guest
- Both

**Comment by LieutenantRoger** [comment]
What do you mean by `Both` ?  The menu showing is either from logged in or from Guest

**Comment by luizrrodrigues** [comment]
Yep, I'll show to logged or Guest

**Comment by LieutenantRoger** [comment]
MR here:  

Community app: https://github.com/topcoder-platform/community-app/pull/3559

Navigation_Component repo: https://github.com/topcoder-platform/navigation-component/pull/93

**Comment by nithyaasworld** [comment]
Verified in test env

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1003" alt="Screenshot 2020-02-27 at 11 27 04 AM" src="https://user-images.githubusercontent.com/58783823/75416366-26b8ed80-5954-11ea-839c-95ccc9390b30.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="982" alt="Screenshot 2020-02-28 at 9 34 16 AM" src="https://user-images.githubusercontent.com/58783823/75509422-86270400-5a0d-11ea-9e02-88568092d236.png">
