### ISSUE TITLE
New Nav - Selection indicator looks odd in some places

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2728]
In the following screens, the selection indicator looks odd

Screen1: Tracks --> Data Science
Screen2: Tracks --> competitive programming
Screen3: Explore --> Statistics

![image](https://user-images.githubusercontent.com/5114190/60968509-e233ff80-a33a-11e9-9557-f48ed26d9839.png)

**Comment by SathyaJayabal** [comment]
Verified and closed
![Uploading Screenshot 2019-12-16 at 6.50.01 PM.png…]()

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1405" alt="Screenshot 2020-01-29 at 12 49 43 PM" src="https://user-images.githubusercontent.com/58783823/73335589-dd627900-4295-11ea-8411-b84b361853a5.png">
