### ISSUE TITLE
[$10] - keyboard shortcuts button not shown properly 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#276]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges

- Click filters 

- Select date

- observe keyboard shortcuts button   

Actual Result(s)
-----------------------------------------------------------------
keyboard shortcuts icon not fit for the layout 

Expected Result(s)
-----------------------------------------------------------------
 should fit the layout 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

![screenshot-community-app topcoder com 2017-08-25 12-44-06](https://user-images.githubusercontent.com/3225433/29703438-322105c4-8993-11e7-9351-f649b524e4c3.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
We should correct the style of this button, to make it look better.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru any design spec for this?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh no, just add some more padding, whatever. My concern with this button now is that the question symbol is touching the edge of the shaded background, so it looks goofy.

**Comment by birdofpreyru** [comment]
Or, may be make it a square button with a smaller question symbol.
