### ISSUE TITLE
[MSFT-48] [Registration] A <noscript> element is present for Facebook

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#2769]
**Steps to Reproduce**
1. Go to https://accounts.topcoder.com/member/registration
2. Inspect Element
3. Observe no-Script element.

**Expected Result**
A <noscript> element should not be  present.

**Actual Result**
Inspect element is showing like this : 
<noscript>
<img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=1174423269336130&amp;ev=PageView&amp;noscript=1
https://www.facebook.com/tr?id=1174423269336130&amp;ev=PageView&amp;noscript=1
">
</noscript>

**Device**: Desktop/Labtop
**Operating System**: macOS
**Browser**: Chrome

**WCAG Category**: 4. Robust
**WCAG Level**: A
**WCAG Success Criterion**: 4.1.2 Name, Role, Value
**Screen Reader Used**: 
**Accessibility Audit Tool used**: Other

**Attachment**

**Comment by mishacucicea** [comment]
This is debatable, no script is good in case javascript is disabled.

**Comment by crazyk07** [comment]
Agreed.
