### ISSUE TITLE
[$30] - keyboard shortcuts not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#277]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges

- Click filters 

- Select date

- use keyboard shortcuts  

Actual Result(s)
-----------------------------------------------------------------
keyboard shortcuts not working 

Expected Result(s)
-----------------------------------------------------------------
  must enable keyboard shortcuts 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-community-app topcoder com 2017-08-25 12-31-50](https://user-images.githubusercontent.com/3225433/29703241-58742766-8992-11e7-9780-5fe62d1c70fe.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
The shortcuts should work.

**Comment by karthikbecse** [comment]
@birdofpreyru it is tool issue see  http://airbnb.io/react-dates/  and check
