### ISSUE TITLE
[MSFT-64] [Member Log In][Edge] WCAG 2.0 A account member page check have one issue

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#2779]
**Steps to Reproduce**
1)  Got to the page "https://accounts.topcoder.com/member" in edge broswer.
2) Use to check accessibility compliance website 'http://www.cynthiasays.com/' and enter  menederoty things with webpage URL e.g. Email ID, Web Page URL(https://accounts.topcoder.com/member),
Compliance mode(WCAG 2.0A)
3) Tick the term and condition 
4) Submit the Test you site button and observe the scan output.

**Expected Result**
None of the issue found after scan the site

**Actual Result**
Found one issue related to the language of the page and HTML and XML:LANG attribute not defined.

**Device**: Desktop/Labtop
**Operating System**: Windows
**Browser**: Edge

**WCAG Category**: 3. Understandable
**WCAG Level**: A
**WCAG Success Criterion**: 3.1.1 Language of Page
**Screen Reader Used**: Other
**Accessibility Audit Tool used**: Achecker

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/pd-topcoder_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=8ab28edc%2Dd11f%2D4bb3%2Db9cf%2Da743b86a634f&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fpd%2Dtopcoder%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2FMSFT%2DTeams%2DQA%2FJune%202019%2F29%20Jun%2FTest%20Results%2FBug%20Videos%20%26%20Log%20Files%2Fkmurti%2FAccessibility%2F1

**Comment by mishacucicea** [comment]
might be fixed by #2783

**Comment by Oanh-and-only-Oanh** [comment]
closing because it's a duplicate bug
