### ISSUE TITLE
[$30] - Can enter invalid values to the 'Date range' and Save the filter

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#278]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click 'Filter'

- Enter 'ewrewr' to the Start and End Dates

- Click 'Save Filter'

Actual Result(s)
-----------------------------------------------------------------
- Can enter invalid values to the 'Date range' and Save the filter

Expected Result(s)
-----------------------------------------------------------------
- Must not allow invalid characters to the 'Date range'

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![50](https://user-images.githubusercontent.com/4592712/29703660-1b2d0f88-8994-11e7-852d-51366c20e15d.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
Not sure, whether we can do anything about it on our side, as it is a 3-rd party component, but if it is possible, let's fix it.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru it is not possible to prevent invalid inputs in the field. https://github.com/airbnb/react-dates/issues/232
but we can validate dates, then disable/enable save button. is it ok?

**Comment by sushilshinde** [comment]
Checked airbnb/react-dates package even their demo has this issue. 

I'm looking into solution, will update once its solved.

**Comment by sushilshinde** [comment]
Fixed and tested on desktop and mobile, will creating PR.
@birdofpreyru

**Comment by birdofpreyru** [comment]
Fixed by #466
