### ISSUE TITLE
[$30] - close button shown for Sub community dropdown box 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#279]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges

- Click filters 

- Select Sub community

- observe 

Actual Result(s)
-----------------------------------------------------------------
close button shown for dropdown value 

Expected Result(s)
-----------------------------------------------------------------
  remove close button 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

![screenshot-community-app topcoder com 2017-08-25 12-49-27](https://user-images.githubusercontent.com/3225433/29703679-3467a7a6-8994-11e7-8f69-406925983a75.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
I would say, let's leave this button for all communities (it makes sense to me, as it clears this filter). But, let's ensure that when it is clicked, the `All` element is selected in the field, and that one has no such button. (Not sure, whether it is doable, but it will be cool if we can do it).
