### ISSUE TITLE
[MSFT-76] [Register] Can't access social media login via keyboard

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#2790]
**Steps to Reproduce**
1. Go to https://accounts.topcoder.com/member/registration
2. Focus the cursor on the first name field and click tab till the selection reaches to social media icons

**Expected Result**
Can't access social media login via keyboard

**Actual Result**

Can't access social media login via keyboard

**Device**: Desktop/Labtop
**Operating System**: Windows
**Browser**: Chrome

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: Other

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/pd-topcoder_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=58da9b68%2Df2a3%2D45d2%2Dbbae%2D15abdfd0865b&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&sortField=Modified&isAscending=true&id=%2Fpersonal%2Fpd%2Dtopcoder%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2FMSFT%2DTeams%2DQA%2FJune%202019%2F29%20Jun%2FTest%20Results%2FBug%20Videos%20%26%20Log%20Files%2Fcodejam%2DAccessibility%2F38

**Comment by mishacucicea** [comment]
Fixed by #2834

**Comment by Oanh-and-only-Oanh** [comment]
closing because it's a duplicate bug
