### ISSUE TITLE
[$50] - ended date is wrong 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#281]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges/?

- scroll down to past challenges 

- check Github Helper Service challenge end date 

Actual Result(s)
-----------------------------------------------------------------
end date is sep 3 

Expected Result(s)
-----------------------------------------------------------------
shoud show end date properly 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1  64bit
- **Browser(s):** FF54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-community-app topcoder com 2017-08-25 12-54-11](https://user-images.githubusercontent.com/3225433/29703834-ef34bd4e-8994-11e7-89b0-21fbe6095983.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points. It looks specific to F2F: they can be completed, but it does not update the original finish date, introduced into Direct. We should add some logic, to use the actual completion date there.

**Comment by birdofpreyru** [comment]
Pay attention to #288 this should be also fixed in the timeline tooltip.
