### ISSUE TITLE
[$50] - Sort by: Time to submit will sort the list by Time to register

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#282]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Sort by: Time to submit in 'My Challenges'

- Check the sorted list

Actual Result(s)
-----------------------------------------------------------------
- Sort by: Time to submit will sort the list by Time to register

Expected Result(s)
-----------------------------------------------------------------
- Sort by: Time to submit must sort the list by Time to Submit

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by birdofpreyru** [comment]
Accepted, 3 points. I am not actually sure, in what order does it sort challenges now, but it looks working definitely wrong. Should be fixed.

**Comment by birdofpreyru** [comment]
Also pay attention to #286. Seems to be the same problem, so both should be fixed here.

**Comment by Colinh84** [comment]
@birdofpreyru Need some clarification on this. It appears the results ARE actually being sorted by time to submit correctly, though for "My Challenges" the results are listed in ASC order from least -> most time remaining and "Open for Registration" listings are sorted in DESC order from most -> least time remaining. See screenshot of where time to submit is listed:
![sort-order](https://user-images.githubusercontent.com/2287621/29736748-2041d2ea-89b9-11e7-9363-1a7279efea1b.png)

What is the correct order to sort these categories by (ASC or DESC time remaining)? Other than that order difference, the challenges are sorting correctly except for one stalled challenge shown at the top of the "open for registration" category.

**Comment by birdofpreyru** [comment]
@Colinh84 I better double-check tomorrow. But, in principle, I would expect that sorting by sumbmission time, would sort challenges by time left till the next submission deadline, from the first one to the last. In case of dev. challenges we have just one submission deadline, so it is clear; in case of design ones, we take as submission deadline the least of the times till checkpoint submission, and till the final submissition, and sort these from soonest, to the farthest.

**Comment by Colinh84** [comment]
@birdofpreyru Just checking if you have more information on the preferred sort order yet. Another thing I noticed is that in "My Challenges", there are also registered challenges listed that are past the submission phase. Should these be filtered out when sorting by "time to submit", or displayed and listed at the top, or bottom?

**Comment by birdofpreyru** [comment]
@Colinh84 No, if you don't see anything wrong with my previous msg, I think this should be the order. The challenges with completed submission phase, I guess, we should show in the very end, as they are probably the least useful for users who use this sorting.
