### ISSUE TITLE
[$20] - footer shown centre of the page while loading 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#285]
Steps to Reproduce

   
  - Goto http://community-app.topcoder.com/challenges/
  - observe while loading 

Actual Result(s)
footer shown centre of the page 

Expected Result(s)
Should show the footer properly 
 
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
   
![2017-08-25_1311](https://user-images.githubusercontent.com/3225433/29704345-0cbfcadc-8997-11e7-8518-10da6c8ed6d3.png)

**Comment by birdofpreyru** [comment]
Accepted 1 point. Indeed, it will be handy to ensure that footer cannot be higher than the bottom of window.
