### ISSUE TITLE
Sort By: Time to submit will display invalid results in Open for registration

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#286]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Sort by: Time to submit in 'Open for registration'

- Check the sorted list

Actual Result(s)
-----------------------------------------------------------------
- Sort By: Time to submit will display invalid results in Open for registration specially when the design challenges with checkpoints are in the list
- Check the challenge "Synergy - Campus Recruitment Web Application Design Challenge" it has +10 days for submission but it displayed in the middle of the result list

Expected Result(s)
-----------------------------------------------------------------
- Must calculate the correct submission time in design challenges and place them in the correct position

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![53](https://user-images.githubusercontent.com/4592712/29704460-8d800f42-8997-11e7-9f9c-36458cb0394e.jpg)

**Comment by birdofpreyru** [comment]
Looks quite like a dublicate of #282. But, let me accept and add 2 points for this
