### ISSUE TITLE
wrong Ends  date  shown 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#288]
Steps to Reproduce

   
  - Goto http://community-app.topcoder.com/challenges/
  - Check challenge end date 
  - move cursor on timeline 
  - observe  

Actual Result(s)
- wrong Ends  date  shown 

Expected Result(s)
- Should show Ends  date  properly 
  
Environment

    Device(s): Laptop
    Operating System: Windows 8.1  64bit
    Browser(s): FF 54.0.1

Image/Video/JS Log/Console Log 
![dsfdsf](https://user-images.githubusercontent.com/3225433/29704643-4a31d1fc-8998-11e7-99f8-806da3ff4ca8.png)

**Comment by birdofpreyru** [comment]
Looks like a semi-dublicate of #281, but I'll accept, 3 points.
