### ISSUE TITLE
[$10] - 3 digit values must comma separated to be consistent with the other locations

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#290]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30055839/?type=develop

- Check the first price

Actual Result(s)
-----------------------------------------------------------------
- 3 digit values are not comma separated
- $1900

Expected Result(s)
-----------------------------------------------------------------
- 3 digit values must comma separated to be consistent with the other locations
- $1,900

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![55 2](https://user-images.githubusercontent.com/4592712/29705826-592222b6-899d-11e7-85a7-81fb6a75bd3f.jpg)
![55 1](https://user-images.githubusercontent.com/4592712/29705827-5924bbac-899d-11e7-9409-80cbbec1a72a.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point. Right, the design specs also demands this separator.
