### ISSUE TITLE
Submission tab is not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#291]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30049794/?type=develop

- Click on Submission tab

Actual Result(s)
-----------------------------------------------------------------
- Submission tab is not working

Expected Result(s)
-----------------------------------------------------------------
- Must display the content when user click on the 'Submission' tab

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![56](https://user-images.githubusercontent.com/4592712/29706661-3a696d54-89a0-11e7-8de3-cad6915cb909.jpg)

**Comment by birdofpreyru** [comment]
I believe, it dublicates #208
