### ISSUE TITLE
[$40] - Registration deadline is missing

### ISSUE THREAD

**Issue by Vetteru** [topcoder-platform/community-app#292]
## Steps to Reproduce
- access to http://community-app.topcoder.com/challenges/30058958/?type=develop

## Actual Result(s)
- Registration deadline is missing

## Expected Result(s)
- Registration deadline is shown between "Started" and "Submission"

## Environment
```
Device(s): Laptop
Operating System: MacOS 10.12.6
Browser(s): Google Chrome 60.0.3112.101 (Official Build) (64-bit)
```

## Image/Video/JS Log/Console Log (If not attached here, Please check the comments section)
![screen shot 2017-08-25 at 17 27 29](https://user-images.githubusercontent.com/6219446/29706993-a8eb3992-89be-11e7-97f9-dc9d9789f4e9.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
I believe, we should add a bit of fancy logic here. In the `Next Deadline` text we should show Registration if user is not yet registered to this challenge, and Submission (or Checkpoint) if he has registered already. In the exandable panel we add registration deadline.
