### ISSUE TITLE
[$20] - Submission count is not displayed in the tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#294]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30056022/?type=design

- Click on Submission tab and check the count in the tab header

Actual Result(s)
-----------------------------------------------------------------
- Submission count is not displayed in the tab

Expected Result(s)
-----------------------------------------------------------------
- Submission count must displayed in the tab

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![57 2](https://user-images.githubusercontent.com/4592712/29709946-085b9826-89ac-11e7-8653-b9a7ece3bda0.jpg)
![57 1](https://user-images.githubusercontent.com/4592712/29709947-089722ba-89ac-11e7-878f-f320331122ea.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
