### ISSUE TITLE
Winning participants submission IDs won't match with the IDs in the Checkpoint page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#295]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30056022/?type=design

- Click on REGISTRANTS tab (You can see 1st, 2nd and 3rd all of them won checkpoint prizes - Green icon displayed in front of the Roudn 1 Submission)

- Eg: f0rc0d3r, picachui and nPixel

- Click on Winners tab

- Check the IDs of f0rc0d3r=#234920, picachui=#234901 and nPixel=#234910

- Click on Checkpoint tab

- Check the IDs there; non of the IDs found in the page (#234821, #234805, #234820, #234741, #234763)

Actual Result(s)
-----------------------------------------------------------------
- Winning participants submission IDs won't match with the IDs in the Checkpoint page
- There are 5 green marked icons and all three placements got that mark, when we check the IDs of the winning submissions from the 'Winners' tab and cross check it with the 'Checkpoint' tab won't found any match

Expected Result(s)
-----------------------------------------------------------------
- Winning participants submission IDs that have won the checkpoint price must match with the IDs in the Checkpoint page

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![58 2](https://user-images.githubusercontent.com/4592712/29710231-128dc39a-89ad-11e7-8bb2-0d61c202dc23.jpg)
![58 1](https://user-images.githubusercontent.com/4592712/29710232-12c4787c-89ad-11e7-905e-841b3073c8b6.jpg)

**Comment by birdofpreyru** [comment]
Not a bug, I believe, the submissions to checkpoints and to the final round are independent, thus having different IDs.
