### ISSUE TITLE
[$20] - [Common] Empty 2nd Prize value displayed for Design F2F Challenges

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#296]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058138/?type=design

- Check the 2nd place prize $0

Actual Result(s)
-----------------------------------------------------------------
- Empty 2nd Prize value displayed for Design F2F Challenges

Expected Result(s)
-----------------------------------------------------------------
- Must remove the 2nd Prize value displayed for Design F2F Challenges
- Compared with https://www.topcoder.com/challenge-details/30058138/?type=design

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![59 2](https://user-images.githubusercontent.com/4592712/29711364-0da90ce0-89b2-11e7-91ef-6bf88a0ce99f.jpg)
![59 1](https://user-images.githubusercontent.com/4592712/29711365-0da99340-89b2-11e7-8e6a-44b897046dac.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
