### ISSUE TITLE
[$10] - Empty Tool tip displayed for 'Studio Other' Challenges

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#297]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[subtracks][0]=Studio%20Other

- Hover over the 'O' icon

Actual Result(s)
-----------------------------------------------------------------
- Empty Tool tip displayed for 'Studio Other' Challenges

Expected Result(s)
-----------------------------------------------------------------
- Must display a tool tip text

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![60](https://user-images.githubusercontent.com/4592712/29712205-44ce564a-89b6-11e7-81c6-cbe29dfcdfd2.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

**Comment by iversonLv** [comment]
What description should for  'Studio Other' tooltip?

**Comment by birdofpreyru** [comment]
@vic-topcoder @ajefts How should we describe this category?

**Comment by vic-topcoder** [comment]
Good catch! We had a [track code document](https://docs.google.com/spreadsheets/d/14EEg-eHbiPdl6cGqXIdvNrQ27Xayb8u6JWHBVlaNI0s/edit?usp=sharing) and I think "Other" is misleading. It should be "Design" only as a generic term.

Let's try with this: "Generic design challenge". @ajefts feel free to overrule me.
