### ISSUE TITLE
[$10] - [DETAILS]layout is broken 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#298]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058662/?type=design

- observe description 

Actual Result(s)
-----------------------------------------------------------------
- image breaks the layout 

Expected Result(s)
-----------------------------------------------------------------
- should format the layout 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1 
- **Browser(s):** FF 54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![sadsad](https://user-images.githubusercontent.com/3225433/29712705-c1de8608-89b8-11e7-9c9b-ca72a0945366.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
I believe, we just should add `max-width` to the image styles, to ensure image sizes cannot be larger than the layout. Or, probably, to add `overflow` scrolling to make sure it is cut and can be scrolled. Or some combination of these.
