### ISSUE TITLE
[$20] - When scrolling while searching 'View more challenges' displayed in the search page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#299]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?filter[subtracks][0]=Front-End%20Flash&filter[subtracks][1]=Development

- While filtering Scroll down and then up

- Observe the page

Actual Result(s)
-----------------------------------------------------------------
- When scrolling while searching 'View more challenges' displayed in the search page

Expected Result(s)
-----------------------------------------------------------------
- Must not display such link while search because there there are no any items displayed also

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by daft300punk** [comment]
Checkout PR - https://github.com/topcoder-platform/community-app/pull/332
