### ISSUE TITLE
[$20] - Challenge description page code display layout issue

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#300]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30041383/?type=develop

- Scroll down to the content and check the code section

Actual Result(s)
-----------------------------------------------------------------
- Codes are displayed overlapped each lines

Expected Result(s)
-----------------------------------------------------------------
- Codes must display clearly as per the desin guideline

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
HTML Code as below;

``
<span class="small_info_spec" id="rswDetailedRequirements"><code><span style="background-color:white;">year (int),&nbsp; dayOfYear (int), latitude (double), longitude (double), [daytime in hours (double), optional ], other data (list of doubles, separated by "," and with "." as floating point delimiter)</span></code></span>
``

**Comment by sdgun** [comment]
![62](https://user-images.githubusercontent.com/4592712/29714002-be417a9a-89be-11e7-8536-24cf7ee9f4c6.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points, as it is not that easy to noticed (because such markup is not met on many challenge specs).
