### ISSUE TITLE
[$30] - '0' is missing (or "min" should be erased) at remaining time

### ISSUE THREAD

**Issue by Vetteru** [topcoder-platform/community-app#303]
## Steps to Reproduce
- access to http://community-app.topcoder.com/challenges (see challenges that end time is now)

## Actual Result(s)
- 5d min

## Expected Result(s)
- 5d 0min or 5d

## Environment
```
Device(s): Laptop
Operating System: MacOS 10.12.6
Browser(s): Google Chrome 60.0.3112.101 (Official Build) (64-bit)
```

## Image/Video/JS Log/Console Log (If not attached here, Please check the comments section)
![screen shot 2017-08-25 at 22 00 26](https://user-images.githubusercontent.com/6219446/29715299-b8a33b82-89e1-11e7-9025-90c96d93d420.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
That text should be properly formatted. If it is more than one day, we should show Xd YYh (i.e. days and hours); once it goes under one day, we should show XXh YYmin (i.e. hours + minutes), and when it goes under 1 hour, then minutes and seconds.

**Comment by twicoder** [comment]
PR #320
