### ISSUE TITLE
[FAST-52] [Firefox] Text parallel to the image but not use heading element

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3076]
**Steps to Reproduce**
1) Go to 'https://www.topcoder.com/community/accessibility-testing'.
2) 'An Inclusive World at Topcoder' Text appear heading above the image 
3) Text not use heading element.

**Expected Result**
Text should be use heading element ```<h1>- <h6>```

**Actual Result**
Text appears to be a heading but is not a heading element.

**Device**: Desktop/Labtop
**Browser**: Firefox

**WCAG Category**: 2. Operable
**WCAG Level**: AA
**WCAG Success Criterion**: 2.4.6 Headings and Labels
**Screen Reader Used**: Other
**Accessibility Audit Tool used**: Web Accessibility Toolbar (WAT)

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=2cd27847%2Dc944%2D4866%2Da87f%2D5eec4e505c52&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fkmurti%2FBug1

**Comment by hokienick** [comment]
It uses H1 now.
