### ISSUE TITLE
[FAST-13] Page must contain a level-one heading

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3098]
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Open DevTools (right click -> inspect)
3. In the Elements tab, open the search bar (Cmd+F on Mac)
4. Search for level-one heading, using xpath: //h1

**Expected Result**
The page or atleast one of its frames should contain a level-one heading

**Actual Result**
Page doesn’t contain <h1> element

**Device**: Desktop/Labtop
**Browser**: Chrome

**WCAG Category**: 2. Operable
**WCAG Level**: AA
**WCAG Success Criterion**: 2.4.6 Headings and Labels
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=2521ab22%2D4cea%2D4606%2Da210%2D50280914399c&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fyoctocode%2Fbug%207

**Comment by hokienick** [comment]
H1 applied to the banner
