### ISSUE TITLE
[FAST-64] Space between word separator / in paragraph

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3100]
**Steps to Reproduce**
1) Go to the page https://www.topcoder.com/community/accessibility-testing
2) Slide page and go to the So, what are the benefits? section 
3) In third para space between two word while using separator e.g. talk back / voice over,

**Expected Result**
No extra space if should fine if we using word separator.

**Actual Result**
Space between two word while using word separator /

**Device**: Desktop/Labtop
**Browser**: Firefox

**WCAG Category**: 1. Perceivable
**WCAG Level**: AA
**WCAG Success Criterion**: 1.4.12 Text Spacing
**Screen Reader Used**: 
**Accessibility Audit Tool used**: 

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=2cd27847%2Dc944%2D4866%2Da87f%2D5eec4e505c52&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fkmurti%2FBug7

**Comment by hokienick** [comment]
Space between separator and words have been removed.
