### ISSUE TITLE
[FAST-25] User can't access the sub-menus of Tracks and Community

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3107]
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Focus on the URL and press tab key until Tracks or Community selected
3. Use arrow or tab key to select the sub-menus

**Expected Result**

User should be able to access the sub-menus using arrows keys/ or tab keys

**Actual Result**
User can't access the sub-menus of "Tracks" and "Community"

**Device**: Desktop/Laptop
**Browser**: Chrome

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=0bf9d0fe%2Dbdaa%2D4af3%2Dad48%2Dd3fa9f0e20e1&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&sortField=Modified&isAscending=false&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fcodejam%2F8

**Comment by hokienick** [comment]
This ticket is now part of #3118
