### ISSUE TITLE
[FAST-2] User can't focus on the "COMPETE" and "COMMUNITY" items on the header using tab

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3108]
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Press tab key till the "COMPETE" and "COMMUNITY" items on the header are selected

**Expected Result**
User should be able to select all items on the header using tab

**Actual Result**
User can't focus on the "COMPETE" and "COMMUNITY" items on the header using tab

**Device**: Desktop/Labtop
**Browser**: Chrome

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=6b62afda%2Dc894%2D4ce2%2Da924%2D74186e1c15dc&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fdoremihong%2Fbug%204

**Comment by hokienick** [comment]
This ticket is now part of #3118

**Comment by PrakashDurlabhji** [comment]
@hokienick this has been already done by me in a PR.
