### ISSUE TITLE
[FAST-18] User can't focus on the 'Attachments' item using tab

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3110]
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Click on "Support" button (bottom-right)
3. Press tab key till the 'Attachments' item is selected

**Expected Result**
User should be able to select the 'Attachments' item using tab

**Actual Result**
User can't focus on the 'Attachments' item using tab

**Device**: Desktop/Labtop
**Browser**: Chrome

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=6b62afda%2Dc894%2D4ce2%2Da924%2D74186e1c15dc&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fdoremihong%2FBug%5F6

**Comment by hokienick** [comment]
This ticket is now part of #3118

**Comment by tc-mfikria** [comment]
@hokienick it cannot be fixed because the attachment field is on zendesk form which is not in `community-app` but fetch and initialized directly from topcoder.zendesk.com
