### ISSUE TITLE
[FAST-36] When user focus on the search button via tab key Focus is not visible

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3112]
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Press the tab key until search icon is selected

**Expected Result**
When user focus on the search button via tab key Focus should be visible by highlighting the icon with a blue border

**Actual Result**
When user focus on the search button via tab key Focus is not visible

**Device**: Desktop/Labtop
**Browser**: Chrome

**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=0bf9d0fe%2Dbdaa%2D4af3%2Dad48%2Dd3fa9f0e20e1&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&sortField=Modified&isAscending=false&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fcodejam%2F11

**Comment by hokienick** [comment]
This ticket is now part of #3118
