### ISSUE TITLE
Dashboard banner shows code when collapsed

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3123]
Dashboard banner shows code when collapsed

![image](https://user-images.githubusercontent.com/5114190/61928242-7934c480-af95-11e9-941c-7a8918c76ade.png)

**Comment by veshu** [comment]
@nithyaasworld Is this still reproducible? I can't reproduce this.

**Comment by nithyaasworld** [comment]
Yeah, this is not reproducible. Closing this. Thanks @veshu for checking.
