### ISSUE TITLE
I am not able to Add/Delete Skills and not able to save Email Preferences

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3140]
Issue1: In Settings --> Profile --> Skills: I am not able to add or remove Skills. Seeing the following error in the console.

![image](https://user-images.githubusercontent.com/5114190/61993144-f9862300-b084-11e9-9b54-672a8cb94d61.png)
![image](https://user-images.githubusercontent.com/5114190/61993149-10c51080-b085-11e9-92bf-62d7a408f6fe.png)

Issue2: In Settings -> Preferences --> Email: I am not able to change the preferences. Receiving error as below.

![image](https://user-images.githubusercontent.com/5114190/61993173-6ef1f380-b085-11e9-855f-b4f11264d6e6.png)

Note: When @sushilshinde checked, it worked for him. It seems to be an issue only for me as of now. When I checked the same function 2 days back, it worked for me too.

**Comment by codeMinter** [comment]
@nithyaasworld is this on DEV / TEST or PROD ?

**Comment by nithyaasworld** [comment]
This is on Production. I happened to see this when performing Smoke test for Accessibility in Beta.

**Comment by codeMinter** [comment]
@nithyaasworld can you re-try? Works fine for me on PROD and beta.

**Comment by nithyaasworld** [comment]
Yeah, just tried @codeMinter . I still see the same issue. Please find the video below.

[skills, email not working for me.zip](https://github.com/topcoder-platform/community-app/files/3439509/skills.email.not.working.for.me.zip)

**Comment by sushilshinde** [comment]
Something with @nithyaasworld 's account 

FYI... @urwithat

**Comment by cagdas001** [comment]
Username: same as the GitHub

I'm having the same issue when trying to add/remove skills

|  Frontend | API Response |
|---|---|
| ![2019-08-02_22-58-11](https://user-images.githubusercontent.com/28513447/62399814-c1e81100-b585-11e9-80e5-db36fe7b0ef9.png)  | ![2019-08-02_22-58-45](https://user-images.githubusercontent.com/28513447/62399820-c6142e80-b585-11e9-8a88-f146792567bf.png)  |

Tag ID is always `47`, even if I try to add/remove different skills.

The same issue also happens on Dev instance, on my side (with `TonyJ` account)

Here is the response for the dev instance

```json
{
  "id":"6127029e:16c2d9dbaab:-2bfe",
  "result":{
    "success":true,
    "status":400,
    "metadata":null,
    "content":"[\"Tag id 167 is not valid\", \"Tag id 272 is not valid\", \"Tag id 280 is not valid\", \"Tag id 303 is not valid\", \"Tag id 356 is not valid\", \"Tag id 375 is not valid\", \"Tag id 388 is not valid\", \"Tag id 406 is not valid\", \"Tag id 109 is not valid\", \"Tag id 309 is not valid\", \"Tag id 353 is not valid\", \"Tag id 360 is not valid\", \"Tag id 377 is not valid\", \"Tag id 130 is not valid\", \"Tag id 284 is not valid\", \"Tag id 248 is not valid\", \"Tag id 154 is not valid\", \"Tag id 187 is not valid\", \"Tag id 195 is not valid\", \"Tag id 123 is not valid\", \"Tag id 126 is not valid\"]"
  },
  "version":"v3"
}
```

**Comment by nithyaasworld** [comment]
Now the issue also occurs when trying to save Work entries for my account.

cc: @Oanh-and-only-Oanh 

![image](https://user-images.githubusercontent.com/5114190/69334663-3f44a800-0c81-11ea-8a11-2e0f189d835a.png)

**Comment by nithyaasworld** [comment]
@cagdas001 Can you please check your Skill's Add/Delete function and Work's Add/Delete function?

My Skill's Add/Delete function is working today but I still have issues with Work's Add/Delete function.

**Comment by cagdas001** [comment]
@nithyaasworld Just checked, both work fine. (including Edit functionality of Works)

**Comment by Oanh-and-only-Oanh** [comment]
@nithya @lakshmiathreya , can you confirm on your ends and close out ticket if we can?

**Comment by nithyaasworld** [comment]
Unfortunately, Work and Email preferences are still an issue for my account.

**Comment by cagdas001** [comment]
I had not checked the Email preferences/subscriptions before (had checked just Skills&Works), now I checked it too. It's also working fine on my end. (production environment - cagdas001 account)

Are you still getting a similar response from API? Or a different one this time?

**Comment by nithyaasworld** [comment]
Yeah, getting the same error response as before:

![image](https://user-images.githubusercontent.com/5114190/69654732-49a8dc80-109b-11ea-9f3e-820fa98a6898.png)

**Comment by nithyaasworld** [comment]
and This is the error I am getting when trying to add a new Work Experience.

![image](https://user-images.githubusercontent.com/5114190/69654932-9db3c100-109b-11ea-953a-b1dcd15775d9.png)

**Comment by lakshmiathreya** [comment]
Verified on Dev - Able to Add/Delete Skills, Email Preferences and Work Experiences.

**Comment by nithyaasworld** [comment]
Its not working for my account in Dev environment too. My Dev user credentials: nithyaasworld / appirio123

![image](https://user-images.githubusercontent.com/5114190/69697526-b27a6e00-1108-11ea-91e2-8791384f0b93.png)

**Comment by lakshmiathreya** [comment]
Thanks for the update @nithyaasworld. It worked for my account. @urwithat pls note ...

**Comment by urwithat** [comment]
The `Email Preferences` server in AWS is down, we are going to resolve this in AWS.

**Comment by urwithat** [comment]
Thank you for informing, the fix has been deployed to development environment

**Comment by urwithat** [comment]
We are working on passing the AWS dynamodb access via roles and not by passing tokens, for improving the overall security.

**Comment by urwithat** [comment]
This has been fixed

**Comment by nithyaasworld** [comment]
Thanks @urwithat Issue with the Member Work Addition is resolved and verified in Dev.

I will create a new issue to track the issue with the Email-Preferences.
