### ISSUE TITLE
Ability to tag images in Contentful

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#3205]
As the quest to become accessibility compliant, we will need images to be tagged on the page so that a screenreader can "read" it.

There are two way images appear in our page: ```<img> tags``` and "Choose Image" in Contentful.  We will need ways to include tags in both scenarios.

**Comment by kkartunov** [comment]
@hokienick 
Nice reference to follow https://www.oomphinc.com/notes/2019/01/images-alt-tags-out-loud-experience-oomph-inc/

For `<img>` we do support all attributes which include `alt` as well.
For "Choose Image" we need to add image tags field below it, correct?

**Comment by kkartunov** [comment]
demo: https://community-app.topcoder.com/examples/contentful/viewport/5CG0ObzaFavsxSAqYviNol
source: https://app.contentful.com/spaces/b5f1djy59z3a/entries/5CG0ObzaFavsxSAqYviNol

**Comment by kkartunov** [comment]
Done with 32b8f5086fce330f8cd905d81faa18e5b2d94c03
