### ISSUE TITLE
Need placeholder animation for submissions tab on details page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#3218]
This is only applicable to `mm-leaderboard` branch as of today.

This spinner experience

![Test-MM-For-Rated-Match 2019-08-15 13-27-02](https://user-images.githubusercontent.com/683231/63081561-86741c00-bf61-11e9-8564-62a6052d406a.png)

Should be replaced by place holder animation experience but it should imitate submission table structure
 
![Test-MM-For-Rated-Match 2019-08-15 13-29-09](https://user-images.githubusercontent.com/683231/63081213-b66eef80-bf60-11e9-8587-21e827f0528f.png)

**Examples** 

https://github.com/zalog/placeholder-loading

**Comment by rashmi73** [comment]
@sushilshinde will this be open later?

**Comment by sushilshinde** [comment]
@rashmi73 it's not approved yet, I'm adding my suggestion only.

**Comment by sushilshinde** [comment]
@Oanh-and-only-Oanh @cwdcwd @ajefts what do you guys think?

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde, let's go with this. 
https://github.com/zalog/placeholder-loading/blob/develop/docs/imgs/placeholder-loading-demo-1.gif
