### ISSUE TITLE
Able to un-register from a challenge after submitting to the challenge

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#3221]
**Describe the bug**
User is able to un-register from a challenge even after submitting to the challenge if the registration phase is open. 

**To Reproduce**
1. Go to 'https://www.topcoder.com/challenges/30096444' or any challenge which has the submission and registration phase open.
2. Click on 'register'
3. Submit to the challenge.
4. Unregister button is still active and the user can unregister from the challenge.

**Expected behavior**
User should not be able to unregister in case he/she has submitted to the challenge.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 77

**Note**

User "wleite" was able to unregister from the challenge "https://www.topcoder.com/challenges/30096444" even after submission on the challenge and has reported the issue.

**Comment by sandhiyakavi** [comment]
Tested in Prod. UnRegister button becomes inactive once the user submits for the challenge.

<img width="917" alt="unregister button_inactive" src="https://user-images.githubusercontent.com/55895538/78342962-c272f480-75b7-11ea-80e9-8c2c4f0d5434.PNG">

<img width="928" alt="submitted" src="https://user-images.githubusercontent.com/55895538/78342982-cd2d8980-75b7-11ea-9258-db9261a1508f.PNG">

cc: @SathyaJayabal

**Comment by SathyaJayabal** [comment]
Closing this as it. is no more reproducible.
