### ISSUE TITLE
New Submission Tab is showing `4` as a score if the submission's actual score is `-1`

### ISSUE THREAD

**Issue by dushyantb** [topcoder-platform/community-app#3262]
submission-id - `188fb59a-0f6a-4074-9345-6691c9f3f268`
challenge - `30095825`

<img width="1126" alt="Screenshot 2019-08-23 at 3 58 35 PM" src="https://user-images.githubusercontent.com/1861713/63593439-a6df4e80-c5d1-11e9-80b1-4d9930d24f6b.png">
<img width="1376" alt="Screenshot 2019-08-23 at 3 58 47 PM" src="https://user-images.githubusercontent.com/1861713/63593442-a6df4e80-c5d1-11e9-91c2-5f5f147a6d30.png">

**Comment by nithyaasworld** [comment]
Is this okay or should we show -1 instead of the dash?

![image](https://user-images.githubusercontent.com/5114190/64081147-86726b00-cd1a-11e9-9c75-bcb86ccd7de2.png)

**Comment by nithyaasworld** [comment]
@ThomasKranitsas @dushyantb @sushilshinde 

If the most recent provisional score is 0 for a user, then his final provisional score is displayed as dash. 
Expecting the Final Provisional score same as the user's most recent provisional score.


![image](https://user-images.githubusercontent.com/5114190/64155312-25e54a00-ce50-11e9-9f8e-028276fa49cf.png)

**Comment by nithyaasworld** [comment]
@sushilshinde @ThomasKranitsas @dushyantb  I think we haven't fixed this yet.

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh @lakshmiathreya @sushilshinde confirming that the issue stated in my last comment still exists.

**Comment by nithyaasworld** [comment]
Closing this as we have https://github.com/topcoder-platform/community-app/issues/3389 in open to address the issue with the final provisional score.
