### ISSUE TITLE
JOIN TOPCODER Registration Form Error Using GMail and Facebook Account

### ISSUE THREAD

**Issue by empaguia84** [topcoder-platform/community-app#3270]
**Describe the bug**
The design bug happened after failing to register and when the error message appeared: **"We weren't able to register you because of a system error. Please try again or contact support@topcoder.com."** in [](https://accounts.topcoder.com/member/registration). The First Name and Last Name fields was moved left, instead staying in the middle.

Here the screenshot:

![image](https://user-images.githubusercontent.com/28289169/63834412-da422480-c9a7-11e9-8a8f-0e39af4042b2.png)

**To Reproduce**
1. Go to 'https://www.topcoder.com/'
2. Click on 'Join TopCoder'
3. You will be rediected here 'https://accounts.topcoder.com/member/registration'
4. Scroll down, click Google
![image](https://user-images.githubusercontent.com/28289169/63834674-6fddb400-c9a8-11e9-9089-91e2e93f451a.png)
5. Popup appeared, choose your Google account
![image](https://user-images.githubusercontent.com/28289169/63834785-aa475100-c9a8-11e9-8627-97bcfa863436.png)
6. Type your Country,
![image](https://user-images.githubusercontent.com/28289169/63834835-c3e89880-c9a8-11e9-8a95-34ad930b7e7a.png)
7. Click JOIN
![image](https://user-images.githubusercontent.com/28289169/63834881-db278600-c9a8-11e9-873b-6e2398916a7e.png)
8. JOIN button will become Saving button upon processing
![image](https://user-images.githubusercontent.com/28289169/63834907-f0041980-c9a8-11e9-89b0-0e64b42a11bb.png)
9. and after a failed registration, the First Name and Last Name textbox were moved to the left.
![image](https://user-images.githubusercontent.com/28289169/63834995-2346a880-c9a9-11e9-9a80-4734aeba0e8d.png)

**Expected behavior**
The UI should be intact, not moved if a new message appeared, like the error message appeared up there.

**Screenshots**
Screenshot were already attached in each step to reproduce the behavior.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Google Chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

1. **Error 500** in https://api.topcoder.com/v3/users
2. **Error in** angular.js:15018 Error in registering new user Error: We weren't able to register you because of a system error. Please try again or contact support@topcoder.com.
    at n (auth.js:390)
![image](https://user-images.githubusercontent.com/28289169/63835383-e929d680-c9a9-11e9-980b-7c58dbcbbe3d.png)

**Comment by sandhiyakavi** [comment]
Closing the issue as it is not happening with current auth0 implementation.
