### ISSUE TITLE
Zurich subdomain challenge listing issue

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#3279]
Question (came up from Zurich): When we navigate to their challenge listing like this:
1. https://zurich.topcoder.com/challenges?communityId=zurich
We see the correct listing of only their challenges. However when they go here:
2. https://zurich.topcoder.com/challenges
We see all listings (as expected).
This has caused an issue in some cases where users are arriving at #2 url through other means. Zurich wants this view to also default to only the Zurich challenges.
I think this is would be a new feature.
The thought would be to update the community-app template capability to include a per community “default filter settings”, which would specify how the filter is set when arriving at [COMMUNITY-NAME].topcoder.com/challenges.
Thoughts on this? (good / bad / how hard would it be / …etc) 

On the behalf of @mtwomey @ajefts

**Comment by sushilshinde** [comment]
https://github.com/topcoder-platform/community-app/pull/3274

**Comment by lakshmiathreya** [comment]
Verified both urls on Prod - notice inconsistent behavior. 
Observations: (cc @nithyaasworld @sushilshinde @Oanh-and-only-Oanh @mtwomey @ajefts)
1. Both urls route to https://zurich.topcoder.com/challenges?communityId=zurich.
2. In incognito mode, however, initially, Challenge count is 53 and then eventually shows 48: would Zurich be fine with displaying Challenges prior to login? Also, we need to consistently display the correct number of challenges without any other intermittent counts.
3. Upon login, the Challenge Counts are displayed are different for each url though the final landing url is the same.

**Comment by lakshmiathreya** [comment]
@sushilshinde @Oanh-and-only-Oanh is this Issue being addressed? It would be high priority for Zurich? ...

**Comment by lakshmiathreya** [comment]
-- Verified that both urls result in presenting of Zurich challenges only - with correct Challenge counts. 
-- Also, in incognito, prior to login, Challenges are not displayed.
