### ISSUE TITLE
Size Problem with Profile Image

### ISSUE THREAD

**Issue by yillapens** [topcoder-platform/community-app#328]
**Steps to Reproduce**

1.  Goto http://community-app.topcoder.com/challenges/?bucket=past
2. Move cursor on some winners

**Actual Result(s)**
 
It seems that profile image has different size

**Expected Result(s)**

Should show the image in same size

**Environment**

- Device(s): MacBookPro13,2
- Operating System: macOS Sierra 10.12.5
- Browser(s): Safari 10.1.1

**Image/Video/JS Log/Console Log (If not attached here, Please check the comments section)**

<img width="834" alt="2017-08-26 10 11 21" src="https://user-images.githubusercontent.com/17176123/29737911-7aaf96d2-8a49-11e7-8154-471be954636a.png">

<img width="850" alt="2017-08-26 10 11 02" src="https://user-images.githubusercontent.com/17176123/29737915-8703cb6a-8a49-11e7-8397-8891281883a5.png">

<img width="839" alt="2017-08-26 10 10 41" src="https://user-images.githubusercontent.com/17176123/29737917-91c4876a-8a49-11e7-8426-47066ce8d04c.png">

**Comment by birdofpreyru** [comment]
Dublicates #251
