### ISSUE TITLE
Past Marathon Listings Not Usable

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3280]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.topcoder.com/challenges?filter[tracks][data_science]=true&bucket=past'
2. Wait for marathon matches to load
3. For me it either doesn't load, or it's REALLY slow.

**Expected behavior**
Past matches should load right away and all filter controls should work.

**Screenshots**

![image](https://user-images.githubusercontent.com/3812270/64178802-181fcc80-ce30-11e9-91b0-d0aced88bdde.png)

**Comment by ajefts** [comment]
@Oanh-and-only-Oanh @sushilshinde @cwdcwd This one is a pain point for us and fits into the DS priority.  Can we add it to the list for something we can fix in the short term?

**Comment by codeMinter** [comment]
@ajefts can you give a try here - https://beta-community-app.topcoder.com/challenges ?

**Comment by ajefts** [comment]
@codeMinter I'm still seeing the issue.  The challenges actually start to load after a while (more than a minute).  I see repeated API calls in the console that seem to be getting the next 50 challenges, so I'm assuming once it starts to find MM challenges it starts to display them.


![image](https://user-images.githubusercontent.com/3812270/65515124-ac6bd500-deac-11e9-82f6-66fd3a0ff62c.png)

My guess is that it's trying to get all past matches and then filtering in the front end for subtrack and tech tag = "Data Science"???  Can the API call do the filtering?

**Comment by sushilshinde** [comment]
Fix is here https://github.com/topcoder-platform/community-app/pull/3334

Beta is not free will deploy on test today.

@cwdcwd @ajefts

**Comment by lakshmiathreya** [comment]
The Past Marathon Listings are definitely seen at https://www.topcoder.com/challenges?filter%5Btracks%5D%5Bdata_science%5D=true&bucket=past - however loading latency issue continues to be seen.
fyi @ajefts @codeMinter @Oanh-and-only-Oanh @nithyaasworld @sushilshinde

**Comment by codeMinter** [comment]
@lakshmiathreya did you try this on test ?  The fix is deployed to test, can you try once there ?

**Comment by sushilshinde** [comment]
This is an issue was fixed on the wrong branch, it should be fixed in `hot-fix`

I opened another issue https://github.com/topcoder-platform/community-app/issues/3341

@codeMinter is covering that change, if fixed will deploy over the weekend

**Comment by codeMinter** [comment]
@sushilshinde @ajefts  how do we handle this ticket as we have covered the requirement in #3341  ?

**Comment by nithyaasworld** [comment]
@codeMinter @sushilshinde I am closing this as this has been verified in Production.

There is still an issue with loading if we apply any keyword filter or date-range filter along with DS filter. I will open a new issue for that.

**Comment by codeMinter** [comment]
Sure @nithyaasworld you can tag or assign it to me and will look into it. 

Thanks
