### ISSUE TITLE
Thrive - Search Bar Dropdown "View All Results" does not work on first click

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#3294]
If you use the search bar in the banner and type something that will start off the dropdown menu and you click "View all results" the dropdown disappears and nothing happens.

If you click on the search bar again to make the dropdown appear and click "View all results" again, it will direct you to the correct page.

The first click should have directed the user to the correct page.

**Comment by kkartunov** [comment]
@hokienick I am having difficulty to reproducing this one. We need to chat about it...

**Comment by kkartunov** [comment]
Canceled.
