### ISSUE TITLE
Almost Half of the Marathon Matches are not opening

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3305]
Almost half of the Marathon Matches are not opening for me.

Some examples:
https://www.topcoder.com/challenges/30095825
https://www.topcoder.com/challenges/30095824
https://www.topcoder.com/challenges/30095823
https://www.topcoder.com/challenges/30095821
https://www.topcoder.com/challenges/30095562
https://www.topcoder.com/challenges/30098568
https://www.topcoder.com/challenges/30098582
https://www.topcoder.com/challenges/30094323
https://www.topcoder.com/challenges/30101518

![image](https://user-images.githubusercontent.com/5114190/64600964-ab7d7280-d3d9-11e9-8800-34b9133788b3.png)

**Comment by nithyaasworld** [comment]
These challenges are not opening in incognito window too. So it should be affecting everyone.

**Comment by nithyaasworld** [comment]
CC: @sushilshinde @Oanh-and-only-Oanh

**Comment by dushyantb** [comment]
@nithyaasworld these all are completed MMs and for some reason, we had to move them in private group; and hence you are not able to access them.

this is not an issue... @sushilshinde

**Comment by nithyaasworld** [comment]
@dushyantb These are all present under **'Ongoing Challenges' bucket** except one of them. Please confirm if they still come under the private group.

**Comment by dushyantb** [comment]
Yes they are under private group
