### ISSUE TITLE
SSR: 'View more challenges' link is displayed though there is nothing more to view

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3312]
'View more challenges' link is displayed though there is nothing more to view

![image](https://user-images.githubusercontent.com/5114190/64693606-3ed7a600-d4b5-11e9-9d6c-3d85e82cbad1.png)

**Comment by nithyaasworld** [comment]
@sushilshinde @ThomasKranitsas

**Comment by SathyaJayabal** [comment]
tracking here #4964
