### ISSUE TITLE
Newsletters are not sent to subscribers

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3316]
In the Settings -> Preferences, Subscribe to all the newsletters. Check that the user is not receiving any of the newsletters.

![image](https://user-images.githubusercontent.com/5114190/65136179-c3ca3e80-da24-11e9-8217-fe5a24b7583c.png)

Also users have reported this in the Slack Support Channel:

![image](https://user-images.githubusercontent.com/5114190/65136263-e65c5780-da24-11e9-84de-41047a1114fa.png)

**Comment by nithyaasworld** [comment]
CC: @Oanh-and-only-Oanh @sushilshinde @codeMinter @Dara-K @ajefts

**Comment by nithyaasworld** [comment]
CC: @RiteshTC

**Comment by Dara-K** [comment]
Is there any update on this @RiteshTC ?

**Comment by RiteshTC** [comment]
@Dara-K It probably requires code fixes. Code fixes are managed by the product team and not by support.

**Comment by Dara-K** [comment]
@RiteshTC I understand. @ajefts can you look into fixing this please/ have someone from your team help with it?

**Comment by SathyaJayabal** [comment]
Closing this as we do not have this section now.
