### ISSUE TITLE
Dashboard: Clicking on Submit button present on the challenge card redirects to a blank page

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3329]
In Dashboard: Clicking on Submit button present on the challenge card redirects to a blank page

![image](https://user-images.githubusercontent.com/5114190/65555478-6a916c00-df4a-11e9-8fb2-7644d80c4446.png)

![image](https://user-images.githubusercontent.com/5114190/65555492-75e49780-df4a-11e9-9876-20f2a6c91198.png)

**Comment by nithyaasworld** [comment]
Confirming that this is still an issue

**Comment by sandhiyakavi** [comment]
My Active challenges tab is hided.
