### ISSUE TITLE
Dropdown Notification for Community

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3337]
# Overview

> Enable notifications for community members. These will be similar to what we have for Connect users.  The purpose is to keep members updated and aware of activities they are required to complete as well pushing info to them that might be of interest.

References

- Tech Requirements:  <https://docs.google.com/document/d/11JdLhu8ql1qqZqfrLIM-bJYYsDjcmzfhvOGDbRBymsM/edit>

- <https://docs.google.com/spreadsheets/d/1AMPSBj_wUdMM-hs9oaVRubSkhAnk3bKTjAxcDn8rx60/edit?ts=5cc888f3#gid=967851284>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1323423

**Comment by luizrrodrigues** [comment]
Notifications Popup is done and already merged with **community-app** _notifications_ branch.
Challenge: http://www.topcoder.com/challenges/30114259
Fixes (F2F): http://www.topcoder.com/challenges/30115261

Notifications Listings challenge is LIVE (submission deadline: 02.22.2020)
http://www.topcoder.com/challenges/30116087

**Comment by SathyaJayabal** [comment]
1. Can you provide the access to
https://docs.google.com/spreadsheets/d/1AMPSBj_wUdMM-hs9oaVRubSkhAnk3bKTjAxcDn8rx60/edit?ts=5cc888f3#gid=967851284

2. What are the states of the notifications in the pop-up?
There is "un seen" with a pink dot. There is "un read" with the grey dot. There seems to be another state "read", with no dot. What is the use of this state ? In connect( and in general) when a notification is read it is removed from the list. Will the notifications be removed when the related contest is completed or when the user closes the respective completed challenge notification?  
<img width="499" alt="Screenshot 2020-02-20 at 9 03 21 AM" src="https://user-images.githubusercontent.com/58783823/74899381-c4477680-53c2-11ea-88b3-6a51c1fbabea.png">

3. Should the "Mark All as Read" should be disabled once all the notifications are read? Same with the tick in the mobile view.
<img width="564" alt="Screenshot 2020-02-20 at 8 47 53 AM" src="https://user-images.githubusercontent.com/58783823/74899508-21432c80-53c3-11ea-9be1-6c11e09aebc3.png">

4. Mobile view: Will the notification icon and the number of notifications be always in pink or only if there are unread notifications? If not what is the colour for the other two states?
<img width="512" alt="Screenshot 2020-02-20 at 9 28 36 AM" src="https://user-images.githubusercontent.com/58783823/74899965-5308c300-53c4-11ea-885c-81d37dbc7bf0.png">

5. The same set of notifications are displayed when we reload the page, even though we have closed/read some of the notifications. Why are user actions not saved? Is it for testing purposes?


cc @luizrrodrigues cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
UI Issues:
1. The space between the notification icon and the pink dot seems more than the design
<img width="352" alt="Screenshot 2020-02-20 at 8 41 54 AM" src="https://user-images.githubusercontent.com/58783823/74900693-a54ae380-53c6-11ea-9944-8b766dadb425.png">
Design:
<img width="54" alt="Screenshot 2020-02-20 at 9 52 23 AM" src="https://user-images.githubusercontent.com/58783823/74900757-c3184880-53c6-11ea-895d-5a63aa969717.png">

2. The hover state background circle is not centered.
<img width="345" alt="Screenshot 2020-02-20 at 8 42 01 AM" src="https://user-images.githubusercontent.com/58783823/74900787-d7f4dc00-53c6-11ea-9489-39e32555505f.png">
<img width="356" alt="Screenshot 2020-02-20 at 8 46 22 AM" src="https://user-images.githubusercontent.com/58783823/74900802-ddeabd00-53c6-11ea-84fc-12d010d0b1c5.png"> 

3. The notifications title is not aligned correctly in mobile view
<img width="504" alt="Screenshot 2020-02-20 at 9 54 35 AM" src="https://user-images.githubusercontent.com/58783823/74900856-0c689800-53c7-11ea-96b0-c6dc17cc7137.png">

cc @luizrrodrigues

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , not able to test the empty state as I am not able to remove the notifications.

**Comment by luizrrodrigues** [comment]
> @luizrrodrigues , not able to test the empty state as I am not able to remove the notifications.

Let cover all issues in populated state first, then I'll clear the notifications to we test empty state.

**Comment by luizrrodrigues** [comment]
2. @SathyaJayabal Please check challenge spec: 
https://www.topcoder.com/challenges/30114259

3. @Oanh-and-only-Oanh Please confirm this one.

4. @Oanh-and-only-Oanh Please confirm this one.

5. @SathyaJayabal Yes, currently we're using mock data, so always when refresh will load previous data.

----

UI issues, I'll fix all.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , how can we test the empty state?

**Comment by SathyaJayabal** [comment]
From the challenge spec:
Mark All as Read - will remove all notifications
All the notifications that have a pink dot are new notifications that have not been seen before (not seen means a user didn't open the popup)
All notifications who have a gray dot are notifications that have been see (meaning the user opened the popup before) but have not been read (as in the user didn't click them)

@luizrrodrigues, Marking as read does not remove the notifications at present.

**Comment by SathyaJayabal** [comment]
Why do the completed challenges have a x button to remove them?  They could also be removed once read.

**Comment by SathyaJayabal** [comment]
Completed challenges: why do they have a close icon to dismiss the notification ? Why cant they be dismissed the usual way, by marking them as read ? What the need for two different ways to dismiss the notifications ?
cc @luizrrodrigues @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal @luizrrodrigues

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , one more UI issue. The handle should be bold like in the design.
<img width="488" alt="Screenshot 2020-02-20 at 10 39 28 PM" src="https://user-images.githubusercontent.com/58783823/74960236-f9d77880-5431-11ea-88e0-67e0e128db66.png">
@Oanh-and-only-Oanh @Dara-K , should the handle be a link?

**Comment by Dara-K** [comment]
@Oanh-and-only-Oanh @SathyaJayabal Here's the design for that screen when the notifications are seen: https://marvelapp.com/dcc2h8h/screen/66552240

**Comment by Dara-K** [comment]
I don't think we want the handle to be a link - that would take the members to the user profile, which doesn't bring any value here, but from a UI perspective if we make the handle link, we have to make it blue and underlined to pass accessibility test, which would just distract the user from the notification itself.

@Oanh-and-only-Oanh  what are your thoughts on this?

**Comment by SathyaJayabal** [comment]
@Dara-K , I agree, the handle as a link does not add any value and will distract from the actual notification. Forget that I asked :)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , @Dara-K , are the notifications themselves clickable like in connect? Do they take the user to the appropriate page (eg: to the challenge details - checkpoints tab when the checkpoint review is ready etc) ?

**Comment by luizrrodrigues** [comment]
@SathyaJayabal 
> Mark All as Read - will remove all notifications

This was a spec typo, Mark All as Read will just remove gray/pink marks.

----

@Dara-K Thanks for clarifications, just to confirm: 

a) In mobile, the notifications count is only to unseen notifications?
b) If only have unread notifications, need to show count too?
c) If we have both, unread and unseen notifications:
  - Show the bell icon in red color;
  - Show counter in red color;
  - The counter will be unseen or unread count?

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , so the notifications will be removed when the challenge is completed?

**Comment by luizrrodrigues** [comment]
@SathyaJayabal when challenge is completed will move to Completed Challenges at bottom:
![image](https://user-images.githubusercontent.com/7029641/75049553-28dd0100-54a9-11ea-9e12-c72c02725940.png)

In this section we have X button, click in this button will remove notification from panel.

**Comment by Dara-K** [comment]
@SathyaJayabal  Yes, it would be great if we could make the notifications clickable as in Connect to take the user to the related page.

@luizrrodrigues 
a) Right
b) No
c) 
-     Show the bell icon in red color;  -> Right
-     Show counter in red color;  -> Right 
-     The counter will be unseen or unread count? -> Unseen

Also, for the Completed Challenges we would like to limit their number that are displayed in the popup to 5. We can show the rest of them in the Notifications Details page.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , all the issues above have been addressed. 

New Requirements that need to be implemented:
Remove the completed challenges section from the popup.

Clarification: 
@luizrrodrigues , the challenge notification should take the suer to the. challenge details page on clicking it.  Will this be implemented after api integration

**Comment by luizrrodrigues** [comment]
> Clarification: the challenge notification should take the user to the. challenge details page on clicking it. Will this be implemented after API integration?

@SathyaJayabal Yes, we need to check as the backend will pass the challenge link.

**Comment by macs054** [comment]
Verified in Test Env

**Comment by SathyaJayabal** [comment]
Bell icon is in active state but the notifications popup and the notifications page do not display any notifications
<img width="1440" alt="Screenshot 2020-03-26 at 5 21 41 PM" src="https://user-images.githubusercontent.com/58783823/77644084-81ab2800-6f86-11ea-8f97-5f86fa7e9e65.png">

@luizrrodrigues , this could be because of the older submission uploaded notifications returned by the backend, but not shown by the front end.

**Comment by SathyaJayabal** [comment]
cc @sachin-maheshwari

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yep, we need to remove this from backend return.

**Comment by SathyaJayabal** [comment]
Sure @luizrrodrigues

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="1440" alt="Screenshot 2020-03-30 at 1 55 57 PM" src="https://user-images.githubusercontent.com/58783823/77892917-f20cbe80-7290-11ea-9146-419d9dcdb0f2.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-30 at 5 53 01 PM" src="https://user-images.githubusercontent.com/58783823/77913216-7cfdb100-72b1-11ea-9417-5b453f04c667.png">
