### ISSUE TITLE
Past challenges for Data Science filter isn't loading

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#3341]
**Steps to reproduce:** 

1. Login with `dan_developer / dantopcoder123` on https://community-app.topcoder-dev.com/
2. Check this video https://youtu.be/HvwmGlHf2M8

**Fix required**

Data Science challenges should continue to load as we scroll down

Use these branches for PR :  
1. https://github.com/topcoder-platform/community-app/tree/hot-fix
2. https://github.com/topcoder-platform/topcoder-react-lib/tree/hot-fix

As this is P0, please submit in 12 hours

**Comment by PrakashDurlabhji** [comment]
will this be open?

**Comment by sushilshinde** [comment]
@ajefts please have a look at the fix

https://beta-community-app.topcoder.com/challenges

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde it's loading for me but VERY slowly.

**Comment by lakshmiathreya** [comment]
Verified on https://beta-community-app.topcoder.com/challenges - Past challenges for Data Science Filter loading speed has considerably improved - average loading time is now less than 10 seconds. On Prod, the same query doesnt load the page even after a few minutes - appears to hang.

**Comment by sushilshinde** [comment]
@nithyaasworld please test on prod, and please other issues that you mentioned earlier, but refer prod app only.

**Comment by lakshmiathreya** [comment]
Verified on Prod - the loading is working well. Would like @nithyaasworld to double check and close the Issue.
