### ISSUE TITLE
[$30] - Searching using 'Other' tag will display items that won't have other tag

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#335]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Click on 'Other' tag from the listed items

- Observe the items

Actual Result(s)
-----------------------------------------------------------------
- Searching using 'Other' tag will display items that won't have other tag

Expected Result(s)
-----------------------------------------------------------------
- Must display the items that have other tag

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![64](https://user-images.githubusercontent.com/4592712/29739660-dc1dce36-8a60-11e7-9ac2-6e49b28710e0.jpg)

**Comment by sdgun** [comment]
https://www.screencast.com/t/iHRlwHpgUuHj

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Current logic is to check for tag text in name, technologies or platform. Some of the challenges have 'other' in their platforms array. Therefore they are included in result.
How should it fix it?
