### ISSUE TITLE
Sort MM Leaderboard

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3351]
Have sort buttons in the Registration Tab on name, ratings, registered, submitted and also add country in the leaderboard? I am personally very much used to checking how many reds are registered from how many countries on a match and if they submitted.

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2834805

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh FYI, we have the code ready we are getting some backend things in place, before we make it available to QA for testing. We should be ready in 1-2 days more.

**Comment by Oanh-and-only-Oanh** [comment]
@codeMinter, the sorting for username isn't alphabetical.
![image](https://user-images.githubusercontent.com/47536078/66938058-5a265b80-eff5-11e9-9bc9-b512e439bee5.png)

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh We used lex order hence we see the results that way. As discussed, will push the change to make it alpha sort.

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh @nithyaasworld this is on dev now with changes requested for sorting of username in alphabetical order

**Comment by codeMinter** [comment]
@sushilshinde

**Comment by Oanh-and-only-Oanh** [comment]
"countryname/flag" is out of scope of now. 
FYI @codeMinter @nithyaasworld

**Comment by nithyaasworld** [comment]
Please find the testing observations here https://github.com/topcoder-platform/community-app/issues/3427#issuecomment-548273042

**Comment by codeMinter** [comment]
@nithyaasworld this is on test and beta, please help test.

**Comment by codeMinter** [comment]
@nithyaasworld this is on beta, please help test.

**Comment by Oanh-and-only-Oanh** [comment]
@codeMinter @nithyaasworld, the sorting for username works in beta. question I have is if username starts with a number or special character, how does it sort?
See below. 
![image](https://user-images.githubusercontent.com/47536078/69077533-ae549f00-09ea-11ea-88e6-87dd9452e18c.png)

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh it is `alpha` sort as discussed earlier. If I am not wrong alpha sort, works on ASCII code.

**Comment by nithyaasworld** [comment]
Verified in Production.

Note: "countryname/flag" is out of scope for now. A new ticket has to be logged if we need them.
