### ISSUE TITLE
TCO20 Sub community filter is not working

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3360]
1. In the challenge listing page, apply sub-community filter as TC020 
2.Observe that it displays blank result though we have challenges for TCO20

![image](https://user-images.githubusercontent.com/5114190/66109106-944d3180-e5e1-11e9-9b9f-67ebb9804e21.png)

**Comment by sushilshinde** [comment]
@nithyaasworld TCO20 hasn't started to there won't be any challenge there. We will have to see if we can launch TCO20 challenge on dev.

**Comment by nithyaasworld** [comment]
@sushilshinde I thought we should see the current challenges which have TCO20 tag in it. Please correct me if I am wrong. Thanks.

![image](https://user-images.githubusercontent.com/5114190/66801777-e96d3980-ef37-11e9-904b-5a157e7abefc.png)

**Comment by lakshmiathreya** [comment]
@Oanh-and-only-Oanh @sushilshinde pls advise reg timeline for fix.

**Comment by sushilshinde** [comment]
@Oanh-and-only-Oanh please help with the priority

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde, this is low priority. I'll put this on the TO DO column but ON HOLD until we wrap up other more pressing issues.

**Comment by SathyaJayabal** [comment]
This will be fixed as part of #3278
