### ISSUE TITLE
[$20] - Placeholder text of SearchBox is not in the middle

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#337]
## Steps to Reproduce
Goto http://community-app.topcoder.com/challenges/

## Actual Result(s)
placeholder text of SearchBox is not in the middle

## Expected Result(s)
placeholder text aligned in the middle

## Environment
```
Device(s): Mac mini & iPad Air2
Operating System: MacOS 10.11.6 & iOS 9.3.2
Browser(s): Safari 10.1.2
```

#### Mac
![Mac Safari](https://user-images.githubusercontent.com/948001/29740061-763a6992-8a80-11e7-99c8-c89cecdd2ff7.png)

#### iPad
![iPad Safari](https://user-images.githubusercontent.com/948001/29740051-43c3c0d0-8a80-11e7-8331-ad84fe40ece0.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
I believe, this happens only on some browsers (e.g. works fine in Chrome on Ubuntu). We should check related style to ensure it is not broken on main browsers (note that we have autoprefixer setup in the app, so probably it is worth to check here, why it did not help in this case).

**Comment by elfman** [comment]
@birdofpreyru I just notice that the Topcoder Header is missing in tablet (see the second picture in the issue), is it a bug or a feature?

**Comment by elfman** [comment]
@birdofpreyru what's wrong with backend now? I can't open challenge detail page now, it works several hours ago. I see 504 error and `No 'Access-Control-Allow-Origin' header'` in console

**Comment by elfman** [comment]
@birdofpreyru I made Topcoder Header displayed on iPad, and I found some bug on it.
1. when iPad is landscape, the page use the design of PC, when click on the menu item, subMenu opened, but I can't find a way to close the submenu. (This is not the styling problem, I think I should open another issue for this bug.)
2. the search icon at top-right is not at the right position.
3. the page use the design for PC, but the Topcoder Footer use the design for mobile.

#### Header on iPad
![topcoder-header](https://user-images.githubusercontent.com/948001/29742519-47d8e82a-8ab3-11e7-90ed-b6c35c1476b3.png)

#### Footer on iPad
![topcoder-footer](https://user-images.githubusercontent.com/948001/29742521-4fc1e5fa-8ab3-11e7-802e-b5fa104518de.png)

**Comment by birdofpreyru** [comment]
@elfman Yeah, please log it as a sepate issue. It is a good catch about desktop header in landscape view on tablet.

The API v2 in dev seems to be down indeed, I'll ask to restart it.
