### ISSUE TITLE
Implement all styles for buttons from Contentful

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3387]
Design: https://marvelapp.com/1g8j2156/screen/60434788/handoff
- All buttons need to be available for usage from Contentful.
- Related docs should be updated

**Comment by lakshmiathreya** [comment]
@kkartunov @sushilshinde pls clarify reg verification for this Issue. cc @nithyaasworld

**Comment by kkartunov** [comment]
The demo should be [here](https://community-app.topcoder-dev.com/examples/contentful/contentblock/3k7k1JpnSvIRrJYWs4izYi) after PR is merged.

**Comment by kkartunov** [comment]
@lakshmiathreya ^^^

**Comment by Oanh-and-only-Oanh** [comment]
@kkartunov, it's unclear what about the buttons need to be verified or tested.

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh we want to confirm if demo https://community-app.topcoder-dev.com/examples/contentful/contentblock/3k7k1JpnSvIRrJYWs4izYi match design as per https://marvelapp.com/1g8j2156/screen/60434788/handoff
