### ISSUE TITLE
[$60] - Can not close SubMenu of TopCoder Head[er on tablet

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#339]
Steps to Reproduce
-----------------------------------------------------------------

- iPad at landscape, Go to 'local.topcoder-dev.com:3000/challenges' (currently the Topcoder Header is not shown on public server, so I use local dev, it will be fixed in #337)

- Tap on Menu item, SubMenu appears

- Tap on clean area of the page, the subMenu doesn't close

Actual Result(s)
-----------------------------------------------------------------
- Can not close SubMenu in landscape view on iPad

Expected Result(s)
-----------------------------------------------------------------
- When tap on empty area of page, close the submenu.

Environment
-----------------------------------------------------------------
- **Device(s):** iPad Air2
- **Operating System:** iOS 9.3.2
- **Browser(s):** Safari

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section)

**Comment by birdofpreyru** [comment]
Yeah, we should update header's code, to ensure that it works with clicks in addition to hovering. I.e. clicking on the main menu item's opens submenu, clicking outside of the submenu items, when the submenu is opened, closes it.
