### ISSUE TITLE
MM Leaderboard: Past challenges scores are not visible

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3392]
Past MM challenges scores are not visible

Challenge URL: https://www.topcoder.com/challenges/30101930?tab=submissions

![image](https://user-images.githubusercontent.com/5114190/66801203-e83b0d00-ef35-11e9-8f81-8cd8926d21af.png)

**Comment by nithyaasworld** [comment]
CC: @dushyantb @sushilshinde @codeMinter

**Comment by codeMinter** [comment]
The fix for this and #3269 is going to be same, as discussed with @dushyantb we changed the API response structure. We need to finalise the approach whether we migrate all old challenges to new api response structure of we fix this in UI. 

Linking them as the same fix is needed for both.

**Comment by skyhit** [comment]
@Oanh-and-only-Oanh @sushilshinde  per testing, I can see the page. like 

![image](https://user-images.githubusercontent.com/58106/78450465-4e1c7c00-76b1-11ea-91bb-d0299ebd401f.png)

but one interesting thing is when looking at the networking, it keeps calling api like

https://api.topcoder.com/v4/challenges/?filter=status%3DACTIVE%26technologies%3D&limit=50&offset=0, but for challenge detail page, why it is calling so many times? to listing challenges?

**Comment by Oanh-and-only-Oanh** [comment]
@skyhit, looks like this might be a challenge V4 api issue and we're currently migrating to challenge V5 api. That migration should be complete in of April, so let's put this on hold until migration is done to see if it is still an issue.

**Comment by skyhit** [comment]
@Oanh-and-only-Oanh sure.

**Comment by SathyaJayabal** [comment]
> @skyhit, looks like this might be a challenge V4 api issue and we're currently migrating to challenge V5 api. That migration should be complete in of April, so let's put this on hold until migration is done to see if it is still an issue.

adding the on hold label

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal @lakshmiathreya, is this front-end or backend issue?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , the scores are displayed now
<img width="1440" alt="Screenshot 2020-09-09 at 9 36 46 AM" src="https://user-images.githubusercontent.com/58783823/92553231-0a412a80-f280-11ea-83c5-787c38ef41c9.png">
