### ISSUE TITLE
My Challenges served from the members challenge api endpoint

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#3396]
https://www.topcoder.com/challenges/30103914

**Comment by lakshmiathreya** [comment]
Verified that My Challenges is served from the endpoint as stated in Challenge requirements. Pls clarify reg additional verifications @codeMinter

**Comment by codeMinter** [comment]
@lakshmiathreya can you please elaborate what clarifications are needed here ?

**Comment by codeMinter** [comment]
If you referring to what else to test, we are targeting to speed up loading of the `/challenges` page, so not sure if you have tools to test the same. It would be good to get some stats around it so we can then plan to do similar thing for other buckets if this process has speeded up loading of My Challenges bucket?

**Comment by Oanh-and-only-Oanh** [comment]
Yes, agreed. Please note the time in Prod now for comparison. Thank you

**Comment by codeMinter** [comment]
@sushilshinde can we deploy this to `beta` so @lakshmiathreya can run a comparison with PROD as they both are served using same backend ?

**Comment by codeMinter** [comment]
> @lakshmiathreya can you please elaborate what clarifications are needed here ?

@lakshmiathreya can you elaborate what clarifications are needed here ?

**Comment by lakshmiathreya** [comment]
@codeMinter Clarification requested was regarding specifics of verification - its clear now that /challenges load times need to be noted. thanks! Deploying on beta would help to make a direct comparison as you suggested.

**Comment by sushilshinde** [comment]
Currently, these changes are on avail on beta but deployed on dev

**Comment by nithyaasworld** [comment]
@codeMinter On dev, the fix seems to be good, apart from the below issue.

Could you check, please?

Steps to reproduce:
1. Login as dan_developer 
2. Click on View More Challenges present under 'My challenges' section
3. Scroll to the end of the screen and notice that all the 49 challenges are displayed
4. Scroll up and disable all the Dev, DS and Design toggle filter
5. Enable only Design filter and scroll and check
6. Then Enable Dev too and scroll
7. Check that it keeps on showing the loading animation

Video: 
[My Challenges issue02.zip](https://github.com/topcoder-platform/community-app/files/3803768/My.Challenges.issue02.zip)

**Comment by codeMinter** [comment]
@nithyaasworld @sushilshinde is helping push this to DEV, are you around and can help re-test this ?

**Comment by codeMinter** [comment]
This is on hold so moving back to To Do - the code changes are in place, needs to be deployed and tested once server becomes available

**Comment by SathyaJayabal** [comment]
we are now using the v5 challenge api.
