### ISSUE TITLE
Development TCO20 Leaderboard is Empty

### ISSUE THREAD

**Issue by Schpotsky** [topcoder-platform/community-app#3398]
**Describe the bug**
The TCO20 leaderboard http://tco20.topcoder.com/competition-overview/development/leaderboard is empty even if there are eligible development challenges that were already completed : 
https://www.topcoder.com/challenges/30103927
https://www.topcoder.com/challenges/30103885

All the points for development challenges are counted in the QA leaderboard :
http://tco20.topcoder.com/competition-overview/qa/leaderboard

**To Reproduce**
1. Go to http://tco20.topcoder.com/competition-overview/development/leaderboard
The leaderboard is empty
2. Go to http://tco20.topcoder.com/competition-overview/qa/leaderboard
The leaderboard points seem to consider the development challenges as well
![qa-leaderboard](https://user-images.githubusercontent.com/5437419/66920688-530e4600-f013-11e9-912c-f42de055fe31.png)

**Expected behavior**
The QA leaderboard should only count the TCO points for QA challenges.
The TCO points for development challenges should be counted in the development leaderboard

NB :
Not sure if this will be fixed as part of this issue fix #3377 
cc @kkartunov

**Comment by sandhiyakavi** [comment]
It is working now.
Development Leaderboard:

![image](https://user-images.githubusercontent.com/55895538/78527860-a364a480-77fb-11ea-897c-16f68289bdb1.png)

QA Leaderboard:

![image](https://user-images.githubusercontent.com/55895538/78527967-e292f580-77fb-11ea-8ff1-ae36b45f35f9.png)

cc: @SathyaJayabal
