### ISSUE TITLE
Submission Management Page for MM

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3399]
This new feature will allow MM submitters to manage their submissions directly on the platform. 

- view submission status

- view submission scores

- view submission metadata

<p></p>

Marvel design: <https://marvelapp.com/cch42ib/screen/61330572>

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/3112446

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @nithyaasworld

**Comment by nithyaasworld** [comment]
@veshu Function about the new SMP is clear from the Marvel app design. I dont have access to Productboard link shared by Tony above. Is there anything else we need to know when testing?

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld here you go. 
Building on Chris and Tony's submission mgmt page https://submission-review.topcoder.com/, how to get it in a user-ready state.
where will it live
what's the member user flow
the designs are at https://marvelapp.com/c026e87/screen/57758299 - create a list of requirements for fixing the designs

Here are the designs for the list view: https://drive.google.com/open?id=1HVryoX27HF5wk26zDERTJdGjcxoPszmN
Marvel link and Marvel handoff:
https://marvelapp.com/93iib33
Marvel Handoff:
https://marvelapp.com/93iib33/screen/58998400/handoff

**Comment by nithyaasworld** [comment]
@veshu 
Sorting function, Upload and download submission functions are all good! Follow are the things noted but none of them are major-issue:

1. Language column is not available, like present in the design. 

2. Final and Provision columns should be under the 'Score' title, like in the design. At present, Provision and Time columns are present under the 'Score' title.

3. I am not able to verify the various statuses as all my submissions are stuck in 'processing'. Can you upload a valid submission and check if it shows 'success tick' status? (Or please share me a valid submission which I can upload and test)

![image](https://user-images.githubusercontent.com/5114190/72375646-763fb300-3732-11ea-952c-5ec7e431d347.png)

**Comment by Oanh-and-only-Oanh** [comment]
@veshu @nithyaasworld, 
1.  **Language column is not available, like present in the design.** We don't need language anymore so this is fine.
2. **Final and Provision columns should be under the 'Score' title, like in the design. At present, Provision and Time columns are present under the 'Score' title.** Yes, please fix this.
3.  I am not able to verify the various statuses as all my submissions are stuck in 'processing'. Can you upload a valid submission and check if it shows 'success tick' status? (Or please share me a valid submission which I can upload and test). @veshu, can you help with this?

**Comment by veshu** [comment]
@nithyaasworld 3. can you please share the challenge link?

**Comment by veshu** [comment]
@nithyaasworld This is ready for QA. Could you please verify again.
Thanks!
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@veshu . Looks good.

Verified in dev

**Comment by veshu** [comment]
@SathyaJayabal This is now on prod beta http://beta-community-app.topcoder.com/

Could you please help verify this. Planned deployment for production is tomorrow.
Thanks

**Comment by SathyaJayabal** [comment]
@veshu , My submissions count displays as 0 while the the My Submissions and Submissions tab is loading. Once the tab is loaded the count is displayed correctly.

Please see the attached video.
[My submisisons.mov.zip](https://github.com/topcoder-platform/community-app/files/4151783/My.submisisons.mov.zip)

**Comment by Oanh-and-only-Oanh** [comment]
The issue mentioned here is valid but separate. Other than that, looks like it passed QA? If so, let’s go ahead and release this feature to close It out. We can log this issue as a new bug- P4.

**Comment by SathyaJayabal** [comment]
Marking as QA pass in Beta. Logging a new issue to track the submissions count issue.

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
<img width="1385" alt="Screenshot 2020-02-06 at 8 17 40 PM" src="https://user-images.githubusercontent.com/58783823/73947652-d1258e00-491d-11ea-8924-f48fb1d36d82.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1401" alt="Screenshot 2020-02-07 at 12 12 39 PM" src="https://user-images.githubusercontent.com/58783823/74007036-5dc65f80-49a3-11ea-9444-ff5e696eed4f.png">

@veshu , can you please verify this with a valid submission for a MM and let us check if the scores are displayed accordingly.
