### ISSUE TITLE
Challenge Listing page: Tooltip is blank for Idea Generation Challenges

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3409]
Challenge listing page: 

Tooltip is blank for Idea Generation Challenges

![image](https://user-images.githubusercontent.com/5114190/67230077-35e5d700-f45a-11e9-87f1-6493131c0578.png)

**Comment by nithyaasworld** [comment]
This is a known issue for a long time.

CC: @Oanh-and-only-Oanh @lakshmiathreya

**Comment by sandhiyakavi** [comment]
Closing this issue as it is not applicable now.
