### ISSUE TITLE
When I update my profile image/avatar in my profile settings, it doesn't reflect back in the forums profile/avatar!

### ISSUE THREAD

**Issue by reuf** [topcoder-platform/community-app#3414]
1. I go to https://www.topcoder.com/settings/profile
2. I update my avatar with the new image
3. It is changed everywhere except in the forums. The old avatar is still displayed in the forums.

**Comment by nithyaasworld** [comment]
This issue will be tracked here: https://github.com/topcoder-platform/community-app/issues/1872
