### ISSUE TITLE
Add quick survey to challenges page

### ISSUE THREAD

**Issue by codeMinter** [topcoder-platform/community-app#3416]
Create a survey for challenges page using below 

```
<script>(function(t,e,s,o){var n,c,l;t.SMCX=t.SMCX||[],e.getElementById(o)||(n=e.getElementsByTagName(s),c=n[n.length-1],l=e.createElement(s),l.type="text/javascript",l.async=!0,l.id=o,l.src=["https:"===location.protocol?"https://":"http://","widget.surveymonkey.com/collect/website/js/tRaiETqnLgj758hTBazgd6PjYIXGGOw0KVk2yWQQRPhEwpPgmCCgOC_2BvAyG1MDsy.js"].join(""),c.parentNode.insertBefore(l,c))})(window,document,"script","smcx-sdk");</script>
```

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh FYI ☝️

**Comment by codeMinter** [comment]
@nithyaasworld are you around to test this quickly, deployment happening for beta right now ?

**Comment by nithyaasworld** [comment]
@codeMinter @Oanh-and-only-Oanh Verified in production.

**Comment by nithyaasworld** [comment]
@codeMinter The survey keep showing whenever I open the challenges page, though I have already completed the survey. Could you check please?

![image](https://user-images.githubusercontent.com/5114190/67625554-6a440380-f85d-11e9-9a2f-38fad90284ab.png)

**Comment by Oanh-and-only-Oanh** [comment]
removing the pop up survey tomorrow. FYI @nithyaasworld

**Comment by codeMinter** [comment]
@nithyaasworld yes, we don't do session management, it is normal survey monkey which will be there. We are taking this off as @Oanh-and-only-Oanh has the needed info, revert for the same is #3426

**Comment by codeMinter** [comment]
Let's move it back to Done, if you agree to above as revert is different ticket as posted above.

**Comment by nithyaasworld** [comment]
I will check and close this issue by tonight.

**Comment by nithyaasworld** [comment]
Verified and confirming that this survey is removed.
