### ISSUE TITLE
Default text overlap with the search icon in the menu

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#342]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Expand the menu and check the search default text and search icon

Actual Result(s)
-----------------------------------------------------------------
-  Default text overlap with the search icon in the menu

Expected Result(s)
-----------------------------------------------------------------
- Default text must not overlap with the search icon in the menu there must be small spacing in between them

Environment
-----------------------------------------------------------------
- **Device(s):** iPad Air 2
- **Operating System:** iOS 10.3.3
- **Browser(s):** Safari

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by birdofpreyru** [comment]
Dublicates #194, I believe
