### ISSUE TITLE
What is shown for Member Skills is different from backend data

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3421]
**Describe the bug**
There are some differences in the "Member skills" data between what is shown on frontend and what is in backend data

**To Reproduce**
1. Go to https://www.topcoder.com/members/ananthhh
2. The profile shows 10 skills however in Dynamo there are 37 skills for this user

**Comment by lakshmiathreya** [comment]
@Oanh-and-only-Oanh @urwithat  is this fixed in Dev? https://www.topcoder-dev.com/members/ananthhh to be verified?

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya, yes it needs to be verified.

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh @lakshmiathreya Member Profile page in Dev environment is not loading. It gets loaded for a second and then displays a blank white screen. Please check: https://www.topcoder-dev.com/members/tonyj

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld @lakshmiathreya , the profiles page in Dev is working again. Can you proceed with verification?

**Comment by lakshmiathreya** [comment]
@Oanh-and-only-Oanh Profiles page still not loading. Working with @sushilshinde @urwithat to resolve it before we proceed for verification. cc @nithyaasworld

**Comment by urwithat** [comment]
Fixed and deployed on dev environment

**Comment by lakshmiathreya** [comment]
Verified Skills presented with Dynamo Db. Seems to be working. However, for the user listed above "ananthhh" - Skills are presented on Member skills Dev page but Dynamo Db returns no results for this handle - so unable to verify the Skills count at backend. Need clarification @urwithat.

**Comment by urwithat** [comment]
The member profile elastic search data for `ananthhh` was missing in dev, I'll run the dynamodb to es sync application. Once done, will request to test once again.

**Comment by lakshmiathreya** [comment]
Verified after sync. Dynamo Db returns skills for "ananthhh" in tune with Member Profile page for the same user.
