### ISSUE TITLE
Community/Business Toggle to Navigation

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3422]
Add the following elements to the Community side.

1) Community/Business toggle- we want this toggle feature to be present for BOTH logged in and logged out states. IT's the same as what the marketing side has currently.
See screenshot 
![image](https://user-images.githubusercontent.com/47536078/67507575-05619100-f644-11e9-9441-288412956254.png)

2) The user dropdown menu- For the Logged In state, we want the user drop down menu
![image](https://user-images.githubusercontent.com/47536078/67507519-e19e4b00-f643-11e9-9ceb-9b108e9dc704.png)

**Comment by nithyaasworld** [comment]
Avatar and email seem to be not correct. Tried for the user nithyaasworld/appirio123 in Test environment.

Not able to check the Review-Opportunities page in test environment. I will test this on Beta when this fix is moved to beta. Also not able to check the My Profile page as it shows 404 in test env.  There are no other issues observed.


![image](https://user-images.githubusercontent.com/5114190/68105936-0cbb5100-ff06-11e9-93a8-c4342b001ac7.png)

CC: @sushilshinde

**Comment by Oanh-and-only-Oanh** [comment]
Tested for user: ajefts@topcoder.com/appirio123 in test enviro and didn't see the same avatar and email issue as indicated by @nithyaasworld above. Let's retest in beta.

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld, can we do a check to make sure the new navi meets accessibility standards?

**Comment by nithyaasworld** [comment]
@luizrrodrigues On accessing My Profile -> Preferences tab, it shows 404 error. After that, whenever I access My Profile, it shows 404. Can you please confirm if its a test environment issue?

CC: @Oanh-and-only-Oanh 

![image](https://user-images.githubusercontent.com/5114190/68325153-e0165d80-00ee-11ea-89c1-c94b45a0d433.png)

**Comment by luizrrodrigues** [comment]
@nithyaasworld This page? 
https://test-community-app.topcoder-dev.com/settings/profile

**Comment by nithyaasworld** [comment]
Yes, it works if the user has never navigated to Preferences tab of the above URL.

**Comment by luizrrodrigues** [comment]
@nithyaasworld Looks like this is an issue with API, check dev site:
https://www.topcoder-dev.com/members/dan_developer

**Comment by SathyaJayabal** [comment]
Verified
![Uploading Screenshot 2019-12-16 at 7.58.07 PM.png…]()

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, we only close the ticket once it has been verified in PROD.

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal, we only close the ticket once it has been verified in PROD.

@Oanh-and-only-Oanh, I am sorry about this. I had assumed that since navigation is completely new and not yet in production, it was ok to close the bugs after testing on Beta. I will make sure to close the bugs only after testing  in production.

**Comment by SathyaJayabal** [comment]
<img width="1406" alt="Screenshot 2019-12-17 at 3 59 08 PM" src="https://user-images.githubusercontent.com/58783823/70987665-5c389380-20e6-11ea-83eb-0dc438550b21.png">

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1440" alt="Screenshot 2019-12-19 at 7 35 56 PM" src="https://user-images.githubusercontent.com/58783823/71179855-fd664c00-2296-11ea-9223-bcc62c755061.png">
<img width="1435" alt="Screenshot 2019-12-19 at 7 36 39 PM" src="https://user-images.githubusercontent.com/58783823/71179857-ff300f80-2296-11ea-86a8-dcfee009ba55.png">
