### ISSUE TITLE
Sort Submissions Columns

### ISSUE THREAD

**Issue by codeMinter** [topcoder-platform/community-app#3427]
https://www.topcoder.com/challenges/30104447/?type=develop

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh added this ticket to track Submissions page sorting changes. 

@sushilshinde FYI ☝️

**Comment by Oanh-and-only-Oanh** [comment]
"countryname/flag" is out of scope of now. 
FYI @codeMinter @nithyaasworld

**Comment by codeMinter** [comment]
@nithyaasworld can you help test this on DEV ?

**Comment by nithyaasworld** [comment]
@codeMinter Please find the results below:

1. MM Results are not shown in Beta. 
![image](https://user-images.githubusercontent.com/5114190/67930886-c05ed100-fbe6-11e9-96d6-5c0d742ed061.png)

2. I think we should not show the Rating column for the Design Challenges as they don't have rating. Please correct me if I am wrong. Thanks.
![image](https://user-images.githubusercontent.com/5114190/67932057-36fcce00-fbe9-11e9-8c8f-2fa91b274185.png)

3. I guess Rating is not applicable to F2F challenges too. Please confirm.
![image](https://user-images.githubusercontent.com/5114190/67932068-3ebc7280-fbe9-11e9-9d2b-de04a84f2bd4.png)

4. In Design challenges' Submission tab, info text is going out of the frame. Please check the screenshot below:

![image](https://user-images.githubusercontent.com/5114190/67932839-acb56980-fbea-11e9-90ca-350fdc3149f7.png)

**Comment by codeMinter** [comment]
Thanks @nithyaasworld 

1. MM Results are not shown in Beta
> I know the problem, bcos this deployment was done from branch, which doesn't still has the code from master. This will go once we merge, let me do that and push new release to beta tomm

2. I think we should not show the Rating column for the Design Challenges as they don't have rating. Please correct me if I am wrong. Thanks.
> Yes, you are right here, while you were working on testing, I was fixing this as realised Design doesn't has ratings. 

3. I guess Rating is not applicable to F2F challenges too. Please confirm.
> Most of Code developers work on F2F, so I guess we can leave it here. 

4. In Design challenges' Submission tab, info text is going out of the frame. Please check the screenshot below:
> will look at this and push along with fix for 1 above. 

I will flag you once this is pushed to dev/beta for testing.

**Comment by codeMinter** [comment]
FYI - @nithyaasworld everything except 1 is on beta now. I will flag once we have 1 on beta, tracing what is causing it as we already synced and deployed the latest code now.

**Comment by nithyaasworld** [comment]
Ok, I will wait for 1 and test them all together

**Comment by nithyaasworld** [comment]
@codeMinter is No:1 ready for testing?

**Comment by codeMinter** [comment]
@nithyaasworld not yet, we are still sorting the branch conflicts, will update as soon as ready.

**Comment by codeMinter** [comment]
@nithyaasworld this is on test and beta, please help test.

**Comment by codeMinter** [comment]
@nithyaasworld this is on beta, please help test.

**Comment by nithyaasworld** [comment]
@codeMinter Registration sorting seems to be not correct. Please check the challenge: https://beta-community-app.topcoder.com/challenges/30106903?tab=registrants

![image](https://user-images.githubusercontent.com/5114190/69066759-e76f2c80-0a47-11ea-86e7-82f9bbd14bcf.png)

![image](https://user-images.githubusercontent.com/5114190/69067085-7e3be900-0a48-11ea-87b3-a859e17c2cc5.png)

**Comment by codeMinter** [comment]
@nithyaasworld doesn't look like you applied sorting - once you apply sorting you should see color of arrows as blue highlighted which I don't see in your shared snapshot above.

**Comment by nithyaasworld** [comment]
You are right! I just updated my above comment with more details. Please check.

**Comment by codeMinter** [comment]
@nithyaasworld yes, just saw, will make it default sorted as per PROD. Thanks

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh @nithyaasworld Since Design and F2F wouldn't have Rating, I have swapped default sort to be by `Registration Date` like we have currently in PROD.

**Comment by nithyaasworld** [comment]
I think we need to remove the Rating column for Bug Hunt too as its not a rated competition.

Apart from this and the default registration sorting issue, there are no other issues.

![image](https://user-images.githubusercontent.com/5114190/69131607-abd07300-0ad8-11ea-9f63-f6a3cca6a4d0.png)

**Comment by codeMinter** [comment]
@nithyaasworld ☝️  has been addressed too.  Kindly test on beta once you are ready. 

@Oanh-and-only-Oanh @nithyaasworld FYI, note below change:
1. Registrations sorting now happens on Registration Date. 
2. Submissions sorting now happens on Submitted Date. For MM, it is based on Provisional and Final score. 

So this way we will have default sorting in sync for all kind of challenges.

**Comment by Oanh-and-only-Oanh** [comment]
@codeMinter, was only able to replicate the issue @nithyaasworld mentioned above using incognito mode.

**Comment by codeMinter** [comment]
@Oanh-and-only-Oanh have pushed in fix, @nithyaasworld is helping test this once more. I did some code formatting for previous issue which caused this issue. It worked for you bcos of browser cache. Let @nithyaasworld confirm and will work with @sushilshinde in morning to get this merged and pushed for smoke testing after which we can move this to PROD tomm likely 🤞

**Comment by nithyaasworld** [comment]
@codeMinter 
Issue:1-> For the below challenge, Provisional ranks 74, 75 are displayed at the last
![image](https://user-images.githubusercontent.com/5114190/69220738-ac7e0d80-0b9b-11ea-85a6-76b02650ad9c.png)

Issue:2-> I am really not sure what does -1 imply in the final score. But when it's available, sorting is not done correctly.
![image](https://user-images.githubusercontent.com/5114190/69220831-dd5e4280-0b9b-11ea-87fb-7ed4b73852df.png)

Issue:3-> Also sorting by Provisional score for the below past-challenge seems to have an issue:
![image](https://user-images.githubusercontent.com/5114190/69220872-ef3fe580-0b9b-11ea-9423-72e5b5b7a3b0.png)

**Comment by codeMinter** [comment]
@nithyaasworld 
1. We are doing sorting by Provisional Score, so Rank is ignored. For such cases, we might have to build backup formatting, which would be too much. 

2. It should not show -1, as per my knowledge, we decided to show the icon with cross and not -1

3. This is weird issue, as it works fine on Safari. Checking for chrome, why not working.

**Comment by nithyaasworld** [comment]
Ok, For:1 -> It is when sorted by default. That is, it happens when I access the [URL](https://beta-community-app.topcoder.com/challenges/30103825?tab=submissions) directly

**Comment by codeMinter** [comment]
yes 1 is `Provisional score` by default, if Review of challenge hasn't completed. we can swap to do it as `Provisional Rank` by default.

**Comment by codeMinter** [comment]
@nithyaasworld to fix the above add-on issues, following has been done:
1. Default sorting has been moved to Provisional  (when Review not complete) and Final Rank (when review complete)

2. All -1 final scores have been fixed to be 0, as min final score can be 0. 

3. Sorting issues fixed.

**Comment by nithyaasworld** [comment]
> Default sorting has been moved to Provisional Rank (when Review not complete) and Final Rank (when review complete)

For 1: It is already like you have stated.. right?

Ok, Please let me know when it's available in beta for test. I will test this.

**Comment by nithyaasworld** [comment]
Thanks @codeMinter This is verified.

**Comment by nithyaasworld** [comment]
Verified in Production.

Note: "country name/flag" is out of scope for now. A new ticket has to be logged if we need them.
