### ISSUE TITLE
Leaderboard issue: Submitter handle sometimes won’t be the actual submitter

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3429]
**Describe the bug**
The issue is that we’re showing the submitters list using the handle of the user that created the submission.  There is also an API field that has the ID of the submitter.  The issue with using createUser is that it’s really an audit field and sometimes it won’t be the actual submitter.  For example, if ritesh uploads a submission on behalf someone else, then it’s showing ritesh as the submitter instead of the member

![image](https://user-images.githubusercontent.com/47536078/67877576-09375c80-faf7-11e9-94c0-f3ff20a5ad38.png)

link: https://www.topcoder.com/challenges/30103939?tab=submissions

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, can you please verify if this is still an issue? Use case is if support had to submit on behalf of a member. The submission should show the member's handle, not the support team.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , I am not able to access the above challenge. But we did test and fix this issue during the v5 integration
https://github.com/topcoder-platform/community-app/issues/4667
