### ISSUE TITLE
Won't close the date time picker in filter when user click on a empty area

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#343]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Click Filter

- Expand the Date Range and click on a empty place or any other field

Actual Result(s)
-----------------------------------------------------------------
- Won't close the date time picker in filter when user click on a empty area

Expected Result(s)
-----------------------------------------------------------------
- Must close the date time picker in filter when user click on a empty area

Environment
-----------------------------------------------------------------
- **Device(s):** iPad Air 2
- **Operating System:** iOS 10.3.3
- **Browser(s):** Safari

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by birdofpreyru** [comment]
Hmm... it sounds like I have seen a msg about this bug before, but cannot find it now.
