### ISSUE TITLE
Challenges count are incorrect right after logging in

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3438]
1. Open https://www.topcoder.com/challenges in a New Incognito window
2. Notice the Challenge count
3. Login with your user and check the Challenges count in the right panel

Actual:
'My challenges' count is shown as 0 though I have registered on 5 challenges. Only on refreshing, it shows the right counts.

![image](https://user-images.githubusercontent.com/5114190/68298555-b42fb380-00bf-11ea-9cec-8f84a4d8184f.png)

![image](https://user-images.githubusercontent.com/5114190/68298725-14265a00-00c0-11ea-94a1-e3ad567a8992.png)

**Comment by sandhiyakavi** [comment]
Challenge counts are correctly displayed now

![image](https://user-images.githubusercontent.com/55895538/106861903-bf7dee80-6709-11eb-90b5-7c9d76a2b739.png)
