### ISSUE TITLE
prize amount is wrong 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#344]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges?

- Move cursor on  Ohio Deferred Compensation - Wireframe Challenge challenges  prize amount 
- Check tootl tip amount and prize amount  

Actual Result(s)
-----------------------------------------------------------------
-  sum of prize is wrong 

Expected Result(s)
-----------------------------------------------------------------
- should show prize amount properly 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 54.0.1

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![dfsdfds](https://user-images.githubusercontent.com/3225433/29746948-48d39cde-8b08-11e7-8b8b-75a852914a35.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points. @ajefts @skyhit I believe, it is api-related bug, in fact?

**Comment by ajefts** [comment]
@skyhit Can you check the prize calc for design challenges?  It looks like it might be only summing the first 3 prizes....

**Comment by birdofpreyru** [comment]
This one is still pending a check in API. At a closer look, the current behavior is:
- If challenge has checkpoint prizes (probably this relates to bonuses as well), then checkpoint prize is included in the end of prizes array in API v3 (but even if there are multiple checkpoint prizes, only one is included, so this is any way inconsistent). See #243 as well.
- When the total prize is calculated in the API, only regular prizes are summed up.
