### ISSUE TITLE
New Navi: Need to click on Compete twice in order to see the sub menus

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3444]
1. Go to https://beta-community-app.topcoder.com/community/competitive-programming (without loging in)
2. Click on Community and then on Compete

Actual:
Observe that no sub-menus are displayed. User needs to click again on 'Compete' to see the Submenus.

Expected:
It should display the submenus on the first click itself.

![image](https://user-images.githubusercontent.com/5114190/68392097-068bd580-018f-11ea-8c2d-3b714fb5f044.png)

![image](https://user-images.githubusercontent.com/5114190/68392130-202d1d00-018f-11ea-8917-cde8468d66a4.png)

**Comment by nithyaasworld** [comment]
CC: @luizrrodrigues @Oanh-and-only-Oanh

**Comment by luizrrodrigues** [comment]
@nithyaasworld I think this was a old request:

When page have your own navigation, we need to hide submenu (@Oanh-and-only-Oanh Please confirm that)

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, the 3rd level navi that shows "upcoming matches, matchlist, etc", please remove that level. We will move that under Track>>Competitive Programming>>submenus

**Comment by luizrrodrigues** [comment]
This one was fixed, submenu always will show.

https://github.com/topcoder-platform/community-app/pull/3466

**Comment by nithyaasworld** [comment]
@luizrrodrigues The 3rd level menus are not removed and placed under Competitive Programming menu as advised by @Oanh-and-only-Oanh above. Can you check please?

![image](https://user-images.githubusercontent.com/5114190/69720878-a1962080-1139-11ea-93a8-63c005b562be.png)

**Comment by luizrrodrigues** [comment]
@nithyaasworld @Oanh-and-only-Oanh 
The 3rd level menu in this page, is part of page inner/own content. So this is out from Nav, we'll need to change others components.

Let me know if we'll need go forward.

**Comment by SathyaJayabal** [comment]
Verified in Production
[BUG 3444.mov.zip](https://github.com/topcoder-platform/community-app/files/3983880/BUG.3444.mov.zip)
