### ISSUE TITLE
Regarding Business Links

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3446]
Business in the Navbar takes the user to www.topcoder.com
Whereas 'Switch to Business' in the User menu takes the user to connect.topcoder.com

Please confirm if this is okay or should we redirect both the Business links to Topcoder Connect. 

![image](https://user-images.githubusercontent.com/5114190/68403311-bfa7db00-01a2-11ea-9f83-5aeee6957030.png)

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @nithyaasworld, please change the BUSINESS in the dropdown menu to navigation to www.topcoder.com

**Comment by nithyaasworld** [comment]
This will be re-opened when necessary.

CC: @Oanh-and-only-Oanh
