### ISSUE TITLE
Business Link should not be available for a community member

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3447]
1. Login as a community member
2. Check the New Navbar

Actual:
New Navbar still has the Business Menu for the community member. However, Business menu is removed from the User dropdown menu.

Expected:
Business links should not be available for community member as per Scenario No:3 of #3336 

![image](https://user-images.githubusercontent.com/5114190/68404826-1e6e5400-01a5-11ea-91b6-eee07f9e6f08.png)

**Comment by nithyaasworld** [comment]
cc: @Oanh-and-only-Oanh @lakshmiathreya

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld, this has been changed so that Business link in top navi is available to ALL users now. You can close this ticket.
