### ISSUE TITLE
Customer (Business) user has access to 'Community'

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3449]
1. Create a customer user in connect.topcoder.com
2. Go to www.topcoder.com and login as customer user
3. Check the New Navbar

Actual:
New Navbar shows Community menu for a customer user.

Expected:
As per #3336 , Community menu should be hidden for a Business user.

![image](https://user-images.githubusercontent.com/5114190/68408049-9e4aed00-01aa-11ea-9dfa-c5362c1cf295.png)

![image](https://user-images.githubusercontent.com/5114190/68408183-e9fd9680-01aa-11ea-8792-3ee8ba0e80ca.png)

**Comment by nithyaasworld** [comment]
cc: @Oanh-and-only-Oanh @lakshmiathreya

**Comment by nithyaasworld** [comment]
@Oanh-and-only-Oanh Please confirm if this is okay

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld, Top level BUSINESS/Community toggle will remain visible for ALL users (community and customers) in logged in and Logged out states. You can close this ticket.
