### ISSUE TITLE
Some of the Marathon matches are not opening

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3453]
1. Go to www.topcoder.com (do not log in)
2. Check all the MM Challenges

Actual:
Some of them are not loading. 

This happened a long time back and this issue is returned again.

![image](https://user-images.githubusercontent.com/5114190/68483061-d6146c00-0260-11ea-9175-49c8f3cea2ad.png)

**Comment by nithyaasworld** [comment]
cc: @dushyantb @cwdcwd @Oanh-and-only-Oanh @lakshmiathreya

**Comment by sandhiyakavi** [comment]
Able to open all Marathon matches now.
