### ISSUE TITLE
When URL of 'past challenges and search combination filter' is accessed directly, its not working

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3455]
1. In the challenge listing page, click on 'Past Challenges'
2. Then in the Search text filter, enter 'Framework'
3. Observe that it starts to load the matching results
4. Copy the URL of the current page and try to access this URL directly
5. Observe that it's not loading the results when the URL is accessed directly.

Try this URL in a new incognito window: https://www.topcoder.com/challenges?filter[text]=framework&bucket=past

![image](https://user-images.githubusercontent.com/5114190/68734303-ea10f280-05ff-11ea-9fed-f1efc5fac478.png)

**Comment by nithyaasworld** [comment]
CC: @lakshmiathreya

**Comment by sandhiyakavi** [comment]
Verified.Its working now.

https://www.topcoder.com/challenges?bucket=allPast&search=framework

![image](https://user-images.githubusercontent.com/55895538/106863063-5a2afd00-670b-11eb-8c6e-c02398338836.png)
