### ISSUE TITLE
TaaS See-More Link is displayed on the TaaS page too

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3456]
TaaS See-More Link is displayed on the TaaS page too

![image](https://user-images.githubusercontent.com/5114190/69052077-0fe92d80-0a2c-11ea-873a-fe823d4d84e6.png)

**Comment by nithyaasworld** [comment]
Assigning this with P1 as it's on Marketing site.

cc: @kkartunov @Oanh-and-only-Oanh @sushilshinde

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld, please close this ticket for now as it is on Marketing side. any marketing side tickets you can mark Trevor and Quest. You can get ping them on slack to get their github access
