### ISSUE TITLE
TaaS Page: One of the member's profile link is broken

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3457]
TaaS Page: Codejam's profile link is broken

![image](https://user-images.githubusercontent.com/5114190/69052425-00b6af80-0a2d-11ea-9391-026efe8225e3.png)

**Comment by nithyaasworld** [comment]
cc: @kkartunov @Oanh-and-only-Oanh @sushilshinde

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld, please close marketing tickets. Thank you.
