### ISSUE TITLE
[$20] - TopcoderHeader mobile menu triggered when click on JOIN/LOG IN Button

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#346]
## Steps to Reproduce
- access to http://community-app.topcoder.com/challenges/30058637 in portrait view on iPad
- Tap the JOIN or LOG IN Button

## Actual Result(s)
- mobile menu is opened before redirect to other page

## Expected Result(s)
- redirect to other page without other response

## Environment
```
Device(s): iPad Air2
Operating System: iOS 9.3.2
Browser(s): Safari
```

**Comment by birdofpreyru** [comment]
Accepted, 3 points
