### ISSUE TITLE
Submission Tab for MM are not filtering scores from Virus Scan and showing `100` score

### ISSUE THREAD

**Issue by dushyantb** [topcoder-platform/community-app#3469]
<img width="1268" alt="Screenshot 2019-11-22 at 9 46 38 AM" src="https://user-images.githubusercontent.com/1861713/69408302-918ed300-0d2c-11ea-9b3d-87a169799a90.png">
Steps To Reproduce: 
- On any Marathon Match type challenge, submit the submission
- Virus Scan should generate review with score `100` for the submission

Expected Result: Score from Virus Scan review must be filtered out and `100` score from the Virus Scan should not be displayed on the leaderboard

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/community-app/tree/hot-fix for PR

@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

**Comment by codeMinter** [comment]
@dushyantb can you share submission which generates 100 score. I tried submitting few dummy here but got -1 always. https://www.topcoder.com/challenges/30092303?tab=submissions

**Comment by codeMinter** [comment]
> @dushyantb can you share submission which generates 100 score. I tried submitting few dummy here but got -1 always. https://www.topcoder.com/challenges/30092303?tab=submissions
> 
> Looks like it is an issue with branch, on PROD this is working fine. I did get email with 100 virus scan but online it shows image for -1

ignore - I see the issue via code, looking into it why it wouldn't do as expected.

**Comment by sushilshinde** [comment]
@dushyantb issue fixed 

https://www.npmjs.com/package/topcoder-react-lib/v/1000.4.0

**Comment by codeMinter** [comment]
@dushyantb @sushilshinde are we good here ?

**Comment by harshitmehta123** [comment]
Hey @sushilshinde - When will this be deployed? I will inform the members about it. 
cc: @Oanh-and-only-Oanh

**Comment by nithyaasworld** [comment]
@codeMinter The issue seems to exist still. Could you check please?

![image](https://user-images.githubusercontent.com/5114190/70035089-41d7c380-15d8-11ea-8358-2227ed8a747e.png)

**Comment by nithyaasworld** [comment]
@codeMinter One more screenshot of the issue:

![image](https://user-images.githubusercontent.com/5114190/70035304-9b3ff280-15d8-11ea-9323-378836164a3a.png)

**Comment by sushilshinde** [comment]
@Oanh-and-only-Oanh @nithyaasworld deploying on beta please test in 20 mins

**Comment by nithyaasworld** [comment]
@codeMinter It just **shows a dash** now instead of showing one of the following statuses:

1. Submission in Queue
2. Submission Failed
3. Score of Submission

![image](https://user-images.githubusercontent.com/5114190/70346351-27c20d80-1884-11ea-8290-5f5f6e7cf099.png)

**Comment by codeMinter** [comment]
@nithyaasworld do you see in API response any reviews being passed back ?

**Comment by nithyaasworld** [comment]
Ok, In case, if no reviews are passed back, It should be with 'Submission in Queue' status.. right?

**Comment by codeMinter** [comment]
@nithyaasworld checked, it is issue with backend - check API response for Request URL: https://api.topcoder.com/v5/submissions?challengeId=30094385&page=1&perPage=500 in your browser. 

@dushyantb @cwdcwd can you help check why backend is not running review for the submissions @nithyaasworld is pushing.

**Comment by codeMinter** [comment]
> Ok, In case, if no reviews are passed back, It should be with 'Submission in Queue' status.. right?

No, we have status flag for each review, so if backend is running review, it should push a review element and mark status as in review and not completed. Let's see what @cwdcwd has here as I am not familiar a lot with backend process for MM reviews.

**Comment by codeMinter** [comment]
> @nithyaasworld checked, it is issue with backend - check API response for Request URL: https://api.topcoder.com/v5/submissions?challengeId=30094385&page=1&perPage=500 in your browser.
> 
> @dushyantb @cwdcwd can you help check why backend is not running review for the submissions @nithyaasworld is pushing.

@nithyaasworld I did discussed with @cwdcwd over slack the way we are showing now is ok. There are times when review wouldn't run for sometime, so we show `-`.  So once backend will trigger review, we will see a new review json in response which would have status as `in queue` in which case we show the icon you referring to.

**Comment by nithyaasworld** [comment]
> "There are times when the review wouldn't run for some time, so we show -"

But there are items with 'dash' for more than a month. Can you please confirm if this is okay?

![image](https://user-images.githubusercontent.com/5114190/70375461-087abd00-1924-11ea-8035-575bbf4df60f.png)

**Comment by codeMinter** [comment]
> > "There are times when the review wouldn't run for some time, so we show -"
> 
> But there are items with 'dash' for more than a month. Can you please confirm if this is okay?
> 
> ![image](https://user-images.githubusercontent.com/5114190/70375461-087abd00-1924-11ea-8035-575bbf4df60f.png)

@cwdcwd @dushyantb FYI ☝️ - this would need a fix on backend.

**Comment by codeMinter** [comment]
@nithyaasworld As you can verify this is something which needs to be fixed in backend as API is an issue here and not community-app which runs this. I did discussed with @cwdcwd last week and it is fine to show `-` when backend hasn't triggered Review for the submission. 

I think we shouldn't hold this for new work but yes, it is an issue should be track. I would suggest we open a new ticket to track it and assign it to @dushyantb who handles API impl for MM, I guess, so he can look into it and fix the backend logic for the same.

**Comment by SathyaJayabal** [comment]
Verified in p
<img width="1403" alt="3469 verification" src="https://user-images.githubusercontent.com/58783823/70845348-88001300-1e73-11ea-9a6e-9392f8cf6ebd.png">
roduction
