### ISSUE TITLE
[$10] - placeholder text overlap the search icon in mobile menu of TopcoderHeader

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#347]
## Steps to Reproduce
- Goto http://community-app.topcoder.com/challenges/ in portrait view on iPad
- Tap on the center of TopcoderHeader.
- menu opened, checkout the search input
- tap the search input, input some text to it and check 

## Actual Result(s)
- placeholder text overlap the search icon
- when there are characters in search input, the text overlap on the search icon

## Expected Result(s)
- placeholder text align to the right of search icon 
- text in search input align to the right of search icon

## Environment
```
Device(s): iPad Air2
Operating System:  iOS 9.3.2
Browser(s): Safari
```

## Image/Video/JS Log/Console Log (If not attached here, Please check the comments section)
![13b7ec87-b1c7-49ef-8557-2b802c40ef24](https://user-images.githubusercontent.com/948001/29750604-13501a66-8b75-11e7-849c-8cb51925f45b.png)

![c642d6fb-b31e-43cd-9a37-961de3d1b99d](https://user-images.githubusercontent.com/948001/29750895-7f0c90f4-8b7a-11e7-8da3-a0e769d153a1.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point
