### ISSUE TITLE
Submission tab for MM - Submission row is not showing `0` score while submission history is showing

### ISSUE THREAD

**Issue by dushyantb** [topcoder-platform/community-app#3470]
<img width="1097" alt="Screenshot 2019-11-22 at 1 34 27 PM" src="https://user-images.githubusercontent.com/1861713/69408524-22fe4500-0d2d-11ea-8083-bdafa2cfb7d8.png">
Steps To Reproduce: 
- On any Marathon Match type challenge, submit the submission
- Create the review with score `0` 

Expected Result: `0` score should be visible on the submission row as well

**Comment by sushilshinde** [comment]
Use https://github.com/topcoder-platform/community-app/tree/hot-fix for PR

@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

**Comment by sushilshinde** [comment]
Deployed on dev please test 

@Oanh-and-only-Oanh @nithyaasworld @codeMinter

**Comment by codeMinter** [comment]
@sushilshinde there was a failing scenario found so pushed the fix.

**Comment by nithyaasworld** [comment]
@codeMinter How do we test this on Dev environment? There is no MM Challenge with Score 0 in Dev environment.

**Comment by codeMinter** [comment]
> @codeMinter How do we test this on Dev environment? There is no MM Challenge with Score 0 in Dev environment.

@nithyaasworld true, from locally I was testing using PROD mode so yes we cannot unless we get some data on dev. 

@sushilshinde can we move this to beta?

**Comment by codeMinter** [comment]
> > @codeMinter How do we test this on Dev environment? There is no MM Challenge with Score 0 in Dev environment.
> 
> @nithyaasworld true, from locally I was testing using PROD mode so yes we cannot unless we get some data on dev.
> 
> @sushilshinde can we move this to beta?

moved to beta for testing

**Comment by nithyaasworld** [comment]
@codeMinter It shows 0 even when the score is not 0 ( i.e. it shows 0 for the score 'dash')

![image](https://user-images.githubusercontent.com/5114190/70370547-6d1b2500-18ee-11ea-986b-1da7000c6c2b.png)

**Comment by nithyaasworld** [comment]
Thanks @codeMinter 

Verified in beta:

![image](https://user-images.githubusercontent.com/5114190/70370695-5d9cdb80-18f0-11ea-804a-a011e847defc.png)

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1401" alt="3470 verification" src="https://user-images.githubusercontent.com/58783823/70845422-84b95700-1e74-11ea-96d3-f080bfd1addf.png">
