### ISSUE TITLE
Add QA tools logo to QA skills

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3472]
s profile settings page.

Tools [Free]
Selenium
JMeter
Jenkins
SoapUI
Appium
Espresso
Robotium
Cucumber
JIRA
Bugzilla
Postman
REST Assured
TestLink
Cypress
Robot Framework
Sahi
RedwoodHQ
Galen
Gauge

Tools [Paid]
HP Unified Functional Testing (UFT)
HP Quality Center (HP QC)
HP LoadRunner

I have also attached the logos of the above tools

Logos.zip

**Comment by sushilshinde** [comment]
https://github.com/topcoder-platform/community-app/issues/1564#issuecomment-561081908
