### ISSUE TITLE
Member Profile Screen: Some members have incorrect info and dead links

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3476]
Some of the affected users:

https://www.topcoder.com/members/tourist
https://www.topcoder.com/members/codejam
https://www.topcoder.com/members/mess

Issue1: Profile image, country, forum post link, profile name are incorrect for the above users
Issue2. Clicking on SRM or MM Activity link on tourist's profile shows some error. This issue likely to exist with the other two affected users.

Issue1 Screenshot:
![image](https://user-images.githubusercontent.com/5114190/69714026-a0f68d80-112b-11ea-8ef4-1900eea8b8b9.png)

Issue2 Screenshot:
![image](https://user-images.githubusercontent.com/5114190/69714085-c8e5f100-112b-11ea-94b0-e3f4fe19edaa.png)

**Comment by urwithat** [comment]
Thank you for informing, the fix has been deployed to development environment

**Comment by lakshmiathreya** [comment]
@urwithat @nithyaasworld Member Profile seems to be fine now except Forum posts.

**Comment by nithyaasworld** [comment]
Some more affected users in Production:

https://www.topcoder.com/members/wenbin
https://www.topcoder.com/members/maxceem

**Comment by nithyaasworld** [comment]
One more person whose profile image is missing: 

https://www.topcoder.com/members/picachui/ 

![image](https://user-images.githubusercontent.com/5114190/70392592-924f8680-1a07-11ea-8d80-d285a553fbfc.png)

**Comment by sandhiyakavi** [comment]
This issue is resolved now.

![image](https://user-images.githubusercontent.com/55895538/107182052-5fe05580-6a1f-11eb-90af-6b1969ecfde3.png)
![image](https://user-images.githubusercontent.com/55895538/107182104-79819d00-6a1f-11eb-870d-56a4bcf554bb.png)
![image](https://user-images.githubusercontent.com/55895538/107182163-95853e80-6a1f-11eb-9049-b17f4587fda6.png)
