### ISSUE TITLE
[$10] - Delete submission enable for past challenge

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#348]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges/30058497/my-submissions 

- See  Delete button 

Actual Result(s)
-----------------------------------------------------------------
-  Delete submission enable for past challenge

Expected Result(s)
-----------------------------------------------------------------
- Disable delete button 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 55.0.3

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-0bcc0aa7-5704-4b74-b7d4-49b5953caceb-2017-08-27-20-54-00](https://user-images.githubusercontent.com/3225433/29751358-ec6905ee-8b69-11e7-8e4d-274df0418e51.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points
