### ISSUE TITLE
Some of the menus in Beta env are redirecting to Prod env

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3488]
Some of the menus in Beta env are redirecting to Prod env. So cannot check the New Nav Menu for those menus.

Some Examples:
![image](https://user-images.githubusercontent.com/5114190/70143391-81c6a580-16c1-11ea-88cd-2a53a2580791.png)

![image](https://user-images.githubusercontent.com/5114190/70143553-f7cb0c80-16c1-11ea-97a5-76d5ec175bbb.png)

**Comment by nithyaasworld** [comment]
@luizrrodrigues

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @nithyaasworld, @sushil says it's an environment issue that won't be a problem in production. It's routing routing to the correct page so marking this as pass.

**Comment by luizrrodrigues** [comment]
@nithyaasworld This not be a problem in Prod. :)

**Comment by nithyaasworld** [comment]
Yes @luizrrodrigues but I am not able to check new-nav on those pages.

Is it easy to fix them in beta?

**Comment by luizrrodrigues** [comment]
Overview, How It Works and Why Join - All already update with new nav in Prod.

Dataset - This one is page level navigation.
But you can access with directly link:
https://beta-community-app.topcoder.com/community/data-science/datasets

**Comment by luizrrodrigues** [comment]
@nithyaasworld Note: I have updated some links to use path URL and not full URL. But some link need by full url, because is out from main domain.

**Comment by SathyaJayabal** [comment]
Verified in production
