### ISSUE TITLE
[$10] - time displays for past challenge 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#349]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges/30058497/my-submissions 

- observe 

Actual Result(s)
-----------------------------------------------------------------
-  time displays for past challenge 

Expected Result(s)
-----------------------------------------------------------------
- Should show like challenge is end 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 55.0.3

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-0bcc0aa7-5704-4b74-b7d4-49b5953caceb-2017-08-27-20-57-34](https://user-images.githubusercontent.com/3225433/29751393-635984e4-8b6a-11e7-94d9-45ce6aec278e.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points
