### ISSUE TITLE
Email preferences in Settings page is not working for my user

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3490]
Email preferences in Settings page are not working **for my user**

![image](https://user-images.githubusercontent.com/5114190/70174818-a17abf80-16fb-11ea-9d49-3f603770e3b2.png)

**Comment by nithyaasworld** [comment]
cc: @urwithat

**Comment by nithyaasworld** [comment]
This is fixed and working.

Thank you @urwithat

**Comment by urwithat** [comment]
@nithyaasworld - The users you've mentioned, according to API verification it working for all.
