### ISSUE TITLE
Skill/Competitor Search results do not have consistent results

### ISSUE THREAD

**Issue by crazyk07** [topcoder-platform/community-app#3492]
**Describe the bug**
Search results change each time you refresh the browser.  Also, when clicking on one profile and going back to the search results, the results change.

**To Reproduce**
1. Go to 'www.topcoder.com/challenges'
2. Click on 'member skill search'
3. Type in any skill
4. Refresh screen multiple times and click through profiels and go back to the results.  
5. Observe Bug

**Expected behavior**
List stays the same, since it is suppose to be the top competitors in that skill.

**Screenshots**
See Video

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 

**Smartphone (please complete the following information):**

**Additional context**
Video Link: https://drive.google.com/a/appirio.com/file/d/1x-yqnhKdL_MybIBB9rB5mFrQCw4fb0ln/view?usp=sharing

**Comment by crazyk07** [comment]
@Oanh-and-only-Oanh

**Comment by urwithat** [comment]
@Oanh-and-only-Oanh & @crazyk07 - When we are querying elastic search we sort by the score of a particular skill. If the members have the same skill score, they can be returned back in a different order. To solve this I'll put another sort on the usersId as we don't have any name field in our skills index.

**Comment by urwithat** [comment]
@Oanh-and-only-Oanh & @crazyk07 - deployed the fix to dev

**Comment by nithyaasworld** [comment]
@urwithat Can you please tell me How do we calculate this skill score?

When I search by the skill 'QA', I see a list of people who have never won any challenges in 'QA' 

![image](https://user-images.githubusercontent.com/5114190/70352062-4d551400-1890-11ea-992e-adf745aaa89f.png)

**Comment by urwithat** [comment]
@Oanh-and-only-Oanh - Can you please clarify @nithyaasworld question on how the skill score is calculated.

@nithyaasworld - There is not even one user with skill QA that has been given a score by participating in a challenge, in the production environment.

**Comment by Oanh-and-only-Oanh** [comment]
@nithyaasworld @urwithat, we don't any QA rating score currently and they are in the coding track for now. 
@urwithat, for QA skill, can we query list of members by number of QA challenges they have won?

**Comment by urwithat** [comment]
@nithyaasworld - fix deployed in prod

**Comment by nithyaasworld** [comment]
@urwithat Now I am seeing the following list of people when searching for 'QA'.. but actually these members are not our Top Members in 'QA'.. Expecting to see 'codejam', 'winterflame', 'sdgun', 'sandhiyaA', 'macs054' as these profiles have more wins in QA Challenges than the profiles we see at present.

![image](https://user-images.githubusercontent.com/5114190/70514098-f03fb380-1b58-11ea-83ef-d44581748817.png)

**Comment by SathyaJayabal** [comment]
The member handles/profile pic on the results page are not clickable. They should be links that take the user to the members profile page.

<img width="1424" alt="Screenshot 2020-01-13 at 10 06 44 AM" src="https://user-images.githubusercontent.com/58783823/72233304-92d1d300-35ec-11ea-9de0-09c8475c7053.png">
