### ISSUE TITLE
"member since" date is wrong in member search results

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3497]
This bug is first reported [here ](https://github.com/topcoder-platform/Training-Challenges/issues/34)

"member since" date is wrong in member search results

Screenshot: 

![image](https://user-images.githubusercontent.com/5114190/70398112-20defa80-1a3e-11ea-9c7e-7be0103d96f8.png)

**Comment by nithyaasworld** [comment]
cc: @urwithat

**Comment by urwithat** [comment]
@nithyaasworld & @Oanh Tran - This has been fixed, and is available in dev. Will do a deployment to prod tomorrow.

**Comment by urwithat** [comment]
Was reported by @codeMinter last week

**Comment by urwithat** [comment]
@nithyaasworld - Kindly test and closed if found fixed.

**Comment by nithyaasworld** [comment]
Verified.

Thanks @urwithat 

Verification Screenshot
![image](https://user-images.githubusercontent.com/5114190/70514880-6690e580-1b5a-11ea-9fea-bb3f5a6c0ee8.png)
