### ISSUE TITLE
update submission button enabled for past challenge 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#350]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges/30058497/my-submissions 

- observe 

Actual Result(s)
-----------------------------------------------------------------
-  update submission button enabled for past challenge 

Expected Result(s)
-----------------------------------------------------------------
- Should disable  update submission button  

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 55.0.3

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-0bcc0aa7-5704-4b74-b7d4-49b5953caceb-2017-08-27-20-43-35](https://user-images.githubusercontent.com/3225433/29751228-7710fffa-8b68-11e7-8df9-a471a6de25b4.png)

**Comment by birdofpreyru** [comment]
Dublicates #233
