### ISSUE TITLE
Add Project Fit to the CS portal homepage

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3501]
Requirements for CS Platform. 

Description: Copy the “project fit” section from the FAQ link to the home page. On the home page. Add a new image with a description and button that links to the project fit section. 
Navigate to home page. 
Click on FAQ link
Copy the contents of what is a good fit to home page. 
On the home page create another section at the bottom underneath “Why Topcoder works in Credit Suisse”  (replicate the image below). 
Replace the text “Why Topcoder works in Credit Suisse” with “What is a good fit”. 
Replace the description (text beneath the heading) with “This is a test for now”. 
Please note: I will work on getting you a description and image but I don’t want this hold you up from working on development therefore, just use the generic testing sentence. 
For now keep the same image. 
Please note: I will work on getting you an image but I don’t want this hold you up from working on development therefore, just use the same image 
Create a new button. With text that says “Lean More” 
When the button is clicked it should display the contents of “what is a good fit” 

Replicate this section on the home page and follow steps 4 -8.
See attachement
[Requirements for CS Platform.docx](https://github.com/topcoder-platform/community-app/files/3940636/Requirements.for.CS.Platform.docx)

**Comment by kkartunov** [comment]
Done.
