### ISSUE TITLE
Challenges listing page takes longer time ( more than 2 mins) to load the challenges

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3507]
1. Go to www.topcoder.com/challenges
2. Observe

Actual:
It shows the Loading indicator for a long time. After about 2+ mins, it shows the list of challenges with an error message as in the second screenshot below.

![image](https://user-images.githubusercontent.com/5114190/70688101-f22f8100-1cd6-11ea-9b6e-1f7e163ed06a.png)

![image](https://user-images.githubusercontent.com/5114190/70688022-c44a3c80-1cd6-11ea-9bd9-f2c5d3a293af.png)

**Comment by nithyaasworld** [comment]
cc: @sushilshinde @lakshmiathreya @urwithat @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
Happens when the backend api is down. Not an issue with the community app.
@sushilshinde
