### ISSUE TITLE
Community - > Overview links to about TCO18 page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3510]
Community - > Overview links to about TCO18 page

**To Reproduce**

Prerequisite: user must be logged out

1. Click on Community and then Overview in the new nav
2. Opens the About TCO18 page
https://www.topcoder.com/about-the-2018-topcoder-open/
3. Also opens the page in production, must open the correct page on the beta env.

**Expected behavior**
Should open the Community Overview page in the beta env.

[Community overview bug.mov.zip](https://github.com/topcoder-platform/community-app/files/3960061/Community.overview.bug.mov.zip)

**Comment by SathyaJayabal** [comment]
cc @nithyaasworld @lakshmiathreya

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh I need know what link need be.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @nithyaasworld, the Overview should direct user to https://www.topcoder.com/community/learn

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld @sachin-maheshwari 
This one was fixed/deployed and ready to test.

**Comment by SathyaJayabal** [comment]
verified

**Comment by SathyaJayabal** [comment]
Verified in Production
<img width="1400" alt="Screenshot 2019-12-19 at 7 21 36 PM" src="https://user-images.githubusercontent.com/58783823/71178743-d27af880-2294-11ea-8059-350ddc0403b1.png">
