### ISSUE TITLE
Community -> Tracks goes to "https://beta-community-app.topcoder.com/community/learn"

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3511]
**Describe the bug**
Community -> Tracks goes to "https://beta-community-app.topcoder.com/community/learn"

**To Reproduce**
Pre requisite: user must be logged out

1. Click on Community and then tracks
2. goes to "https://beta-community-app.topcoder.com/community/learn". 

**Expected behavior**
1. Is this the correct link for tracks ?
2. The second level menu is collapsed on clicking tracks. It should be expanded

**Screenshots**
[Community tracks bug.mov.zip](https://github.com/topcoder-platform/community-app/files/3960136/Community.tracks.bug.mov.zip)

**Comment by SathyaJayabal** [comment]
cc @nithyaasworld @lakshmiathreya

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh I need confirmation if link is right.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues and @nithyaasworld, take out TRACKS and WHY JOIN from submenu

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld @sachin-maheshwari 
This one was fixed/deployed and ready to test.

**Comment by SathyaJayabal** [comment]
verified

**Comment by SathyaJayabal** [comment]
verified in production
<img width="1400" alt="Screenshot 2019-12-19 at 7 19 18 PM" src="https://user-images.githubusercontent.com/58783823/71178594-87f97c00-2294-11ea-8553-5c5efc21de85.png">
