### ISSUE TITLE
Explore -> Forums takes the user to topcoder.com after logging in

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3513]
**Describe the bug**
Explore -> Forums takes the user to topcoder.com after logging in

**To Reproduce**
Prerequisite: user should be logged out
1. Click on Explore and the forums
2. Log in

**Expected behavior**
After logging in the user should be taken to the forums page instead of topcoder.com

**Screenshots**
[explore forums bug.mov.zip](https://github.com/topcoder-platform/community-app/files/3960208/explore.forums.bug.mov.zip)

**Comment by SathyaJayabal** [comment]
cc @nithyaasworld @lakshmiathreya

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This not a new nav issue, is how login redirect works.

Please test in Prod:
- Logout
- Go to challenge list: https://www.topcoder.com/challenges
- Login
- Will redirect to www.topcoder.com

**Comment by SathyaJayabal** [comment]
When you directly click on a link that requires logging in, then the user is taken to login page and then the original link. 
 
- Logout
- Go to Compete -> Competitive Programming
- Login
- Arena

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari I see, but in this case when try to access the page without login, the own page will redirect to login with retUrl, ( https://accounts.topcoder.com/member?retUrl=https:%2F%2Farena.topcoder.com%2Findex.html ) 

We can't add this via nav link.

@Oanh-and-only-Oanh This is a valid issue, but not related with navigation component and need fixed in page level.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, let's not worry about this right now as it's not part of Navi.

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @nithyaasworld pls review this and move to relevant milestone.

**Comment by sandhiyakavi** [comment]
It is now directing to Forums page after logging in

![image](https://user-images.githubusercontent.com/55895538/107189706-1f87d400-6a2d-11eb-9bc1-68531ba41b5f.png)
