### ISSUE TITLE
User icon -> About Topcoder goes to About TCO18 page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3514]
**Describe the bug**
User icon -> About Topcoder goes to About TCO18 page

**To Reproduce**
Prerequisite: user must be logged in
1. Click on the user icon on the top right
2. Click on "About Topcoder" menu item in the drop down menu that appears

**Expected behavior**
User is takes to "https://www.topcoder.com/about-the-2018-topcoder-open/" page instead of the correct About Topcoder page.

**Screenshots**
[about topcoder bug.mov.zip](https://github.com/topcoder-platform/community-app/files/3960254/about.topcoder.bug.mov.zip)

**Comment by SathyaJayabal** [comment]
cc @nithyaasworld @lakshmiathreya

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh I need know what link need be.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues , I'm not sure what the purpose of "About Topcoder" is that's different from the other pages. Let's just remove completely from drop down.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld @sachin-maheshwari 
This one was fixed/deployed and ready to test.

**Comment by SathyaJayabal** [comment]
verified

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1424" alt="Screenshot 2019-12-19 at 6 15 53 PM" src="https://user-images.githubusercontent.com/58783823/71174632-ae66e980-228b-11ea-9d66-18e662690b45.png">
