### ISSUE TITLE
Add THRIVE to submenu

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3515]
For Logged out AND logged IN users, add THRIVE to the navigation menu under EXPLORE next to Blog

![image](https://user-images.githubusercontent.com/47536078/70814753-ff08af00-1d80-11ea-81b2-3a3748065002.png)

THRIVE should direct users to https://www.topcoder.com/thrive

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld @sachin-maheshwari 
This one was fixed/deployed and ready to test.

**Comment by SathyaJayabal** [comment]
verified

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1417" alt="Screenshot 2019-12-19 at 6 13 56 PM" src="https://user-images.githubusercontent.com/58783823/71174501-5a5c0500-228b-11ea-99a5-d3c714733020.png">
