### ISSUE TITLE
Community - > How it works : Wrong link

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3516]
For logged out users,

**Describe the Bug:**
Community--> How it works : take user to FAQ page https://www.topcoder.com/faqs/

**Expected:**
"How it works" submenu under Community should direct members to https://www.topcoder.com/thrive/tracks?track=Topcoder

![image](https://user-images.githubusercontent.com/47536078/70815137-cfa67200-1d81-11ea-8225-7c6931ca903f.png)

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @nithyaasworld @sachin-maheshwari 
This one was fixed/deployed and ready to test.

**Comment by SathyaJayabal** [comment]
Verified

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1397" alt="Screenshot 2019-12-19 at 6 09 30 PM" src="https://user-images.githubusercontent.com/58783823/71174337-f20d2380-228a-11ea-9b45-18595f2f27b9.png">
