### ISSUE TITLE
$10 | Remove EVENTS on submenu

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3519]
For both Logged in and logged out states:

remove "EVENTS" on the submenu in the navi

![image](https://user-images.githubusercontent.com/47536078/71016619-43aa8800-20aa-11ea-9dca-63d8bc678cc9.png)

**Comment by iversonLv** [comment]
@luizrrodrigues Could I take this?

Thanks.

**Comment by luizrrodrigues** [comment]
@iversonLv Yes

**Comment by iversonLv** [comment]
@luizrrodrigues read for review
Thanks.

**Comment by nithyaasworld** [comment]
Verified in test-env

**Comment by SathyaJayabal** [comment]
Verified on beta
<img width="1418" alt="Screenshot 2020-02-27 at 11 06 01 AM" src="https://user-images.githubusercontent.com/58783823/75415296-3d117a00-5951-11ea-940e-7bb01ddd4ecd.png">
<img width="1424" alt="Screenshot 2020-02-27 at 11 06 15 AM" src="https://user-images.githubusercontent.com/58783823/75415301-400c6a80-5951-11ea-8eab-a7d5a77fc3b2.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1394" alt="Screenshot 2020-02-28 at 9 35 29 AM" src="https://user-images.githubusercontent.com/58783823/75509490-c090a100-5a0d-11ea-932e-3f525c501350.png">
<img width="1395" alt="Screenshot 2020-02-28 at 9 35 57 AM" src="https://user-images.githubusercontent.com/58783823/75509498-c4242800-5a0d-11ea-9ed3-d105d0b2f695.png">
