### ISSUE TITLE
Error message displayed when user try to submit for a challenge

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#352]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- http://community-app.topcoder.com/challenges/30059023/?type=design

- Register to the Challenge

- Click 'Submit'

Actual Result(s)
-----------------------------------------------------------------
- Error: You are either not registered for this challenge, or it is not a valid challenge. Please use your browser's back button to return.

Expected Result(s)
-----------------------------------------------------------------
- Must not display an error and user must able to submit for this challenge

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![66a](https://user-images.githubusercontent.com/4592712/29751671-129c0a5a-8b6e-11e7-8f23-c7655924c087.jpg)

**Comment by birdofpreyru** [comment]
It looks like a dublicate of #235
