### ISSUE TITLE
$15 | Open new tab for "Payments"

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3520]
For logged in state:

**Reported bug:** When user clicks on "Payment" in the submenu, they are directed to https://community.topcoder.com/PactsMemberServlet?module=PaymentHistory&full_list=false

**Expected behavior:**
When user clicks on "Payment" in the submenu, a separate tab should open that takes them to https://community.topcoder.com/PactsMemberServlet?module=PaymentHistory&full_list=false

**Comment by luizrrodrigues** [comment]
#3558 
https://github.com/topcoder-platform/navigation-component/pull/82

**Comment by luizrrodrigues** [comment]
@gets0ul Open in new tab works fine, but if back to origin page the Payments menu is active.

So when link will open in new tab we need make sure to not change status of link to active.

![image](https://user-images.githubusercontent.com/7029641/72357432-bdde2480-36c9-11ea-8511-f708bb5c926d.png)

**Comment by gets0ul** [comment]
@luizrrodrigues PR is updated.

**Comment by nithyaasworld** [comment]
Link is not active. However its in Payments menu-item with grey selection indicator.

@luizrrodrigues @Oanh-and-only-Oanh Is this okay?

Here is the screenshot:

**Comment by Oanh-and-only-Oanh** [comment]
Can you please share screenshot?

<https://www.topcoder.com/>

*Oanh Tran*

Product Manager, Community App

732-353-9457

www.topcoder.com  | @topcoder <http://twitter.com/topcoder>

**Comment by SathyaJayabal** [comment]
Verified in beta.

**Comment by macs054** [comment]
Verified in Prod
