### ISSUE TITLE
$10 | open new tab for "Forums"

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3521]
**For logged in state:**

**Reported bug:** When user clicks on "Forums" in the submenu, they are directed to https://apps.topcoder.com/forums/

**Expected behavior:**
When user clicks on "Forums" in the submenu, a separate tab should open that takes them to https://apps.topcoder.com/forums/

**For logged out state:**

**Reported bug:** When user clicks on "Forums" in the submenu, they are directed to https://accounts.topcoder.com/member

**Expected behavior:**
When user clicks on "Forums" in the submenu, a separate tab should open that takes them to https://accounts.topcoder.com/member

**Comment by luizrrodrigues** [comment]
Relate with #3520

**Comment by nithyaasworld** [comment]
Verified in test env that it opens a new window.

**Comment by SathyaJayabal** [comment]
Verified on beta

**Comment by macs054** [comment]
Verified in Prod
