### ISSUE TITLE
Switch to tc-core-library-js for fetching m2m token

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#3522]
Switch to tc-core-library-js for fetching m2m token

**Comment by sushilshinde** [comment]
https://github.com/topcoder-platform/topcoder-react-lib/pull/46

**Comment by sushilshinde** [comment]
https://github.com/topcoder-platform/topcoder-react-lib/issues/123

**Comment by SathyaJayabal** [comment]
Challenge details page is not loading
<img width="1430" alt="Screenshot 2020-02-25 at 9 38 15 AM" src="https://user-images.githubusercontent.com/58783823/75218889-5be10680-57c1-11ea-9b57-f59399f61e11.png">

**Comment by SathyaJayabal** [comment]
Verified on dev and beta (feature branch) on 28 feb

**Comment by SathyaJayabal** [comment]
verified on beta on mar.2 (develop branch)
verified on prod on mar 3
