### ISSUE TITLE
Contentful slider white arrows

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3524]
Contentful slider white arrows need to be transparent, not white.

![Screenshot from 2019-12-18 22-42-57](https://user-images.githubusercontent.com/5585002/71121788-cdac3b00-21e7-11ea-8ec6-0ef550f93230.png)

**Comment by SathyaJayabal** [comment]
Verified in production
<img width="1422" alt="Screenshot 2020-01-14 at 12 17 21 PM" src="https://user-images.githubusercontent.com/58783823/72320504-d8af9980-36c7-11ea-8007-3e3d34c06eed.png">
