### ISSUE TITLE
Blog link goes to 404

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3527]
The blog link from the new nav goes to the 404 page. (https://www.topcoder.com/blog)
Refreshing the page opens the blog correctly (https://www.topcoder.com/blog/)
<img width="1396" alt="Screenshot 2019-12-19 at 5 44 59 PM" src="https://user-images.githubusercontent.com/58783823/71172852-562de880-2287-11ea-8324-a99a8625e449.png">
[Blog link.mov.zip](https://github.com/topcoder-platform/navigation-component/files/3983522/Blog.link.mov.zip)

**Comment by lakshmiathreya** [comment]
@sushilshinde whats the version name for the next milestone?

**Comment by SathyaJayabal** [comment]
verified in beta

**Comment by SathyaJayabal** [comment]
Verified In production
[blog fixed.mov.zip](https://github.com/topcoder-platform/community-app/files/3987644/blog.fixed.mov.zip)
