### ISSUE TITLE
[Submission] enhance status message

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#353]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges/30058577/my-submissions

- observe left text 

Actual Result(s)
-----------------------------------------------------------------
-  "left " text shown under time  

Expected Result(s)
-----------------------------------------------------------------
- Should show same line 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 55.0.3

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-0bcc0aa7-5704-4b74-b7d4-49b5953caceb-2017-08-27-21-16-35](https://user-images.githubusercontent.com/3225433/29751580-0b66c726-8b6d-11e7-9357-de47dc2169bd.png)

**Comment by birdofpreyru** [comment]
It actually matches design:
![04 development - manage submission - empty state](https://user-images.githubusercontent.com/20144632/29752915-18a8e7bc-8b67-11e7-9c0d-72c1870e40a2.png)
I was thinking to reuse your ticket to enhance status messages (as you see, original design was a bit verbose to say `left to submission`), but I guess, it is actually done this way, when we are in submission phase? If not - please open another ticket about those messages in that place.
