### ISSUE TITLE
Settings page is different when navigating to it from the member search results page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3530]
1. go to challenges listings page
2. use member search from header to search for any member
3. member search results page is displayed
4. click on the user handle-> settings
5. older settings page is displayed

Some pages have the older header. (member search results page). When clicking on the settings page form the old head, from the user menu a different settings page is displayed.

Both the settings pages are different. please see video
<img width="1404" alt="Screenshot 2019-12-19 at 11 44 05 AM" src="https://user-images.githubusercontent.com/58783823/71187571-53da8700-22a5-11ea-9858-700e30aaa903.png">
<img width="1405" alt="Screenshot 2019-12-19 at 11 51 53 AM" src="https://user-images.githubusercontent.com/58783823/71187572-53da8700-22a5-11ea-8eb9-abcf69d66b41.png">
[settings page different UI.mp4.zip](https://github.com/topcoder-platform/community-app/files/3984373/settings.page.different.UI.mp4.zip)

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, can you verify if this is still an issue? If so, is the navigation the new or old?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , Yes, it is still an issue. The issue is with the old nav. At present production has some pages with old nav( like the member search results page). Do we let is get fixed when we move the member search to the community app (#3550) ?

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, this should should get fixed with when we move the member search to community App. Can you add that requirement to #3550?  thanks
