### ISSUE TITLE
Same Challenges displayed under more than one track

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3531]
**Describe the bug**
Some of the Challenges are displayed under more than one track in the challenge listing page
For example a code challenge with keyword Data science shows up under both the Development and Data Science tracks. Is this the expected behaviour ?

<img width="1440" alt="Screenshot 2019-12-19 at 9 28 23 PM" src="https://user-images.githubusercontent.com/58783823/71188284-b1230800-22a6-11ea-9536-15f7a7b9686a.png">
<img width="1437" alt="Screenshot 2019-12-19 at 9 29 05 PM" src="https://user-images.githubusercontent.com/58783823/71188285-b1230800-22a6-11ea-9a73-09d894c3e25b.png">

cc @sushilshinde @nithyaasworld

**Comment by nithyaasworld** [comment]
cc: @cwdcwd

**Comment by ajefts** [comment]
That is the expected behavior.

**Comment by sushilshinde** [comment]
Thanks @ajefts
