### ISSUE TITLE
Clicking on Apply from open for review listings in challenge listing page shows an error

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3543]
User is not logged in
Go to All Challenges
Click on Open for review filter
click on apply for any of the challenges listed

actual: displays  the review opportunities page with an error
expected: must redirect the user to login page
<img width="1427" alt="Screenshot 2020-01-06 at 4 45 32 PM" src="https://user-images.githubusercontent.com/58783823/71820118-3171a780-30b4-11ea-81c5-66953f35037c.png">

**Comment by sandhiyakavi** [comment]
Closing the issue as its directing to login page now.

![image](https://user-images.githubusercontent.com/55895538/106864241-ef7ac100-670c-11eb-8e87-b1adc61b6531.png)
