### ISSUE TITLE
Migrate Member Search Feature on Community App

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3550]
Migrate the search feature into community app as opposed to trying to update the nav on that old topcoder-app.   topcoder-app should be deprecated.

<p></p>

Front-end code

<https://github.com/appirio-tech/topcoder-app/blob/dev/app/layout/header/header.jade>

<https://github.com/appirio-tech/topcoder-app/tree/dev/app/member-search>

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/3613959

**Comment by SathyaJayabal** [comment]
Migration should fix issue reported in #3530

**Comment by LieutenantRoger** [comment]
Challenge Link to address this feature: https://www.topcoder.com/challenges/30115867/?type=develop

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , the search from the header in the test env is redirecting the user to the search results page of the dev env(legacy page). Please see video.
The migrated search results page works fine when accessed using the url. The search functionality works fine.
[search.mov.zip](https://github.com/topcoder-platform/community-app/files/4281032/search.mov.zip)

**Comment by LieutenantRoger** [comment]
Thanks, will take a look at the navigation issue.

**Comment by LieutenantRoger** [comment]
The fixes to the issues above are deployed under `test` environment

**Comment by SathyaJayabal** [comment]
Verified on test (feature branch)
<img width="1440" alt="Screenshot 2020-03-09 at 10 58 50 AM" src="https://user-images.githubusercontent.com/58783823/76185403-2262bf00-61f5-11ea-9407-208a8093c0f6.png">

**Comment by macs054** [comment]
Verified in Beta
![image](https://user-images.githubusercontent.com/1199534/76407812-e54e2680-63c6-11ea-9636-d7140a89c6c5.png)

**Comment by SathyaJayabal** [comment]
verified on production
<img width="1440" alt="Screenshot 2020-03-12 at 12 16 23 PM" src="https://user-images.githubusercontent.com/58783823/76495088-2f351c00-645c-11ea-9e7f-5eee97628e59.png">
<img width="1440" alt="Screenshot 2020-03-12 at 12 16 30 PM" src="https://user-images.githubusercontent.com/58783823/76495099-34926680-645c-11ea-8fc2-e27815d6411d.png">
