### ISSUE TITLE
Contentful leaderboards fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3552]
- Leaderboard podium cards -  "fulfillment" text color should be #2A2A2A. Demo https://tco20.topcoder.com/competition-overview/win-a-trip/copilot-tournament
- Leaderboard podium - move the 1st,2nd and 3rd card upper to be closer to that tabs. In case of title is empty do not render H2 tag that makes layout expand.
- Add 4th place podium card to leaderboards and required support for it.

Design to follow is here: https://marvelapp.com/5554efd/screen/65173645

Entry component: https://github.com/topcoder-platform/community-app/tree/develop/src/shared/containers/tco/Leaderboard

**Comment by manoj389852** [comment]
Kindly give permission to work  on this issue

**Comment by SathyaJayabal** [comment]
@kkartunov @sushilshinde , This issue is deployed on beta, can you please give us the beta URL to test this ? The below links are not working.
https://beta-community-app.tco20.topcoder.com/competition-overview/win-a-trip/copilot-tournament
https://tco20.beta-community-app.topcoder.com/competition-overview/win-a-trip/copilot-tournament
cc @Oanh-and-only-Oanh

**Comment by kkartunov** [comment]
@SathyaJayabal test URLs are here:
- beta: https://beta-community-app.topcoder.com/__community__/tco20/competition-overview/marathon/leaderboard
- dev: http://community-app.topcoder-dev.com/__community__/tco20/competition-overview/marathon/leaderboard

I think it works but please do QA.
Thanks

**Comment by SathyaJayabal** [comment]
- Leaderboard podium cards - "fulfillment" text color should be #2A2A2A. Demo (**Fixed**)
<img width="290" alt="Screenshot 2020-01-20 at 5 29 33 PM" src="https://user-images.githubusercontent.com/58783823/72724869-816b6680-3baa-11ea-8f3f-6e33440364e8.png">

- Leaderboard podium - move the 1st,2nd and 3rd card upper to be closer to that tabs. In case of title is empty do not render H2 tag that makes layout expand. (**Not Fixed**)
- Add 4th place podium card to leaderboards and required support for it.

**Comment by SathyaJayabal** [comment]
- Leaderboard podium cards - "fulfillment" text color should be #2A2A2A. Demo (**Fixed**)

- Leaderboard podium - move the 1st,2nd and 3rd card upper to be closer to that tabs. In case of title is empty do not render H2 tag that makes layout expand. (**Not Fixed**)
The cards have not been moved up.
<img width="1440" alt="Screenshot 2020-01-20 at 5 34 05 PM" src="https://user-images.githubusercontent.com/58783823/72725609-30f50880-3bac-11ea-8ba8-2460dd8ef18b.png">
<img width="1438" alt="Screenshot 2020-01-20 at 5 34 25 PM" src="https://user-images.githubusercontent.com/58783823/72725610-30f50880-3bac-11ea-95c0-e6265cbe3227.png">

- Add 4th place podium card to leaderboards and required support for it. (**Not Fixed**)

Some of the track leaderboards have only three cards, even though the rules say four finalists per stage
<img width="1439" alt="Screenshot 2020-01-20 at 5 44 32 PM" src="https://user-images.githubusercontent.com/58783823/72725742-8e895500-3bac-11ea-913c-ef025669b28b.png">
Tracks :
Algorithm -  shows three cards (top 1 gets a berth to onsite round and next 11 advance from this stage to online round 4, so I am not sure if 3 or 4 cards is correct for this track, maybe just one card )
Development - shows three cards, but four finalists are selected from each stage
F2F - shows three cards, but four finalists are selected from each stage
QA -  shows three cards, but four finalists are selected from each stage
UI Design - shows three cards, but four finalists are selected from each stage

- Alignment issue : The stage headers, the leaderboard title and the leaderboard table is not aligned like in the design.
<img width="1427" alt="Screenshot 2020-01-20 at 5 54 54 PM" src="https://user-images.githubusercontent.com/58783823/72726421-4ff49a00-3bae-11ea-8a05-17d6f5f17cc2.png">
<img width="1393" alt="Screenshot 2020-01-20 at 5 56 37 PM" src="https://user-images.githubusercontent.com/58783823/72726423-508d3080-3bae-11ea-8829-4bdb43c695a2.png">

**Comment by SathyaJayabal** [comment]
cc @kkartunov

**Comment by kkartunov** [comment]
@SathyaJayabal thank you for your testing.

Please note that Contentful is a little different than the other parts of the app. We will need to sync together to complete tasks.

For this one:
- Podium cards are moved upper as per spec. You can compare it to the current prod http://tco20.topcoder.com/competition-overview/marathon/leaderboard see Stage 1.

- You see the demo is switched to 4. Rest needs to be switched from Contentful which we will do when we have this one in production.

- Alignment issues are known. This can't be other as because of the leaderbord table width differences between design and real prod. In prod we do have  1024px width but in design is 1035px. 

I think we should accept this one.

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal , thanks for testing. @kkartunov, thanks for the follow up explanation. I'm marking this as QA Pass per the comments.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @kkartunov , Is this bug only for the demo track. Can we verify this issue for the one track and close this bug?

**Comment by SathyaJayabal** [comment]
Verified in production.
<img width="1436" alt="Screenshot 2020-01-21 at 3 13 27 PM" src="https://user-images.githubusercontent.com/58783823/72793679-c94cc500-3c60-11ea-8a2a-a47a125a07a9.png">
<img width="1437" alt="Screenshot 2020-01-21 at 3 14 12 PM" src="https://user-images.githubusercontent.com/58783823/72793684-c9e55b80-3c60-11ea-8b21-998adc49479e.png">

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, please close out the tickets that pass QA in PROD. Thank you.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , the changes have been made to just one track(for demo). Waiting for the changes to be applied to the other tracks before closing this ticket.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , I am closing this out. We can create a new issue for the rest of the tracks.

**Comment by kkartunov** [comment]
Not in prod

**Comment by SathyaJayabal** [comment]
Verified.
<img width="1440" alt="Screenshot 2020-01-23 at 2 10 56 PM" src="https://user-images.githubusercontent.com/58783823/72969212-0a70e080-3deb-11ea-8f08-8fa88de17f37.png">

**Comment by SathyaJayabal** [comment]
@bug-hunt-helper help
