### ISSUE TITLE
Add submission button enabled at apporval phase 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#356]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user 

- Go to http://community-app.topcoder.com/challenges/30058497/my-submissions 

- observe 

Actual Result(s)
-----------------------------------------------------------------
- Add submission button enabled at apporval phase  

Expected Result(s)
-----------------------------------------------------------------
- Should disable add submission button 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 8.1
- **Browser(s):** FF 55.0.3

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![screenshot-0bcc0aa7-5704-4b74-b7d4-49b5953caceb-2017-08-27-21-18-05](https://user-images.githubusercontent.com/3225433/29751793-17f7a200-8b70-11e7-9b1c-ae0d46016ac5.png)

**Comment by birdofpreyru** [comment]
I'll accept for 1 point, though it is mostly dublicate of #233
