### ISSUE TITLE
Get THRIVE article recommendations in challenge details page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3565]
Challenge spec. 

Dev copilot: Veshu

Design copilot: Fajar

<https://docs.google.com/document/d/1KeGUf57j9sdSft7EJt00387_JnTaifIZVXGp11ywb4c/edit?usp=sharing>

<p></p>

additional requirements:  

- display up to 3 related challenges and 3 articles

- If challenge is tagged with "other", do not show anything

- if more than one tag is present, display related articles and challenges based on first tag

<p></p>

<p></p>

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1849761

**Comment by veshu** [comment]
The challenge for recommended article https://www.topcoder.com/challenges/30113877
There will be separate challenge for related challenges.

**Comment by SathyaJayabal** [comment]
1. Recommendations links and articles do not show up when the user clicks on other tabs in the challenge details page (Registrants, Submissions). Is this the expected behaviour?  See attached video for reference.
[thrive.mov.zip](https://github.com/topcoder-platform/community-app/files/4179093/thrive.mov.zip)

2. Title must be left aligned to the first card. The marvel design is also not aligned. Is this the expected design?
<img width="1401" alt="Screenshot 2020-02-10 at 10 58 12 AM" src="https://user-images.githubusercontent.com/58783823/74123313-63ff4a80-4bf4-11ea-8750-dcec1aef5136.png">

3. When there are less than three articles, what should be the alignment of the cards? Left aligned or center aligned?




cc @Oanh-and-only-Oanh , @veshu @lakshmiathreya

**Comment by veshu** [comment]
1 and 3 I have confirmed that on forum to be so. @Oanh-and-only-Oanh @Dara-K please suggest your thought.

**Comment by SathyaJayabal** [comment]
@veshu , I don't have access to the challenge forums. Shall I consider 1 and 3 as expected ?

**Comment by Dara-K** [comment]
Hi @SathyaJayabal 

Good points!

1. Recommended Links and Articles should stay in the header even when the user moves to any tabs : details registrants, checkpoints, etc.

2. You can move the title more to the left, to have that space removed.

3. Should be left-aligned.

**Comment by SathyaJayabal** [comment]
@Dara-K , thank you for the answers.

@veshu , I am marking this as QA fail, so that the above can be fixed.

**Comment by veshu** [comment]
ok getting fixed this at f2f https://www.topcoder.com/challenges/30115205

**Comment by SathyaJayabal** [comment]
@veshu, Verified on dev.

<img width="1371" alt="Screenshot 2020-02-12 at 11 19 57 AM" src="https://user-images.githubusercontent.com/58783823/74306858-ca69a180-4d89-11ea-9b28-c8200f18225d.png">
<img width="1375" alt="Screenshot 2020-02-12 at 11 20 10 AM" src="https://user-images.githubusercontent.com/58783823/74306866-cf2e5580-4d89-11ea-9892-54c1f9bcafb8.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1433" alt="Screenshot 2020-02-17 at 10 40 39 AM" src="https://user-images.githubusercontent.com/58783823/74625370-0c238f00-5172-11ea-958e-bfe43f3802cc.png">

@veshu , When less than three related thrive articles are present, they are not left aligned like the recommenced challenges. They expand to fill the space. See attached screenshot above for reference. Is this behaviour ok? If not I will create a new issue to fix this.

**Comment by veshu** [comment]
@Dara-K @Oanh-and-only-Oanh Please check if fluid card of thrive article is okay or it should be fixed width.

**Comment by Dara-K** [comment]
@veshu @SathyaJayabal   When there are less than 3 cards, I suggest to keep them left aligned (use same width as when there are 3 cards)

**Comment by SathyaJayabal** [comment]
verified
<img width="1418" alt="Screenshot 2020-02-19 at 2 24 23 PM" src="https://user-images.githubusercontent.com/58783823/74817816-9101da80-5323-11ea-9500-0f5042a7f62c.png">

**Comment by SathyaJayabal** [comment]
Verified in prod
<img width="1428" alt="Screenshot 2020-02-19 at 6 14 57 PM" src="https://user-images.githubusercontent.com/58783823/74836130-c79c1d00-5344-11ea-8b0c-fed70ce62f75.png">
