### ISSUE TITLE
ThemedButtons are changed when used in dashboard banner

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3593]
As following demo shows https://community-app.topcoder.com/my-dashboard?announcementPreviewId=2Gy61Ty0FUD5Z9GHyCDq26 buttons are changed from original design/implementation when used in dashboard banner. 

They should look like design reference: https://community-app.topcoder.com/examples/contentful/contentblock/3k7k1JpnSvIRrJYWs4izYi

**Comment by SathyaJayabal** [comment]
Verified on beta
<img width="1347" alt="Screenshot 2020-01-30 at 2 22 19 PM" src="https://user-images.githubusercontent.com/58783823/73434031-fd646c00-436b-11ea-8b4b-b03e09bc2904.png">

**Comment by kkartunov** [comment]
Done.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1406" alt="Screenshot 2020-01-30 at 5 52 49 PM" src="https://user-images.githubusercontent.com/58783823/73449522-61495d80-4389-11ea-9105-7ae3bd4f4d50.png">
