### ISSUE TITLE
Clicking on fourth place card member handle from leaderboard goes to blank page (DEV,QA,F2F,Design tracks)

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3603]
1. Go to tco20 leaderboard for any of the four tracks (Dev, QA, F2F, Design)
https://tco20.topcoder.com/competition-overview/first2finish/leaderboard
https://tco20.topcoder.com/competition-overview/development/leaderboard
https://tco20.topcoder.com/competition-overview/qa/leaderboard
https://tco20.topcoder.com/competition-overview/ui-design/leaderboard
2. Click on the member handle of the fourth place member 

Actual: A blank screen is displayed.
[history popup.mov.zip](https://github.com/topcoder-platform/community-app/files/4102473/history.popup.mov.zip)

Expected :The completed challenges history popup must be displayed
<img width="1012" alt="Screenshot 2020-01-23 at 3 42 11 PM" src="https://user-images.githubusercontent.com/58783823/72975517-f337f000-3df6-11ea-8c4f-4bd4b46387de.png">

**Comment by kkartunov** [comment]
PR for this https://github.com/topcoder-platform/community-app/pull/3613

**Comment by SathyaJayabal** [comment]
Verified on beta 
<img width="1402" alt="Screenshot 2020-01-30 at 9 23 24 AM" src="https://user-images.githubusercontent.com/58783823/73418613-3b4c9a80-4342-11ea-92ea-b5308cedf1e0.png">

**Comment by SathyaJayabal** [comment]
Verified on beta
<img width="1440" alt="Screenshot 2020-01-30 at 12 40 26 PM" src="https://user-images.githubusercontent.com/58783823/73428028-149c5d00-435e-11ea-9122-8b54b241a116.png">

**Comment by kkartunov** [comment]
Done.

**Comment by SathyaJayabal** [comment]
Verified in prod
<img width="1398" alt="Screenshot 2020-01-30 at 5 49 20 PM" src="https://user-images.githubusercontent.com/58783823/73449433-25ae9380-4389-11ea-8925-cbf0aa682772.png">
