### ISSUE TITLE
[$10] - Search input at search flyout not vertical align

### ISSUE THREAD

**Issue by iversonLv** [topcoder-platform/community-app#361]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Hover on top right corner search icon

- Slide down the search flyout

Actual Result(s)
-----------------------------------------------------------------
- Open the flyout, the placeholder not vertical align

Expected Result(s)
-----------------------------------------------------------------
- The value(placeholder) should vertical align

Environment
-----------------------------------------------------------------
- **Device(s):** Desktop PC
- **Operating System:** Windows 10 64bit
- **Browser(s):** Version 60.0.3112.113 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![image](https://user-images.githubusercontent.com/4952611/29754760-a4c4840c-8bbe-11e7-8fa4-c44aebc5317c.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

**Comment by elfman** [comment]
sorry, I wrote a wrong issue id in my commit
