### ISSUE TITLE
Get Recommendations Challenges on challenge details page 

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3620]
Challenge spec.

Dev copilot: Veshu

Design copilot: Fajar

https://docs.google.com/document/d/1KeGUf57j9sdSft7EJt00387_JnTaifIZVXGp11ywb4c/edit?usp=sharing

additional requirements:

display up to 3 related challenges and 3 articles

If challenge is tagged with "other", do not show anything

if more than one tag is present, display related articles and challenges based on first tag

**Comment by veshu** [comment]
The challenge has been launched at https://www.topcoder.com/challenges/30114285

**Comment by SathyaJayabal** [comment]
The recommended challenges must not include the current challenge (the challenge that is being viewed).

Clarifications needed:
1. Title must be left aligned to the first card. The marvel design is also not aligned. Is this the expected design?
<img width="1401" alt="Screenshot 2020-02-10 at 10 58 12 AM" src="https://user-images.githubusercontent.com/58783823/74124049-f6085280-4bf6-11ea-9acc-40baf0b99288.png">

2. When there are less than three articles, what should be the alignment of the cards? Left aligned or center aligned?
<img width="1259" alt="Screenshot 2020-02-10 at 11 15 14 AM" src="https://user-images.githubusercontent.com/58783823/74124029-d4a76680-4bf6-11ea-810b-45aefca23edd.png">

3. Clicking on a recommended challenge opens the challenge in the same tab. Should it open the challenge in a new tab?

**Comment by SathyaJayabal** [comment]
cc @Oanh-and-only-Oanh @lakshmiathreya @veshu  , please see clarifications needed items in the above comment.

**Comment by TheOsch** [comment]
Excuse me.. So what's the answer? Must we align those 2 challenges left or leave them as they are?

**Comment by veshu** [comment]
@TheOsch based on this https://github.com/topcoder-platform/community-app/issues/3565#issuecomment-583999810

1. You can move the title more to the left, to have that space removed.

2. Should be left-aligned.

**Comment by TheOsch** [comment]
Clear, thank you.

**Comment by TheOsch** [comment]
And these two lines in CSS are really everything that we have to do? Cool.

**Comment by veshu** [comment]
@TheOsch Yes correct. Also please check https://github.com/topcoder-platform/community-app/issues/3565#issuecomment-583964673 these 3 items too

**Comment by TheOsch** [comment]
To open contest links in a new tab? Yes, it's convenient.

**Comment by SathyaJayabal** [comment]
@TheOsch , please also check this comment

"The recommended challenges must not include the current challenge (the challenge that is being viewed). "
At present, the recommended challenges also includes the challenge whose detail page is being viewed. This should not be the case. 

cc @veshu

**Comment by SathyaJayabal** [comment]
#veshu, everything looks fine except for the below minor issues

1. clicking on # of registrants should open the challenge detail page(registrants tab selected when number of reg > 0, else details tab selected) in a new tab. Currently it is opening in the same tab.
2. Clicking on #of Subs should open the challenge detail page(submissions tab selected when number of submissions > 0, else details tab selected) in a new tab. Currently it is opening in the same tab and the details tab is selected even when submission > 0.

<img width="1368" alt="Screenshot 2020-02-12 at 11 27 54 AM" src="https://user-images.githubusercontent.com/58783823/74307257-ede11c00-4d8a-11ea-92a3-44281e886ca9.png">

**Comment by SathyaJayabal** [comment]
@veshu 
1. this is fixed.
2. When you click on the number of submissions, it opens the challenge in the new tab(as expected) but the selected tab is details. But the selected tab of the current window is changed to submissions tab. 

see video for reference.
[submissions count link.mov.zip](https://github.com/topcoder-platform/community-app/files/4190695/submissions.count.link.mov.zip)

**Comment by SathyaJayabal** [comment]
@veshu , verified on beta (feature branch)

<img width="1432" alt="Screenshot 2020-02-13 at 8 53 48 PM" src="https://user-images.githubusercontent.com/58783823/74449745-047a9680-4ea3-11ea-8371-eccc12796e06.png">

**Comment by SathyaJayabal** [comment]
verified in beta
<img width="1433" alt="Screenshot 2020-02-17 at 10 40 39 AM" src="https://user-images.githubusercontent.com/58783823/74625332-fc0baf80-5171-11ea-89dc-e68ed55d3c33.png">

**Comment by SathyaJayabal** [comment]
Verified in Prod
<img width="1428" alt="Screenshot 2020-02-19 at 6 14 57 PM" src="https://user-images.githubusercontent.com/58783823/74836179-e26e9180-5344-11ea-988e-2a5360392bf8.png">
