### ISSUE TITLE
Alphabetize Sub-Categories in Thrive

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3630]
**Expected**: Sub-Categories in Thrive should be in alphabetical order.

Bonus: If possible to follow orders as listed in Contentful.

**Comment by kkartunov** [comment]
For reference: https://topcoder.monday.com/boards/444155520/pulses/444305529

**Comment by SathyaJayabal** [comment]
@kkartunov , I do not have access to these boards
https://topcoder.monday.com/boards/444155520/pulses/444305529

Is there any other information in the boards apart from the subcategories alphabetical order ?

Verified on test
<img width="1405" alt="Screenshot 2020-02-11 at 2 43 06 PM" src="https://user-images.githubusercontent.com/58783823/74223528-e95e2a00-4cdc-11ea-8482-482f775645b9.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1435" alt="Screenshot 2020-02-12 at 1 27 54 PM" src="https://user-images.githubusercontent.com/58783823/74314489-82537a80-4d9b-11ea-91de-bcc04e659b79.png">

**Comment by SathyaJayabal** [comment]
verified in production
<img width="1427" alt="Screenshot 2020-02-12 at 6 18 17 PM" src="https://user-images.githubusercontent.com/58783823/74336359-1c2f1d80-4dc4-11ea-84fe-3a5ccd658568.png">
