### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3647]
![image](https://user-images.githubusercontent.com/42398485/73994628-d681d900-491b-11ea-8ef0-486a995ba858.png)

**Target URL:** https://www.topcoder.com/thrive

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive
3. Enter 'sadsadsadfasdsad' and press Enter
4. Should display the matching articles /or should display No results found

**Actual:** Search is not working

**Expected:** Search Should work

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge 44.18362.449.0 | Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
Actually, the search is working. When there are search results returned, there will be a modal displayed below the keyword. Maybe we need to display something like "No results found" when nothing found.
cc: @kkartunov

**Comment by kkartunov** [comment]
Done.
