### ISSUE TITLE
Featured Articles ui issue 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3648]
Target URL: https://www.topcoder.com/thrive

### Reproduction Steps ###

1 goto website 
2 see Featured Articles

### Expected Result ###
Should show properly 

### Actual Result ###

layout is not proper 
![bandicam 2020-02-07 07-34-30-514](https://user-images.githubusercontent.com/3225433/73994656-53449f80-497c-11ea-8e34-21d3064cd906.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
It's on purpose, not a bug.
