### ISSUE TITLE
search not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3649]
Target URL: https://www.topcoder.com/thrive

### Reproduction Steps ###

1 goto web
2 In search filed enter qa
3 press enter 

### Expected Result ###
should show search result 

### Actual Result ###
nothing happens 

### Screenshots or screencast ###

[bandicam 2020-02-07 07-38-53-529.zip](https://github.com/topcoder-platform/community-app/files/4168654/bandicam.2020-02-07.07-38-53-529.zip)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
Dupe with https://github.com/topcoder-platform/community-app/issues/3647
