### ISSUE TITLE
[$20] - [Mobile] [Challenge Filter]: Select can not choose the item which is covering the Date range field

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#365]
Steps to Reproduce
-----------------------------------------------------------------

- access to http://community-app.topcoder.com/challenges/ in iPad on portrait

- Tap `Filter`, open filter dialog

- Tap the Select of Keywords or Subtrack, select the item which is at the same line of Date range

- Tap on the area outside the date picker

Actual Result(s)
-----------------------------------------------------------------
- Select closed but the item of Select is not selected, and the date picker opened
- Date picker is not closed when tap on the are out the picker, unless the start date and end date has been chose.

Expected Result(s)
-----------------------------------------------------------------
- the item of Select should be selected, the date range picker should not be triggered.
- When tap on the area outside the date range picker, the picker should be closed

Environment
-----------------------------------------------------------------
- **Device(s):** iPad Air2
- **Operating System:** iOS 9.3.2
- **Browser(s):** Safari

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.
