### ISSUE TITLE
The page content is lacked of padding

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3650]
Title: The page content is lacked of padding

Target URL: https://www.topcoder.com/thrive
### Reproduction Steps ###
1. Open the page
### Expected Result ###
There should be a padding of the page container
### Actual Result ###
The container don’t have a padding, the page’s element is close to the edge of the page.
### Screenshots or screencast ###
![Xnip2020-02-07_10-09-42](https://user-images.githubusercontent.com/5466773/73994980-46cb4180-4992-11ea-9c19-67a9564d743e.jpg)
### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by staticfire** [comment]
This issue should be displayed when browser's width is under 1280px

**Comment by winterflame** [comment]
Not a bug, the page is responsive.
