### ISSUE TITLE
[Web-Firefox] Go To TCO 20 Have Alignment Issue 

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3651]
1. Go To https://www.topcoder.com/community/member-programs/topcoder-open

2. Click On TCO

3. Click On Go To TCO20

4. See Screenshot

5. Expected Result: Go To TC20 Should Be Aligned Properly

6. Actual Result: Go To TCO20 Having Alignment Issue

7. Screenshot:
![TCO 20 1](https://user-images.githubusercontent.com/42583358/73995268-0a8de600-497e-11ea-9f2c-7578b74c1ea4.png)

8. OS Details: 
![Mac Version](https://user-images.githubusercontent.com/42583358/73995089-a66b2200-497d-11ea-8c81-2b197a939ea2.png)

9. Browser: 
![Firefox Version](https://user-images.githubusercontent.com/42583358/73995056-89365380-497d-11ea-8ee0-65a0bf2c3e47.png)

**Comment by winterflame** [comment]
Out of scope.
