### ISSUE TITLE
Filter should not display populated dates

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3652]
![image](https://user-images.githubusercontent.com/42398485/73995146-65432580-491d-11ea-8832-ffea6695d02a.png)

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming

1. Open the Application and Login as valid user
2. Click 'COMPETITIVE PROGRAMMING' title
3. Click 'Show Filter' > tag=Math > Apply Filter
4. No results found because the date filter is already set by default

**Actual:** Filter should not display populated dates

**Expected:** Dates values should be empty. If not each and every filter user needs to set the dates

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge 44.18362.449.0 | Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by kkartunov** [comment]
This filter panel is being redesigned.
