### ISSUE TITLE
Content not well aligned

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3653]
![align](https://user-images.githubusercontent.com/37167721/73995281-233fd100-4969-11ea-9f04-ede87a00297f.jpg)
Target URL: https://www.topcoder.com/thrive

Open the Application and Login as valid user
Go to https://www.topcoder.com/thrive
Observe under "FEATURED ARTICLES"
Cards should be well aligned
Actual: The content is not well aligned

Expected: The cards with content should be well aligned

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Dupe with https://github.com/topcoder-platform/community-app/issues/3648
