### ISSUE TITLE
"Like/ Dislike" button doesn't work

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#3654]
**Describe the bug**
![Screenshot_1](https://user-images.githubusercontent.com/26895101/73995048-18496880-498a-11ea-80cb-26f50bef2ae0.png)

**To Reproduce**
1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder
3. Click on "Like/ Dislike" button and observe

**Actual:** "Like/ Dislike" button doesn't work

**Expected:** "Like/ Dislike" button should be work

**Environment:** Lenovo legion, Windows 10
**Browser:**  Google Chrome 80.0.3987.87

**Comment by kkartunov** [comment]
Fixed
