### ISSUE TITLE
Quite gap between calendar popup and text box

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3657]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=SRMs 

**To Reproduce**
1. Go to thrive page
2. Click on the SRM > apply filter
3. tap on calendar box and observe

**Actual-**
Quite gap between calendar and box.

**Expected behavior**
No more gap between box and popup calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/73995362-5b054380-497e-11ea-8791-95e995e02de2.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Firefox
 - Version: 72.0.2

**Comment by kkartunov** [comment]
This filter panel is being redesigned and will implement a new date picker.
