### ISSUE TITLE
like and dislike option not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3658]
Target URL: https://www.topcoder.com/thrive/articles/Blockchain%20for%20Beginners:%20What%20You%20Need%20to%20Know

### Reproduction Steps ###

1 goto web 
2 click any article  
3 in article page click like and dislike 

### Expected Result ###

able to like or dislike the article 

### Actual Result ###
like and dislike option not working 

### Screenshots or screencast ###

[bandicam 2020-02-07 07-52-02-216.zip](https://github.com/topcoder-platform/community-app/files/4168680/bandicam.2020-02-07.07-52-02-216.zip)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
Dupe with #3654. We'll only consider the earliest ticket as valid.
