### ISSUE TITLE
[$10] - Tapping on the user profile image won't go to the profile page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#366]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Go to 'Past Challenges' and click on the profile image

Actual Result(s)
-----------------------------------------------------------------
- Tapping on the user profile image won't go to the profile page. Instead it will show 'undefined' message

Expected Result(s)
-----------------------------------------------------------------
- When tap on a profile image must open the profile page of the user

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![2](https://user-images.githubusercontent.com/4592712/29763153-8d97f04e-8bef-11e7-90d7-a6bd056bfe65.png)

**Comment by sdgun** [comment]
https://www.screencast.com/t/yeKHI9fPTv

**Comment by birdofpreyru** [comment]
Accepted, 3 points
