### ISSUE TITLE
author profile link not enabled 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3660]
Target URL: https://www.topcoder.com/thrive/articles/Blockchain%20for%20Beginners:%20What%20You%20Need%20to%20Know
Reproduction Steps

1 goto web
2 click any article
3 in article page click author icon 

Expected Result

able to view author profile from article 

Actual Result

author profile link not enabled 

Screenshots or screencast

![bandicam 2020-02-07 07-53-55-348](https://user-images.githubusercontent.com/3225433/73995600-26de5280-497f-11ea-8006-d341ac5de9f2.jpg)

OS/Browser Information

windows 10 and Firefox 72.0.2

**Comment by kkartunov** [comment]
It is not by planned design.
