### ISSUE TITLE
[Web-Firefox] Search Button Should Be Either Upward Or Downward To Image Not In Between

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3662]
URL: https://www.topcoder.com/thrive

**Describe the bug**
Search Button Should Be Either Upward Or Downward To Image Not In Between

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive'

2. See The ScreenShot

**Expected behavior**
Search Button Should Be Either Upward Or Downward To Image Not In Between

**Actual Result**
Search Button Is In Between Image

**Screenshots**
![Search](https://user-images.githubusercontent.com/42583358/73995690-60af5900-497f-11ea-9cc1-f78d9e671868.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/73995711-6e64de80-497f-11ea-93a3-af4aa8c5c190.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/73995737-84729f00-497f-11ea-87ad-a08ed32088fb.png)

**Comment by winterflame** [comment]
Not a bug
