### ISSUE TITLE
Pop up calender not auto adjust up and down as per the view screen

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3663]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=SRMs 

**To Reproduce**
1. Go to thrive page
2. Click on the SRM > apply filter
3. tap on calendar box and observe

**Actual-**
Filter popup calendar always open below the box

**Expected behavior**
Popup calendar should be auto adjust to open up or down as per view page

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/73995741-8a688000-497f-11ea-93bb-4d874635559c.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Firefox
 - Version: 72.0.2

**Comment by kkartunov** [comment]
This filter panel is being redesigned and will implement a new date picker.
