### ISSUE TITLE
[Functional] Nothing happens on click of search result

### ISSUE THREAD

**Issue by sanju-singh** [topcoder-platform/community-app#3664]
Target URL: https://www.topcoder.com/thrive

### Reproduction Steps ###

1. Go to https://www.topcoder.com/thrive
2. Search something.
3. Click on any article on links shown in the search result.
4. Observe, nothing happens

### Expected Result ###

Clicking on search result should take us to the corresponding link.

### Actual Result ###

Nothing happens on click of search result.

### Screenshots or screencast ###

[Screen Recording 2020-02-07 at 7.52.50 AM.zip](https://github.com/topcoder-platform/community-app/files/4168698/Screen.Recording.2020-02-07.at.7.52.50.AM.zip)

### OS/Browser Information ###

Macos / chrome 80.0.3987.87

**Comment by sanju-singh** [comment]
Observation: If it works first time, go back to the previous page, search and click on a result, and see if it works.

**Comment by winterflame** [comment]
Sorry, I cannot reproduce.

**Comment by sanju-singh** [comment]
Still able to reproduce on different system, try going back and forth few times ( clicking on result, if works, go back and try again multiple times), I was able to reproduce in second time.
Thanks
