### ISSUE TITLE
Reset filter does't work properly

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3666]
Target URL: https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=&author=All%20authors&startDate=2020-01-07T10%3A23%3A59%2B08%3A00&endDate=2020-02-07T10%3A23%3A59%2B08%3A00

### Reproduction Steps ###
1. Open the page
2. Click 'show filter' link
3. Input 'testing' in the tag field
4. Click 'Apply filter'
5. Click 'Reset'
### Expected Result ###
There's totally 10 articles in this category, when user apply testing filter, there should be 1 item, then user click 'reset', the tag's field in the search form should be clear, and the search result should be reset, display 10 articles. 
### Actual Result ###
When user click 'reset', the tag's field in the search form is clear, but the search result is still 1 article. User have to click the 'apply filter' again to show the whole articles.
### Screenshots or screencast ###
[Screen Recording 2020-02-07 at 10.29.58 AM.mov.zip](https://github.com/topcoder-platform/community-app/files/4168713/Screen.Recording.2020-02-07.at.10.29.58.AM.mov.zip)
### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
dupe with #3656
