### ISSUE TITLE
Like and Dislike icon not enabled(FUNCTIONAL)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3667]
Target URL: https://www.topcoder.com/thrive/articles/Solving%20Problems%20Using%20Constraint%20Logic%20Programming

Open the Application and Login as valid user
Go to https://www.topcoder.com/thrive/articles/Solving%20Problems%20Using%20Constraint%20Logic%20Programming
Go to the articles details below

Actual: The icons are not functional

Expected: The like and dislike icons should be funtional
![Desktop 2020-02-07 05-28-48](https://user-images.githubusercontent.com/37167721/73995951-52574200-496b-11ea-9684-a6bc7c1c1395.jpg)

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Duplicated.
