### ISSUE TITLE
The result filter doesn't matching with selected date.

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#3669]
**Describe the bug**
![Screenshot_2](https://user-images.githubusercontent.com/26895101/73996109-47ada480-498d-11ea-9f9c-b7f7f01795d6.png)

**To Reproduce**
1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming
3. Click on "Show filter" button and select date "Jan 7, 2020 - Feb 7, 2020"
4. Click on "Apply Filter" and observe result

**Actual:** The result filter doesn't matching with date "Jan 7, 2020 - Feb 7, 2020"

**Expected:** The result filter should matching with date "Jan 7, 2020 - Feb 7, 2020"

**Environment:** Lenovo legion, Windows 10
**Browser:**  Google Chrome 80.0.3987.87

**Comment by winterflame** [comment]
Dupe with #3659
