### ISSUE TITLE
[$10] - 'Purse' tag is too large 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#367]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Go to 'Ongoing Challenges' and check the 'Purse' tag 

Actual Result(s)
-----------------------------------------------------------------
-  'Purse' tag is too large and the width of the tag is too big

Expected Result(s)
-----------------------------------------------------------------
- Must reduce the width of the tag. The gray background must only display below the text area

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![1](https://user-images.githubusercontent.com/4592712/29763156-90473b74-8bef-11e7-88a9-ad63427ade53.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
