### ISSUE TITLE
Better to have a Search for Filter > Author field

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3670]
![image](https://user-images.githubusercontent.com/42398485/73996114-5447e380-4920-11ea-8545-f56fa76602a8.png)

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming

1. Open the Application and Login as valid user
2. Click 'COMPETITIVE PROGRAMMING' title
3. Click Filter > Author

**Actual:** Better to have a Search for Filter > Author field

**Expected:** Should display meaningful names

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge 44.18362.449.0 | Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by kkartunov** [comment]
This filter panel is being redesigned.
