### ISSUE TITLE
from filter option not working 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3671]
Target URL:https://www.topcoder.com/thrive/search?author=Shubham%20Prasad&startDate=2020-01-07T08%3A05%3A44%2B05%3A30&endDate=2020-02-07T08%3A05%3A44%2B05%3A30&track=&tax=

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 click Data Visualization
3 click author name 
4.click apply filter 

### Expected Result ###

result should based on filter options 

### Actual Result ###

from filter option not working 

### Screenshots or screencast ###

![bandicam 2020-02-07 08-07-03-496](https://user-images.githubusercontent.com/3225433/73996160-e4b61080-4980-11ea-8599-cd9cafd97882.jpg)
### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
Dupe with #3659
