### ISSUE TITLE
[Web-Firefox] Icons Are Not Aligned Properly

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3672]
URL: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=SRM%20Editorials

**Describe the bug**
Icons Some Part Is Cutting

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive'

2. Scroll down to 'Competitive Programming'

3. Click On SRM EDitorials

**Expected behavior**
Icons Parts Should Not Be Cutting.

**Actual Result**
Icons Some Part Is Cutting

**Screenshots**
![Icons 1](https://user-images.githubusercontent.com/42583358/73996144-d831b800-4980-11ea-98c7-552c8e525aba.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/73996169-e7186a80-4980-11ea-93bf-77a6dfe03af0.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/73996195-f3042c80-4980-11ea-98a5-c4a839eec675.png)

**Comment by winterflame** [comment]
It's a "Play" button overlapped the text "top", not a bug.
