### ISSUE TITLE
It's difficult to filter by an specific author

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3676]
Target URL: 
https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=&author=All%20authors&startDate=2020-01-07T10%3A30%3A15%2B08%3A00&endDate=2020-02-07T10%3A30%3A15%2B08%3A00

### Reproduction Steps ###
1. Open the page
2. Click 'show filter'
### Expected Result ###
There should be a easy way to filter the articles by a specific author.
### Actual Result ###
If I want to filter all articles of the author 'Daniela', I have to click the 'author' dropdown in the filter form, and scroll until I find and click the 'Daniela'. The dropdown options isn't arranged, such like in alphabetical order, and I can't input 'D' via keyboard to find the 'Daniela', it's difficult to do the filter.
### Screenshots or screencast ###
[Screen Recording 2020-02-07 at 10.40.56 AM.mov.zip](https://github.com/topcoder-platform/community-app/files/4168741/Screen.Recording.2020-02-07.at.10.40.56.AM.mov.zip)
### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
Dupe with #3670.
