### ISSUE TITLE
'Thrive' menu underline UI issue

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3677]
![image](https://user-images.githubusercontent.com/42398485/73996449-39c23a00-4921-11ea-8457-6141ab38b1a1.png)

**Target URL:** https://www.topcoder.com/thrive

1. Open the Application and Login as valid user
2. Check the menu

**Actual:** 'Thrive' menu underline UI issue

**Expected:** Should display below the text

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge 44.18362.449.0

**Comment by winterflame** [comment]
Edge is not in scope. Similar to #3665.
