### ISSUE TITLE
[$10] - [Bug Hunt] - when there is a locked sign Download link shouldnt be provided

### ISSUE THREAD

**Issue by kaygee1** [topcoder-platform/community-app#368]
Login to the site

Open
https://community-app.topcoder.com/challenges/30058637
Click on Winners

Click on Download

actual - it opens up the OR page and then says it cannot be downloaded

expected - since it says lock on the submission image there should not be a download link

**Comment by kaygee1** [comment]
![1](https://user-images.githubusercontent.com/5115050/29757622-d61a994a-8bca-11e7-9669-aba1c7baca6f.png)

**Comment by kaygee1** [comment]
Not able to add the label to this issue.

**Comment by birdofpreyru** [comment]
Accepted, 3 points
