### ISSUE TITLE
Details not hidden on clicking the up arrow near the titles in the right side bar.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3681]
**Describe the bug**
Details not hidden on clicking the up arrow near the titles in the right side menu bar.

**To Reproduce**

1. Go to 'https://www.topcoder.com/thrive/tracks?track=Development&tax='
2. Click on down arrow button near Development menu in the right side menu bar.
3. Click the up arrow button near Development menu in the right side menu bar.

**Expected behavior**
The details displayed should be hided while clicking the up arrow button near the Development menu.

Actual behaviour:
The details displayed were not hided while clicking the up arrow button near the Development menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/55895538/73996550-e2a08180-4981-11ea-89fd-5f4e33c132ed.png)

**Desktop (please complete the following information):**
 - Windows 10 home single language, 64 bit 
 - Chrome
 - Version 79.0.3945.130

**Comment by winterflame** [comment]
It's by design - you can click the "Down" arrow for other tracks (e.g. DATA SCIENCE), then the DEVELOPMENT part will be collapsed and the contents for DATA SCIENCE will be displayed in the main area.
