### ISSUE TITLE
filter tags recommendation missing 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3682]
Target URL: https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2020-01-07T08%3A05%3A44%2B05%3A30&endDate=2020-02-07T08%3A05%3A44%2B05%3A30&track=Data%20Science

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 click Data Visualization
3 enter keyword as test

### Expected Result ###
keyword should recommendation keywords as per entered text 

### Actual Result ###
filter tags recommendation missing 
[bandicam 2020-02-07 08-15-47-709.zip](https://github.com/topcoder-platform/community-app/files/4168750/bandicam.2020-02-07.08-15-47-709.zip)

### Screenshots or screencast ###

[bandicam 2020-02-07 08-15-47-709.zip](https://github.com/topcoder-platform/community-app/files/4168750/bandicam.2020-02-07.08-15-47-709.zip)
### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
won't fix
