### ISSUE TITLE
Go Back Link is Contact is not working 

### ISSUE THREAD

**Issue by Palanimurugana** [topcoder-platform/community-app#3683]
**Describe the bug**
Go Back Link in Contact Us - Message Send Page is not working. it should navigate back to Contact Us Screen. 

**To Reproduce**
1. Go to 'the Page "https://www.topcoder.com/thrive"
2. Click on 'Support' button located at Bottom Right
3. Fill values for input fields and click Send button on the Contact US Page 
4. The Message Send Screen will be opened and Click Go Back link

**Expected behavior**
After clicking Go Back link it should navigate to Contact Us screen again

**Actual behavior**
it has minimized the support screen (Message Send Screen) 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: [ Windows 10]
 - Browser [Chrome 79]
 

**Additional context**

**Comment by winterflame** [comment]
out of scope.
