### ISSUE TITLE
TEXTS and Graphics Ovelaying(UI)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3685]
Target URL: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=SRM%20Editorials

Open the Application and Login as valid user
Go to https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=SRM%20Editorials

Observe the "Competitive Programming " Title

Actual: The last letter in the title overlays on the graphic image

Expected: Theletter should not overlay the graphic image
Browser: Google Chrome Version 79.0.3945.130
![UI](https://user-images.githubusercontent.com/37167721/73996720-6d2ab600-496d-11ea-92ba-996dabc2750d.jpg)

**Comment by winterflame** [comment]
not a bug
