### ISSUE TITLE
Author name is not properly aligned on any article page 

### ISSUE THREAD

**Issue by varun22303270** [topcoder-platform/community-app#3691]
**Describe the bug**
Author name is not properly aligned on any article page 

**Target URL**
https://www.topcoder.com/thrive/articles/Managing%20Tasks

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Managing%20Tasks
2. Observe the Author name

**Actual**
Author name is not properly aligned on any article page 

**Expected behavior**
Author name should be properly aligned on the article page as the below fields

**Screenshots**
<img width="960" alt="error_screen" src="https://user-images.githubusercontent.com/7602356/73996995-4a0b0100-4983-11ea-97a8-23401e1a19b1.png">
<img width="960" alt="chrome_version_latest" src="https://user-images.githubusercontent.com/7602356/73996997-4bd4c480-4983-11ea-9e4d-6267eb3e017b.png">

**Desktop (please complete the following information):**
Environment: Windows 10 x64 Browser: Chrome Version 80.0.3987.87

**Comment by varun22303270** [comment]
Label: UI

**Comment by varun22303270** [comment]
**Expected Results**:
Author name should be properly aligned on the article page as the below fields

or there should be a profile icon if the author's pic is not available

**Comment by winterflame** [comment]
It missed an avatar/logo. Dupe with #3675.
