### ISSUE TITLE
The tag's content is overflow

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3692]
Target URL: https://www.topcoder.com/thrive
### Reproduction Steps ###
1. Open the page
2. Set the browser's window's width to about 1000px
3. Scroll down the page to the 'Featured articles' section
### Expected Result ###
The content in the tag should be wrapped correctly of the tag component
### Actual Result ###
The content in the tag is overflowed
### Screenshots or screencast ###
![Xnip2020-02-07_10-54-21](https://user-images.githubusercontent.com/5466773/73996981-35853380-4998-11ea-8411-d8881873ce99.jpg)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by kkartunov** [comment]
Fixed
