### ISSUE TITLE
The texts not well aligned and no User profile image found

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3693]
Target URL: https://www.topcoder.com/thrive/articles/Solving%20Problems%20Using%20Constraint%20Logic%20Programming

Open the Application and Login as valid user
Go to https://www.topcoder.com/thrive/articles/Solving%20Problems%20Using%20Constraint%20Logic%20Programming
Observe under Articles details

Actual:The texts are not well aligned 

Expected: The texts should be well aligned on one side
![al](https://user-images.githubusercontent.com/37167721/73997015-5e90ce80-496e-11ea-9334-87697438f53b.jpg)

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Dupe with #3675.
