### ISSUE TITLE
The Number should be align center with label

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#3694]
**Describe the bug**

![Screenshot_4](https://user-images.githubusercontent.com/26895101/73997048-feab1f80-498f-11ea-9a77-a40d8c1c3b97.png)

**To Reproduce**
1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/tracks?track=QA
3. Observe the title

**Actual:** The Number doesn't align center with label

**Expected:** The Number should be align center with label
**Environment:** Lenovo legion, Windows 10
**Browser:**  Google Chrome 80.0.3987.87

**Comment by winterflame** [comment]
It's by design - left aligned.
