### ISSUE TITLE
Reset/clear button not available near the filter search .

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3695]
**Describe the bug**
Reset/clear button not available near the filter search (UX issue).

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/search?author=Christopher%20DeLaurentis
2. Enter Tag name in the Tags field in the right corner of the page.

**Expected behavior**
A Reset /clear button should be available for user to clear the entered contents and easier user experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/55895538/73997041-66a73900-4983-11ea-869b-911b41874f64.png)

**Desktop (please complete the following information):**
 - Windows 10 home single language,64 bit
 - Chrome.
 - Version 79.0.3945.130

**Comment by winterflame** [comment]
Dupe with #3673.
