### ISSUE TITLE
The featured article's cards isn't displayed properly

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3697]
Target URL: https://www.topcoder.com/thrive
### Reproduction Steps ###
1. Open the page
2. Set the browser window's width to about 680px
3. Scroll down to the 'Featured articles' section
### Expected Result ###
The featured article's cards should be displayed properly
### Actual Result ###
The featured article's cards isn't displayed properly, there's a tiny overflow of the image under the 'wave' cover.
### Screenshots or screencast ###
![Xnip2020-02-07_10-59-41](https://user-images.githubusercontent.com/5466773/73997300-058a6000-4999-11ea-9cb8-512891d6d20a.jpg)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
not a bug, please test in normal browser resolutions.
