### ISSUE TITLE
Layout boundary not aligned

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#3698]
**Target URL:** https://www.topcoder.com/thrive

**To Reproduce**
1. Go to https://www.topcoder.com/thrive
2. Scroll down and observe

**Expected behavior**
Layout boundary should be aligned with other box

**Screenshots**
![1](https://user-images.githubusercontent.com/51490878/73997291-0b297b00-4984-11ea-93f1-4a9902dff26c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
#3648
