### ISSUE TITLE
[$10] - Drop down arrow not shown at the right place

### ISSUE THREAD

**Issue by kaygee1** [topcoder-platform/community-app#370]
Open the page
http://community-app.topcoder.com/challenges/30058529
SEe the View all deadlines drop down
Actual - The arrow is shown before the Text

Expected - it should be after the view all deadline text

device = laptop
Safari 5.1.7
Windows 10
![2](https://user-images.githubusercontent.com/5115050/29759412-0eda6540-8bd9-11e7-8ee1-cf3298fc9356.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point
