### ISSUE TITLE
Select All checkbox not included(UI)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3701]
**Target URL:** https://www.topcoder.com/thrive/search?tags[0]=Productivity&author=All%20authors&startDate=2020-01-07T05%3A58%3A28%2B03%3A00&endDate=2020-02-07T05%3A58%3A28%2B03%3A00&track=Design&tax[0]=User%20Experience&tax[1]=Data%20Visualization&tax[2]=UI%20Design&tax[3]=Customer%20Success%20Stories&tax[4]=Other

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/search?tags[0]=Productivity&author=All%20authors&startDate=2020-01-07T05%3A58%3A28%2B03%3A00&endDate=2020-02-07T05%3A58%3A28%2B03%3A00&track=Design&tax[0]=User%20Experience&tax[1]=Data%20Visualization&tax[2]=UI%20Design&tax[3]=Customer%20Success%20Stories&tax[4]=Other

Observe under sub-categories in the Search results

**Actual:** The user can only select each checkbox after the other  and no "ALL" to check all

**Expected:** There should be a select "All" to check all the boxes in the sub-category
![no](https://user-images.githubusercontent.com/37167721/73997557-e1feef80-496f-11ea-8576-71da8110f410.jpg)

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
not necessary.
