### ISSUE TITLE
tool tip is not meaningful for icon associated with search category selection

### ISSUE THREAD

**Issue by Palanimurugana** [topcoder-platform/community-app#3703]
**Describe the bug**
tool tip is not meaningful for the icon associated with search category selection

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive'
2. In the Search Box, On the right Side do mouser hover over the icon associated with category selection (Icon Left to All Text)

**Expected behavior**
it should display meaningful information in the tool tip

**Actual Behaviors**
its displaying un-meaningful information 

**Screenshots**
Please find attached

**Desktop (please complete the following information):**
 Windows 10 OS
Chrome 79 Browser

Bug Label:UX

**Comment by winterflame** [comment]
no screenshot.
