### ISSUE TITLE
[Functional] can't upvote an article

### ISSUE THREAD

**Issue by sanju-singh** [topcoder-platform/community-app#3704]
Target URL: https://www.topcoder.com/thrive/articles/Blockchain%20for%20Beginners:%20What%20You%20Need%20to%20Know
### Reproduction Steps ###

1. Go to any article with upvote and downvote at bottom, ex: https://www.topcoder.com/thrive/articles/Blockchain%20for%20Beginners:%20What%20You%20Need%20to%20Know
2. Try clicking on upvote and downvote
3. Observe, nothing happens.

### Expected Result ###

Upvote and downvote button should work.

### Actual Result ###

Upvote and downvote buttons are not working

### Screenshots or screencast ###

[Screen Recording 2020-02-07 at 8.36.33 AM.zip](https://github.com/topcoder-platform/community-app/files/4168799/Screen.Recording.2020-02-07.at.8.36.33.AM.zip)

### OS/Browser Information ###

Macos / chrome 80.0.3987.87

**Comment by winterflame** [comment]
dupe with #3654
