### ISSUE TITLE
Up and down arrow is displayed near the Tags filter instead of down arrow button.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3706]
**Describe the bug**
Up and down arrow is displayed near the Tags filter instead of down arrow button.Since up and down arrow is used for increment or decrement of numbers and it is not used for this purpose here.(UX issue).

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive/tracks?track=Development&tax='
2. Check the Tags near the upper search field.

**Expected behavior**
Up and down arrow near the Tags should be replaced by down arrow.

**Screenshots**

![image](https://user-images.githubusercontent.com/55895538/73997643-1f21ac80-4985-11ea-903e-f2e22e09c6c1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 home single language, 64 bit OS 
 - Chrome
 - Version 79.0.3945.130

**Comment by kkartunov** [comment]
The filter bar is per design.
