### ISSUE TITLE
Article form search result does not open in first click 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#3708]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Tips

**Steps**
1. Go to https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Tips
2. Click on Search edit box and "debug"
3. wait for search result and click on item from search result
Observe

**Expected behavior**
Article form search result does not open in first click 

**Screenshots**
[2.zip](https://github.com/topcoder-platform/community-app/files/4168810/2.zip)
![2](https://user-images.githubusercontent.com/51490878/73997985-1da4b400-4986-11ea-8353-9bb391525bbf.png)

**OS/Browser Information:**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by coderkid19** [comment]
"Expected behavior" wrongly updated in first place

Correct one should be below.
"Article form search result should get loaded in first click"

**Comment by winterflame** [comment]
Cannot reproduce - it can load on the first click on the search result.
