### ISSUE TITLE
The author's default avatar displayed uncorrectly

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3709]
Target URL: 
https://www.topcoder.com/thrive/articles/Evaluate%20Your%20Submission%20Design%20Before%20Uploading%20it%20to%20UI%20Design%20Challenges

### Reproduction Steps ###
1. Open the page
2. Scroll down the page to the author's avatar position
### Expected Result ###
The author's default avatar should be displayed correctly.
### Actual Result ###
The author's default avatar isn't displayed correctly. When I refresh, the avatar displayed about 1 second and then disappear, I check it in the element inspector and find that the svg isn't not displayed correctly.
### Screenshots or screencast ###
[Screen Recording 2020-02-07 at 11.13.55 AM.mov.zip](https://github.com/topcoder-platform/community-app/files/4168811/Screen.Recording.2020-02-07.at.11.13.55.AM.mov.zip)
### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
dupe with #3675
