### ISSUE TITLE
[$10] - Like View All Deadlines, it should be Hide All Deadlines

### ISSUE THREAD

**Issue by kaygee1** [topcoder-platform/community-app#371]
Open the page
http://community-app.topcoder.com/challenges/30058925/?type=design

CLick on View all Deadlines
See the text now

Actual - it says - Hide Deadlines

expected - it should be Hide All Deadlines

Chrome 60
Win 10
Laptop
![3](https://user-images.githubusercontent.com/5115050/29760224-524449c6-8bdf-11e7-903c-d0c03376aa1c.png)

**Comment by birdofpreyru** [comment]
Not sure: on one hand, current text matches design specs; on the other hand having / not having `All` both when expanded and collapsed makes sense to me. @vic-topcoder what do you say?

**Comment by vic-topcoder** [comment]
`All` is not needed, please remove it. The text should read "Show deadlines" / "Hide deadlines". Good catch!

**Comment by birdofpreyru** [comment]
Accepted, 1 point

**Comment by twicoder** [comment]
PR #402
