### ISSUE TITLE
Filter tags does not remove via backspace

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3710]
**Target URL:**  https://www.topcoder.com/thrive/tracks

**To Reproduce**
1. Go to thrive page > track
2.  Tap on show filter and add tags 
3. Add some tags and try to remove via backspace

**Actual-**
tags does not remove via backspace

**Expected behavior**
Tags should be remove via backspace.

**Screenshots**
https://drive.google.com/open?id=1CQcGj0oajWkoYj5FzMk9Z7cz_vA-sT95

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Firefox
 - Version: 72.0.2

**Comment by kkartunov** [comment]
Not expected UX.
