### ISSUE TITLE
When click the 'thumb up' button in the article nothing happen, same as 'thumb down' button

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3713]
Target URL:
https://www.topcoder.com/thrive/articles/Evaluate%20Your%20Submission%20Design%20Before%20Uploading%20it%20to%20UI%20Design%20Challenges

### Reproduction Steps ###
1. Open the page
2. Scroll down to the bottom
3. Click the 'thumb up' button
### Expected Result ###
The thumb up count should +1
### Actual Result ###
Nothing happen
### Screenshots or screencast ###
[Screen Recording 2020-02-07 at 11.17.56 AM.mov.zip](https://github.com/topcoder-platform/community-app/files/4168821/Screen.Recording.2020-02-07.at.11.17.56.AM.mov.zip)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
dupe with #3658
