### ISSUE TITLE
No pop-up message of the date of the article author

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3714]
**Target URL:** https://www.topcoder.com/thrive/search?tags[0]=Ai&author=All%20authors&startDate=2019-06-03T12%3A00%3A00Z&endDate=2020-02-07T06%3A12%3A20%2B03%3A00&track=&tax=

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/search?tags[0]=Ai&author=All%20authors&startDate=2019-06-03T12%3A00%3A00Z&endDate=2020-02-07T06%3A12%3A20%2B03%3A00&track=&tax=

Observe the  Articles details card

**Actual:** No pop-up message of the date when the user moves the mouse on the date of the author

**Expected:**There should be a pop-up message when the user moves the mouse on the date
![pop](https://user-images.githubusercontent.com/37167721/73998146-c268c680-4971-11ea-9581-c07c92346919.jpg)

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
not a bug
