### ISSUE TITLE
"Sub-category" doesn't expand when click on "category" radio button

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#3716]
**Describe the bug**
![Screenshot_6](https://user-images.githubusercontent.com/26895101/73998092-1afc8b80-4993-11ea-9356-4a60cb735472.png)

**To Reproduce**
1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?
3. Click on any radio button on the CATEGORY item -> "Sub-category" auto expand
4. Click on "arrow" icon to collapse "Sub-category"
5. Continue click on any radio button on the CATEGORY item and Observe result

**Actual:** "Sub-category" doesn't expand after clicking arrow icon to collapse "Sub-category" in step 4

**Expected:** "Sub-category" should be expand when click on any "category" radio button
**Environment:** Lenovo legion, Windows 10
**Browser:**  Google Chrome 80.0.3987.87

**Comment by kkartunov** [comment]
Not expected by design.
