### ISSUE TITLE
The out-site linked page is open in the current browser tab, which breaks user's flow.

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3718]
Target URL:
https://www.topcoder.com/thrive/articles/Evaluate%20Your%20Submission%20Design%20Before%20Uploading%20it%20to%20UI%20Design%20Challenges

### Reproduction Steps ###
1. Open the page
2. Scroll down the page to the first image in the article
3. Click the 'Source' link below the image
### Expected Result ###
The browser should open a new tab to display the linked page, because it's a out-site link.
### Actual Result ###
The linked page is open in the current browser tab, which breaks user's flow.
### Screenshots or screencast ###
[Screen Recording 2020-02-07 at 11.22.15 AM.mov.zip](https://github.com/topcoder-platform/community-app/files/4168829/Screen.Recording.2020-02-07.at.11.22.15.AM.mov.zip)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
not a bug
