### ISSUE TITLE
"View all result" does not do any action or does not navigate to any page

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#3721]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Tips

**Steps **

1. Go to https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Tips
2. Click on search edit box and type "debug" and wait for search result
3. Search result window click on "view all results"
Observe that nothing happens upon click on "view all results"

**Expected behavior**
Click on "View all result" should do some action or navigate to new page

**Screenshots**
![4](https://user-images.githubusercontent.com/51490878/73998428-a07a3e80-4987-11ea-99e0-ec615b26ff12.png)

**Environment**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Cannot reproduce. If you're searching "debug', the link for "View all results" would be: https://www.topcoder.com/thrive/search?phrase=debug
