### ISSUE TITLE
There should be a space between the paragraph and a heading

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3724]
Target URL: 
https://www.topcoder.com/thrive/articles/Evaluate%20Your%20Submission%20Design%20Before%20Uploading%20it%20to%20UI%20Design%20Challenges

### Reproduction Steps ###
1. Open the page

### Expected Result ###
It's about typography layout, there should be a space between the paragraph and a heading.

### Actual Result ###
There isn't a proper space between the paragraph and a heading, it's even narrower than the normal paragraphs'.

### Screenshots or screencast ###
![Xnip2020-02-07_11-27-18](https://user-images.githubusercontent.com/5466773/73998587-1210b780-499d-11ea-8d7d-946f00e0d60f.jpg)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
Content issue out of scope.
