### ISSUE TITLE
[Web-Firefox] ^ Button Is Not Sorting The File

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3726]
https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=

**Describe the bug**
While Clicking On ^ Button Its Not Sorting The Details

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax='

2. Click on 'Data Science'

4. See Screencast & observe

**Expected behavior**
^ Button Should Be Shorting The Detail

**Actual Behaviour**
^ Button Is Not Not Sortong Details

**Screencast**
[Sorting 1.mp4.zip](https://github.com/topcoder-platform/community-app/files/4168838/Sorting.1.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/73998529-ec2ce800-4987-11ea-836a-1c4aeb977c61.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/73998663-5ba2d780-4988-11ea-81a3-706093c65573.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
not a bug, it is as designed.

**Comment by devsreekrishna** [comment]
But Sir
V Is Taking As Expanding The Details

**Comment by winterflame** [comment]
See #3681.
