### ISSUE TITLE
Topcoder Cookbook link opens to user profile while loading

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3728]
**Target URL:** https://www.topcoder.com/thrive

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive

Observe under Competitive programming tag links

Actual: The Topcoder Cookbook link first directs to the user profile details before actual url while loading
![Screenshot from 2020-02-07 06-28-26](https://user-images.githubusercontent.com/37167721/73998816-d1e90f00-4973-11ea-9d15-267693ec5d51.jpg)

Expected: The Topcoder Cookbook link should directly open the the cookbook details after it is clecked while loading to page

Browser: Google Chrome Version 79.0.3945.130

**Comment by kkartunov** [comment]
Unable to reproduce.
