### ISSUE TITLE
Three Iconic Design... card redirected to the 404 page

### ISSUE THREAD

**Issue by fahfai** [topcoder-platform/community-app#3729]
**Testing URL** https://www.topcoder.com/thrive

**To Reproduce**
1. Go to https://www.topcoder.com/thrive
2. Scroll down to Design cards
3. Click on Three Iconic Design... card
4. Observe the result

**Expected behavior**

**Actual Result**
Clicking on the Three Iconic Design card redirects the user to the 404 page

**Screenshots**
![Bug2](https://user-images.githubusercontent.com/39216496/73998643-3b314800-499d-11ea-8b57-437b40808a85.png)

[Uploading Bug2.zip…]()

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.2
 - Browser Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Bug Label** 
Functional

**Comment by kkartunov** [comment]
Archived.
