### ISSUE TITLE
[$10] - Be consistent in displaying the prize money

### ISSUE THREAD

**Issue by kaygee1** [topcoder-platform/community-app#373]
Open the listings page
http://community-app.topcoder.com/challenges

Hover over the prize money section

SEe the display

actual - in the table it is listed as $ 1500 ( $ and the amount has a space)
In the box that appears see the display

actual - there is no space between $ and the amount

expected consistency is expected

chrome 60
Win 10 Laptop
![5](https://user-images.githubusercontent.com/5115050/29760599-1508d600-8be2-11e7-8e38-6c268f986113.png)

**Comment by birdofpreyru** [comment]
Hmm... @vic-topcoder should we consider it as a bug?

**Comment by vic-topcoder** [comment]
It can be considered. I think this is my bad - we didn't formalize display of currency in the system. When there is a Currency, we should always say `$ammount` to be correct. The list design is not following the standard and introduces a space - this should be fixed.

**Comment by birdofpreyru** [comment]
Accepted, 3 points
