### ISSUE TITLE
Should use Label Tags as Click Targets for Checkbox

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3731]
Target URL: 
https://www.topcoder.com/thrive/search?author=Mohammad%20Iqbal

### Reproduction Steps ###
1. Open the page
2. Click the category checkbox in the left sidebar

### Expected Result ###
Should use Label Tags as Click Targets for Checkbox, which is the best practice. 
Reference: [UX Design: Checkbox and Toggle in Forms](https://uxplanet.org/checkbox-and-toggle-in-forms-f0de6086ac41), 'Use Label Tags as Click Targets for Checkbox' section

### Actual Result ###
User have to click the checkbox which is not friendly UX

### Screenshots or screencast ###
![Xnip2020-02-07_11-37-20](https://user-images.githubusercontent.com/5466773/73998978-42a52100-499e-11ea-992d-ab93f606f379.jpg)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
dupe with #3699
