### ISSUE TITLE
Design article is not re-directed to the correct url: Three iconic designs that Came from crowdsourcing competitions

### ISSUE THREAD

**Issue by varun22303270** [topcoder-platform/community-app#3732]
**Describe the bug**
Design article is not re-directed to the correct url: Three iconic designs that Came from crowdsourcing competitions

**Target URL**
https://www.topcoder.com/thrive/

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/
2. Click on Three iconic designs that Came from crowdsourcing competitions article under Desgins section and Observe

**Actual**
Design article is not re-directed to the correct url: Three iconic designs that Came from crowdsourcing competitions

**Expected behavior**
Should re-direct to the correct article URL

**Screenshots**
<img width="960" alt="error_screen_1" src="https://user-images.githubusercontent.com/7602356/73999022-79247100-4989-11ea-8394-c1790f4d01c1.png">
<img width="960" alt="chrome_version_latest" src="https://user-images.githubusercontent.com/7602356/73999027-7b86cb00-4989-11ea-8b31-8c124d97b71c.png">
![Uploading error_screen.png…]()

**Desktop (please complete the following information):**
 Environment: Windows 10 x64 Browser: Chrome Version 80.0.3987.87

**Comment by varun22303270** [comment]
Label: Functional

**Comment by winterflame** [comment]
#3729
