### ISSUE TITLE
'View All Results' hyperlink is not working

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3733]
![image](https://user-images.githubusercontent.com/42398485/73999039-1c916980-4929-11ea-8c03-882e83c1f9bd.png)

**Target URL:** https://www.topcoder.com/thrive/

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/
3.  Type 'ca' and change the dropdown to 'Tags'
4. Click on search field > Click 'View All Results'

**Actual:** 'View All Results' hyperlink is not working

**Expected:** Should remove if it is not required according to the search term

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
Cannot reproduce. Dupe with #3721
