### ISSUE TITLE
Problem of the Week link opens to user profile while loading

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3735]
**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Problem%20of%20the%20WeekOpen the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive

Observe under Competitive programming tag links
![prof2](https://user-images.githubusercontent.com/37167721/73999222-1923cf80-4975-11ea-9190-5acc959fb4ab.jpg)

**Actual:** The Problem of the Week link first directs to the user profile details before actual url while loading

**Expected:** The Problem of the Week link should directly open the problem of the week details after it is clecked while loading to page

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Dupe with #3728.
