### ISSUE TITLE
The print result of the article is not friendly

### ISSUE THREAD

**Issue by staticfire** [topcoder-platform/community-app#3737]
Target URL:
https://www.topcoder.com/thrive/articles/Be%20a%20Problem%20Solver!

### Reproduction Steps ###
1. Open the page
2. Click the 'print' button in the left side

### Expected Result ###
The print result of the article should be friendly

### Actual Result ###
The print result of the article should be friendly, there are many unuseless part showing in the preview. 
Such like, the header(the user avatar, 'explore', huge blank section), social media link buttons, 'thumb up' info, and footer.

### Screenshots or screencast ###
![Xnip2020-02-07_11-45-16](https://user-images.githubusercontent.com/5466773/73999353-76cd1180-499f-11ea-9675-aaa5b345989e.jpg)
![Xnip2020-02-07_11-45-31](https://user-images.githubusercontent.com/5466773/73999356-79c80200-499f-11ea-801d-9e84e7a9427f.jpg)

### OS/Browser Information ###
- OS: macOS 10.15.2
- Browser: Chrome 79

**Comment by winterflame** [comment]
out of scope.
