### ISSUE TITLE
Search list should not have redundant space

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#3739]
**Describe the bug**
![Screenshot_7](https://user-images.githubusercontent.com/26895101/73999516-8c3e3d80-4997-11ea-8a66-157e81acae52.png)

**To Reproduce**
1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?
3. Click on dropdown in the right of search bar -> select "Author" option
4. Enter "Mariia Mykhailova" in the search box and observe result

**Actual:** Search list have redundant space in the bottom

**Expected:** Search list should not have redundant space
**Environment:** Lenovo legion, Windows 10
**Browser:**  Google Chrome 80.0.3987.87

**Comment by winterflame** [comment]
#3730
