### ISSUE TITLE
Choosing subtrack filter causes infinite loop of API requests

### ISSUE THREAD

**Issue by Colinh84** [topcoder-platform/community-app#374]
Steps to Reproduce
-----------------------------------------------------------------

- Go to http://community-app.topcoder.com/challenges?

- Press Ctrl + Shift + i to open the developer console in Chrome

- Click the "Network" tab on the console to see network requests.

- Click on "Filters" button on the topcoder challenge listing page.

- Select "Development" from the subtrack dropdown box.

- Watch in the Chrome console as an infinite loop of Challenge API requests occur on the page.

- Page often becomes unresponsive due to volume of requests, but if not can only be stopped by clearing the filter.

Actual Result(s)
-----------------------------------------------------------------
-  Seemingly infinite loop of server API requests for challenges when a subtrack is filtered.

Expected Result(s)
-----------------------------------------------------------------
- Filter the challenge results with one API request.

Environment
-----------------------------------------------------------------
- **Device(s):** Desktop
- **Operating System:** Windows 10
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by Colinh84** [comment]
Video:
[https://www.screencast.com/t/D9VJXYaha](https://www.screencast.com/t/D9VJXYaha)

**Comment by birdofpreyru** [comment]
Not a bug. Just a workaround for backend restrictions.

**Comment by Colinh84** [comment]
@birdofpreyru Did you watch the video? none of the results can even load and there are hundreds of API requests.. How can this not be a bug??

**Comment by birdofpreyru** [comment]
Actually, I'll accept your ticket. Still, it is not a bug in principle, it just means that it keeps on searching past challenges, and can't find any matching the filter.

However, I've paid attention now, that you have selected `Development` sub-track, and it sill does not match any challenge (cause the subtrack in challenge objects for such challenges is `CODE`). Don't open this ticket for pick up yet, as I have no clear understanding, whether it is our app, or a backend issue.
