### ISSUE TITLE
[Web-Firefox] Quickpath Analytics Is Not Opening Detail

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3740]
URL: https://www.topcoder.com/thrive/search?tags[0]=Quickpath%20Analytics

**Describe the bug**
While Clicking On Quickpath Analytics Its Not Opening Details

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive/search?tags[0]=Quickpath%20Analytics'

2. Click on 'Quickpath Analytics'

3. See Screencast & Observe

**Expected behavior**
While Clicking On Quickpath Analytics Its Not Opening Details

**Actual Behaviour**
While Clicking On Quickpath Analytics It Should Open The Details

**Screenshots**
[Quickpath.mp4.zip](https://github.com/topcoder-platform/community-app/files/4168890/Quickpath.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/73999541-13d17f80-498b-11ea-989a-1eae3b8bcda7.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/73999556-2055d800-498b-11ea-8e30-a07ee97487f5.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
"Quickpath Analytics" is a tag, clicking on it will trigger the search action - search by itself.
