### ISSUE TITLE
Nothing is opening through search results

### ISSUE THREAD

**Issue by varun22303270** [topcoder-platform/community-app#3743]
**Describe the bug**
Nothing is opening through search results

**Target URL**
https://www.topcoder.com/thrive/

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/
2. Search for "Single" and click on any searched article > Observe

**Actual**
Nothing is opening through search results

**Expected behavior**
Articles should open from Search results

**Screenshots**
<img width="960" alt="error_screen" src="https://user-images.githubusercontent.com/7602356/73999693-8e020400-498b-11ea-949d-396df15ef232.png">
<img width="960" alt="chrome_version_latest" src="https://user-images.githubusercontent.com/7602356/73999706-935f4e80-498b-11ea-9cec-67eee8021a4d.png">

**Desktop (please complete the following information):**
 Environment: Windows 10 x64 Browser: Chrome Version 80.0.3987.87

**Comment by winterflame** [comment]
Dupe with #3708.
