### ISSUE TITLE
SRM Tutorial > Much space present between the text and the wavy line

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3745]
Target URL: https://www.topcoder.com/single-round-match-753-editorials/

Reproduction Steps
1. Open https://www.topcoder.com/thrive
2. Click on First SRM tutorial
3. Observe the space between the text and wavy line.

Expected Result

Space should not present much between the text and wavy line.

Actual Result

Space present much between the text and wavy line.

Screenshots or screencast
[Issue1.zip](https://github.com/topcoder-platform/community-app/files/4168929/Issue1.zip)

OS/Browser Information
Windows / Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
not a bug
