### ISSUE TITLE
Able to select date range where start date greater than end date

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#3746]
**Target URL:**   https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2020-01-31T12%3A00%3A00Z&endDate=2020-01-01T12%3A00%3A00Z&track=&tax=

**Steps**
1. Go to  https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2020-01-31T12%3A00%3A00Z&endDate=2020-01-01T12%3A00%3A00Z&track=&tax=
2. From date range select start date and end date, where start date is greater than end date.
Observe

**Expected behavior**
User should not be able to select start date greater than end date.

**Screenshots**
![6](https://user-images.githubusercontent.com/51490878/74000368-cf93ae80-498d-11ea-96eb-057e93f0aa28.png)

**Environment:**
 - OS:Windows
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
dupe with #3725
