### ISSUE TITLE
Can not close the expand icon

### ISSUE THREAD

**Issue by fahfai** [topcoder-platform/community-app#3748]
**Testing URL** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming

**To Reproduce**
1. Go to https://www.topcoder.com/thrive
2. Click on Competitive Programming
3. Click on expand/collapse icon next to Competitive Programming at the sidebar 
4. Observe the result

**Expected behavior**
When the user clicks on the expand icon next to Competitive Programming to close the dropdown menu, it should collapse/close the dropdown menu

**Actual Result**
Can not close the dropdown menu at sidebar when clicking on the expand/collapse icon

**Screenshots**
![Bug3](https://user-images.githubusercontent.com/39216496/74000409-f6101480-49a2-11ea-9b6d-e49e426008df.png)

**Screencast**
[Bug3.zip](https://github.com/topcoder-platform/community-app/files/4168943/Bug3.zip)

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.2
 - Browser Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by fahfai** [comment]
Bug Label : Functional

**Comment by winterflame** [comment]
not a bug
