### ISSUE TITLE
[Web-Firefox] While Clicking On Back Page Its Going To Home page

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3749]
URL: https://www.topcoder.com/thrive

**Describe the bug**
While Clicking On Back Arrow Key Its Going To Home page

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive'

2. Scroll down to Topcoder

3. Select Copilot > Click On Data Science

4. Click On Show More 8 To 9 Times Till End

5. Click On Back arrow Key Then See & observe

**Expected behavior**
While Clicking On Back Page It Should Go To One page Back

**Actual Behaviour**
While Clicking On Back Page Its Going To Home page

**Screencast**
[Topcoder.mp4.zip](https://github.com/topcoder-platform/community-app/files/4168947/Topcoder.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74000563-9445af80-498e-11ea-9005-cd55ca15dea4.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74000578-a0317180-498e-11ea-8a0a-76e0f0721587.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
This is a browser feature, not a bug.
