### ISSUE TITLE
[$10] - Layout issue in the date time picker when user opens it; part of the date time picker is hidden

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#375]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Click Filter

- Click on Date Range

Actual Result(s)
-----------------------------------------------------------------
- Layout issue in the date time picker when user opens it; part of the date time picker is hidden

Expected Result(s)
-----------------------------------------------------------------
- Must display mobile date time picker that open bottom of the screen

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![3](https://user-images.githubusercontent.com/4592712/29763142-82a7e892-8bef-11e7-859d-5d5326e7464c.png)

**Comment by sdgun** [comment]
https://www.screencast.com/t/GGaZD1Gpj1lw

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

**Comment by twicoder** [comment]
PR #407
