### ISSUE TITLE
Search_Tags > Articles selected were not navigating to respective URL

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3750]
Target URL: https://www.topcoder.com/thrive

Open the Application and Login as valid user
1.Go to https://www.topcoder.com/thrive
2. Select Tags as filter
3. Enter text "SRM"
4. The articles get listed select the article getting listed out.
5. Its not navigating to respective URL.

Actual: The articles get listed were not navigating to respective URL

**Expected:**The articles get listed should navigate to respective URL

**Browser:

[Issue2.zip](https://github.com/topcoder-platform/community-app/files/4168953/Issue2.zip)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
#3708
