### ISSUE TITLE
Article's right side description is not aligned properly.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3753]
**Describe the bug**
Article's right side description is not aligned properly.The name of the authoe does not align properly with the rest of the details(duration,categories & tags). [UI issue]

**To Reproduce**

1. Go to ' https://www.topcoder.com/thrive/articles/List%20of%20awesome%20learning%20resources'
2. Check the alignement of the author name and handle with the result details in the right side of the page.

**Expected behavior**
The author name and handle should align with the rest of the details in the articles page.

**Screenshots**

![image](https://user-images.githubusercontent.com/55895538/74000885-9f4d0f80-498f-11ea-814f-7b5d043b45f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 home single language, 64 bit OS 
 - Chrome
 - Version 79.0.3945.130

**Comment by winterflame** [comment]
It's because the image is missing, see #3675
