### ISSUE TITLE
Featured Articles> Tiles were not of same size

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3754]
Target URL: https://www.topcoder.com/thrive

Open the Application and Login as valid user
1.Go to https://www.topcoder.com/thrive
2. Scroll down to Featured Articles.
3. Observe the Tiles were not of same Size

Actual: The tile size of the Featured Articles were not of same size.

**Expected:**The title size of the featured articles should be of same size.

**Browser:

![FeauredArticles_Tiles](https://user-images.githubusercontent.com/13567734/74000942-d7ece900-498f-11ea-8f35-dd5265f885f7.jpg)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
duplicated with #3648.
