### ISSUE TITLE
[Functional] Two pages exist for thrive article searching

### ISSUE THREAD

**Issue by sanju-singh** [topcoder-platform/community-app#3756]
Target URL: https://www.topcoder.com/thrive

### Reproduction Steps ###

1. Go to https://www.topcoder.com/thrive
2. Go to 'Design' or any other section, click on any blue links below it.
3. Observe the page loaded.
4. Again to go https://www.topcoder.com/thrive
5. Go to 'FEATURED ARTICLES' section, click on tags inside the articles.
6. Observe the page loaded.

### Expected Result ###

Both the above links should lead to same page. First one looks old UI.

### Actual Result ###

Different links showing different page with same information, but with different way of showing filtering.

### Screenshots or screencast ###

[Screen Recording 2020-02-07 at 9.54.12 AM.zip](https://github.com/topcoder-platform/community-app/files/4168968/Screen.Recording.2020-02-07.at.9.54.12.AM.zip)

### OS/Browser Information ###

Macos / chrome 80.0.3987.87

**Comment by winterflame** [comment]
They're as designed, not a bug.
