### ISSUE TITLE
User is able to select invalid date range

### ISSUE THREAD

**Issue by akhilkanand** [topcoder-platform/community-app#3757]
Title: User is able to select invalid date range
Target URL: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Math%2C%20Advanced%20Math&author=Daniela&startDate=2020-01-23T12%3A00%3A00Z&endDate=1984-02-02T12%3A00%3A00Z
### Reproduction Steps ###
Step 1: Go to the application - https://www.topcoder.com/thrive/
Step 2: Select one of the article from the home page
Step 3: Go to the filter options
Step 4: Enter invalid filter range
### Expected Result ###
Application should throw an error saying that user have selected an invalid data range
<Expected result after reproduction steps>
User should get an error message saying that the selected date range is invalid
<Actual result after reproduction steps>
Application is saying that the search is completed 

<Screenshots or screencast showing the bug>
![image](https://user-images.githubusercontent.com/41775743/74001058-29957380-4990-11ea-9a9d-ae2dc6808e3d.png)

### OS/Browser Information ###
Win 10, Chrome 79

**Comment by winterflame** [comment]
duplicated with #3725
