### ISSUE TITLE
Page like option does not work

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#3758]
**Target URL:** https://www.topcoder.com/thrive/articles/Topcoder%20Bug%20Hunt%20Competitions

**Steps**
1. Go to https://www.topcoder.com/thrive/articles/Topcoder%20Bug%20Hunt%20Competitions
2. scroll down and click on Like sign
Observe that like does not work

**Expected behavior**
Page like should work and increase count

**Screenshots**
![8](https://user-images.githubusercontent.com/51490878/74001140-78430d80-4990-11ea-8b5e-c17f618b12f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
duplicated with #3658
