### ISSUE TITLE
[Web-Firefox] Whole Texts Should Be In Box

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3759]
URL: https://www.topcoder.com/thrive

**Describe the bug**
Whole Written Icon Texts Should Be In Box

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll down to 'Topcoder'

3. Click On Copilots

4. Click On Data Science Select Topcoder-Centric

5. Scroll Down Below To Practical Skills Needed to Win Data Science Competitions

6. See Screenshot & Observe

**Expected behavior**
Whole Written Icon Texts Should Be In Box

**Actual Behaviour**
Whole Written Icon Texts Are Not In Box

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74001142-78dba400-4990-11ea-9f18-f928e1ca216e.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74001158-88f38380-4990-11ea-8171-7c3fa81fb3a7.png)

**Additional context**
UI Issue

**Comment by winterflame** [comment]
No screenshot.
