### ISSUE TITLE
[$10] - Number of filters applied count is not displayed in the filter area

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#376]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges?

- Scroll down and click on a technology tag (eg: C++)

- Check the Filter button

Actual Result(s)
-----------------------------------------------------------------
- Number of filters applied count must displayed in the blue circle in the filter area when user click on a technology tag

Expected Result(s)
-----------------------------------------------------------------
- Number of filters applied count is not displayed in the filter area  when user click on a technology tag

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![4 1](https://user-images.githubusercontent.com/4592712/29763679-ccd570c2-8bf1-11e7-8a58-cb509a855a67.png)
![4 2](https://user-images.githubusercontent.com/4592712/29763681-ccd9bb28-8bf1-11e7-8791-13b7cacf337d.jpg)

**Comment by sdgun** [comment]
https://www.screencast.com/t/c9QT2KWTen

**Comment by birdofpreyru** [comment]
@sdgun I believe, it is intentional to save space in the mobile layout. @vic-topcoder ?

**Comment by vic-topcoder** [comment]
I accept it as a bug - the consistency of the design is broken in this case. It should be showing the number of filters applied on the list the same way as on desktop - mechanics is the same. For mobile design we should remove the label of the menu and keep the icon with the badge (when there are modifiers). The design was not correct. Good catch!

Please update to the following:
![screen shot 4](https://user-images.githubusercontent.com/8484061/29781561-712a77fe-8bce-11e7-8812-8025998e5ca5.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by twicoder** [comment]
PR #401
