### ISSUE TITLE
No author details displayed/included in the article

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3760]
**Target URL:** https://www.topcoder.com/deploying-apps-to-heroku-with-docker/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/deploying-apps-to-heroku-with-docker/

Observe under the articles details

**Actual:**  The details of the articles author are not included in the article

**Expected:** There should be the author details in the article details page
![none](https://user-images.githubusercontent.com/37167721/74001217-cc8fc280-497b-11ea-9f6d-93ee8d576b65.jpg)

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
#3660
