### ISSUE TITLE
Symbols truncating if browser window size is modified

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/community-app#3761]
Description: Symbols truncating if browser window size is modified. UI should be responsive.

Target URL: https://www.topcoder.com/blog/

Reproduction Steps:
1. Go to https://www.topcoder.com/thrive -> Explore -> Blog
2. Let the page load and then minimise the window size
3. Scroll down to the bottom of the page
4. Notice symbols are truncating. If window is enlarged or back to normal size then symbols are not visible at all.

Expected Result:
Symbols should be visible even if browser window is modified.

Actual Result:
Notice symbols are truncating. If window is enlarged or back to normal size then symbols are not visible at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/12671119/74001265-f3a4bf00-4990-11ea-850a-6bee1a675b1f.png)

OS/Browser Information:
 - OS: Windows 10
 - Browser : Google Chrome
 - Version : Version 80.0.3987.87 (Official Build) (64-bit)

Bug Label: UI

**Comment by winterflame** [comment]
out of scope.
