### ISSUE TITLE
In Article page place holder image should be present for user when user does not have own picture in profile

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#3762]
**Target URL:**  https://www.topcoder.com/thrive/articles/Test%20Scenarios%20and%20Scripts

**Steps**
1. Go to https://www.topcoder.com/thrive/articles/Test%20Scenarios%20and%20Scripts
Observe the user name.
When user does not have profile picture, article shows not properly aligned but actually user place holder image is not present

**Expected behavior**
User place holder image should be present when actual user photo in not available for that user.

**Screenshots**
![9](https://user-images.githubusercontent.com/51490878/74001377-5c8c3700-4991-11ea-8a88-733ca09d2478.png)

**Environment**
 - OS: Windows 10 
 - Browser Chrome
 - Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
#3675
