### ISSUE TITLE
[Web-Firefox] Video Should Play In Same Tab

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3764]
URL: https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Big%20Data

**Describe the bug**
While Playing Video Its Playing In New Tab

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll down to Topcoder

3. Click on Copilot

4. Click On Data Science > Select Big Data

5. Click On Play Button Then See Screencast & Observe

**Expected behavior**
Video Should Play In Same Tab

**Actual Behaviour**
While Playing Video Its Playing In New Tab

**Screencast**
[Video.mp4.zip](https://github.com/topcoder-platform/community-app/files/4169001/Video.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74001638-65313d00-4992-11ea-9d49-20221844c996.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74001662-724e2c00-4992-11ea-82a0-a24f68b0e461.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
not a bug

**Comment by kkartunov** [comment]
External content should open in new tab
