### ISSUE TITLE
Search dropdown won't close if user does any operation on the page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3766]
https://www.screencast.com/t/xXwwCtmxx

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/
3. Click 'COMPETITIVE PROGRAMMING'
4. Click on Filter dropdown
5. Scroll down and click on the 'SRM Editorials'
6. Check the dropdown

**Actual:** Search dropdown won't close if user does any operation on the page

**Expected:** Should close the dropdown

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by kkartunov** [comment]
This is expected behavior.
