### ISSUE TITLE
Left Nav > Suggest to increase the display the letters with spacing in the left nav.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3767]
Target URL: https://www.topcoder.com/thrive/articles/How%20to%20create%20a%20LUX%20RUX%20presentation%20for%20Topcoder

Steps to Reproduce.

1. Navigate to the above URL.
2. Observe the Left nav.
3. Charecters were getting hided.

Actual: The size of the left nav charecters were not give any space.

**Expected:**The space should be given between the charecters and browser window.

**Browser:
[Issue4.zip](https://github.com/topcoder-platform/community-app/files/4169016/Issue4.zip)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by Jacob15** [comment]
This is happening for most of the pages. For Example
https://www.topcoder.com/thrive/tracks?track=Design&tax=Design%20Theory&author=All%20authors&startDate=1920-01-01T12%3A00%3A00Z&endDate=2020-02-07T11%3A06%3A10%2B05%3A30

**Comment by winterflame** [comment]
Unable to reproduce. Maybe it's due to small screen size.
