### ISSUE TITLE
Articles > Suggest to display Show Less button if the articles count reached the maximum number.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3769]
Target URL: 

https://www.topcoder.com/thrive/search?tags[0]=Tips

Steps to Reproduce.

Navigate to the above URL.
1. Click on Show More until all the articles get loaded.
2.  Observe there is no show Less button to get the articles page to original position.

**Expected:** Suggest to display "Show Less" button to get the articles page to original position.

**Browser:
[Issue5.zip](https://github.com/topcoder-platform/community-app/files/4169038/Issue5.zip)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
not needed
