### ISSUE TITLE
[$30] - 'Winner' tab text is not fully visible

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#377]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges/30058868/?type=design

- Scroll the title till the Winners tab

- Check the text and it is half hidden

Actual Result(s)
-----------------------------------------------------------------
- 'Winner' tab text is not fully visible

Expected Result(s)
-----------------------------------------------------------------
- 'Winner' tab text must fully visible

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![5](https://user-images.githubusercontent.com/4592712/29763902-b38bd1be-8bf2-11e7-8201-2406be1fde25.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

### Expected Fix
That transparency gradient element is there intentionally, to show that there is more options if we scroll. What we need is to hide it when the tab selector is scrolled till the end. Also, we need to add similar gradient on the left side of the tab selector (visible when we scroll out of the start).

**Comment by daft300punk** [comment]
Is PR still being accepted for bugs with OPEN FOR PICKUP tag? I have hacked a solution for this. I will submit a PR if it is still being accepted.

**Comment by birdofpreyru** [comment]
@daft300punk here is no such tag anymore :) but if you get a good solution for this, I'll be more than happy to accept it and pay :)

**Comment by daft300punk** [comment]
@birdofpreyru after updating the develop branch, I see the class names are random strings, not the ones that used to be before. Has something changed? I wanted to select an element that previously used to have a class "src-shared-components-challenge-detail-Header-TabSelector-style___mask", but now instead "_3_wOir" is being shown on inspecting.

**Comment by birdofpreyru** [comment]
@daft300punk Yes, now all class names are hashed for production builds. It is a big optimization, cause it decreases the size of resulting css bundles 2-3 times. For test and development builds classnames are still verbose, to simiplify matching between styles and original code without sourcemaps. Hashing is done by `babel-plugin-react-css-modules`. I believe, inside JS code of the component you can do something like:
```js
import style from './style.scss';
const className = style['CLASS_NAME_IN_THE_CODE'];
```
to get class name automatically resolved to the resulting name in the bundle. Otherwise, you may use element `id`s for selection.

**Comment by daft300punk** [comment]
Cool. Checkout PR - https://github.com/topcoder-platform/community-app/pull/442
