### ISSUE TITLE
Autocompletion box instead of dropdown for author field in the Filter.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3770]
**Describe the bug**
Autocompletion box is better for the author field in the Filter instead of dropdown since it is difficult for the user to scroll down to search a particular author. [UX issue]

**To Reproduce**

1. Go to ' https://www.topcoder.com/thrive/search?tags[0]=Recipe'
2. Check the author dropdown field under the filter.

**Expected behavior**
Dropdown should be replaced with autocompletion for the Author field for easy filter by the user.

**Screenshots**

![image](https://user-images.githubusercontent.com/55895538/74002117-0d93d100-4994-11ea-88f8-a5661ba66e93.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 home single language, 64 bit OS 
 - Browser: Google chrome 
 - Version: 79.0.3945.130

**Comment by winterflame** [comment]
similar to #3670
