### ISSUE TITLE
[Common] Some links on the videos; will open the link on the same page and other on a separate page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3772]
https://www.screencast.com/t/UgUPikJ9rpzi

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Design&tax=&author=All%20authors&startDate=2010-01-01T12%3A00%3A00Z&endDate=2020-02-06T22%3A53%3A09-06%3A00

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/
3. Click 'Design'
4. Click on Filter > Set the date to Jan 1, 2010 - Feb 7, 2020 > Applt Filter
5. Click 'Videos' tab
6. Check all 4 links

**Actual:** Some links on the videos; will open the link on the same page and other on a separate page

**Expected:** Should be consistant

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
#3764
