### ISSUE TITLE
Author dropdown should only show the authors from the listed articles for that category

### ISSUE THREAD

**Issue by smartgood** [topcoder-platform/community-app#3773]
![issue1](https://user-images.githubusercontent.com/60750613/74002303-d540c280-4994-11ea-852f-601a35b459e1.png)

Target URL: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming
    
    Open the Application and Login as valid user
    Go to https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming
    Click "Show Filter" link
     Check the Author dropdown

Actual: All the universal authors are displayed in the drop down. This will be a pain for the user to loop thru all the authors who don't have a article for the selected category.

Expected: Author drop down should only list the authors who have their articles listed for the selected category.
For example, the the competitive  programming category, only 14 articles are listed. with only 10 authors. But the drop down is showing numerous authors which will confuse the user and will take more time to find the actual author they are looking for.

Environment: Asus 15.6inch ; Windows 10
Browser: Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
We'll consider this: #3670
