### ISSUE TITLE
Thrive Menu Link > Should be selectable to make the user interaction easier

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3774]
Target URL:

https://www.topcoder.com/thrive/search?tags[0]=Tips

Steps to Reproduce.

Navigate to the above URL.

1. Click on Thrive menu link
2. Its not selectable.
3. It should be selectable to navigate the user back to Thrive.

Expected Result

Thrive menu link should be selectable to navigate the user back to Thrive.

**Browser:
[Issue6.zip](https://github.com/topcoder-platform/community-app/files/4169053/Issue6.zip)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
On any other page, it should provide an easy way to go back to home page.

**Comment by kkartunov** [comment]
fixed.
