### ISSUE TITLE
An article link leads to 404 error page(Functional)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3775]
**Target URL:** https://www.topcoder.com/thrive

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/iconic-designs-crowdsourcing-competitions/

Go to Designs, Observe under the design tags
Click the article

**Actual:
[404.zip](https://github.com/topcoder-platform/community-app/files/4169060/404.zip)
** The article link when clicked it opens a 404 topcoder error page

**Expected:** The article link should direct to article details page when clicked

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
#3729
