### ISSUE TITLE
There is no character limit set for entering search key words on the search bar

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/community-app#3777]
Description:
There is no character limit set for entering search key words on the search bar

Target URL: https://www.topcoder.com/thrive 

Reproduction Steps:
1. Go to- https://www.topcoder.com/thrive 
2. Start entering any random characters in the search bar.
3. Search bar allows user to enter unlimited characters in the search bar

Expected Result:
There should be word/ character limit on search bar specially if user has selected Author/tab option

Actual Result:
User is able to enter unlimited characters in the search bar

Screen Shot:
![image](https://user-images.githubusercontent.com/12671119/74002608-abd46680-4995-11ea-8bf3-c60af40219a4.png)

OS/Browser Information:
 - OS: Windows 10
 - Browser : Google Chrome
 - Version : Version 80.0.3987.87 (Official Build) (64-bit)

Bug Label: Functional

**Comment by winterflame** [comment]
#3747
