### ISSUE TITLE
[$20] - Inconsistency in time remaining for registration phase in two locations

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#378]
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- Check the 'Predix - Integration with Alexa Voice Service'

- Below the progress bar > 6d 4:51h to go

- Blue box area > 6d 4:50h to register

Actual Result(s)
-----------------------------------------------------------------
- Inconsistancy in time remaining for registration phase in two locations

Expected Result(s)
-----------------------------------------------------------------
- In both locations time remaining must be same

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/Console Log
-----------------------------------------------------------------
> If attachment is not here, Please check the comments section

**Comment by sdgun** [comment]
![68](https://user-images.githubusercontent.com/4592712/29764969-f172d17c-8bf6-11e7-83a2-d0ca8be47b65.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru what's the price for this one?

**Comment by birdofpreyru** [comment]
@shubhendusaurabh I'd say $20

**Comment by shubhendusaurabh** [comment]
@birdofpreyru not a bug. one is registration remaining time and other is submission remaining time

**Comment by birdofpreyru** [comment]
Ohh... indeed
