### ISSUE TITLE
Article read time and author name link not displayed/missing

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3782]
**Target URL:** https://www.topcoder.com/usa-diving-tracks-health-and-performance-data-with-crowdsourced-ipad-app/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/usa-diving-tracks-health-and-performance-data-with-crowdsourced-ipad-app/

Observe under the articles details

**Actual:** No link of the authors name and read time of the article is displayed

**Expected:** There should be read time and author name link displayed in the article
![user4](https://user-images.githubusercontent.com/37167721/74003102-81c57900-4982-11ea-8752-f7e5c01c4a6d.jpg)

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Not in scope. The URL should start with https://www.topcoder.com/thrive/
