### ISSUE TITLE
There is no picture for Debugging for Marathon Competitions card article

### ISSUE THREAD

**Issue by fahfai** [topcoder-platform/community-app#3784]
**Testing URL** https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=

**Step To Reproduce**
1. Go to https://www.topcoder.com/thrive
2. Click on Data Science
3. Scroll down to the Debugging for Marathon Competitions card article
4. Observe 

**Expected Result**
The Debugging for Marathon Competitions card article should have a picture on the card just the same as the other cards

**Actual Result**
The Debugging for Marathon Competitions card article don't have a picture on the card

**Screenshots**
![Bug5](https://user-images.githubusercontent.com/39216496/74003141-90c12100-49ac-11ea-83b4-a43102ce41e6.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina version 10.15.2
 - Browser Chrome
 - Version 79.0.3945.130 (Official Build) (64-bit)

**Bug Label** UI

**Comment by winterflame** [comment]
not a bug, not all articles have pictures.
