### ISSUE TITLE
[Web-Firefox] Alignment Issue

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3785]
URL: https://www.topcoder.com/thrive

**Describe the bug**
There Is Alignment Issue In QA. It Looks Like Some Part is Cutting

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse Below To Topcoder

3. Select Copilot  > Select QA

4. See Screenshot & Observe

**Expected behavior**
QA Should Be Aligned Properly

**Actual Behaviour**
There Is Alignment Issue In QA

**Screenshots**
![Alignment](https://user-images.githubusercontent.com/42583358/74003113-821c3f00-4997-11ea-9e6e-5136139d2e1e.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74003130-95c7a580-4997-11ea-86bf-91a3409ed2ed.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74003149-a37d2b00-4997-11ea-933b-9499b26657f7.png)

**Additional context**
UI Issue

**Comment by winterflame** [comment]
not a bug, it is left aligned.
