### ISSUE TITLE
Nachos link opens a different page same as atlassian.design when clicked

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3787]
**Target URL:** https://www.topcoder.com/a-study-of-design-language-part-1-introduction/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/a-study-of-design-language-part-1-int

roduction/
[Nacho.zip](https://github.com/topcoder-platform/community-app/files/4169146/Nacho.zip)

**Go to** "Nachos" link in the article detail

**Actual:** If you click "Nachos" link it opens the atlassian.design same as when you click atlassian Design system.

**Expected:** The Nachos link should open Nachos page and not atlassian page 
Check the video below
Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Out of scope. See https://apps.topcoder.com/forums/?module=Thread&threadID=950448&start=0
