### ISSUE TITLE
When the screen size is modified(approx. 600x570)'Featured Articles' blocks alignment is not proper

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/community-app#3788]
Description:
When the screen size is modified to 600x570 size blocks alignment is not proper whereas when it is modified to 534x570 alignment is proper.

Target URL: https://www.topcoder.com/thrive

Reproduction Steps:
1. Go to https://www.topcoder.com/thrive
2. Minimize window size (approx. 600x570).
3. Notice 'Featured Articles' blocks alignment is not proper
4. Minimise this screen further( approx 534x570 ), alignment is proper now.

Expected Result :
Blocks under 'Featured Articles' should always be properly aligned since page is responsive.

Actual Result:
'Featured Articles' blocks alignment is not proper.

ScreenShot:
![image](https://user-images.githubusercontent.com/12671119/74003464-af1d2180-4998-11ea-8f0d-0df0d036c226.png)

OS/Browser Information:
 - OS: Windows 10
 - Browser : Google Chrome
 - Version : Version 80.0.3987.87 (Official Build) (64-bit)

Bug Label: UI

Similar issue reported reference: https://github.com/topcoder-platform/community-app/issues/3754

**Comment by winterflame** [comment]
#3697
