### ISSUE TITLE
[Web-Firefox] Competitive Programming Is Overlapping Image

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3789]
URL: https://www.topcoder.com/thrive

**Describe the bug**
Word Competitive Programming Is Overlapping Image

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Click on Competitive Programming

3. See Screenshot & Observe

**Expected behavior**
Word Comprtitive Programming Should Not Overlap Image

**Actual Behaviour**
Word Competitive Programming Is Overlapping Image

**Screenshots**
![Programming](https://user-images.githubusercontent.com/42583358/74003661-6e71d800-4999-11ea-8ff2-cad113d0d0e2.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74003681-80ec1180-4999-11ea-9648-324665da1c42.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74003698-8ea19700-4999-11ea-94ed-014251685284.png)

**Additional context**
UI Issue

**Comment by winterflame** [comment]
Works fine with normal screen size.
