### ISSUE TITLE
1st and 2nd should be consistently written

### ISSUE THREAD

**Issue by kaygee1** [topcoder-platform/community-app#379]
Open the page 
http://community-app.topcoder.com/challenges/30058995/?type=develop

See the prizes first and second and how they are written

actual - First is written as 1 st with a space between 1 and st and SEcond is written as 2nd without a space between 2 and nd

expected - they should be consistently written

chrome 60
Win 10
laptop
![6](https://user-images.githubusercontent.com/5115050/29766707-47658812-8bfd-11e7-8772-e78013566a68.png)

**Comment by birdofpreyru** [comment]
Not a bug: there is no extra whitespace in `1st`, it is just that font creates a bit more spacing between `1` and `s`, than between `2` and `n`.
