### ISSUE TITLE
Track details_Apply Filter> Reset is no clearing the text entered

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3791]
Target URL:

https://www.topcoder.com/thrive/tracks?track=Design&tax=Design%20Theory&author=All%20authors&tags[0]=ui%20design&startDate=2020-01-07T11%3A04%3A26%2B05%3A30&endDate=2020-02-07T11%3A04%3A26%2B05%3A30

Steps to Reproduce.

Navigate to the above URL.

1. Type ui design in the tag name.
2. Apply reset
3. Its not clearing out the tags entered.

Expected Result

Reset to clear the filters entered

**Browser:

[Issue8.zip](https://github.com/topcoder-platform/community-app/files/4169160/Issue8.zip)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
duplicated
