### ISSUE TITLE
Instagram option is not available for sharing an article

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3792]
When the user clicks on any article present on the Thrive page, the article can be shared with Linkedin, Facebook, and Twitter but there is no option of sharing it on Instagram

**Target URL**:  https://www.topcoder.com/thrive

**Steps to reproduce the behavior:**
1. Go to [https://www.topcoder.com/thrive]
2. Click on any article  under any of the Tags available 
3. Scroll down to Share option
4. Observe that Instagram option is missing for sharing

**Expected behavior**
There should be an Instagram option for sharing the articles available
**Actual** 
Instagram icon is not available for sharing the article on Instagram
**Screenshots**
![Bug001](https://user-images.githubusercontent.com/46349625/74004227-2e135980-499b-11ea-9393-b6ac692b06fb.jpg)

Environment: Micromax LI351568W 15.6 ; Windows 10x64
Browser: Google Chrome Version 80.0.3987.87

**Comment by kalindipandey** [comment]
<Functional>

**Comment by kalindipandey** [comment]
Bug Label:<Functional>

**Comment by kalindipandey** [comment]
**Bug Label**:`Functional`

**Comment by kalindipandey** [comment]
Bug Label: <UI>

**Comment by kalindipandey** [comment]
Labels`Functional`

**Comment by winterflame** [comment]
not a bug
