### ISSUE TITLE
Highlighted Outline is missing in corner and few places

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/community-app#3793]
Target URL: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Topcoder-Centric

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/
3. Go to COMPETITIVE PROGRAMMING Tab> TOPCODER-CENTRIC
4. Click on the Post "GITHUB REPOSITORIES WITH COMPETITIVE PROGRAMMING LIBRARIES"
5. Observe the outline is missing in corner and  few places
6. Similar Problem in "MM retrospective", "Advanced Math"

 Actual: Highlighted Outline is missing in corner and  few places

Expected : Highlighted Outline should not be missing in corner and  few places

**Screenshots**

![Screenshot (76)](https://user-images.githubusercontent.com/29044523/74004370-982bfe80-499b-11ea-9239-5c3beffa654f.png)

ScreenCast

[bandicam 2020-02-07 11-19-45-242.zip](https://github.com/topcoder-platform/community-app/files/4169195/bandicam.2020-02-07.11-19-45-242.zip)

Desktop:

OS: [Windows]
Browser Google Chrome 80.0.3987.87 | FF 72.0.2]

**Comment by winterflame** [comment]
Actually, there should be no outline while clicking.

**Comment by Vips19** [comment]
@winterflame Is there any existing bug for removing the outline when selected or else a new issue should be created for it. As for all the items selected there is some outline available.

**Comment by winterflame** [comment]
@Vips19 Yes, see https://github.com/topcoder-platform/community-app/issues/3719.
