### ISSUE TITLE
Page  not found when link in the article clicked(FUNCTIONAL)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3794]
**Target URL:** https://www.topcoder.com/the-new-rules-of-ux/

Open the Application and Login as valid user
**Go to
[page.zip](https://github.com/topcoder-platform/community-app/files/4169198/page.zip)
** https://www.topcoder.com/the-new-rules-of-ux/

Observe the "one-third of users will abandon a site because of a poor experience " link

**Actual:** When the link is clicked it opens a "Page not found"

**Expected:** When the link is clicked it should direct to the links details

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
The targe URL is not in scope for this challenge.
