### ISSUE TITLE
Description displayed below the title are different from article to article

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3795]
![image](https://user-images.githubusercontent.com/42398485/74004593-c679f180-493b-11ea-9a3f-3b0ee8182b8a.png)
![image](https://user-images.githubusercontent.com/42398485/74004607-d0035980-493b-11ea-8fa7-be32297f8c1d.png)

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Help%20Articles

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Help%20Articles
3. Check the article description

**Actual:** description displayed below the title are different from article to article. Sometimes display like paragraphs, Font formattings are preserved etc... 

**Expected:** description displayed below the title should be formatted properly

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by kkartunov** [comment]
Fixed.
