### ISSUE TITLE
[Web-Firefox] In Video Thums Up & Thums Down Is Not Increasing Numbers

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3796]
URL: https://www.topcoder.com/thrive

**Describe the bug**
In Video Thums Up & Thums Down Is Not Increasing Numbers While Clicking On It. It Still Showing ZERO

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse To QA

3. Select Best Practices/Instructions/Tricks/Tips

4. Click On Video Then Play It.

5. Click On Thums UP & Thums Down Then Observe

**Expected behavior**
In Video Thums Up & Thums Down Number Should Be Increased

**Actual Behaviour**
In Video Thums Up & Thums Down Is Not Increasing Numbers

**Screencast**
[Thums Up.mp4.zip](https://github.com/topcoder-platform/community-app/files/4169199/Thums.Up.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74004610-35873280-499c-11ea-8d28-c01940646726.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74004619-42a42180-499c-11ea-9b21-524b805531d9.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
#3654
