### ISSUE TITLE
Social links title unnecessary prefix.

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/community-app#3797]
Title: Social links title unnecessary prefix.

Target URL: https://www.topcoder.com/thrive/articles/King%20of%20the%20Silicon%20Hill:%20Today's%20High-End%20Microprocessors

### Reproduction Steps ###
1. Go to Target URL
2. On Social Share Icons hover over twitter button. (or other social icons)
3. Icon title will be "icon twitter" instead of just "twitter"

### Expected Result ###
1. Social icon hover title should be "twitter". 

### Actual Result ###
1. Social icon hover title is "icon twitter". 

### Screenshots or screencast ###
![Screenshot from 2020-02-07 13-48-48](https://user-images.githubusercontent.com/7783676/74004697-7c335780-49b1-11ea-8832-d5bebca18953.png)

### OS/Browser Information ###
Version 79.0.3945.130 (Official Build) (64-bit)

Bug Label: UI

**Comment by kkartunov** [comment]
No longer present.
