### ISSUE TITLE
[$10] - Discrepancy between same pages in desktop and phone

### ISSUE THREAD

**Issue by kaygee1** [topcoder-platform/community-app#380]
Open the page 
http://community-app.topcoder.com/challenges/30058932/?type=develop
on both phone and desktop

Phone iPhone 6+
iOS 10.3.3

Chrome 60

Click on Registrants and see the display

actual - in desktop there is no Round 2 Submitted date
In phone there is a label - Round 2 submitted date

expected - discrepancy should not be there

![7](https://user-images.githubusercontent.com/5115050/29767182-23881854-8bff-11e7-8d3a-6ba8c5468c47.png)

![8](https://user-images.githubusercontent.com/5115050/29767220-45b72a64-8bff-11e7-8438-6c778198a0f7.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point
