### ISSUE TITLE
Link in the design article not functional and opens 404 error

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3801]
**Target URL:**https://www.topcoder.com/your-guide-to-mobile-first-design/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/your-guide-to-mobile-first-design/

Observe under the article details

**Actual:**  The "interact with content." link in the article directs to a 404 page error

Expected: The "interact with content" link should direct to the links details
[Top.zip](https://github.com/topcoder-platform/community-app/files/4169226/Top.zip)

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
out of scope
