### ISSUE TITLE
Click Here button hover  effect is  not properly shown 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3803]
Target URL: 

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 scroll down to footer 
3. mouse over Click Here button  

### Expected Result ###

should enable hover  effect

### Actual Result ###
Click Here button hover  effect is  not properly shown 

### Screenshots or screencast ###
[bandicam 2020-02-07 11-30-12-505.zip](https://github.com/topcoder-platform/community-app/files/4169235/bandicam.2020-02-07.11-30-12-505.zip)

![here](https://user-images.githubusercontent.com/4590317/74394387-7de49b80-4e47-11ea-8cc9-7404c0a6f4bd.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by karthikbecse** [comment]
Target URL:https://www.topcoder.com/thrive/

**Comment by kkartunov** [comment]
Button no longer exists.
