### ISSUE TITLE
"How to Win with Design & Development as a Small Business"link opens 404 page error

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3804]
**Target URL:** https://www.topcoder.com/design-and-development-smb-ebook/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/design-and-development-smb-ebook/

Observe under articles details

Actual: The link "How to Win with Design & Development as a Small Business" opens a 404 page when clecked

Expected: The link should direct to link details when clicked
[top1.zip](https://github.com/topcoder-platform/community-app/files/4169252/top1.zip)

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
out of scope
