### ISSUE TITLE
[Web-Firefox] Gradient Boosting Algorithms Opening In New Tab

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3806]
URL: https://www.topcoder.com/thrive

**Describe the bug**
Markov Model & King Of The Silicon Hill Topics Are Opening In Same Tab While Gradient Boosting Algorithm Is Opening In New Tab

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Click on Markov Model & King Of The Silicon Hill Topics Its Opening In Same Tab

3. Click On Gradient Boosting Algorithms Its Opening In Another Tab

4. See Screencast & Observe

**Expected behavior**
All Three Topics Should Open In Same Tab

**Actual Behaviour**
Gradient Boosting Algorithms Opening In New Tab

**Screencast**
[Gradient.mp4.zip](https://github.com/topcoder-platform/community-app/files/4169265/Gradient.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74005597-67e65f00-499f-11ea-9883-ca4f77708610.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74005618-7765a800-499f-11ea-9b15-6a41e5cd2743.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
Similar to #3764

**Comment by kkartunov** [comment]
Yes, external articles need to open in new tabs.
