### ISSUE TITLE
facebook : share article is  not configred properly 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3807]
Target URL: https://www.topcoder.com/thrive/articles/Python%20for%20Data%20Visualization%20%E2%80%93%20Seaborn%20Plots%20Basics

### Reproduction Steps ###
1 goto https://www.topcoder.com/thrive/
2 click Data Visualization
3 click Python for Data Visualization – Seaborn Plots Basics 
4.click share facebook 

### Expected Result ###
should share article details properly 

### Actual Result ###
article is not configured for sharing with Facebook 

### Screenshots or screencast ###

![bandicam 2020-02-07 11-41-33-107](https://user-images.githubusercontent.com/3225433/74005646-88aeb480-499f-11ea-8f78-c895083a2069.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

Note:
article title and image should print Facebook preview while sharing instead of topcoder banner

**Comment by kkartunov** [comment]
Those share buttons are no longer in use.
