### ISSUE TITLE
When searched with special character in the search bar, no error message is displayed.

### ISSUE THREAD

**Issue by apatra16** [topcoder-platform/community-app#3808]
Target URL: 
https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Recursion

Reproduction Steps:
1. Go the testing url
2. Enter special characters in the search bar , say  #%$^%&^&^*&(*
3. Hit enter

Expected Result:
Error message should be displayed if no results are returned

Actual Result:
![no search results are returned](https://user-images.githubusercontent.com/36477026/74005660-982dfd80-499f-11ea-8541-d5a0c7bd597d.jpg)

OS/Browser Information: Chrome

**Comment by winterflame** [comment]
Duplicated with #3647.
