### ISSUE TITLE
When User opens the Thrive page by entering the URL "Events" is Underlined instead of "Thrive" option

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3809]
**Describe the bug**
When User opens the Thrive page by entering the URL "Events" option is underlined instead of the "Thrive" option which makes the impression that the Event option is open.

**Target URL**: https://www.topcoder.com/thrive

**Steps To Reproduce**
1. Open the Application and Login as valid-user
2. Go to https://www.topcoder.com/thrive/
3. Observe

**Actual**:  When User opens the Thrive page by entering the URL "Events" is Underlined instead of "Thrive" option
**Expected**: When User opens the Thrive page by entering the URL "Thrive" option should be Underlined

**Environment**:  Micromax LI351568W 15.6 ; Windows 10x64
**Browser**:  Google Chrome Version 80.0.3987.87

![Bug002](https://user-images.githubusercontent.com/46349625/74005652-919f8600-499f-11ea-8254-f60776429738.jpg)

**Bug Label**: <UI>

**Comment by kalindipandey** [comment]
**labels**:`ui`

**Comment by kalindipandey** [comment]
Labels`ui`

**Comment by winterflame** [comment]
Similar to #3665

**Comment by kkartunov** [comment]
Not relevant anymore.
