### ISSUE TITLE
[$10] - 'Data Science' text font is different from others

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#381]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges

- Click Tracks

- Check the font size and style in 'Data Science' 

Actual Result(s)
-----------------------------------------------------------------
- 'Data Science' text font is different from others

Expected Result(s)
-----------------------------------------------------------------
- 'Data Science' text font must match with the others

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![6](https://user-images.githubusercontent.com/4592712/29768510-2a0ff55c-8c04-11e7-8395-ee6dcf6f29d4.png)

**Comment by birdofpreyru** [comment]
Accepted, 1 point
