### ISSUE TITLE
Article reference links should open new tab 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3810]
Target URL: https://www.topcoder.com/thrive/articles/Python%20for%20Data%20Visualization%20%E2%80%93%20Seaborn%20Plots%20Basics

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 click Data Visualization
3 click Python for Data Visualization – Seaborn Plots Basics
4. In page click reference link 

### Expected Result ###
should open external tab  

### Actual Result ###
current tab redirected to the new  link 

### Screenshots or screencast ###
[bandicam 2020-02-07 11-53-57-517.zip](https://github.com/topcoder-platform/community-app/files/4169289/bandicam.2020-02-07.11-53-57-517.zip) 

![ar](https://user-images.githubusercontent.com/4590317/74396376-ba66c600-4e4c-11ea-8f3c-a894226f1a03.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by kkartunov** [comment]
External articles should open in a new tab.
