### ISSUE TITLE
Problems solving- Ternary search  link not working

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3812]
**Target URL:**  https://www.topcoder.com/thrive

**To Reproduce**
1. Go to topcoder thrive page 
2.  Type "Binary Search" in the search bar
3.  In dorp-down we got Problems solving- Ternary search in forum post

**Actual-**
Forum post Problems solving- Ternary search is not working.

**Expected behavior**
Forum post Problems solving- Ternary search link should be working

**Screenshots**
https://drive.google.com/open?id=1k5kK_QFXbQWXLjd_8c1bavqXLIkI8e5W

**Desktop:**
 - OS: Lenovo, Windows 10 Home
 - Browser: Firefox
 - Version: 72.0.2

**Comment by winterflame** [comment]
Cannot reproduce in Mac+Firefox. Duplicated with #3708 .
