### ISSUE TITLE
No enough margin/Images in the page not well displayed 

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3814]
**Target URL:** https://www.topcoder.com/thrive/articles/Power%20BI:%20Basic%20Things%20Not%20to%20Be%20Missed%20(Desktop%20Version)

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/articles/Power%20BI:%20Basic%20Things%20Not%20to%20Be%20Missed%20(Desktop%20Version)

Observe under Articles details

**Actual:** There is a small margin on the right to the images in the articles details

**Expected:** There should be enough margin to the images in the articles details
![pad](https://user-images.githubusercontent.com/37167721/74006521-fef5eb80-498c-11ea-9ffb-c2dd9cc57b60.jpg)

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
won't fix
