### ISSUE TITLE
There is no permissible limit set for the date picker.

### ISSUE THREAD

**Issue by apatra16** [topcoder-platform/community-app#3815]
**Describe the bug**
There is no permissible limit set for the date picker.

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/search?tags[0]=Algorithm
2. Delete the date displayed in the date picker and enter random characters.

**Expected behavior**
Permissible limit should be set for the date picker

Actual Result: User is able to enter infinite characters:

Data entered:
111111111111111111111111111111111222245234444445555555555555555555555555555555555647656456465764576475674657643756746576487657465764566576456457465876456764574657645646587658747658746764658764564657643875687465874576487658746576487564876574658764875476587657647567465876458764875687465874658764875648765874658764756874

**Screenshots**

Screenshot attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version: 79.0.3945.130 

![No permissible limit set](https://user-images.githubusercontent.com/36477026/74006682-75511880-49a2-11ea-969e-e6e6327ac8ad.jpg)

**Comment by winterflame** [comment]
same as #3813
