### ISSUE TITLE
Author username is not a link/not clickable

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3817]
**Target URL:** https://www.topcoder.com/thrive/articles/Tableau:%20Basic%20Things%20Not%20to%20Be%20Missed

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/articles/Tableau:%20Basic%20Things%20Not%20to%20Be%20Missed

Observe the author details under the articles details

**Actual:
![user3](https://user-images.githubusercontent.com/37167721/74006822-e934f600-498d-11ea-9c71-9f37e7bb9232.jpg)
** The author username is not clickable 

**Expected:** The author username should be a link and should be clickable to direct to the username profile page

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
duplicated with #3660
