### ISSUE TITLE
No error message is displayed, when date is entered in incorrect format and user clicks on Apply Filter

### ISSUE THREAD

**Issue by apatra16** [topcoder-platform/community-app#3818]
**Describe the bug**
No error message is displayed, when date is entered in incorrect format and user clicks on Apply Filter

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/search?tags[0]=Algorithm
2. Delete the date displayed in the date fields and enter random charcater
3. Click on Apply filters

**Expected behavior**
Should display error message or Apply filter field should be disabled.

Actual behavior:
Apply filter remains enabled.

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [Chrome
 - Version 79.0.3945.130 

![Apply Filter button is not working](https://user-images.githubusercontent.com/36477026/74007035-5dc65f80-49a3-11ea-8490-792a0d20a988.jpg)

**Comment by winterflame** [comment]
duplicated with #3725
