### ISSUE TITLE
UI Issue > Present in the https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3819]
URL
https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder

To Reproduce

1.Visit the above URl
2.Observe the spacing and UI issues w.r.t text, image present

Expected behavior

UI issues should not present in the article page

Actual Result: UI issues present in the articles page. for ex:
https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder

Screenshots

Screenshot attached

![QA_UIIssues](https://user-images.githubusercontent.com/13567734/74007495-7a16cc00-49a4-11ea-8a39-26c6a28ed777.jpg)

Desktop (please complete the following information):

OS: Windows
Browser : Firefox
Version: 72.0.2 (64-bit)

**Comment by winterflame** [comment]
I cannot see any UI issues.
