### ISSUE TITLE
[$20] - After Selecting multiple 'Subtrack' (10) it is hard to select 'Date range'

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#382]
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL

- Login as a valid user (Portraot Mode)

- Go to http://community-app.topcoder.com/challenges

- Click Filters

- Select 10 Subtracks from the filter and try to select 'Date Range'

Actual Result(s)
-----------------------------------------------------------------
- After Selecting multiple 'Subtrack' (10) it is hard to select 'Date range'
- And also user can't Clear or Save Filters; those buttons are also hidden

Expected Result(s)
-----------------------------------------------------------------
- User must able to scroll up and select the 'Date range'

Environment
-----------------------------------------------------------------
- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Browser(s):** Chrome

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment]
![7](https://user-images.githubusercontent.com/4592712/29768822-601690ce-8c05-11e7-8651-9269445c7c81.png)

**Comment by birdofpreyru** [comment]
Accepted, 3 points
