### ISSUE TITLE
More option in video sharing is not working properly

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3820]
**Describe the bug**
The "More" option for sharing  any video article opened from Thrive page does not give more options for sharing instead it opens the video on Youtube

**Target URL**: https://www.topcoder.com/thrive
**Steps to reproduce:**
1. Go to 'https://www.topcoder.com/thrive'
2. Go to QA track > Click on "QA & IT'S FUTURE AT TOPCODER"
3. Scroll down to the video part 
4. Click on Share 
5. Click on three dots for more option
6. Observe the behavior 

**Expected behavior**
More option should give more options like Gmail, Pinterest where the video can be shared
**Actual Behaviour**
When the user clicks on the "More" option under the "Share" option it starts to play the video article on youtube in another window

**Environment:** Micromax LI351568W 15.6 ; Windows 10x64
**Browser:** Google Chrome Version 80.0.3987.87

![Bug003](https://user-images.githubusercontent.com/46349625/74007622-c5c97580-49a4-11ea-923f-4e4ebec79d97.jpg)

**Comment by kalindipandey** [comment]
Bug Label: `Functional`

**Comment by winterflame** [comment]
out of scope.
