### ISSUE TITLE
Show Filter > Tabbed area were not highlighted in the UI

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3821]
URL
https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Copilot&author=All%20authors&tags[0]=Copilot&startDate=2020-01-07T12%3A25%3A13%2B05%3A30&endDate=2020-02-07T12%3A25%3A13%2B05%3A30

To Reproduce

1.Visit the above URl
2.Click on show filter.
3. Tab keys and observe.
4. Tabbed area in the UI is not getting highlighted

Expected behavior

Tabbed area should get highlighted to the user in the application

Actual Result: Tabbed area were not highlighted.

Screenshots

Screenshot attached

[Issue9.zip](https://github.com/topcoder-platform/community-app/files/4169391/Issue9.zip)

Desktop (please complete the following information):

OS: Windows
Browser : Firefox
Version: 72.0.2 (64-bit)

**Comment by winterflame** [comment]
not a bug
