### ISSUE TITLE
Image overlap with the background due to improper padding(UI)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3822]
**Target URL:** https://www.topcoder.com/start-writing-es6-javascript-in-your-node-js-apps-today/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/start-writing-es6-javascript-in-your-node-js-apps-today/

Observe the image on the article details

Actual: The image is overlapped at the top and at the bottom by the backgruound color.

Expected: The image should not overlap with the background color. THe image should appear alone
![image](https://user-images.githubusercontent.com/37167721/74008203-51390b80-4991-11ea-96bd-36836a862790.jpg)

Browser: Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
The target URL is out of scope for this challenge.
