### ISSUE TITLE
Show Filter > User were not able to select the author names in the author dropdown.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3823]
*URL
https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Copilot&author=All%20authors&tags[0]=Copilot&startDate=2020-01-07T12%3A25%3A13%2B05%3A30&endDate=2020-02-07T12%3A25%3A13%2B05%3A30

To Reproduce

1.Visit the above URl
2.Click on show filter.
3. Tab keys in the Author dropdown and observe.
4. Unable to select author names in the Author dropdown.

Expected behavior

User should be able to select author name via keyboard tabs

Actual Result: User were not able to select author name via keyboard tabs..

Screenshots

Screenshot attached

[Issue10.zip](https://github.com/topcoder-platform/community-app/files/4169411/Issue10.zip)

Desktop (please complete the following information):

OS: Windows
Browser : Firefox
Version: 72.0.2 (64-bit)

**Comment by winterflame** [comment]
not a bug
