### ISSUE TITLE
Underline for the Thrive menu is not below the title when the browser is minimised.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3824]
**Describe the bug**
Underline for the Thrive menu is not below the title when the browser is minimised.

**To Reproduce**

1. Go to ' https://www.topcoder.com/thrive'
2. Minimize the chrome browser by clicking the minimize button near the 'x' button of the browser.
3. Check the Thrive menu in the header section. [UI issue]

**Expected behavior**
The green colour underline under the Thrive should be displayed correctly below the Thrive text.

**Screenshots**

![image](https://user-images.githubusercontent.com/55895538/74008468-edb9d880-49a6-11ea-9181-76eb7cbdb03b.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 home single language, 64 bit 
 - Browser : Chrome
 - Version : 79.0.3945.130

**Comment by kkartunov** [comment]
This is not a Thrive bug it is a navigation module issue. Changing labels...
@SathyaJayabal can you confirm?

**Comment by sandhiyakavi** [comment]
Closing the issue as it is displaying correctly now.

![image](https://user-images.githubusercontent.com/55895538/107481857-33187380-6bc2-11eb-88a6-b8accf6a91d5.png)
