### ISSUE TITLE
articles_opening > All Articles should open in new tab always for consistency

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3825]
URL
https://www.topcoder.com/thrive/

To Reproduce

1.Visit the above URl
2.Tap the articles.
3. Some articles get opened in new tab and other were not.

Expected behavior

Articles should get opened in new tab for consistency.

Actual Result: Articles were not opened in new tab for consistency.

Screenshots

Screenshot attached

[Issue11.zip](https://github.com/topcoder-platform/community-app/files/4169435/Issue11.zip)

Desktop (please complete the following information):

OS: Windows
Browser : Firefox
Version: 72.0.2 (64-bit)

**Comment by winterflame** [comment]
duplicated #3810
