### ISSUE TITLE
Previously entered data is not getting reset in Share screen page 

### ISSUE THREAD

**Issue by apatra16** [topcoder-platform/community-app#3826]
**Describe the bug**
Previously entered data is not getting reset in Share screen page 

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/search?tags[0]=Algorithm
2. Click on the link "KING OF THE SILICON HILL: TODAY'S HIGH-END MICROPROCESSORS"
3. Hover on the "+ icon" and click on More
4. Search for a service, say Beat100
5. Click on "X" icon and close the Share screen page
![Previously entered data is not getting reset on closing the Share pag](https://user-images.githubusercontent.com/36477026/74008571-34a7ce00-49a7-11ea-9122-a2d2f770a3eb.png)
.
6. Again hover on the "+ icon" and click on More
![Previously entered data is not getting reset on closing the Share pag](https://user-images.githubusercontent.com/36477026/74008612-4c7f5200-49a7-11ea-922e-4eedaef8ddc5.png)

**Expected behavior**
data entered previously should have got reset on closing the Share page.

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 79.0.3945.130

**Comment by kkartunov** [comment]
No more share like this used.
