### ISSUE TITLE
Like/Dislike button is not functional

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/community-app#3827]
Description:
Like/Dislike icons/buttons are not working on the articles.

Target URL: https://www.topcoder.com/thrive/articles/Blockchain%20for%20Beginners:%20What%20You%20Need%20to%20Know

**To Reproduce**
1. Go to https://www.topcoder.com/thrive -> Development 
2. Click on 1st article -> Block Chain for Beginners
3. Scroll down to the bottom of the page.
4. Try to click on like/dislike buttons. Nothing will happen. Only blue color outline will appear & disappear.

Expected Result:
User should be able to like/dislike the article

Actual Result:
Like/dislike button is not functional.

Screenshot:
![image](https://user-images.githubusercontent.com/12671119/74008614-4ee1ac00-49a7-11ea-95b5-25f178ffc442.png)

OS/Browser Information:
 - OS: Windows 10
 - Browser : Google Chrome
 - Version : Version 80.0.3987.87 (Official Build) (64-bit)

Bug Label: Functional

Similar Issue reported:
https://github.com/topcoder-platform/community-app/issues/3667 (Chrome)
https://github.com/topcoder-platform/community-app/issues/3658 (Firefox)
https://github.com/topcoder-platform/community-app/issues/3654 (Chrome)

**Comment by winterflame** [comment]
duplicated
