### ISSUE TITLE
More button is also a part of share options

### ISSUE THREAD

**Issue by InfinityToP** [topcoder-platform/community-app#3829]
**Describe the bug**
More button having "Addthis" tooltip is also a part of the more share options. Clicking on which returns to the same page.
https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder

 

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/QA%20&%20It's%20Future%20At%20Topcoder
2. Scroll down to find 'share options' towards the left
2. Click on '+'
4. Scroll down to the M alphabet options to find "More..." option as well included.
5. Click on it.

 

**Expected behavior**
The "More..." icon button should not be a part of the list.

 

**Screenshots**
![image](https://user-images.githubusercontent.com/32297688/74008985-46d63c00-49a8-11ea-940a-c2a8048113e8.png)

 

**Desktop:**
 - OS: windows 10
 - Browser: chrome
 - Version: 79.0.3945

**Comment by kkartunov** [comment]
This is no more.
