### ISSUE TITLE
[$10] - [Mobile] Join button overlapping on Menu.

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#383]
1.access to http://community-app.topcoder.com/challenges/ **in Mobile**
2.Observe UI

Actual Result(s)
Join button is overlapping on Menu.

Expected Result(s)
Menu should be clearly visible.

Device(s): Sony Xpera E3
Operating System: Android 4.4.4
Browser(s): Chrome

![overlappingbutton](https://user-images.githubusercontent.com/24410217/29768953-c6ee9ce2-8c05-11e7-99c1-ce86f5ae5494.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.

Let's wrap these buttons into the next row, when there is not enough space for a single row.
