### ISSUE TITLE
Thrive_Home > Design article link is navigating to dead URL

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3831]
URL
https://www.topcoder.com/thrive/

To Reproduce

1.Visit the above URl
2.Click on the "Three  iconic designs that.." tiles under Design.
3. Its navigating to 404 URL

Expected behavior

It should not get navigate to dead URL

Actual Result: Article is getting navigate to dead URl.
Screenshots

Screenshot attached

[Issue12.zip](https://github.com/topcoder-platform/community-app/files/4169485/Issue12.zip)

Desktop (please complete the following information):

OS: Windows
Browser : Firefox
Version: 72.0.2 (64-bit)

**Comment by winterflame** [comment]
duplicated
