### ISSUE TITLE
'Nothing Found' message is displayed under the articles

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/community-app#3832]
Title: Nothing Found message is displayed under the article

**To Reproduce**
1. Go to ' https://www.topcoder.com/thrive'
2. Click on 'development tab'
3. Click any tab under the heading and see the article.
 
**Actual Behavior**
'Nothing Found' message is displayed
**Expected behavior**
'Nothing Found' message  should not be displayed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser chromw
 - Version 79.0.3945.130
![Nothing found error](https://user-images.githubusercontent.com/60426529/74009891-358e2f00-49aa-11ea-8f56-18653ab6c578.png)

**Comment by winterflame** [comment]
cannot reproduce
