### ISSUE TITLE
The large titles are not displayed fully and no scroll bar if the browser window is minimized.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#3833]
**Describe the bug**
The large titles are not displayed fully if the browser window is minimized.Also the scroll bar is also not available to view the rest of the title.

**To Reproduce**

1. Go to 'https://www.topcoder.com/thrive/tracks?track=QA&tax='
2. Minimize the chrome browser window.
3. Click basic Practices/Instructions/Tricks/Tips sub menu under the QA menu in the right side bar.
4. check the title displayed in the page.

**Expected behavior**
The large titles should also be displayed fully even during minimizing the window.

**Screenshots**

![image](https://user-images.githubusercontent.com/55895538/74010381-5b680380-49ab-11ea-9293-7628d1bfa7bb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 home single language, 64 bit 
 - Browser : Google chrome 
 - Version : 79.0.3945.130

**Smartphone (please complete the following information):**

**Additional context**

**Comment by winterflame** [comment]
not a bug
