### ISSUE TITLE
User is able to set future date in the date filter 

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3834]
User is able to set a future date in the filter option for filtering out articles and no error message comes

**Target URL**: https://www.topcoder.com/thrive

**Steps to reproduce the behavior:**
1. Open the application and log in as a valid-user
2. Go to [https://www.topcoder.com/thrive/tracks?track=Data%20Science]
3. Click on "MACHINE LEARNING TOOLS & LIBRARIES"
4. Click on  Show Filter
5. Set the date from - 7 Feb 2020  To- 13 Feb 2020 
6. Click on Apply Filter

**Expected behavior**
User should not be able to set future dates and there should be an error message for the same if the user tries to set a future date
**Actual behavior**
User is able to set future date in the date filter 

**Environment**: Micromax LI351568W 15.6 ; Windows 10x64
**Browser**: Google Chrome Version 80.0.3987.87

Screenshots

![Screenshot (63)](https://user-images.githubusercontent.com/46349625/74012175-9cfaad80-49af-11ea-8103-31414690d2ef.jpg)

**Comment by winterflame** [comment]
not a bug
