### ISSUE TITLE
Should be a cancel button to Cancel the article creation request.- 

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/community-app#3836]
Should have a cancel or close button to cancel the request if user is not trying to create an article or mistakenly opened it. 

Target URL: https://www.topcoder.com/thrive

Open the application and log in as a valid-user
https://docs.google.com/forms/d/e/1FAIpQLSeWdp--ofWQOAEQq1cKFKIr3fnlMKKjUWCDDDM2T-ZjtWbJcQ/viewform
Go to create an article
Observe - CLose or cancel button is not available.

Environment: Macbook Air - 10.15.2
Browser: Google Chrome Version 80.0.3987.87

Screenshots
![Screen Shot 2020-02-07 at 2 13 13 PM](https://user-images.githubusercontent.com/57220292/74014128-041a6100-49b4-11ea-9751-d636c8f38c19.png)

**Comment by winterflame** [comment]
out of scope
