### ISSUE TITLE
Top Design Videos- the mouse icon does not change to be clickable even though is clickable

### ISSUE THREAD

**Issue by InfinityToP** [topcoder-platform/community-app#3838]
**Describe the bug**
The mouse icon on the videos in "Top Design Videos" does not change to be clickable even though the whole area of the thumbnail is clickable. Only the text area is shown clickable. This seems to confuse the user.

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive/search?tags[0]=Member%20Stories'
2. Scroll down to 'Top Design Videos'
4. Hover over the video thumbnail, observe the mouse icon to not change into a clickable one, 
5. Click
6. The article opens up.

**Expected behavior**
The whole of the video thumbnail placeholder should be shown as clickable when mouse hovers.

**Screenshots**
![image](https://user-images.githubusercontent.com/32297688/74016288-31690e00-49b8-11ea-894d-7bd458d44bb1.png)

![image](https://user-images.githubusercontent.com/32297688/74016331-404fc080-49b8-11ea-8137-3a3e7a41b30c.png)
**Only on the text**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 79.0.3945.130

**Additional context**
UI issue

**Comment by winterflame** [comment]
same as #3837
