### ISSUE TITLE
article image  not shown 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3841]
Target URL: https://www.topcoder.com/thrive/search?phrase=b

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 in search box enter b -->click view  all result 
3 .see Debugging for Marathon Competitions   -->article image 

### Expected Result ###

should show article image or default image 

### Actual Result ###

image missing 

### Screenshots or screencast ###
![bandicam 2020-02-07 15-12-39-044](https://user-images.githubusercontent.com/3225433/74018851-a4748380-49bc-11ea-98e1-508528a33d83.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
not a bug, some article has no images.
