### ISSUE TITLE
Header indication not similar in both browser

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3842]
**Target URL:**  https://www.topcoder.com/thrive

**To Reproduce**
1. Go to topcoder thrive page 
2.  Open in firefox so Thrive indicates it part of the community but Chrome indicate it part of explore

**Actual-**
Header indication is not similar in both browser

**Expected behavior**
Header indication should be similar

**Screenshots**
Firefox- 
![image](https://user-images.githubusercontent.com/23450398/74018991-df76b700-49bc-11ea-966b-f5a8acbd42bf.png)

Chrome-
![image](https://user-images.githubusercontent.com/23450398/74019079-059c5700-49bd-11ea-9115-01496ca080d1.png)

**Desktop:**
 - OS: Lenovo, Windows 10 Home
 - Browser: Firefox-72.0.2, Chrome-80.0.3987.87

**Comment by kkartunov** [comment]
Not related to Thrive. This is the default TC navigation module and it is so as per design.
