### ISSUE TITLE
Inconsistency  button style

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3844]
Target URL: https://www.topcoder.com/thrive/search?phrase=b,https://www.topcoder.com/thrive/
### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 scroll down  to Have an article in mind that you’d like to see on Thrive? 
3.observe click button css 
4 in search box enter b -->click view all result
5.scroll down  to Have an article in mind that you’d like to see on Thrive? 
6. observe click button css 

### Expected Result ###

Should show properly 

### Actual Result ###
button color is not matching 

### Screenshots or screencast ###
![bandicam 2020-02-07 15-18-12-163](https://user-images.githubusercontent.com/3225433/74019548-d1756600-49bd-11ea-8fb3-4cd0bf3e2f0a.jpg)
![bandicam 2020-02-07 15-18-39-230](https://user-images.githubusercontent.com/3225433/74019558-d9350a80-49bd-11ea-832d-1ee0f106148d.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by kkartunov** [comment]
Buttons are per design and match expectations.
