### ISSUE TITLE
Wrong Find members icon tooltip

### ISSUE THREAD

**Issue by InfinityToP** [topcoder-platform/community-app#3845]
**Describe the bug**
Wrong "Find Members by username or skill" search icon tooltip

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive'
2. Hover over the 'Magnifying glass' icon top right.

**Expected behavior**
Right tooltip seen

**Screenshots**
![image](https://user-images.githubusercontent.com/32297688/74019672-04b7f500-49be-11ea-9156-16b6a3d94458.png)

**Desktop (please complete the following information):**
OS: Windows
Browser: chrome
Version: 79.0.3945.130

**Additional context**
UX Issue

**Comment by kkartunov** [comment]
No present anymore.
