### ISSUE TITLE
unable to navigate Thrive home page from article page 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3847]
Target URL: https://www.topcoder.com/thrive/articles/Markov%20Model

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 In Data Science click Markov Model article
3. In menu click  Thrive 

### Expected Result ###

Should goto Thrive  home page 

### Actual Result ###

nothing happend 

### Screenshots or screencast ###

![bandicam 2020-02-07 15-42-03-101](https://user-images.githubusercontent.com/3225433/74020852-6bd6a900-49c0-11ea-9f9b-135ff6e0d190.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
duplicated
