### ISSUE TITLE
like and dislike button   should redirect into login page for non loged in users

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3848]
Target URL: https://www.topcoder.com/thrive/articles/Markov%20Model

### Reproduction Steps ###
[pre req :Non logged in ]
1 goto https://www.topcoder.com/thrive/
2 In Data Science click Markov Model article
3. click like and dislike button  

### Expected Result ###
user should redirect into sign up or login page 

### Actual Result ###
nothing happened 

### Screenshots or screencast ###

[bandicam 2020-02-07 15-47-08-014.zip](https://github.com/topcoder-platform/community-app/files/4170177/bandicam.2020-02-07.15-47-08-014.zip)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
Related to #3654

**Comment by kkartunov** [comment]
Like and dis buttons should be working for anonymous users too.
