### ISSUE TITLE
[Mobile] Inconsistancy in UI for the Count displayed for Challenges (Improper Allignment)

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#385]
1.Open the URL

2.Login as a valid user (Portraot Mode)

3.Go to http://community-app.topcoder.com/challenges

4. Observe UI. All Chalenges count & other count displayed are not inconsistant

Actual Result(s)
Inconsistancy in UI fot the Count displayed for Challenges

Expected Result(s)
Consistant UI for all Counts displayed (Proper Alignment)

Device(s): Sony Xpera E3
Operating System: Android 4.4.4
Browser(s): Chrome

![countinconsistancy](https://user-images.githubusercontent.com/24410217/29769199-e93ff9e8-8c06-11e7-8275-a3ac94c9260e.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
Not openning for pickup yet, as it might be fixed in another related issue.
