### ISSUE TITLE
share option padding is differ for logged in and non logged in page 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3850]
Target URL: https://www.topcoder.com/thrive/articles/Markov%20Model

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 In Data Science click Markov Model article
3. observe share option 

[pre req :Non logged in ]
1 goto https://www.topcoder.com/thrive/
2 In Data Science click Markov Model article
3. observe share option 

### Expected Result ###
should show both pages properly 

### Actual Result ###
share option padding is differ for logged in and non logged in page 

### Screenshots or screencast ###

![bandicam 2020-02-07 15-47-35-999](https://user-images.githubusercontent.com/3225433/74021700-05528a80-49c2-11ea-92ca-78594befc0b5.jpg)
![bandicam 2020-02-07 15-54-28-123](https://user-images.githubusercontent.com/3225433/74021764-2a46fd80-49c2-11ea-98e7-91c875ff1e3b.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by kkartunov** [comment]
That share is no more.
