### ISSUE TITLE
Tab key is not working to navigate to other links or subcategories

### ISSUE THREAD

**Issue by apatra16** [topcoder-platform/community-app#3851]
**Describe the bug**
Tab key is not working to navigate to other links or subcategories

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/trackstrack=Competitive%20Programming&tax=Recursion
2. Tap on Tab key to navigate to other links.

**Expected behavior**
User should be able to navigate to other links.

Actual behavior:
Tab function is not working

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version : 79.0.3945.130 

![tab function is not working](https://user-images.githubusercontent.com/36477026/74021772-2e731b00-49c2-11ea-93c8-cc63289d324c.png)

**Comment by winterflame** [comment]
out of scope
