### ISSUE TITLE
Thrive external source bug fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3852]
1. When the user searches an article on THRIVE and clicks on the details, if the article is on an external source(for instance the blog), the THRIVE content details is currently showing the page but should redirect to the link of the external article.

To reproduce type: "USING MEANINGFUL TYPOGRAPHY" in search bar in Thrive and click the result. Should be the blog article, not the articles detail page.

2. Hitting the article details page directly, in this case, should also redirect to external source link.
Example: https://www.topcoder.com/thrive/articles/Using%20Meaningful%20Typography%20in%20Your%20Design should redirect to https://www.topcoder.com/using-meaningful-typography-design/

**Comment by SathyaJayabal** [comment]
1. clicking on article in search results does not open the article
2. clicking on "view all results" does not open the search results"
see attached video for reference
[thrive search.mov.zip](https://github.com/topcoder-platform/community-app/files/4185041/thrive.search.mov.zip)

3. Accessing the article by its link throws a file not found error
https://www.beta-community-app-topcoder.com/thrive/articles/Using%20Meaningful%20Typography%20in%20Your%20Design

<img width="1406" alt="Screenshot 2020-02-11 at 3 35 02 PM" src="https://user-images.githubusercontent.com/58783823/74227270-1e21af80-4ce4-11ea-99ef-ff5bc2d86c7c.png">

**Comment by SathyaJayabal** [comment]
@kkartunov , #3 is working. 
The correct URL is https://beta-community-app.topcoder.com/thrive/articles/Using%20Meaningful%20Typography%20in%20Your%20Design

**Comment by kkartunov** [comment]
@SathyaJayabal 1&2 are not in scope. For 3.your test url is wrong. Please, correct it and retry.

**Comment by SathyaJayabal** [comment]
@kkartunov ,  this is the bug description
When the user searches an article on THRIVE and clicks on the details, if the article is on an external source(for instance the blog), the THRIVE content details is currently showing the page but should redirect to the link of the external article.

How can #1 be out of scope ? Clicking on the details when you search on thrive does not work.

Let me know  if I have misunderstood the bug.

**Comment by kkartunov** [comment]
@SathyaJayabal can you please verify 1.&2. again? It is all working for me in beta. See this video https://drive.google.com/file/d/17jkLoNdMdEAgfXEcBC7TfHgoOYJmp6ut/view

**Comment by SathyaJayabal** [comment]
@kkartunov , I am still getting the same issue.

@nithyaasworld @lakshmiathreya , can you please verify the above scenario?

**Comment by SathyaJayabal** [comment]
@kkartunov , I am marking this as QA pass with the video you have submitted.

**Comment by SathyaJayabal** [comment]
Verified on Beta (develop branch)

**Comment by SathyaJayabal** [comment]
verified in production
[thrive search prod.mov.zip](https://github.com/topcoder-platform/community-app/files/4192170/thrive.search.prod.mov.zip)
