### ISSUE TITLE
Some articals not belongs to the thrive

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3853]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Development&tax=Mobile%20App%20Development

**To Reproduce**
1. Go to topcoder thrive page 
2.  Go to development > Mobile app development
3.  Tap on some article so some are the part of thrive and some are not

**Actual-**
Not all the articals part of the thrive

**Expected behavior**
Articles should be sub part of the thrive which is existing 

**Screenshots**
https://drive.google.com/open?id=1t_P2L1-Ff9LyOc3_Y-s1g2PFOOgva7uD

**Desktop:**
 - OS: Lenovo, Windows 10 Home
 - Browser: Firefox
 - Version: 72.0.2

**Comment by winterflame** [comment]
not a bug
