### ISSUE TITLE
General_Performance > Page loading time of thrive is more than 5 sec

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3854]
Page loading time of thrive is taking more than 5 sec

Target URL: https://www.topcoder.com/thrive/

Open the application
1.  Observe the page loading time
2. Page loading time is more when compared to other pages.

Expected behavior

Page loading time of thrive should be less than 5 sec compared to other apps.

Actual behavior

Page loading time is more than 5 sec.

Environment: Windows 10x64
Browser: FF Version 72.0.2 (64-bit

Screenshots

[Issue13.zip](https://github.com/topcoder-platform/community-app/files/4170276/Issue13.zip)

**Comment by winterflame** [comment]
not a bug, it depends on network speed.
