### ISSUE TITLE
should show related Article  section 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3856]
Target URL: https://www.topcoder.com/thrive/articles/Markov%20Model

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 In Data Science click Markov Model article
3. scroll down to end of the article 

### Expected Result ###

should show related article 

### Actual Result ###
related Article section  missing 

### Screenshots or screencast ###

![bandicam 2020-02-07 16-13-41-103](https://user-images.githubusercontent.com/3225433/74023103-dbe72e00-49c4-11ea-8ade-97f30affd996.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
not a bug
