### ISSUE TITLE
Cursor when hovered on upvote or downvote icon  below an video article shows random text

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3857]
The user when hovers the cursor over the upvote and downvote icon "group 9 " text which is invalid is shown
**Target URL**: https://www.topcoder.com/thrive

**Steps to reproduce the behavior:**

1. Open the application and log in as a valid-user
2. Goto[https://www.topcoder.com/thrive/articles/How%20to%20create%20a%20LUX%20RUX%20presentation%20for%20Topcoder]
3. Scroll down 
4. Hover on the upvote and downvote icon 
5. Observe
**Expected behavior**
There should not be random and invalid text on hovering on downvote and upvote icon
**Actual behavior**
The user when hovers the cursor over the upvote and downvote icon "group 9 " text which is invalid is shown
**Environment**: Micromax LI351568W 15.6 ; Windows 10x64
**Browser**: Google Chrome Version 80.0.3987.87

**Screencast**

http://somup.com/cYni6Gh66F

**Comment by kalindipandey** [comment]
**BugLabel**: `UI`

**Comment by winterflame** [comment]
duplicated
