### ISSUE TITLE
Some articles tags out of the section

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3859]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Development&tax=Topcoder-Centric

**To Reproduce**
1. Go to topcoder thrive page 
2. Tap on Development > Topcoder-Centric
3.  Scroll down and observe the articles tag out of the section

**Actual-**
Some tags out of the section

**Expected behavior**
Tags should  with in the section

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74023808-8744b280-49c6-11ea-9414-fd697695a7a1.png)

**Desktop:**
 - OS: Lenovo, Windows 10 Home
 - Browser: Firefox
 - Version: 72.0.2

**Comment by kkartunov** [comment]
Fixed
