### ISSUE TITLE
Calendar range filter is not working properly

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/community-app#3861]
Description:
Articles which are not from selected date range also appear in the filtered result.

Target URL: https://www.topcoder.com/thrive/search?tags[0]=Insight

Reproduction Steps:
1. Go to https://www.topcoder.com/thrive/search?tags[0]=Insight
2. Don't select any category.
3. Use 'Insight' as filter
4. Authors - All
5. Select Date range as -> Sep 1, 2019 - Feb 7, 2020
6. Click on 'Apply Filter'
7. Notice articles which were posted on dates not within the selected date range are also appearing.

Expected Result:
Articles only posted within given date range should appear in the filtered result

Actual Result:
Articles which were posted on dates not within the selected date range are also appearing as filtered result.

Screenshots:
![image](https://user-images.githubusercontent.com/12671119/74024552-27e7a200-49c8-11ea-8e1d-cc79f1fe6ada.png)

OS/Browser Information:
 - OS: Windows 10
 - Browser : Google Chrome
 - Version : Version 80.0.3987.87 (Official Build) (64-bit)

Bug Label: Functional

**Comment by winterflame** [comment]
duplicated
