### ISSUE TITLE
Browser_Resize > Tags present in the article were not shown properly when it is resized.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3862]
*Target URL: https://www.topcoder.com/thrive/search?tags[0]=Topcoder
To Reproduce

1.Go to topcoder thrive page
2. Navigate to the above URL.
3. Resize the browser window to see the article image.
4. Tags were not displayed properly.

Actual-

Tags were not displayed properly

Expected behavior

Tags should be displayed properly

Screenshots

[Issue15.zip](https://github.com/topcoder-platform/community-app/files/4170433/Issue15.zip)

Desktop:

OS: Windows 10 Home
Browser: Firefox
Version: 72.0.2

**Comment by winterflame** [comment]
duplicated
