### ISSUE TITLE
Articles_No results > UI gets misaligned and text appears in different place compared to articles display

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3863]
**Target URL: https://www.topcoder.com/thrive/search?tags[0]=Topcoder
To Reproduce

1.Go to topcoder thrive page
2. Navigate to the above URL.
3. Click on Videos
4. Nothing found message appears.
5. Look at the Place and UI alignment while it loades.
6. It appears in different place of articles also the UI gets misaligned to its place.

Actual-

UI misaligned and text appears in different place when there are no articles to display

Expected behavior

UI should not misaligned and text should appear in the same place when there are no articles to display.

Screenshots

[Issue16.zip](https://github.com/topcoder-platform/community-app/files/4170477/Issue16.zip)

Desktop:

OS: Windows 10 Home
Browser: Firefox
Version: 72.0.2

**Comment by winterflame** [comment]
duplicated #3783
