### ISSUE TITLE
Articles_Filter > Suggest to display Reset filters to make user experience easier manner

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3864]
***Target URL: https://www.topcoder.com/thrive/search?tags[0]=Structured%20Test%20Case%20Writing&tags[1]=topcoder&author=All%20authors&startDate=2001-01-01T12%3A00%3A00Z&endDate=2020-02-07T16%3A52%3A41%2B05%3A30&track=&tax=

To Reproduce

1.Go to topcoder thrive page
2. Navigate to the above URL.
3. Observe the filters on left panel.
4. Apply filters and Click Apply filter.
5. No option to reset the filters
6. User need to manually edit the filters entered to get the desired results.

Actual-
User need to manually edit the filters to get the desired results

Expected behavior

Suggested to place reset filters in the Filter panel column.

Screenshots

[Issue17.zip](https://github.com/topcoder-platform/community-app/files/4170501/Issue17.zip)

Desktop:

OS: Windows 10 Home
Browser: Firefox
Version: 72.0.2

**Comment by winterflame** [comment]
duplicated
