### ISSUE TITLE
References articles link also incorrect

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3868]
**Target URL:**  https://www.topcoder.com/thrive/articles/King%20of%20the%20Silicon%20Hill:%20Today's%20High-End%20Microprocessors

**To Reproduce**
1. Go to topcoder thrive page 
2.  Tap "Hardware" in Data science section 
3.  Tap on the article presents "King of the Silicon Hill: Today's High-End Microprocessors"
4.  Observe the Reference articles 

**Actual-**
All reference articles incorrect link

**Expected behavior**
 Each articles link should be correct 

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74026625-97f82700-49cc-11ea-8f39-b539d6c9aeaf.png)

**Desktop:**
 - OS: Lenovo, Windows 10 Home
 - Browser: Firefox
 - Version: 72.0.2

**Comment by winterflame** [comment]
duplicated
