### ISSUE TITLE
Social buttons are not working on an article page

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3869]
**Target URL**

https://www.topcoder.com/thrive/articles/Marathon%20Matches:%20Retro-Visualizers

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Please click on any social icon on the left.

**Expected Result**

1. Social icons should work.

**Actual Result**

1. Social icons do not work.

**Screenshots or screencast**

![Topcoder](https://user-images.githubusercontent.com/3612991/74027922-2b325c00-49cf-11ea-83ce-0a04edf270e5.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by kkartunov** [comment]
Those buttons are no more.
