### ISSUE TITLE
[Mobile] On Filters Popup Alignment Of Label,Button is not Proper.

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#387]
1.Open the URL

2.Login as a valid user 

3.Go to http://community-app.topcoder.com/challenges in mobile

4.Click on Filters. Observe Popup UI

Actual Result(s)
Alignment Of Label,Button is not Proper.
Sub Community input field Text,close sign,Expand Arrow overlapping.

Device(s): Sony Xpera E3
Operating System: Android 4.4.4
Browser(s): Chrome
![filterui](https://user-images.githubusercontent.com/24410217/29769885-e7527bd0-8c09-11e7-8d60-154fc38f6562.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 1 point.
Not opening, as I have already noted it before and asked to fix in another issue related to this panel
