### ISSUE TITLE
video link redirected to external site[ youtube] 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3870]
Target URL: https://www.topcoder.com/thrive/tracks?track=Data%20Science

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 click Data Science-->video tab 
3.click video 

### Expected Result ###
should redirect to article page 

### Actual Result ###
redirected to youtube site 

### Screenshots or screencast ###
[bandicam 2020-02-07 17-32-53-394.zip](https://github.com/topcoder-platform/community-app/files/4170637/bandicam.2020-02-07.17-32-53-394.zip)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
duplicated
