### ISSUE TITLE
The copyright label is not aligned with the social media icon strip in the footer

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3871]
**Target URL**

https://www.topcoder.com/thrive/articles/Write%20Problems%20for%20Topcoder

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Please observe the alignment of the social media icon strip relative to the copyright label in the footer.

**Expected Result**

1. There should not be an alignment issue.

**Actual Result**

1. There is an alignment issue. 

**Screenshots or screencast**

![Topcoder (2)](https://user-images.githubusercontent.com/3612991/74028622-d0016900-49d0-11ea-9999-4a266550ebdb.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by kkartunov** [comment]
This footer is no more.
