### ISSUE TITLE
The green short underline decoration does not move when the browser window is resized

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3873]
**Target URL**

https://www.topcoder.com/thrive

**Reproduction Steps**

1. Please open the target url mentioned above with browser window size 1024x576, you can use the [window resizer](https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh) chrome extension for this purpose.
2. Observe the green short underline decoration under "Thrive".
3. Now, maximize or press f11 to go full screen.
4. Observe the decoration again.

**Expected Result**

1. The decoration should be aligned with "Thrive" in all window sizes.

**Actual Result**

1. The decoration does not remain aligned with "Thrive" when the window is maximized or the user goes fullscreen from window size 1024x576.

**Screenshots or screencast**

![Topcoder (3)](https://user-images.githubusercontent.com/3612991/74029411-aa755f00-49d2-11ea-82b7-7aa4e93a6fd5.png)
![Topcoder (4)](https://user-images.githubusercontent.com/3612991/74029420-ad704f80-49d2-11ea-8c32-f2fbda1c1f70.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
duplicated
