### ISSUE TITLE
View box drop downs do not close

### ISSUE THREAD

**Issue by InfinityToP** [topcoder-platform/community-app#3874]
**Describe the bug**
View box drop down does not close. No close functionality is enabled.

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive/tracks?track=Topcoder&tax='
2. Try clicking on the arrow beside 'Topcoder'

**Expected behavior**
The drop down should be reduced.

**Actual behavior**
Nothing happens, it does not close.

**Screenshots**
![image](https://user-images.githubusercontent.com/32297688/74029563-f922f900-49d2-11ea-8a4f-e261a1e2b6ef.png)

**Desktop (please complete the following information):**
OS: Windows
Browser: chrome
Version: 79.0.3945.130

**Additional context**
UI Issue

**Comment by winterflame** [comment]
by design
