### ISSUE TITLE
should show divider at end of the article 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#3875]
Target URL: https://www.topcoder.com/thrive/articles/Markov%20Model

### Reproduction Steps ###

1 goto https://www.topcoder.com/thrive/
2 In Data Science click Markov Model article
3. scroll down to end of the article

### Expected Result ###
should show divider  

### Actual Result ###

divider is missing 

### Screenshots or screencast ###
![bandicam 2020-02-07 17-56-47-186](https://user-images.githubusercontent.com/3225433/74029694-3f785800-49d3-11ea-922f-2a50f6ce476e.jpg)

### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by winterflame** [comment]
not a bug
