### ISSUE TITLE
Cursor does not change to pointer

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3878]
**Target URL**

https://www.topcoder.com/thrive/search?tags[0]=Tips

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Observe that, under articles tab, inside the grey box of an article, where there is no text, if you click anywhere, the article opens in a new tab. Observe the cursor before you click.

**Expected Result**

1. The cursor should be a pointer as it is a link area.

**Actual Result**

1. The cursor remains default.

**Screenshots or screencast**

![Topcoder (6)](https://user-images.githubusercontent.com/3612991/74030604-77809a80-49d5-11ea-89e5-cd8c54270b85.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
duplicated with #3838
