### ISSUE TITLE
[$20] - Inconsistency in Tooltip UI for Delete Filter

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#388]
1.Open the URL

2.Login as a valid user 

3.Go to http://community-app.topcoder.com/challenges

4.Click on Edit link in front of My Filters.

5.Hover over "X" button next to any filter. Observe tooltip

Actual Result(s)
Everywhere tooltip background is black with white text. Delete Filter Tooltip background is not black. 
Inconsistency.

Device(s): Desktop
Operating System: Windows 7
Browser(s): Chrome

![tooltip](https://user-images.githubusercontent.com/24410217/29770235-a25893a0-8c0b-11e7-92a4-d9077553980d.jpg)
![tooltip_inconsistant](https://user-images.githubusercontent.com/24410217/29770236-a25e9c78-8c0b-11e7-91bc-62cd62749671.jpg)

**Comment by birdofpreyru** [comment]
Accepted, 3 points
