### ISSUE TITLE
'TOP DESIGN VIDEOS' section is not aligned properly

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3881]
![image](https://user-images.githubusercontent.com/42398485/74031037-21303f00-4976-11ea-9764-48b5513cd6d4.png)

**Target URL:** https://www.topcoder.com/thrive/search?tags[0]=AI

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?tags[0]=AI
3. Scroll down and check 'TOP DESIGN VIDEOS' section

**Actual:** 'TOP DESIGN VIDEOS' section is not aligned properly

**Expected:** Should have the same padding from the left and right

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
duplicated
