### ISSUE TITLE
[Web-Firefox] In Between Math & Graph Theory (,) Sign Should Not Be There

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3885]
URL: https://www.topcoder.com/thrive

**Describe the bug**
While Math & Graph Theory Opening In One Tab There Should Be No (,) Sign In Between
**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse To Competitive Programming

3. Click on Math

4. See Screencast & Screenshot Then Observe

**Expected behavior**
In Between Math & Graph Theory (,) Sign Should Not Be There

**Actual Behaviour**
There Is (,) Sign In Between Math & Graph Theory

**Screenshot & Screencast**
![In Between Math   Graph Theory](https://user-images.githubusercontent.com/42583358/74034548-8455bc00-49de-11ea-9bcc-10557673ca8e.png)

[In Between Math & Graph Theoty.mp4.zip](https://github.com/topcoder-platform/community-app/files/4171067/In.Between.Math.Graph.Theoty.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74034718-da2a6400-49de-11ea-8226-bfbcc1f31153.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74034744-e8788000-49de-11ea-830d-cf6a17abeaa6.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment]
same as #3887
