### ISSUE TITLE
Some video icons are not displayed properly in white related background

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3886]
![image](https://user-images.githubusercontent.com/42398485/74034865-c18a6180-497e-11ea-88f8-cbc5ae0fc4be.png)

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Topcoder-Centric

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Topcoder-Centric
3. GO to 'TOP DESIGN VIDEOS'
4. Check 3rd video

**Actual:** Some video icons are not displayed properly in white related background

**Expected:** Should have an overlay in between the icon and the image

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
duplicated
