### ISSUE TITLE
[Common] In some articles; tags on the card is totally different from the tags inside

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3888]
![image](https://user-images.githubusercontent.com/42398485/74036277-8e959d00-4981-11ea-9b3c-138c22f15117.png)

![image](https://user-images.githubusercontent.com/42398485/74036289-93f2e780-4981-11ea-9f15-02f13d270e20.png)

**Target URL:** https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2010-01-01T06%3A00%3A00-06%3A00&endDate=2020-02-07T07%3A57%3A34-06%3A00&track=Development&tags[0]=HTML%2FCSS%2FJavascript&tax[0]=Tools&tax[1]=First2Finish&tax[2]=Topcoder-Centric

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2010-01-01T06%3A00%3A00-06%3A00&endDate=2020-02-07T07%3A57%3A34-06%3A00&track=Development&tags[0]=HTML%2FCSS%2FJavascript&tax[0]=Tools&tax[1]=First2Finish&tax[2]=Topcoder-Centric
3. Check the tags
4. Click on the articles
5. Check the tags

**Actual:** In some articles; tags on the card is totally different from the tags inside

**Expected:** Should be the same. Either the card should display the correct tags on the article

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by kkartunov** [comment]
If the article is external, like this the case here, tags could be different.
