### ISSUE TITLE
[Common] Can enter same tag again and again

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3889]
![image](https://user-images.githubusercontent.com/42398485/74036731-6f4b3f80-4982-11ea-8117-9432bdb96eef.png)

**Target URL:** https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2010-01-01T06%3A00%3A00-06%3A00&endDate=2020-02-07T07%3A57%3A34-06%3A00&track=Development&tags[0]=Angular%2FAngularJS&tags[1]=Front-end&tags[2]=Front-end

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2010-01-01T06%3A00%3A00-06%3A00&endDate=2020-02-07T07%3A57%3A34-06%3A00&track=Development
3. Go to Tags and enter 'Front-end' > Press ENTER key
4. Go to Tags and enter 'Front-end' > Click Apply Filter

**Actual:** Can enter same tag again and again

**Expected:** Should not display duplicate tags, if the tag is duplicate should oberwrite the current one/ or just ignore

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
#3811
