### ISSUE TITLE
When many filters are added. My Filters Section overlaps on footer at the bottom.

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#389]
1.Open the URL

2.Login as a valid user 

3.Go to http://community-app.topcoder.com/challenges

4.Scroll Down at the bottom. Observe My Filters Overlapping on Footer (when too many filters are added)

Actual Result(s)
when many filters are added. My Filters Section overlaps on footer at the bottom.

Device(s): Desktop
Operating System: Windows 7
Browser(s): Chrome

![filter_overlapping_footer](https://user-images.githubusercontent.com/24410217/29770479-f2bcb064-8c0c-11e7-8b7e-8b9850f72f92.jpg)

**Comment by birdofpreyru** [comment]
Dublicates #198
