### ISSUE TITLE
[Web-Firefox] Date Picker Should Be Accessible

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3890]
URL: https://www.topcoder.com/thrive

**Describe the bug**
While Clicking On Date Picker, Its Not Accessing

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse To Competitive Programming

3. Click On SRM Editorials

4. Click On Show Filter

5. Try To Click On Date Picker 

6. Then See Screencast & Observe

**Expected behavior**
Date Picker Should Be Accessible

**Actual Behaviour**
Date Picker Is Not Accessing

**Screencast**
[Date Picker.mp4.zip](https://github.com/topcoder-platform/community-app/files/4171195/Date.Picker.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74036835-0c3dc500-49e3-11ea-8b7a-27e7267bdda1.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74036864-18298700-49e3-11ea-8eb6-eb88f9f3c09b.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
Not a bug, user should click on the date to open the date picker.
