### ISSUE TITLE
[Common] Some articles don't have descriptions on the cards

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3895]
![image](https://user-images.githubusercontent.com/42398485/74038553-0c5ba780-4986-11ea-9f91-9fb82e2d30ec.png)
![image](https://user-images.githubusercontent.com/42398485/74038567-1382b580-4986-11ea-8a60-93b85d4c9c17.png)

**Target URL:** https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2010-01-01T06%3A00%3A00-06%3A00&endDate=2020-02-07T07%3A57%3A34-06%3A00&track=Development&tags[0]=Back-end

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2010-01-01T06%3A00%3A00-06%3A00&endDate=2020-02-07T07%3A57%3A34-06%3A00&track=Development&tags[0]=Back-end
3. Check article descriptions

**Actual:** Some articles don't have descriptions on the cards

**Expected:** Should display the descriptions to be consistant

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
not a bug
