### ISSUE TITLE
[Web-Firefox] While Pressing Delete Key After Selecting Filter Its Going To Back Page

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3896]
URL: https://www.topcoder.com/thrive

**Describe the bug**
After Selecting Filter & Pressing Delete Button Its Going To Back Page
**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse To Topcoder

3. Select Copilot

4. Scroll Down Mouse To Copilot

5. Click On Copilot

6. Select Filter Then Press Delete Key & See.

7. See Screencast & Observe

**Expected behavior**
While Pressing Delete Key After Selecting Filter It Should Not  Go To Back Page

** Actual Result**
While Pressing Delete Key After Selecting Filter Its Going To Back Page

**Screencast**
[Filter.mp4.zip](https://github.com/topcoder-platform/community-app/files/4171411/Filter.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74040515-dfd97700-49e9-11ea-90c0-724f0b51c4fa.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74040557-f089ed00-49e9-11ea-95e4-5158057e267f.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
It's browser's feature.
