### ISSUE TITLE
Better to introduce a 'Select All' option for Sub category section

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3897]
![image](https://user-images.githubusercontent.com/42398485/74040919-4af36100-498a-11ea-8fe5-38b31efd8fed.png)

**Target URL:** https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2000-01-01T12%3A00%3A00Z&endDate=2020-02-07T08%3A31%3A35-06%3A00&track=Design

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2000-01-01T12%3A00%3A00Z&endDate=2020-02-07T08%3A31%3A35-06%3A00&track=Design
3. Select Category=Design
4. Expand the Sub Category
5. Select all the options

**Actual:** No way to quickly select all the options

**Expected:** Better to introduce a 'Select All' option for Sub categoty section, that way user can save time if he/she wants to filter the data from 3/4 of the sub categories. Like Select All and then deselect unwanted categories.

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
#3701
