### ISSUE TITLE
[Web-Firefox] While Clicking On Marathon Again Clicking On Back Button Its Going Back To QA Help Center

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3898]
URL: https://www.topcoder.com/thrive

**Describe the bug**
While Clicking Data Science > Clicking Help Center > Clicking Marathon & Clicking On Back Button Its Automatically Going To QA Help Center

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse To Topcoder

3. Select Copilot

4. Select Data Science > Select Help Center

5. Click On Marathon Then Click Back Button & Observe

6. See Screencast & Observe

**Expected behavior**
It Should Go To Data Science Help Center

**Current Behaviour**
It Going To QA Help Center

**Screenshots**
[Marathon.mp4.zip](https://github.com/topcoder-platform/community-app/files/4171904/Marathon.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74046827-3ef0b900-49f5-11ea-9728-1a7e76c10fea.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74046851-4ca63e80-49f5-11ea-8412-c1146d2e0321.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
Not a bug of the web app.
