### ISSUE TITLE
Filter_author>Filtering by author name in forum posts doesn't show the results highlighted in forum post

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3899]
Target URL: 

https://www.topcoder.com/thrive/search?tags[0]=String%20Parsing

Open the Application and Login as valid user
1. Go to https://www.topcoder.com/thrive/search?tags[0]=String%20Parsing
2. Navigate to Forum posts
3. Click on author name Nickolas
4. Observe the search.
5. The focus is now in the Articles area highlighting the articles.
6. The focus should be in Forum posts showing the Forum posts where author is nickolas.

Expected:  Focus should be expected in Forum posts showing how many forum posts articles where author is nickolas.

Environment: Toshibha Satellite L370 14 inch; Windows 10
Browser: Google Chrome 80.0.3987.87 | FF 72.0.2

[Issue19.zip](https://github.com/topcoder-platform/community-app/files/4171944/Issue19.zip)

**Comment by winterflame** [comment]
not a bug.
