### ISSUE TITLE
When there is no data filled in any field, Clear Filter button should be disabled. 

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#390]
1.Open the URL

2.Login as a valid user 

3.Go to http://community-app.topcoder.com/challenges

4.Click on Filters

 
Actual Result(s)
When there is no data filled in any field, Clear Filter button should be disabled. You Can See in attached Image Clear Filter Button is focused (blue border).
It should be disabled and non focusable

Device(s): Desktop
Operating System: Windows 7
Browser(s): Chrome

![clearfilter_disabled](https://user-images.githubusercontent.com/24410217/29771145-eca03856-8c0f-11e7-9421-24666ba2fe07.jpg)

**Comment by birdofpreyru** [comment]
Ok. Accepted with 3 points, although it is similar to #216 and will be addressed there
