### ISSUE TITLE
[Common] Most of the thrive article contents are not properly formatted

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3901]
![image](https://user-images.githubusercontent.com/42398485/74047842-9e6bac00-4996-11ea-8aca-b2b213ef36d3.png)

**Target URL:** https://www.topcoder.com/thrive/articles/Five%20Books%20Every%20Designer%20Should%20Read

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/articles/Five%20Books%20Every%20Designer%20Should%20Read
3. Check the content

**Actual:** Most of the thrive article contents are not properly formatted

**Expected:** Should have proper consistent paragraph spacing, section spacing, bullet or numbering indentation etc..

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
out of scope
