### ISSUE TITLE
[Web-Firefox] Nothing Is Written About Topic Gradient Boosting Algorithms

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3903]
URL: https://www.topcoder.com/thrive

**Describe the bug**
While Selecting Gradient Boosting Algorithms Nothing Is Written About Topic

**To Reproduce**
1. Go to https://www.topcoder.com/thrive

2. Scroll Down Mouse To Topcoder Then Click On Copilot

3. Click On Data Science Then Select Gradient Boosting Algorithms

4. Then Click On MMSI & Observe

5. See Screencast & Observe

**Expected behavior**
Something Should Be written about Topic Gradient Boosting Algorithms

**Actual Behaviour**
Nothing Is Written About Topic Gradient Boosting Algorithms

**Screenshots**
[Nothing Is Briefing.mp4.zip](https://github.com/topcoder-platform/community-app/files/4171972/Nothing.Is.Briefing.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74047864-0b169300-49f7-11ea-80a1-e870043e2652.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74047882-15d12800-49f7-11ea-9496-d4304e85699c.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
#3686
