### ISSUE TITLE
Articles loaded through show more should be maintained when Back button is pressed.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3906]
Target URL:

https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Help%20Articles
Open the Application and Login as valid user

1.Go to https://www.topcoder.com/thrive/search?tags[0]=String%20Parsing
2. Click on Show More button.
3. Select a article and read
4. Now press back button in the browser.
5. Articles loaded through show more were not retained.

Expected: Articles loaded should be maintained for the convenience of the user

Environment: Toshibha Satellite L370 14 inch; Windows 10
Browser: Google Chrome 80.0.3987.87 | FF 72.0.2

[Issue21.zip](https://github.com/topcoder-platform/community-app/files/4172055/Issue21.zip)

**Comment by winterflame** [comment]
won't fix
