### ISSUE TITLE
[Web-Firefox] Opportunities, Links Collection & Hackathons Are Not Showing Any Details About It.

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3908]
URL: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Topcoder-Centric

**Describe the bug**
While Clicking On Opportunities, Links Collection & Hackathons Are Not Opening Details About Them

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Topcoder-Centric

2. Click on Topcoder Centric

3. Click One By One On Opportunities, Links Collection & Hackathons Then Observe

4. See Screencast

**Expected behavior**
Opportunities, Links Collection & Hackathons Should Show Some Details About.

**Current Behaviour**
Opportunities, Links Collection & Hackathons Are Not Showing Any Details About It.

**Screencast**
[Opportunities.mp4.zip](https://github.com/topcoder-platform/community-app/files/4172137/Opportunities.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74050757-a9f1be00-49fc-11ea-94d7-6ca34264dada.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74050775-b249f900-49fc-11ea-9d90-efeee23ed21a.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
not a bug, clicking on a tag will search by that tag.
