### ISSUE TITLE
[$20] - When user wants to manually change date for Eg. want to change month from 01 to 11. Cursor position is not displayed. User have to try to reach to appropriate position and then edit.

### ISSUE THREAD

**Issue by rrmehta83** [topcoder-platform/community-app#391]
1.Open the URL

2.Login as a valid user

3.Go to http://community-app.topcoder.com/challenges

4.Click on Filters.

5.Enter Date and try to modify date manually.

Actual Result(s)
When user wants to manually change date for Eg. want to change month from 01 to 11. Cursor position is not displayed. User have to try to reach to appropriate position and then edit .

Device(s): Desktop
Operating System: Windows 7
Browser(s): Chrome

**Comment by birdofpreyru** [comment]
Accepted, 3 points
