### ISSUE TITLE
Search output drop-down content has not action

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3910]
**Target URL:**  https://www.topcoder.com/thrive/

**To Reproduce**
1. Go to topcoder thrive page
2. Type 'b' in search and enter
3. Tap on the first content of the search drop-down

**Actual-**
Search drop-down content has no action

**Expected behavior**
Every content link is not working

**Screenshots**
https://drive.google.com/open?id=1kWfX2BOgPv0rLmblv9j1NDeaB_Nhugvw

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Chrome
 - Version: 80.0.3987.87

**Comment by winterflame** [comment]
duplicated with #3708
