### ISSUE TITLE
[Web-Firefox] Van's Hardware Icon Is Showing Error

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3914]
URL: https://www.topcoder.com/thrive/articles/King%20of%20the%20Silicon%20Hill:%20Today's%20High-End%20Microprocessors

**Describe the bug**
While Clicking On Van's Hardware Icon Its Showing Error

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/King%20of%20the%20Silicon%20Hill:%20Today's%20High-End%20Microprocessors

2. Scroll Down Mouse To Van's Hardware

3. Click On Van's Hardware

4. Then See Screencast & Observe

**Expected behavior**
Van's Hardware Icon Should Not Show Any Error.

**Current Behaviour**
Van's Hardware Icon Is Showing Error

**Screencast**
[Van's Hardware.mp4.zip](https://github.com/topcoder-platform/community-app/files/4172343/Van.s.Hardware.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74055347-da8a2580-4a05-11ea-9965-bb49d903bdb2.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74055371-e8d84180-4a05-11ea-9dd7-d06fafb5b8c5.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
duplicated #3865
