### ISSUE TITLE
Some content of the 'IMPROVE DEBUGGING EFFICIENCY WITH LLDB' article is hidden

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3915]
![image](https://user-images.githubusercontent.com/42398485/74056931-83099c80-49a8-11ea-8ca9-e2b0ddc4c681.png)

**Target URL:** https://www.topcoder.com/thrive/articles/Improve%20Debugging%20Efficiency%20with%20LLDB

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/articles/Improve%20Debugging%20Efficiency%20with%20LLDB
3. Check the 3. COMMONLY USED COMMANDS

**Actual:** Some content of the 'IMPROVE DEBUGGING EFFICIENCY WITH LLDB' article is hidden

**Expected:**  Content should be visible

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by winterflame** [comment]
cannot reproduce in 15.4-inch display.
