### ISSUE TITLE
[Web-Firefox] Some Part Of Texts Are Cutting Both Side

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3916]
https://www.topcoder.com/thrive/articles/Problem%20Solving%20-Verifying%20Your%20Own%20Local%20Test%20Runner%20Against%20a%20Supplied%20Visualizer

**Describe the bug**
Some Parts Of text Are Cutting Both Side

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Problem%20Solving%20-Verifying%20Your%20Own%20Local%20Test%20Runner%20Against%20a%20Supplied%20Visualizer

2. See Screenshot & Observe

**Expected behavior**
There Should Be No Cutting On Both Side Texts

**Actual Behaviour**
Some Part Of Texts Are Cutting

**Screenshots**

![Some Part Is Cutting](https://user-images.githubusercontent.com/42583358/74057128-43bf6800-4a09-11ea-8ba6-9f2f218a58f8.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74057171-576ace80-4a09-11ea-884e-74cec1efc00c.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74057189-63569080-4a09-11ea-80b0-7cc0dca2c38d.png)

**Additional context**
UI Issue

**Comment by kkartunov** [comment]
This is a banner image it has to cut and also is blobed now.
