### ISSUE TITLE
Video size not well structured / diagonal size not well displayed

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3923]
**Target URL:** https://www.topcoder.com/how-to-review-feedback-and-then-apply-it-revealed/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/how-to-review-feedback-and-then-apply-it-revealed/

Observe under the article details

**Actual:** The Video size is small and diagonal size is not matching

**Expected:** The Video should have equal height and width to be well displayed

**Browser:
![vid](https://user-images.githubusercontent.com/37167721/74059097-701eb880-49f8-11ea-80f8-cb2d73c862e5.jpg)
** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
URL is out of scope.
