### ISSUE TITLE
Section content image not there

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3924]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

**To Reproduce**
1. Go to topcoder thrive page
2. Go to the section Development > Miscellaneous
3. Load more content and observe

**Actual-**
Content image not there

**Expected behavior**
Content image should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74060430-f72b5b00-4a0f-11ea-8084-aabd23c0df76.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Chrome
 - Version: 80.0.3987.87

**Comment by winterflame** [comment]
not a bug, not every article has an image.
