### ISSUE TITLE
[Web-Firefox] COEDITING Should Be Written Either CO-EDITING Or CO EDITING

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3925]
URL: https://www.topcoder.com/thrive/articles/Why%20UI%20or%20UX%20Designers%20Will%20Fall%20in%20Love%20With%20Adobe%20XD

**Describe the bug**
COEDITING Is Written Wrongly

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Why%20UI%20or%20UX%20Designers%20Will%20Fall%20in%20Love%20With%20Adobe%20XD

2. Scroll Down Mouse To COEDITING Then See & Observe

3. See Screenshot & Observe

**Expected behavior**
COEDITING Should Be Written Either CO-EDITING Or CO EDITING

Actual Behaviour
CO-EDITING Is Written As COEDITING.

**Screenshot**
![Co-Editing](https://user-images.githubusercontent.com/42583358/74060554-3f4a7d80-4a10-11ea-8f53-f42bd3111e33.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74060587-50938a00-4a10-11ea-869d-a782a4855bde.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74060622-6012d300-4a10-11ea-8222-6b40b3cac6cd.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment]
out of scope
