### ISSUE TITLE
Article page header image not proper

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3926]
**Target URL:**  https://www.topcoder.com/thrive/articles/Five%20Things%20You%20Didn't%20Know%20About%20C++%20-%20Part%202

**To Reproduce**
1. Go to topcoder thrive page
2. Go to the section Development > Miscellaneous
3. Load more content and go to the "FIVE THINGS YOU DIDN'T KNOW ABOUT C++ - PART 2"

**Actual-**
article image is not proper

**Expected behavior**
Default topcoder image should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74060928-fd6e0700-4a10-11ea-8bbb-791e1bb0bbe2.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Chrome
 - Version: 80.0.3987.87

**Comment by winterflame** [comment]
won't fix
