### ISSUE TITLE
404 HTTP ERROR  in link "He told me once LOTS of people asked him why" Link opens an error page

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3927]
**Target URL:
[HTTP.zip](https://github.com/topcoder-platform/community-app/files/4172692/HTTP.zip)
** https://www.topcoder.com/5-big-mysteries-in-our-design-community-solved/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/5-big-mysteries-in-our-design-community-solved/

Observe under the article details, click the link "He told me once LOTS of people asked him why"

**Actual:** The Link "He told me once LOTS of people asked him why" directs to an error page

**Expected:** The link should redirect to the page with link details

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Out of scope.
