### ISSUE TITLE
Design pattern for C++ part 2 referece link is not correct

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3928]
**Target URL:**  https://www.topcoder.com/thrive/articles/Design%20Patterns%20in%20C++%20Part%202

**To Reproduce**
1. Go to topcoder thrive page
2. Go to the section Development > Miscellaneous
3. Load more content and go to the "DESIGN PATTERNS IN C++ PART 2"

**Actual-**
Link has redirects to the 404 not found page

**Expected behavior**
Reference link should be correct and landed to correct page

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74061513-2a6ee980-4a12-11ea-9266-696ca6acf00e.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Chrome
 - Version: 80.0.3987.87

**Comment by kkartunov** [comment]
Link works now.
