### ISSUE TITLE
[Web-Firefox] Texts Are Not Aligned Properly

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3929]
URL: https://www.topcoder.com/thrive/articles/How%20to%20Prepare%20for%20a%20Design%20Direction%20Challenge

**Describe the bug**
Texts Security, Facility & Information Are Not Aligned Properly

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/How%20to%20Prepare%20for%20a%20Design%20Direction%20Challenge

2. Scroll Down Mouse Below To Design Mandatory

3. See Texts Security, Facility & Information Then Observe

4. See Screenshot & Observe

**Expected behavior**
Texts Security, Facility & Information Should Be Aligned Properly

**Screenshots**
![Texts Are Not](https://user-images.githubusercontent.com/42583358/74061690-95b8bb80-4a12-11ea-8e22-cf20c82a6dd6.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74061726-aec16c80-4a12-11ea-8201-bcbbcfa490c9.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74061743-b7b23e00-4a12-11ea-89be-63cfbb4ae042.png)

**Additional context**
UI Issue

**Comment by winterflame** [comment]
not a bug
