### ISSUE TITLE
[Web-Firefox] Sentence Knowing Your Purpose and Dreams Is Written Wrong

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3930]
URL: https://www.topcoder.com/thrive/articles/How%20Beginner%20Designers%20Can%20Win%20UI%20Design%20Challenges%20in%20the%20Topcoder%20Community

**Describe the bug**
Sentence Knowing Your Purpose and Dreams Is Written Wrong. It Should Be Written As Knowing Your Purposes and Dreams

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/How%20Beginner%20Designers%20Can%20Win%20UI%20Design%20Challenges%20in%20the%20Topcoder%20Community

2. Scroll Down Mouse To Knowing Your Purpose and Dreams Then Observe

3. See Screenshot & Observe

**Expected behavior**
Sentence Should Be Written As Knowing Your Purposes and Dreams.

**Actual Behaviour**
Sentence Is Written As Knowing Your Purpose and Dreams

**Screenshots**
![Purposes](https://user-images.githubusercontent.com/42583358/74062311-fe546800-4a13-11ea-9289-8accc39eb5e4.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74062343-10360b00-4a14-11ea-889f-f3a98901aa71.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74062359-1a580980-4a14-11ea-9118-99a24a724941.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment]
not a bug
