### ISSUE TITLE
development >  Miscellaneous >Using the .Net Configuration Manager, .NET Framework, NAnt link is not functioning

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3931]
**Target URL:**  https://www.topcoder.com/thrive/articles/Using%20the%20.Net%20Configuration%20Manager

**To Reproduce**
1. Go to topcoder thrive page
2. Go to the section Development > Miscellaneous
3. Load more content and go to the "Using the .Net Configuration Manager"
4. Load that page and scroll below
5. Tap on the .NET Framework and NAnt has no correct link.

**Actual-**
Link has redirects to the 404 not found page

**Expected behavior**
Reference link should be correct and landed to correct page

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74062913-5b9ce900-4a15-11ea-935a-26f52648a761.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Chrome
 - Version: 80.0.3987.87

**Comment by winterflame** [comment]
#3918
