### ISSUE TITLE
No read time for the article from Topcoder Admin

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3932]
**Target URL:** https://www.topcoder.com/crowdsourcing-20-amazing-social-good-solutions-hpe-living-progress-challenge/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/crowdsourcing-20-amazing-social-good-solutions-hpe-living-progress-challenge/

Observe under article details in the username section

**Actual:** There is no read time for the article

**Expected:** There should be read time for the article for the reader to know how much time it wll take

**Browser:
![read](https://user-images.githubusercontent.com/37167721/74062936-70bb4d00-4a00-11ea-962f-7464d167f054.jpg)
** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Out of scope.
