### ISSUE TITLE
"404 HTTP Error" opened when "this informative page " link is clicked

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3933]
**Target URL:** https://www.topcoder.com/hpe-crowdsourcing-living-progress-challenge-design-development-topcoder-blitz/

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/hpe-crowdsourcing-living-progress-challenge-design-development-topcoder-blitz/

Observe the link in the article details

**Actual:** The link directs the user to a HTTP error page,.

**Expected:** The link should direct to the article link page
**Browser:
[link.zip](https://github.com/topcoder-platform/community-app/files/4172830/link.zip)
** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
Out of scope.
