### ISSUE TITLE
[Web-Firefox] Full Stop Should Not Be There At The End Of Topic Name

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3934]
URL: https://www.topcoder.com/thrive/articles/How%20to%20Make%20an%20Attractive%20Design%20Portfolio

**Describe the bug**
Topic Start to make your own brand. Is Having FillStop At The End

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/How%20to%20Make%20an%20Attractive%20Design%20Portfolio

2. Scroll Down Mouse To Topic Number 2. Start to make your own brand. Then See & Observe

3. See Screenshot & Observe

**Expected behavior**
Full Stop Should Not Be There At The End Of Topic Name

**Actual Behaviour**
Full Stop Should Is There At The End Of Topic Name

**Screenshots**
![Fullstop](https://user-images.githubusercontent.com/42583358/74063893-77a18a00-4a17-11ea-9fe6-7f13eb9e96f4.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74063936-89832d00-4a17-11ea-9ab5-6ecde16263fc.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74063974-a3bd0b00-4a17-11ea-9014-f0ccc739f269.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment]
content issue is out of scope.
