### ISSUE TITLE
[Web-Firefox] Sentence Is Written Wrong (A) Should Be Not There

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3935]
URL: https://www.topcoder.com/thrive/tracks?track=Design&tax=How-To

**Describe the bug**
Sentence Using Marvel at Topcoder: A How-to Guide for Designers. A Should Be Not There

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Design&tax=How-To

2. Scroll Down Mouse To Using Marvel at Topcoder: A How-to Guide for Designers  Then See & Observe

3. See Screenshot & Observe

**Expected behavior**
(A) Should Be Not There In Sentence Using Marvel at Topcoder: A How-to Guide for Designers 

**Actual Behaviour**
(A) Is There In Sentence Using Marvel at Topcoder: A How-to Guide for Designers 

**Screenshots**
![A](https://user-images.githubusercontent.com/42583358/74064656-24c8d200-4a19-11ea-85cf-1336208e693f.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74064689-37430b80-4a19-11ea-838a-2188ea0ec68e.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74064721-475aeb00-4a19-11ea-8ccb-c86440593440.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment]
not a bug
