### ISSUE TITLE
[Web-Firefox] Topic: 7 Tips to Be Successful in Topcoder Design & Topic: Design Month How Tos: Effective Landing Pages Is Written Twice

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3938]
URL: https://www.topcoder.com/thrive/tracks?track=Design&tax=How-To

**Describe the bug**
Topic: 7 Tips to Be Successful in Topcoder Design & Topic: Design Month How Tos: Effective Landing Pages Are Written Twice

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Design&tax=How-To

2. Scroll Down Mouse To  7 Tips to Be Successful in Topcoder Design. Another Topic: Design Month How Tos: Effective Landing Pages & Again Scroll Down Mouse Below & Observe

3. See Screencast

**Expected behavior**
Topic: 7 Tips to Be Successful in Topcoder Design & Topic: Design Month How Tos: Effective Landing Pages Should Be Written Only Ones

**Actual Result**
Topic: 7 Tips to Be Successful in Topcoder Design & Topic: Design Month How Tos: Effective Landing Pages Are Written Twice

**Screencasts**
[Same Topic.mp4.zip](https://github.com/topcoder-platform/community-app/files/4172929/Same.Topic.mp4.zip)

[Design.mp4.zip](https://github.com/topcoder-platform/community-app/files/4172958/Design.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74065836-c3eec900-4a1b-11ea-9749-236772c8dd3c.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74065864-d49f3f00-4a1b-11ea-8331-395eb19ad188.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment]
out of scope.
