### ISSUE TITLE
"DOES THE UI UX DESIGNER HAVE TO UNDERSTAND HOW TO WRITE CODE?" article directs to Topcoder Page not found

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3940]
**Target URL:** https://www.topcoder.com/thrive/tracks?track=Design&tax=Did%20You%20Know%20That%3F

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/tracks?track=Design&tax=Did%20You%20Know%20That%3F

Observe under Design track, UNDER title Did you know that? , Click the article title
[top4.zip](https://github.com/topcoder-platform/community-app/files/4172980/top4.zip)

![404](https://user-images.githubusercontent.com/4590317/74398527-dff6ce00-4e52-11ea-92c9-088e85a06195.jpg)

**Actual:** The article title link redirects to a Topcoder page not found error 404

**Expected:** The article title link should direct to a page with the article details

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
duplicated with #3907
