### ISSUE TITLE
No error in wrong date format in the To date section

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3941]
**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Geometry&author=All%20authors&startDate=2020-08-14T12%3A00%3A00Z&endDate=2019-06-02T12%3A00%3A00Z

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=Geometry&author=All%20authors&startDate=2020-08-14T12%3A00%3A00Z&endDate=2019-06-02T12%3A00%3A00Z

Observe under Competitive programming tag links, Click Geometry tag , Under Geometry click the dates

**Actual:** There is no error message when in the To date section past dates are selected.

Expected: When past dates are selected in the To Date section, there should be an error message. Check the image. Date
![date](https://user-images.githubusercontent.com/37167721/74067865-3b682c80-4a0b-11ea-96f6-b58597784b84.jpg)

Browser: Google Chrome Version 79.0.3945.130

**Comment by kkartunov** [comment]
This filter is currently undergoing redesign and new functionality. The error will in no more relevant.
