### ISSUE TITLE
The Up-close icon to minimize tags in Competitive programming not working(FUNCTIONAL)

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3942]
**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=&author=All%20authors&startDate=2020-01-08T00%3A39%3A13%2B03%3A00&endDate=2020-02-08T00%3A39%3A13%2B03%3A00

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=&author=All%20authors&startDate=2020-01-08T00%3A39%3A13%2B03%3A00&endDate=2020-02-08T00%3A39%3A13%2B03%3A00

Observe under Competitive programming tag links

**Actual:** The minimize icon for the tags is not functional/not working

**Expected:** The Up-close to minimize the 
[comp1.zip](https://github.com/topcoder-platform/community-app/files/4173051/comp1.zip)
tags should close all the options when clicked

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
it's as designed
