### ISSUE TITLE
'Show more' button alignment issue

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3944]
![image](https://user-images.githubusercontent.com/42398485/74069005-b0fbda80-49c2-11ea-83e6-5c6f2178301d.png)

**Target URL:** https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2000-01-01T12%3A00%3A00Z&endDate=2020-02-07T08%3A31%3A35-06%3A00&track=Design

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/search?author=All%20authors&startDate=2000-01-01T12%3A00%3A00Z&endDate=2020-02-07T08%3A31%3A35-06%3A00&track=Design
3. Scroll down and check the 'Show more' button alignment 

**Actual:** 'Show more' button alignment issue

**Expected:**  Should align the button to the center of the section

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by kkartunov** [comment]
Button should be centered as per design.
![Screenshot from 2020-10-16 14-43-32](https://user-images.githubusercontent.com/5585002/96254482-08286500-0fbe-11eb-8538-b43b2115f2d9.png)
