### ISSUE TITLE
"Three iconic designs that came from crowdsourcing competitions" article directs the user to 404 not found page (Functional)

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3946]
**Describe the bug**
the article "Three iconic designs that came from crowdsourcing competitions" under "DESIGN" track directs the user to 404 not found page

**Target URL** : https://www.topcoder.com/thrive

**Steps to reproduce the behavior:**
1. Go to https://www.topcoder.com/thrive
2. Go to DESIGN track 
3. Click on the article "Three iconic designs that came from crowdsourcing competitions"
4. Observe error

**Expected behavior**
The article link when clicked it should take the user to a page where the article is present 

**Actual behavior**
The article link when clicked directs the user to a page 404 not found

**Environment:** Micromax LI351568W 15.6 ; Windows 10x64
**Browser:** Google Chrome Version 80.0.3987.87

**Screencast**
http://somup.com/cYnirph6gt

**Comment by winterflame** [comment]
duplicated #3729
