### ISSUE TITLE
close icon to minimize tags in Topcoder not working(FUNCTIONAL) 

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/community-app#3947]
**Target URL:** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=&author=All%20authors&startDate=2020-01-08T00%3A39%3A13%2B03%3A00&endDate=2020-02-08T00%3A39%3A13%2B03%3A00

Open the Application and Login as valid user
**Go to** https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=&author=All%20authors&startDate=2020-01-08T00%3A39%3A13%2B03%3A00&endDate=2020-02-08T00%3A39%3A13%2B03%3A00

Observe under Topcoder tag links

**Actual:** The minimize icon for the tags is not functional/not working

**Expected:** The Up-close to minimize the tags should close all the options when clicked to minimize the tags
![coder](https://user-images.githubusercontent.com/37167721/74069434-3b6a2b80-4a0f-11ea-8058-f364057bfa75.jpg)

**Browser:** Google Chrome Version 79.0.3945.130

**Comment by winterflame** [comment]
not a bug
