### ISSUE TITLE
Inconsistent behavior of articles opening when clicked [Functional]

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3948]
**Describe the bug**
Few articles when clicked open in the same tab while others on clicked open in a new tab showing inconsistent behavior

**Target URL :** https://www.topcoder.com/thrive

1. Go to https://www.topcoder.com/thrive
2. Go to Competitive Programming 
3. Click on the article "SINGLE ROUND MATCH 753 EDITORIALS"
4. Observe the article opens in another tab
5. Now go to Data Science track
6.  Click on the article "MARKOV MODEL"
7. Observe > this article opens in the same tab

**Expected behavior**
The user when clicks an article link it should either open in new tab or it should open in the same tab always for consistent behavior

**Actual behavior**
Few articles when clicked open in the same tab while others on clicked open in a new tab showing inconsistent behavior

**Environment**: Micromax LI351568W 15.6 ; Windows 10x64
**Browser**: Google Chrome Version 80.0.3987.87

Screencast
http://somup.com/cYni3bh6pI

**Comment by winterflame** [comment]
similar to #3810

**Comment by kkartunov** [comment]
External articles do and should be opening in a new tab. Internal in the same tab. This is correct and expected behavior.
