### ISSUE TITLE
When user Copies the name of the article the date above it is also highlighted, spacing between lines is not correct[UI]

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/community-app#3949]
**Describe the bug**
When user Copies the name of the article after clicking on any article, the date above it is also highlighted

**Target URL :** https://www.topcoder.com/thrive

**Steps to reproduce the behavior:**
1. Go to https://www.topcoder.com/thrive
2. Click on any article
3. Copy the heading of the article 
4. Observe that date above the article is also highlighted

**Expected behavior**
The user when Copies the name of the article the date above should not be highlighted, there should be correct spacing between the lines

**Actual behavior**
When user Copies the name of the article the date above it is also highlighted

**Environment:** Micromax LI351568W 15.6 ; Windows 10x64
**Browser:** Google Chrome Version 80.0.3987.87

**Screenshot**
![Bug007](https://user-images.githubusercontent.com/46349625/74070995-93615c00-4a28-11ea-992f-7773342f13b2.jpg)

**Comment by winterflame** [comment]
Maybe need to increase the space between the date and the title.

**Comment by kalindipandey** [comment]
@winterflame is the bug accepted?

**Comment by winterflame** [comment]
@kalindipandey Yes, it's accepted.

**Comment by kkartunov** [comment]
Spacing is correct and follows design.
