### ISSUE TITLE
Some extra character seem to visible 

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/community-app#3951]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Member%20Roles

**To Reproduce**
1. Go to tpcoder thrive page
2.  In section topcoder > Member Role
3. Load more and observe some section extra content visible

**Actual-**
Some extra content visible in section and make whole section large

**Expected behavior**
Should not make section large due to extra non meaningful char

**Screenshots**
![image](https://user-images.githubusercontent.com/23450398/74078715-b2c1ae80-4a53-11ea-97bd-c1d01c5a8936.png)

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Firefox
 - Version: 72.0.2

**Comment by winterflame** [comment]
not a bug
