### ISSUE TITLE
Thrive_Cursor Focus > Its not in the middle of the text if the articles page were opened.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/community-app#3952]
Target URL: https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Help%20Articles

To Reproduce

1.Go to topcoder thrive page
2. Observe the cursor selection under Thrive. Its is in the middle of the THRIVE text.
3. Now select Topcoder> Help Articles.
4. Observe the position of cursor below the text THRIVE. Its not in the middle of the text unlike THRIVE home page.

Actual-

Position of the cursor is not in the middle of the text unlike THRIVE HOME page.

Expected behavior

Position of the cursor should be in the middle of the text.

Screenshots

[Issue22.zip](https://github.com/topcoder-platform/community-app/files/4173759/Issue22.zip)

Desktop:

OS: Toshibha Satellite L370; Windows 10pro
Browser: Firefox
Version: 72.0.2

**Comment by winterflame** [comment]
duplicated
