### ISSUE TITLE
To date before from date gets accepted

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3953]
**Target URL**

https://www.topcoder.com/thrive/search?tags[0]=Tips

**Reproduction Steps**

1. Please open the target url mentioned above.
2. In the filter section on the left, select a to date before from date.
3. Click on apply filter button.

**Expected Result**

1. There should be an error message as the to date is before from date.

**Actual Result**

1. There is no error message.

**Screenshots or screencast**

![Topcoder (7)](https://user-images.githubusercontent.com/3612991/74080552-15727480-4a6b-11ea-9c30-aaafa650da0a.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
duplicated #3725
