### ISSUE TITLE
[UI] inconsistency in read time format on articles

### ISSUE THREAD

**Issue by sanju-singh** [topcoder-platform/community-app#3954]
Target URL: https://www.topcoder.com/thrive

### Reproduction Steps ###

1. Go to https://www.topcoder.com/thrive
2. Observe read time displayed on articles.

### Expected Result ###

Read time format should be same on all the articles.

### Actual Result ###

Read time format is inconsistent on different articles.

### Screenshots or screencast ###

<img width="1440" alt="Screenshot 2020-02-08 at 11 59 32 AM" src="https://user-images.githubusercontent.com/7385269/74080596-8f0a6280-4a6b-11ea-98a5-9283b058e2a9.png">

### OS/Browser Information ###

Macos / chrome 80.0.3987.87

**Comment by winterflame** [comment]
#3877
