### ISSUE TITLE
[UI] wrong ellipses count shown at some places

### ISSUE THREAD

**Issue by sanju-singh** [topcoder-platform/community-app#3956]
Target URL: https://www.topcoder.com/thrive

### Reproduction Steps ###

1. Go to https://www.topcoder.com/thrive
2. On search and in article title, ellipsis consist of 2 dots, whereas in featured articles it is three dots.

### Expected Result ###

Ellipsis dots should be consistent and should consist of 3 dots.

### Actual Result ###

Ellipsis dots at some places showing only 2 dots.

### Screenshots or screencast ###

<img width="1440" alt="Screenshot 2020-02-08 at 12 53 40 PM" src="https://user-images.githubusercontent.com/7385269/74081235-bb75ad00-4a72-11ea-8e56-994877486f58.png">
![Uploading Screenshot 2020-02-08 at 12.53.50 PM.png…]()

### OS/Browser Information ###

Macos / chrome 80.0.3987.87

**Comment by sanju-singh** [comment]
<img width="1426" alt="Screenshot 2020-02-08 at 12 53 50 PM" src="https://user-images.githubusercontent.com/7385269/74081273-350d9b00-4a73-11ea-8d2f-b570c6f6696f.png">

**Comment by sandhiyakavi** [comment]
Tested in Test Environment.Ellipsis consist of 3 dots in Search and Article title.

<img width="956" alt="#3956" src="https://user-images.githubusercontent.com/55895538/79183987-f965c780-7e4d-11ea-95fd-b56c492b4939.PNG">

Featured articles

<img width="957" alt="#3956_1" src="https://user-images.githubusercontent.com/55895538/79184012-071b4d00-7e4e-11ea-98d8-749441f411fc.PNG">

**Comment by sandhiyakavi** [comment]
cc: @SathyaJayabal

**Comment by hokienick** [comment]
Good to go!

**Comment by Jobee1** [comment]
Tested in Beta Environment. Ellipsis consist of 3 dots in Search and Article title.

![Screenshot_3](https://user-images.githubusercontent.com/48575864/79444480-f2c88300-7ffa-11ea-8b66-173b0a2755e3.png)

Featured Articles:
![Screenshot_4](https://user-images.githubusercontent.com/48575864/79444522-fe1bae80-7ffa-11ea-8a66-ea5318ea3446.png)

**Comment by SathyaJayabal** [comment]
verified on production
<img width="1440" alt="Screenshot 2020-04-16 at 7 30 21 PM" src="https://user-images.githubusercontent.com/58783823/79465486-05ea4b80-8019-11ea-844e-1a453db9c0ca.png">
<img width="1414" alt="Screenshot 2020-04-16 at 7 32 04 PM" src="https://user-images.githubusercontent.com/58783823/79465561-1e5a6600-8019-11ea-97e1-41d96f9a2c2a.png">
