### ISSUE TITLE
[Web-Firefox] Link Is Breaking

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3958]
URL: https://www.topcoder.com/thrive/articles/Word%20Embeddings:%20Context%20Matters%20in%20Natural%20Language%20Processing

**Describe the bug**
 http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Musical_Instruments_5.json.gz Link Is Not Opening & Breaking

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Word%20Embeddings:%20Context%20Matters%20in%20Natural%20Language%20Processing

2. Scroll Down Mouse To How to use Word2Vec

3. Click On Link  http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Musical_Instruments_5.json.gz Then See & Observe.

4. See Screencast & Observe

**Expected behavior**
Link Should Open & Should Not Break

**Actual Behaviour**
Link Is Not Opening & Breaking

**Screencast**
[Link.mp4.zip](https://github.com/topcoder-platform/community-app/files/4173952/Link.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74082107-a56cea00-4a7c-11ea-8f60-e0c38086d82d.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74082125-d64d1f00-4a7c-11ea-9c77-3c50c2045e07.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
cannot reproduce
