### ISSUE TITLE
Thrive - "tips" tag Author dropdown (UI) 

### ISSUE THREAD

**Issue by martian360** [topcoder-platform/community-app#3959]
**Target URL**
https://www.topcoder.com/thrive/search?tags[0]=Tips

**Steps to Reproduce**
1. Go to https://www.topcoder.com/thrive/search?tags[0]=Tips
2. Click on the Author dropdown on the left column

**Expected results**
On click of the dropdown the dropdown arrow should change to water image of itself
representing that on click it the options will collapse

**Actual results**
On click of the dropdown the dropdown arrow does not change to water image of itself

**Screenshots**
![1](https://user-images.githubusercontent.com/60810387/74082360-2331f500-4a7f-11ea-8058-d0f62c1015d7.png)

**OS**
Windows 10

**Browser**
Google Chrome 
Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by winterflame** [comment]
duplicated
