### ISSUE TITLE
Search results disappear when user right clicks

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3960]
**Target URL**

https://www.topcoder.com/thrive

**Reproduction Steps**

1. Please open the target url mentioned above.
2. In the search box, enter "ab".
3. Wait for the search results to appear.
4. Right click on any result to open in a new tab.

**Expected Result**

1. Results should remain visible after right click.

**Actual Result**

1. Although open in new tab works, results disappear when user right clicks.

**Screenshots or screencast**

![searchResult](https://user-images.githubusercontent.com/4590317/74441508-e749c600-4eaa-11ea-8bd5-9f2b2502a631.jpg)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by Jobee1** [comment]
Verified in Test Environment.

Attached video for reference:
[3960_test_env.zip](https://github.com/topcoder-platform/community-app/files/4558653/3960_test_env.zip)

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
[3960.mov.zip](https://github.com/topcoder-platform/community-app/files/4655025/3960.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod

[3960.mov.zip](https://github.com/topcoder-platform/community-app/files/4662033/3960.mov.zip)
