### ISSUE TITLE
White spaces are hyperlinked

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3961]
**Target URL**

https://www.topcoder.com/thrive

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Hover the mouse cursor on the white spaces to the right of the text labels, for instance, competitive programming, data science, design etc.
3. Observe the cursor.

**Expected Result**

1. White spaces should not be hyperlinked, unless it is clearly understandable.

**Actual Result**

1. White spaces are hyperlinked.

**Screenshots or screencast**

![Topcoder (8)](https://user-images.githubusercontent.com/3612991/74082638-f206f400-4a81-11ea-98c6-591e8554b3d2.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
duplicated
