### ISSUE TITLE
Red/pink vertical line visible at window size 1024x576

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3962]
**Target URL**

https://www.topcoder.com/thrive

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Ensure browser window size is 1024x576.
3. On the extreme right, observe very carefully the red/pink vertical line visible under the man pointing at the screen. the line disappears when the window is maximized.

**Expected Result**

1. The red/pink vertical line should not be present.

**Actual Result**

1. The red/pink vertical line is present.

**Screenshots or screencast**

![Topcoder (9)](https://user-images.githubusercontent.com/3612991/74082750-31821000-4a83-11ea-9a52-8387f6f6972b.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
small screen size is not in scope.
