### ISSUE TITLE
[Web-Firefox] While Clicking On Link http://lldb.llvm.org/download.html. Its Showing Error

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3963]
URL: https://www.topcoder.com/thrive/articles/Improve%20Debugging%20Efficiency%20with%20LLDB

**Describe the bug**
While Clicking On Link http://lldb.llvm.org/download.html. Its Showing Error As Not Found
The requested URL /download.html was not found on this server.

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Improve%20Debugging%20Efficiency%20with%20LLDB

2. Scroll Down Mouse To Basic Usages

3. Click On Link http://lldb.llvm.org/download.html. Then See & Observe.

**Expected behavior**
Link Should Not Show Error.

**Actual Result**
Link Is Showing Error As Its Showing Error As Not Found
The requested URL /download.html was not found on this server.

**Screencast**
[Not Found.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174033/Not.Found.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74083329-c50a0f80-4a88-11ea-863b-36beacd24e9e.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74083339-df43ed80-4a88-11ea-8fe1-8c4bb9b02ea8.png)

**Additional context**
Functional Issue

**Comment by hokienick** [comment]
Link updated
