### ISSUE TITLE
Selection box is broken at the corners

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3964]
**Target URL**

https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Tips

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Right click on the first article to see the selection box. Press esc to close the context menu.

**Expected Result**

1. The box should not be broken at the corners.

**Actual Result**

1. The box is broken at the corners.

**Screenshots or screencast**

Not required

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
Missing screenshot. Also duplicated with #3793
