### ISSUE TITLE
Video thumbnail is not fully visible 

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/community-app#3965]
**Target URL**

https://www.topcoder.com/thrive/tracks?track=QA&tax=

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Please resize the browser window at 1024x576.
3. In the top design videos section, scroll to the extreme left.
4. Observe the thumbnail of the video titled to create a lux rux ... .

**Expected Result**

1. The thumbnail should be fully visible.

**Actual Result**

1. The thumbnail is not fully visible.

**Screenshots or screencast**

![Topcoder (10)](https://user-images.githubusercontent.com/3612991/74083469-6a71b300-4a8a-11ea-8051-4b54da158060.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 80.0.3987.87 (official build) (32-bit)

**Comment by winterflame** [comment]
out of scope
