### ISSUE TITLE
[Web-Firefox] Link BUILDCONFIG.gn Is Not Opening & Its Showing Error.

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3966]
URL: https://www.topcoder.com/thrive/articles/Introduction%20to%20Build%20Tools%20GN%20&%20Ninja

**Describe the bug**
Link BUILDCONFIG.gn Is Not Opening. Its Showing Error As Hmm. We’re having trouble finding that site.

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Introduction%20to%20Build%20Tools%20GN%20&%20Ninja

2. Scroll Down To Step 1: Create /BUILDCONFIG.gn & Click On Link  BUILDCONFIG.gn Then See & Observe.

3. See Screencast & Observe

**Expected behavior**
Link BUILDCONFIG.gn Should Open & Should Not Show Error.

**Actual Behaviour**
Link BUILDCONFIG.gn Is Not Opening & Its Showing Error As Hmm. We’re having trouble finding that site.

**Screencast**
[We Are.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174052/We.Are.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74083539-3b0f7600-4a8b-11ea-874a-1a97f5e140e4.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74083543-4c588280-4a8b-11ea-915c-0ceba6407bf3.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
external link not in scope.
