### ISSUE TITLE
[Web-Firefox] Link BUILD.gn Is Not Opening Its Showing Error

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3967]
URL: https://www.topcoder.com/thrive/articles/Introduction%20to%20Build%20Tools%20GN%20&%20Ninja

**Describe the bug**
Link BUILD.gn Is Not Opening Its Showing Error As Hmm. We’re having trouble finding that site.

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Introduction%20to%20Build%20Tools%20GN%20&%20Ninja

2. Scroll Down Mouse To Step 3: Create & Click On Link BUILD.gn Then Observe

3. See Screencast & Observe

**Expected behavior**
Link BUILD.gn Is Not Opening & Its Showing Error As Hmm. We’re having trouble finding that site.

**Actual Behaviour**
Link BUILD.gn Should Open & Shouldn't Show Any Error

**Screencast**
[Config.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174066/Config.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74083700-2af89600-4a8d-11ea-8dc4-6bd8a50f0c2a.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74083706-39df4880-4a8d-11ea-842f-5cd7ebc56f81.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
external link not in scope.
