### ISSUE TITLE
[Web-Firefox] Only Topic Name Is Change Details Are Same In Both Topic

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3968]
URL: https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

**Describe the bug**
Topic Invariance, Covariance and Contravariance types in C# - Part 2 & Topic Invariance, Covariance and Contravariance types in C# - Part 1 Name Is Different But Details Are Same

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

2. Scroll Down Mouse To Show More & Click Three Times On It

3. Click on Topic Invariance, Covariance and Contravariance types in C# - Part 2 

4. Again Go To https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

5. Scroll Down Mouse To Show More & Click Three Times On It

6. Again Click On Topic Invariance, Covariance and Contravariance types in C# - Part 1

7. See Details Are Different In Inside In Both Topic & Observe

8. See Screencast & Observe

**Expected behavior**
As Topic Is Different. Details Should Be Different.

**Actual Behaviour**
As Topic Is Different. Details Are Same.

**Screencast**
[Table.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174139/Table.mp4.zip)

[Table 2.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174140/Table.2.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74084501-c5f56e00-4a95-11ea-9aeb-fb6270681622.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74084506-d0176c80-4a95-11ea-8d92-0d394fa00fbf.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
To summarize: 
Links https://www.topcoder.com/thrive/articles/Invariance,%20Covariance%20and%20Contravariance%20types%20in%20C#%20-%20Part%201
and 
https://www.topcoder.com/thrive/articles/Invariance,%20Covariance%20and%20Contravariance%20types%20in%20C#%20-%20Part%202 share the same content.

**Comment by hokienick** [comment]
Related to #3972

**Comment by kkartunov** [comment]
Yes, fix for #3972 will fix this one as well

**Comment by Jobee1** [comment]
When I clicked on "Invariance, Covariance and Contravariance types in C# - Part 1" the details and the title is same as that of Part 2.

Attached video for reference:
[3968.zip](https://github.com/topcoder-platform/community-app/files/4559106/3968.zip)

**Comment by kkartunov** [comment]
@dushyantb @Jobee1 this one. I renamed the articles to:
- https://test-community-app.topcoder-dev.com/thrive/articles/Invariance,%20Covariance%20and%20Contravariance%20types%20in%20C%20Sharp%20-%20Part%20Two
- https://test-community-app.topcoder-dev.com/thrive/articles/Invariance,%20Covariance%20and%20Contravariance%20types%20in%20C%20Sharp%20-%20Part%20One

**Comment by Jobee1** [comment]
Verified in Test Environment. Different articles are displayed when clicked on different links.

Attached video for reference:
[3968.zip](https://github.com/topcoder-platform/community-app/files/4562959/3968.zip)

**Comment by SathyaJayabal** [comment]
Verified on beta(develop branch)
[3968.mov.zip](https://github.com/topcoder-platform/community-app/files/4655019/3968.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[3968.mov.zip](https://github.com/topcoder-platform/community-app/files/4662102/3968.mov.zip)
