### ISSUE TITLE
[Web-Firefox] Topic Name & In Details Topic Name Are Different

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3969]
URL: https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

**Describe the bug**
Topic Name Is Five Things You Didn't Know About C++ - Part 2 But While Clicking On Topic Name Its Showing Different Topic Name As Five things you didn't know about C++ - Part 3 

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

2. Scroll Down Mouse To Show More Then Click Four Times On It.

3. Scroll down to Topic Five Things You Didn't Know About C++ - Part 2 Then Click On It.

4. See Screencast & Screenshot Then Observe

**Expected behavior**
Topic Name & In Details Name Should Be Same.

**Actual Behavior**
Topic Name & In Details Name Are Different

**Screenshot & Screencast**
[Part 2.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174164/Part.2.mp4.zip)

![Part2](https://user-images.githubusercontent.com/42583358/74084926-fe974680-4a99-11ea-983a-fa1195f2cdce.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74084937-15d63400-4a9a-11ea-8e41-8c727b3189f0.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74084961-3f8f5b00-4a9a-11ea-9867-bdfd6269c1f7.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
To summarize:
![bug](https://user-images.githubusercontent.com/4590317/74436739-e6606680-4ea1-11ea-8204-2c316781b56e.jpg)

**Comment by hokienick** [comment]
This can be solved by my team, but may need a push to production.

**Comment by kkartunov** [comment]
Yes. Fix for #3972 will fix this as well.

**Comment by Jobee1** [comment]
Verified in Test Environment. The topic name and the details in the topic are same.

Attached video for reference:
[3969_test_env.zip](https://github.com/topcoder-platform/community-app/files/4558528/3969_test_env.zip)

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
[3969.mov.zip](https://github.com/topcoder-platform/community-app/files/4655013/3969.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[3969.mov.zip](https://github.com/topcoder-platform/community-app/files/4662091/3969.mov.zip)
