### ISSUE TITLE
[Web-Firefox] Topic Name Is Different & In Detail Topic Name is Different 

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3970]
URL: https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

**Describe the bug**
Topic Name Is Five Things You Didn't Know About C++ - Part 1. While Clicking On It. In Details Its Topic Name Is Five things you didn't know about C++ - Part 3

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

2. Scroll Down Mouse Below To Show More & Click On It Four Times

3. Scroll down to Five Things You Didn't Know About C++ - Part 1

4. Click On It & Observe Its Showing Topic As Five things you didn't know about C++ - Part 3

5. See Screencast & Screenshot 

**Expected behavior**
Topic Name & In Detail Name Should Be Same

**Current Behaviour**
Topic Name Is Different & In Detail Topic Name is Different 

**Screenshot & Screencast**
![Part 1](https://user-images.githubusercontent.com/42583358/74085500-774cd180-4a9f-11ea-9c60-d0af4ad91c4e.png)

[Part 1.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174185/Part.1.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74085530-bed35d80-4a9f-11ea-9532-ebfd7ecdb3f6.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74085539-cdba1000-4a9f-11ea-828d-6e3779cf3fe6.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
duplicated with #3969
