### ISSUE TITLE
[Web-Firefox] Link http://www.boost.org/libs/spirit/phoenix/index.html. is not Opening

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3971]
URL: https://www.topcoder.com/thrive/articles/Design%20Patterns%20in%20C++%20Part%202

**Describe the bug**
While Clicking On Link http://www.boost.org/libs/spirit/phoenix/index.html. Its Not Opening & Showing Error As 
404 Not Found 
File "/home/www/shared/archives/live/boost_1_72_0/libs/spirit/phoenix/index.html" not found.
Unable to find file.

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/articles/Design%20Patterns%20in%20C++%20Part%202

2. Scroll Down Mouse Below To  Bottom

3. Click On Link  http://www.boost.org/libs/spirit/phoenix/index.html & Observe

4. See Screencast & Observe

**Expected behavior**
Link http://www.boost.org/libs/spirit/phoenix/index.html. Should Open.

**Actual Behavior**
Link  http://www.boost.org/libs/spirit/phoenix/index.html Is Showing Error As 
404 Not Found File "/home/www/shared/archives/live/boost_1_72_0/libs/spirit/phoenix/index.html" not found.
Unable to find file.

**Screencast**
[Boost.mp4.zip](https://github.com/topcoder-platform/community-app/files/4174198/Boost.mp4.zip)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74085737-3acea500-4aa2-11ea-93d8-e4893e8b8025.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74085741-4a4dee00-4aa2-11ea-9369-848077aeda65.png)

**Additional context**
Functional Issue

**Comment by winterflame** [comment]
external link is out of scope.
