### ISSUE TITLE
Incorrect article loads when user click on 'DESIGN PATTERNS IN C++ PART 1'

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#3972]
![image](https://user-images.githubusercontent.com/42398485/74088544-392ebe00-4a5d-11ea-965e-013238a77ec6.png)

**Target URL:** https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous

1. Open the Application and Login as valid user
2. Go to https://www.topcoder.com/thrive/tracks?track=Development&tax=Miscellaneous
3. Click View more 5 times
4. Click on the 'DESIGN PATTERNS IN C++ PART 1'  links 

**Actual:** 'example is available here' link is not working

**Expected:** Link should work and redirect the page to the correct one

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Google Chrome 80.0.3987.87 | FF 72.0.2

**Comment by hokienick** [comment]
Issue with external link in thrive.  Closing.

**Comment by hokienick** [comment]
This wasn't the case seemingly.

**Comment by Jobee1** [comment]
When opening the both links, different articles is loaded.
Verified in Test Environment.

Attached screenshot for reference:
DESIGN PATTERNS IN C++ PART 1
![Part 1](https://user-images.githubusercontent.com/48575864/80720314-76669180-8b1c-11ea-9c1b-188b2316dc2b.png)

DESIGN PATTERNS IN C++ PART 2
![Part 2](https://user-images.githubusercontent.com/48575864/80720376-88e0cb00-8b1c-11ea-9f40-3d2a92573293.png)

**Comment by SathyaJayabal** [comment]
The fix is when you try search for DESIGN PATTERNS IN C++ PART 1 and then DESIGN PATTERNS IN C++ PART 2 it always opens same article but should make a difference

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
[3972.mov.zip](https://github.com/topcoder-platform/community-app/files/4649539/3972.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[3972.mov.zip](https://github.com/topcoder-platform/community-app/files/4662010/3972.mov.zip)
