### ISSUE TITLE
New themes for Contentful tabs

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3974]
Implement 2 themes for Contentful tabs.
1. Pills - https://marvelapp.com/4f8i35i/screen/61272621/handoff
2. Vertical - https://marvelapp.com/535c9ga/screen/66047176/handoff

**Pills test:** https://community-app.topcoder-dev.com/examples/contentful/viewport/2M4dQrVH6z3sP2wFf2TFxu

**Vertical**:  https://community-app.topcoder-dev.com/examples/contentful/viewport/29livWGlTJbJbvpHJMZUt7

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1358" alt="Screenshot 2020-02-11 at 2 32 08 PM" src="https://user-images.githubusercontent.com/58783823/74222884-72746180-4cdb-11ea-9a80-f19d034c37df.png">
<img width="1350" alt="Screenshot 2020-02-11 at 2 32 58 PM" src="https://user-images.githubusercontent.com/58783823/74222890-77d1ac00-4cdb-11ea-8ab7-3d37267dd10d.png">

**Comment by SathyaJayabal** [comment]
<img width="1358" alt="Screenshot 2020-02-11 at 2 32 08 PM" src="https://user-images.githubusercontent.com/58783823/74223055-e282e780-4cdb-11ea-9db9-f654dba3aefe.png">

**Comment by SathyaJayabal** [comment]
Verified on Beta
<img width="1433" alt="Screenshot 2020-02-12 at 1 24 48 PM" src="https://user-images.githubusercontent.com/58783823/74314222-1e30b680-4d9b-11ea-92b5-ee9a5bfb35f4.png">
<img width="1430" alt="Screenshot 2020-02-12 at 1 25 01 PM" src="https://user-images.githubusercontent.com/58783823/74314241-225cd400-4d9b-11ea-9b1f-630bf42915ec.png">

**Comment by SathyaJayabal** [comment]
@kkartunov , how do we test this in production. The given test URLs do not work in production

**Comment by SathyaJayabal** [comment]
verified in production
<img width="1431" alt="Screenshot 2020-02-12 at 6 39 24 PM" src="https://user-images.githubusercontent.com/58783823/74337861-21419c00-4dc7-11ea-9885-68fd7dff55de.png">
<img width="1429" alt="Screenshot 2020-02-12 at 6 40 00 PM" src="https://user-images.githubusercontent.com/58783823/74337867-243c8c80-4dc7-11ea-969b-115832470281.png">
