### ISSUE TITLE
Statistic tables (looker tag) refresh

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3976]
Update Looker components to match new look and feel as per https://marvelapp.com/535c9ga/screen/66047176/handoff

Test: https://www.topcoder.com/community/statistics

Note: statistics are available **only on prod env** not on dev.

**Comment by SathyaJayabal** [comment]
@kkartunov , this cannot be tested on test env ?

**Comment by SathyaJayabal** [comment]
@kkartunov 
Table header and sorting is missing
Handles need to be a link 
<img width="1103" alt="Screenshot 2020-02-11 at 3 27 26 PM" src="https://user-images.githubusercontent.com/58783823/74226725-14e41300-4ce3-11ea-9e4f-926bc97ec101.png">

<img width="405" alt="Screenshot 2020-02-11 at 3 27 12 PM" src="https://user-images.githubusercontent.com/58783823/74226718-11e92280-4ce3-11ea-884f-606978a76255.png">

**Comment by SathyaJayabal** [comment]
As per @kkartunov's comments, verified one sample table where headers and handle links are implemented. 

<img width="1404" alt="Screenshot 2020-02-11 at 3 51 38 PM" src="https://user-images.githubusercontent.com/58783823/74228482-840f3680-4ce6-11ea-96a0-c6c22c0925ef.png">

**Comment by SathyaJayabal** [comment]
Verified on Beta (Develop branch)
<img width="344" alt="Screenshot 2020-02-12 at 1 30 01 PM" src="https://user-images.githubusercontent.com/58783823/74314658-d3fc0500-4d9b-11ea-884c-ceffd21c01ad.png">

**Comment by SathyaJayabal** [comment]
verified for sample table in production.

@kkartunov , please apply the styles for the rest of the tables and verify.
<img width="330" alt="Screenshot 2020-02-12 at 6 20 12 PM" src="https://user-images.githubusercontent.com/58783823/74336532-7203c580-4dc4-11ea-9db7-072a3e0ece5f.png">
