### ISSUE TITLE
Hide search feature on CS portal

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3983]
Hide the search icon on Credit Suisse's portal 
![image](https://user-images.githubusercontent.com/47536078/74272635-d4c16800-4cc3-11ea-8868-d2de2f2645a1.png)

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1439" alt="Screenshot 2020-03-31 at 10 33 14 AM" src="https://user-images.githubusercontent.com/58783823/77988925-10c78f80-733b-11ea-841d-7a5ab35a4542.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="1431" alt="Screenshot 2020-04-02 at 12 23 19 PM" src="https://user-images.githubusercontent.com/58783823/78219242-c7af4100-74dc-11ea-9494-0a5820fbaef6.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1432" alt="Screenshot 2020-04-02 at 5 14 43 PM" src="https://user-images.githubusercontent.com/58783823/78245742-9f880800-7505-11ea-91f9-d9267e67366d.png">
