### ISSUE TITLE
Update Privacy URL on Community App

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#3984]
Currently, we have 2 pages for the same thing…and they are always out of sync
marketing site page:  https://www.topcoder.com/privacy-policy/
community-app page:  https://www.topcoder.com/community/how-it-works/privacy-policy/

Expected behavior:
Direct to marketing site page:  https://www.topcoder.com/privacy-policy/ and disable community-app page https://www.topcoder.com/community/how-it-works/privacy-policy/

**Comment by kkartunov** [comment]
Left a redirect notice on the community-app page: https://www.topcoder.com/community/how-it-works/privacy-policy/

**Comment by Oanh-and-only-Oanh** [comment]
@kkartunov,  please don't close tickets until it's been confirmed by either me or QA. please disable this  page completely. The link should just redirect user to marketing page

**Comment by SathyaJayabal** [comment]
@kkartunov ,  the link https://www.topcoder.com/community/how-it-works/privacy-policy/ should redirect to https://www.topcoder.com/privacy-policy/

The link does not redirect to the marketing site page and still has a redirect notice.
<img width="1440" alt="Screenshot 2020-03-31 at 10 47 52 AM" src="https://user-images.githubusercontent.com/58783823/77989772-3d7ca680-733d-11ea-95b8-02eb1dab864e.png">

cc @sandhiyakavi

**Comment by kkartunov** [comment]
@SathyaJayabal this one is okay. We decided to keep the warning until all related fixes are merged. I will remove it when we are done. Related to redirection it is not possible to automatically redirect reroutes thus we decided to remove legacy URL.
This one is good to go! cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@kkartunov marking this as pass based on comment above.

**Comment by sandhiyakavi** [comment]
verified the issue,Working as expected

Privacy link in Challenges page.
![image](https://user-images.githubusercontent.com/55895538/78219130-8e76d100-74dc-11ea-9d58-f6570af145bb.png)

Privacy policy link in Footer
![image](https://user-images.githubusercontent.com/55895538/78219227-bd8d4280-74dc-11ea-8ca0-a8f0433e7be5.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod.Working as expected.

Privacy policy link in footer

![image](https://user-images.githubusercontent.com/55895538/78246411-bbd87480-7506-11ea-9fb8-b037018996a9.png)

Privacy link in challenges page

![image](https://user-images.githubusercontent.com/55895538/78246483-dad70680-7506-11ea-9add-e8013bbcba9f.png)
