### ISSUE TITLE
'Failed to get member stats' error is thrown in dev environment when accessing 'my dashboard'

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3988]
1. Login as nithyaasworld / appirio123 in Dev environment
2. Then go to https://www.topcoder-dev.com/my-dashboard and check

Actual:
It throws error as 'Failed to get member stats'. 

![image](https://user-images.githubusercontent.com/5114190/74331258-50511100-4db9-11ea-9d00-06cef03efd4e.png)

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by lakshmiathreya** [comment]
@sushilshinde

**Comment by urwithat** [comment]
This is on dev

**Comment by SathyaJayabal** [comment]
Verified on dev
<img width="1440" alt="Screenshot 2020-03-06 at 10 59 46 AM" src="https://user-images.githubusercontent.com/58783823/76055423-9dc83480-5f99-11ea-84fa-08b674f017bf.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-06 at 3 20 42 PM" src="https://user-images.githubusercontent.com/58783823/76072493-1640ec80-5fbe-11ea-8de4-40ea81c541ff.png">
