### ISSUE TITLE
Member profile page is not loading in Dev Env

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3991]
1. Go to Member profile page in Dev Env. Example: https://www.topcoder-dev.com/members/winterflame
2. Check

Actual:
It is displaying blank page. It happens only in Dev. Whereas in Production, it works good.

![image](https://user-images.githubusercontent.com/5114190/74400948-a8cdf000-4e45-11ea-972b-5ee9fc026a0d.png)

**Comment by nithyaasworld** [comment]
@urwithat Kindly review and remove the _member-service-api-issue_ label if its not related to member-service api. Thanks.

**Comment by nithyaasworld** [comment]
cc: @lakshmiathreya

**Comment by SathyaJayabal** [comment]
this issue is fixed now
<img width="1440" alt="Screenshot 2020-03-04 at 2 32 37 PM" src="https://user-images.githubusercontent.com/58783823/75862476-05a93e80-5e25-11ea-9648-2cad764e1426.png">
