### ISSUE TITLE
Associate User Statistics with Groups

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#3992]
Link to feature
https://docs.google.com/document/d/1imQHvjV3rsNNv4pjILhc3oNjVPOp68oVxk5hfihyHzw/edit

**Comment by SathyaJayabal** [comment]
Feature deployed on test env, but not able to verify the member profile page in topgear  community.
<img width="1428" alt="Screenshot 2020-02-13 at 12 18 27 PM" src="https://user-images.githubusercontent.com/58783823/74409199-42080100-4e5c-11ea-824e-686155f93e9b.png">
![image](https://user-images.githubusercontent.com/58783823/74409234-5ba94880-4e5c-11ea-95c5-d717ad7ed323.png)

**Comment by SathyaJayabal** [comment]
The data in the member profile page and the member stats page is not filtered based on the community
<img width="1428" alt="Screenshot 2020-02-19 at 2 47 29 PM" src="https://user-images.githubusercontent.com/58783823/74819817-f7d4c300-5326-11ea-85bf-374775f35e11.png">
<img width="1428" alt="Screenshot 2020-02-19 at 2 48 31 PM" src="https://user-images.githubusercontent.com/58783823/74819820-f99e8680-5326-11ea-8973-5893a76ff142.png">

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, FYI public stats would be everything without a group. Can you please update QA tags based on new clarification? 
@ajefts

**Comment by SathyaJayabal** [comment]
@SathyaJayabal, FYI public stats would be everything without a group. 

@Oanh-and-only-Oanh , I don't understand the above statement. Can you please elaborate ?

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, public stats would be everything without a GROUPID. I believer member stats end point identifier for public stats is `0`

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, please see correction to above statement.
If there are no groups passed in then it should return public data.

**Comment by SathyaJayabal** [comment]
Not able to test the profile page due to 404 error

<img width="1440" alt="Screenshot 2020-02-27 at 8 23 48 PM" src="https://user-images.githubusercontent.com/58783823/75455653-9f916700-599f-11ea-82ff-8c13c20e74f7.png">

**Comment by LieutenantRoger** [comment]
Moving it to `Dev QA` as related issues are resolved, thanks.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger 
On comparing the public stats and community specific stats for the SRM detail pages 
https://community-app.topcoder-dev.com/__community__/wipro/members/Standlove/details/?track=DATA_SCIENCE&subTrack=SRM
https://community-app.topcoder-dev.com/members/Standlove/details/?track=DATA_SCIENCE&subTrack=SRM

1. The topgear rating history graph displays the public data. 
<img width="1435" alt="Screenshot 2020-03-02 at 6 48 30 PM" src="https://user-images.githubusercontent.com/58783823/75680028-b2b17900-5cb6-11ea-950e-6028f231ada1.png">


2. Also the active challenges count on the top right is also the same for both the pages.
<img width="1421" alt="Screenshot 2020-03-02 at 6 47 32 PM" src="https://user-images.githubusercontent.com/58783823/75680036-b80ec380-5cb6-11ea-8f33-b28fff672e44.png">

3. The topgear details section just shows a 0

<img width="1440" alt="Screenshot 2020-03-02 at 6 47 52 PM" src="https://user-images.githubusercontent.com/58783823/75680049-bba24a80-5cb6-11ea-9724-7666978c3d9a.png">
<img width="1440" alt="Screenshot 2020-03-02 at 6 49 41 PM" src="https://user-images.githubusercontent.com/58783823/75680055-bcd37780-5cb6-11ea-992a-40351c0e39cc.png">

**Comment by LieutenantRoger** [comment]
Thanks @SathyaJayabal ,  I believe these are due to the mock data are in-correct.  I'll ask upbeat to take a look.

**Comment by urwithat** [comment]
The data is mocked for now, for this we will need to test with production data

**Comment by SathyaJayabal** [comment]
Awaiting mocking of correct data in dev so that we can test the various profile detail pages.

**Comment by SathyaJayabal** [comment]
Verified on dev env
Testing with user thomaskranitsas for the topcoder, topgear, cognitive communities. Compared the data on the profile with the data returned by members api.
Note: Profile history pages are not available for private groups. 

<img width="1440" alt="Screenshot 2020-03-04 at 11 06 46 AM" src="https://user-images.githubusercontent.com/58783823/75848531-7b52e180-5e08-11ea-9c8d-5188d68a4e86.png">

<img width="1440" alt="Screenshot 2020-03-04 at 11 06 38 AM" src="https://user-images.githubusercontent.com/58783823/75848527-79891e00-5e08-11ea-9d20-07f46f2165c5.png">



<img width="1440" alt="Screenshot 2020-03-04 at 11 06 31 AM" src="https://user-images.githubusercontent.com/58783823/75848517-74c46a00-5e08-11ea-84c4-81ef694c09b5.png">

**Comment by SathyaJayabal** [comment]
There seems to be an integration issue. When the user clicks on the my profile link from their username drop down menu (in the respective community sites), they are directed to the public stats page. They should be directed to the respective community profile page
[profile.mov.zip](https://github.com/topcoder-platform/community-app/files/4287254/profile.mov.zip)

**Comment by SathyaJayabal** [comment]
Verified on dev (develop branch)
Note: Only topgear community is in scope.
<img width="1440" alt="Screenshot 2020-03-05 at 1 06 33 PM" src="https://user-images.githubusercontent.com/58783823/75958742-dd801500-5ee2-11ea-8dd1-8913b903965d.png">
<img width="1440" alt="Screenshot 2020-03-05 at 1 06 37 PM" src="https://user-images.githubusercontent.com/58783823/75958752-e244c900-5ee2-11ea-8a40-46f5c9d2be3e.png">
<img width="1440" alt="Screenshot 2020-03-05 at 1 06 46 PM" src="https://user-images.githubusercontent.com/58783823/75958756-e375f600-5ee2-11ea-8c85-c86fffa12719.png">
<img width="1440" alt="Screenshot 2020-03-05 at 1 06 51 PM" src="https://user-images.githubusercontent.com/58783823/75958759-e53fb980-5ee2-11ea-9daf-3d891a43ebb8.png">
<img width="1440" alt="Screenshot 2020-03-05 at 1 09 14 PM" src="https://user-images.githubusercontent.com/58783823/75958762-e5d85000-5ee2-11ea-953f-ade068c44b84.png">

**Comment by SathyaJayabal** [comment]
verified on prod
topgear profile
<img width="1626" alt="Screenshot 2020-03-06 at 1 40 36 PM" src="https://user-images.githubusercontent.com/58783823/76073062-0d9ce600-5fbf-11ea-9564-be89a1ab5b7b.png">

topgear empty profile
<img width="1573" alt="Screenshot 2020-03-06 at 2 40 11 PM" src="https://user-images.githubusercontent.com/58783823/76072894-c6165a00-5fbe-11ea-9787-a029bac3d85a.png">

public profile
<img width="1440" alt="Screenshot 2020-03-06 at 3 28 10 PM" src="https://user-images.githubusercontent.com/58783823/76073123-2a391e00-5fbf-11ea-8ce2-1abb0239e9a8.png">

public profile : subtrack/history page:
<img width="1440" alt="Screenshot 2020-03-06 at 3 29 01 PM" src="https://user-images.githubusercontent.com/58783823/76073225-46d55600-5fbf-11ea-8ad1-6f41794439e6.png">

public empty profile:
<img width="1440" alt="Screenshot 2020-03-06 at 3 29 58 PM" src="https://user-images.githubusercontent.com/58783823/76073295-62d8f780-5fbf-11ea-89cd-538d077ef85c.png">
