### ISSUE TITLE
Accomodate the member stats API change in the legacy topcoder app

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#3999]
**Describe the bug**

We currently updated the member stats API to return the stats data as an array in the content field in the response. 

We need to update the legacy member profile page to accommodate the new API stats change. 

**To Reproduce**
Visit `https://www.topcoder.com/search/members/?q=upbeat` and click upbeat to go to member profile screen. 

**Expected behavior**
The app should work just like before.

**Comment by LieutenantRoger** [comment]
Challenge Link to address this feature: https://www.topcoder.com/challenges/30115866/?type=develop

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-02-27 at 8 35 33 PM" src="https://user-images.githubusercontent.com/58783823/75456616-c1d7b480-59a0-11ea-87bc-03218b2eee57.png">
<img width="1440" alt="Screenshot 2020-02-27 at 8 35 37 PM" src="https://user-images.githubusercontent.com/58783823/75456644-cb611c80-59a0-11ea-8acd-4fa14ad616de.png">

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-03-06 at 11 28 02 AM" src="https://user-images.githubusercontent.com/58783823/76056831-930f9e80-5f9d-11ea-85f1-d08bb95e56f7.png">
<img width="1440" alt="Screenshot 2020-03-06 at 11 28 07 AM" src="https://user-images.githubusercontent.com/58783823/76056839-9a36ac80-5f9d-11ea-8428-acd8b5240441.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-06 at 3 19 25 PM" src="https://user-images.githubusercontent.com/58783823/76072373-e396f400-5fbd-11ea-8ea6-2262f21fb732.png">
