### ISSUE TITLE
Separate line is moving when we toggle the challenge type radio option

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#4000]
**Describe the bug**

The separate line is moving when we toggle the challenge type.

**To Reproduce**
1. Go to 'www.topcoder.com/challenges'
2. Click on 'Filter' button to open up the filter panel
3. Toggle on/off the challenge type radio button
4. See the separate line is moving right/left upon step 3.

**Expected behavior**
The separate line on the filter panel should not move right/left when we toggle the challenge type button.

**Screenshots**
https://take.ms/qCoLj

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 79

**Comment by sandhiyakavi** [comment]
This issue is not applicable now.
