### ISSUE TITLE
New Feature - Related challenge suggestions on challenge details page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4001]
http://www.topcoder.com/challenges/30113877
https://www.topcoder.com/challenges/30114285
https://www.topcoder.com/challenges/30115205

**Comment by SathyaJayabal** [comment]
tracked here
https://github.com/topcoder-platform/community-app/issues/3565
https://github.com/topcoder-platform/community-app/issues/3620
