### ISSUE TITLE
Member search result page bugs

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#4010]
**Describe the bug**

When searching for a term (ex: upbeat) the `result.metadata.totalCount` at first is 10 and the list shows 10 results (there are 12 matched items totally), then if the user clicks on any item to navigate to the profile page and click the back button of the browser to come back, the number of results is displayed as 2 but it actually shows 12 matched items. If continue clicking an item and come back again, the `End of results` disappears. Should we keep migrating these behaviour as it is?

https://take.ms/Ehboq

Note: when loading more, `result.metadata.totalCount` is always the number of returned results (which is <= 10, even there are many matched results, ex: https://www.topcoder.com/search/members/?q=github => 53 results totally)

**To Reproduce**

Please see above description.

**Expected behavior**

**Additional context**

The bugs were found in this challenge:
http://www.topcoder.com/challenge-details/30115867/?type=develop

We have migrated the corresponding screen to community app as is.
So presumably the migrated member search screens have similar bugs which we need to resolve.

**Comment by Oanh-and-only-Oanh** [comment]
@LieutenantRoger, please launch challenge to resolve this after we release private stats to PROD.

**Comment by LieutenantRoger** [comment]
Hi @Oanh-and-only-Oanh 

After some discussion with @urwithat , this ticket seems not an issue.  
It seems by design that we only show top 10 result returned if there are more than 10 result.

Could you please take a more deep look about whether there's issue on this screen  ?  

Thank you.

**Comment by LieutenantRoger** [comment]
Also, please take a look at below steps as well to see if this is a valid issue on this screen: 

1. visit https://www.topcoder.com/search/members/?q=java (note, at bottom table, it shows 10 results)
2. click the first member card in the result list at the top table, then click <- button in the browser to go back to the search result screen.
3. scroll down to the bottom table, it still display 10 results, but the actual row records are more than 10.)

**Comment by Oanh-and-only-Oanh** [comment]
Looks like this is not a valid issue. Closing ticket.
