### ISSUE TITLE
My earning and my stats fix on My Dashboard screen

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#4012]
**Describe the bug**
My earning and stats is not displaying correct data on `My Dashboard` screen.

**To Reproduce**
Visit www.topcoder.com/my-dashboard, the my-earning section is loading data forever.

**Expected behavior**
My earning and stats section should display correct data.

**Screenshots**
https://take.ms/RvPcAs

**Additional context**
The work should be down against `hot-fix-my-earnings`

**Comment by SathyaJayabal** [comment]
tracked here #3300
