### ISSUE TITLE
Update Newsletter Signup Button

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4017]
The way the newsletter signup button is developed uses the old style and shows up as a blue button.  We need to update it to a green button similar to the "How To Qualify" section here: https://tco20.topcoder.com/regional-events/north-america

**Comment by SathyaJayabal** [comment]
@kkartunov , where can we find the newsletter signup button?

**Comment by kkartunov** [comment]
@SathyaJayabal on the track pages like for instance http://beta-community-app.topcoder.com/community/data-science It won't let you click it if your test user is registered already.  I guess try in incognito and with different users....

**Comment by SathyaJayabal** [comment]
@kkartunov , the disabled state of the button looks a bit odd. Do you have the design spec for it ?
<img width="423" alt="Screenshot 2020-02-25 at 10 23 56 PM" src="https://user-images.githubusercontent.com/58783823/75268497-92e50580-581d-11ea-9328-ea056825cd4c.png">

**Comment by kkartunov** [comment]
Yes, it is and was aways here https://zeroheight.com/1g0pfacwv/p/4098cf-buttons--links/b/62b18f

**Comment by SathyaJayabal** [comment]
@kkartunov , Thank you

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1430" alt="Screenshot 2020-02-26 at 2 47 26 PM" src="https://user-images.githubusercontent.com/58783823/75330384-02eb9e00-58a7-11ea-8291-89e7f1b25752.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-02-28 at 10 59 38 AM" src="https://user-images.githubusercontent.com/58783823/75513040-731a3100-5a19-11ea-9cd1-275dad5aa1fe.png">

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2020-02-28 at 3 51 17 PM" src="https://user-images.githubusercontent.com/58783823/75540530-3adb1880-5a42-11ea-9db0-3dc2e85fa586.png">
