### ISSUE TITLE
Format text spacing properly

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4018]
- change css for `<p>` tags to have `margin-bottom:20px`
- update margin-top and margin-bottom for H1-H6

**Comment by kkartunov** [comment]
@SathyaJayabal ready for prod QA.
spec: https://marvelapp.com/535c9ga/screen/66613451
test: http://beta-community-app.topcoder.com/examples/contentful/article/23IwNHJaMnKJYp50QD8Aaj?space=EDU

**Comment by SathyaJayabal** [comment]
Verified in beta
<img width="1378" alt="Screenshot 2020-02-25 at 10 35 11 PM" src="https://user-images.githubusercontent.com/58783823/75269595-2cf97d80-581f-11ea-9c5f-92df4e23083c.png">
<img width="1387" alt="Screenshot 2020-02-25 at 10 35 21 PM" src="https://user-images.githubusercontent.com/58783823/75269609-3387f500-581f-11ea-9162-5f5b2c9eeb5e.png">

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
<img width="1427" alt="Screenshot 2020-02-26 at 2 45 22 PM" src="https://user-images.githubusercontent.com/58783823/75330207-c15af300-58a6-11ea-95cc-493e72b58c39.png">
<img width="1429" alt="Screenshot 2020-02-26 at 2 45 37 PM" src="https://user-images.githubusercontent.com/58783823/75330256-c5871080-58a6-11ea-94e9-57b72a100378.png">

**Comment by SathyaJayabal** [comment]
verified on beta

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2020-02-28 at 3 43 19 PM" src="https://user-images.githubusercontent.com/58783823/75540423-05362f80-5a42-11ea-8f2b-280afe564b74.png">
<img width="1440" alt="Screenshot 2020-02-28 at 3 43 26 PM" src="https://user-images.githubusercontent.com/58783823/75540433-0a937a00-5a42-11ea-86aa-655ca7c1c245.png">
