### ISSUE TITLE
Images in Thrive articles

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4019]
- Apply `max-width: 70%`  to images in the articles details page.

**Comment by SathyaJayabal** [comment]
@kkartunov , any examples to test ?

**Comment by kkartunov** [comment]
@SathyaJayabal yes here https://beta-community-app.topcoder.com/examples/contentful/article/23IwNHJaMnKJYp50QD8Aaj?space=EDU

**Comment by SathyaJayabal** [comment]
verified
<img width="1427" alt="Screenshot 2020-02-26 at 8 44 05 AM" src="https://user-images.githubusercontent.com/58783823/75308325-2fd28d80-5874-11ea-86d8-a2dbfc7f978d.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1431" alt="Screenshot 2020-02-26 at 2 49 25 PM" src="https://user-images.githubusercontent.com/58783823/75330507-3af2e100-58a7-11ea-8d5c-7b8e9dec7a7f.png">

**Comment by SathyaJayabal** [comment]
verified on beta

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2020-02-28 at 3 45 27 PM" src="https://user-images.githubusercontent.com/58783823/75540146-7cb78f00-5a41-11ea-8355-d8038b9907d5.png">
