### ISSUE TITLE
New Navi integration to Contentful

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4020]
New Navi integration should remove BUSSINESS & COMMUNITY menu items to look more closely to https://marvelapp.com/5554efd/screen/65173641

Test url: https://community-app.topcoder.com/examples/contentful/viewport/1nvm6EsPMHPLBtuGXNRMYV

**Comment by kkartunov** [comment]
prod test url is here @SathyaJayabal http://beta-community-app.topcoder.com/examples/contentful/viewport/1nvm6EsPMHPLBtuGXNRMYV

**Comment by SathyaJayabal** [comment]
After clicking on a menu item, the menu gets reloaded and the does not show the correct selected menu.

https://drive.google.com/open?id=1YM1bwDIFlkQ_YIQAzklPyLe4iUvjpf4f

The new nav is https://drive.google.com/open?id=1YM1bwDIFlkQ_YIQAzklPyLe4iUvjpf4f
<img width="1423" alt="Screenshot 2020-02-25 at 10 56 21 PM" src="https://user-images.githubusercontent.com/58783823/75271399-21f41c80-5822-11ea-8c7e-cab907dc45c4.png">
 different from the one in the design. Do you have an updated design
<img width="1428" alt="Screenshot 2020-02-25 at 10 56 07 PM" src="https://user-images.githubusercontent.com/58783823/75271387-1dc7ff00-5822-11ea-940f-04aab64412a0.png">

**Comment by SathyaJayabal** [comment]
After clicking on a menu item, the menu gets reloaded and the does not show the correct selected menu.

https://drive.google.com/open?id=1YM1bwDIFlkQ_YIQAzklPyLe4iUvjpf4f

The new nav is  different from the one in the design. Do you have an updated design
https://drive.google.com/open?id=1YM1bwDIFlkQ_YIQAzklPyLe4iUvjpf4f
<img width="1423" alt="Screenshot 2020-02-25 at 10 56 21 PM" src="https://user-images.githubusercontent.com/58783823/75271399-21f41c80-5822-11ea-8c7e-cab907dc45c4.png">

<img width="1428" alt="Screenshot 2020-02-25 at 10 56 07 PM" src="https://user-images.githubusercontent.com/58783823/75271387-1dc7ff00-5822-11ea-940f-04aab64412a0.png">

**Comment by kkartunov** [comment]
@SathyaJayabal this is all fine and controllable from Contentful. You should just confirm that it looks like in the design. In prod, links will not reload and will have different organizations.

So please update this one. Thanks!

**Comment by hokienick** [comment]
@SathyaJayabal - As @kkartunov mentioned, he has just updated the functionality and design of this navigation bar to align with our marketing navigation.

In this environment the navigation will not direct you to the appropriate page because it is just an example viewport with the menu overlayed on top so that we can see that the animations and the format are to our liking.

The reason the navigation reloads each time is because the link changes every time because it is faked with a prefix.  Once this is in production, it will not have these issues.  We do need this in the next release please.

**Comment by SathyaJayabal** [comment]
@hokienick , I am marking this as pass based on above comments.

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
<img width="1430" alt="Screenshot 2020-02-26 at 2 43 26 PM" src="https://user-images.githubusercontent.com/58783823/75329870-7214c280-58a6-11ea-81c8-7031422abb76.png">

**Comment by SathyaJayabal** [comment]
verified on beta 
<img width="1438" alt="Screenshot 2020-02-28 at 10 57 39 AM" src="https://user-images.githubusercontent.com/58783823/75512960-2e8e9580-5a19-11ea-8894-d9c3fb7ee1fb.png">

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1439" alt="Screenshot 2020-02-28 at 3 48 01 PM" src="https://user-images.githubusercontent.com/58783823/75540297-c30cee00-5a41-11ea-8247-2c625d18c4e0.png">
