### ISSUE TITLE
Add "React Native" as a Challenge Tag

### ISSUE THREAD

**Issue by crazyk07** [topcoder-platform/community-app#4022]
**Is your feature request related to a problem? Please describe.**
React Native tag is not an available tag.  React Native is a framework, React js is something different.

**Describe the solution you'd like**
Add "React Native" as a challenge tag

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by crazyk07** [comment]
@Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
added tag to spreadsheet https://docs.google.com/spreadsheets/d/1FGP7Ly9JFHtaXP9F_InSJT8Qyb9E5t3zTASoQTcyMww/edit#gid=0
