### ISSUE TITLE
Challenge detail page issue in the dev environment.

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#4026]
**Describe the bug**
Visit the challenge detail page in `dev` environment, e.g: 
https://www.topcoder-dev.com/challenges/30055960

We spot this issue showed up: 
https://monosnap.com/file/hK83lc5M6hp4OsxxUdTufOXNTpWO76

**To Reproduce**
1. Visit a challenge detail link in `dev` environment
2. Open up the console and observe

**Expected behavior**
The challenge related page should be rendered correctly.

**Screenshots**
https://monosnap.com/file/hK83lc5M6hp4OsxxUdTufOXNTpWO76

**Additional context**
The work should be done against: `hot-fix-challenge-page`

**Comment by LieutenantRoger** [comment]
Made a new test release of `topcoder-react-lib` resolved this ticket.  The new lib is under testing, I'll move the ticket to `Dev QA` accordingly

**Comment by SathyaJayabal** [comment]
verified on dev env
<img width="1440" alt="Screenshot 2020-03-04 at 6 15 45 PM" src="https://user-images.githubusercontent.com/58783823/75880912-377dcd80-5e44-11ea-8dd3-d43e70e55a31.png">
@LieutenantRoger , as this problem happens only on dev env, I am closing this issue.
