### ISSUE TITLE
Toolbox feature in Challenge Details page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#4029]
Add "Toolbox" area in the sidebar if challenge details page to promote: 

# "Topcoder Extension for VSCode"

When clicked on, takes user to <https://marketplace.visualstudio.com/items?itemName=Topcoder.topcoder-workflow&ssr=false#overview>

**Comment by ajefts** [comment]
Link to subfeature: https://tcprod.productboard.com/feature-board/planning/features/4021530

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh 

This the updated source code and preview on local.topcoder-dev.com

![4029-1](https://user-images.githubusercontent.com/4476442/95946128-1b003580-0e16-11eb-99d4-8f1579d58c03.png)
![4029-2](https://user-images.githubusercontent.com/4476442/95946131-1d628f80-0e16-11eb-849f-46e1ff740ead.png)
![4029-3](https://user-images.githubusercontent.com/4476442/95946135-1f2c5300-0e16-11eb-80b8-5772c6f461ff.png)
![4029-4](https://user-images.githubusercontent.com/4476442/95946140-20f61680-0e16-11eb-9d55-a95bc5b2a7dd.png)

Please let me know for any feedback.

**Comment by Oanh-and-only-Oanh** [comment]
@dedywahyudi
1) This link should open in new tab
2) This links should be available for all challenge tracks and types
3) Please add tooltip to show "shortcuts to perform actions related to the Topcoder platform without having to open a browser' on hovering over link

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh 

2. So, need show up for Design challenges as well?

**Comment by dedywahyudi** [comment]
![Screen Shot 2020-10-14 at 22 26 41](https://user-images.githubusercontent.com/4476442/96010810-6e04d780-0e6c-11eb-9429-951ee0a6c832.png)
![Screen Shot 2020-10-14 at 22 26 45](https://user-images.githubusercontent.com/4476442/96010818-6fce9b00-0e6c-11eb-8325-f94772a998b3.png)

@Oanh-and-only-Oanh how about this updated solution?

**Comment by SathyaJayabal** [comment]
Verified on staging, appears for all types of challenges including design.
<img width="1440" alt="Screenshot 2020-10-15 at 11 04 49 AM" src="https://user-images.githubusercontent.com/58783823/96081177-61b56480-0ed6-11eb-9ff0-d7421893ac16.png">
<img width="1440" alt="Screenshot 2020-10-15 at 11 04 51 AM" src="https://user-images.githubusercontent.com/58783823/96081187-6c6ff980-0ed6-11eb-9be1-11acef0e5b5e.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-11-03 at 2 18 52 PM" src="https://user-images.githubusercontent.com/58783823/97964948-9b93cf80-1ddf-11eb-9a91-cdbd805ecf91.png">
<img width="1440" alt="Screenshot 2020-11-03 at 2 18 57 PM" src="https://user-images.githubusercontent.com/58783823/97964963-a2224700-1ddf-11eb-8209-7b25a7b237f1.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-03 at 5 22 29 PM" src="https://user-images.githubusercontent.com/58783823/97982055-38169b80-1df9-11eb-98d4-2c97fefa5d05.png">
