### ISSUE TITLE
Toolbox feature

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#4030]
Add "Toolbox" area in the sidebar if challenge details page to promote: 

# "Topcoder Extension for VSCode"

When clicked on, takes user to <https://marketplace.visualstudio.com/items?itemName=Topcoder.topcoder-workflow&ssr=false#overview>

**Comment by ajefts** [comment]
Link to subfeature: https://tcprod.productboard.com/feature-board/planning/features/4021530

**Comment by Oanh-and-only-Oanh** [comment]
duplicate
