### ISSUE TITLE
API Errors on challenge pages

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#4031]
**Describe the bug**
I'm seeing API errors when loading challenge pages.  The error is on API calls like this:  https://api.topcoder.com/v4/challenges/?filter=status%3DACTIVE%26technologies%3D&limit=50&offset=0

**To Reproduce**
1. Go to  any challenge page
2. Check errors in the console

**Comment by ajefts** [comment]
@Oanh-and-only-Oanh @sushilshinde fyi

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya, can you verify if this is still an issue?

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya, what's the end user impact of this error here? If there isn't an impact, can you please close?

**Comment by lakshmiathreya** [comment]
This error is not seen. The api call returns success.
