### ISSUE TITLE
Broadcast Notifications Backend

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4033]

**Comment by Oanh-and-only-Oanh** [comment]
Please verify in the dev backend.

**Test #1**- let's do the following broadcast message: "Topcoder Bug Hunt now live. Join the hunt today!"
Recipient group: Members who have QA as a skill
**Test #2**- let's do the following broadcast message: "Mark you calendars, registration opens March 30 for next MM." 
Recipient group: Members who are part of Competitive Programming track

Additional recipient groups may include:

- All public members
- Members in each of the following tracks- QA, Dev, Competitive Programming, Design 
- Members with "X" skill (ie Node.js) in profile.

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , can you please help me test this functionality?

**Comment by sachin-maheshwari** [comment]
{
 "topic": "admin.notification.broadcast",
 "originator": "admin-app-postman",
 "timestamp": "2020-02-26T11:32:08.214Z",
 "mime-type": "application/json",
 "payload": {
 	"message" : "Topcoder Bug Hunt now live. Join the hunt today!",
 	"recipients": {
 		"groups":  [], 
 		"skills" : ["qa"],
 		"tracks" : []
 	}
 }
}
{
 "topic": "admin.notification.broadcast",
 "originator": "admin-app-postman",
 "timestamp": "2020-02-26T11:34:08.214Z",
 "mime-type": "application/json",
 "payload": {
 	"message" : "Mark you calendars, registration opens March 30 for next MM.",
 	"recipients": {
 		"groups":  [], 
 		"skills" : [],
 		"tracks" : ["DATA_SCIENCE"]
 	}
 }
}
I pushed the above messages as mentioned.

**Comment by sachin-maheshwari** [comment]
Please note - on DEV "QA" skill is not available. So for testing purpose I am pushing same message for "Node.js" skill to test it.   
{
 "topic": "admin.notification.broadcast",
 "originator": "admin-app-postman",
 "timestamp": "2020-02-26T11:34:08.214Z",
 "mime-type": "application/json",
 "payload": {
 	"message" : "Topcoder Bug Hunt now live. Join the hunt today!",
 	"recipients": {
 		"groups":  [], 
 		"skills" : ["Node.js"],
 		"tracks" : []
 	}
 }
}

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , Will we be able to see this notification in the notifications popup on the front end?

@sachin-maheshwari @lakshmiathreya , How can we test if this notification is available to the target users?

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  not sure if that will be able on community front-end pop-up or not.  

You can find it in backend api response by using your JWT "user-token".  For example - https://api.topcoder-dev.com/v5/notifications/list?read=false   or https://api.topcoder-dev.com/v5/notifications/list?read=false&platform=community&per_page=2  
Response would be like - 
{
    "items": [
        {
            "id": 106739,
            "userId": 40153932,
            "type": "admin.notification.broadcast",
            "contents": {
                "id": "6",
                "group": "broadcast",
                "title": "Broadcast Message",
                "message": "message2 : This is new broadcast for 'Cognitive' group"
            },
            "read": false,
            "seen": false,
            "version": null,
            "createdAt": "2020-02-20T12:07:56.132Z",
            "updatedAt": "2020-02-20T12:07:56.132Z"
        }.....

I think, need to incorporate the broadcast message structure in front-end.

**Comment by sachin-maheshwari** [comment]
Just further explaining the  broadcast message design - 
case #1 - "Topcoder Bug Hunt now live. Join the hunt today!"
Recipient group: Members who have QA as a skill 

@Oanh-and-only-Oanh  As per my interpretation on this - you want to send this message to all public QA member. correct ? 
If yes, i designed the message like this -  
{
"topic": "admin.notification.broadcast",
"originator": "admin-app-postman",
"timestamp": "2020-02-26T11:32:08.214Z",
"mime-type": "application/json",
"payload": {
"message" : "Topcoder Bug Hunt now live. Join the hunt today!",
"recipients": {
"groups": [],
"skills" : ["qa"],
"tracks" : []
}
}
}
So it'll send all public member only, not any private member. 

For sending message to private/specific group, we need to mention in "groups" field as "," separated like -  same message can be send for community member who is part of any group 'A' , 'B' or 'C'
{
"topic": "admin.notification.broadcast",
"originator": "admin-app-postman",
"timestamp": "2020-02-26T11:32:08.214Z",
"mime-type": "application/json",
"payload": {
"message" : "Topcoder Bug Hunt now live. Join the hunt today!",
"recipients": {
"groups": ["A", "B", "C"],
"skills" : ["qa"],
"tracks" : []
}
}
}

**Comment by Oanh-and-only-Oanh** [comment]
@sachin-maheshwari, correct to your question above.

**Comment by sachin-maheshwari** [comment]
I just want to confirm the definition of "public" member in our Topcoder system. As per me, public member will not belong **any** "private group". correct ?

**Comment by SathyaJayabal** [comment]
Verified the various tracks, groups and skills filter in dev backend.
