### ISSUE TITLE
Community sub menus are not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4036]
The community sub menu is not displayed in the dev/test/beta envs
<img width="1430" alt="Screenshot 2020-02-26 at 3 25 49 PM" src="https://user-images.githubusercontent.com/58783823/75333540-4e547b00-58ac-11ea-9f85-d1945907fa54.png">
Also clicking on the topcoder logo in the menu takes the user to the 404 page 
(https://beta-community-app.topcoder.com/undefined)
<img width="1425" alt="Screenshot 2020-02-26 at 3 26 45 PM" src="https://user-images.githubusercontent.com/58783823/75333641-81970a00-58ac-11ea-89dd-687fe1dac530.png">

**Comment by SathyaJayabal** [comment]
cc @sushilshinde

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This one was fixed.

Not a real issue, the problem was not merged the **community-app** branch together with **navigation-component**

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , thank you for the quick solution on this one.
