### ISSUE TITLE
Add TaaS page to navigation menu

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#4037]
**Expected**: Add TaaS page to Community 

Requirements   
1) URL <https://www.topcoder.com/community/member-programs/taas> should change to this new URL [https://www.topcoder.com/community/taas](https://www.topcoder.com/taas) 

2) Add TaaS to menu on the main navigation under "Compete" next to Competitive Programming 

3) TaaS should be visible to all users (logged-in and logged-out states)

![](https://productboard-files.s3.amazonaws.com/production/attachments/13881a286a454b21da772f8c06b0670c2c3a250ba685de25bed3fe880c0f6b1d/image.png)

<p></p>

<p></p>

<p></p>

<p></p>

**Comment by ajefts** [comment]
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/4044407

**Comment by luizrrodrigues** [comment]
https://github.com/topcoder-platform/community-app/tree/feature-nav-taas

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2020-03-02 at 9 33 07 AM" src="https://user-images.githubusercontent.com/58783823/75644750-4eb49380-5c69-11ea-8c44-354556c12bf4.png">
<img width="1440" alt="Screenshot 2020-03-02 at 9 33 26 AM" src="https://user-images.githubusercontent.com/58783823/75644758-56743800-5c69-11ea-8c4a-fa25e2b1c68b.png">

**Comment by drasticdpk** [comment]
Verified on Beta Env :
![image](https://user-images.githubusercontent.com/25297859/76206744-b009d300-6224-11ea-908f-6830563c5817.png)

But there is typo on Taas page. Shall I create new issue for it or we can fix here too ?  cc @luizrrodrigues @SathyaJayabal 
![image](https://user-images.githubusercontent.com/25297859/76207389-cd8b6c80-6225-11ea-8a31-6f480289af96.png)

**Comment by lakshmiathreya** [comment]
verified on Beta - but the typo "technolgies" called out above is still there - should be fixed.
<img width="1658" alt="Screenshot 2020-03-09 at 5 13 24 PM" src="https://user-images.githubusercontent.com/51733042/76210082-5d7ee580-6229-11ea-9815-8e54a188bae7.png">

**Comment by sushilshinde** [comment]
@luizrrodrigues please check

**Comment by luizrrodrigues** [comment]
@drasticdpk Yes, please create a new ticket, the issue not related to this one.

@sushilshinde looks like double QA in this one:
> verified on Beta - but the typo "technolgies" called out above is still there - should be fixed.

This was a comment about previous QA (37min ago), so the "still there" no valid. :D

**Comment by macs054** [comment]
Verified in Prod
![image](https://user-images.githubusercontent.com/1199534/76390907-4109b700-63a9-11ea-8388-158a6de6bc98.png)
