### ISSUE TITLE
Notifications Listings - When click in any link/button in this page showing blue border

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4040]
**Describe the bug**
Notifications Listings - When click in any link/button in this page showing blue border

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/7029641/75490614-3c013c80-5993-11ea-8485-ee66a3a13551.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari, Chrome and Edge
 - Version: Latest

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1437" alt="Screenshot 2020-03-03 at 9 32 36 AM" src="https://user-images.githubusercontent.com/58783823/75742301-3f9a1800-5d33-11ea-8057-dc020db37513.png">

**Comment by SathyaJayabal** [comment]
verified on beta (develop)
<img width="1440" alt="Screenshot 2020-03-30 at 1 52 59 PM" src="https://user-images.githubusercontent.com/58783823/77892471-49f6f580-7290-11ea-97d4-1b5e2fc17d77.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-30 at 5 38 46 PM" src="https://user-images.githubusercontent.com/58783823/77910790-59386c00-72ad-11ea-81a9-b6b464fac91d.png">
