### ISSUE TITLE
Notifications Listings page - Tab need be aligned to left

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4041]
**Describe the bug**
Notifications Listings page - Tab need be aligned to left

**Expected behavior**
Please check design: https://marvelapp.com/89423f8/screen/65608868

**Screenshots**
![image](https://user-images.githubusercontent.com/7029641/75491259-6f909680-5994-11ea-8179-2b7493f91c0d.png)

**Comment by SathyaJayabal** [comment]
verified on test
<img width="448" alt="Screenshot 2020-03-03 at 9 31 11 AM" src="https://user-images.githubusercontent.com/58783823/75741823-c1894180-5d31-11ea-9b7f-ba52a7026c84.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="1440" alt="Screenshot 2020-03-30 at 1 52 59 PM" src="https://user-images.githubusercontent.com/58783823/77892362-25028280-7290-11ea-9a3e-184d5fb0a309.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-30 at 5 38 46 PM" src="https://user-images.githubusercontent.com/58783823/77910996-b46a5e80-72ad-11ea-951b-150a7a8370b4.png">
