### ISSUE TITLE
Leaderboard Details Modal - new design

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4050]
Modal for the leaderboards detail screen, so when the user clicks on a member's name, he will see this popup: https://marvelapp.com/5554efd/screen/66555017

**Comment by kkartunov** [comment]
Notes for QA:
- "TCO Points" should be just "Points"

**Comment by Jobee1** [comment]
When the user clicks on the member's name new tab is opened with user details.

Attached video for reference:
[4050.zip](https://github.com/topcoder-platform/community-app/files/4562568/4050.zip)

**Comment by kkartunov** [comment]
@Jobee1 yes this is the expected behavior.
Some leaderboards do not have details/history thus they open member profile on click. Modal should open for challenge history details. Check:
- http://tco20.topcoder.com/competition-overview/development/leaderboard
- http://tco20.topcoder.com/competition-overview/algorithm/leaderboard
cc @SathyaJayabal

**Comment by Jobee1** [comment]
Verified in Test Environment.

Attached video for reference.
[4050.zip](https://github.com/topcoder-platform/community-app/files/4562986/4050.zip)

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-05-20 at 12 12 34 PM" src="https://user-images.githubusercontent.com/58783823/82413588-3fd4c480-9a93-11ea-90ca-e9e89a69a248.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-05-21 at 4 22 38 PM" src="https://user-images.githubusercontent.com/58783823/82552225-56f0e080-9b7f-11ea-8325-edb9f9570070.png">
