### ISSUE TITLE
Contentful Codeblocks fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4051]
Scope to fix:

- indentation - breaks for copy/paste code into Contentful
- add line numbering
- make the theme look like on the marketing site

**Comment by kkartunov** [comment]
Look&feel like on blog https://www.topcoder.com/single-round-match-777-editorials/

**Comment by SathyaJayabal** [comment]
@kkartunov , do you the url where these changes could be tested?

**Comment by kkartunov** [comment]
@SathyaJayabal when testing this one note:
- we decided to have different theme from the marketing site thus it looks different
test here https://test-community-app.topcoder-dev.com/examples/contentful/viewport/f7JWRi9xxxsRQItjL1w6e

**Comment by SathyaJayabal** [comment]
Verified on test 

- indentation 
- line numbering

<img width="1436" alt="Screenshot 2020-03-31 at 4 10 24 PM" src="https://user-images.githubusercontent.com/58783823/78017635-2c965a00-736a-11ea-9f8b-8563f14f2e01.png">

**Comment by sandhiyakavi** [comment]
Verified indentation and line numbering in Beta environment,working as expected.

![image](https://user-images.githubusercontent.com/55895538/78218293-2d023280-74db-11ea-82af-590e34c6ce52.png)

**Comment by sandhiyakavi** [comment]
verified in Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/78245923-e7a72a80-7505-11ea-9c05-9b7fe5620f13.png)
