### ISSUE TITLE
 Fix articles cards to NOT render raw HTML

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4052]
Articles cards render raw HTML/markdown in Thrive.

Examples:
- https://www.topcoder.com/thrive/articles/The%20Room%20Summary%20Window - but should be parsed html
- Index cards on track search pages like https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Help%20Articles

**Comment by sandhiyakavi** [comment]
Verified in Test Environment.Working as expected.

<img width="950" alt="articles_parsed_HTML" src="https://user-images.githubusercontent.com/55895538/79742755-44944480-833e-11ea-8618-c1bf0f4e4e27.PNG">

<img width="952" alt="track_search_page" src="https://user-images.githubusercontent.com/55895538/79742783-5544ba80-833e-11ea-96e4-b873518957fd.PNG">

**Comment by sandhiyakavi** [comment]
Verified in Beta. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/79836378-086aed80-83eb-11ea-82ea-b9ba85666d64.png)

![image](https://user-images.githubusercontent.com/55895538/79836555-40723080-83eb-11ea-80ce-c30dd4c52969.png)

**Comment by Jobee1** [comment]
Tested and verified in production environment. 
![Screenshot_15](https://user-images.githubusercontent.com/48575864/79868986-740b8580-8400-11ea-9d08-58d7e971edc2.png)

![Screenshot_16](https://user-images.githubusercontent.com/48575864/79868999-779f0c80-8400-11ea-9a59-8ce4fbdcccb5.png)
