### ISSUE TITLE
Headings on mobile do not work properly as per GUI Kit

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4053]
Will need to fix headings on mobile as per https://marvelapp.com/4f8i35i/screen/61272611/handoff

**Comment by kkartunov** [comment]
Tests:
- community - https://community-app.topcoder.com/examples/contentful/contentblock/x0Qo7c5N1yQELR11LDhdD
- thrive - https://community-app.topcoder-dev.com/examples/contentful/article/7auxO4Dvh5YhPaVpUddPse?space=EDU

**Comment by SathyaJayabal** [comment]
verified on test
<img width="501" alt="Screenshot 2020-03-31 at 2 04 38 PM" src="https://user-images.githubusercontent.com/58783823/78005562-5abf6e00-7359-11ea-87c4-9142026cbcd4.png">
<img width="499" alt="Screenshot 2020-03-31 at 2 09 41 PM" src="https://user-images.githubusercontent.com/58783823/78005569-5dba5e80-7359-11ea-8da8-f7bc2144ef09.png">

**Comment by sandhiyakavi** [comment]
verified on Beta env,working as expected.

<img width="357" alt="font_check1" src="https://user-images.githubusercontent.com/55895538/78216848-608f8d80-74d8-11ea-87b8-3bace32c78e6.PNG">
<img width="303" alt="font_check2" src="https://user-images.githubusercontent.com/55895538/78216853-64231480-74d8-11ea-818a-0ffc919b6e3a.PNG">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="495" alt="Screenshot 2020-04-02 at 5 17 59 PM" src="https://user-images.githubusercontent.com/58783823/78246002-0dccca80-7506-11ea-9386-a35adebd84c2.png">
<img width="503" alt="Screenshot 2020-04-02 at 5 18 10 PM" src="https://user-images.githubusercontent.com/58783823/78246008-12917e80-7506-11ea-8a48-1f68afa06f43.png">
