### ISSUE TITLE
Ability to Sort Newsletter Archives

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4058]
Update [newsletter archives component](https://www.topcoder.com/community/newsletterarchive) to match new design https://marvelapp.com/535c9ga/screen/66441678/handoff

**Comment by Jobee1** [comment]
There is issue in this one.
In the design of the newsletter, there is "Load More" button to load the number of articles but in the test environment, there is scroll bar to scroll the number of articles.

**Attached screenshot for the reference:
As mentioned in the design**:
![Screenshot_38](https://user-images.githubusercontent.com/48575864/80783919-13680f80-8b9b-11ea-9b21-b08045fe3aef.png)

**As displayed in Test Environment:**
![Screenshot_39](https://user-images.githubusercontent.com/48575864/80783928-1d8a0e00-8b9b-11ea-8f89-e1b1cf5e5ff8.png)

**Comment by kkartunov** [comment]
@Jobee1 @SathyaJayabal There won't be "Load More" button. It is out of scope as we decided to load all data in one call and skip load more functionality.

**Comment by Jobee1** [comment]
Verifying this on the basis of the comment in Test environment.

Attached video for reference.
[4058.zip](https://github.com/topcoder-platform/community-app/files/4562998/4058.zip)

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-05-20 at 12 15 10 PM" src="https://user-images.githubusercontent.com/58783823/82413771-93471280-9a93-11ea-9c28-aacf2db3f752.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-05-21 at 4 25 33 PM" src="https://user-images.githubusercontent.com/58783823/82552461-c666d000-9b7f-11ea-97ea-d0cc47a34da4.png">
