### ISSUE TITLE
Add "Title" Filter Option to Thrive and make Default

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4059]
When the "Title" filter is selected Thrive search should search for keyword matches only on the title of articles. Keep existing functionality intact.

**Comment by macs054** [comment]
Verified in Beta
![image](https://user-images.githubusercontent.com/1199534/76606606-823acc00-654d-11ea-9c95-3463e57b6a09.png)

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="1440" alt="Screenshot 2020-03-16 at 9 33 00 AM" src="https://user-images.githubusercontent.com/58783823/76722364-4b410200-6769-11ea-816b-5b3b620ebb60.png">

**Comment by SathyaJayabal** [comment]
verified on production
<img width="1440" alt="Screenshot 2020-03-16 at 3 43 33 PM" src="https://user-images.githubusercontent.com/58783823/76746093-ef906c00-679c-11ea-8246-315a598bb2ee.png">
