### ISSUE TITLE
Style of save / clear fitler buttons in disabled state

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#406]
![screenshot](https://user-images.githubusercontent.com/20144632/29820952-84364618-8cc6-11e7-9f96-8499b15405e9.png)

**Comment by sushilshinde** [comment]
Working on it.

**Comment by birdofpreyru** [comment]
@sushilshinde Current logic behind this buttons is correct: they are disabled when no filters are selected. Sub-community filter is treated as not select in "All" state for the main listing, and when it selects current community, for the listing within a community.

What this ticket says, is that styling of these buttons, when they are in disabled state, is ugly and inconsistent with each other, nor other buttons. Also, both buttons now are implement just as `<button>`, we should turn them in the instances of our new standard themeable buttons: https://github.com/topcoder-platform/community-app/tree/develop/src/shared/components/buttons
