### ISSUE TITLE
Update fetch service of Contentful 

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4061]
Fetch service of Contentful is hitting API rate limits for pages with large number of models. Increase the wait time to avoid problems like it.

Test: https://community-app.topcoder.com/examples/contentful/viewport/4yKPWM9C02JNg0vhtuh2TI
Expected: Render the page instead of showing "Too Many Requests"

**Comment by macs054** [comment]
Too Many Request still appears
![image](https://user-images.githubusercontent.com/1199534/76605188-00e23a00-654b-11ea-8286-4b235252fe23.png)

**Comment by SathyaJayabal** [comment]
@kkartunov , this issue is still happening (3 out of 5 times)
<img width="1440" alt="Screenshot 2020-03-13 at 2 40 24 PM" src="https://user-images.githubusercontent.com/58783823/76606698-bfe12a00-6538-11ea-9b26-fe0b8b669b40.png">

**Comment by kkartunov** [comment]
@SathyaJayabal probably network related. This patch is attempting to fix it and if it does not succeed sure does not make it worst. It actually works for me here is a video that proofs: http://beta-community-app.topcoder.com/examples/contentful/viewport/4yKPWM9C02JNg0vhtuh2TI

Let's keep this one open for further dev/testing and move forward.

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal @kkartunov, is this ticket in the wrong column?

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal @kkartunov, is this ticket in the wrong column?

@Oanh-and-only-Oanh , I have updated the column, thanks

**Comment by kkartunov** [comment]
@SathyaJayabal can we QA that again please? There is commit claiming to fix it...

**Comment by SathyaJayabal** [comment]
@kkartunov , got the error 5 out of 6 times.

If you try to open the above in in two tabs at the same time you get the error.

<img width="1436" alt="Screenshot 2020-03-31 at 10 56 53 AM" src="https://user-images.githubusercontent.com/58783823/77990198-62254e00-733e-11ea-8bd6-e7ed2052b913.png">

**Comment by kkartunov** [comment]
@SathyaJayabal okay thanks. Removing this from PR. We continue without it as we did last time...

**Comment by SathyaJayabal** [comment]
Verified on test env
<img width="1440" alt="Screenshot 2020-04-17 at 6 29 12 PM" src="https://user-images.githubusercontent.com/58783823/79571796-6ccf3980-80d9-11ea-87a5-b5df8ee9d49d.png">

**Comment by sandhiyakavi** [comment]
Verified on beta Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/79834928-d0fb4180-83e8-11ea-8daa-7c301342e120.png)

**Comment by Jobee1** [comment]
Tested and verified in Production environment.
![Screenshot_14](https://user-images.githubusercontent.com/48575864/79868464-a8cb0d00-83ff-11ea-8c67-c41fbfef9641.png)
