### ISSUE TITLE
Topcoder Communities 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4075]
Some of the communities listed below are not working on production
https://beta-community-app.topcoder.com/

Communities that are. not working:
https://beta-community-app.topcoder.com/__community__/iot
https://beta-community-app.topcoder.com/__community__/mobile
https://beta-community-app.topcoder.com/__community__/qa
https://beta-community-app.topcoder.com/__community__/srmx
https://beta-community-app.topcoder.com/__community__/taskforce

Have these been retired? Is the list of communities complete ?

**Comment by Oanh-and-only-Oanh** [comment]
These communities have been retired.
