### ISSUE TITLE
Typo on Taas page

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/community-app#4081]
1. Go to Taas page https://www.topcoder.com/community/taas
2. Go to SALESFORCE DEVELOPERS section.
3.  There is technolgies instead of technologies.

![image](https://user-images.githubusercontent.com/25297859/76207389-cd8b6c80-6225-11ea-8a31-6f480289af96.png)

_Originally posted by @drasticdpk in https://github.com/topcoder-platform/community-app/issues/4037#issuecomment-596465151_

**Comment by luizrrodrigues** [comment]
@kkartunov This is about typo in Salesforce Developers card.

**Comment by kkartunov** [comment]
@drasticdpk @luizrrodrigues fixed.
