### ISSUE TITLE
Notifications - Challenges item need be clickable and go to Challenge page

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4085]
The challenge notification should take the user to the. challenge details page on clicking it. Will this be implemented after API integration?

**Comment by macs054** [comment]
Verified in Test Env.

**Comment by macs054** [comment]
@luizrrodrigues 

When clicking the red/gray dot it should only remove the dot but instead it also directs the user to the challenge details page.

**Comment by luizrrodrigues** [comment]
@macs054 Fixed and ready to QA.
642e6ddf49515fb6e305437d9031c0ebc2fc1a97

cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on test env

**Comment by SathyaJayabal** [comment]
verified on beta (develop)

**Comment by SathyaJayabal** [comment]
verified on prod
[notif.mov.zip](https://github.com/topcoder-platform/community-app/files/4402628/notif.mov.zip)
