### ISSUE TITLE
View Member stats history for Private communities.

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4086]
Currently, the member stats data for public and private communities are being provided and displayed on the front end.
Member stats history data for public communities are available and displayed on the front end.
Member stats history data for private communities will display the public stats history, so we have removed the link for now until we can get data populated to dynamodb via the data loader

Expect behavior: We need stats history data for private communities. When a topgear user clicks on a topgear user handle, they should be able to view member stats AND member stats history for TOPGEAR only.

**Comment by Oanh-and-only-Oanh** [comment]
Testing criteria:
1. public member only -> other people public profile only
2. public+private(some group let's say topgear) member  -> other people public profile only + other people private(topgear only) profile  
3. private(eg - topgear) member only -> other people public profile only + other people private(topgear only) profile only

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh, this is tracked here
https://github.com/topcoder-platform/community-app/issues/4137

**Comment by SathyaJayabal** [comment]
cc @LieutenantRoger
