### ISSUE TITLE
Thrive search click on item in results dropdown fix

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4091]
We got a bug report about case where click on the dropdown item in Thrive search results does not work. Details:

- video https://www.dropbox.com/s/sun0gz5mpkc88qp/cannotclickonThrivelinks.mp4?dl=0
- Slack link https://topcodercommunity.slack.com/archives/C0HEL2N1L/p1583862052045000
- OS - Windows/Mac
- Browser - Chrome/Safari
- Resolution - 1680 x 911 and 1366 x 768

**Comment by SathyaJayabal** [comment]
@kkartunov , I am not able to reproduce this issue on mac with Chrome/Firefox/Safari
[thrive ser.mov.zip](https://github.com/topcoder-platform/community-app/files/4317211/thrive.ser.mov.zip)

**Comment by kkartunov** [comment]
It appears this bug is related to clicking on the gray area of the search item not on the item text or image. @SathyaJayabal can you QA that and document it?

**Comment by SathyaJayabal** [comment]
@kkartunov , clicking on the grey area also causes the issue.  The entire grey box is clickable and must take the user to the article, not just the text and image area. 

The video attached to. the issue description shows. that even clicking on the actual text. does not. work sometimes(which I cannot still reproduce)

**Comment by sandhiyakavi** [comment]
Tested in Test Environment. Search not working

[4091_fails.zip](https://github.com/topcoder-platform/community-app/files/4473142/4091_fails.zip)

**Comment by sandhiyakavi** [comment]
cc: @SathyaJayabal

**Comment by sandhiyakavi** [comment]
Additional Information:

Browser: Chrome Incognito
Browser size: 1280*610
screen size: 1280*720

**Comment by kkartunov** [comment]
@SathyaJayabal @Oanh-and-only-Oanh unable to reproduce this one. It is all working for us. Suggesting to move that to the backlog.

**Comment by SathyaJayabal** [comment]
@kkartunov, I had observed one thing regarding this issue. When I do a hard tap on the trackpad it does not work, but a soft tap works.

**Comment by hokienick** [comment]
@SathyaJayabal Yes, I can replicate what you mean here.  What a strange bug!

**Comment by SathyaJayabal** [comment]
verified on dev (feature branch)

**Comment by SathyaJayabal** [comment]
Verified on prod. Works as expected.
