### ISSUE TITLE
About and Contact link under RSS link leads to incorrect pages

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/community-app#4096]
**Describe the bug**
About and Contact link under RSS link leads to incorrect pages

**To Reproduce**
1. Click 'About' link under Get the RSS feed link
2. Click 'Contact' link under Get the RSS feed link

**Expected behavior**
Should lead to correct pages

**Actual behavior**
1. About link leads to: https://www.topcoder.com/about-the-2018-topcoder-open/
2. Contact link leads to: https://www.topcoder.com/thrive/tracks?track=Topcoder/hc/en-us/articles/219069687-Contact-Support

**Screenshots**
![image](https://user-images.githubusercontent.com/1199534/76413552-9efdc500-63d0-11ea-98f1-a9e560f75c58.png)

**Comment by sandhiyakavi** [comment]
This issue is not applicable now.
