### ISSUE TITLE
Community dropdown links

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#41]
Let's make these real links that go to the specific community sites:

![image](https://cloud.githubusercontent.com/assets/3812270/26597749/04c572a4-4541-11e7-95cd-1e9ed8098dd7.png)

We should probably have some kind of config for it.

**Comment by birdofpreyru** [comment]
Fixed for Wipro community by hard-coding necessary redirect links into the code. Pending is a proper fix, with necessary URLs coming from the config.

**Comment by birdofpreyru** [comment]
Will be finished in #587
