### ISSUE TITLE
[Challenge List] When network is slow, the list sometimes keeps flashing before data loaded.

### ISSUE THREAD

**Issue by elfman** [topcoder-platform/community-app#410]
Steps to Reproduce
-----------------------------------------------------------------
- Go to http://community-app.topcoder.com/challenges/

- Click Subtrack => Idea Generation (other filter may also cause this bug)

- see the challenge list.

Actual Result(s)
-----------------------------------------------------------------
- the list keeps flashing before loaded.

Expected Result(s)
-----------------------------------------------------------------
- don't flash the list

Environment
-----------------------------------------------------------------
- **Device(s):** Mac mini
- **Operating System:** Mac OS 10.11.6
- **Browser(s):** Chrome 60

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![bmweixchpr](https://user-images.githubusercontent.com/948001/29827384-7bc7790c-8d0c-11e7-974b-2f20b5a0ffc8.gif)

**Comment by birdofpreyru** [comment]
it was fixed a while ago
