### ISSUE TITLE
Contentful Slider Disappears

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4100]
**Describe the bug**
After the slider auto-scrolls to the end, the next time it scrolls it becomes blank and keeps scrolling through blank items.

**Expected behavior**
The slider should start from the beginning after it has reached the end.

**Comment by kkartunov** [comment]
Test url: https://community-app.topcoder.com/examples/contentful/slider/7CVn4Rglib0w2UUoID5wIw

Expected:
- Slides to be visible after the end and return to the beginning
- There should be gray arrows around the slider

**Comment by kkartunov** [comment]
@SathyaJayabal FYI

**Comment by kkartunov** [comment]
Here is test url on beta http://beta-community-app.topcoder.com/examples/contentful/slider/7CVn4Rglib0w2UUoID5wIw

**Comment by SathyaJayabal** [comment]
Verified that on auto scrolling to the end , the sliders start again from the beginning. Grey arrows around the slider are present.

**Comment by SathyaJayabal** [comment]
@kkartunov, the slider is not auto scrolling. 
On using the grey arrows , the first slides is displayed upon reaching the end of the slides.

**Comment by kkartunov** [comment]
@SathyaJayabal auto-scrolling is an option that is configurable from Contentful. It was disabled for other reasons. I enabled it for your request. Thanks

**Comment by SathyaJayabal** [comment]
Verified on beta(develop branch)
@kkartunov , verified that after the slider auto-scrolls to the end, the slider starts from the beginning.
Grey arrows around the slider are present.

**Comment by SathyaJayabal** [comment]
Verified on production
@kkartunov , verified that after the slider auto-scrolls to the end, the slider starts from the beginning.
Grey arrows around the slider are present.
