### ISSUE TITLE
Update Topgear site so it’s mostly controlled by Contentful similar to zurich and cs

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4101]
Currently, other than the banner and the FAQ page Topgear's portal is all hard coded into the app. We want to make it so it's controlled by Contentful.

**Comment by Oanh-and-only-Oanh** [comment]
please hold work on this until end of June

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh @SathyaJayabal testing URL is https://community-app.topcoder-dev.com/__community__/wipro

**Comment by SathyaJayabal** [comment]
@kkartunov, Topgear site on dev env works as on prod except for the below differences.
Home page:
1. Initiate Project URL includes user_id param in prod while it is missing here.
PROD: https://topgear-app.wipro.com/topcoder_projects/initiate_project?user_id=xxxxxx
FEATURE BRANCH: https://topgear-app.wipro.com/topcoder_projects/initiate_project

2. Differences in style in the home page and footer

**Comment by kkartunov** [comment]
Thanks @SathyaJayabal! @Oanh-and-only-Oanh ^^^, fyi

**Comment by kkartunov** [comment]
Thanks, @Oanh-and-only-Oanh. @SathyaJayabal we will continue with that as it is...

**Comment by SathyaJayabal** [comment]
verified on beta.

**Comment by SathyaJayabal** [comment]
Verified on prod. Topgear site works as before.
<img width="1440" alt="Screenshot 2020-07-21 at 9 17 21 AM" src="https://user-images.githubusercontent.com/58783823/88010676-12f46a80-cb33-11ea-8945-6699d6b64d9e.png">

**Comment by kkartunov** [comment]
This one depends on #4665 
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
Verified on beta (develop branch). Topgear site works as before except for style issues
<img width="1440" alt="Screenshot 2020-07-22 at 4 06 47 PM" src="https://user-images.githubusercontent.com/58783823/88166776-71097680-cc35-11ea-8d69-0d430c6dc0cd.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-22 at 6 29 36 PM" src="https://user-images.githubusercontent.com/58783823/88179380-71137180-cc49-11ea-964a-b33c59db68bd.png">
