### ISSUE TITLE
Settings/Profile - Graduated checkbox is misplaced in Education tab

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/community-app#4103]
**Describe the bug**
Graduation checkbox is misplaced in Education tab

**To Reproduce**
1. Go to https://www.topcoder.com/settings/profile#education
2. Check the Graduated checkbox

**Expected behavior**
The checkbox should be beside the Graduated label

**Screenshots**
![image](https://user-images.githubusercontent.com/1199534/76595360-5fe98400-6536-11ea-8fec-9e5e9851f5a3.png)

**Comment by sandhiyakavi** [comment]
This issue is resolved now.
![image](https://user-images.githubusercontent.com/55895538/107620352-e4d5a400-6c97-11eb-8068-314d2b82d66f.png)
