### ISSUE TITLE
Notification Backend Integration: All competitors should get challenge spec modified notification

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4104]
At present only submitters get the challenge spec modified notification. All members registered to te challenge must get the challenge spec modified notification.

**Comment by SathyaJayabal** [comment]
cc @macs054

**Comment by sachin-maheshwari** [comment]
{
    "id": "733ed472:170d302c354:-7b8b",
    "result": {
        "success": true,
        "status": 200,
        "metadata": null,
        "content": [
            {
                "id": 1078643,
                "projectId": 30055753,
                "name": null,
                "role": "Manager",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "23221139",
                    "Handle": "mdesiderio"
                },
                "updatedAt": "2020-02-04T11:23:03.126Z",
                "createdAt": "2019-11-27T14:43:38.812Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078644,
                "projectId": 30055753,
                "name": null,
                "role": "Manager",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "22770213",
                    "Payment Status": "N/A",
                    "Handle": "Applications"
                },
                "updatedAt": "2020-02-04T11:23:03.174Z",
                "createdAt": "2019-11-27T14:43:38.884Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078645,
                "projectId": 30055753,
                "name": null,
                "role": "Copilot",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "Payment": "600.0",
                    "External Reference ID": "8547899",
                    "Payment Status": "No",
                    "Manual Payments": "false",
                    "Handle": "TonyJ"
                },
                "updatedAt": "2020-02-04T11:23:03.223Z",
                "createdAt": "2019-11-27T14:43:38.899Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078646,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "22693694",
                    "Payment Status": "N/A",
                    "Handle": "delemach"
                },
                "updatedAt": "2020-02-04T11:23:03.271Z",
                "createdAt": "2019-11-27T14:43:38.932Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078647,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "305384",
                    "Payment Status": "N/A",
                    "Handle": "mess"
                },
                "updatedAt": "2020-02-04T11:23:03.317Z",
                "createdAt": "2019-11-27T14:43:38.951Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078648,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "15050434",
                    "Payment Status": "N/A",
                    "Handle": "FireIce"
                },
                "updatedAt": "2020-02-04T11:23:03.393Z",
                "createdAt": "2019-11-27T14:43:38.962Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078649,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "23197217",
                    "Payment Status": "N/A",
                    "Handle": "ttakasu_tc"
                },
                "updatedAt": "2020-02-04T11:23:03.452Z",
                "createdAt": "2019-11-27T14:43:38.976Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078650,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "23303359",
                    "Payment Status": "N/A",
                    "Handle": "tiwasaki"
                },
                "updatedAt": "2020-02-04T11:23:03.516Z",
                "createdAt": "2019-11-27T14:43:40.900Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078651,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "40031683",
                    "Payment Status": "N/A",
                    "Handle": "TakumiYambe"
                },
                "updatedAt": "2020-02-04T11:23:03.567Z",
                "createdAt": "2019-11-27T14:43:40.912Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078652,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "23241014",
                    "Payment Status": "N/A",
                    "Handle": "tcs424"
                },
                "updatedAt": "2020-02-04T11:23:03.612Z",
                "createdAt": "2019-11-27T14:43:40.926Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078653,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "8544935",
                    "Payment Status": "N/A",
                    "Handle": "Wendell"
                },
                "updatedAt": "2020-02-04T11:23:03.671Z",
                "createdAt": "2019-11-27T14:43:40.938Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078654,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "23235151",
                    "Payment Status": "N/A",
                    "Handle": "thabo"
                },
                "updatedAt": "2020-02-04T11:23:03.722Z",
                "createdAt": "2019-11-27T14:43:40.949Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1078655,
                "projectId": 30055753,
                "name": null,
                "role": "Approver",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "11.27.2019 09:43 AM",
                    "External Reference ID": "8547899",
                    "Payment Status": "N/A",
                    "Handle": "TonyJ"
                },
                "updatedAt": "2020-02-04T11:23:03.774Z",
                "createdAt": "2019-11-27T14:43:40.962Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 1079120,
                "projectId": 30055753,
                "name": null,
                "role": "Observer",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "01.31.2020 12:25 AM",
                    "External Reference ID": "40154344",
                    "Handle": "GunaK-TopCoder"
                },
                "updatedAt": "2020-02-04T11:23:03.820Z",
                "createdAt": "2020-01-31T05:25:51.320Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 40050374,
                "projectId": 30055753,
                "name": null,
                "role": "Submitter",
                "phaseId": null,
                "submissions": [
                    209090,
                    209089,
                    209088,
                    208971,
                    208851,
                    208855,
                    208854,
                    208853,
                    208852,
                    208859,
                    208858,
                    208857,
                    208920,
                    208856,
                    208862,
                    208861,
                    208860,
                    208867,
                    208866,
                    208869,
                    208868,
                    209002,
                    209001,
                    209006,
                    209005,
                    208882,
                    208881,
                    208880,
                    208887,
                    209083,
                    208889,
                    209080,
                    209087,
                    209086,
                    209085,
                    209084
                ],
                "properties": {
                    "Registration Date": "11.28.2019 01:48 AM",
                    "External Reference ID": "8547899",
                    "Appeals Completed Early": "NO",
                    "Handle": "TonyJ"
                },
                "updatedAt": "2020-02-04T11:23:03.868Z",
                "createdAt": "2019-11-28T06:48:58.000Z",
                "createdBy": "8547899",
                "updatedBy": "8547899"
            },
            {
                "id": 40050384,
                "projectId": 30055753,
                "name": null,
                "role": "Submitter",
                "phaseId": null,
                "submissions": [
                    208883
                ],
                "properties": {
                    "Registration Date": "12.04.2019 05:19 PM",
                    "External Reference ID": "23175096",
                    "Appeals Completed Early": "NO",
                    "Handle": "nithyaasworld"
                },
                "updatedAt": "2020-02-04T11:23:04.011Z",
                "createdAt": "2019-12-04T22:19:03.000Z",
                "createdBy": "23175096",
                "updatedBy": "8547899"
            },
            {
                "id": 40050426,
                "projectId": 30055753,
                "name": null,
                "role": "Submitter",
                "phaseId": null,
                "submissions": [],
                "properties": {
                    "Registration Date": "01.13.2020 01:53 PM",
                    "External Reference ID": "305384",
                    "Appeals Completed Early": "NO",
                    "Handle": "mess"
                },
                "updatedAt": "2020-02-04T11:23:04.074Z",
                "createdAt": "2020-01-13T18:53:24.000Z",
                "createdBy": "305384",
                "updatedBy": "8547899"
            },
            {
                "id": 40050428,
                "projectId": 30055753,
                "name": null,
                "role": "Submitter",
                "phaseId": null,
                "submissions": [
                    209007,
                    208973,
                    208972
                ],
                "properties": {
                    "Registration Date": "01.29.2020 11:04 PM",
                    "External Reference ID": "40158994",
                    "Appeals Completed Early": "NO",
                    "Handle": "TCConnCopilot"
                },
                "updatedAt": "2020-02-04T11:23:04.122Z",
                "createdAt": "2020-01-30T04:04:52.000Z",
                "createdBy": "40158994",
                "updatedBy": "8547899"
            }
        ]
    },
    "version": "v3"
}

As I checked the response of corresponding API  /v4/challenges/30055753/resources , 'dan_developer' is not coming in 'submitter'.
Please note - here submitter is 'register user'.  So its upstream API issue at DEV.   
@SathyaJayabal  should go to @sushilshinde or @dushyantb, not sure.

**Comment by SathyaJayabal** [comment]
@sushilshinde @dushyantb , for reference please see https://github.com/topcoder-platform/community-app/issues/4055#issuecomment-597584585

dan_developer is a registered to the specific contest, but the corresponding api call does not return that user.

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  as checked randomly on prod for API v4/challenges/{challenge-id}/resources , getting correct data. So could be data syncing issue at DEV. Lets test it on Beta. Hopefully it should work there.

**Comment by SathyaJayabal** [comment]
closing this as spec modified notification is not in scope now
https://github.com/topcoder-platform/community-app/issues/4147#issuecomment-608067304
