### ISSUE TITLE
Checkpoint Review Notification

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4114]
To track discussions 
https://topcoder.slack.com/archives/CG2J9RH70/p1584083663037900

For Design:
1. Event- Checkpoint screening starts
Message-  "Checkpoint screening phase is now open. You may now begin screening  checkpoint submissions." 
Target audience- screeners for that particular design challenge
2. Event- Checkpoint Review starts
Message- "Checkpoint Review is now open. You may now begin reviewing checkpoint submissions
Target audience- reviewers for that particular design challenge.

cc @Oanh-and-only-Oanh @sachin-maheshwari @luizrrodrigues

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari Let me know when this one is ready in backend.

**Comment by sachin-maheshwari** [comment]
@Oanh-and-only-Oanh  @luizrrodrigues  @SathyaJayabal  #1, here "target audience" is not clear to me, please explain with example. And that is for "Design challenge" only ? what about other challenges ? 
As I checked for Live Design Challenge https://www.topcoder.com/challenges/30119422 , corresponding backend api - v4/challenges/30119422/resources is giving only one "Primary Screener" i.e. "leben" . So only "leben" will be notified in this case. correct ? 
And #2, above api giving only one "Specification Reviewer"  i.e. "fajar.min". correct ?

**Comment by SathyaJayabal** [comment]
@Dara-K @Oanh-and-only-Oanh , I think checkpoint review phase is only applicable for design contests. Other challenges will not have this notification. Am I correct?

@Dara-K , Do design challenges have a reviewer role or is it done by the copilot (actual review by the client) ?

cc @sachin-maheshwari

**Comment by Dara-K** [comment]
@SathyaJayabal  Yes, the reviewer is the copilot for design challenges who acts in the name of the customer.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , to summarise 

When checkpoint screening starts, "Checkpoint screening phase is now open. You may now begin screening checkpoint submissions." to Primary Screener

When checkpoint review starts, ""Checkpoint Review is now open. You may now begin reviewing checkpoint submissions." to the Copilot.

cc @Oanh-and-only-Oanh @Dara-K

**Comment by SathyaJayabal** [comment]
cc @luizrrodrigues

**Comment by SathyaJayabal** [comment]
verified on test env
<img width="1440" alt="Screenshot 2020-03-18 at 5 19 26 PM" src="https://user-images.githubusercontent.com/58783823/76957899-a6771e00-693c-11ea-8251-49671274a9dc.png">

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @Dara-K @sachin-maheshwari @sushilshinde 
On testing in beta, it became clear that the checkpoint screening is done by the "Checkpoint Screener" role and not "Primary Screener" as perviously mentioned. 

We need to update the code to reflect this. The Checkpoint Screener must get the Checkpoint Screening Start notification.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @sachin-maheshwari @sushilshinde 
Checkpoint screening start notification was not received.
On looking into it, the event for checkpoint screening start was not published by OR. 
Other events like checkpoint screening end, checkpoint review start etc were published. I have contacted support to help with resetting the contest phases so that we can try testing again.

The checkpoint review start notification was received by the copilot.
<img width="508" alt="Screenshot 2020-03-26 at 6 53 27 PM" src="https://user-images.githubusercontent.com/58783823/77654549-36e5dc00-6f97-11ea-9570-ee4fa436db34.png">

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @sachin-maheshwari @sushilshinde ,  checkpoint screening notification was also received when testing today
![Topcoder Challenges 2020-03-27 11-42-24](https://user-images.githubusercontent.com/58783823/77727750-fcc11c80-7020-11ea-8090-76eee5d642b1.png)

**Comment by SathyaJayabal** [comment]
> @Oanh-and-only-Oanh @Dara-K @sachin-maheshwari @sushilshinde
> On testing in beta, it became clear that the checkpoint screening is done by the "Checkpoint Screener" role and not "Primary Screener" as perviously mentioned.
> 
> We need to update the code to reflect this. The Checkpoint Screener must get the Checkpoint Screening Start notification.

This issue will be tracked in #4146

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
<img width="1440" alt="Screenshot 2020-03-30 at 1 55 57 PM" src="https://user-images.githubusercontent.com/58783823/77891214-41052480-728e-11ea-9ee1-9d1971ef1377.png">
![Topcoder Challenges 2020-03-30 13-58-07](https://user-images.githubusercontent.com/58783823/77891588-ce487900-728e-11ea-85db-c953ab675c64.png)

**Comment by SathyaJayabal** [comment]
Verified on prod.
<img width="1440" alt="Screenshot 2020-03-30 at 5 53 01 PM" src="https://user-images.githubusercontent.com/58783823/77912462-3d829500-72b0-11ea-8fd1-7cbd4eaa7d7c.png">
