### ISSUE TITLE
Dashboard - My Communities tab labels are in white font

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/community-app#4117]
**Describe the bug**
Dashboard - My Communities tab labels are in white font

**To Reproduce**
1. Go to https://www.topcoder.com/my-dashboard
2. Click on My Communities tab

**Expected behavior**
The labels should be in black

**Screenshots**
![image](https://user-images.githubusercontent.com/1199534/76840164-aeb65700-6871-11ea-8b96-7d703b05e007.png)

**Comment by sandhiyakavi** [comment]
The My Communities tab is hided at present.
