### ISSUE TITLE
Notifications - Remove "Completed Challenges" until Backend is ready

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4120]
- Remove **Completed Challenges** tab from listing page
- Change **Active Challenges** tab to just **Challenges**
- The **Challenges** tab will show both Active and Completed challenges notifications for now

**Comment by SathyaJayabal** [comment]
verified on test env
<img width="1406" alt="Screenshot 2020-03-18 at 3 58 26 PM" src="https://user-images.githubusercontent.com/58783823/76951237-5a72ac00-6931-11ea-9913-cd6c1bae52a3.png">

**Comment by SathyaJayabal** [comment]
verified on beta(feature branch)
<img width="1440" alt="Screenshot 2020-03-26 at 5 27 56 PM" src="https://user-images.githubusercontent.com/58783823/77644555-2fb6d200-6f87-11ea-86c3-bff0d87085c8.png">

**Comment by SathyaJayabal** [comment]
verified on beta. (develop branch)
<img width="1440" alt="Screenshot 2020-03-30 at 1 52 59 PM" src="https://user-images.githubusercontent.com/58783823/77890917-d05e0800-728d-11ea-9c48-03e68e49fba2.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-03-30 at 5 38 46 PM" src="https://user-images.githubusercontent.com/58783823/77912553-6145db00-72b0-11ea-86ad-da2970678b92.png">
