### ISSUE TITLE
Notification: Link in broadcast messages

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4122]
Expected: Clicking the broadcast message must take the. user to the respective page

Actual: The link is displayed as part of the broadcast message

cc @sachin-maheshwari 
<img width="1440" alt="Screenshot 2020-03-18 at 3 24 14 PM" src="https://user-images.githubusercontent.com/58783823/76948078-95beac00-692c-11ea-9b20-aca215ef699f.png">

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Please confirm this.

We going to use the link directly in the Notification body with the highlighted test (in e.g. above the Topcoder will be blue like "View all Notifications". Or we'll make the whole notification item as a link, as we have in Challenge Notifications type?

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, the notification item should take them to the respective page.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Yep, this requirement is okay.

Question is about if not will show link in notification body level, like the example above (screenshot) only Topcoder will be a link.

**Comment by luizrrodrigues** [comment]
If follow example above, notifications with a link will show like this:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/7029641/76999414-5ba5d800-6935-11ea-9eb3-a0531ec9c91e.png">

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, see below 
<img width="607" alt="Screen Shot 2020-03-18 at 1 20 40 PM" src="https://user-images.githubusercontent.com/47536078/77004116-cd712800-691b-11ea-8990-6adc32d6dc4a.png">

**Comment by luizrrodrigues** [comment]
Okay, I just update **Sachin:3 public group testing Topcoder** to confirm :)

I think not a better way, think about we add a new field to API response with the URL and make whole notification item as a link, like challenge items.

But this change will need to do in the backend, so we can do this later. 

I'll make the updates like the request above.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I'm done the implementation and build is running (ready to QA in 20min).

But need to fix links in notifications items.

![Screen Shot 2020-03-21 at 16 03 30](https://user-images.githubusercontent.com/7029641/77234955-e5051680-6b90-11ea-8794-2ff4d868ee59.png)

Need to change **herf** to **href**

**Comment by luizrrodrigues** [comment]
The build is done: 
![image](https://user-images.githubusercontent.com/7029641/77235196-90629b00-6b92-11ea-8044-f77334810055.png)

**Comment by SathyaJayabal** [comment]
verified on test env
<img width="1440" alt="Screenshot 2020-03-23 at 10 39 26 AM" src="https://user-images.githubusercontent.com/58783823/77283546-a1c2b900-6cf2-11ea-94b0-c4aa539e0063.png">
<img width="1440" alt="Screenshot 2020-03-23 at 10 39 30 AM" src="https://user-images.githubusercontent.com/58783823/77283562-ac7d4e00-6cf2-11ea-9ee6-f2ed74ac05fa.png">

**Comment by SathyaJayabal** [comment]
Verified by @sushilshinde  beta(feature branch)

**Comment by SathyaJayabal** [comment]
can be verified on production only when a broadcast message with a link is published.
