### ISSUE TITLE
Change "TaaS" navigation to "Gig Work"

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4124]
Change the "Taas" label in the top navigation to say: Gig Work

**Comment by sandhiyakavi** [comment]
Tested the issue.It is working as expected.

![image](https://user-images.githubusercontent.com/55895538/77991414-7159cb00-7341-11ea-93f6-c63c193111c9.png)

**Comment by Jobee1** [comment]
Tested in Beta Environment: "Gig Work" is displayed.

![4124](https://user-images.githubusercontent.com/48575864/78216590-f1b33400-74d9-11ea-90a2-1af4c4655789.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-04-02 at 5 23 39 PM" src="https://user-images.githubusercontent.com/58783823/78246422-c135bf00-7506-11ea-9407-b051048f6240.png">
