### ISSUE TITLE
Header Navi: Landing Pages to Thrive

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4125]
All track landing pages should know link to their category in Thrive:

- Competitive Programming: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming
- Data Science: https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=
- Design: https://www.topcoder.com/thrive/tracks?track=Design&tax=
- Development: https://www.topcoder.com/thrive/tracks?track=Development&tax=
- QA: https://www.topcoder.com/thrive/tracks?track=QA&tax=

**Comment by sandhiyakavi** [comment]
Tested the issue.All track landing pages are landing to their respective category in Thrive.

But after directing to the page they are not pointing to the Tracks in the header.Instead it is pointing/showing  the Explore in the header.

Attached screenshot as well as video of the same.

![image](https://user-images.githubusercontent.com/55895538/77993763-67869680-7346-11ea-8aff-9e7d51cd1a29.png)

[issue#4125.zip](https://github.com/topcoder-platform/community-app/files/4407154/issue.4125.zip)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh  @kkartunov , the nav must reflect the selected track like in production now.
<img width="1411" alt="Screenshot 2020-03-31 at 12 12 33 PM" src="https://user-images.githubusercontent.com/58783823/77995200-f5638100-7348-11ea-9f61-f0ad6e75b846.png">

**Comment by kkartunov** [comment]
@SathyaJayabal this is a bug in the navigation module and has to be fixed in new ticket. It appears that it does not correctly highlight the active link. I think we should proceed with this as it is and have it fixed separately. cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , van you please help

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Sure, I'll take a look today.

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, let's proceed with this and mark as "Passed QA" so we can deploy. Can you open a new ticket for the navi issue and assign to @luizrrodrigues? Please label ticket as Navi and add to the "Later" column on the Issues Board. We'll do a hot fix in a few weeks to resolved.

**Comment by SathyaJayabal** [comment]
Tracking the Nav issue here
https://github.com/topcoder-platform/navigation-component/issues/168

**Comment by sandhiyakavi** [comment]
Tested in Beta environment.Working as expected.

Attached video for reference.


[beta_env_issue#4125.zip](https://github.com/topcoder-platform/community-app/files/4419228/beta_env_issue.4125.zip)

**Comment by SathyaJayabal** [comment]
verified. on prod
[tracks.mov.zip](https://github.com/topcoder-platform/community-app/files/4420791/tracks.mov.zip)
