### ISSUE TITLE
TC Footer - Privacy Policy link

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4126]
Update it to https://www.topcoder.com/privacy-policy/.
With the completion of it delete https://www.topcoder.com/community/how-it-works/privacy-policy/ and close this and #3984

**Comment by SathyaJayabal** [comment]
verified on test
[footer privacy.mov.zip](https://github.com/topcoder-platform/community-app/files/4407176/footer.privacy.mov.zip)

**Comment by Jobee1** [comment]
Tested on Beta Environment: Clicking on the "Privacy Policy" redirects to "https://www.topcoder.com/privacy-policy/".

[privacy_policy.zip](https://github.com/topcoder-platform/community-app/files/4419229/privacy_policy.zip)

![Screenshot_40](https://user-images.githubusercontent.com/48575864/78217518-fc6ec880-74db-11ea-955e-6901054d4920.png)

**Comment by sandhiyakavi** [comment]
verified on Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/78246168-5a180a80-7506-11ea-8d77-c32af22cba2c.png)
