### ISSUE TITLE
Not able to view profile page for user: CADEdgeXTC-20

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4134]
A blank page is displayed on accessing the profile of member: CADEdgeXTC-20
<img width="1425" alt="Screenshot 2020-03-24 at 3 25 16 PM" src="https://user-images.githubusercontent.com/58783823/77412455-e8dca700-6de3-11ea-95f3-846d458fdeeb.png">

**Comment by SathyaJayabal** [comment]
reported on slack
https://topcodercommunity.slack.com/archives/C0HEL2N1L/p1585003361065700

**Comment by LieutenantRoger** [comment]
The work is done against `hot-fix-profile-page`

**Comment by LieutenantRoger** [comment]
Test url: https://www.topcoder.com/members/CADEdgeXTC-20

**Comment by SathyaJayabal** [comment]
verified on beta (hot fix branch)
<img width="1440" alt="Screenshot 2020-03-24 at 5 12 14 PM" src="https://user-images.githubusercontent.com/58783823/77421920-b1292b80-6df2-11ea-8768-0aab024739a3.png">

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , this one is already fixed on production.
<img width="1435" alt="Screenshot 2020-03-31 at 2 54 22 PM" src="https://user-images.githubusercontent.com/58783823/78010049-8b0a0b00-735f-11ea-9243-f8a2d146ca3b.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop)
<img width="1440" alt="Screenshot 2020-03-31 at 3 04 05 PM" src="https://user-images.githubusercontent.com/58783823/78011213-e8eb2280-7360-11ea-996c-91c3f2396a2f.png">

**Comment by LieutenantRoger** [comment]
Hi @SathyaJayabal 

I think we should we close this ticket.

**Comment by LieutenantRoger** [comment]
@SathyaJayabal
