### ISSUE TITLE
Notification pop-up inconsistent 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4140]
@luizrrodrigues sometimes I see this pop-up

![Topcoder Challenges 2020-03-26 17-00-20](https://user-images.githubusercontent.com/683231/77643520-828f8a00-6f85-11ea-8289-c7711a18ed4b.png)

and sometimes I see this 

![Topcoder Challenges 2020-03-26 17-11-40](https://user-images.githubusercontent.com/683231/77643549-93d89680-6f85-11ea-9fe9-d1ffc6a13df5.png)

FYI @Oanh-and-only-Oanh @SathyaJayabal

**Comment by Oanh-and-only-Oanh** [comment]
@Dara-K, from a UI perspective, when should members see the above?

**Comment by Dara-K** [comment]
When they have read all notifications. That's also why the "Mark all as read" link is not there anymore.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , the. issue is members should see the empty state only when they do not have any notifications.  But sometimes for the same user, they see both the above randomly. Sometimes it shows the empty state and sometimes with notifications.

**Comment by SathyaJayabal** [comment]
cc @sushilshinde

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @Dara-K @SathyaJayabal 

Yeah, the issue here is about sometimes the notifications items not loaded.

This happen after login if refresh back to normal. I'll check this one.

**Comment by luizrrodrigues** [comment]
@sushilshinde I can't reproduce this one anymore, maybe was API instability? 
Can you recheck and let me know if still able to see the issue?

cc @SathyaJayabal 

Thanks

**Comment by luizrrodrigues** [comment]
**UPDATE**
I have found the issue, this happen when user token is changed. It is updated regularly over a period of time.

Working on fix.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal @sushilshinde 
This was fixed and ready for QA in Beta.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on beta. The notifications load correctly every time.

**Comment by SathyaJayabal** [comment]
Verified on beta (develop branch)

**Comment by SathyaJayabal** [comment]
verified on prod.
