### ISSUE TITLE
remove Notifications Settings link 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4141]
Hide notifications settings link until settings page is ready

**Comment by SathyaJayabal** [comment]
The notification settings button and related text must be removed from the notification popup empty state.
![Topcoder Challenges 2020-03-26 17-11-40](https://user-images.githubusercontent.com/58783823/77643909-2e38da00-6f86-11ea-8884-80ca5b4d785a.png)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , need to remove the settings icon from the mobile view too
<img width="500" alt="Screenshot 2020-03-26 at 6 53 45 PM" src="https://user-images.githubusercontent.com/58783823/77651928-80342c80-6f93-11ea-8a3a-5d92a9cb76da.png">

**Comment by Oanh-and-only-Oanh** [comment]
Update text to "check your notification settings"

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Done.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @luizrrodrigues , I am sorry there was some misunderstanding. This is the text I was talking about.
<img width="639" alt="Screenshot 2020-03-27 at 8 07 27 AM" src="https://user-images.githubusercontent.com/58783823/
77715647-2454bc80-7002-11ea-8c97-e78e2b2c0c8b.png">

We need to hide the button and also hide this text as it refers to the settings.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Ah okay, so keep **Notification Settings** in button and hide both, button and text bellow.

Right?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , yes right.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Fixed and deployed in Beta server.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on beta
<img width="1398" alt="Screenshot 2020-03-29 at 9 52 19 AM" src="https://user-images.githubusercontent.com/58783823/77840284-2c982d80-71a3-11ea-90f8-e7f6022f2713.png">

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch). Settings link and icon removed.
<img width="1433" alt="Screenshot 2020-03-30 at 1 47 10 PM" src="https://user-images.githubusercontent.com/58783823/77890469-20889a80-728d-11ea-841d-a9152160e2f7.png">

<img width="502" alt="Screenshot 2020-03-30 at 1 46 07 PM" src="https://user-images.githubusercontent.com/58783823/77890456-1bc3e680-728d-11ea-85e9-de1698a0a5e9.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="479" alt="Screenshot 2020-03-30 at 5 42 46 PM" src="https://user-images.githubusercontent.com/58783823/77911148-f693a000-72ad-11ea-8c51-47502310a97d.png">
<img width="501" alt="Screenshot 2020-03-30 at 5 43 03 PM" src="https://user-images.githubusercontent.com/58783823/77911154-f8f5fa00-72ad-11ea-8a70-770056dcab6d.png">
