### ISSUE TITLE
Not receiving QA challenges notification.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/community-app#4142]
**Describe the bug**

**To Reproduce**
1. Login as User
2. Select as QA challenger

**Expected behavior**
Should receive a notification whenever a new challenge is in uploaded  .

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Oanh-and-only-Oanh** [comment]
Added this feature request to roadmap. closing ticket.
