### ISSUE TITLE
No challenges found in My Challenges message even though  user has multiple challenges

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/community-app#4143]
No challenges found in My Challenges message even though  user has multiple challenges

**To Reproduce**
1. Login as user.
2. Click on any project link.
3. Click on < icon or goback 
4. View the my challenges

**Expected behavior**
All the challenges should display

**Screenshots**

![image](https://user-images.githubusercontent.com/61318135/77675499-0875fa00-6fb3-11ea-842a-f8f4717e6d36.png)

**Comment by Oanh-and-only-Oanh** [comment]
closing due to duplicate issue
