### ISSUE TITLE
Add "Paypal" as a challenge tag

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/community-app#4145]
**Is your feature request related to a problem? Please describe.**
Cannot find the tag "Paypal" for challenges

**Describe the solution you'd like**
Need a new tag "Paypal" to add to challenges

**Describe alternatives you've considered**
None

**Additional context**
This will denote integration with Paypal

**Comment by Oanh-and-only-Oanh** [comment]
added to spreadsheet tracker https://docs.google.com/spreadsheets/d/1FGP7Ly9JFHtaXP9F_InSJT8Qyb9E5t3zTASoQTcyMww/edit#gid=0
