### ISSUE TITLE
Spec modified event is not published by TC Direct

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4147]
Spec modified event is not published by TC Direct.

Make sure the the spec modified event is only considered for active contests and not for draft contests

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , we need to make sure the. notification is sent only on active challenges modifictaion.

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal as per @dushyantb response - https://topcoder.slack.com/archives/CG2J9RH70/p1585814073150000 There is no way to trigger the specification modifcation events from Direct-app. It can be possible through API. 
BTW, tc-notification backend is working fine on Production. sharing screen in which modification event received and generated notification accordingly. 
<img width="1440" alt="Screenshot 2020-04-02 at 1 37 48 PM" src="https://user-images.githubusercontent.com/6467888/78225755-55445e00-74e8-11ea-9c14-58233f6d8069.png">

**Comment by Oanh-and-only-Oanh** [comment]
Closing this ticket. No longer valid
