### ISSUE TITLE
Refreshing the notifications page takes the user to 404 page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4152]
go to https://www.topcoder.com/notifications
Refreshing the page

expected: notification page is displayed
actual: 404 page is displayed

please refer to video
[notif 404.mov.zip](https://github.com/topcoder-platform/community-app/files/4402868/notif.404.mov.zip)

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh We're investigating this one. 

Talking with @sushilshinde and checking if is a problem with Loader Balancer.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Confirmed, this was problem with Balancer, @sushilshinde Added the path to Balancer and fixed.

https://www.topcoder.com/notifications

I think we don't need a QA here and just close this one.

**Comment by SathyaJayabal** [comment]
verified on production.
