### ISSUE TITLE
Notifications - Implement Google Analytics event tracking

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4154]
Google Analytics needs to track all events bellow:

- Open popup notifications;
- Click "Mark All Read";
- Click in "Mark Notifications As Read";
- Click in Notification item, if is a challenge type;
- Event "Mark All Notifications As Seen";
- Visite Notifications Details page;

**Comment by SathyaJayabal** [comment]
verified on test env
<img width="1124" alt="Screenshot 2020-04-03 at 10 37 58 AM" src="https://user-images.githubusercontent.com/58783823/78326759-c8a5a880-7598-11ea-8cfd-15ccd27f4bd1.png">

**Comment by SathyaJayabal** [comment]
verified on beta. Unable to test the following because there are no unseen/unread notifications on prod backend .
Click "Mark All Read" 
Click in "Mark Notifications As Read"
Event "Mark All Notifications As Seen" 
<img width="1132" alt="Screenshot 2020-04-03 at 11 07 10 AM" src="https://user-images.githubusercontent.com/58783823/78327875-77e37f00-759b-11ea-9037-82a3507e4ac1.png">

**Comment by luizrrodrigues** [comment]
Thanks @SathyaJayabal 

@Oanh-and-only-Oanh Please let me know if the events above are fine or if need add/remove.
Sent invite to Google Analytics account:
https://analytics.google.com/analytics/web/#/report/content-event-events/a161803421w226847870p214772878/_u.date00=20200326&_u.date01=20200403&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D

Also, please let me know which account we'll use to tracking these events, currently, in community-app I see 2 Google Analytics ID.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, can you add, "click notification event". We want to know how many people click on the notification vs just marking it as "read".
Can we also add, when the user just clicks on the bell icon to read their notifications. We want to know how many click to see the drop down but don't make any subsequent actions such as "mark as read".

What are the 2 Google analytics IDs?

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh 

> can you add, "click notification event". We want to know how many people click on the notification vs just marking it as "read".    

Do you mean when clicking in an item and go to the challenge page? Or when click in URL inside notification?
When clicking in challenge item type, we already track this: **Notification Item**, I can change text here if needed.

-----

> Can we also add, when the user just clicks on the bell icon to read their notifications. We want to know how many click to see the drop down but don't make any subsequent actions such as "mark as read".    

We already tracking this: **Open Notification Popup**, again I can change text here if needed.

-----

> What are the 2 Google analytics IDs?    

Sorry, have just one GA ID, another is Google Tag Manager:
GA: UA-6340959-1
TM: GTM-MXXQHG8

<img width="451" alt="image" src="https://user-images.githubusercontent.com/7029641/78414831-7abe8e00-75f4-11ea-9278-180bc4e6ffdc.png">

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues, please use first account.

 Please change to **Open Notification Dropdown**

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh 

1. Ok
2. Ok
3. This is when the change between tabs in Details page: Active Challenges / Complete Challenges / Notifications
4. We have 2 different types of notification item here:
a) Challenge type: This is linked with a challenge, so each item have the challenge ID, so the whole notification item area is clickable.
b) Broadcast type: Don't have a challenge linked, the link coming from the body of notification, so we can't make this item whole area clickable, so links are rendered link normal link (blue with underline).

So to b) case, I can't track when user clicks just in the link, but able to track if user clicks in any area from notification item. This means, if a user just clicks out from the link (like if want to select the notification text) will track as a click.

Make sense?

**Comment by Oanh-and-only-Oanh** [comment]
Ok i think i understand 4b.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh 

2. Already updated. cc @SathyaJayabal 

4. So currently way is fine?

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , the events are tracked only after the user navigates to the notifications page and refreshes it once.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Please try clear browser cache.

Here working well: 
[Screen Recording 2020-04-28 at 10.27.48.mov.zip](https://github.com/topcoder-platform/community-app/files/4546049/Screen.Recording.2020-04-28.at.10.27.48.mov.zip)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , it works now. Thank you. 
Verified on Beta( develop branch)
<img width="1130" alt="Screenshot 2020-04-28 at 7 09 54 PM" src="https://user-images.githubusercontent.com/58783823/80494288-21901300-8984-11ea-88b7-0b6c9c6172ed.png">

**Comment by SathyaJayabal** [comment]
This GA events are tracked in the test account and not on the production account

**Comment by SathyaJayabal** [comment]
related to #4345

**Comment by luizrrodrigues** [comment]
@SathyaJayabal we removed GA from `topcoder-react-lib` and moved to `community-app`, this ready and waiting for @sushilshinde

**Comment by SathyaJayabal** [comment]
verified on test  env (`ga-hotfix` branch)
<img width="1132" alt="Screenshot 2020-05-08 at 10 19 40 AM" src="https://user-images.githubusercontent.com/58783823/81371481-90eccc00-9115-11ea-9ff8-73d4db8de91c.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues we will  close this one along with #4309

**Comment by SathyaJayabal** [comment]
closed through #4309
