### ISSUE TITLE
Thrive tags fix

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4159]
Tags break when on two lines and when many of them present. Example: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&tax=SRM%20Editorials

Need to fix.

**Comment by sandhiyakavi** [comment]
Tested in Test environment.Working as expected.

Competitive programming 

![image](https://user-images.githubusercontent.com/55895538/79182341-83f7f800-7e49-11ea-89eb-b0732ff83140.png)

Data Science:

![image](https://user-images.githubusercontent.com/55895538/79182490-e224db00-7e49-11ea-98b1-d2fb3b686123.png)

Design:

![image](https://user-images.githubusercontent.com/55895538/79182553-0a143e80-7e4a-11ea-927f-1a9d8b435912.png)

Development:

![image](https://user-images.githubusercontent.com/55895538/79182598-257f4980-7e4a-11ea-9b4b-8771e2f3f1de.png)

QA

![image](https://user-images.githubusercontent.com/55895538/79182633-392ab000-7e4a-11ea-9c8c-25588332ca89.png)

**Comment by sandhiyakavi** [comment]
cc: @SathyaJayabal

**Comment by hokienick** [comment]
Good to go.

**Comment by Jobee1** [comment]
Tested in Beta environment. Working as expected.

Competitive Programming

![Competitive Programming](https://user-images.githubusercontent.com/48575864/79442820-c3187b80-7ff8-11ea-9909-0f4a868a02c0.png)

Data Science

![Data Science](https://user-images.githubusercontent.com/48575864/79442844-cc094d00-7ff8-11ea-9cf1-33a7b9d3304d.png)

Design

![DEsign](https://user-images.githubusercontent.com/48575864/79442872-d3c8f180-7ff8-11ea-80a8-cfe333cf0ae5.png)

Development

![Development](https://user-images.githubusercontent.com/48575864/79442885-d88da580-7ff8-11ea-893a-70f2c4d3e6a3.png)

QA

![QA](https://user-images.githubusercontent.com/48575864/79442902-ddeaf000-7ff8-11ea-8f3e-13f6b6122cae.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-04-16 at 7 27 03 PM" src="https://user-images.githubusercontent.com/58783823/79464886-49908580-8018-11ea-9685-22e09411a0b7.png">
