### ISSUE TITLE
Add Amazon QLDB as a challenge Tag

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/community-app#4160]
**Is your feature request related to a problem? Please describe.**
Cannot find the tag "QLDB" from Amazon for challenges

**Describe the solution you'd like**
Need a new tag "QLDB" for challenges

**Describe alternatives you've considered**
None

**Additional context**
This will denote integration with Amazon's Ledger Database

**Comment by Oanh-and-only-Oanh** [comment]
Adding to this spreadsheet for tracking https://docs.google.com/spreadsheets/d/1FGP7Ly9JFHtaXP9F_InSJT8Qyb9E5t3zTASoQTcyMww/edit#gid=0
