### ISSUE TITLE
Add General Newsletter switch to Email Preferences in Settings

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4165]
We should keep the original layout as it was previously but this section should contain several switches.

Currently, all members are automatically registered for the General Newsletter and have the ability to unsubscribe in the email, however, we should also give them the opportunity to unsubscribe via our preferences.

Switch Turned ON: add contact to the tag in  Mailchimp.
Switch Turned OFF: unsubscribe contact from tag (do not delete)

List of toggles to add:
```
Challenge Pipeline (Pipeline) - Subscribe to this newsletter if you want to get updates on the types of challenges coming up in the future.  To view these challenges at your leisure you can always visit the Challenge Pipeline page.

Gig Work (Taas) - This newsletter gets sent out at various times, specifically when we have an opportunity of mass appeal.  For more information you can visit the Gig Work page.

Monthly Newsletter (Monthly Newsletter) - This newsletter gets sent out at the end of every month and contains a variety of important information across all of our tracks.

Marathon Match Reminders - Receive updates whenever a new marathon match is scheduled.

Single Round Match (SRM) Reminders - Attention Competitive Programmers!  If there is any newsletter you are subscribing too, it better be this one.  Receive updates when a new SRM event is scheduled.

TCO Newsletter (TCO) - For all the latest updates surrounding the Topcoder Open you should definitely be subscribing to this one.  Expect an update in your mailbox every Tuesday!
```

Testing this can be done on dev when logged in.

**Comment by SathyaJayabal** [comment]
verified that this is reverted on develop branch (beta env) 
<img width="1440" alt="Screenshot 2020-05-21 at 1 09 39 PM" src="https://user-images.githubusercontent.com/58783823/82535415-6f9fcd00-9b64-11ea-9d4c-a3a79c330bc9.png">

**Comment by SathyaJayabal** [comment]
@kkartunov @hokienick 
`Single Round Match (SRM) Reminders - Attention Competitive Programmers!  If there is any newsletter you are subscribing too, it better be this one.  Receive updates when a new SRM event is scheduled.
`

I think the "too" must be "to" in the above text.

**Comment by SathyaJayabal** [comment]
marking as pass as per comments
https://topcoder.slack.com/archives/C53KB3T7Z/p1594189377249000?thread_ts=1594065168.241700&cid=C53KB3T7Z

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-08 at 3 05 22 PM" src="https://user-images.githubusercontent.com/58783823/86903087-7bebe380-c12c-11ea-81e7-b3f4d14bc438.png">
