### ISSUE TITLE
Remove "Invitation Letter" and "Referrals" from Preferences Sidebar

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4167]
We aren't sure where these options came from, nevertheless there are dead links in these 2 sections.  Please remove them from the sidebar.

![Screen Shot 2020-04-02 at 1 48 00 PM](https://user-images.githubusercontent.com/1373998/78307308-76ae4580-74fa-11ea-9efb-e2e7cd596426.png)

**Comment by sandhiyakavi** [comment]
Tested in Test Environment. Invitation letter and Referrals are removed.

![image](https://user-images.githubusercontent.com/55895538/79183435-6d06d500-7e4c-11ea-8a8d-fce04122f830.png)

**Comment by sandhiyakavi** [comment]
cc: @SathyaJayabal

**Comment by Jobee1** [comment]
Tested in Beta environment, Working as expected.

![Screenshot_1](https://user-images.githubusercontent.com/48575864/79443246-52259380-7ff9-11ea-9285-bc4afb126aed.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-04-16 at 7 28 15 PM" src="https://user-images.githubusercontent.com/58783823/79465030-747ad980-8018-11ea-9a88-5e14235d4f55.png">
