### ISSUE TITLE
Comcast Home : Content issue : text size

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4178]
The text size is smaller when compared to the Topcoder in the Time of Covid-19 page

<img width="1440" alt="Screenshot 2020-04-07 at 9 36 15 AM" src="https://user-images.githubusercontent.com/58783823/78629045-91ded380-78b3-11ea-8d88-f11164594b96.png">

**Comment by SathyaJayabal** [comment]
@kkartunov Still present
<img width="1440" alt="Screenshot 2020-04-08 at 4 45 32 PM" src="https://user-images.githubusercontent.com/58783823/78778201-875a3200-79b8-11ea-8743-a3be30bd4264.png">

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-04-08 at 5 42 01 PM" src="https://user-images.githubusercontent.com/58783823/78782915-6990cb00-79c0-11ea-889b-089abf036750.png">

**Comment by kkartunov** [comment]
@SathyaJayabal fixed

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1432" alt="Screenshot 2020-04-15 at 3 55 02 PM" src="https://user-images.githubusercontent.com/58783823/79327145-92b9da00-7f31-11ea-8400-ca08e8936ca7.png">
<img width="1429" alt="Screenshot 2020-04-15 at 3 55 24 PM" src="https://user-images.githubusercontent.com/58783823/79327161-977e8e00-7f31-11ea-8a97-da5af3df6213.png">
