### ISSUE TITLE
Comcast Home: What's Next - content issue

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4181]
<img width="605" alt="Screenshot 2020-04-07 at 10 02 46 AM" src="https://user-images.githubusercontent.com/58783823/78630332-167f2100-78b7-11ea-9244-e686fd22b8aa.png">

**Comment by SathyaJayabal** [comment]
@kkartunov Still present.
<img width="1440" alt="Screenshot 2020-04-08 at 4 34 18 PM" src="https://user-images.githubusercontent.com/58783823/78777262-d99a5380-79b6-11ea-90db-361535a92774.png">

**Comment by kkartunov** [comment]
@SathyaJayabal what is the issue here?

**Comment by SathyaJayabal** [comment]
@kkartunov , newline after "site" and "oppotunities"

**Comment by kkartunov** [comment]
@SathyaJayabal this is fixed. Please check.
