### ISSUE TITLE
Comcast: Give Back - Content Issues

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4184]
1. Expected: Two placeholder projects must come before the. "About Comcast Cares Day" section. 
Actual: One placeholder project after the "About Comcast Cares Day" section. 

<img width="1440" alt="Screenshot 2020-04-07 at 11 02 36 AM" src="https://user-images.githubusercontent.com/58783823/78633484-66fa7c80-78bf-11ea-801a-2686d9f29d05.png">

2. Is this section required?
<img width="945" alt="Screenshot 2020-04-07 at 11 04 51 AM" src="https://user-images.githubusercontent.com/58783823/78633591-a032ec80-78bf-11ea-9ac3-4c9616864cc5.png">

**Comment by SathyaJayabal** [comment]
Verified on production
Missing "View Challenge" button on the sample challenges.

**Comment by kkartunov** [comment]
@SathyaJayabal which challenge? :) Why opening tickets for mock texts?

**Comment by SathyaJayabal** [comment]
@kkartunov , they are sample projects right? So we need a button to view the project/challenge. Maybe defer it until we know more about the content.

**Comment by kkartunov** [comment]
@SathyaJayabal this is now obsolete. I thin you should close it.
