### ISSUE TITLE
Open Thrive in new window

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4192]
When user clicks on "Learn" tab in navigation, open THRIVE in a separate tab.

**Comment by kkartunov** [comment]
@SathyaJayabal this is now ready to test on beta

**Comment by SathyaJayabal** [comment]
verified on beta (feature branch)
[thrive link.mov.zip](https://github.com/topcoder-platform/community-app/files/4461713/thrive.link.mov.zip)

**Comment by SathyaJayabal** [comment]
Verified on beta(develop branch)
[thrive link.mov 2.zip](https://github.com/topcoder-platform/community-app/files/4473660/thrive.link.mov.2.zip)

**Comment by sandhiyakavi** [comment]
Verified in Prod
[nav_link_Thrive.zip](https://github.com/topcoder-platform/community-app/files/4474687/nav_link_Thrive.zip)
