### ISSUE TITLE
Update header and footer for Comcast

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4195]
Footer as per design.
Header to be as close as possible per design.

**Comment by SathyaJayabal** [comment]
Header and footer updated.  

<img width="1440" alt="Screenshot 2020-04-08 at 2 02 30 PM" src="https://user-images.githubusercontent.com/58783823/78762832-0728d200-79a2-11ea-9734-7a9cf78cfdbc.png">

Header has minor style issue
<img width="1406" alt="Screenshot 2020-04-08 at 2 04 38 PM" src="https://user-images.githubusercontent.com/58783823/78763181-730b3a80-79a2-11ea-90b5-f4b0cdcaf361.png">
![Uploading Screenshot 2020-04-08 at 2.07.46 PM.png…]()

**Comment by lakshmiathreya** [comment]
@SathyaJayabal - pls add Env label too ...

**Comment by lakshmiathreya** [comment]
and milestone ...

**Comment by SathyaJayabal** [comment]
Verified on prod
<img width="1410" alt="Screenshot 2020-04-08 at 4 14 38 PM" src="https://user-images.githubusercontent.com/58783823/78775610-1dd82480-79b4-11ea-97de-806abd5ee0e4.png">
<img width="1421" alt="Screenshot 2020-04-08 at 4 14 50 PM" src="https://user-images.githubusercontent.com/58783823/78775622-22044200-79b4-11ea-8af0-748f90a2608c.png">
