### ISSUE TITLE
Comcast Home : Overlapping between Home menu and Comcast Community dropdown.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4197]
**Describe the bug**
There is a overlapping between Home menu and Comcast Community dropdown.

Steps:
1. open 'https://comcast.topcoder.com/'
2. Check the header.

Expected behavior:
No overlapping between Home menu and Comcast Community dropdown in the header.

**Screenshots**
![image](https://user-images.githubusercontent.com/55895538/78781248-dadd7780-79da-11ea-825b-5a3d27c9a3da.png)

**Comment by SathyaJayabal** [comment]
@kkartunov happens when you resize the browser.

**Comment by kkartunov** [comment]
@SathyaJayabal mobile responsive is not in the scope

**Comment by SathyaJayabal** [comment]
closing as per above comment
