### ISSUE TITLE
Comcast: Banner Content issue- Font style is different from design

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4198]
Font style is different from design on the Home, Explore and Give back pages.

<img width="1440" alt="Screenshot 2020-04-08 at 5 46 35 PM" src="https://user-images.githubusercontent.com/58783823/78783333-179c7500-79c1-11ea-8a7d-46e2cdb5e540.png">

**Comment by kkartunov** [comment]
@SathyaJayabal style is per design. What is the issue here?

**Comment by SathyaJayabal** [comment]
@kkartunov , font weight is more. Its bolder.

**Comment by kkartunov** [comment]
@SathyaJayabal font is as per design see:
![Screenshot from 2020-04-16 17-26-28](https://user-images.githubusercontent.com/5585002/79468401-8e5ff080-8007-11ea-873f-53825a945fd5.png)

I think you can close this one.
