### ISSUE TITLE
Comcast Settings: Pop up button styles are different from the Topcoder site.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4201]
Description:
Pop up button styles are different from the Topcoder site.

Steps:
1. Go to 'https://www.topcoder.com/settings/profile#language'
2. Click Delete icon for an exisitng language.
3. Check the pop up message.

Expected behavior:
Pop up button styles should be same.

**Screenshots**
Comcast Popup:

<img width="370" alt="popup_comcast" src="https://user-images.githubusercontent.com/55895538/78784743-dc11a300-79e0-11ea-9768-afa5403c3b2a.PNG">

Topcoder popup:

<img width="389" alt="popup-topcoder" src="https://user-images.githubusercontent.com/55895538/78784693-c43a1f00-79e0-11ea-8a25-ed17ee02f5dd.PNG">

**Comment by kkartunov** [comment]
@sandhiyakavi they won't be the same. Comcast header won't match TC header.

**Comment by SathyaJayabal** [comment]
@kkartunov , some of the button styles are not applied correctly for comcast
<img width="1422" alt="Screenshot 2020-04-09 at 3 25 44 PM" src="https://user-images.githubusercontent.com/58783823/78883072-9dc6c300-7a76-11ea-825c-31aa3cb255b0.png">

**Comment by SathyaJayabal** [comment]
Closing this as this seems to be a problem with all sub communities
