### ISSUE TITLE
Comcast Explore: Paid Projects section must be Paid Work

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4202]
"Paid Projects" section must be "Paid Work". We already have a "Paid Projects" section on the home page.
cc @Oanh-and-only-Oanh 
<img width="1440" alt="Screenshot 2020-04-08 at 6 10 47 PM" src="https://user-images.githubusercontent.com/58783823/78785214-5aac1780-79c4-11ea-8059-56ffbd2985b4.png">.

<img width="1440" alt="Screenshot 2020-04-08 at 6 10 33 PM" src="https://user-images.githubusercontent.com/58783823/78785191-5122af80-79c4-11ea-9818-422d9b5378da.png">

**Comment by kkartunov** [comment]
@SathyaJayabal updated
