### ISSUE TITLE
Comcast Work Page: Clicking on a challenge gives a 404  error

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4206]
Expected: 

Clicking on a challenge from the listings page must take the user to the challenge detail page
https://comcast.topcoder.com/work?communityId=comcast&tab=details

Actual:
Clicking on a challenge from the listings page throws a 404 error.
[comcast challenge link.mov.zip](https://github.com/topcoder-platform/community-app/files/4455417/comcast.challenge.link.mov.zip)

**Comment by SathyaJayabal** [comment]
@kkartunov similar issue when you click on back from challenge details. Same issue for the submit button from challenge details.
[challenge details back.mov.zip](https://github.com/topcoder-platform/community-app/files/4455461/challenge.details.back.mov.zip)

**Comment by SathyaJayabal** [comment]
Verified on beta(feature branch)
[comcast_work links.mov.zip](https://github.com/topcoder-platform/community-app/files/4461739/comcast_work.links.mov.zip)

**Comment by SathyaJayabal** [comment]
Verified on beta(develop branch)
@kkartunov , there is one challenge that is displaying a blank page. Maybe it has bad data. All other challenge detail pages are working fine.
https://beta-community-app.topcoder.com/__community__/comcast/work/30122226

[challenge link .mov.zip](https://github.com/topcoder-platform/community-app/files/4474077/challenge.link.mov.zip)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , can we close out the below challenge as the challenge details page is not displayed for this one challenge, cc @kkartunov 
https://beta-community-app.topcoder.com/__community__/comcast/work/30122226

**Comment by sandhiyakavi** [comment]
Verified on Prod.

[4206_Prod_test.zip](https://github.com/topcoder-platform/community-app/files/4474758/4206_Prod_test.zip)
