### ISSUE TITLE
Shows "no access" page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4208]
I have to refresh multiple times to see the Comcast community page, this is not happening with TopGear or any other private community.

This is happening on beta and production as well.

![Topcoder 2020-04-09 20-12-27](https://user-images.githubusercontent.com/683231/78910985-4e4abc00-7aa3-11ea-83cb-3458bafa2406.png)

The work will be done against `hot-fix-accessing-comcast`

**Comment by sushilshinde** [comment]
@Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@sushilshinde @kkartunov , This issue happens to me but the page displays after a second without any refresh needed. Please see attached video.
cc @Oanh-and-only-Oanh 
[comcast.mov.zip](https://github.com/topcoder-platform/community-app/files/4457480/comcast.mov.zip)

**Comment by sushilshinde** [comment]
It should show loading indicator if there is waiting 

https://github.com/topcoder-platform/community-app/blob/94148104526449e6d461f59e089f21e28ede6474/src/shared/containers/tc-communities/Loader.jsx#L74

but it’s throwing 

https://github.com/topcoder-platform/community-app/blob/94148104526449e6d461f59e089f21e28ede6474/src/shared/containers/tc-communities/Loader.jsx#L99

for a render

**Comment by sandhiyakavi** [comment]
Tested in Beta Environment.Comcast community page is displayed without any refresh.

[#4208.zip](https://github.com/topcoder-platform/community-app/files/4468009/4208.zip)

**Comment by SathyaJayabal** [comment]
Verified on production

[comcast_loadingscreen.mov.zip](https://github.com/topcoder-platform/community-app/files/4470056/comcast_loadingscreen.mov.zip)
