### ISSUE TITLE
Even when there are no any registrants for the challenges, the submission count is displayed as 1.

### ISSUE THREAD

**Issue by Jobee1** [topcoder-platform/community-app#4209]
For the challenges where the registrants count is 0, the submission count is displayed as 1.

Attached video/screenshot file for reference:

![Screenshot_1](https://user-images.githubusercontent.com/48575864/78919518-ba342100-7ab1-11ea-82c4-661d2e518c76.png)

[No_registrants_Submission_count_1.zip](https://github.com/topcoder-platform/community-app/files/4457507/No_registrants_Submission_count_1.zip)

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , this also happens on production.

**Comment by SathyaJayabal** [comment]
closing this as its tracked here
https://github.com/topcoder-platform/community-app/issues/4288
