### ISSUE TITLE
Comcast: Give Back - Change title to Comcast Gives Back

### ISSUE THREAD

**Issue by aaabbott** [topcoder-platform/community-app#4215]
1. On the Give Back page, change "Comcast Supports You" to "Comcast Gives Back" and add then add some lorem ipsum under that.  
2. Below this, add a panel on the left for Comcast Cares with a button to learn more and another to sign up now (these don’t have to work).  
3. On the right lets add a panel for Comcast Codes for Good with a brief description under that which explains this is an opportunity to complete tasks or participate in freelance engagement for local non-profit organization

**Comment by aaabbott** [comment]
1. On the Give Back page, change "Comcast Supports You" to "Comcast Gives Back" and add then add some lorem ipsum under that.
2. Below this, add a panel on the left for Comcast Cares with a button to learn more and another to sign up now (these don’t have to work).
3. On the right lets add a panel for Comcast Codes for Good with a brief description under that which explains this is an opportunity to complete tasks or participate in freelance engagement for local non-profit organization

**Comment by kkartunov** [comment]
@aaabbott this is ready for review.

**Comment by aaabbott** [comment]
@kkartunov which environment?

**Comment by kkartunov** [comment]
prod
https://comcast.topcoder.com/give-back

**Comment by aaabbott** [comment]
Great, now i see it. must have needed to refresh my cache
