### ISSUE TITLE
Comcast: Give Back | Second section layout and copy updates

### ISSUE THREAD

**Issue by aaabbott** [topcoder-platform/community-app#4236]
If doable, we'd like to slightly tweak the layout of the second section of the page and update the copy. If the layout part is not safely doable for tomorrow (Tuesday), when the customer demos, we can skip this and just make the copy updates.

1. Layout update - instead of two sections, left and right, its a single section where the links are on the bottom. Note these links do not have to work; in fact, if easier to make it all a single image, that is no problem. Marvel link (https://marvelapp.com/4ec0h8g/screen/68071204) 
![image](https://user-images.githubusercontent.com/6266701/79159056-65d8bc00-7da5-11ea-9d06-97afe8f17fc3.png)

2. Copy updates - **Comcast Codes For Good** title remains unchanged. Can we change the other text to:

> “Comcast Cares is all about Comcast helping others. Here we are looking to use all the talents of Comcast team members to help do good for others. Helping non-profits, supporting our community - that is the goal of Comcast Cares. And you can be a big part of that, using your talents and skills for good.”

**Comment by aaabbott** [comment]
@Oanh-and-only-Oanh I have already reviewed this with @kkartunov and he's comfortable its doable tonight

**Comment by kkartunov** [comment]
Done.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1430" alt="Screenshot 2020-04-15 at 3 58 09 PM" src="https://user-images.githubusercontent.com/58783823/79327383-f8a66180-7f31-11ea-8b2a-09f34bb711f4.png">
