### ISSUE TITLE
Request to add Vue JS as a Skill

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#4238]
This ticket is to add Vue JS to the Skill list if its not already present. 

I couldn't verify the Skill List as its empty for me. (Raised another bug for this)

This issue was originally reported here: https://github.com/topcoder-platform/Training-Challenges/issues/57

**Comment by nithyaasworld** [comment]
CC: @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
Added Vue JS to doc below
https://docs.google.com/spreadsheets/d/1FGP7Ly9JFHtaXP9F_InSJT8Qyb9E5t3zTASoQTcyMww/edit#gid=0

**Comment by Oanh-and-only-Oanh** [comment]
going to close this for now.
