### ISSUE TITLE
[ UX / Usability bug ] Remove the register button from tracks when user is logged in

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#4240]
**Steps to Reproduce:**

1. Navigate to the landing page / Home page https://www.topcoder.com/
2. Log in or register
3. Click on COMMUNITY button
4. Click on the Tracks
5. Click on Design or Development or QA or Competitive Programming 

**Actual**
1. There is a 'How to compete' and 'Register with Topcoder' buttons in the content area

**Expected Results**
1. When I am already logged and registered with Topcoder, the 'Register with Topcoder' button is irrelevant. 
2. The button could be used for other buttons that redirect me to other resources 

**Screencast**
https://drive.google.com/open?id=1AzQ1wLrVAjFpSNNlUQ6sMcAz2z4JUQU7

Device/OS/Browser Information:
Google Chrome
Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
This bug was originally reported here: https://github.com/topcoder-platform/Training-Challenges/issues/60

**Comment by sandhiyakavi** [comment]
This issue is not applicable now.
