### ISSUE TITLE
Challenge listings page: Incorrect registrants count in Open for review challenges.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4245]
Description:
Incorrect registrants count is displayed for open for review challenges in Challenge listings page.

Steps:

1. Go to 'https://www.topcoder.com/challenges?'
2. Click on open for review in right side menu section.
3. Check the registrants count for a challenge.
4. Click the challenge.
5. Check the registrant count in Challenge details page.

Expected behavior:
Registrants count for the challenge should be the same in both Open for review challenge listing and challenge details page.

Screenshots

<img width="949" alt="reviewopportunities_registrantscount_1" src="https://user-images.githubusercontent.com/55895538/79228212-09a49380-7e9c-11ea-9ebe-396e6cde8157.PNG">

In Challenge details page:

<img width="955" alt="reviewopportunities_registrantscount_2" src="https://user-images.githubusercontent.com/55895538/79228242-16c18280-7e9c-11ea-8dd7-b5040c5e37fb.PNG">

**Comment by Oanh-and-only-Oanh** [comment]
@sandhiyakavi, can you verify if this is still an issue?

**Comment by sandhiyakavi** [comment]
Closing the issue as comparison is between the number of open positions for review and number of registrants of the challenge.

![image](https://user-images.githubusercontent.com/55895538/93044548-1d913300-f690-11ea-9d51-33de4bb2e728.png)
