### ISSUE TITLE
Got an error in browser console

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#425]
Uncaught TypeError: Cannot read property 'on' of undefined
    at <anonymous>:1:40
    at r.run (analytics.min.js:9)
    at i (analytics.min.js:9)

**Comment by vikasrohit** [comment]
Welcome @sushilshinde to the team!!

It is a known issue: https://github.com/appirio-tech/connect-app/issues/1111 It is appearing in all repos, where we have segment analytics integrated. It would be great if you can do more investigation about it.

**Comment by birdofpreyru** [comment]
Already logged in this repo as #174
