### ISSUE TITLE
Update nav to reflect thrive links for tracks pages

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4260]
Description:

Update nav to reflect thrive links for tracks pages - https://github.com/topcoder-platform/navigation-component/issues/168

**Comment by sandhiyakavi** [comment]
Verified on beta.Working as expected

Before login : 
[#4260_before_login.zip](https://github.com/topcoder-platform/community-app/files/4486328/4260_before_login.zip)

After login:

[#4260_after_login.zip](https://github.com/topcoder-platform/community-app/files/4486331/4260_after_login.zip)

**Comment by SathyaJayabal** [comment]
verified on prod



after login
[tracks nav_AL.mov.zip](https://github.com/topcoder-platform/community-app/files/4487596/tracks.nav_AL.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod



after login
[tracks nav_AL.mov.zip](https://github.com/topcoder-platform/community-app/files/4487596/tracks.nav_AL.mov.zip)

**Comment by SathyaJayabal** [comment]
before login
[tracks nav.mov.zip](https://github.com/topcoder-platform/community-app/files/4487658/tracks.nav.mov.zip)
