### ISSUE TITLE
Marathon match stats: Getting error message when trying to access MM challenges stats.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4262]
Description:

Getting error message when trying to access MM challenges stats.

Steps:

1. Go to 'https://www.topcoder.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH&tab=challenges'

Expected behavior:

User should be able to view the past MM challenges and no error message should be displayed.

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/79426211-c6facc80-7ffd-11ea-8182-32e0ff6d5809.png)

**Comment by SathyaJayabal** [comment]
tracked here #2359
