### ISSUE TITLE
After successful submission, "Back to Challenges" and "Submit Again" button is not displayed.

### ISSUE THREAD

**Issue by Jobee1** [topcoder-platform/community-app#4263]
After successful submission of any challenges,  "Back to Challenges" and "Submit Again" button is not displayed. It is being hidden.

Video/Image for reference:
![Screenshot_7](https://user-images.githubusercontent.com/48575864/79455418-8bb3ca00-800c-11ea-8ec7-92414aed9f67.png)

[issue1.zip](https://github.com/topcoder-platform/community-app/files/4486946/issue1.zip)

**Comment by kkartunov** [comment]
@SathyaJayabal why do you assign tickets to me?

**Comment by SathyaJayabal** [comment]
Issue is not solved. Please see screenshot
<img width="1440" alt="Screenshot 2020-04-17 at 6 25 52 PM" src="https://user-images.githubusercontent.com/58783823/79571529-f3cfe200-80d8-11ea-875b-fb0966e4e940.png">

**Comment by SathyaJayabal** [comment]
not resolved yet
<img width="1440" alt="Screenshot 2020-04-17 at 7 42 59 PM" src="https://user-images.githubusercontent.com/58783823/79578319-b45ac300-80e3-11ea-810a-c048ec72a7a2.png">

**Comment by sandhiyakavi** [comment]
Verified in Test Environment.Able to view the Back to challenge and submit again button.

![image](https://user-images.githubusercontent.com/55895538/79729346-4e13b180-832a-11ea-8214-99d26238c1af.png)

**Comment by sushilshinde** [comment]
@kkartunov can you PR to develop branch, please

**Comment by Oanh-and-only-Oanh** [comment]
placing on hold because "A certain user is not able to submit, but we are not able to reproduce the problem. Harshit has offered to work with the user one on one and try to find out more. No one else has the issue. But that user has been mailing support for everytime they submit."

**Comment by sandhiyakavi** [comment]
verified in Beta Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/79831019-92ae5400-83e1-11ea-82d3-3ce4653d79cb.png)

**Comment by Jobee1** [comment]
Tested and verified in Production.
![Screenshot_10](https://user-images.githubusercontent.com/48575864/79865270-a0bc9e80-83fa-11ea-95a7-929c794f8da9.png)
