### ISSUE TITLE
My Profile page: Forum posts got hidden in the Footer while scrolling down.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4264]
Description:
Forum posts got hidden in the Footer while scrolling down in the My Profile page.

Steps:
1. Go to 'https://beta-community-app.topcoder.com/members/SandhiyaA'
2. Scroll down to the page.

Expected behavior:

The user should be able to view the Forum posts link while scrolling to the bottom of the page.

Screenshots:

<img width="945" alt="forumpost" src="https://user-images.githubusercontent.com/55895538/79455977-adbb4580-8028-11ea-8a43-f4388e59d1cb.PNG">

**Comment by kkartunov** [comment]
@sandhiyakavi NO. This is not expected behavior. As you know we hide it because of this https://github.com/topcoder-platform/community-app/issues/4158
