### ISSUE TITLE
[$30] Challenge details arrow icons not displaying well

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#4268]
**Describe the bug**
The arrow icons on the challenge details page, for registrants tab are not displaying well anymore

**To Reproduce**
1. Go to https://www.topcoder.com/challenges/30122200?tab=registrants
2. Check the headers of the table Username, Registration date, etc. there is some strange sign there, instead of the old arrows

**Expected behavior**
Expect to see the arrow icons to sort by.

**Screenshots**
![image](https://user-images.githubusercontent.com/25185079/79501861-6c7e6200-8037-11ea-91a6-c0420dab461d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 75.0

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this is displaying fine now
<img width="1440" alt="Screenshot 2020-10-12 at 9 28 04 AM" src="https://user-images.githubusercontent.com/58783823/95704136-7e029880-0c6d-11eb-9a92-28f66941d8f3.png">
