### ISSUE TITLE
Zurich videos added to portal

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4272]
Added training videos to Zurich portal
See below
![image](https://user-images.githubusercontent.com/47536078/79583280-c1df6100-8081-11ea-83d6-23c9d02cb3c3.png)

6 training videos will be added to the "How it Works" page here https://zurich.topcoder.com/learn

The videos should be in 2 rows of 3 videos in the following order: 
![image](https://user-images.githubusercontent.com/47536078/79583681-3e723f80-8082-11ea-8d17-fa6698f481f6.png)

If possible, allow video to be played on website and downloaded. If not able to play on website without dev work on Community App, just download option is fine.

**Comment by Oanh-and-only-Oanh** [comment]
@kkartunov, I'm unable to added the movie files here so will send them to you directly via slack.

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh https://community-app.topcoder.com/examples/contentful/viewport/5wvD0VxpYWqwSAYQMy4qco?space=zurich

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh this is done. Want to close?

**Comment by Oanh-and-only-Oanh** [comment]
complete.
