### ISSUE TITLE
[$60] Subcommunities : Past Challenges are not displayed if directly accessed through url.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4279]
Description:
Past challenges are not displayed if accessed directly through url in Blockchain and Cognitive community.
url : https://blockchain.topcoder.com/challenges?communityId=blockchain&bucket=past
https://cognitive.topcoder.com/challenges?communityId=cognitive&bucket=past

Steps to Reproduce:

1. Go to 'https://blockchain.topcoder.com/challenges?communityId=blockchain&bucket=past'
2. Check if only past challenges are displayed.

Expected behavior:
Only past challenges should be displayed.

Actual behaviour:
All Challenges are displayed.

Screenshot:

BlockChain Community:
<img width="960" alt="blockchain_community" src="https://user-images.githubusercontent.com/55895538/79747329-6eea0000-8346-11ea-8cff-61cc7ae894cd.PNG">

cognitive community:
<img width="957" alt="comcast_community" src="https://user-images.githubusercontent.com/55895538/79747355-7a3d2b80-8346-11ea-8f55-f7fbfa2146ac.PNG">

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , closing this now, as we do not have the past challenges bucket anymore
