### ISSUE TITLE
No Email Preferences visible

### ISSUE THREAD

**Issue by saksham189** [topcoder-platform/community-app#4280]
**Describe the bug**
I want to get email notifications for SRM. However when I go to settings -> Preferences -> email preferences
there are no settings or options available and the screen is blank.

**To Reproduce**
1. Login to topcoder
2. Click on the arrow beside your username (in top right corner) and select settings.
3. Select Preferences and Email Preferences should show up.
4. There should be a blank screen with no settings available. 

**Expected behavior**
There should be setting to get emails for SRM.

**Screenshots**
![Screenshot 2020-04-19 at 12 07 09 AM](https://user-images.githubusercontent.com/7020962/79763993-68598980-8342-11ea-98f5-7bab34b72fcd.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser Google Chrome
 - Version 81.0.4044.113 (latest)

**Comment by SathyaJayabal** [comment]
@saksham189 This section will be added shortly
https://github.com/topcoder-platform/community-app/issues/4165

**Comment by SathyaJayabal** [comment]
FYI: https://github.com/topcoder-platform/community-app/issues/3641
