### ISSUE TITLE
Add link Changlog to footer in About Section 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4283]
Changelog - https://www.topcoder.com/community/changelog

**Comment by sandhiyakavi** [comment]
verified in Beta Env.Working as expected.

<img width="938" alt="footer" src="https://user-images.githubusercontent.com/55895538/79843259-ff7f1980-83f4-11ea-82bc-777dc912cdee.PNG">

![image](https://user-images.githubusercontent.com/55895538/79843272-0574fa80-83f5-11ea-89b3-dd84af4b46ce.png)

**Comment by Jobee1** [comment]
Tested and verified in Production.
![Screenshot_8](https://user-images.githubusercontent.com/48575864/79864369-14f64280-83f9-11ea-96ef-f41b37327dcd.png)

![Screenshot_9](https://user-images.githubusercontent.com/48575864/79864380-1a538d00-83f9-11ea-853d-165a0b894dd3.png)
