### ISSUE TITLE
Fix content on the bottom of challenge details

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4286]
Related to #4234

Update the payments paragraph to say

Topcoder will compensate members in accordance with our standard payment policies, unless otherwise specified in this challenge. For information on payment policies, setting up your profile to receive payments, and general payment questions, please refer to [Payment Policies and Instructions](https://www.topcoder.com/thrive/articles/Payment%20Policies%20and%20Instructions).

Remove Reliability Section completely.

**Comment by Jobee1** [comment]
Verified in Test Environment:
![4286_test](https://user-images.githubusercontent.com/48575864/80713414-1ddec680-8b13-11ea-8088-01f13cf97c38.png)

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-05-19 at 2 54 19 PM" src="https://user-images.githubusercontent.com/58783823/82309392-b369c980-99e0-11ea-8827-60a81991ae2c.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-05-21 at 4 14 19 PM" src="https://user-images.githubusercontent.com/58783823/82551629-2bb9c180-9b7e-11ea-8afd-1cb154217294.png">
