### ISSUE TITLE
Topcoder Home page redirects to splash page when accessed for the first time

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4287]
Topcoder Home page redirects to splash page when accessed for the first time. 
This could be a redirection after login/ logout, or clicking on the topcoder logo from the header or directly accessing the homepage from the url.
[splash.mov.zip](https://github.com/topcoder-platform/community-app/files/4514549/splash.mov.zip)
[splash2.mov.zip](https://github.com/topcoder-platform/community-app/files/4514553/splash2.mov.zip)

**Comment by sandhiyakavi** [comment]
Closing this issue as it is not happening now.
