### ISSUE TITLE
[Dashboard] All the filter options are not displayed when clicking on any filter with 0 challenges.

### ISSUE THREAD

**Issue by Jobee1** [topcoder-platform/community-app#4295]
In the filter, when there is even only one challenges, all the list in the filter is displayed but if there is 0 challenges, the list is hidden.

Attached screenshot with challenges and without any challenges
**With Challenges** 
![Screenshot_25](https://user-images.githubusercontent.com/48575864/80336685-b2c59380-8877-11ea-9dac-c0622831d6af.png)

**Without challenges**:
![Screenshot_24](https://user-images.githubusercontent.com/48575864/80336634-8c075d00-8877-11ea-838d-bca02c472ce6.png)

**Comment by sandhiyakavi** [comment]
This issue is not applicable now.
