### ISSUE TITLE
Add "Practice" to drop down navigation

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4297]
Add "Practice" to drop down navigation next to Gig Work
![image](https://user-images.githubusercontent.com/47536078/80387787-e3003880-885d-11ea-9a8b-134b289c47b4.png)

- Page is visible to all users (members and non-members). But only registered members can register for the practice challenges and compete
- When a user clicks on "Practice", direct user to new URL: https://www.topcoder.com/community/practice 
- https://www.topcoder.com/community/practice URL is a new Practice page (in development) 

Deadline to go LIVE: May 13, 2020

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Can you confirm if URL is right, looks like not present in Dev:
https://www.topcoder-dev.com/community/practice

**Comment by luizrrodrigues** [comment]
The navigation is ready in `nav-practice` branch:
https://github.com/topcoder-platform/community-app/pull/4364

On ~HOLD until we have page ready too.

![Screen Shot 2020-05-13 at 14 23 11](https://user-images.githubusercontent.com/7029641/81844865-1ca39580-9526-11ea-85a4-a5a80265512f.png)
![Screen Shot 2020-05-13 at 14 22 10](https://user-images.githubusercontent.com/7029641/81844868-1dd4c280-9526-11ea-86bf-f6061701ed59.png)

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-06-30 at 2 23 05 PM" src="https://user-images.githubusercontent.com/58783823/86106441-2edd9100-bade-11ea-9d54-4f1a207c1478.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-02 at 4 41 35 PM" src="https://user-images.githubusercontent.com/58783823/86352115-f0cda200-bc82-11ea-8184-4ab44024f452.png">
