### ISSUE TITLE
Profile page is getting 404 error

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4299]
Getting an error looking up a member profile

Go to https://www.topcoder.com/members/igoroshko
See 404 error

**Comment by skyhit** [comment]
@Oanh-and-only-Oanh this is related to v3 member api, like https://api.topcoder.com/v3/members/igoroshko

should I work with @urwithat to figure this out?

**Comment by Oanh-and-only-Oanh** [comment]
closing because this is not a handle...
