### ISSUE TITLE
New Customer/Member registration page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4306]

**Comment by mtwomey** [comment]
As for the page where user's choose - let’s just build it into the marketing site. quesks should be able to help here. It just need to offer the two options and direct the user to accounts app with the appropriate return URL set.

**Comment by Oanh-and-only-Oanh** [comment]
link in staging is https://www.topcoder.com/staging/memberaccount/
password is m3mb3r4cc0unt

**Comment by Oanh-and-only-Oanh** [comment]
closing issue because we will not have the new Member/Customer selection page on Community App. Everyone will be assigned Member when they sign up from Community App.
