### ISSUE TITLE
Thrive page filter by date is not working

### ISSUE THREAD

**Issue by charan2628** [topcoder-platform/community-app#4308]
**Describe the bug**
In Thrive page when I'm applying filter by date it's not working.

**To Reproduce**
1. Please visit this [URL](https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming&author=All%20authors&startDate=2020-03-01T17%3A30%3A00%2B05%3A30&endDate=2020-04-27T15%3A27%3A30%2B05%3A30&tax=SRM%20Editorials).

**Expected behavior**
I should get SRM editorials between Mar 1 2020 and Apr 27 2020.

**Screenshots**
![Screenshot (117)](https://user-images.githubusercontent.com/20705703/80560786-f2b78280-89ff-11ea-9fc0-db144fb578aa.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 
 - 76.0b6

**Comment by sandhiyakavi** [comment]
Thrive page filter by date is working now.

![image](https://user-images.githubusercontent.com/55895538/107616326-2dd62a00-6c91-11eb-9b79-ed94ef78ade5.png)
