### ISSUE TITLE
GA Tracking Code Change

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4309]
1. Move GAIDs for prod and dev profiles to env vars instead of config file.
2. Move all the GA code to community-app from topcoder-react-lib
Get rid of this dependency cycle 
![Webgraphviz 2020-04-29 11-54-23](https://user-images.githubusercontent.com/683231/80566593-f3a4e000-8a10-11ea-9c26-49d8c49c5483.png)

**Comment by luizrrodrigues** [comment]
@sushilshinde branch `ga-hotfix` ready to deploy.

**Comment by SathyaJayabal** [comment]
verified on test env (`ga-hotfix` branch)
<img width="1132" alt="Screenshot 2020-05-08 at 10 19 40 AM" src="https://user-images.githubusercontent.com/58783823/81371607-ede88200-9115-11ea-9d38-da24c40fa657.png">

**Comment by SathyaJayabal** [comment]
verified on beta env (`ga-hotfix` branch)
The events are tracked in the prod GA account. @luizrrodrigues is that fine?
<img width="1425" alt="Screenshot 2020-05-08 at 12 24 31 PM" src="https://user-images.githubusercontent.com/58783823/81379661-247ac880-9127-11ea-9d5c-a351bea53582.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yes, that is working as expected. 

> Last time was tracked wrong because of the existing problem with `topcoder-react-lib`

**Test** or **Dev** env = Tracking in Develop GA account
**Beta** env = Tracking in Production GA account

**Comment by SathyaJayabal** [comment]
@luizrrodrigues the change tab event is not tracked and we are getting a console error
<img width="1440" alt="Screenshot 2020-05-09 at 11 40 28 AM" src="https://user-images.githubusercontent.com/58783823/81465771-00cc8680-91ea-11ea-8b29-52faae05c757.png">

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
<img width="1437" alt="Screenshot 2020-05-09 at 1 20 06 PM" src="https://user-images.githubusercontent.com/58783823/81467673-f74a1b00-91f7-11ea-8399-8d4eb6e22ad0.png">

<img width="1440" alt="Screenshot 2020-05-09 at 1 19 52 PM" src="https://user-images.githubusercontent.com/58783823/81467668-ec8f8600-91f7-11ea-975b-926f51edcf58.png">

**Comment by SathyaJayabal** [comment]
verified on test(develop branch)
<img width="1138" alt="Screenshot 2020-05-09 at 1 35 02 PM" src="https://user-images.githubusercontent.com/58783823/81467964-f2866680-91f9-11ea-9466-369acb0fa822.png">

**Comment by SathyaJayabal** [comment]
verified on prod.
<img width="1440" alt="Screenshot 2020-05-12 at 12 43 45 PM" src="https://user-images.githubusercontent.com/58783823/81662839-c538f300-945b-11ea-9e44-4148ec4bef32.png">
