### ISSUE TITLE
Topcoder Community's Hall of fame pages are down.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4312]
Description:

The hall of fame page : https://www.topcoder.com/community/hall-of-fame/tco is broken.

![image](https://user-images.githubusercontent.com/55895538/80669416-52388f80-8adf-11ea-9bd5-097e3d13333e.png)

**Comment by sandhiyakavi** [comment]
Verified in Beta. Working as expected

![image](https://user-images.githubusercontent.com/55895538/80671967-4ac8b480-8ae6-11ea-80a7-7076572fbf08.png)

**Comment by sandhiyakavi** [comment]
Verified on Beta (develop branch). Working as expected.

![image](https://user-images.githubusercontent.com/55895538/80680229-51acf280-8af9-11ea-944b-bf243baeb876.png)

**Comment by SathyaJayabal** [comment]
verified on prod

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-04-30 at 6 13 48 PM" src="https://user-images.githubusercontent.com/58783823/80711695-65af1f00-8b0e-11ea-9063-f4d89c573df3.png">

**Comment by SathyaJayabal** [comment]
Reopened this as this change was reverted.
https://topcoder.slack.com/archives/C53KB3T7Z/p1588700782350900

**Comment by SathyaJayabal** [comment]
cc @LieutenantRoger @Oanh-and-only-Oanh we will need to fix this, as original fix was reverted and the Hall of Fame pages are again broken.
https://topcoder.slack.com/archives/C53KB3T7Z/p1588700782350900
<img width="1440" alt="Screenshot 2020-05-06 at 8 26 35 AM" src="https://user-images.githubusercontent.com/58783823/81134754-5814f180-8f73-11ea-94ba-ffac0430d28f.png">
