### ISSUE TITLE
Community site getting 404 cloudfront URL

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4317]
**Describe the bug**
Sometimes when a user access community site is broken, it looks like missing CSS styles.

**To Reproduce**
1. Go to www.topcoder.com
2. Click on COMMUNITY
3. Sometimes page looks broken
4. See the errors in the browser console

**Screenshots**
![Screen Shot 2020-04-30 at 13 55 36](https://user-images.githubusercontent.com/7029641/80737747-561ddf00-8aea-11ea-991e-ce7b1256a6f4.png)

![Screen Shot 2020-04-30 at 13 55 54](https://user-images.githubusercontent.com/7029641/80737757-59b16600-8aea-11ea-8c3a-ba4f86fa07aa.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari, Chrome and Firefox
 - Version: Latest

**Additional context**
Looks like sometimes the community site calling old/remove URLs from Cloudfront:
https://d1of0acg2orgco.cloudfront.net/static-assets/main-1588232511636.css

But sometimes get the right one:
https://d2nl5eqipnb33q.cloudfront.net/static-assets/main-1588248246833.css

**Comment by kkartunov** [comment]
![Screenshot from 2020-05-01 10-30-33](https://user-images.githubusercontent.com/5585002/80790609-00077500-8b98-11ea-94f6-44e9d3efe0b7.png)

**Comment by adroc-tc** [comment]
Still seeing this issue @Oanh-and-only-Oanh

**Comment by adroc-tc** [comment]
@Oanh-and-only-Oanh @mtwomey this issue still seems to be happening - clearing cache is not a fix. 
- I get "white" blank pages on some of the pages (randomly) and some after clearing cache either reappear or stay white. It is not consistent.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this was fixed with the CF hotfix
https://github.com/topcoder-platform/community-app/commit/fac841270b12f5570bf08139492a25e36cf888a6

@adroc-tc the blank pages is tracked here
#4338
