### ISSUE TITLE
User handle is not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4318]
The user handle and profile picture is not displayed in the header
<img width="1430" alt="Screenshot 2020-05-01 at 9 39 12 AM" src="https://user-images.githubusercontent.com/58783823/80781366-ac912900-8b8f-11ea-85f0-db8132c16818.png">

**Comment by Jobee1** [comment]
The sub-menus under "Community" is also not displayed accordingly after the user is logged in. "Overview" and "How it Works" is displayed while "Dashboard" "My Profile" and "Payments" should have been displayed. 

![Screenshot_40](https://user-images.githubusercontent.com/48575864/80787124-4fa06d80-8ba5-11ea-9874-17e74add234a.png)

**Comment by Jobee1** [comment]
This issue still persists in Dev environment.
