### ISSUE TITLE
Challenge  Listings: Ongoing  and Open for Registration counts Issue

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4319]
A challenge must be either in Open for registration or Ongoing. But we find most of  the challenges in both the buckets
<img width="427" alt="Screenshot 2020-05-01 at 9 43 55 AM" src="https://user-images.githubusercontent.com/58783823/80781604-959f0680-8b90-11ea-8d11-6399f8c4caf4.png">
@LieutenantRoger, you can move this to API repo is this is an API issue.

**Comment by Jobee1** [comment]
Tested in dev Environment. 
The count is displayed only for "All Challenges" and no count is displayed for other.

![Screenshot_12](https://user-images.githubusercontent.com/48575864/82015058-9f029580-969d-11ea-8f79-8c1bc647a682.png)
