### ISSUE TITLE
Size of avatars returned by API

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#432]
Right now, API returns user avatar images with their original size. E.g. mine is 1269 x 1269 px. I am not aware about any place in the platform, where such size is necessary; however I am aware of at least one place (past challenges in the challenge listings) where we do render many avatars in the same page, and loading them with this size surely has an impact on performance. I believe, we need a special API for getting avatar images with desired size (e.g. a few predefined ones, so that API can scale them once to a few sizes, and then serve requested ones answering to the call like `/avatar/birdofpreyru.jpeg?size=small`).

**Comment by sushilshinde** [comment]
https://www.npmjs.com/package/express-resize

@birdofpreyru  Something like this?

**Comment by birdofpreyru** [comment]
I don't know, what code handles avatar images in Topcoder backend, but I would guess it is Java?

**Comment by sushilshinde** [comment]
It will be very effective if it can be done at CDN level, CDN server should be able to interpret GET request and run optimizing logic based on URL params.

Something like this. http://blog.endpoint.com/2016/05/caching-resizing-reverse-proxying-image-server-nginx.html

Dynamic image optimization shouldn't be part of backend or API layer. Though any backend framework whether Spring(Filter) or Express JS(middleware) will have a solution for sure.

**Comment by birdofpreyru** [comment]
For a record, I took care about this in https://github.com/topcoder-platform/community-app/commit/21e7d81672d1be0c9f8456205a8285fb2b681bb3 and the next, not yet commited update. It lacks testing and deployment to prod, but otherwise we may consider it is solved.
