### ISSUE TITLE
Challenge details: Register Button not active even though challenges is in registration phase

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4321]
Challenge details: Register Button not active even though challenges is in registration phase

<img width="1428" alt="Screenshot 2020-05-01 at 9 53 16 AM" src="https://user-images.githubusercontent.com/58783823/80781889-b1ef7300-8b91-11ea-873c-4bca46740347.png">

**Comment by Jobee1** [comment]
This issue still exists in Dev environment.
