### ISSUE TITLE
Challenge Listing: Track filters  are not working

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4322]
The tracks filters are not working as expected. Only the data science contest are  getting filtered.
[Uploading track filters.mov.zip…]()

<img width="1440" alt="Screenshot 2020-05-01 at 10 00 35 AM" src="https://user-images.githubusercontent.com/58783823/80782174-a94b6c80-8b92-11ea-87a9-729a069dd9c7.png">
<img width="1440" alt="Screenshot 2020-05-01 at 10 00 45 AM" src="https://user-images.githubusercontent.com/58783823/80782202-bf592d00-8b92-11ea-874a-9eeea43450af.png">

**Comment by Jobee1** [comment]
Tested in dev environment.

Challenge Listing: Disabling either "Data Science" or "Development" or "Design" from the filter displays blank page.

Attached Screenshot/Video for reference:
![Screenshot_13](https://user-images.githubusercontent.com/48575864/82021654-ef342480-96aa-11ea-92a6-6b132434cf9c.png)

[data_science_blank_page.zip](https://github.com/topcoder-platform/community-app/files/4632758/data_science_blank_page.zip)

[design_blank_page.zip](https://github.com/topcoder-platform/community-app/files/4632760/design_blank_page.zip)

[Development_blank_page.zip](https://github.com/topcoder-platform/community-app/files/4632762/Development_blank_page.zip)
