### ISSUE TITLE
Challenge  Listings: Sub tracks filter not working

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4324]
Challenge  Listings: Sub tracks filter not working

<img width="1440" alt="Screenshot 2020-05-01 at 10 24 27 AM" src="https://user-images.githubusercontent.com/58783823/80783017-fe3cb200-8b95-11ea-952e-311ed842255d.png">
<img width="1440" alt="Screenshot 2020-05-01 at 10 24 35 AM" src="https://user-images.githubusercontent.com/58783823/80783042-10b6eb80-8b96-11ea-9ba9-10098cc5b809.png">

**Comment by sandhiyakavi** [comment]
Retested the issue.Sub track filter is working fine now.

![image](https://user-images.githubusercontent.com/55895538/82026143-4a770e80-96cd-11ea-9393-7688283ca91f.png)

Hence closing the issue.
