### ISSUE TITLE
Profile Settings -> Accounts page is throwing a 404 error

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4329]
Profile Settings -> Accounts page is throwing a 404 error

<img width="1440" alt="Screenshot 2020-05-01 at 11 44 00 AM" src="https://user-images.githubusercontent.com/58783823/80786391-22ea5700-8ba1-11ea-9e9c-9d766dd9718a.png">

**Comment by sandhiyakavi** [comment]
Retested in Dev Environment. Issue still exists.
