### ISSUE TITLE
Challenge Listings: Open for review is loading a blank page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4330]
Challenge Listings: Open for review is loading a blank page
<img width="1440" alt="Screenshot 2020-05-01 at 11 51 23 AM" src="https://user-images.githubusercontent.com/58783823/80786723-1d414100-8ba2-11ea-8853-0feb35f62e50.png">

**Comment by sandhiyakavi** [comment]
Retested in Dev Environment.Issue still exists.
