### ISSUE TITLE
My Profile history stats: Active challenges count issues

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4333]
Description:
Active challenges count is displayed in the Profile history stats, though there are no active challenges for the user.

Screenshot:

Profile history stats page:
<img width="948" alt="active_challenges" src="https://user-images.githubusercontent.com/55895538/80787356-4d4c0c80-8bc1-11ea-8ef7-25df8b3f6bb2.PNG">

My Challenges count in Challenge listing page:
<img width="956" alt="my_challenges" src="https://user-images.githubusercontent.com/55895538/80787385-5ccb5580-8bc1-11ea-92c4-82e8fc7397cf.PNG">

**Comment by SathyaJayabal** [comment]
The my challenges in the listings page is not displaying the correct count

**Comment by sandhiyakavi** [comment]
Retested the issue in Dev Environment.Getting the error "Failed to get member active challenges" on clicking the history stats section.

![image](https://user-images.githubusercontent.com/55895538/82016820-cddc3400-96bc-11ea-9f8c-2e5724b9fc3d.png)
