### ISSUE TITLE
Challenge Listings: Incomplete challenge data

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4335]
Challenge data has been loaded from 2019-01-01 forward https://topcoder.slack.com/archives/CCXM6QZQC/p1588315066203200

But we dont see any challenges in past challenges, nor any registrants or submissions for any challenges

<img width="1440" alt="Screenshot 2020-05-01 at 12 17 44 PM" src="https://user-images.githubusercontent.com/58783823/80788075-cc334c00-8ba5-11ea-98e5-0babbaea1e5d.png">
<img width="1440" alt="Screenshot 2020-05-01 at 12 17 47 PM" src="https://user-images.githubusercontent.com/58783823/80788093-d2c1c380-8ba5-11ea-98f9-875ab882fedd.png">

**Comment by sandhiyakavi** [comment]
Adding to the above issue.The current status in the Challenge details page is displayed as Registration for all challenges, irrespective of their status.

![image](https://user-images.githubusercontent.com/55895538/80793509-4679c580-8bd2-11ea-956f-11dfa322a34d.png)

**Comment by sandhiyakavi** [comment]
The above mentioned issues still exists in Dev Environment.
