### ISSUE TITLE
My dashboard blank page

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4338]
**Describe the bug**
https://www.topcoder.com/my-dashboard shows blank page. Needs reload/refresh to appear.

**To Reproduce**
1. Open new tab in Chrome
2. Go to https://www.topcoder.com/my-dashboard
3. See error - blank page is shown
4. Refresh page to reload

**Expected behavior**
Page to appear directly.

**Screenshots**
https://drive.google.com/file/d/1uMcpGjLDktO5pVmtbN2bJM-kPjiIKRdF/view

**Comment by SathyaJayabal** [comment]
Also happens for the challenge listings page occasionally.

**Comment by SathyaJayabal** [comment]
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , also observed here by Adam.
https://github.com/topcoder-platform/community-app/issues/4317#issuecomment-624118536

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, can you confirm it's still happening after Matt's revert yesterday?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh ,this  seems to be  a different issue than the rendering issue. This one is still happening occasionally.

**Comment by SathyaJayabal** [comment]
@mtwomey @luizrrodrigues @Oanh-and-only-Oanh 
Tested  the `ga-hotfix`branch on beta env for the blank screen issue. The blank screen issue was 
 encountered in the below places. When  we click on the browser back button from the blank screen the previous page also displays a blank screen. All other  pages were displayed correctly and no new issues found during the smoke test.
Sub community pages:
1. TCO20 page : https://beta-community-app.topcoder.com/__community__/tco20
2. Block Chain page:  https://beta-community-app.topcoder.com/__community__/blockchain
3. Submit from Dashboard->My Active Challenges tab (Strangely this seems to be a very old known issue and we can still see this one on production https://github.com/topcoder-platform/community-app/issues/3329 )
<img width="1440" alt="Screenshot 2020-05-08 at 1 17 21 PM" src="https://user-images.githubusercontent.com/58783823/81392442-4fbbe280-913c-11ea-8c7c-1ecfeed2f9a1.png">
<img width="1440" alt="Screenshot 2020-05-08 at 2 48 41 PM" src="https://user-images.githubusercontent.com/58783823/81392449-55192d00-913c-11ea-831e-9bd2bb8d9bf0.png">
<img width="1440" alt="Screenshot 2020-05-08 at 2 59 29 PM" src="https://user-images.githubusercontent.com/58783823/81392639-9578ab00-913c-11ea-8cd3-633bb7544a3a.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal 

1. and 2. Can you please try clear cache and try again, looks for error you had shared and looks like the issue with CDN url.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal 

3. I see the issue, but it looks like this not related to the original issue related here. 

I think we need to create a new issue to track the issue when trying access the Submission page via the Dashboard page. 

So we can release the `ga-hotfix` to **community-app** to the recent release.

@Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@luizrrodrigues 
We already have an issue for 3. 
I cant seem to reproduce 1 and 2. Let us go ahead with this and open a new issue in case we see 1 and 2 again. We don't want to delay the hotfix.
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
Verified on beta (develop branch). Completed a smoke test. Tested the following scenarios for the blank screen issue:

- Logout and login and then access the page

- Be inactive in a page for 10 mins(for token expiry) and then refresh  the page

- Access the pages directly through the URL

- Clear the cache and access the page

- Test in incognito mode

**Comment by SathyaJayabal** [comment]
Verified on prod.
