### ISSUE TITLE
URLs not bolded when within markdown tags

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4344]
Example: https://www.topcoder.com/community/changelog

Notice how the links are not bolded with the rest of it's area.

**Comment by sandhiyakavi** [comment]
Verified in Test Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/81061909-228aec80-8f10-11ea-8b19-41d8c56665f4.png)

**Comment by SathyaJayabal** [comment]
Verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-05-20 at 12 17 07 PM" src="https://user-images.githubusercontent.com/58783823/82413932-e02ae900-9a93-11ea-964d-73044256302f.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-05-21 at 4 34 27 PM" src="https://user-images.githubusercontent.com/58783823/82553065-f82c6680-9b80-11ea-9093-c6ca4402f95d.png">
