### ISSUE TITLE
topcoder-react-lib using Development config file in Production

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4345]
@sushilshinde This ticket to track the issue we discuss before.

**Comment by luizrrodrigues** [comment]
Maybe related with this commit: https://github.com/topcoder-platform/topcoder-react-lib/commit/6435cd4f5754cdee0237ccec6dffe91601d481e9

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Issue found.

The origin of the issue was in this commit: https://github.com/topcoder-platform/topcoder-react-lib/commit/2106478707389fdbe0451ed25601d7efabedbce6#

This removed `NODE_ENV=` from package.json

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , how de we verify this issue. Will verification of #4336 cover this one too?

**Comment by luizrrodrigues** [comment]
Yes, this one fix #4336 issue.

To verify, just check the AV Scan ID, `topcoder-react-lib` have a configuration file to dev and prod env.

**topcoder-react-lib**
```
config/development.json
config/production.json
```

**Comment by SathyaJayabal** [comment]
verified on beta.
<img width="516" alt="Screenshot 2020-05-11 at 11 00 21 AM" src="https://user-images.githubusercontent.com/58783823/81555972-2226a180-93a7-11ea-836e-0be5df0f77f1.png">

<img width="993" alt="Screenshot 2020-05-11 at 4 46 25 PM" src="https://user-images.githubusercontent.com/58783823/81555959-1b982a00-93a7-11ea-9f17-3da32eb5b64a.png">

**Comment by SathyaJayabal** [comment]
Verified on beta (develop branch)
<img width="993" alt="81555959-1b982a00-93a7-11ea-9f17-3da32eb5b64a" src="https://user-images.githubusercontent.com/58783823/81669068-43e55e80-9463-11ea-8c4b-895d29d608fd.png">
<img width="1440" alt="Screenshot 2020-05-12 at 3 13 17 PM" src="https://user-images.githubusercontent.com/58783823/81669078-48117c00-9463-11ea-8017-64461f67e1c8.png">

**Comment by sandhiyakavi** [comment]
Verified in Production Env. Working as Expected.
