### ISSUE TITLE
Challenge Details: Two tooltip with same content displayed on hovering over the Question mark near Review scorecard link.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4348]
Description:
Two tooltip with same content is displayed on hovering over the Question mark near Review scorecard link in the Challenge details page.

Screenshot:
<img width="960" alt="image (1)" src="https://user-images.githubusercontent.com/55895538/81146361-173ccd00-8fb3-11ea-8190-e152a06d6e44.png">

**Comment by Oanh-and-only-Oanh** [comment]
@sandhiyakavi, is the challenge API related?

**Comment by sandhiyakavi** [comment]
@Oanh-and-only-Oanh No it is not related to challenge API

**Comment by sandhiyakavi** [comment]
Closing this issue as it is not happening now.

![image](https://user-images.githubusercontent.com/55895538/107482970-c0a89300-6bc3-11eb-881a-9ab1550a7c29.png)
