### ISSUE TITLE
Submission Management Page is not quite responsive to the window size

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#435]
Problem is that we (at least I) don't have mobile / tablet designs for it.

**Comment by vic-topcoder** [comment]
Push back to DaraK - she'll add that/fix those missing things

**Comment by Dara-K** [comment]
I will design that for you tomorrow. But being honest, I don't know how many people will upload submissions from their phone :)

**Comment by birdofpreyru** [comment]
@Dara-K Probably nobody, but somebody might try to double-check what has he submitted before. I believe, there is no need be especially fancy for it.

**Comment by Dara-K** [comment]
Here they are: designs and specifications.

[Submissions Management - Design and Specs.zip](https://github.com/topcoder-platform/community-app/files/1286399/Submissions.Management.-.Design.and.Specs.zip)
