### ISSUE TITLE
Add terms page to footer

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4353]
Link https://www.topcoder.com/community/terms as "Terms" in the footer. It should be the last Item under "About".

**Comment by Jobee1** [comment]
Verified in Test environment. 

Attached screenshot for reference:
![Screenshot_2](https://user-images.githubusercontent.com/48575864/81306991-da9acf80-909f-11ea-9787-292a7aa7f044.png)

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @kkartunov let's close this only after assigning the correct milestone.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-05-28 at 6 25 31 PM" src="https://user-images.githubusercontent.com/58783823/83144199-ab143b80-a110-11ea-8ef9-a7c783e54e54.png">
