### ISSUE TITLE
Thrive article URLs to support hyphens

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4354]
We plan to deprecate spaces in Thrive article URLs. So links like https://www.topcoder.com/thrive/articles/Setting%20Up%20Topcoder%20Java%20Applet%20Arena%20&%20Kawigi%20Editor will turn into a more friendly format with hyphens.

Expected: Thrive article URLs to support hyphens and spaces (%20).

Test demo article with hyphens slug set to it:
https://test-community-app.topcoder-dev.com/thrive/articles/Data-Science-Challenge-Types
https://test-community-app.topcoder-dev.com/thrive/articles/Data%20Science%20Challenge%20Types

**Comment by Jobee1** [comment]
Verified in Test environment:

Attached screenshot for reference:
With hyphens:
![Screenshot_3](https://user-images.githubusercontent.com/48575864/81307556-86441f80-90a0-11ea-8bbb-fd6589cb91ad.png)

With spaces:
![Screenshot_4](https://user-images.githubusercontent.com/48575864/81307619-9825c280-90a0-11ea-9b71-263aa2b88bf5.png)

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @kkartunov - let's close this only after assigning the correct milestone.

**Comment by SathyaJayabal** [comment]
verified on prod for the example article.
 As per @kkartunov  the rest of the articles will support the hyphen format when the hyphen slug is enabled in contentful

<img width="1440" alt="Screenshot 2020-05-28 at 6 40 38 PM" src="https://user-images.githubusercontent.com/58783823/83145780-f891a800-a112-11ea-8c83-d22d22a649ae.png">
<img width="1440" alt="Screenshot 2020-05-28 at 6 40 53 PM" src="https://user-images.githubusercontent.com/58783823/83145795-fdeef280-a112-11ea-938e-03a4214c70c3.png">
