### ISSUE TITLE
Loading Indicator

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#436]
Now we are using this one all around the app:
![ripple](https://user-images.githubusercontent.com/20144632/30141113-576bb7bc-9379-11e7-9d93-24ae652eff1a.gif)
There are two problems, visible if you try to place this gif above a non-white background:

1. In some frames of the animation it has solid white background, which blinks against a non-white background.

2. Also transition between circles and transparent background is not well anti-aliazed: possible to see some ugly white pixels on the edge of these circles.

Thus, at the moment we can use this loading indicator only against white background.
Also, I believe, it whould be cool to have a smaller version of the indicator, to show inside buttons when we are waiting for the result of action triggered by a button.

**Comment by Dara-K** [comment]
Can you show me a html page on the site where is posted on a non-white background? so I can see the problems

**Comment by birdofpreyru** [comment]
@Dara-K Please meet the test page for loading indicators:
http://community-west.topcoder-dev.com/examples/loading-indicators
I guess, we need to re-draw current indicator as animated SVG instead of GIF.
And then we can add more variants for different use-cases / sizes.

**Comment by Dara-K** [comment]
Agree. Thanks for making the test page.

Will work on making it the same first time.

**Comment by Dara-K** [comment]
Let me know if you need to explain the animation somehow else.
[Preloader.zip](https://github.com/topcoder-platform/community-app/files/1307470/Preloader.zip)
