### ISSUE TITLE
Communities Page: Getting "Failed to fetch sub-communities listing" error occasionally.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4361]
Description:

Getting "Failed to fetch sub-communities listing" error occasionally in the following pages.
1. Challenge listing page
2. Challenge detail page and
3.On clicking the My Communities tab of Dashboard page.

Screenshot:
![image (3)](https://user-images.githubusercontent.com/55895538/81685465-06002e80-9493-11ea-996b-8cced5883ecb.png)

**Comment by SathyaJayabal** [comment]
@dushyantb groups api seems to down many times and we get this error, Is this  a front-end or api issue?
cc @lakshmiathreya @sushilshinde

**Comment by lakshmiathreya** [comment]
cc @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya and @SathyaJayabal, FYI, this "My communities" section of the dashboard will NOT be in the new version of the dashboard. If this is an issue on the challenge listings page, then we should resolve. But if this is just occurring on the current dashboard, we will not resolve as work on new dashboard will begin in few weeks.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh this issue happens on the challenge listings and details page too.

**Comment by dushyantb** [comment]
I'm not having any idea about this, also from the screenshot it is not clear whether that is `groups-api` which is causing the problem or not

**Comment by Oanh-and-only-Oanh** [comment]
please hold work on this until end of June.

**Comment by Oanh-and-only-Oanh** [comment]
@sandhiyakavi @SathyaJayabal , can you close this if it's been resolved?
