### ISSUE TITLE
[$55] Account Settings: Error message is displayed while trying to change the Email address first time

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4365]
Description:
Error message "ERROR: Failed to update user profile!" is displayed while trying to change the Email address first time but the error message is not shown after refreshing the page.

Steps to Reproduce:

1. Clear all the Cache in the browser.
2. Login to Topcoder.
3. Go to "https://www.topcoder.com/settings/account"
4. Click Change Email button.
5. Enter a new valid Email.
6. Click Send Verification Email button.

Screenshot:
<img width="960" alt="Accountsettings_error" src="https://user-images.githubusercontent.com/55895538/81899028-dc5f1880-95f4-11ea-9486-5e2be0317b5a.png">

**Comment by SathyaJayabal** [comment]
tracking in #5106
