### ISSUE TITLE
Challenge Listing: Clear Filters Button not deleting localStorage.

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/community-app#4368]
**Description**
In Challenge Listing Page "Clear filters" button clears filters in front-end, but does not clear from localStorage. 

**To Reproduce**
1. Go to '/challenges'
2. Open pane by clicking 'Filters' button
3. change start and end date/
4. Clear filter by clicking "Clear Filters" button.
4. Refresh the page. Filter preserved.

**Expected behavior**
After page refresh filters should be gone.

**Screencast**
https://monosnap.com/direct/X9V1CmWKZ7k6a0M0MHevvhhA0ESIJN

**Desktop (please complete the following infrormation):**
 - OS: Ubuntu
 - Browser: Chrome latest

**Additional context**
- When i see codebase, "Clear Filters" button calls "setFilter" action from "actions/challenge-listing". But "setFilter" action is not there, but test code exists. Maybe code is deleted somehow.

**Comment by SathyaJayabal** [comment]
This issue is fixed in #4686
