### ISSUE TITLE
Not able to select date from date-selector in profile#work while editing Organisation end and start date

### ISSUE THREAD

**Issue by PSWanjari** [topcoder-platform/community-app#4370]
**Describe the bug**
When you navigate to Profile->Work page, and try to add a company. In this process of adding a organisation when you try to add "Company End " and "Company start" Date , you are unable to do so as some of the dates hide behind the footer of the page.

**To Reproduce**
1. Go to Profile->Work page
2. Click on "Add Work experience"
3.Select "End date" and try to insert a date.
4. See error -> all dates are not visible some of them hide behind the Footer.

**Expected behavior**
The End and Start date should be display properly and should be accessible easily. 

**Screenshots**
Screenshots attached

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 NA
**Additional context**
NA
![bug](https://user-images.githubusercontent.com/26870752/82071947-6e9a1600-96f4-11ea-8e75-65c9eba0cc88.JPG)

**Comment by SathyaJayabal** [comment]
tracked here
https://github.com/topcoder-platform/community-app/issues/4294
