### ISSUE TITLE
Unable to delete submissions 

### ISSUE THREAD

**Issue by 0xf17** [topcoder-platform/community-app#4371]
**Describe the bug**
Submissions are not getting deleted after delete request.

**To Reproduce**
1. Go to any challenge page (that you are already registered and made a submission for)
2. Click on View Submissions
3. Select a submission that you wish to delete
4. Confirm delete

**Expected behavior**
Submission should get deleted and disappear from the my submission list

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4 (19E287)
 - Browser: FireFox 76.0.1 (64-bit)

**Additional context**
I suspect that this is the case with this feature being broken as it has happened to me in multiple challenges.

**Comment by Oanh-and-only-Oanh** [comment]
Thanks for reporting. Correct, this is a known feature that's not working. We have this on our roadmap.
