### ISSUE TITLE
Hackerone issue

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4373]
Remove this newsletter subscription feature. 
![image](https://user-images.githubusercontent.com/47536078/82254652-15a2cb80-9908-11ea-9c6d-2c001282b467.png)

**Comment by jswheeler** [comment]
https://topcoder.atlassian.net/browse/VULN-1809

**Comment by Oanh-and-only-Oanh** [comment]
resolved and closed along with https://github.com/topcoder-platform/community-app/issues/4683
