### ISSUE TITLE
Add Events Calendar to Footer

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4374]
We need to add the Events Calendar to the footer.

- "Events Calendar"
- Place under "Community"
- Link to: topcoder.com/community/events
- Make sure this column is alphabetized

**Comment by SathyaJayabal** [comment]
verified on beta (develop)
<img width="1440" alt="Screenshot 2020-07-08 at 11 12 04 AM" src="https://user-images.githubusercontent.com/58783823/86881408-e8a2b600-c10b-11ea-911b-d87c2bca085b.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-08 at 3 04 47 PM" src="https://user-images.githubusercontent.com/58783823/86903029-64acf600-c12c-11ea-9fcf-2649cb42d7a0.png">
