### ISSUE TITLE
Challenge phases in v3 api

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#439]
Registration phase object does not has the same format as objects for other phases. It does not create big problems at the moment, and can be leveraged on community-app side; but it would be better just to fix it in the api, to have it self-consistent.
![screenshot](https://user-images.githubusercontent.com/20144632/30165133-408ce488-93df-11e7-97f1-0dabf00649fe.png)

**Comment by ajefts** [comment]
@skyhit Can you please take a look at this one?  Any reason we shouldn't be consistent?

**Comment by birdofpreyru** [comment]
My bad: this is not a result of API response, this is an extra registration phase object injected at the frontend side to render cards with deadline details on challenge details page.
