### ISSUE TITLE
Challenge Listings: V5 Challenge api call failing for logged in users

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4392]
Challenge Listings: V5 Challenge api call failing for logged in users

https://test-community-app.topcoder-dev.com/challenges
https://test-community-app.topcoder-dev.com/__community__/blockchain/challenges?communityId=blockchain

<img width="1440" alt="Screenshot 2020-05-22 at 3 11 37 PM" src="https://user-images.githubusercontent.com/58783823/82654644-ae09ba80-9c3e-11ea-9f2f-4b8d72b51f06.png">

**Comment by sushilshinde** [comment]
This is API issues 

https://github.com/topcoder-platform/challenge-api/issues/130

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya @SathyaJayabal, this ticket has been marked with QA Pass. Does that mean the API issue has been resolved?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this issue has been solved.

**Comment by SathyaJayabal** [comment]
Reverified on beta and test after data model update
(https://topcoder.slack.com/archives/G012CL5GF71/p1591254930370200)
