### ISSUE TITLE
Phase times sync between api v3 and OR / Direct

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#440]
It looks to me that when I extend a review phase in OR, the updated end date/time does not make it to the responses of API v3. I would guess, it also should be true for other staff we can update in OR.

**Comment by ajefts** [comment]
@birdofpreyru are you noticing this just in dev?  Or prod too?

**Comment by birdofpreyru** [comment]
@ajefts In prod. Just yesterday I've extended review phase of this challenge: https://www.topcoder.com/challenge-details/30058889/?type=develop
and it was not reflected in the challenge listing, where it says the time till the end of current phase.

**Comment by birdofpreyru** [comment]
I've checked API response now, and now it contains the correct phase end date already, but it was not the case for the first time after the update.
