### ISSUE TITLE
Submission Pages

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#441]
Higher priority: for submission to development challenges we redirect competitors to the legacy submission page. I believe, we need a better design for it, and then we should assemble it inside community app.
![screenshot](https://user-images.githubusercontent.com/20144632/30169914-f3981102-93ed-11e7-8744-16c2da0b4692.png)

Lower priority: for submissions to design challenges we redirect to current design submission page. It does not look that bad, but it leaves in the legacy codebase (topcoder-app). We surely want to port it to community app at some point, thus if you have in mind to update its design functionality, it might be better to prepare the new design first, and then implement it here right away.

**Comment by birdofpreyru** [comment]
@ajefts Are there design challenges in TopGear community? The point about porting submission pages is mostly related to communities (so that we don't redirect for submission outside of community sub-domain). If they don't have design challenges there, then we can relax about design submissions page for now, and just make the development one, which surely is more simple.

**Comment by birdofpreyru** [comment]
Or do we just use Submission Management Page for submissions in dev?

**Comment by Dara-K** [comment]
Basic question: what is TopGear community?

The Submission Management Page was done for Design and Development challenges.

**Comment by birdofpreyru** [comment]
TopGear is one of communities (if you are curious, you may check `Separate Topcoder Communities` section at http://community-west.topcoder-dev.com/, using `dan_developer` / `dantopcoder123` as credentials, where you need to be logged-in), being used by Wipro internally. Contains information and challenges for their employees. The point is that although these communtiies re-use the same code, in prod they are accessible via dedicated domains, like `topgear.topcoder.com`, and we want that when vistitors hang around that communties, they are not redirected to legacy pieces of the platform by links they can find.

I've mentioned SMP by mistake. It has `Add Submission` button, but I forgot that that button just redirects to Submission Page. Thus, what do we do with submission pages?

**Comment by ajefts** [comment]
@birdofpreyru topgear does have some design challenges running. It's a minority right now, but they are being used.  

I do think we need to post the submission pages out of topcoder-app and into community app.  If you want to start on that, it would probably be something good for @sushilshinde to work on with you.

**Comment by ajefts** [comment]
Regarding the submission pages between design and dev (and marathon matches for that matter), we want to move towards a single experience that makes submitting more consistent across the challenge types. I think we do need some design work for this (and backend updates), but maybe we can start simple and just get the design submission page upgraded to also support dev submissions?

**Comment by birdofpreyru** [comment]
@ajefts Cool! Let's move it on. My idea is:

1. Waiting for designs from @Dara-K . For now, we can keep using the same APIs as now, but surely restyle the dev submission page to look similar to design one. Then depending on the designs, we'll try to re-use as much staff for these pages as possible.

2. We ran a code challenge to implement these pages in Community App.

3. Any necessary clean-up of the results from (2).

What should be @sushilshinde's role here? Do you want him to act as copilot for (2)?

**Comment by birdofpreyru** [comment]
Yeah, for MMs we should call Tim, I believe, or somebody else who does them, so that he can collaborate with Dara on how it should look / work, and then we can implement it as soon as ready, without blocking dev / design cases, which are a way more clear to me.

**Comment by ajefts** [comment]
welcome to the party @sushilshinde !

**Comment by Dara-K** [comment]
@birdofpreyru I sent already sent the developers designs pages with mobile, tablet and desktop version and interactive specifications.
[Submissions Management - Design and Specs.zip](https://github.com/topcoder-platform/community-app/files/1288705/Submissions.Management.-.Design.and.Specs.zip)

**Comment by birdofpreyru** [comment]
@Dara-K Yeap, and I already got an F2F running to implement those for Submission Management Page.

But, those designs don't include the pages we are talking about here. Like the ones where you really specifies the files to upload (and select all fonts / stock images source, etc. in case of design challenges), and push the `upload` button. The linked designs only relate to the page where you can see your previous submissions, the feedback for them, and download / remove them.

**Comment by Dara-K** [comment]
Here are the designs for Design & Develop Submit page, desktop, tablet and mobile. 

Let me know if I should send you anything else on this.

[File Submit.zip](https://github.com/topcoder-platform/community-app/files/1301277/File.Submit.zip)

**Comment by sushilshinde** [comment]
I'm testing submission deliverable against spec by @Dara-K

**Comment by birdofpreyru** [comment]
Implemented. Any further fixes / improvements are tracked via different issue tickets.
