### ISSUE TITLE
Contentful pages: Challenge url format must be in new format

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4434]
There are many contentful pages where there are links to challenge details. These challenge URLs are in V4 format. It should be in the new format

Expected URL format:  https://test-community-app.topcoder-dev.com/challenges/50a59121-0100-42fb-a7b5-329b3702bf00
Actual URL format: https://test-community-app.topcoder-dev.com/challenges/30120975

Example Pages:
https://test-community-app.topcoder-dev.com/community/stayhome (challenges section)
https://test-community-app.topcoder.com/__community__/comcast/explore (Paid Work section)

Maybe @kkartunov can help with identifying these pages.

**Comment by sushilshinde** [comment]
@kkartunov how are you adding these challenges?

**Comment by sushilshinde** [comment]
@SathyaJayabal this link is not working 
https://test-community-app.topcoder.com/__community__/comcast/explore

**Comment by SathyaJayabal** [comment]
@sushilshinde 
https://test-community-app.topcoder-dev.com/__community__/comcast/explore

please add dan_developer to comcast community/group

**Comment by kkartunov** [comment]
@SathyaJayabal this will be handled by https://github.com/topcoder-platform/community-app/issues/4435

**Comment by SathyaJayabal** [comment]
@sushilshinde @kkartunov , we will close this with #4435

**Comment by SathyaJayabal** [comment]
@sushilshinde , these challenges not yet migrated on prod
https://github.com/topcoder-platform/challenge-api/issues/149

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-06-10 at 9 14 21 AM" src="https://user-images.githubusercontent.com/58783823/84224699-d2004380-aafa-11ea-915e-43cf6634e19a.png">

**Comment by SathyaJayabal** [comment]
@sushilshinde , we can close this. tcx_accepted label needed.
