### ISSUE TITLE
Challenge Details: Contest Deadlines date/times are incorrect

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4447]
Contest deadline dates and times do not match with V4 dates and times. The checkpoint review deadline is  also missing for design challenges.
user: not logged in
V4 URL:https://www.topcoder.com/challenges/30126014
V5 URL:https://beta-community-app.topcoder.com/challenges/fbd47239-43dc-4f50-8d0d-739dfe82191a
<img width="1440" alt="Screenshot 2020-06-01 at 10 29 29 AM" src="https://user-images.githubusercontent.com/58783823/83377417-1ac94580-a3f3-11ea-9e80-5bb818972a32.png">

**Comment by sushilshinde** [comment]
@SathyaJayabal did you debug API response?

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal did you debug API response?

No

**Comment by SathyaJayabal** [comment]
https://api.topcoder.com/v5/challenges/fbd47239-43dc-4f50-8d0d-739dfe82191a
https://api.topcoder.com/v4/challenges/30126014

Phases details are not matching between V4 and V5

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/challenge-api/issues/146

**Comment by SathyaJayabal** [comment]
@sushilshinde @rootelement phases matching in dev env after migration of data
<img width="1440" alt="Screenshot 2020-06-02 at 3 49 45 PM" src="https://user-images.githubusercontent.com/58783823/83517344-5f89d500-a4f6-11ea-8165-0fca83b8c13e.png">

**Comment by SathyaJayabal** [comment]
Reverified on beta and test after data model update
(https://topcoder.slack.com/archives/G012CL5GF71/p1591254930370200)
<img width="1440" alt="Screenshot 2020-06-05 at 12 04 24 PM" src="https://user-images.githubusercontent.com/58783823/83845053-c6410580-a725-11ea-9da3-ad3754553519.png">
<img width="1440" alt="Screenshot 2020-06-05 at 12 08 40 PM" src="https://user-images.githubusercontent.com/58783823/83845064-cb9e5000-a725-11ea-8af2-1cb3d4cba704.png">
