### ISSUE TITLE
Challenge details: TCO20 tag is missing

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4449]
TCO20 tag is missing
user: not logged in
V4 URL:https://www.topcoder.com/challenges/30126014
V5 URL:https://beta-community-app.topcoder.com/challenges/fbd47239-43dc-4f50-8d0d-739dfe82191a

<img width="1440" alt="Screenshot 2020-06-01 at 10 37 12 AM" src="https://user-images.githubusercontent.com/58783823/83377688-06d21380-a3f4-11ea-8b89-a6e217e6eed5.png">

**Comment by sushilshinde** [comment]
I compared API, it doesn't return the tag

**Comment by sushilshinde** [comment]
https://api.topcoder.com/v5/challenges/fbd47239-43dc-4f50-8d0d-739dfe82191a

vs 

https://api.topcoder.com/v4/challenges/30126014

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/challenge-api/issues/144
