### ISSUE TITLE
Next Deadline msg on Challenge Details page for past challenges

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#445]
It has been fixed during Bug Bash, but it look like we missed some corner-cases (most probably, it is relevant to past F2F only, where data from API are a bit surprizing).

![screenshot](https://user-images.githubusercontent.com/20144632/30190620-a59bdb5c-943b-11e7-8ec2-1ffd288810f3.png)

**Comment by birdofpreyru** [comment]
### Expected Fix:
It seems that this status msg still can be wrong in some corner cases. You should check all types of challenges in different tracks and states that you can find in dev and prod environment, and fix all discrepancies you can find.

For stalled challenges (in case they really don't have a winner) we should write there `The challenge is stalled`. If the current phase is late, and was not closed, we should properly report it as well, saying it is late (similar to how it is done in the challenge listing), etc.

**Comment by nahidshahin** [comment]
Hi, can you please assign this ticket to me? I don't have the permission. Thanks

**Comment by ThomasKranitsas** [comment]
@nahidshahin this ticket is not part of my bug bash.
