### ISSUE TITLE
Sign Up button on website results in 404

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#4455]
**Describe the bug**
The signup button on the header of the website takes the user to a page which shows 404

**To Reproduce**
1. open browser incognito mode
2. go to topcoder.com
3. select "Sign Up" button in header (upper right-hand corner)
![image](https://user-images.githubusercontent.com/45197181/83444173-9d401c80-a468-11ea-94ef-a2fb2c7b720c.png)
4. The redirection is at https://www.topcoder.com/user-selection/ which shows 404 

![image](https://user-images.githubusercontent.com/45197181/83444221-b34ddd00-a468-11ea-9cca-209c6907c4f6.png)

**Expected behavior**
The button click should take the user to the sign-up form

**Comment by m-yadav** [comment]
cc @Oanh-and-only-Oanh

**Comment by Oanh-and-only-Oanh** [comment]
thanks. will get this resolved ASAP.

**Comment by Oanh-and-only-Oanh** [comment]
fixed
