### ISSUE TITLE
Challenge details header for challenges with no prizes

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#446]
For fun challenges with no prizes nothing is rendered in the prizes section. That much empty space is not fun. If I just put there a text note, that this challenge has no prizes, there still gonna be a lot of empty space (and if I just make the font of that note large, it probably will look ugly).

![screenshot](https://user-images.githubusercontent.com/20144632/30190680-11fb0ac0-943c-11e7-9a70-1bc3fc0514a1.png)

**Comment by Dara-K** [comment]
Maybe we can show we have 5 t-shirts prize or other type? but also specify prizes 1->3:  $0 so all members know there are no cash involved

**Comment by birdofpreyru** [comment]
I am not sure that all fun challenges offer t-shirts as prizes. Showing 3 $0 prizes also seems a bit redundant for me. But, no problem, if you don't have any specific idea about it, I'll try to experiment myself. Most probably just put a message like `This challenge is for fun. No regular prizes offered here, just priceless experience.` :)

**Comment by Dara-K** [comment]
Can't this be customized? Like say for some challenge there is no prize as your example phrase, but show the prizes and t-shirts for others. There is a lot of space now on prizes area.

**Comment by birdofpreyru** [comment]
We just don't have a way to set such preferences in APIs (Direct, OR), so for now we can just do the same for all challenges that has no prizes specified by API.

**Comment by Dara-K** [comment]
I guess simple text will have to do it then for fun challenges.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/11/2017 and back
