### ISSUE TITLE
TCO21 site

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4467]
Create TCO21 site.

**Comment by SathyaJayabal** [comment]
@kkartunov, @sushilshinde. except for the below issue, other pages look good.
(Content not in scope)
The regional pages are missing the footer
<img width="1440" alt="Screenshot 2020-06-22 at 1 04 27 PM" src="https://user-images.githubusercontent.com/58783823/85260876-01169d80-b489-11ea-9dd0-cef6a842e54f.png">
<img width="1440" alt="Screenshot 2020-06-22 at 1 04 55 PM" src="https://user-images.githubusercontent.com/58783823/85260936-1986b800-b489-11ea-9d32-ea3a009cf67b.png">

**Comment by SathyaJayabal** [comment]
@kkartunov , user dropdown menu is hidden in some pages
example:
https://community-app.topcoder-dev.com/__community__/tco21/competition-overview/algorithm
https://community-app.topcoder-dev.com/__community__/tco21/competition-overview/qa
<img width="1440" alt="Screenshot 2020-06-22 at 1 30 46 PM" src="https://user-images.githubusercontent.com/58783823/85263369-b26b0280-b48c-11ea-8749-7dc51fae6d39.png">

**Comment by SathyaJayabal** [comment]
The user menu issues is fixed
<img width="1440" alt="Screenshot 2020-06-22 at 2 33 32 PM" src="https://user-images.githubusercontent.com/58783823/85269349-5fe21400-b495-11ea-8a91-9459f467055d.png">

**Comment by SathyaJayabal** [comment]
@kkartunov, User menu issue in the below pages
https://community-app.topcoder.com/__community__/tco21/sponsors
<img width="1440" alt="Screenshot 2020-06-23 at 10 35 37 AM" src="https://user-images.githubusercontent.com/58783823/85362918-4f857400-b53d-11ea-85f3-b1eb6b160d32.png">

**Comment by kkartunov** [comment]
@SathyaJayabal thanks. This issue is now fixed.

Please, keep this ticket open until 1 July, the actual TCO21 release.

**Comment by kkartunov** [comment]
@SathyaJayabal we can close this one now.
