### ISSUE TITLE
Footer - Add "Challenge Pipeline" Under Community

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4468]
It should link to http://www.topcoder.com/community/pipeline

**Comment by SathyaJayabal** [comment]
verified on dev (feature branch)
<img width="1440" alt="Screenshot 2020-07-09 at 2 54 58 PM" src="https://user-images.githubusercontent.com/58783823/87022535-3d216080-c1f4-11ea-94e5-d31a8f037064.png">

**Comment by SathyaJayabal** [comment]
verified in beta(develop branch)

<img width="1440" alt="Screenshot 2020-07-13 at 3 49 27 PM" src="https://user-images.githubusercontent.com/58783823/87295326-a53cb300-c522-11ea-9aaf-1cf3081c28ae.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-13 at 6 13 25 PM" src="https://user-images.githubusercontent.com/58783823/87305731-96f79280-c534-11ea-82c2-15ea219ae202.png">
