### ISSUE TITLE
Challenge listings page: Api error

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4475]
https://test-community-app.topcoder-dev.com/challenges?
V5 Challenge api returns "memberId\" is not allowed" error in dev.
user:jcori/appirio123

https://api.topcoder-dev.com/v5/challenges?status=Active&memberId=40029484
No error in prod  env
https://api.topcoder.com/v5/challenges?status=Active&memberId=22778049

<img width="1440" alt="Screenshot 2020-06-05 at 12 43 01 PM" src="https://user-images.githubusercontent.com/58783823/83847768-70229100-a72a-11ea-80cb-22c32a306a44.png">
<img width="1440" alt="Screenshot 2020-06-05 at 12 43 11 PM" src="https://user-images.githubusercontent.com/58783823/83847788-787acc00-a72a-11ea-8959-9efef08fed5c.png">

**Comment by sushilshinde** [comment]
@rootelement please help

**Comment by rootelement** [comment]
Working on this. This will have to change to calling the resources api to get challenge ids, then call the GET /v5/challenges with a search body of `{ids: [uuid, uuid, uuid]}`

**Comment by sushilshinde** [comment]
Thanks @rootelement please tag once this is resolved.

**Comment by rootelement** [comment]
This works in dev:
```
curl --location --request GET 'https://api.topcoder-dev.com/v5/challenges' \
--header 'Content-Type: application/json' \
--data-raw '{ "ids": ["1958ee63-61b7-439e-8527-d9b502366eb2", "b63979ab-cca0-433d-9387-3ef3b333ee3b"]}'
```
