### ISSUE TITLE
[$50] - Check the difference between react-dropdown and react-select. Do we really need both?

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#448]

**Comment by sushilshinde** [comment]
@birdofpreyru I did check their specs.

React-dropdown is a basic component, limited configuration options and is just a subset of react-select. 
And react-select has large set up of configuration options. I think react-select will covers rich set of use cases.

**Comment by birdofpreyru** [comment]
@sushilshinde Then, I would say, we should drop out `react-dropdown` and use `react-select` everywhere. Sure we should take some care not to change any functionality / look of any elements using `react-dropdown`.

**Comment by sushilshinde** [comment]
@birdofpreyru I'll fix it later this week.

`react-dropdown` is used at two places, `react-select` is used at one place

**Comment by birdofpreyru** [comment]
### Expected Fix:
- Any use of `react-dropdown` should be replaced by `react-select`;
- `react-dropdown` dependency should be dropped;
- `react-select` should be updated to the latest version of the package;
- Double-check that this does not affect any logic / styling.

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/614
hash: 28f9577
