### ISSUE TITLE
Challenge Details: Fails to load

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/community-app#4493]
After the latest deployment today - Challenge details fail to load:
<img width="1665" alt="Screenshot 2020-06-08 at 7 34 46 PM" src="https://user-images.githubusercontent.com/51733042/84039754-59e13300-a9bf-11ea-8e15-bc3320252819.png">

**Comment by lakshmiathreya** [comment]
cc @SathyaJayabal

**Comment by lakshmiathreya** [comment]
v4 Challenge Details as reference for the same challenge:
<img width="1622" alt="Screenshot 2020-06-08 at 7 41 47 PM" src="https://user-images.githubusercontent.com/51733042/84040622-76ca3600-a9c0-11ea-8abf-60cc765f8f6e.png">

**Comment by rootelement** [comment]
I just tried clicking a listing, got to the details page and got the not found error, but if I try the API with that same ID, it works fine:
works: http://api.topcoder-dev.com/v5/challenges/d741f46c-fb1b-4ead-8112-4c2a674b3c7f
doesn't work: https://test-community-app.topcoder-dev.com/challenges/d741f46c-fb1b-4ead-8112-4c2a674b3c7f

This has to be a frontend issue.

**Comment by SathyaJayabal** [comment]
@sushilshinde @luizrrodrigues

**Comment by sushilshinde** [comment]
working now

**Comment by SathyaJayabal** [comment]
not yet working on beta 
https://beta-community-app.topcoder.com/challenges/de5379a2-5c3c-46bc-879b-029a813f47a7
<img width="1440" alt="Screenshot 2020-06-09 at 10 39 13 AM" src="https://user-images.githubusercontent.com/58783823/84108344-9bb0be80-aa3d-11ea-9be1-c2faf399bcc4.png">
Also not working on test for  design   challenges
https://test-community-app.topcoder-dev.com/challenges/5d4e5332-9012-44ca-a364-f477d2a0ea5c
<img width="1440" alt="Screenshot 2020-06-09 at 10 41 51 AM" src="https://user-images.githubusercontent.com/58783823/84108462-ddda0000-aa3d-11ea-9ca1-a7be329ebc41.png">

**Comment by SathyaJayabal** [comment]
working now
<img width="1440" alt="Screenshot 2020-06-09 at 6 28 38 PM" src="https://user-images.githubusercontent.com/58783823/84150151-177f2b00-aa7f-11ea-9eb8-482aa430d0ea.png">

<img width="1440" alt="Screenshot 2020-06-09 at 6 28 36 PM" src="https://user-images.githubusercontent.com/58783823/84150138-10581d00-aa7f-11ea-905c-7b11f57853f5.png">
