### ISSUE TITLE
Add place for special badges on dashboard

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#450]
We have an upcoming SRM event(s) that will yield some special badges that we want to put on the member's dashboard if they have the badge.  Let's modify the top of the page a bit to accommodate it. 

![pasted image at 2017_07_27 08_32 am 1](https://user-images.githubusercontent.com/3812270/30292047-a4ecee5c-9702-11e7-9ea0-c7542c201892.png)

**Comment by ajefts** [comment]
@birdofpreyru We probably need to do this in both topcoder-app and community-app so we're ready with it in either case.

**Comment by birdofpreyru** [comment]
@ajefts This is not how the dashboard looks now. In the current version, in the row under header menu, we have avatar / handle / earnings on left; and `DASHBOARD` label on right. Though, there is many space between them, where we can add the badge.

How do we get it? Will be exposed as some of the fields in profile object?
When exactly do we need it ready?

**Comment by ajefts** [comment]
Can we update the top part to look like the design?

For getting the data, I'm thinking of a couple options.  Can you mock it for a couple users for now?

**Comment by birdofpreyru** [comment]
Ok, running as an F2F for `topcoder-app` case: https://www.topcoder.com/challenge-details/30059314/?type=develop&noncache=true

**Comment by ajefts** [comment]
@sushilshinde I'd like you to follow this one and when @birdofpreyru has the submission tested locally, you can manage the PR for it and make sure it's verified in dev...and then we'll push to prod...

**Comment by birdofpreyru** [comment]
@sushilshinde Ok, as @ajefts wants you to take care about this issue from this point, here is the winning submission, commited as a separate branch to topcoder-app: https://github.com/appirio-tech/topcoder-app/commits/f2f-dashboard-ronakkaria-3

I have no idea, though, what badge Tony wants to display in Dashboard :) What that update does is (1) it restyles header part of dashboard, (2) it allows to specify that some of the badges from user profile, if user has them, should be also rendered in the dashboard. So, we still should add the to the app the badge Tony wants to add, and configure it to show in dashboard

**Comment by birdofpreyru** [comment]
@sushilshinde I got an email from the winner of this F2F, pointing out that both him and me, we have overlooked that dashboard header directive, that he has modified, is also used in other dashboard / profile pages, probably somewhere else. So, you shoud check whether the update works fine there, or we need some further modifications for that.

**Comment by sushilshinde** [comment]
Started looking into this.

**Comment by sushilshinde** [comment]
Question @birdofpreyru @ajefts 

Are we pushing this to dev/prod before the badge logic integration?

**Comment by ajefts** [comment]
@sushilshinde How is the logic setup/mocked to show the badge right now?

**Comment by ajefts** [comment]
fyi, I setup some data in dev.  I'll chat on slack for how to test...

**Comment by sushilshinde** [comment]
@ajefts There is a logic to show a badge with the mock data. I was able to render badge.

![topcoder-badges](https://user-images.githubusercontent.com/683231/30685353-40ca4fb4-9ed2-11e7-9504-8ad4ee531d1c.png)

**Comment by birdofpreyru** [comment]
@sushilshinde @ajefts 
Yeah, right, to render a badge on Dashboard we just need: (1) to add the badge image for Dashboard into `topcoder-app` repo; (2) to add this badge ID into the response of the same API that returns badges for profile pages.

> Currently, mock data code ({<user_handle>:<badge_name>}) suggest for another API call for dashboard badge names, my guess is it doesn't exist right now.

We just slightly modify that code there. Now that mock allows to inject specified badge for specified users only, for testing. We simply update it to work for arbitrary users. I.e. we'll hard-code a set of badge IDs (just one for now), that should be rendered in the Dashboard, if present in API response for any user; we filter achievements against that set, and if something matches we render

**Comment by sushilshinde** [comment]
![slash](https://user-images.githubusercontent.com/683231/30743805-d7408036-9fbc-11e7-8827-69f8d68a0e32.png)

Got original specs from vic-tor, it doesn't have a slash as @ajefts posted in the post. Will remove it in the further development.

**Comment by sushilshinde** [comment]
Up and running on production

**Comment by sushilshinde** [comment]
Reopening for community app upgrade of this feature

**Comment by birdofpreyru** [comment]
I think we'll do a full code challenge, to make this, and also to port to Community App the new news/banners block

**Comment by sushilshinde** [comment]
Sure.

**Comment by sushilshinde** [comment]
@birdofpreyru I'm working on this change as per my discussion with @ajefts, we don't need to launch a challenge for this.
