### ISSUE TITLE
Profile settings - skills update

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4500]
1) a member should be able to add [newly added](https://docs.google.com/spreadsheets/d/1JRuRpP6K7vqi0s9bCDiGIlBnhhD37gxvKQWixgxrRJU/edit#gid=0) skills to their profiles
2) these skills should be able to be "verified" if member wins a challenge tagged with this new skill

BUG:
Member has participated in two challenges with react.js tags in it. (also other tags like scss, html5) but does not have it verified yet.
Topcoder handle: nursoltan-s
member profile: https://www.topcoder.com/members/nursoltan-s
challenge  won #1: https://www.topcoder.com/challenges/30122528?tab=winners
challenge  won #2: https://www.topcoder.com/challenges/30119357?tab=winners

**Comment by nursoltan-s** [comment]
Same Issue: https://github.com/topcoder-platform/community-app/issues/4316

**Comment by SathyaJayabal** [comment]
closing this as we are tracking it in #4316
