### ISSUE TITLE
Develop Policy Pages - Contentful based

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4502]
Desktop: https://marvelapp.com/22595fi6/screen/67508151
Mobile: https://marvelapp.com/e21fai1/screen/67567449

Links should be:
- BUSSINESS -> https://www.topcoder.com/
- COMMUNITY -> https://www.topcoder.com/community/learn

Should reuse standard TC footer.

Desired URL address of the pages is http://topcoder.com/policy/[XYZ]. Link to policy from TC footer - "Policies"

Testing URL: https://community-app.topcoder-dev.com/policy
No content testing needed. It will be handled by the team.

**Comment by SathyaJayabal** [comment]
@kkartunov, what do you mean  by
```
Links should be:
BUSSINESS -> https://www.topcoder.com/
COMMUNITY -> https://www.topcoder.com/community/learn
Should reuse standard TC footer.
```

**Comment by kkartunov** [comment]
@SathyaJayabal I mean links in navi 
![Screenshot 2020-07-16 12:12:28](https://user-images.githubusercontent.com/5585002/87653074-b02f5780-c75d-11ea-8403-be6f937948e8.png)
and footer at page bottom.

**Comment by SathyaJayabal** [comment]
Thanks @kkartunov , one more question?
Will this format not work https://www.topcoder-dev.com/policy?

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-07-16 at 3 50 50 PM" src="https://user-images.githubusercontent.com/58783823/87662071-4de74e80-c77f-11ea-9dc3-81420d51e548.png">
<img width="498" alt="Screenshot 2020-07-16 at 3 51 08 PM" src="https://user-images.githubusercontent.com/58783823/87662092-550e5c80-c77f-11ea-944d-7e116173544e.png">
<img width="1440" alt="Screenshot 2020-07-16 at 4 13 17 PM" src="https://user-images.githubusercontent.com/58783823/87662110-5b043d80-c77f-11ea-832e-f928576b51a1.png">

**Comment by kkartunov** [comment]
Thank You @SathyaJayabal!

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="603" alt="Screenshot 2020-07-20 at 2 18 54 PM" src="https://user-images.githubusercontent.com/58783823/87918455-184ea800-ca94-11ea-9a4b-a775ec6dbaaa.png">
<img width="1440" alt="Screenshot 2020-07-20 at 2 19 08 PM" src="https://user-images.githubusercontent.com/58783823/87918473-1d135c00-ca94-11ea-9f50-49ec0a4e79cd.png">

**Comment by SathyaJayabal** [comment]
Verified on prod
<img width="1440" alt="Screenshot 2020-07-21 at 9 13 36 AM" src="https://user-images.githubusercontent.com/58783823/88010532-b729e180-cb32-11ea-9899-df9c67dc8f97.png">
<img width="525" alt="Screenshot 2020-07-21 at 9 13 46 AM" src="https://user-images.githubusercontent.com/58783823/88010553-c4df6700-cb32-11ea-8d74-4afb236feb83.png">

**Comment by SathyaJayabal** [comment]
reopening as this was reverted

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-07-22 at 3 54 54 PM" src="https://user-images.githubusercontent.com/58783823/88165685-b4fb7c00-cc33-11ea-89b2-da29525ed9bc.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-22 at 3 54 54 PM" src="https://user-images.githubusercontent.com/58783823/88179350-6527af80-cc49-11ea-9348-880b0fc67d89.png">
