### ISSUE TITLE
Add support for switching tabs via URL query parameters

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4503]
For example https://www.topcoder.com/community/statistics

One should be able to link to a particular tab page/state.

Testing: This can be tested on dev here https://www.topcoder-dev.com/community/statistics but note that on dev stats do not work and will display an error "lookerApi: Not Found" which is not an issue. Dev can be used to test this.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-07-27 at 12 28 16 PM" src="https://user-images.githubusercontent.com/58783823/88512938-f9589480-d004-11ea-9fec-0e8179b63467.png">

**Comment by SathyaJayabal** [comment]
@kkartunov , Don't see these updates on beta
<img width="1440" alt="Screenshot 2020-08-03 at 3 29 19 PM" src="https://user-images.githubusercontent.com/58783823/89170997-21fd0300-d59e-11ea-92c7-c8b79835beb6.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-08-03 at 4 34 33 PM" src="https://user-images.githubusercontent.com/58783823/89176537-5aeda580-d5a7-11ea-9767-98c05fb8a886.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-04 at 3 29 22 PM" src="https://user-images.githubusercontent.com/58783823/89281178-4f61b380-d667-11ea-84f3-a17ae42c89be.png">
