### ISSUE TITLE
Setup community for blockchain

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#451]
Please setup a new community at blockchain.topcoder.com

Site Security:  public site with option to join.
Challenge Security: Filtered by group
Group ID: 20000010
Challenge Listings Page:  Can we add something so if the user is not in the group yet, we present the option to join with a message saying "Join now to participate in exclusive blockchain challenges!"
Leaderboard: Add the page, but hide it from the menu for now.

For content, just copy the qa site.

**Comment by ajefts** [comment]
@birdofpreyru Any chance you could set this one up quick?

**Comment by birdofpreyru** [comment]
@ajefts Added and pushed to dev.

Missing the logic at challenge listing page (showing content only for members of community). Will do it later today.
