### ISSUE TITLE
Implement backward compatibility for legacy challenge urls(v4) - Sometimes redirection does not work

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4515]
https://github.com/topcoder-platform/community-app/issues/4435#issuecomment-641716574

example:https://test-community-app.topcoder-dev.com/challenges/30056660

**Comment by simranb86** [comment]
@SathyaJayabal @sushilshinde as per last comment, this seems now fixed - just tested on test env several times and it redirects fine https://test-community-app.topcoder-dev.com/challenges/30056660 .

**Comment by SathyaJayabal** [comment]
@sushilshinde , please hold off on opening this  for pickup until we can verify if this is already fixed in the latest deployment.

cc: @simranb86

**Comment by lakshmiathreya** [comment]
Seems intermittent - <img width="1630" alt="Screenshot 2020-06-11 at 4 55 11 PM" src="https://user-images.githubusercontent.com/51733042/84380266-b08b7e80-ac04-11ea-9fd8-7e6a8179efe6.png">

**Comment by SathyaJayabal** [comment]
@sushilshinde @simranb86 , we still face the issue. 
<img width="1440" alt="Screenshot 2020-06-11 at 4 57 14 PM" src="https://user-images.githubusercontent.com/58783823/84380308-c00ac780-ac04-11ea-9bc1-f429cc2e586a.png">

<img width="1440" alt="Screenshot 2020-06-11 at 4 54 33 PM" src="https://user-images.githubusercontent.com/58783823/84380280-b6815f80-ac04-11ea-8972-4a6c6a0073e9.png">

**Comment by simranb86** [comment]
@SathyaJayabal @sushilshinde here is root cause of the problem. So once we fix #4505 , this intermedittent will be fixed. If you want I can try to push a fix for #4505 today ? Feel free to assign that to me if other developer cannot fix it and then let's see how it fix goes about it. 

<img width="1406" alt="issue_ 4515" src="https://user-images.githubusercontent.com/40840038/84451592-2e856f00-ac71-11ea-8740-b1e6e6b405bd.png">

**Comment by sushilshinde** [comment]
@simranb86 do we need review types for no-auth calls?

**Comment by simranb86** [comment]
> @simranb86 do we need review types for no-auth calls?

@sushilshinde no review types is auth based call. I guess that is reason why we say animation forever in other ticket also - I have pushed one PR to make sure we check for auth before making call to challenge-api. 

That change should also fix #4505 

Let's revisit once that PR is merged.

**Comment by SathyaJayabal** [comment]
@sushilshinde, issue is not observed now. 
cc @lakshmiathreya
