### ISSUE TITLE
Using Helmet

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#452]
This is not a bug but a security practice for express node web apps
Ref : http://expressjs.com/en/advanced/best-practice-security.html#use-helmet

I can take this up, let me know what you think @ajefts @birdofpreyru

**Comment by birdofpreyru** [comment]
@sushilshinde This looks good to me. I mean, you can install it. We just have to double-check carefuly afterwards that setting these headers won't break any of our frontend segments, and if it does, then to correct them properly.
