### ISSUE TITLE
Snyk repo scan report

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#453]
I did snyk into community app, there are security issues. Please check attachment.

![snyk-report](https://user-images.githubusercontent.com/683231/30315812-c7c8735e-97c2-11e7-81df-1a30c9910a3a.png)

**Comment by birdofpreyru** [comment]
These are not direct dependencies. I agree, that it would be better to upgrade them in those TC apps that depend on them, but it can be quite tricky: in many places they are so outdated, that installing newer versions produces a loooot of obscure issues, that can take lots of efforts to fix.
@ajefts
