### ISSUE TITLE
colorStyle need calculated in Frontend

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#4530]
**Describe the bug**
Before **challenges-api** returning `colorStyle` from DB, this sets the color of the handle by rating. In V5 this need be done by FE following this: https://www.topcoder.com/community/competitive-programming/how-to-compete/ratings

**To Reproduce**
1. Go to challenge details
2. Click on Registrants or Submissions
3. See all handle have black color

**Expected behavior**
Handle need to show color follow the rank rating

**Screenshots**
![image](https://user-images.githubusercontent.com/7029641/84584710-fd767d00-addd-11ea-8c72-2f0fbcae5602.png)

**Comment by luizrrodrigues** [comment]
Fix need be applied here:
https://github.com/topcoder-platform/topcoder-react-lib/pull/195/files

**Comment by SathyaJayabal** [comment]
Colour mapping
https://github.com/topcoder-platform/community-app/issues/4289#issuecomment-619785058

**Comment by SathyaJayabal** [comment]
Colour mapping is being taken care of the respective issues #4546 and #4552. cc @luizrrodrigues @sushilshinde @lakshmiathreya
