### ISSUE TITLE
Challenge details page throwing an error

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4532]
Challenge details page throwing an error on Test Env for all challenges
example:
https://test-community-app.topcoder-dev.com/challenges/fc906e83-d2ee-4ec5-9edb-b4a7ecdf49c6
<img width="1440" alt="Screenshot 2020-06-13 at 10 45 46 AM" src="https://user-images.githubusercontent.com/58783823/84584819-9cbf6280-ae26-11ea-8c1b-a3e9fb7b375a.png">

**Comment by SathyaJayabal** [comment]
The details page works now
<img width="1440" alt="Screenshot 2020-06-13 at 10 45 46 AM" src="https://user-images.githubusercontent.com/58783823/84584831-c5dff300-ae26-11ea-94c8-227bb2265636.png">

**Comment by SathyaJayabal** [comment]
@sushilshinde. We now see the issue on  both beta and test env. It is intermittent and the page sometimes loads on  refreshing. This issue occurs only in the logged out state.

<img width="1440" alt="Screenshot 2020-06-15 at 12 45 32 PM" src="https://user-images.githubusercontent.com/58783823/84629982-d1a3e600-af08-11ea-88c0-fcad0466ff0a.png">

<img width="1440" alt="Screenshot 2020-06-15 at 1 03 52 PM" src="https://user-images.githubusercontent.com/58783823/84629967-cbae0500-af08-11ea-98b2-09c076f03861.png">

**Comment by SathyaJayabal** [comment]
@sushilshinde , for logged in users, we get this error. This is also intermittent.
example urls:
https://beta-community-app.topcoder.com/challenges/728f0685-391d-437d-bf23-cbb84b2bb627
https://test-community-app.topcoder-dev.com/challenges/4bc9acfe-2850-4738-8660-fb55727e1e4f
<img width="1440" alt="Screenshot 2020-06-15 at 12 45 32 PM" src="https://user-images.githubusercontent.com/58783823/84630524-b08fc500-af09-11ea-8567-e928e01d5311.png">
<img width="1440" alt="Screenshot 2020-06-15 at 1 08 33 PM" src="https://user-images.githubusercontent.com/58783823/84630550-bab1c380-af09-11ea-9abc-fc8fbb71d265.png">

**Comment by sushilshinde** [comment]
@SathyaJayabal please reduce dependencies for intermittent occurrences

**Comment by SathyaJayabal** [comment]
Closing this as its not observed now.
