### ISSUE TITLE
"Failed to Authenticate token" api error on Challenge Listings for some users

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4533]
"Failed to Authenticate token" error on Challenge Listings for some users and the page keeps on loading.
https://beta-community-app.topcoder.com/challenges?
User: lakshmiathreya (admin user)

<img width="1616" alt="Screenshot 2020-06-12 at 11 40 10 AM" src="https://user-images.githubusercontent.com/58783823/84584906-8bc32100-ae27-11ea-9336-aca83acad5ec.png">

<img width="1260" alt="Screenshot 2020-06-12 at 11 36 45 AM" src="https://user-images.githubusercontent.com/58783823/84584901-8534a980-ae27-11ea-8b8e-c59d61463823.png">

**Comment by sushilshinde** [comment]
@lakshmiathreya please share user details

**Comment by sushilshinde** [comment]
Please explain "Some Users"?

**Comment by SathyaJayabal** [comment]
@sushilshinde , it has been observed only for the one user : lakshmiathreya

**Comment by sushilshinde** [comment]
Please reduce priority.

**Comment by lakshmiathreya** [comment]
<img width="1672" alt="Screenshot 2020-06-16 at 6 44 46 PM" src="https://user-images.githubusercontent.com/51733042/84779071-8ae5e700-b001-11ea-81eb-2ce49aac4059.png">
<img width="1642" alt="Screenshot 2020-06-16 at 6 44 55 PM" src="https://user-images.githubusercontent.com/51733042/84779086-920cf500-b001-11ea-9e6a-fb1aeeb0ee49.png">
