### ISSUE TITLE
PWA practices

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#454]
_This is not a bug, it's a suggestion._

Community page loading experience is slow in-spite of server-side rendering. We can add PWA serviceworkers to speed it up. I can take up this task.

@ajefts @birdofpreyru your comments.

**Comment by birdofpreyru** [comment]
I would double-check what is the actual bottleneck. I guess, for many pages, the loading speed can be primarily affected by Topcoder API response time, especially in remote development environment, especially when we use API v2 (in many places).

**Comment by sushilshinde** [comment]
API calls are definitely slow but HTML markup loading is also slow. PWA will mostly address asset caching and HTML pages but not interfere with API calls. 

PWA will not prevent first time load but later loads time. Regular users of apps will find significant difference in the load time.

**Comment by birdofpreyru** [comment]
I don't quite see how is it supposed to work alongside the server-side rendering, taking into account that most of our pages have dynamic content. Assets are already cached at the client side.

**Comment by sushilshinde** [comment]
Here are some details 

https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-4-site-is-progressively-enhanced-b5ad7cf7a447

**Comment by birdofpreyru** [comment]
@sushilshinde I am still not getting the idea. I looked through the article briefly, and it looks like most of it is about server-side rendering alongside with the client-side one; this we already have in our setup (though, there is number of pages/segments, where it is not working properly yet, but it is easily fixable).

**Comment by sushilshinde** [comment]
Done
