### ISSUE TITLE
Themes support for dropdown component

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4542]
Add themes support to the existing dropdown component. New theme design like FAQ section from https://marvelapp.com/dhhd877/screen/67158505 

Test URL: http://community-app.topcoder-dev.com/examples/contentful/viewport/4GPiJa2vnl8UzhLYlPkYOb

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-07-22 at 10 58 47 AM" src="https://user-images.githubusercontent.com/58783823/88137982-579f0500-cc0a-11ea-84c5-05c40ba15356.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-08-03 at 2 24 08 PM" src="https://user-images.githubusercontent.com/58783823/89164717-0f320080-d595-11ea-8320-2d26a9839dd0.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-04 at 3 07 13 PM" src="https://user-images.githubusercontent.com/58783823/89278812-36a3ce80-d664-11ea-8198-2c059fd9f07c.png">
