### ISSUE TITLE
Google Indexing: Challenge Pages and Member Profiles

### ISSUE THREAD

**Issue by harshitmehta15** [topcoder-platform/community-app#4544]
There is definitely something wrong with the Google indexing of our challenges and member profile pages on community-app. 

Example 1
I used to search for Petr Topcoder and get Petr's profile right on the top. I see TCO17/18 interview now 

Example 2:

I used to search  CDC Text Topcoder and get the challenge link. No challenges are coming up in google search anymore.  Something when you search a unique title = you get this kind of a link. https://community-app.topcoder.com/__community__/veterans/challenges/30103825?tab=registrants
Not sure where is this link coming from?

**Comment by ajefts** [comment]
Fyi, Matt and I are trying a couple things to help on this one.

1. Adding an additional google sitemap to assist with indexing our pages.

I think this will help the "duplicate page" issue, the odd URL,  and the ranking of some pages over time. This mostly addresses #2 above.

@harshitmehta15 I think the case of petr not being at the top of the search results is more a factor of google rankings changing and not necessarily something we're doing...

**Comment by harshitmehta15** [comment]
Thanks @ajefts.  That would help! 

I did some investigation in Google Search Console and still looking at what happened to member profile pages. Having Petr's profile on the top with "Petr Topcoder"  was always there, even my search history shows that I clicked on it on May 31st.

It was always on top and now days not even in the first 383 pages, concerns me.  (I haven't checked further) Writing a script for it to deep dive! 

Something is wrong with the member profile pages indexing. I will investigate a bit more. 

Will come back and share if I find something!

**Comment by adroc-tc** [comment]
@ajefts @mtwomey 
Do we have a plan of attack on this one? Anything I can help with?
- Understanding how to fix the issue (research on what google recommends for handling canonical URL)
- How to fix it on our site (when can we update?) and tracking
- Do we need to find a google expert in the community (or check with them directly via Jessie/members)
- An estimated date we want to corral this by?

Consolidate duplicate URLs
https://support.google.com/webmasters/answer/139066?hl=en

**Comment by ajefts** [comment]
@adroc-tc @harshitmehta15 So far we added a sitemap and informed google about it.  There had previously been one, but at some point seems to have been replaced by the marketing sitemaps. Wating to see if that has any impact as it re-indexes. Are you able to help us identify other possible issues with the indexing?

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde  
1) how can we change the Page Titles? For example, I imagine we'll need a script to help update all the page titles so that if you're on /members/ page, the title would update to "/members/profile/" or whatever. Right now, Page Title shows "Topcoder".
![image](https://user-images.githubusercontent.com/47536078/94329778-de59c080-ff72-11ea-8e07-eb923b1cb0d8.png)

2) #2) how can we change the Meta content? Right now, all the pages have the following meta content: "Topcoder is a crowdsourcing marketplace that connects businesses with hard-to-find expertise. The Topcoder Community includes more than one million of the world's top designers, developers, data scientists, and algorithmists. Global enterprises and startups alike use Topcoder to accelerate innovation, solve challenging problems, and tap into specialized skills on demand." 
![Uploading image.png…]()

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @sushilshinde 

1) What is expected to page title?

2) What is expected to Meta content?

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @adroc-tc here's the spreadsheet. https://docs.google.com/spreadsheets/d/1Ee9GnRTd6nR1BYsddxoqjfK3TpAOepWx0ODV6HBTrf0/edit#gid=0

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Thanks, looks like not complete yet.

**Comment by Oanh-and-only-Oanh** [comment]
also related to this ticket https://github.com/topcoder-platform/community-app/issues/5016

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Ready in Stag env.

Sheet to ref.: https://docs.google.com/spreadsheets/d/1cXHdGbzbmP1ZqigosVsqF5nJr3CeIxAuvXLqHbAPDaA/edit#gid=596837481

**Comment by SathyaJayabal** [comment]
verified
Profile page
<img width="1440" alt="Screenshot 2020-11-24 at 9 44 38 AM" src="https://user-images.githubusercontent.com/58783823/100048086-fd24e800-2e39-11eb-9376-11906fb9f6eb.png">
Challenge Listings
<img width="1440" alt="Screenshot 2020-11-24 at 9 46 14 AM" src="https://user-images.githubusercontent.com/58783823/100048101-0615b980-2e3a-11eb-8fcf-b0ee64665ea7.png">
<img width="1440" alt="Screenshot 2020-11-24 at 9 46 34 AM" src="https://user-images.githubusercontent.com/58783823/100048112-09a94080-2e3a-11eb-8f72-247d37f23339.png">

Challenge Details
<img width="1440" alt="Screenshot 2020-11-24 at 9 47 37 AM" src="https://user-images.githubusercontent.com/58783823/100048148-2b0a2c80-2e3a-11eb-9fe7-902e3d26edc3.png">
<img width="1440" alt="Screenshot 2020-11-24 at 9 47 50 AM" src="https://user-images.githubusercontent.com/58783823/100048155-31000d80-2e3a-11eb-9afe-3c784e18ff05.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)

Challenge details
<img width="1440" alt="Screenshot 2020-11-24 at 4 51 43 PM" src="https://user-images.githubusercontent.com/58783823/100087975-7f7ecd80-2e75-11eb-8b97-14c132f8799c.png">
<img width="1440" alt="Screenshot 2020-11-24 at 4 52 30 PM" src="https://user-images.githubusercontent.com/58783823/100087997-8574ae80-2e75-11eb-996a-9e4fb9a84506.png">

Challenge listings
<img width="1440" alt="Screenshot 2020-11-24 at 4 53 07 PM" src="https://user-images.githubusercontent.com/58783823/100088053-99b8ab80-2e75-11eb-8d99-849bba32f804.png">
<img width="1440" alt="Screenshot 2020-11-24 at 4 53 11 PM" src="https://user-images.githubusercontent.com/58783823/100088065-9fae8c80-2e75-11eb-8a97-5203e21bed8c.png">

Profile Pages
<img width="1440" alt="Screenshot 2020-11-24 at 4 54 25 PM" src="https://user-images.githubusercontent.com/58783823/100088229-cc62a400-2e75-11eb-9b1f-8ca3fb7907fa.png">
<img width="1440" alt="Screenshot 2020-11-24 at 4 54 45 PM" src="https://user-images.githubusercontent.com/58783823/100088265-d97f9300-2e75-11eb-8b6a-ae364a0d1016.png">

**Comment by SathyaJayabal** [comment]
verified on prod

challenge details
<img width="1440" alt="Screenshot 2020-11-24 at 7 57 10 PM" src="https://user-images.githubusercontent.com/58783823/100107130-5408dc80-2e8f-11eb-90aa-571dc24cabd2.png">
<img width="1440" alt="Screenshot 2020-11-24 at 7 57 26 PM" src="https://user-images.githubusercontent.com/58783823/100107155-5bc88100-2e8f-11eb-901a-15dccd839a07.png">

challenge listings
<img width="1440" alt="Screenshot 2020-11-24 at 7 58 05 PM" src="https://user-images.githubusercontent.com/58783823/100107238-74389b80-2e8f-11eb-979c-3a00c3239315.png">
<img width="1440" alt="Screenshot 2020-11-24 at 7 58 18 PM" src="https://user-images.githubusercontent.com/58783823/100107267-7bf84000-2e8f-11eb-8f1a-068f52108990.png">

profile page
<img width="1440" alt="Screenshot 2020-11-24 at 7 59 14 PM" src="https://user-images.githubusercontent.com/58783823/100107402-9a5e3b80-2e8f-11eb-8d3b-6cb095e835e2.png">
<img width="1440" alt="Screenshot 2020-11-24 at 7 59 28 PM" src="https://user-images.githubusercontent.com/58783823/100107422-9fbb8600-2e8f-11eb-8388-e7a086087230.png">
