### ISSUE TITLE
Performance issue - It takes nearly a minute to load all the buckets on the listings page for a logged in user

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4547]
My Challenges: Performance issue - It takes nearly a minute to all the buckets including the My Challenges bucket. V4 only takes less than 8 seconds. 
https://beta-community-app.topcoder.com/challenges?

[perf_listings.mp4.zip](https://github.com/topcoder-platform/community-app/files/4790520/perf_listings.mp4.zip)

In comparison, for the not logged in user, the loading time is faster
[not logged in.mov.zip](https://github.com/topcoder-platform/community-app/files/4790526/not.logged.in.mov.zip)

**Comment by simranb86** [comment]
@SathyaJayabal try after changes for #4541 are merged, should be faster than a minute.

**Comment by SathyaJayabal** [comment]
@simranb86 ,thanks.

**Comment by SathyaJayabal** [comment]
@simranb86 @sushilshinde , there is no improvement in the time even after removing the  resources call (#4541 )

[4547.mp4.zip](https://github.com/topcoder-platform/community-app/files/4790945/4547.mp4.zip)

**Comment by simranb86** [comment]
> @simranb86 @sushilshinde , there is no improvement in the time even after removing the resources call (#4541 )
> 
> [4547.mp4.zip](https://github.com/topcoder-platform/community-app/files/4790945/4547.mp4.zip)

then maybe we need to note the time challenges API take to respond to each call and time it used to take in V4 and go from there.

**Comment by SathyaJayabal** [comment]
fixed on the backend
