### ISSUE TITLE
Review Opportunities Bucket: Api calls

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4568]
To get the review opportunities bucket details, both the Prod V4 and V5 integration branch on beta is using the V3 call
https://api.topcoder.com/v3/reviewOpportunities?limit=1000&offset=0

@sushilshinde, Does this have to be updated to V5 ?
<img width="1440" alt="Screenshot 2020-06-19 at 2 51 55 PM" src="https://user-images.githubusercontent.com/58783823/85117462-88bb9c80-b23c-11ea-8a23-2f1844cb1b39.png">

<img width="1440" alt="Screenshot 2020-06-19 at 2 51 36 PM" src="https://user-images.githubusercontent.com/58783823/85117430-76d9f980-b23c-11ea-857d-cad18b24ee4f.png">

**Comment by sushilshinde** [comment]
@rootelement so we should continue v3 here?

**Comment by rootelement** [comment]
@sushilshinde yes, we don't have a review API yet

**Comment by sushilshinde** [comment]
@SathyaJayabal we can close this one

**Comment by SathyaJayabal** [comment]
@sushilshinde @lakshmiathreya , the review opportunity details page also uses the V3 calls. 

To get the challenge details 
https://api.topcoder.com/v3/reviewOpportunities/30126150

To apply for a review opportunity
https://api.topcoder.com/v3/reviewOpportunities/30126150/applications?reviewApplicationRoleIds=9 

<img width="1440" alt="Screenshot 2020-07-01 at 2 35 23 PM" src="https://user-images.githubusercontent.com/58783823/86225790-5731c200-bba8-11ea-9366-0c65d23f8658.png">
<img width="1440" alt="Screenshot 2020-07-01 at 2 35 28 PM" src="https://user-images.githubusercontent.com/58783823/86225831-69abfb80-bba8-11ea-8bf6-115db3733396.png">

**Comment by sushilshinde** [comment]
@rootelement is there v3 sync with v5?

**Comment by rootelement** [comment]
@sushilshinde not sure i understand the question... Are you saying that you're going to keep community app on v3 for this, so changes in v5 propagate back? If so, yes, when some action is taken in v5, it propagates through the legacy challenge processor and legacy challenge resource processor into informix, so this should work fine.

There was a problem with the legacy-challenge-resource-processor that has been fixed today, so i would say retry this first.
