### ISSUE TITLE
Challenge phases are out of sync between V4 and V5

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4569]
We can see many challenges that are closed still in the active challenges. Also many of the Ongoing challenges in Open for registration. On looking at the api responses we can see that the api responses for  V4 and V5 have different data.

Examples:
https://www.topcoder.com/challenges/30128012  - Closed
https://beta-community-app.topcoder.com/challenges/7f9b4dfc-14b8-463d-9651-c06cbb842d6d - Ongoing
<img width="1440" alt="Screenshot 2020-06-19 at 3 36 53 PM" src="https://user-images.githubusercontent.com/58783823/85122585-69287200-b244-11ea-908c-8e10a0e0ccdd.png">
<img width="1440" alt="Screenshot 2020-06-19 at 3 37 44 PM" src="https://user-images.githubusercontent.com/58783823/85122607-75acca80-b244-11ea-8909-cd6a15dea40a.png">

https://www.topcoder.com/challenges/30130268 - Ongoing
https://beta-community-app.topcoder.com/challenges/2197c7a8-525c-4b67-829b-b4981ff15674 - Open for Registration(Stalled)
<img width="1440" alt="Screenshot 2020-06-19 at 3 42 56 PM" src="https://user-images.githubusercontent.com/58783823/85122618-7a717e80-b244-11ea-93ea-b637bc726c14.png">
<img width="1440" alt="Screenshot 2020-06-19 at 3 41 56 PM" src="https://user-images.githubusercontent.com/58783823/85122592-6f1e5300-b244-11ea-8b85-56bc880e8f95.png">

 cc @lakshmiathreya @rootelement @sushilshinde

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/challenge-api/issues/186

**Comment by rootelement** [comment]
@SathyaJayabal @lakshmiathreya Can you guys install this browser extension so when you show API output, it's clearer to read?

https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en

Also, if you're showing comparisons like this, it helps me if you not only provide the links, but pull out the v5:updated, v4:updatedAt properties for comparison. I'm going to continue reviewing this. Thanks!

**Comment by rootelement** [comment]
I'm sorry, nevermind about the updated property. i forgot that's not provided by v4

**Comment by rootelement** [comment]
Please review. The example here lines up now:
http://api.topcoder.com/v4/challenges/30128012
http://api.topcoder.com/v5/challenges?legacyId=30128012

**Comment by rootelement** [comment]
Is this still an issue? After the recent sync update and fixes to the legacy processors, this seems to be fine.

**Comment by mtwomey** [comment]
Yes kindly reconfirm this one due to recent updates.

**Comment by SathyaJayabal** [comment]
Still an issue @rootelement @mtwomey 
https://github.com/topcoder-platform/challenge-api/issues/186#issuecomment-653355484

**Comment by lakshmiathreya** [comment]
Pls note that the discrepancies across V4 (Prod) & V5 (Beta) are largely due to pending Data migration issues which are work in progress currently: https://github.com/topcoder-platform/challenge-api/issues?q=is%3Aissue+is%3Aopen+label%3AP0

**Comment by Oanh-and-only-Oanh** [comment]
closing because this is a duplicate issue
