### ISSUE TITLE
A: Apply new challenge fetch policy to listinig page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4594]
I. Implement for non-auth users 
II. The change applies to these challenge buckets 
   

1. All Challenges
2. Open for registration 
3. Ongoing challenges

III.  It should work with all the filters 
IV. Count panel should show correct counts
V. Sorting and searching should be remote

**Comment by Oanh-and-only-Oanh** [comment]
@sushil, for @LieutenantRoger to begin these performance tickets, he is currently waiting for the metadata.json change at client side to incorporate the group features. Can you give update on that work and when we can expect that to be complete so @LieutenantRoger can begin his work?

**Comment by rootelement** [comment]
This says waiting for an API fix, but I see no action or linked issue here. @Oanh-and-only-Oanh @sushilshinde please confirm what's needed here or clean up the label please.

**Comment by rootelement** [comment]
@sushilshinde @Oanh-and-only-Oanh Is this waiting on anything from API side?

**Comment by Oanh-and-only-Oanh** [comment]
@LieutenantRoger anything you need from API for this ticket?

**Comment by LieutenantRoger** [comment]
Don't need anything for now.  The new challenge fetch policy has been implemented and can be submitted.

I'm asking to exclude the groupId requirement in the new challenge list as that part seems not relevant to the challenge list.
