### ISSUE TITLE
D: Apply new challenge fetch policy to listinig page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4597]
I. Implement for auth and non-auth users 
II. The change applies to these challenge buckets 
   

1. Open for review
2. Past challenges

III.  It should work with all the filters 
IV. Count panel should show correct counts
V. Sorting and searching should be remote

**Comment by simranb86** [comment]
@sushilshinde FYI `Open for Review` we use V3 API, as it is not supported on V5, please check once and confirm on this?

**Comment by sushilshinde** [comment]
yes
