### ISSUE TITLE
Registrants table or # of registrants not updated for some contests

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4608]
On accessing the above challenge again and clicking on register, the user was able to register and the register button changed to unregister. But the registration tab is not displayed nor is the number of registrants updated on the listings page. This issue is happening only for few contests. Example:
https://beta-community-app.topcoder.com/challenges/d06475ea-8b93-4998-820c-d55a96d16972
https://beta-community-app.topcoder.com/challenges/0084eae1-4eb9-4def-bf53-e39f13b6d12b
<img width="1440" alt="Screenshot 2020-06-26 at 9 18 44 AM" src="https://user-images.githubusercontent.com/58783823/85823414-016dac00-b79b-11ea-8cd8-245de612a05c.png">
<img width="1440" alt="Screenshot 2020-06-26 at 9 19 06 AM" src="https://user-images.githubusercontent.com/58783823/85823432-0c284100-b79b-11ea-8c43-cf250c54d140.png">

**Comment by SathyaJayabal** [comment]
This seems like a  data sync issue. When I register/unregister to a challenge whose registrants have  not yet been migrated , the V4 registrations are synced and  I can see the table of registrants. And registrations work as expected.The  registrants count is also updated on the listings page. This should be fixed when the registrations are synced with V4.
https://github.com/topcoder-platform/challenge-api/issues/165

Please see video.

[registration sync.mov.zip](https://github.com/topcoder-platform/community-app/files/4836549/registration.sync.mov.zip)
<img width="1440" alt="Screenshot 2020-06-26 at 4 30 47 PM" src="https://user-images.githubusercontent.com/58783823/85850576-b075ac00-b7ca-11ea-9bc6-f462f4af0e25.png">

**Comment by rootelement** [comment]
This should be fixed as of Sunday Night with the updated sync. If you're seeing issues here, please link Challenge UUIDs and/or LegacyIDs. The issue was the sync was not updating the numberOfRegistrants and numberOfSubmissions counts when data was brought forward, but if you register for a challenge, that would trigger the ES processor which _does_ update those counts. So you wouldn't see it at first, but then it's properly calculated. Please retest.

**Comment by SathyaJayabal** [comment]
@rootelement , there are a few registrations that are not synced.

For example
https://www.topcoder.com/challenges/30130750?tab=registrants
https://beta-community-app.topcoder.com/challenges/d06475ea-8b93-4998-820c-d55a96d16972?tab=registrants

the last few registrations are not synced.
<img width="1440" alt="Screenshot 2020-07-01 at 1 44 28 PM" src="https://user-images.githubusercontent.com/58783823/86220372-239f6980-bba1-11ea-983d-354fbac61af6.png">
<img width="1440" alt="Screenshot 2020-07-01 at 1 45 14 PM" src="https://user-images.githubusercontent.com/58783823/86220394-2a2de100-bba1-11ea-898c-e59a7f46425d.png">

**Comment by SathyaJayabal** [comment]
Another example @rootelement :
https://www.topcoder.com/challenges/30131891?tab=registrants
https://beta-community-app.topcoder.com/challenges/dd6b3627-f720-4868-8a84-ee0c85a154a9
Even after registering to this challenge the counts are not updated.

[registration.mov.zip](https://github.com/topcoder-platform/community-app/files/4856612/registration.mov.zip)

**Comment by rootelement** [comment]
All examples here line up for me @SathyaJayabal. Please review.

**Comment by SathyaJayabal** [comment]
@rootelement , the registrations are lining up when you run the migration script, but the real time sync is not happening as expected. For the above example: two more users registered after you last checked. This must have been synced realtime(with a lag if 1-5 mins). But as you can see these have not been synced to v5.
<img width="1440" alt="Screenshot 2020-07-03 at 9 54 38 AM" src="https://user-images.githubusercontent.com/58783823/86431800-5ec1aa00-bd13-11ea-90f2-3cd07f1b766f.png">
<img width="1440" alt="Screenshot 2020-07-03 at 9 54 40 AM" src="https://user-images.githubusercontent.com/58783823/86431809-6719e500-bd13-11ea-8853-8547bb58f827.png">

**Comment by SathyaJayabal** [comment]
This one is tracked here. Closing this as no FE updates needed.
cc @sushilshinde @lakshmiathreya 
https://github.com/topcoder-platform/challenge-api/issues/201
