### ISSUE TITLE
Topgear changes

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4611]
We need below changes to home page of topgear.topcoder.com

 

1. The order of the content needs to be modified in the home page of topgear.topcoder.com. In the attached screenshot, I marked the content with the numbers. Please refer the attachment.

2. One link to be added to “Leverage the crowd" section.

a. Link label is ‘Reusable Components’

b. URL is https://wipro365.sharepoint.com/sites/ipgateway/SiteContent/Components.aspx

3. Update the link for ‘Request Group’ button with this link  https://topgear-app.wipro.com/topgear_groups/confirm_group_membership

a. Change the label to ‘Add me to account groups’.

4. Update FAQ link in the menu on Top with this link https://topgear-app.wipro.com/faq-categories

**Comment by Oanh-and-only-Oanh** [comment]
![image](https://user-images.githubusercontent.com/47536078/85867838-551dcc80-b77e-11ea-8ddf-9a09a411f3cd.png)

**Comment by SathyaJayabal** [comment]
verified on dev (feature branch)

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-07-09 at 5 18 08 PM" src="https://user-images.githubusercontent.com/58783823/87037541-ffc7cd80-c209-11ea-8d10-b1464c3edfdf.png">

<img width="1440" alt="Screenshot 2020-07-09 at 5 19 36 PM" src="https://user-images.githubusercontent.com/58783823/87039162-664deb00-c20c-11ea-8075-5acba05adb3d.png">
<img width="1440" alt="Screenshot 2020-07-09 at 5 22 14 PM" src="https://user-images.githubusercontent.com/58783823/87039202-749c0700-c20c-11ea-9146-1196fc975876.png">
<img width="1440" alt="Screenshot 2020-07-09 at 5 25 30 PM" src="https://user-images.githubusercontent.com/58783823/87039457-cb094580-c20c-11ea-9f4a-ef471ae31214.png">

**Comment by SathyaJayabal** [comment]
Verified on beta(develop branch)

<img width="1440" alt="Screenshot 2020-07-13 at 3 40 07 PM" src="https://user-images.githubusercontent.com/58783823/87294437-6f4aff00-c521-11ea-8dd5-b153a67fa5ef.png">
<img width="1440" alt="Screenshot 2020-07-13 at 3 40 53 PM" src="https://user-images.githubusercontent.com/58783823/87294489-81c53880-c521-11ea-9251-b30aab4a24f6.png">
<img width="1440" alt="Screenshot 2020-07-13 at 3 41 29 PM" src="https://user-images.githubusercontent.com/58783823/87294574-943f7200-c521-11ea-892f-d6e945537886.png">

<img width="1440" alt="Screenshot 2020-07-13 at 3 45 37 PM" src="https://user-images.githubusercontent.com/58783823/87294863-fac49000-c521-11ea-9480-f6193d770d11.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-13 at 6 11 07 PM" src="https://user-images.githubusercontent.com/58783823/87305648-77f90080-c534-11ea-8a3a-a7f60f874c2d.png">
<img width="1440" alt="Screenshot 2020-07-13 at 6 11 28 PM" src="https://user-images.githubusercontent.com/58783823/87305684-83e4c280-c534-11ea-8a59-d70bf991a937.png">
<img width="1440" alt="Screenshot 2020-07-13 at 6 11 51 PM" src="https://user-images.githubusercontent.com/58783823/87305729-96f79280-c534-11ea-8919-e4222054e943.png">
<img width="1440" alt="Screenshot 2020-07-13 at 6 12 13 PM" src="https://user-images.githubusercontent.com/58783823/87305739-9bbc4680-c534-11ea-85e3-c1adf296d8c2.png">
