### ISSUE TITLE
Add support for custom link on navi menu logo

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4614]
https://github.com/topcoder-platform/navigation-component/issues/177

**Comment by SathyaJayabal** [comment]
http://tco21.topcoder.com/
Clicking on Logo for logged in user takes user to 404
http://tco21.topcoder.com/my-dashboard
[logo.mov.zip](https://github.com/topcoder-platform/community-app/files/4850490/logo.mov.zip)

Clicking on logo for not logged in user takes user to topcoder home page
[logo_not loggen in.mov.zip](https://github.com/topcoder-platform/community-app/files/4850497/logo_not.loggen.in.mov.zip)

**Comment by kkartunov** [comment]
@shttp://beta-community-app.topcoder.com/__community__/tco21

**Comment by SathyaJayabal** [comment]
verified on beta
[logo.mov 2.zip](https://github.com/topcoder-platform/community-app/files/4850640/logo.mov.2.zip)

**Comment by SathyaJayabal** [comment]
verified don prod
