### ISSUE TITLE
Members api: failed to fetch error on challenge listings and details pages

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4620]
https://beta-community-app.topcoder.com/challenges?

<img width="1440" alt="Screenshot 2020-07-01 at 1 06 32 PM" src="https://user-images.githubusercontent.com/58783823/86216606-ec7a8980-bb9b-11ea-9d8d-90132faf7a7f.png">

**Comment by sushilshinde** [comment]
@SathyaJayabal I can't reproduce this

**Comment by SathyaJayabal** [comment]
@sushilshinde
closing this as it can be tracked in #4587
