### ISSUE TITLE
Challenge details page throwing "Unable to load Challenge" error for some users

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4623]
Challenge details page throwing "Unable to load Challenge" error for some users

examples:
https://beta-community-app.topcoder.com/challenges/0e19815e-fb7e-4a8c-bb52-6e5c6c101818
https://beta-community-app.topcoder.com/challenges/0084eae1-4eb9-4def-bf53-e39f13b6d12b?tab=registrants
This issue is observed for only this user and the  above challenges are displayed correctly for not logged in users.

user: CustomerUser/appirio123
There  is an error returned for the reviewtypes api call

<img width="1440" alt="Screenshot 2020-07-02 at 8 59 04 AM" src="https://user-images.githubusercontent.com/58783823/86313262-5baab900-bc42-11ea-9d1e-ea486a96cf5a.png">
<img width="1440" alt="Screenshot 2020-07-02 at 8 59 08 AM" src="https://user-images.githubusercontent.com/58783823/86313278-65ccb780-bc42-11ea-8d9a-f0e61099ec83.png">

**Comment by mtwomey** [comment]
Ok I think we got this one, while troubleshooting we found an issue with permissions for the submissions reviewTypes call. We updated that API via hotfix: https://github.com/topcoder-platform/submissions-api/pull/187

Kindly retest.

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-07-03 at 9 15 18 AM" src="https://user-images.githubusercontent.com/58783823/86429623-beb55200-bd0d-11ea-8939-f97f261e4e06.png">
