### ISSUE TITLE
Competitive programming page under Compete

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4626]
Should link to https://www.topcoder.com/community/arena page.

**Comment by SathyaJayabal** [comment]
@kkartunov , in both the header and footer?

**Comment by SathyaJayabal** [comment]
verified on dev env (feature branch)
<img width="1440" alt="Screenshot 2020-07-08 at 3 20 44 PM" src="https://user-images.githubusercontent.com/58783823/86904686-b0609f00-c12e-11ea-8289-7dfe161d51de.png">
<img width="1440" alt="Screenshot 2020-07-08 at 3 20 49 PM" src="https://user-images.githubusercontent.com/58783823/86904880-ee5dc300-c12e-11ea-9910-b55d4b53078c.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-07-13 at 3 48 20 PM" src="https://user-images.githubusercontent.com/58783823/87293698-5130cf00-c520-11ea-9f2b-9ecc6eaa9ea6.png">

<img width="1440" alt="Screenshot 2020-07-13 at 3 48 25 PM" src="https://user-images.githubusercontent.com/58783823/87294274-2004ce80-c521-11ea-9a82-a7b8dfcca10f.png">

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2020-07-13 at 6 14 52 PM" src="https://user-images.githubusercontent.com/58783823/87305889-cefed580-c534-11ea-90e4-e7cebea8da0e.png">
<img width="1440" alt="Screenshot 2020-07-13 at 6 14 57 PM" src="https://user-images.githubusercontent.com/58783823/87305904-d58d4d00-c534-11ea-9856-315ea279f9fa.png">
