### ISSUE TITLE
Registered, but not showing in OR

### ISSUE THREAD

**Issue by dmessing** [topcoder-platform/community-app#4629]
I registered in incognito with Mess at this challenge

https://beta-community-app.topcoder.com/challenges/4888baa8-1618-4fde-839d-c79608e68303?tab=registrants

**To Reproduce**
1. I registered for the challenge
2. I show up in the registrants list here: https://beta-community-app.topcoder.com/challenges/4888baa8-1618-4fde-839d-c79608e68303?tab=registrants
3. Navigate to OR: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30132044t5
4. I am not listed as a registrant

**Expected behavior**
I'd expect to be registered in [OR](url
![Screen Shot 2020-07-06 at 1 26 39 PM](https://user-images.githubusercontent.com/664840/86622691-53c67e00-bf8e-11ea-9d4b-6ad887517d50.png)
![Screen Shot 2020-07-06 at 1 26 34 PM](https://user-images.githubusercontent.com/664840/86622694-55904180-bf8e-11ea-911b-2fa870ef06be.png)
![Screen Shot 2020-07-06 at 1 41 30 PM](https://user-images.githubusercontent.com/664840/86622749-6c369880-bf8e-11ea-8e28-0119102231b1.png)

)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dmessing** [comment]
tried submitting too, and the submission works but not in OR

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal @sushilshinde  FYI.

**Comment by SathyaJayabal** [comment]
Thanks @dmessing , 
Registrations made from V5 do not show up in OR. We are tracking it here.
https://github.com/topcoder-platform/challenge-api/issues/204#issuecomment-654159305

But submissions made from V5 were showing up in OR after yesterdays fix. I will look into it again and retest.
https://github.com/topcoder-platform/challenge-api/issues/204#issuecomment-654050241

**Comment by lakshmiathreya** [comment]
cc @mtwomey @sushilshinde - great catch by Mess! - this is an immediate scenario we will face once we cut V5 over to Prod ...

**Comment by SathyaJayabal** [comment]
Retested the submissions issue. Unless the registrations are not synced, submissions also don't get synced.
https://github.com/topcoder-platform/challenge-api/issues/204#issuecomment-654585563

**Comment by Oanh-and-only-Oanh** [comment]
closing becuase this is a known and duplicate issue.
