### ISSUE TITLE
Change the color of the white outline button to dark green

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4635]
For the green outline button, the green border in the visited state should stay the same as the default one #137D60

(example: the View button here: https://marvelapp.com/prototype/535c9ga/screen/69629930)

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="1440" alt="Screenshot 2020-07-13 at 3 56 13 PM" src="https://user-images.githubusercontent.com/58783823/87294485-80940b80-c521-11ea-9acb-9b4ab526cace.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-13 at 6 16 15 PM" src="https://user-images.githubusercontent.com/58783823/87306010-03729180-c535-11ea-9b9a-5665cf7f8e28.png">
