### ISSUE TITLE
"All Challenges" navigation link not working

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#4639]
**Describe the bug**
When on a challenge listing page, clicking on compete shows a panel that houses options like All challenges, competitive programming, gig work, and practice. Out of these 4 options, all except "All challenges" redirects the user to appropriate locations on the portal. "All challenges" is not associated with any links.

**To Reproduce**
1. Go to 'https://www.topcoder.com/challenges/30132353' or any challenge page 
2. Click on 'Compete' --> it will open up a short panel with 4 options
3. All other options except "All challenges" are having a link associated with it

**Expected behavior**
"All challenges" should be linked to the challenges home page where the user gets the list of all challenges.

**Screenshots**
Below screenshot for reference 
![image](https://user-images.githubusercontent.com/45197181/87017550-bf5a5680-c1ed-11ea-8ad9-c14715a9e225.png)

**Comment by m-yadav** [comment]
cc: @Oanh-and-only-Oanh

**Comment by lakshmiathreya** [comment]
cc @SathyaJayabal

**Comment by SathyaJayabal** [comment]
Closing this as this is a known issue. It will be fixed soon.
https://github.com/topcoder-platform/community-app/issues/4441
cc @lakshmiathreya @m-yadav
