### ISSUE TITLE
Fix tables in Contentful - ContentBlock themes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4655]
For the tables, as per the one for [Schedule for Argentina](https://tco20.topcoder.com/regional-events/caribbean-and-south-central-america) event, the following items should be fixed:
- font size should be 16px
- color #2a2a2a
- distance between  2 gray lines to be 63px

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-07-24 at 4 38 52 PM" src="https://user-images.githubusercontent.com/58783823/88385580-38e86c00-cdcc-11ea-828e-db0e53580dbd.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-08-03 at 2 21 02 PM" src="https://user-images.githubusercontent.com/58783823/89164362-9df24d80-d594-11ea-987e-55ba80c63843.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-04 at 3 05 39 PM" src="https://user-images.githubusercontent.com/58783823/89278641-03613f80-d664-11ea-925b-91b2581e8578.png">
