### ISSUE TITLE
Look API Changes for Leaderboards

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4662]
Look API has undergone dev changes which demand updates in the frontend. The ticket implements what is needed to support the renamed API fields.

For now, only TCO21 dev leaderboard is switched to the new format which results in issues https://tco21.topcoder.com/competition-overview/development/leaderboard.

Testing page: https://community-app.topcoder-dev.com/__community__/tco21/competition-overview/development/leaderboard

**Comment by SathyaJayabal** [comment]
@kkartunov , looks good except for one user's avatar
<img width="1440" alt="Screenshot 2020-07-24 at 4 27 06 PM" src="https://user-images.githubusercontent.com/58783823/88384805-bf03b300-cdca-11ea-8a2c-150e01548688.png">
<img width="1440" alt="Screenshot 2020-07-24 at 4 28 12 PM" src="https://user-images.githubusercontent.com/58783823/88384817-c5922a80-cdca-11ea-9146-d4b541f55e7c.png">

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-08-03 at 2 17 40 PM" src="https://user-images.githubusercontent.com/58783823/89164073-35a36c00-d594-11ea-8f90-cc61da84260b.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-04 at 3 02 59 PM" src="https://user-images.githubusercontent.com/58783823/89278368-a2396c00-d663-11ea-9744-3a87316f77b0.png">
