### ISSUE TITLE
Add Userid param to Initiate project link in Topgear

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4663]
https://github.com/topcoder-platform/community-app/issues/4101#issuecomment-659912309

cc @lakshmiathreya @sushilshinde

**Comment by lakshmiathreya** [comment]
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
reverted  
https://github.com/topcoder-platform/community-app/milestone/51

<img width="1440" alt="Screenshot 2020-07-21 at 5 19 46 PM" src="https://user-images.githubusercontent.com/58783823/88051876-0265e380-cb77-11ea-82f1-024e61e1fd43.png">
