### ISSUE TITLE
Implement template placeholders for Contentful

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4665]
Add support for template placeholders. It will be using https://lodash.com/docs/4.17.15#template

Adding something like this in Contentful should result to rendered page when the user is logged in.
```
Hello __<%= profile.firstName %> <%= profile.lastName %>__(<%= profile.handle %>)!

Some data we have for you:
- userId: <%= profile.userId %>
- Autogenerated link to profile: <a href="https://topcoder.com/members/<%= profile.handle %>"><%= profile.handle %></a>
```

Test URL: https://community-app.topcoder-dev.com/examples/contentful/contentblock/2JEvQENG9pSUTdZSSAAxOK

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-07-22 at 10 56 45 AM" src="https://user-images.githubusercontent.com/58783823/88137850-13ac0000-cc0a-11ea-94ff-c50930b080a9.png">

**Comment by SathyaJayabal** [comment]
verified on beta (develop branch)
<img width="1440" alt="Screenshot 2020-07-22 at 3 53 48 PM" src="https://user-images.githubusercontent.com/58783823/88165596-91d0cc80-cc33-11ea-8654-676df31c5443.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-07-22 at 6 31 46 PM" src="https://user-images.githubusercontent.com/58783823/88179484-a3bd6a00-cc49-11ea-8250-6ceadc637c52.png">
