### ISSUE TITLE
Thrive updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4679]
In scope:

- no default avatar when member avatar is missing - https://marvelapp.com/prototype/1hei31bg/screen/71426378/handoff
- changed the. title of the cards to be smaller : https://marvelapp.com/prototype/1hei31bg/screen/71426374/handoff
- blob image for the articles on Thrive - https://marvelapp.com/prototype/1hei31bg/screen/60646916/handoff
- for the SRM Editorials we talked of using no banner: https://marvelapp.com/prototype/1hei31bg/screen/71426378/handoff
- For the author name and role, please use # 2a2a2a color
- For author name and role,  let's use 14px size as per design
- Social media icons: let's. update to the gray ones

**Comment by Dara-K** [comment]
Note: the date should always be bottom aligned in the same position @kkartunov

**Comment by SathyaJayabal** [comment]
@kkartunov, SRM Editorials still have a banner
<img width="1440" alt="Screenshot 2020-08-03 at 10 47 00 AM" src="https://user-images.githubusercontent.com/58783823/89148210-cff4b700-d576-11ea-8878-5fa3455e45e5.png">

**Comment by kkartunov** [comment]
@SathyaJayabal we will update them in Contentful soon. The functionality for articles without a banner is included in this ticket so we are good about it. Thanks!

**Comment by SathyaJayabal** [comment]
Verified on dev


1. no default avatar when member avatar is missing - https://marvelapp.com/prototype/1hei31bg/screen/71426378/handoff
2. changed the. title of the cards to be smaller : https://marvelapp.com/prototype/1hei31bg/screen/71426374/handoff
3. blob image for the articles on Thrive - https://marvelapp.com/prototype/1hei31bg/screen/60646916/handoff
4. for the SRM Editorials we talked of using no banner: https://marvelapp.com/prototype/1hei31bg/screen/71426378/handoff
5. For the author name and role, please use # 2a2a2a color
6. For author name and role, let's use 14px size as per design
7. Social media icons: let's. update to the gray ones
<img width="1440" alt="Screenshot 2020-08-03 at 12 43 38 PM" src="https://user-images.githubusercontent.com/58783823/89156033-9d9f8580-d587-11ea-8ed1-6f549f473d92.png">
<img width="1440" alt="Screenshot 2020-08-03 at 12 46 01 PM" src="https://user-images.githubusercontent.com/58783823/89156035-9ed0b280-d587-11ea-8e2e-aaab537e2e86.png">

<img width="1440" alt="Screenshot 2020-08-03 at 12 42 43 PM" src="https://user-images.githubusercontent.com/58783823/89156012-97110e00-d587-11ea-81b8-cee32d094f02.png">


Note: Images for all SRMs will be updated from Contentful soon.

**Comment by SathyaJayabal** [comment]
Verified on beta
<img width="1440" alt="Screenshot 2020-08-03 at 3 42 04 PM" src="https://user-images.githubusercontent.com/58783823/89172401-33dfa580-d5a0-11ea-9d5a-11a4638ccd31.png">
<img width="1440" alt="Screenshot 2020-08-03 at 3 43 42 PM" src="https://user-images.githubusercontent.com/58783823/89172412-39d58680-d5a0-11ea-8c87-1aac39387ccb.png">
<img width="1440" alt="Screenshot 2020-08-03 at 3 43 58 PM" src="https://user-images.githubusercontent.com/58783823/89172414-3a6e1d00-d5a0-11ea-9130-13dbb478ff8e.png">

Note: Images for all SRMs will be updated from Contentful soon.

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-04 at 3 13 36 PM" src="https://user-images.githubusercontent.com/58783823/89279620-38ba5d00-d665-11ea-9f1d-37ef07683753.png">
<img width="1440" alt="Screenshot 2020-08-04 at 3 13 52 PM" src="https://user-images.githubusercontent.com/58783823/89279641-3eb03e00-d665-11ea-9e62-f78c9edf5b37.png">
<img width="1440" alt="Screenshot 2020-08-04 at 3 14 09 PM" src="https://user-images.githubusercontent.com/58783823/89279644-3f48d480-d665-11ea-88fc-11df0355e6cf.png">
