### ISSUE TITLE
Remove ability to subscribe to newsletter on Cognitive community

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4683]
Remove the bottom section of the Cognitive community page that allows user to opt into receiving newsletter. 

See below. 
![image](https://user-images.githubusercontent.com/47536078/88555685-f6e24480-cfdc-11ea-8e56-896bd4c1216a.png)

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-08-05 at 11 20 32 AM" src="https://user-images.githubusercontent.com/58783823/89376592-bb96f280-d70d-11ea-8927-996c4602845d.png">

**Comment by Oanh-and-only-Oanh** [comment]
@kiril, let's release this when you come back from vacation in 2 weeks. FYI @SathyaJayabal @lakshmiathreya

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
<img width="1440" alt="Screenshot 2020-09-08 at 5 57 51 PM" src="https://user-images.githubusercontent.com/58783823/92476796-2354c780-f1fd-11ea-827d-bb2bc712222b.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-08 at 7 23 07 PM" src="https://user-images.githubusercontent.com/58783823/92485631-d2e36700-f208-11ea-8ac7-8760ec4d37aa.png">
