### ISSUE TITLE
Zurich Case studies update

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4684]
Update Zurich portal case studies. 
https://docs.google.com/presentation/d/1s3YhP-5lobMA_NWUK3Re7aFmngfmvpTGwZVYX2X90eA/edit

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh updated.

**Comment by Oanh-and-only-Oanh** [comment]
completed
