### ISSUE TITLE
"Failed to get member active challenges" error on stats history pages

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4690]
"Failed to get member active challenges" error on stats history pages
example
https://beta-community-app.topcoder.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=MARATHON_MATCH
https://beta-community-app.topcoder.com/members/picachui/details/?track=DEVELOP&subTrack=WIREFRAMES

<img width="1440" alt="Screenshot 2020-07-29 at 8 34 56 PM" src="https://user-images.githubusercontent.com/58783823/88817885-b3a1f480-d1db-11ea-8406-8eb5a4b93f30.png">

cc @sushilshinde

**Comment by sushilshinde** [comment]
@SathyaJayabal I can't replicate this

**Comment by SathyaJayabal** [comment]
closing this as its fixed form backend.
<img width="1440" alt="Screenshot 2020-08-05 at 11 06 13 AM" src="https://user-images.githubusercontent.com/58783823/89375646-b46ee500-d70b-11ea-8d79-91670c073c21.png">
<img width="1440" alt="Screenshot 2020-08-05 at 11 06 16 AM" src="https://user-images.githubusercontent.com/58783823/89375656-b9cc2f80-d70b-11ea-8983-7ae5a2cbd34c.png">
