### ISSUE TITLE
Review Opportunity 403 Error with no user feedback.

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/community-app#4691]
**Describe the bug**
When topcoder members aren't allowed to review a challenge and tries to apply for review, Modal confirmation block just closes like review request sent successfully but in console it gives HTTP 403 Error.

**To Reproduce**
1. Login as new member.
2. Go to 'https://www.topcoder.com/challenges/30134623/review-opportunities'
2. Click on 'Apply for review' button
3. Modal closes with no success or error message.
4. See console error "403: User is not allowed to review this challenge".

**Expected behavior**
Alert modal should appear that says "You are not allowed to review this challenge".

**Screenshots**
https://monosnap.com/direct/Kqbfh83T2u7OQ4d7tU5c1zQvCAutzw

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84

**Comment by Oanh-and-only-Oanh** [comment]
issue resolved
