### ISSUE TITLE
Front-end changes to subtracks

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4692]
Remove subtrack dropdown filter on challenge listings page
![image](https://user-images.githubusercontent.com/47536078/88879700-d0d8c200-d1df-11ea-826b-b00cc9798749.png)

Remove subtrack abbreviations on challenge listings page
![image](https://user-images.githubusercontent.com/47536078/88879653-b868a780-d1df-11ea-958d-c0f3e3081323.png)

**Comment by lakshmiathreya** [comment]
cc @SathyaJayabal

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , how about the updates to the member profile pages and the stats history.

cc @lakshmiathreya @sushilshinde 

Without subtracks will the member ratings for different subtracks be calculated properly ?
Same question regarding stats for the different subtracks ?

<img width="1440" alt="Screenshot 2020-07-30 at 9 48 26 AM" src="https://user-images.githubusercontent.com/58783823/88880252-dd920000-d249-11ea-87c4-c29c6689ac27.png">

**Comment by Oanh-and-only-Oanh** [comment]
That's a good question and I think we need @rootelement to help answer. 
cc @mtwomey

**Comment by sushilshinde** [comment]
Listing Page Change : https://github.com/topcoder-platform/community-app/issues/4706
