### ISSUE TITLE
Update mobile experience of underlined tabs

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4697]
as per https://marvelapp.com/prototype/5bhjaie/screen/71551840

**Comment by kkartunov** [comment]
Tesing:
http://community-app.topcoder-dev.com/examples/contentful/viewport/3YZkRulnz4xBabdFPiVlZc
https://community-app.topcoder-dev.com/__community__/tco20/competition-overview/development/leaderboard

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="499" alt="Screenshot 2020-08-03 at 2 13 11 PM" src="https://user-images.githubusercontent.com/58783823/89163640-86669500-d593-11ea-841a-453a29ecfa81.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="495" alt="Screenshot 2020-08-04 at 3 01 22 PM" src="https://user-images.githubusercontent.com/58783823/89278190-67cfcf00-d663-11ea-99ef-9cd1dacc21e9.png">
