### ISSUE TITLE
Statistics page not loading data for some tabs

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4705]
example:
https://www.topcoder.com/community/statistics?tabs[All-pills]=0&tabs[Design]=0&tabs[General]=1&tabs[MM]=0&tabs[QA]=0&tabs[Dev]=0&tabs[SRM]=0
<img width="1440" alt="Screenshot 2020-08-04 at 3 31 01 PM" src="https://user-images.githubusercontent.com/58783823/89281321-8a63e700-d667-11ea-9db7-aecbdf6a2bb3.png">
<img width="1440" alt="Screenshot 2020-08-04 at 3 12 20 PM" src="https://user-images.githubusercontent.com/58783823/89281334-8f289b00-d667-11ea-90a7-a7069da607a5.png">

**Comment by SathyaJayabal** [comment]
cc @RiteshTC

**Comment by kkartunov** [comment]
@SathyaJayabal I can't reproduce this error. Data is loading for me...can you re-check on your side?

**Comment by SathyaJayabal** [comment]
works now
<img width="1440" alt="Screenshot 2020-08-28 at 11 34 05 AM" src="https://user-images.githubusercontent.com/58783823/91526954-66bc5580-e922-11ea-9fd6-6e405e41d474.png">
