### ISSUE TITLE
TCO flag on My Dashboard - My Challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4712]
In V4 we display only the challenge subtrack tag. 
In V5 along with the challenge type flag, we also display the TCO flag.
<img width="1440" alt="Screenshot 2020-08-06 at 11 10 24 AM" src="https://user-images.githubusercontent.com/58783823/89495234-7b9b4280-d7d5-11ea-82be-ca668bef7829.png">

@Oanh-and-only-Oanh, we can close this issue, if you can confirm if this is fine.

**Comment by Oanh-and-only-Oanh** [comment]
Please close out. Thank you
