### ISSUE TITLE
"Marathon Match" must be added to the keywords filter drop down 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4717]
"Marathon Match" must be added to the keywords filter drop down on the challenge listings page
<img width="1440" alt="Screenshot 2020-08-06 at 1 59 49 PM" src="https://user-images.githubusercontent.com/58783823/89509604-24a16780-d7ed-11ea-9efa-fc0b2e157937.png">

@Oanh-and-only-Oanh, can you get this added in the DB please?

cc @sushilshinde

**Comment by rootelement** [comment]
Done in dev and prod
![Screen Shot 2020-08-10 at 7 25 30 AM](https://user-images.githubusercontent.com/5400156/89778010-c28d7e80-dada-11ea-966c-f9a4f89c4795.png)

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2020-08-10 at 4 59 37 PM" src="https://user-images.githubusercontent.com/58783823/89778318-eb3d6480-db2a-11ea-8f2a-50fc745ba080.png">
