### ISSUE TITLE
Blank page is displayed on listings page on mouse over on the challenge badge

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4720]
1. Go to challenge listings
https://beta-community-app.topcoder.com/challenges?
2. Mouse over on challenge badge

@rootelement thanks for helping in pinning down the cause.

cc @sushilshinde 
<img width="1440" alt="Screenshot 2020-08-06 at 9 02 04 PM" src="https://user-images.githubusercontent.com/58783823/89551106-2c323200-d828-11ea-8ad9-ff74d86dd287.png">

<img width="1440" alt="Screenshot 2020-08-06 at 3 26 06 PM" src="https://user-images.githubusercontent.com/58783823/89521942-0728c980-d7fe-11ea-9bf2-6df7055fca5a.png">

**Comment by SathyaJayabal** [comment]
Not able to replicate this issue now @sushilshinde

**Comment by luizrrodrigues** [comment]
@SathyaJayabal @sushilshinde This was with my latest update, I'll push a hotfix shortly.

**Comment by luizrrodrigues** [comment]
@sushilshinde hot fix ☝️

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , Thank you

**Comment by SathyaJayabal** [comment]
@luizrrodrigues, the tooltip should have type details, not subtrack details
https://api.topcoder-dev.com/v5/challenge-types

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yeah, I forgot to ask about this. I'll update.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Tooltip type details will be fixed in https://github.com/topcoder-platform/community-app/issues/4709

**Comment by SathyaJayabal** [comment]
Closing this as the tooltip details will be fixed with #4709
