### ISSUE TITLE
Colored member handles in leaderboards

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4722]
Update leaderboards to support colored member handles as now **some** looker APIs return the required rating data.
In the case of rating data not present in API response then render handles as blue links.

Match design https://marvelapp.com/prototype/ed9e597/screen/70330089

**Comment by kkartunov** [comment]
@SathyaJayabal will be no sorting on the table as it will change the podium places thus not good.

**Comment by SathyaJayabal** [comment]
@kkartunov , verified.
Does it apply only for tco21 for now?
<img width="1440" alt="Screenshot 2020-12-03 at 5 27 35 PM" src="https://user-images.githubusercontent.com/58783823/101015443-6e2c7400-358d-11eb-91ee-ab5e70271ffe.png">

**Comment by kkartunov** [comment]
@luizrrodrigues this now ready to release with the next milestone.

**Comment by SathyaJayabal** [comment]
verified on staging (develop) for TCO21
<img width="1440" alt="Screenshot 2020-12-11 at 11 50 21 AM" src="https://user-images.githubusercontent.com/58783823/101870187-228a5380-3ba7-11eb-8b1c-ae4062307a67.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-12-11 at 3 05 28 PM" src="https://user-images.githubusercontent.com/58783823/101887029-5626a700-3bc2-11eb-939f-526fd1dacdfa.png">
