### ISSUE TITLE
[$70] Technology name starting with number gives error on challenge page

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#4724]
**Describe the bug**
Challenge when mapped to a technology which starts with a number, for example, "3D Reconstruction" results in a blank page instead of challenge details on the portal. The below error is shown on the browser console.

![image](https://user-images.githubusercontent.com/45197181/89626467-20418100-d8b7-11ea-8de6-c24bb7aefcd2.png)

![image](https://user-images.githubusercontent.com/45197181/89626834-9e058c80-d8b7-11ea-9721-a608d4be0836.png)

**To Reproduce**
1. Create any new challenge or use any demo existing challenge and map the technology "3d reconstruction" or "3D" to the challenge via direct portal.
2. Go to the challenge page : www.topcoder.com/challenges/<challengeId>
3.  A blank page appears on the browser with error appearing in the browser console.

**Expected behavior**
Ideally, the challenge details should be visible on the portal instead of the blank page.

**Comment by m-yadav** [comment]
cc: @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@m-yadav , Are you still facing this issue. I can see the below challenge details page.
<img width="1440" alt="Screenshot 2020-10-12 at 9 22 01 AM" src="https://user-images.githubusercontent.com/58783823/95703380-91613400-0c6c-11eb-96e1-46be09a72a03.png">

**Comment by SathyaJayabal** [comment]
cc @Oanh-and-only-Oanh
