### ISSUE TITLE
Facing problem in registering actual start and end date in work experience and in Education section of topcoder profile

### ISSUE THREAD

**Issue by vishal1000** [topcoder-platform/community-app#4763]
**Describe the bug**
When adding End Date in Education I can't see or select later dates and also the same thing is happening with me when I am adding my Work Experience Start date and End Date in which I can't select the actual date as it is not visible.
When I decrease the screen resolution of my Laptop I can see all dates in date picker but all the other information which I have written above or below in the page gets lost and when I again fill out my information and set the date again the information gets lost.

**To Reproduce**
1. Go to  https://www.topcoder.com/settings/profile
2. Click on  https://www.topcoder.com/settings/profile#education 
https://www.topcoder.com/settings/profile#work
3. Scroll down to Start Date and End Date in https://www.topcoder.com/settings/profile#education and https://www.topcoder.com/settings/profile#work
4. See error - All Dates of the months are not visible When I decrease the screen resolution of my Laptop I can see all dates in date picker but all the other information which I have written above or below in the page gets lost and when I again fill out my information and set the date again the information gets lost.

**Expected behavior**
As per other platform we need to see all the dates in the date picker and if we select the later dates in this the information doesn't gets to lost.

**Screenshots**

![Request3](https://user-images.githubusercontent.com/54699172/90376861-b8e4b780-e094-11ea-95d5-27451b379d28.png)
![Request 2](https://user-images.githubusercontent.com/54699172/90376865-ba15e480-e094-11ea-9870-cfe67363d4f0.png)
![Request1](https://user-images.githubusercontent.com/54699172/90376868-bb471180-e094-11ea-9493-2685793c31ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome , Firefox 
 - Version Chrome(84.0.4147.125), Firefox(76.0.1)

**Additional context**

**Comment by SathyaJayabal** [comment]
we are tracking this here
#4294
