### ISSUE TITLE
SEO: friendly profile page titles

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#4769]
**Describe the bug**
Currently, all of our profile pages have the title "Topcoder". This is hurting our SEO and making it difficult for google to correctly index our pages. 

**To Reproduce**
1. Go to 'https://www.topcoder.com/members/Ansary'
2. View page source and notice the title.

**Expected behavior**
Each profile page should incorporate something that is indexable into the page title.  For example, "Topcoder Profile - Ansary".

**Comment by ajefts** [comment]
fyi @Oanh-and-only-Oanh .  Wanted to get this on our radar.  It's believed to be part of our search results issue.

**Comment by luizrrodrigues** [comment]
https://github.com/topcoder-platform/community-app/issues/4544

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed in Test env.

Please use this sheet to QA: https://docs.google.com/spreadsheets/d/1cXHdGbzbmP1ZqigosVsqF5nJr3CeIxAuvXLqHbAPDaA/edit

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed in Stag env now.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , SEO updated for profile pages
<img width="1440" alt="Screenshot 2020-11-03 at 11 41 49 AM" src="https://user-images.githubusercontent.com/58783823/97954494-ad6a7800-1dc9-11eb-8e69-a2fefa4df431.png">
<img width="1440" alt="Screenshot 2020-11-03 at 11 42 09 AM" src="https://user-images.githubusercontent.com/58783823/97954501-b2c7c280-1dc9-11eb-9b84-a97e8087d5de.png">

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-11-03 at 11 56 30 AM" src="https://user-images.githubusercontent.com/58783823/97955216-b2302b80-1dcb-11eb-9f8b-ec207e130df9.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-11-03 at 2 48 46 PM" src="https://user-images.githubusercontent.com/58783823/97967845-cd0e9a00-1de3-11eb-9c9e-39ed6ba1f0fc.png">
<img width="1440" alt="Screenshot 2020-11-03 at 2 49 05 PM" src="https://user-images.githubusercontent.com/58783823/97967866-d5ff6b80-1de3-11eb-8119-c8347708e08e.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-03 at 5 31 43 PM" src="https://user-images.githubusercontent.com/58783823/97982948-84aea680-1dfa-11eb-9bfb-6d8ef2669315.png">
