### ISSUE TITLE
Challenge Terms - Issues noted by reviewers

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#477]
- I'm not sure whether you are developing on a more high resolution display, but it looks like this on my standard 15 inch MacBook Pro Retina (effective resolution 1440 x 900 HiDPi) Chrome (without any zoom)
  Screenshots:
  ![screenshot](https://drive.google.com/uc?id=0By0mvJgQ4uBjaGFGa0dvdHI4bUk)
  ![screenshot](https://drive.google.com/uc?id=0By0mvJgQ4uBjZlVpaF9kYVVCenM)
  Note: The Agree/Disagree buttons are not visible. When I zoom-out to 80% on chrome, only then they are visible.

- When some terms of the challenge have been agreed for already, they should be shown in the progress bar as agreed, but should not appear in the agreement flow.
  - Done, verified using 2 different challenges (http://local.topcoder.com/challenges/30059412) and (http://local.topcoder.com/challenges/30059255)
  - **Recommended:** The agreement already signed, if that can appear first on the progress bar then it will look much nicer.

- In some cases there might be more than 2 terms to agree. In this case, on mobile layout, the progress bar be horizontally scollable and show just two terms within the view at a time. See how such scrolling is 
done for mobile layout of tabs selector on Challenge Details page (https://github.com/topcoder-platform/community-app/tree/develop/src/shared/components/challenge-detail/Header/TabSelector), pay 
attention to the semi-transparent elements on the edges of scrollable area, when it is not scrolled till the end. We want to copy that solution here as well.
  - Scrolling is working
  - semi-transparent elements on the edges of scrollable area are not present (issue)

**Comment by nithyaasworld** [comment]
> I'm not sure whether you are developing on a more high resolution display, but it looks like this on my standard 15 inch MacBook Pro Retina (effective resolution 1440 x 900 HiDPi) Chrome (without any zoom)
> Screenshots:
> screenshot
> screenshot
> Note: The Agree/Disagree buttons are not visible. When I zoom-out to 80% on chrome, only then they are visible.

The above issue is fixed.

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/11/2017 and back
