### ISSUE TITLE
Challenge timeline does not include checkpoint submission

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4776]
Challenge timeline does not include checkpoint submission
<img width="1440" alt="Screenshot 2020-08-18 at 7 31 57 PM" src="https://user-images.githubusercontent.com/58783823/90522667-9f716780-e189-11ea-9114-b5e66f4c12be.png">
<img width="1440" alt="Screenshot 2020-08-18 at 7 32 03 PM" src="https://user-images.githubusercontent.com/58783823/90522677-a4361b80-e189-11ea-9644-640f5367246c.png">

**Comment by cagdas001** [comment]
@SathyaJayabal This should be fixed as part of #4771, as I've made some changes at the phase displaying logic of challenge-listing page.

![checkpoint-validation](https://user-images.githubusercontent.com/28513447/90524872-41d41f80-e177-11ea-988f-ac3c05ffc421.jpg)

**Comment by SathyaJayabal** [comment]
verified on staging (i-v5-develop-24Aug)
<img width="1440" alt="Screenshot 2020-08-24 at 11 16 11 AM" src="https://user-images.githubusercontent.com/58783823/91008106-411a0e00-e5fb-11ea-8998-a1a59c798b37.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-24 at 8 01 58 PM" src="https://user-images.githubusercontent.com/58783823/91057339-b0682000-e644-11ea-9341-91b57674f93d.png">
