### ISSUE TITLE
[$200] - Switch of Challenge Details to API v3

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#478]
Now, a large part of challenge details is fetched from API v2. A new endpoint for challenge details has been added to API v3 (https://github.com/appirio-tech/ap-challenge-microservice/pull/192), thus we should move to use it as much as possible.

**Comment by birdofpreyru** [comment]
### Current State & Expected Fix:
Right now, when we access a challenge details page, the actual details are pulled from:
1. `/v3/challenges?filter=id=CHALLENGE_ID`
2. `/v2/challenges/CHALLENGE_ID`
3. Some details might be pulled from other endpoints.

Actually, the new, and proper API v3 endpoint to pull challenge details from is the
`/v3/challenges/CHALLENGE_ID`, and we want to move to use it as much as possible
(keeping the old APIs only for the stuff we cannot get elsewhere). Note that this proper endpoint
may not return in its response some data present in (1).

So, here we expect the following:
- Add `getChallenge` method into [challenge service](https://github.com/topcoder-platform/community-app/blob/develop/src/shared/services/challenges.js); it should call the new API v3 endpoint, and, if the response misses some data served by (1), it should additionally call (1) and properly merge the responses (for that update and use the `normalizeChallenge` function inside the service: we should guarantee that the result returned from the challenge service always has a standard shape and content, so that any other code in Community App can rely on it, and does not need to make any duplicated checks of the challenge data content).
- Update the actions and reducer responsible for the challenge details page; so that they use the new service method, and it does not break anything in code.
- Clean-up any related obsolete code.

**Comment by kondakovdmitry** [comment]
Could you answer some questions:
1. There seems to be a typo here: "if the response misses some data served by (1), it should additionally call (1) ". Did you mean data served by `/v3/challenges/CHALLENGE_ID`?
2. Should `getChallenge` fallback to extracting data from v2 API result in the case when v3 API call fails? (like it is done currently in [`extractChallengeDetail`](https://github.com/topcoder-platform/community-app/blob/develop/src/shared/containers/challenge-detail/index.jsx#L284))
3. I do not have access to [ap-challenge-microservice](https://github.com/appirio-tech/ap-challenge-microservice/pull/192), how can I get API v3 specs?

**Comment by birdofpreyru** [comment]
@kondakovdmitry 
1. Right, I mean if `/v3/challenges/CHALLENGE_ID` misses something, then get it from (1), and mention in the code comments, what exactly is missing.
2. Nope. We are aiming to deprecate `v2` as soon as possible. So, it is fine to still keep existing `v2` calls if they pull something that is not yet in the new `v3` endpoint (I was told all data from `v2` already made available in that `v3` endpoint, but have not double-checked myself); but definitely don't implement new logic using v2.
3. I'll drop the latest swagger spec into the forum in a few mins; I am not sure, though, whether it is up-to-date. But for `/v3/challenges/CHALLENGE_ID` you can just call it and see what you get. It is supposed to be mostly with the same fieldnames as the legacy v2 endpoint.

**Comment by kondakovdmitry** [comment]
`normalizeChallenge` function inside the service is also used in group functions like `getChallenges` (plural) and `getUserChallenges` which are used for challenge listing page and use (1) endpoint above (or similar). Merging with other responses does not seem appropriate in this case. Maybe keep `normalizeChallenge` as is and add new function like `normalizeChallengeDetails` for the purpose of response merging for `getChallenge` (single)?

**Comment by birdofpreyru** [comment]
@kondakovdmitry yeap, this sounds right, let's add the dedicated normalization function for the challenge details.

**Comment by kondakovdmitry** [comment]
PR: #625 
hash: 236f6e5
