### ISSUE TITLE
Unable to open Old marathon rounds via challenge page 

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#4781]
Challenge page for old marathon matches was visible via the URL "topcoder.com/challenges/<</roundId/>> . but it has started giving error now saying "Cannot read property 'id' of undefined"

Steps :

1.Pick any old round id . for eg : 17036 -- SpaceNet RoadDetector - RoadDetector Marathon Match
2.Hitting the URL topcoder.com/challenges/17036 shows below

![image](https://user-images.githubusercontent.com/45197181/90610232-c29c2580-e222-11ea-88bd-542cb7119b9b.png)

**Comment by lakshmiathreya** [comment]
related to https://github.com/topcoder-platform/community-app/issues/4760  - will be fixed in an upcoming release ...

**Comment by lakshmiathreya** [comment]
cc @Oanh-and-only-Oanh @SathyaJayabal

**Comment by luizrrodrigues** [comment]
@lakshmiathreya @SathyaJayabal this one is 
Duplicate of #4298
