### ISSUE TITLE
Challenge Submission Numbers

### ISSUE THREAD

**Issue by sgumilang** [topcoder-platform/community-app#4789]
I just found out since yesterday, the submission numbers in challenges have been changed into a complex set of numbers like " aed73fa6-7442-4c37-bcf4-48c207029d17" compared to previous method with only 6 digit of numbers.

The problem is that sequence is not very friendly to end users such as clients, copilots, even designers, and make us difficult to remember or to take quick notes.

Can you guys please mask that complex sequence to more user friendly, such as "Abdullah01, Abdullah02" or back to "302114", so when we check our submissions in the challenge page or in the forum, we can easily find which one is whose?

Thank you.

**Comment by Oanh-and-only-Oanh** [comment]
This has been resolved.
