### ISSUE TITLE
[$30] - Challenge register/unregister with API v3

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#479]
Related functionality has been added to API v3 (https://github.com/appirio-tech/ap-challenge-microservice/pull/189). We should make necessary changes to use it instead API v2.

**Comment by birdofpreyru** [comment]
Tried and failed to switch. See details here: https://github.com/appirio-tech/ap-challenge-microservice/pull/189#issuecomment-335182838

**Comment by birdofpreyru** [comment]
### Expected Fix:
Presumably, the new endpoints should be functional now, thus this should be an easy update to move from v2 to v3.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Unregister works, but getting 403 "You should agree with all terms of use." error on register api.
![register](https://user-images.githubusercontent.com/1818387/33330986-5d4ccefc-d486-11e7-9f3a-8569a0c53480.png)
I don't get this error in V2

**Comment by sushilshinde** [comment]
@skyhit we need your help here, I will open the separate issue on challenge API.

**Comment by birdofpreyru** [comment]
API is supposed to be fixed: https://github.com/appirio-tech/ap-challenge-microservice/pull/189#issuecomment-353608943
Let's try again to finally close this ticket

**Comment by arun1595** [comment]
@birdofpreyru Submitted a [PR](https://github.com/topcoder-platform/community-app/pull/722) to fix this issue. We can finally close it :smile:

**Comment by birdofpreyru** [comment]
@ajefts @skyhit so, the registration / unregistration with v3 seems to work in dev now (I have am still not merging it into the codebase to prevent accidential leak of the change into prod). What about the prod? I still see the issue there. Do we just need to push the API update into prod, or we need to revise prod configuration?
