### ISSUE TITLE
Lists not rendering (not a style issue - the lists are not rendering at all)

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/community-app#4791]
Requesting the relevant team to please look into this - Lists are not working in the challenge page. That is, even if I paste code containing ul or ol based lists and can see the proper rendering in the Direct preview and locally in the HTML file, when I check it in the challenge page, there is no sign of the list whatsoever - no indentation, no bullet points, no numbering - nothing.
Have also started a ticket - https://help.topcoder.com/hc/en-us/requests/67276?page=1. This is bit urgent because it's making my specs look like a mess, so in case the relevant team members or individuals are reading this, please look into it with priority, and kindly try to fix it asap.

**To Reproduce**

Open the challenge https://www.topcoder.com/challenges/c74d6aa8-0724-40a5-b177-3bf05b36e046, view source and see that there are lists in the HTML - but no lists are being rendered. Or open the project page of this challenge in Direct and verify in the Direct preview of the specification.

**Comment by cagdas001** [comment]
Looks like some minor CSS issues causing this

![2020-08-24_03-17-05](https://user-images.githubusercontent.com/28513447/90992430-5caff500-e5b8-11ea-930b-eb186dec1579.gif)

Links are also in regular text format, you can't realize it's a link until hovering on it. So, a bit styling is also needed for anchor tags.

For embedded video, it doesn't exist in the description at all. So I think it's related to somewhere else, probably where you create/edit descriptions. It might be removing iframes before saving the description

**Comment by lakshmiathreya** [comment]
Related Issue - https://github.com/topcoder-platform/community-app/issues/4510

**Comment by SathyaJayabal** [comment]
This one was fixed along with #4510
