### ISSUE TITLE
Verified symbol on skills is not showing up

### ISSUE THREAD

**Issue by sanju-singh** [topcoder-platform/community-app#4793]
**Describe the bug**
Skills under my profile don't show any skills with verified symbol even I have won multiple competition. 
As per my understanding, this issue seems to be occurring as I already added those skills manually and not added by system on winning competition, because of that skill parameter might be stating that added by user and verified symbol is not shown.

**To Reproduce**
1. Go to my profile 'https://www.topcoder.com/members/logicbreaker'
2. Check, I have won multiple first2finish and code competition.
3. It doesn't show even a single skill as verified.

**Expected behavior**
Even if skills are already added by user, after winning competition, skills should show verified symbol.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome
 - Version: latest

**Comment by SathyaJayabal** [comment]
tracked here #4316
