### ISSUE TITLE
Zurich Auth check fail 

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4797]
Community groups are loading the new id which results in some cases where auth checks fail as they use old ids

**Describe the bug**
1) "Start a Project" buttons in the catalog page of the Zurich portal are missing. See screenshot below. Zurich members should be assigned Competitor role. Those with Requestor role should be able to see "Start a Project" button

![image](https://user-images.githubusercontent.com/47536078/90851168-bbf7d600-e328-11ea-9542-a8c0849a372e.png)

2) TaaS offering is missing in Zurich catalog portal. See screenshot below

![image](https://user-images.githubusercontent.com/47536078/90851276-0e38f700-e329-11ea-854e-1623102c2574.png)
 
Refer to this document for Tass offering details: https://docs.google.com/presentation/d/1msEoE-Eaxz-qpa4oUlUMa7vpMJ0z7qhALYq0fz2YAhM/edit?ts=5eb597d9#slide=id.g77860dcee1_0_22

Community groups are loading the new id which results in some cases where auth checks fail as they use old ids

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
user:picachui belongs to `Zurich - Requestors`
<img width="1440" alt="Screenshot 2020-08-24 at 4 16 09 PM" src="https://user-images.githubusercontent.com/58783823/91036668-61f75900-e625-11ea-86a2-59de0b434c83.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-08-24 at 7 54 35 PM" src="https://user-images.githubusercontent.com/58783823/91056495-aabe0a80-e643-11ea-8356-4d9f844b4009.png">
