### ISSUE TITLE
After challenge registration, a significant delay before email notification is received, before forum is accessible and before it is listed on Online Review page

### ISSUE THREAD

**Issue by tmalbonph** [topcoder-platform/community-app#4800]
**Describe the bug**
After challenge registration, a significant delay (approximately 15 minutes in my case) before email notification is received, before forum is accessible and before it is listed on Online Review page.

**To Reproduce**
1. Open the Online Review page here https://software.topcoder.com/review/actions/ListProjects
2. On another tab, open your email provider link, E.g. https://mail.google.com/mail/u/0  for gmail
3. Go to Challenge page listing at https://www.topcoder.com/challenges/?bucket=openForRegistration
4. Select one of the listed challenge and register on that challenge by click on the **Register** button
5. Wait until the **Register** button turn color from blue to red and the text change into **Unregister**
6. After step 5. the challenge page will be refresh and the **CHALLENGE FORUM** tab will appear on that page. Right click and visit that link to verify if Forum for the challenge is properly created.
7. Check O.R. link (tab) on step 1 to verify if the challenge appear on the O.R. page
8. Check Email link (tab) on step 2 to verify if the challenge email notification is sent on user Email
9. Repeat step 6, step 7 and step 8 until the Forum is accessible, O.R. listed the challenge and Email received the Email notification for that challenge.

**Expected behavior**
1. The Forum for the challenge is accessible in less than 30 seconds after the challenge is created as indicated in step 6
2. The Online Review page will display a new Application (E.g. First2Finish, Code, Bug Hunt, Test Suites, Marathon Match, Web Design, etc.) in less than 30 seconds as indicated in step 7
3. The Email notification will be received for that challenge in less than 30 seconds as indicated in step 8

**Actual results**
After registration with an **F2F** challenge, it took approximately 15 minutes,
1. before I received the email notification,
2. before I am able to access the forum for the challenge,
3. before the challenge is shown at the Online Review page.

**Desktop (please complete the following information):**
OS: Ubuntu 18.04
Browser: Chrome
Version: Version 84.0.4147.125 (Official Build) (64-bit)

**F2F Registration**
![F2F-registration-2020-08-22-07-17-33](https://user-images.githubusercontent.com/3745678/90942353-1045a780-e448-11ea-9101-413507e4a09c.png)

**Email Notification**
![Email-notification-2020-08-22-07-19-25](https://user-images.githubusercontent.com/3745678/90942363-1b98d300-e448-11ea-9793-4de2235411c2.png)

**Comment by SathyaJayabal** [comment]
@rootelement @mtwomey, registrations from v4 (beta env) immediately reflect in OR, Forums and email confirmation (within 5 seconds)

Registrations from V5 took around 20 mins to reflect on OR, Forums and receive the confirmation email

**Comment by SathyaJayabal** [comment]
@rootelement , I see the following behaviour
1. Register to a challenge in v5. Registration seen in V5
2. No change  yet in V4 (OR or Beta)
3. After one min unregister from the above challenge. User unregistered in V5
4. No Change yet in V4(OR or Beta)
5 After 10-30 mins, user is registered to the challenge (in V4 and V5). User gets conf mail, can see the challenge in OR)
The unregistration done in step 3 is lost.

**Comment by rootelement** [comment]
Please re-test this. I've made a few tweaks to the legacy-challenge-resource-processor. I'm getting the email in < 5 seconds now. There was an issue with how we implemented retry for attempting to add a resource to a challenge that doesn't exist. I've shut that off for now, and changed the kafka group for the processor. I'll continue to monitor over the next day.

**Comment by SathyaJayabal** [comment]
@rootelement , registrations from v5 are reflecting in v4 immediately. But unregistrations from v5 are not working as expected. 

1. Register in v5. Registrations immediately reflect in v4
2. Unregister from v5. not reflected in v4
3. After few mins (approx 5-10 mins), user is registered in v5 too. Unregistration done in step 2 is lost.

**Comment by SathyaJayabal** [comment]
@rootelement , unregistrations are also working fine now.
