### ISSUE TITLE
Challenge not appearing in the Data Science listings

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/community-app#4809]
**Describe the bug**
The challenge http://www.topcoder.com/challenges/30137850 is not appearing in the Data Science listings:
https://www.topcoder.com/challenges?filter[tracks][Data%20Science]=true

Usually if a challenge has the 'Data Science' tag, it appears in the DS listings. Furthermore, in the challenge page, the logo being used is the usual 'Code' green logo, instead of the Orange DS Code logo.

**Comment by Oanh-and-only-Oanh** [comment]
@ketzjs09, this challenge was launched as CODE in Direct.

**Comment by ketzjs09** [comment]
@Oanh-and-only-Oanh  - Okay, but previously challenges of all types used that had the 'Data Science' tag used to appear in the https://www.topcoder.com/challenges?filter[tracks][Data%20Science]=true listings.

Has that been changed? If yes, which challenge formats are allowed now and what's the reason for this change?

**Comment by Oanh-and-only-Oanh** [comment]
DS is its own track now so it must be launched as a DS challenge to show up in DS filter. However, if it is tagged with DS tag, it will show up in challenge keywords search. Basically, if challenge is DS, it should just be launched as one and not as a DEV challenge and tagged as DS.

**Comment by ketzjs09** [comment]
"Basically, if challenge is DS, it should just be launched as one and not as a DEV challenge and tagged as DS." Well my 2+ years of copiloting experience says that it's not possible to do that.

A challenge can be a Dev challenge and still be a DS challenge. In fact, I have been a Data Science Code challenge copilot all along and my challenges used to list in the DS listings and had an orange DS badge. 

The way it worked was: I launched the challenge as a usual Dev track Code challenge, but if it had the 'Data Science' tag included, it automatically showed up in the Data Science listings and had an orange badge.

I guess things have somehow changed inadvertently?

**Comment by ketzjs09** [comment]
Here are the options for selecting a challenge type: https://drive.google.com/file/d/1THo30rtW8HY-grS0fB7AOWzHRf-t06_7/view?usp=sharing

There's no way to launch a Code challenge of DS type in there. Ideally there should be. But till now, we used to launch DS code challenges, the way I described above.

**Comment by Oanh-and-only-Oanh** [comment]
@ketzjs09 you're correct this was the case but we as of last week we integrated with v5 challenge API which changed how challenges are shown. 

If you launch a Data Science > Marathon Match, it will come over in the Data Science track, be a Challenge, with a tag of Marathon Match on it. Right now, there’s no way to launch a non-Marathon Match in the data science track until the new challenge manager comes out. We are discussing this now.

**Comment by rootelement** [comment]
This is fixed in prod:
https://www.topcoder.com/challenges/c74d6aa8-0724-40a5-b177-3bf05b36e046

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2020-08-31 at 9 27 45 AM" src="https://user-images.githubusercontent.com/58783823/91681495-4089f600-eb6c-11ea-9bdd-3dea95c7c96e.png">
