### ISSUE TITLE
Can't register on the challenge and always get an error message

### ISSUE THREAD

**Issue by arnandosimanjuntak** [topcoder-platform/community-app#4815]
Hi guys,
I'm facing issue while registering on the challenge in the last few days.
I can't register and always get an error message like this:

![image](https://user-images.githubusercontent.com/30616976/91334301-f1a13100-e7f8-11ea-87f7-9908a50efb7b.png)

![image](https://user-images.githubusercontent.com/30616976/91334322-f9f96c00-e7f8-11ea-9180-e82ad1e05cb0.png)

I have tried to clear my browser cached but that issue still happening, so I always need to send an email to support to help me registering on the challenge. 

The support team said there might be some issue with my handle (preventing registration) and they told me to post that issue here to get solution and consideration from the product team.

So, is there any solution for that?

**Comment by Oanh-and-only-Oanh** [comment]
hi @arnandosimanjuntak, thanks for opening this ticket. We are working on this ticket now. Feel free to follow the status here https://github.com/topcoder-platform/community-app/issues/4787

**Comment by SathyaJayabal** [comment]
tracking in #4787
