### ISSUE TITLE
Submissions not reflecting in OR

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4819]
Some of the submissions made from v5, do not reflect in OR.

Example:
https://www.topcoder.com/challenges/01aabee6-a81b-4e62-8d0b-b9400be811c4?tab=submissions
This challenge has 14 submissions (only two of these submissions are from the same user).

![image (9)](https://user-images.githubusercontent.com/58783823/91398775-622c6a00-e85a-11ea-82b2-666a5a6d6393.png)
<img width="1440" alt="Screenshot 2020-08-27 at 11 42 43 AM" src="https://user-images.githubusercontent.com/58783823/91398810-72444980-e85a-11ea-8f85-1393b7394124.png">

Another example:
https://www.topcoder.com/challenges/c0b166e9-9d6f-4169-affa-20d6aadb57ec
where they was an change to the winner, because a submission did not show up in OR

cc @sushilshinde @rootelement @callmekatootie

**Comment by SathyaJayabal** [comment]
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
here is a comparison with v4 of the same challenge
<img width="1440" alt="Screenshot 2020-08-27 at 12 07 43 PM" src="https://user-images.githubusercontent.com/58783823/91400822-f4823d00-e85d-11ea-85f4-4dfe7c613f83.png">

**Comment by rootelement** [comment]
I believe this was due to the slow registration. The user was registered in v5 so was able to submit, but the legacy processor wouldn't add it in direct/OR. Please retest.

**Comment by rootelement** [comment]
@mtwomey tested in prod after fix was deployed and saw his submission in direct in real time.

**Comment by SathyaJayabal** [comment]
This can be closed along with #4800
