### ISSUE TITLE
Submission tab displays all submissions of members

### ISSUE THREAD

**Issue by cagdas001** [topcoder-platform/community-app#4822]
**Describe the bug**
Submission tab displays all submissions a member has made.

**To Reproduce**
1. Go to https://www.topcoder.com/challenges/cd3eb886-50fc-4def-a6b0-ba51fb08abf3
2. Click on **Submissions** tab

**Expected behavior**
Only the latest submission should be reflected in the Submission tab.

**Screenshots**

![image](https://user-images.githubusercontent.com/28513447/91433075-5f864080-e86b-11ea-8e61-0708a4453363.png)

**Comment by SathyaJayabal** [comment]
@cagdas001 This is expected.
https://www.topcoder.com/an-update-from-the-product-development-team-challenge-v5-api-release/.
