### ISSUE TITLE
Gig work pages post prod fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4826]
- Should be a message that says "No Results" if no results are found in the search
- Please allow user to press "enter" to search
- Clicking in search bar does not place cursor there if you click on placeholder text
- Skills icon on Listing Page is messed up

**Comment by SathyaJayabal** [comment]
verified on staging. @kkartunov is the font of the "No Results" ok?
<img width="1440" alt="Screenshot 2020-08-28 at 1 58 15 PM" src="https://user-images.githubusercontent.com/58783823/91539322-c0c71600-e936-11ea-9701-19b87d8c7d0f.png">

<img width="1440" alt="Screenshot 2020-08-28 at 1 58 07 PM" src="https://user-images.githubusercontent.com/58783823/91539301-bc026200-e936-11ea-98a4-7498ee810997.png">

**Comment by hokienick** [comment]
Yes the font is ok for now.

**Comment by SathyaJayabal** [comment]
verified in staging(develop branch)
<img width="1440" alt="Screenshot 2020-09-01 at 5 07 51 PM" src="https://user-images.githubusercontent.com/58783823/91845114-3eac5980-ec76-11ea-8022-3702afee1275.png">
<img width="1440" alt="Screenshot 2020-09-01 at 5 12 03 PM" src="https://user-images.githubusercontent.com/58783823/91845139-4835c180-ec76-11ea-8dfe-992dbbcc5a85.png">

Also includes some content changes in the gig details page
<img width="1440" alt="Screenshot 2020-09-01 at 5 12 24 PM" src="https://user-images.githubusercontent.com/58783823/91845227-68658080-ec76-11ea-8d04-3949e61c3624.png">
<img width="1440" alt="Screenshot 2020-09-01 at 5 12 49 PM" src="https://user-images.githubusercontent.com/58783823/91845243-6dc2cb00-ec76-11ea-8c7e-0e82741555ba.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-01 at 6 45 37 PM" src="https://user-images.githubusercontent.com/58783823/91855873-68b84880-ec83-11ea-8fc5-bfe62bb56da8.png">
<img width="1440" alt="Screenshot 2020-09-01 at 6 45 40 PM" src="https://user-images.githubusercontent.com/58783823/91855885-6e159300-ec83-11ea-971b-684622808db0.png">
