### ISSUE TITLE
TCO Scoreboard - Issues found by reviewers

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#483]
- Authorization checks are not implemented correctly: tokens are not verified via TC API
- Input validation is not handled properly.
  - I can create a new submission for a 'Code' challenge without any of the 'Code'-specific fields.
  - Even if they are configured as 'required' there's no error and the submission is created successfully.
  - I can create a submission for a 'Code' challenge with the fields from a 'Design' challenge.
- Edit Submission -> Update Submission
- In API or model, you do not restrict this field values - sumbission type (provisional / final)
- In API or model, you do not restrict this field values -state (idle / testing / complete)
- Update competitor’s progress: this will update competitor’s status on the specified challenge, writing to the database his score, time of submission, sumbission type (provisional / final), state (idle / testing / complete), score. The actual data to put into the database should be configured per challenge type.

  You are not including time of submission
- Delete submission fails with this error even though I have a token -Authorization token is required. 
  ```
  ::ffff:127.0.0.1 > 404 DELETE /api/scoreboard/submissions/7 1.611 ms 32 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

  TypeError: Cannot read property 'split' of undefined
    at decodeToken (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/tc-accounts/core/token.js:26:17)
    at getTokenExpirationDate (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/tc-accounts/core/token.js:74:19)
    at isTokenExpired (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/tc-accounts/core/token.js:42:13)
    at _callee$ (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/src/server/tco/scoreboard/common/auth.js:42:7)
    at tryCatch (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/e/Reviews/Scoreboard/Subs/submission-518805-
  Submission/community-app/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/e/Reviews/Scoreboard/Subs/submission-
  518805-Submission/community-app/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise (<anonymous>)
    at F (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/core-js/library/modules/_export.js:35:28)
    at /e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at auth (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/src/server/tco/scoreboard/common/auth.js:60:17)
    at /e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/src/server/tco/scoreboard/index.js:29:26
    at Layer.handle [as handle_request] (/e/Reviews/Scoreboard/Subs/submission-518805-
  Submission/community-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/express/lib/router/route.js:137:13)
    at _callee$ (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/src/server/tco/scoreboard/index.js:56:17)
    at tryCatch (/e/Reviews/Scoreboard/Subs/submission-518805-Submission/community-
  app/node_modules/regenerator-runtime/runtime.js:65:40)
  ```
- https://apps.topcoder.com/forums/?module=Thread&threadID=905802&start=0

  You are not capturing competitor's country
- https://apps.topcoder.com/forums/?module=Thread&threadID=905801&start=0

  The current codebase supports only code and design - the copilot confirmed

  ' Challenge type in specs does not mean code / F2F / design, etc. It is just some auxiliary ID we use for configuration of the scoreboard; so that we can say: all challenges of this type should have these data, and the scoreboard for them should be styled the following way. At the moment we are planning to input all data manually, so it is quite independent from TC platform itself. '

  However, your model definition is not generic to support all challenge types

- If challenge-specific values are not passed when creating a new submission, the word 'test' is shown in the table as default.

- Should provide validation and negative scenario tests for create challenge
- Should provide validation and negative scenario tests for update challenge
- There are some existing test failures (no score down for this)
- Data is wrong - https://cl.ly/2i0q3P2V2P3d
  This is for a single challenge so how can durations and challenge types be different?
- https://cl.ly/0O1I0q411o1Y - There is no submission state called 'Done'
- There are many lint errors.
- The new components don't use react-css-themr properly. Please check how other components use it. (eg: The Modal component)
- When the token is invalid the response code is 404 Not Found. It should be 401 Unauthorized for missing/invalid token and 403 Forbidden if the user is not an admin.
- DELETE /scoreboard/submissions/:id & DELETE /scoreboard/challenges/:id always return 200 OK even if the provided ID does not exist. Not a major issue though.
- It would be better to return the error message as a JSON object instead of plain text.
- In server.js

  import tcCommunitiesDemoApi from './tc-communities';
  import scoreboardApi from './tco/scoreboard';
  import scoreboardModels from './tco/scoreboard/models';

  // serve demo api
  app.use('/api/tc-communities', tcCommunitiesDemoApi);

  // serve scoreboard api
  scoreboardApi(app, '/api/scoreboard');

  Why do you use a different coding convention for scoreboard?
- /**
  * Gets a submission
  * @param {Integer} id the submission id
  * @returns {Object} the submission
  */
  function get(id) {

  Better to name id -> submissionId
- Get a detail of challenge -> Get the details of challenge
- Get a detail of submission -> Get the details of submission

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/11/2017 and back
