### ISSUE TITLE
Member Rank color is not consistent

### ISSUE THREAD

**Issue by tmalbonph** [topcoder-platform/community-app#4831]
**Describe the bug**
Member Rank color is not consistent. Please note that coder rank is very important when you need it to show up on your accomplishment portfolio or you are aspiring to get a work a gig-work with better pay for a weekly base job.

**To Reproduce**
1. Visit your profile, (replace TMALBONPH with your handle) https://www.topcoder.com/members/TMALBONPH  
2. Visit one of your registered challenge, take note your rank color like the following: https://www.topcoder.com/challenges/c74d6aa8-0724-40a5-b177-3bf05b36e046?tab=registrants
3. Visit your Forum posting like the following: https://apps.topcoder.com/forums/?module=ThreadList&forumID=775886&sortField=9&sortOrder=0&start=15
4. Visit Online Review page like the following: https://software.topcoder.com/review/actions/ListProjects

**Expected behavior**
All Coder rank color should have the same color, one of black, gray, green, blue, yellow or red.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04
- Browser: Chrome
- Version: Version 84.0.4147.125 (Official Build) (64-bit)

**Actual Results**
Coder rank color does not display the same color on the selected pages mention in step 1, step 2, step 3 and step 4.

**Step 1 Coder Profile color, shown is BLUE (1)**

![Profile_color](https://user-images.githubusercontent.com/3745678/91615190-9f593f00-e9b5-11ea-9eff-dde723d6ad6d.png)

**Step 2 Coder Challenge color, shown is BLUE (2)**

![Signup_color](https://user-images.githubusercontent.com/3745678/91615220-ac762e00-e9b5-11ea-9041-3a64a681e836.png)

**Step 3 Coder Forum color, shown is GREEN (3) and GRAY (4)**

![Forum_color](https://user-images.githubusercontent.com/3745678/91615240-b304a580-e9b5-11ea-8fc7-6dc89bec12c4.png)

**Step 4 Coder Online Review color, shown is GRAY (5)**
![OnlineReview_color](https://user-images.githubusercontent.com/3745678/91615281-c748a280-e9b5-11ea-98af-ffab74e704ca.png)

**Online Review color, shown is BLUE (6) since August 28 2020 @ 04:02:58 PHT, this is gray now (5)**
![OR_Before_2020-08-28_04-02-58](https://user-images.githubusercontent.com/3745678/91616896-468ba580-e9b9-11ea-9aef-55f3357086b7.png)

**Comment by tmalbonph** [comment]
see similar issue created by @VanitaW here: https://github.com/topcoder-platform/community-app/issues/4794

**Comment by luizrrodrigues** [comment]
@rootelement API returning different rating in `/MEMBER/stats` and `/MEMBERS/stats/history`:

![image](https://user-images.githubusercontent.com/7029641/91797768-c607b780-ebf9-11ea-9c80-9b3a122ff104.png)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , the colour shown is forums and online review is out of scope for us. We need to make sure what we display on challenge details and member profiles/stats history page is correct.

For the api issue we already have https://github.com/topcoder-platform/community-app/issues/4794
