### ISSUE TITLE
Create URL for New Activate Success Welcome Page

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4847]
@kkartunov and I are building a 50/50 landing page for those who click the activation link after registering with Topcoder.  This currently points to the [Practice Page](https://www.topcoder.com/community/practice).

Please create a url for topcoder.com/start

**Comment by Oanh-and-only-Oanh** [comment]
@kkartunov, what's the proposed new URL for the new 50/50 page? FYI @luizrrodrigues

**Comment by kkartunov** [comment]
@Oanh-and-only-Oanh it should be www.topcoder.com/start

**Comment by luizrrodrigues** [comment]
@kkartunov This URL will be created in Contentful right?

**Comment by kkartunov** [comment]
@luizrrodrigues yes and it also need to be opened in LB in AWS. @sushilshinde is aware of that.

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-09-10 at 7 53 04 AM" src="https://user-images.githubusercontent.com/58783823/92674351-be9f8700-f33a-11ea-8125-6ce3c78cc5fc.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env

![image](https://user-images.githubusercontent.com/55895538/92682650-d7746080-f36b-11ea-8762-b242f058e171.png)

**Comment by sandhiyakavi** [comment]
Member Welcome page URL redirecting to some other page.

![image](https://user-images.githubusercontent.com/55895538/92721624-59cb4780-f3a1-11ea-87db-2e75e3ff7752.png)

[#4847_fail.zip](https://github.com/topcoder-platform/community-app/files/5201188/4847_fail.zip)

**Comment by sushilshinde** [comment]
@Kiril this https://www.topcoder-dev.com/start is always re-directed https://www.topcoder.com/start-typ-ing/

**Comment by sandhiyakavi** [comment]
Retested on Production.Working as Expected.

![image](https://user-images.githubusercontent.com/55895538/92727095-94d17900-f3a9-11ea-91b1-77d533ef68ed.png)
