### ISSUE TITLE
Create 50/50 Member Welcome Page

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4848]
@kkartunov will be creating this page and will have the url being created in ticket #4847 .

This page should not have a header navigation and only 2 buttons.  One that goes to the [Gigs Listings](www.topcoder.com/gigs) page on one that goes to the [Practice](https://www.topcoder.com/community/practice) page.

**Comment by kkartunov** [comment]
Required look and feel: https://marvelapp.com/prototype/535c9ga/screen/72461895

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-09-10 at 7 53 04 AM" src="https://user-images.githubusercontent.com/58783823/92674341-b8a9a600-f33a-11ea-9b7e-91fa8a527c42.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env.

![image](https://user-images.githubusercontent.com/55895538/92682478-6b91f800-f36b-11ea-96c4-a8e138bd76bb.png)

**Comment by sandhiyakavi** [comment]
Member Welcome page URL redirecting to some other page.

![image](https://user-images.githubusercontent.com/55895538/92721624-59cb4780-f3a1-11ea-87db-2e75e3ff7752.png)

**Comment by sandhiyakavi** [comment]
Retested on Prod.Working as Expected.

![image](https://user-images.githubusercontent.com/55895538/92727065-86835d00-f3a9-11ea-9047-c7a0b3af6f1a.png)
