### ISSUE TITLE
Filter by Keywords supports partial matching of Technology.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4852]
Description:
Filter by Keyword  supports partial matching of Technology.If filtered with technology 'Java' , the challenges related to 'JavaScript' technology is also getting displayed.

Steps to reproduce:
1. Go to the Challenge listings page.
2. Click the Filters button.
3. Enter 'Java' in the Keywords search.
4. Check the challenges filtered.

Expected behavior:
Only Challenges related to Java technology should be displayed.

Actual behavior:
Challenges related to 'JavaScript' is also displayed along with Java.

Screenshots:
<img width="957" alt="keyword_partial" src="https://user-images.githubusercontent.com/55895538/92079105-56ace600-edfa-11ea-94f4-0dfbc4bbd6ac.png">

**Comment by Oanh-and-only-Oanh** [comment]
@sandhiyakavi, thanks for this filing this tickets but we actually do want to allow partial matching so this is acceptable.
