### ISSUE TITLE
RSSFeed page is not displayed on clicking the RSS Feed link at Challenge listings page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4853]
Description:
RSSFeed page is not displayed on clicking the RSS Feed link at Challenge listings page.

Steps to reproduce:
1. Go to the challenge listings page.
2. Click on RSS Feed link at the right side bar.
3. Check if the RSS Feed page is getting displayed.

Screenshots:
<img width="959" alt="RSSFeed" src="https://user-images.githubusercontent.com/55895538/92082443-81e60400-edff-11ea-8322-984b1cf3c9b5.png">

**Comment by Oanh-and-only-Oanh** [comment]
closing. we have a ticket for this issue already.
