### ISSUE TITLE
Add legacy ID to new submission ID

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4858]
Problem: when design copilots post checkpoint feedback, they refer to submission numbers. These submission numbers come from OR. However, designers are not able to correlate their submission to these submission numbers because what they see in the front-end of CA is a different set of numbers. 

New feature requirement: 
Add legacy submission ID found in OR underneath new submission ID in light grey color

![image](https://user-images.githubusercontent.com/47536078/92149353-c0b19500-edd2-11ea-9b1c-d416d2001bd1.png)

**Comment by skyhit** [comment]
https://github.com/topcoder-platform/community-app/pull/4903

**Comment by luizrrodrigues** [comment]
@skyhit Please PR to https://github.com/topcoder-platform/community-app/tree/submissionId-hotfix

**Comment by Oanh-and-only-Oanh** [comment]
@skyhit @luizrrodrigues, is this in DEV for QA?

**Comment by luizrrodrigues** [comment]
I'll deploy today

**Comment by luizrrodrigues** [comment]
Updated PR: https://github.com/topcoder-platform/community-app/pull/4933

**Comment by luizrrodrigues** [comment]
@skyhit Solution using `legacyId` but API return `legacySubmissionId`

![image](https://user-images.githubusercontent.com/7029641/93380821-228fe700-f836-11ea-9a20-764dbbe08e78.png)

cc @rashmi73

**Comment by luizrrodrigues** [comment]
@sandhiyakavi Ready For Review

**Comment by sandhiyakavi** [comment]
Verified .Working as Expected.

![image](https://user-images.githubusercontent.com/55895538/93430708-0f484e80-f8fe-11ea-86df-dfb8692dfdd6.png)
![image](https://user-images.githubusercontent.com/55895538/93430783-28e99600-f8fe-11ea-91b0-cfe38d41e094.png)

**Comment by sandhiyakavi** [comment]
Verified on Staging.

![image](https://user-images.githubusercontent.com/55895538/93445071-d7e09e80-f90b-11ea-9953-760732eb298d.png)
![image](https://user-images.githubusercontent.com/55895538/93445258-eaf36e80-f90b-11ea-938a-3e03e331152c.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-17 at 6 09 21 PM" src="https://user-images.githubusercontent.com/58783823/93471430-f7c69100-f910-11ea-8f3f-358b5ff03449.png">
