### ISSUE TITLE
View Old Challenge

### ISSUE THREAD

**Issue by hbaidouri** [topcoder-platform/community-app#4860]
**Describe the bug**
Could not view my old challenge from the following link : https://www.topcoder.com/members/MoroccoMIT/details/?track=DEVELOP&subTrack=CODE&tab=challenges

**To Reproduce**
1. Go to 'Community' version
2. Login using a developper account
3. Click on the alias of the developper a the top bar
4. Go to 'My Profile' Tab
5. Scroll down to 'DEVELOPMENT ACTIVITY'
6. Click on the 'Code' or 'First2Finish' or any one
7. Switch to the 'Challenges' Tab

**Expected behavior**
The application should show the list of the old challenges

**Screenshots**
The following screenshot show the actual result :
![Sn](https://user-images.githubusercontent.com/24258575/92226672-ffac1d00-ee9c-11ea-924b-5826f0664e51.png)

**Desktop**
 - OS: Windows
 - Browser : chrome
 - Version : 85

**Comment by Oanh-and-only-Oanh** [comment]
Thank you for filing this ticket. This is a known bug and our team is working on fixing. Closing this ticket but you can track the status of the work with this other ticket. https://github.com/topcoder-platform/community-app/issues/4527

**Comment by hbaidouri** [comment]
Great. Thanks 👍
