### ISSUE TITLE
Challenge history is empty in user profile

### ISSUE THREAD

**Issue by lstkz** [topcoder-platform/community-app#4863]
**Describe the bug**
The challenge history is empty in the user profile. API returns an empty array.

**To Reproduce**
open
https://www.topcoder.com/members/Sky_/details/?track=DEVELOP&subTrack=CODE&tab=challenges

**Expected behavior**
There should be challenges.

**Screenshots**
![image](https://user-images.githubusercontent.com/4478684/92262909-1c1b7a00-eedc-11ea-92f7-e845d6c43899.png)

**Comment by Oanh-and-only-Oanh** [comment]
Thanks for filing this ticket. This is a known bug and our team is working on fixing. Closing this ticket but you can track the status of the work with this other ticket. #4527
