### ISSUE TITLE
Can't register to any challenge

### ISSUE THREAD

**Issue by lstkz** [topcoder-platform/community-app#4864]
**Describe the bug**
I cannot register for any challenge.

**To Reproduce**
- Open challenge
- Click register

**Expected behavior**
I should be able to register.

**Screenshots**
![image](https://user-images.githubusercontent.com/4478684/92263273-a532b100-eedc-11ea-8016-90587a9366ea.png)

**Comment by Oanh-and-only-Oanh** [comment]
I am not able to reproduce this issue. @SathyaJayabal @lakshmiathreya, can you try?

**Comment by SathyaJayabal** [comment]
its the member handle with special character issue @Oanh-and-only-Oanh . This member's handle is `sky_`
Tracking here
https://github.com/topcoder-platform/community-app/issues/4787

**Comment by SathyaJayabal** [comment]
@lstkz, We are working on fixing this issue, meanwhile please contact support to get yourself registered.

**Comment by SathyaJayabal** [comment]
@lstkz, you should be able to register now
