### ISSUE TITLE
Add gig work category to Thrive

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4867]
We need Gig Work category in Thrive. Therefore changes needed are:
- Homepage - new section as per https://marvelapp.com/prototype/1hei31bg/screen/71426374
- Category page - as per https://marvelapp.com/prototype/1hei31bg/screen/72463989

**Comment by SathyaJayabal** [comment]
@kkartunov , gigs category page is not loading
<img width="1440" alt="Screenshot 2020-09-09 at 1 25 36 PM" src="https://user-images.githubusercontent.com/58783823/92570820-f9a0ac80-f29f-11ea-9329-a35ca8d30717.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-09-09 at 3 39 30 PM" src="https://user-images.githubusercontent.com/58783823/92585536-b7349b00-f2b2-11ea-93cf-ffd11878d705.png">
<img width="1440" alt="Screenshot 2020-09-09 at 2 39 06 PM" src="https://user-images.githubusercontent.com/58783823/92585557-bbf94f00-f2b2-11ea-8acd-5d6790948717.png">

**Comment by SathyaJayabal** [comment]
@kkartunov 
1. Gig Work must be below QA
<img width="1440" alt="Screenshot 2020-09-09 at 3 45 55 PM" src="https://user-images.githubusercontent.com/58783823/92586495-eef01280-f2b3-11ea-9ce9-8aa4ac286811.png">

2. Clicking on How To category from GIGS  from thrive home page opens the correct page, however the category selected on the left is incorrect.The How To category under QA is selected.
[gigs.mp4.zip](https://github.com/topcoder-platform/community-app/files/5194436/gigs.mp4.zip)

**Comment by kkartunov** [comment]
@SathyaJayabal thanks.
1. The tree and its items are and should be sorted alphabetically. Will will follow that and skip design as it is wrong about the correct place.
2. Fix pushed for that and deploying on text&stage...

**Comment by SathyaJayabal** [comment]
Thanks @kkartunov , verified on staging

**Comment by sandhiyakavi** [comment]
Verified in Staging environment.

![image](https://user-images.githubusercontent.com/55895538/92682180-a9425100-f36a-11ea-9993-e40e73329aec.png)

![image](https://user-images.githubusercontent.com/55895538/92682221-c840e300-f36a-11ea-8361-7e84235f83e7.png)

**Comment by sandhiyakavi** [comment]
Verified on Production.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/92720891-3bb11780-f3a0-11ea-8816-d88de0784f1c.png)

![image](https://user-images.githubusercontent.com/55895538/92721022-63a07b00-f3a0-11ea-832c-0eaa268f5d0d.png)
