### ISSUE TITLE
Gig Work - fixes #2

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4868]
- For the gig listing page, move the last 3 columns  more to the right side so the skills can fit better
- https://drive.google.com/file/d/1TPW56QgujZ4oe-zy0Vcr5nHAyF83mhke/view?usp=sharing
- For the GiG EDU page, fix the modal window style to look the same as the TCO20 and TCO21 ones (on leaderboards)

**Comment by kkartunov** [comment]
@SathyaJayabal this is ready for QA.
Test urls:
- gig EDU page https://test-community-app.topcoder-dev.com/community/getting-the-gig

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal this is ready for QA.
> Test urls:
> 
> * gig EDU page https://test-community-app.topcoder-dev.com/community/getting-the-gig

@kkartunov , Do we have an issue for the gigs edu page? This issue is about fixes to the gigs details page.

**Comment by SathyaJayabal** [comment]
For the modal on the edu page.
1. There is too much space above the heading
2. Modal is closed by the `X` sign on the top right, where as in the TCO modals, we have a `RETURN TO PAGE` button

<img width="1440" alt="Screenshot 2020-09-09 at 1 39 57 PM" src="https://user-images.githubusercontent.com/58783823/92572463-1a6a0180-f2a2-11ea-9984-7f8bea461cfb.png">
<img width="1440" alt="Screenshot 2020-09-09 at 1 40 35 PM" src="https://user-images.githubusercontent.com/58783823/92572479-1fc74c00-f2a2-11ea-9170-4d26145bc735.png">


verified other fixes
<img width="1440" alt="Screenshot 2020-09-09 at 1 33 17 PM" src="https://user-images.githubusercontent.com/58783823/92571746-1db0bd80-f2a1-11ea-94cc-8b7c0887b983.png">

**Comment by kkartunov** [comment]
@SathyaJayabal 
1. Is content. I reduced the top space.
2. This is a generic modal thus should not have the button as it could be at any page or even part of it.

This one is good to go. Thank You

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/92681705-5320de00-f369-11ea-899a-4248c7835481.png)

![image](https://user-images.githubusercontent.com/55895538/92681728-65028100-f369-11ea-99a3-4cf78fb31e98.png)

**Comment by sandhiyakavi** [comment]
Verified on Production.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/92720358-736b8f80-f39f-11ea-945a-e06afadef05a.png)

![image](https://user-images.githubusercontent.com/55895538/92720525-af065980-f39f-11ea-83c5-45cc99d5edff.png)
