### ISSUE TITLE
OG meta tags for Thrive pages

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4887]
Should be fixed:
Article page:
- title
- description
- og:title
- og:image
- og:description
- twitter:description
- twitter:image

Home page/Search page/Track page:
- title
- description
- og:title
- og:description
- twitter:description

**Comment by SathyaJayabal** [comment]
@kkartunov , I don't find the below meta tag

Article page:
`title`
Home page/Search page/Track page:
`title`

**Comment by kkartunov** [comment]
@SathyaJayabal `title` is the `<title>` in head.

**Comment by SathyaJayabal** [comment]
oh ok :)

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-09-15 at 11 43 27 AM" src="https://user-images.githubusercontent.com/58783823/93172723-08c4a600-f749-11ea-8d50-fa5b3b3d0b5e.png">
<img width="1440" alt="Screenshot 2020-09-15 at 11 44 29 AM" src="https://user-images.githubusercontent.com/58783823/93172736-0e21f080-f749-11ea-86bb-80a09f59b9fa.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-15 at 4 55 53 PM" src="https://user-images.githubusercontent.com/58783823/93204884-7639fc00-f774-11ea-8f86-877248006b1e.png">
<img width="1440" alt="Screenshot 2020-09-15 at 4 56 24 PM" src="https://user-images.githubusercontent.com/58783823/93204899-7cc87380-f774-11ea-9814-320c30286ab3.png">
