### ISSUE TITLE
Thrive search - no results update

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4888]
If a user types in something that we do not have, the dropdown should still appear with "no results". 

However, if the user press the return button after their query, they should be taken to the search results page, which should display a message "No results found"

**Comment by SathyaJayabal** [comment]
If a user types in something that we do not have, the dropdown appears with "no results".

However, if the user press the return button after their query, the search results page, with message message "No results found" is not displayed. The search results page keeps on loading.
<img width="1440" alt="Screenshot 2020-09-14 at 5 18 38 PM" src="https://user-images.githubusercontent.com/58783823/93082333-5fc96d00-f6ae-11ea-9d82-16a1709db239.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-09-14 at 6 27 06 PM" src="https://user-images.githubusercontent.com/58783823/93088803-049c7800-f6b8-11ea-86fb-79bbeb104419.png">

**Comment by sandhiyakavi** [comment]
Verified on staging.

![image](https://user-images.githubusercontent.com/55895538/93172725-5f8ca880-f766-11ea-99c6-b9a73b8f73c6.png)

![image](https://user-images.githubusercontent.com/55895538/93172761-6fa48800-f766-11ea-880c-fad5b10af17f.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-15 at 4 53 21 PM" src="https://user-images.githubusercontent.com/58783823/93204610-0461b280-f774-11ea-81db-d5fabfa7331f.png">
<img width="1440" alt="Screenshot 2020-09-15 at 4 53 27 PM" src="https://user-images.githubusercontent.com/58783823/93204630-0cb9ed80-f774-11ea-8719-e8e7233af002.png">
