### ISSUE TITLE
Thrive -filtering by date does not work

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4889]
Replication Steps:

1. Go to Development Category
2. Click "Show Filter"
3. Set "Begin Date" to  Jan 1, 2017 and make sure end date is present date.
4. Click "Apply Filter"
5. Notice that an article from 2009 is still displayed toward the top.

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-09-14 at 6 33 50 PM" src="https://user-images.githubusercontent.com/58783823/93089502-06b30680-f6b9-11ea-8438-5777f0a8713e.png">

**Comment by sandhiyakavi** [comment]
Verified on staging.

![image](https://user-images.githubusercontent.com/55895538/93172363-afb73b00-f765-11ea-9277-2b63fca19e30.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-15 at 4 50 38 PM" src="https://user-images.githubusercontent.com/58783823/93204367-9cab6780-f773-11ea-9624-c0ca94ee953a.png">
