### ISSUE TITLE
Clicking an article on Thrive listings still contains bad url path for new articles

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4896]
1. In Thrive search type `10 years`
2. Click on the result
3. URL is https://www.topcoder.com/thrive/articles/10%20YEARS%20OF%20PROBLEM%20WRITING:%20MY%20FAVORITE%20PROBLEMS
4. It has to be https://www.topcoder.com/thrive/articles/10-years-of-problem-writing-my-favorite-problems

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2020-09-14 at 5 24 32 PM" src="https://user-images.githubusercontent.com/58783823/93082828-3826d480-f6af-11ea-8c1d-b563d3830ced.png">

**Comment by sandhiyakavi** [comment]
Verified on staging.

![image](https://user-images.githubusercontent.com/55895538/93168608-4253dc00-f75e-11ea-94ac-5b4418b49ed4.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-15 at 4 54 31 PM" src="https://user-images.githubusercontent.com/58783823/93204716-3115ca00-f774-11ea-9216-6317821d11c4.png">
