### ISSUE TITLE
TCO21 Algo leaderboard fix

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#4897]
https://tco21.topcoder.com/competition-overview/algorithm/leaderboard

Should display `TOTAL SCORE` properly.
Rename `# OF CHALLENGES` to `# OF MATCHES`

**Comment by SathyaJayabal** [comment]
@kkartunov ,
1. Total score should be updated the top  3 cards too
2. Rename # OF CHALLENGES to # OF MATCHES on top 3 cards too

<img width="1440" alt="Screenshot 2020-11-04 at 11 42 21 AM" src="https://user-images.githubusercontent.com/58783823/98075708-db67bf00-1e92-11eb-9466-5ef55bdaacc0.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-04 at 1 59 32 PM" src="https://user-images.githubusercontent.com/58783823/98087445-16272280-1ea6-11eb-91a4-0761244c05ca.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-10 at 1 13 06 PM" src="https://user-images.githubusercontent.com/58783823/98644503-90e4b780-2356-11eb-93e7-e387798a7968.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-10 at 7 58 50 PM" src="https://user-images.githubusercontent.com/58783823/98687004-3ddb2680-238f-11eb-98cb-e15d9503e72a.png">
