### ISSUE TITLE
Code Challenge should display the latest submission

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#4906]
If a user uploads multiple submissions in a code challenge, only the the latest one is retained in OR.
The rest of the submissions are marked as deleted.

Front end should have the same logic, to keep artefacts consistent.

**Comment by Oanh-and-only-Oanh** [comment]
closing this ticket as this issue will be resolved along with this https://github.com/topcoder-platform/community-app/issues/4527
