### ISSUE TITLE
[$25] The spacer shouldn't be right up against the number - needs spacing

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4929]
Issue: 
there is a spacing issue.
![image](https://user-images.githubusercontent.com/47536078/93234798-9a281e00-f731-11ea-99c7-95d72fe3a3ed.png)

Expected behavior:
The spacer shouldn't be right up against the number - needs spacing

**Comment by Oanh-and-only-Oanh** [comment]
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to:

https://github.com/topcoder-platform/community-app/tree/milestone-20200924
https://github.com/topcoder-platform/topcoder-react-lib/tree/milestone-20200924

run npm run test before PR

**Comment by cagdas001** [comment]
PR: #4930

**Comment by sandhiyakavi** [comment]
Verified.Working as Expected.

![image](https://user-images.githubusercontent.com/55895538/93423679-7d3a4900-f8f1-11ea-859b-fb24ce3243eb.png)

**Comment by sandhiyakavi** [comment]
Verified on staging.

![image](https://user-images.githubusercontent.com/55895538/93447153-0f9c1600-f90d-11ea-9e8a-f3a27e44acc8.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-09-17 at 6 03 57 PM" src="https://user-images.githubusercontent.com/58783823/93470870-2ee87280-f910-11ea-992e-de8d666b1606.png">

**Comment by cagdas001** [comment]
@SathyaJayabal There is no payment task for this issue

**Comment by SathyaJayabal** [comment]
reopening for payment processing

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @sushilshinde , the TCX challenge was not created for this ticket. Can you please take a look?

**Comment by Oanh-and-only-Oanh** [comment]
@cagdas001, I'm going to post payment to you via a private Task for this ticket.
