### ISSUE TITLE
Challenge details page -> Registrants tab: Some of the handles are repeated twice

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#4932]
**Describe the bug**
Some of the registrants are shown twice
**To Reproduce**
1. Go to challenge details page (ex: https://www.topcoder.com/challenges/6d33bded-9b76-44ce-b478-994dd2f9b26b?tab=registrants )
2. Check that some of the registrants handles are repeated twice and thus showing an increased total count

**Expected behavior**
Registrants list should be unique

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/93257171-1bc38e80-f7ba-11ea-80d5-991435cb333d.png)

![image](https://user-images.githubusercontent.com/5114190/93257348-53cad180-f7ba-11ea-94b4-ba104b615062.png)

**Comment by nithyaasworld** [comment]
![image](https://user-images.githubusercontent.com/5114190/93257948-44985380-f7bb-11ea-96c7-968f8ded8b4b.png)

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @SathyaJayabal, is this a duplicate of another ticket?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , yes this is a duplicate
https://github.com/topcoder-platform/challenge-api/issues/265

**Comment by Oanh-and-only-Oanh** [comment]
reopening so we can track this ticket on the Front-end

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/challenge-api/issues/265#issuecomment-694413390
