### ISSUE TITLE
Need to test this PR for "New Auth Flow"

### ISSUE THREAD

**Issue by sachin-maheshwari** [topcoder-platform/community-app#4937]
PR - https://github.com/topcoder-platform/community-app/pull/4935 

Expecting following functionalities need to be tested - 

- Login 
- Logout 
- Refresh Token
- Zurich 
- Topgear

**Comment by Oanh-and-only-Oanh** [comment]
@lakshmiathreya @SathyaJayabal @sandhiyakavi FYI

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues  please discuss with @sushilshinde. I already discussed my plan with him.

**Comment by sachin-maheshwari** [comment]
<img width="1453" alt="Screenshot 2020-09-16 at 9 23 17 PM" src="https://user-images.githubusercontent.com/6467888/93361794-e0c96580-f862-11ea-9a0e-15bba535529f.png">
I think existing issue, Topgear - Return url is null.

**Comment by sachin-maheshwari** [comment]
<img width="1161" alt="Screenshot 2020-09-16 at 9 26 52 PM" src="https://user-images.githubusercontent.com/6467888/93362243-63eabb80-f863-11ea-882d-b26d6338e3d1.png">
Know issue - I didn't find this forbidden page to change the link url "Register or Login here" . Same for Topgear.

**Comment by Oanh-and-only-Oanh** [comment]
Known issue- https://github.com/topcoder-platform/community-app/issues/4931. Need to resolve as well as part of the new flow.

**Comment by luizrrodrigues** [comment]
@sushilshinde @sachin-maheshwari This is Ready for QA in QA env, right?

**Comment by sushilshinde** [comment]
Yes.
