### ISSUE TITLE
Not Logged in user: Clicking on forums link takes the user to the old login form

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4955]
1. click on forums link in the header or footer
2. User  is taken to the old login form
https://accounts.topcoder-dev.com/member

expected:
User must be redirected to the new Auth0 login
https://accounts-auth0.topcoder-dev.com/
[forum.mov.zip](https://github.com/topcoder-platform/community-app/files/5244633/forum.mov.zip)
<img width="1440" alt="Screenshot 2020-09-18 at 2 49 32 PM" src="https://user-images.githubusercontent.com/58783823/93581071-441bda80-f9be-11ea-8cc4-9a638e7f3f78.png">

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  As i checked in recorded video your were using "http". Please use https and reverify. HTTP is know issue.

**Comment by SathyaJayabal** [comment]
tracked here
https://github.com/topcoder-platform/tc-auth-lib/issues/12
