### ISSUE TITLE
Accessing the Auth0 page directly does not open the login popup

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4956]
1. Access the Auth0 page directly.
actual: Login popup not displayed
expected: Accessing the Auth0 page directly, must open the login popup and redirect to topcoder home page after login
https://accounts-auth0.topcoder-dev.com/
<img width="1440" alt="Screenshot 2020-09-18 at 2 55 01 PM" src="https://user-images.githubusercontent.com/58783823/93581569-f489de80-f9be-11ea-9143-f8c60bd6944e.png">

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  That is designed as such. We can move it from here and file here - https://github.com/topcoder-platform/tc-auth-lib

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari If it is designed as such, can we close it?

**Comment by sachin-maheshwari** [comment]
Before closing please report at here -  https://github.com/topcoder-platform/tc-auth-lib for further discussion. This is general behavior so will discuss there only.

**Comment by SathyaJayabal** [comment]
tracking here
https://github.com/topcoder-platform/tc-auth-lib/issues/10
