### ISSUE TITLE
Console error on all pages

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4957]
The following console error on all pages
<img width="1440" alt="Screenshot 2020-09-18 at 5 28 09 PM" src="https://user-images.githubusercontent.com/58783823/93595132-cfa06600-f9d4-11ea-8007-07812b9de3ba.png">

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal that was due to protocol "http" for https it is working.

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , so will it be fixed for `http` ?

**Comment by sachin-maheshwari** [comment]
From intra level we'll fix this.  "New login" will not work on HTTP.

**Comment by SathyaJayabal** [comment]
tracked here
https://github.com/topcoder-platform/tc-auth-lib/issues/11
