### ISSUE TITLE
Challenge listing's loading with a flickering image even after reaching the end of the list.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4963]
Description:
Challenge listing's loading with a flickering image even after reaching the end of the list.

Steps to Reproduce:
1. Click My Challenges link in the right side menu bar.

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/93741880-25208100-fc28-11ea-9678-706e1fcd4ccd.png)
[Challenge_listing_loading_issue.zip](https://github.com/topcoder-platform/community-app/files/5253946/Challenge_listing_loading_issue.zip)

**Comment by SathyaJayabal** [comment]
Even after he last challenges are retrieved, the FE keeps calling the api.
[api calls.mov.zip](https://github.com/topcoder-platform/community-app/files/5256219/api.calls.mov.zip)

**Comment by sushilshinde** [comment]
@LieutenantRoger PR?

**Comment by LieutenantRoger** [comment]
@sushilshinde  I have submitted the code to the branch `feature-refactor-challengelist-fixes` directly per the instruction in the slack.

**Comment by LieutenantRoger** [comment]
PR is here: https://github.com/topcoder-platform/community-app/pull/4993

**Comment by SathyaJayabal** [comment]
Verified
<img width="1440" alt="Screenshot 2020-09-24 at 9 18 15 AM" src="https://user-images.githubusercontent.com/58783823/94098761-f6ccbc80-fe46-11ea-8d12-4a8e93062316.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-10-05 at 3 07 48 PM" src="https://user-images.githubusercontent.com/58783823/95063884-8f531e80-071c-11eb-99fa-f704153c7a47.png">
