### ISSUE TITLE
Challenge details page displaying a blank screen

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4965]
Description:

Challenge details page displaying a blank screen

![image](https://user-images.githubusercontent.com/55895538/93746902-d5928300-fc30-11ea-83cb-fdb7ac491e6e.png)

**Comment by LieutenantRoger** [comment]
The PRs:

**Comment by luizrrodrigues** [comment]
@LieutenantRoger I see changes done in **community-app** and I think need first this one too:
https://github.com/topcoder-platform/topcoder-react-lib/commit/d7e336ea391ebf3c950cf09f999a48a00db7402a#r42801128

After change lib need make sure to update all components using that lib. 

-----

@sushilshinde We good to comment a lot of code block instead remove?
https://github.com/topcoder-platform/community-app/pull/5008#discussion_r496306776

**Comment by mtwomey** [comment]
What's needed on this one to proceed @luizrrodrigues ?

**Comment by luizrrodrigues** [comment]
@mtwomey vars was changed **topcoder-react-lib**, but this not changed in all places in **community-app**, so some places will broken if not reflect the changes done in lib.

Changes in lib:
```
export const COMPETITION_TRACKS = {
  DATA_SCIENCE: 'Data Science',
  DESIGN: 'Design',
  DEVELOP: 'Development',
  QA: 'Quality Assurance',
}
```

to 

```
export const COMPETITION_TRACKS = {
  DS: 'Data Science',           <===
  DES: 'Design',                <===
  DEV: 'Development',           <===
  QA: 'Quality Assurance',
}
```

So need make sure all ref to `COMPETITION_TRACKS.DATA_SCIENCE`, `COMPETITION_TRACKS.DESIGN` and `COMPETITION_TRACKS.DEVELOP` was changed to `COMPETITION_TRACKS.DS`, `COMPETITION_TRACKS.DES` and `COMPETITION_TRACKS.DEV` respectively

**Comment by mtwomey** [comment]
@luizrrodrigues Do you know why this was changed in the lib? Should we change it back for now, or should we just update the refs?

**Comment by luizrrodrigues** [comment]
@mtwomey This looks like unnecessary change.

@LieutenantRoger Can you share why was need that change in lib?

**Comment by LieutenantRoger** [comment]
I remember I need to send the tracks related parameter when fetching V5 API, the value I changed are the ones used in the V5 API. 
I made the change so I don't need do the conversion when calling the API.

**Comment by sushilshinde** [comment]
I had a chat with @LieutenantRoger he will make necessary changes to community-app

**Comment by LieutenantRoger** [comment]
@luizrrodrigues  I have updated the PR. The change is to align with the V5 challenge api filter naming.

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2020-10-01 at 10 37 54 AM" src="https://user-images.githubusercontent.com/58783823/94770404-30b33b00-03d2-11eb-82c5-88a03911ce13.png">
