### ISSUE TITLE
Blank screen displayed on clicking the Technology tags in the Challenge listings and Details pages

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4967]
Description:
Blank screen displayed on clicking the Technology tags in the Challenge listings page

steps to Reproduce:
1. Go to Challenge listings page.
2. Click a technology tag displayed below a challenge listed.

Expected Result:
Challenges should be filtered (according the particular technology) and listed.

Screenshot:

<img width="958" alt="Filter_by_technology tag" src="https://user-images.githubusercontent.com/55895538/93749351-c1e91b80-fc34-11ea-9eef-feb0c52e54ec.png">

Video:
[Filter_by_technology.zip](https://github.com/topcoder-platform/community-app/files/5254376/Filter_by_technology.zip)

**Comment by sandhiyakavi** [comment]
@LieutenantRoger : Filtering the challenges according to the keyword (Technology) is not working.

![image](https://user-images.githubusercontent.com/55895538/93844736-2fe71e80-fcd9-11ea-94da-71fd3e0053f8.png)

video:

[Keyword_filter_Fails.zip](https://github.com/topcoder-platform/community-app/files/5259205/Keyword_filter_Fails.zip)

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , when I search by keywords I see more number of challenges
<img width="1440" alt="Screenshot 2020-09-22 at 10 27 10 AM" src="https://user-images.githubusercontent.com/58783823/93845417-5a77ae00-fcbe-11ea-9248-9fac2eeb0f34.png">
<img width="1440" alt="Screenshot 2020-09-22 at 10 27 38 AM" src="https://user-images.githubusercontent.com/58783823/93845424-61062580-fcbe-11ea-9ac3-fcfaf84a177a.png">

**Comment by LieutenantRoger** [comment]
@SathyaJayabal  Are you sure the staging is deploying my code ?  Please see the staging when I have Other as the filter, it looked like this: https://take.ms/vJaTs

And in my local, before filter:

https://take.ms/h1l3Z

After filter

https://take.ms/b4W6b

**Comment by LieutenantRoger** [comment]
@SathyaJayabal  Please double check based on the snapshots I provided above.

**Comment by LieutenantRoger** [comment]
@sushilshinde

**Comment by LieutenantRoger** [comment]
> @LieutenantRoger : Filtering the challenges according to the keyword (Technology) is not working.
> 
> ![image](https://user-images.githubusercontent.com/55895538/93844736-2fe71e80-fcd9-11ea-94da-71fd3e0053f8.png)
> 
> video:
> 
> [Keyword_filter_Fails.zip](https://github.com/topcoder-platform/community-app/files/5259205/Keyword_filter_Fails.zip)


The keyword under `dev` environment is working as expected.
I couldn't find `TypeScript` keyword under `dev` environment,  please better provide the API request sent as well

Have you tried otherwise keywords ?  This is very possibly due to the API issue.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger looks like API issue:

Call (without tags): https://api.topcoder-dev.com/v5/challenges/?status=Active&isLightweight=true&perPage=1&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA

no auth: 560
**with auth: 560**

-------

Cal (with tags)l: https://api.topcoder-dev.com/v5/challenges/?status=Active&isLightweight=true&perPage=1&tags[]=Java&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA

no auth: 26
**with auth: 563**

cc @SathyaJayabal

**Comment by LieutenantRoger** [comment]
@luizrrodrigues needs to add `API Issues` label in this case.

**Comment by ThomasKranitsas** [comment]
With Auth:
<img width="1104" alt="Screenshot 2020-09-24 at 5 38 26 PM" src="https://user-images.githubusercontent.com/4612921/94159910-c576df80-fe8c-11ea-91d7-bd198fb0fedd.png">
Without Auth:
<img width="1105" alt="Screenshot 2020-09-24 at 5 38 11 PM" src="https://user-images.githubusercontent.com/4612921/94159921-c871d000-fe8c-11ea-9e79-05b9cea1af32.png">

Seems to be working fine. Please provide the cURL you're using if you still think it's an API issue.

**Comment by Oanh-and-only-Oanh** [comment]
@sushilshinde @luizrrodrigues, is this still an API issue?

**Comment by rootelement** [comment]
Testing on this environment, every tag I clicked on works fine.
https://test-community-app.topcoder-dev.com/challenges

**Comment by SathyaJayabal** [comment]
@rootelement , it is not working in staging. 
Please check here the current deployment statuses
https://community-app-dev-dashboard.herokuapp.com/#/dashboard

See screenshots for example.
<img width="1440" alt="Screenshot 2020-09-29 at 11 59 54 AM" src="https://user-images.githubusercontent.com/58783823/94521298-6f6ab900-024b-11eb-9140-7578025dfb49.png">

<img width="1440" alt="Screenshot 2020-09-29 at 11 58 19 AM" src="https://user-images.githubusercontent.com/58783823/94521284-6974d800-024b-11eb-97a3-6bc4362426a9.png">

**Comment by rootelement** [comment]
@ThomasKranitsas  I don't understand what's going on here... The query with tags looks like this:
```javascript
if (criteria.tags) {
    if (criteria.includeAllTags) {
      for (const tag of criteria.tags) {
        boolQuery.push({ match_phrase: { tags: tag } })
      }
    } else {
      for (const tag of criteria.tags) {
        shouldQuery.push({ match: { tags: tag } })
      }
    }
  }
```

Should that second shouldQuery be `match_phrase` as well?

If I query from postman with my jwt in prod, i get:
`https://api.topcoder.com/v5/challenges/?status=Active&tags[]=3D%20Reconstruction&isLightweight=true&tracks[]=Des&tracks[]=Dev&tracks[]=QA&tracks[]=DS`
<img width="357" alt="Screen Shot 2020-09-29 at 11 12 56 AM" src="https://user-images.githubusercontent.com/5400156/94577568-be612000-0244-11eb-9cf9-fa09b6bdb11f.png">

If I query the same with a jwt from a non-privileged user in prod (jcori_arena), i get 91 items, and they're coming back without the tag in the tags array (example ID: `26416dcb-17f0-45be-9ad0-0517b6f0c743`)
<img width="396" alt="Screen Shot 2020-09-29 at 11 15 29 AM" src="https://user-images.githubusercontent.com/5400156/94578028-37f90e00-0245-11eb-8220-f8bd20c3fade.png">

<img width="171" alt="Screen Shot 2020-09-29 at 11 16 16 AM" src="https://user-images.githubusercontent.com/5400156/94578041-3c252b80-0245-11eb-9d11-58ac21151dad.png">

**Comment by rootelement** [comment]
@ThomasKranitsas this is the built ES query from the server logs. 
A couple things I noticed.
1. I tried to use the `includeAllTags` flag to see if match_phrase would fix it. I see `includeAllTags` included in the built ES query.
2. Even if I remove it and run this against prod, i get 0 results. I'm not sure if it's the way the tags are searched for or if it's the task debacle at the top that's causing issues.


```
{
    "query": {
        "bool": {
            "must": [
                {
                    "bool": {
                        "should": [
                            {
                                "bool": {
                                    "must_not": {
                                        "exists": {
                                            "field": "task.isTask"
                                        }
                                    }
                                }
                            },
                            {
                                "match_phrase": {
                                    "task.isTask": false
                                }
                            },
                            {
                                "bool": {
                                    "must": [
                                        {
                                            "match_phrase": {
                                                "task.isTask": true
                                            }
                                        },
                                        {
                                            "match_phrase": {
                                                "task.isAssigned": false
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "match_phrase": {
                                    "task.memberId": "40061596"
                                }
                            }
                        ]
                    }
                },
                {
                    "bool": {
                        "should": [
                            {
                                "bool": {
                                    "must_not": {
                                        "exists": {
                                            "field": "groups"
                                        }
                                    }
                                }
                            }
                        ]
                    }
                },
                {
                    "bool": {
                        "filter": [
                            {
                                "match_phrase": {
                                    "status": "Active"
                                }
                            },
                            {
                                "match_phrase": {
                                    "includeAllTags": "true"
                                }
                            },
                            {
                                "bool": {
                                    "should": [
                                        {
                                            "match_phrase": {
                                                "trackId": "5fa04185-041f-49a6-bfd1-fe82533cd6c8"
                                            }
                                        },
                                        {
                                            "match_phrase": {
                                                "trackId": "9b6fc876-f4d9-4ccb-9dfd-419247628825"
                                            }
                                        },
                                        {
                                            "match_phrase": {
                                                "trackId": "36e6a8d0-7e1e-4608-a673-64279d99c115"
                                            }
                                        },
                                        {
                                            "match_phrase": {
                                                "trackId": "c0f5d461-8219-4c14-878a-c3a3f356466d"
                                            }
                                        }
                                    ]
                                }
                            },
                            {
                                "match_phrase": {
                                    "tags": "Heroku"
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "sort": [
        {
            "created": {
                "order": "desc",
                "missing": "_last",
                "unmapped_type": "String"
            }
        }
    ]
}
```

If I run this query, I get 1 result back:
```
{
    "query": {
        "bool": {
            "must": [
                {
                    "match_phrase": {
                        "status": "Active"
                    }
                },
                {
                    "match_phrase": {
                        "tags": "3D Reconstruction"
                    }
                }
            ]
        }
    }
}
```

**Comment by SathyaJayabal** [comment]
reducing the priority as the blank screen issue is resolved

**Comment by rootelement** [comment]
We're testing a fix to the search difference in dev currently. The tags issue _should_ be fixed, but we will report back in a bit.

**Comment by rootelement** [comment]
It seems to be working well in dev. This will be queued for release shortly. The ability to type in the search box and filter on tags is a new feature request, and has been opened on the challenge api repo as a separate topic.

**Comment by Oanh-and-only-Oanh** [comment]
@rootelement, the new feature request, is 1) the ability to type in search box and match on "Challenge title" and "tags". 2) However, we also want the ability to display list of challenges with a specific tag if a "tag" is selected from the Challenge Listings page or Details page. I believe, this is second point refers to this ticket.

**Comment by rootelement** [comment]
Yes, and that's what I said is done and working. so this ticket is solved.

**Comment by SathyaJayabal** [comment]
@rootelement , let us know when the tags fix is released to prod.

**Comment by sandhiyakavi** [comment]
Verified on staging.

![image](https://user-images.githubusercontent.com/55895538/95544873-53c79580-0a37-11eb-80a1-128a5d4d0da9.png)

[challengedetail_keywordfilter.zip](https://github.com/topcoder-platform/community-app/files/5352649/challengedetail_keywordfilter.zip)
