### ISSUE TITLE
Blank screen displayed on challenge listing if not logged in.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#4968]
Description:
Blank screen displayed on challenge listing if not logged in.

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/93751194-a7647180-fc37-11ea-91cd-f5452b6af149.png)

![image](https://user-images.githubusercontent.com/55895538/93751260-c400a980-fc37-11ea-8352-065613eaec71.png)

**Comment by sandhiyakavi** [comment]
Verified. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/93844295-a8e57680-fcd7-11ea-9f2b-404a1ea55c12.png)

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-10-05 at 3 16 54 PM" src="https://user-images.githubusercontent.com/58783823/95064762-d261c180-071d-11eb-8922-4ec3f7799b4a.png">
