### ISSUE TITLE
[$40] Topgear Logout: Return url is Null

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4969]
Topgear Logout: Return url is Null
Clicking on logout, displays the below page. This is due to the return url being null.

<img width="1440" alt="Screenshot 2020-09-21 at 7 07 40 PM" src="https://user-images.githubusercontent.com/58783823/93773771-193fb980-fc3e-11ea-9859-08606eaeaf2b.png">
<img width="1440" alt="Screenshot 2020-09-21 at 7 09 21 PM" src="https://user-images.githubusercontent.com/58783823/93773784-1f359a80-fc3e-11ea-879b-ec09aab592c9.png">

**Comment by Oanh-and-only-Oanh** [comment]
Please update so if user logs out of Topgear, reroute the user to https://accounts.topcoder.com/member

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this is fixed now.
[topgear logout.mov.zip](https://github.com/topcoder-platform/community-app/files/5627047/topgear.logout.mov.zip)
