### ISSUE TITLE
Update forbidden page login link for subcommunities

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4970]
Update the login link for the forbidden pages for the sub communities. This page is displayed when the user is logged and access the sub community page they are not a member of
https://community-app.topcoder.com/__community__/zurich/forbidden
<img width="1440" alt="Screenshot 2020-09-21 at 7 21 05 PM" src="https://user-images.githubusercontent.com/58783823/93775092-a0d9f800-fc3f-11ea-8f2d-c44f14d999cb.png">

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues this is known issue which i mentioned in mater ticket https://github.com/topcoder-platform/community-app/issues/4937. Please fix.

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues please make sure for all community too.

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari I think this page coming from Contentful, @kkartunov can you confirm that please?

**Comment by sachin-maheshwari** [comment]
@sushilshinde i am not sure about Contentful. Expert advice needed here :)

**Comment by sushilshinde** [comment]
@kkartunov

**Comment by kkartunov** [comment]
Yep, Contentful content it is. Post the link and I will update it...@SathyaJayabal 
cc @luizrrodrigues @sushilshinde

**Comment by luizrrodrigues** [comment]
@kkartunov 

`${config.URL.AUTH}?utm_source=CURRENTLY_PAGE&retUrl=RETURN_PAGE`

**Comment by kkartunov** [comment]
> @kkartunov
> 
> `${config.URL.AUTH}?utm_source=CURRENTLY_PAGE&retUrl=RETURN_PAGE`

@luizrrodrigues there is no access to `config` from static content like Contentful text block. This what you propose is not working. Url has to be a static link.

**Comment by luizrrodrigues** [comment]
@kkartunov okay, I'll share static URL shortly, but in this case if we click in login in Dev env, we'll redirect to Prod login?

**Comment by kkartunov** [comment]
> @kkartunov okay, I'll share static URL shortly, but in this case if we click in login in Dev env, we'll redirect to Prod login?

Unfortunately yes

**Comment by luizrrodrigues** [comment]
@kkartunov 

need change from 

```
https://accounts.topcoder.com/sso-login/?retUrl=https://zurich.topcoder.com?utm_source=zurich
```

to 

```
https://accounts-auth0.topcoder.com/?retUrl=https://zurich.topcoder.com?utm_source=zurich
```

**Comment by kkartunov** [comment]
@SathyaJayabal I updated the link as per @luizrrodrigues post. Please, verify and close. Thanks

cc @sachin-maheshwari

**Comment by luizrrodrigues** [comment]
@SathyaJayabal any feedback in this one?

**Comment by SathyaJayabal** [comment]
@luizrrodrigues ,this one has to be done from contentful directly  on production after release. Will test and close after release.

**Comment by SathyaJayabal** [comment]
@kkartunov @sushilshinde @luizrrodrigues , forbidden page links to be updated
https://community-app.topcoder.com/__community__/zurich/forbidden
https://community-app.topcoder.com/__community__/cs/forbidden
https://community-app.topcoder.com/__community__/comcast/forbidden

The login and register url needs to be updated to the new auth0 urls, example for zurich is here
https://github.com/topcoder-platform/community-app/issues/4970#issuecomment-709440144

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , can u provide the example url for CS register

**Comment by luizrrodrigues** [comment]
@SathyaJayabal We going to use same link to login for now and fix that to show Register tab by default after release: https://github.com/topcoder-platform/community-app/issues/5101#issuecomment-714250299

Zurich: https://accounts-auth0.topcoder.com/?retUrl=https://zurich.topcoder.com&utm_source=zurich
CS: https://accounts-auth0.topcoder.com/?retUrl=https://cs.topcoder.com&utm_source=cs
Comcast: https://accounts-auth0.topcoder.com/?retUrl=https:://cs.topcoder.com&utm_source=cs

**Comment by SathyaJayabal** [comment]
> @SathyaJayabal We going to use same link to login for now and fix that to show Register tab by default after release: [#5101 (comment)](https://github.com/topcoder-platform/community-app/issues/5101#issuecomment-714250299)
> 
> Zurich: https://accounts-auth0.topcoder.com/?retUrl=https://zurich.topcoder.com&utm_source=zurich
> CS: https://accounts-auth0.topcoder.com/?retUrl=https://cs.topcoder.com&utm_source=cs
> Comcast: https://accounts-auth0.topcoder.com/?retUrl=https:://cs.topcoder.com&utm_source=cs

@luizrrodrigues , i think comcast link is wrong and has not been updated to comcast from cs (issue existing on prod too too)

**Comment by luizrrodrigues** [comment]
Let me check in source files

**Comment by luizrrodrigues** [comment]
@SathyaJayabal @kkartunov 
Comcast: https://accounts-auth0.topcoder.com/?retUrl=http://comcast.topcoder.com&utm_source=comcast

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-02 at 2 26 34 PM" src="https://user-images.githubusercontent.com/58783823/97848699-776cbb80-1d17-11eb-949f-bb09a0a220b4.png">
