### ISSUE TITLE
Subcommunity Filter: Unable to select TCO20 and TCO21

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4976]
Subcommunity Filter: Unable to select TCO20 and TCO21 from the subcommunity dropdown

[TCO20.mov.zip](https://github.com/topcoder-platform/community-app/files/5256183/TCO20.mov.zip)

**Comment by LieutenantRoger** [comment]
This appears to be the `TCO20` and `TCO21` are not returning the groupIds,  when I couldn't find an groupId, I made it to select 'All'

This could be relevant with the groupIds enhancements feature.

**Comment by LieutenantRoger** [comment]
Verified that `dev` environment doesn't have TCO20 and TCO21 groups.  Discussing whether we can create them in `dev` environment directly

**Comment by LieutenantRoger** [comment]
I have made necessary change at community-app, so once a domain doesn't have a groupId, I will not show it in the `Sub Community` dropdown list.  `tco20` and `tco21` happens to be this case.

**Comment by LieutenantRoger** [comment]
Here's the PR: https://github.com/topcoder-platform/community-app/pull/5031

1. Restore the groupIds per discussion in the slack channel
2. Hide the community without a groupId, instead of showing them in the dropdown list. So you won't be able to see `tco20` and `tco21` now.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Looks like add unnecessary `hidden: true` to meta data: https://github.com/topcoder-platform/community-app/compare/develop...listing-develop-sync

**Comment by LieutenantRoger** [comment]
They are expected per discussion with @Oanh-and-only-Oanh  in the slack.  

Actually we should only show `tco21` but `tco21` doesn't have groupId, so I fall back to show only `tco19` for demonstration purpose.  Once the `tco21` has valid groupIds returned, we can switch `tco19` back to `tco21`

**Comment by LieutenantRoger** [comment]
Here's the link in the slack for it. https://topcoder.slack.com/archives/G018ZDY3G7L/p1601488642040400?thread_ts=1601483416.038200&cid=G018ZDY3G7L

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Insteaad `hidden: true` use `hideSearch: true`

**Comment by LieutenantRoger** [comment]
I thought `hidden` is used to `hide` a group,  where the `hideSearch` is used ?

**Comment by luizrrodrigues** [comment]
@LieutenantRoger sorry, ignore. `hideSearch` will hide just search icon from header. 

`hidden` looks right one, but have an issue when navigate from listing page to dashboard.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , by default we should have an `all` option that should be selected. 
1. go to listings page
2. click on dashboard, we get a blank page
3.Go to listings
4. select tco19 from sub communities filter
5, go to dashboard, dashboard is displayed properly.

**Comment by LieutenantRoger** [comment]
I will take a look at the `all` option.  

Dashboard page I think you meant this ticket, right ? https://github.com/topcoder-platform/community-app/issues/5049

It's another ticket.

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , yes dashboard page is #5049 , but looks like that is only happening when we don't select any sub communities on listings page. Otherwise accessing dashboard directly works. Selecting any subcommunity from listings filter dropdown and then accessing dashboard also works. So I think #5049 is related to this ticket.

**Comment by LieutenantRoger** [comment]
ok, let me take a look

**Comment by LieutenantRoger** [comment]
Here's the PR for the `All` option fix: https://github.com/topcoder-platform/community-app/pull/5052

**Comment by luizrrodrigues** [comment]
@SathyaJayabal New requirement related with this one: https://github.com/topcoder-platform/community-app/issues/5056

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , lets close this one and track the sub community filter on #5056
