### ISSUE TITLE
Open for Review count is empty

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4979]
**Describe the bug**
"Open for Review" bucket does not have a count even when there are available challenges 

Steps to Reproduce:

1. Click Open for Review link
2. See screenshot
![image](https://user-images.githubusercontent.com/47536078/93795068-c4745280-fbed-11ea-9ebd-083c29b9aee8.png)

**Comment by LieutenantRoger** [comment]
@Oanh-and-only-Oanh   `Open For Review bucket` doesn't have count before as well.

**Comment by Oanh-and-only-Oanh** [comment]
@LieutenantRoger reprioritizing this ticket then to P4. A count would be nice but because this is a new thing, we can hold off for now.

**Comment by LieutenantRoger** [comment]
@Oanh-and-only-Oanh  Based on current fetching challenge logic, we won't know the number until 
1. we open up the `Open For Review` bucket 
2. wait for the requests to fetch the `review opportunities` complete.

So I think this is not feasible requirement with our current setup.

**Comment by Oanh-and-only-Oanh** [comment]
Closing due to feasibility assessment
