### ISSUE TITLE
All Challenges and Ongoing Challenges count is incorrect and Ongoing Challenges does not return all Ongoing Challenges

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4980]
**Bug:**
The count on the All Challenges filter is not accurate.

**How to reproduce:**
1. go to https://staging-community-app.topcoder.com/challenges?
2. Turn off all track filters except for QA track
3. click on All Challenges filter 
3. See that count is 22 but only 2 challenges show
![image](https://user-images.githubusercontent.com/47536078/93828771-e3d8a300-fc20-11ea-8757-0d6f711d1095.png)

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , the ongoing challenges bucket is missing some of the challenges
example when u filter by few tracks. See comparison with prod
<img width="1440" alt="Screenshot 2020-09-22 at 9 42 18 AM" src="https://user-images.githubusercontent.com/58783823/93843581-f0f4a100-fcb7-11ea-9fc1-237a59520b70.png">
<img width="1440" alt="Screenshot 2020-09-22 at 9 42 21 AM" src="https://user-images.githubusercontent.com/58783823/93843590-f651eb80-fcb7-11ea-963d-4c28e78886e7.png">

**Comment by LieutenantRoger** [comment]
@rootelement 

Could you take a look if I have used the correct filter when fetching challenge data

'All Challenges' count: `Request URL: https://api.topcoder-dev.com/v5/challenges/?status=Active&isLightweight=true&perPage=1&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA`

'Ongoing Challenges':  `Request URL: https://api.topcoder-dev.com/v5/challenges/?status=Active&currentPhaseName=Submission&perPage=10&page=1&sortBy=updated&sortOrder=desc&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA`


The count numbers are retrieved from the response `x-total` field.

**Comment by rootelement** [comment]
That looks fine, but you don't need to include the tracks if you want them all on... unless that's an artifact of the switches in the ui. Either way is fine.

**Comment by rootelement** [comment]
The second query you could use `isLightweight` and only retrieve 1 like you are in the first one for it to be faster, but that's also not required.

**Comment by LieutenantRoger** [comment]
@rootelement the second query will retrieve the 10 ongoing challenge, and the `total ongoing challenge` as well, so need to use `perPage=10`  :) 

@Oanh-and-only-Oanh @rootelement ,I believe there are some gaps between server side filters and client side filters(old way),  hence the discrepancy above.

**Comment by ThomasKranitsas** [comment]
Maybe this has been fixed? Buckets seem to work fine on my end
<img width="1553" alt="Screenshot 2020-10-08 at 5 41 31 PM" src="https://user-images.githubusercontent.com/4612921/95474345-aa789500-098d-11eb-99f6-032343091344.png">
<img width="1553" alt="Screenshot 2020-10-08 at 5 41 28 PM" src="https://user-images.githubusercontent.com/4612921/95474366-af3d4900-098d-11eb-9c0d-a66947fd1368.png">

**Comment by rootelement** [comment]
The decision is to remove this bucket, because it's not useful to members, and it's covered by the All Challenges bucket.

**Comment by SathyaJayabal** [comment]
Closing this- 
hiding the bucket tracked here
https://github.com/topcoder-platform/community-app/issues/5073
