### ISSUE TITLE
Add Marathon submission link to MM challenges

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#4994]
Can we add a link to https://www.topcoder.com/thrive/articles/How%20To%20Compete%20in%20a%20Marathon%20Match to every Marathon match?  Maybe put it in the sidebar?  This is important for all members to have access to when competiting in an MM.

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh 

![4994-1](https://user-images.githubusercontent.com/4476442/95946232-53a00f00-0e16-11eb-909d-3716ccaad7b3.png)
![4994-2](https://user-images.githubusercontent.com/4476442/95946235-56026900-0e16-11eb-8420-0e53055f6a54.png)
![4994-3](https://user-images.githubusercontent.com/4476442/95946238-57cc2c80-0e16-11eb-96e6-8e663a02b9b2.png)
![4994-4](https://user-images.githubusercontent.com/4476442/95946241-5864c300-0e16-11eb-91a8-58ab61d3f391.png)

Please let me know for any feedback.

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-10-15 at 11 02 20 AM" src="https://user-images.githubusercontent.com/58783823/96080963-ece22a80-0ed5-11eb-982a-668b0eb84202.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-11-03 at 2 22 58 PM" src="https://user-images.githubusercontent.com/58783823/97965712-ce8a9300-1de0-11eb-884f-2e61d109af6d.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-03 at 5 24 15 PM" src="https://user-images.githubusercontent.com/58783823/97982249-8166eb00-1df9-11eb-8d9f-abf4593f0873.png">
