### ISSUE TITLE
[$150] - Community fitler and "Save Filter" functionality

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#500]
The way "Save Filter" works now, if community filter is activated, it saves the current challenge filter implied by the community + any other filters explicitely set by user. It means that if user saves such filter, and call it e.g. `Design challenges in TopGear` and then we re-configure challenge filter in TopGear (or change user groups related to TopGear) the saved filter will become out of sync with the actual TopGear filtering (and very confusing, cause its name in such scenario claims different). Thus, it looks like saving of community filter state should be reworked.

**Comment by birdofpreyru** [comment]
### Expected Fix:
We need a good and clean solution for this. If community filtering is activated, saving filter should save the community ID, so that when the filter is applied later, using the community ID, it gets the actuall community challenge filter from the up-to-date backend response. It should also behave nicely if community ID has been changed in the backend, since the saving of the filter by user (show error message). It also should fit nicely in the current code.

**Comment by kondakovdmitry** [comment]
"Save Filter" button does not work. It throws the following error:
> Uncaught TypeError: Cannot read property 'challengeListing' of undefined
    at getAvailableFilterName (chunk.js:37816)
    at saveFilter (chunk.js:37852)

Seems like `getAvailableFilterName` expects `state` parameter, but none is provided. See here: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/containers/challenge-listing/FilterPanel.jsx#L53

**Comment by birdofpreyru** [comment]
@kondakovdmitry Yeah, you are right; an easy fix, though, just pass in the piece of state that keeps the current list of saved filters, which is kept inside the Redux state; and update `getAvailableFilterName` accordingly.

**Comment by kondakovdmitry** [comment]
PR:  #631
hash: 8f91a23

To see error message in saved filter when community ID is changed in the backend, you can change the communityId in the metadata.json file for the community.
