### ISSUE TITLE
Option for Device - Smartphone does not include Google Pixel

### ISSUE THREAD

**Issue by witcradg** [topcoder-platform/community-app#5007]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SathyaJayabal** [comment]
Please email support with the request

**Comment by SathyaJayabal** [comment]
@witcradg 

> Please email support with the request
