### ISSUE TITLE
MM Leaderboard

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5012]
This is a live mm leaderboard component. It basically checks mm challenge submissions and renders a sortable table for Rank, Handle, Score. Here score is provisional score from MMatch's submission tab. Should be following look and feel of our brand tables like:

![Screenshot 2020-10-05 12:24:06](https://user-images.githubusercontent.com/5585002/95062769-147f0900-0706-11eb-873a-84eaed8fbe55.png)

**Comment by kkartunov** [comment]
@SathyaJayabal test URL: http://qa-community-app.topcoder-dev.com/examples/contentful/contentblock/cFNLQkRNiXAutV7irFBhF

Challenge: https://www.topcoder-dev.com/challenges/2a3eda4d-c289-4a3f-a663-db09ada062ea

**Comment by SathyaJayabal** [comment]
@kkartunov , where will the leaderboard be displayed.
https://qa-community-app.topcoder-dev.com/challenges/2a3eda4d-c289-4a3f-a663-db09ada062ea
<img width="1440" alt="Screenshot 2020-10-05 at 3 36 04 PM" src="https://user-images.githubusercontent.com/58783823/95066796-806e6b00-0720-11eb-87b3-bcd5d5f260bd.png">

**Comment by kkartunov** [comment]
@SathyaJayabal 
1. In Contentful pages where it is needed
2. Fixed

**Comment by SathyaJayabal** [comment]
@kkartunov , verified 2.
<img width="1440" alt="Screenshot 2020-10-06 at 10 38 47 AM" src="https://user-images.githubusercontent.com/58783823/95161228-38068a00-07c0-11eb-80d5-7f59d439c9e2.png">

**Comment by kkartunov** [comment]
@SathyaJayabal it is not working properly on prod.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues @SathyaJayabal @kkartunov, do we need to revert or can we just continue to fix the issue with reverting?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , its not in prod yet. @kkartunov means prod backend when he tested on staging.

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-10-09 at 2 06 56 PM" src="https://user-images.githubusercontent.com/58783823/95561691-ba00e800-0a38-11eb-8107-7f4fae54fac3.png">

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-10-13 at 7 48 23 PM" src="https://user-images.githubusercontent.com/58783823/95873062-2a876c00-0d8d-11eb-8851-94f6bb91f441.png">
@kkartunov , both the 0 score and the failed score shows as -1 in the leaderboard. Is this fine?

**Comment by kkartunov** [comment]
@SathyaJayabal thanks. We will present it this way to the customer and eventually be back for corrections.

**Comment by SathyaJayabal** [comment]
@kkartunov, when provisional scores are not available, leaderboard still shows 100
<img width="1416" alt="Screenshot 2020-10-13 at 8 26 10 PM" src="https://user-images.githubusercontent.com/58783823/95878084-738def00-0d92-11eb-82d4-8109a3622164.png">

**Comment by SathyaJayabal** [comment]
Fixed: When provisional scores are not available, leaderboard shows "..."
<img width="1440" alt="Screenshot 2020-10-13 at 9 49 46 PM" src="https://user-images.githubusercontent.com/58783823/95888029-34fe3180-0d9e-11eb-92fa-66381303ffad.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-10-14 at 12 11 19 AM" src="https://user-images.githubusercontent.com/58783823/95902040-d9d63a00-0db1-11eb-8584-f467d51443d3.png">
