### ISSUE TITLE
[$50] Ongoing Challenges : End date is incorrect 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5015]
https://test-community-app.topcoder-dev.com/challenges?bucket=ongoing

The end date mentioned below the challenge name is incorrect.
<img width="1440" alt="Screenshot 2020-09-29 at 10 10 01 AM" src="https://user-images.githubusercontent.com/58783823/94513352-219a8480-023c-11eb-9e64-5cee2e8a2aec.png">

**Comment by LieutenantRoger** [comment]
Could you be more specific on why it's incorrect ?

**Comment by SathyaJayabal** [comment]
@LieutenantRoger , the actual end date of those challenges are different
<img width="1440" alt="Screenshot 2020-10-01 at 8 55 12 PM" src="https://user-images.githubusercontent.com/58783823/94830028-c2e62e00-0428-11eb-8670-1970006434f4.png">
<img width="1440" alt="Screenshot 2020-10-01 at 8 57 02 PM" src="https://user-images.githubusercontent.com/58783823/94830044-c7aae200-0428-11eb-9846-f0aed54cc580.png">

**Comment by LieutenantRoger** [comment]
I checked the link in your first snapshot, the actual challenge object returned seems having endDate 10-02.  
Do we have many `design challenge` in the database ?

**Comment by SathyaJayabal** [comment]
closing this as we do not have ongoing bucket now.
