### ISSUE TITLE
SEO 101 - fix meta description

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5016]
Currently, the community app is setting the wrong meta description tag. This is happening for **all pages**(Contentful and others).

![Screenshot 2020-09-29 10:22:41](https://user-images.githubusercontent.com/5585002/94526110-b9e53900-023d-11eb-9507-3a59d4306909.png)

`<meta poperty="description" ... >`  should change to `<meta name="description" ... >` because of SEO reasons.

This behavior is controlled by the underlined library `topcoder-react-utils` here https://github.com/topcoder-platform/topcoder-react-utils/blob/50d6622593d3e927d8b7feb03e3bb73643296631/src/shared/components/MetaTags.jsx#L34

Expected:
1. Fix the error in the library code
2. Release new version of it to npm
3. Update the community app to use that new version here https://github.com/topcoder-platform/community-app/blob/c865c7c1d983b7cb21a6a7683934a7c981defbba/package.json#L142

**Comment by Oanh-and-only-Oanh** [comment]
also related to this ticket https://github.com/topcoder-platform/community-app/issues/4544

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Ready in Stag env.

**Comment by SathyaJayabal** [comment]
verified for challenge listings page, challenge details page, member profile page, gigs page, profile settings page and thrive page
<img width="1440" alt="Screenshot 2020-11-24 at 9 38 08 AM" src="https://user-images.githubusercontent.com/58783823/100047706-2133f980-2e39-11eb-8aa5-1c91d7ba3848.png">

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
<img width="1440" alt="Screenshot 2020-11-24 at 4 37 25 PM" src="https://user-images.githubusercontent.com/58783823/100086497-83a9eb80-2e73-11eb-9506-836488fc8538.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-24 at 7 55 57 PM" src="https://user-images.githubusercontent.com/58783823/100106938-2328a780-2e8f-11eb-91f2-4db9b2526794.png">
