### ISSUE TITLE
Resolve react helmet issue

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5022]
Fix community-app SEO, currently search engines getting Title and Meta before **react-helmet** update with respective page content. We need to make sure to run **react-helmet** in server side render instead client side.

Example page: https://www.topcoder.com/challenges/48406f89-3b18-488e-bccf-b7c7e6e8dd0b 

**SSR:**
title: Topcoder

**CSR:**
title: QA Practice Challenge - Find Bugs on Topcoder

-----

Lib: https://github.com/topcoder-platform/topcoder-react-utils

branches:
https://github.com/topcoder-platform/community-app/tree/seo-fix
https://github.com/topcoder-platform/topcoder-react-utils/tree/seo-fix

-----

Challenge: https://www.topcoder.com/challenges/78711bc1-13ad-450c-ab01-18a799b6a0a2

**Comment by luizrrodrigues** [comment]
#4836

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , 
1. Still see topcoder in title but for a shorter time.  See video
[seo.mov.zip](https://github.com/topcoder-platform/community-app/files/5375608/seo.mov.zip)

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Can we track this in new issue, this happen because currently logical add a default meta to side in client side (this not affect Google engine to get meta info)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues ok

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
[seo.mov.zip](https://github.com/topcoder-platform/community-app/files/5480241/seo.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[seo_prod.mov.zip](https://github.com/topcoder-platform/community-app/files/5481034/seo_prod.mov.zip)
