### ISSUE TITLE
Add RDM Email Switch in Preferences

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5023]
Should toggle "RDM" tag in MailChimp.
Should say:
Rapid Development Match (RDM) Reminders
Receive notifications of our brand new RDMs! These rated, development matches will be a fun new way to engage with us!

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed in QA env

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-10-01 at 8 30 14 AM" src="https://user-images.githubusercontent.com/58783823/94760531-64856500-03c0-11eb-8335-3470b9006765.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-10-01 at 12 45 04 PM" src="https://user-images.githubusercontent.com/58783823/94779113-05394c00-03e4-11eb-85f3-b0473ccb6d2d.png">

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1440" alt="Screenshot 2020-10-01 at 7 34 46 PM" src="https://user-images.githubusercontent.com/58783823/94819808-51ed4900-041d-11eb-805f-c6aed9d29e73.png">
