### ISSUE TITLE
Payments text in challenge details incorrect for topgear challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5029]
Payments text in challenge details incorrect for topgear challenges
example:
https://staging-community-app.topcoder.com/challenges/a3b4d2d7-b325-4373-8045-920b8427d24f?tab=details
expected:
https://www.topcoder.com/challenges/a3b4d2d7-b325-4373-8045-920b8427d24f?tab=details

<img width="1440" alt="Screenshot 2020-10-01 at 11 23 51 AM" src="https://user-images.githubusercontent.com/58783823/94773089-b2a66280-03d8-11eb-8d96-9ddc61f6d64d.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , will this be fixed if we sync from develop?
this issue was fixed in
https://github.com/topcoder-platform/community-app/issues/4727

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yep, waiting for confirmation from @sushilshinde to run the sync with `develop`

**Comment by SathyaJayabal** [comment]
verified. fixed after sync
<img width="1440" alt="Screenshot 2020-10-05 at 3 31 06 PM" src="https://user-images.githubusercontent.com/58783823/95066456-10f87b80-0720-11eb-8ae4-9776e2c859a1.png">
