### ISSUE TITLE
TCOs Header fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5032]
- Remove Dropdown on TCOs <= 19 from the header bar
- For TCO20 only add:
  - logo+linked to home
  - login buttons as per https://marvelapp.com/prototype/5554efd/screen/66504645 for anonymous users. For logged-in users keep the profile section(at most right) similar on TCO19 https://tco19.topcoder.com/
  - Navi menu stays as it is now, unchanged. No, follow the design on that.

**Comment by SathyaJayabal** [comment]
verified
1.Remove Dropdown on TCOs <= 19 from the header bar
<img width="1398" alt="Screenshot 2020-10-19 at 11 47 03 AM" src="https://user-images.githubusercontent.com/58783823/96409484-f97ebf80-1202-11eb-958c-7a670dbbd5a0.png">
<img width="1389" alt="Screenshot 2020-10-19 at 11 47 33 AM" src="https://user-images.githubusercontent.com/58783823/96409490-fc79b000-1202-11eb-8b54-a4cf00be301d.png">
<img width="1394" alt="Screenshot 2020-10-19 at 11 48 23 AM" src="https://user-images.githubusercontent.com/58783823/96409491-fd124680-1202-11eb-8bf2-3e4492a1b19a.png">
<img width="1393" alt="Screenshot 2020-10-19 at 11 49 37 AM" src="https://user-images.githubusercontent.com/58783823/96409492-fe437380-1202-11eb-8a93-1230f0470bdb.png">
<img width="1391" alt="Screenshot 2020-10-19 at 11 49 59 AM" src="https://user-images.githubusercontent.com/58783823/96409494-fedc0a00-1202-11eb-84af-6f450cb06678.png">
<img width="1397" alt="Screenshot 2020-10-19 at 11 50 23 AM" src="https://user-images.githubusercontent.com/58783823/96409495-fedc0a00-1202-11eb-96cc-fbc22f924909.png">
<img width="1394" alt="Screenshot 2020-10-19 at 11 50 47 AM" src="https://user-images.githubusercontent.com/58783823/96409496-000d3700-1203-11eb-8901-cd37a78e8289.png">
<img width="1400" alt="Screenshot 2020-10-19 at 11 51 12 AM" src="https://user-images.githubusercontent.com/58783823/96409499-00a5cd80-1203-11eb-86ad-8b7a5acbab2c.png">
<img width="1396" alt="Screenshot 2020-10-19 at 11 51 30 AM" src="https://user-images.githubusercontent.com/58783823/96409500-013e6400-1203-11eb-93ab-5cf000f3c9b1.png">
<img width="1396" alt="Screenshot 2020-10-19 at 11 51 51 AM" src="https://user-images.githubusercontent.com/58783823/96409501-01d6fa80-1203-11eb-8a6b-3e82405410ec.png">
<img width="1399" alt="Screenshot 2020-10-19 at 11 52 33 AM" src="https://user-images.githubusercontent.com/58783823/96409505-026f9100-1203-11eb-8412-fda03dd17dce.png">
<img width="1400" alt="Screenshot 2020-10-19 at 11 52 54 AM" src="https://user-images.githubusercontent.com/58783823/96409506-03082780-1203-11eb-982e-f8e3cb08093c.png">
<img width="1394" alt="Screenshot 2020-10-19 at 11 53 12 AM" src="https://user-images.githubusercontent.com/58783823/96409507-03082780-1203-11eb-933f-865c80d67218.png">
<img width="1391" alt="Screenshot 2020-10-19 at 11 53 39 AM" src="https://user-images.githubusercontent.com/58783823/96409510-03a0be00-1203-11eb-88aa-487d64110a56.png">
<img width="1394" alt="Screenshot 2020-10-19 at 11 54 01 AM" src="https://user-images.githubusercontent.com/58783823/96409512-03a0be00-1203-11eb-84dc-688e93fe27de.png">
<img width="1395" alt="Screenshot 2020-10-19 at 11 54 22 AM" src="https://user-images.githubusercontent.com/58783823/96409516-04395480-1203-11eb-93ad-2ac63813a3f5.png">
<img width="1398" alt="Screenshot 2020-10-19 at 11 54 56 AM" src="https://user-images.githubusercontent.com/58783823/96409518-04d1eb00-1203-11eb-92e3-aa772c43dfd6.png">
<img width="1389" alt="Screenshot 2020-10-19 at 11 55 21 AM" src="https://user-images.githubusercontent.com/58783823/96409519-04d1eb00-1203-11eb-9439-0d2c427bb435.png">
<img width="1393" alt="Screenshot 2020-10-19 at 11 55 59 AM" src="https://user-images.githubusercontent.com/58783823/96409520-056a8180-1203-11eb-8cd9-1a61faacdc8d.png">
2.For TCO20 only add:
logo+linked to home
login buttons as per https://marvelapp.com/prototype/5554efd/screen/66504645 for anonymous users. For logged-in users keep the profile section(at most right) similar on TCO19 https://tco19.topcoder.com/
Navi menu stays as it is now, unchanged. No, follow the design on that.
<img width="1403" alt="Screenshot 2020-10-19 at 11 57 57 AM" src="https://user-images.githubusercontent.com/58783823/96409554-13200700-1203-11eb-9a28-c0f6362a70fd.png">
<img width="1396" alt="Screenshot 2020-10-19 at 11 58 55 AM" src="https://user-images.githubusercontent.com/58783823/96409560-161af780-1203-11eb-975e-c490efcb6519.png">

**Comment by luizrrodrigues** [comment]
@kkartunov @SathyaJayabal We good to release this tomorrow?

**Comment by sandhiyakavi** [comment]
Verified on Staging.

![image](https://user-images.githubusercontent.com/55895538/97971752-da894b80-1e06-11eb-8a1e-f6c8f208687a.png)
![image](https://user-images.githubusercontent.com/55895538/97971775-e543e080-1e06-11eb-8d72-3249037cbc40.png)


![image](https://user-images.githubusercontent.com/55895538/97971600-a9108000-1e06-11eb-9179-364b570b3086.png)
![image](https://user-images.githubusercontent.com/55895538/97971715-cc3b2f80-1e06-11eb-8ad8-db2914df8502.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1435" alt="Screenshot 2020-11-03 at 5 33 54 PM" src="https://user-images.githubusercontent.com/58783823/97983770-d146b180-1dfb-11eb-9fc6-21e43596ccbf.png">
<img width="1439" alt="Screenshot 2020-11-03 at 5 34 15 PM" src="https://user-images.githubusercontent.com/58783823/97983779-d441a200-1dfb-11eb-934c-95d787825186.png">
<img width="1436" alt="Screenshot 2020-11-03 at 5 34 38 PM" src="https://user-images.githubusercontent.com/58783823/97983781-d4da3880-1dfb-11eb-85f4-3bda8388d494.png">
<img width="1440" alt="Screenshot 2020-11-03 at 5 35 01 PM" src="https://user-images.githubusercontent.com/58783823/97983784-d572cf00-1dfb-11eb-9d46-5913591cd41b.png">
<img width="1438" alt="Screenshot 2020-11-03 at 5 36 32 PM" src="https://user-images.githubusercontent.com/58783823/97983786-d60b6580-1dfb-11eb-9584-6f030060a400.png">
<img width="1439" alt="Screenshot 2020-11-03 at 5 36 44 PM" src="https://user-images.githubusercontent.com/58783823/97983788-d6a3fc00-1dfb-11eb-8d09-098d21482b80.png">
