### ISSUE TITLE
SMP (#441) - Development/Design Flow - UI jumps

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#504]
_It's not a bug, UX improvement suggestion._

When in the transition from one view to the other UI jumps and it looks deformed for few seconds. It shows up even on a fast network and when speed throttled it is more visible on slow networks.

**These packages are solving this problem** 

https://www.npmjs.com/package/react-page-transitions
https://www.npmjs.com/package/react-router-page-transition

**Comment by birdofpreyru** [comment]
@sushilshinde Do you mean the same as #351? I believe, it is just a markup / style problem in the page, not related to transitions between pages.

**Comment by sushilshinde** [comment]
No, it's not same I'll post a screencast for this.
