### ISSUE TITLE
Applying for a gig job end up in OOPS - try again in error

### ISSUE THREAD

**Issue by tmalbonph** [topcoder-platform/community-app#5040]
**Describe the bug**
I have applied for a gig job and it end up in OOPS - try again in error for the 3rd time.

**To Reproduce**
1. Go to https://www.topcoder.com/gigs/22141334/apply
2. Fill up the application
3. Click the APPLY TO THIS JOB button at the bottom of the page.
4. Expected a successful application.

**Expected behavior**
A successful **job application** should display something like a **success message**, a moment later, I should be receiving an email from *Jessie*.

**Desktop (please complete the following information):**
 - OS : *Ubuntu 18.04*
 - Browser : *chrome*
 - Version : *Version 85.0.4183.121 (Official Build) (64-bit)*

**Screenshot of the Failed gig job application**

![Error-Gig-Job-2020-10-03-11-46-33](https://user-images.githubusercontent.com/3745678/94982896-de5c5080-0570-11eb-9b3f-1239dfb41ff9.png)

**Comment by kkartunov** [comment]
Hey, @tmalbonph thanks for bug report. Can you please elaborate more on the error details and show us your full console output? There is no issue with service worker but probably with API communication to API

**Comment by tmalbonph** [comment]
@kkartunov I have no idea what is happening.

- But I am guessing that maybe I **already applied to the gig job** and the API refused my application,

- or maybe I am **applying with the wrong location** as the gig job welcomes only applicants from **India or nearby countries**.

- also, the **gig job link** was in the first place sent to me and mention that **I am qualified** to apply to it as **Matty Dixon of TC** writes on his email invitation to me.

**Comment by tmalbonph** [comment]
@kkartunov @Oanh-and-only-Oanh Any updates on this issue?

**Comment by Oanh-and-only-Oanh** [comment]
Hi,

Yes, I've alerted the community team to look into that issue. Thank you.

<https://www.topcoder.com/>

*Oanh Tran*

Product Manager, Community App

732-353-9457

www.topcoder.com  | @topcoder <http://twitter.com/topcoder>

**Comment by kkartunov** [comment]
@tmalbonph please retry again and share your full console output with us. We are not able to reproduce it currently with it. Thanks

**Comment by tmalbonph** [comment]
@kkartunov What do you mean by **full console output** ? I already get and posted the **full chrome output**.

**Comment by tmalbonph** [comment]
@kkartunov Did you **trace the code that display the OOPS error**? Did you **trace back what will trigger this error** messages? If you did, then you have a **case to explore**!

**Comment by tmalbonph** [comment]
@kkartunov @Oanh-and-only-Oanh **The error is gone**

- see **NoMoreError-2020-10-06-07-00-01.png**

![NoMoreError-2020-10-06-07-00-01](https://user-images.githubusercontent.com/3745678/95141190-1d71e800-07a3-11eb-8f62-5acdcc17ab09.png)

**Comment by kkartunov** [comment]
@tmalbonph great to hear, thank You!
