### ISSUE TITLE
WIP - Implement New Forums Object

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/community-app#5041]
The challenge object will now have a discussions node. The logic on the frontend should be:
1. If the challenge object has a discussions object, loop through it and look for `type`: `challenge`.
2. If it has `type`: `challenge`, build a link for the `<a href="{url}">{name}</a>`
3. If there is no discussions node, if there is no type challenge, or if the type challenge has no url, default back to looking for the `legacy.forumId` that you do now.

Note, it _is_ valid to have multiple type challenge nodes, so the frontend code should list them in a `<ul>` type list. Order of the array is fine, you don't need to sort them alphabetically or anything.

## Example Challenge Object
```json
{
  ...
  "discussions": [
    {
       "name": "Challenge Discussions",
       "type": "challenge",
       "provider": "vanilla",
       "url": "https://vanilla.topcoder-dev.com/forum/group/discussionid",
       "options": [{ "key": "foo", "value": "bar" }]
    }
  ]
}
```

The `options` array has nothing currently on the challenge forum. That's for future-proofing if we need to do registration for slack, or some other setup for other providers. Ignore that for now for Vanilla challenge forums.

Reference Issue:
https://github.com/topcoder-platform/challenge-api/issues/290

**Comment by rootelement** [comment]
This is working in dev. I created this challenge in work manager:
https://challenges.topcoder-dev.com/projects/16640/challenges/6f87e86b-5694-4547-b267-35f3ddd87906/view

The challenge object looks like this:
```json
"discussions": [
        {
            "provider": "vanilla",
            "name": "Forum Creation Test Discussion",
            "id": "a730ce22-20f7-4566-b99f-ba8901999a31",
            "type": "challenge",
            "url": "https://vanilla.topcoder-dev.com/categories/6f87e86b-5694-4547-b267-35f3ddd87906"
        }
    ],
```
@Oanh-and-only-Oanh FYI

**Comment by rootelement** [comment]
@Oanh-and-only-Oanh @luizrrodrigues do you have an ETA for this to be in Dev? We'd like to start E2E testing.

**Comment by luizrrodrigues** [comment]
@rootelement I'll push to QA env shortly

**Comment by luizrrodrigues** [comment]
@rootelement Done, deployed in QA env:
https://qa-community-app.topcoder-dev.com/challenges

**Comment by rootelement** [comment]
Thank you sir, We are testing.

I'm thinking we shouldn't show the forum link until the person is registered on the challenge? I will check that. We might not send it on the forum object if the person isn't registered. Not sure yet.

Good so far. Don't worry about multiple yet.

**Comment by rootelement** [comment]
@Oanh-and-only-Oanh i thought this went out with the last release. This not being in prod will prevent us from using new forums on things launched out of Work Manager.

@sushilshinde can this functionality go out first thing your daytime?

cc: @mtwomey

**Comment by SathyaJayabal** [comment]
@rootelement @luizrrodrigues , able to see the forums link on  details page even without logging in or registering  to the challenge
<img width="1440" alt="Screenshot 2020-11-12 at 8 56 09 AM" src="https://user-images.githubusercontent.com/58783823/98892660-cb6d6200-24c6-11eb-8d3a-6d04d813ac04.png">

**Comment by SathyaJayabal** [comment]
@rootelement @luizrrodrigues , while testing on prod backend, 
1. created a challenge through WM
https://staging-community-app.topcoder.com/challenges/e4c77f3b-fd3c-4591-bad5-03b17b527d55

2. Do not see the new forums link on details page because the vanilla forum url is missing in  the discussions object

<img width="1440" alt="Screenshot 2020-11-12 at 9 29 21 AM" src="https://user-images.githubusercontent.com/58783823/98894412-bc88ae80-24ca-11eb-935d-d76900b0cc9f.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @Oanh-and-only-Oanh 
Admin user and registered user able to view "Challenge Discussion" link and link opens new vanilla forums in new tab. As expected

<img width="1440" alt="Screenshot 2020-11-12 at 10 34 47 AM" src="https://user-images.githubusercontent.com/58783823/98898248-29a04200-24d3-11eb-9ffb-4deaacbc6bd3.png">
[forums.mov.zip](https://github.com/topcoder-platform/community-app/files/5528381/forums.mov.zip)

Not logged in or not registered users not able to see "Challenge Discussion" link as expected.
<img width="1440" alt="Screenshot 2020-11-12 at 10 33 10 AM" src="https://user-images.githubusercontent.com/58783823/98898296-4dfc1e80-24d3-11eb-97d2-b1f063314e11.png">
<img width="1440" alt="Screenshot 2020-11-12 at 10 33 39 AM" src="https://user-images.githubusercontent.com/58783823/98898302-52c0d280-24d3-11eb-8a44-661261720c53.png">

But for some Challenges, the Discussions object does not have the URL field and hence even new challenges created using WM point to the old forums. 
Example:
Prod backend: https://github.com/topcoder-platform/community-app/issues/5041#issuecomment-725817191
Dev backend: https://community-app.topcoder-dev.com/challenges/f008b241-864a-47a8-9b0d-c07b0b0c66ca
<img width="1440" alt="Screenshot 2020-11-12 at 10 41 41 AM" src="https://user-images.githubusercontent.com/58783823/98898599-01651300-24d4-11eb-9e1e-cb9414a7ae8d.png">
