### ISSUE TITLE
[$40] Sort : When new sort order is selected the bucket disappears for a few seconds before the new sort order is applied

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5044]
Got to listings page
Select a new sort order for my challenges bucket
Observe My challenges bucket disappears for a  few seconds before the new sort order is applied.
Same issue for Open for registration buckets too. 
Please see sort functionality for Ongoing bucket for expected behaviour.

[sort.mov.zip](https://github.com/topcoder-platform/community-app/files/5325562/sort.mov.zip)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh, The above issue is fixed after the past challenges update.

The current issue is for the All Challenges bucket, when sort is applied the "No Challenges found" message is displayed before the sort is applied and challenges are displayed.
[sort.mov.zip](https://github.com/topcoder-platform/community-app/files/5353165/sort.mov.zip)

**Comment by Oanh-and-only-Oanh** [comment]
Can you close this ticket if the original issue is fixed? I'll open a new ticket for this new issue.
