### ISSUE TITLE
Dashboard displaying a blank page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5049]
Dashboard displaying a blank page
<img width="1440" alt="Screenshot 2020-10-05 at 1 35 33 PM" src="https://user-images.githubusercontent.com/58783823/95054636-ca028a00-070f-11eb-893c-8202da86b6c5.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues maybe related to 
https://github.com/topcoder-platform/community-app/issues/4976#issuecomment-703547898

**Comment by luizrrodrigues** [comment]
F2F: https://www.topcoder.com/challenges/fa6a9710-cf06-434e-a8bd-d32285c85374

**Comment by SathyaJayabal** [comment]
This is fixed in staging
[dashboard.mov.zip](https://github.com/topcoder-platform/community-app/files/5352158/dashboard.mov.zip)
