### ISSUE TITLE
Gig Work Email Landing Page

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5051]
Marvel here https://marvelapp.com/prototype/f0i4ece/screen/72958362

Notes for QA:
- Header should be standard TC header not as per design

**Comment by SathyaJayabal** [comment]
@kkartunov , what is the page URL please?

**Comment by kkartunov** [comment]
Test URL: https://staging-community-app.topcoder.com/community/gig-subscribe

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
<img width="1440" alt="Screenshot 2020-10-13 at 3 37 28 PM" src="https://user-images.githubusercontent.com/58783823/95847188-0a928100-0d6a-11eb-81a0-970fdca3ec0a.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-10-14 at 12 08 44 AM" src="https://user-images.githubusercontent.com/58783823/95901766-75b37600-0db1-11eb-9c33-33d770cf5df9.png">
