### ISSUE TITLE
Update Sub-community challenge listings page URL (filter by community) to follow  new format

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5057]
Some of the challenge  pages of the sub communities will be by default filtered by sub-community. The filter url must be updated to use the new format. 
Example:
This is the challenges link URL for Zurich
https://staging-community-app.topcoder.com/__community__/zurich/challenges?communityId=zurich
To filter by community Zurich, the new URL is 
https://staging-community-app.topcoder.com/__community__/zurich/challenges?groups[]=6e353b35-61d4-4048-8cae-2e21526cbfd6

We must update the Challenges link to the new format so the filter is applied correctly.

<img width="1440" alt="Screenshot 2020-10-06 at 10 12 16 AM" src="https://user-images.githubusercontent.com/58783823/95160057-37202900-07bd-11eb-8ce3-dea73690fcb8.png">
<img width="1440" alt="Screenshot 2020-10-06 at 10 12 40 AM" src="https://user-images.githubusercontent.com/58783823/95160076-41422780-07bd-11eb-9ed0-a07aba3025ea.png">

**Comment by luizrrodrigues** [comment]
**F2F**: https://github.com/topcoder-platform/community-app/issues/5057

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , the filter count should be 1 as only the sub-community filter is applied
<img width="1440" alt="Screenshot 2020-10-13 at 11 24 45 AM" src="https://user-images.githubusercontent.com/58783823/95821032-d5286c00-0d46-11eb-86d0-fa8ce9e4b62e.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on staging
<img width="1440" alt="Screenshot 2020-10-13 at 12 37 14 PM" src="https://user-images.githubusercontent.com/58783823/95827077-e4141c00-0d50-11eb-9a40-1a61120321fd.png">

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
<img width="1440" alt="Screenshot 2020-10-13 at 3 35 08 PM" src="https://user-images.githubusercontent.com/58783823/95847023-d6b75b80-0d69-11eb-98a3-d58cd7129237.png">

**Comment by SathyaJayabal** [comment]
verified on prod

<img width="1440" alt="Screenshot 2020-10-14 at 12 04 20 AM" src="https://user-images.githubusercontent.com/58783823/95901482-0a69a400-0db1-11eb-91db-9ccc23567ab4.png">
