### ISSUE TITLE
Gig Work application process - change status in recruitCRM to "apply"

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5059]
In recruitCRM it looks like it is “assigning” people to gigs and not “applying” them. We need to change that.

**Comment by kkartunov** [comment]
@SathyaJayabal verified on stage. No issues found.

**Comment by SathyaJayabal** [comment]
@kkartunov , please verify on prod and close this issue.

**Comment by SathyaJayabal** [comment]
Closing this as @hokienick has verified it on prod.
