### ISSUE TITLE
When filter by type is selected "No Live Challenges" message displayed even when challenges are present

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5064]
user: tonyj
1. go to listings page
https://qa-community-app.topcoder-dev.com/challenges?
2. Filter by type = task
We can see challenges under `My challenges` and `Open for registration` buckets, but still `No Live Challenges found in All Challenges` message is displayed.

actual: `No Live Challenges found in All Challenges` message is displayed.
expected: `My challenges` and `Open for registration` buckets must be displayed. 

<img width="1440" alt="Screenshot 2020-10-07 at 11 10 38 AM" src="https://user-images.githubusercontent.com/58783823/95291744-d01e7500-088d-11eb-8741-381c3a562c84.png">
<img width="1440" alt="Screenshot 2020-10-07 at 11 11 04 AM" src="https://user-images.githubusercontent.com/58783823/95291758-d44a9280-088d-11eb-9dbc-0988629b65a4.png">

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, is this bug on PROD as well or just an issue in QA environment?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , its just in the new listings.

**Comment by Oanh-and-only-Oanh** [comment]
My view of the screen is different from what yours when i go to https://qa-community-app.topcoder-dev.com/challenges?

1. I have "past challenges" bucket...
2. I'm not getting the No Live Challenges found in All Challenges message. 

![image](https://user-images.githubusercontent.com/47536078/95367718-f0e4cb80-0889-11eb-8f10-fd308a260096.png)

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , please try now.

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, I'll try again logged but this is the logged out view. 
![Uploading image.png…]()

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , this is one is fixed as part of the past challenges updates.
<img width="1440" alt="Screenshot 2020-10-09 at 8 10 12 AM" src="https://user-images.githubusercontent.com/58783823/95535791-ef8cdd80-0a06-11eb-89cf-ee39d1a51385.png">
