### ISSUE TITLE
retUrl in Log In button in the standard TC header

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#507]
it is not used there, should be added

**Comment by sushilshinde** [comment]
Fixed and added in `small-fixes` branch

**Comment by birdofpreyru** [comment]
When we did the fix in (A) https://github.com/topcoder-platform/community-app/blob/develop/src/shared/components/TopcoderHeader/index.jsx
we have overlooked that there is later implementation of Login / Register buttons block (B) https://github.com/topcoder-platform/community-app/tree/develop/src/shared/components/TopcoderHeader/Auth
which, turns out, is used in some places, but not everywhere. So, the fix should be moved into (B), and we should ensure that all places where these buttons are necessary, like (A), are updated to just use the (B) component.
