### ISSUE TITLE
Listings : filters are retained when user navigates away and returns to the page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5085]
Go to listings page
Apply tracks filter
Navigate away to another page
Return to Listings page
Previously applied filters are retained.

@Oanh-and-only-Oanh , is this behaviour fine?
[filter.mov.zip](https://github.com/topcoder-platform/community-app/files/5353366/filter.mov.zip)

**Comment by Oanh-and-only-Oanh** [comment]
This is expected behavior. Closing ticket.
