### ISSUE TITLE
Gig Work - details page fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5086]
https://www.topcoder.com/gigs/22281320

- hourly compensation wrong
- hours per week - show only n/a if not set
- add in gig details notes section - "**USA Visa Holders - Please consult an attorney before applying to any Topcoder Gig. Some visa statuses will or will not allow you to conduct freelance work with Topcoder."
- current ** will become ***

**Comment by SathyaJayabal** [comment]
verified on test
@kkartunov , for the hourly compensation, when we have only one number, do we need to display as `$70 - $70 / hourly`. Shouldn't it be simply `$70 / hourly`

<img width="1440" alt="Screenshot 2020-10-09 at 3 05 48 PM" src="https://user-images.githubusercontent.com/58783823/95567920-37305b00-0a41-11eb-90f9-47235b11305f.png">
<img width="1440" alt="Screenshot 2020-10-09 at 3 06 03 PM" src="https://user-images.githubusercontent.com/58783823/95567950-3f889600-0a41-11eb-914b-f83493b09419.png">

**Comment by kkartunov** [comment]
> verified on test
> @kkartunov , for the hourly compensation, when we have only one number, do we need to display as `$70 - $70 / hourly`. Shouldn't it be simply `$70 / hourly`

In this case, they equal but more often we have min/max $ set differently. We need that for cases like it.
@SathyaJayabal

**Comment by SathyaJayabal** [comment]
@kkartunov , the section titles are center aligned instead of left aligned
<img width="1440" alt="Screenshot 2020-10-13 at 3 41 18 PM" src="https://user-images.githubusercontent.com/58783823/95849511-3400dc00-0d6d-11eb-9c73-e24122a127a3.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-10-13 at 8 15 56 PM" src="https://user-images.githubusercontent.com/58783823/95883338-6ecc3980-0d98-11eb-99de-5e16856051ce.png">
<img width="1440" alt="Screenshot 2020-10-13 at 8 16 14 PM" src="https://user-images.githubusercontent.com/58783823/95883354-7390ed80-0d98-11eb-9f45-08307021bcd0.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-10-14 at 12 06 40 AM" src="https://user-images.githubusercontent.com/58783823/95901638-40a72380-0db1-11eb-920c-f93c9d774e3a.png">
<img width="1440" alt="Screenshot 2020-10-14 at 12 06 54 AM" src="https://user-images.githubusercontent.com/58783823/95901659-4866c800-0db1-11eb-9867-58cd39c9d274.png">
