### ISSUE TITLE
[$75] Search not returning results for multiple words

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5087]
Search not returning results for multiple words
example: search for "Skill Builder"
<img width="1440" alt="Screenshot 2020-10-09 at 3 20 03 PM" src="https://user-images.githubusercontent.com/58783823/95569293-fe918100-0a42-11eb-99bf-4ac6005a2abc.png">
<img width="1440" alt="Screenshot 2020-10-09 at 3 20 20 PM" src="https://user-images.githubusercontent.com/58783823/95569312-05b88f00-0a43-11eb-8c92-dc4b91138784.png">

cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@rootelement , this was working before today's release. Can you take a look please.

**Comment by rootelement** [comment]
Please clarify. This was working in prod before we released API updates to prod? Did you test this in dev before yesterday's release?

**Comment by Oanh-and-only-Oanh** [comment]
@rootelement it was test in staging environment last night before release.

**Comment by rootelement** [comment]
Staging environment was new code pointed at prod, not dev. Was this tested in dev? We changed the search to be a wildcard search. I'm seeing the issue now. Will get on it this weekend.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , removing bug bash label, its a back end fix

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , fixed

This is the preloaded filter for skill builder
https://www.topcoder.com/challenges?name=skill%20builder&tracks[Dev]=true&tracks[Des]=true&tracks[DS]=true&tracks[QA]=true

<img width="1440" alt="Screenshot 2020-10-22 at 10 14 17 AM" src="https://user-images.githubusercontent.com/58783823/96825770-83bb6380-144f-11eb-8dc8-0177072020d0.png">
