### ISSUE TITLE
Public challenges showing in private communities

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5089]
All subcommunitieis that the member is assigned to are showing in the private community portals. 

How to reproduce: 
1. Go to https://zurich.topcoder.com/challenges?communityId=zurich
2. See that non Zurich challenges are shown and dropdown in subcommunities filter shows TCO20, TCO21 and other subcommunities
![image](https://user-images.githubusercontent.com/47536078/95625483-66d56800-0a2d-11eb-9656-fb69f3cebd0a.png)

Expected behavior:
1. Go to https://zurich.topcoder.com/challenges?communityId=zurich
2. ONLY Zurich challenges should be shown. Dropdown in subcommunities filter should ONLY show Zurich even if member has assess to other subcommunities

This applies to all private communities. Each private community (Zurich, CS, Topgear) should only see challenges for that group. No other challenges or subcommunities should be down even if user is assigned toe other communities.

**Comment by Oanh-and-only-Oanh** [comment]
Is this because I'm seeing all subcommunities I'm assigned to? 
![Uploading image.png…]()

**Comment by rootelement** [comment]
Just tested in prod with a couple different zurich groups. The groups functionality did not change recently. Here's the response from the api with one of the zurich groups:

GroupID: b0fad960-b05b-4c50-a036-34ad9ae35462
Response (with M2M):
<img width="1038" alt="Screen Shot 2020-10-09 at 3 39 50 PM" src="https://user-images.githubusercontent.com/5400156/95624965-b3c53880-0a45-11eb-857d-d918c721d457.png">

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh @rootelement I'm run some rollback in my local env and looks like issue coming from first challenge listing refactor (dc52de06a3752058561efd63246182ef4057389a)

@LieutenantRoger You remember if fixed this before?

**Comment by LieutenantRoger** [comment]
I am not sure. Please check what filters have been sent when using url like this to visit challenge list screen

The communityId query parameter is not utilized, I think.

**Comment by luizrrodrigues** [comment]
@LieutenantRoger Yeah, looks like we loose part of code to get url `communityId` and convert to filter.

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/community-app/issues/5057
tracked here

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , its just the default filter that is not set here. The users could still filter but all in sub-communities filter and view public challenges previously.
