### ISSUE TITLE
[$50] - Submission logic issue

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#509]
*NOTE: Included into a code challenge*

Do the following:
- Submit to a challenge;
- See submission success page;
- Press back in browser to get back to the challenge details page;
- Click Submit button:
  - It will get you to the submission success page you saw before;
  - Should start the new submission flow instead.

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/622
hash: 271df9e
