### ISSUE TITLE
show the usable code links on the challenge description

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#5102]
**Is your feature request related to a problem? Please describe.**
For new member it is not clear what kind of code they can use/reuse on the code challenge, we have article https://www.topcoder.com/thrive/articles/Usable%20Code%20in%20Dev%20Challenges but it is not easily accessible to the member

**Describe the solution you'd like**
Have a link to the https://www.topcoder.com/thrive/articles/Usable%20Code%20in%20Dev%20Challenges in the code challenge detail page similar to Review Scorecard 
![image](https://user-images.githubusercontent.com/2202045/95891900-72b28880-0da5-11eb-93ae-9ccccc59626d.png)

**Describe alternatives you've considered**
currently I am sharing this on the forum or on spec but this doesn't give uniform experience for the members

**Additional context**
na

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh 


![5102-1](https://user-images.githubusercontent.com/4476442/95946242-5995f000-0e16-11eb-92d7-2d4446bb9300.png)
![5102-2](https://user-images.githubusercontent.com/4476442/95946244-5a2e8680-0e16-11eb-8689-13bd8111df81.png)
![5102-3](https://user-images.githubusercontent.com/4476442/95946246-5b5fb380-0e16-11eb-93b3-6f66fa5781df.png)

Please let me know for any feedback.

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh 

1. Ok
2. Yes, this is only for Dev challenges
3. Ok

**Comment by dedywahyudi** [comment]
![Screen Shot 2020-10-14 at 22 13 58](https://user-images.githubusercontent.com/4476442/96009344-c1762600-0e6a-11eb-921c-144ff827b4e0.png)
![Screen Shot 2020-10-14 at 22 15 09](https://user-images.githubusercontent.com/4476442/96009352-c33fe980-0e6a-11eb-9f9e-0ead5b2c2956.png)


@Oanh-and-only-Oanh how about this updated solution?

**Comment by SathyaJayabal** [comment]
Verified on staging.

I can see this link added to QA challenges too including BH's. Is that fine @Oanh-and-only-Oanh 
example:
https://staging-community-app.topcoder.com/challenges/48406f89-3b18-488e-bccf-b7c7e6e8dd0b

<img width="1440" alt="Screenshot 2020-10-15 at 10 52 21 AM" src="https://user-images.githubusercontent.com/58783823/96080528-e0110700-0ed4-11eb-866a-73e2b8f16147.png">

**Comment by dedywahyudi** [comment]
1. Waiting @Oanh-and-only-Oanh feedback
2. @SathyaJayabal spacing should be consistent now. For example: 

![Screen Shot 2020-10-15 at 13 52 08](https://user-images.githubusercontent.com/4476442/96087171-a5679880-0eed-11eb-95f8-2e443223da1e.png)


cc @luizrrodrigues @sushilshinde  this is applied to the new commit: https://github.com/topcoder-platform/community-app/pull/5104/commits

**Comment by Oanh-and-only-Oanh** [comment]
Thanks for the feedback @SathyaJayabal. 
@dedywahyudi, can you include this feature for QA challenges? THanks.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , The feature is present for QA challenges already. The question was , is it necessary to have this link for QA challenges ? At present we exclude only design and marathon matches, Should we exclude for QA too?

**Comment by Oanh-and-only-Oanh** [comment]
Yes, that's fine. I'd like to include for QA especially bug bash challenges.

**Comment by SathyaJayabal** [comment]
Thanks @Oanh-and-only-Oanh,

**Comment by SathyaJayabal** [comment]
verified.
<img width="1440" alt="Screenshot 2020-10-15 at 9 04 21 PM" src="https://user-images.githubusercontent.com/58783823/96152324-0c0aa780-0f2a-11eb-9fc9-697398ddbabc.png">

**Comment by dedywahyudi** [comment]
@SathyaJayabal @Oanh-and-only-Oanh 

Ok, from discussion above. I think there's no more edit right since url already showing up?

**Comment by SathyaJayabal** [comment]
@dedywahyudi , we are good to go.

**Comment by SathyaJayabal** [comment]
verified in staging (develop branch). link appears for all challenges except MM and Design challenges.
<img width="1440" alt="Screenshot 2020-11-03 at 2 34 20 PM" src="https://user-images.githubusercontent.com/58783823/97966416-d1d24e80-1de1-11eb-9ec0-e4f4645fec93.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-03 at 5 26 50 PM" src="https://user-images.githubusercontent.com/58783823/97982434-cbe86780-1df9-11eb-8a49-f6b6df21b155.png">
