### ISSUE TITLE
[$80] visiting F2F on profiles and click on challenges tab, the page display empty

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5103]
How to reproduce:
1. Go to: https://www.topcoder.com/members/tourist/details/?track=DEVELOP&subTrack=FIRST_2_FINISH
2. Click on Challenges tab
3. Page reloads as blank/empty. See errors at roles
![image](https://user-images.githubusercontent.com/47536078/95910354-ccd72d80-0d54-11eb-829d-4d7f8a0e63c4.png)

**Comment by SathyaJayabal** [comment]
tracked here #5082
