### ISSUE TITLE
Blank page on accessing review opportunities bucket

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5120]
Blank page on accessing review opportunities bucket

The v3 call returns an error `Error in authenticating credentials`
<img width="1440" alt="Screenshot 2020-10-16 at 10 10 51 AM" src="https://user-images.githubusercontent.com/58783823/96213981-e4522880-0f97-11eb-8ae6-dc9c30c3766a.png">

**Comment by sushilshinde** [comment]
This call is failing

![1](https://user-images.githubusercontent.com/683231/96221975-1750e800-0fa9-11eb-9392-85ff8f290fec.png)

![2](https://user-images.githubusercontent.com/683231/96221980-1a4bd880-0fa9-11eb-97b5-bc7125d21f1c.png)

**Comment by sachin-maheshwari** [comment]
Fixed on dev.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2020-10-16 at 2 34 09 PM" src="https://user-images.githubusercontent.com/58783823/96238974-b92e0000-0fbc-11eb-9767-ccb54f3bf3d7.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-02 at 2 23 05 PM" src="https://user-images.githubusercontent.com/58783823/97848351-f3b2cf00-1d16-11eb-98f4-f3180248f8a4.png">
