### ISSUE TITLE
Checkpoints tab not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5121]
example:
develop branch
https://test-community-app.topcoder-dev.com/challenges/640cd60c-9acb-45e7-8a62-9ac12e43c8b1?tab=checkpoints

auth0 branch
http://www.topcoder-dev.com/challenges/640cd60c-9acb-45e7-8a62-9ac12e43c8b1

**Comment by SathyaJayabal** [comment]
<img width="1440" alt="Screenshot 2020-10-16 at 1 16 56 PM" src="https://user-images.githubusercontent.com/58783823/96227620-ffca2d00-0fb1-11eb-9168-57bbd0a7648b.png">
<img width="1440" alt="Screenshot 2020-10-16 at 1 17 45 PM" src="https://user-images.githubusercontent.com/58783823/96227654-09ec2b80-0fb2-11eb-8021-e64564fd05b2.png">

**Comment by sushilshinde** [comment]
@sachin-maheshwari 

Call from Community-App 
```
https://api.topcoder.com/v2/design/challenges/checkpoint/30127234
```

Not working with token 

![image](https://user-images.githubusercontent.com/683231/96573506-db40be80-12eb-11eb-8dae-6926b939ce80.png)


It is working without token 

![image](https://user-images.githubusercontent.com/683231/96573590-03302200-12ec-11eb-8924-e3811d701594.png)

**Comment by sachin-maheshwari** [comment]
@sushilshinde  i think, v2 call will not work for "new auth". This could be blocker for ur.

**Comment by sushilshinde** [comment]
@sachin-maheshwari @rootelement what if we don't pass token at all anyway checkpoints are accessible even the user is not logged in a quick fix?

**Comment by rootelement** [comment]
I don't know where this API lives. I'm trying to find it. I assume the feedback is not available if you're not logged in?

**Comment by sushilshinde** [comment]
Yeah, feedback won't be available.

**Comment by sachin-maheshwari** [comment]
> @sachin-maheshwari @rootelement what if we don't pass token at all anyway checkpoints are accessible even the user is not logged in a quick fix?

@sushilshinde I don't have any idea reading the checkpoints. so i can't comment on this.

**Comment by mtwomey** [comment]
Can we change this v2 api call and make it not a v2 api call, as a hotfix, tomorrow? @sushilshinde @rootelement

**Comment by mtwomey** [comment]
Or, maybe - not use the token, that's fine too.

**Comment by sushilshinde** [comment]
> Can we change this v2 api call and make it not a v2 api call, as a hotfix, tomorrow? @sushilshinde @rootelement

@rootelement?

**Comment by sushilshinde** [comment]
> Or, maybe - not use the token, that's fine too.

The user won't be able to see the feedback on their submissions

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-10-22 at 10 34 53 AM" src="https://user-images.githubusercontent.com/58783823/96827024-4a382780-1452-11eb-872d-54cac000b50f.png">
<img width="1440" alt="Screenshot 2020-10-22 at 10 35 14 AM" src="https://user-images.githubusercontent.com/58783823/96827034-4f957200-1452-11eb-8a68-c97111cfadba.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-02 at 2 22 07 PM" src="https://user-images.githubusercontent.com/58783823/97848264-d251e300-1d16-11eb-8b2f-2297d522a8c0.png">
