### ISSUE TITLE
Logout from TCO pages is not working

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5126]
1. Login using new auth0
2. Go to any of the tco pages. example:
https://community-app.topcoder-dev.com/__community__/tco19
3. Click on logout

expected: user must be logged out 

actual: an error page is displayed and the suer is not logged out
<img width="1440" alt="Screenshot 2020-10-19 at 3 54 16 PM" src="https://user-images.githubusercontent.com/58783823/96435582-5db17b80-1223-11eb-8b17-6b4c824ecf15.png">

[logout.mov.zip](https://github.com/topcoder-platform/community-app/files/5401095/logout.mov.zip)

**Comment by SathyaJayabal** [comment]
Same happens for other sub community pages too

**Comment by sachin-maheshwari** [comment]
@LieutenantRoger please fix, retUrl is missing (null) in logout. 
<img width="1679" alt="Screenshot 2020-10-20 at 4 12 50 PM" src="https://user-images.githubusercontent.com/6467888/96576079-4049e380-12ef-11eb-8c16-1569a2249a92.png">

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari I think you try @ mention me instead LieutenantRoger 

So this menu coming from Contentful, @kkartunov can you us in this one?

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari Fixed `retUrl` in my local env, but still getting error to this one:

https://accounts-auth0.topcoder-dev.com/?logout=true&retUrl=https://community-app.topcoder-dev.com/__community__/tco19

or 

https://accounts-auth0.topcoder-dev.com/?logout=true&retUrl=https%3A%2F%2Fcommunity-app.topcoder-dev.com%2F__community__%2Ftco19

Looks like issue with `_` in URL

**Comment by kkartunov** [comment]
@luizrrodrigues this sub-menu is not Contentful it is part of TC header(old codebase). You need to patch here https://github.com/topcoder-platform/community-app/blob/12adaecd72774539d013014b4cb3ce3f6deaa2f9/src/shared/components/TopcoderHeader/index.jsx#L298

**Comment by luizrrodrigues** [comment]
@kkartunov Yeah, sorry. Working on this. :)

**Comment by SathyaJayabal** [comment]
verified on staging
[logout_subcomm.mov.zip](https://github.com/topcoder-platform/community-app/files/5420246/logout_subcomm.mov.zip)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , can you also update the return urls for the other sub communities
<img width="1440" alt="Screenshot 2020-10-22 at 10 56 34 AM" src="https://user-images.githubusercontent.com/58783823/96828461-596ca480-1455-11eb-8476-c12fe03323ab.png">
<img width="1440" alt="Screenshot 2020-10-22 at 10 56 54 AM" src="https://user-images.githubusercontent.com/58783823/96828482-64273980-1455-11eb-8029-1658dad8d2e8.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Done.

**Comment by sandhiyakavi** [comment]
@luizrrodrigues Logout of tco18 is not working. Getting below screen after clicking logout and user is not logged out.

<img width="959" alt="tco18_error" src="https://user-images.githubusercontent.com/55895538/96958962-e25d0c00-1539-11eb-849f-eaa46fc37464.png">

[tco18_logout_fail.zip](https://github.com/topcoder-platform/community-app/files/5427439/tco18_logout_fail.zip)

Logout for Blockchain and Cognitive subcommunity is working fine.

[Blockchain_logout_pass.zip](https://github.com/topcoder-platform/community-app/files/5427440/Blockchain_logout_pass.zip)
[Cognitive_logout_pass.zip](https://github.com/topcoder-platform/community-app/files/5427441/Cognitive_logout_pass.zip)

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi i am fixing this from auth0.

**Comment by sachin-maheshwari** [comment]
@sandhiyakavi  sorry i misinterpreted the issue, logout is working fine. but login is the issue. we need to fix that. 
@LieutenantRoger  please fix. For me its "link not updated issue".

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari Let me check

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari @sandhiyakavi 

Logout link bellow not working:

https://accounts-auth0.topcoder.com/?logout=true&retUrl=https%3A%2F%2Fstaging-community-app.topcoder.com%2F__community__%2Ftco18

https://accounts-auth0.topcoder.com/?logout=true&retUrl=https%3A%2F%2Fstaging-community-app.topcoder.com%2F__community__%2Ftco17
 
https://accounts-auth0.topcoder.com/?logout=true&retUrl=https%3A%2F%2Fstaging-community-app.topcoder.com%2F__community__%2Fveterans

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues  done.

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari Cool, looks like working well now.

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues logout fixed, but for registration url  i am fixing...

**Comment by sachin-maheshwari** [comment]
Fixed!

**Comment by sandhiyakavi** [comment]
Verified on Staging. Logout working for Veterans, tco18 and tco17 subcommunities.
[Logout_subcommunities_pass.zip](https://github.com/topcoder-platform/community-app/files/5437341/Logout_subcommunities_pass.zip)

**Comment by SathyaJayabal** [comment]
verified on prod for tco18 site
