### ISSUE TITLE
Unable to Login to Enterprise Topgear on Staging

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/community-app#5130]
-- Loaded https://staging-community-app.topcoder.com/__community__/wipro 
-- Redirects to this page and is frozen here: 
<img width="1280" alt="Screenshot 2020-10-20 at 3 48 15 PM" src="https://user-images.githubusercontent.com/51733042/96575613-99fdde00-12ee-11eb-8b7c-972a87d4ac54.png">

**Comment by luizrrodrigues** [comment]
@lakshmiathreya Tested this in Dev and looks like working well, can you re check please?

https://accounts-auth0.topcoder-dev.com/?retUrl=http%3A%2F%2Flocal.topcoder-dev.com%2F__community__%2Fwipro&utm_source=wipro

**Comment by sushilshinde** [comment]
@luizrrodrigues it is just for login

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , you see similar behaviour for these test cases. Please compare dev and staging. Its fine in dev but not working in staging even though we have the same branch deployed in both places.
https://github.com/topcoder-platform/community-app/issues/5131#issue-726231595

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari @sushilshinde 

Dev: `/sso-login/?retUrl=`
https://accounts-auth0.topcoder-dev.com/sso-login/?retUrl=https%3A%2F%2Fcommunity-app.topcoder-dev.com%2F__community__%2Fwipro&utm_source=wipro

redirect to: `https://accounts-auth0.topcoder-dev.com/#!/sso-login/?retUrl=https%3A%2F%2Fcommunity-app.topcoder-dev.com%2F__community__%2Fwipro&utm_source=wipro`

-----

Stag: `/sso-login/?retUrl=`
https://accounts-auth0.topcoder.com/sso-login/?retUrl=https%3A%2F%2Fhttp://staging-community-app.topcoder.com%2F__community__%2Fwipro&utm_source=wipro

redirect to: `https://accounts-auth0.topcoder.com/#!/sso-login/`

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya @SathyaJayabal Fixed, there was CloudFront "Query String Forwarding and Caching" issue.

**Comment by lakshmiathreya** [comment]
@sachin-maheshwari @luizrrodrigues - Login to Topgear seems to be working fine for Chrome and Firefox now. Issue is unresolved on Safari. The Staging Topgear url https://staging-community-app.topcoder.com/__community__/wipro redirects to this page:

<img width="1606" alt="Screenshot 2020-10-22 at 8 31 26 AM" src="https://user-images.githubusercontent.com/51733042/96819340-fffa7a80-1440-11eb-832a-41c76e974799.png">

**Comment by SathyaJayabal** [comment]
> @lakshmiathreya @SathyaJayabal Fixed, there was CloudFront "Query String Forwarding and Caching" issue.

@sachin-maheshwari , could there be a chance for the same issue to happen in other apps? As we have only tetsed on dev for the other apps.

**Comment by lakshmiathreya** [comment]
-- Verified for Windows/Edge - redirect to Wipro adfs working fine.

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya just FYI, if you see current prod, https://topgear.topcoder.com is also not working as per expectation on Safari browser.

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya this is fixed. Please verify and close the issue.  Please note - you may need to clear your browser cache first on Safari. Also sanity on other browsers too please.

**Comment by lakshmiathreya** [comment]
Safari verified.
