### ISSUE TITLE
Checkpoints tab missing for design challenges with checkpoints

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5136]
Checkpoints tab missing for design challenges with checkpoints

example:
https://www.topcoder.com/challenges/804fd6b0-f1d3-43e6-84a9-14dca48fa8e7

compare with v4 (where we can see checkpoints)
https://beta-community-app.topcoder.com/challenges/30144368

<img width="1440" alt="Screenshot 2020-10-22 at 9 57 11 AM" src="https://user-images.githubusercontent.com/58783823/96824668-fb3bc380-144c-11eb-9670-cb573aeb6fa6.png">

cc @rootelement

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This was fixed here: https://github.com/topcoder-platform/topcoder-react-lib/pull/275/files

Issue: API return `challenge.legacyId` as **string** (I think to new challenges), so this validation broken:
```
state.details.legacyId === action.payload.challengeId
```

changed to:
```
`${state.details.legacyId}` === `${action.payload.challengeId}`
```

**Comment by SathyaJayabal** [comment]
@luizrrodrigues,so this will be fixed as part of auth0 release?

cc @sushilshinde

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yes

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-02 at 2 22 07 PM" src="https://user-images.githubusercontent.com/58783823/97848603-5310df00-1d17-11eb-88ce-59c8a48c5fff.png">
