### ISSUE TITLE
Add support for password protection to Contentful routes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5142]
If a password is set on route level in Contentful user should be presented with an auth screen to type that password then continue to content. In case the password is wrong then a simple error message in red above the button will inform the user.

![Screenshot from 2020-10-27 16-15-14](https://user-images.githubusercontent.com/5585002/97314385-5536f180-1870-11eb-861a-3a84d4595d44.png)

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2020-11-02 at 12 09 11 PM" src="https://user-images.githubusercontent.com/58783823/97837466-433bcf80-1d04-11eb-8e54-99d394f5f959.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging.

![image](https://user-images.githubusercontent.com/55895538/97848558-988fd500-1d34-11eb-99f7-6eb593377ff0.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-03 at 1 32 20 PM" src="https://user-images.githubusercontent.com/58783823/97961296-05f54180-1dd9-11eb-9572-4d2ed65c4351.png">
