### ISSUE TITLE
Create and configure apollo.topcoder.com

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5143]
https://apollo.topcoder.com to route to community-app that should load a Contentful route for https://community-app.topcoder.com/apollo.

**Comment by SathyaJayabal** [comment]
@kkartunov , what is the test url for test env, where this is deployed?

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2020-11-02 at 12 08 28 PM" src="https://user-images.githubusercontent.com/58783823/97837400-243d3d80-1d04-11eb-90b3-8c842122b383.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging.

![image](https://user-images.githubusercontent.com/55895538/97848715-d68cf900-1d34-11eb-9189-ea2f080a1a83.png)

**Comment by SathyaJayabal** [comment]
`https://community-app.topcoder.com/apollo` works fine but route `https://www.apollo.topcoder.com/` is not yet configured

**Comment by kkartunov** [comment]
verified https://apollo.topcoder.com and https://www.topcoder.com/apollo work as expected.
