### ISSUE TITLE
Sort is not returning any challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5154]
got to https://www.topcoder.com/challenges?
apply sort for any of the following buckets
```
All Challenges
My Challenges
Open for Registration
```

Expected: Challenges must be displayed sorted on the selected sort criteria
Actual: `No Challenges Found` message is displayed and no challenges are displayed.

The below api call does not return any challenges
`https://api.topcoder.com/v5/challenges/?status=Active&currentPhaseName=Registration&perPage=10&page=1&sortBy=name&sortOrder=asc&tracks[]=Dev&tracks[]=Des&tracks[]=DS&tracks[]=QA`
[sort_issue.mov.zip](https://github.com/topcoder-platform/challenge-api/files/5480393/sort_issue.mov.zip)

cc @sushilshinde @Oanh-and-only-Oanh

**Comment by rootelement** [comment]
A fix has been deployed for prod. @SathyaJayabal please re-test.

**Comment by SathyaJayabal** [comment]
@rootelement , fix is working fine. Thanks
