### ISSUE TITLE
SEO: Fix Challenge Listing page and update Challenge Details

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5157]
**1 - Challenge Listing**
https://www.topcoder.com/challenges

a) Update SEO Title:
“Topcoder Challenge Listings | Topcoder Community | Topcoder”

b) Update Meta Description:
“Browse the challenges currently available on Topcoder. Search by type of challenge, then find those of interest to register for and compete in today.”

------

**2 - Challenge Details**
example: https://www.topcoder.com/challenges/d9b17657-585c-403e-8629-2211274e8807

a) Update SEO Title:
“Topcoder Challenge | Topcoder Community | Topcoder”

b) Update Meta Description:
“Browse the challenges currently available on Topcoder. Search by type of challenge, then find those of interest to register for and compete in today. ”

**Comment by luizrrodrigues** [comment]
Challenge: https://www.topcoder.com/challenges/4b21403c-4a02-4950-a368-1d1387ea9d68

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Test env

**Comment by sandhiyakavi** [comment]
Verified in Test Env.

Challenge Listings Page
![image](https://user-images.githubusercontent.com/55895538/98069770-ee828b00-1ea2-11eb-9f5b-49c0ea901668.png)

Challenge Details
![image](https://user-images.githubusercontent.com/55895538/98069810-04904b80-1ea3-11eb-9794-3b170e5d9651.png)

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-11-10 at 1 16 44 PM" src="https://user-images.githubusercontent.com/58783823/98645057-69421f00-2357-11eb-8492-8eb7622e6575.png">
<img width="1440" alt="Screenshot 2020-11-10 at 1 19 12 PM" src="https://user-images.githubusercontent.com/58783823/98645076-6f380000-2357-11eb-918c-2a16141104d3.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-10 at 8 00 45 PM" src="https://user-images.githubusercontent.com/58783823/98687277-90b4de00-238f-11eb-86c5-b8e4473570ba.png">
<img width="1440" alt="Screenshot 2020-11-10 at 8 01 07 PM" src="https://user-images.githubusercontent.com/58783823/98687308-99a5af80-238f-11eb-8509-113ee939d204.png">
