### ISSUE TITLE
Auth0 - Issue when token expires

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5159]
When token expires showing error and blank page to Challenge Listing and Challenge Details.

**Comment by SathyaJayabal** [comment]
challenge listings: subcommunities not loading and we get the console error
challenge details: error message displayed along with console error
both pages are fine once we refresh the page
<img width="1440" alt="Screenshot 2020-11-05 at 8 40 00 AM" src="https://user-images.githubusercontent.com/58783823/98233505-2661ff00-1f85-11eb-8994-7becb019de4a.png">
<img width="1440" alt="Screenshot 2020-11-05 at 8 51 56 AM" src="https://user-images.githubusercontent.com/58783823/98233516-2c57e000-1f85-11eb-9894-502fe7a5387f.png">
