### ISSUE TITLE
Change URL for Apollo

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5164]
`/apollo` change to `/wipro-apollo`

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2020-11-05 at 4 34 09 PM" src="https://user-images.githubusercontent.com/58783823/98233255-c8cdb280-1f84-11eb-97ea-5c26ea976102.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-05 at 5 22 43 PM" src="https://user-images.githubusercontent.com/58783823/98237867-907da280-1f8b-11eb-9dc4-b9f44d471bb3.png">
