### ISSUE TITLE
The forum link in the challenge page should open the forum in a separate tab 

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#5169]
**Steps**
Go to a challenge details page ex- https://qa-community-app.topcoder-dev.com/challenges/99ac6731-0c23-42a4-9193-abbde35b8394
Click CHALLENGE DISCUSSION link

**Actual result**
The forum is opened in the same tab

**Expected result**
The forum should be opened in a separate tab

**Comment by SathyaJayabal** [comment]
[forums_new_tab.mov.zip](https://github.com/topcoder-platform/community-app/files/5514823/forums_new_tab.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on dev(develop branch)
[forums.mov.zip](https://github.com/topcoder-platform/community-app/files/5528411/forums.mov.zip)
