### ISSUE TITLE
Contentful media queries fix window resize

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5172]
Contentful media queries need to trigger on window resize too. Currently, page reload on the new resolution is required to trigger media queries. The scope is to change that behavior.

Test URL: https://community-app.topcoder.com/examples/contentful/viewport/72IxVCieryAuXbDe4uPPlk
Steps:
1. Load the page at 1440px resolution
2. Resize to 1024px
3. Observe. Reload page
4. video https://drive.google.com/file/d/1Tl0Uhapij5wEWjiVdp4WGj_sXn5wDSyE/view?usp=sharing

**Comment by luizrrodrigues** [comment]
@SathyaJayabal ready for QA in Stag env.

**Comment by SathyaJayabal** [comment]
verified on staging (feature branch)
[5172.mov.zip](https://github.com/topcoder-platform/community-app/files/5509424/5172.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
[media_queries.mov.zip](https://github.com/topcoder-platform/community-app/files/5515518/media_queries.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[5172_prod.mov.zip](https://github.com/topcoder-platform/community-app/files/5517859/5172_prod.mov.zip)
