### ISSUE TITLE
Profile update not working 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#5173]
![image](https://user-images.githubusercontent.com/683231/98511037-29613600-228a-11eb-9591-26a9b5dc65aa.png)

On @mtwomey 's behalf

**Comment by SathyaJayabal** [comment]
Please try again, This seems to be  working
[5173.mov.zip](https://github.com/topcoder-platform/community-app/files/5508811/5173.mov.zip)
