### ISSUE TITLE
Sorting on MM Leaderboards wrong

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5174]
Fix sorting on MM Leaderboards
Test: https://community-app.topcoder.com/examples/contentful/contentblock/45ybaKa7q2oBzdYef90czi

**Comment by kkartunov** [comment]
@SathyaJayabal, please check

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1439" alt="Screenshot 2020-11-24 at 4 28 33 PM" src="https://user-images.githubusercontent.com/58783823/100085790-7ccea900-2e72-11eb-9ab6-9ed30d60d777.png">
<img width="1386" alt="Screenshot 2020-11-24 at 4 29 05 PM" src="https://user-images.githubusercontent.com/58783823/100085797-80623000-2e72-11eb-9d64-5acd08c4a053.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-11-24 at 7 41 24 PM" src="https://user-images.githubusercontent.com/58783823/100105201-17d47c80-2e8d-11eb-9ef2-0af91fb7f3fd.png">
<img width="1440" alt="Screenshot 2020-11-24 at 7 41 33 PM" src="https://user-images.githubusercontent.com/58783823/100105220-1c993080-2e8d-11eb-9501-977f7cac1e19.png">
