### ISSUE TITLE
Skills auto-suggest for gig work application is not working

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5196]
Should filter the skills when the user types some letters.
![Screenshot from 2020-11-17 12-44-40](https://user-images.githubusercontent.com/5585002/99380623-e3801f80-28d2-11eb-91ed-b01d29d5dc4b.png)

**Comment by kkartunov** [comment]
@SathyaJayabal please note that we move the search field on the top of the suggestion dropdown not as it was on the bottom.

**Comment by SathyaJayabal** [comment]
@kkartunov verified
<img width="1440" alt="Screenshot 2020-12-01 at 7 03 38 PM" src="https://user-images.githubusercontent.com/58783823/100747601-49f35a80-3408-11eb-9744-3547663f7cb1.png">
<img width="1440" alt="Screenshot 2020-12-01 at 7 05 53 PM" src="https://user-images.githubusercontent.com/58783823/100747626-4f50a500-3408-11eb-8b45-acd063e7ea51.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2020-12-04 at 9 56 23 AM" src="https://user-images.githubusercontent.com/58783823/101121810-0458ac80-3617-11eb-8f82-c7b6e3a25de2.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-12-04 at 1 04 11 PM" src="https://user-images.githubusercontent.com/58783823/101135174-74742c00-3631-11eb-84c4-9d8783426076.png">
