### ISSUE TITLE
Gig application fails for many skills

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5199]
Due limitation in recruit API application fails when the user selects many skills.
Expected: application to succeed
![Screenshot from 2020-11-18 11-04-21](https://user-images.githubusercontent.com/5585002/99509356-57cbc900-298e-11eb-8005-87f5bf4717fa.png)
![Screenshot from 2020-11-18 11-06-24](https://user-images.githubusercontent.com/5585002/99509370-5ac6b980-298e-11eb-9055-5234b9ac55b8.png)

**Comment by SathyaJayabal** [comment]
@kkartunov, validation error message displayed for the above scenario.
<img width="1440" alt="Screenshot 2020-12-01 at 6 58 27 PM" src="https://user-images.githubusercontent.com/58783823/100746988-75c21080-3407-11eb-96aa-f8c291d6d3da.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2020-12-04 at 9 52 51 AM" src="https://user-images.githubusercontent.com/58783823/101121695-c5c2f200-3616-11eb-86e3-33b7dc3a30cd.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-12-04 at 1 03 44 PM" src="https://user-images.githubusercontent.com/58783823/101135106-59a1b780-3631-11eb-817a-a76ef6d9fb7d.png">
