### ISSUE TITLE
My Dashboard : Displaying a blank page when token is expired

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5202]
1. Go to My Dashoard page after the token is expired
https://www.topcoder.com/my-dashboard

Expected: user must be redirected to login page
Actual: Blank page is displayed.
<img width="1440" alt="Screenshot 2020-11-19 at 1 18 31 PM" src="https://user-images.githubusercontent.com/58783823/99636792-ee20ed00-2a69-11eb-8134-3726eb1ea6f2.png">

**Comment by sachin-maheshwari** [comment]
@SathyaJayabal  How to reproduce this ?

**Comment by SathyaJayabal** [comment]
@sachin-maheshwari , you can wait for the token to expire or, open a new incognito/private window and directly access the dashboard link
https://www.topcoder.com/my-dashboard

**Comment by sachin-maheshwari** [comment]
I tried, initially blank screen, but get auto login and got screen correctly. 
<img width="1680" alt="Screenshot 2020-11-19 at 1 47 00 PM" src="https://user-images.githubusercontent.com/6467888/99639567-c764b580-2a6d-11eb-9946-890caead4b0b.png">

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues Please catch the error or check blank token before decoding. Earlier v3Token was very long expiry.    
<img width="1070" alt="Screenshot 2020-11-19 at 3 43 49 PM" src="https://user-images.githubusercontent.com/6467888/99653005-8628d180-2a7e-11eb-938b-ea7878be65c1.png">
<img width="1405" alt="Screenshot 2020-11-19 at 3 44 09 PM" src="https://user-images.githubusercontent.com/6467888/99653026-8a54ef00-2a7e-11eb-9f95-bfd6718dbaa7.png">

**Comment by luizrrodrigues** [comment]
@sachin-maheshwari I'll check this one shortly.

**Comment by sachin-maheshwari** [comment]
@luizrrodrigues thanks! also I changed in some refresh token logic. so please use this latest "auth lib" tag 1.0.3 - https://github.com/topcoder-platform/tc-auth-lib/releases/tag/1.0.3

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag env.

cc @sachin-maheshwari

**Comment by SathyaJayabal** [comment]
@luizrrodrigues verified
[dashboard.mov.zip](https://github.com/topcoder-platform/community-app/files/5613784/dashboard.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
[dashboard.mov 2.zip](https://github.com/topcoder-platform/community-app/files/5621665/dashboard.mov.2.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-12-01 at 5 23 34 PM" src="https://user-images.githubusercontent.com/58783823/100737288-f7ab3d00-33f9-11eb-90a0-d9b90ab6dec7.png">
