### ISSUE TITLE
Add additional fields to challenge page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#521]
We're adding 2 more fields to a challenge spec that are optional.  

Code Repository
Environment

Both are text fields, but will usually be entered as URLs.  They should display as part of the challenge spec when they are populated. They should only be available for development challenges.

Let's use the "Challenge Links" section for this:

![image](https://user-images.githubusercontent.com/3812270/31628806-ccb45b3a-b27f-11e7-945b-a8de0e44fee4.png)

**Comment by ajefts** [comment]
fyi @sushilshinde 

Here is a new requirement to get implemented.  This should be done on the community-app version of the challenge page.  We're adding these fields to the api response...

**Comment by ajefts** [comment]
@sushilshinde Please put this one next on your list.  Thanks.

**Comment by sushilshinde** [comment]
@ajefts yes working on it. I had a brief discussion with @skyhit last week. Today I got details, also checking code.

**Analysis** 

1. Direct app is updated for editing of these two, this is not in production yet as it is waiting for **2**
2. API Change - https://www.topcoder.com/challenge-details/30059861/?type=develop
Is about changing 
- Challenge API for save/update
- Challenge Details API for read
- Challenge List API for read
- Member challenge API for read 
3. Topcoder challenge details page for development challenges will see the two new links under CHALLENGE LINKS section, here is the mock
![challenge_details_new_fields](https://user-images.githubusercontent.com/683231/31661695-406ed10c-b359-11e7-98c5-4f780ab11879.png)

**Comment by ajefts** [comment]
yep.  Your understanding looks right.  Can you run something to get the challenge page update to support the display of the links (part 3)?

**Comment by sushilshinde** [comment]
@ajefts above changes are committed to `challenge_details_new_fields-issue#521`.
Once API is ready just mapping code will change, now I have coded the URLs.

**Comment by sushilshinde** [comment]
Challenge API has been updated on a development environment. So, I did change and commit code with these new attributes mappings into the feature branch: `challenge_details_new_fields-issue#521`. It's ready for PR, once API is pushed to the production I will create one.

Meanwhile, it's ready for review @ajefts @birdofpreyru

**Comment by sushilshinde** [comment]
Change is available at `dev`, it's ready for production.
 
**Test challenges** 

Develop challenge (Positive Test)
http://community-app.topcoder-dev.com/challenges/30051266

Design challenge (Negative Test)
http://community-app.topcoder-dev.com/challenges/30050696

Data science challenge (Negative Test)
http://community-app.topcoder-dev.com/challenges/30049604

Please review @ajefts @birdofpreyru
