### ISSUE TITLE
Viewport with animation on scroll throws error when resized

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5214]
As per the title above.
Testing https://community-app.topcoder.com/examples/contentful/viewport/ZSLKiIGgYqmYg2WBuiNit
Everything works and observe animations are displayed until the browser is resized.

**Comment by SathyaJayabal** [comment]
@kkartunov verified
[viewport.mov.zip](https://github.com/topcoder-platform/community-app/files/5615426/viewport.mov.zip)

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
[viewport.mov 2.zip](https://github.com/topcoder-platform/community-app/files/5621644/viewport.mov.2.zip)

**Comment by SathyaJayabal** [comment]
verified on prod
[viewport.mov 3.zip](https://github.com/topcoder-platform/community-app/files/5622363/viewport.mov.3.zip)
