### ISSUE TITLE
Spirit award winners for Hall of Fame

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5218]
Add space for the spirit award on the hall of fame pages https://www.topcoder.com/community/hall-of-fame/tco
Design: https://marvelapp.com/prototype/21aficcg/screen/66396378
Test URL: /community/hall-of-fame/tco/19

**Comment by SathyaJayabal** [comment]
verified @kkartunov 
<img width="1440" alt="Screenshot 2020-11-30 at 3 15 44 PM" src="https://user-images.githubusercontent.com/58783823/100593873-f6f1a880-331e-11eb-9b16-44ef146dc391.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-12-01 at 3 13 50 PM" src="https://user-images.githubusercontent.com/58783823/100723526-e0fbea80-33e7-11eb-9bc2-3366b3af58a1.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2020-12-01 at 5 19 08 PM" src="https://user-images.githubusercontent.com/58783823/100736869-6045ea00-33f9-11eb-9c9a-4abe5e31083e.png">
