### ISSUE TITLE
SEO - Show challenge name title in Social og:title

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5219]
Format: 
```[$100/$50] Challenge name```

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed in QA env

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified
<img width="535" alt="Screenshot 2020-12-04 at 8 50 08 AM" src="https://user-images.githubusercontent.com/58783823/101117837-ef2b5000-360d-11eb-918d-b3b7725024a4.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="528" alt="Screenshot 2020-12-04 at 10 09 14 AM" src="https://user-images.githubusercontent.com/58783823/101122815-5ef30800-3619-11eb-8f42-9619bb4f437d.png">
<img width="532" alt="Screenshot 2020-12-04 at 10 09 43 AM" src="https://user-images.githubusercontent.com/58783823/101122819-60bccb80-3619-11eb-85c7-d1ffcda587bf.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="541" alt="Screenshot 2020-12-04 at 1 17 58 PM" src="https://user-images.githubusercontent.com/58783823/101136503-6de6b400-3633-11eb-8635-f8f88240ab11.png">
<img width="541" alt="Screenshot 2020-12-04 at 1 19 31 PM" src="https://user-images.githubusercontent.com/58783823/101136521-7343fe80-3633-11eb-85f2-981487767285.png">
