### ISSUE TITLE
Add Terms flow when joining a community

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#522]
Each community should be configurable to require 1 or more terms to be agreed to by the user as they join.  The terms can be an array of Terms Ids in the communities config file.

Let's try to reuse the terms flow we have for the new challenge pages as much as possible.

**Comment by birdofpreyru** [comment]
I've launched the [challenge](https://www.topcoder.com/challenge-details/30059817/?type=develop&noncache=true) to address this.

**Comment by birdofpreyru** [comment]
It was done in the challenge referrenced above
