### ISSUE TITLE
SubCommunities not displayed in Dashboard page

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5226]
Description:

Communities were not displayed under the My Communities tab of Dashboard page.

Account used: TonyJ

![image](https://user-images.githubusercontent.com/55895538/100869825-f43eb100-34e0-11eb-9cef-85c3f99f8bd7.png)

**Comment by sandhiyakavi** [comment]
cc: @lakshmiathreya

**Comment by lakshmiathreya** [comment]
Groups of Tonyj user in Dev:
<img width="1680" alt="Screenshot 2020-12-02 at 7 28 46 PM" src="https://user-images.githubusercontent.com/51733042/100882032-b045af00-34d4-11eb-8f9b-8aa2dcc17403.png">
<img width="1680" alt="Screenshot 2020-12-02 at 7 28 59 PM" src="https://user-images.githubusercontent.com/51733042/100882062-bcca0780-34d4-11eb-8f25-9e2eeb805e0a.png">

**Comment by lakshmiathreya** [comment]
cc @rootelement

**Comment by lakshmiathreya** [comment]
Prod for reference:
<img width="1680" alt="Screenshot 2020-12-02 at 7 42 16 PM" src="https://user-images.githubusercontent.com/51733042/100883641-90af8600-34d6-11eb-8426-93643124a554.png">
<img width="1680" alt="Screenshot 2020-12-02 at 7 38 19 PM" src="https://user-images.githubusercontent.com/51733042/100883679-9d33de80-34d6-11eb-8fb9-60d06502b62c.png">

**Comment by callmekatootie** [comment]
Could you check again. It might have been the bug I introduced in dev (that has since been resolved).

For user TonyJ, I see the communities now:

![image](https://user-images.githubusercontent.com/2317133/101285936-fc169200-380d-11eb-90e0-003d05577c41.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod. Able to view the sub communities.

![image](https://user-images.githubusercontent.com/55895538/102864831-299f4480-4478-11eb-81a9-cbcfaf4e6cdb.png)
