### ISSUE TITLE
Only public communities displayed in the Subcommunities Filter of Challenge listings page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5227]
Description:
Only public communities displayed in the Subcommunities Filter of Challenge listings page.

Account used: TonyJ

![image](https://user-images.githubusercontent.com/55895538/100870523-197fef00-34e2-11eb-9069-5cf6e1590415.png)

**Comment by sandhiyakavi** [comment]
cc: @lakshmiathreya

**Comment by lakshmiathreya** [comment]
cc @rootelement

**Comment by lakshmiathreya** [comment]
Please note comparison for Subcommunities Filter for Prod and Dev - Groups info of the User included for reference:
<img width="1680" alt="Screenshot 2020-12-02 at 7 38 19 PM" src="https://user-images.githubusercontent.com/51733042/100883305-33b3d000-34d6-11eb-8181-a386f6333661.png">

<img width="1680" alt="Screenshot 2020-12-02 at 7 37 40 PM" src="https://user-images.githubusercontent.com/51733042/100883272-2ac2fe80-34d6-11eb-9563-cf2b86be3c88.png">

<img width="1680" alt="Screenshot 2020-12-02 at 7 36 31 PM" src="https://user-images.githubusercontent.com/51733042/100883265-2860a480-34d6-11eb-927c-79a71906a902.png">
<img width="1680" alt="Screenshot 2020-12-02 at 7 35 44 PM" src="https://user-images.githubusercontent.com/51733042/100883248-226ac380-34d6-11eb-8ecd-fb3cb5d45aa1.png">

**Comment by callmekatootie** [comment]
Could you check again - it might have been the bug I introduced in dev (that has since been resolved). I see the following communities for TonyJ now (in dev):

![image](https://user-images.githubusercontent.com/2317133/101286030-59124800-380e-11eb-8a50-11c3f73d5461.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/102866474-a9c6a980-447a-11eb-85bf-6806c5d48977.png)
