### ISSUE TITLE
Enable/Disable communities in Settings page doesn't affect the members group.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5228]
Description:
Enable/Disable communities in Settings page doesn't affect the members group.

![image](https://user-images.githubusercontent.com/55895538/100871104-0de0f800-34e3-11eb-9375-5e331152d63c.png)

cc: @lakshmiathreya

**Comment by lakshmiathreya** [comment]
Removing Groups from User via Admin also doesn't work.

**Comment by sandhiyakavi** [comment]
Verified in Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/102866129-20af7280-447a-11eb-8ef2-70a550e3a81c.png)

![image](https://user-images.githubusercontent.com/55895538/102866083-11302980-447a-11eb-9624-c945cf38d8e7.png)
