### ISSUE TITLE
Hall of fame - fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5229]
- Browse Photos button to be fixed so the text shows in one line only
- The photo of the champions looks cut at the bottom by the gray area...we should see the faces of Tong, Victor and Sergey full size as well
- On Fun Facts, for each card, between the green line and the photo above there is some white space - let's remove that so it follows the design
- On Fun Facts - text outside the box
- All Time champions - the trophies icons on the right side are using outline icons but we have filled icons in the design - please fix
TCO Spirit Award has design changed see https://marvelapp.com/prototype/21aficcg/screen/75128755
- QA column needs to be green color

**Comment by sandhiyakavi** [comment]
Verified.Working as expected.

Point 1 & 2:
![image](https://user-images.githubusercontent.com/55895538/101346395-d0f27800-38cb-11eb-80e2-96169ceb364d.png)

Point 3 & 4:
![image](https://user-images.githubusercontent.com/55895538/101346542-0ac37e80-38cc-11eb-92aa-e815ee914062.png)

Point 5:
![image](https://user-images.githubusercontent.com/55895538/101346772-655cda80-38cc-11eb-8edb-ee666eef3e45.png)
![image](https://user-images.githubusercontent.com/55895538/101346827-7e658b80-38cc-11eb-8a5c-75e0efa8e7b8.png)

Point 6:
![image](https://user-images.githubusercontent.com/55895538/101346865-8c1b1100-38cc-11eb-9e39-65932a06e81b.png)

**Comment by SathyaJayabal** [comment]
verified on  staging (develop branch)
<img width="1440" alt="Screenshot 2020-12-11 at 11 40 24 AM" src="https://user-images.githubusercontent.com/58783823/101869823-5ca72580-3ba6-11eb-8175-3d51756da82a.png">
<img width="1440" alt="Screenshot 2020-12-11 at 11 41 47 AM" src="https://user-images.githubusercontent.com/58783823/101869833-63ce3380-3ba6-11eb-9f2f-3fba337e1978.png">
<img width="1440" alt="Screenshot 2020-12-11 at 11 43 56 AM" src="https://user-images.githubusercontent.com/58783823/101869836-6466ca00-3ba6-11eb-843a-2044c7b359fb.png">
<img width="1440" alt="Screenshot 2020-12-11 at 11 44 14 AM" src="https://user-images.githubusercontent.com/58783823/101869838-6597f700-3ba6-11eb-85d1-e0105ee63919.png">
<img width="1440" alt="Screenshot 2020-12-11 at 11 44 50 AM" src="https://user-images.githubusercontent.com/58783823/101869841-6597f700-3ba6-11eb-9c09-fabe47c71e30.png">

**Comment by SathyaJayabal** [comment]
@kkartunov , there still seems to be some space here. 
`On Fun Facts, for each card, between the green line and the photo above there is some white space - let's remove that so it follows the design`

<img width="1440" alt="Screenshot 2020-12-11 at 11 41 47 AM" src="https://user-images.githubusercontent.com/58783823/101870072-e48d2f80-3ba6-11eb-870b-dce31510260d.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-12-11 at 3 07 32 PM" src="https://user-images.githubusercontent.com/58783823/101887462-e82eaf80-3bc2-11eb-98fd-d57588fc430b.png">
<img width="1440" alt="Screenshot 2020-12-11 at 3 08 02 PM" src="https://user-images.githubusercontent.com/58783823/101887480-efee5400-3bc2-11eb-9d18-5698e1dbf16e.png">
<img width="1440" alt="Screenshot 2020-12-11 at 3 08 33 PM" src="https://user-images.githubusercontent.com/58783823/101887482-f086ea80-3bc2-11eb-8f24-bbe49b8ac2f9.png">
<img width="1440" alt="Screenshot 2020-12-11 at 3 08 51 PM" src="https://user-images.githubusercontent.com/58783823/101887486-f1b81780-3bc2-11eb-90bc-73bafe584327.png">
<img width="1440" alt="Screenshot 2020-12-11 at 3 09 15 PM" src="https://user-images.githubusercontent.com/58783823/101887502-f7156200-3bc2-11eb-91d3-4a348c6625ab.png">
