### ISSUE TITLE
Gig listing page updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5241]
On https://www.topcoder.com/gigs

-  change the logic so that “Any Location” displays gigs with “Any Location” only
- update the “Anywhere” filter to read as “All” and keep the logic behind it
- change compensation to format: $800-900 (USD) / week

**Comment by sandhiyakavi** [comment]
Verified in Test Environment.

Point 1:
![image](https://user-images.githubusercontent.com/55895538/101350574-858f9800-38d2-11eb-87c9-0475da2e82a7.png)

Point 2:
![image](https://user-images.githubusercontent.com/55895538/101350723-cd162400-38d2-11eb-9d14-660664d020a5.png)

Point 3:
![image](https://user-images.githubusercontent.com/55895538/101350814-fe8eef80-38d2-11eb-80a5-75ba6f03f1c8.png)

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2020-12-11 at 11 35 18 AM" src="https://user-images.githubusercontent.com/58783823/101869412-68deb300-3ba5-11eb-8c10-2ede7bd6e386.png">
<img width="1440" alt="Screenshot 2020-12-11 at 11 36 43 AM" src="https://user-images.githubusercontent.com/58783823/101869418-6e3bfd80-3ba5-11eb-9146-6cf7766b0722.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2020-12-11 at 3 03 52 PM" src="https://user-images.githubusercontent.com/58783823/101886905-2d9ead00-3bc2-11eb-87f0-3d5e845e46ee.png">
<img width="1440" alt="Screenshot 2020-12-11 at 3 03 58 PM" src="https://user-images.githubusercontent.com/58783823/101886923-33948e00-3bc2-11eb-8e20-799892fa2b0b.png">
