### ISSUE TITLE
 Remove “Availabillity per week” in gig application form

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5261]
As per title.

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2020-12-18 at 2 13 04 PM" src="https://user-images.githubusercontent.com/58783823/102597353-87fab900-4140-11eb-8c00-de20da444376.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1424" alt="Screenshot 2020-12-22 at 7 08 09 PM" src="https://user-images.githubusercontent.com/58783823/102894423-15b00e80-4489-11eb-8b9c-490f2b30188b.png">

**Comment by sandhiyakavi** [comment]
Verified in Prod. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/102957126-fcf13880-451c-11eb-9d3e-ff924d280a3e.png)
