### ISSUE TITLE
Update tc-auth-lib to v1.0.4

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5262]
Update tc-auth-lib to v1.0.4

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed in Stag env

cc @sachin-maheshwari

**Comment by sandhiyakavi** [comment]
Verified. Working as expected.

The following functionalities are tested.

1. Direct Signup
2. Login
3. Community app All page access
4. Register, Unregister and Submit for a challenge.
5. Token refresh
6. Logout.

**Comment by sachin-maheshwari** [comment]
Thanks! guys.

**Comment by SathyaJayabal** [comment]
verified the following on staging (develop branch)
Direct Signup
Login
Community app All page access
Register, Unregister and Submit for a challenge.
Token refresh
Logout.

**Comment by sandhiyakavi** [comment]
Verified the below functionalities on Prod.Working as expected.

1. Direct Signup
2. Login
3. Password Reset
4. Community app All page access
5. Register, Unregister and Submit for a challenge.
6. Token refresh
7. Logout.
