### ISSUE TITLE
Unable to type space while searching the challenge

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/community-app#5264]
**Steps** 
 1. Try to type "Topcoder Admin" on Challenge search box.
**Reference**  

![image](https://user-images.githubusercontent.com/25297859/102772906-6dc71200-43b0-11eb-837e-0d128e483392.png)

**Comment by luizrrodrigues** [comment]
@SathyaJayabal @sandhiyakavi Deployed in QA env.

**Comment by SathyaJayabal** [comment]
verified
<img width="1429" alt="Screenshot 2020-12-22 at 2 46 01 PM" src="https://user-images.githubusercontent.com/58783823/102871588-9ad4fc80-4464-11eb-8afb-02f30ff2007f.png">
<img width="1426" alt="Screenshot 2020-12-22 at 2 46 58 PM" src="https://user-images.githubusercontent.com/58783823/102871656-b0e2bd00-4464-11eb-9442-9e0a34d94ac2.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1424" alt="Screenshot 2020-12-22 at 7 09 11 PM" src="https://user-images.githubusercontent.com/58783823/102894513-3a0beb00-4489-11eb-8ece-b71884beab3b.png">

**Comment by sandhiyakavi** [comment]
Verified in Prod.Working as expected.

![image](https://user-images.githubusercontent.com/55895538/102957514-edbeba80-451d-11eb-9ed5-7d202a955f22.png)
