### ISSUE TITLE
Thtive - track filter updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5284]
Update the track filter to match design and functionality as shown here: https://marvelapp.com/prototype/528hj20/screen/73566938

**Comment by kkartunov** [comment]
@SathyaJayabal this ready for QA on staging, please and thanks.

**Comment by SathyaJayabal** [comment]
@kkartunov , verified on staging (feature branch)
<img width="1440" alt="Screenshot 2021-01-21 at 3 07 12 PM" src="https://user-images.githubusercontent.com/58783823/105334405-d9dda580-5bfc-11eb-96b1-32bd99c83a0d.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-01-26 at 11 15 33 PM" src="https://user-images.githubusercontent.com/58783823/105883077-6e486d80-602c-11eb-99e4-7e2f3545884d.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-27 at 1 45 46 AM" src="https://user-images.githubusercontent.com/58783823/105899952-65ae6200-6041-11eb-98e7-2af197b05f68.png">
