### ISSUE TITLE
Hide My Communities from My Dashboard

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5288]
Hide My Communities from My Dashboard

**Comment by luizrrodrigues** [comment]
@sandhiyakavi Deployed in QA env.

**Comment by sandhiyakavi** [comment]
Verified in QA Env.

![image](https://user-images.githubusercontent.com/55895538/103880576-a8ed7300-511c-11eb-8ce3-c6c1b4ceb1a5.png)

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-01-07 at 5 37 09 PM" src="https://user-images.githubusercontent.com/58783823/103890988-08448680-510f-11eb-913d-713358ad72da.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-07 at 11 06 28 PM" src="https://user-images.githubusercontent.com/58783823/103925095-08f41180-513d-11eb-89e6-8728ed9de7fe.png">
