### ISSUE TITLE
Impliment CCI approval w/f for automated test cases

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#5293]
Implement https://circleci.com/docs/2.0/workflows/#holding-a-workflow-for-a-manual-approval for automated test cases

(https://circleci.com/blog/manual-job-approval-and-scheduled-workflow-runs)

**References repo:** 
https://github.com/topcoder-platform/tc-project-service/blob/develop/.circleci/config.yml

**Comment by luizrrodrigues** [comment]
@sushilshinde  Implemented manual approval to ci-manual-approval branch.
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/2419/workflows/358eec5e-fdc6-4606-beeb-a38d62c77a6e

Please take a look and let me know if this working as expected. (note: Currently after approve workflow will deploy to Stag just for testing)

**Comment by SathyaJayabal** [comment]
verified approval flow for smoke test build on staging
<img width="1154" alt="Screenshot 2021-01-14 at 6 50 25 PM" src="https://user-images.githubusercontent.com/58783823/104596038-6e925180-5699-11eb-9fc4-e0bf75567fd9.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , lets close this one after configuration done for `build-prod`

**Comment by SathyaJayabal** [comment]
Approval workflow implemented for prod
<img width="1440" alt="Screenshot 2021-01-15 at 1 24 23 PM" src="https://user-images.githubusercontent.com/58783823/104697031-2163bd80-5735-11eb-9665-788b8f60709b.png">
