### ISSUE TITLE
Automated Smoke Test Integration

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5294]

**Comment by luizrrodrigues** [comment]
**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC_006] should verify whether the user is able to search for a challenge by using the Search challenges textbox**
- API issue, looks like currently have issue to search for challenge name

-----

**Comment by SathyaJayabal** [comment]
Verified smoke test run staging  build.
<img width="1440" alt="Screenshot 2021-01-14 at 6 50 40 PM" src="https://user-images.githubusercontent.com/58783823/104596114-95508800-5699-11eb-8521-d43ad030e6e9.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , lets close this one after configuration done for `build-prod`

**Comment by SathyaJayabal** [comment]
Smoke test running on prod.
<img width="1440" alt="Screenshot 2021-01-15 at 1 24 23 PM" src="https://user-images.githubusercontent.com/58783823/104696990-1446ce80-5735-11eb-9852-84de14a9de96.png">
