### ISSUE TITLE
Update vets community content

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#530]
[Veterans.topcoder web layout, Ted Bullard edition.pdf](https://github.com/topcoder-platform/community-app/files/1398647/Veterans.topcoder.web.layout.Ted.Bullard.edition.pdf)

- No leaderboard page for now
- groupId = 20000013
- Include the join feature

**Comment by ajefts** [comment]
images...

[retopcoderforveteransproject.zip](https://github.com/topcoder-platform/community-app/files/1398801/retopcoderforveteransproject.zip)

**Comment by birdofpreyru** [comment]
@ajefts In principle done. I've noticed, though, that I've overlooked the point about group ID. Right now the Veterans Community is configured to use the group `20000007` for everything. As you have also done some modifications yourself, and did not touch it, I wanna double-check, should I change it to `20000013`, or we keep `20000007`?

**Comment by ajefts** [comment]
Good catch. It should be 20000013
