### ISSUE TITLE
Gig application error page fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5300]
Update the page:
![image](https://user-images.githubusercontent.com/5585002/104559793-978cf500-564d-11eb-9078-5c44bf45f155.png)

- add the error message as returned from API to that “oops” page
- add the text: “Please send us an email at gigwork@topcoder.com with the subject ‘Gig Error’ and paste the URL for the gig you are attempting to apply for so that we know of your interest”
- add a white button - "VIEW OTHER GIGS" linked to the gig listings page

**Comment by kkartunov** [comment]
For QA: an easy way to test this is by mocking the offline state in the network tab.
![image](https://user-images.githubusercontent.com/5585002/108812802-6bec1b80-75b8-11eb-91dc-95ca23edf36b.png)

**Comment by SathyaJayabal** [comment]
@kkartunov , I dont find this deployed yet.

**Comment by SathyaJayabal** [comment]
verified on qa env
<img width="1440" alt="Screenshot 2021-02-24 at 12 44 35 PM" src="https://user-images.githubusercontent.com/58783823/108961988-2013a200-769e-11eb-92aa-814a36bacbfb.png">

**Comment by SathyaJayabal** [comment]
verified on staging - develop branch
<img width="1440" alt="Screenshot 2021-02-25 at 6 42 46 PM" src="https://user-images.githubusercontent.com/58783823/109158463-6863ba80-7799-11eb-88d3-c00091223f66.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-02-25 at 9 03 39 PM" src="https://user-images.githubusercontent.com/58783823/109176583-f9905c80-77ac-11eb-8ce9-6ba453769ec9.png">
