### ISSUE TITLE
Gig Page: "Go To Challenges" link URL not filtering challenges by "Skill Builder"

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5306]
Description:

Clicking "Go to Challenges" link in Gigs page, not filtering challenges by "Skill Builder" in Challenge listings page.

Steps to Reproduce:

1. Go to the Gig Work page.
2.  Click "Go to Challenges" button at the bottom of the page.

Actual Result:
Page is directed to the Challenge Listing page and Challenges are not filtered by the "Skill Builder" term.

Expected Result:
Only Skill builder Challenges should be displayed.
 
![image (19)](https://user-images.githubusercontent.com/55895538/104704088-8f22e000-575b-11eb-895d-65958892fedc.png)

https://user-images.githubusercontent.com/55895538/104704211-b679ad00-575b-11eb-9db0-a7fe32406da9.mp4

**Comment by kkartunov** [comment]
Thank you @sandhiyakavi, fixed now.
