### ISSUE TITLE
Automated Smoke Testing Fix Test Cases

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5307]
WIP : Report

-----

**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC_002] should verify whether the current page is redirected to Registration page on clicking the Log in button**
- This working well in local env, so I thin maybe can be issue with vars in Env?

-----

**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC_006] should verify whether the user is able to search for a challenge by using the Search challenges textbox**
- API issue, looks like currently have issue to search for challenge name

-----

**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC-007] should verify that the "Filter" button is working correctly**
- This test not valid anymore, filter now is always visible.

-----

**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC-008] should verify that the "Filter" option "keywords" is working correctly**
- This test not valid anymore
- Filter by tag/skill was removed
- Now need to use search field

-----

**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC-009] should verify that the "Filter" option "Type" is working correctly**
- Filter by `Type` was changed from dropdown to checkbox, need update whole logic here.

-----

**Topcoder Challenge Listing Page Tests:  Before Login Test Cases [TC-010] should verify that the "Filter" option "Sub Community" is working correctly**
- Filter always open now, and changed some fields too.

-----

**Before Login Test Cases [TC-011] should verify that the "Filter" option for "Date range" is working correctly**
- Data range filter just show up if select `Past Challenge` and `Custom Date` in  `Past Period`

-----

**Before Login Test Cases [TC_012] should verify whether the challenges are filtered according to the keyword/Type/Sub community/Date range fields selected under the Filter function**
- Need re-write this one, because filter received a lot of changes

-----

**Before Login Test Cases [TC_013] should verify whether the user is able to select more than one keyword/Type under the filter function**
- This test not valid anymore
- Filter by tag/skill was removed
- Now need to use search field

-----

**Before Login Test Cases [TC_014] should verify whether the cross symbol inside the textbox keyword/Type filters removes the selected keyword/Type**
- This test not valid anymore
- Filter by tag/skill was removed
- Now need to use search field

-----

**Before Login Test Cases [TC_015] should verify whether the number of filters applied are shown into Filter button according to the keyword/Type/Sub community/Date range fields selected**
- This test not valid anymore
- The new field area haven't a total of active filters

-----

**Before Login Test Cases [TC_016] should verify whether the clear filter button clears all the filters selected and all the challenges are displayed**
- This test not valid anymore
- `Clear Filters` button was removed

-----

**Before Login Test Cases [TC_017] should verify whether the Clear filter button is deactivated into filter function**
- This test not valid anymore
- `Clear Filters` button was removed

-----

**Before Login Test Cases [TC-020] should verify that when user selects a challenge "tag", only challenges under the selected tag are shown**
- Challenge Tag changed from <button> to <a> in Challenge Details page

-----

**Before Login Test Cases [TC-021] should verify that the challenge count matches the number of challenges displayed**
- **FIXED**

-----

**Before Login Test Cases [TC-022] should verify that the challenge count remains the same when switching to the challenge details and then back to the challenge listings page**
- **FIXED**

-----

**Before Login Test Cases [TC-023] should verify All Challenges link functionality with the design, development, data science and QA toggle switches on**
- **FIXED**

-----

**Before Login Test Cases [TC-024] should verify All Challenges link functionality with the design, development, data science and QA toggle switches Off**
- **FIXED**

-----

**With Login tests [TC_028] should verify whether the current page is redirected to my profile page on clicking the my profile under the Username menu.**
- This working well in local env, so I thin maybe can be issue with vars in Env?

-----

**With Login tests [TC_030] should verify whether the current page is redirected to the settings page on clicking the settings under the Username menu**
- This working well in local env, so I thin maybe can be issue with vars in Env?

-----

**[TC_031] should verify whether the logout happens on clicking the logout under the Username menu**
- This working well in local env, so I thin maybe can be issue with vars in Env?

-----

**With Login tests [TC_032] should verify whether the user is able to search the member by their username/skill using the search icon**
- This working well in local env, so I thin maybe can be issue with vars in Env?

-----

**With Login tests [TC_033] should verify whether all the my challenges, open for registration are listed on clicking the Challenge tab**
- This working well in local env, so I thin maybe can be issue with vars in Env?

-----

**Comment by luizrrodrigues** [comment]
@drasticdpk @sushilshinde @lakshmiathreya Here details about each test case falling, some was fixed with `test-automation-fix` branch

I think we need to run a challenge to fix / rewrite test cases

**Comment by SathyaJayabal** [comment]
qa pass on staging
