### ISSUE TITLE
Update Segment script

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#5313]
To comply with the latest security model, we need to update the segment script that is being included in the app.

Please refer to https://help.trychameleon.com/en/articles/4281577-using-secure-identity-verification-beta for the full explanation. We will be using the approach of modifying the want we include and call the Segment script.

Here is an example of the code that needs to be added/modified.  Also see the attachment.

<img width="1023" alt="Screen Shot 2021-01-15 at 10 21 31 AM (1)" src="https://user-images.githubusercontent.com/3812270/105500538-05aa6b00-5c91-11eb-9b34-f129fdb90836.png">

[topcoder-segment-example.js (1).txt](https://github.com/topcoder-platform/community-app/files/5856295/topcoder-segment-example.js.1.txt)

**Expected behavior**
Notify @ajefts and @jswheeler once this is updated and they can verify if the change is functioning.

**Note**
The uid_hash can be obtained from @ajefts or @jswheeler AND needs to be included as an env var so it doesn't get publicly exposed.

**Comment by ajefts** [comment]
fyi @Oanh-and-only-Oanh.  Can we put this one on the P1 list?

**Comment by ajefts** [comment]
Please see the comments on https://github.com/appirio-tech/connect-app/issues/4282 for updated advice on how to implement this.

**Comment by luizrrodrigues** [comment]
Challenge: https://www.topcoder.com/challenges/1c31d453-bc55-468c-8f1c-41b75a7898b1

**Comment by luizrrodrigues** [comment]
@ajefts @jswheeler Can you share the API Key in Slack please?

**Comment by ajefts** [comment]
@luizrrodrigues Just checking when  this one will be released?  I keep seeing the milestone adjusted, but not sure what that means for the dates.  Thanks.

**Comment by luizrrodrigues** [comment]
Hey @ajefts sorry delay on this. I forget to update status here, we deployed this to QA, but failed, implementation have an issue, I'll include this to next release Thursday.

**Comment by Oanh-and-only-Oanh** [comment]
thanks for the update @luizrrodrigues

**Comment by SathyaJayabal** [comment]
verified on staging

Network tab there are be 2 requests POST to https://api.segment.io/v1/i, one will send it to segment and one will send only to chameleon (with request payload { integrations: { All: false, Chameleon: true }})
<img width="906" alt="Screenshot 2021-04-15 at 5 25 24 PM" src="https://user-images.githubusercontent.com/58783823/114865234-95cefb00-9e0f-11eb-8abc-83fae02cd7f2.png">
<img width="1440" alt="Screenshot 2021-04-15 at 5 19 40 PM" src="https://user-images.githubusercontent.com/58783823/114865012-53a5b980-9e0f-11eb-8fe1-8bfa0e2c119f.png">


Different accounts have different uid_hash values
<img width="1440" alt="Screenshot 2021-04-15 at 5 19 44 PM" src="https://user-images.githubusercontent.com/58783823/114865100-6e782e00-9e0f-11eb-92a1-9c4cf1cd62c0.png">
<img width="1440" alt="Screenshot 2021-04-15 at 5 21 32 PM" src="https://user-images.githubusercontent.com/58783823/114865119-73d57880-9e0f-11eb-8fec-c5e645b0f6f8.png">

**Comment by SathyaJayabal** [comment]
verified on staging(develop branch)

Network tab there are be 2 requests POST to https://api.segment.io/v1/i, one will send it to segment and one will send only to chameleon (with request payload { integrations: { All: false, Chameleon: true }})
<img width="825" alt="Screenshot 2021-04-15 at 6 28 40 PM" src="https://user-images.githubusercontent.com/58783823/114872985-75f00500-9e18-11eb-811e-21d10328d014.png">
<img width="828" alt="Screenshot 2021-04-15 at 6 28 49 PM" src="https://user-images.githubusercontent.com/58783823/114873003-79838c00-9e18-11eb-9481-9bff0247c519.png">
Different accounts have different uid_hash values
<img width="1440" alt="Screenshot 2021-04-15 at 6 29 35 PM" src="https://user-images.githubusercontent.com/58783823/114873157-a5067680-9e18-11eb-945a-a7f68bfa747a.png">
<img width="1440" alt="Screenshot 2021-04-15 at 6 29 53 PM" src="https://user-images.githubusercontent.com/58783823/114873191-a9cb2a80-9e18-11eb-8529-0f1139c9e493.png">

**Comment by SathyaJayabal** [comment]
verified on prod
Network tab there are 2 requests POST to https://api.segment.io/v1/i, one will send it to segment and one will send only to chameleon (with request payload { integrations: { All: false, Chameleon: true }})
<img width="829" alt="Screenshot 2021-04-15 at 7 28 18 PM" src="https://user-images.githubusercontent.com/58783823/114881737-e6028900-9e20-11eb-8932-0f8cde989a3c.png">
<img width="826" alt="Screenshot 2021-04-15 at 7 28 35 PM" src="https://user-images.githubusercontent.com/58783823/114881752-e9961000-9e20-11eb-8e48-a5b4e72d73c8.png">
Different accounts have different uid_hash values
<img width="831" alt="Screenshot 2021-04-15 at 7 30 10 PM" src="https://user-images.githubusercontent.com/58783823/114881952-16e2be00-9e21-11eb-9d15-fafb343a2c6b.png">
<img width="822" alt="Screenshot 2021-04-15 at 7 30 34 PM" src="https://user-images.githubusercontent.com/58783823/114881976-1a764500-9e21-11eb-9c5e-9c317ca75dbc.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I'll reopen this one until @ajefts check.

@ajefts This one was release, please let me know if working well in your side.

Thanks.
