### ISSUE TITLE
Challenges Listing showing blank page when some challenge missing prizes in placementPrizes

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5314]
Challenges Listing showing blank page when some challenge missing prizes in placementPrizes

**Comment by SathyaJayabal** [comment]
verified on staging and dev envs (develop branch)
<img width="1440" alt="Screenshot 2021-01-26 at 11 12 46 PM" src="https://user-images.githubusercontent.com/58783823/105882755-072ab900-602c-11eb-948a-9fc5db1315e6.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-01-27 at 1 46 23 AM" src="https://user-images.githubusercontent.com/58783823/105900022-7fe84000-6041-11eb-90be-22310d8e9fea.png">
