### ISSUE TITLE
Recommended checkbox functionality

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5319]
Recommended checkbox must not be part of the challenge type group. 
It must a standalone checkbox

<img width="436" alt="Screenshot 2021-01-27 at 3 37 03 PM" src="https://user-images.githubusercontent.com/58783823/105976274-f757b700-60b5-11eb-89ae-5fcd8b17a4e6.png">

At present checking the recommended checkbox, deselects the challenge type checkboxes. This must not be the case.

**Comment by dedywahyudi** [comment]
Ok, clear about this requirement

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-02-01 at 8 36 33 AM" src="https://user-images.githubusercontent.com/58783823/106410333-a571b100-6468-11eb-9cd0-f7a2ce39358b.png">
