### ISSUE TITLE
Sorting of recommended challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5321]
Is the sort by best match applied to  all "Open for Registration" challenges or only to the filtered list of recommended challenges (challenges that have a match score above a certain threshold) ?

**Comment by Oanh-and-only-Oanh** [comment]
For the simple UI, it will be applied only to the filtered list of recommended challenges

**Comment by SathyaJayabal** [comment]
SUM UP : 
1. When recommended checkbox is checked, add sort option `best match` to Open for Registration bucket
2. This is the default sort option
3. When selected sorts the list fo challenges by match score in descending order
4. When recommended checkbox is unchecked, remove sort option `best match` 

cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
tracking all requirements here
#5325
