### ISSUE TITLE
Filtering of recommended challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5322]
Challenges with a match score above a certain threshold will be displayed when recommended filter check box is selected.

1. What is the threshold value? 
2. Will these recommended challenges be displayed under a new bucket `recommended challenges`  or the `open for registration` bucket will simply be filtered to only show the recommended  challenges ?

**Comment by Oanh-and-only-Oanh** [comment]
These recommended challenges should be displayed under the` open for registration bucket` will simply be filtered to only show the recommended challenges ?

**Comment by Oanh-and-only-Oanh** [comment]
- match score should be converted into percentage.
- percentage match should be displayed on FE

**Comment by SathyaJayabal** [comment]
Based on the call, the threshold value is anything above 0 %

**Comment by SathyaJayabal** [comment]
Sum Up:
1. Recommended Checkbox displayed only for Open for Registration bucket
2. Recommended Checkbox is displayed only for logged in users
3. When recommended check box is checked, make a call to the recommender api with user's handle. Api returns list of open for registration challenges with match score for each.
4. Filter the "Open for Registration" bucket with challenges that have a match score above 0.
5. Default sorting is by `best match` (sorting by match score in desc order) .
6. If user does not have any challenge with non 0 match score (ie no recommendations) show this text 
"There are no challenges open for registration at the moment that match your skills. Try exploring other challenges or checking back later.”
cc @Oanh-and-only-Oanh , anything missing?

**Comment by Oanh-and-only-Oanh** [comment]
1. We also want to make sure that user can further filter within the "Recommended" list. For example, show only Challenges or F2F. 

2. The default when "Recommended" in ON, is all Types (CH, TSK, F2F) and tracks (design, DD, Dev, QA) should be selected. 

3. Update count to show correct count of "Recommended" challenges

**Comment by SathyaJayabal** [comment]
> 2. The default when "Recommended" in ON, is all Types (CH, TSK, F2F) and tracks (design, DD, Dev, QA) should be selected.

@Oanh-and-only-Oanh when recommended is on, we should just leave the other filters as they were. right?  For example, if the user already has his filter set to only `data science` track `challenge` type, checking on recommended must not reset these filters. 

Am I right ?

**Comment by Oanh-and-only-Oanh** [comment]
You may be right, but I'm also concerned this will further limit how many recommended challenges will show up if we did that. I'd rather show every Recommended challenge and then have user filter future for now and see what users say.

**Comment by SathyaJayabal** [comment]
Ok so, when recommended is on, all Types (CH, TSK, F2F) and tracks (design, DD, Dev, QA) should be selected.

**Comment by dedywahyudi** [comment]
Thanks for the feedback @SathyaJayabal @Oanh-and-only-Oanh 

I'll get all these fixed by asking previous winner to fix OR using F2F
We will need extra payment for the fixes.

**Comment by SathyaJayabal** [comment]
tracking all requirements here
https://github.com/topcoder-platform/community-app/issues/5325
