### ISSUE TITLE
Gig Listings: Issues in Location dropdown

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5354]
Description:

1. Field name is missing for Location dropdown.
![image](https://user-images.githubusercontent.com/55895538/108072306-11c7f380-70aa-11eb-9427-6cb70850b0cc.png)

2.  If a location is selected from dropdown, the selected location is not appearing in the field.

https://user-images.githubusercontent.com/55895538/108072883-ca8e3280-70aa-11eb-9cbb-0e197815e7d5.mp4

**Comment by SathyaJayabal** [comment]
@kkartunov , I dont find this deployed yet.

**Comment by SathyaJayabal** [comment]
verified on qa
<img width="1440" alt="Screenshot 2021-02-24 at 12 37 00 PM" src="https://user-images.githubusercontent.com/58783823/108961269-189fc900-769d-11eb-872f-8427e9ef8b3e.png">
<img width="1440" alt="Screenshot 2021-02-24 at 12 37 22 PM" src="https://user-images.githubusercontent.com/58783823/108961295-22c1c780-769d-11eb-98e3-9b6aea3a47d2.png">
<img width="1440" alt="Screenshot 2021-02-24 at 12 37 26 PM" src="https://user-images.githubusercontent.com/58783823/108961306-26554e80-769d-11eb-9f17-db35210b67aa.png">

**Comment by SathyaJayabal** [comment]
verified on staging  (develop branch)
<img width="1440" alt="Screenshot 2021-02-25 at 6 40 09 PM" src="https://user-images.githubusercontent.com/58783823/109158127-f5f2da80-7798-11eb-9ef5-6b969e239ca1.png">
<img width="1440" alt="Screenshot 2021-02-25 at 6 40 13 PM" src="https://user-images.githubusercontent.com/58783823/109158137-fab78e80-7798-11eb-96b9-07ef355e7d34.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-02-25 at 9 00 19 PM" src="https://user-images.githubusercontent.com/58783823/109176189-90a8e480-77ac-11eb-99dd-f838f94ba6dd.png">
<img width="1440" alt="Screenshot 2021-02-25 at 9 00 23 PM" src="https://user-images.githubusercontent.com/58783823/109176222-96062f00-77ac-11eb-8694-4e3ae6394a5e.png">
