### ISSUE TITLE
Unable to download submission from OR

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/community-app#5357]
**Reference** : 
https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30058299

User : jcori/appirio123 

![image](https://user-images.githubusercontent.com/25297859/108084623-86943100-709c-11eb-988a-e5405dd7fec9.png)
![image](https://user-images.githubusercontent.com/25297859/108084658-914ec600-709c-11eb-811a-fe0732a4ea7d.png)
Note : Please let us know if this is due submission API issues. For more details. https://github.com/topcoder-platform/submissions-api/issues/215

**Comment by drasticdpk** [comment]
cc @SathyaJayabal @lakshmiathreya

**Comment by SathyaJayabal** [comment]
@drasticdpk , only in dev right?

**Comment by drasticdpk** [comment]
> @drasticdpk , only in dev right?

Yes it is  in dev mode.

**Comment by lakshmiathreya** [comment]
@sachin-maheshwari can we move this Issue to submissions api repo? cc @SathyaJayabal @mtwomey @drasticdpk

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , we need to move it to OR repo
https://github.com/topcoder-platform/tc-online-review
