### ISSUE TITLE
Add recommended challenges for private communities

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5361]
Enhancement: Add recommended challenges for private communities

**Comment by lakshmiathreya** [comment]
cc @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
Verified the following on dev
I have verified the following scenarios e2e:
User wins a public challenge with skill A -->
Topgear challenge with skill A is recommended
Public challenge with skill A is recommended
2. User wins a topgear challenge with skill B  -->
Topgear challenge with skill B is recommended
Public challenge with skill B is recommended
