### ISSUE TITLE
Forums on top navigation should take use to Vanilla Forums

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5366]
Currently, when user clicks Forums, it takes user to our legacy Jive Forums.

Expected: When user clicks Forums on top navigation, user should be taken to Vanilla Forums https://discussions.topcoder.com/

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh:
- When click in forum link, will keep opening in new window?

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to QA and Stag envs.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , forums links in the footer needs to be updated too (for logged in and not logged in users).

**Comment by luizrrodrigues** [comment]
@SathyaJayabal I'll update and push shortly

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Updated and deployed to QA env.

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues it doesn't need to open in new window anymore.

**Comment by luizrrodrigues** [comment]
@Oanh-and-only-Oanh Cool. I'll updated.

**Comment by SathyaJayabal** [comment]
Verified
<img width="1440" alt="Screenshot 2021-02-20 at 6 01 48 PM" src="https://user-images.githubusercontent.com/58783823/108595437-e2fd9600-73a5-11eb-94d1-474a8c7feed0.png">
<img width="1440" alt="Screenshot 2021-02-20 at 6 02 19 PM" src="https://user-images.githubusercontent.com/58783823/108595448-f01a8500-73a5-11eb-9231-51f6dedab6af.png">

**Comment by SathyaJayabal** [comment]
verified on prod
