### ISSUE TITLE
Update nav item for TopGear

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5367]

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Test env

**Comment by sandhiyakavi** [comment]
Verified on Test Env. Title "Learn" changed into "TopGear Operations"

![image](https://user-images.githubusercontent.com/55895538/108457326-c97d2100-72b5-11eb-8794-d4ecea61efe9.png)

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2021-02-22 at 2 37 30 PM" src="https://user-images.githubusercontent.com/58783823/108686514-8ae8a000-751b-11eb-993b-f9011a54c438.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1439" alt="Screenshot 2021-02-22 at 4 14 08 PM" src="https://user-images.githubusercontent.com/58783823/108697554-06048300-7529-11eb-9329-d8c7a52d1507.png">
