### ISSUE TITLE
Fix infinity loading on TCO21 copilot leaderboards

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5370]
Go to: https://tco21.topcoder.com/competition-overview/win-a-trip/copilot-tournament
Scroll to dev
Click on S1 winner for details

**Comment by sandhiyakavi** [comment]
@kkartunov I tried the above steps in Prod Env ,its taking time to load but displaying eventually. Can you please confirm what I tested is correct? Attached video.
If not please let me know what exactly needs to be tested.

https://user-images.githubusercontent.com/55895538/108669199-e3ba3780-751f-11eb-8e98-271f8901dc54.mp4

**Comment by kkartunov** [comment]
@sandhiyakavi yes correct tested.
Although it currently works(was fixed by support) this fix here implements better error handling and etc. Therefore we will proceed to merge it.

See how those requests are fired in offline mode. This should not be and is fixed in the patch.
https://drive.google.com/file/d/11fnxSKqMwDdc_By7XLFyWq1pdDNZ25ME/view?usp=drivesdk

**Comment by SathyaJayabal** [comment]
verified on test

https://user-images.githubusercontent.com/58783823/108805628-03a43680-75c6-11eb-80e9-64a5201f52b8.mov

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)

https://user-images.githubusercontent.com/58783823/109160126-669af680-779b-11eb-9db5-f8746898559a.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/109175964-56d7de00-77ac-11eb-87b8-92fcea96c1ea.mov
