### ISSUE TITLE
Recommended Challenges: Hide Sorting options "Most recent" and "Title A-Z" when recommended toggle is on

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5371]
When the recommended toggle is on, the default sort option is best match. But when the user selects other sort options like most recent and title(A-Z) the sort does not work.

<img width="1440" alt="Screenshot 2021-02-19 at 4 46 13 PM" src="https://user-images.githubusercontent.com/58783823/108497808-07883e00-72d2-11eb-9726-966ab6be26ee.png">

**Comment by nursoltan-s** [comment]
<img width="1440" alt="Screen Shot 2021-02-19 at 20 53 21" src="https://user-images.githubusercontent.com/7783676/108506948-94dc8a00-72f4-11eb-9ea9-1681fd9e2b95.png">

Frontend sending request with "sortBy" query parameter. I tried with "sort_by" as well. Can we check if it's backend issue or not?

cc @dedywahyudi

**Comment by dedywahyudi** [comment]
@nursoltan-s 
I think recommender-api not support the SortBy yet. 
I'll check with backend developer

**Comment by dedywahyudi** [comment]
Closing this, will taken care in next release

**Comment by SathyaJayabal** [comment]
@dedywahyudi , we are hiding sort options "Most recent" and "Title A-Z"

**Comment by dedywahyudi** [comment]
Ok, clear about to hide those 2 options

**Comment by SathyaJayabal** [comment]
@dedywahyudi , just to be clear hide only when recommended toggle is on

**Comment by dedywahyudi** [comment]
local testing: 

![Screen Shot 2021-02-24 at 23 14 46](https://user-images.githubusercontent.com/4476442/109030116-1ddd3200-76f6-11eb-83fa-f6457e54bdb6.png)

![Screen Shot 2021-02-24 at 23 14 31](https://user-images.githubusercontent.com/4476442/109030110-1cac0500-76f6-11eb-843a-2b8fcdd29d77.png)

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-02-25 at 9 29 30 AM" src="https://user-images.githubusercontent.com/58783823/109101055-0892f280-774c-11eb-9a6a-ff5e56f32ad9.png">
<img width="1440" alt="Screenshot 2021-02-25 at 9 29 39 AM" src="https://user-images.githubusercontent.com/58783823/109101075-0d57a680-774c-11eb-85e1-a15dfe306277.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-01 at 12 48 24 PM" src="https://user-images.githubusercontent.com/58783823/109464289-77de4e80-7a8c-11eb-8c95-233b2559b9da.png">
