### ISSUE TITLE
Recommended Challenges: HIde sub community filter when recommended toggle is on

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5372]
When the recommended challenges toggle is on, the sub-community filter does not work
.
<img width="1440" alt="Screenshot 2021-02-19 at 5 47 04 PM" src="https://user-images.githubusercontent.com/58783823/108503537-8c775580-72da-11eb-974c-f4c2a9022131.png">
<img width="1440" alt="Screenshot 2021-02-19 at 5 47 11 PM" src="https://user-images.githubusercontent.com/58783823/108503547-913c0980-72da-11eb-9ac6-dce35f73bd30.png">

**Comment by nursoltan-s** [comment]
<img width="1440" alt="Screen Shot 2021-02-19 at 20 57 40" src="https://user-images.githubusercontent.com/7783676/108507390-349a1800-72f5-11eb-80aa-3e13096db4c1.png">

Is backend supports "events[]" filter?

cc @dedywahyudi

**Comment by dedywahyudi** [comment]
@nursoltan-s Same here, events not supported yet i think

**Comment by dedywahyudi** [comment]
Closing this, will taken care in next release

**Comment by SathyaJayabal** [comment]
@dedywahyudi , we need to hide sub community filter when recommended toggle is on

**Comment by dedywahyudi** [comment]
Yes, clear about hide the sub-community filter

**Comment by dedywahyudi** [comment]
Local testing: 

![Screen Shot 2021-02-24 at 23 14 31](https://user-images.githubusercontent.com/4476442/109030236-377e7980-76f6-11eb-88fb-dfd3b40d0105.png)
![Screen Shot 2021-02-24 at 23 14 46](https://user-images.githubusercontent.com/4476442/109030242-38afa680-76f6-11eb-88ec-90e4aab0bd8b.png)

**Comment by SathyaJayabal** [comment]
verified on dev env
<img width="1440" alt="Screenshot 2021-02-25 at 9 27 45 AM" src="https://user-images.githubusercontent.com/58783823/109100929-ccf82880-774b-11eb-9424-f5dd318fb6ef.png">
<img width="1440" alt="Screenshot 2021-02-25 at 9 27 50 AM" src="https://user-images.githubusercontent.com/58783823/109100935-d1bcdc80-774b-11eb-905e-1becdfec8862.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-01 at 12 48 24 PM" src="https://user-images.githubusercontent.com/58783823/109464412-a2300c00-7a8c-11eb-9bc8-35fc10231cc7.png">
