### ISSUE TITLE
Highlighting Matched Skills: Clarification

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5373]
@Oanh-and-only-Oanh , 

The Open for registration list shows the copilot entered tags below the challenge. When the recommended challenges toggle is on, the matched skills are displayed. these are extracted skills from the spec, that also match the user's skills. 

Is this behaviour fine, where the user sees additional skills to the challenge once recommended toggle is on?
<img width="983" alt="Screenshot 2021-02-19 at 6 04 51 PM" src="https://user-images.githubusercontent.com/58783823/108505443-6b643400-72dd-11eb-8b45-7319a630de91.png">
<img width="978" alt="Screenshot 2021-02-19 at 6 05 46 PM" src="https://user-images.githubusercontent.com/58783823/108505445-6c956100-72dd-11eb-8b79-30d4c9d8dda9.png">

**Comment by Oanh-and-only-Oanh** [comment]
these matched skills are manually added by copilot or extracted from spec? We just want highlighted skills if they match extracted skills.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , The matched skills are extracted from the spec.
