### ISSUE TITLE
Dynamic loading is not working when recommended toggle is on

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5375]
When there are more than 10 recommended challenges , when the user scrolls down, more challenges must be loaded.
Also the count is also displayed only as 10.
example: user : tonyj
The api returns 11 challenges with non zero jaccard_index (match score). but only 10 are displayed.
<img width="1440" alt="Screenshot 2021-02-22 at 11 15 33 AM" src="https://user-images.githubusercontent.com/58783823/108667485-549d2780-74ff-11eb-9939-52f0b416b229.png">

**Comment by dedywahyudi** [comment]
@dedywahyudi Okay, clear

**Comment by dedywahyudi** [comment]
Local testing: 

https://user-images.githubusercontent.com/4476442/109030457-672d8180-76f6-11eb-82d4-f7a9cc343257.mp4

**Comment by SathyaJayabal** [comment]
verified on prod
