### ISSUE TITLE
Challenge Forum link in challenge details page redirecting to Vanilla Roundtables

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5377]
Example challenge: https://www.topcoder.com/challenges/d38904ea-ef4a-4315-b955-6b3be1dc63b7

**Comment by luizrrodrigues** [comment]
@SathyaJayabal deployed to QA env.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , challenge link from example challenge in QA env going to Old dev forums with read only banner
https://qa-community-app.topcoder-dev.com/challenges/84588230-34b8-4280-bc94-a45ebc8fd8ae

<img width="1440" alt="Screenshot 2021-02-23 at 7 35 09 AM" src="https://user-images.githubusercontent.com/58783823/108793513-aef2c280-75a9-11eb-94ea-1f7ce1897e6e.png">

**Comment by SathyaJayabal** [comment]
Can we deploy this on staging, @luizrrodrigues

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Sorry, yeah. The best way to test old forum is in Stag. I'll deploy now.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag env.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on staging

https://user-images.githubusercontent.com/58783823/108821112-255fe680-75e3-11eb-94b5-61912a2d4951.mov

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)

https://user-images.githubusercontent.com/58783823/108828934-81c80380-75ed-11eb-8efc-82cf87f054d2.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/108838899-4ed83c80-75fa-11eb-9544-c65fe3879fa2.mov
