### ISSUE TITLE
Placement of search bar

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5379]
Placement fo search bar is displayed on the right. It should be as it is in production

<img width="1440" alt="Screenshot 2021-02-23 at 11 42 21 AM" src="https://user-images.githubusercontent.com/58783823/108808313-5da7fa80-75cc-11eb-9a0d-159b5dbfec78.png">

**Comment by SathyaJayabal** [comment]
@dedywahyudi , another example. search should be above the message
<img width="1440" alt="Screenshot 2021-02-23 at 2 20 32 PM" src="https://user-images.githubusercontent.com/58783823/108820598-6d323e00-75e2-11eb-81eb-e394b4eaa47c.png">

**Comment by dedywahyudi** [comment]
@SathyaJayabal Ok got it

**Comment by dedywahyudi** [comment]
Local testing: 

![Screen Shot 2021-02-24 at 23 17 45](https://user-images.githubusercontent.com/4476442/109030642-8e844e80-76f6-11eb-9eb1-6c22de2a60d6.png)

**Comment by SathyaJayabal** [comment]
verified don dev
<img width="1440" alt="Screenshot 2021-02-25 at 8 30 20 AM" src="https://user-images.githubusercontent.com/58783823/109096552-c2d22c00-7743-11eb-872b-ce4ea80dde10.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-01 at 12 51 38 PM" src="https://user-images.githubusercontent.com/58783823/109464580-e4f1e400-7a8c-11eb-94c8-bc3d2330b2ff.png">
