### ISSUE TITLE
TCO Scoreboard - Admin Page

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#538]
The challenge has been completed. The review score of the winner is barely passing (81.0).
Pending is the evaluation of the outcome and reviews, merge of the code into the codebase, and further fixes.
Direct: https://www.topcoder.com/direct/contest/detail?projectId=30059890
OR: https://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30059890

**Comment by nithyaasworld** [comment]
@birdofpreyru This seems like an info than an issue. Hence closing this.
