### ISSUE TITLE
Filter by track and type issue when all filters are off

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5380]
When all track filters are switched off or when all type filters are switched off, then the page keeps loading.
<img width="1440" alt="Screenshot 2021-02-23 at 12 33 56 PM" src="https://user-images.githubusercontent.com/58783823/108811708-bcbd3d80-75d3-11eb-8498-08a5577e8058.png">
<img width="1440" alt="Screenshot 2021-02-23 at 12 35 07 PM" src="https://user-images.githubusercontent.com/58783823/108811721-c21a8800-75d3-11eb-8a15-9c3f7252850f.png">

**Comment by dedywahyudi** [comment]
@SathyaJayabal Clear about this.

**Comment by dedywahyudi** [comment]
Local testing:
https://user-images.githubusercontent.com/4476442/109031025-e91daa80-76f6-11eb-8f76-30adb346e8f7.mp4

**Comment by SathyaJayabal** [comment]
verified on dev env
<img width="1440" alt="Screenshot 2021-02-25 at 8 28 30 AM" src="https://user-images.githubusercontent.com/58783823/109096460-94545100-7743-11eb-8a8c-5e25abb9b890.png">
<img width="1440" alt="Screenshot 2021-02-25 at 8 28 53 AM" src="https://user-images.githubusercontent.com/58783823/109096476-99b19b80-7743-11eb-974a-8f556c28c869.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-01 at 12 52 22 PM" src="https://user-images.githubusercontent.com/58783823/109464668-0a7eed80-7a8d-11eb-9d52-5caf6f6bae3a.png">
<img width="1440" alt="Screenshot 2021-03-01 at 12 52 34 PM" src="https://user-images.githubusercontent.com/58783823/109464691-0fdc3800-7a8d-11eb-9094-d869b3552cc6.png">
