### ISSUE TITLE
Hidden Subcommunity filter and search bar must be displayed again when other buckets are selected

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5398]
1. Select recommended challenges toggle on
2. subcommunity filter and search bar is hidden
3. switch to any other bucket like All Challenges bucket or My Challenges bucket or Past Challenges

expected: subcommunity filter and search bar must be displayed again, they must be again hidden when switched to open for registration bucket 
actual: subcommunity filter and search bar are still hidden

https://user-images.githubusercontent.com/58783823/109332744-8fe38180-7884-11eb-840a-8e7ca620de2c.mov

**Comment by dedywahyudi** [comment]
@SathyaJayabal 

I think this is already fixed: 
Can you check here: https://test-community-app.topcoder-dev.com/challenges?bucket=openForRegistration&tracks[DS]=true&tracks[Des]=true&tracks[Dev]=true&tracks[QA]=true&types[]=CH&types[]=F2F&types[]=TSK

![Screen Shot 2021-02-27 at 18 11 02](https://user-images.githubusercontent.com/4476442/109385548-3f713000-7927-11eb-845d-559fb970141d.png)
![Screen Shot 2021-02-27 at 18 11 21](https://user-images.githubusercontent.com/4476442/109385549-41d38a00-7927-11eb-9a55-63a41e737333.png)
![Screen Shot 2021-02-27 at 18 11 28](https://user-images.githubusercontent.com/4476442/109385551-439d4d80-7927-11eb-973e-af0c42560537.png)

**Comment by SathyaJayabal** [comment]
this is verified
