### ISSUE TITLE
setup logentries.com

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#54]
Let's make sure we're setup to log to logentries.com

https://docs.logentries.com/v1.0/docs/nodejs

**Comment by birdofpreyru** [comment]
@ajefts What do we want to log? All messages from client- and server-side, or just those from the server-side?

**Comment by ajefts** [comment]
I was going to say server side, but with the architecture of this app is it possible to log both front and back end stuff?

If not, we have getsentry.com for front-end logging if we need it

**Comment by birdofpreyru** [comment]
@ajefts Why do you prefer different services for the client- and server-side logging?

Yes, I can setup logging with logentries on both sides. They have libs both for node and for the browser. Also I can use just their nodejs library for server-side logging, and the log messages from the client side I can proxy through our server. Sure, these details will be hidden from the rest of the code, on both sides it will stay the same simple as it is now:

```
import logger from 'utils/logger';
logger.log('Hello World!');
```

**Comment by ajefts** [comment]
ok, cool.  I prefer just using 1 service, but I know Parth setup both logentries and getsentry, so I wasn't sure if we needed both in all cases.

**Comment by birdofpreyru** [comment]
So, which one do you prefer? @parthshah

**Comment by ajefts** [comment]
Logentries.

**Comment by ajefts** [comment]
Failed to create challenge
Status code: 503
Response body:
```
"<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"
```

**Comment by ajefts** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30057901/?type=develop&noncache=true
