### ISSUE TITLE
TCO21 leaderboard is loading the same data for completed challenge history

### ISSUE THREAD

**Issue by mahestro** [topcoder-platform/community-app#5413]
**Describe the bug**
TCO21 leaderboard is loading the same data for the completed challenge history. It happens in all the leaderboards (design, copilots, data science, etc)

**To Reproduce**
1. Go to https://tco21.topcoder.com/competition-overview/development/leaderboard?tracks%5Bdev%5D=2
2. Click on jeevan900929
3. Close the popup
4. Then click on any other member, it will display the same data

**Expected behavior**
It should display the data related to each selected member 

**Screenshots**
https://take.ms/nNvT3

**Comment by SathyaJayabal** [comment]
verified on qa
<img width="1440" alt="Screenshot 2021-03-05 at 4 11 42 PM" src="https://user-images.githubusercontent.com/58783823/110104733-8cdd1980-7dcd-11eb-9022-06ff922b95be.png">
<img width="1440" alt="Screenshot 2021-03-05 at 4 11 47 PM" src="https://user-images.githubusercontent.com/58783823/110104753-91a1cd80-7dcd-11eb-8873-19d3dd9aa822.png">
<img width="1440" alt="Screenshot 2021-03-05 at 4 11 55 PM" src="https://user-images.githubusercontent.com/58783823/110104759-92d2fa80-7dcd-11eb-96c6-6344e20f080b.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2021-03-11 at 4 27 47 PM" src="https://user-images.githubusercontent.com/58783823/110777167-d5417f00-8286-11eb-85c7-6ee41f282414.png">
<img width="1440" alt="Screenshot 2021-03-11 at 4 27 53 PM" src="https://user-images.githubusercontent.com/58783823/110777200-dd012380-8286-11eb-860c-8f9d47d67ece.png">
<img width="1440" alt="Screenshot 2021-03-11 at 4 27 59 PM" src="https://user-images.githubusercontent.com/58783823/110777206-decae700-8286-11eb-9d41-2fc117e6117d.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-11 at 6 21 03 PM" src="https://user-images.githubusercontent.com/58783823/110790059-974c5700-8296-11eb-86d2-f67e77e589f5.png">
<img width="1440" alt="Screenshot 2021-03-11 at 6 21 07 PM" src="https://user-images.githubusercontent.com/58783823/110790077-9c110b00-8296-11eb-9a9f-57b297f7c54a.png">
<img width="1440" alt="Screenshot 2021-03-11 at 6 21 12 PM" src="https://user-images.githubusercontent.com/58783823/110790082-9d423800-8296-11eb-881c-ba6803613dd0.png">
