### ISSUE TITLE
Update Gig Forums Link in Gig Details

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5414]
It has to link to new forums instead.

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1440" alt="Screenshot 2021-03-03 at 6 27 20 PM" src="https://user-images.githubusercontent.com/58783823/109809447-4f9e4d80-7c4e-11eb-9ad0-8522f817d41d.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-03-04 at 2 51 12 PM" src="https://user-images.githubusercontent.com/58783823/109941389-2090e600-7cf9-11eb-8700-37276c45f634.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-04 at 6 15 52 PM" src="https://user-images.githubusercontent.com/58783823/109966023-c3eff400-7d15-11eb-91f8-85173c643b29.png">
<img width="1440" alt="Screenshot 2021-03-04 at 6 16 01 PM" src="https://user-images.githubusercontent.com/58783823/109966050-cce0c580-7d15-11eb-9aa6-dd3aca3d9b6d.png">
