### ISSUE TITLE
User should not be able to even see the Application Form unless logged in.

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5415]
If user clicks the Apply button, there should be validation about whether the user is logged in or not. 
If not, display modal similar to Gig Referral warning box.

**Comment by SathyaJayabal** [comment]
@kkartunov , user is unable to close the warning box, by clicking outside it.


https://user-images.githubusercontent.com/58783823/109809979-f682e980-7c4e-11eb-98cc-648d28f561fc.mov

**Comment by kkartunov** [comment]
Thanks, @SathyaJayabal. Pushed an update for it. Please, check in ~15...

**Comment by SathyaJayabal** [comment]
@kkartunov verified on test

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2021-03-04 at 2 52 19 PM" src="https://user-images.githubusercontent.com/58783823/109941516-40280e80-7cf9-11eb-8a52-815093bff89c.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-03-04 at 6 17 13 PM" src="https://user-images.githubusercontent.com/58783823/109966205-fa2d7380-7d15-11eb-951a-f7979097bf6d.png">
