### ISSUE TITLE
Submissions Tab not showing any data on Skill Builder Challenge :: Angular

### ISSUE THREAD

**Issue by dedywahyudi** [topcoder-platform/community-app#5421]
**Describe the bug**
Submissions Tab not showing any data on Skill Builder Challenge :: Angular

**To Reproduce**
Easy: https://www.topcoder.com/challenges/ca04b5ba-b0f5-42a0-9b79-f61ce40e9f70?tab=submissions 
Medium: https://www.topcoder.com/challenges/5ad5beec-56ff-4c75-b26b-6d353e9a0480 
Hard: https://www.topcoder.com/challenges/e8b07653-2959-4201-89d5-1401ea1529a4?tab=submissions 

**Expected behavior**

**Screenshots**
![Screen Shot 2021-03-03 at 20 55 00](https://user-images.githubusercontent.com/4476442/109966980-74182980-7d23-11eb-98dc-b58bc3e66486.png)
![Screen Shot 2021-03-03 at 20 54 19](https://user-images.githubusercontent.com/4476442/109966986-767a8380-7d23-11eb-9fcb-975cc8684cde.png)
![Screen Shot 2021-03-03 at 20 54 15](https://user-images.githubusercontent.com/4476442/109966994-79757400-7d23-11eb-9748-00a42b427031.png)

**Comment by SathyaJayabal** [comment]
@dedywahyudi , seems good now
<img width="1440" alt="Screenshot 2021-04-02 at 2 31 31 PM" src="https://user-images.githubusercontent.com/58783823/113400892-29d8a580-93c0-11eb-8394-7484606577b0.png">
<img width="1440" alt="Screenshot 2021-04-02 at 2 31 35 PM" src="https://user-images.githubusercontent.com/58783823/113400917-33faa400-93c0-11eb-9a5e-89c6ee87488c.png">
<img width="1440" alt="Screenshot 2021-04-02 at 2 31 38 PM" src="https://user-images.githubusercontent.com/58783823/113400922-35c46780-93c0-11eb-8832-6ab636afca9c.png">
