### ISSUE TITLE
Automatic Contentful Route Redirects

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5424]
Implement redirects for routes if configured in Contentful.

For QA:
/community/gig-resources is set to redirect to /community/learn

**Comment by SathyaJayabal** [comment]
verified on test

https://user-images.githubusercontent.com/58783823/110771402-75e07080-8280-11eb-836a-ff686bb91dc1.mov

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)

https://user-images.githubusercontent.com/58783823/110780762-0de35780-828b-11eb-87fa-e774352c488f.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/110789890-62400480-8296-11eb-80bf-868cda4e7c76.mov
