### ISSUE TITLE
Update gigs application process

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5429]
QA to verify:
- apply as an existing user in recruit
- apply as a new user in recruit
- form validation works properly

**Comment by SathyaJayabal** [comment]
@kkartunov , 
please confirm that the following are the updates to the application process.

Updates to the application Process
Existing user in recruit:
User : TonyJ

General: Add text "It looks like you have applied to a gig previously. Perfect! We have most of your information. Is there anything you would like to update to your Gig Work Profile?”

Personal Information Section : 
	⁃	Make “First Name” “Last Name” and “Email” as readonly
	⁃	Pre populate The Country Drop down

Topcoder Information Section : Remove section

Share your weekly pay expectations section
	⁃	Remove Available From field
	⁃	Pre populate Weekly Pay Expectation
	⁃	Remove text “Your Professional Work History”

Resume and Skills section
	⁃	Add link to previously added resume
	⁃	Pre populate skills

Final Questions Section
	⁃	Remove text “Please Complete the Following Questions”
	⁃	Remove field “How did you hear about this gig ?” 
	⁃	Remove field “Why do you think you are a good fit for this gig ?”
	⁃	Remove field “Any other notes you might have”


New user in recruit
User :tester123456

Personal Information Section : 
	⁃	Make “First Name” “Last Name” and “Email” as readonly

Topcoder Information Section : 
	⁃	Make Topcoder Username and Topcoder Profile fields as readonly

Share your weekly pay expectations section
	⁃	Remove Available From field
	⁃	Remove text “Your Professional Work History”

Final Questions Section
	⁃	Remove text “Please Complete the Following Questions”
	⁃	Update field to dropdown“How did you hear about this gig ?”   
	⁃	Remove field “Why do you think you are a good fit for this gig ?”
	⁃	Remove field “Any other notes you might have”

**Comment by kkartunov** [comment]
Confirmed. Thank You @SathyaJayabal!

**Comment by SathyaJayabal** [comment]
verified on test

existing user:
![Screenshot_2021-03-18 Gig Work Topcoder Community Topcoder](https://user-images.githubusercontent.com/58783823/111574428-745bfe80-87d2-11eb-9751-85a97075d466.png)

new user:
![Screenshot_2021-03-18 Gig Work Topcoder Community Topcoder(2)](https://user-images.githubusercontent.com/58783823/111574767-24316c00-87d3-11eb-8425-7a23252c99a0.png)

**Comment by sandhiyakavi** [comment]
@kkartunov Below are some of the observations,
1. The values of the prepopulated field (for the existing user) that is changed while applying for a gig, 
Is displayed as empty fields if the page is not refreshed and only navigated.
Note: The values are displayed only after refresh.


https://user-images.githubusercontent.com/55895538/111579362-3aeab980-87f9-11eb-81df-3721abf77da7.mp4

2. The City field takes value from Settings page and not from the previous application. Is it fine?

![image](https://user-images.githubusercontent.com/55895538/111579615-aa60a900-87f9-11eb-85ed-ca67fef61db3.png)

Other than that all validations are working properly and able to apply for the new users.

**Comment by kkartunov** [comment]
@SathyaJayabal thank you!
1. Fixed bug
2. It is preffered to take values from TC profile if present, so yes it is fine.

**Comment by sandhiyakavi** [comment]
@kkartunov Now if we navigate (without refreshing) to another Gig application form, the previous values are getting displayed (not the current changes) instead of empty fields. Still the current values are displayed only after refresh.


https://user-images.githubusercontent.com/55895538/111612504-de9b9000-8820-11eb-9b66-d2978e58106f.mp4

**Comment by sandhiyakavi** [comment]
Verified on Test Env. Working as expected.

1. The values are correctly displayed without refresh.

https://user-images.githubusercontent.com/55895538/111623366-a5b5e800-882d-11eb-833a-dab33b4bfe04.mp4



2. Able to apply both as Existing and New user.
3. The form validations are working correctly.

**Comment by SathyaJayabal** [comment]
verified on staging (develop) branch
apply as an existing user in recruit
apply as a new user in recruit
form validation works properly

**Comment by SathyaJayabal** [comment]
verified on prod
apply as an existing user in recruit
apply as a new user in recruit
form validation works properly
