### ISSUE TITLE
New thumbnail image for social share

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5430]
update to this
![Topoder Image Preview V1](https://user-images.githubusercontent.com/5585002/111316899-54aac600-866c-11eb-9987-5bb7033a307c.png)

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="625" alt="Screenshot 2021-03-16 at 7 00 42 PM" src="https://user-images.githubusercontent.com/58783823/111317405-25a34d00-868a-11eb-8cc1-f03009e7c14c.png">

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @kkartunov , i dont see the preview image on staging
<img width="718" alt="Screenshot 2021-03-18 at 6 32 50 PM" src="https://user-images.githubusercontent.com/58783823/111630436-5f09c300-8818-11eb-95a6-f67e3a6e0de1.png">

**Comment by SathyaJayabal** [comment]
verified on beta(develop branch)
<img width="631" alt="Screenshot 2021-03-18 at 7 40 35 PM" src="https://user-images.githubusercontent.com/58783823/111640106-e0198800-8821-11eb-947f-4ed45688c6e6.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="841" alt="Screenshot 2021-03-18 at 8 41 33 PM" src="https://user-images.githubusercontent.com/58783823/111649462-676af980-882a-11eb-87d4-f047ed73e7ca.png">
