### ISSUE TITLE
Add "weeks" to gigs duration

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5431]
![Screen Shot 2021-03-12 at 5 03 27 PM](https://user-images.githubusercontent.com/5585002/111270084-14c9eb80-8638-11eb-9a38-c7594c576a85.png)
and under gig detail page too.
Add only if the value is an integer otherwise keep what untouched.

**Comment by SathyaJayabal** [comment]
verified on qa env
<img width="1284" alt="Screenshot 2021-03-16 at 4 39 53 PM" src="https://user-images.githubusercontent.com/58783823/111299695-42358a00-8676-11eb-8490-2931123fcd16.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-03-18 at 6 27 17 PM" src="https://user-images.githubusercontent.com/58783823/111629827-b8252700-8817-11eb-9448-ff905d3673bb.png">
<img width="1440" alt="Screenshot 2021-03-18 at 6 27 46 PM" src="https://user-images.githubusercontent.com/58783823/111629848-bd827180-8817-11eb-8f44-0bbf990c85a8.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1284" alt="Screenshot 2021-03-18 at 8 20 28 PM" src="https://user-images.githubusercontent.com/58783823/111646252-7dc38600-8827-11eb-8650-ce83fa0e25b3.png">
<img width="1335" alt="Screenshot 2021-03-18 at 8 20 36 PM" src="https://user-images.githubusercontent.com/58783823/111646266-82883a00-8827-11eb-926d-8a84a2cd6219.png">
