### ISSUE TITLE
Dark mode for FAQ component

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5432]
Like shown on https://marvelapp.com/prototype/bj002ag/screen/77662351

**Comment by kkartunov** [comment]
Test page for QA:
https://community-app.topcoder.com/examples/contentful/viewport/1ekIMzLLz2CrkRxPgA4FZ1

**Comment by SathyaJayabal** [comment]
@kkartunov,
Separators are not 40 % opaque like in design
Text and arrow must be white
<img width="1416" alt="Screenshot 2021-03-30 at 1 39 32 PM" src="https://user-images.githubusercontent.com/58783823/112956118-bfc0c600-915d-11eb-99dd-76164fdb0f55.png">

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1433" alt="Screenshot 2021-03-30 at 8 00 08 PM" src="https://user-images.githubusercontent.com/58783823/113005965-8f474f00-9192-11eb-9882-a09d3f1ff0ba.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1438" alt="Screenshot 2021-04-02 at 3 40 38 PM" src="https://user-images.githubusercontent.com/58783823/113406872-dbc89f80-93c9-11eb-8c13-5d55f52b7c37.png">

**Comment by SathyaJayabal** [comment]
verified in prod
<img width="1437" alt="Screenshot 2021-04-02 at 7 27 20 PM" src="https://user-images.githubusercontent.com/58783823/113421959-8ef4c100-93e9-11eb-9e7c-7cecb283d36d.png">
