### ISSUE TITLE
Update login modal on gig details page

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5448]
When clicking "APPLY TO THIS JOB" this modal pops:
![image](https://user-images.githubusercontent.com/5585002/112947411-6a75bc00-913f-11eb-939d-745a04390882.png)

We want to update it to match: https://marvelapp.com/prototype/f0i4ece/screen/78025759

**Comment by sandhiyakavi** [comment]
@kkartunov In Design (https://marvelapp.com/prototype/f0i4ece/screen/78025759) the heading is in single line but the pop up is going to second line in Test Env.

![image](https://user-images.githubusercontent.com/55895538/113672506-d6819280-96f2-11eb-8bd8-f383d2d62e2d.png)
![image](https://user-images.githubusercontent.com/55895538/113672572-eb5e2600-96f2-11eb-8a88-fc92268fd0e7.png)

**Comment by kkartunov** [comment]
@sandhiyakavi what is the screen resolution used?

**Comment by kkartunov** [comment]
The design referred is for 1440px and above. It is fine to go to more lines for screens smaller than 1440px. We can processed with that...

**Comment by sandhiyakavi** [comment]
@kkartunov Yes, my screen resolution is lower than 1440px. I will mark the issue as pass.

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-04-09 at 11 52 54 AM" src="https://user-images.githubusercontent.com/58783823/114137742-429a0b80-992a-11eb-907a-9b516175f13d.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/114163206-e0aac780-9964-11eb-8a66-ded18860bcca.png)
