### ISSUE TITLE
Secure recruitCRM API responses

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5453]
APIs should show only limited set of fields/values due to security reasons.
List of fields per API point bellow:

- https://www.topcoder.com/api/recruit/jobs?job_status=1
- https://www.topcoder.com/api/recruit/jobs/25953109
- https://www.topcoder.com/api/recruit/jobs/search?job_status=1
```
id
slug
country
locality
city
name,
custom_fields,
enable_job_application_form,
created_on,
updated_on
min_annual_salary
salary_type
max_annual_salary
job_description_text
```

- https://www.topcoder.com/api/recruit/candidates/search?email=kiril.kartunov@gmail.com
```
id
slug
first_name
last_name
email
contact_number
skill
resume
locality
salary_expectation
custom_fields
```

Aditionally QA need to validate all gigs related ops are not broken. Means:
- listing, applying and etc

**Comment by sandhiyakavi** [comment]
@kkartunov When I tried to Refer the Gig, I am getting error message "Failed to get your referralId."

Account used: tester1234

![image](https://user-images.githubusercontent.com/55895538/113662853-e5147d80-96e3-11eb-9f5c-97589d7b151f.png)

Other than the above, the fields for the api responses are correct

<img width="924" alt="recruitcrm_1" src="https://user-images.githubusercontent.com/55895538/113663319-c6fb4d00-96e4-11eb-8fc7-95048f0b86f8.png">
<img width="925" alt="recruitcrm_2" src="https://user-images.githubusercontent.com/55895538/113663326-ca8ed400-96e4-11eb-8912-d8fb471b6a5b.png">
<img width="920" alt="recruitcrm_3" src="https://user-images.githubusercontent.com/55895538/113663330-ccf12e00-96e4-11eb-8651-94e93511792f.png">
<img width="767" alt="recruitcrm_4" src="https://user-images.githubusercontent.com/55895538/113663338-cf538800-96e4-11eb-86f3-6a3be1dfe233.png">

**Comment by kkartunov** [comment]
@sandhiyakavi this appears to be env issue. Test env does not have all keys needed.
![Screenshot from 2021-04-06 09-13-47](https://user-images.githubusercontent.com/5585002/113667011-d8c6fb00-96b8-11eb-8f6b-26dd6997f5b8.png)

Let's test this on dev to make sure it works. It is deploying currently. Please test in ~15min...

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. 
1. Able to refer persons in Dev Env without any error.

<img width="960" alt="refer_person_devenv" src="https://user-images.githubusercontent.com/55895538/113676124-0c287a80-96f7-11eb-96e7-5be81859b0a8.png">

2. The fields for the api responses are correct
https://www.topcoder-dev.com/api/recruit/jobs?job_status=1
<img width="923" alt="recruitcrm_api_1" src="https://user-images.githubusercontent.com/55895538/113676303-3f6b0980-96f7-11eb-990f-4e25807118d2.png">

https://www.topcoder-dev.com/api/recruit/jobs/25953109
<img width="930" alt="recruitcrm_api_2" src="https://user-images.githubusercontent.com/55895538/113676345-4a259e80-96f7-11eb-8032-cfd4bdc04885.png">

https://www.topcoder-dev.com/api/recruit/jobs/search?job_status=1
<img width="929" alt="recruitcrm_api_3" src="https://user-images.githubusercontent.com/55895538/113676376-527dd980-96f7-11eb-856f-da2b3ab934df.png">

https://www.topcoder-dev.com/api/recruit/candidates/search?email=kiril.kartunov@gmail.com
<img width="928" alt="recruitcrm_api_4" src="https://user-images.githubusercontent.com/55895538/113676406-5b6eab00-96f7-11eb-8b27-a27ec749a0f8.png">

3. All gig related ops Gig listing , Gig details, Applying to Gig( both new and old member), all URLs are working fine.

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-04-09 at 11 48 01 AM" src="https://user-images.githubusercontent.com/58783823/114137368-b5ef4d80-9929-11eb-9e8f-27f7a95c2621.png">
<img width="1440" alt="Screenshot 2021-04-09 at 11 49 02 AM" src="https://user-images.githubusercontent.com/58783823/114137381-bb4c9800-9929-11eb-8bb5-43695a921faa.png">
<img width="1440" alt="Screenshot 2021-04-09 at 11 49 40 AM" src="https://user-images.githubusercontent.com/58783823/114137386-bc7dc500-9929-11eb-8b4b-d5f491433bbc.png">
<img width="1440" alt="Screenshot 2021-04-09 at 11 50 43 AM" src="https://user-images.githubusercontent.com/58783823/114137437-d8816680-9929-11eb-8b58-91fa3c74924c.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/114165568-9e36ba00-9967-11eb-88b4-3a86c13933b0.png)
![image](https://user-images.githubusercontent.com/55895538/114165737-d5a56680-9967-11eb-96e4-3aae13e08a64.png)
![image](https://user-images.githubusercontent.com/55895538/114165873-fe2d6080-9967-11eb-8fdf-924b13381414.png)
![image](https://user-images.githubusercontent.com/55895538/114166007-2c12a500-9968-11eb-98dc-1a656ed61f5f.png)
