### ISSUE TITLE
Topcoder Open 2018 Link on Challenge Detail Page redirects to dashboard

### ISSUE THREAD

**Issue by harshitmehta123** [topcoder-platform/community-app#546]
The Topcoder Open 2018 Link on Challenge Detail Page takes us to https://community.topcoder.com/tco18 and then redirects to Dashboard. Should take to tco18.topcoder.com

**Comment by birdofpreyru** [comment]
This belongs to the legacy challenge details page (tc-site repo). I've double-checked that the link is correct in the new challenge details. We are planning to switch to the new challenge details page later this week, I believe.
