### ISSUE TITLE
Add search state in URL for gig listing page

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5466]
When searching should update the URL so links to specific results are possiible.

**Comment by sandhiyakavi** [comment]
@kkartunov The Search state in URL is displayed when a text is searched using Search textbox.

<img width="954" alt="url_search_added_loggedin" src="https://user-images.githubusercontent.com/55895538/113687492-57488a80-9703-11eb-9b95-50f21a7eded2.png">

The Search results are displayed correctly when accessed directly through URL.

<img width="960" alt="url_searcj_2" src="https://user-images.githubusercontent.com/55895538/113687504-5adc1180-9703-11eb-91a9-c5fd80b302c7.png">

**Comment by SathyaJayabal** [comment]
verified that the Search state in URL is displayed when a text is searched using Search text box.
<img width="1440" alt="Screenshot 2021-04-09 at 11 42 30 AM" src="https://user-images.githubusercontent.com/58783823/114136778-e2569a00-9928-11eb-81dc-131886b1c384.png">

The Search results are displayed correctly when accessed directly through URL.
<img width="1440" alt="Screenshot 2021-04-09 at 11 43 49 AM" src="https://user-images.githubusercontent.com/58783823/114136790-e7b3e480-9928-11eb-8d0a-ed8d5af69f74.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/114162288-ef44af00-9963-11eb-85a3-51c1034dd33c.png)

Able to access using url
![image](https://user-images.githubusercontent.com/55895538/114162759-5eba9e80-9964-11eb-9810-cd4463d4137b.png)
