### ISSUE TITLE
Gig listing marketing

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5476]
Implement support for:
- tags for gigs: https://marvelapp.com/prototype/27i3a2cg/screen/78281998/handoff
- hotlist of gigs on the right side: https://marvelapp.com/prototype/27i3a2cg/screen/76301096/handoff

**Comment by SathyaJayabal** [comment]
verified on test
tags
<img width="1440" alt="Screenshot 2021-04-13 at 4 45 30 PM" src="https://user-images.githubusercontent.com/58783823/114545607-c846ef80-9c79-11eb-9252-97f3e2f3549c.png">
hotlist
<img width="1440" alt="Screenshot 2021-04-13 at 4 50 20 PM" src="https://user-images.githubusercontent.com/58783823/114545610-ca10b300-9c79-11eb-9d66-c574e7c69222.png">
hotlist not displayed for some users
<img width="1440" alt="Screenshot 2021-04-13 at 4 56 00 PM" src="https://user-images.githubusercontent.com/58783823/114545613-caa94980-9c79-11eb-9327-78ff431392fc.png">

**Comment by SathyaJayabal** [comment]
verified on staging.

Tags
<img width="1440" alt="Screenshot 2021-04-15 at 5 48 40 PM" src="https://user-images.githubusercontent.com/58783823/114868298-60c4a780-9e13-11eb-9651-9c5c48a9351a.png">

hotlist
<img width="1440" alt="Screenshot 2021-04-15 at 5 52 11 PM" src="https://user-images.githubusercontent.com/58783823/114868328-691ce280-9e13-11eb-81f6-748737387dab.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-04-15 at 6 26 12 PM" src="https://user-images.githubusercontent.com/58783823/114872744-3aedd180-9e18-11eb-8721-257c3ab82f81.png">
<img width="1440" alt="Screenshot 2021-04-15 at 6 27 03 PM" src="https://user-images.githubusercontent.com/58783823/114872769-3fb28580-9e18-11eb-90f7-85406e3c19cc.png">

**Comment by SathyaJayabal** [comment]
Tags
<img width="1440" alt="Screenshot 2021-04-15 at 7 31 42 PM" src="https://user-images.githubusercontent.com/58783823/114882130-442f6c00-9e21-11eb-836f-3fb6c87a729e.png">
![Uploading Screenshot 2021-04-15 at 7.31.55 PM.png…]()
