### ISSUE TITLE
Remove Outage Banner

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5477]
Reference: #5467

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-04-12 at 8 50 16 PM" src="https://user-images.githubusercontent.com/58783823/114419259-e6a4e080-9bd0-11eb-81e0-fdc4b20ef9fb.png">
<img width="1440" alt="Screenshot 2021-04-12 at 8 50 21 PM" src="https://user-images.githubusercontent.com/58783823/114419332-f58b9300-9bd0-11eb-8a09-40c70aea586f.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-04-12 at 9 18 49 PM" src="https://user-images.githubusercontent.com/58783823/114423349-ba8b5e80-9bd4-11eb-81ea-1491c7d26538.png">
<img width="1440" alt="Screenshot 2021-04-12 at 9 18 57 PM" src="https://user-images.githubusercontent.com/58783823/114423412-caa33e00-9bd4-11eb-964d-5bd3f94e2e36.png">
