### ISSUE TITLE
Topgear challenge details page not loading

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5482]
1. Go to Listings page: User can see Topgear challenges as they are a member of wipro-all group (user: picachui)
<img width="1440" alt="Screenshot 2021-04-15 at 1 13 35 PM" src="https://user-images.githubusercontent.com/58783823/114832706-69ee4e00-9dec-11eb-83b1-49499d884fe9.png">

2. Click on any one topgear challenge

Challenge details page does not load, and there is no response form challenge api call
https://www.topcoder.com/challenges/b2306c77-88e6-4162-ae26-d1c31ee2ce3f
<img width="1440" alt="Screenshot 2021-04-15 at 1 09 31 PM" src="https://user-images.githubusercontent.com/58783823/114832192-d7e64580-9deb-11eb-904d-e9e063bdd743.png">

Note: Topgear also doesnt appear on the sub community dropdown
<img width="1440" alt="Screenshot 2021-04-15 at 1 10 20 PM" src="https://user-images.githubusercontent.com/58783823/114832289-f5b3aa80-9deb-11eb-9111-7c13d0e9149d.png">

Also not able to access the topgear site, even though user is logged in at topcoder
<img width="1440" alt="Screenshot 2021-04-15 at 1 11 15 PM" src="https://user-images.githubusercontent.com/58783823/114832466-2562b280-9dec-11eb-83d1-b6afde028f6a.png">

cc @sushilshinde @lakshmiathreya @mtwomey

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Can you click in error call and then click in `preview`?

![image](https://user-images.githubusercontent.com/7029641/114867054-b3c63c80-9dca-11eb-9d8a-ba15affb77f6.png)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , works now
<img width="1440" alt="Screenshot 2021-04-15 at 5 46 02 PM" src="https://user-images.githubusercontent.com/58783823/114867543-9321d500-9e12-11eb-9a51-7d481f363983.png">
<img width="1440" alt="Screenshot 2021-04-15 at 5 46 38 PM" src="https://user-images.githubusercontent.com/58783823/114867562-99b04c80-9e12-11eb-8394-500ba739881e.png">
<img width="1440" alt="Screenshot 2021-04-15 at 5 46 40 PM" src="https://user-images.githubusercontent.com/58783823/114867568-9a48e300-9e12-11eb-9331-1925e18afd6d.png">
