### ISSUE TITLE
Remove CORS from tc-communities

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5487]
Remove CORS from `tc-communities` call to allow Earn Micro App works well.

**Comment by SathyaJayabal** [comment]
Verified on staging (develop)
Subcommunities are loading fine
<img width="1433" alt="Screenshot 2021-04-20 at 5 46 13 PM" src="https://user-images.githubusercontent.com/58783823/115394343-52560180-a200-11eb-8b2e-f1284136850b.png">

**Comment by SathyaJayabal** [comment]
Verified on prod 
Subcommunities are loading fine
<img width="1440" alt="Screenshot 2021-04-20 at 6 52 13 PM" src="https://user-images.githubusercontent.com/58783823/115403000-9bf71a00-a209-11eb-860a-d10972693c78.png">
