### ISSUE TITLE
Challenges Tab Live 

### ISSUE THREAD

**Issue by AetBoston** [topcoder-platform/community-app#549]
@birdofpreyru we need to activate the Challenges tab on the Blockchain microsite as soon as possible. Can you make sure that tab is live?

**Comment by birdofpreyru** [comment]
@AetBoston @ajefts sure, can do it later tonight, if somebody tells me what challenges should be included there?

**Comment by ajefts** [comment]
Can we include the group + tag=blockchain or etherium?

**Comment by birdofpreyru** [comment]
@ajefts Sure! Will it be fine, though, if any blockchain challenge is shown in the community? Right now its Home page strongly suggests that it is all about Ethereum only.

**Comment by birdofpreyru** [comment]
@ajefts @AetBoston I did this and tested locally against the prod backend, here is what I get in the listing (all thanks to the tags fitler, which also reacts on tags present in the title text):
![screenshot](https://user-images.githubusercontent.com/20144632/32353879-8d097910-c027-11e7-86b2-36eaed197036.png)
Does it look good for you?

**Comment by birdofpreyru** [comment]
Fixed by dea39eb93824a82fc94de985f3c7c4fd661b3379; will be deployed later today.

**Comment by AetBoston** [comment]
@birdofpreyru we only have one challenge active so far and it's the Hello World challenge so that should be showing. When do you think the tab will be live?

**Comment by ajefts** [comment]
it's going live right now....
