### ISSUE TITLE
Update text on application form

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5492]
![Screen Shot 2021-04-27 at 1 43 09 PM](https://user-images.githubusercontent.com/5585002/116374475-fb12eb00-a816-11eb-84eb-4ecb12766be1.png)

update "Upload Your..." text to:

"Please upload your resume/CV. Double-check that all of your tech skills are listed in your resume/CV and add them to the tech skills section below."

**Comment by SathyaJayabal** [comment]
The updated text  when the user already had applied before is:
Please upload your resume/CV. Double-check that all of your tech skills are listed in your resume/CV and add them to the tech skills section below, Test CV.docx
<img width="884" alt="Screenshot 2021-04-28 at 5 33 29 PM" src="https://user-images.githubusercontent.com/58783823/116400617-e3a02600-a847-11eb-88e7-c5c24762a56c.png">

Shouldn't it  be ?
Please upload your resume/CV. Double-check that all of your tech skills are listed in your resume/CV and add them to the tech skills section below, OR use Test CV.docx

**Comment by kkartunov** [comment]
@SathyaJayabal let's keep format as it was before, with the comma.

**Comment by sandhiyakavi** [comment]
Verified on Beta Env.

![image](https://user-images.githubusercontent.com/55895538/117109429-9d0a7880-adbf-11eb-88e0-60ee929f02db.png)
![image](https://user-images.githubusercontent.com/55895538/117109604-dfcc5080-adbf-11eb-85b8-2e0a2ecbf4d1.png)

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/117386977-dc050f00-af22-11eb-9e19-545ab4e7ab63.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/117415687-8e54ca80-af53-11eb-893f-bc96320c2170.png)
![image](https://user-images.githubusercontent.com/55895538/117415770-a4fb2180-af53-11eb-8f75-c340455cdbc3.png)
