### ISSUE TITLE
Update the duration icon

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5493]
![image](https://user-images.githubusercontent.com/5585002/116375002-87251280-a817-11eb-9d8e-d272b6012ea5.png)

update the duration icon (sand clock) to calendar icon as per:

![image](https://user-images.githubusercontent.com/5585002/116375133-a4f27780-a817-11eb-83d2-516ddc6ccc45.png)

**Comment by SathyaJayabal** [comment]
verified on test
<img width="1292" alt="Screenshot 2021-04-28 at 3 42 05 PM" src="https://user-images.githubusercontent.com/58783823/116387341-5903fa80-a838-11eb-8b5f-32aaad5fc3a4.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/117386101-3ef5a680-af21-11eb-8afd-eda94afe2985.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected

![image](https://user-images.githubusercontent.com/55895538/117414070-b04d4d80-af51-11eb-9b74-5d783f3e28dd.png)
