### ISSUE TITLE
Fix failed gig application - edge case

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5498]
Problem: `salary_expectation` accepts spaces wich breaks the application process.
Solution: Application should pass if value is number, nomatter the spaces which should be trimed when calling the API.

**Comment by sandhiyakavi** [comment]
Verified in Beta Env. Application is getting submitted successfully even if the Salary expectation has space in it.


https://user-images.githubusercontent.com/55895538/117253775-8c6f0680-ae82-11eb-84aa-7c82cf324073.mp4


https://user-images.githubusercontent.com/55895538/117253781-8f69f700-ae82-11eb-866c-ee30a21a21c3.mp4

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Working as expected


https://user-images.githubusercontent.com/55895538/117388258-664e7280-af25-11eb-92c1-ee6a5f8c949d.mp4

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected


https://user-images.githubusercontent.com/55895538/117417427-4b93f200-af55-11eb-9892-c0a57a9a49d3.mp4
