### ISSUE TITLE
Gig tags update + featured gigs via toggle

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5500]
Update tagging process for gigs so that tagged gigs are not always sorted at the top unless explicitly set via toggle in recruitCRM

**Comment by kkartunov** [comment]
@SathyaJayabal @sandhiyakavi this is on beta ready for QA

**Comment by sandhiyakavi** [comment]
Verified in Beta Env.

Tagged gigs which are toggled on in recruitcrm are displayed at the top.
https://beta-community-app.topcoder.com/gigs/26751764
 https://beta-community-app.topcoder.com/gigs/26744449
![image](https://user-images.githubusercontent.com/55895538/117139748-909a1600-ade7-11eb-9b5b-361f2563a790.png)
![image](https://user-images.githubusercontent.com/55895538/117139787-9bed4180-ade7-11eb-9b91-073490ad722d.png)
![image](https://user-images.githubusercontent.com/55895538/117139945-c212e180-ade7-11eb-92d9-dcc25fb9f0a7.png)

Tagged gig which is toggled off in recruitcrm is not displayed at the top.
https://beta-community-app.topcoder.com/gigs/26307379
![image](https://user-images.githubusercontent.com/55895538/117140124-03a38c80-ade8-11eb-89c2-07314b240b3f.png)
![image](https://user-images.githubusercontent.com/55895538/117140227-233ab500-ade8-11eb-96eb-a20360aef836.png)

**Comment by luizrrodrigues** [comment]
@kkartunov please raise PR to this one and other ready issues.
Thanks.

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Working as expected

<img width="958" alt="test_1" src="https://user-images.githubusercontent.com/55895538/117386768-6b5df280-af22-11eb-973c-fabd99a84041.png">
<img width="960" alt="api_1" src="https://user-images.githubusercontent.com/55895538/117386788-7022a680-af22-11eb-8f3a-8cb0001440d9.png">
<img width="958" alt="gig_tag_2" src="https://user-images.githubusercontent.com/55895538/117386791-744ec400-af22-11eb-9f9f-162656acb922.png">
<img width="960" alt="gig_tag_not_3_api" src="https://user-images.githubusercontent.com/55895538/117386803-79137800-af22-11eb-8e61-fd1775134206.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Working as expected

<img width="960" alt="Prod_1" src="https://user-images.githubusercontent.com/55895538/117414907-a841dd80-af52-11eb-8e34-1a0c0ebb81b1.png">
<img width="960" alt="Prod_2" src="https://user-images.githubusercontent.com/55895538/117414918-abd56480-af52-11eb-89d6-a848a723a587.png">
<img width="959" alt="Prod_3" src="https://user-images.githubusercontent.com/55895538/117414923-ad9f2800-af52-11eb-8f71-a8b09b17d526.png">
<img width="959" alt="Prod_4" src="https://user-images.githubusercontent.com/55895538/117414930-b132af00-af52-11eb-82c8-7f445775ab1a.png">
