### ISSUE TITLE
Prevent people already placed on a gig from applying to a gig

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5509]
as per title.
Look & feel to match:
![Gig-Work-Topcoder-Community-Topcoder](https://user-images.githubusercontent.com/5585002/117787811-78931e00-b24f-11eb-8a40-9075f89d2c0d.png)

**Comment by SathyaJayabal** [comment]
@kkartunov , verified on beta.

User already placed in a gig
<img width="1437" alt="Screenshot 2021-05-11 at 3 16 14 PM" src="https://user-images.githubusercontent.com/58783823/117795804-23193a00-b26c-11eb-8def-c8017bbb28dd.png">

User not yet placed in any gig
<img width="1440" alt="Screenshot 2021-05-11 at 3 17 55 PM" src="https://user-images.githubusercontent.com/58783823/117795887-31675600-b26c-11eb-938a-8ed83e118d9e.png">

**Comment by SathyaJayabal** [comment]
verified on staging
user who is placed
<img width="1440" alt="Screenshot 2021-05-13 at 8 42 19 PM" src="https://user-images.githubusercontent.com/58783823/118146095-e4ca7900-b42b-11eb-97af-a98d9b3e56f8.png">
user who is not placed
<img width="1440" alt="Screenshot 2021-05-13 at 8 42 56 PM" src="https://user-images.githubusercontent.com/58783823/118146116-eac05a00-b42b-11eb-960b-6fc9b779b421.png">

**Comment by SathyaJayabal** [comment]
verified on prod. 
user who is already placed
<img width="1440" alt="Screenshot 2021-05-13 at 9 56 37 PM" src="https://user-images.githubusercontent.com/58783823/118155811-4099ff80-b436-11eb-8d2e-e6ac867eda06.png">
user who is not placed
<img width="1440" alt="Screenshot 2021-05-13 at 9 57 03 PM" src="https://user-images.githubusercontent.com/58783823/118155846-4a236780-b436-11eb-8036-304720d6f938.png">
