### ISSUE TITLE
A/B gig listing v2 - centered hotlist

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5513]
Update the Hotlist position to be after the featured gigs in the listing.
Ref design: https://marvelapp.com/prototype/27i3a2cg/screen/79287138

**Comment by SathyaJayabal** [comment]
verified 
<img width="1440" alt="Screenshot 2021-05-12 at 8 01 02 PM" src="https://user-images.githubusercontent.com/58783823/117992949-ec6f1c80-b35c-11eb-807d-2765b7ee6ca7.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-05-13 at 8 45 32 PM" src="https://user-images.githubusercontent.com/58783823/118146675-76d28180-b42c-11eb-9ceb-b8076cb4e446.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-13 at 9 55 33 PM" src="https://user-images.githubusercontent.com/58783823/118155564-fa44a080-b435-11eb-83eb-4fcc2d93228f.png">
