### ISSUE TITLE
URLs to tabs not working properly

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5514]
1. Go to https://www.topcoder.com/community/member-programs/webinars
2. Click on "Past Webinars" and copy the URL from browser address
3. Paste it new tab and navigate to it
4. Expected is page to load and switch to past automatically

**Comment by sandhiyakavi** [comment]
Verified on Dev qa Env. Page is loading correctly with Past Webinars selected


https://user-images.githubusercontent.com/55895538/118916570-344c0000-b96a-11eb-92f5-0c12fb3ef142.mp4

**Comment by sandhiyakavi** [comment]
Verified on staging env.


https://user-images.githubusercontent.com/55895538/119084347-92491800-ba3c-11eb-9f2f-8fea172d6ff8.mp4

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/119153902-48c5f080-ba6f-11eb-9011-575730684e33.mov
