### ISSUE TITLE
UI fixes for gig details page - mobile viewports

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5520]
- Buttons size are disproportional
https://monosnap.com/file/TstRieXOAatcNZOQKIjHPoc3PxEJjp
- right-side content stretches outside view on mobile

**Comment by sandhiyakavi** [comment]
Verified on Dev Env. Button sizes are proportional now in mobile.

![mobile_view](https://user-images.githubusercontent.com/55895538/118793863-f7cdc500-b8d3-11eb-9ebd-7c0c95fac814.jpg)

Mobile : iphone 12 mini

**Comment by sandhiyakavi** [comment]
Verified on Staging Env.

![unnamed](https://user-images.githubusercontent.com/55895538/119084087-24045580-ba3c-11eb-84cb-d9ac911f3225.jpg)
