### ISSUE TITLE
add sign up to navigation

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5526]
Update the top navigation on https://www.topcoder.com/community/learn.
1. If the user is logged out, there should be  Sign Up and Log in buttons
2. If the user clicks on SIGN ON, member should be routed to the account creation page.
3. the reURL should be https://accounts-auth0.topcoder.com/?retUrl=https://www.topcoder.com/start&mode=signUp

**Comment by Oanh-and-only-Oanh** [comment]
@Dara-K can you share design here.

**Comment by Dara-K** [comment]
@Oanh-and-only-Oanh  Here is the design: https://marvelapp.com/prototype/86aaj33/screen/79554452

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to QA and Beta env.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on beta
<img width="1433" alt="Screenshot 2021-05-28 at 4 24 41 PM" src="https://user-images.githubusercontent.com/58783823/119973558-40226c80-bfd1-11eb-8bd8-c924bff6fc88.png">

**Comment by SathyaJayabal** [comment]
verified on staging (feature branch)
<img width="1439" alt="Screenshot 2021-05-28 at 7 21 39 PM" src="https://user-images.githubusercontent.com/58783823/119994175-f85c0f00-bfe9-11eb-94c1-5292bd563c7c.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-05-28 at 9 45 12 PM" src="https://user-images.githubusercontent.com/58783823/120013140-0451cc00-bffe-11eb-8638-786b8ee5d76d.png">
