### ISSUE TITLE
Winners tab broken for tasks

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#5529]
**Describe the bug**
Attempting to view winner on the challenge page for tasks is not working. The page is blank and the console shows an error.

**To Reproduce**
1. Go to and task and view the winner.  For example, https://www.topcoder.com/challenges/e5f1c4d0-ff4a-4fdf-9f66-b1f906329537?tab=winners
2. See error

**Comment by ajefts** [comment]
fyi @Oanh-and-only-Oanh

**Comment by dedywahyudi** [comment]
@ajefts @Oanh-and-only-Oanh 

I received this error when access the page. Can you help add me to the challenge first pls? So i can see the correct error. 
Thank you

<img width="1678" alt="Screen Shot 2021-05-25 at 11 41 02" src="https://user-images.githubusercontent.com/4476442/119440238-1f96b000-bd4e-11eb-805b-3df8d65b8c06.png">

**Comment by dedywahyudi** [comment]
@ajefts @Oanh-and-only-Oanh 

We received solutions for this. I can see the Winner tab content now. 

![Screen Shot 2021-05-29 at 13 17 12](https://user-images.githubusercontent.com/4476442/120060346-8e8f4400-c081-11eb-86e1-836420cba13e.png)
![Screen Shot 2021-05-29 at 13 19 08](https://user-images.githubusercontent.com/4476442/120060347-90590780-c081-11eb-913b-99c74a0e8956.png)

Question, how about for Non-Logged In users? I see this challenge not exists error. Thoughts? 
![Screen Shot 2021-05-29 at 12 17 51](https://user-images.githubusercontent.com/4476442/120060364-a9fa4f00-c081-11eb-9407-ed482443ec0a.png)

**Comment by Oanh-and-only-Oanh** [comment]
Only show for logged-in users. Thank you for checking.

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh Ok, cool! 

@luizrrodrigues 
The fix for this issue ready in this PR: https://github.com/topcoder-platform/community-app/pull/5551

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Beta env

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , i still see the error on winners tab
<img width="1440" alt="Screenshot 2021-05-31 at 7 21 24 PM" src="https://user-images.githubusercontent.com/58783823/120203577-7cf69980-c245-11eb-8c99-95dac09dd40d.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal looks like I can't access this challenge, you have any other example?

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , we just need to user any v5 pure task. There are few examples on dev we can use
https://www.topcoder-dev.com/challenges/c3dc0eac-372c-4c07-9a17-683468eb5891
https://www.topcoder-dev.com/challenges/4954eea1-6af3-4b61-b6ee-53c24e3735e9
<img width="1427" alt="Screenshot 2021-06-01 at 1 19 45 PM" src="https://user-images.githubusercontent.com/58783823/120286639-1c666b80-c2dc-11eb-954a-b2f41634f720.png">

usre:tonyj

**Comment by SathyaJayabal** [comment]
verified on staging (feature branch)
<img width="1440" alt="Screenshot 2021-06-01 at 5 46 35 PM" src="https://user-images.githubusercontent.com/58783823/120321839-64e45000-c301-11eb-9c57-2ddee1ecf56d.png">

**Comment by SathyaJayabal** [comment]
verified on staging(develop)
<img width="1440" alt="Screenshot 2021-06-01 at 7 39 20 PM" src="https://user-images.githubusercontent.com/58783823/120337630-1ccd2980-c311-11eb-9f63-627fd5ffeaf1.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-01 at 9 58 05 PM" src="https://user-images.githubusercontent.com/58783823/120358750-7c810000-c324-11eb-99b8-ab90ccc4ab90.png">
