### ISSUE TITLE
Change logo to rainbow for June

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5531]
Change Topcoder logo to rainbow for June 1st. 

All Topcoder sites including our MFEs.
file:///Users/Oanh/Downloads/topcoder%20icon%20pride.svg

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh the svg not uploaded

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @luizrrodrigues 

This is ready: 

![Screen Shot 2021-05-28 at 22 16 07](https://user-images.githubusercontent.com/4476442/120005744-598fdc80-c002-11eb-803a-6d6af594de45.png)

PR: https://github.com/topcoder-platform/community-app/pull/5548

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to QA env.

**Comment by SathyaJayabal** [comment]
verified on qa

<img width="1440" alt="Screenshot 2021-05-31 at 7 23 50 PM" src="https://user-images.githubusercontent.com/58783823/120203925-de1e6d00-c245-11eb-8527-72e0a4baf438.png">
<img width="1438" alt="Screenshot 2021-05-31 at 7 24 07 PM" src="https://user-images.githubusercontent.com/58783823/120203936-e1b1f400-c245-11eb-8919-b467aa9e6cd4.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1424" alt="Screenshot 2021-06-01 at 7 40 08 PM" src="https://user-images.githubusercontent.com/58783823/120337837-4be39b00-c311-11eb-9110-34201ceca19c.png">
<img width="1440" alt="Screenshot 2021-06-01 at 7 40 38 PM" src="https://user-images.githubusercontent.com/58783823/120337850-4ede8b80-c311-11eb-8c4e-13d1615e4236.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1438" alt="Screenshot 2021-06-01 at 10 00 43 PM" src="https://user-images.githubusercontent.com/58783823/120359106-ef8a7680-c324-11eb-95c9-27288050fd97.png">
<img width="1440" alt="Screenshot 2021-06-01 at 10 01 08 PM" src="https://user-images.githubusercontent.com/58783823/120359136-f5805780-c324-11eb-9d17-61de36d9d30c.png">
