### ISSUE TITLE
sub category icon issue

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5536]
Target URL: https://www.topcoder.com/thrive/search?author=Mariia%20Mykhailova

### Reproduction Steps ###
1 goto https://www.topcoder.com/thrive/
2 click Data Visualization
3 click author name
4. click Data science option under category

### Expected Result ###
Should show sub category icon properly 

### Actual Result ###

icon is wrongly showing 

### Screenshots or screencast ###

![bandicam 2020-02-07 08-21-23-543](https://user-images.githubusercontent.com/3225433/73996855-da951180-4982-11ea-8f5d-917c7c87725f.jpg)
### OS/Browser Information ###

 windows 10  and Firefox 72.0.2

**Comment by sandhiyakavi** [comment]
Verified in Beta Env.

![image](https://user-images.githubusercontent.com/55895538/120296148-c953df00-c302-11eb-8dae-e0c730cca44d.png)

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2021-06-01 at 7 35 33 PM" src="https://user-images.githubusercontent.com/58783823/120337047-97497980-c310-11eb-94a9-6aabba2a6dd9.png">
<img width="1440" alt="Screenshot 2021-06-01 at 7 35 37 PM" src="https://user-images.githubusercontent.com/58783823/120337078-9f091e00-c310-11eb-8f40-46044853b4af.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-01 at 9 54 41 PM" src="https://user-images.githubusercontent.com/58783823/120358357-07152f80-c324-11eb-8858-b26e75a3559e.png">
<img width="1440" alt="Screenshot 2021-06-01 at 9 54 45 PM" src="https://user-images.githubusercontent.com/58783823/120358408-11cfc480-c324-11eb-8f7b-aa700cfe4c50.png">
