### ISSUE TITLE
UI issue while adding long text in tags

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5538]
**Target URL:**  https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=

**To Reproduce**
1. Go to thrive page
2. Click on the SRM > apply filter
3.  Add long text in the tags

**Actual-**
Log text extract the whole page rather than wrap the text.

**Expected behavior**
Long text in tags should be wrap

**Desktop:**
 - OS: Lenovo Thinkpad; Windows 10pro
 - Browser: Firefox
 - Version: 72.0.2

**Comment by kkartunov** [comment]
![Screenshot from 2021-05-27 11-19-43](https://user-images.githubusercontent.com/5585002/119791380-741c6580-bedd-11eb-9610-cb391545abc9.png)

**Comment by SathyaJayabal** [comment]
verified on beta. limit of 40 characters per tag
<img width="1440" alt="Screenshot 2021-06-08 at 11 27 02 AM" src="https://user-images.githubusercontent.com/58783823/121130844-98b4fd80-c84c-11eb-80d5-446a5b41f732.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-06-08 at 6 05 10 PM" src="https://user-images.githubusercontent.com/58783823/121185884-23fdb580-c884-11eb-8f6e-446b7be1a4c2.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-08 at 7 53 40 PM" src="https://user-images.githubusercontent.com/58783823/121202860-42b77880-c893-11eb-8aaa-478c80f2f712.png">
