### ISSUE TITLE
Update smoke test cases TC_020 and TC_006 to match search improvements

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5549]
TC_006 and TC_020
https://github.com/topcoder-platform/challenge-api/pull/408

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , does this fix TC_006  too?

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Yep.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , I still see TC_020 failed on the latest prod smoke test.
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3002/workflows/404d5278-6ebf-4b4c-ad23-89365924e6e1/jobs/12754

**Comment by lakshmiathreya** [comment]
@SathyaJayabal @luizrrodrigues - shall we move this out of 1.9.6 milestone so we can close the milestone?

**Comment by SathyaJayabal** [comment]
verified on prod
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3121/workflows/c072fd1a-ccfb-4d25-ae20-01c37886c304/jobs/12944
