### ISSUE TITLE
Add EdgeNet icon for Member Profile

### ISSUE THREAD

**Issue by harshitmehta15** [topcoder-platform/community-app#5553]
Hi Team. 
Can you please help add EdgeNet icon for skills on the member profile. Here's the icon: https://drive.google.com/drive/folders/1TB3pi5QJWXUY9ye-1nvQwXnbSHDA8-GZ?usp=sharing

@Oanh-and-only-Oanh @luizrrodrigues

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @Oanh-and-only-Oanh , I cant seem to add EdgeNet to my profile, I get the error "Tag id 604 is not valid"

<img width="1440" alt="Screenshot 2021-05-31 at 11 14 55 AM" src="https://user-images.githubusercontent.com/58783823/120145685-9118a780-c201-11eb-92aa-98f8712f4f14.png">

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @SathyaJayabal 
F2F is live, i'll share once we received submission.

**Comment by nursoltan-s** [comment]
Can't update skills with id 604 (EdgeNet) and 605 (Angular 11). 

PATCH /v3/members/:userHandle/skills

<img width="586" alt="Screen Shot 2021-06-03 at 17 09 55" src="https://user-images.githubusercontent.com/7783676/120626539-55960b80-c495-11eb-8fa5-8c67594d2036.png">

But, these two skills are appearing on Get tags.
https://api.topcoder.com/v3/tags/?filter=domain%3DSKILLS%26status%3DAPPROVED&limit=1000

Any thoughts? Can you please check production data for these two skills?

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @luizrrodrigues 
Possible to check backend api?

**Comment by Oanh-and-only-Oanh** [comment]
@harshitmehta15 FYI

**Comment by dedywahyudi** [comment]
Any updates here? Our F2F submitter waiting the fixes on the backend.

**Comment by Oanh-and-only-Oanh** [comment]
checking

**Comment by urwithat** [comment]
@dedywahyudi & @Oanh-and-only-Oanh - This should be working now.
FYI - when any new tag/skill is added to the v3 tags API a restart of the v3 members API is required. The v3 tags data is cached by member v3 API at startup.

**Comment by dedywahyudi** [comment]
@urwithat Awesome, thanks. 
I'll check with submitters

**Comment by dedywahyudi** [comment]
@Oanh-and-only-Oanh @SathyaJayabal @luizrrodrigues 
Please check this PR: https://github.com/topcoder-platform/community-app/pull/5575
It look EdgeNet Skill only exists in Prod backend api.

**Comment by luizrrodrigues** [comment]
Thanks @dedywahyudi 

@SathyaJayabal Deployed to QA and BETA env.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Hold, I'll deploy this one to Stag env, BETA is busy now. (reverting Kiril branch on BETA)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues @dedywahyudi , able to add edgenet skill now. But new icon is not seen yet.
<img width="1440" alt="Screenshot 2021-06-15 at 9 27 53 AM" src="https://user-images.githubusercontent.com/58783823/121990793-036db800-cdbc-11eb-8f53-8a71337c4ecc.png">

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Sorry, this not deployed to Stag yet, deploying now.
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3030/workflows/7685257f-82fd-4df0-9700-9d8620635ba8

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Done, deployed in Stag env.

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , verified on staging
<img width="939" alt="Screenshot 2021-06-15 at 11 19 01 AM" src="https://user-images.githubusercontent.com/58783823/121999888-92360100-cdcb-11eb-8127-eea7d4b3c66c.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-06-23 at 6 32 11 PM" src="https://user-images.githubusercontent.com/58783823/123101174-64972a80-d451-11eb-8a8c-4e7230164e37.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-23 at 8 20 20 PM" src="https://user-images.githubusercontent.com/58783823/123118720-80ee9380-d460-11eb-999c-c0015d478711.png">
