### ISSUE TITLE
CircleCI deployment not updating in Deployment Dashboard

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5556]
CircleCI deployment not updating in Dashboard:
https://community-app-dev-dashboard.herokuapp.com/#/dashboard

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This was fixed, deploying now to Stag env.

**Comment by SathyaJayabal** [comment]
verified. latest deployments reflected in dashboard
<img width="1440" alt="Screenshot 2021-06-01 at 5 16 57 PM" src="https://user-images.githubusercontent.com/58783823/120318251-43816500-c2fd-11eb-9af3-34b1aa540215.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-06-01 at 7 43 03 PM" src="https://user-images.githubusercontent.com/58783823/120338186-9e24bc00-c311-11eb-8d6d-2c82e7872ec0.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-01 at 10 02 29 PM" src="https://user-images.githubusercontent.com/58783823/120359248-1648ad00-c325-11eb-92b2-5e3623ce866e.png">
