### ISSUE TITLE
Automated Smoke Testing - Flow/Approval without jobs

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5557]
![image](https://user-images.githubusercontent.com/7029641/120299704-a0e7c880-c2a1-11eb-9f7b-353e4baf318e.png)

- Expected; Automated Smoke Testing will be called when any branch are deployed to **Stag** or **Prod** env.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal ready for QA, `fix-circleci-deployment` was deployed to Stag env, then Smoke Testing to Stag env was called:
![image](https://user-images.githubusercontent.com/7029641/120317027-810dd000-c2b4-11eb-9146-e09d67e7f029.png)

**Comment by SathyaJayabal** [comment]
smoke tests run for develop branch on staging
<img width="1169" alt="Screenshot 2021-06-01 at 7 44 50 PM" src="https://user-images.githubusercontent.com/58783823/120338450-df1cd080-c311-11eb-9f8b-c567e10f6740.png">

**Comment by SathyaJayabal** [comment]
smoke tests run on prod
<img width="1173" alt="Screenshot 2021-06-01 at 10 03 18 PM" src="https://user-images.githubusercontent.com/58783823/120359390-3b3d2000-c325-11eb-93e0-bc7bee4f4b6e.png">
