### ISSUE TITLE
Registrants count is incorrect after users unregisters from a challenge

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5562]
1. register to a challenge
2. registrants count is updated and user handle listed under registrants tab
3. unregister form the challenge

expected: Registrants count updated accordingly and user handle removed form registrants tab
actual: handle is removed from the registrants tab, but registrants count not updated

example:
https://www.topcoder.com/challenges/4c90cb40-0b80-4c79-8b2c-14438fb2920e
https://www.topcoder.com/challenges/ecc7267d-76eb-4aa7-be2a-248e0d734b44
user: picachui

<img width="1440" alt="Screenshot 2021-06-01 at 10 25 39 PM" src="https://user-images.githubusercontent.com/58783823/120362396-a63c2600-c328-11eb-82f7-499632724a91.png">

<img width="1440" alt="Screenshot 2021-06-01 at 10 27 14 PM" src="https://user-images.githubusercontent.com/58783823/120362429-b0f6bb00-c328-11eb-8d4e-ee75b7a58fe1.png">

NOTe: this issue is found only for some challenges.

**Comment by dedywahyudi** [comment]
@SathyaJayabal @Oanh-and-only-Oanh From screenshots problem only for F2F Challenge type?

**Comment by dedywahyudi** [comment]
@SathyaJayabal @Oanh-and-only-Oanh 

For my testing on live challenge, it look the count and list of users are consistent. 
Any ideas how to reproduce the problem? 

![Screen Shot 2021-06-02 at 10 41 47](https://user-images.githubusercontent.com/4476442/120422604-ce606f00-c392-11eb-8183-8a7d16ebe8c4.png)
![Screen Shot 2021-06-02 at 10 42 03](https://user-images.githubusercontent.com/4476442/120422608-d15b5f80-c392-11eb-8105-bbf0d181f763.png)
![Screen Shot 2021-06-02 at 10 42 50](https://user-images.githubusercontent.com/4476442/120422613-d3252300-c392-11eb-8251-5b8f55bd8d8b.png)

**Comment by SathyaJayabal** [comment]
@dedywahyudi ,can u try for these challenges
https://www.topcoder.com/challenges/4c90cb40-0b80-4c79-8b2c-14438fb2920e
https://www.topcoder.com/challenges/ecc7267d-76eb-4aa7-be2a-248e0d734b44?tab=registrants

**Comment by dedywahyudi** [comment]
@SathyaJayabal both not exists to me: 

![Screen Shot 2021-06-02 at 11 53 30](https://user-images.githubusercontent.com/4476442/120425879-387c1280-c399-11eb-842b-386d62a01083.png)

**Comment by SathyaJayabal** [comment]
@dedywahyudi , ok they are topgear challenges, but i dont see the issue with all topgear challenges. let me try and get another example

**Comment by SathyaJayabal** [comment]
@dedywahyudi try this one pls
https://www.topcoder.com/challenges/7c0f4623-7312-42f7-843b-de499c2207e9?tab=registrants

**Comment by SathyaJayabal** [comment]
@dedywahyudi ,The issue is not particular to any challenge track, type or sub community. But it does happen only for some challenges, and I am not able to identify what makes these challenges different from the others.

**Comment by dedywahyudi** [comment]
@SathyaJayabal 

Ok, i see the problem now at https://www.topcoder.com/challenges/7c0f4623-7312-42f7-843b-de499c2207e9?tab=registrants

Initial count: 31
After Register: 32
After Unregister: 32

![Screen Shot 2021-06-02 at 12 12 55](https://user-images.githubusercontent.com/4476442/120427525-40898180-c39c-11eb-8f2a-efd1beab18fd.png)
![Screen Shot 2021-06-02 at 12 13 22](https://user-images.githubusercontent.com/4476442/120427528-41baae80-c39c-11eb-9589-2f2f2d7eb049.png)
![Screen Shot 2021-06-02 at 12 13 27](https://user-images.githubusercontent.com/4476442/120427532-42ebdb80-c39c-11eb-9edd-0b8b102c9a89.png)

Weird thing: I'm not see any error :/

**Comment by SathyaJayabal** [comment]
@dedywahyudi , the BE returns this incorrect data.

**Comment by dedywahyudi** [comment]
Missing screenshot?

**Comment by SathyaJayabal** [comment]
@dedywahyudi , I cant reproduce the issue now for the above challenges. It is working fine now. Shall we close the issue?
<img width="1440" alt="Screenshot 2021-06-02 at 11 17 47 AM" src="https://user-images.githubusercontent.com/58783823/120430165-3499c180-c394-11eb-8ab7-b98ed09774c4.png">
<img width="1440" alt="Screenshot 2021-06-02 at 11 17 54 AM" src="https://user-images.githubusercontent.com/58783823/120430184-3bc0cf80-c394-11eb-910a-3bc0813189fe.png">

**Comment by dedywahyudi** [comment]
@SathyaJayabal @Oanh-and-only-Oanh 

Ok, sure i'm good with close this one. The problem is intermittent.

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , issues was noticed yesterday for few challenges. But they seem to be working fine now. Closing this for now. Will reopen in case I see it again.

Thanks @dedywahyudi
