### ISSUE TITLE
Create TCO22 subcommunity

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5564]
1. Create it and link to Contentful similar to tco21
2. Setup tco22.topcoder.com domain and configure it

**Comment by kkartunov** [comment]
@SathyaJayabal QA URL is: https://beta-community-app.topcoder.com/__community__/tco22

**Comment by sandhiyakavi** [comment]
Verified on Beta Env. Everything is fine.

@kkartunov The Leaderboard contents for TCO22 is having the old TCO21 contents.is it ok for now?

Also under Overview menu --> Prizes topic --> Link for button 'View Prize Payment terms' has tco21 link (https://tco21.topcoder.com/competition-rules). 
![image](https://user-images.githubusercontent.com/55895538/121998703-409b6f80-cde7-11eb-9533-cf698cbe7260.png)

![image](https://user-images.githubusercontent.com/55895538/121998291-9c192d80-cde6-11eb-8f4b-92f5a23edc9b.png)

**Comment by kkartunov** [comment]
@sandhiyakavi yes it is fine. Team is working on actual content which we will update later via Contentful when the site is connected to it.

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-06-23 at 6 35 32 PM" src="https://user-images.githubusercontent.com/58783823/123101590-d96a6480-d451-11eb-890b-b0a71a3cb05c.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-06-23 at 8 46 53 PM" src="https://user-images.githubusercontent.com/58783823/123123054-2a835400-d464-11eb-9d03-308cbfe3f413.png">

content updates and domain setup pending

**Comment by SathyaJayabal** [comment]
domain setup complete:
https://tco22.topcoder.com/
<img width="1440" alt="Screenshot 2021-06-28 at 1 13 04 PM" src="https://user-images.githubusercontent.com/58783823/123598874-9d991b80-d812-11eb-9691-27f7d847cbaa.png">
