### ISSUE TITLE
Improve TopGear redirect

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5565]

**Comment by lakshmiathreya** [comment]
@luizrrodrigues Please provide details reg the change ...

**Comment by luizrrodrigues** [comment]
@lakshmiathreya Deployed a fix to reduce redirect time from old topgear home page to new topgear-app.

**Comment by lakshmiathreya** [comment]
@Oanh-and-only-Oanh Please let us know if we can close this ...

**Comment by Oanh-and-only-Oanh** [comment]
this has been resolved. You can go ahead and close. Thanks
