### ISSUE TITLE
Thrive search page - Datepicker fixes

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5571]
Replace the date picker with the new componet as used by track results page filter
![image](https://user-images.githubusercontent.com/5585002/121028794-c6e4ff80-c7b0-11eb-9385-b6cbd50c418c.png)
For instacene: https://www.topcoder.com/thrive/tracks?track=Competitive%20Programming

![image](https://user-images.githubusercontent.com/5585002/122880884-3297a280-d343-11eb-8192-77542e0c68ee.png)

Should follow condensed US date format - m/d/y without calendar icon

**Comment by SathyaJayabal** [comment]
@kkartunov , i dont see any difference between prod and beta, both follow the m/d/y format with a calendar icon.

**Comment by kkartunov** [comment]
@SathyaJayabal we are updating the datepickers on thrive search page http://beta-community-app.topcoder.com/thrive/search?title=test

**Comment by SathyaJayabal** [comment]
verified
<img width="262" alt="Screenshot 2021-06-23 at 9 15 12 AM" src="https://user-images.githubusercontent.com/58783823/123032481-a305f880-d403-11eb-8b54-991a1706539a.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="272" alt="Screenshot 2021-06-23 at 6 28 31 PM" src="https://user-images.githubusercontent.com/58783823/123100602-e3d82e80-d450-11eb-89c1-fecc1a065c57.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="255" alt="Screenshot 2021-06-23 at 8 16 36 PM" src="https://user-images.githubusercontent.com/58783823/123118221-1178a400-d460-11eb-9b38-8049f1171547.png">
