### ISSUE TITLE
Automated Smoke Testing - Fix Test Cases 008, 012 and 020

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5577]
![image](https://user-images.githubusercontent.com/7029641/121710778-4b38ca80-cab0-11eb-8687-18ca7151deb2.png)

**Comment by SathyaJayabal** [comment]
008, 012 and 020 passed smoke test
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3028/workflows/1b1ba5c7-47a6-4885-9136-e1df2739cad6/jobs/12799
