### ISSUE TITLE
Challenge Details : Doesn't show next deadline

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/community-app#558]
Next deadline is not shown on the Challenge Details pages

Review Appeals Phase https://www.topcoder.com/challenges/30060087/?type=develop&nocache=true&tab=details

![topcoder 2017-11-04 08-37-26](https://user-images.githubusercontent.com/146016/32400497-d73149d6-c13b-11e7-9788-f0971ce69832.png)

Submission Phase https://www.topcoder.com/challenges/30060210/?type=develop

![topcoder 2017-11-04 08-41-47](https://user-images.githubusercontent.com/146016/32400517-34ec27a8-c13c-11e7-853e-c34cd9536fe7.png)

It still shows the next deadline for the Registration Phase https://www.topcoder.com/challenges/30060271/?type=develop

![topcoder 2017-11-04 08-48-56](https://user-images.githubusercontent.com/146016/32400944-f530a34a-c141-11e7-9344-8eb29a11682e.png)

Could be connected with  #541

OS: macOS Siera 10.12.6
Browser: Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by birdofpreyru** [comment]
@maxceem do you want to investigate and fix it? Cause for me it all works fine on Ubuntu / Chrome.
At least, try to update `moment` and `moment-timezone` dependencies to the latest versions, and see whether it helps. I would bet it should be either a bug or some functional restriction in them for some OS / browsers, that causes this problem.

**Comment by maxceem** [comment]
@birdofpreyru Sure, I'll try to investigate it tomorrow.

**Comment by maxceem** [comment]
@birdofpreyru I'm sorry still a little bit busy. As I'm the only one having it, will try to check it later.

**Comment by birdofpreyru** [comment]
Hopefully fixed, as I did some related fixes. If there are still any issues related to this, please create a new ticket.
