### ISSUE TITLE
Automated Smoke Testing - Challenge Details Test Cases

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5583]
Enable/Fix test cases to Challenge Details page.

**Comment by SathyaJayabal** [comment]
verified on staging
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3057/workflows/e21af4b9-5870-4ba7-960b-75d7111ebe38/jobs/12842

**Comment by SathyaJayabal** [comment]
verified on prod
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3059/workflows/4b073b8f-7afc-46ab-adf0-03b3cca7369b/jobs/12845
