### ISSUE TITLE
Design Submission Page Issues

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#559]
Hey Sergey,

I saw the submission page went live, but we have couple of bugs/changes:

Let me know if you need any design files/input. Also feel free to test anything related to design track with me, before launching it so I might catch some bugs earlier.

Thanks and good luck! 

### Resolved Issues:
1. ~~For photo declaration, is better to use only file number - this was my bad for forgetting it as we changed to file URL, but I talked to members and Adam and when we save a file from istockphoto we get the number first. So that way is faster and we don't need the other fields "Photo URL", "Photo Description"~~

2. ~~Need to see upload progress in “Submission”, “Source”, “Preview” section
(can’t see in chrome browser by some members) - for Filestack and Drag & Drop upload~~

3. ~~The progress bar on the Submitting Now… page is not there anymore as per design, but members with low internet connection said they find it useful~~

4. ~~Once each challenge phase that has ended we should not be allowed to delete submitted work~~

5. ~~When clicking on Add New Submission on Manage Submission page, gets me to a 404 Error page.~~

6. ~~Once I submitted a file and then I deleted (so I have 0 submissions), the Unregister button becomes disabled - should still be active.~~

7. ~~Adam said we can remove the Studio Standard Fonts options from fonts dropdown and we can just declare them on notes area.~~ *for Studio Standard Fonts the input mechanics has been updated to ask only for the font name, and not for the URL. I believe, this is was the main issue behind this point*

**Comment by Dara-K** [comment]
4*. Update to 4:  we can keep the delete option until the screening phase starts, but remove it after, so members can delete junk submissions (junk submission being a submission that adds small increments to another submission). This should save screener some time and copilot too.

**Comment by birdofpreyru** [comment]
@skyhit @ajefts for the point (1) I've updated UI to require only file number, but API does not accept submissions if source URL is missing in stock art description, so I have to submit dummy URLs there. We should update API to make only file number obligatory.

**Comment by Dara-K** [comment]
@birdofpreyru Please use just the URL, as sometimes we might use photos from other sites than istockphoto and the URL is more relevant this way

**Comment by birdofpreyru** [comment]
@Dara-K for the progress bar on submitting now page, I just need some a picture, how to style it, and I'll add it.

**Comment by Dara-K** [comment]
Check attached @birdofpreyru 
[Preloader.zip](https://github.com/topcoder-platform/community-app/files/1451575/Preloader.zip)

**Comment by Dara-K** [comment]
A couple of notes on the same page:
1.  I noticed the prototype doesn't respect 100% the design. Like on the right column some line spacings are missing. Grouping information or not helps reading and scanning it faster. Can you follow the attached design please more accurate?
[Style Guide.zip](https://github.com/topcoder-platform/community-app/files/1451683/Style.Guide.zip)

2. On main column, there are places where H3 should be used but it's not and also the accent blue bar colors are missing.

3. The design challenge details page should not have a review scorecard - when I click on it, it gets me to UI prototype criterias.

4. I don't think we need the green checkbox for "Standard Terms for TopCoder Competitions v2.1". Right now is distracting.

Thank you.

**Comment by Dara-K** [comment]
On winners tabs, when we have only 2 winners, let's show them one below the other as it looks better.
Not like it is now - example here: https://www.topcoder.com/challenges/30058214/?type=design&tab=winners

**Comment by birdofpreyru** [comment]
@Dara-K Can you give an example of a place where H3 is supposed to be used, but it is not? And where the accent colors are missing?

**Comment by Dara-K** [comment]
@birdofpreyru Sure! Check attached files.
The first one is how we defined the headings, while in second I marked for the RUX challenge, which headers should be H3. I also added some notes on the right side for spacings as I didn't see the fixed changes being pushed to site. 

The accent color is the blue bar, which we added to highlight the listed required pages. It does not appear on RUX, but it does on normal challenges.

![02 challenge details h3 marked](https://user-images.githubusercontent.com/25185079/32792099-356f8e36-c96b-11e7-93ad-88c72198bf02.png)
![01 challenge details original](https://user-images.githubusercontent.com/25185079/32792100-358e885e-c96b-11e7-842e-e21b81006519.png)

**Comment by birdofpreyru** [comment]
Actually, all this text for RUX challenges seems to be just copy/pasted as a regular challenge specs into Direct, so at the moment, we don't have a good control over those headers on Community App's side. We kind of can leverage it in a hacky way, but it can be error-prone. A good solution would be to fix the standard RUX description template that is copy pasted for RUX challenges.

**Comment by birdofpreyru** [comment]
I believe, taking into account the previous message, everything that we can solve in this big ticket is solved now. If something was missed, let's create and track it in new tickets.
