### ISSUE TITLE
Part of my Gigs Impl - Add Submit re-direction from community app

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#5590]
When user applies for the gigs from community-app, they should be directed to earns > my gigs page

NOTE : This may break Gigs > Apply flow as they can't apply from my gigs once they are here @Oanh-and-only-Oanh Glenn

**Comment by LieutenantRoger** [comment]
For Option 1, do we need to show how many gigs the user has applied ?  This looks like another API required.

**Comment by LieutenantRoger** [comment]
@SathyaJayabal @sushilshinde @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @sushilshinde , also do we not display option 1 when the user has not applied to any gigs yet?
<img width="559" alt="Screenshot 2021-06-26 at 8 55 00 PM" src="https://user-images.githubusercontent.com/58783823/123517833-cf9a6880-d6c0-11eb-868f-44dbb8367bc7.png">

**Comment by SathyaJayabal** [comment]
@LieutenantRoger @Oanh-and-only-Oanh @sushilshinde ,should we only display this for logged in users?

**Comment by SathyaJayabal** [comment]
Option 2 is verified on staging
<img width="1440" alt="Screenshot 2021-06-26 at 9 21 44 PM" src="https://user-images.githubusercontent.com/58783823/123518668-9663f780-d6c4-11eb-838c-fb3244693631.png">

**Comment by LieutenantRoger** [comment]
> For Option 1, do we need to show how many gigs the user has applied ? This looks like another API required.

We integrated the API in the earn-app, so this feature has been implemented.

**Comment by SathyaJayabal** [comment]
@sushilshinde @LieutenantRoger , verified option1

User with gigs
<img width="1440" alt="Screenshot 2021-06-28 at 12 41 05 PM" src="https://user-images.githubusercontent.com/58783823/123595438-89ebb600-d80e-11eb-9fbb-d5dc16157f72.png">

Not logged in user
<img width="1440" alt="Screenshot 2021-06-28 at 12 42 04 PM" src="https://user-images.githubusercontent.com/58783823/123595471-91ab5a80-d80e-11eb-9cfe-8abcb29de3e1.png">

User without gigs
<img width="1440" alt="Screenshot 2021-06-28 at 12 43 06 PM" src="https://user-images.githubusercontent.com/58783823/123595484-96700e80-d80e-11eb-95db-628ba46e3444.png">

**Comment by SathyaJayabal** [comment]
verified option 1 and 2 on prod
