### ISSUE TITLE
New theme for Contentful Tabs

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5595]
Desktop: https://marvelapp.com/prototype/ccah4h1/screen/80447501
Mobile: https://marvelapp.com/prototype/666a7di/screen/80484871

**Comment by kkartunov** [comment]
Here https://github.com/topcoder-platform/community-app/tree/new-tabs-theme

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-07-05 at 3 14 34 PM" src="https://user-images.githubusercontent.com/58783823/124452233-d3567b00-dda3-11eb-8fbc-e1e185a63274.png">

![mobile](https://user-images.githubusercontent.com/58783823/124452150-bf127e00-dda3-11eb-9802-08045c04ddf0.jpeg)

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-07-06 at 8 48 36 PM" src="https://user-images.githubusercontent.com/58783823/124625656-9d94bd80-de9b-11eb-8d57-52fc8b5e556a.png">
<img width="502" alt="Screenshot 2021-07-06 at 8 48 52 PM" src="https://user-images.githubusercontent.com/58783823/124625686-a4233500-de9b-11eb-8b1f-6cca76228f92.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-07-06 at 9 41 50 PM" src="https://user-images.githubusercontent.com/58783823/124633619-13e8ee00-dea3-11eb-88b1-be52bf85615b.png">
<img width="502" alt="Screenshot 2021-07-06 at 9 42 08 PM" src="https://user-images.githubusercontent.com/58783823/124633626-15b2b180-dea3-11eb-9a5e-535646c7653a.png">
