### ISSUE TITLE
New theme for TCO leaderboards

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5596]
Dekstop: https://marvelapp.com/prototype/ccah4h1/screen/80452646
Mobile: Not present, follow desktop in responsive way.

**Comment by SathyaJayabal** [comment]
TCO22 leaderboard challenge history popup: Challenge link broken 
https://tco22.topcoder.com/competition/development/leaderboard?tracks[dev-tco22]=0
<img width="1438" alt="Screenshot 2021-07-16 at 11 58 35 AM" src="https://user-images.githubusercontent.com/58783823/125906324-93edf60c-d900-4d78-97d1-5e6c1fd8db5f.png">

**Comment by kkartunov** [comment]
QA Link: `<ENV>/examples/contentful/viewport/4zT5nOVd9S7SQjvhNSmfix`

**Comment by SathyaJayabal** [comment]
verified on qa env
<img width="1429" alt="Screenshot 2021-07-16 at 3 13 27 PM" src="https://user-images.githubusercontent.com/58783823/125927993-dd2a59ca-59e1-4d2d-901b-8ba2183395c4.png">

<img width="642" alt="Screenshot 2021-07-16 at 3 12 39 PM" src="https://user-images.githubusercontent.com/58783823/125928010-d5d45ef9-7f7b-4378-9781-4e59765446bd.png">


<img width="1440" alt="Screenshot 2021-07-16 at 3 10 52 PM" src="https://user-images.githubusercontent.com/58783823/125928034-b7dc7562-a141-40ec-832d-2ed76dfbe6a0.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-07-20 at 9 23 40 AM" src="https://user-images.githubusercontent.com/58783823/126259472-77dd2c4e-01e0-4ab4-b4f8-1b4fa988de88.png">
<img width="495" alt="Screenshot 2021-07-20 at 9 20 49 AM" src="https://user-images.githubusercontent.com/58783823/126259490-8b687b03-cdfb-4342-a1ab-793484354509.png">
<img width="1440" alt="Screenshot 2021-07-20 at 9 20 31 AM" src="https://user-images.githubusercontent.com/58783823/126259491-ddfb5c00-1bbb-4e04-b274-4a379594c69b.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-07-20 at 6 33 39 PM" src="https://user-images.githubusercontent.com/58783823/126328955-0d74c5fe-5dff-4abf-89ef-28cc7b496895.png">
<img width="1440" alt="Screenshot 2021-07-20 at 6 31 14 PM" src="https://user-images.githubusercontent.com/58783823/126328972-37897e03-c1e2-47fa-8f02-e42d5fc4538d.png">
<img width="539" alt="Screenshot 2021-07-20 at 6 31 35 PM" src="https://user-images.githubusercontent.com/58783823/126328984-7f1c24a9-cb6e-47c5-b790-9e19496bca29.png">
