### ISSUE TITLE
New Navi component for TCO22

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5599]
Desktop: https://marvelapp.com/prototype/ccah4h1/screen/80447499
Mobile: https://marvelapp.com/prototype/666a7di/screen/80484873

**Comment by kkartunov** [comment]
@SathyaJayabal this one can be tested on https://beta-community-app.topcoder.com/examples/contentful/viewport/1nvm6EsPMHPLBtuGXNRMYV/

- ignore that it loads the same page all the time, we focus on the top header Navi itself in this issue

**Comment by SathyaJayabal** [comment]
@kkartunov for mobile the current sub menu selection is not highlighted

for example, this is the marathon page under competition, menu, but the marathon nav item is not highlighted.
![WhatsApp Image 2021-07-07 at 4 14 32 PM](https://user-images.githubusercontent.com/58783823/124746432-79d68380-df3e-11eb-973a-2749d67ddf81.jpeg)

**Comment by kkartunov** [comment]
@SathyaJayabal it is as per design but the team is looking into that. Please hold ...

**Comment by sdgun** [comment]
@kkartunov Verified in mobile. Current sub menu selection is highlighted now. Also checked in desktop.

![image](https://user-images.githubusercontent.com/4592712/125029881-e91bb700-e0a7-11eb-8e5e-58bf5c859074.png)

**Comment by sandhiyakavi** [comment]
@kkartunov If we click the user handle dropdown at the top header navi , the pop up menu is getting hided behind the image.

![image](https://user-images.githubusercontent.com/55895538/125231220-4c5e5100-e315-11eb-9d3b-601970577f8b.png)

Also under Regionals menu, only the submenu Overview is getting displayed, but in the design I am able to see many sub menus. is it expected?

![image](https://user-images.githubusercontent.com/55895538/125231462-becf3100-e315-11eb-88e9-7063b8bd1fd6.png)

![image](https://user-images.githubusercontent.com/55895538/125231439-b24ad880-e315-11eb-86a1-b9834db14fa2.png)

**Comment by kkartunov** [comment]
@sandhiyakavi this issues with z-index is fixed.

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Issue resolved and the Header navi in both desktop as well as Mobile is good.

![image](https://user-images.githubusercontent.com/55895538/125261749-8858dc80-e33c-11eb-8971-e8bd6eea6433.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env using the url https://community-app.topcoder.com/examples/contentful/viewport/1nvm6EsPMHPLBtuGXNRMYV/sponsors
![image_123986672](https://user-images.githubusercontent.com/55895538/125392742-b17f7880-e3e1-11eb-839c-ad389e8942e7.JPG)

![image](https://user-images.githubusercontent.com/55895538/125392364-feaf1a80-e3e0-11eb-8651-5c9eb4bbc721.png)
