### ISSUE TITLE
New "member talk cloud" component

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5600]
Desktop: https://marvelapp.com/prototype/ccah4h1/screen/80447499

**Comment by kkartunov** [comment]
Test URL for QA: https://qa-community-app.topcoder-dev.com/examples/contentful/viewport/5REupgS4MfQlKZkwthHFMU
Team approved the positioning of the avatars.

**Comment by kkartunov** [comment]
@SathyaJayabal this ready for QA, please.

**Comment by SathyaJayabal** [comment]
verified on qa @kkartunov 
<img width="1440" alt="Screenshot 2021-07-14 at 5 52 47 PM" src="https://user-images.githubusercontent.com/58783823/125621405-01006765-bf6e-4370-9b95-126c19772c87.png">
<img width="499" alt="Screenshot 2021-07-14 at 5 53 08 PM" src="https://user-images.githubusercontent.com/58783823/125621430-defb1fd4-a609-4433-a702-0447e3253376.png">

**Comment by kkartunov** [comment]
@SathyaJayabal @luizrrodrigues this one will be re-designed thus removing from milestone.

**Comment by kkartunov** [comment]
@SathyaJayabal this one is ready iteration, please QA.
It is currently on QA env: https://qa-community-app.topcoder-dev.com/examples/contentful/viewport/5REupgS4MfQlKZkwthHFMU

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-08-04 at 11 25 22 AM" src="https://user-images.githubusercontent.com/58783823/128129472-651247c4-ebd1-438f-a656-5f430e94a5ee.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-08-05 at 4 57 40 PM" src="https://user-images.githubusercontent.com/58783823/128342653-49167163-f7f8-434e-afd6-2ab656f2036c.png">
<img width="493" alt="Screenshot 2021-08-05 at 4 57 59 PM" src="https://user-images.githubusercontent.com/58783823/128342664-3e726d8c-779f-41c7-8e19-23eedc900272.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1434" alt="Screenshot 2021-08-05 at 10 03 25 PM" src="https://user-images.githubusercontent.com/58783823/128387362-34382cd8-4e9b-4003-aca7-ea94cbeb319d.png">
<img width="500" alt="Screenshot 2021-08-05 at 10 03 53 PM" src="https://user-images.githubusercontent.com/58783823/128387380-9819d08e-f2a3-4bf3-b142-650ff32f8401.png">
