### ISSUE TITLE
Remove TC logo pride

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5608]
tc logo pride

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-06-30 at 7 47 59 PM" src="https://user-images.githubusercontent.com/58783823/123979772-a2aac600-d9de-11eb-9027-190a7f7530bf.png">

**Comment by SathyaJayabal** [comment]
verified  on prod
<img width="1440" alt="Screenshot 2021-06-30 at 8 28 16 PM" src="https://user-images.githubusercontent.com/58783823/123983779-c15e8c00-d9e1-11eb-83dd-307ee4029a76.png">
