### ISSUE TITLE
Automated Smoke Testing - Member Profile TC_004 and TC_005

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5623]
- TC_001 ✔️ 
- TC_002 ✔️ 
- TC_003 ✔️ 
- TC_004 ❌ 
- TC_005 ❌ 
- TC_006 ✔️ 
- TC_007 ✔️ 

**Currently Results** (7 specs, 2 failures):
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3150/workflows/a6b36c59-51d1-4b23-85e1-9bb30b0deaeb/jobs/12985/parallel-runs/0/steps/0-107

**Comment by luizrrodrigues** [comment]
Fixed:

https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3150/workflows/e9b14cb4-8c8b-4e16-b51f-7a347225484f/jobs/13004/parallel-runs/0/steps/0-107

**Comment by SathyaJayabal** [comment]
fixed
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3166/workflows/1dfb847b-380e-406d-ab2f-4dcbc7de88a4/jobs/13014

**Comment by SathyaJayabal** [comment]
fixed on prod
https://app.circleci.com/pipelines/github/topcoder-platform/community-app/3169/workflows/b8742d03-8d50-4f19-8ff3-e7b7c6c31d36/jobs/13019
