### ISSUE TITLE
Add externalId=xxxx param when user navigates from Community-App to Earn-App after applied a gig opportunity

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#5631]
Expected behavior: 

After member applied a gig opportunity successfully, and once the user click 'CHECK GIG APPLICATION STATUS' button, the app shall redirect the member to the earn-app list screen with the gig externalId=xxx added in the query string,

so that earn-app can check whether the newly applied gig is synced yet in our backend system.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-07-07 at 1 29 30 PM" src="https://user-images.githubusercontent.com/58783823/124722354-9a471380-df27-11eb-96c4-abc7ac423fcf.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-07-07 at 2 20 47 PM" src="https://user-images.githubusercontent.com/58783823/124730154-b7331500-df2e-11eb-9fd2-293f4320936a.png">

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/124752028-f2404300-df44-11eb-8083-dc597a10f407.mov
