### ISSUE TITLE
Server logs showing these errors

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#5642]
Something is calling the metafiles those don't exists, that code is consuming CPU resource. This code needs to be optimized.
![CloudWatch Management Console 2021-07-14 11-52-32](https://user-images.githubusercontent.com/683231/125573822-186419f2-16e1-4e82-a1c9-5da35a7b4a9f.png)

**Comment by luizrrodrigues** [comment]
Issue coming from : https://github.com/topcoder-platform/topcoder-react-lib/blob/0fece444e72eed519ea33db680a1b44d5aad8272/src/services/terms.js#L56

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Fix validation will be done in server side (AWS Log)

Changes are related with Terms and Sub-Communities, please validate items bellow:
- Access Sub-Communities via custom domain ex: https://veterans.topcoder.com/
- Access Sub-Communities via community app URL, ex: https://community-app.topcoder.com/__community__/veterans
- New user when try to access Sub-Community first time, show terms to accept.

**Comment by SathyaJayabal** [comment]
verified on staging, if terms is displayed
<img width="1440" alt="Screenshot 2021-07-16 at 10 02 00 AM" src="https://user-images.githubusercontent.com/58783823/125892274-bd92afac-85de-45f8-a3dc-4bf4f9a9561b.png">

able to access veterans site for old user on dev
<img width="1440" alt="Screenshot 2021-07-16 at 10 05 01 AM" src="https://user-images.githubusercontent.com/58783823/125892375-78986d96-2a57-47d3-b2a2-d4433616e75d.png">

not able to use custom domain on dev

**Comment by luizrrodrigues** [comment]
`/community/learn`:
![image](https://user-images.githubusercontent.com/7029641/125895907-ae6ae84b-a585-485a-9825-6db0654e2e82.png)

`/community/member-programs`:
![image](https://user-images.githubusercontent.com/7029641/125896289-f6d5205c-ef5a-4b21-8b39-7957ec64d107.png)

**Comment by luizrrodrigues** [comment]
**Prod**
`/community/member-programs`:
![image](https://user-images.githubusercontent.com/7029641/125901575-2deaf2df-3962-4f6c-85c6-f87dbef49614.png)
