### ISSUE TITLE
TCO21 leaderboards fix

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5651]
The modal with history details is using the new look&feel(TCO22) for the podium spot card - this needs to be same card as the main view is using.

**Comment by kkartunov** [comment]
Screenshot
![Screenshot from 2021-07-22 10-22-59](https://user-images.githubusercontent.com/5585002/126603017-7475f9d1-1407-43ad-b9e4-850bff91a462.png)

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2021-07-22 at 3 31 25 PM" src="https://user-images.githubusercontent.com/58783823/126622198-4bfd9dc0-3133-47dd-afc2-f83789c667a8.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-07-23 at 4 12 41 PM" src="https://user-images.githubusercontent.com/58783823/126771314-df9e0875-82b6-431e-bc3d-4ae10086b0cd.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-07-23 at 5 56 31 PM" src="https://user-images.githubusercontent.com/58783823/126781621-454f7170-7ecd-4e91-b184-cd1f83bca57f.png">
