### ISSUE TITLE
Challenge Details phases : Read from scheduledEndDate if actualEndDate is not present

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5655]
https://github.com/topcoder-platform/work-manager/issues/1219#issuecomment-885782278
https://user-images.githubusercontent.com/51733042/126515791-6efd4e85-bb90-4a63-84e3-6b85d78633a9.png

**Comment by SathyaJayabal** [comment]
cc @luizrrodrigues @lakshmiathreya

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag and Dev env.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-07-29 at 10 25 07 AM" src="https://user-images.githubusercontent.com/58783823/127436483-e20a8065-48ee-4fe7-a721-d140125a5278.png">

**Comment by SathyaJayabal** [comment]
verified on code
<img width="697" alt="Screenshot 2021-08-05 at 4 56 13 PM" src="https://user-images.githubusercontent.com/58783823/128342412-0354a02d-9192-40ac-b981-4db75353f26f.png">

**Comment by SathyaJayabal** [comment]
verified in prod
