### ISSUE TITLE
Private Profile Redirection

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5656]
Whenever there is link from the topgear user on the community app it should directed to
Prod : https://topgear-app.wipro.com/user-details

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @sushilshinde @rakibansary , verified on QA env cases 1 to 6.

Logged in user: tonyj (topgear user)
1. When Topgear user accesses their own profile
https://qa-community-app.topcoder-dev.com/members/TonyJ
Redirects to WIPRO login page (Will test this on beta to test redirection to https://topgear-app.wipro.com/user-details)
<img width="1440" alt="Screenshot 2021-07-30 at 12 04 18 PM" src="https://user-images.githubusercontent.com/58783823/127611024-325ed49d-7f6f-414a-aba5-c78c66964126.png">


2. When Topgear user accesses another topgear user's profile.
https://qa-community-app.topcoder-dev.com/members/dan_developer
Loads the public profile of the user
<img width="1440" alt="Screenshot 2021-07-30 at 12 02 06 PM" src="https://user-images.githubusercontent.com/58783823/127610820-12251069-d718-4049-a302-12085ee1c7ac.png">

3. When Topgear user accesses another non topgear user's profile.
https://qa-community-app.topcoder-dev.com/members/tester1234
Loads the public profile of the user
<img width="1440" alt="Screenshot 2021-07-30 at 12 02 12 PM" src="https://user-images.githubusercontent.com/58783823/127610828-d566e9bd-d44b-4bcf-ae47-1e76b9e6e30a.png">

Logged in as tester1234 (non topgear user)
4. When a non topgear user accesses their own profile
https://qa-community-app.topcoder-dev.com/members/tester1234
Loads the public profile of the user

5. When a non topgear user accesses topgear users profile
https://qa-community-app.topcoder-dev.com/members/tonyj
Loads public profile of the user

6. When a non topgear user accesses another non topgear user's profile
https://qa-community-app.topcoder-dev.com/members/topacc_three
Loads public profile of the user


When the topgear member is accessing their profile from the topgear site, then the redirection is not happening. I think in this case too we must redirect to https://topgear-app.wipro.com/user-details
https://qa-community-app.topcoder-dev.com/__community__/wipro/members/tonyj
<img width="1440" alt="Screenshot 2021-07-30 at 12 07 58 PM" src="https://user-images.githubusercontent.com/58783823/127611408-a6c9de59-b4bd-4d5f-b315-d1432d5a3612.png">

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh @sushilshinde @rakibansary , verified on Dev env.
1. logged in topgear accesses their own profile, is redirected to wipro login
https://topgear.topcoder-dev.com/members/dan_developer
<img width="1440" alt="Screenshot 2021-08-02 at 9 03 07 AM" src="https://user-images.githubusercontent.com/58783823/127801452-e1053401-2c1c-4ecf-b85e-cfe12a5926e7.png">

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , 
1. What should be the behaviour when a topgear user accesses another topgear user's member profile on the topgear site?
example: https://topgear.topcoder-dev.com/members/TonyJ (logged in as dan_developer)

2. What should be the behaviour when a topgear user accesses another public user's member profile on the topgear site?
example: https://topgear.topcoder-dev.com/members/tester1234 (logged in as dan_developer)

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , Can you please verify the below ?
1. Login with wipro id.
2. Access https://beta-community-app.topcoder.com/__community__/wipro/members/<your handle>
3. Verify if the page is redirected to https://topgear-app.wipro.com/user-details

**Comment by lakshmiathreya** [comment]
@SathyaJayabal - verified both urls with my Wipro login - they redirect to https://topgear-app.wipro.com/user-details as expected. Will upload videos shortly.

**Comment by lakshmiathreya** [comment]
https://user-images.githubusercontent.com/51733042/127841446-b6819231-790d-43ad-85c8-764c95c1a946.mov

**Comment by lakshmiathreya** [comment]
https://user-images.githubusercontent.com/51733042/127844798-624c175c-4661-4cae-82a1-1156f9a41d7d.mov

**Comment by Oanh-and-only-Oanh** [comment]
> @Oanh-and-only-Oanh ,
> 
> 1. What should be the behaviour when a topgear user accesses another topgear user's member profile on the topgear site? 
>    example: https://topgear.topcoder-dev.com/members/TonyJ (logged in as dan_developer)
> 2. What should be the behaviour when a topgear user accesses another public user's member profile on the topgear site?
>    example: https://topgear.topcoder-dev.com/members/tester1234 (logged in as dan_developer)

@SathyaJayabal, Topgear user should **NOT** be allowed to access another topgear user's member profile.

**Comment by SathyaJayabal** [comment]
So @Oanh-and-only-Oanh , for these cases we should redirect to public profile?

**Comment by SathyaJayabal** [comment]
@rakibansary ,
for rule # 8 and #12, while accessing a members profile on the topgear site, we must load the public profile. But on dev, it loads the private profile.

Example:
pls compare
https://www.topcoder-dev.com/members/standlove and
https://topgear.topcoder-dev.com/members/standlove

<img width="1440" alt="Screenshot 2021-08-12 at 2 26 12 PM" src="https://user-images.githubusercontent.com/58783823/129168785-b1122a82-43ca-4a4a-9834-3e66ade96890.png">

<img width="1440" alt="Screenshot 2021-08-12 at 2 25 59 PM" src="https://user-images.githubusercontent.com/58783823/129168766-ba3ae8b1-c9ec-4b09-918e-38f89aff3b2d.png">

**Comment by SathyaJayabal** [comment]
verified on dev env (develop branch)
https://docs.google.com/spreadsheets/d/1zHO3upydBs1dwbmdO_rhQZv9SPxKEYhE5UGpDVko7v4/edit#gid=794201747

**Comment by SathyaJayabal** [comment]
verified on prod
