### ISSUE TITLE
Thrive - Details page updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5657]
﻿-- ﻿Generic banner and def image support. When no banner is set use a default image

﻿-- ﻿Separated Categories and Tags on the left side column﻿﻿

﻿-- Ads support on the left side of articles

design: https://marvelapp.com/prototype/14fiadgj/screen/81193803

**Comment by kkartunov** [comment]
@SathyaJayabal fyi

**Comment by kkartunov** [comment]
QA links:
https://qa-community-app.topcoder-dev.com/thrive/articles/publishing-dart-and-flutter-packages-at-pub-dev-part-1
https://qa-community-app.topcoder-dev.com/thrive/articles/preparing-to-work-with-datetime-information

**Comment by SathyaJayabal** [comment]
@kkartunov , the image is cutoff on the bottom
<img width="1440" alt="Screenshot 2021-08-11 at 9 42 31 AM" src="https://user-images.githubusercontent.com/58783823/128968645-dd7a2605-62b6-442c-9363-debc00bc1444.png">

**Comment by kkartunov** [comment]
@SathyaJayabal this should be fixed. Please re-test...

**Comment by SathyaJayabal** [comment]
Thanks @kkartunov 
<img width="1440" alt="Screenshot 2021-08-11 at 11 26 10 AM" src="https://user-images.githubusercontent.com/58783823/128976962-19f340d3-ae5e-4054-a51a-a859b55beb28.png">

**Comment by SathyaJayabal** [comment]
verified on staging
![Screenshot 2021-08-11 at 15-51-37 Preparing to Work with DateTime Information](https://user-images.githubusercontent.com/58783823/129013164-a27f001b-89dd-4e39-8b4c-dae39b1ae4d3.png)
![Screenshot 2021-08-11 at 15-52-30 Publishing Dart and Flutter packages at pub dev - Part 1](https://user-images.githubusercontent.com/58783823/129013189-efcfe0f2-4f60-499b-9347-06383dba7838.png)

**Comment by SathyaJayabal** [comment]
@kkartunov , this part is different form the design
<img width="1434" alt="Screenshot 2021-08-11 at 3 59 35 PM" src="https://user-images.githubusercontent.com/58783823/129014149-b2f47ed0-64b2-49d7-a05e-d36e831d4869.png">
<img width="1439" alt="Screenshot 2021-08-11 at 4 00 39 PM" src="https://user-images.githubusercontent.com/58783823/129014190-a9f2b43e-66aa-437c-88f4-0866c65fe474.png">
.

**Comment by kkartunov** [comment]
Thanks, this is content that can be edited from Contentful. We will use it for new published articles and keep the old style for existing ones.

Please proceed with release.
