### ISSUE TITLE
Meta tags! Page titles!

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#566]
1. Page name should reflect the content! For challenges - the name of the challenge, for the listing - saying it is the listing.

2. Meta tags for Open Graph protocol!
http://ogp.me/

**Comment by gondzo** [comment]
If possible, please render these server side. Many third party apps will just load the static content and won't execute any JS to get the meta tags. This is also true for Topcoder Connect. Related issue https://github.com/appirio-tech/connect-app/issues/881

**Comment by birdofpreyru** [comment]
Sure, I believe it will be done within the next few days.

**Comment by birdofpreyru** [comment]
There is a room for improvement, but initial implementation is ready and deployed (for challenge listing and details pages).
