### ISSUE TITLE
Generic referral links update

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5665]
In scope:
- Generic referral links support - from listing page and details page
- Update social share buttons on details page to include `referralId` in the link if member logged it
- Follow design https://marvelapp.com/prototype/80c404g/screen/81203940
  - [logged in case](https://marvelapp.com/prototype/80c404g/screen/81203943)
  - [anonymous case](https://marvelapp.com/prototype/80c404g/screen/81203940) with l[ogin modal](https://marvelapp.com/prototype/80c404g/screen/81203941)

**Comment by SathyaJayabal** [comment]
@kkartunov , the location of the gig application status for logged users is different in the design than that in production. Should the referral link be below the application status or above the title ?
<img width="1430" alt="Screenshot 2021-08-17 at 10 49 00 AM" src="https://user-images.githubusercontent.com/58783823/129667831-1280373c-a7bc-4c63-922a-81888f03da4e.png">

<img width="1440" alt="Screenshot 2021-08-17 at 10 47 48 AM" src="https://user-images.githubusercontent.com/58783823/129667819-f30d975b-4d5a-4ddf-9fcb-9404da7ce216.png">

**Comment by kkartunov** [comment]
@SathyaJayabal status banner is not in scope of this ticket. Referral should be above the title as on second image.

**Comment by SathyaJayabal** [comment]
@kkartunov , verified for the following cases:
1. Not logged in user: gigs listings, login modal, gigs details page.
<img width="1440" alt="Screenshot 2021-08-17 at 12 22 53 PM" src="https://user-images.githubusercontent.com/58783823/129677858-bd959f75-2c97-4448-abd3-5cabfb226921.png">

<img width="1440" alt="Screenshot 2021-08-17 at 11 58 30 AM" src="https://user-images.githubusercontent.com/58783823/129677882-556bf149-bec9-41b0-a64c-072571bd9d84.png">
<img width="1440" alt="Screenshot 2021-08-17 at 12 29 13 PM" src="https://user-images.githubusercontent.com/58783823/129678834-11491d38-6fb3-4144-a250-827f4b21ae0a.png">

 2. Gig Referral Page:
<img width="1440" alt="Screenshot 2021-08-17 at 12 24 25 PM" src="https://user-images.githubusercontent.com/58783823/129678105-c359ef41-4519-468b-a70f-962726f99699.png">

3. Logged in User: Gigs Listings page. Gigs Details Page
<img width="1440" alt="Screenshot 2021-08-17 at 12 31 10 PM" src="https://user-images.githubusercontent.com/58783823/129679130-a028e4ce-a712-468b-b882-54d4a352b5c5.png">
<img width="1440" alt="Screenshot 2021-08-17 at 12 31 55 PM" src="https://user-images.githubusercontent.com/58783823/129679152-9c482adc-94d0-4b64-9646-eb238b5f1971.png">

4. Verified that the application of a user who uses the referral link has the referral link associated with the  application,
![image (35)](https://user-images.githubusercontent.com/58783823/129679367-64835424-4436-4ab2-adfa-b43bf004dac2.png)

**Comment by SathyaJayabal** [comment]
5. Referral id added to social share buttons. 
<img width="1440" alt="Screenshot 2021-08-17 at 12 47 12 PM" src="https://user-images.githubusercontent.com/58783823/129681412-6ba6ddab-341d-475a-a98e-6469bb09924c.png">
<img width="1440" alt="Screenshot 2021-08-17 at 12 47 29 PM" src="https://user-images.githubusercontent.com/58783823/129681431-7b9c4409-f017-4f48-8ee5-3609fdf312bd.png">

<img width="1440" alt="Screenshot 2021-08-17 at 12 46 52 PM" src="https://user-images.githubusercontent.com/58783823/129681376-8fa5131b-f781-4759-9a04-0c901257369b.png">

**Comment by SathyaJayabal** [comment]
Verified on staging:
1. Not logged in user: gigs listings, login modal, gigs details page.
<img width="1440" alt="Screenshot 2021-08-19 at 10 08 12 AM" src="https://user-images.githubusercontent.com/58783823/130008752-cdbe2b72-04a3-4908-ab83-d64e59652aae.png">
<img width="1440" alt="Screenshot 2021-08-19 at 10 08 21 AM" src="https://user-images.githubusercontent.com/58783823/130008763-a0a1f271-2166-4f61-96d3-9a267f4c7694.png">
<img width="1440" alt="Screenshot 2021-08-19 at 10 08 50 AM" src="https://user-images.githubusercontent.com/58783823/130008765-ef66b1fe-1268-4b17-a5d9-1966b40c21f5.png">

2. Gig Referral Page:
<img width="1440" alt="Screenshot 2021-08-19 at 10 11 14 AM" src="https://user-images.githubusercontent.com/58783823/130008860-396463a0-211c-4692-b1c8-9883d5ac40c9.png">


3. Logged in User: Gigs Listings page. Gigs Details Page
<img width="1440" alt="Screenshot 2021-08-19 at 10 10 09 AM" src="https://user-images.githubusercontent.com/58783823/130008806-e94ef380-c9f0-4ea6-ba3e-f5170b5791e7.png">
<img width="1440" alt="Screenshot 2021-08-19 at 10 10 34 AM" src="https://user-images.githubusercontent.com/58783823/130008823-3856912a-f775-451f-a781-5e5d466ad094.png">


4. Referral id added to social share buttons.
<img width="1440" alt="Screenshot 2021-08-19 at 10 11 50 AM" src="https://user-images.githubusercontent.com/58783823/130009016-56aab4fd-48bc-44ae-b648-70f2d7764bb9.png">
<img width="1440" alt="Screenshot 2021-08-19 at 10 12 09 AM" src="https://user-images.githubusercontent.com/58783823/130009021-0dbb090b-4f1a-4f6a-a327-075037d59092.png">
<img width="1440" alt="Screenshot 2021-08-19 at 10 12 31 AM" src="https://user-images.githubusercontent.com/58783823/130009024-e44480d7-4f03-4d99-b549-59713956b3fc.png">

**Comment by SathyaJayabal** [comment]
verified on staging that referral is reflecting on growsurf

![Screenshot from 2021-08-19 09-36-33](https://user-images.githubusercontent.com/58783823/130020423-b8e6bd47-a36a-4f22-a15d-fd28b75c9a5c.png)
![Screenshot from 2021-08-19 09-38-12](https://user-images.githubusercontent.com/58783823/130020529-a3d0d134-2dde-48f3-8b8d-32b8a85f8ebd.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-08-19 at 3 38 03 PM" src="https://user-images.githubusercontent.com/58783823/130050848-818c3ab4-9078-4d1c-9a5f-c194e2a44ef4.png">
<img width="1440" alt="Screenshot 2021-08-19 at 3 38 05 PM" src="https://user-images.githubusercontent.com/58783823/130050872-2a4af6fe-5456-4b11-9415-2d9ca3b875ea.png">
<img width="1440" alt="Screenshot 2021-08-19 at 3 38 14 PM" src="https://user-images.githubusercontent.com/58783823/130050883-fe96984f-a871-4186-a170-e1f80466268b.png">
<img width="1440" alt="Screenshot 2021-08-19 at 3 38 45 PM" src="https://user-images.githubusercontent.com/58783823/130050888-528f66a6-f88d-47a1-ab69-2f9ad25597a9.png">
<img width="1440" alt="Screenshot 2021-08-19 at 3 38 51 PM" src="https://user-images.githubusercontent.com/58783823/130050889-e5b1cd3a-8268-4a3b-a931-0c99961257c6.png">
![Screenshot from 2021-08-19 13-03-07](https://user-images.githubusercontent.com/58783823/130050944-04395261-6aa8-4f93-9864-1788f682b777.png)
<img width="1264" alt="Screenshot 2021-08-19 at 3 35 20 PM" src="https://user-images.githubusercontent.com/58783823/130050965-343f3058-bffa-45d3-8e6b-02adadb98f6e.png">
