### ISSUE TITLE
Topgear to Topcoder redirection Issue for Challenge Listings and Details pages

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5666]
-- Non logged in Topgear member - after login - is redirected to Topgear home page instead of the respective Challenge Listings or Details page they accessed prior to login.
image
cc @SathyaJayabal

we worked on previously on this kind of issue here - topcoder-platform/community-app#5576 topcoder-platform/community-app#5565

**Comment by Oanh-and-only-Oanh** [comment]
@luizrrodrigues can you please work with @sachin-maheshwari to resolve this issue? Thank.

**Comment by lakshmiathreya** [comment]
Ref: https://github.com/topcoder-platform/tc-auth-lib/issues/265

**Comment by luizrrodrigues** [comment]
@SathyaJayabal @sachin-maheshwari 

Fix deployed to Dev and Stag.

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , can you please help test this.

**Comment by luizrrodrigues** [comment]
@lakshmiathreya @sachin-maheshwari Please hold on testing this one, I'll need use Dev and Stag to a release. 
I'll ping here when this fix back to Dev and Stag.

**Comment by luizrrodrigues** [comment]
@lakshmiathreya @sachin-maheshwari 
Fix deployed again to Dev and Stag envs.

**Comment by lakshmiathreya** [comment]
@luizrrodrigues pls confirm if you have deployed the fix on Staging. I will test it later in the day today once confirmed.

**Comment by luizrrodrigues** [comment]
@lakshmiathreya Yep, branch currently deployed to Staging only.

**Comment by lakshmiathreya** [comment]
Verified Redirection on Staging.

**Comment by lakshmiathreya** [comment]
- Listings and Details redirection verified on Topgear Staging.

**Comment by lakshmiathreya** [comment]
Verified redirection for Home page, Challenge Listings and Details page - Production Topgear. Verified on MacOS, iOS, FF, Chrome and Safari.
