### ISSUE TITLE
Exempt all @topcoder.com emails from getting redirected to topgear profile

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5673]
All @topcoder.com emails must be exempted from getting redirected to topgear profile and instead must load their topcoder profiles

cc @Oanh-and-only-Oanh @sushilshinde

**Comment by SathyaJayabal** [comment]
verified on dev
https://docs.google.com/spreadsheets/d/1zHO3upydBs1dwbmdO_rhQZv9SPxKEYhE5UGpDVko7v4/edit#gid=794201747

**Comment by lakshmiathreya** [comment]
Verified on Prod:
-- With Topcoder email and handle - https://topcoder.com/members/lakshmiathreya - redirected to:

-- With Topgear handle/Wipro email - https://topgear.topcoder.com/members/lakshmiwip2306 - redirected to:
<img width="1680" alt="Screenshot 2021-09-01 at 4 01 06 PM" src="https://user-images.githubusercontent.com/51733042/131656526-1cbf7b6d-4925-45a4-a55e-1a83fe8640db.png">
-- With Topgear handle/Wipro email - https://topgear.topcoder.com/members/lakshmiathreya - redirected to:
<img width="1680" alt="Screenshot 2021-09-01 at 4 08 17 PM" src="https://user-images.githubusercontent.com/51733042/131657598-2a60fb4a-06b6-4d28-8c66-5424b567945d.png">

**Comment by lakshmiathreya** [comment]
-- With TC email/handle member of Wipro-all - https://topcoder.com/members/lakshmiwip2306 - redirected to:
<img width="1680" alt="Screenshot 2021-09-01 at 4 28 43 PM" src="https://user-images.githubusercontent.com/51733042/131660113-dabf7bad-0afc-486f-810a-0fd1b7cd100f.png">

**Comment by lakshmiathreya** [comment]
@SathyaJayabal - Please review the above combinations and let me know ...

**Comment by SathyaJayabal** [comment]
@lakshmiathreya , looks good
