### ISSUE TITLE
Thrive - updates

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5676]
1. Add info section below the search bar as per design: https://marvelapp.com/prototype/528hj20/screen/81640444

2. Update Thrive page title to: "Tutorials And Workshops That Matter | Thrive | Topcoder"

3.  Update category section to match design: https://marvelapp.com/prototype/14fiadgj/screen/81423110

**Comment by SathyaJayabal** [comment]
verified on qa
<img width="1440" alt="Screenshot 2021-09-09 at 3 08 25 PM" src="https://user-images.githubusercontent.com/58783823/132663136-01a04207-c088-445c-87ca-c3bc7ac5a004.png">
<img width="1440" alt="Screenshot 2021-09-09 at 3 12 14 PM" src="https://user-images.githubusercontent.com/58783823/132663177-b68dac12-5366-4b53-a24b-c54eb6418bf8.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-09-09 at 6 11 51 PM" src="https://user-images.githubusercontent.com/58783823/132688197-fd6cb3b9-a1dc-4fa7-a3dd-49aafe3164cc.png">
<img width="1440" alt="Screenshot 2021-09-09 at 6 14 09 PM" src="https://user-images.githubusercontent.com/58783823/132688227-9d6a8824-7a0b-427c-8738-66bc3953a214.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-09-09 at 7 50 24 PM" src="https://user-images.githubusercontent.com/58783823/132703496-2c100ba1-f1ec-41db-931b-1d4052d91423.png">
<img width="1440" alt="Screenshot 2021-09-09 at 7 51 12 PM" src="https://user-images.githubusercontent.com/58783823/132703704-50598a04-e013-44ea-9028-b0a7a3722c0e.png">
