### ISSUE TITLE
Link the text "Topcoder Referral Program"

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5677]
Link it to info page.
﻿Appears when user is logged in on /gigs page in the referr banner.

2. Update the page title for /gigs to: "Find Freelance Work | Gigs | Topcoder"

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-09-08 at 1 07 31 PM" src="https://user-images.githubusercontent.com/58783823/132466750-cb6ec67b-f986-42e9-871a-f99782dd45ef.png">
<img width="1440" alt="Screenshot 2021-09-08 at 1 07 06 PM" src="https://user-images.githubusercontent.com/58783823/132466769-9bc40b3a-1262-45ac-8865-59b09b0e2ac3.png">
@kkartunov , should we also add the link in the not logged in case?
<img width="1440" alt="Screenshot 2021-09-08 at 1 08 47 PM" src="https://user-images.githubusercontent.com/58783823/132467009-73d40a18-a1a0-4959-a898-b833a5d70ca9.png">

**Comment by kkartunov** [comment]
@SathyaJayabal not needed in not logged in case as there is link to info page when they click the Reffer a friend button.

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-09-09 at 6 02 22 PM" src="https://user-images.githubusercontent.com/58783823/132686672-5c4056da-e853-497f-a1a7-5a20bc31505a.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-09-09 at 7 46 06 PM" src="https://user-images.githubusercontent.com/58783823/132702712-5f18b3c9-5f97-4f1f-93c3-f7ce9129a74d.png">
<img width="1440" alt="Screenshot 2021-09-09 at 7 46 20 PM" src="https://user-images.githubusercontent.com/58783823/132702742-1e3e6719-1881-4bf1-9281-403f74b2f4f3.png">
