### ISSUE TITLE
Automated Smoke Testing - Fix profile test data

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5678]

**Comment by SathyaJayabal** [comment]
verified
<img width="1437" alt="Screenshot 2021-09-01 at 11 24 57 AM" src="https://user-images.githubusercontent.com/58783823/131619277-e1d0df2b-1045-41a1-a705-d7193d502c26.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1432" alt="Screenshot 2021-09-01 at 3 48 18 PM" src="https://user-images.githubusercontent.com/58783823/131654804-4bacb4b2-48ab-46da-b143-57819616542d.png">
