### ISSUE TITLE
remove MM prize amount from listing

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#568]
Hide the prize column until we have prizes returned from the API for marathon matches.

**Comment by sushilshinde** [comment]
Done! feature branch : `mm-fixes`

**No value for MM**
![1](https://user-images.githubusercontent.com/683231/32551386-5c71b194-c4b6-11e7-8b7c-e11e5859a3bc.png)

**Other DataScience cards shows value**
![2](https://user-images.githubusercontent.com/683231/32551431-7ce78ba6-c4b6-11e7-9c7d-d3f3c8bea635.png)

**Comment by ajefts** [comment]
Nice!

@birdofpreyru mind doing a quick code review?

**Comment by birdofpreyru** [comment]
@ajefts ok, will check and merge shortly

**Comment by birdofpreyru** [comment]
merged into *develop*
