### ISSUE TITLE
Revamp my-dashboard aka slash TC

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5683]
Design: https://marvelapp.com/prototype/5deb86c/screen/81579177
Mobile: https://marvelapp.com/prototype/cfi4i9b/screen/81579082

URL change:  /my-dashboard -> /home should be the new address.

**Comment by SathyaJayabal** [comment]
@kkartunov , the new address seems to be
https://beta-community-app.topcoder.com/home

**Comment by SathyaJayabal** [comment]
@kkartunov , before the dashboard was available for only the logged in users. Now I think it is available to not logged in users too (as I dont see any user specific data).  Now the logged in users have the `Home` nav item for the new dashboard. But this nav item is missing for not logged in users. 
<img width="1440" alt="Screenshot 2021-09-27 at 11 34 46 AM" src="https://user-images.githubusercontent.com/58783823/134853159-390556c5-9341-4016-a285-ee865427c1f9.png">

<img width="1440" alt="Screenshot 2021-09-27 at 11 35 02 AM" src="https://user-images.githubusercontent.com/58783823/134853151-6cf4f953-06e6-4f13-968d-ac72bae03800.png">

What do you mean by aka slash TC ? I see it also on the carousel on the new dashboard?

**Comment by kkartunov** [comment]
Hi @SathyaJayabal here are the comments:

1. Yes, new address is /home. I updated the ticket.
2. The design is outdated - it has to be 24h time format in UTC time.
3. We don't have blog post about it yet. There will be new slides for the launch that will be linked to posts latter. The 3th slide demoes the capability that links slides from Contentful. It is working fine and we could have linked slided when we want.
4. Updated to next event we will have.
5. News feed is sorted by latest posted discussion not by latest comments. It is not a new news when someone comments on the thread thus we good so.
6. Yes, should be latest 5 gigs/challenges.
7. We can update that from Contentful. It is just ads spot which can be configured. It is better said Azure Data Engineer tho'.
8. Oh, good catch! I has to be accessible only for logged in users. Will push update for that...

/TC is acronym for page that was existing long ago but was taken down. We now bring it back and revamp it so to say.

**Comment by SathyaJayabal** [comment]
@kkartunov so the /TC is the new dashboard page ? so should the www.topcoder.com/tc  load the new dashboard?

**Comment by kkartunov** [comment]
yes. This redirect to /tc will be handled later after we relese the codebase.

**Comment by sdgun** [comment]
Verified in mobile(Android/ios) observed the below issue.

![image](https://user-images.githubusercontent.com/4592712/134894062-9444743e-8e25-4000-9811-5385bf8dc023.png)

**Comment by kkartunov** [comment]
Thanks @sdgun this is fixed in latest comit. cc @SathyaJayabal

**Comment by kkartunov** [comment]
latest updates deployed to https://staging-community-app.topcoder.com/home
@SathyaJayabal @sdgun

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2021-09-28 at 11 56 36 AM" src="https://user-images.githubusercontent.com/58783823/135034676-4f59962b-b78f-4161-a2c9-a2a622a1969d.png">

**Comment by sandhiyakavi** [comment]
Verified in Prod

![image](https://user-images.githubusercontent.com/55895538/135068558-9f03d172-d11f-44a8-ad78-caf8c097c0f3.png)
