### ISSUE TITLE
Challenge Details - Add "All About Topcoder" thrive link

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5691]
Adding new link to the sidebar

![Screen Shot 2021-09-03 at 09 28 54](https://user-images.githubusercontent.com/4476442/131942814-360ead20-e161-4f29-b7a6-b5b081bb99f2.png)

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag env

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-09-09 at 4 54 39 PM" src="https://user-images.githubusercontent.com/58783823/132677419-84f9abaa-d8c9-4f08-8951-e5d155c79a21.png">

**Comment by SathyaJayabal** [comment]
verified on staging (develop)
<img width="1440" alt="Screenshot 2021-09-09 at 6 09 47 PM" src="https://user-images.githubusercontent.com/58783823/132687422-1cedf02b-ee83-400f-9b35-970ecdabe7a3.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-09-09 at 7 48 14 PM" src="https://user-images.githubusercontent.com/58783823/132703199-8321f63a-ee82-474f-872d-3c4c0b5ff148.png">
