### ISSUE TITLE
Create 2 new communities

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#57]
I'd like to add 2 new communities as follows:

1. Topcoder Product Development
  - This will be a community similar to Wipro.  It should be restricted to a group. It can have the same pages as well.

2. Demo Expert Community
  - This should be open to the public - no login required
  - Challenges will use a tech tag for filtering, as well as a group ID.  For example, we might want to show challenges in group 1001 plus any challenge with tech=reactJS.

**Comment by birdofpreyru** [comment]
@ajefts Done in 537be16594d80db0c302261731963b61bb567e97. There is another commit with small correction of authorization logic for the communities, which is still being built, as I am posting this.

Topcoder Product Development community is available at community-west.topcoder-dev.com/community/tc-prod-dev/home, and once you permit such sub-domain it will be accessible as tc-prod-dev.topcoder-dev.com

Demo Expert Community is available at community-west.topcoder-dev.com/community/demo-expert/home, and once you permit such sub-domain, it will be accessible at demo-expert.topcoder-dev.com

There is a small problem with the backend API and challenge listing in case of Demo Expert Community: if we allow access without authentication, we have no auth token, and without auth token the backend ignores group filtering, so you will see all public challenges, filtered by the tag. If you access it while logged in, it currently uses ID 1001 for the group, and `.NET` for the tag filter.
