### ISSUE TITLE
Infinite loop detected on gig referrals banner when loading

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5703]
As per title. Infinite loop with 429 error.
Fix to free API and resources.
![Screenshot from 2021-09-20 12-48-50](https://user-images.githubusercontent.com/5585002/133983648-6b07d39f-a157-4fe9-9293-0f23fc16f731.png)

**Comment by SathyaJayabal** [comment]
A message is now displayed.
<img width="1440" alt="Screenshot 2021-09-20 at 5 05 19 PM" src="https://user-images.githubusercontent.com/58783823/133995869-20312a87-8079-45b2-9c7b-fe983d30eb25.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Message: "Ops, we couldn't load your profile. Please try again later or contact support " is getting displayed now.

![image](https://user-images.githubusercontent.com/55895538/134122870-44e23776-999d-4984-9140-6342b3e94479.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.  Message: "Ops, we couldn't load your profile. Please try again later or contact support " is getting displayed 

![image](https://user-images.githubusercontent.com/55895538/134143891-377dd943-879d-4512-ae64-c57a339cffbc.png)
