### ISSUE TITLE
Add caching layer to speed initial /gigs loading

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5706]
As per title.

**Comment by kkartunov** [comment]
This also handles #5506 
No more duplicates are present in the location dropdown.

**Comment by sandhiyakavi** [comment]
Verified on Dev (QA) Env.


https://user-images.githubusercontent.com/55895538/134862019-36b3eae2-1511-49a9-b080-5ac97f4f19aa.mp4

**Comment by sandhiyakavi** [comment]
Verified on staging Env.


https://user-images.githubusercontent.com/55895538/135032767-be870d28-8c3f-4290-ab96-b3dde7568f4a.mp4

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/135069054-186b5250-8b33-48ef-9168-c937b0efb06f.png)
