### ISSUE TITLE
Submissions tab breaking for this challenge 4dd97775-493e-4bb5-b5e3-cd16aa5ab689

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#5708]
https://www.topcoder.com/challenges/4dd97775-493e-4bb5-b5e3-cd16aa5ab689?tab=submissions

**Comment by sushilshinde** [comment]
fixed and available on staging for QA

**Comment by sandhiyakavi** [comment]
Verified on Staging Env. Submission tab is not breaking for the challenge.

![image](https://user-images.githubusercontent.com/55895538/134458685-ab5fa1a1-122a-41c6-b2d2-efe872ced470.png)

**Comment by sandhiyakavi** [comment]
Verified on Staging (Production backend). Working as expected

![image](https://user-images.githubusercontent.com/55895538/134483798-36f53396-cad1-46ab-bb8e-0f5d67f70adc.png)

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-09-23 at 5 55 38 PM" src="https://user-images.githubusercontent.com/51733042/134506490-59d0bd3f-04ea-4d8d-b215-2e2b42895d43.png">

**Comment by lakshmiathreya** [comment]
Verified Submission tab for this challenge on Prod.
