### ISSUE TITLE
Marathon Match dates are off

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#571]
If you look at the MMs on the listing, you'll notice that 2 of them show as stalled.  The end dates are also displaying as dates in the past.  However, the matches are still open.  For example, here are the real dates for 1 match:  https://community.topcoder.com/tc?module=MatchDetails&rd=16996

![image](https://user-images.githubusercontent.com/3812270/32512233-5deed788-c3c4-11e7-8b43-9aa673b4c03e.png)

I believe the issue is that the API is returning start/end dates incorrectly.  However, I think we can fix this by reading the dates from the API for the phases.  For example, 

https://api.topcoder.com/v3/marathonMatches/?filter=status%3DACTIVE&limit=50&offset=0

Start Date is really registrationStart and End Date is really codingEnd.

![image](https://user-images.githubusercontent.com/3812270/32512334-b2e562c0-c3c4-11e7-925d-314f7166a2b7.png)

**Comment by ajefts** [comment]
@sushilshinde Do you think you could do this one and the prize hiding asap?

**Comment by birdofpreyru** [comment]
@sushilshinde worth to check these places in Community App code, which normalize MM data object to the same structure as the regular challenges:
https://github.com/topcoder-platform/community-app/blob/develop/src/shared/services/challenges.js#L58
I believe, it is enough to edit something there to show the correct status and maybe even prizes.

**Comment by sushilshinde** [comment]
@ajefts @birdofpreyru sure.
