### ISSUE TITLE
Start page update

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5721]
https://www.topcoder.com/start new design and update.

Desktop: https://marvelapp.com/prototype/15ff8jgj/screen/82264831
Mobile: https://marvelapp.com/prototype/15fgfedj/screen/82183678

**Comment by kkartunov** [comment]
@SathyaJayabal QA link: https://qa-community-app.topcoder-dev.com/examples/contentful/viewport/69PIeGEr86ALH5DJzjKShB
After release we will switch this new page to /start from Contentful.

**Comment by sdgun** [comment]
In iOS the images on the animation are not loading.

ios - 14

Ex-

![Image from iOS](https://user-images.githubusercontent.com/4592712/135858333-86f4795b-834c-4115-af2c-23533bd8b4b5.png)

![Image from iOS](https://user-images.githubusercontent.com/4592712/135858340-2bde1c64-bb8e-4542-8329-d7c7234ade72.jpg)

**Comment by kkartunov** [comment]
@sdgun me, the team and other testers do see the images. 
Can you make sure it is not connection issue or slow speed issue?
Some screenshots from console will help too

**Comment by kkartunov** [comment]
@SathyaJayabal can you confirm the issue?

**Comment by kkartunov** [comment]
@SathyaJayabal @sdgun looks those phones have issues with SVGs. Here are the raw srouce links for the images, do you can see them?

https://images.ctfassets.net/b5f1djy59z3a/3sAwNaFzuwGmmZPYSJikJi/0c578a37f31c4a7c6ba5b6e31fe149a9/icon-build-skills.svg
https://images.ctfassets.net/b5f1djy59z3a/3U8CiHTjU2umzKo7YF08IM/c2ab6e9c5b0c4d8bf42fe6372a239c47/icon-learn.svg
https://images.ctfassets.net/b5f1djy59z3a/30TKQ2Wh32OkGefCUJZfBM/585e5892237a1abe134e6ed8ccbdd94e/icon-gig.svg

**Comment by SathyaJayabal** [comment]
I can these
![samplesvg](https://user-images.githubusercontent.com/58783823/135870404-7371926a-1610-458b-98ac-0ecfb0b33202.jpeg)

**Comment by SathyaJayabal** [comment]
@kkartunov verified
![8148](https://user-images.githubusercontent.com/58783823/135952127-a04b8cdf-c849-41b8-a57d-8c0a9ab7348e.jpeg)

**Comment by sdgun** [comment]
Verified in staging 

![image](https://user-images.githubusercontent.com/4592712/135977931-6a94b8ca-f771-48a8-bf98-283954860fe9.png)

**Comment by SathyaJayabal** [comment]
@kkartunov , verified the test page on prod, we can update the start page
<img width="1431" alt="Screenshot 2021-10-05 at 2 49 18 PM" src="https://user-images.githubusercontent.com/58783823/135996135-d6b1636f-b8cd-4c48-9cd4-9baf2e873106.png">
