### ISSUE TITLE
Wrong links building at /home gigs

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5722]
1. Links for Gigs section at /home are wrong. Instead `https://community-app.topcoder.com/gigs...` those should use the `https://topcoder.com/gigs...` addresses.
2. View all challenges should change to /challenges.

**Comment by kkartunov** [comment]
@SathyaJayabal

**Comment by sdgun** [comment]
Verified in Beta.


https://user-images.githubusercontent.com/4592712/135849898-6d385868-d280-4132-bf47-8b6faf385430.mp4

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/135974744-270a2b94-147e-4167-b15e-845e4e42ae28.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-10-05 at 2 53 38 PM" src="https://user-images.githubusercontent.com/58783823/135996927-44e79873-7a12-4124-b0ce-15485a06ba19.png">
<img width="1440" alt="Screenshot 2021-10-05 at 2 53 56 PM" src="https://user-images.githubusercontent.com/58783823/135996976-a4027b25-6060-44f2-aed8-fb8b75c21da1.png">
