### ISSUE TITLE
Add new options to "where did you hear about this gig" in the application

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5723]
To add:

"Topcoder Newsletter"
"Referral"

**Comment by kkartunov** [comment]
@SathyaJayabal deployed on test env.

**Comment by sdgun** [comment]
Verified in dev

![image](https://user-images.githubusercontent.com/4592712/135849076-75a2d490-35ec-4f43-bc44-150e30bca5ce.png)

**Comment by sdgun** [comment]
Verified in Staging.

![image](https://user-images.githubusercontent.com/4592712/135972583-93c40b8f-9d2b-4e8e-97cb-59a1ecda38c6.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-10-05 at 2 52 46 PM" src="https://user-images.githubusercontent.com/58783823/135996631-0afe1226-a0d8-4e7c-8d13-032ecf193bd2.png">
