### ISSUE TITLE
Remove X-Frame-Options from DocuSign request

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5732]
Reference: https://github.com/topcoder-platform/micro-frontends-challenges-app/issues/18

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. 

NDA Terms:

https://user-images.githubusercontent.com/55895538/136174634-f9d0ff49-d909-4162-aad9-38f15a88b10d.mp4

Standard Terms:


https://user-images.githubusercontent.com/55895538/136174738-19aad35c-d49a-4b9f-a1ba-df19a3e2b85e.mp4
