### ISSUE TITLE
"Home" page's challenges total prize is wrong.

### ISSUE THREAD

**Issue by nursoltan-s** [topcoder-platform/community-app#5739]
**Describe the bug**
Dashboard (Home) page's challenges component's total prize is displaying wrong prize.

**To Reproduce**
1. Go to 'https://www.topcoder.com/home'
2. Select one challenge and see total prize.
3. Click on challenge and see placement prizes. 
4. See error home page's total prize and challenge detail page's prizes are not equal. Home page's prize is adding copilot's prize as well.

**Expected behavior**
It should be same as challenge detail page's total prize.

**Screenshots**
For example, see this challenge:
<img width="703" alt="Screen Shot 2021-10-12 at 20 59 24" src="https://user-images.githubusercontent.com/7783676/136961026-17d4a3fe-aec6-4574-b10c-db339788cee0.png">

It should add only "placement" type prizes. Therefore, this challenge should show: "1200$".
<img width="1440" alt="Screen Shot 2021-10-12 at 21 00 53" src="https://user-images.githubusercontent.com/7783676/136961152-d02c90ba-8943-4af9-bace-260c605cf9e3.png">

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 94

**Comment by kkartunov** [comment]
@SathyaJayabal this is deployed on staging for QA against real challanges.

**Comment by SathyaJayabal** [comment]
verified on staging (feature branch)
<img width="1440" alt="Screenshot 2021-10-14 at 8 39 29 AM" src="https://user-images.githubusercontent.com/58783823/137244457-08cebc6d-dab8-496a-8394-e953000f5639.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env

![image](https://user-images.githubusercontent.com/55895538/137267063-310c8574-8a20-4e6c-ac90-7830c6564ee3.png)
