### ISSUE TITLE
Submission throwing error for tasks for all tracks [Dev, Design, DS and QA]

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/community-app#5744]
**Describe the bug**
When trying to submit complete work through the community app. It's a throwing error. please see attached screenshot for the issue

**To Reproduce**
1. Go to Task of any tracks for eg.''https://www.topcoder.com/challenges/53df552c-2c99-48cc-a0f3-2832605afa8a"
2. Click on ''Submit" button
3. See an error
4. 
![image](https://user-images.githubusercontent.com/62358241/138115442-86a8d69f-bfd2-4a37-ab2a-5c076ff110d4.png)

**Expected behavior**
Submission should work for task for all tracks

**Screenshots**
![image](https://user-images.githubusercontent.com/62358241/138115526-cb068e67-d03e-4138-9955-4bbc639da7b6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Window 10
 - Browser [e.g. chrome, safari]: All latest browser

**Comment by codejamtc** [comment]
@lakshmiathreya This is not a `Task`? https://www.topcoder.com/challenges/4bbbc3d6-c762-4f11-8894-de330bad7456
This is a dev challenge? cc @coderhacker

**Comment by coderhacker** [comment]
This is passed on production, please attached screenshot

https://user-images.githubusercontent.com/62358241/139619344-b0c2a5a9-d0a6-434d-89fc-42c33ce2c458.mp4
