### ISSUE TITLE
Registrants values are wrong on MM cards

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#576]
@dmessing observed values are zero for registrants in marathon cards

![screenshot-www topcoder com-2017-11-09-11-45-35-989](https://user-images.githubusercontent.com/683231/32591326-a7464340-c544-11e7-8667-2e6b251435cf.png)

**Comment by sushilshinde** [comment]
## Analysis

**This is the MM API Endpoint**
https://api.topcoder.com/v3/marathonMatches/?filter=status%3DACTIVE&limit=50&offset=0

[Code](https://github.com/topcoder-platform/community-app/blob/324faebd7c780bce723f1b6d42bd49065aef8785/src/shared/services/challenges.js#L90) that normalizes response.

This code expects challenge object to have numRegistrants but it's not returned in the API reponse.
`numRegistrants: challenge.numRegistrants ? challenge.numRegistrants[0] : 0`

And submissions is the derived value of userIds array length @ajefts is this right. 
`numSubmissions: challenge.userIds ? challenge.userIds.length : 0`

challenge.numRegistrants attribute is not a part of object/response and it will always be zero.

My guess is this bug existed from the first commit, probably nomalization was percieved from the challenge API response.

On the other hand [Challenge API](https://api.topcoder.com/v3/challenges/?filter=status%3DCOMPLETED&limit=50&offset=0) have these attributes 
```
numSubmissions: 0,
numRegistrants: 0,

```

**Comment by birdofpreyru** [comment]
@sushilshinde agree, what is now set to `numSubmissions` during the normalization, should be actually `numRegistrants`; and for number of submissions we just don't have data in the API response. I we can rapidly add them into response on API side, putting the correct mapping into that normalization function should fix the problem.

**Comment by dmessing** [comment]
Yes ok to leave submissions as 0 just flop registrants numbers

**Comment by sushilshinde** [comment]
Issue fixed @birdofpreyru PR created 

FYI - @dmessing @ajefts

**Comment by sushilshinde** [comment]
@birdofpreyru one observation as you mentioned above, submissions value is available here and should be a part of API response in API fix
![obser](https://user-images.githubusercontent.com/683231/32609263-243104cc-c585-11e7-93c5-90d75f5c3355.png)
