### ISSUE TITLE
Thrive spooky1 bugs - 2

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5763]
In scope are:

https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/186
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/400
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/109
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/441
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/467 related with 441
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/303
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/438

**Comment by kkartunov** [comment]
@SathyaJayabal on beta please check.

**Comment by sandhiyakavi** [comment]
Verified in Beta Env.

1. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/186
![image](https://user-images.githubusercontent.com/55895538/140010660-1f182c06-8b78-49e5-a1db-dd6ca7b50bb6.png)

2. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/400

https://user-images.githubusercontent.com/55895538/140011077-dfb61d5c-bb33-4375-88a4-3ba0f21cda8a.mp4

3. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/109

https://user-images.githubusercontent.com/55895538/140011469-95aff177-b903-4a52-bcac-6448dcb530de.mp4

4. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/441 and https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/467

https://user-images.githubusercontent.com/55895538/140011768-0094223f-2248-4847-9559-916a4378d389.mp4

5. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/303
![image](https://user-images.githubusercontent.com/55895538/140012258-317ad701-e528-429b-a0d1-007a73ffb4c6.png)

6. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/438 - Able to get results now by applying filters and no console error is shown.

![image](https://user-images.githubusercontent.com/55895538/140012669-a5536e62-1848-44fe-a69d-13d134863ae9.png)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env. Working as expected.

**Comment by sandhiyakavi** [comment]
Verified in Staging Env (Smoke test). Working as expected

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as Expected.
