### ISSUE TITLE
Contentful tabs - mobile update

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5764]
Scope: update tabs for mobile (<768px) devices as per this design https://marvelapp.com/prototype/ed9e597/screen/83121229

URL: https://tco21.topcoder.com/interviews?tracks[tco21-algorithm]=0&tracks[tco21-development]=0&tracks[tco21-f2f-interview]=0&tracks[tco21-marathon]=0&tracks[tco21-qa-track]=0&tracks[tco21-track]=0&tracks[tco21-trip-winners]=0&tracks[tco21-ui-design-track]=0

**Comment by kkartunov** [comment]
@SathyaJayabal this is currently on beta deployed. Can use this URL for QA: https://beta-community-app.topcoder.com/__community__/tco21/interviews?tracks[tco21-algorithm]=2&tracks[tco21-development]=4&tracks[tco21-track]=1

**Comment by SathyaJayabal** [comment]
verified on beta
![Screenshot 2021-11-16 at 09-33-10 TCO21 Finalist Interviews](https://user-images.githubusercontent.com/58783823/141901557-6138a6c8-64e6-4b61-856f-9290d500f3d6.png)
[1881F451-8D3C-4C81-9EAD-22573E842C8A.pdf](https://github.com/topcoder-platform/community-app/files/7543286/1881F451-8D3C-4C81-9EAD-22573E842C8A.pdf)

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="501" alt="Screenshot 2021-11-18 at 3 32 31 PM" src="https://user-images.githubusercontent.com/58783823/142394151-b02ce5e1-c907-4085-98fd-721ab1df80fb.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="501" alt="Screenshot 2021-11-18 at 4 21 07 PM" src="https://user-images.githubusercontent.com/58783823/142401902-6cf0be5f-fcee-4470-849d-dc6a216a3559.png">
