### ISSUE TITLE
Gigs apply integration API Update

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5766]
Update the get RCRM profile API `/profile` to return salaryExpectation and skill if they are presented on rcrm

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-11-04 at 1 33 00 PM" src="https://user-images.githubusercontent.com/58783823/140278220-80223941-e402-447e-ae7b-4cf3e53f8cbb.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-11-04 at 2 53 19 PM" src="https://user-images.githubusercontent.com/58783823/140289306-13da60f7-57f3-4831-9806-79a2e0347a1b.png">
