### ISSUE TITLE
RCRM API Update in Community App

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#5774]
1. Make the Apply For Job endpoint to be able to serve the MFE while maintain all the features.
2. Make sure all the other endpoints are not getting affected related to the RCRM Endpoint

https://docs.google.com/document/d/1wjvWoOyJoEvXtB9cWmGBdYjrjj_9Zh1S5VXd-XUfsr0/edit?usp=sharing

**Comment by SathyaJayabal** [comment]
@kkartunov @LieutenantRoger , the referral field is not getting updated in rcrm, when user applies using the referral link.

**Comment by SathyaJayabal** [comment]
This is verified on staging with RCRM prod.
Working as expected
![Screenshot from 2021-11-11 10-24-25](https://user-images.githubusercontent.com/58783823/141265429-f5b7a325-3f5e-4e2d-98a0-d4deab9ff819.png)
![Screenshot from 2021-11-11 10-23-30](https://user-images.githubusercontent.com/58783823/141265440-7ca59d78-3e97-482c-ad8a-136f680214a8.png)

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/micro-frontends-gigs-app/issues/64
