### ISSUE TITLE
[$100] - Add groups filter to challenge listing page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#58]
On the challenges page, add a filter to allow the user to switch between the challenges that are in the current community (based on the group) or All challenges.  All challenges would be everything that is open (public) plus any challenges the user has access to via their groups.

We have some designs for this from challenges that chekspir ran.  We should use those designs.

**Comment by birdofpreyru** [comment]
@ajefts In the design this filter is drawn as a dropdown list, which shows all communities, counts challenges for them, shows tooltips, etc.:
![screenshot](https://user-images.githubusercontent.com/20144632/26885776-dd72e150-4ba3-11e7-9f52-3b18039f08ae.png)
Implementing all this right now is doable, I guess, but will demands some efforts.

Do you want this, or just a simple switch for now, similar to track switches?

**Comment by ajefts** [comment]
Let's do a simpler version to start with.  Can we just do the current community you're in plus an option for All?  If possible, I think we should still keep it a dropdown so we can enhance it per the design later.  Don't worry about the different stats and states for registered, # chllenges, etc.

**Comment by birdofpreyru** [comment]
UPDATE: The groups filter is added, allowing to switch between all challenges / selected group the vistior has access to. Though, it is still not that beatifull, functional, as on the screenshot above (no registered/not registered status on communities, no tooltips, no challenge counts). Thus, we still keep this ticket open.

**Comment by birdofpreyru** [comment]
### Expected Fix:
To fininalize this ticket we need the following:
- Add registration info, as in the screenshot above. Underlying logic to determine whether the user is a member of community, or not, can be copied from https://github.com/topcoder-platform/community-app/blob/develop/src/shared/containers/tc-communities/Loader.jsx#L77
- Add the tooltip. For that we have a tooltip component being used around the challenge listing;
- For challenge counts let's show how much challenges belong to each community, after all other filtering filters already applied (all necessary data and logic should be already present in the Redux state and in the challenge listing code).

**Comment by arun1595** [comment]
@birdofpreyru Submitted a [PR](https://github.com/topcoder-platform/community-app/pull/721). Please take a look when you get a chance and let me know how I can improve my solution.
