### ISSUE TITLE
Thrive - spooky1 - 3

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5808]
In scope:
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/323
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/77
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/378

**Comment by kkartunov** [comment]
@SathyaJayabal this is deploying on beta.

**Comment by sandhiyakavi** [comment]
Verified on Beta Env.

1. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/323
![image_72192707](https://user-images.githubusercontent.com/55895538/142353223-66d62260-ed24-42a9-a6de-7b435086f32f.JPG)

2. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/77  (verified with Windows Firefox browser)

https://user-images.githubusercontent.com/55895538/142353276-aa7f2b85-ca63-4754-98a3-e2dcc9f5e355.mp4


3. https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/378

<img width="960" alt="screen_3" src="https://user-images.githubusercontent.com/55895538/142352898-02170408-7b51-4acb-ab08-bc92028d801f.png">

**Comment by SathyaJayabal** [comment]
verified on staging
1. 
![thrive1](https://user-images.githubusercontent.com/58783823/142393506-1283ab18-27e4-4c8d-ab20-6312b4278445.jpeg)
2. verified
3. 
<img width="1440" alt="Screenshot 2021-11-18 at 3 30 47 PM" src="https://user-images.githubusercontent.com/58783823/142393860-da62f5b8-eb41-4d82-aba0-1cb74d0c287d.png">

**Comment by SathyaJayabal** [comment]
verified on prod
1. 
![thrive1_prod](https://user-images.githubusercontent.com/58783823/142402380-99b4c82f-ad98-4267-8494-eea50db4bc3a.jpeg)
2. verified
3. 
<img width="1425" alt="Screenshot 2021-11-18 at 4 25 29 PM" src="https://user-images.githubusercontent.com/58783823/142402536-12ca2b82-daed-4972-a8a1-6c4bf479bad4.png">
