### ISSUE TITLE
Gig details - can't send email referral more than once

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5825]
Steps to reproduce:
1. go to https://www.topcoder.com/gigs/16341500556800013350dQL or any other gig
2. Use the form to send relerral by email
![image](https://user-images.githubusercontent.com/5585002/142649240-0cebf089-a0c4-4020-817e-ddce2d2d9870.png)
3. Go to another gig and try send to same email used in step 2 -> Error triggers.
![Screenshot from 2021-11-19 17-33-58](https://user-images.githubusercontent.com/5585002/142649386-2873d04d-79d9-4431-9aed-0c102f6ade3c.png)

Expected: No error modal. Referral email sent. No count for the $10 award as the recipient was already referred.

**Comment by kkartunov** [comment]
@SathyaJayabal this is deploying on beta env. Please check...

**Comment by SathyaJayabal** [comment]
verified on beta:
1. referred email form gig detail page
<img width="1440" alt="Screenshot 2021-11-23 at 3 39 40 PM" src="https://user-images.githubusercontent.com/58783823/143006070-cff0a6c1-e064-406d-bf7f-47289384dd5a.png">

2. referral reflected on growsurf
![Screenshot from 2021-11-23 12-10-57](https://user-images.githubusercontent.com/58783823/143006132-a1469770-f73a-4686-ab1b-d59c700d4a44.png)

3. referred email from another gig detail page
<img width="1440" alt="Screenshot 2021-11-23 at 3 42 04 PM" src="https://user-images.githubusercontent.com/58783823/143006515-e66fd664-2f51-4d05-8202-1c8a2d572382.png">
4. Email received for both the gig referrals
<img width="1440" alt="Screenshot 2021-11-23 at 3 45 29 PM" src="https://user-images.githubusercontent.com/58783823/143006490-5c670f4b-c766-4e22-9b0a-15f89c861a3a.png">

**Comment by codejamtc** [comment]
**Staging Environment:**

https://staging-community-app.topcoder.com/gigs

Email used `codejamgigstaging@mailinator.com`

- https://staging-community-app.topcoder.com/gigs/16379472242210013350rlg
- https://staging-community-app.topcoder.com/gigs/16305973203140013350VLM

![bandicam 2021-11-30 17-35-38-870](https://user-images.githubusercontent.com/42398485/144044426-5df31634-d0d2-4f05-aad8-dd70d5c1dd2d.jpg)

https://user-images.githubusercontent.com/42398485/144042949-c206f437-8ec8-4b12-9bed-b289b1519a5d.mp4

**Development Environment:**

https://community-app.topcoder-dev.com/gigs

Email used `codejamgigdev@mailinator.com`

- https://community-app.topcoder-dev.com/gigs/16364343558620010128EOf
- https://community-app.topcoder-dev.com/gigs/16333316170950010128cHl

![bandicam 2021-11-30 17-35-55-593](https://user-images.githubusercontent.com/42398485/144044404-2cb3c97f-745a-4d87-875a-b66b7e4027ae.jpg)


https://user-images.githubusercontent.com/42398485/144043090-33cd2f8a-0448-4856-aeec-55fa03aa478f.mp4

**Comment by codejamtc** [comment]
@kkartunov Possible to get the `growsurf` records for above items

**Comment by kkartunov** [comment]
@codejamtc attached. Looks correct, only one entry is saved for `codejamgigstaging@mailinator.com`


![Screenshot from 2021-11-30 17-42-40](https://user-images.githubusercontent.com/5585002/144079221-449d1674-3b5c-432e-a393-05c3c67b16e0.png)

**Comment by codejamtc** [comment]
Prod Environment:

https://www.topcoder.com/gigs

Email used codejamgigprod@mailinator.com

https://www.topcoder.com/gigs/16379472242210013350rlg
https://www.topcoder.com/gigs/16305973203140013350VLM


https://user-images.githubusercontent.com/42398485/144088105-aaa0e0c0-cf91-48d9-9dd4-4aaf5462bd40.mp4


@kkartunov Possible to get the growsurf records for above items

**Comment by kkartunov** [comment]
@codejamtc attached
![Screenshot from 2021-11-30 18-35-19](https://user-images.githubusercontent.com/5585002/144088621-b4907546-e053-48f1-bc68-fe03f36f84f3.png)
