### ISSUE TITLE
Add Loading Indicator when the challenge API is searching

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#5828]
Current:

Currently, when we changed any filter, we will call the API to get the challenge data with latest updated Query

Expected:

When the API is trying to get the data from backend, we should display a loading indicator to let user is aware of that the API is loading data.   This can happen when a user visits challenge page initially, or the user changed any filter that causing the reloading of the challenges data.

https://monosnap.com/file/9QoY7B7dgMhz1uNS2NiTcYPwmysEan
Please reuse the loading indicator we have implemented when loading a challenge detail page.

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/micro-frontends-challenges-app/issues/182
transferred here.
