### ISSUE TITLE
[$50] - Challenge listing (at least in blockchain community) redirects to challenge details pages on main www.topcoder.com domain

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#583]
### Expected Fix:
We should ensure that in all sub-communities accessing challenge details pages keeps us inside that sub-community. The correct way to do it, I believe, is implemented inside the Wipro community; so it just should be carefully copied everywhere where it is missing.

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/619
hash:  1d17846
