### ISSUE TITLE
Thrive - spooky bugs - 4

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5833]
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/304
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/342
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/3
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/10
https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/270

**Comment by kkartunov** [comment]
@SathyaJayabal this is ready for QA and deploying on beta, please check...

**Comment by codejamtc** [comment]
All fixed :ok:

- https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/304#note_746951508
- https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/342#note_746952203
- https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/3#note_746952618
- https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/10#note_746952896
- https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/270#note_746953736
- https://gitlab.com/topcoder-thrive/spooky-bugs/-/issues/270#note_746953736
