### ISSUE TITLE
[$100] - We should protected auxiliary endpoints in Community App's server by API key

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#586]
Look through the server code module: https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js
There is a bunch of auxiliary endpoint, we should protect them by an API key.

For remote deployment the key should come from CircleCI environment variables. To track everything you need in code to make it happen, please search for all places where `FILESTACK_API_KEY` string is present (it is an unrelated api key, but it also comes from CircleCI for remote deployment).

**Comment by ekundayo-ab** [comment]
Hi @birdofpreyru I'm trying to understand what needs to be done here. Does it mean like, any calls to the auxiliary endpoints should pass through an authentication middleware which checks for the `FILESTACK_API_KEY` before it can be allowed to access the intended auxiliary endpoint?

Kindly give your thoughts on this. Thanks

**Comment by birdofpreyru** [comment]
1. It should be a separate key, say `COMMUNITY_APP_API_KEY`. The `FILESTACK_API_KEY` is mentioned as a working example of how to pass a key from Circle CI env vars into the app configuration during the build time - we want the same for the new key.

2. The new key should be passed via some request header and checked by auxiliary endpoints defined in the app:
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L51
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L98
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L104
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L110
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L118
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L131
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L137
https://github.com/topcoder-platform/community-app/blob/develop/src/server/server.js#L145
