### ISSUE TITLE
[$30] - Update communities dropdown in header to be dynamic

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#587]
Use the same logic we have in the challenge filter.

**Comment by birdofpreyru** [comment]
### Expected Fix:
Just re-use the code and functionality being used by the challenge listing to load the listing of communities visible to the visitor/user, and use it to populate the selector in sub-community header.

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/615
hash:  6a82124

**Comment by birdofpreyru** [comment]
@zjuasmn Great, accepted. I'll keep the PR open for some more time, as I want to double-check some things with TC team before I can merge it; but nothing to worry about on your side.
