### ISSUE TITLE
Thrive RSS feed

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5892]
Develop web feed under /api/feeds/thrive that conforms with RSS standard.
Feed shoud show latest 20 articles from Thrive.
Sould pass W3C validation https://validator.w3.org/feed/#validate_by_uri

**Comment by kkartunov** [comment]
@SathyaJayabal deployed on staging https://staging-community-app.topcoder.com/api/feeds/thrive please check...

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Stag env have develop branch now ( to smoke testing )

Deployed `thrive-rss` to QA env.

https://qa-community-app.topcoder-dev.com/api/feeds/thrive

**Comment by sandhiyakavi** [comment]
Verified in QA Env.

![image](https://user-images.githubusercontent.com/55895538/144970830-1d92bc0f-4b43-4981-8a79-6dacc76f56c9.png)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/145018605-8732035f-b1c8-460a-8861-892e11d7dc2c.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/145160681-534a3541-9e71-402e-94d9-540e7ea5540e.png)
