### ISSUE TITLE
Show "no verified skills" message and highest paying challenge for users without skills matched challenges

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/community-app#5903]
## Context

We have a feature to show recommended challenges based on skills match https://monosnap.com/file/AdjBXbZRwUs2eqR6BzR8jR9knRvvlQ

But if user doesn't have any verified skills, or there are no challenges matching verified user skills, then user doesn't get any recommendation and see message 

![image](https://user-images.githubusercontent.com/146016/144442490-6667948d-ecc4-4130-a7cd-e021fe3dc5d8.png)

## Task

When user doesn't get any challenge recommended based on skill show a new message with the list of highest paying open challenges as per design https://www.figma.com/file/7FveQImIT3iQsw71fkCtpx/Recommended-Challenges?node-id=0%3A1

![image](https://user-images.githubusercontent.com/146016/144443011-3388f00a-9168-417b-aa09-3b37589c23f4.png)

## QA

You may use the next 2 users for testing:

- `tester1234/appirio123` (has one challenge recommended)
- `dan_developer/dantopcoder123` (doesn't have any recommended challenges)

**Comment by maxceem** [comment]
This was implemented via challenge https://www.topcoder.com/challenges/6756db6f-55c9-400d-908c-9124fc109540?tab=details and private task to fulfill updated requirements after the challenge https://www.topcoder.com/challenges/b9726a84-4ae9-4b37-9e0d-66516cade104

For DEV deployment PRs has to be merged in the next order:
- Challenge Recommender API https://github.com/topcoder-platform/challenge-recommender-api/pull/56
- Topcoder React Lib https://github.com/topcoder-platform/topcoder-react-lib/pull/318
- Community App https://github.com/topcoder-platform/community-app/pull/5900

**Comment by luizrrodrigues** [comment]
@maxceem FYI: Updated **topcoder-react-lib** PR in description (because need a branch inside repo to create a test-release)

from: https://github.com/topcoder-platform/topcoder-react-lib/pull/318
to: https://github.com/topcoder-platform/topcoder-react-lib/pull/319

**Comment by codejamtc** [comment]
@maxceem https://staging-community-app.topcoder.com/challenges?bucket=openForRegistration&tracks[DS]=true&tracks[Des]=true&tracks[Dev]=true&tracks[QA]=true&types[]=CH&types[]=F2F&types[]=TSK

customerUser/appirio123

- I am not getting any challenges when I turn ON the toggle

https://user-images.githubusercontent.com/42398485/144626310-92666671-2dc2-4707-8750-78d7e543f1f8.mp4

**Comment by maxceem** [comment]
Hey, @codejamtc somehow I cannot log in with this user https://monosnap.com/file/yPoWHMqf0h1j56lO6NESHS9cYe4j0o.

Maybe it has another password?

**Comment by maxceem** [comment]
@codejamtc I've got it.

We only deployed our API update to DEV.

So for now it only works on DEV it doesn't work on Staging.

Could you please test it on DEV only.

**Comment by codejamtc** [comment]
@maxceem `Dev` it works https://github.com/topcoder-platform/community-app/issues/5903#issuecomment-985597378

**Comment by maxceem** [comment]
Great, then everything looks good.

**Comment by codejamtc** [comment]
Verified in `Dev` (develop branch)   :ok:

tester1234/appirio123 (has one challenge recommended)

https://user-images.githubusercontent.com/42398485/144967844-101c60d9-b4b6-451d-8e13-a6ccad124d19.mp4

dan_developer/dantopcoder123 (doesn't have any recommended challenges) https://www.figma.com/file/7FveQImIT3iQsw71fkCtpx/Recommended-Challenges?node-id=0%3A1
- The challenges are listed Desc from the prize money
- 
![bandicam 2021-12-07 10-16-16-975](https://user-images.githubusercontent.com/42398485/144968028-29a6333f-f8b7-4489-956d-28f540ce5919.jpg)

https://user-images.githubusercontent.com/42398485/144968033-948559b2-3142-42db-917d-739f1df027ef.mp4

**Comment by codejamtc** [comment]
Verified in Prod  :ok:

- User with `skills` used my own account  :ok:

https://user-images.githubusercontent.com/42398485/144989602-968621b6-c0f4-4e0c-93dd-3f20e178b375.mp4

- User without skills (new prod account)  :ok:

https://user-images.githubusercontent.com/42398485/144989576-5374c00c-13b1-4794-a34e-e7ac19ea7803.mp4

![bandicam 2021-12-07 13-29-35-315](https://user-images.githubusercontent.com/42398485/144989587-182619d7-45e9-41b0-87db-764754fc0762.jpg)
