### ISSUE TITLE
MM Leaderboard

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5911]
Add new theme for Contentful MM Leaderboard based on design:
![image](https://user-images.githubusercontent.com/5585002/144827112-6ef748a2-dec4-4c67-b12d-a1a30a45dc09.png)
mobile
![image](https://user-images.githubusercontent.com/5585002/144827168-2c7113e9-8b67-46b6-8510-541cb3d30a0a.png)

**Comment by kkartunov** [comment]
QA link: https://beta-community-app.topcoder.com/examples/contentful/viewport/5B3ZQikEG0q3J4RzLuw4g1

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="453" alt="Screenshot 2021-12-09 at 9 22 08 AM" src="https://user-images.githubusercontent.com/58783823/145331588-ee650e50-15b4-4ad8-9a05-c12f9f3c7a3b.png">
<img width="580" alt="Screenshot 2021-12-09 at 9 21 31 AM" src="https://user-images.githubusercontent.com/58783823/145331603-3f318c0f-0e67-4705-946f-577df93f0f19.png">
@kkartunov where does the leaderboard go? on the tco leaderboard or the challenge details page?

**Comment by kkartunov** [comment]
@SathyaJayabal challenge details page, it is live MM data. Thanks!

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-12-13 at 4 35 38 PM" src="https://user-images.githubusercontent.com/58783823/145801518-73951c73-fe00-41a7-ba35-2573146bb524.png">

<img width="633" alt="Screenshot 2021-12-13 at 4 36 16 PM" src="https://user-images.githubusercontent.com/58783823/145801616-015b202f-3235-4534-8639-87c513f0395f.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-12-13 at 6 27 00 PM" src="https://user-images.githubusercontent.com/58783823/145816510-13d1439c-5d95-46b2-815a-be2fe14ce702.png">
