### ISSUE TITLE
Automated Smoke Testing - Fix timeline test form challenge sample

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#5915]

**Comment by luizrrodrigues** [comment]
https://13987-84477388-gh.circle-artifacts.com/0/automated-smoke-test/test-results/TestResult.html

**Comment by SathyaJayabal** [comment]
verified
<img width="1431" alt="Screenshot 2021-12-08 at 1 35 27 PM" src="https://user-images.githubusercontent.com/58783823/145171476-a061546e-3b07-4969-ad48-33a3871bc574.png">
