### ISSUE TITLE
Settings page update to use v5 member api

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/community-app#5918]
The onboarding app uses v5 member Api to save member traits. These traits should appear exactly as they were saved in the onboarding app in Community App. Similarly for existing users the traits visible in settings page of the community app should be available in the onboarding app. There were some inconsistencies due to use of v3 and v5.

This is now fixed in https://github.com/topcoder-platform/community-app/pull/5917. Relevant issue in onboarding app: https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/147

**Comment by sandhiyakavi** [comment]
Verified in Dev Env and following issues are logged.

https://github.com/topcoder-platform/community-app/issues/5934
https://github.com/topcoder-platform/community-app/issues/5933
https://github.com/topcoder-platform/community-app/issues/5931
https://github.com/topcoder-platform/community-app/issues/5919

**Comment by SathyaJayabal** [comment]
qa pass on dev

**Comment by SathyaJayabal** [comment]
qa pass on staging

**Comment by SathyaJayabal** [comment]
verified on prod
