### ISSUE TITLE
The DASHBOARD tab should be visible only for MM

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5921]
The DASHBOARD tab should be visible only for MMs. At present it is displayed for all data science challenges.

example:
https://staging-community-app.topcoder.com/challenges/46fc6a80-57ee-4581-ac57-8e520152bf45?tab=mm_dashboard
<img width="1440" alt="Screenshot 2021-12-11 at 8 17 59 AM" src="https://user-images.githubusercontent.com/58783823/145661256-34c10348-2566-4380-93dd-db326ac569fd.png">

**Comment by rmitchell-iii** [comment]
Agreed.

**Comment by ThomasKranitsas** [comment]
@rmitchell-iii  @SathyaJayabal  How do we differentiate marathon matches from regular data science challenges? Is there a specific tag or something? I followed the instructions from the original challenge that were `challenge.track === 'Data Science' && challenge.type === 'Challenge'`

**Comment by rmitchell-iii** [comment]
I'm not sure. If there is not another tag that is specific to MM then we may have to live with this tab showing up for non-MM data science challenges.

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas @rmitchell-iii , the Marathon matches have the tag Marathon match
<img width="977" alt="Screenshot 2021-12-13 at 1 01 55 PM" src="https://user-images.githubusercontent.com/58783823/145770436-4022ddfe-0d08-49ff-8e7e-351e92c9f50f.png">

**Comment by ThomasKranitsas** [comment]
Thanks @SathyaJayabal

**Comment by SathyaJayabal** [comment]
https://github.com/topcoder-platform/community-app/blob/61a254c46f0952b5266664ab4860035c99ca2489/src/shared/utils/challenge.js#L10
I think this helper is used to identify a marathon match

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-12-13 at 1 58 35 PM" src="https://user-images.githubusercontent.com/58783823/145777694-b134c2bb-fa3f-49bc-b554-6492466e227c.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-12-13 at 1 58 35 PM" src="https://user-images.githubusercontent.com/58783823/145777694-b134c2bb-fa3f-49bc-b554-6492466e227c.png">

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-12-13 at 1 58 35 PM" src="https://user-images.githubusercontent.com/58783823/145777694-b134c2bb-fa3f-49bc-b554-6492466e227c.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-12-13 at 4 03 41 PM" src="https://user-images.githubusercontent.com/58783823/145796758-b5783269-ec24-4a99-ac6b-2f79570cb02b.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-12-13 at 6 18 13 PM" src="https://user-images.githubusercontent.com/58783823/145815324-de3f9834-5a3b-476b-a8e3-d06320eeb709.png">
