### ISSUE TITLE
Show a loading indicator before the  dashboard loads

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5922]
Show a loading indicator before the  dashboard loads. At present a message "Dashboard Data is not available" is displyed before the chart loads.

https://user-images.githubusercontent.com/58783823/145661379-9e17c6da-4e1f-43de-a644-0dde86ace4b7.mov

**Comment by rmitchell-iii** [comment]
Agreed. Let's make two changes here:
* Change the text to say "Dashboard data loading"
* Show a spinner beneath the text

**Comment by ThomasKranitsas** [comment]
We usually just show the spinner. Should we also include the text?

**Comment by rmitchell-iii** [comment]
Just the spinner is good.

**Comment by SathyaJayabal** [comment]
verified

https://user-images.githubusercontent.com/58783823/145788645-3db157df-c917-46a6-839c-52cc738bddc9.mov

**Comment by SathyaJayabal** [comment]
verified on staging

https://user-images.githubusercontent.com/58783823/145797118-8295f49c-8dc0-4f25-b18d-c4978995ff82.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/145815559-3b5013bd-81c9-4675-a104-630bc492a140.mov
