### ISSUE TITLE
Dashboard displaying a blank page for some Marathon Matches

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5923]
https://staging-community-app.topcoder.com/challenges/116fc3d9-a4e0-4a93-8ef1-a075ae16ee88
<img width="1440" alt="Screenshot 2021-12-11 at 8 33 13 AM" src="https://user-images.githubusercontent.com/58783823/145661654-c67bc4ae-0298-45ad-a1a8-55ebccbe59b2.png">

**Comment by SathyaJayabal** [comment]
another example:
https://staging-community-app.topcoder.com/challenges/c522c9e3-29d3-4788-98db-05748f0842dc?tab=mm_dashboard

**Comment by rmitchell-iii** [comment]
@ThomasKranitsas is this a bug or do these marathon matches not have data available? If they don't have data available I suggest we detect this situation and show a message "Data not available".

**Comment by SathyaJayabal** [comment]
@rmitchell-iii , I think there is something wrong with the data for this specific challenge. The error seems to be  "String value sent to series.data, expected Number"

**Comment by rmitchell-iii** [comment]
@SathyaJayabal is this unique to this challenge or do other MM challenges have this same issue? i.e. are there multiple formats for the data that need to be supported or can this issue be ignored since this is malformed MM data?

**Comment by SathyaJayabal** [comment]
@rmitchell-iii , I saw the issue just for this challenge. We will need to investigate the cause of the bad data in this challenge, so we know if there is a chance for this happening  again, or if its just a one off scenario.

**Comment by ThomasKranitsas** [comment]
That specific challenge has some data with `null` scores or `-1`. I'll default those to `0` to avoid issues while displaying the chart

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-12-13 at 1 57 31 PM" src="https://user-images.githubusercontent.com/58783823/145777543-89b35819-7525-46f2-93c9-fce94aca167c.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-12-13 at 4 02 31 PM" src="https://user-images.githubusercontent.com/58783823/145796556-41666e49-72c1-4b69-b65e-9bea29056466.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-12-13 at 6 21 12 PM" src="https://user-images.githubusercontent.com/58783823/145815729-b80f042f-16cf-4806-8011-b911b3185413.png">
