### ISSUE TITLE
Final Scores : Feature request

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5924]
The Dashboard displays the chart of the user's provisional scores. This is fine when the challenge is running. But once the challenge is completed, it will be good to have a chart with the final scores of the submitters.

**Comment by ThomasKranitsas** [comment]
I agree, though, based on the requirements, I was expected to show the score from the review object that has metadata regardless of the review type ID

**Comment by rmitchell-iii** [comment]
@SathyaJayabal , good suggestion. I've captured in our internal Jira https://topcoder.atlassian.net/browse/PLAT-223 for prioritization. We will implement when it rises in priority.
