### ISSUE TITLE
When accessing the MM dashboard directly through the URL for other challenge types, user must be redirected to the details tab

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5927]
When accessing the MM dashboard directly through the URL for other challenge types, user must be redirected to the details tab
example:
https://staging-community-app.topcoder.com/challenges/981cacac-d437-46b0-8adc-813dd158eb84?tab=mm_dashboard
https://staging-community-app.topcoder.com/challenges/c51f7063-40bd-4e68-ace1-8b5fcb93452d?tab=mm_dashboard
At present we display the dashboard 
<img width="1440" alt="Screenshot 2021-12-11 at 9 04 08 AM" src="https://user-images.githubusercontent.com/58783823/145662370-daf39621-7b00-4ff0-bdf9-c259bf302d7b.png">

**Comment by rmitchell-iii** [comment]
Agreed. If there is an attempt to access the dashboard for a non-MM challenge we should redirect to that challenge's details tab.

**Comment by SathyaJayabal** [comment]
verified 

https://user-images.githubusercontent.com/58783823/145777395-f325538a-2128-47ec-8731-35dfa05e28f9.mov

**Comment by SathyaJayabal** [comment]
verified on staging

https://user-images.githubusercontent.com/58783823/145796377-b62d6b77-4ce6-450f-bbb2-ba3cda7c1d1c.mov

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/145815939-5474c872-434c-47bf-b0db-5655b9ce7b41.mov
