### ISSUE TITLE
Baseline and Award Metrics

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5928]
Do we need to display the base line and award metrics at  50 and 70 respectively ?
<img width="1436" alt="Screenshot 2021-12-11 at 9 19 17 AM" src="https://user-images.githubusercontent.com/58783823/145662730-9cafc9ed-908b-4122-ab89-4a07ae9a76ac.png">

**Comment by ThomasKranitsas** [comment]
This is supported. If the challenge object contains a baseline/awardLine metadata value, it’ll be displayed.

**Comment by rmitchell-iii** [comment]
@SathyaJayabal , the metadata value that causes the Award line to show is not present in the underlying data by default. It must be added manually. In the future we may add a feature to enable it to be added through the user interface.

@ThomasKranitsas can you provide a postman demonstrating how to set the awardLine value in the metadata so @SathyaJayabal can verify it appears?

@SathyaJayabal after testing and verifying you can close this ticket.

Thanks!

**Comment by ThomasKranitsas** [comment]
[MM Dashboard.postman_collection.json.zip](https://github.com/topcoder-platform/community-app/files/7701997/MM.Dashboard.postman_collection.json.zip)

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-12-13 at 2 04 42 PM" src="https://user-images.githubusercontent.com/58783823/145778701-32a82c4f-0ec0-45c3-bfdf-2c2a46c479d4.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-12-13 at 3 59 59 PM" src="https://user-images.githubusercontent.com/58783823/145796172-946859c2-4053-407e-a366-e6f7c408f51c.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1436" alt="Screenshot 2021-12-13 at 6 24 34 PM" src="https://user-images.githubusercontent.com/58783823/145816230-9191940c-1197-4af6-bbda-d56995da3b29.png">
