### ISSUE TITLE
Default profile pic is not rendered properly

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5929]
When the member has not added their profile picture, the default image is not rendered properly

<img width="291" alt="Screenshot 2021-12-11 at 9 25 36 AM" src="https://user-images.githubusercontent.com/58783823/145662936-8c06e459-f6d0-412c-8a20-52141768c0e0.png">
example of the default image
<img width="419" alt="Screenshot 2021-12-11 at 9 25 43 AM" src="https://user-images.githubusercontent.com/58783823/145662939-470934ae-fdf7-4cf0-b458-7bea8a264e53.png">

**Comment by rmitchell-iii** [comment]
@ThomasKranitsas if this is trivial to fix would you please fix this? If non-trivial we can leave as-is.

**Comment by SathyaJayabal** [comment]
verified
<img width="1440" alt="Screenshot 2021-12-13 at 2 07 59 PM" src="https://user-images.githubusercontent.com/58783823/145778984-a5622417-5541-4085-9bb2-071b2b488360.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="297" alt="Screenshot 2021-12-13 at 3 58 01 PM" src="https://user-images.githubusercontent.com/58783823/145795882-59928e39-8704-4d59-afc5-d8cefcf01c61.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="342" alt="Screenshot 2021-12-13 at 6 25 53 PM" src="https://user-images.githubusercontent.com/58783823/145816362-012ca74f-6200-4a7d-8f43-db248e697e4f.png">
