### ISSUE TITLE
Settings page: User name and country are not saved for first time Signup

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5933]
Description:

As per https://github.com/topcoder-platform/micro-frontends-onboarding-app/issues/147#issuecomment-990823941

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. It is getting displayed now.

![image](https://user-images.githubusercontent.com/55895538/148019362-8c282cc6-c8ce-47e8-b015-f8c2d6726fdf.png)
![image](https://user-images.githubusercontent.com/55895538/148019393-3ba355c0-7b6f-474c-bbce-c5dd763a1daf.png)

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2022-01-10 at 3 43 24 PM" src="https://user-images.githubusercontent.com/58783823/148749326-6c309c74-e429-4d24-971b-ce3dce4ce296.png">
