### ISSUE TITLE
Settings Page: Skills settings uses v3 member api.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5934]
Description:

All other settings apart from Skills settings are moved to v5 member api.

<img width="959" alt="skills_v3" src="https://user-images.githubusercontent.com/55895538/145769870-e328eba3-4332-4b3a-85a6-08ad01125b90.png">

**Comment by sandhiyakavi** [comment]
The skills are now using the v5 api in Dev Env.

<img width="960" alt="skills_1" src="https://user-images.githubusercontent.com/55895538/148019146-b78a46e7-ed65-4671-ad79-cb01c314f198.png">
<img width="957" alt="skills_2" src="https://user-images.githubusercontent.com/55895538/148019153-e6048f2c-37ca-4cf1-8818-8b6a40797d03.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2022-01-10 at 2 10 41 PM" src="https://user-images.githubusercontent.com/58783823/148738841-d5257c74-6e5f-48c4-a5fd-e4b81aa88974.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2022-01-10 at 3 40 59 PM" src="https://user-images.githubusercontent.com/58783823/148748993-2764d439-3d0e-42cc-b385-6ff584dee549.png">
