### ISSUE TITLE
Build MM Dashboard

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#5935]
- Build an MVP version of the dashboard that is currently setup manually. This MVP version would:
  - Provide a link labeled “Dashboard” shown on the challenge page for all MM challenges.
  - Clicking the “Dashboard” link will open the dashboard in a new tab.
- The dashboard will show:
  -Title
  - The graph (see Data Science Dashboard )
  - The data points for submissions color coded by member rank
- Hovering the data point shows the following info:
  - Submitter handle
  - Total # submissions
  - Submission score
  - Submission date
- Baseline bar (pulled from challenge data - no way to set this when creating the challenge, must be set manually in the data).
- Please document via postman example how to set this value.
- The dashboard will not show anything else (don’t show the filters, data below the graph, etc.)
- Permissions to view the dashboard should be the same as the challenge if easy to implement. If not easy then make the dashboard public (as it is with the current manually created dashboard).
- The data shown in the graph should be pulled from V5 APIs (not from Informix as is currently done).
- The dashboard should not be hosted in Heroku - instead just host it like other parts of the platform (i.e. like any other page in the platform).

Note: This dashboard feature should only be available for Marathon Matches

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2021-12-13 at 3 56 11 PM" src="https://user-images.githubusercontent.com/58783823/145795521-4eeb007d-d144-4c66-a28a-da9ef41e00cd.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2021-12-13 at 6 17 14 PM" src="https://user-images.githubusercontent.com/58783823/145815213-0d966849-f4ac-4f43-b91d-f62c0da94bf6.png">
