### ISSUE TITLE
Topgear intermittently inaccessible 

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/community-app#5940]
Reported by @RiteshTC, Reproducible in QA: Topgear doesn’t seem accessible. Rebooted Groups api. It works for a few minutes before throwing the back stage error.

<img width="1680" alt="Screenshot 2021-12-15 at 4 49 09 PM" src="https://user-images.githubusercontent.com/51733042/146180830-306516b2-84e1-4a6b-9c11-7f041cf588e4.png">

**Comment by lakshmiathreya** [comment]
<img width="1190" alt="Screenshot 2021-12-15 at 4 19 14 PM" src="https://user-images.githubusercontent.com/51733042/146180987-0ef6eccf-57b6-4a73-bd48-b43a6c3966ab.png">

**Comment by lakshmiathreya** [comment]
Closing based on update from @rmitchell-iii "Based on a meeting I had with TopGear earlier today I believe this is resolved from their end." https://topcoder.slack.com/archives/G1W6YEFRQ/p1639599452150100

**Comment by lakshmiathreya** [comment]
Issue is reappearing ...

**Comment by lakshmiathreya** [comment]
cc @ThomasKranitsas - current Level III support Rep ...

**Comment by ThomasKranitsas** [comment]
This is a result of the performance issue of the Groups API. I have created this https://github.com/topcoder-platform/groups-api/issues/97 for tracking so I'm closing this one
