### ISSUE TITLE
Settings page must not require user to enter short bio

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5947]
Settings page must not require user to enter short bio
<img width="1440" alt="Screenshot 2022-01-04 at 12 54 21 PM" src="https://user-images.githubusercontent.com/58783823/148023620-a7b212ac-4b2e-402a-adf2-eb11a1d3108c.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev env. Short bio is not a mandatory field now

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2022-01-10 at 2 11 47 PM" src="https://user-images.githubusercontent.com/58783823/148738749-6de4a8a5-7e19-4d3b-89b8-3ce32aab7e5b.png">

**Comment by SathyaJayabal** [comment]
verified on prod


https://user-images.githubusercontent.com/58783823/148748861-a7aa164d-6787-4ed3-85b4-43ece1e51c8f.mov
