### ISSUE TITLE
Settings page gives an error while saving without adding a profile photo 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5948]
Settings page gives an error while saving without adding a profile photo 
<img width="1440" alt="Screenshot 2022-01-04 at 12 55 42 PM" src="https://user-images.githubusercontent.com/58783823/148023918-09a6dc65-ba25-4a17-88e1-3db8e68d2382.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. Able to save without adding profile photo

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2022-01-10 at 2 11 47 PM" src="https://user-images.githubusercontent.com/58783823/148738643-a605cbbf-e57f-418b-af40-fdc5fafaa258.png">

**Comment by SathyaJayabal** [comment]
verified on  prod
<img width="1440" alt="Screenshot 2022-01-10 at 3 36 00 PM" src="https://user-images.githubusercontent.com/58783823/148748447-ea0e00cf-6e61-434b-a2ec-81dc4f606b64.png">
