### ISSUE TITLE
Not able to remove the entered address related fields.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5949]
Description:

User is not able to remove the already entered address related fields Address, Address2, City, state and zip. If removed and tried to save . It is showing error.

![image](https://user-images.githubusercontent.com/55895538/148031179-2ff0d866-cbbf-4531-8df8-5c443fe73218.png)

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/148225611-1ea6b4b0-d2d1-4fe0-951b-5f5803ef2e36.mov

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2022-01-10 at 2 14 19 PM" src="https://user-images.githubusercontent.com/58783823/148738470-be7cdbad-85c4-4891-a5bf-a35965c33fee.png">
<img width="1440" alt="Screenshot 2022-01-10 at 2 14 37 PM" src="https://user-images.githubusercontent.com/58783823/148738498-0b41924c-c8f6-4bc0-8107-f889081c53a7.png">

**Comment by SathyaJayabal** [comment]
verified on prod

https://user-images.githubusercontent.com/58783823/148748689-f1143882-eb4e-463d-a99b-22f987025bba.mov
