### ISSUE TITLE
Two success messages are displayed in the Basic info settings page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#5950]
Description:
Two success messages are displayed in the Basic info settings page.

<img width="960" alt="2successmsg" src="https://user-images.githubusercontent.com/55895538/148032394-0c9998e0-1323-479f-bb9d-54ddb8111c1f.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/148326166-cc7274a5-bf18-4907-a0d0-b1bf86a2708f.png)

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2022-01-10 at 2 11 47 PM" src="https://user-images.githubusercontent.com/58783823/148738157-510976a7-bf29-4762-b2ce-0d607e36cef1.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1440" alt="Screenshot 2022-01-10 at 3 36 00 PM" src="https://user-images.githubusercontent.com/58783823/148748380-b3a0f861-e941-4e44-a9cf-d384fced5873.png">
