### ISSUE TITLE
Unable to add skills for thee first time from settings page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5953]
Unable to add skills for thee first time from settings page. The PATCH  call is made, but a POST call must be made as there are no skills yet for the user
<img width="1440" alt="Screenshot 2022-01-07 at 11 19 33 AM" src="https://user-images.githubusercontent.com/58783823/148498367-c4af4d2f-9fdb-429e-b6d4-7965e12ca103.png">

**Comment by nursoltan-s** [comment]
PR: https://github.com/topcoder-platform/topcoder-react-lib/pull/330

**Comment by SathyaJayabal** [comment]
verified on dev, user is able to add skills for the first time on settings page
<img width="1440" alt="Screenshot 2022-01-10 at 11 00 45 AM" src="https://user-images.githubusercontent.com/58783823/148722034-d48ee51a-b1a3-47a2-819f-48d9a52395db.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1440" alt="Screenshot 2022-01-10 at 2 10 44 PM" src="https://user-images.githubusercontent.com/58783823/148738052-7e73c89d-76fc-4d49-bc15-e30b7ab9edc0.png">

**Comment by sandhiyakavi** [comment]
Verified on Prod Env. Able to add skills first time.

![image](https://user-images.githubusercontent.com/55895538/148748555-f4f38559-ae31-45d7-bde2-6673f6e54832.png)
