### ISSUE TITLE
Remove Challenge Pipeline link from footer

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5965]
As per title. Pgane was deprecated.

**Comment by kkartunov** [comment]
@SathyaJayabal deployed on beta.

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1440" alt="Screenshot 2022-01-11 at 3 15 57 PM" src="https://user-images.githubusercontent.com/58783823/148919452-a5ae2835-09c0-4943-8b22-785b129c607b.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env.

![image](https://user-images.githubusercontent.com/55895538/149279331-4efac474-472f-4e48-92f2-db6b0d74ac0e.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/149286977-2dad3bd7-b453-43f6-bce6-eba0ab9b8724.png)
