### ISSUE TITLE
Allow rating colors in Lookers

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5966]
Add support for colors If rating is provided by API response.
https://www.topcoder.com/community/statistics

**Comment by kkartunov** [comment]
@SathyaJayabal deployed on bete: https://beta-community-app.topcoder.com/examples/contentful/contentblock/2HDwAYdizt2VDmZeQWIRwv

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="1434" alt="Screenshot 2022-01-11 at 3 19 28 PM" src="https://user-images.githubusercontent.com/58783823/148919938-65de5682-9068-48b5-a8e4-5483990d2e44.png">

**Comment by sandhiyakavi** [comment]
Verified on Staging Env.

![image](https://user-images.githubusercontent.com/55895538/149280884-2492d6f9-6cf9-47bc-b304-1af8f467ad35.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env.

![image](https://user-images.githubusercontent.com/55895538/149286683-f19448b4-9d51-4305-bcdb-5afa4d0e9249.png)
