### ISSUE TITLE
New email preference - NASA Community

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5967]
Organize and add new email preference - NASA Community to https://www.topcoder.com/settings/preferences

**Comment by kkartunov** [comment]
@SathyaJayabal deployed on beta for QA...

**Comment by SathyaJayabal** [comment]
verified on  beta
<img width="1439" alt="Screenshot 2022-01-12 at 5 13 44 PM" src="https://user-images.githubusercontent.com/58783823/149134329-6da03191-4f70-4c2e-aadd-097d98533ecd.png">
![image (39)](https://user-images.githubusercontent.com/58783823/149134465-514ecc24-8c84-4f39-aae3-0e0df1199921.png)

**Comment by SathyaJayabal** [comment]
verified on staging (develop branch)
<img width="1435" alt="Screenshot 2022-01-13 at 12 14 18 PM" src="https://user-images.githubusercontent.com/58783823/149279601-9bfa601a-e77d-438e-b024-48c988c74e26.png">
![image (40)](https://user-images.githubusercontent.com/58783823/149279618-a95c5647-b2df-43bc-ac9f-ca17bbd67e5a.png)

**Comment by SathyaJayabal** [comment]
verified on prod

<img width="1440" alt="Screenshot 2022-01-13 at 1 10 11 PM" src="https://user-images.githubusercontent.com/58783823/149286691-8cb9ecf4-e16b-443b-a414-0f629b5fb22b.png">
