### ISSUE TITLE
[$50] - F2F Challenge closing not handled properly

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/community-app#597]
In F2F challenges, I am able to register even after challenge is completed.

https://www.topcoder.com/challenges/30060460/?type=develop&tab=details
topcoder.com
 
This challenge though it got completed, Register button is still visible. If I click on register, it's actually registering and submit is also enabled.

Hence I raised an issue earlier, stating that once a solution is accepted, Registration / Submission should be closed but it's not being done now. I have raised even a ticket regarding this two months back https://help.topcoder.com/hc/en-us/requests/12729

Now only it's been assigned to someone

**Comment by birdofpreyru** [comment]
### Expected Fix:
The logic for enabling/disabling of Register / Submit buttons on challenge details page should be updated accordingly to disallow such actions on completed F2Fs.

**Comment by sharathkumaranbu** [comment]
Please note it's not only about handling in Community App, it should be handled in OR as well. So API fix would be better.

**Comment by birdofpreyru** [comment]
Yeah, though I believe, if we just leverage it in the frontend, nobody will note this anymore. For fixing it in API we should ask @skyhit and @ajefts to note it on their todo list.

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/618
hash: 9e8c6a0
