### ISSUE TITLE
Unable to edit basic info from profile settings page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5976]
Unable to edit basic info from profile settings page.
Go to https://www.topcoder.com/settings/profile
Edit short Bio and save, an error is displayed for the call
```
Request URL: https://api.topcoder.com/v5/members/picachui
Request Method: PUT
```
<img width="1435" alt="Screenshot 2022-01-18 at 5 23 40 PM" src="https://user-images.githubusercontent.com/58783823/149932990-de243e48-c5f0-4924-a404-f0c759eed79d.png">

cc @rakibansary

**Comment by nursoltan-s** [comment]
@SathyaJayabal I think that's related to this:
https://github.com/topcoder-platform/community-app/pull/5974

**Comment by SathyaJayabal** [comment]
https://topcoder.atlassian.net/browse/PLAT-669

**Comment by coderhacker** [comment]
QA Comments: This is not working on the dev environment, please see attached video and screenshot

https://user-images.githubusercontent.com/62358241/154271537-2126bfb5-9f96-437a-a4ca-4d88365e3f83.mp4

![image](https://user-images.githubusercontent.com/62358241/154271558-f280d1d4-b801-485e-8358-9a17e4785f81.png)

**Comment by SathyaJayabal** [comment]
This one is  verified
https://github.com/topcoder-platform/community-app/issues/5954#issuecomment-1041064797

**Comment by sandhiyakavi** [comment]
Verified in Staging Env. Error not displayed

![image](https://user-images.githubusercontent.com/55895538/154413224-ca81285d-58c5-4cc0-a216-7d544824af13.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected

![image](https://user-images.githubusercontent.com/55895538/154426640-f4da7000-6517-462d-aed6-8ab20d9c63ef.png)
