### ISSUE TITLE
Update twitter:title meta for Thrive articles

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5981]
![image](https://user-images.githubusercontent.com/5585002/150299175-5d782932-c31f-4fa2-a25b-9935275cc3e5.png)

Twitter title should be atricle title, not just Topcoder.

**Comment by sandhiyakavi** [comment]
Verified in Beta Env.

![image](https://user-images.githubusercontent.com/55895538/150313245-89c51de4-cf17-4217-9ba1-a4383184df11.png)
![image](https://user-images.githubusercontent.com/55895538/150313369-f5638e2e-9b61-4985-b709-b3f6437865ce.png)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/150502379-45e9c4db-b634-4ab0-a4b6-eccdb0f4c0ed.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/150510691-608bf5d2-5141-4b3b-a4e3-076edc3627c6.png)
