### ISSUE TITLE
Show a tag for self service challenges

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5982]
Show a tag for self service challenges

**Comment by SathyaJayabal** [comment]
verified on dev for the challenge details page:
<img width="1440" alt="Screenshot 2022-01-20 at 3 13 46 PM" src="https://user-images.githubusercontent.com/58783823/150313759-8db4ccb9-65e9-433c-815b-f702732a54d2.png">

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/150503983-3610f919-d569-48d0-90f0-f6c86c2b31e3.png)

**Comment by sandhiyakavi** [comment]
Released to Prod Env.
