### ISSUE TITLE
Logout option is not showing

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/community-app#5990]
**Describe the bug**
Once the user login is successful, its redirects here https://www.topcoder-dev.com/start. 
Once you click the user name, there no logout option is showing.

**To Reproduce**
1. Go to 'https://accounts-auth0.topcoder-dev.com/?retUrl=https://www.topcoder-dev.com/start&mode=signUp' and login with user account
2. Click on username there is logout option is hiding 
3. See an error in the attached screenshot

**Expected behavior**

The logout menu should be accessible and in working correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/62358241/150909505-63efd380-173b-4c72-a7f6-a6dee32cf87c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]- Window
 - Browser [e.g. chrome, safari] All browsers

**Comment by kkartunov** [comment]
Fixed.

**Comment by coderhacker** [comment]
This is working fine on both env. dev and production.

Dev Passed: 
![image](https://user-images.githubusercontent.com/62358241/150936979-444aa6d5-7d49-4e9e-8129-4810417678b1.png)

Prod Passed:
![image](https://user-images.githubusercontent.com/62358241/150937031-93209b58-5a19-4d7d-82de-7e19b4a29e6d.png)
