### ISSUE TITLE
Remove Admins link from TC footer

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#5991]
as per title
![image](https://user-images.githubusercontent.com/5585002/150940675-5411fe07-b462-492c-ad5f-415b0cbb5fbe.png)

**Comment by kkartunov** [comment]
@SathyaJayabal please check...

**Comment by SathyaJayabal** [comment]
verified
<img width="1437" alt="Screenshot 2022-01-28 at 12 05 31 PM" src="https://user-images.githubusercontent.com/58783823/151499447-2f6462c0-5e01-4818-ae96-2420bffce9ca.png">

<img width="1436" alt="Screenshot 2022-01-28 at 12 06 10 PM" src="https://user-images.githubusercontent.com/58783823/151499473-b84a0dda-3b72-4d83-aa36-3f5baa09b200.png">
Note: Will need to remove form the forums footer too

**Comment by kkartunov** [comment]
@SathyaJayabal thanks! I think forums footer will update when we release, let's see...

**Comment by SathyaJayabal** [comment]
@kkartunov , forums footer just replicates the CA footer, but is actually a different one.

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/153827025-c89f320e-0827-4335-8763-021276eef55c.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected.
