### ISSUE TITLE
Unit test coverage

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#6]
After the last challenge there are some failing tests, also the global test coverage should be increased.

**From that submission comments**

> `SubmissionManagement` component will fail the snapshot test since we need to dinamically show the user the time left till the current phase ends.

The time for that component comes from a call to Topcoder API. That call should be mocked with standard Jest methods, and then snapshot test will be feasible.

**Comment by birdofpreyru** [comment]
UPDATE: Will be addressed in this F2F: http://www.topcoder.com/challenge-details/30057203/?type=develop

**Comment by birdofpreyru** [comment]
UPDATE: Unit test coverage was as high as 83% of branches, 93% of functions, 93% of lines and 93% of statements, but it droped low again after migration of challenge listing code into this repo.

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test coverage](https://trello.com/c/mBhnBAXI/3-test-coverage)
