### ISSUE TITLE
A bug (more like a bad design, restricting functionality) in terms reducer

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#601]
It seems, the way it is designed now, it can load only one set of terms; while theoretically we might need more: e.g. when we enter a challenge details page while being in some community - in this case we might need both terms protecting the community, and the terms protecting the challenge.

Most probably, it is not causing any problems now, as the community terms are being used only for join community flow; but it is something that we might need to address at some point.

### Expected Fix:
Terms actions, reducer and the code using them should be updated in the manner similar to RSS actions/reducers:
https://github.com/topcoder-platform/community-app/blob/develop/src/shared/actions/rss.js
https://github.com/topcoder-platform/community-app/blob/develop/src/shared/reducers/rss.js
that allow to load any number of RSS feeds into the Redux state, silently re-load them behind the scene, and to track the timestamps when different feeds were loaded the last time.

**Comment by daft300punk** [comment]
The code only supports 'challenge' or 'community' and not both of them together. Is there anything special about the url of a challenge that is both a community and challenge entity. Like for 'challenge' the code uses this check - https://github.com/topcoder-platform/community-app/blob/develop/src/shared/reducers/terms.js#L311

**Comment by birdofpreyru** [comment]
@daft300punk my problem is that now the fetching of term details is hidden inside the `getTermsDone()` action with no reason, I believe, and it is not flexible. That's why I want to refactor it similarly to RSS actions/reducer, to have actions for:
- load specified (by ID) term details;
- drop specified term details;
- drop all term details.

And then we provide different actions / reducer / service methods to get the list of terms related to a challenge / community; so the interested container will first dispatch the first action to find out which term IDs he is interested in, and then dispatch a bunch of actions to load necessary term details. Actually, for the challenge terms we even won't have to dispatch a separate action to get the list of related term IDs, I believe, as the new v3 endpoint just includes those IDs into the challenge details object.

Why is important? Example is the other ticket in this Bug Bash: https://github.com/topcoder-platform/community-app/issues/607: with the current organization of terms actions / reducer, implementing that page is not straightforward, cause no way to fetch individual term details we need.

**Comment by zjuasmn** [comment]
@birdofpreyru there is an action called GET_TERM_DETAILS_DONE to specified (by ID) term details.

**Comment by birdofpreyru** [comment]
@zjuasmn ok, but with the current design of the corresponding reducer, there is no way to load several term details a time.

**Comment by zjuasmn** [comment]
@birdofpreyru So the expected fix is still keep one set of terms in redux state (as multiple sets can always be merged into one set), but is abled to keep multiple terms details into it. The `TermDetails` component use `state.details[termId]` instead of `state.details`. Right?

**Comment by birdofpreyru** [comment]
@zjuasmn let's just hold off this till the next bug bash.
