### ISSUE TITLE
Add parameters to all navigation items

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#6028]
Top Nav: https://www.topcoder.com/community/?ref=nav

Bottom Nav(All footer): https://www.topcoder.com/community/?ref=navb

**Comment by kkartunov** [comment]
@SathyaJayabal fyi please...

**Comment by sandhiyakavi** [comment]
@kkartunov Observed the below points,

1. In the footer, "Talk to Sales" link is giving 404 error page as it is now not redirected to https://go.topcoder.com/contact/ after adding the parameter.


https://user-images.githubusercontent.com/55895538/155092325-8300e207-7317-43ee-9054-ed482fdc497c.mp4

2. For the pages below the URL has the nav parameter when hovered over but when we go to the page, the parameter is not getting displayed in the URL. Is it expected ?
       1. Challenges page
       2. Programs page
       3. Statistics page
       4. My profile page
       5. Connect.topcoder.com (on clicking the "Switch to business" link )
       6. Changelog page (Footer)
       7. youtube (Footer)


https://user-images.githubusercontent.com/55895538/155093522-f8543f07-4199-43c5-89dd-e494135de388.mp4

**Comment by kkartunov** [comment]
Hey @sandhiyakavi thanks!

1. is fixed.
2. Yes it is okay. We want to track the clicks on those links thus the paramenter.

**Comment by kkartunov** [comment]
@sandhiyakavi fix is deploying on beta now...

**Comment by sandhiyakavi** [comment]
Above issue is resolved.

<img width="960" alt="talk_to_sales" src="https://user-images.githubusercontent.com/55895538/155114605-ba6295b6-70fb-4f5d-9483-4504e753146b.png">

@kkartunov For My profile, the URL is not displaying the parameter.

![image](https://user-images.githubusercontent.com/55895538/155115029-c9b42b12-e1e8-4f91-ab8f-c766eff0cf66.png)

Also the URL for the Topcoder logo is not having the parameter

![image](https://user-images.githubusercontent.com/55895538/155115178-d9b5b2e6-e315-4634-a8d8-4c88f23906f5.png)

**Comment by kkartunov** [comment]
@sandhiyakavi there won't be ref=xxx needed on profile & logo, they excluded.

**Comment by sandhiyakavi** [comment]
verified in Beta Env. Working as expected

**Comment by sandhiyakavi** [comment]
Verified in Staging Env. Working as expected.

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected
