### ISSUE TITLE
Member Profile : the User handle should be treated like an invalid one

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#6029]
Member Profile : the User handle should be treated like an invalid one

https://topcoder.atlassian.net/browse/PLAT-687
Community App shows user profile as active, even if the user is suspended via the admin tool.  eg the user handle `liyakat` was suspended for spamming, but shows up as Active in Community app

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag and Dev.
https://staging-community-app.topcoder.com/members/liyakat

If member `status` != `ACTIVE` will return 404.

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/165018523-101add4c-d40d-4b59-a2c4-0e777e54a3b5.png)

Dev Env.
![image](https://user-images.githubusercontent.com/55895538/165018687-67563552-6136-4e58-90a6-08c47b42add5.png)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/165492458-edd254af-b054-4eff-a971-f99ee87d0073.png)
![image](https://user-images.githubusercontent.com/55895538/165492695-778f96c7-3fca-46b1-8c61-3ef3abfa2fcb.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/165718796-1f585ae2-75f6-4a31-b5ca-710b1000907b.png)
