### ISSUE TITLE
Getting a unnecessary dialog box of error after going to the page of a challenge

### ISSUE THREAD

**Issue by vivonk** [topcoder-platform/community-app#604]
This is what I am getting :- 
ERROR: Failed to load the challenge

Please, try again a bit later

We are sorry you have encountered this problem. Please log the issue into our GitHub repository so that we can fix it as soon as possible

**Comment by birdofpreyru** [comment]
If you see this dialog, there is surely something that failed to load, due to some temporarily problems. If you still see that dialog somewhere, please give the link(s) to the challenges where it happens.
