### ISSUE TITLE
Update 404 error page

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#6041]
as per title
https://marvelapp.com/prototype/7dg07ij/screen/85359372
no searchbar and search functionality should be included.

**Comment by kkartunov** [comment]
Deployed on beta. @SathyaJayabal please check...

**Comment by sandhiyakavi** [comment]
Verified in Beta Env. Working as expected


https://user-images.githubusercontent.com/55895538/157169350-a332604c-f041-42ee-b4d5-184510e9b831.mp4

**Comment by sandhiyakavi** [comment]
Verified in Staging Env. 

![image](https://user-images.githubusercontent.com/55895538/157391441-576bb2b6-5025-4ac6-accc-dee5f4f9c227.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected

![image](https://user-images.githubusercontent.com/55895538/157421102-b3867536-3ff4-4030-b8fd-0449cf1feb9b.png)
