### ISSUE TITLE
Add discord button to Thrive articles

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#6051]
Design: https://marvelapp.com/prototype/69f39fc/screen/85778895/handoff

**Comment by kkartunov** [comment]
JIRA: https://topcoder.atlassian.net/browse/PROD-1803

**Comment by kkartunov** [comment]
Ready for QA on beta. Please check @SathyaJayabal 
Should be on any article details page like for instance https://beta-community-app.topcoder.com/thrive/articles/long-short-term-memory-networks-lstm

**Comment by SathyaJayabal** [comment]
verified on beta
<img width="390" alt="Screenshot 2022-05-05 at 3 18 22 PM" src="https://user-images.githubusercontent.com/58783823/166899775-e3ea5d9b-ae3d-4e26-b921-7b8da92482c7.png">

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1439" alt="Screenshot 2022-05-10 at 2 46 34 PM" src="https://user-images.githubusercontent.com/58783823/167594360-d951328f-b3d4-48fe-bd04-bd5f5c236042.png">

**Comment by sandhiyakavi** [comment]
verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/167610888-d4239cdb-393b-40a3-b018-53fe6e31af84.png)
