### ISSUE TITLE
Add Request a Marvel App Project Button

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#606]
We need to add a Request a Marvel App Project Button on the challenge details page to avoid so many requests on forums. This button should display only after a member has registered for a challenge, and only on those challenges where is requested ( for example we don't need it on logo challenges, etc).

In the zip file attached, there is a powerpoint file, that shows how the process is now. 

In the new version, once the designer request a project, the copilot will get an email notification about the request. He will then allocate a project in Marvel and copy paste the details-link and name - of this (in Direct maybe?) so they display on the challenge details page, ONLY for that designer. Each designer can see his own link only. 

Also, when I say project..a designer will press the Request a Marvel App Project, but if the challenge needs 2 Marvel Projects like for desktop and mobile, the copilot will know that the specific challenge requires 2 prototypes and will give him 2.

Let me know if you have any questions.
[Marvel App Project.zip](https://github.com/topcoder-platform/community-app/files/1503862/Marvel.App.Project.zip)

**Comment by Dara-K** [comment]
I added to these files the API icon and the Connection Lost one, that you asked about - just check the interactive specs files or download here.
[icons.zip](https://github.com/topcoder-platform/community-app/files/1503886/icons.zip)

**Comment by Dara-K** [comment]
New update from Adam: Let's implement it like in this design. Once the button is clicked it just triggers an email to copilot, who will then allocate in Marvel a link. The text "Request Sent" will appear below button. the button stays in case there is an issue.

[Marvel App Project Update.zip](https://github.com/topcoder-platform/community-app/files/1506592/Marvel.App.Project.Update.zip)

**Comment by ajefts** [comment]
Love the idea in general, but we need to figure out how to add this feature more generically to the challenge engine.  I.e. it's a similar situation if people need access to a git repo, virtual env, software license, evironment access, etc.

We will review to see where this fits on the roadmap.
