### ISSUE TITLE
THRIVE Articles not accessible to Topgear

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#6063]
https://topcoder.atlassian.net/browse/PLAT-922

Topgear user is getting a blank page when trying to open the recommended Thrive articles that are embedded in the challenge page.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag and Dev.

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.


https://user-images.githubusercontent.com/55895538/165019586-143411d1-6fcf-4d4a-b788-70307a7862bc.mp4

**Comment by sandhiyakavi** [comment]
verified in dev Env.


https://user-images.githubusercontent.com/55895538/165498849-19b28f07-fed3-4775-b175-25e03f84d2b4.mp4

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

<img width="1680" alt="Screenshot 2022-04-28 at 2 49 31 PM" src="https://user-images.githubusercontent.com/55895538/165721296-49d990c3-df2b-4e51-aabd-468a610f5c78.png">
