### ISSUE TITLE
[$150] - Basic Terms Page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#607]
We need a version of the terms page that we can link to in a non-modal form:

![image](https://user-images.githubusercontent.com/3812270/33274168-4da20d98-d35d-11e7-84a0-c23371f0bf86.png)

We used to have these links:  https://www.topcoder.com/challenges/terms/detail/21153/

I believe they are not working now that we have community-app serving /challenges.  I'd like to have community app provide functionality to display the terms under the same URLs.

**Comment by birdofpreyru** [comment]
### Notes
- The page should support both the simple TC terms, and the DocuSign terms.
- In the case of the simple TC terms it should be styled with the standard TC text styling (https://github.com/topcoder-platform/community-app/blob/develop/src/styles/_mixins/_typography.scss - `@include tc-title` for the main title, `@include tc-heading-md` and `@inlcude tc-body-md` for the headers and paragraphs).

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/633
hash: 1f19c57
