### ISSUE TITLE
[Web] [Chrome] - Page does not scroll when Lets talk button is clicked a few times

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/community-app#6072]
- **Device**:  Laptop

- **Operating System:** Windows 10

- **Browser**:  Chrome Version 100.0.4896.60 (Official Build) (64-bit)

**- Steps to reproduce:** 
1.  go to https://www.topcoder.com/data-science/data-advisory/
2. click on Lets talk button a few times
3.  try scrolling

**- Actual result:** 
Page does not scroll when Lets talk button is clicked

**- Expected results:** 
Page should scroll bottom

**- Testing collateral:**

https://user-images.githubusercontent.com/46344490/161292210-8ef98303-e5cb-45cf-9b90-96ab8559233c.mp4

**Comment by draco-malfoy** [comment]
**Update**: Same for the Lets talk button available in card 'PRODUCT SNAPSHOT'

**Comment by drasticdpk** [comment]
Not a valid issue.
