### ISSUE TITLE
[Web] [Chrome] - Accordion close button does not work

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/community-app#6074]
- **Device**:  Laptop

- **Operating System:** Windows 10

- **Browser**:  Chrome Version 100.0.4896.60 (Official Build) (64-bit)

**- Steps to reproduce:** 
1.  go to https://www.topcoder.com/data-science/
2. scroll to section where 'DATA SCIENCE FAQS' is there
3. open a question and try closing it

**- Actual result:** 
 Accordion close button does not work

**- Expected results:** 
 Accordion close button should work

**- Testing collateral:**

https://user-images.githubusercontent.com/46344490/161293105-42a93470-f993-402a-9c9b-463f01defd0a.mp4

**Comment by drasticdpk** [comment]
Not a bug.
