### ISSUE TITLE
[Mobile] [Chrome] - Data analytics page has white spaces

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/community-app#6076]
- **Device**:  Laptop

- **Operating System:** Windows 10

- **Browser**:  Chrome Version 100.0.4896.60 (Official Build) (64-bit)

**- Steps to reproduce:** 
1.  go to https://www.topcoder.com/blog/case-study-types/data-analytics/
2.  scroll to bottom

**- Actual result:** 
Data analytics page has white spaces 

**- Expected results:** 
Should not  have white space  

**- Testing collateral:**

https://user-images.githubusercontent.com/46344490/161294342-1cf9bf97-7976-4056-ac92-f5a1e63e5e8d.mp4

**Comment by drasticdpk** [comment]
Out of scope
