### ISSUE TITLE
Data Analytics button is so small and not properly visible to user 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6077]
**Describe the bug**
Data Analytics button is so small and not properly visible to user 

**To Reproduce**
1.	Login in to https://www.topcoder.com/case-studies/spacenet/
2.	 ( Do Login With Valid Credentials)
3.	Observe the Data Analytics button
4.	Observe the UI

**Actual behavior**
Data Analytics button is so small and not properly visible to user 

**Expected behavior**
Data Analytics button should be little big and properly visible to user 

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser [Chrome, Safari, Microsoft Edge, and Firefox]
 - Version [Firefox - 98.0.2 (64-bit)]

**Screenshots**

![image](https://user-images.githubusercontent.com/31862600/161294421-3811a36f-e87e-4bb4-8e45-67861e8c374a.png)

**Comment by drasticdpk** [comment]
out of scope( page url)
