### ISSUE TITLE
[Web] [Chrome] - Currently selected filter icon is wrong

### ISSUE THREAD

**Issue by draco-malfoy** [topcoder-platform/community-app#6080]
- **Operating System:** Windows 10

- **Browser**:  Chrome Version 100.0.4896.60 (Official Build) (64-bit)

**- Steps to reproduce:** 
1.  go to https://www.topcoder.com/blog/case-study-types/data-analytics/
2. scroll to data analytics section
3. click on grid and line displays
4. the selected items turn gray, which is opposite

**- Actual result:** 
Button has no action

**- Expected results:** 
When grid is selected, its color becomes gray, and when line is selected its color becomes gray

i.e the selected item should be green indicating that is activated, but opposite is happening

**- Testing collateral:**
When grid is selected, its color should be green, and when line is selected its color should be green

https://user-images.githubusercontent.com/46344490/161296288-98b4f346-91a9-4087-b686-bbd64388e5f0.mp4

**Comment by drasticdpk** [comment]
@draco-malfoy 
In-scope 
https://www.topcoder.com/
https://www.topcoder.com/data-science/
https://www.topcoder.com/data-science/data-exploration/
https://www.topcoder.com/data-science/data-advisory/
https://www.topcoder.com/data-science/find-me-data/
https://www.topcoder.com/how-it-works/?ref=nav
