### ISSUE TITLE
Web [Edge] - "^" icon is not squeezing.Details are not getting hidden

### ISSUE THREAD

**Issue by gthrone2021** [topcoder-platform/community-app#6082]
1. Go to 'https://www.topcoder.com/data-science/'
2. Goto Data Science FAQ
3. Scroll down to Expand / Shrink the details below

Issue : Last "^" icon content is not getting hidden.

**Expected behavior**
Details should get hidden on click of "^" icon

![Screencast 2022-04-01 21-04-00](https://user-images.githubusercontent.com/88379172/161296467-c23b6914-959d-4aab-9ffa-734b2ffb756e.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [chrome , Edge]
 - Version [chrome - Version 100.0.4896.60]
           [Edge - Version 99.0.1150.55]

**Comment by drasticdpk** [comment]
Not a issue.
