### ISSUE TITLE
Android, Homepage

### ISSUE THREAD

**Issue by LeboThulare-bit** [topcoder-platform/community-app#6085]
**Bug Description**
The Topcoder logo icon is placed to the left in homepage before signup.

Device - Android 8
Browser - chrome " 99.0.48"

1. Click on homepage link
2. Land on the homepage
3. Look at the top part of the page
4. Locate the Topcoder logo icon

Expected Results:
The Topcoder logo icon should be positioned at the center.

Actual Results:
The Topcoder logo icon is positioned to the left.

Bug Type - UX

Screenshot
![Screenshot_20220401-172803](https://user-images.githubusercontent.com/61011018/161296815-1d528845-18d6-423a-bb81-774f095fb440.png)

**Comment by drasticdpk** [comment]
not a bug
