### ISSUE TITLE
DATA SCIENCE FAQS expand collapse not working -: /data-science/

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6086]
**Describe the bug**
DATA SCIENCE FAQS expand collapse not working 

**To Reproduce**
1. Go to (https://www.topcoder.com/data-science/)
2. Scroll down to DATA SCIENCE FAQS area
4. Expand questions and try to collapse 

**Expected behavior**
After expanding when try to collapse, collapse is not working 

**Screenshots**

https://user-images.githubusercontent.com/98445449/161297366-f4379618-ddf3-430f-afd1-5f32545a76ce.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 96.0.4664.110

Type of Bug -: Functional

**Comment by drasticdpk** [comment]
Not a bug.
