### ISSUE TITLE
In talk to sales form Message "This field is required " is not displaying for all required fields.

### ISSUE THREAD

**Issue by ashree1** [topcoder-platform/community-app#6094]
**Describe the bug**
When there is multiple click on submit button without any input in talk to sales form,selects value for field What are you interested in field and then clicks on submit button app is not able to display message "This field is required" for all other remaining mandatory fields.
**To Reproduce**
1. Open the url https://www.topcoder.com/
  2. Scroll down the page and reach Web Development.
3. Click on LET'S TALK 
4. Click on Submit button.
5. Again click on submit button and observe.
6. Select the value in field "What are you interested in?
7. Click on submit button without entering values in other fields.

**Expected behavior**
"This field is required" message should be there for all mandatory fields.
**Screenshots**
https://user-images.githubusercontent.com/98447324/161298772-e895c2af-9f3d-4ad7-b6bf-7021405e4ead.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [Version 98.0.2 (64-bit)]

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/community-app/issues/6069
