### ISSUE TITLE
Edge – App is highlighting entire “Lets Talk” form while double clicking the “Let Talk” button ( while clicking 2nd time do long click and don release left click and drag cursor to form)

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6095]
**Describe the bug**
Edge – App is highlighting entire “Lets Talk” form while double clicking the “Let Talk” button ( while clicking 2nd time do long click and don release left click and drag cursor to form)

**To Reproduce**
1.	Login in to Find Me Data - Topcoder
2.	 ( Do Login With Valid Credentials)
3.	Double click and while clicking 2nd time do long click and don release left click and drag cursor to form
4.	Observe the UI

**Actual behavior**
Edge – App is highlighting entire “Lets Talk” form

**Expected behavior**
Edge – App should not highlight entire “Lets Talk” form

This issue not happening in firefox 

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser [Chrome, Safari, Microsoft Edge, and Firefox]
 - Version [Edge - Version 99.0.1150.55 (Official build) (64-bit)]

**Screenshots**

https://user-images.githubusercontent.com/31862600/161299054-7f724742-d8d0-4b15-aebf-a24a4e28d438.mp4

**Comment by drasticdpk** [comment]
Unable to replicate it.
