### ISSUE TITLE
[Web][Chrome] Notification icon in the profile modal is not visible correctly

### ISSUE THREAD

**Issue by ashabailu** [topcoder-platform/community-app#6098]
Weight: 2
**Describe the bug**
Notification Bell icon near the profile Avatar in the profile modal is not visible correctly.

**To Reproduce**
1. Launch "https://www.topcoder.com/"
2. Click on 'Login'
3. Click on arrow icon near user name on left  top navigation bar
4. Check the notification icon near the profile avatar

**Expected behavior**
Notification bell should be visible correctly

**Current Behavior**
Half of the bell is not visible

![image](https://user-images.githubusercontent.com/102788789/161299335-30b9ccb8-aed4-47fa-a18d-ce79853f46b5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser [chrome]
 - Version Version 99.0.4844.84 (Official Build) (64-bit)
 -

**Comment by drasticdpk** [comment]
out of scope.
