### ISSUE TITLE
FireFox – This Field Required error message is different in in Edge 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6099]
**Describe the bug**
FireFox – This Field Required error message is different in in Edge 

**To Reproduce**
1.	Login in to https://www.topcoder.com/data-science/find-me-data/
2.	 ( Do Login With Valid Credentials)
3.	Click  “Lets Talk” button
4.	Don’t enter any details
5.	Click Submit button
6.	Observe error message between Firefox and Edge 

**Actual behavior**
FireFox – This Field Required error message is different in in Edge 

**Expected behavior**
FireFox – This Field Required error message is different in in Edge 

This issue not happening in firefox 

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser [Chrome, Safari, Microsoft Edge, and Firefox]
 - Version [Edge - Version 99.0.1150.55 (Official build) (64-bit)]

**Screenshots**

https://user-images.githubusercontent.com/31862600/161299726-b4da0f98-ad10-4a76-8074-2b64fd66d1a9.mp4

**Comment by drasticdpk** [comment]
This is browser behavior.
