### ISSUE TITLE
[$150] - Refactor Select Font section in Design Submission page

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#610]
### Expected Fix:
- That section (related code, division into components, related actions and reducer) should be refactored in the manner similar to the Stock Art Input section;
- Obsolete code (MultiInput, anything else, which is not necessary anymore) should be removed;
- For the `Studio Standard Fonts List` option we don't need to show the Font URL input at all. With the new organization of the related code, it should be easy to do in a clean way;
- Double check, that design submission process remains functional.

**Comment by zjuasmn** [comment]
PR: https://github.com/topcoder-platform/community-app/pull/634
hash: ec39634
