### ISSUE TITLE
Overlap issue in https://www.topcoder.com/how-it-works/?ref=nav

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6111]
**Describe the bug**
Overlap issue in https://www.topcoder.com/how-it-works/?ref=nav

**To Reproduce**
1.	Login in to https://www.topcoder.com/how-it-works/?ref=nav
2.	 ( Do Login With Valid Credentials)
3.	Observe UI 

**Actual behavior**
Overlap issue in https://www.topcoder.com/how-it-works/?ref=nav

**Expected behavior**
App should not overlap 

This issue not happening in firefox 

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser [Chrome, Safari, Microsoft Edge, and Firefox]
 - Version [Edge - Version 99.0.1150.55 (Official build) (64-bit)]

**Screenshots**

![image](https://user-images.githubusercontent.com/31862600/161301624-db2fc6a6-a1bc-421b-ad7f-dec938b5ec8e.png)

**Comment by youdare** [comment]
https://user-images.githubusercontent.com/31862600/161301774-e5e368eb-09f3-4045-bbfb-6317b0383417.mp4

**Comment by drasticdpk** [comment]
duplicate
