### ISSUE TITLE
 [Web] [Chrome] Pop up out of place when page is scrolled down.

### ISSUE THREAD

**Issue by akiransa** [topcoder-platform/community-app#6158]
**Issue Title :** [Web] [Chrome] Pop up out of place
**Device:** Laptop
**Operating System:** Windows
**Browser:** Chrome
**Steps to reproduce:** 

- Login and go to URL - https://www.topcoder.com/data-science/data-exploration/
- Click on Let's talk
- Click on what are you interested in

**Actual result:** 
- Pop up out of place

https://user-images.githubusercontent.com/9376922/161309917-0746385c-df50-434b-8350-047fcc8f81e3.mp4

**Expected results:** 
- Pop up in place

**Bug Type:** UI Bug

**Testing collateral:** 
 - Chrome Version 99.0.4844.82 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
duplicate
