### ISSUE TITLE
Cognitive Community Design Updates

### ISSUE THREAD

**Issue by trevorgerring** [topcoder-platform/community-app#616]
@birdofpreyru UI design updates for the Cognitive Community site. Style wise, this is based on the Veterans site, so should be pretty straight forward. The big thing is to keep things consistent across sites, which we've already been talking about, so all good there. 

Added the designs to Zeplin and added you here: https://zpl.io/aXKNzgX

The client is reviewing the copy updates so there may be some changes, but overall I dont think the structure will change much. Let me know what else you need

**Comment by birdofpreyru** [comment]
@ajefts I've run an F2F for this yesterday: https://www.topcoder.com/challenges/30060820/?type=develop
Had some problems to actually invite the ppl to the design specs, but it should be resolved now, so I hope to see it done in a day or few.

**Comment by trevorgerring** [comment]
@birdofpreyru How are we looking here? We originally had a go-live date of 12/6 for this. There are a few design updates based on feedback from the client. I've added a V2 to the same Zeplin link. I know this will change/ delay things, so let us know what that looks like.

**Comment by birdofpreyru** [comment]
@trevorgerring unfortunately, after a few submissions to the dedicated F2F that had problems, there seems to be not much action. If tomorrow is critical, I can jump in and make it myself. Also, have you seen my msgs to you in Slack?

**Comment by birdofpreyru** [comment]
Mostly done, any other fixes should be tracked in separate tickets
