### ISSUE TITLE
 [Web] [Safari] Button highlights disappear in Cognitive disability profile on Platform>platform tools> Manage Work

### ISSUE THREAD

**Issue by akiransa** [topcoder-platform/community-app#6200]
*Issue Title :* [Web] [Safari] Button highlights disappear in Cognitive disability profile on Platform>platform tools> Manage Work

- Device: Laptop, MacBook Air (13-inch, 2017)

- Browser:  Safari Version 15.2 (17612.3.6.1.6)

- Operating system : Mac OS Monterey Version 12.1

*Steps to Reproduce:*

[https://www.topcoder.com/security/?ref=nav](https://www.topcoder.com/data-science/data-advisory/)

Accessibility adjustments
Turn on cognitive disability profile on
Main Menu
click on Platform
click on Platform Tools>Manage Work
Buttons “Book a platform demo” and “book a demo” are highlighted.
switch to platform > overview> security
switch it back again to Platform>platform tools> Manage Work

*Actual Results:*

Buttons “Book a platform demo” and “book a demo” highlights are disappeared
*Expected Results:*

- Buttons “Book a platform demo” and “book a demo” highlights should appear.

*Bug Type:* UI/UX Bug

*Testing collateral:* 

 - Safari Version

**Comment by drasticdpk** [comment]
Reference image/video is missing. and Above URL is not in scope.

**Comment by akiransa** [comment]
https://user-images.githubusercontent.com/9376922/161502735-35001c7f-6e21-426f-8097-2f48c6be34bd.mov

@drasticdpk 
Steps to Reproduce:

[[https://www.topcoder.com/security/?ref=nav](https://www.topcoder.com/data-science/data-advisory/)
](https://www.topcoder.com)


Main Menu
click on Platform
click on Platform Tools>Manage Work
Accessibility adjustments
Turn on cognitive disability profile on
Buttons “Book a platform demo” and “book a demo” are highlighted.
switch to a different menu for ex: platform > overview> security
switch it back again to Platform>platform tools> Manage Work

Actual Results:

Buttons “Book a platform demo” and “book a demo” highlights are disappeared
Expected Results:

Buttons “Book a platform demo” and “book a demo” highlights should appear.
Bug Type: UI/UX Bug
