### ISSUE TITLE
[Web][Chrome]Topcoder HomePage

### ISSUE THREAD

**Issue by mesh98** [topcoder-platform/community-app#6201]
**Describe the bug**
When you click at let's talk under 'What can I do at Topcoder' section, it changes the URL at the search bar and remains even when the pop-up is closed.

**To Reproduce**
1. Go to www.topcoder.com
2. Scroll down to the section "What can I do at Topcoder"
3. Click on Let's talk under Web Development/ UI design/ QA testing
4. Notice the URL at the top 
5. Now, Close the pop-up 
6. See that the URL still remains the same

**Expected behavior**
The URL should get back to topcoder.com

**Actual behaviour**
The URL adds the extension "topcoder.com/#do-box-block_6237f8de0dd83" when pop-up appears and remains though it was closed.

**Screenshots**

**Laptop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Chrome
 - Version 100

**Comment by drasticdpk** [comment]
Not a issue.
