### ISSUE TITLE
[Web] [Safari] Highlights which appear intially when cognitive disability profile on , are disappearing in almost all sub menu pages when switching in between the sub menus.

### ISSUE THREAD

**Issue by akiransa** [topcoder-platform/community-app#6203]
*Issue Title :* [Web] [Safari] Highlights which appear intially when cognitive disability profile on , are disappearing in almost all sub menu pages when switching in between the sub menus.

- Device: Laptop, MacBook Air (13-inch, 2017)

- Browser:  Safari Version 15.2 (17612.3.6.1.6)

- Operating system : Mac OS Monterey Version 12.1

*Steps to Reproduce:*

[https://www.topcoder.com/the-talent/?ref=nav](https://www.topcoder.com/data-science/data-advisory/)

Accessibility adjustments
Turn on cognitive disability profile on
Main Menu
click on Platform
click on Platform Tools>Manage Work
Buttons “Book a platform demo” and “book a demo” are highlighted.
switch to platform > overview> security
switch it back again to Platform>platform tools> Manage Work

Similar issues for all of the submenus.
*Actual Results:*

Buttons “Book a platform demo” and “book a demo” highlights are disappeared
Need to switch in between  sub menu pages and check
*Expected Results:*

- Highlights shouldnt disappear

*Bug Type:* UI/UX Bug

*Testing collateral:* 

 - Safari Version

--------

**Comment by drasticdpk** [comment]
We need reference video for every issue.
