### ISSUE TITLE
Firefox Mobile –In Section “Get A Project Completed”,  App is navigating to other link while clicking empty space near the “Start A Project” button  

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6208]
**Describe the bug**
Firefox Mobile –In Section “Get A Project Completed”,  App is navigating to other link while clicking empty space near the “Start A Project” button  

**To Reproduce**
1.	Login in to https://www.topcoder.com/how-it-works/?ref=nav
2.	 ( Do Login With Valid Credentials)
3.	Go to section “Get A Project Completed”,  
4.	Click Empty space near the  “Start A Project” button  
5.	Observe the UI

**Actual behavior**
Firefox Mobile –In Section “Get A Project Completed”,  App is navigating to other link while clicking empty space near the “Start A Project” button  

**Expected behavior**
Firefox Mobile –In Section “Get A Project Completed”,  App should not navigate to other link while clicking empty space near the “Start A Project” button  

**Smartphone (please complete the following information):**
 - Device: [Samsung A50]
 - OS: [Android]
 - Browser [Firefox]
 - Version [11]

https://user-images.githubusercontent.com/31862600/161319396-20681b74-ee9a-4c91-ba0d-d623b5da52b3.mp4

**Comment by drasticdpk** [comment]
Unable to replicate.
