### ISSUE TITLE
[Web][Safari] Inconsistency across devices

### ISSUE THREAD

**Issue by akiransa** [topcoder-platform/community-app#6209]
**Issue Title :** [Web] [Safari] Consistency of display elements
**Device:** iPad
**Operating System:** MacOS
**Browser:** Safari
**Steps to reproduce:** 

- Go to URL - https://www.topcoder.com/data-science/data-advisory/
- Scroll to "GET STARTED WITH DATA SCIENCE AT TOPCODER"

**Actual result:** 
- for every 10 secs, the above one is scrolling in web is not scrolled here in iPad 

https://user-images.githubusercontent.com/9376922/161319919-a4e9bf95-6b60-403a-9b2c-3d33ab42ce1d.mp4

https://user-images.githubusercontent.com/9376922/161320013-e15b06eb-3843-4cfd-804c-5fddc5aaf531.mp4

**Expected results:** 
-  consistency in behaviour across devices.

**Bug Type:** UI Bug

**Testing collateral:** 
 - Chrome Version 99.0.4844.82 (Official Build) (64-bit)

**Comment by drasticdpk** [comment]
Woking for me.
