### ISSUE TITLE
Firefox Mobile –  App is navigating to other link while clicking empty space in the “And More” Link  

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6210]
**Describe the bug**
Firefox Mobile –  App is navigating to other link while clicking empty space in the “And More” Link  

**To Reproduce**
1.	Login in to https://www.topcoder.com/how-it-works/?ref=nav
2.	 ( Do Login With Valid Credentials)
3.	Scroll down the page
4.	Click Empty space near the  “And More” Link  
5.	Observe the UI

**Actual behavior**
Firefox Mobile –  App is navigating to other link while clicking empty space in the “And More” Link  

**Expected behavior**
Firefox Mobile –  App should not navigating to other link while clicking empty space in the “And More” Link  

**Smartphone (please complete the following information):**
 - Device: [Samsung A50]
 - OS: [Android]
 - Browser [Firefox]
 - Version [11]

https://user-images.githubusercontent.com/31862600/161319906-65f4fce8-a3ea-4543-846b-1865d4210b23.mp4

**Comment by drasticdpk** [comment]
I am unable to replicate this issue with  finger in my device.

**Comment by youdare** [comment]
@drasticdpk , i am able to reproduce the issue by clicking empty space
I used my hand to reproduce and recorded using DU Screen Recorder

https://user-images.githubusercontent.com/31862600/161436570-24c6de26-7017-4ae9-b5f7-644c6bfb6f98.mp4
