### ISSUE TITLE
Tab key is leading unexpected design issue.

### ISSUE THREAD

**Issue by ashree1** [topcoder-platform/community-app#6215]
**Describe the bug**
user is getting unexpected design issue after using tab key.

**To Reproduce**
1. Open https://www.topcoder.com/oil-gas-utilities-energy/?ref=nav
2. Press tab key 6 times and observe.
3. From the displayed screen click on any one topic and observe.

**Expected behavior**
when user Navigates app using tab key app should allow user to navigate without design error.

**Screenshots**

![1](https://user-images.githubusercontent.com/98447324/161323650-941dd82b-af5c-452e-a823-5e228b71b66b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox ]
 - Version [98.0.2 (64-bit)]

**Comment by drasticdpk** [comment]
Unbale to replicate
