### ISSUE TITLE
User is getting blank area on clicking on clicking on hovering over the Platform menu.

### ISSUE THREAD

**Issue by ashree1** [topcoder-platform/community-app#6217]
**Describe the bug**
User is getting blank area on clicking on clicking on hovering over the Platform menu.

**To Reproduce**
1. Open https://www.topcoder.com/oil-gas-utilities-energy/?ref=nav
2. Press tab key 6 times.
3. Press escape key
3. Now click on platform menu and observe.

**Expected behavior**
When user clicks on Platform menu, user should get the sub menu/menu item of Platform menu.

**Screenshots**

https://user-images.githubusercontent.com/98447324/161323851-f76b685c-18c4-497f-b5a9-f022c5c2e205.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox ]
 - Version [98.0.2 (64-bit)]

**Comment by drasticdpk** [comment]
Unbale to replicate.
