### ISSUE TITLE
Firefox -  Let Talk -> App is not popping out the “Talk To Sale” form while clicking “Data Science” Header

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6230]
**Describe the bug**
Firefox -  Let Talk -> App is not popping out the “Talk To Sale” form while clicking “Data Science” Header

Note:- When We click other Header app is involving form ( See Video ) 

**To Reproduce**
1.	Login in to https://www.topcoder.com/
2.	 ( Do Login With Valid Credentials)
3.	Click Header “Data Science” 
4.	Observe UI

**Actual behavior**
App is not popping out the “Talk To Sale” form while clicking “Data Science” Header

**Expected behavior**
App should pop up form while clicking  “Data Science” Header

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser [Chrome, Safari, Microsoft Edge, and Firefox]
 - Version [Edge - Version 99.0.1150.55 (Official build) (64-bit)]

**Screenshots**

https://user-images.githubusercontent.com/31862600/161328858-38af0b78-11f4-409f-9258-e95552e4ab15.mp4

**Comment by drasticdpk** [comment]
Not a bug. This is expected.
