### ISSUE TITLE
iPhone IOS -  In Landscape Mode – While Submitting empty form of “Talk To Sales” , app is not automatically navigating top displaying “Field Required” pop up message 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6250]
**Describe the bug**
iPhone IOS -  In Landscape Mode – While Submitting empty form of “Talk To Sales” , app is not automatically navigating top displaying “Field Required” pop up message 

**To Reproduce**
1.	Login in to https://www.topcoder.com/
2.	 ( Do Login With Valid Credentials)
3.	Go to Landscape Mode
4.	Click “Lets Talk” button
5.	App display Talk To Sales Form
6.	Without entering any details click “Submit” button
7.	Observe UI

**Actual behavior**
While Submitting empty form of “Talk To Sales” , app is not automatically navigate to top  and display “Field Required” pop up message

**Expected behavior**
While Submitting empty form of “Talk To Sales” , app should automatically navigating top displaying “Field Required” pop up message

**Smartphone (please complete the following information):**
 - Device: [iPhone 13]
 - OS: [14]
 - Browser [Safari]

https://user-images.githubusercontent.com/31862600/161353422-f3638e89-3a6a-42b6-ad10-3b464ae7e892.mp4

**Comment by drasticdpk** [comment]
duplicate
