### ISSUE TITLE
iPhone IOS -  In “Get started with Data Science at Topcoder” section , left and right navigation button is missing 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#6254]
**Describe the bug**
iPhone IOS -  In “Get started with Data Science at Topcoder” section , left and right navigation button is missing 

**To Reproduce**
1.	Login in to https://www.topcoder.com/data-science/find-me-data/
2.	 ( Do Login With Valid Credentials)
3.	Go to Landscape Mode or Portrait mode 
4.	Go to “Get started with Data Science at Topcoder” section
5.	Observe the UI

**Actual behavior**
In “Get started with Data Science at Topcoder” section , left and right navigation button is missing

**Expected behavior**
In “Get started with Data Science at Topcoder” section , left and right navigation button should be available

**Smartphone (please complete the following information):**
 - Device: [iPhone 13]
 - OS: [14]
 - Browser [Safari

https://user-images.githubusercontent.com/31862600/161354487-dde60fd2-44ea-4c43-b571-3abb3be92c04.mp4

**Comment by drasticdpk** [comment]
duplicate
