### ISSUE TITLE
Flipped password text placeholders in topcoder profile settings

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#6283]
We need to flip the placeholder for New Password  and Re-type New password field. Please check below screenshot for the same.
![image-20220404-191309](https://user-images.githubusercontent.com/58783823/161688197-8ac81ecd-23fe-4892-9d79-1fe804cec984.png)

**Comment by SathyaJayabal** [comment]
https://topcoder.atlassian.net/browse/PLAT-946

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Dev and Stag env

**Comment by sandhiyakavi** [comment]
Verified in Staging and Dev Env.

![image](https://user-images.githubusercontent.com/55895538/164603490-c86a1de5-63b7-4452-851a-ba78d98a5a14.png)
![image](https://user-images.githubusercontent.com/55895538/164603541-4f9a14fd-7cb6-4c8e-872d-d67855c3e924.png)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/165492122-620ac92c-4293-4c87-bdfd-3c25e2ea20c3.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/165719413-b28327b5-895d-41d9-9aac-8d43da00533c.png)
