### ISSUE TITLE
Remove Default Payment Section in Challenge Spec

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#6289]
Remove Default Payment Section in Challenge Spec
Ref: https://topcoder.atlassian.net/browse/PLAT-953
From @Oanh-and-only-Oanh :` you can just remove the default payment section. Currently, we can’t allow challenge creator to add customize payment text so we’ll just remove the default completely.`

code ref: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/components/challenge-detail/Specification/index.jsx

**Comment by luizrrodrigues** [comment]
@SathyaJayabal This section: 
![image](https://user-images.githubusercontent.com/7029641/162358461-fcea2b1c-9dab-46e9-9acb-b6743653c9e1.png)

**Comment by SathyaJayabal** [comment]
@luizrrodrigues , remove this section only for public challenges and leave the wipro payment section for wipro ones.

**Comment by luizrrodrigues** [comment]
@SathyaJayabal Deployed to Stag and Dev env

**Comment by sandhiyakavi** [comment]
@luizrrodrigues If there is only Challenge Overview in the description section for a challenge, it's alignment is varying.

![image](https://user-images.githubusercontent.com/55895538/164604531-229ce6b2-8e6e-4619-883a-302c9e33fc3e.png)

Alignment in Prod Env,
![image](https://user-images.githubusercontent.com/55895538/164604607-08c53189-5ee7-4ad4-91c3-709ec5f4c76f.png)

**Comment by luizrrodrigues** [comment]
@sandhiyakavi Fixed.

**Comment by sandhiyakavi** [comment]
Verified in Staging Env. 

![image](https://user-images.githubusercontent.com/55895538/165017413-0c090e43-8639-45db-a1bd-636438dd7d61.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Payment section is removed.

![image](https://user-images.githubusercontent.com/55895538/165720036-007bf8b3-2c91-425a-912a-8e80a739761f.png)
