### ISSUE TITLE
Error message while trying to submit to the challenges.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/community-app#6293]
Description:

Getting error "Identifier 'reviewers' has already been declared" while trying to submit to the challenges. 
Sample users getting error: TCConncopilot, tester1234

Note: But the Admin is able to submit to the challenge without error. (TCConAdmin).

![image (4)](https://user-images.githubusercontent.com/55895538/162946138-24fb81ac-e222-49d0-9f69-634024631219.png)

**Comment by sandhiyakavi** [comment]
cc: @lakshmiathreya @SathyaJayabal

**Comment by SathyaJayabal** [comment]
its working now.
