### ISSUE TITLE
New TC logo on /community - Contentful

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#6297]
As per https://topcoder.atlassian.net/browse/MO-18?atlOrigin=eyJpIjoiZWVmNzdlZDJiNDQ1NDBkYmJmMGY4OWY0ZjFjMTliZGIiLCJwIjoiaiJ9

![image](https://user-images.githubusercontent.com/5585002/163778735-bef33c1e-25a6-478a-b47f-ccb8cf069a98.png)

**Comment by kkartunov** [comment]
@SathyaJayabal FYI

**Comment by sandhiyakavi** [comment]
@kkartunov In the Design (https://www.figma.com/file/jXE4RmI1mIG0fTP8uS2Jjk/Marketing-Site-Nav-%26-Footer?node-id=0%3A1) , the platform UI is also mentioned but I am not able to view the new Topcoder logo in the https://www.platform.topcoder.com. Is this not under this release?

![image](https://user-images.githubusercontent.com/55895538/163792959-f22529f6-e523-40bc-bc1d-ea53406e01f0.png)

Other than the above, the new logo is displaying in other pages,

1.  Header of community app

![image](https://user-images.githubusercontent.com/55895538/163793476-0e62593c-6475-4a86-9df7-83d927082a24.png)

2. Marketing nav header

![image](https://user-images.githubusercontent.com/55895538/163793576-682415ca-4145-42b6-bdda-8f9bc670e831.png)

3. Marketing footer.

![image](https://user-images.githubusercontent.com/55895538/163793652-8c00962e-ea7f-425f-b75d-6c94e1bcdea5.png)

4. Mobile pages

![image](https://user-images.githubusercontent.com/55895538/163793911-115168f4-8e55-46ce-9abf-e6b50eba410e.png)
![image](https://user-images.githubusercontent.com/55895538/163793970-47a21d9b-dda3-452a-b5e9-b0246218a135.png)
![image](https://user-images.githubusercontent.com/55895538/163794122-bbf17b2f-4a2e-4d6a-9863-b178d8b52127.png)

**Comment by SathyaJayabal** [comment]
@sandhiyakavi , only the community app  headers are in scope. Thanks

**Comment by SathyaJayabal** [comment]
verified on staging
<img width="1437" alt="Screenshot 2022-04-18 at 9 13 32 PM" src="https://user-images.githubusercontent.com/58783823/163834191-1249555a-f023-482f-89dd-75a1d41b9174.png">
<img width="1440" alt="Screenshot 2022-04-18 at 9 14 53 PM" src="https://user-images.githubusercontent.com/58783823/163834218-37932353-b7ae-4865-b9bc-adf2b55d459b.png">
<img width="502" alt="Screenshot 2022-04-18 at 9 15 02 PM" src="https://user-images.githubusercontent.com/58783823/163834221-fd5f53d5-70a5-429c-a5d3-0f2df6191b96.png">
<img width="497" alt="Screenshot 2022-04-18 at 9 15 19 PM" src="https://user-images.githubusercontent.com/58783823/163834223-9da93d17-5eb2-4d0e-8c39-554bf2e15c79.png">

**Comment by SathyaJayabal** [comment]
verified on prod
<img width="1437" alt="Screenshot 2022-04-19 at 8 42 57 AM" src="https://user-images.githubusercontent.com/58783823/163912989-b618152c-63a7-4733-baf9-a10766c4b27e.png">
<img width="487" alt="Screenshot 2022-04-19 at 8 43 10 AM" src="https://user-images.githubusercontent.com/58783823/163913004-fa44204b-8e32-4663-a375-a6f8036077e3.png">
<img width="1397" alt="Screenshot 2022-04-19 at 8 43 40 AM" src="https://user-images.githubusercontent.com/58783823/163913007-11806afd-dceb-47bf-9715-189582ae9ed8.png">
<img width="496" alt="Screenshot 2022-04-19 at 8 43 53 AM" src="https://user-images.githubusercontent.com/58783823/163913012-3e3c93be-930e-49fc-abc8-913ea9b1f039.png">
