### ISSUE TITLE
Show appropriate error message if member haven't access to private challenges

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#6311]
https://topcoder.atlassian.net/browse/PROD-1643

![image](https://user-images.githubusercontent.com/7029641/165224481-222695c2-db11-4648-a7b3-66b13ce84289.png)

![image](https://user-images.githubusercontent.com/7029641/165224492-49b74a0e-91ec-4de7-8e40-a5919613bc6c.png)

![image](https://user-images.githubusercontent.com/7029641/165224522-de7181ca-8de9-4095-8806-b5b87954fea9.png)

**Comment by luizrrodrigues** [comment]
@codejamtc Can you confirm if we'll keep default message (below of modal) and if this title looks good:

![image](https://user-images.githubusercontent.com/7029641/165265934-9bb28886-43b4-4676-b7af-728c1aedcfa5.png)

**Comment by codejamtc** [comment]
@luizrrodrigues I can see a typo: `available`

**Comment by luizrrodrigues** [comment]
@codejamtc Thanks, fixed.

Other questions is good?

**Comment by codejamtc** [comment]
@luizrrodrigues This is the message posted on JIRA

`“This challenge is only available to those in a private group. It looks like you do not have access to this challenge. If you believe you are receiving this message in error, please reach out to support.”`

**Comment by luizrrodrigues** [comment]
@codejamtc So we'll remove default message: 
```We are sorry that you have encountered this problem. Please, contact our support ‌[support@topcoder.com](mailto:support@topcoder.com)‌ to help us resolve it as soon as possible.``` 

I'm asking because this modal is a template to all msg error in CA, dynamic parts is just title and first line, msg above is fixed. Then if we going to remove I'll create a new template without this msg.

**Comment by codejamtc** [comment]
@lakshmiathreya Please check

**Comment by luizrrodrigues** [comment]
@codejamtc Deployed to Beta and QA env:
https://beta-community-app.topcoder.com/challenges/e61f19bd-5cef-4d6d-ae07-7011140fffeb

**Comment by codejamtc** [comment]
![bandicam 2022-04-26 20-59-00-285](https://user-images.githubusercontent.com/42398485/165337116-84339e96-27d0-4b94-9ee8-ffc586afab96.jpg)
![bandicam 2022-04-26 20-59-34-899](https://user-images.githubusercontent.com/42398485/165337124-495ecac8-47a8-40bf-9ca4-ee7db2fbf757.jpg)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/165493758-cd770779-fdbd-47b8-baaf-6410c0099b99.png)

**Comment by codejamtc** [comment]
Verified in Prod  :ok:
- https://www.topcoder.com/challenges/e61f19bd-5cef-4d6d-ae07-7011140fffeb

![bandicam 2022-04-28 14-36-00-623](https://user-images.githubusercontent.com/42398485/165718264-aeae3767-febd-4f8e-9492-920a5c2297bd.jpg)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/165718471-b85c7da8-3304-4f19-98b7-5f3d12f2242b.png)
