### ISSUE TITLE
Fix challenge link for marathon match in member statics page

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#6328]
Issue: https://topcoder.atlassian.net/browse/PROD-1599

Fix challenge link for marathon match in member statics page

**Comment by luizrrodrigues** [comment]
@morehappiness Creating the issue here because I haven't access to Jira ticket yet.

@SathyaJayabal @lakshmiathreya @codejamtc Hey someone can help with QA on this?

Thanks

**Comment by SathyaJayabal** [comment]
@luizrrodrigues this ticket is marked as qa pass on JIRA. @sdgun is the qa for this one.

**Comment by SathyaJayabal** [comment]
https://topcoder.atlassian.net/browse/PROD-1599?focusedCommentId=19282

**Comment by luizrrodrigues** [comment]
Thanks @SathyaJayabal 

@sdgun Can re check this on Stag env, have some code changes done today.

Thanks.

**Comment by sdgun** [comment]
@luizrrodrigues Earlier we saw the app redirecting to the legacy challenge when click on the tooltips of latest(>2019) MMs, but now we observe it opening up a non-existent challenge when clicking the tool tip of the challenges later than 2019 Jan:

![image](https://user-images.githubusercontent.com/4592712/167063905-de6307d7-9242-4853-9e60-913750d8c2a2.png)


https://user-images.githubusercontent.com/4592712/167064178-68e768ff-a29c-4621-9fb4-f554dd94af55.mp4

**Comment by luizrrodrigues** [comment]
@morehappiness ☝️

**Comment by SathyaJayabal** [comment]
verified on staging

https://user-images.githubusercontent.com/58783823/167597994-054486b3-27c9-47a0-8327-8ff137820936.mov

**Comment by sdgun** [comment]
Verified in production. 


https://user-images.githubusercontent.com/4592712/167608064-07f13a23-5bbb-46f0-960f-0a609ca32fc9.mp4
