### ISSUE TITLE
CircleCI - Deployment fail

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/community-app#6349]
We getting issues to run jobs on CircleCI to Community App project.
Looks like all deployments are falling now, inclusive previous success jobs before, if rerun will fail now.

--- 

Update; Response from CircleCI support team:
> Thanks for contacting CircleCI Support!
> NPM seems to have a bug that began around 5 days ago, affecting many builds: https://github.com/npm/cli/issues/4896
> Specifically, this part of it seems to have resolved for many people: https://github.com/npm/cli/issues/4896#issuecomment-1128472004
> Please take a look and let me know if you have any additional questions or information! Thank you and looking forward to your response.

**Comment by luizrrodrigues** [comment]
Following CircleCI support reply, implemented a solution to git use https:// instead git://

https://github.com/topcoder-platform/community-app/pull/6348

**Comment by SathyaJayabal** [comment]
Jobs are running successfully at present.
