### ISSUE TITLE
Fix social share custom image on Contentful

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#6356]
Custom social share images are not working and need fix.

Code produces invalid image URLs:

![image](https://user-images.githubusercontent.com/5585002/170274138-aa389279-dcd5-4126-8d69-7142d5f3dba9.png)

which results in bad social sharing behavior.

**Comment by sandhiyakavi** [comment]
@kkartunov From the description, this issue seems to be existing when we try to share a thrive article/videos to Facebook, Twitter or LinkedIn (sample: https://www.topcoder.com/thrive/articles/figma-skillbuilder-lessons). can you please confirm ?

Also the thrive articles page seems to be not working in Dev Env, loading for a long time

![image](https://user-images.githubusercontent.com/55895538/172119631-693e001e-7ea9-45ea-80a8-59a1d0e00ed2.png)

**Comment by kkartunov** [comment]
Hello @sandhiyakavi, please note:

- Scope of this is on /community pages. Thrive is excluded also this test/dev env issue is not to be handled here.
- QA URL is [this on BETA env](https://beta-community-app.topcoder.com/community/learn/figma) - have just re-doloyed it for QA
- You sould use [SocialSharePreview ](https://socialsharepreview.com/?url=https://beta-community-app.topcoder.com/community/learn/figma) or other service to verify the fix. The QA URL has custom social share image set, should be certificate one.

Let me know if you need any help...

**Comment by sandhiyakavi** [comment]
Thanks @kkartunov. Issue verified in Beta Env. Below are the images displayed in various social sites (Facebook, Twitter, LinkedIn).

![image](https://user-images.githubusercontent.com/55895538/172135553-59977d29-5962-4e74-8f39-f05e5e6b720c.png)
![image](https://user-images.githubusercontent.com/55895538/172135630-6c569f9a-7351-4746-a138-2352ea384b23.png)
![image](https://user-images.githubusercontent.com/55895538/172135677-51cf1dbe-b932-48da-a4e5-360171273346.png)

**Comment by sandhiyakavi** [comment]
Verified in Staging Env.

![image](https://user-images.githubusercontent.com/55895538/173540578-4340a935-4411-4a13-af59-70949d76b652.png)
![image](https://user-images.githubusercontent.com/55895538/173540639-d9771034-e067-499b-95fa-9b8a26c1a73c.png)
![image](https://user-images.githubusercontent.com/55895538/173540696-df58cb79-3328-41bb-8a96-5312fa49cd2a.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env.

![image](https://user-images.githubusercontent.com/55895538/173736446-fb54855e-5df9-4170-b4da-4bcda8318253.png)
![image](https://user-images.githubusercontent.com/55895538/173736464-e73b4805-f9bf-496b-89d0-d69a9c4c9b52.png)
![image](https://user-images.githubusercontent.com/55895538/173736489-81e3df3a-e822-4083-b24a-29e0b4c8905f.png)
