### ISSUE TITLE
Missing Web Application Headers for tco subdomain

### ISSUE THREAD

**Issue by eisbilir** [topcoder-platform/community-app#6362]
JIRA: https://topcoder.atlassian.net/browse/VULN-2487
https://topcoder.atlassian.net/browse/VULN-2478
https://topcoder.atlassian.net/browse/VULN-2485

**Comment by eisbilir** [comment]
#6358

**Comment by luizrrodrigues** [comment]
@eisbilir Deployed to Stag env

**Comment by codejamtc** [comment]
- https://topcoder.atlassian.net/browse/VULN-2487 - Web Application Headers [tco15.topcoder.com] - https://staging-community-app.topcoder.com/__community__/tco15
- https://topcoder.atlassian.net/browse/VULN-2478 - Web Application Headers [tco16.topcoder.com] - https://staging-community-app.topcoder.com/__community__/tco16
- https://topcoder.atlassian.net/browse/VULN-2485 - Web Application Headers [tco17.topcoder.com] - https://staging-community-app.topcoder.com/__community__/tco17

Fixed all

![bandicam 2022-05-27 09-07-42-422](https://user-images.githubusercontent.com/42398485/170625638-3f71ab64-2065-420a-9767-83de3c4d227e.jpg)
![bandicam 2022-05-27 09-10-37-331](https://user-images.githubusercontent.com/42398485/170625643-e90b6eff-a45e-4fa2-86ae-8346046e7390.jpg)
![bandicam 2022-05-27 09-11-40-377](https://user-images.githubusercontent.com/42398485/170625650-98e7419a-626e-47d0-8f88-6ec6c323a082.jpg)
