### ISSUE TITLE
TCO23

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#6376]
Topcoder Open 2023 website should be created as subcommunity in the scope of this ticket.
The new community URL: /\_\_community\_\_/tco23

https://topcoder.atlassian.net/browse/PROD-2128

**Comment by kkartunov** [comment]
This one is deployed on test and ready for QA.
 QA link: https://test-community-app.topcoder-dev.com/__community__/tco23
Scope:
- make sure page loads clone of tco22 site (without home page)
- home page should be
![image](https://user-images.githubusercontent.com/5585002/173387519-f5b6ff3b-f3ca-4113-9703-d15f2b3b1898.png)

**Comment by sandhiyakavi** [comment]
@kkartunov The header is looking different when compared to tco22 site. Is it expected?

![image](https://user-images.githubusercontent.com/55895538/173519239-793f88fc-4722-4ff9-97b0-278f3a07b0de.png)

tco22 site:

![image](https://user-images.githubusercontent.com/55895538/173519434-594031cd-0a45-4b50-9cd6-6a556e7901bf.png)

**Comment by sandhiyakavi** [comment]
Verified in Test Env.

![image](https://user-images.githubusercontent.com/55895538/173988498-9fa2d85f-1fda-48b1-8556-646a08f224e0.png)
![image](https://user-images.githubusercontent.com/55895538/173988517-9d99463a-78ec-4d1a-b76e-97d286b30095.png)
![image](https://user-images.githubusercontent.com/55895538/173988544-015f9197-d04e-4d87-af50-a27fb7326304.png)
![image](https://user-images.githubusercontent.com/55895538/173988565-d1d2a222-fa2c-4084-b058-5eb4c94f351a.png)
![image](https://user-images.githubusercontent.com/55895538/173988595-be1ef728-b7ac-4138-80c2-e2315e0ba0ab.png)

**Comment by sandhiyakavi** [comment]
@kkartunov I observed below issues in the tco23 site

1. Competition -> Algorithm -> Leaderboard is displaying a blank page.

<img width="960" alt="competition_algorithm_leaderboard" src="https://user-images.githubusercontent.com/55895538/175206009-776ac09a-6420-4b09-a26d-ee595ff8cfd9.png">

2. Competition -> Development ->Leaderboard is displaying blank page.

![image](https://user-images.githubusercontent.com/55895538/175206622-205553e5-6e16-4769-a7c3-a087b910e8c6.png)

3. Competition -> Win a trip -> Copilot Tournament is displaying a blank page.

<img width="960" alt="copilot_tournament" src="https://user-images.githubusercontent.com/55895538/175206772-d70befaa-9631-4f2c-8e33-c543e26d201a.png">

4. Also I can see some UI changes in some pages now. Is it expected?

<img width="960" alt="competition_changes" src="https://user-images.githubusercontent.com/55895538/175206852-3b3468c5-5b25-4435-89c5-91622d33dfe7.png">

**Comment by sandhiyakavi** [comment]
Verified in Staging Env. Issue is resolved.

![image](https://user-images.githubusercontent.com/55895538/175220369-306882cf-3e50-48a2-b88a-9fcdbc79210b.png)
![image](https://user-images.githubusercontent.com/55895538/175220417-bcae9d5d-7447-4999-83e9-505cf36fc970.png)
![image](https://user-images.githubusercontent.com/55895538/175220524-b1cfe38e-ba5c-4218-b7cd-9cca9d8400a3.png)

**Comment by sandhiyakavi** [comment]
Verified in Prod Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/175461270-d0ebffa2-4c19-46b8-a8fa-473e1d0c8d86.png)
![image](https://user-images.githubusercontent.com/55895538/175461300-465d301f-a657-41fa-b7db-e1ad7bd5c4c9.png)
![image](https://user-images.githubusercontent.com/55895538/175461318-4b4472b8-c9ce-4fd2-a9b4-de7711c05e08.png)
![image](https://user-images.githubusercontent.com/55895538/175461343-5626b622-378c-4a17-b300-28d84c6ad6a3.png)
