### ISSUE TITLE
Social Logos - Rotation  is not smooth 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#6392]
**Device:**  Laptop 
**Operating System:** Windows 10 
**Browser:**  Firerox 101.0.1 (64-bit) 

**To Reproduce**
pre req:login as user
1. Go to (https://www.topcoder.com/)
2. Click on 'community'
4. See logos

**Actual Result**
rotation is not smooth 

**Expected behavior**
rotation should be smooth 
**Bug Type:**  Functional 

**Testing collateral**

https://user-images.githubusercontent.com/3225433/175193302-c9bf58e7-44bf-4207-9ffa-33c5e1040da7.mp4

**Comment by ClintonBon24** [comment]
I don't see a problem with the example @drasticdpk - do you?
