### ISSUE TITLE
Join Topcoder  button displayed for  logged in

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/community-app#6393]
**Device:**  Laptop 
**Operating System:** Windows 10 
**Browser:**  Firerox 101.0.1 (64-bit) 

**To Reproduce**
pre req: login as user 
1. Go to (https://www.topcoder.com/)
2. Click on Community 
3. See Join Topcoder 

**Actual Result**

Join Topcoder  button is available for logged in user 

**Expected behavior**
if user logged in Should not show Join Topcoder  button  
**Bug Type:**  Functional 

**Testing collateral**

![bandicam 2022-06-23 07-56-39-010](https://user-images.githubusercontent.com/3225433/175193976-722eed7c-43ea-4a5f-99f8-3e98c2d21442.jpg)

**Comment by ClintonBon24** [comment]
Not a bug. The expectation is that a logged in user will never come here. This is fine. @drasticdpk
