### ISSUE TITLE
[Web-Chrome] After logged in it's not showing as https://www.topcoder.com/home

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#6395]
**Describe the bug**
After logged in it's not showing as https://www.topcoder.com/home

**To Reproduce**
1. Go to 'www.topcoder.com'
2. Click on 'LOG IN'
3. Fill details then click Log In
4. Click back Then observe top right & URL to be written line then observe.
5. Actual Result:- After logged in it's not showing as https://www.topcoder.com/home
6. Expected Result:- After logged in it should show as https://www.topcoder.com/home
7. Bug Type:- Functional
8. See Screenshot & Screencast:-
![BUG 1](https://user-images.githubusercontent.com/42583358/175194950-5b3370ec-1cc3-4df6-99ff-cb6a3d93bca4.png)
https://user-images.githubusercontent.com/42583358/175195007-02a48168-e190-43b7-883f-1a57171d90cc.mp4

**Desktop (please complete the following information):**
 - OS: 
![Mac VERSION](https://user-images.githubusercontent.com/42583358/175195121-93a6d5bc-f490-4398-b7e3-964616bc0bfd.png)

 - Browser:- 
![CHROME VERSION](https://user-images.githubusercontent.com/42583358/175195213-5472cb3f-0396-4fc5-b05c-bbbb20650177.png)

 - Device: Laptop
 
Label:- "Bug-hunt-June22"

**Comment by devsreekrishna** [comment]
Hi 
At least you should mention reason for closing to do better in next challenge.
Thanks

**Comment by drasticdpk** [comment]
This is an invalid issue. No need to show home for the home/index page.
