### ISSUE TITLE
[Web] User Name is appearing twice 

### ISSUE THREAD

**Issue by mmmengg-dev** [topcoder-platform/community-app#6396]
Device: Laptop
Operating System: Windows8.1
Browser: Version 97.0.4692.99 (Official Build) (64-bit)

Steps to reproduce:
1. Logon to https://www.topcoder.com/
2. On home page click on "JOIN TOPCODER"
3. User will be redirected to - https://platform.topcoder.com/onboard
4. Notice user name is visible twice

Actual result: 
user name is visible twice

Expected results: 
User Name should be visible once

Bug Type: UX
![browser_info](https://user-images.githubusercontent.com/68599579/175195084-64d8d87e-025a-46b6-9d30-08328819e540.jpg)

![Device_info](https://user-images.githubusercontent.com/68599579/175195111-b2524cae-550d-4476-9c0f-4c49915752b3.jpg)

![image](https://user-images.githubusercontent.com/68599579/175195119-5b119770-07ed-4333-8f0b-d1cc42cea0c1.png)

**Comment by mmmengg-dev** [comment]
Bug-hunt-June22

**Comment by drasticdpk** [comment]
Its , first name last name then handle
