### ISSUE TITLE
Sign up validation goes without proper input

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6397]
Issue Title : Sign up validation goes without proper input

Device: Laptop

Operating System: Windows 11

Browser: Chrome

Steps to reproduce: 
Step 1: Go to Topcoder.com and navigate to sign up
Step 2: Click the Sign up button and check validation fields
Step 3 : enter one character removed the validation error even it is not a correct input

Actual result: Even after  the wrong input the validation error disappear
Expected results: validation should be there till we input the correct input 

Bug Type: Functional issue

Testing collateral: 
![chrome version](https://user-images.githubusercontent.com/98445449/175195471-82a97a23-30c6-4d97-a5a2-dcf4fc02789f.jpg)
![device info](https://user-images.githubusercontent.com/98445449/175195477-bb09d1a8-8aec-4071-b31f-4882641a6233.jpg)

https://user-images.githubusercontent.com/98445449/175195518-19b53f04-267e-4a2d-aaf1-bff522eafd92.mp4

Label :Bug-hunt-June22

**Comment by radhamrutham** [comment]
@drasticdpk I can see other bugs accepted in the same page. Why this bug is not acceptable?

**Comment by drasticdpk** [comment]
This is out of scope for now.
