### ISSUE TITLE
[$50] - Communities server-side service: no need to read from disk on each request

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#640]
We can read at start-up and serve from memory. A bit less convenient for local dev, but better performance for prod deployment.

The problem to fix is here: https://github.com/topcoder-platform/community-app/blob/develop/src/server/services/communities.js#L73

**Comment by imadx** [comment]
added a PR to this issue: https://github.com/topcoder-platform/community-app/pull/701

**Comment by imadx** [comment]
@birdofpreyru  updated the PR with the async file reads, according to your suggestion... https://github.com/topcoder-platform/community-app/pull/701

**Comment by birdofpreyru** [comment]
@imadx Updated PR was functionally good enough to merge into the codebase, but I still want a bit more changes to make the code cleaner. I don't totally like your `groomMetadata` function, because you pass in `resolve`, which is confusing (to understand what is going on, somebody will have to track from which promise it originates); and also `groupsService`, which you cood just access as `this.private.groupsService` whould you do `groomMetadatada(..)` a private `this.private.groomMetadata(..)` method of the class instead. But, you don't even need to separate it into a dedicated function, if you do proper promise chaining. Now you have:

```
this.private.getMetadata = (communityId, knownGroups = {}) =>
  new Promise((resolve, reject) => {
    ...
    if (..) {
      ...
      groomMetadata(..);
    } else {
      ...
      fs.readFile(uri, 'utf8', (err, res) => {
        ...
        return groomMetadata(..);
      });
    }
  });
```

You better do:
```
this.private.getMetadata = (communityId, knownGroups = {}) => {
  const promise = new Promise((resolve, reject) => {
    ...
    if (...) {
      ...
      resolve(metadata); // These are non-groomed metadata
    } else {
      fs.readFile(uri, 'utf8', (err, res) => {
        if (err) {
          ...
          reject(...);
        }
        ...
        resolve(metadata); // These are non-groomed metadata
      });
    }
  });
  return promise.then((metadata) => {
    ... // Do the groomming here
    return metadata; // These are groomed metadata.
  });
};
```

Or you can keep the grooming code as a private method `this.private.groomMetadata(metadata, knownGroups)`; and then use it in the promise chaining doing in the end.

```
return promise.then(metadata => this.private.groomMetadata(metatada, knownGroups));
```
this is probably, the most clean option.

So, please do this, and will close the issue.

**Comment by imadx** [comment]
@birdofpreyru, Made the necessary changes... https://github.com/topcoder-platform/community-app/pull/732
