### ISSUE TITLE
[$50] - Challenge details header: standard buttons styling

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#641]
The challenge details header uses `<ThemeProvider>` to style the buttons within it, hence when the entire component is mounted inside a sub-community, those buttons do not pick-up the proper context theme from the community. This should be fixed.

**Comment by birdofpreyru** [comment]
Expected fix: remove that `<ThemeProvider>` and clean-up any related code not used anymore. In the result, the buttons in the challenge specs header should pick up their styles from the context theme defined for the page elsewhere, if any, or just fallback to defaults. For the challenge details at the main site it means they will stay unchanged; while for many sub-communities they will match their styles with the default button styles of those communities.

**Comment by imadx** [comment]
Added PR https://github.com/topcoder-platform/community-app/pull/699 with the ThemeProvider and related code removed
