### ISSUE TITLE
[MacOS] Book a demo choice feature is not available

### ISSUE THREAD

**Issue by sudhamoorthi** [topcoder-platform/community-app#6411]
**Describe the bug**
As per the requirement document 
Book a Demo should:
Take a User to Sales Landing Page 
**The “Book a Demo” choice should pre-populate a section of the form where a user could choose to book a demo from an available pick-list**

**To Reproduce**
1. Go to https://www.topcoder.com/
2. Click on 'Book a Demo' button in the top navigation bar
3. Navigates to 'User to Sales Landing Page '
4. There is no pre-populated section of the form 

**Expected behavior**
As per the requirement, there should be a prepopulated section to choose 

**Screenshots**
<img width="1350" alt="Screenshot 2022-06-23 at 8 43 50 AM" src="https://user-images.githubusercontent.com/203884/175199522-3e815611-d899-442d-aff2-696bcda8152a.png">

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser [chrome ]
 - Version 102.0.5005.115 (Official Build) (x86_64)

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/community-app/issues/6410
