### ISSUE TITLE
Web: Both popup and page navigation is doing in lets talk click

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6417]
Issue Title : Web: Both popup and page navigation is doing in lets talk click

Device: Laptop

Operating System: Windows 11

Browser: Chrome

Steps to reproduce: 
Step 1: Go to topcoder.com
Step 2: Scroll down and go to QA & TESTING
Step 3: click learn more button in QA
Step 4: Scroll down
Step 5: Go to GET STARTED WITH QUALITY ASSURANCE AT TOPCODER
Step 6: Slide - Click  Manual regression 
Step 7: We can see both the popup and the navigation page of lets talk 

Actual result: Both pop up and navigation page is coming in lets talk click

Expected results: navigate to the lets talk page

Bug Type: Functional issue

Testing collateral: 
![chrome version](https://user-images.githubusercontent.com/98445449/175201978-3ac5cd86-b007-46fc-808c-d6454af73c6d.jpg)
![device info](https://user-images.githubusercontent.com/98445449/175202020-14518707-2888-411c-ae05-417b7811e961.jpg)

https://user-images.githubusercontent.com/98445449/175203349-949eb3c8-e1db-4092-8f82-25fda6bb9db7.mp4

Label : Bug-hunt-June22

**Comment by radhamrutham** [comment]
@drasticdpk May I know why this is not a valid issue

**Comment by drasticdpk** [comment]
@radhamrutham, we are doing AB Testing, this is expected

**Comment by radhamrutham** [comment]
@drasticdpk Either of the one form is expected right. Here both forms are coming together

**Comment by drasticdpk** [comment]
@radhamrutham  this time I am unable to replicate the popup scenario.

**Comment by radhamrutham** [comment]
@drasticdpk  Ys but at the testing period the issue was there. Please refer the video.
