### ISSUE TITLE
Blank space is present in the case study 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6422]
**Describe the bug**
Blank space is present in the case study 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on Enterprise
3. click on View case study 
4. click on Crowd testing & QA
5. observe

**Expected behavior**
Blank space should be removed or should have some elements to display 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 103.0.5060.53

https://user-images.githubusercontent.com/96585505/175203823-6d49d655-077c-44eb-ac06-6631bfcdc56b.mp4

**Comment by drasticdpk** [comment]
this is out of scope different app
