### ISSUE TITLE
Web: Logos are not rotating in lets talk page

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6425]
Issue Title : Web: Social Logos are not rotating in lets talk page

Device: Laptop

Operating System: Windows 11

Browser: Chrome

Steps to reproduce: 
Step 1: Go to topcoder.com
Step 2: scroll down and click lets talk
Step 3: Scroll down
Step 4: In TRUSTED BY icons are not rotating 

Actual result: Logos are not rotating in lets talk page

Expected results: Logos Should rotate in lets talk page

Bug Type: Functional issue

Testing collateral: 
![chrome version](https://user-images.githubusercontent.com/98445449/175201978-3ac5cd86-b007-46fc-808c-d6454af73c6d.jpg)
![device info](https://user-images.githubusercontent.com/98445449/175202020-14518707-2888-411c-ae05-417b7811e961.jpg)

https://user-images.githubusercontent.com/98445449/175205000-d6b3ee2b-6110-4975-9aa0-57636daae266.mp4

Label :Bug-hunt-June22

**Comment by radhamrutham** [comment]
@drasticdpk  Please see the requirement shared below. Logos need to rotate as per requirement
https://user-images.githubusercontent.com/98445449/175499042-1cd7c6b2-8d26-451b-91df-6e3aacc61784.png

**Comment by radhamrutham** [comment]
@drasticdpk can you please respond

**Comment by ClintonBon24** [comment]
Not a bug. Landing pages are hosted on Unbounce and that functionality was not coded into this experience @drasticdpk
