### ISSUE TITLE
web dropdown heading not showing in "Book a demo" form

### ISSUE THREAD

**Issue by shivam-51** [topcoder-platform/community-app#6426]
**Describe the bug**
in the Book a demo page check the "Let's talk" form, the heading for the first dropdown is clear(`Your role`) but the one below is is blank

**To Reproduce**
1. Go to 'www.topcoder.com'
2. Click on 'Book a demo' button at the top
3. Check the "Let's talk" form
4. There is no heading in the 2nd dropdown

**Expected behavior**
The dropdown should show an heading of "What are you interested in" by default.

**Screenshots**
<img width="1440" alt="Screenshot 2022-06-23 at 9 20 43 AM" src="https://user-images.githubusercontent.com/47945055/175205311-0e922ac5-1cce-4693-99bd-4cde4cddc7d8.png">

Desktop (please complete the following information):

Device: [e.g. macbook pro intel chip]
OS: [e.g. macOS Monterey v12.1]
Browser [Google Chrome]
Version [93.0.4577.63 (Official Build) (x86_64)]

**Comment by shivam-51** [comment]
bug type: UI

**Comment by shivam-51** [comment]
in the `Desktop` details please ignore the e.g, I have added my device details but did not remove the e.g tag.

**Comment by shivam-51** [comment]
Please ignore the `e.g` in desktop description:

Device:  macbook pro intel chip
OS: macOS Monterey v12.1
Browser: Google Chrome
Version: 93.0.4577.63 (Official Build) (x86_64)

**Comment by drasticdpk** [comment]
duplicate
