### ISSUE TITLE
Web : Logos are not in black color 

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6429]
Issue Title : Logos are not in black color 

Device: Laptop

Operating System: Windows 11

Browser: Chrome

Steps to reproduce: 
Step 1: Goto topcoder.com
Step 2: Click get Wok Done button
Step 3: scroll down 
Step4: Logos are not in black color 

Actual result: Logos are not in black color 

Expected results: All logos should be black and white (gray) and no color(As per Doc)

Bug Type: UI issue

Testing collateral: 
![chrome version](https://user-images.githubusercontent.com/98445449/175201978-3ac5cd86-b007-46fc-808c-d6454af73c6d.jpg)
![device info](https://user-images.githubusercontent.com/98445449/175202020-14518707-2888-411c-ae05-417b7811e961.jpg)

https://user-images.githubusercontent.com/98445449/175206298-9f3484bb-30b0-4972-808c-337f09cf5acb.mp4

Label :Bug-hunt-June22

**Comment by radhamrutham** [comment]
@drasticdpk Please see the requirement shared below. 

![image](https://user-images.githubusercontent.com/98445449/175499042-1cd7c6b2-8d26-451b-91df-6e3aacc61784.png)

**Comment by drasticdpk** [comment]
Not able to reproduce 

![image](https://user-images.githubusercontent.com/25297859/175504234-f2991e08-7295-4cf2-ae2a-2206d0d302d0.png)

**Comment by drasticdpk** [comment]
![image](https://user-images.githubusercontent.com/25297859/175504970-117c7f52-a390-4735-9e47-ef4255ee3b81.png)

**Comment by radhamrutham** [comment]
@drasticdpk  I think there are changes in the current version. But at the testing period it was another page as you can see the video for the reference. 

The logos was like https://go.topcoder.com/book-a-demo/?ref=nav

**Comment by radhamrutham** [comment]
@drasticdpk can you please respond

**Comment by drasticdpk** [comment]
Will consider payment for those issues. 
Thank you
