### ISSUE TITLE
[Desktop PC] Two diferent Forms to Book a Demo 

### ISSUE THREAD

**Issue by jcampos1981** [topcoder-platform/community-app#6439]
**Issue Title**
Two Forms to Book a Demo 

Device
Desktop PC

Operating System
Windows 10

Browser
Mozilla Firefox

Steps to reproduce

-     Open https://www.topcoder.com/

-     Click on Book a Demo button on the menu, and observe the required form fields.
-     Go back to https://www.topcoder.com/ and click on Resources -> Book a Demo menu and observe the required form fields.

    **Actual result**

-     Exists two different forms used to book a demo for example Company Size field is present in one but not in the other. Field Order is different. **Use Case** and **What Are you Interested In** differ in options quantity, etc.

    Expected results

    Should use a unique Book a Demo form

    Bug Type
    Functional

    Testing collateral
![demo1](https://user-images.githubusercontent.com/9984952/175208055-703e7b9c-0720-49a3-8ff9-626cef09ace6.JPG)
![demo2](https://user-images.githubusercontent.com/9984952/175208071-d660d6b4-f1b2-4cfa-a3a1-c973f174a744.JPG)

**Comment by drasticdpk** [comment]
this is due to AB Testing or not, please confirm.

**Comment by ClintonBon24** [comment]
this is resolved @drasticdpk
