### ISSUE TITLE
[iphone ] Not able to close the release and update dropdown clicking from outside 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6451]
**Describe the bug**
when user tries to enter some input to the field the Release and update  page is zoomed

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on resources 
3. click on releases & update 
4. click on input field in releases 
5. click outside to close the dropdown 
6. click on icon present in dropdown to close options 

**Expected behavior**
user should able to close the dropdown options 

**Screenshots**

https://user-images.githubusercontent.com/96585505/175211990-c32b4417-c639-4e3b-9b65-8ca9e50a22fd.mp4

**Mobile (please complete the following information):**
 - OS: Iphone 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
N/A
