### ISSUE TITLE
[web] inconsistent use of full stop in the menu bar option's descriptions.

### ISSUE THREAD

**Issue by shivam-51** [topcoder-platform/community-app#6453]
**Describe the bug**
Some entries in the menu bar ends with a full stop(like Data Science, Web Development under `About`) while some do not(like Security under the same tab `About`).

**To Reproduce**
1. Go to www.topcoder.com
2. Click on About in the menu bar
3. Notice that the descriptions of some categories like `Data Science`, `Web Development` ends with a full stop, while for some like `Security` does not.

**Expected behavior**
Either all of the descriptions should end with full stop, or none should.

**Screenshots**
<img width="1440" alt="Screenshot 2022-06-23 at 10 18 14 AM" src="https://user-images.githubusercontent.com/47945055/175213561-aa0c4e0d-e4de-4f9f-b365-112367abe1c2.png">

**Desktop (please complete the following information):**
Device: macbook pro intel chip]
OS: macOS Monterey v12.1
Browser: Google Chrome
Version: [93.0.4577.63 (Official Build) (x86_64)]

**Comment by ClintonBon24** [comment]
This is already fixed. @drasticdpk
