### ISSUE TITLE
[$150] - Update NodeJS and dependencies

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#646]
Current LTS NodeJS is `8.9.2`, we still use `8.2.1` - should be upgraded.
Also a bunch of other dependencies should be carefully updated again.

**Comment by birdofpreyru** [comment]
NodeJS and a bunch of dependencies are updated in 6048906019deda79a26f1ad4a294a49f86e54c90, however the linters update will demand more efforts (lots of code style fixes should be done manually),

**Comment by birdofpreyru** [comment]
Current NodeJS LTS is `8.9.4`, so we can upgrade again, but we should beware of some difference in the behavior (at least in some snapshot test, check the comment in c417a80993e605e8643ec0926cafd4192182d1ef).

**Comment by birdofpreyru** [comment]
### Expected Fix:
Update NodeJS version and all dependencies to the latest versions, ensure that it does not break anything in our codebase, and in case of any issues, properly resolve them.

**Comment by tejaram15** [comment]
I am new to this community and i have submitted my PR as follows. #714 #715 #716

**Comment by arun1595** [comment]
@birdofpreyru I had a shot at updating node and the dependencies. As expected, some tests failed but I noticed something strange. Upon updating the snapshots, the `JoinCommunity.jsx.snap` turned out to be really huge(139MB). Could you please shed some light on why this might be the case?

Thanks!

**Comment by birdofpreyru** [comment]
@arun1595 wow, this is weird; and it is part of the issue to figure this out and fix it. I guess, it is something in the test code leads to an incorrect rendering for snapshots with the updated Node.

**Comment by arun1595** [comment]
@birdofpreyru Yeah, looks like it. Will try to figure it out :)

**Comment by birdofpreyru** [comment]
@tejaram15 first of all, the fix should be a single PR (and you can commit multiple commits into the same branch, to add them into the same PR). Second, you don't update npm dependencies, which was part of the task, and I also guess you don't resolve any issue related with Node version update, that I believe might be there.

**Comment by arun1595** [comment]
@birdofpreyru I am bit stuck at the issue we talked about yesterday. It would be awesome if you could help me out get unstuck. 

Thanks!

**Comment by birdofpreyru** [comment]
@arun1595 I honestly have no idea what happens there. I can sit and figure it out, but then I'll basically end up making the update myself; cause it is the main problem of the dependencies update: to figure out why something is broken by updated dependencies and finding how to fix it.

**Comment by KevinLeigh** [comment]
@birdofpreyru Hey there, I will start working on this issue now, currently I cannot assign it to myself as it seems I am not authorised to, while I work on issue please could you post the link the I need to use to authorise myself to pick up issue or assign ticket to me. Much appreciated

**Comment by birdofpreyru** [comment]
Hey, @KevinLeigh , I believe, it is actually not a part of the ongoing bug bash: this is an old issue, that was a part of some bug bush long time ago, and just was not closed properly. Sorry about the confusion.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069369 has been created for this ticket.

**Comment by KevinLeigh** [comment]
Thank you @birdofpreyru for the update, much appreciated. @ThomasKranitsas I will upgrade dependencies for free, no cash and only for a skills endorsement on LinkedIn, is that okay?

**Comment by ThomasKranitsas** [comment]
@KevinLeigh I'm not sure if we really need that. Upgrading the dependencies can be tricky and will require a lot of investigation to make sure we don't break anything.

And definitely, there's no need to do any free work ;)
There will be other tickets to work on. I'll let you know

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Cool thank you so much Thomas, will be ready when there is an update on some new tickets. Also I really do not mind putting in the effort for any kind of development :). Here is my LinkedIn profile -> https://www.linkedin.com/in/kevin-leigh-crain-414769101/

**Comment by ThomasKranitsas** [comment]
@KevinLeigh fyi https://github.com/topcoder-platform/community-app/issues/986 this is now open for pickup

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you Thomas, please could you assign the issue to me? because for some reason I cannot assign the issue.
