### ISSUE TITLE
[Web] Dead link provided at Terms and Conditions page

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/community-app#6462]
**Describe the bug**
Outdated link in Terms and Conditions page under Accounts; Passwords; Security

**To Reproduce**
1. Go to https://www.topcoder.com/community/how-it-works/terms/  
2. Under Accounts; Passwords; Security, see and click the provided link

**Expected behavior**
Provided link should be updated and direct to a live page

**Screenshots**
![dead link](https://user-images.githubusercontent.com/1199534/175220750-1f856508-cf87-40a0-9f54-c0e1e72936f1.png)

**Desktop (please complete the following information):**
- Device: Desktop
- OS: Windows 10 Pro version 21H2 build 19044.1766
- Browser: 
  - Chrome 103.0.5060.53
  - Firefox 101.0.1
  - Microsoft Edge 102.0.1245.44

**Additional context**

**Comment by drasticdpk** [comment]
out of scope
