### ISSUE TITLE
[Web] Topcoder spelled as "topocder"

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/community-app#6463]
**Describe the bug**
Outdated link in Terms and Conditions page under Accounts; Passwords; Security

**To Reproduce**
1. Go to https://www.topcoder.com/community/how-it-works/terms/  
2. Under Accounts; Passwords; Security, read the second paragraph, second to the last sentence

**Expected behavior**
Should be spelled as "topcoder"

**Screenshots**
![image](https://user-images.githubusercontent.com/1199534/175221104-de68f819-38f2-4d71-8f2d-fed150ba567c.png)

**Desktop:**
- Device: Desktop
- OS: Windows 10 Pro version 21H2 build 19044.1766
- Browser: 
  - Chrome 103.0.5060.53
  - Firefox 101.0.1
  - Microsoft Edge 102.0.1245.44

**Additional context**

**Comment by ClintonBon24** [comment]
Unsure if you can change this page @jamesmarquez or if this is Kiril or other? Plz let us know.

**Comment by jamesmarquez** [comment]
@ClintonBon24 this is Kiril

**Comment by kkartunov** [comment]
fixed
![Screenshot from 2022-06-29 18-21-00](https://user-images.githubusercontent.com/5585002/176474089-219be1ee-ce4d-4a76-ae4e-372c16291fbe.png)
