### ISSUE TITLE
Iphone Horizontal scroll is overlapping the options 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6466]
**Describe the bug**
Horizontal scroll is overlapping the options 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on menu 
3. click on resources 
4. click on blog 
5. scroll down
6. slide the horizontal scroll 

**Expected behavior**
scrollbar should not overlap the options in list 

**Screenshots**

https://user-images.githubusercontent.com/96585505/175221870-dbb40695-97fe-464b-bbe2-cad636a4dc1d.mp4

**Desktop (please complete the following information):**
 - OS: iphone 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
out of scope.
