### ISSUE TITLE
Iphone All blog post user click on the dropdown options page is zoomed up 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6468]
**Describe the bug**
user click on the dropdown options page is zoomed up 
**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on menu 
3. click on resources 
4. click on blog 
5. scroll down
6. click on view all post 
7. click on popular topics and sort by dropdown 

**Expected behavior**
page should not zoom in when the dropdown is expanded 

**Screenshots**

https://user-images.githubusercontent.com/96585505/175222478-30b26ad0-0ec4-454b-8f7e-64b17ca62883.mp4

**Desktop (please complete the following information):**
 - OS: iphone 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
Out of scope.
