### ISSUE TITLE
Iphone Release and update icon is not change when dropdown is expanded 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6472]
**Describe the bug**
icon is not changed on expanded dropdown 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on menu 
3. click on resources 
4. click on blog 
5. scroll down
6. slide the horizontal scroll 

**Expected behavior**
icon should be changed once the field is expanded eg 
![2](https://user-images.githubusercontent.com/96585505/175223200-b5e0e88a-9ab1-4168-abb7-06f1f9e74d75.jpeg)

**Screenshots**
![1](https://user-images.githubusercontent.com/96585505/175223170-e6069bbb-79b4-4397-a569-45157d4c3967.jpeg)

**Desktop (please complete the following information):**
 - OS: iphone 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
out of scope.
