### ISSUE TITLE
[ios] There is spelling mistake under 'Book a demo' page

### ISSUE THREAD

**Issue by sudhamoorthi** [topcoder-platform/community-app#6473]
**Describe the bug**
In iPhoneXR, Book a demo has a spelling mistake

**To Reproduce**

1. Go to https://www.topcoder.com/
2. Tap on the Menu icon
3. Tap on Book a Demo option
4. **There is a spelling mistake for WE THOUGHT _YA_ MIGHT**

**Expected behavior**
It should be  **WE THOUGHT _YOU_ MIGHT**

**Screenshots**
![Screen Shot 2022-06-23 at 11 11 16 AM](https://user-images.githubusercontent.com/203884/175223637-75e82ea3-27ff-478d-8e9b-f3b3f466f472.png)

**Smartphone (please complete the following information):**
	•	Device: [iphoneXR]
	•	OS: [e.g. iOS15.1]
	•	Browser [Chrome]
	•	Version 96.0.4664.53

**Comment by drasticdpk** [comment]
Developer Note: For now I am accepting this bug, please close if this is expected.

**Comment by ClintonBon24** [comment]
this is expected @drasticdpk - using slang on purpose
