### ISSUE TITLE
[Web] Topcoder logo not redirecting to topcoder page in when clicked.

### ISSUE THREAD

**Issue by hasinamahamootha** [topcoder-platform/community-app#6476]
**Describe the bug**
'Topcoder-A wipro company' logo not redirecting to topcoder(topcoder.com) page in when clicked in 'Topcoder talk to sales page'.

**To Reproduce**
1. Go to 'https://topcoder.com/'
2. Click on 'Book a demo' button on top.
3. click on the' topcoder- a wipro company' logo on the top left'
4. The logo not clickable and not redirecting to the topcoder.com page

**Expected behavior**
The logo should be clickable and should redirect to the topcoder.com page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

https://user-images.githubusercontent.com/25719514/175225787-64452adf-b92a-4bb7-b506-b31b4add048f.mp4

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/community-app/issues/6401
