### ISSUE TITLE
Payments App: Payments tab is showing white screen

### ISSUE THREAD

**Issue by kbowerma** [topcoder-platform/community-app#648]
I think this is a browser issue,   I will reload my browser in a bit but tony asked me to add this

https://github.com/topcoder-platform/community-app/issues
![image](https://user-images.githubusercontent.com/1180747/33773011-2c8e0ccc-dbfc-11e7-85c0-f7f8aa67c382.png)

```
main.js:20 Uncaught (in promise) Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (main.js:20)
    at st (main.js:20)
    at m (main.js:20)
    at _ (main.js:20)
    at main.js:20
    at s (main.js:20)
    at i (main.js:20)
    at beginWork (main.js:20)
    at a (main.js:20)
    at i (main.js:20)
```

**Comment by kbowerma** [comment]
Lazybaer is getting this too and I added mtwomey to this project (https://www.topcoder.com/direct/projectOverview?formData.projectId=11109)  and he is getting the white screen.   This project has no billing account but is active.

**Comment by kbowerma** [comment]
Special thanks to @mtwomey  who realized that the project above had a space in the name, that was killing the response.

**Comment by birdofpreyru** [comment]
@kbowerma is it related to Community App? I am not following, which payments tab are you talking about?

**Comment by kbowerma** [comment]
yes,  the payment app.

**Comment by birdofpreyru** [comment]
ah, ok, got it now: indeed, fails only on selected projects.

**Comment by cwdcwd** [comment]
@kbowerma pls retest

**Comment by kbowerma** [comment]
Yup seems to be fixed
