### ISSUE TITLE
[Web] The sign up button is available to click even if the terms check box is alone clicked

### ISSUE THREAD

**Issue by hasinamahamootha** [topcoder-platform/community-app#6481]
**Describe the bug**
The sign up button in the join topcoder page turns green and is available to click even if the terms and privacy check box is alone checked.

To Reproduce

Go to 'https://topcoder.com/'
Click on 'Join the community' button on top right.
check the privacy and terms box below.
The sign up button turns green and is now clickable.

Expected behavior
The sign up button should not turn clickable and it should be available to click only if all the boxes are filled.
![bug2- sign up box](https://user-images.githubusercontent.com/25719514/175227137-61ea87ba-2423-4119-a959-4d467f6a2c57.PNG)

Screenshots

Desktop (please complete the following information):

OS: [Windows 10]
Browser [Chrome]

**Comment by drasticdpk** [comment]
Expected.
