### ISSUE TITLE
Web :All Let’s Talk  not going to  Sales Landing Pages 

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6482]
Issue Title : All Let’s Talk  not going to  Sales Landing Pages 

Device: Laptop

Operating System: Windows 11

Browser: Chrome

Steps to reproduce: 
Step 1: Goto topcoder.com 
Step2: scroll down click DATA SCIENCE
Step 3: Scroll down click Find me data
Step : All lets talk button is not landing to sales page 

Actual result: All lets talk button is not landing to sales page 

Expected results: All lets talk button is Should land to sales page

Bug Type: Functional issue

Testing collateral: 
![chrome version](https://user-images.githubusercontent.com/98445449/175201978-3ac5cd86-b007-46fc-808c-d6454af73c6d.jpg)
![device info](https://user-images.githubusercontent.com/98445449/175202020-14518707-2888-411c-ae05-417b7811e961.jpg)

https://user-images.githubusercontent.com/98445449/175227784-e95a6633-65e0-42df-bf8e-99c5da2d3442.mp4

![2](https://user-images.githubusercontent.com/98445449/175227853-8422844a-04e5-44cf-b932-fe536df40a24.jpg)

label - Bug-hunt-June22

**Comment by ClintonBon24** [comment]
this is already fixed @drasticdpk
