### ISSUE TITLE
From talent placement lets talk what are you interested in dropdown is not auto populate 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6488]
**Describe the bug**
Mandatory form field for FORRESTER REPORT do not have asterisk sign 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on enterprise 
3. click on BFSI
4. scroll down click on view engagement model 
5. click on PROJECTS & PROFESSIONAL SERVICES 
6. go back and click on Talent placement 

**Expected behavior**
talent placement should be auto populated 

**Screenshots**

https://user-images.githubusercontent.com/96585505/175231591-64899e03-f8f3-44fc-bf7f-4e237228ecb2.mp4

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/community-app/issues/6400
