### ISSUE TITLE
Web : The username in signup section appear in the login tab also 

### ISSUE THREAD

**Issue by radhamrutham** [topcoder-platform/community-app#6501]
Issue Title : Web : The username in signup section copied  to login username

Device: Laptop

Operating System: Windows 11

Browser: Chrome

Steps to reproduce: 
Step 1: Go to topcoder.com
Step 2: Click join in topcoder button
Step 3. enter the username name in sign up tab 
Step4: Switch the tab to sign in we can see the username entered there

Actual result: In signin / signup tab after entering username it copied to username of next tab

Expected results: Username name should not copy to next tab value

Bug Type: Functional issue

Testing collateral: 
![chrome version](https://user-images.githubusercontent.com/98445449/175201978-3ac5cd86-b007-46fc-808c-d6454af73c6d.jpg)
![device info](https://user-images.githubusercontent.com/98445449/175202020-14518707-2888-411c-ae05-417b7811e961.jpg)

https://user-images.githubusercontent.com/98445449/175239728-d9bde1c3-6644-4896-b970-4a9cd91ed37e.mp4

label - Bug-hunt-June22

**Comment by drasticdpk** [comment]
Known issue.
