### ISSUE TITLE
Iphone Trusted by client logo are not changing some logo are overlapping 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6502]
**Describe the bug**
client logo are over lapping and the logo are not changing 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on menu 
3. click on the community 
4. scroll to trusted by 
5. change  orientation to landscape 
6. change again to portrait 

**Expected behavior**
client logo should not overlap and should change 

**Screenshots**

https://user-images.githubusercontent.com/96585505/175240895-b225536f-9e2e-44a3-8b11-039c175e83b6.mp4

**Desktop (please complete the following information):**
 - OS: iphone 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
duplicate
