### ISSUE TITLE
web No space is seen on popup for country selector 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6509]
**Describe the bug**
No space is seen in country selector 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on Join the community 
3.  click on select your country 
4. see the top of county selector 

**Expected behavior**
there is no space on top of the country selector 

**Screenshots**
![image](https://user-images.githubusercontent.com/96585505/175250099-9dee7874-8932-4e95-92b4-c618b903cfca.png)

![image](https://user-images.githubusercontent.com/96585505/175250185-ee778c2f-f60a-4da3-91aa-a1f7d576ad78.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 103.0.5060.53

**Comment by drasticdpk** [comment]
Know issue.
