### ISSUE TITLE
[Web] Topcoder logo is not returning to home page

### ISSUE THREAD

**Issue by ashree1** [topcoder-platform/community-app#6515]
**Bug Describe**
User not able to return to home page from sales page when clicking on the Topcoder logo
**To Reproduce**
1) Click on the Book a Demo option in the Home page
2) You will reach the sales page
3) Try clicking on the Topcoder logo to return to the Homepage

**Actual behavior**
Clicking on the Topcoder logo does nothing

**Expected behavior**
Clicking on the Topcoder logo should  take you back to the Home Page

**Screenshots**

https://user-images.githubusercontent.com/98447324/175253252-a056c9f1-d8a3-49fe-adf2-67adcd1fe151.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser- Chrome
 - Version - 103.0.5060.53

**Comment by drasticdpk** [comment]
duplicate
