### ISSUE TITLE
[iphone] Placeholder for the press room is not going to default position on closing dropdown 

### ISSUE THREAD

**Issue by timeazc** [topcoder-platform/community-app#6535]
**Describe the bug**
Placeholder for the press room is not going to default position on closing dropdown 

**To Reproduce**
1. Go to https://www.topcoder.com/
2. click on resources 
3. click on press room 
4. click  on press room from icon 
5. click outside of press room 

**Expected behavior**
clicking on dropdown  icon to close the press room placeholder should be inside the field 

**Screenshots**

https://user-images.githubusercontent.com/96585505/175276457-16620974-397e-4ac9-a9ea-6c0fb26ccd06.mp4

**Desktop (please complete the following information):**
 - OS: iphone 
 - Browser safari 
 - Version

**Comment by drasticdpk** [comment]
Out of scope.
