### ISSUE TITLE
How it works: The watermark photos are not correct

### ISSUE THREAD

**Issue by azibabari** [topcoder-platform/community-app#6536]
The photos used as watermarks for 'Projects and Professional services', 'Talent Placement', and 'Launch your own challenge' are not exactly the same as the ones in the Scenario document

1.Go to 'https://www.topcoder.com/how-it-works

2.Observe the 'Projects and Professional services', 'Talent Placement', and 'Launch your own challenge' features

**Expected Result**
The photos used as watermarks for 'Projects and Professional services', 'Talent Placement', and 'Launch your own challenge' should be exactly the same as the ones in the Scenario document

**Screencast/Screenshot**

![IMG_3895](https://user-images.githubusercontent.com/107992814/175278054-4fe8be39-0b7c-45b6-83c9-225ff1951612.jpg)

**Environment
Smartphone**

Device: [ iPhone6s]
OS: [ iOS15.1]
Browser [safari]
Version [15.1]

**Bug Type**
UI
Bug-hunt-June22

**Comment by ClintonBon24** [comment]
Hi @drasticdpk this is a good observation. We did change it from the Scenario Document. So no real bug here.
