### ISSUE TITLE
Two "Show Password" icons are appearing on "Sign In" page

### ISSUE THREAD

**Issue by cgoma** [topcoder-platform/community-app#6543]
**Issue Title**
Two "Show Password" icons are appearing on "Sign In" page

**Device**
Desktop PC

**Operating System**
Windows 10

**Browser**
Microsoft Edge

**To Reproduce**
1. Go to 'https://www.topcoder.com/'
2. Click on "Login"
3.  On "Sign In" page, enter password in "Password" input box
4. Verify if two "Show Password" icons appeared at the end of "Password" input box. 

**Expected behavior**
Only one "Show Password" icon should appear

**Actual Result**
Two "Show Password" icons appeared

**Screenshots**

https://user-images.githubusercontent.com/10756434/175283039-56e37da0-e924-46a5-b796-db46336667be.mp4

**Bug Type**
UI

**Comment by drasticdpk** [comment]
https://github.com/topcoder-platform/community-app/issues/6539
