### ISSUE TITLE
Double-check the terms modal

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#655]
https://apps.topcoder.com/forums/?module=Thread&threadID=909689&start=0&mc=2#2232184

**Comment by nithyaasworld** [comment]
Buttons are visible in the viewport and are static to the scroll.

![image](https://user-images.githubusercontent.com/5114190/59877605-d69c8b00-93c3-11e9-908d-79b6d25d09f1.png)
