### ISSUE TITLE
[Web] The Community link does not lead to /community

### ISSUE THREAD

**Issue by macs054** [topcoder-platform/community-app#6555]
**Describe the bug**
The Community link does not lead to /community but to /the-community

**To Reproduce**
1. Go to https://www.topcoder.com/
2. Click on 'The Community'
3. Observe the link

**Expected behavior**
The Community should take a user to topcoder.com/community as per the [reference doc](https://docs.google.com/document/d/14R5rV0drrFysEN2C1vt429M6zXAWXVxHIHRCXRnUoUQ/edit)

**Screenshots**
![image](https://user-images.githubusercontent.com/1199534/175309897-c5ad0103-2451-4107-b43b-c0c6a8eae189.png)

**Desktop (please complete the following information):**
- Device: Desktop
- OS: Windows 10 Pro version 21H2 build 19044.1766
- Browser: 
  - Chrome 103.0.5060.53
  - Firefox 101.0.1
  - Microsoft Edge 102.0.1245.44

**Additional context**

**Comment by ClintonBon24** [comment]
Hi @drasticdpk - this is not a bug. I had thought the URL structure was going to use /community.

We changed that to /the-community but the expected behavior is correct, so not a bug. Plz close, thx you.
