### ISSUE TITLE
Submission Closed!

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/community-app#6560]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hasinamahamootha** [comment]
Hi @drasticdpk , 

I have not submitted in the topcoder within the given time. In topcoder page I remember I saw that the submission deadline was shown as 3d, hence I didnt submit it there. But i have identified about 8 bugs and have logged it in github. Please accept my submission with my credentias below.

Topcoder handle: mahamootha
github handle: hasinamahamootha

**Comment by drasticdpk** [comment]
@hasinamahamootha, 
will consider you this time, but make sure you will make the submission on time for the next challenge.
Thank you
