### ISSUE TITLE
[Web] 'Discover the impact' Text changes in size and flickers in forrester resport page

### ISSUE THREAD

**Issue by hasinamahamootha** [topcoder-platform/community-app#6561]
**Describe the bug**
'Discover the impact' Text changes in size and flickers in forrester resport page

**To Reproduce**
1. Go to 'https://topcoder.com/'
2. Click on About and then click on get free report.
3. The forrester report page flickers with changes in Text size of 'Discover the impact'

**Expected behavior**
The page should not flicker and the text size should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/25719514/175345202-413262cb-405c-4fe7-9768-fcb7e22e1926.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome

https://user-images.githubusercontent.com/25719514/175347129-cb6524e2-8ac2-4268-86ba-bbe16716dee9.mp4

]

**Comment by drasticdpk** [comment]
The bug submission period has been closed.
