### ISSUE TITLE
Cognitive Site - Leave site and go back (landing page is wrong)

### ISSUE THREAD

**Issue by cdngirl** [topcoder-platform/community-app#658]
@birdofpreyru When I got main homepage of cognitive site and then click on one of the other communities like Blockchain community from the top drop down link. Then I click on "cognitive community site" again from the drop down, it takes me to the old cognitive site not the new one.

**Comment by birdofpreyru** [comment]
Not a bug. This is just because you tested in production environment, but Tony has not switched the prod routing of https://cognitive.topcoder.com from legacy to the new version yet. If you try the same starting from https://cognitive.topcoder-dev.com/ you'll see it works fine.
