### ISSUE TITLE
Cognitive Site - FAQs Content

### ISSUE THREAD

**Issue by trevorgerring** [topcoder-platform/community-app#659]
@birdofpreyru The first 2 FAQ text is wrong. should match what is in the design: https://zpl.io/bro3Qnr

**Comment by birdofpreyru** [comment]
@trevorgerring Ok, the 2-nd FAQ I am updating to match the design, with removing *Lite* from occurences of *IBM Cloud Lite*?

For the 1-st one, you asked at some point to sync it with the content from old version, which was:
![screenshot](https://user-images.githubusercontent.com/20144632/33857273-52f5a31c-decb-11e7-8cc5-9ce467b250d9.png)
so I did, which a small update of the text to fit with the additional first paragraph about joining from your desing (which currently dissapears if the user is already member).

Thus, wanna double-check about 1-st item: do you want to change it back to the design, or something else?

**Comment by trevorgerring** [comment]
@birdofpreyru Sorry about the confusion. Yes, it should match the latest design.
