### ISSUE TITLE
Change text on TCO challenge filter

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6592]
**Describe the bug**
We need to change the text `TCO Eligible Challenges` in the filters to `Only Show TCO Eligible Challenges`

The problem is that just replacing the text isn't enough because the layout breaks:

1.  The text overlaps with the `i` tooltip 
2. When resizing to a smaller width, the text overflows the box:3. 

<img width="271" alt="Screen Shot 2022-07-22 at 1 45 48 pm" src="https://user-images.githubusercontent.com/21790/180358462-0683e4e4-0d20-4e44-8452-86fa329c2ec5.png">

**Expected behavior**
After the fix, the updated text should be applied, along with updated CSS so that the overlaps are fixed and the text doesn't go outside the sidebar at smaller widths.

We need to ensure this is tested on all filter areas, like `All Challenges`, `My Challenges`, and `Past Challenges`.

**Comment by Assem5** [comment]
."    " input {
    position:relative;
    width:50%;
}
