### ISSUE TITLE
Filters - Text alignment

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6660]
**Describe the bug**
For the sections, the track and “Only“ word are not centered - same thing happens for the other sections.

**Screenshot**
![image-20221005-212516](https://user-images.githubusercontent.com/21790/194177176-a9679f58-f685-4dd8-a376-abcfa2c37532.png)

**Comment by thiendang** [comment]
> **Describe the bug** For the sections, the track and “Only“ word are not centered - same thing happens for the other sections.
> 
> **Screenshot** ![image-20221005-212516](https://user-images.githubusercontent.com/21790/194177176-a9679f58-f685-4dd8-a376-abcfa2c37532.png)

Hi @jmgasper , what is the url for the sections?
