### ISSUE TITLE
Cognitive Site - Wrong Link 

### ISSUE THREAD

**Issue by cdngirl** [topcoder-platform/community-app#670]
@birdofpreyru on the https://cognitive.topcoder.com/ site, on the homepage, There are are 3 steps to "Get Started Today" The 3rd step, "Compete using IBM Cloud" should link to this FAQ please, under the "Resources" Tab -> FAQ, "How Do I Get an IBM Cloud Account" please. 

![image](https://user-images.githubusercontent.com/22596035/33960196-f8de61ea-e017-11e7-9989-ceb82ee50053.png)

Thank you!

**Comment by cdngirl** [comment]
@birdofpreyru so sorry but I wrote the wrong FAQ to link, it should go to  Link to Resources, "What is IBM Cloud and Why do I need It?" FAQ.

**Comment by cdngirl** [comment]
@birdofpreyru it's linking to a different FAQ still, should go to "What is IBM Cloud and Why do I need It?" FAQ.

**Comment by birdofpreyru** [comment]
@cdngirl seems to be fine now. The ticket was closed when I pushed the change to dev environment; Tony was doing other changes on Veterans in parallel, so I didn't push to prod. It seems, he pushed all changes to prod now.
