### ISSUE TITLE
Veterans site - Switch out image

### ISSUE THREAD

**Issue by trevorgerring** [topcoder-platform/community-app#673]
@birdofpreyru We need to switch out the image on https://veterans.topcoder.com/learn for "The Types of Challenges" content box.

New image:
![9da32ff8cafff782e4ddf78b06cda2a7](https://user-images.githubusercontent.com/21342409/34008116-7fa32810-e0c1-11e7-9011-b11ce9872ca9.jpg)

This should just be a 1:1 switch

**Comment by birdofpreyru** [comment]
Done by Tony
