### ISSUE TITLE
Cognitive Site - Add Tags to any and all "sign up for IBM cloud" links

### ISSUE THREAD

**Issue by cdngirl** [topcoder-platform/community-app#679]
Hi @birdofpreyru 
Can you please add tags to the links going to IBM Cloud sign up so we can track. 
Wherever we have a link or button to IBM Cloud sign up page, let's add "?cm_mmc=dw-_-cognitive-_-topcoder-_-community" at the end of the url so it looks like this: https://console.bluemix.net/registration/free?cm_mmc=dw-_-cognitive-_-topcoder-_-community

On Resources Tab: 
- FAQ, "What is IBM Cloud and Why do I need it" -> The "Sign up for IBM Cloud" link needs to be updated so that url has the tag at the end. 
-FAQ "How do I Get an IBM Cloud Account" -> The "Click Here" link needs to be updated so that URL has the tag at the end

Thank you

**Comment by harshitmehta123** [comment]
Hi @birdofpreyru, 
Can you give us an idea when this will be deployed :)

**Comment by birdofpreyru** [comment]
Done in 04cabeaca14e167fa740ecbfe6c23c18d66eb753 and deployed to prod
