### ISSUE TITLE
[$30] - Bug of Downloads section in Challenge details sidebar

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#682]
> Class C - https://www.topcoder.com/challenges/30060999/?type=design&tab=details <--- no downloads link available |  https://www.topcoder.com/challenges/30060999 <- Downloads now show....it's weird. Logged in. Chrome(latest). Win 10.

> birdofpreyru [22 hours ago] 
hm... while I was trying to check what is going on there, I found out that the downloads link has appeared again, at least for me.

> toxicpixel [7 hours ago] 
@birdofpreyru still not showing for me...".../?type=design&tab=details" is the only issue it seems. I remove that part of the address and PLOP there are the downloads.

> birdofpreyru [< 1 minute ago] 
Nope, I believe, if you reload the page, it will show you downloads on any url. We'll fix this bug later - good catch :slightly_smiling_face:

I guess the problem is this: downloadable documents are included into challenge details from api only when they are fetched with a valid auth token. So, if somebody goes directly to the page with expired token, the challenge specs are fetched as anonymous user, and don't include downloads. Once the page is loaded to the user, his auth token is automatically refreshed, but the specs are not updated, thus the downloads never appear.

### Expected Fix
If my guess is correct, then the challenge details container, in its `componentWillReceiveProps` should check the authorization segment of the state, and when `auth.user.userId` changes it should silently reload the challenge details with the new auth token.

**Comment by imadx** [comment]
Added PR https://github.com/topcoder-platform/community-app/pull/699 with the ThemeProvider and related code removed

**Comment by andela-jomadoye** [comment]
I have raised a PR for this issue [HERE](https://github.com/topcoder-platform/community-app/pull/710)
