### ISSUE TITLE
Download buttons for RDM submissions

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6826]
@suppermancool - A new request, to match the `Marathon Match` download buttons is that we expand this to RDM (Rapid Development Match) challenges as well.  We will have to add a new check (`isRDM`), instead of reusing the `isMM` check we already have, since we still want to be able to differentiate between marathon and rapid development matches elsewhere.

For this first iteration, we'll determine and RDM based on:

* Challenge type (not currently in prod, but will be upcoming)
* Tag (`Rapid Development Match`)

The functionality should be the same as it is now for marathon matches - a logged in user can download individual submissions, all submissions, individual winner, or all winners.

**Comment by suppermancool** [comment]
@jmgasper done in [issue-6826.patch](https://github.com/topcoder-platform/community-app/files/10752861/issue-6826.patch) (against commit d5acd6a78ddee66e9719410ba2ec79e243088d55 in marathon_match_submission_download branch). 


I can not find any RDM challenge in dev. I try to create this RDM challenge https://challenges.topcoder-dev.com/projects/22248/challenges/c0df11c6-69ba-4e65-9309-8b6f5711d87d/edit and close it in https://software.topcoder-dev.com/review/actions/EditProject?pid=30092863, but I'm not sure if I can close the challenge in dev( it may make real payment for submitter)

**Comment by jmgasper** [comment]
@suppermancool - Thanks, deploying to QA now.  Note that you can do anything you want in dev - it won't make any real payments.
