### ISSUE TITLE
Test fixes

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6839]
From code review of recent PR: https://github.com/topcoder-platform/community-app/pull/6836#discussion_r1120046589

Disabling lint rules instead fixing the issues is not best practice.

1. Are easy to fix and affect just some files:
```
"react/jsx-no-bind": false,
"react/destructuring-assignment": false,
"react/no-array-index-key": false
```

2. This affect a lot of files and need some work to update all.
```
"react/no-unknown-property": false,
```

**Comment by luizrrodrigues** [comment]
@jmgasper We have issues with /Gigs pages, looks like related with these changes:
https://github.com/topcoder-platform/community-app/commit/9536487075c4d8c60489911531910a1e533a8583#diff-e71f18fbe2291ded6a699e09d03da7a86b30b432552753e097d633d07242edb0
