### ISSUE TITLE
Hide download for MM / RDM

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6867]
@suppermancool - The fix to download submissions using the M2M token caused a security problem because that token got leaked to the client side.  

For now, we're going to hide those download buttons for:

1.  Winners 
2. Submissions
3. Download All

Can you go through and hide those please?  I'll let you know when we figure out a solution for how to handle this better - likely formalised into the submissions API.

**Comment by suppermancool** [comment]
@jmgasper done in 
[community-app-issue-6867.patch](https://github.com/topcoder-platform/community-app/files/11350130/community-app-issue-6867.patch)

This patch against commit 0d2ae964f113e911e2c467381547e1d268be77bc (develop branch)
