### ISSUE TITLE
update topgear home banner

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#687]
Please update the banner on the homepage with the following image.

![topcoder_banner1 1](https://user-images.githubusercontent.com/3812270/34156657-2516ae2a-e48c-11e7-8e70-01165a12cc46.png)

**Comment by ajefts** [comment]
@birdofpreyru can you do this image switch when you're available please?

**Comment by birdofpreyru** [comment]
@ajefts do you have the image separately, without the circle with text?

**Comment by ajefts** [comment]
[retopgear_topcoder_combannerchanges.zip](https://github.com/topcoder-platform/community-app/files/1574275/retopgear_topcoder_combannerchanges.zip)

fyi @birdofpreyru ...please see attached images
