### ISSUE TITLE
Add link to gigs on challenge listings page on CA

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6874]
REF: https://topcoder.atlassian.net/browse/PROD-4221

**Describe the bug**
Add a Gigs link to the right of “past challenges” on the current challenge listings page that will direct user to https://www.topcoder.com/gigs

<img width="409" alt="image-20230503-160525" src="https://user-images.githubusercontent.com/21790/236115817-e2027efc-16ce-4f90-888d-436f25723d5c.png">

### Changes

We will change:

1. The challenge listing page to add the `Gigs` link
2. The gigs page header

#### Gigs page header

We will redesign the Gigs page header to more closely match the Challenge list header.

1. Add the challenge header and tabs to the Gigs page, above the referral link
2. Change `Challenges` to `Gig Work Opportunities`
3. Show the referral section below the header

When on the `Gigs` page, the `Gigs` option in the tab list should be highlighted.  The `Active Challenges` and `Past Challenges` links should go back to the challenge listing

<img width="1802" alt="SCR-20230504-nkcn" src="https://user-images.githubusercontent.com/21790/236116994-61ff5959-0def-4406-9789-2a91b06461ab.png">

<img width="1802" alt="SCR-20230504-nkho" src="https://user-images.githubusercontent.com/21790/236117002-3803cb1d-f54a-4e61-8b4b-1e5ae78eaf44.png">

**Comment by suppermancool** [comment]
@jmgasper done in 
[community-app-issue-6874.patch](https://github.com/topcoder-platform/community-app/files/11396614/community-app-issue-6874.patch)

this PR against commit 9192e1ff926353e5ad5774f7a841f0b89552c73a (develop branch)

The `GIG WORK OPPORTUNITIES` text in the below screenshot is configured in Contentful you should remove it inside the Contentful dashboard

<img width="1802" alt="SCR-20230504-nkho" src="https://user-images.githubusercontent.com/21790/236117002-3803cb1d-f54a-4e61-8b4b-1e5ae78eaf44.png">
