### ISSUE TITLE
Show security reminder to members before downloading project data

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6880]
REF: https://topcoder.atlassian.net/browse/PROD-4255

### Description

As a member, when I attempt to download data from a challenge/work item, I should be reminded to keep project data private and delete it at project completion, to reduce the risk of accidental data leakage. 

* I must accept/agree before I am able to register for the challenge, for challenges where an NDA is required

### Implementation

For challenges where an NDA is required, we will show a popup when the "Register" button is clicked.

We will show the text below, along with a checkbox that says "I agree" and then another button "Register" that will complete the registration.  Note that the "Register" button in the popup will *only* be enabled once `I agree` is checked

### Text

IMPORTANT REMINDER: In accordance with the Terms & Conditions and Code of Conduct you agree:
* to keep private any downloaded data (including code) 
  * except sharing or submission as directed or authorized by Topcoder
* to delete such data after completion of the challenge or project

**Comment by suppermancool** [comment]
@jmgasper done in 
[community-app-issue-6880.patch](https://github.com/topcoder-platform/community-app/files/11538708/community-app-issue-6880.patch)

**Comment by jmgasper** [comment]
@suppermancool - I don't think this is quite right.  We want to show this for *every* member registering for *every* challenge with an NDA, regardless of whether or not they've already agreed to the terms.

Here's a test challenge in dev:  https://www.topcoder-dev.com/challenges/9a76f0c8-bf91-40d3-b871-72423df39933?tab=details

**Comment by suppermancool** [comment]
@jmgasper pls revert my previous patch file, thanks!
Done in [community-app-issue-6880.patch](https://github.com/topcoder-platform/community-app/files/11540502/community-app-issue-6880.patch)  (the patch against commit 723a52a5a485d1e775ee7f73b392b32fc041a58b in develop branch)

**Comment by jmgasper** [comment]
@suppermancool - Looks good, thanks.  Can we add an "X" in the upper right to cancel out of the popup please?

<img width="1464" alt="SCR-20230524-kngz" src="https://github.com/topcoder-platform/community-app/assets/21790/031d06a8-9cc5-4eb7-9a05-49078f930123">

**Comment by suppermancool** [comment]
@jmgasper pls revert my previous patch file, thanks!
Done in [community-app-issue-6880.patch](https://github.com/topcoder-platform/community-app/files/11550493/community-app-issue-6880.patch) (the patch against commit 723a52a5a485d1e775ee7f73b392b32fc041a58b in develop branch)
