### ISSUE TITLE
Redirect current profiles path to new profiles URL

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6895]
To support all the various apps we have that send users to the current profiles link, like:

https://www.topcoder-dev.com/members/Ghostar

We are going to update the `/members/{handle}` route in community app to redirect the browser to the new profiles app:

https://profiles.topcoder-dev.com/{handle}

**Comment by suppermancool** [comment]
@jmgasper done in 
[community-app-issue-6895.patch](https://github.com/topcoder-platform/community-app/files/12017716/community-app-issue-6895.patch)
. This patch again commit 3e94fdb4888633e932783b4a763a76f2a3e170f6 in develop branch
