### ISSUE TITLE
TCO community sites still linking to old profiles

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6908]
REF: https://topcoder.atlassian.net/browse/MP-352

### Bug

TCO websites still show old profiles view. See: https://tco23.topcoder.com/members/kiril.kartunov 
We have missed to redirect those to new profiles app (profiles.topcoder.com/{handle}). 

This looks to be the case for all sub-communities in community-app. 

#### Profiles links examples:

* https://zurich.topcoder.com/members/kiril.kartunov
* https://comcast.topcoder.com/members/kiril.kartunov

#### Settings link

For all of the above if applicable /settings/profile should redirect to the new account-settings.topcoder.com app. For example:

https://tco23.topcoder-dev.com/settings/profile should send the user to account-settings.topcoder.com. The settings link is in the menu in the header.

![image](https://github.com/topcoder-platform/community-app/assets/21790/7b7204e4-3e38-4522-a3d8-536e338dee7a)

### Fix

We need to go through all the communities and add the redirect

https://github.com/topcoder-platform/community-app/tree/develop/src/shared/routes/Communities

For instance, in the case of TCO23: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/routes/Communities/TCO23/Routes.jsx

### Common pattern

There's a lot of sub-communities, so please let me know if there's a good way to tackle this in an easy way.

Scope of websites to handle is:

All TCOs 23 - 01 - https://tco23.topcoder-dev.com/settings/profile - https://tco01.topcoder-dev.com/settings/profile

https://zurich.topcoder.com/members/kiril.kartunov

https://comcast.topcoder.com/members/kiril.kartunov

For all of the above if applicable /settings/profile should redirect to new account-settings app. For example:

https://tco23.topcoder-dev.com/settings/profile should send the user to account-settings.topcoder.com and similar. Settings is link on drop down menu in header at the top right.

**Comment by suppermancool** [comment]
@jmgasper yes i can make this work for all sub-communities
