### ISSUE TITLE
Marvel Rules and Texbox

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#691]
We'd like to add a new field on the submit page for design challenges, a textbox which should be named Prototype link. Is basically a link to Marvel/Invision as it should be mandatory for all challenges except Print/Presentations.

Also the same challenges, should have some specific rules added in specifications as text when making these Prototypes. The Marvel/Invision is a thing we are using in the latest 2 years, at first on and off, but now all the time, so as is part of the process we thought to integrate it in the site.

**Comment by nithyaasworld** [comment]
@Dara-K Can you please confirm if we want this feature still?

**Comment by Dara-K** [comment]
No, we don't need it anymore

**Comment by nithyaasworld** [comment]
Thanks @Dara-K for confirming!
