### ISSUE TITLE
Replace Submission Review tab with My Submissions

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6912]
REF: https://topcoder.atlassian.net/browse/PROD-3088

Currently, the Submissions Review tab unde the challenge details page, takes the user off the platform to and the Submission Review app which is not really useful.

Update: Replace Submission Review tab with My Submissions and when the user clicks on My Submissions, they will be taken to the page below.

<img width="1636" alt="image-20221019-212159" src="https://github.com/topcoder-platform/community-app/assets/21790/2ef789d4-148e-4665-8e5e-56d0c1949638">

**Comment by suppermancool** [comment]
@jmgasper done in 
[community-app-issue-6912.patch](https://github.com/topcoder-platform/community-app/files/12658843/community-app-issue-6912.patch)
