### ISSUE TITLE
Community App- Inconsistent block quotes

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6915]
REF: [PROD-43](https://topcoder.atlassian.net/browse/PROD-4047)

Block quotes added to a spec in Work Manager are rendering differently, depending on how they were added.  We need all of them to render as the first in the image below, with the green bar to the left:

![image-20230918-042445](https://github.com/topcoder-platform/community-app/assets/21790/170829a6-fc9e-42c7-aeb3-9fb56f488f75)

**Comment by suppermancool** [comment]
@jmgasper I can not reproduce the above issue. Can you provide the raw content of the above challenge?

**Comment by jmgasper** [comment]
@suppermancool - Sure, working on it.  QA reported this, so I've reached out to them.

**Comment by suppermancool** [comment]
@jmgasper In your screenshot the second and third blocks look like Code blocks, not quote blocks.

**Comment by jmgasper** [comment]
@suppermancool - See attached/. The third block was mistakenly a code block, so it can be ignored.

[blockquote.txt](https://github.com/topcoder-platform/community-app/files/12710832/blockquote.txt)

Updated screenshot:

![image-20230925-021822](https://github.com/topcoder-platform/community-app/assets/21790/5f8fd1e2-51fd-4fe8-849a-ad0a5fc76901)

**Comment by suppermancool** [comment]
@jmgasper In the provided text the second block starts with the `tap key`. In Mardown `tap key` is used for code block, not quotes block. I can implement this but this will look confusing for anyone that familiar to markdown format

**Comment by suppermancool** [comment]
@jmgasper ANY this done in 
[community-app-issue-6915.patch](https://github.com/topcoder-platform/community-app/files/12711543/community-app-issue-6915.patch)

**Comment by jmgasper** [comment]
Ok, thanks.  I'll discuss with the team.
