### ISSUE TITLE
Replace skills selector in gigs application page

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6916]
REF: https://topcoder.atlassian.net/browse/TSJR-118

Skills picker in gig application form needs to get updated to standardised v5 skills using the same auto-complete endpoint we implemented in Work Manager here:  https://github.com/topcoder-platform/work-manager/issues/1569

Where to find it:

topcoder.com/gigs → apply for a gig → application form.

We are going to replace the current dropdown with an autocomplete field, similar to the WM one above.

Code is located here: 

https://github.com/topcoder-platform/community-app/blob/develop/src/shared/containers/Gigs/techSkills.js

**Comment by suppermancool** [comment]
@jmgasper there are no gigs in https://topcoder-dev.com/gigs . Can you create some example gigs in dev?

**Comment by jmgasper** [comment]
> @jmgasper there are no gigs in https://topcoder-dev.com/gigs . Can you create some example gigs in dev?

Working on it - may take a day, sorry.

**Comment by jmgasper** [comment]
@suppermancool - We fixed the gigs in dev - there should be some there now.

**Comment by suppermancool** [comment]
@jmgasper done in [community-app-issue-6916.patch](https://github.com/topcoder-platform/community-app/files/12790095/community-app-issue-6916.patch) (this patch against commit ea7a1ef37fc2210f3819ac57dc51e995ceab7b65 in develop branch)
