### ISSUE TITLE
[$100] - Restyle the standard TC footer

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#692]
![image](https://user-images.githubusercontent.com/20144632/34321638-4ec70d1a-e814-11e7-8539-935804f0059a.png)
> The Challenge Details Sketch file I have uses the top footer, while the site has the bottom. Did Victor do a new design or you talked about updating it?

So, we should re-style it to match the top version

**Comment by Dara-K** [comment]
Attached are the icons for the footer

[footer icons.zip](https://github.com/topcoder-platform/community-app/files/1584354/footer.icons.zip)

**Comment by Dara-K** [comment]
You can take the font size and colors, also the spacing from this html files.

Can you check the navigation uses Roboto font like here? and when we are under a Compete page that page should be active with the blue bar under it (as wide as text).

[html specs.zip](https://github.com/topcoder-platform/community-app/files/1584356/html.specs.zip)

**Comment by pkvprakash** [comment]
So we need to update the footer icons and the text styles in footer. Does this also include to update the header as well (Blue bar under active tab as given in the previous comment)?

**Comment by birdofpreyru** [comment]
Yes, everything mentioned in this ticket should be fixed

**Comment by imadx** [comment]
Added a PR to this bug. Any comments on it?
https://github.com/topcoder-platform/community-app/pull/698

**Comment by birdofpreyru** [comment]
@imadx cool, I'll be reviewing everything submitted today in the evening. About ~12h from now

**Comment by imadx** [comment]
@birdofpreyru Cool..

**Comment by iversonLv** [comment]
@birdofpreyru I think you should set this not Open Ticket:) and assign it to @imadx

**Comment by birdofpreyru** [comment]
@imadx accepted; but it looks to me that there are some slight differences in spacings between the design and your styling, so final fixes are necessary to clean it up. I have not really measured it carefully, but I believe, the spacing and alignment of the social network icons is a bit different, and also the padding below the copyright text.

I'll also ask @Dara-K to have a look at this, so she might ask you for some other fixes.

@Dara-K please check the look of the updated footer at https://www.topcoder-dev.com/challenges/30050464

**Comment by birdofpreyru** [comment]
@imadx yeah, I guess, it will be better to wait for feedback from @Dara-K before actually doing final fixes

**Comment by imadx** [comment]
@birdofpreyru I added another PR with the required refinements for the spacing on the footer anyway: Here https://github.com/topcoder-platform/community-app/pull/720

**Comment by Dara-K** [comment]
@imadx I did some small updates to the footer since this ticket was open, particular changing font size for menu to 15px, footer height to 220px. Make sure to check spacings again - the gray bar with logos is too far down now - should be 40px only. Gray bar is also 205px width, and has 2px height.

The padding between social logos is okay, but from logos to copyright text it should be 28px (I can see on CSS it has padding-bottom 28px, but when I measure it in Photoshop is 32px - maybe there is some padding to the copyright text...?).

On hover state, the Site Map, About Us, etc. should be white #FFFFFF.

I also added the mobile version, so you can see how it should act there as well. 

[Footer Details.zip](https://github.com/topcoder-platform/community-app/files/1616988/Footer.Details.zip)

**Comment by imadx** [comment]
@Dara-K @birdofpreyru made the necessary changes.. https://github.com/topcoder-platform/community-app/pull/727

**Comment by Dara-K** [comment]
@imadx Are the changes visible here? 
I've cleared cache and tried on both Firefox and Chrome but still looks like before.

**Comment by birdofpreyru** [comment]
@Dara-K not yet, I'll ping you once I push them to dev

**Comment by birdofpreyru** [comment]
@Dara-K ready

**Comment by Dara-K** [comment]
@imadx @birdofpreyru Looks good now. Thanks imadx!
