### ISSUE TITLE
Duplicate `My Submissions` tab in marathon match

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6922]
REF: https://topcoder.atlassian.net/browse/PROD-3088

Sample: https://staging-community-app.topcoder.com/challenges/971eb6a9-59d3-49da-a465-e9b70f1ce019?tab=my%20submissions

Login with `jgasperMobile12` / `Appirio123`

### Bug
You'll see *two* `My Submissions` tabs, because the custom marathon match view already has one

### Fix

We'll remove the `My Submissions` tab that is *not* marathon match specific, keeping the one that shows up when a marathon match is displayed, and only in that case.  Remove the one highlighted in the screenshot below.

### Screenshot

<img width="1410" alt="SCR-20231003-oqkx" src="https://github.com/topcoder-platform/community-app/assets/21790/a1496acc-ff4b-49cc-b802-7091000fb486">

**Comment by suppermancool** [comment]
@jmgasper done in [community-app-issue-6922.patch](https://github.com/topcoder-platform/community-app/files/12790297/community-app-issue-6922.patch) (this patch against commit ea7a1ef37fc2210f3819ac57dc51e995ceab7b65 develop branch)
