### ISSUE TITLE
Skills dropdown tweaks on gigs application

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6923]
A couple minor tweaks required here:

1.  The dropdown arrow to the right can be removed, since this isn't really a dropdown anymore as much as it is a text field.  The dropdown arrow is confusing because we don't populate this list anymore since the number of available skills is now too big.

2.  When clicking the text field, the display is a bit weird - can we have this say:
* `Type to search` if no skills are entered
* `Type to add another skill...` if at least one skill is in the list, but shows after the skills in the list.

**Comment by suppermancool** [comment]
@jmgasper done in [community-app-issue-6923.patch](https://github.com/topcoder-platform/community-app/files/12843652/community-app-issue-6923.patch) (this patch against commit 3a9a745692aa0708882d8eea3d58127be14fcd06 in develop branch)
