### ISSUE TITLE
Can't search gigs in dev

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/community-app#6928]
Sample URL:  https://www.topcoder-dev.com/gigs?search=Justin

This loads a blank white screen, instead of doing the actual search.

**Comment by suppermancool** [comment]
@jmgasper done in 
[community-app-issue-6928.patch](https://github.com/topcoder-platform/community-app/files/13176417/community-app-issue-6928.patch) (this patch against commit f018a465df7b7af8d92d72e9c0d225a66df9fad6 in develop branch)
