### ISSUE TITLE
Incorrect wins count

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#694]
Hi,

Wins count does not increase on the member profile page for last 5 contest. 

 See this screenshot 
https://gyazo.com/6b345c623e75478c1809f406389446fc

Please check and resolve.

**Comment by birdofpreyru** [comment]
@ajefts do we need to restart some backend micro-service?

**Comment by ThomasKranitsas** [comment]
Same issue here.

Check the following screenshots:

![code](https://user-images.githubusercontent.com/4612921/34905696-ffe149b4-f866-11e7-90bf-24a36138fea8.png)

![f2f](https://user-images.githubusercontent.com/4612921/34905697-042d18c2-f867-11e7-9fc9-642145939773.png)
