### ISSUE TITLE
[$50] - Error on accessing /my-submissions is not handled gracefully

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#696]
Try to go directly to an URL like `www.topcoder.com/challenges/:challengeId/my-submissions` for a challenge where you have not submitted, nor registered. Our JS will break and you'll see just a blank page. It should be handled gracefully (display placeholder text like "You have not registered to this challenge yet", or "You have not submitted to this challenge yet", whatever is more appropriate for a specific situation, and also show the link to go back to the challenge specs page.
  
P.S.: It seems, the error also happens on some past challenges, where submissions have been done. Probably, the problems is not related to what is written above. Anyway, the issue with the page should be investigated and resolved.

**Comment by ekundayo-ab** [comment]
Hi @birdofpreyru can't seem to reproduce the blank page as you described. Is there something i'm missing?

### I got this for a challenge where **I've** registered
<img width="1438" alt="screen shot 2018-01-07 at 1 22 16 pm" src="https://user-images.githubusercontent.com/20375577/34649374-27751860-f3ae-11e7-9ec8-bdbdea99087a.png">

### While i got this for a challege where **I did not register**
<img width="1440" alt="screen shot 2018-01-07 at 1 25 02 pm" src="https://user-images.githubusercontent.com/20375577/34649382-5205c4c6-f3ae-11e7-8ef4-4b715ecdfc7f.png">

**Comment by imadx** [comment]
Errors already have been handled gracefully... The problem was not handling an undefined variable. Added a PR for this: https://github.com/topcoder-platform/community-app/pull/703
