### ISSUE TITLE
Change link color in details page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#730]
I always have to manually set the color of each link in direct otherwise the links are not clearly visible.

Check the following screenshot:

![topcoder - create review opportunity application endpoints 2018-01-11 14-30-40](https://user-images.githubusercontent.com/4612921/34825683-23b3cb82-f6dc-11e7-83ea-30a4cf24cb5a.png)

Not sure if this is an issue with the WYSIWYG editor though.

**Comment by birdofpreyru** [comment]
> I always have to manually set the color of each link in direct otherwise the links are not clearly visible.

Bad boy :)

The current default and hovered link color in challenge specs is #0a71e6, also known as *tc-dark-blue*; #0C4E98 for the visited links, #59a7ff for active links. These come from design specs, and if you manually override them via Direct, somewhere @Dara-K feels sad about it :-D

**Comment by ThomasKranitsas** [comment]
hahaha 😂 
Sorry @Dara-K 😇  😛

**Comment by Dara-K** [comment]
That's a good point - don't override the colors, font type or other things @ThomasKranitsas! 

@birdofpreyru is correct with the only exception that default and hover dark blue color is #0b71e6. Can you fix this? :)

I saw this difference in links colors too as I launched my first challenge and I don't think the visited state color gives a good enough contrast to regular text either, but those states were defined by Vic (wrote him couple hours ago as I saw your messages to use the default color). Will let you know when I have any updates.

**Comment by birdofpreyru** [comment]
@Dara-K do you mean *tc-dark-blue* should be `#0b71e6` all around? Cause here: https://wwwtc.wpengine.com/about-topcoder/brand-guidelines/ it is told that TC blue color is `#0a71e6`

**Comment by Dara-K** [comment]
Yes, exactly. I never saw it with #0a71e6 - on all the designs and files Vic shared with me it was #0b71e6 
![tc app connect palette](https://user-images.githubusercontent.com/25185079/34839642-038b45e0-f70b-11e7-87b5-62e2d40989de.png)

**Comment by birdofpreyru** [comment]
@Dara-K ok, cool, I'll check that colors from the pallet correspond this page of TC UI Kit :)

**Comment by Dara-K** [comment]
@birdofpreyru Hope you don't have too many pages to update now :)

**Comment by Dara-K** [comment]
@birdofpreyru You can use the same color for the active state as for the visited state.

@ThomasKranitsas good that you brought this up :)

**Comment by birdofpreyru** [comment]
FYI @Dara-K, the page from TC UI Kit you have shared above has some bugs:
![screenshot](https://user-images.githubusercontent.com/20144632/35017015-56034f8e-fb1b-11e7-8ffd-05896cf0a409.png)
Probably, not a big deal (the stylesheet we have in Community App has the missing colors; may be they are a bit different from the assumed values, but should be close enough anyway).

**Comment by Dara-K** [comment]
Thanks for pointing it out - Vic defined those and I never checked all codes as I use the ones from site to copy-paste faster the color code: https://company-56102.frontify.com/d/zEXqGHFD1YN2/ui-library#/tc-styles/tc-colors  <- you can see the right ones here

Will update them..

**Comment by Dara-K** [comment]
Here's the corrected version.

![tc app connect palette](https://user-images.githubusercontent.com/25185079/35044706-126ba076-fb9a-11e7-96b2-8174187c3421.png)
