### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#748]
Hi

This link https://help.topcoder.com/data-science/competing-in-algorithm-challenges/algorithm-tutorials/
is not working. Pls check and do the needful.

**Comment by birdofpreyru** [comment]
Hey @JayaDhaka, can you also tell please, which page contains this link?

FYI @ajefts: at the moment I can't find this link inside Community App, so probably, it relates to some other piece of the platform; but sure, still a bug.

**Comment by JayaDhaka** [comment]
@birdofpreyru Please go to this page https://www.topcoder.com/community/data-science/getting-started-in-data-science/ then click on this text "member-created algorithm tutorials here" 

![deadlink](https://user-images.githubusercontent.com/34749364/36094717-58d6b408-1015-11e8-9298-8f22785aa874.png)
![deadlink2](https://user-images.githubusercontent.com/34749364/36094723-5cafedec-1015-11e8-863f-2b9d5752a363.png)

**Comment by harshitmehta123** [comment]
@birdofpreyru @ajefts @JayaDhaka This is fixed!
