### ISSUE TITLE
Challenge-community stats check

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#750]
An ask from Ashley Steele:
- We need a way to find out how many of a challenge registrants are members of the related community.

Her main interest is the Blockchain community, but we can do a generic solution.

@ajefts this can be done with a relatively simple script using current APIs on the Community App side, or it can be added as a feature to the APIs itself. Whatever you prefer?

**Comment by ajefts** [comment]
Hold up on this.  Let me ask what the real need here is first...
