### ISSUE TITLE
Challenge details: winners tab

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#751]
An ask from @Dara-K 
![image](https://user-images.githubusercontent.com/20144632/35125273-58ab6cdc-fca9-11e7-9a1f-26716e44aac9.png)

**Comment by Dara-K** [comment]
![colors](https://user-images.githubusercontent.com/25185079/36145954-a2c48198-10bb-11e8-95fc-1d5a144f133c.png)
@birdofpreyru related to winners tab: 
- the color under the prizes should have the same blue as for places 4,5,etc. 
- don't forget to remove the 2 side gray lines we have now and extend the horizontal ones until the margin
