### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#763]
Hi,

Please check this link http://http//tco18.topcoder.com/ is not working

**Comment by birdofpreyru** [comment]
Hi @JayaDhaka , can you say where have you encountered this link?

**Comment by JayaDhaka** [comment]
Please go to this link https://www.topcoder.com/community/competitive-programming/ then click on TCO 18 be the next TCO Champion image then you will be redirected to this link http://http//tco18.topcoder.com/ 

Please visit the below link: 

![inkedimage 1 _li](https://user-images.githubusercontent.com/34749364/35732719-86e4b1b0-0840-11e8-9232-fa4a960a002a.jpg)

**Comment by harshitmehta123** [comment]
Hi @JayaDhaka I have fixed the same. 
This is now resolved.
