### ISSUE TITLE
Add text entry to vets signup modal

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#765]
Change signup process to ask for some information specific to the military.  We don't need to do an official authentication, but just something to allow users to enter info to help deter non veterans from registering

Here is what we'd like to add:

1. Dropdown for Branch.  Use this list from https://www.defense.gov/About/Military-Departments/Uniformed-Services/, and include "Other" as an option.

2. A free form single line text field to enter "Unit Identification Code". This is referring to  https://en.wikipedia.org/wiki/Unit_Identification_Code

**Comment by birdofpreyru** [comment]
This is vague at the moment. Do you want to ask something trivial like:
- Are you more than 18 years old?
- Have you served in the military?

Or something more tricky, like:
- What is the effective range of fire for M16 rifle in the Middle East climate?

Or do you mean, just to implement a generic way ot make such questions, and we configure the exact questions later?

**Comment by ajefts** [comment]
@birdofpreyru I've adding some more specific requirements

**Comment by nithyaasworld** [comment]
@ajefts This seems to have been implemented. Please re-open otherwise.

![image](https://user-images.githubusercontent.com/5114190/59584720-6a3c3600-90fc-11e9-8dfe-d7a62d1ae151.png)
