### ISSUE TITLE
Upload Page Issues

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#767]
1.Right now on upload section for design, we have no default font added, though we always use at least one font and even if it's standard font we have to declare it.

2. On declaring images and fonts, we should show inline validation once the user moves to next text field and not before, as it makes the user think he did something wrong before actually filling the field. As a suggestion, we can write on the top right, "Required" so the user knows he has to fill that field.
![upload page](https://user-images.githubusercontent.com/25185079/35888281-cb87a8f6-0b9f-11e8-9e86-d28c911bca69.png)

https://baymard.com/blog/inline-form-validation

**Comment by nithyaasworld** [comment]
@Dara-K I think this is no more an issue as the UI has changed. I am closing this issue. Please feel free to re-open if I am not right.

![image](https://user-images.githubusercontent.com/5114190/59376051-02d55d80-8d6d-11e9-8b7c-858a2ba4a6e4.png)

**Comment by Dara-K** [comment]
Yes, that's correct.
