### ISSUE TITLE
Possible Open redirect on topcoder.com

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#770]
An open redirect is a security flaw in an app or a web page that causes it to fail to properly authenticate URLs. A user can be sent a URL link that can lead to malicious content. The user will believe the link is trust-worthy because it still has the name of topcoder.com

Refer to https://topcoder.zendesk.com/agent/tickets/15421 for details.

**Comment by birdofpreyru** [comment]
@ajefts
