### ISSUE TITLE
Payments App: Can't clear project

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/community-app#772]
After selecting a project and hitting the "New Payment" button on a project without a billing account, an error is thrown when trying to clear the project name out. 
Example project selected:
![image](https://user-images.githubusercontent.com/1504607/35924724-d21c56ba-0bf1-11e8-9914-3c9f5624385c.png)
console log error thrown:
![image](https://user-images.githubusercontent.com/1504607/35924745-e4393d7c-0bf1-11e8-8e2e-f7ea2a1393fc.png)

**Comment by cwdcwd** [comment]
note, this occurs regardless of billing account status it would see

**Comment by birdofpreyru** [comment]
@cwdcwd are you testing it in prod? Can you add me to the project, so I can track the problem?

**Comment by cwdcwd** [comment]
I believe that was prod but will retest and confirm. perhaps it's resolved with those other issues

**Comment by cwdcwd** [comment]
prod
https://www.topcoder.com/direct/projectOverview.action?formData.projectId=15444
https://www.topcoder.com/direct/projectOverview.action?formData.projectId=15445

**Comment by birdofpreyru** [comment]
Both works fine for me now, do you see any issues?

**Comment by cwdcwd** [comment]
hitting the little X in the input box produces:

![image](https://user-images.githubusercontent.com/1504607/36113814-13c51ea4-0ffc-11e8-9a75-10d636886aa7.png)

**Comment by birdofpreyru** [comment]
Issue moved to [topcoder-payment-tool](https://github.com/topcoder-platform/topcoder-payment-tool) repo.
