### ISSUE TITLE
Change metal colors

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#773]
I added the new metal shades me and Vic chose, that is to 
[Winners.zip](https://github.com/topcoder-platform/community-app/files/1704370/Winners.zip)
to be used for medals and you can also see an updated color palette inside the archive.

**Comment by Dara-K** [comment]
Don't forget to read the notes on how they should be used.

**Comment by birdofpreyru** [comment]
@Dara-K 
noticed that color levels in the image included into this archive disagree with what is defined in our code:
```
$tc-level-1: $tc-gray-50;
$tc-level-2: $tc-pastel-green;
$tc-level-3: $tc-pastel-blue;
$tc-level-4: $tc-pastel-yellow;
$tc-level-5: $tc-pastel-crimson;
```
The code definition looks correct to me, as we should start from a gray color.

**Comment by Dara-K** [comment]
Right. We forgot to add it in the design, please reuse same gray shade as before, those didn't change.

**Comment by birdofpreyru** [comment]
@Dara-K updated in dev (should be visible shortly at topcoder-dev.com/challenges)
There is one side-effect: now flag colors for 2-nd and places after 3-rd one are almost identical (those use `$tc-gray-20`, which is `#a3a3ad`. Also, the places after 3-rd used to have white text color, but now it looked a bit strange comparing to top places, where text became darker than the background, so I changed font color for low placement to `$tc-gray-40`. In result, flags for low placement look very similar to the 2-nd place one.
