### ISSUE TITLE
Show additional challenges on vets site

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#776]
Currently, we only show challenges in the vets group...which are all private until  you are a member of the group.  This is a poor experience right now since when you visit the site as a non-member, it looks like there is nothing to do.

We'd like to do the following:

1.  Add a section to the  homepage that shows the most currently launched public challenges.  Something like we do here:  https://ios.topcoder.com/

2. On the challenge listings page, default the filter to public challenges, but add a section at the top that shows the Vets challenges.  If the user is not logged in and/or not a members, then show a message that if they join they get exclusive access to more challenges. If they are logged in and a member of vets, then the top section should show vets challenges that are open for registration.

"Join Now to access challenges that are exclusively available for US veterans."

**Comment by nithyaasworld** [comment]
> Add a section to the homepage that shows the most currently launched public challenges

It does not show the most recently launched public challenge. It shows an Expired QA Challenge.

![image](https://user-images.githubusercontent.com/5114190/59588017-3ebd4980-9104-11e9-8d23-2dce80fac976.png)
