### ISSUE TITLE
Registered email forum url is wrong

### ISSUE THREAD

**Issue by iversonLv** [topcoder-platform/community-app#777]
There is additional '/' before forum id

![image](https://user-images.githubusercontent.com/4952611/36010441-65182264-0d8c-11e8-8738-c5d6aaa50dd2.png)

**Comment by birdofpreyru** [comment]
@iversonLv is it in the email you get after registration?
@ajefts who is in charge of these emails?

**Comment by ajefts** [comment]
@skyhit Can we get your assist on this one please??

**Comment by iversonLv** [comment]
@birdofpreyru 
Yes, after registered the challenge, and receive the email.
the forum link shows double "//" before forum id.

**Comment by ajefts** [comment]
I think this is a config issue.  Working on resolving it....

**Comment by ajefts** [comment]
This is fixed completely for dev challenges.

@skyhit I need some help fixing it for design.  The wrong forumUrl prefix is getting set....

**Comment by skyhit** [comment]
@ajefts is design and studio same concept ?

you can see https://github.com/appirio-tech/ap-challenge-microservice/blob/dev/src/main/resources/challenge-service.yaml#L143

**Comment by ajefts** [comment]
We don’t need both design and studio - it’s the same. But for the design challenge forums, check the urls of an active challenge. We need forumId instead of categoryId.
