### ISSUE TITLE
Payments App: Only show projects w/ active billing accounts

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/community-app#779]
When displaying projects, only show projects in the listing that have active billing accounts associated with them. 
This should greatly reduce the size of the list and increase speed thus improving the UX

**Comment by cwdcwd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove projects that lack active billing accounts](https://trello.com/c/DOXTeh4X/2-remove-projects-that-lack-active-billing-accounts)

**Comment by cwdcwd** [comment]
@birdofpreyru I forget where we left off on this. Did we ever fix the API for this or is that still outstanding?

**Comment by birdofpreyru** [comment]
I believe, it is all done, we just never closed the ticket.
