### ISSUE TITLE
DASH ISSUES

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#780]

**Comment by billsedison** [comment]
In https://community-app.topcoder.com/my-dashboard, not showing the number of challenges that are being copiloted.

**Comment by sdgun** [comment]
Here https://community-app.topcoder.com/my-dashboard 'Announcement' top banner goes beyond the left and right margin.

![2018-02-16_6-45-09](https://user-images.githubusercontent.com/4592712/36289533-6c4d1a80-12e6-11e8-84ff-5255b4f354c7.jpg)

**Comment by sdgun** [comment]
Compared to https://www.topcoder.com/my-dashboard/; here > Title fonts are different https://community-app.topcoder.com/my-dashboard

- DASHBOARD (Format: Bold)
- My Challenges and My Communities (Format: Bold and All Caps)
- SINGLE ROUND MATCHES (Format: Bold)
- iOS COMMUNITY (Format: Bold)
- FROM THE COMMUNITY BLOG (Format: Bold)
- VIEW MORE (Different Font)

![2 2](https://user-images.githubusercontent.com/4592712/36289815-207daff0-12e8-11e8-8846-5ace27e8ede2.jpg)
![2](https://user-images.githubusercontent.com/4592712/36289816-20b8ec1e-12e8-11e8-90eb-71cde02f1157.jpg)
![2 1](https://user-images.githubusercontent.com/4592712/36289817-20f811b4-12e8-11e8-9cc1-ec0cf61e9b56.jpg)

**Comment by sdgun** [comment]
Compared to https://www.topcoder.com/my-dashboard/; here https://community-app.topcoder.com/my-dashboard > Phase timing and date format issue

![3 2](https://user-images.githubusercontent.com/4592712/36289891-9df93b34-12e8-11e8-980a-6dee48728efc.jpg)


app.topcoder:

![3 1](https://user-images.githubusercontent.com/4592712/36289887-98b3a3b2-12e8-11e8-9f5a-fa70753c2154.jpg)

**Comment by iversonLv** [comment]
Seems not just misses COPILOT data, my side, misses COPILOT, DEVELOPMENT, WEB DESIGN.

**Comment by iversonLv** [comment]
My challenge List view:
1 As now right side display a filter box, the list row text need decrease the fontsize, look at the VIEW SCORECARD button, text is broken into 2 lines if content is too much, 
![image](https://user-images.githubusercontent.com/4952611/36295594-93ebfeca-1323-11e8-9f2b-d500fc4907a6.png)

**Comment by iversonLv** [comment]
My Community tab, Register button click nothing happen?
And what should it be if there are many challenge for that community? Register all challenges? Register the latest one?

**Comment by iversonLv** [comment]
Bottom 2 poster learn more button font family is different from other places
![image](https://user-images.githubusercontent.com/4952611/36295703-2f9012da-1324-11e8-81db-c02fb1930f7e.png)

**Comment by ThomasKranitsas** [comment]
- The stats section is actually a carousel but there's no indicator so the user has to guess it :)
- The copiloted challenges are at the very end of the carousel while should be at the beginning.
- I prefer the collapsible announcement as it takes less space.
- I don't really like showing 3 challenges per row. Can we make the challenge cards smaller? I usually have 8-10+ active challenge and scrolling to find them is not the best UX.
- The `WON IN PRIZES` should be `.toFixed(0)`. I don't see why we should show a value like `***,***.*`

**Comment by birdofpreyru** [comment]
Discussion moves to #787
