### ISSUE TITLE
Dashboard Update

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#787]
Issues and suggestions related to the dashboard update.

**Comment by mahestro** [comment]
Digging it! I like the new content the dashboard offers. Two things I noticed so far:

1. The old studio badge came back, not sure what it is http://take.ms/sWjGl
2. There's an `F` in the communities section. I guess it's meant to be a menu. Just a curious thing, the F letter didn't allow my low cognitive level to determine what it was :)
3. Do the `show my earnings` toggle works along with the show earnings from the profile in the global settings of the tc account?

**Comment by birdofpreyru** [comment]
@mahestro 

1. Not sure either: I've just ported badges-related code and graphics from the legacy code without modifications. We should ping somebody to think about what badges we want there, if we want them at all.

2. **F**ilters. Waiting for a proper icon from Dara.

3. Do we have such option in the global settings? Can't find it. At the moment the switch in the new dash just remembers your choice in browser's cookies; and defaults to *show* if no cookie is set.

**Comment by Schpotsky** [comment]
@birdofpreyru 
> 3. Do we have such option in the global settings? Can't find it. At the moment the switch in the new dash just remembers your choice in browser's cookies; and defaults to show if no cookie is set.

There was an option to enable/disable showing earnings in the public profile in the old settings update page.
But after the switch to the new theme, this option is not implemented and the competitors are now unable to switch it On/Off.

It looks like this option is enabled by default for new created profiles, and I can see the earnings of the new users by accessing this link  https://www.topcoder.com/tc?module=PaymentSummary&cr=<USER_ID>
Replace the <USER_ID> by the real user id.

I hope that this feature will be brought back, and allow the users to hide or show the earnings in the public profile.

This was discussed here [show/hide earnings](https://github.com/appirio-tech/topcoder-app/issues/910) but it is not implemented yet.

**Comment by nithyaasworld** [comment]
If there is still an issue with Dashboard that needs to be addressed, Please open a new issue.

> It looks like this option is enabled by default for new created profiles, and I can see the earnings of the new users by accessing this link https://www.topcoder.com/tc?module=PaymentSummary&cr=<USER_ID>
> Replace the <USER_ID> by the real user id.

The above URL is no more working. So no Problem.
