### ISSUE TITLE
SSO Users receiving a message - Unable to load SubCommunities

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#789]
SSO Users are receiving a message 
Failed to fetch subcommunities listing.

![image001 1](https://user-images.githubusercontent.com/5771673/37046528-912fdf02-218e-11e8-822e-62c3b7b08c98.jpg)

**Comment by RiteshTC** [comment]
@birdofpreyru 
Can you please provide insights into this error ? Its blocking users from loggin to private communities

cc @ajefts

**Comment by birdofpreyru** [comment]
@RiteshTC is it a new problem? I am not sure I have touch anything related to this at Community App side recently. Is it a persistent error, or reloading of the page helps to avoid it? Any additional detatils on the error in console and network trace tool?

**Comment by birdofpreyru** [comment]
@ajefts it might be either a bug in Community App itself, or some problem with auth in `/groups/:GROUP_ID` endpoint for SSO users (this endpoint is called to figure out which groups the users belong to, thus which communities should be accessible to them).

**Comment by nithyaasworld** [comment]
@RiteshTC It is not happening any more. Please re-open if this happens again. Thanks.

![image](https://user-images.githubusercontent.com/5114190/60045714-242a3800-96e3-11e9-950c-bfafeab26ce0.png)
