### ISSUE TITLE
Setup CS commnunity

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#790]
Create a clone of topgear.topcoder.com.

Name:  cs.topcoder.com
Parent group id: TBD
Branding: Will be attached shortly
Pages:  Home, Learn, Challenges, FAQ

**Comment by birdofpreyru** [comment]
@ajefts placeholder is setup both in dev and prod:
https://community-app.topcoder-dev.com/community/cs
https://community-app.topcoder.com/community/cs
it looks like the dedicated sub-domain is not yet configured in either of environments
