### ISSUE TITLE
Challenge Details Header and Tabs Updates

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#793]
Here's the updates as we talked about challenge details page: https://www.dropbox.com/s/p5w93arkbvnygze/Challenge%20Details%20Updates.zip?dl=0

1. Header: different states for different track
2. Registrants tab: added photos
3. Checkpoint tab: removed the left column
4. Winners tab: reduce white space on winners and there are no more gray side lines
5. Final Fix tab: new one - important to add as when final fix is submitted it triggers in Direct next phase and right now members can upload them only in OR or old Studio site
6. Challenge Forum link: moved to the right + arrow

Let me know if you have any questions/need icons, etc.

**Comment by birdofpreyru** [comment]
The URL above does not work anymore. @Dara-K can you verify that my copy of the file is the most recent and complete version?

[Challenge Details - New Header.zip](https://github.com/topcoder-platform/community-app/files/1967639/Challenge.Details.-.New.Header.zip)

**Comment by Dara-K** [comment]
You can use this link:
https://github.com/topcoder-platform/community-app/files/1967639/Challenge.Details.New.Header.zip
