### ISSUE TITLE
Cannot make payments for a project

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/community-app#796]
I am trying to use https://community-app.topcoder.com/sandbox/payments for making payments for one of my projects.

The project in question is [Wipro Synergy - Campus Recruitment App](https://www.topcoder.com/direct/projectOverview.action?formData.projectId=14696)

When I load the page and then select the project, the page does not show anything after indicating that it is trying to load.

The error in console [points to this url](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=) describing the error that occurred.

**Comment by birdofpreyru** [comment]
@ajefts @cwdcwd can you give me access to the project in question, so I can debug it? Cause, all projects I am involved in currently work fine with the tool.

**Comment by birdofpreyru** [comment]
Presumably, fixed by 414506a68f9811de92113e920bc8f1779955b5b1

**Comment by callmekatootie** [comment]
:+1: Confirmed. Works now
