### ISSUE TITLE
SMP - Challenge preview and screening/review status

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#8]
Current version of SMP shows dummy submission previews and no screening / review status info.
The core problem is that TC API v3 does not allow to fetch challenges yet (or have we failed to find the right endpoints?) and TC API v2 does not provide previews and screening / review info.

**Comment by birdofpreyru** [comment]
@ajefts Any chances to get this functionality any soon?

**Comment by ajefts** [comment]
@birdofpreyru  For "fetching challenges", what data do you need?

For previews, did you try endpoints like this in v2?  https://api.topcoder.com/v2/design/download/236613?submissionType=preview&submissionImageTypeId=29

If not, short term patch might also be to use the legacy urls for previews:  https://studio.topcoder.com/?module=DownloadSubmission&sbmid=236611&sbt=full&sfi=1

**Comment by birdofpreyru** [comment]
@ajefts
>  For "fetching challenges", what data do you need?

My misprint. I meant "fetching submissions with API v3". In particular, fetching screening status and any related info is what we are missing.

**Comment by ajefts** [comment]
@birdofpreyru Can you point me to the latest page design please?

**Comment by birdofpreyru** [comment]
@ajefts Yeap. Download this: https://drive.google.com/open?id=0B3y3SEA9cIEkTTBYYVRycmhTSTg
And look inside `/Design-and-Assets` folder inside that .zip

**Comment by ajefts** [comment]
thanks.  For now, let's leave out that status until we get it added to the API response...

**Comment by birdofpreyru** [comment]
Yeah, absence of that field in API response does not break the prototype, it just hides that column (this way it is compatible with development challenges, which won't have that screening info).

**Comment by birdofpreyru** [comment]
UPDATE: In the commit https://github.com/topcoder-platform/community-app/commit/960680269eb4de2f173954d5b48755dd872ec21b previes has been added with use of legacy (Studio) API.
