### ISSUE TITLE
Veterans Community Sign Up

### ISSUE THREAD

**Issue by dustinWeaver** [topcoder-platform/community-app#800]
Currently, when a person signs up to the Veterans Community, they are redirected to the standard TC signup form.  However, a requirement of being able to compete in challenges within the Veterans Community is that one be a US Vet or Active Duty.  As such, I'd like for us to change the process so that we ask for the following information before letting someone signup:

- Branch

- MOS (Military Occupation Code)

- Unit

Would be preferred if we could store this information with a person's profile so that the copilots and CAs could view this information as needed.

**Comment by birdofpreyru** [comment]
@cwdcwd @dustinWeaver just to confirm, that if you can setup up a dedicated Docusign agreement for them, and you are able to collect those data from signed Docusign agreements, then it is super easy to demand signing that agreement at Community App side.
