### ISSUE TITLE
Unable to scroll the Terms and Conditions page

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#803]
User cannot scroll the Terms and Conditions page, have to use tab key to navigate the page. Facing issues on both Mac(Firefox) and Windows(Edge) machine.

Steps to reproduce.

1. Visit veterans.topcoder.com in Firefox.
2. Click on Join Now.
3. Click on Login and enter the credentials.
4. Unable to scroll the Terms and Condition page.
5. Please check this video to validate above given steps  https://www.screencast.com/t/LTYyqsUAx

@birdofpreyru @ajefts

**Comment by ajefts** [comment]
@birdofpreyru please let me know if you can address these.  Thanks.

**Comment by birdofpreyru** [comment]
Fixed by 28d576fdf9ee4fea5f5d4b2298fd15ff2c0ee60a
