### ISSUE TITLE
Re-direct after clicking "Finish" from the docusign form is slow 

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#804]
Steps to reproduce:

1. Go to veterans.topcoder.com
2. Click on Join Now.
3. Login with the credentials.
4. Click on checkbox next to "I agree" on Terms and Condition page.
5. Click on Continue.
6. Fill in the required details.
7. Add your signature to docusign.
8. Click on Finish button.
9. Please check this video to validate above given steps: https://www.screencast.com/t/WXGVwkkF1WOg

@birdofpreyru @ajefts

**Comment by birdofpreyru** [comment]
@skyhit @sushilshinde @ajefts this is API-related problem: when we agree with DocuSign terms, at the moment there is a significant time gap between the actual agreement and the agreement status update inside TC backend; so, Community App, has to wait until the TC backend updated the status of all agreed terms, and for that it waits and repeatedly checks the agreement status (at most 5 attempts with 5 sec delay, if after the last attempt the status is not updated yet, the registration operation is canceled).

Of course, originally this logic comes from challenge registration, where, if we call registration endpoint before the TC has updated the status of terms agreement, it will fail. For communities registration, I believe, we can just ignore this (cause underlying self-joining to user groups, I believe, does not check the terms in the api yet); but does not look like a proper solution of the problem.

**Comment by nithyaasworld** [comment]
Issue video: 
[terms issues.zip](https://github.com/topcoder-platform/community-app/files/3312992/terms.issues.zip)
