### ISSUE TITLE
DEV - For Zero prizes on MM, column should be empty

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#816]
Just like current production (https://www.topcoder.com/challenges?filter[tracks][datasci]=true), if the prizes aren't present for MM, the column shouldn't show anything. Currently, on DEV, they are showing zero prizes for MMs.

**Comment by birdofpreyru** [comment]
Fixed in 2d1a6fd2144af33e041a67b1f9ca1dff8f453f86 (deployed to dev)
