### ISSUE TITLE
Add new community

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#82]
Please add another community.  For now, just call it community2.  The ID is 20000002.

Let's set it up to be private, like the wipro community. So, it should require login and auth to access the site.

**Comment by ajefts** [comment]
@birdofpreyru Mind doing this one?

**Comment by birdofpreyru** [comment]
@ajefts No problem, I'll add it tomorrow :)

**Comment by birdofpreyru** [comment]
@ajefts Added: 84671f5581fea4fac8cc2b4b3e23abf24b84c904
