### ISSUE TITLE
Payments App - Add Technologies Tags

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/community-app#830]
A lot of us use the payments app now to pay out bug bash winners and stuff like that. Associating technologies with the tickets will help maintain the technologies used, so we can utilize it in the heatmap, etc.

Just include the same type-search technologies widget that's available on a challenge in direct.

**Comment by birdofpreyru** [comment]
Issue moved to [topcoder-payment-tool](https://github.com/topcoder-platform/topcoder-payment-tool) repo.
