### ISSUE TITLE
Should we additionally mark sub-community challenges / payment tasks in the challenge listing?

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#836]
Say, I open the main challenge listing. In addition to the public challenges, that are visible to everybody, I may see there stuff with restricted visibility: private tasks, payments, challenges from private communities - lot's of stuff visible only to some members. At the moment there is no any visual hint about it, and I think we need it. Probably, additional tag for such challenge cards (with sub-community title / or task / payment label)? Or, just a small band / dot in the card, which message this information via a color code?

@Dara-K @ajefts

**Comment by Dara-K** [comment]
For communities and private tasks, how about we add those to the right side filter panel?

I don't think payment should belong to challenges page, where we have contests and private tasks.

**Comment by birdofpreyru** [comment]
> I don't think payment should belong to challenges page, where we have contests and private tasks.

Yeah, but at the moment payments and tasks are technically the same.

> For communities and private tasks, how about we add those to the right side filter panel?

Problem is not that I cannot filter them out with existing filters, if I want to. The problem is that looking at the listing, without any filters applied, it is easy to forget that some stuff is not visible to everybody.

Real life story: yesterday I saw in the listing a challenge with a cool name from Veterans community, which is not visible to non-members. Then I saw that Slack bot did not post it into dev challenges channel, so I put a link there myself. And only then ppl told me that: hey, not everybody can see it.

**Comment by Dara-K** [comment]
As we talked on Slack, the best is to use an icon for showing private challenges. I have attached a SVG icon and the preview here.
![challenge listing - private challenge](https://user-images.githubusercontent.com/25185079/39772006-b62e80b6-52fc-11e8-8865-d7a138ee3086.png)

[lock-icon.zip](https://github.com/topcoder-platform/community-app/files/1984954/lock-icon.zip)
