### ISSUE TITLE
New Badge needed for Marathon Match 100

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#838]
A new badge CSS Badge is required for Marathon Match 100 . eg the similar to one created for TCO 17 finalist. 
//CSS Excerpt
{ 
id: 1010, 
name: 'TCO17 Finalist', 
groupClass: 'TCO17-Finalist', 
active: false 
}, 

name = Marathon Match 100
SVG file is available here.
https://drive.google.com/file/d/1l5Jidngj_T6ERjWF00JouhWdvJEcXTMC/view?usp=sharing

**Comment by RiteshTC** [comment]
@ThomasKranitsas I think you did the TCO 17 one. Can you take this one ?
cc @urwithat

**Comment by ThomasKranitsas** [comment]
@RiteshTC I did the badges in the https://github.com/appirio-tech/topcoder-app/ repo.

I'm working on moving the user profile page from the topcoder-app to community-app but we're not ready yet.

I can temporarily add the Marathon Match 100 badge on the legacy code if that helps.

**Comment by ThomasKranitsas** [comment]
@RiteshTC I've completed this.

The details for the new badge are:

```
{
  id: 1014,
  name: 'Marathon Match 100',
  groupClass: 'MM100',
  active: false
}
```

@urwithat should I launch a small F2F to fix the badges in the community-app as well?

**Comment by ThomasKranitsas** [comment]
@birdofpreyru what kind of badges should we show in the header?

I only see the `Predix` and the `TCO17` badges in my dashboard by I have more

**Comment by birdofpreyru** [comment]
@ThomasKranitsas I think all that looks like separate icons (even if taken from the sprite image).

**Comment by RiteshTC** [comment]
@ThomasKranitsas 
It looks like the badges are not showing up. Is there anything missing that needs be done in db or UI
Can you please check ?
eg these members show the TCO17 Badge but not the MM100 one.
https://www.topcoder.com/members/sdya/
https://www.topcoder.com/members/scott_wu/

**Comment by ThomasKranitsas** [comment]
@RiteshTC the `Marathon Match 100` should be added to the members `Achievements`.

If you check this https://api.topcoder.com/v2/users/scott_wu/ the `Marathon Match 100` is missing.

**Comment by RiteshTC** [comment]
Thanks @ThomasKranitsas for the api link. 
This has been resolved now.
