### ISSUE TITLE
Challenge Listing: Sorting of past challenges

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#842]
Current sorting order, by default, seems to be by the start date. It is confusing, cause the end dates are written in the challenge cards. Better sort them by the end date.

https://github.com/topcoder-platform/community-app/issues
![image](https://user-images.githubusercontent.com/20144632/39920395-38be7ccc-5517-11e8-90da-3cab30a74617.png)

**Comment by nithyaasworld** [comment]
@birdofpreyru Currently the newly launched challenges are displayed at the top which looks good to me.

If we sort by end-date, we will have newly launched challenges in between the other challenges, and user might miss noticing it.

Your thoughts please?

**Comment by nithyaasworld** [comment]
@birdofpreyru Closing this. Please feel free to re-open if needed.
