### ISSUE TITLE
Community App changes for Direct MM

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#845]
For MMs like these

track: "DEVELOP",
subTrack: "DEVELOP_MARATHON_MATCH"

We need 

1. From community app details page registration should be done same flow as develop challenge.
2. From community app details page submission button should take a user to a new submission pages same as develop. And submit to the same endpoint as develope. This submission page should be new and exact copy of the develop submission page. I will make changes to text copy. 
3. Button colors should represent registration, registration and submission states
4. All the other details tabs should be similar to develop challenges (Registrant, submission, forum tabs)

Branch to be used : 
https://github.com/topcoder-platform/community-app/tree/mm-feature-experiment

**Comment by birdofpreyru** [comment]
@sushilshinde done.

**Comment by sushilshinde** [comment]
Thanks, @birdofpreyru.

I have done fixes for button statuses. Only thing I was not able to figure out after the submission there is an error, which is not a serverside error. Please have quick look at it.

![capture](https://user-images.githubusercontent.com/683231/40107191-36e508ce-5915-11e8-8acf-9a3588761b50.PNG)
