### ISSUE TITLE
Make community sites contentful

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#846]
Let's make parts of the various community sites contentful, starting with the expert communities.

General requirement:  As much as possible, our standard template site should be contentful so we can handle most of the content setup via contentful.

Let's start with blockchain.topcoder.com as the first example:

![image](https://user-images.githubusercontent.com/3812270/40001418-28c852d8-575c-11e8-8b4c-8ca587e21ae9.png)

1. Header: Specify the menu items.

3. Banner Area
4-6. Main content stack: Allow the user to add 1 or more sections that stack on top of each other here.
7. Stats area:  Include/exclude the member count, prize $, challenge count section.

**Comment by Oanh-and-only-Oanh** [comment]
WIP with other projects/open tickets. Duplicate so closing
