### ISSUE TITLE
Responsive review opportunities page

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#853]
Can we make this page responsive and mobile friendly?
It is quite annoying to see such broken page and need login from desktop just to read review details or apply for review position.
![screenshot from 2018-05-17 08-54-35](https://user-images.githubusercontent.com/5585002/40159458-18123802-59b2-11e8-9de8-a5ac8e062c7e.png)
![screenshot from 2018-05-17 08-54-45](https://user-images.githubusercontent.com/5585002/40159463-1c2398f0-59b2-11e8-9771-7110d8bcda0d.png)

**Comment by ajefts** [comment]
@ThomasKranitsas Do you have time to run this without interfering with other projects?  If not, I think @kkartunov can probably run it too...

**Comment by ThomasKranitsas** [comment]
@ajefts I already have all required assets for this so I can launch it in the next minutes

**Comment by ajefts** [comment]
ok

**Comment by ThomasKranitsas** [comment]
The challenge was completed. I have the code but it needs some fixes.

**Comment by ajefts** [comment]
@ThomasKranitsas let's get it wrapped up please.

**Comment by ThomasKranitsas** [comment]
Fixed
