### ISSUE TITLE
Review Opportunities doesn't gracefully handle completed Challenges

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#859]
If a challenge has reviewers already assigned or is completed, the review opportunity page throws a 504 Gateway error.

eg 
https://www.topcoder.com/challenges/30065688/review-opportunities

Expected:
A message stating the user, the challenge is no longer accepting reviewers or is completed. 

@ThomasKranitsas 

cc @ajefts

**Comment by ThomasKranitsas** [comment]
@ajefts should we return the review opp details and just show a message that this opp is not available or should the backend return 404 NOT FOUND for completed review opps?

**Comment by ajefts** [comment]
@ThomasKranitsas Yes, I like  your approach.

**Comment by ThomasKranitsas** [comment]
Fixed
