### ISSUE TITLE
Merge `new-settings-profile` into `new-develop` branch

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#860]
@dedywahyudi ok, we have more problems with it:

In parallel with implementation of Profile Settings page, we have spawned out various actions / reducers / services into the stand-alone library, [topcoder-react-lib](https://github.com/topcoder-platform/topcoder-react-lib). Profile Settings code modifies some of the moved stuff; thus, we should move such updates to the *topcoder-react-lib*, and then update the Profile Settings page doing:
- Merge *new-develop* branch into *new-settings-profile*;
- Resolve merge conflicts;
- Update *topcoder-react-lib* version;
- Test everything / fix any bugs;
- Finally, merge *new-settings-profile* into *new-develop*.

Will you take care about this?

**Comment by dedywahyudi** [comment]
@birdofpreyru 
Okay, this look like lot things to do :)
But, I'll send back the updates later for any questions.

**Comment by dedywahyudi** [comment]
@birdofpreyru
It look we need update topcoder-react-lib first to contains any action/reducers/service for new-settings-profile. 

Can you help create new branch for testing on topcoder-react-lib ?

**Comment by birdofpreyru** [comment]
@dedywahyudi do you mean, you don't have write access to that repo? I have added you as collaborator, now you should be able to create new branches there yourself.

I recommend to handle both update of *topcoder-react-lib* and *community-app* within the same task/challenge, this way it can be easily seen whether the lib's update works properly, or not.

Btw, the commit `e780c4df4d05f6cf574e943101856095cdf7ae8f` is the fork point where the stuff was moved to the lib. From comparison of the latest profile settings with that commit it should be quite easy, technically, to find out what modifications should be done in the lib.

**Comment by dedywahyudi** [comment]
Cool, thanks for adding me! 

Okay, noted about to handle both update of topcoder-react-lib and community-app within the same task.
