### ISSUE TITLE
Improve free-text search of challenges

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#861]
*See https://github.com/appirio-tech/topcoder-app/issues/1310*

Actually, the free-text search of challenges works, but it works sub-optimally, especially for past challenges, and should be improved. We sure talked about it multiple times, let's check again whether we can improve it now?

@ajefts @skyhit does the challenge API support filtering by text (current front-end implementation search for entered text inside challenge name and platfrom/tech tags, like this: https://github.com/topcoder-platform/topcoder-react-lib/blob/master/src/utils/challenge/filter.js#L153).

**Comment by rsial2** [comment]
Hey @birdofpreyru this does not work - if you try to search for "intel" or "movidius" (which are both past challenges), you will not get any results. So it is a true defect.

**Comment by cwdcwd** [comment]
@birdofpreyru https://api.topcoder.com/v3/marathonMatches/?filter=name%3DMovidius&limit=50 works for name based searching

**Comment by nithyaasworld** [comment]
Again, the search function seems to be not working as expected.

Searching for _fun_  is not fetching past fun challenges
