### ISSUE TITLE
Challenge Navigation Via Query String Doesn't work properly

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/community-app#872]
While navigating to REGISTRANTS tab using query string (https://www.topcoder.com/challenges/30065205?tab=registrants) is not showing REGISTRANTS tab, but it shows DETAILS tab. Similarly navigating below links with different tab using query string is not working, but it loads DETAILS tab. Please could you look at this issue.

Challenge tab links:
REGISTRANTS: https://www.topcoder.com/challenges/30065205?tab=registrants
SUBMISSIONS: https://www.topcoder.com/challenges/30065205?tab=submissions
WINNERS: https://www.topcoder.com/challenges/30065205?tab=winners

@birdofpreyru

**Comment by birdofpreyru** [comment]
Fixed
