### ISSUE TITLE
Manage Submission Page - Actions Mot Working

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#879]
On Manage Submission Page the delete and expand icons are not working anymore.
![screenshot 2018-06-06 16 43 38](https://user-images.githubusercontent.com/25185079/41035741-438a140c-6996-11e8-92d2-72f1220425d9.png)

**Comment by birdofpreyru** [comment]
Was duplicated in #887, closing this ticket, to take care about the issue there.
