### ISSUE TITLE
Veterans Site new photos

### ISSUE THREAD

**Issue by jmpld40** [topcoder-platform/community-app#882]
We need to update the photos on the veterans community site. please use the following ones instead.
[fwdfwistockimagesfortopcoderveterans.zip](https://github.com/topcoder-platform/community-app/files/2077169/fwdfwistockimagesfortopcoderveterans.zip)

**Comment by ajefts** [comment]
@birdofpreyru let's switch this to contentful if we can please...

**Comment by birdofpreyru** [comment]
@ajefts serving the main content blocks (_Why We Started_, _How the Topcoder Veterans Community Works_, _The Topcoder Team is Here to Help_) - is easy (we already have necessary components / themes). Header banner, quote block, active challenge, and two cards in the bottom - these will need additional coding.

For the quote block, we'll need to coordinate with @kkartunov, as he was going to make IoT contentful, and there was similar quote block as well.

**Comment by jmpld40** [comment]
hey @ajefts @birdofpreyru can we get this done asap? thanks much

**Comment by birdofpreyru** [comment]
@jmpld40 

Check this out: https://community-app.topcoder-dev.com/__community__/veterans

I have "contentfulized" the page, so further corrections can be done here: https://app.contentful.com/spaces/b5f1djy59z3a/entries/40IAAw08Z2meqMu24CEM0O

**Comment by Oanh-and-only-Oanh** [comment]
closing tickets dated 07/2017 and back
