### ISSUE TITLE
Make BSIC page on blockchain contentful

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#885]
We'd like to be able to manage the content on this page.

**Comment by ajefts** [comment]
We were looking to change the blocks in the "Get Started" section first.  I assume that is one of the parts that requires some more work to define the content models?

**Comment by ajefts** [comment]
For the other parts (banner, text blocks) we can convert them to our standard components and adjust the content.   We can ignore the FAQ for now.

**Comment by birdofpreyru** [comment]
Yes, it will require some more work. I guess, no need for new content types, but a careful update of the already existing Viewport and ContentBlock should do it.
