### ISSUE TITLE
Make IoT community accessible via the dedicated sub-domain

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#886]
@birdofpreyru @ajefts 
How can we make IoT community to load from iot.topcoder.com domain?
The `subdomains` config is set in `metadata.json` See: https://github.com/topcoder-platform/community-app/blob/new-develop/src/server/tc-communities/iot/metadata.json#L37 but currently when one navigates to the it only `DNS_PROBE_FINISHED_NXDOMAIN` is returned.
As the IoT community has landed to production it is bad to have it in the "communities" drop down menu but redirect to not working domain.

**Comment by kkartunov** [comment]
![screenshot from 2018-06-07 09-44-22](https://user-images.githubusercontent.com/5585002/41082806-27e077f8-6a38-11e8-887a-16a6514a5a25.png)

**Comment by birdofpreyru** [comment]
I believe, @ajefts or somebody else from dev team should update Nginx routing for the community.

**Comment by kkartunov** [comment]
Wo
