### ISSUE TITLE
Delete and expand icons in view submission page don't work.

### ISSUE THREAD

**Issue by JayaDhaka** [topcoder-platform/community-app#887]
Delete and expand icons in view submission page don't work. Please check and resolve.

The page link is: https://www.topcoder.com/challenges/30065798/my-submissions 

![inkedscreenshot 2018-06-07 09 26 11_li](https://user-images.githubusercontent.com/34749364/41082731-e636bcc6-6a4c-11e8-99a5-afe4c136ae0d.jpg)
@birdofpreyru

**Comment by birdofpreyru** [comment]
Presumably fixed, but I was not able to carefuly test the delete button functionality. @Dara-K can you try it on some design challenge in prod website?

**Comment by Dara-K** [comment]
The  2 icons work now but the modal window is not well styled. Check below. 
![modal](https://user-images.githubusercontent.com/25185079/41473595-652cf150-70c2-11e8-9953-639c9c56a19d.png)
