### ISSUE TITLE
Can't connect to dropbox, upload submission page

### ISSUE THREAD

**Issue by iammtong** [topcoder-platform/community-app#888]
Can't connect to dropbox, upload submission page
![screenshot 2018-06-08 11 23 05](https://user-images.githubusercontent.com/40050596/41139022-49f7a4f6-6b0f-11e8-8513-bd2017de83b6.png)
![screenshot 2018-06-08 11 22 55](https://user-images.githubusercontent.com/40050596/41139023-4a394da2-6b0f-11e8-99cd-6d570d401315.png)

**Comment by birdofpreyru** [comment]
@iammtong was it working recently at all?

@ajefts my current guess is that we miss some Dropbox-related configuration in our Filestack account, as per these instructions: https://www.filestack.com/docs/dropbox-integration Wanna fix it?

**Comment by iammtong** [comment]
It was my first time trying to connect with dropbox, not sure if it was working earlier.

Thanks
Tong

On 12 Jun BE 2561, at 06:52, Dr. Sergey Pogodin <notifications@github.com<mailto:notifications@github.com>> wrote:


@iammtong<https://github.com/iammtong> was it working recently at all?

@ajefts<https://github.com/ajefts> my current guess is that we miss some Dropbox-related configuration in our Filestack account, as per these instructions: https://www.filestack.com/docs/dropbox-integration Wanna fix it?
