### ISSUE TITLE
Save button will not be enabled after changing the new profile pic

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#891]
Summary:
Save button will not be enabled after changing the new profile pic
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/profile/
2. Update a new photo on  the existing profile pic

### Expected Result ###

Save button will not be enabled after changing the new profile pic

### Actual  Result ###

* Save button should be enabled after changing the new profile pic

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41176680-f56e7246-6b7e-11e8-96ac-6af090631430.png)
![image](https://user-images.githubusercontent.com/31862600/41176688-ff17ca9a-6b7e-11e8-8dfb-c08085d40642.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
