### ISSUE TITLE
ADD A NEW SKILL RESULTS NOT WORKING.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#893]
Summary:
ADD A NEW SKILL RESULTS NOT WORKING.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/profile/
2. GO to NEW SKILL TEXT BOX
3.TYPE JAVA

### Expected Result ###

ADD A NEW SKILL SHOULD RESULt THE MATCHING SKILLS.

### Actual  Result ###

ADD A NEW SKILL RESULTS NOT WORKING.

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41176797-7066b30a-6b7f-11e8-9b3e-93b9ad69d377.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by youdare** [comment]
@ThomasKranitsas  
We have duplicate issue Need to close this issue #932

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
