### ISSUE TITLE
[$20] ABLE TO ADD INVALID OR INVALID FORMAT WEB URL IN ADD A WEB LINK.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#894]
Summary:
ABLE TO ADD INVALID OR INVALID FORMAT WEB URL IN ADD A WEB LINK.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/profile/
2. GO to ADD A WEB LINK TEXT BOX
3.ENTER WWW.GOOGLE AND CLICK ADD BUTTON

### Expected Result ###

SHOULD NOT ALLOW TO ADD INVALID OR INVALID FORMAT WEB URL IN ADD A WEB LINK.

### Actual  Result ###

ABLE TO ADD INVALID OR INVALID FORMAT WEB URL IN ADD A WEB LINK.

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069484 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069484 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas right now the Add A Web Link box already check the invalid url can you check that?

**Comment by suppermancool** [comment]
fixed in https://github.com/topcoder-platform/community-app/pull/1194, pls check, thanks

<img width="753" alt="screen shot 2018-08-15 at 7 47 25 pm" src="https://user-images.githubusercontent.com/5815182/44149895-df10f996-a0c7-11e8-9d55-f20e18c8fb4a.png">

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069484 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069484
