### ISSUE TITLE
text 'User Avatar' is shown

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#896]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###
1. login as pshah_manager, open https://apps.topcoder-dev.com/forums/?module=Settings

2. observe top right

### Expected Result ###
Should not show 'User Avatar' text
### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1438" alt="3" src="https://user-images.githubusercontent.com/4590317/41177306-1ca7d598-6b96-11e8-8afe-e3041d9ab7cf.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
