### ISSUE TITLE
ABLE TO CHANGE PASSWORD WITH SAME current password as” topcoder123” and New password as “topcoder123”

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#897]
Summary:
ABLE TO CHANGE PASSWORD WITH SAME current password as” topcoder123” and New password as “topcoder123”
### Reported URL ###
https://www.topcoder-dev.com/settings/account/
### Log In Used ###
pshah_manager/ 	 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/account/ 
2. Enter current password as” topcoder123” and New password as “topcoder123”
3.CLICK “CHANGE PASSWORD” BUTTON

### Expected Result ###

SHOULD NOT ALLOW TO CHANGE PASSWORD WITH SAME current password as” topcoder123” and New password as “topcoder123”
Current and New password should be different

### Actual  Result ###

ABLE TO CHANGE PASSWORD WITH SAME current password as” topcoder123” and New password as “topcoder123”

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
ABLE TO CHANGE PASSWORD WITH SAME current password as” topcoder123” and New password as “topcoder123”
![image](https://user-images.githubusercontent.com/31862600/41177392-86776458-6b81-11e8-8713-e6ca37996f7c.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
