### ISSUE TITLE
ZIPCODE FIELD SHOULD NOT ALLOW TO TAKE CHARACTER AS INPUT 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#899]
Summary:
ZIPCODE FIELD SHOULD NOT ALLOW TO TAKE CHARACTER AS INPUT 
### Reported URL ###
https://www.topcoder-dev.com/settings/account/
### Log In Used ###
pshah_manager/ 	 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/account/ 
2. Go to Address enter all fields  and in zip code field enter “ASDF”
3.Click Save button

### Expected Result ###

ZIPCODE FIELD SHOULD NOT ALLOW TO TAKE CHARACTER AS INPUT 

### Actual  Result ###
ZIPCODE FIELD IS ALLOWING TO TAKE CHARACTER AS INPUT 
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41177587-49128394-6b82-11e8-9179-d3c6c41a4177.png)

**Comment by youdare** [comment]
Note : All Address field validation is getting failed , Need to fix entire section

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
