### ISSUE TITLE
SMP - Submission download does not work

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#9]
**A comment to winning submission tells**
> there's an endpoint in v2 (`/v2/{type}/download/{submId}?submissionType=original`) that states it lets you download a specific submission, doesn't seem to work

Probably it works, but submitter made some auth-related mistake?

**Comment by birdofpreyru** [comment]
@ajefts What do you think about it? Should be working in API v2, if called correctly, right?

**Comment by ajefts** [comment]
I think that's an untested endpoint in v2.  Ideally, we need to get that built in v3.  

In the short, short term we may need to use the legacy download controller...

https://studio.topcoder.com/?module=DownloadSubmission&sbmid=236660

**Comment by birdofpreyru** [comment]
@ajefts FYI: I've double-checked it. Submission downloading with API v2 seems to be non-functional, indeed. The following error message is reported:
```
description: "The request was invalid. An accompanying message will explain why."
details: "connection should be object"
name: "Bad Request"
value: 400
```

I'll fallback for the legacy download controller for now.

**Comment by ajefts** [comment]
Ok.  FireIce is also running a challenge to get the endpoint added to v3.

**Comment by birdofpreyru** [comment]
UPDATE: In the commit https://github.com/topcoder-platform/community-app/commit/960680269eb4de2f173954d5b48755dd872ec21b submission download is fixed with use of legacy (Studio) API.
