### ISSUE TITLE
click on the text should select the radio button

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#900]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###
1. login as pshah_manager, open https://apps.topcoder-dev.com/forums/?module=Settings

2. In General Settings tab, click on the text 'No' of any of last 3 radio buttons,

3. observe

### Expected Result ###
click on the text should select the radio button

### Actual Result ###

See screenshot, won't select the radio button

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="988" alt="5" src="https://user-images.githubusercontent.com/4590317/41177589-3fc59046-6b97-11e8-9a44-5633727b70dc.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
