### ISSUE TITLE
Profile picture is not getting loaded in the Forum preference.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#901]
Summary:
Profile picture is not getting loaded in the Forum preference.
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Forum preference

### Expected Result ###

Profile picture should get loaded in the Forum preference.

### Actual  Result ###
Profile picture is not getting loaded in the Forum preference.
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41177743-ce4335b8-6b82-11e8-8788-8d2d4b05e191.png)

**Comment by youdare** [comment]
Note;- This issue is seen in all preference pages

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
