### ISSUE TITLE
cannot save email address of Paypal account

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#902]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###
1. login as pshah_manager, open https://www.topcoder-dev.com/settings/preferences/

2. click Payment Preferences, enter test@test.com as Paypal account email address, click Save

3. observe

### Expected Result ###
should save the address

### Actual Result ###

See screenshot, it does not save

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="953" alt="6" src="https://user-images.githubusercontent.com/4590317/41177830-0998ca5a-6b98-11e8-9137-e3bd481c5ba9.png">

<img width="891" alt="6 2" src="https://user-images.githubusercontent.com/4590317/41177857-19ed8c1a-6b98-11e8-8df8-02684151dae0.png">

Also, the URL is changed to https://community.topcoder-dev.com/tc after saving.

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
