### ISSUE TITLE
Save button is enabled when there is no change in the Forum preference.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#903]
Summary:
Save button is enabled when there is no change in the Forum preference.
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Forum preference
3.Scroll down and click save button

### Expected Result ###

Save button is enabled when there is no change in the Forum preference.

### Actual  Result ###
Save button is enabled when there is no change in the Forum preference.
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41177899-3c8381c2-6b83-11e8-855f-16e4ca5472df.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
