### ISSUE TITLE
Getting error message as “Apps.topcoder-dev.com says -XSS” while clicking “Forum” link in the Forum preference page

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#904]
Summary:
Getting error message as “Apps.topcoder-dev.com says -XSS” while clicking “Forum” link in the Forum preference page
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Forum preference
3.Click “Forum Link

### Expected Result ###

Should navigate to forum section

### Actual  Result ###
Getting error message as “Apps.topcoder-dev.com says -XSS” while clicking “Forum” link in the Forum preference page
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41178018-a8ae9954-6b83-11e8-87ff-2912bf2dbaa8.png)


![image](https://user-images.githubusercontent.com/31862600/41178007-9b97de60-6b83-11e8-8880-3c1eaf3441e3.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
