### ISSUE TITLE
page height should be increased on visa selection page

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#905]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=VisaSelection

### Reproduction Steps ###
1. login as pshah_manager, open https://community.topcoder-dev.com/tc?module=VisaSelection

2. observe

### Expected Result ###
page height should be increased on visa selection page

### Actual Result ###

See screenshot, it looks not good

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1435" alt="h" src="https://user-images.githubusercontent.com/4590317/41178013-9938b472-6b98-11e8-886b-f374ed0f2935.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
