### ISSUE TITLE
No need to show table header if there is no data

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#906]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=ViewReferrals

### Reproduction Steps ###
1. login as pshah_manager, open https://www.topcoder-dev.com/settings/preferences/
2. click Referrals, observe

### Expected Result ###
No need to show table header if there is no data

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1343" alt="7" src="https://user-images.githubusercontent.com/4590317/41178114-dfb5fcd4-6b98-11e8-974d-ed642887939b.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
