### ISSUE TITLE
too much empty space on the page

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#907]
### Reported URL ###
https://www.topcoder-dev.com/members/TonyJ/details/?track=DESIGN&subTrack=WIDGET_OR_MOBILE_SCREEN_DESIGN

### Reproduction Steps ###
1. open https://www.topcoder-dev.com/members/TonyJ/details/?track=DESIGN&subTrack=WIDGET_OR_MOBILE_SCREEN_DESIGN, observe

### Expected Result ###
Should not have too much empty space

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1412" alt="8" src="https://user-images.githubusercontent.com/4590317/41178182-15b1874a-6b99-11e8-9c1b-eb72789ed7d9.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
invalid issue
