### ISSUE TITLE
No Confirmation message is displayed while saving user setting of Forum preference

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#908]
Summary:
No Confirmation message is displayed while saving user setting of Forum preference
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Forum preference
3.Change 2 or 3 setting and click Save button

### Expected Result ###

Some  Confirmation message should be displayed while saving user setting of Forum preference

### Actual  Result ###
No Confirmation message is displayed while saving user setting of Forum preference
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41178267-66ce0b90-6b84-11e8-94c6-cc4b540e5ca1.png)
![image](https://user-images.githubusercontent.com/31862600/41178288-72f40cda-6b84-11e8-9947-b47ac0f87d90.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
