### ISSUE TITLE
CURRENT PASSWORD is not loaded correctly

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#909]
### Reported URL ###
https://www.topcoder-dev.com/settings/account/
### Reproduction Steps ###

1. login as pshah_manager, open https://www.topcoder-dev.com/settings/account/
2. click SHOW of 'CURRENT PASSWORD', observe

### Expected Result ###
It should load current user's password

### Actual Result ###

See screenshot, it loads your real password for production TC site actually.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1391" alt="9" src="https://user-images.githubusercontent.com/4590317/41178339-819561b6-6b99-11e8-8e27-e19e8c582148.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
I believe the current password should NEVER be returned by the API.
Returning the decrypted password in the API response is a serious security issue.

**Comment by ThomasKranitsas** [comment]
Closing as it's not a valid issue
