### ISSUE TITLE
empty page shown after clicking the grid icon

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#910]
### Reported URL ###
https://www.topcoder-dev.com/members/pshah_manager/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION&tab=statistics

### Reproduction Steps ###

1. open https://www.topcoder-dev.com/members/pshah_manager/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION&tab=statistics

2. then click the grid icon, observe

### Expected Result ###
It should show all tracks data

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1239" alt="a" src="https://user-images.githubusercontent.com/4590317/41178611-645689f8-6b9a-11e8-84cb-7532c111a059.png">
<img width="1392" alt="b" src="https://user-images.githubusercontent.com/4590317/41178612-6484fcac-6b9a-11e8-9bc6-a247a2cf8ba4.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
duplicate
