### ISSUE TITLE
Broken link in refferal page

### ISSUE THREAD

**Issue by ra304413** [topcoder-platform/community-app#911]
Reported URL:https://community.topcoder-dev.com/tc?module=ViewReferrals

**How to replicate:**
Go to https://community.topcoder-dev.com/tc?module=ViewReferrals and try to click on links for unique URL and official rules.
**Actual Result**:See Screenshot
![page_not_found_referals](https://user-images.githubusercontent.com/40026802/41178682-afa5e3be-6b85-11e8-8779-68c15bef84d7.PNG)
![page_not_found_referals_2](https://user-images.githubusercontent.com/40026802/41178683-afd7d4dc-6b85-11e8-9375-6e17ea374458.PNG)

**Comment by ThomasKranitsas** [comment]
This is not part of the community app. It's part of the legacy site. Closing this ticket
