### ISSUE TITLE
Not able to change the existing email address of PayPal account, getting 504 Gateway Time-out

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#912]
Summary:
Not able to change the existing email address of PayPal account, getting 504 Gateway Time-out

### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Payment preference
3.Go to 	he email address of your PayPal account: and Edit the Email address
4.Click Save button

### Expected Result ###

Should allow to change the existing email address of our PayPal account:

### Actual  Result ###
Not able to change the existing email address of PayPal account, getting 504 Gateway Time-out

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41178765-ec6c11d8-6b85-11e8-95d1-b516f1564676.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by youdare** [comment]
Update- Please  give invalid Email ID, Which is not belong to paypal account

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
