### ISSUE TITLE
How to request Visa Letter link is not working in invitation letter

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#914]
Summary:
How to request Visa Letter link is not working in invitation letter

### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Invitation letter 
3.Click How to request Visa Letter link Invitation letter page

### Expected Result ###

How to request Visa Letter link should work in invitation letter

### Actual  Result ###
How to request Visa Letter link is not working in invitation letter

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41178878-4ad46b58-6b86-11e8-8710-63f52ff541ce.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
