### ISSUE TITLE
Page not found page is getting displayed while clicking Referrals links

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#916]
Summary:
Page not found page is getting displayed while clicking Referrals links

### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/preferences/
2. Click 	Referrals
3.Click link like Keep referring!  And Be sure to read the

### Expected Result ###

Correct page should get displayed while clicking Referrals links

### Actual  Result ###
Page not found page is getting displayed while clicking Referrals links

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41178969-ae0378b8-6b86-11e8-8137-f2ab75e2c1d7.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
