### ISSUE TITLE
gets error if entering long string for CITY

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#917]
### Reported URL ###
https://www.topcoder-dev.com/members/pshah_manager/details/?track=DATA_SCIENCE&subTrack=SRM&tab=statistics

### Reproduction Steps ###

1. login as pshah_manager

2. go to account page: https://www.topcoder-dev.com/settings/account

3. enter a long string (uroewqurioewquriojfdlskajfklajsdlkfjsdakljfklasdjflkjasdlkfjskdlajfklasdjfklsdajfkljslk423141234231423143214jlkj4kl321j4klj321lk4jl12k3j4lkfm,ads.mf,.smf,.sdma,f.md.safm.,asdfsdajfasldjfklasjdkflmas.kf,m,as.dmf.,dasm.f,msa.dfasdfdasfasdf) for CITY, click SAVE

4. observe

### Expected Result ###
1. should set max length for text field
2. no error should be shown 

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1353" alt="acc" src="https://user-images.githubusercontent.com/4590317/41178990-b268a954-6b9b-11e8-964b-9d75d76f100a.png">

p.s. this should be a common case for text field without setting max length.

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
