### ISSUE TITLE
country and state/province should be dropdown list

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#919]
### Reported URL ###
https://www.topcoder-dev.com/settings/account/

### Reproduction Steps ###

1. login as pshah_manager

2. go to account page: https://www.topcoder-dev.com/settings/account/

3. observe

### Expected Result ###
country and state/province should be dropdown list

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="977" alt="12" src="https://user-images.githubusercontent.com/4590317/41179161-4c0ad172-6b9c-11e8-98bb-f5be61618b3b.png">

Should be same as other places.

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
