### ISSUE TITLE
Member search is not working

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#920]
Summary:
Member search is not working 

### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1. Go to https://www.topcoder-dev.com/settings/profile/
2. Click Search button
3.Enter “pshah_Manager” and Give Enter in the keyboard

### Expected Result ###

Member search is not working 

### Actual  Result ###
Member search should work

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
pshah_Manager
![image](https://user-images.githubusercontent.com/31862600/41179191-7919fc52-6b87-11e8-915f-a0a97381b181.png)
![image](https://user-images.githubusercontent.com/31862600/41179207-880325b8-6b87-11e8-9d2a-732a8f484524.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
This is out of scope
