### ISSUE TITLE
HOw to get paid option is not working under Payments

### ISSUE THREAD

**Issue by ra304413** [topcoder-platform/community-app#921]
**Reported URL**:https://community.topcoder-dev.com/PactsMemberServlet?module=PaymentHistory&full_list=false

**How to reproduce**:
1 Go to https://community.topcoder-dev.com/PactsMemberServlet?module=PaymentHistory&full_list=false.
2 Click on How to get paid? link.

**Result**: Attached screenshot

![paid_error2](https://user-images.githubusercontent.com/40026802/41179320-f7ab5638-6b87-11e8-83c5-d13e077e37a5.PNG)
![how_req_visa_not_load](https://user-images.githubusercontent.com/40026802/41179321-f7dc3578-6b87-11e8-8c60-127b467f8029.PNG)
![paid_error1](https://user-images.githubusercontent.com/40026802/41179322-f80b7b9e-6b87-11e8-96dc-1805505e469d.PNG)

OS: Windows 10
Browser:Google chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by ThomasKranitsas** [comment]
This is part of the legacy website and not the community app. Closing this ticket as it's not a valid issue
