### ISSUE TITLE
no need to show table header on forums history page if there is no data

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#923]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=History

### Reproduction Steps ###

1. login as pshah_manager

2. open https://apps.topcoder-dev.com/forums/?module=History

3. observe

### Expected Result ###
should have no layout issues (currently needs to scroll horizontal bar to view all text )

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
