### ISSUE TITLE
[payment preferences] click on the text should select the radio button option

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#924]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. click on the text Payoneer, PayPal or Western Union, observe

### Expected Result ###
click on the text should select the radio button option

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="860" alt="15" src="https://user-images.githubusercontent.com/4590317/41179532-90f4f488-6b9d-11e8-998c-87dcd2f17bfb.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
