### ISSUE TITLE
Challenges are not getting listed

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#925]
Summary:
Challenges are not getting listed

### Reported URL ###
https://www.topcoder-dev.com/members/miketest/details/?track=DEVELOP&subTrack=FIRST_2_FINISH&tab=challenges
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/members/miketest/details/?track=DEVELOP&subTrack=FIRST_2_FINISH&tab=challenges
2.	Click challenges tab
### Expected Result ###
Challenges should get listed

### Actual  Result ###
Challenges are not getting listed

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41179594-d6734bf0-6b88-11e8-9018-c149d3383c41.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
This usually happens when the challenges are private. Not a valid issue.
