### ISSUE TITLE
Payment Methods link is broken

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#926]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. click Payment Methods link, observe

### Expected Result ###
should be working

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="753" alt="pm" src="https://user-images.githubusercontent.com/4590317/41179721-417a52e4-6b9e-11e8-81a0-f315e76fa924.png">


<img width="924" alt="w" src="https://user-images.githubusercontent.com/4590317/41179732-4b1059de-6b9e-11e8-83c7-99166bee93d2.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
