### ISSUE TITLE
page layout issues and button style issue

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#927]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Watches

### Reproduction Steps ###

1. login as pshah_manager

2. open https://apps.topcoder-dev.com/forums/?module=Watches

3. observe

### Expected Result ###
1. should have no layout issues
2. style of Update button should be consistent with other button style

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1437" alt="17" src="https://user-images.githubusercontent.com/4590317/41179856-d0f95988-6b9e-11e8-807f-ff8dc84274fa.png">

**Comment by winterflame** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
