### ISSUE TITLE
[common] copyright year should be updated to 2018

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#928]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=ViewReferrals

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=ViewReferrals

3. observe

### Expected Result ###
copyright year should be updated to 2018

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="848" alt="y" src="https://user-images.githubusercontent.com/4590317/41179976-3d92c98a-6b9f-11e8-9c79-8e57674a2e1f.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
