### ISSUE TITLE
Incorrect display of Bonus for Code Challenges

### ISSUE THREAD

**Issue by sharathkumaranbu** [topcoder-platform/community-app#93]
We don't have bonus for code challenges but the challenge listing page display bonus for code challenges as well when we hover on the prize money column.

See here

![image](https://user-images.githubusercontent.com/7723558/27906690-3b1071cc-6262-11e7-8045-bceda33f056b.png)

**Comment by birdofpreyru** [comment]
@ajefts @skyhit I have checked it: it looks like, even we do not have reliability bonus for code challenges, backend still includes non-zero `reliabilityBonus` field into challenge objects it returns. Should be checked inside the backend.

**Comment by ajefts** [comment]
@skyhit Can you run an api fix for this one?
