### ISSUE TITLE
[common] click on text of checkbox should select/deselect the checkbox

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#930]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###

1. login as pshah_manager

2. open https://apps.topcoder-dev.com/forums/?module=Settings, play with some checkbox by clicking its text

3. observe

### Expected Result ###
should be able to select/deselect the checkbox

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1063" alt="ch" src="https://user-images.githubusercontent.com/4590317/41180199-0c49e524-6ba0-11e8-832b-d7e58f422961.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
