### ISSUE TITLE
Getting error message as” Sorry, we are unable to add your account right now. Please try again later. If the problem persists, please contact support@topcoder.com. While closing the LINK YOUR ACCOUNTS PROMPT

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#931]
Summary:
Getting error message as” Sorry, we are unable to add your account right now. Please try again later. If the problem persists, please contact support@topcoder.com. While closing the LINK YOUR ACCOUNTS PROMPT
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to  LINK YOUR ACCOUNTS SECTION
3.	Click GITHUB
4.	Close the Authorize prompt
### Expected Result ###
Should not Get any error message While closing the LINK YOUR ACCOUNTS PROMPT
### Actual  Result ###
Getting error message as” Sorry, we are unable to add your account right now. Please try again later. If the problem persists, please contact support@topcoder.com. While closing the LINK YOUR ACCOUNTS PROMPT
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41180282-58eff3a6-6b8b-11e8-8cc7-adc9a7f8c7b8.png)
![image](https://user-images.githubusercontent.com/31862600/41180303-643d7238-6b8b-11e8-9313-a4a7eee24967.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Configuration issue. Not a valid issues on this repo
