### ISSUE TITLE
Address Fields are look like disabled but user is able to edit all the fields.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#933]
Summary:
Address Fields are look like disabled but user is able to edit all the fields.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.Go to https://www.topcoder-dev.com/settings/account/
2.	GO To Address section 
### Expected Result ###
Address Fields are look like enabled  and  user should able to edit all the fields.
Need to change the fonts
### Actual  Result ###
Address Fields are look like disabled but user is able to edit all the fields.
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41180555-34cd2f6a-6b8c-11e8-8d02-2286600141eb.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
