### ISSUE TITLE
it goes to "PROFILE" tab after clicking "ACCOUNT" tab

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#935]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. click ACCOUNT tab, observe

### Expected Result ###
should stay on ACCOUNT tab

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1184" alt="ac" src="https://user-images.githubusercontent.com/4590317/41180764-df5fa2cc-6ba1-11e8-9161-f820c9813d05.png">

**Comment by winterflame** [comment]
Correction: 
Frequency: Always -> Frequency: Sometimes

**Comment by winterflame** [comment]
[issue.mp4.zip](https://github.com/topcoder-platform/community-app/files/2087626/issue.mp4.zip)

Attached the video, note that this issues is a bit hard to reproduce.

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
