### ISSUE TITLE
[common] unnecessary fields should be removed

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#936]
### Reported URL ###
https://www.topcoder-dev.com/members/tonyj/details/?track=DEVELOP&subTrack=BUG_HUNT&tab=statistics

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/tonyj/details/?track=DEVELOP&subTrack=BUG_HUNT&tab=statistics

3. observe

### Expected Result ###
unnecessary fields should be removed, e.g. for Bug Hunt track, there is no rank.

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1234" alt="bh" src="https://user-images.githubusercontent.com/4590317/41180954-9bc0458e-6ba2-11e8-9d5c-39c8e64c6c61.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this one.  We don't have a list of the `valid` fields at the moment
