### ISSUE TITLE
Getting error as “Error invalid pixel ID” while trying search a member from Forum Preference page

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#937]
Summary:
Getting error as “Error invalid pixel ID” while trying search a member from Forum Preference page
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click  Forum Preference
3.	Click Search button 
4.	Enter to make member search by entering “youdare”
### Expected Result ###
Should allow the member search
### Actual  Result ###
Getting error as “Error invalid pixel ID” while trying search a member from Forum Preference page
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41181010-df8e7f7a-6b8d-11e8-9759-65dd45ae74cf.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
