### ISSUE TITLE
page title should follow the exact user's handle

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#938]
### Reported URL ###
https://www.topcoder-dev.com/members/tonyj/details/?track=DEVELOP&subTrack=BUG_HUNT&tab=statistics

### Reproduction Steps ###

1. open https://www.topcoder-dev.com/members/tonyj/details/?track=DEVELOP&subTrack=BUG_HUNT&tab=statistics

2. observe the page title

### Expected Result ###
page title should follow the exact user's handle, e.g. tonyj should be TonyJ

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="782" alt="tj" src="https://user-images.githubusercontent.com/4590317/41181093-24ceab7c-6ba3-11e8-966b-aef08767669a.png">

**Comment by ThomasKranitsas** [comment]
invalid issue
