### ISSUE TITLE
selected country does not get selected in the dropdown

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#939]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. select United States as COUNTRY TO REPRESENT, save

4. then go to this page again, click COUNTRY TO REPRESENT, observe 

### Expected Result ###
USA should be selected by default in the dropdown and scrolled to that position.

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="825" alt="usa" src="https://user-images.githubusercontent.com/4590317/41181450-31f55142-6ba4-11e8-9f7e-e418d3307b89.png">

It will scroll from the top.

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
