### ISSUE TITLE
Payment preference -> in Payment accrual amount field application allowing to enter and save the value as “0”

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#940]
Summary:
Payment preference -> in Payment accrual amount field application allowing to enter and save the value as “0”
 ### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click  Paymnet Preference
3.	Enter value “0” in Payment accrual amount , Click paypal ,Enter valid email
4.	Click save button 
### Expected Result ###
Payment preference -> in Payment accrual amount field application should not allow to enter and save the value as “0”
Payment accrual amount must be greater or equal to $25
### Actual  Result ###
Payment preference -> in Payment accrual amount field application allowing to enter and save the value as “0”
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41181501-7e240794-6b8f-11e8-9674-974a5ff17c28.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
