### ISSUE TITLE
[$20] unable to delete some web links

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#941]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. create some web links with wrong URL,

4. try to click the trash icon, observe

### Expected Result ###
should be able to remove any of them

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
duplicate

**Comment by winterflame** [comment]
Please note that this one is reported earlier than #1018.

**Comment by ThomasKranitsas** [comment]
Good catch!

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069470 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069470 has been updated - the new changes has been updated for this ticket.
