### ISSUE TITLE
Payment preference -> You have not registered with Payoneer yet error message is coming as a plain text,

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#942]
Summary:
Payment preference -> You have not registered with Payoneer yet error message is coming as a plain text,
 ### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click  Paymnet Preference
3.	Select payment as Payoneer
4.	Enter email as asd@d233.com
5.	Click Save button
### Expected Result ###
Payment preference -> You have not registered with Payoneer yet error message should come as coloured text , So user can note the error message 
### Actual  Result ###
Payment preference -> You have not registered with Payoneer yet error message is coming as a plain text,
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
