### ISSUE TITLE
layout issues in IE11

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#943]
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/preferences/

3. observe

### Expected Result ###
no layout issues

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

OS: *Win 8*

Browser: *IE 11*

**Comment by winterflame** [comment]
![p](https://user-images.githubusercontent.com/4590317/41181915-20dd4340-6ba6-11e8-8c87-6b29224419e9.jpg)

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
