### ISSUE TITLE
Settings -> Can't delete image from user profile after saving changes in Tracks

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#944]
# Reported URL
https://www.topcoder-dev.com/settings/profile/

# Reproduction Steps

1. Log in with a user for ex. testmember1 / tc123456
2. go to https://www.topcoder-dev.com/settings/profile/, If the user doesn't have profile image add one
3. Modify something in the Tracks section and click Save button
3. Click 'Delete' button to delete the profile image
4. Press F5 to reload the page you can see that the image was not removed

# Expected Result
The profile image should be removed

# Actual Result
The image is not removed

# Screenshots

![image_profile](https://user-images.githubusercontent.com/864919/41181828-77a077ea-6b30-11e8-8c6d-a4b8af998464.png)

**Comment by sjbr** [comment]
Added sections in the edit:

Reported URL, Reproduction Steps, Expected Result, Actual Result

**Comment by sjbr** [comment]
OS: Linux
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
@ThomasKranitsas This Issue Labels:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
