### ISSUE TITLE
Forum preference -> Search cursor is not automatically focused to search text box

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#945]
Summary:
Forum preference -> Search cursor is not automatically focused to search text box
Note:- Verified in current build this is working fine 
 ### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click  Forum Preference
3.	Click “Search button”
### Expected Result ###
Payment preference -> Search cursor is not automatically focused to search text box
### Actual  Result ###
Payment preference -> Search cursor should automatically focused to search text box
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41181993-7ece0652-6b91-11e8-9d30-59dee184030a.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
