### ISSUE TITLE
[common] layout issues

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#946]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences
### Reproduction Steps ###

1. login as pshah_copilot
2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences
3. observe

### Expected Result ###
no layout issues

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

OS: *Win 8*

Browser: *IE 11*

**Comment by winterflame** [comment]
<img width="1410" alt="com" src="https://user-images.githubusercontent.com/4590317/41182057-a819dd64-6ba6-11e8-9c7c-dba1532048f0.png">

**Comment by winterflame** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
