### ISSUE TITLE
text should not break new line in IE11

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#947]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###

1. login as pshah_copilot

2. open https://apps.topcoder-dev.com/forums/?module=Settings

3. observe

### Expected Result ###
text should not break new line in IE11

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

OS: *Win 8*

Browser: *IE 11*

**Comment by winterflame** [comment]
<img width="1406" alt="b1" src="https://user-images.githubusercontent.com/4590317/41182303-aa157032-6ba7-11e8-8b4b-9c35a05ff67f.png">
<img width="1389" alt="b2" src="https://user-images.githubusercontent.com/4590317/41182304-aa479152-6ba7-11e8-89f7-42dc42e05c1f.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
