### ISSUE TITLE
no save option as mentioned

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#948]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module= Watches

### Reproduction Steps ###

1. login as pshah_copilot

2. open https://apps.topcoder-dev.com/forums/?module=Watches

3. observe

### Expected Result ###
description should be changed, as there is no save option as mentioned

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1429" alt="sv" src="https://user-images.githubusercontent.com/4590317/41182409-097a87d8-6ba8-11e8-9fdb-9b7b7408cc7d.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
