### ISSUE TITLE
IE11 –Profile –Application is not allowing to edit the text field of COUNTRY TO REPRESENT IF WE FOLLOW THE BELOW STEPS.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#949]
Summary:
IE11 –Profile –Application is not allowing to edit the text field of COUNTRY TO REPRESENT IF WE FOLLOW THE BELOW STEPS.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to COUNTRY TO REPRESENT TEXT FIELD 
3.	TYPE “DEMO”
4.	APPLICATION SHOWS “NO RESULT FOUND” IN THE DROP DOWN BOX
5.	CLICK THE “NO RESULT FOUND” IN THE DROP DOWN BOX
6.	Now try to edit the COUNTRY TO REPRESENT FIELD 
### Expected Result ###
IE11 –Profile –Application should allow to edit the text field of COUNTRY TO REPRESENT IF WE FOLLOW THE ABOVE STEPS.
### Actual  Result ###
IE11 –Profile –Application is not allowing to edit the text field of COUNTRY TO REPRESENT IF WE FOLLOW THE ABOVE STEPS.
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41182711-754ba096-6b94-11e8-808d-eb6a683f0bdd.png)
![image](https://user-images.githubusercontent.com/31862600/41182719-7f365b82-6b94-11e8-819a-e7c4f21a0691.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it'll be replaced by the updated page.
