### ISSUE TITLE
Update to react-dates@12.2.4

### ISSUE THREAD

**Issue by birdofpreyru** [topcoder-platform/community-app#95]
Right now we are using `react-dates@4.3.3` as a dependency. It is quite behind the current version, 12.2.4 and should be properly updated. Ensure that after update the component looks and works the same as before (at the moment it is used only in the filters panel of challenge listing pages).

**Comment by brijeshprasad89** [comment]
@birdofpreyru I have made the change.. could you please provide me the access to push and create PR?

**Comment by birdofpreyru** [comment]
@brijeshprasad89 As it is told in the specs of the corresponding F2F challenge, just submit your Git patch to the challenge, if you have resolved all requested tickets.
