### ISSUE TITLE
IE11 –Profile –Getting error message as “Something went wrong” , If we upload and Delete the profile picture and Followed by saving the short bio.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#950]
Summary:
IE11 –Profile –Getting error message as “Something went wrong” , If we upload and Delete the profile picture and Followed by saving the short bio.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	ADD Profile image
3.	Delete Profile image
4.	Enter “Iam a pro “ in Short Bio Text Field 
5.	Click Save button
### Expected Result ###
IE11 –Profile –Should not get any error message, If we upload and Delete the profile picture and Followed by saving the short bio.
### Actual  Result ###
IE11 –Profile –Getting error message as “Something went wrong” , If we upload and Delete the profile picture and Followed by saving the short bio.
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41183070-3b60b090-6b96-11e8-9c06-fe1f0c333bc1.png)
![image](https://user-images.githubusercontent.com/31862600/41183073-3ec3373a-6b96-11e8-971a-b3633253bc87.png)
![image](https://user-images.githubusercontent.com/31862600/41183085-47c97de4-6b96-11e8-849d-5a2c66d502f8.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
