### ISSUE TITLE
IE11 –Profile – 256 character is not accepted in the “Short Bio” if the text are in the multiple lines.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#951]
Summary:
IE11 –Profile – 256 character is not accepted in the “Short Bio” if the text are in the multiple lines.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to Short Bio Field
3.	Enter “Helo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHelo Length
Helo Length TestHel0”
4.	Click Save button
### Expected Result ###
IE11 –Profile – 256 character should be accepted in the “Short Bio” if the text are in the multiple lines.
.
### Actual  Result ###
IE11 –Profile – 256 character is not accepted in the “Short Bio” if the text are in the multiple lines.
### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41183246-51126b9e-6b97-11e8-9202-1713e742ec32.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
