### ISSUE TITLE
Submission Tab of Challenge Details Page doesn't shows score anymore

### ISSUE THREAD

**Issue by gurmeetb** [topcoder-platform/community-app#952]
Go to any finished challenge details page. Click Submissions, and we do not see the scores the submitter received. Kindly refer to the screen below. 

![scores](https://user-images.githubusercontent.com/14284629/41183280-8a096484-6b97-11e8-982c-c88c5cf65b2d.jpg)

**Comment by nithyaasworld** [comment]
I can see the initial and final score for a Code Challenge. But for the F2F, It is showing just like in the above screenshot and I think its as expected.

@gurmeetb Please tell me if we can close this. Thanks.

**Comment by gurmeetb** [comment]
@nithyaasworld since this was long back, almost a year plus, we can close this, as we changed a lot and this is fixed since long back.
