### ISSUE TITLE
Settings -> Can't save address in account page

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#953]
# Reported URL
https://www.topcoder-dev.com/settings/account/

# Reproduction Steps
1. Login with user testmember1 / tc123456
2. go to https://www.topcoder-dev.com/settings/account/
3. Write an address in the field address and address 2  and click 'Save' button
4. after the message 'Success' appears press F5 to reload the page
5. The Address information was not saved

# Expected Result
Should be able to save address information in the account page

# Actual Result
The address information is not saved

# Screenshots
![address](https://user-images.githubusercontent.com/864919/41183302-45aa725c-6b37-11e8-95d0-69badcdb9e7a.png)

# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
Same bug with the fields:
CITY
STATE/PROVINCE
ZIP/POST CODE

It works only if you fill in all the fields and save

**Comment by sjbr** [comment]
@ThomasKranitsas This Issue Labels:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
