### ISSUE TITLE
Submission Tab of Challenge Details Page doesn't shows Submission Time in Local Timezone anymore

### ISSUE THREAD

**Issue by gurmeetb** [topcoder-platform/community-app#955]
Submission Tab of Challenge Details Page doesn't shows Submission Time in Local Time anymore. It is very confusing to figure out if it is the submission I just updated or the one I uploaded few hours back. 

Expected: The submission time should be shown in local timezone of the user. 

![submissiontime](https://user-images.githubusercontent.com/14284629/41183380-17e485cc-6b98-11e8-8047-31545f47121b.jpg)

**Comment by nithyaasworld** [comment]
I am not seeing this issue in the recent days. 

@gurmeetb Please feel free to re-open if this issue seems to occur still.
