### ISSUE TITLE
[$30] IE11 –Profile – if we add 5 or 6 web link to profile , Page layout is getting increased in the right hand side.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#956]
Summary:
IE11 –Profile – if we add 5 or 6 web link to profile , Page layout is getting increased in the right hand side.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to “Add a Web Link” section
3.	Add 5 to 6 links
4.	Scroll down and view the Linked account section 

### Expected Result ###
IE11 –Profile – if we add 5 or 6 web link to profile, Page layout should not get increased in the right hand side.
.
### Actual  Result ###
IE11 –Profile – if we add 5 or 6 web link to profile , Page layout is getting increased in the right hand side.
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41183599-2c6a5570-6b99-11e8-975c-beb676cc62c9.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069485 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069485 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas : Can you assign me this ticket, I'm going to work on it.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069485 has been updated - it has been assigned to diazz.

**Comment by ThomasKranitsas** [comment]
@suppermancool  please fix the open PRs before you start working on this one

**Comment by suppermancool** [comment]
i fixed the error in PRs, can you assign me to this task?

right now the linked accounts list is ok, but the External Link text box is overlap the beneath list, can i fix that?

![viber-image](https://user-images.githubusercontent.com/5815182/44147833-f6d4459a-a0bf-11e8-96a0-dde6f197c2fc.jpg)

**Comment by ThomasKranitsas** [comment]
sounds good

**Comment by suppermancool** [comment]
fixed in https://github.com/topcoder-platform/community-app/pull/1193, pls check, thanks

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069485
