### ISSUE TITLE
IE11 –Account – In Address -> Country Text Field  is not treated as mandatory field.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#957]
Summary:
IE11 –Account – In Address -> Country Text Field  is not treated as mandatory field.
### Reported URL ###
https://www.topcoder-dev.com/settings/account/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/account/
2.	Scroll down and go to Country Field 
3.	Delete the Country’
4.	Enter zip as 12345
5.	Click Save button

### Expected Result ###
IE11 –Account – In Address -> Country Text Field  should be treated as mandatory field.
.
### Actual  Result ###
IE11 –Account – In Address -> Country Text Field  is not treated as mandatory field.
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41183794-2e818472-6b9a-11e8-888d-54fa2e0294bd.png)
![image](https://user-images.githubusercontent.com/31862600/41183798-33a26d36-6b9a-11e8-9094-5b9ea5ac6f57.png)
![image](https://user-images.githubusercontent.com/31862600/41183807-476ae820-6b9a-11e8-85dd-bdac2d8a3fcf.png)
![image](https://user-images.githubusercontent.com/31862600/41183812-4a96607e-6b9a-11e8-830b-705823324a2d.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
