### ISSUE TITLE
IE11 –Preference – Seeing Text overlap issue in Preference section

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#958]
Summary:
IE11 –Preference – Seeing Text overlap issue in Preference section
### Reported URL ###
https://www.topcoder-dev.com/settings/account/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/account/
2.	Click “Preference” Tab

### Expected Result ###
IE11 –Preference – we should not see any Text overlap issue in Preference section
### Actual  Result ###
IE11 –Preference – Seeing Text overlap issue in Preference section
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41183982-077af178-6b9b-11e8-8acc-82a9aaf73458.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
duplicate

**Comment by youdare** [comment]
@ThomasKranitsas , I dont see any duplicate issue , please check again

**Comment by ThomasKranitsas** [comment]
https://github.com/topcoder-platform/community-app/issues/943

**Comment by youdare** [comment]
@ThomasKranitsas Thanks , Sorry for the Trouble.
