### ISSUE TITLE
[$10] Members Profile -> Link causes the site to reload indefinitely

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#959]
# Reported URL
https://www.topcoder-dev.com/members/testmember1/

# Reproduction Steps
1. Login with user testmember1 / tc123456
2. Go to https://www.topcoder-dev.com/members/testmember1/
3. Click the button 'View other members'
4. This will open https://www.topcoder-dev.com/community/members/undefined/ and will reload the page forever

# Expected Result
This should be a valid link

# Actual Result
The page is continually reloaded

# Screenshots
![screenshot_2018-06-08_14-42-01](https://user-images.githubusercontent.com/864919/41184227-3da98296-6b3c-11e8-9f64-37978157403d.png)
# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
@ThomasKranitsas This Issue Labels:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Remove the `View other members` button as the page doesn't exist anymore.

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069487 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069487 has been updated - the new changes has been updated for this ticket.

**Comment by suppermancool** [comment]
@ThomasKranitsas : Can you assign me this ticket, I'm going to work on it.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069487 has been updated - it has been assigned to diazz.

**Comment by suppermancool** [comment]
@ThomasKranitsas done in https://github.com/topcoder-platform/community-app/pull/1189, pls check, thanks

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069487
