### ISSUE TITLE
Edge –Account – Seeing two show password options in the Current and New password field.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#960]
Summary:
Edge –Account – Seeing two show password options in the Current and New password field. 
### Reported URL ###
https://www.topcoder-dev.com/settings/account/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/account/
2.	In Current password type “Password” and you can see two options to show password
3.	Just Reload the application
4.	In New Password field type “Password” and you can see two options to show password
Note:- If you are not able to reproduce, Please reload the app and try,For second time we are not able to reproduce the issue
### Expected Result ###
Edge –Account – Should see only one show password options in the Current and New password field. 
### Actual  Result ###
Edge –Account – Seeing two show password options in the Current and New password field. 
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41184610-225d3b8c-6b9f-11e8-9f96-fff916eb48f3.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
