### ISSUE TITLE
Chrome –Preference – Go to Preference ->Click Payment Preference->Click Cancel button , Application is navigating to Account section instead of Preference section

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#961]
Summary:
Chrome –Preference – Go to Preference ->Click Payment Preference->Click Cancel button , Application is navigating to Account section instead of Preference section
### Reported URL ###
https://www.topcoder-dev.com/settings/preferences/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click “Payment Preference”
3.	From the payment preference click “Cancel” button
### Expected Result ###
Chrome –Preference – Go to Preference ->Click Payment Preference->Click Cancel button , Application should navigate to Preference section
### Actual  Result ###
Chrome –Preference – Go to Preference ->Click Payment Preference->Click Cancel button , Application is navigating to Account section instead of Preference section
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41184778-322a1b2e-6ba0-11e8-97b6-fccd0c4f7a3b.png)
![image](https://user-images.githubusercontent.com/31862600/41184784-3c8d39b6-6ba0-11e8-8832-64151d875154.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
