### ISSUE TITLE
Chrome –Members – Zero rating is not getting reflected in the Development summary 

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#962]
Summary:
Chrome –Members – Zero rating is not getting reflected in the Development summary 
### Reported URL ###
https://www.topcoder-dev.com/members/Sky_/details/?track=DEVELOP&subTrack=UI_PROTOTYPE_COMPETITION
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/preferences/
2.	Click “UI PROTOTYPE COMPETITION” MENU
3.	application WILL DISPLAY summary OF DEVELOPMENT
4.	Observe the development ratings.

### Expected Result ###
Chrome –Members – Zero rating should get reflected in the Development summary 
### Actual  Result ###
Chrome –Members – Zero rating is not getting reflected in the Development summary 
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41185140-f94d526e-6ba2-11e8-82c8-a73d794e558c.png)
![image](https://user-images.githubusercontent.com/31862600/41185148-0cf4cf7c-6ba3-11e8-9971-a41674bac99e.png)
![image](https://user-images.githubusercontent.com/31862600/41185153-1ab08a20-6ba3-11e8-9072-76ac5794e4f4.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
duplicate

**Comment by youdare** [comment]
@ThomasKranitsas , There is no Duplicate Detect for this , Please check again

**Comment by ThomasKranitsas** [comment]
Oh, actually https://github.com/topcoder-platform/community-app/issues/1003 is duplicate of this but since both are yours, I believe it's fine, right?

**Comment by youdare** [comment]
@ThomasKranitsas 
1003 is for "0" Wins in challenge.

960 is for  No Ratting in Challenge 

If you think if we fix 960 is enough, i am okay do mark 1003 as duplicate

**Comment by ThomasKranitsas** [comment]
yeah, the same change will fix both so it's essentially the same issue with 0/undefined/null being treated the same way.

I'm keeping 1003 as I've already counted it and I'm marking this as a duplicate. It's the same thing ;)

**Comment by youdare** [comment]
Thank for update.
