### ISSUE TITLE
style issue when there is validation error

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#963]
### Reported URL ###
https://www.topcoder-dev.com/settings/account/

### Reproduction Steps ###

1. login as pshah_copilot

2. open https://www.topcoder-dev.com/settings/account/

3. clear LAST NAME, observe

### Expected Result ###
There should be no extra lines for the text fields.

### Actual Result ###

See screenshot, there is a green line for the FIRST NAME field, and a pink line for the LAST NAME field.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="861" alt="p3" src="https://user-images.githubusercontent.com/4590317/41185507-83587764-6bbb-11e8-8aef-c2593e4074fc.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
This page has been replaced
