### ISSUE TITLE
the error message should be adjusted when COUNTRY is empty

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#964]
### Reported URL ###
https://www.topcoder-dev.com/settings/account/

### Reproduction Steps ###

1. login as pshah_copilot

2. open https://www.topcoder-dev.com/settings/account/

3. enter 'a' in the COUNTRY field, then clear input in the COUNTRY field, observe

### Expected Result ###
The error message should be changed as there is no list shown.

### Actual Result ###

See screenshot.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="815" alt="ct" src="https://user-images.githubusercontent.com/4590317/41185586-7c959d16-6bbc-11e8-9e19-54ccae4956c6.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
