### ISSUE TITLE
Edge –Profile – In Short Bio Text Field, Cursor always points to second line of the text box

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#965]
Summary:
Edge –Profile – In Short Bio Text Field, Cursor always points to second line of the text box 
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to Short Bio Field
3.	Write any small in for “HI” click save
4.	Again click Short Bio Field , Delete the all text
5.	Observe the cursor position 

### Expected Result ###
Edge –Profile – In Short Bio Text Field, Cursor always points to first line of the text box 
### Actual  Result ###
Edge –Profile – IN Short Bio Text Field, Cursor always points to second line of the text box 
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41185719-e7308a8c-6ba8-11e8-88d1-86ef247918a1.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
