### ISSUE TITLE
[common] 0 and 0.00 should be consistent

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#966]
### Reported URL ###
https://www.topcoder-dev.com/members/tonyj/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION

### Reproduction Steps ###

1. open https://www.topcoder-dev.com/members/tonyj/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION

2. observe

### Expected Result ###
0 and 0.00 should be consistent

### Actual Result ###
some are 0, some are 0.00

See screenshot.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1205" alt="xyz" src="https://user-images.githubusercontent.com/4590317/41185721-e5826998-6bbd-11e8-9472-de558a5da7d3.png">

**Comment by winterflame** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Will be fixed in https://github.com/topcoder-platform/community-app/issues/985
