### ISSUE TITLE
[common] button style should be consistent

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#967]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences
https://www.topcoder-dev.com/settings/account/
https://www.topcoder-dev.com/settings/email/

### Reproduction Steps ###

1. login as pshah_copilot

2. open above URLs in Reported URL, enable Save button if necessary, observe

### Expected Result ###

button style should be consistent

### Actual Result ###

See screenshots.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1225" alt="s1" src="https://user-images.githubusercontent.com/4590317/41185837-46c08d60-6bbf-11e8-954d-99b7e902b840.png">
<img width="1233" alt="s2" src="https://user-images.githubusercontent.com/4590317/41185838-46ec9b26-6bbf-11e8-86cd-206351f51afb.png">
<img width="1051" alt="s3" src="https://user-images.githubusercontent.com/4590317/41185839-471a0246-6bbf-11e8-8a45-10f5725d2889.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
