### ISSUE TITLE
font family/style should be consistent on the same page

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#968]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_copilot

2. open above URLs in Reported URL, observe

### Expected Result ###

font family/style should be consistent on the same page

### Actual Result ###

See screenshots.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="825" alt="font" src="https://user-images.githubusercontent.com/4590317/41185870-d4f6b5aa-6bbf-11e8-9d9f-778a73bbe33b.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
