### ISSUE TITLE
DELETE button should be enabled if the profile image is not empty

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#969]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. observe the DELETE button

### Expected Result ###
DELETE button should be enabled if the profile image is not empty

### Actual Result ###

See screenshot, it's disabled by default. It should behavior the same as CHANGE IMAGE button.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1258" alt="del" src="https://user-images.githubusercontent.com/4590317/41185929-754cedb2-6bc0-11e8-9831-f66e552f0d7e.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
This page has been replaced
