### ISSUE TITLE
should show a confirmation message when trying to delete the profile image

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#970]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/, upload a profile image if necessary

3. click the DELETE button, observe

### Expected Result ###
should show a confirmation message when trying to delete the profile image

### Actual Result ###

See screenshot, it will delete immediately

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="873" alt="after" src="https://user-images.githubusercontent.com/4590317/41185949-cc4f184c-6bc0-11e8-99e9-d9e69e25eeba.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
this page has been replaced
