### ISSUE TITLE
Chrome –Profile –If user click delete button 2 or 3 times, Application showing multiple confirmation message.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#972]
Summary:
Chrome –Profile –If user click delete button 2 or 3 times, Application showing multiple confirmation message.  
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Add an profile photo
3.	Click Delete button 2 or 3 times 

### Expected Result ###
Chrome –Profile –Application should not allow to  click delete button 2 or 3 times, If it is allows ,please restrict to display one confirmation message.  
### Actual  Result ###
Chrome –Profile –If user click delete button 2 or 3 times, Application showing multiple confirmation message.  
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41186026-0c641810-6bad-11e8-9bb7-e05d46f7d50f.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
