### ISSUE TITLE
Member profile -> Track Statistics sub menu doesn't load for some members

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#973]
# Reported URL
https://www.topcoder-dev.com/members/nhzp339/details/?track=DEVELOP&subTrack=SPECIFICATION
https://www.topcoder-dev.com/members/aleaactaest/details/?track=DEVELOP&subTrack=ARCHITECTURE

# Reproduction Steps
1. Open a user statistic page like https://www.topcoder-dev.com/members/aleaactaest/details/?track=DEVELOP&subTrack=ARCHITECTURE
2. Click on the icon next to the subtrack name that is 9 small rectangles to open the tracks menu
3. Select another subtrack to open it
4. continue repeating step 2 and 3, eventually, this menu will not load and it will be only a blank page

You can also reproduce this bug this way:
1. Open a user statistic page like https://www.topcoder-dev.com/members/nhzp339/details/?track=DEVELOP&subTrack=SPECIFICATION
2. Click on the icon that is 9 small rectangles next to the subtrack name
3. Close the menu by clicking on the X icon
4. continue repeating step 2 and 3, eventually, this menu will not load and it will be only a blank page

# Expected Result
Track Submenu should load correctly

# Actual Result
Submenu doesn't load only appears a blank page

# Screenshots
![tracksubmenu](https://user-images.githubusercontent.com/864919/41186181-4aa62b44-6b4f-11e8-8557-ff1f5f0d8c91.png)

# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
Youtube: https://youtu.be/yyB4m4HW0Sk
Video zip file: 
[video.zip](https://github.com/topcoder-platform/community-app/files/2086957/video.zip)

**Comment by sjbr** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
Although I was not able to reproduce that issue, I got few errors so I'll just mark this as Major instead of Critical

**Comment by sjbr** [comment]
Ok, there is a video in the comments of 2 different ways to reproduce this bug

**Comment by ThomasKranitsas** [comment]
Got it

**Comment by ThomasKranitsas** [comment]
This has been fixed
