### ISSUE TITLE
most links in the footer do not work

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#974]
### Reported URL ###
https://community.topcoder-dev.com/tc?module=VisaSelection

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=VisaSelection

3. click each link in the footer, observe

### Expected Result ###
should be working

### Actual Result ###

See screenshots

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1416" alt="f1" src="https://user-images.githubusercontent.com/4590317/41186354-828e1c60-6bc7-11e8-9b4c-60dc1a9bfa1d.png">


<img width="1159" alt="f2" src="https://user-images.githubusercontent.com/4590317/41186366-ace1c8b8-6bc7-11e8-9e10-777da58773f2.png">

<img width="1211" alt="f3" src="https://user-images.githubusercontent.com/4590317/41186355-82bdc4d8-6bc7-11e8-8147-93308036f502.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
