### ISSUE TITLE
save button should be aligned center

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#975]
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###

1. login as pshah_manager

2. open https://apps.topcoder-dev.com/forums/?module=Settings, click each tab

3. observe the Save button

### Expected Result ###
it should be aligned center, like in other pages

### Actual Result ###

See screenshots

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1409" alt="r1" src="https://user-images.githubusercontent.com/4590317/41186622-2650de4c-6bcc-11e8-8be7-bb6f738fe067.png">
<img width="1439" alt="r2" src="https://user-images.githubusercontent.com/4590317/41186623-267ea278-6bcc-11e8-95a2-34e5b311c781.png">
<img width="1433" alt="r3" src="https://user-images.githubusercontent.com/4590317/41186624-26ac3292-6bcc-11e8-874d-6b21eec3bc45.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
that's part of the legacy app and not the community app
