### ISSUE TITLE
[$40] past SRMs list should be sorted by date descendingly by default

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#976]
### Reported URL ###
https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

3. observe 

### Expected Result ###
past SRMs list should be sorted by date descendingly by default.

### Actual Result ###

See screenshot, it is sorted by points descendingly.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1364" alt="srm" src="https://user-images.githubusercontent.com/4590317/41186698-884f76c0-6bcd-11e8-8fd9-b7afdd28ec59.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069489 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069489 has been updated - the new changes has been updated for this ticket.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, please could you assign this issue to me, also is there a way I can assign issues to myself just in case you are sleeping ?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069489 has been updated - it has been assigned to kevin.crain.

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors since you can’t assign yourself to any ticket, you can:
- Comment on the ticket that you’re working on it.
- Create a pull request 
- Comment that the ticket is ready for review 
- Pick up another ticket

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you so much Thomas, will do my best to complete as many issues as I can tonight along with the other repo Members.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas It looks like the API does not return the list of contests sorted by date desc.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Is there maybe a sort parameter that I can pass to API endpoint -> `https://api.topcoder-dev.com/v3/members/{member}/srms/?filter=status%3Dpast%26isRatedForSRM%3Dtrue&limit=36&offset=72`

**Comment by ThomasKranitsas** [comment]
How does the legacy app fetches the SRMs? https://github.com/appirio-tech/topcoder-app/

**Comment by ThomasKranitsas** [comment]
@KevinLeigh any update here?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas kevinleigh has two issues assigned to himself? will u assign it to me this one if he fails. and i will make sure to complete on time from now.

**Comment by ThomasKranitsas** [comment]
Hi @PrakashDurlabhji, @KevinLeigh got the 2nd ticket after he created a PR for the other one.
The PR wasn't correct thus he has 2 tickets.

Of course, if @KevinLeigh can't complete it, I'll assign you

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, you can assign this ticket/issue to @PrakashDurlabhji :)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069489 has been updated - it has been assigned to PkDurlabhji.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas @PrakashDurlabhji Just a heads up, it would be a good idea to check if scrolling down page to load more SRMs will still keep the list sorted by date desc.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas i am 99% done, just need dummy data which petr profile has of SRMS.
tonyj profile doesnt have past SRM hence not able to check it.
on accessing petr profile locally it says unauthorized.

please help with a profile which has SRM.

**Comment by KevinLeigh** [comment]
@PrakashDurlabhji Hey there, you can check this forum here -> https://apps.topcoder.com/forums/?module=Thread&threadID=922282&start=0, to see how to resolve unauthorized issue. It has to do with not setting Contentful environment variables.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas Mr raised . thanks

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069489
