### ISSUE TITLE
[$20] alignment issue on the past SRM page

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#977]
### Reported URL ###
https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

3. observe 

### Expected Result ###
room and division number should be aligned horizontally

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1366" alt="place" src="https://user-images.githubusercontent.com/4590317/41186719-d125843e-6bcd-11e8-8e19-42dbe284340e.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069509 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069509 has been updated - the new changes has been updated for this ticket.

**Comment by gets0ul** [comment]
@ThomasKranitsas Please assign me. Thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069509 has been updated - it has been assigned to gets0ul.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069509
