### ISSUE TITLE
it's hard to find a specific SRM based on current design

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#978]
### Reported URL ###
https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

3. observe 

### Expected Result ###
Better to add search functionality or use pagination on the page.

### Actual Result ###

See screenshot, user has to scroll down to load more data, which is hard to find a specific SRM.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1397" alt="find" src="https://user-images.githubusercontent.com/4590317/41186740-52787898-6bce-11e8-9caa-710c8073d153.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Will be fixed in #976
