### ISSUE TITLE
[$60] unable to load more SRM data by scrolling down in IE11

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#979]
### Reported URL ###
https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

3. scroll down, observe 

### Expected Result ###
Should be able to load more data in IE11 by scrolling down the page.

### Actual Result ###

See screenshot, in IE11, user cannot load more data by scrolling down.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*
*Win 8*

Browser: *Firefox 60.0.1 (64-bit)* and *IE11*

**Comment by winterflame** [comment]
in IE 11:
<img width="1439" alt="ie11" src="https://user-images.githubusercontent.com/4590317/41186799-9a118478-6bcf-11e8-89a4-4f6da3a0eca1.png">


in Firefox:
<img width="1433" alt="ff" src="https://user-images.githubusercontent.com/4590317/41186802-a3d534a0-6bcf-11e8-965e-a0235e12b2b5.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069475 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069475 has been updated - the new changes has been updated for this ticket.

**Comment by sandipanghos** [comment]
@ThomasKranitsas  please assign me the ticket

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069475 has been updated - it has been assigned to sandipanghosh64.

**Comment by ThomasKranitsas** [comment]
@sandipanghos any update here?

**Comment by sumitdaga** [comment]
can i take this one?
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment]
@sumitdaga sure, I'll add you since @sandipanghos is not responding

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069475 has been updated - it has been assigned to daga_sumit.

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
refer http://take.ms/HKqKv
in my local deployment the loader works in IE 11 though there is layout issue i noticed which is not limited to srm but present in all pages with such stats

**Comment by sumitdaga** [comment]
[Screencast 2018-08-16.mp4.zip](https://github.com/topcoder-platform/community-app/files/2293764/Screencast.2018-08-16.mp4.zip)  
a screenacst showing that the loader works in IE 11

**Comment by ThomasKranitsas** [comment]
Can you please fix the layout issue?

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069475 has been updated - the new changes has been updated for this ticket.

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
this is ready for review ...if you haven't already noticed!
