### ISSUE TITLE
Update content for taskforce community

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#98]
Please see details at https://www.topcoder.com/direct/contest/detail?projectId=30058378

**Comment by ajefts** [comment]
@birdofpreyru If you can, hoping to get this done by end of Monday.

**Comment by birdofpreyru** [comment]
@ajefts Wierdly enough, even though I got an email saying you have shared with me a link to access the doc with specifications, when I click it, I get `You need permission` screen. Double-check, please.

Otherwise, sure, I'll get it ready in time.

**Comment by ajefts** [comment]
@birdofpreyru I see you've commented in the doc so I assume you're ok now?

**Comment by birdofpreyru** [comment]
Yes, Clinton has fixed my access rights.
