### ISSUE TITLE
[$30] Member profile:  Order of icons under profile photo should be the same as the Track and subtracks list

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#980]
# Reported URL
https://www.topcoder-dev.com/members/saarixx/

# Reproduction Steps
1. Open profile page like https://www.topcoder-dev.com/members/saarixx/
2. Observe that the icons that are on the left under the profile photo serve as an index to the track list on the right (if you click the designer icon the page is scrolled to the Design Activity section)
3. The order is different. Should have the same order to be consistent

# Expected Result
The icons should be in the same order as the Track and subtracks list on the right since these function as an index

# Actual Result
No ordered 

# Screenshots
![iconorder](https://user-images.githubusercontent.com/864919/41186807-5e26ca42-6b5a-11e8-86d4-45826780fd5d.png)

# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069505 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069505 has been updated - the new changes has been updated for this ticket.

**Comment by KevinLeigh** [comment]
Completing issue now :)

**Comment by KevinLeigh** [comment]
PR for changes are here -> https://github.com/topcoder-platform/community-app/pull/1183

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069505 has been updated - it has been assigned to kevin.crain.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069505
