### ISSUE TITLE
Settings - Profile and account -> country field editing should be consistent (UX)

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#984]
# Reported URL
https://www.topcoder-dev.com/settings/account/
https://www.topcoder-dev.com/settings/profile/

# Reproduction Steps
1. Login with user testmember1 / tc123456
2. Go to https://www.topcoder-dev.com/settings/profile/ if you edit country to represent it is a drop down box
3. If you go to https://www.topcoder-dev.com/settings/account/ and edit country from address section it is a text field with autocomplete
4. Both should be the same control for consistency

# Expected Result
The same way to edit country information in both settings pages

# Actual Result
See screenshot

# Screenshots
![country1](https://user-images.githubusercontent.com/864919/41187059-96805494-6b5f-11e8-8b3e-f182f272fa2e.png)
![country2](https://user-images.githubusercontent.com/864919/41187062-99136444-6b5f-11e8-9bc5-8fc25b322a24.png)

# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
