### ISSUE TITLE
[$40] % should be rounded to 2 decimals

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#985]
### Reported URL ###
https://www.topcoder-dev.com/members/argolite/details/?track=DEVELOP&subTrack=CONCEPTUALIZATION&tab=statistics

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/argolite/details/?track=DEVELOP&subTrack=CONCEPTUALIZATION&tab=statistics

3. observe

### Expected Result ###
% should be rounded to 2 decimals

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1292" alt="round" src="https://user-images.githubusercontent.com/4590317/41187080-45ae5446-6bd5-11e8-827e-210abfe95d83.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Should also fix #966 as part of this ticket

**Comment by ThomasKranitsas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Bash - Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-bug-bash-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069493 has been created for this ticket.

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069493 has been updated - the new changes has been updated for this ticket.

**Comment by gets0ul** [comment]
Is this open for current bug bash?  
Please assign me

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069493 has been updated - it has been assigned to gets0ul.

**Comment by ThomasKranitsas** [comment]
@gets0ul yep, I'm opening lots of tickets for pickup

**Comment by gets0ul** [comment]
@ThomasKranitsas what is the password for pshah_manager account?

**Comment by ThomasKranitsas** [comment]
Should be `topcoder123`

**Comment by gets0ul** [comment]
Please check the PR. Thanks.

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069493
