### ISSUE TITLE
settings - account -> TAB key doen't work while editing password

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#988]
# Reported URL
https://www.topcoder-dev.com/settings/account/

# Reproduction Steps
1. Login with user testmember1 / tc123456
2. Put the cursor in Current password text field or New password field
3. If you press TAB key the cursor doesn't go to the next control this is not the expected behavior

# Expected Result
TAB key should work in the password fields 

# Actual Result
TAB key doesn't work as expected

# Screenshots
![passwd](https://user-images.githubusercontent.com/864919/41187286-603b74a0-6b63-11e8-8a57-b1ab2fd97ab5.png)

# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
