### ISSUE TITLE
[$40] Member profile -> Track Dialog Menu doesn't close after navigating back in the browser

### ISSUE THREAD

**Issue by sjbr** [topcoder-platform/community-app#989]
# Reported URL
https://www.topcoder-dev.com/members/saarixx/

# Reproduction Steps
1. Open profile page like https://www.topcoder-dev.com/members/saarixx
2. Click on one of the subtracks to open the statistics page
3. Open the Dialog menu by clicking on the icon next to the track name (9 small rectangles)
4. Click the back button in the browser
5. The dialog of the menu is still open after the browser navigated back

# Expected Result
The dialog of the menu should close after navigating back

# Actual Result
See Video

# Video
View on Youtube or download video zip file

https://youtu.be/wjcHyOvH-u8
[video.zip](https://github.com/topcoder-platform/community-app/files/2086625/video.zip)

# Issue Information

Device: Desktop
OS: Linux Fedora 27
Browser: Chrome 66.0.3359.117 (Official Build) (64-bit)
Frequency: Always

**Comment by sjbr** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
@topcoder-platform/topcodercompetitors new ticket available for pickup

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please assign me this. thanks

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30069297 has been updated - it has been assigned to gauravseta.

**Comment by ThomasKranitsas** [comment]
@Gauravseta any update?

**Comment by Gauravseta** [comment]
@ThomasKranitsas its working perfectly fine in "new-develop" branch. i invested a lot of time in it investigating.i could have done some other issue too.

**Comment by ThomasKranitsas** [comment]
Sure, let me check

**Comment by Gauravseta** [comment]
@ThomasKranitsas ok waiting for your comment.

**Comment by ThomasKranitsas** [comment]
Seems like it was fixed here https://github.com/topcoder-platform/community-app/commit/091c2ab0b90c7cbc8a69ce952ac9abadcb393280

**Comment by Gauravseta** [comment]
@ThomasKranitsas No the change u mentioned above is not related to this at all.i dont know how it has started working. but can i get something for time spent?

**Comment by ThomasKranitsas** [comment]
Absolutely

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069297

**Comment by Gauravseta** [comment]
@ThomasKranitsas  thanks
