### ISSUE TITLE
Chrome –Profile –In Linked Account ->Added link will not enable automatically, we need to reload the application to enable the link.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#990]
Summary:
Chrome –Profile –In Linked Account ->Added link will not enable automatically, we need to reload the application to enable the link.

### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to ADD A Web Link Text Field and Enter www.google.com
3.	Click ADD button
4.	Link will be added to the Linked Account
5.	Go to Linked Account section
6.	You will be seeing “LOADING DATA,THIS WILL TAKE 
7.	Wait for few seconds ( 5 to 6 min)
8.	Verify link will not enabled 
9.	Reload the entire page
10.	GO to Linked Account section
11.	Observe the link , it will be enabled 
### Expected Result ###
Chrome –Profile –In Linked Account ->Added link should be enable automatically, we should not reload the application to enable the link.
### Actual  Result ###
Chrome –Profile –In Linked Account ->Added link will not enable automatically, we need to reload the application to enable the link.
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41187821-495658b4-6bd0-11e8-8015-c3d227be3421.png)

After reloading the page 

![image](https://user-images.githubusercontent.com/31862600/41187827-5e56a174-6bd0-11e8-945f-ebb858eeff3f.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Fixed
