### ISSUE TITLE
it does not distinguish http/https protocol when adding web link

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#992]
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###

1. login as pshah_manager, open the web developer console of Chrome

2. open https://www.topcoder-dev.com/settings/profile/

3. enter a web link: http://www.google.com, click ADD

4. enter another web link: https://www.google.com, click ADD

5. observe 

### Expected Result ###
should distinguish the protocol.

### Actual Result ###

See screenshot, it shows error. http and https are the same.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="1253" alt="https" src="https://user-images.githubusercontent.com/4590317/41187872-28733282-6be6-11e8-8c00-0ed382324c4b.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
