### ISSUE TITLE
Chrome –Profile –In Linked Account ->Not able to delete the Added link immediately. User need to wait 5 to 6 min to delete the added link.    

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#993]
Summary:
Chrome –Profile –In Linked Account ->Not able to delete the Added link immediately. User need to wait 5 to 6 min to delete the added link.    

### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to ADD A Web Link Text Field and Enter www.google.com
3.	Click ADD button
4.	Link will be added to the Linked Account
5.	Go to Linked Account section
6.	You will be seeing “LOADING DATA,THIS WILL TAKE 
7.	Click Delete button of www.google.com in the Linked Account section

### Expected Result ###
Chrome –Profile –In Linked Account ->Should allow to delete the Added link immediately 
### Actual  Result ###
Chrome –Profile –In Linked Account ->Not able to delete the Added link immediately. User need to wait 5 to 6 min to delete the added link.    
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41187875-3d6966c6-6bd1-11e8-9ab7-fe9f5fdeeaaa.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
duplicate
