### ISSUE TITLE
spelling is different for web links in delete confirmation

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#994]
### Reported URL ###

https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. enter a web link: http://www.google.com, click ADD

4. wait for a while, click the trash icon of this link

5. observe 

### Expected Result ###
GOOGLE and Google should be consistent.

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="735" alt="g1" src="https://user-images.githubusercontent.com/4590317/41187912-30d839ee-6be7-11e8-9ffa-f9d74a8e97c8.png">
In the message:
<img width="635" alt="g2" src="https://user-images.githubusercontent.com/4590317/41187913-3106b850-6be7-11e8-92db-33ebbd034ed8.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
