### ISSUE TITLE
Chrome –Profile –In Linked Account ->Long Website URL is not displayed completely.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#995]
Summary:
Chrome –Profile –In Linked Account ->Long Website URL is not displayed completely.
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	Go to ADD A Web Link Text Field and Enter http://www.topgear.topcoder.com/setting/Account/reference/youdare/
3.	Click ADD button
4.	Link will be added to the Linked Account
5.	Go to Linked Account section view the URL
### Expected Result ###
Chrome –Profile –In Linked Account ->Long Website URL should be displayed completely.
### Actual  Result ##
Chrome –Profile –In Linked Account ->Long Website URL is not displayed completely.
### Screenshots ###

See in comment section

**Comment by youdare** [comment]
![image](https://user-images.githubusercontent.com/31862600/41187925-65fb0f4e-6bd2-11e8-9d03-a49d1dc0f104.png)

**Comment by youdare** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
Fixed
