### ISSUE TITLE
button style and behavior are different in the confirmation modal

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#996]
### Reported URL ###

https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. enter a web link: http://www.google.com, click ADD

4. wait for a while, click the trash icon of this link

5. observe the buttons

### Expected Result ###
Buttons should have same behavior, e.g. by default, the left button should have same color and style with the right button. And they should behave the same while hovering.

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment]
<img width="663" alt="button" src="https://user-images.githubusercontent.com/4590317/41187932-8d865e8c-6be7-11e8-8f6c-60fa919a4459.png">

**Comment by winterflame** [comment]
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment]
Closing this as it's no longer a valid issue. That part of the platform will be replaced by the updated page.
