### ISSUE TITLE
vertical height needs to be increased

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#997]
### Reported URL ###

https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. observe the PayPal and Western Union sections

### Expected Result ###
vertical height between "Register with PayPal" and "Western Union" should be increased.

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Safari Version 11.1 (13605.1.33.1.4)*

**Comment by ThomasKranitsas** [comment]
That's part of the legacy page and not the community app
