### ISSUE TITLE
error message should be in a different color

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#998]
### Reported URL ###

https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. enter the payment accrual amount as 25.88, click Save

### Expected Result ###
error message should be in a different color

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Safari Version 11.1 (13605.1.33.1.4)*

**Comment by winterflame** [comment]
<img width="766" alt="msg" src="https://user-images.githubusercontent.com/4590317/41187994-219a5cc6-6be9-11e8-9343-46a8bd730b60.png">

**Comment by ThomasKranitsas** [comment]
That's part of the legacy page and not the community app
