### ISSUE TITLE
error message is incorrect when input a big number for payment accrual amount

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#999]
### Reported URL ###

https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

### Reproduction Steps ###

1. login as pshah_manager

2. open https://community.topcoder-dev.com/tc?module=EditPaymentPreferences

3. enter the payment accrual amount as 9999999999, click Save

### Expected Result ###
error message should be adjusted, e.g. you cannot enter number larger than 100000.

### Actual Result ###

See screenshot, it complains 9999999999 is not a positive number

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Safari Version 11.1 (13605.1.33.1.4)*

**Comment by winterflame** [comment]
<img width="782" alt="nine" src="https://user-images.githubusercontent.com/4590317/41188046-40d89dc2-6bea-11e8-923e-0dfc8ba5340b.png">

**Comment by winterflame** [comment]
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment]
That's part of the legacy page and not the community app
